### ISSUE TITLE
Is there any interest in releasing 1.3 now and moving unresolved tickets to 1.4?

### ISSUE THREAD

**Issue by toddw** [fyne-io/fyne#1004]
Fyne has been a life saver for me and I appreciate all of the hard work everyone has put into it. The file dialog could be a really big game changer for this project and I see that looks like it is already done in the 1.3 milestone list: https://github.com/fyne-io/fyne/milestone/7

I know I can use it now before the official 1.3 release but I figured I might suggest releasing 1.3 and moving the open tickets to a 1.4 release? If there are good reasons not to do so I would love to hear what they are.

Anyways, just a thought, looking forward to hearing what everyone thinks.

**Comment by toddw** [comment]
Nvm! I just went through the list and it appears that most of the open tickets are bugs. Those obviously should be fixed before releasing 1.3

**Comment by andydotxyz** [comment]
You’re quite right. We are aiming to release this at the beginning of June so not too long to wait.
