### ISSUE TITLE
No OS border(frameless) form request.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [fyne-io/fyne#1007]
### Is it possible to construct a solution with the existing API?
I can't find any api to do this.

### Describe the solution you'd like to see:
Add `SetNoBorder(bool)` or `SetFrameless(bool)` method to hide os form border.

**Comment by MiyamuraMiyako** [comment]
I found issue 204 to solve this question.

**Comment by andydotxyz** [comment]
You might also find the new splash window type on develop branch to be useful.
