### ISSUE TITLE
Images are intermittently disappear from custom widget.

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1009]
Here is my code:

```golang
package setup

import (
	"image/color"
	"log"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/widget"
)

func headerSize() fyne.Size {
	return fyne.Size{windowWidth, headerItemHeight}
}

type headerRenderer struct {
	items []fyne.CanvasObject
}

func newHeaderRenderer(header *header) *headerRenderer {
	var items []fyne.CanvasObject

	for i := range header.activeItems {
		var item fyne.CanvasObject
		if i == header.activeIndex {
			item = header.activeItems[i]
		} else {
			item = header.inactiveItems[i]
		}
		items = append(items, item)
	}

	return &headerRenderer{items}
}

func (hr *headerRenderer) MinSize() fyne.Size {
	return headerSize()
}

func (hr *headerRenderer) Layout(fyne.Size) {
	log.Printf("Layout %v", hr.items)
	for i, item := range hr.items {
		item.Resize(fyne.Size{headerItemWidth, headerItemHeight})
		item.Move(fyne.NewPos(i*headerItemWidth, 0))
	}
}

func (hr *headerRenderer) BackgroundColor() color.Color {
	return color.Transparent
}

func (hr *headerRenderer) Objects() []fyne.CanvasObject {
	log.Printf("Objects")
	return hr.items
}

func (hr *headerRenderer) Refresh() {
	for _, item := range hr.items {
		item.Refresh()
	}
}

func (hr *headerRenderer) Destroy() {
}

type header struct {
	widget.BaseWidget
	activeItems   []*canvas.Image
	inactiveItems []*canvas.Image
	activeIndex   int
}

func newHeader(pages []*page) *header {
	var active []*canvas.Image
	var inactive []*canvas.Image

	for _, page := range pages {
		active = append(active,
			createImage(page.activeHeaderImage))
		inactive = append(inactive,
			createImage(page.inactiveHeaderImage))
	}

	return &header{
		activeItems:   active,
		inactiveItems: inactive,
	}
}

func (h *header) CreateRenderer() fyne.WidgetRenderer {
	return newHeaderRenderer(h)
}

/*
func (h *header) Size() fyne.Size {
	return headerSize()
}

func (h *header) MinSize() fyne.Size {
	return headerSize()
}
*/

func (h *header) NextPage() bool {
	if h.activeIndex == len(h.activeItems)-1 {
		return false
	}

	h.activeIndex++
	h.Refresh()

	return true
}
```
Sometimes it's being rendered well, sometimes no images appear (about 50% of the cases). Is there a nuance I miss? Anyway it looks like a problem with the library that allows to shoot in a foot so easily.

**Comment by andydotxyz** [comment]
Unfortunately we can't run that code to see what is happening. I don't see anything obvious.
I would recommend that you don't set your minSize to the width of a window though, if that is the case the user will be able to expand the window but never shrink it back.
MinSize is designed to show how small it can possibly go - not it's preferred size (BaseWidget will handle the current size etc).

Overall the code seems strange. CreateRenderer is only going to be called once (when the widget appears) at which point it will read activeIndex and set up the image list. After that it does not read that information again.

It's not entirely clear from your description whether images don't appear initially or after some action causing the NextPage() call?

**Comment by ababo** [comment]
> I would recommend that you don't set your minSize to the width of a window though, if that is the case the user will be able to expand the window but never shrink it back.

This is a fixed-size control on a fixed-size window.

> CreateRenderer is only going to be called once (when the widget appears) at which point it will read activeIndex and set up the image list.

Oh, didn't know that, thanks for clarification.

> It's not entirely clear from your description whether images don't appear initially or after some action causing the NextPage() call?

I meant one time you launch the app and can see the images, next time launching the app they can disappear.

**Comment by mrjrieke** [comment]
I witnessed this on another platform in Android as well.  There I think it is down to multiple threads attempting to acces a file (img) that has been open with exclusive access.  So the other display threads are being blocked intermittently.  That may not be the case here, but thought I'd throw this out there.

**Comment by andydotxyz** [comment]
In absense of the code can you perhaps share a screenshot of a correct run and an failing run? thanks

**Comment by andydotxyz** [comment]
The request for more information (runnable code or screenshots) is 6 months old. 
If this is still an issue please respond with the information so we can progress.

**Comment by ababo** [comment]
I have found a workaround, so this is not an issue anymore, closing.
