### ISSUE TITLE
OpenURL leaks zombie child processes & no I/O from child processes

### ISSUE THREAD

**Issue by jadr2ddude** [fyne-io/fyne#102]
The use of `(*exec.Command).Start` without a corresponding wait causes processes to be started but not waited on. Processes are not removed from the process table until they are waited on. Therefore, the processes spawned become zombie children.

Additionally, the command is created without stdin/stdout/stderr bound. Setting these correctly would allow the user to see any errors/debug output from the process when the application is launched from the command line.

Source of error:
https://github.com/fyne-io/fyne/blob/3fef689c81995e2ef72d06c6e606b696894674e3/app/app_bsd.go#L10
https://github.com/fyne-io/fyne/blob/3fef689c81995e2ef72d06c6e606b696894674e3/app/app_darwin.go#L8
https://github.com/fyne-io/fyne/blob/3fef689c81995e2ef72d06c6e606b696894674e3/app/app_linux.go#L8

I am unsure whether this also applies to Windows systems.

I would also like to remove some of the duplication.

**Comment by jadr2ddude** [comment]
Additionally, I just realized that we do not process errors from this

**Comment by jadr2ddude** [comment]
There are additional edge cases to worry about, since we are passing this as a CLI argument. If the user passes flags (like `--version`), this could cause strange behavior.

**Comment by andydotxyz** [comment]
Perhaps we could try to parse the argument to a URL?
Or should it really be a url.URL anyway?
A breaking change for this should be OK - we'll nail it down for the 1.0 release.

**Comment by andydotxyz** [comment]
My understanding of Command.Run() is that it does not suffer the resource leak of Command.Start() as it is waiting (according to the docs).

**Comment by jadr2ddude** [comment]
Sorry I misread that lol sorry

**Comment by andydotxyz** [comment]
You may still have a point about the I/O and the URL parsing though...
