### ISSUE TITLE
Use Alipay or WeChat sponsorship

### ISSUE THREAD

**Issue by hechty** [fyne-io/fyne#1027]
I really like this project. I want to sponsor it. But I do n’t have a US credit card. Can the government support China ’s Alipay or WeChat sponsorship channels?

**Comment by andydotxyz** [comment]
That is very kind of you indeed, thanks for thinking of sponsoring us!
Unfortunately GitHub sponsors does not currently support Chinese payments - the countries available are: https://github.com/sponsors#countries.

We do still have a legacy page where you can make donations - this page supports more contries including China. https://fossfi.sh/support-fyneio

**Comment by andydotxyz** [comment]
Closing as the two links above provide options that should be suitable.
Please re-open if this is not working for you.
