### ISSUE TITLE
[question] Move circle on mouse drag

### ISSUE THREAD

**Issue by talentlessguy** [fyne-io/fyne#1030]
I am writing an audio player, and I want a circle to be draggable, to change audio track position.

Is there any way to attach a mousedrag handler to a canvas element, so it will be draggable?

this I what I want to achieve:

![image](https://user-images.githubusercontent.com/35937217/82741467-cc64d880-9d5a-11ea-9a7c-1d006329caa8.png)

this is what I have atm:

![image](https://user-images.githubusercontent.com/35937217/82741470-d686d700-9d5a-11ea-81ec-c0ef50a8b415.png)

```go
func dragCircle(pos int) *canvas.Circle {
	circle := canvas.NewCircle(theme.PrimaryColor())

	circle.Resize(fyne.NewSize(20, 20))

	circle.MinSize().Add(fyne.NewSize(20, 20))

	circle.Move(fyne.NewPos(pos-5, -5))

	return circle
}
```

If possible, I would like to attach an event on a circle and handle it.

Or like `<input type="range" />` in HTML, get or set the value.

**Comment by andydotxyz** [comment]
Why not use the slider widget? that is what it's for...

If you want to do it manually you can build a widget that listens to the `Dragged()` event, but you cannot do that on a plan canvas object, as only widgets are able to accept interaction events.

**Comment by talentlessguy** [comment]
@andydotxyz thanks for help once again!

I'll try both methods and will write here which one is better :)

**Comment by talentlessguy** [comment]
@andydotxyz oopsie, yeah, slider works well

closing now
