### ISSUE TITLE
fyne-temp-watch.txt is not deleted

### ISSUE THREAD

**Issue by jkvatne** [fyne-io/fyne#1036]
### Describe the bug:
The file fyne-temp-watch.txt is not deleted on Windows, which is a bit irritating because it appears in git add as a new file (with 0 bytes). This is an issue in TestFileWatcher_FileDeleted and TestWatchFile - both in app/settings_desktop_test.go

### To Reproduce:
Run `go test ./app`

### Solution:
On windows you can not close an open file. So os.Remove(path) will fail unless the file is explicitly closed. Use:
```
  f1, _ := os.Create(path)
  f1.Close()
  os.Remove(path)
```

### Device (please complete the following information):
 - OS: The stupid Windows 10

**Comment by andydotxyz** [comment]
This should be resolved on develop.
There seems to be a new occasional issue where the watcher closes early that I am looking into
