### ISSUE TITLE
generated textfields not respecting indexing

### ISSUE THREAD

**Issue by rjboer** [fyne-io/fyne#1042]
The following piece of code does not respect indexing, or, more likely, somehow I did something wrong....

serverdescription.OnChanged= func(s string) {
			(*servers)[x].Description = s
			//fmt.Printf("%s",*servers)
		}

In the following piece of code I generate a couple of text fields
![image](https://user-images.githubusercontent.com/14197553/83072986-f75b6f00-a06f-11ea-921f-ccb984ef5f35.png)

looking like this:
![image](https://user-images.githubusercontent.com/14197553/83073109-2b369480-a070-11ea-82fa-e777fa81662c.png)

Now if I write test in the description like this (please remark that it is entered on position 3):

![image](https://user-images.githubusercontent.com/14197553/83073231-5e792380-a070-11ea-9fe5-157a46e19483.png)

upon refresh it appears on index 9
![image](https://user-images.githubusercontent.com/14197553/83073283-781a6b00-a070-11ea-9c00-20dfbd3b5aa7.png)
instead of the predicted index 3

Windows 10, latest fyne version

**Comment by andydotxyz** [comment]
This is due to how Go captures variables - the for loop x and y iterate completely so that your button handler OnChanged function always gets the last. value for x.

Inside the for loop add something like 
```go
index := x
```
and then inside OnChanged use `(*servers)[index]`

**Comment by rjboer** [comment]
Not something i would have been able to think out myself!
Works like a charm though, Thank you :P
