### ISSUE TITLE
mobile: content doesn't fit into screen

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#1056]
### Screenshots:
![picture](https://i.imgur.com/zuiI9cl.png)

### Device:
 - OS: Android
 > Pixel 3 API 27__8.1 emulator
hw.lcd.height: 1920
hw.lcd.width: 1080
hw.lcd.density: 420
5.0"
 - Go version: 1.14.2
 - Fyne version: develop, 85790ee40c7570efa530fa8bcd0d2a35bd0860b6

**Comment by andydotxyz** [comment]
Apologies for that regression, fix is now on develop
