### ISSUE TITLE
The password entry doesn't always receive key events when password is visible

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1066]
I wrote the following `widget.Entry` extension:
```golang
package fynex

import (
	"fyne.io/fyne"
	"fyne.io/fyne/widget"
)

// ManagedEntry is an extension of widget.Entry that allows to handle various
// events.
type ManagedEntry struct {
	widget.Entry
	OnTypedKey func(key *fyne.KeyEvent)
}

// NewManagedEntry creates a new managed entry.
func NewManagedEntry() *ManagedEntry {
	entry := &ManagedEntry{}
	entry.ExtendBaseWidget(entry)
	return entry
}

// NewManagedPasswordEntry creates a new managed password entry.
func NewManagedPasswordEntry() *ManagedEntry {
	entry := NewManagedEntry()
	entry.Password = true
	return entry
}

// TypedKey receives key input events when the Entry widget is focused.
func (me *ManagedEntry) TypedKey(key *fyne.KeyEvent) {
	me.Entry.TypedKey(key)
	if me.OnTypedKey != nil {
		me.OnTypedKey(key)
	}
}
```
Now I want a submit button inside my form to become enabled when both username and password entries are not empty and disabled otherwise:

```golang
username := fynex.NewManagedEntry()
password := fynex.NewManagedPasswordEntry()

handleTypedKey := func(key *fyne.KeyEvent) {
	if username.Text != "" && password.Text != "" {
		submit.Enable()
	} else {
		submit.Disable()
	}
}

username.OnTypedKey = handleTypedKey
password.OnTypedKey = handleTypedKey
```

This works as expected until I make the password visible. After that the behaviour turns to be unpredictable (sometimes it stops responding on text input).

Reproduced on OSX Catalina using Golang 1.14.1.

**Comment by andydotxyz** [comment]
I will look into this.
However I would have thought that setting OnChanged would have been easier, as that does not require extending the widget to get the same result.

**Comment by andydotxyz** [comment]
Could the issue here be that you are using TypedKey instead of TypedRune? You need to override both - one for printable and one for others.
Also you should call the handler you have overridden before checking the text content of the keys will not be processed.

**Comment by ababo** [comment]
Oh, thank you for suggesting `OnChanged`, that is the exactly what I need.

**Comment by andydotxyz** [comment]
I looked at this more and the behaviour is consistent.
You would need to hook into `TypedRune` as well as `TypedKey` - once you do that it works as expected.
