### ISSUE TITLE
UI Scaling Issue When Switching Monitors

### ISSUE THREAD

**Issue by jadr2ddude** [fyne-io/fyne#107]
System setup:
* Manjaro Linux (Arch fork)
* AMD RX 470
* X11
* Dual monitor - 4K monitor on left, 1080p TV on right

When I drag the fyne_demo from the monitor to the TV, the fyne demo scales up.
When I drag the fyne_demo back, the layout is messed up

Before (started on monitor):
![image](https://user-images.githubusercontent.com/16477604/52235478-36215080-2892-11e9-864c-eceb1d71f5bb.png)

Halfway between monitors:
![image](https://user-images.githubusercontent.com/16477604/52235514-5224f200-2892-11e9-8c8c-0dcf738fbd64.png)

After (now about 90% of screen height, slack in background for reference):
![image](https://user-images.githubusercontent.com/16477604/52235590-8c8e8f00-2892-11e9-9bc5-4f9f6ca5a704.png)

Moved back to main monitor (now window taller than screen):
![image](https://user-images.githubusercontent.com/16477604/52235630-b2b42f00-2892-11e9-8591-550db80e3e45.png)

**Comment by jadr2ddude** [comment]
With FYNE_SCALE=1, this works fine

**Comment by andydotxyz** [comment]
Auto-scaling to fit appropriately to monitor pixel density is intended.
I wonder if the TV that is connected may not have all the information it needs to calculate correctly...
Possibly related: https://unix.stackexchange.com/questions/75344/how-does-x-server-calculate-dpi

**Comment by andydotxyz** [comment]
Is there a sensible output for the following command?

```xdpyinfo | grep dimension```

**Comment by jadr2ddude** [comment]
```
dimensions:    3840x1080 pixels (1016x285 millimeters)
```
reports size of my monitor

**Comment by Torbilicious** [comment]
I can reproduce this issue on my windows machine.

A few maybe interesting infos:
 - For every switching between monitors the layout gets more messed up
 - I have a (likely related) test failure on my machine:

```
=== RUN   TestWindow_PixelSize
--- FAIL: TestWindow_PixelSize (0.21s)
    window_test.go:36: 
        	Error Trace:	window_test.go:36
        	Error:      	Not equal: 
        	            	expected: 135
        	            	actual  : 176
        	Test:       	TestWindow_PixelSize


Expected :135
Actual   :176
```

My setup: 
left screen: 1280*1024 - 100% Scaling
right screen: 3840*2160 - 150% Scaling

I am happy to give additional info if necessary.

**Comment by andydotxyz** [comment]
Do you see the same problem when running with the EFL driver? (go run -tags efl .)

**Comment by andydotxyz** [comment]
I think this is related to window managers not accepting a resize down. Though it may be the GLFW driver perhaps?
It works as expected on macOS. I will have to check Windows and Linux to get a better idea of where the issue may be.
