### ISSUE TITLE
Rectangle borders are not drawn

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1072]
No matter what `StrokeColor` or `StrokeWidth` is set I cannot see the rectangle's border.

Tested on `develop` (OSX Catalina, Golang 1.14.1).

**Comment by andydotxyz** [comment]
This was fixed in the last few days on `develop` branch for the 1.3 release.
Can you please ensure you are up to date and share what git SHA your develop is set to?

**Comment by ababo** [comment]
Yep, I confirm, that has been fixed.
