### ISSUE TITLE
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize

### ISSUE THREAD

**Issue by newtorn** [fyne-io/fyne#1077]
### Describe the bug:

➜  fyne git:(master) fyne_demo
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
[1]    81470 abort      fyne_demo

### To Reproduce:
Steps to reproduce the behaviour:
1. go get fyne.io/fyne/cmd/fyne_demo/
2. fyne_demo

### Screenshots:

![image](https://user-images.githubusercontent.com/43400069/83686356-a8d44480-a61c-11ea-985c-4b2a66923912.png)

### Device (please complete the following information):
 - OS: MacOS Catalina
 - Version: 10.15.2
 - Go version: go1.12.5 
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment]
It seems that this was a known issue with Go - can you please upgrade to at least 1.12.7 and try again?
golang/go#34935

**Comment by newtorn** [comment]
@andydotxyz okay, thank you! I know that building option should point `-ldflags "-w"`，it means that I should rebuild fyne_demo.

**Comment by andydotxyz** [comment]
You should not need to worry about ldflags. Upgrading go and rebuilding fyne_demo should fix the issue

**Comment by andydotxyz** [comment]
Please let us know if updating helped. No hurry but it's good to know if we have a Fyne issue here or not.
