### ISSUE TITLE
LC_VERSION_MIN_MACOSX is missing when using Fyne on OSX

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1083]
I have an OSX compatibility issue on OSX Catalina when using this library. Just importing the Fyne packages magically makes the binary incompatible with the previous OSX versions.

**Comment by andydotxyz** [comment]
Can you please confirm the command you are using to build and the error you get on older versions?

**Comment by ababo** [comment]
Using the following helped:
```
export CGO_CFLAGS=-mmacosx-version-min=10.12
export CGO_CPPFLAGS=-mmacosx-version-min=10.12
export CGO_LDFLAGS=-mmacosx-version-min=10.12
```
Curious why passing via command line `CGO_CFLAGS=-mmacosx-version-min=10.12 go build ...` doesn't help.

Looks like a false alarm, sorry for bothering. I close the issue.
