### ISSUE TITLE
how to work on vnc-viewer?

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#1087]

**Comment by DiskGetor** [comment]
![Screenshot_2020-06-09-09-39-07-195_com aidlux](https://user-images.githubusercontent.com/19886504/84096720-3b336a00-a9c8-11ea-9890-ee4d60c7373f.png)

**Comment by andydotxyz** [comment]
Did you follow the "getting started" docs from: https://fyne.io/develop/?
You are missing some development headers for your Linux operating system, but you don't say what system you are using. From the error message I am guessing Ubuntu and the package `xorg-dev` is missing.

**Comment by DiskGetor** [comment]
> 您是否遵循[https://fyne.io/develop/中](https://fyne.io/develop/)的“入门”文档？
> 您缺少Linux操作系统的一些开发标头，但没有说明正在使用的系统。从错误消息中，我猜想Ubuntu和软件包`xorg-dev`丢失了。

sorry my bad english,i was installed this linux on android arm64.

http://www.aidlearning.net

**Comment by andydotxyz** [comment]
Can you please share your compile command? Also please share what system you are using - I have not seen LFCE on Android before. Is the linux inside qemu or similar?
If this is a Linux runtime inside Android then my previous comment about headers is relevant - make sure that xorg-dev or equivalent headers are installed for building.

**Comment by DiskGetor** [comment]
> 您能否分享您的编译命令？另外，请分享您使用的系统-之前我还没有在Android上看到LFCE。linux是否在qemu或类似内部？
> 如果这是Android内部的Linux运行时，那么我之前对标头的评论是有意义的-确保已安装xorg-dev或等效标头以进行构建。

i installed goland on lfce, and build fyne demo with goland. i will try apt-get install xorg-dev,thank you.

> 您能否分享您的编译命令？另外，请分享您使用的系统-之前我还没有在Android上看到LFCE。linux是否在qemu或类似内部？
> 如果这是Android内部的Linux运行时，那么我之前对标头的评论是有意义的-确保已安装xorg-dev或等效标头以进行构建。

**Comment by andydotxyz** [comment]
I hope that helps. I still don’t really understand what Linux/OperatingSystem this is - GNURoot perhaps? With Debian on top?

**Comment by DiskGetor** [comment]
> 希望对您有所帮助。我还是不太明白这是什么Linux / OperatingSystem-也许是GNURoot？在Debian之上？

this linux is based  debian,like termux.

**Comment by andydotxyz** [comment]
I am assuming that installing X11 headers fixed the issue as @DiskGetor has filed additional issues indicating that it is working.
Please re-open if this is still a problem
