### ISSUE TITLE
Customize/extend fyne.syso

### ISSUE THREAD

**Issue by nmapx** [fyne-io/fyne#1089]
Hi guys,
First of all - great job with developing the Fyne! I'm currently working on a simple Windows app and looking for a way to customize manifest (`requestedPrivileges`) - to be more precise I would like to set the following:
```
<requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
```
The only clue I have right now is that fyne creates it's own fyne.syso file which doesn't contain that. Is there a way to extend/change it? I've tried with `rsrc` and it works ok but it seems to be ignored when I build everything together using `fyne package ...`

**Comment by andydotxyz** [comment]
Thanks, glad you like the project.
Customising the packages does need work, but what you want should be possible.
The package phase on Windows builds the app if required, creates the .syso and then builds again.
This means that if you edit the .syso file again then use `fyne package again it should work.
If not then perhaps try `go build` after the metadata is created, as that won't try to overwrite the metadata.

**Comment by nmapx** [comment]
Unfortunately manual change of fyne.syso file doesn't work
```
CC=x86_64-w64-mingw32-gcc \
  	CXX=x86_64-w64-mingw32-g++ \
  	GOOS=windows \
  	GOARCH=amd64 \
  	CGO_ENABLED=1 \
  	fyne package -os windows -icon resources/icon.png -release
/tmp/go-build559612002/b001/_pkg_.a(fyne.syso): not an object file
```
I will try with manual build `go build`, let's see...

**Comment by nmapx** [comment]
Alright, so `go build ...` works as expected!
Below you can find a full command how to achieve similar results comparing to `fyne package ...`.
First install `rsrc` - https://github.com/akavel/rsrc and generate `*.syso` file based on your `manifest.xml`.
Next build the app using eg.
```
CC=x86_64-w64-mingw32-gcc \
CXX=x86_64-w64-mingw32-g++ \
GOOS=windows \
GOARCH=amd64 \
CGO_ENABLED=1 \
go build -a -ldflags="-H windowsgui" -o app.exe
```
At least it worked for me :smiley:
Thanks!
