### ISSUE TITLE
Text Colouring

### ISSUE THREAD

**Issue by MJacred** [fyne-io/fyne#1091]
### Is your feature request related to a problem? Please describe:
In case an entered value is incorrect, it would be nice to change the colour of the text in `Label` and `Entry`.
See https://material.io/components/text-fields#anatomy -> `Error text` for an example for `Entry`.

### Is it possible to construct a solution with the existing API?
From what I can see, there are 2 ways to change the colour right now
* the user can define one colour for all texts in `theme.go`, therefore the desired outcome not possible at this time
* or `TextGridStyle`, but then you have to use `TextGrid` (which is for "text editor, code preview or terminal emulator."). This could work for a `Label` replacement (did not test yet), but won't for `Entry`.

### Describe the solution you'd like to see:
This overlaps a bit with #21, but it would be nice to have at least an interim solution, which affects the whole text!  
I believe it would fit nicely into `type TextStyle struct` (or separately, if so desired). If defined, this value can be returned by `Label.textColor()`.

For it to work for `Entry`, the user should be able to define a `TextStyle` as well.

**Comment by Atomotron** [comment]
I have recently had the same requirement.

My interim solution was to create a custom widget that rendered a transparent red rectangle, which was then put over the entry widget and hooked up to the appropriate dynamic controls. While a bit rube-goldbergy, I thought that that solution was better than having to re-implement the renderer for Entry in my own code, and far better than forking Fyne to make one small change.

The need for a "real solution" for validation has been accepted by the project maintainer. We are discussing it here:
https://github.com/fyne-io/fyne/issues/916

**Comment by MJacred** [comment]
Indeed, thank you. I missed that one. And you kindly included other widgets like `Label`!

**Comment by andydotxyz** [comment]
There is a more semantic approach to your request being tracked at #916
