### ISSUE TITLE
Supporting macOS post-OpenGL

### ISSUE THREAD

**Issue by MJacred** [fyne-io/fyne#1095]
### Is your feature request related to a problem? Please describe:
OpenGL is deprecated on macOS so apps using fyne might stop working anytime soon. Might be deprecated in the future for others as well (everybody goes to Vulkan).

### Is it possible to construct a solution with the existing API?
desired outcome not possible at this time

### Describe the solution you'd like to see:
Support Metal (Apple) or use Vulkan part of GLFW (then build macOS apps using MoltenVK).

**Comment by andydotxyz** [comment]
The version released last week (v1.3) stopped using deprecated APIs on macOS.

I’m not sure from this ticket what additional devices would be supported by the list of potential drivers suggested.

**Comment by andydotxyz** [comment]
Ah, I seee what you meant.
I suppose as a summary of what we see in this thread I would say that it's likely "no additional action will be taken at this time".
As the warnings are gone it's not clear if we are using a deprecated code path any more or not.
More investigation would be useful - but adding another driver at this time seems like it would divert effort from other tasks that will bear fruit sooner.

**Comment by andydotxyz** [comment]
Closing as I think we took care of this in the GLFW 3.3 tracking issue #183.
This ticket can be re-opened if it turns out we have more work to do.
