### ISSUE TITLE
Problem with text entry in Entry widget (cursor stays put - Backspace or Delete causes panic)

### ISSUE THREAD

**Issue by RoyTeymant** [fyne-io/fyne#1096]
### Describe the bug:

I raised a question about this on the slack channel on 2020-06-10. After I tab to an Entry field that has been refreshed with i2.Text = "" and i2.Refresh() and start typing the cursor stays at the beginning of the input field. If, after typing a few characters (with the cursor still at the beginning of the input field), I press Backspace or Delete the program panics.

The problem behaviour can be seen in the attached screen grab (first pass is OK, second isn't).
 
At Andrew's suggestion I tried i2.SetText("") instead of i2.Text = "" and that works OK, or has so far.

[2020-06-10 20-25-33.zip](https://github.com/fyne-io/fyne/files/4758215/2020-06-10.20-25-33.zip)

### Device (please complete the following information):

 - OS: Windows 8.1
 - Version: 
 - Go version: go1.14.2 windows/amd64
 - Fyne version: 1.3

**Comment by RoyTeymant** [comment]
Yes the error looks the same:

`panic: runtime error: slice bounds out of range [:11] with capacity 8

goroutine 19 [running]:
fyne.io/fyne/widget.(*textProvider).deleteFromTo(0xc000261b90, 0xa, 0xb, 0xa, 0xc00018ff58, 0x4072ce)
	C:/Users/Roy/Go/src/fyne.io/fyne/widget/text.go:165 +0x241
fyne.io/fyne/widget.(*Entry).TypedKey(0xeaf480, 0xc0022e69e0)
	C:/Users/Roy/Go/src/fyne.io/fyne/widget/entry.go:452 +0x9dc
fyne.io/fyne/internal/driver/glfw.(*window).keyPressed.func7()
	C:/Users/Roy/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:955 +0x3f
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc0000a8000)
	C:/Users/Roy/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1071 +0x81
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
	C:/Users/Roy/Go/src/fyne.io/fyne/internal/driver/glfw/window.go:1095 +0x10a
`

**Comment by andydotxyz** [comment]
On develop for testing :)
