### ISSUE TITLE
Console window

### ISSUE THREAD

**Issue by stej** [fyne-io/fyne#110]
Hi, just a question. Is it possible to get rid of the console window on Windows? I'd like to give it a try and make an app for my colleagues, but this is something that will turn them off...

**Comment by andydotxyz** [comment]
You need to add the following parameter to go build so that the console window does not appear.

-ldflags -H=windowsgui

This needs to go in the documentation somewhere, which page (if any) were you following and I’ll add it there at least.

**Comment by stej** [comment]
It works! 

I just came accross the main README. Installed and took the sample code. 

Maybe the right place would be here:


> And you can run that simply as:
> `go run main.go`

**Comment by andydotxyz** [comment]
Thanks, resolved in README with commit fd1dbcf.

**Comment by pcgeek86** [comment]
Confirmed, this works on Windows 11 to bypass the command window that appears.

**Comment by andydotxyz** [comment]
Years ago we added "fyne package" so this is the default behaviour for packaged apps

**Comment by Jacalz** [comment]
It also is if you are building using the `fyne build` command that is similar to how `go build` works but with some good defaults for fyne applications
