### ISSUE TITLE
ShowModalPopUp doesn't provide a way to hide the popup

### ISSUE THREAD

**Issue by Michael-F-Ellis** [fyne-io/fyne#1102]
### Describe the bug:
Just started testing v1.3.  `NewModalPopUp` is deprecated and `ShowModalPopup` doesn't return a `*PopUp`.  ModalPopups, by intent, prevent user interaction with the app.  I can't find anything in popup.go that provides a means to hide or destroy it.

Am I missing something? 

### To Reproduce:
N/A

### Example code:
N/A

### Device (please complete the following information):
 - OS: any
 - Version: any
 - Go version: any
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
Apologies, the deprecation is really warning of a future change on behaviour...
NewModalPopUp accidentally shows it, so we deprecated the call in favour of ShowModalPopUp. 
However if you are storing the result and then calling Show() manually you can ignore that deprecation. In 2.0 the API will remain but it will no longer show until Show() is called.

**Comment by andydotxyz** [comment]
Closing this as it's not an issue - just confusing deprecated warnings that will go away with 2.0 release
