### ISSUE TITLE
Offer the ability to omit the Quit button in the main menu.

### ISSUE THREAD

**Issue by taliesinmillhouse** [fyne-io/fyne#1104]
### Is your feature request related to a problem? Please describe:
Since it's possible to quit the application by clicking the default OS close button (X on the top right for Windows 10/Ubuntu and top left for Mac). Having the ability to omit the Quit button in the main menu would be great.

### Is it possible to construct a solution with the existing API?
Not as far as I know.

### Describe the solution you'd like to see:
Something along the lines of adding a bool to the fyne.MainMenu struct called "OmitQuitButton" then checking the status of that bool in the buildMenuOverlay method in the glfw package. I'd be more than happy to implement this as a pull request, just checking to see if this is something the maintainers/community want first. Cheers!

**Comment by andydotxyz** [comment]
This is a tricky question. The Quit button has been added to every desktop menu because some operating systems require it (mainly macOS) so it is not possible to remove it from all. For consistency it therefore is added to all.

Removing it does not change the functionality of the app so I’m curious about why you desire this change?

**Comment by taliesinmillhouse** [comment]
Oh that's right, the close button on macOS doesn't quit the application, just closes the window. Forgot about that!

The reason was really trivial, just wanted to remove it because the same functionality was already being replicated with the close button on Windows 10 and Ubuntu.

It sounds like it will be more hassle than it's worth, plus it keeps consistency across all operating systems.

I'll close this issue off. Thanks for the quick reply!
