### ISSUE TITLE
Set SetFixedSize to true, the menus are overlapped.

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#1105]
There is an error like below.

```Go
w.SetFixedSize(true)
```
![image](https://user-images.githubusercontent.com/6222645/84635165-cca55d80-af2d-11ea-9573-dde8658b3ad7.png)

```Go
w.SetFixedSize(false)
```
![image](https://user-images.githubusercontent.com/6222645/84635468-39205c80-af2e-11ea-9734-e3cee84d0a76.png)

### Device (please complete the following information):
 - OS: Windows 10 20H1
 - Go version: latest
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
This also seems to be an issue if you can `Window.Resize()` after `Window.SetMainMenu()`

**Comment by andydotxyz** [comment]
On develop for testing.
