### ISSUE TITLE
Black flickering on resize on MacOS and OS X (possibly not on Catalina)

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1122]
### Describe the bug:
Resizing windows gives a lot of black flickering inside the application. I can't replicate this when using v1.2.4 but with v1.3.0 it is easy to see. It is easier to see it when using the light theme because of the larger contrast ration between the colours.

### To Reproduce:
Steps to reproduce the behaviour:
1. Build a fyne application for the darwin target. (I have replicated on High Sierra and El Capitan)
2. Switch to a light theme for better contrast.
3. Resize the window and notice how it flickers to black.

### Screenshots:

![black-screen-flickering-demo](https://user-images.githubusercontent.com/25466657/85223012-dca2be80-b3bf-11ea-98d5-af5be69265e0.gif)

### Example code:
Check out either `fyne_demo` or https://github.com/Jacalz/sparta. It is with these that I have tested and replicated it.

### Device (please complete the following information):
 - OS: MacOS 10.13 High Sierra and Mac OS X 10.11 El Capitan
 - Version: 10.13 and 10.11
 - Go version: 1.13.11 (have built all applications using fyne-cross v2.0.0)
 - Fyne version: v1.3.0 and current master branch (a82c32879cbaa36888e85389bda9d0dc72e3c5e5)

**Comment by Jacalz** [comment]
Might be more or less related to #1114

**Comment by Jacalz** [comment]
Looks like the flickering gets slightly less noticeable with #1120. However, it is still noticeable.

**Comment by andydotxyz** [comment]
Fix on develop for testing
