### ISSUE TITLE
CJK font display problem

### ISSUE THREAD

**Issue by Deardrops** [fyne-io/fyne#114]
I use a custom font in fyne (e.g. Microsoft Yahei, a Chinese font), and It will cause a display problem.
![image](https://user-images.githubusercontent.com/9463871/52617433-cedd4f00-2ed6-11e9-9e89-547304146801.png)
As shown, chinese characters in `Label` are not diplay completely, some characters are hidden behind.
How to deal with this problem?

**Comment by andydotxyz** [comment]
I have updated the font handling code for measuring glyphs having seen something similar, could you please update and see if the issue is resolved?

**Comment by Deardrops** [comment]
The problem resolved, new code worked prefectly, thank you so much!
![image](https://user-images.githubusercontent.com/9463871/54244741-ec024d80-4568-11e9-9e5c-2b3c9e7ba112.png)
