### ISSUE TITLE
dialog.NewCustomConfirm() does not call the callback for the "ok" and "dismiss" button

### ISSUE THREAD

**Issue by Ragin-LundF** [fyne-io/fyne#1143]
### Describe the bug:
dialog.NewCustomConfirm() does not call the callback of the function after pressing a button.
Background:
dialog.hideWithResponse() method in the base.go file calls only the callback if dialog.sendResponse is true (and if a callback exists). This was not set while creating the new dialog.

### To Reproduce:
Create new NewCustomConfirm dialog with a simple function and print something there to the console -> method will never be called.

### Example code:

```go
dialog.NewCustomConfirm("Callback example",
	"Ok", "Cancel",
	widget.NewLabel("Hello World"),
	func(confirmed bool) {
		fmt.Println("Callback...")
	},
	window)
```

### Device (please complete the following information):
 - OS: all
 - Version: all
 - Go version: all
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
Can you include also how you show the dialog? That might relate to when/how flags are set...

**Comment by andydotxyz** [comment]
Thanks for working through this, it is indeed less confusing now :)
