### ISSUE TITLE
Set picture as background

### ISSUE THREAD

**Issue by Dynamith** [fyne-io/fyne#1147]
Can fyne set the picture as background. If not, can it be added?
This is the effect I made with photoshop:
![uTools_1593345407815](https://user-images.githubusercontent.com/64576195/85947940-4ef73e00-b980-11ea-9def-53cbb8fceeeb.png)

**Comment by andydotxyz** [comment]
You could place an image under another widget or container yes - we do this in FyneTerm: https://github.com/fyne-io/terminal .

You probably want to make a new container with MaxLayout and add the bg then the original container as the content.

**Comment by Dynamith** [comment]
I set the theme.BackgroundColor() to be fully transparent, and then use your method to set the layer background. The effect is not bad and can support most interfaces.
![uTools_1593447979901](https://user-images.githubusercontent.com/64576195/86031834-ff407180-ba68-11ea-90bd-dd505eae76f8.png)

**Comment by andydotxyz** [comment]
Great, glad this is working for you.

**Comment by Dynamith** [comment]
I found another solution: put the translucent background on the top layer. As long as the transparency is selected properly, the effect will be better.
![uTools_1593529272529](https://user-images.githubusercontent.com/64576195/86142286-9b2fb300-bb25-11ea-9c34-397b706fc51a.png)
