### ISSUE TITLE
Add text grid

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#115]
Basic monospaced widget that could be used for a text editor, terminal or code display.

Use the same base text back instance as entry and label.

**Comment by asciifaceman** [comment]
This would be great, I was tinkering around making a rudimentary chat window to play with fyne and found it difficult with the current entry/label/form widgets.

**Comment by andydotxyz** [comment]
Thanks @asciifaceman. The basic idea is a grid format of runes where each can have specific colours.
Do you want to add to that for the first version or shall we start small and iterate?

**Comment by asciifaceman** [comment]
imho thats a great start. Keep the scope small for a first implementation.

Long term I'd imagine it may be useful to be able to:

1. scroll the text editor in user space or programmatically (I guess that means masking or managing lines out of view) This could be scroll back terminal style, perhaps define a maximum scrollback on instantiation and have a method for changing it after instantiation.
2. treat rows of the grid as a single element (say loading strings from a []string/[]byte as lines etc)
3. Readonly the editor (for display only / programatic only purposes)
4. do keypress callbacks
5. have better control of size. I was having problems sizing the existing Entry widgets, I don't know if it was my lack of experience with fyne or them being difficult.
6. have a builtin to append rows (related to but not the same as †2) 
7. during editing, be able to backspace on a 0 width row and have it collapse the line like it would in a text editor

I'll cut my wishlist there before it gets too epic.

Feel free to pick and choose for a first iteration, they are just suggestions from my point of view. I think some of these improvements could be ported back to existing entry/display widgets as well. Feel free to tell me I'm dreaming too big. I ultimately don't know how much you want fyne to do vs. how much the implementing developer would do.

Honestly fyne is the easiest & funnest go GUI I've played with yet, it makes me want to get involved.

**Comment by andydotxyz** [comment]
1: yes
2: interesting, I think this is how we handle text in the backend anyway
3: yes
4: yes
5: let's chat - it should be satisfied by default rather than adding anything new
6: yes
7: yes

And somehow I forgot an obvious one: Line numbers :)

**Comment by Aukstkalnis** [comment]
What is the status of this case? I noticed, that this case are added in release 1.1 milestone, but labelled as 1.2. So I am curious what is happening in a field of text widget :)

**Comment by andydotxyz** [comment]
Apologies for the delay. It is too much work to get this right in 1.1.
In the 1.2 release we will be working on some optimisations that should make it easier and so we will release it then.

There is a feature branch for it but the functionality is still very very basic.

**Comment by andydotxyz** [comment]
Slips from 1.2 as we are focussing more on expanding to mobile.

**Comment by andydotxyz** [comment]
OK this is very close to landing, so updating the ticket for the next release.
In the end I had to move away from the standard text handling as this is a specific use-case and is closer to a [][]rune than it is string... fun times.

**Comment by andydotxyz** [comment]
On develop for testing
