### ISSUE TITLE
Wrong rendering on Windows

### ISSUE THREAD

**Issue by Ragin-LundF** [fyne-io/fyne#1151]
### Describe the bug:
On some Windows, systems Fyne has problems with TabItems and the MainMenu.
In these cases, the MainMenu is not visible and the TabItems and Buttons in Forms are only clickable on a line, which is 3-4 pixel height.

I've added some screenshots of the GPU/CPU and one screenshot of the application on my Windows machine, which is working and a screenshot of another machine on which it is not working. I've already tried out the develop branch, but it doesn't change anything.

### To Reproduce:
The tool was written with code that is similar to the fyne_demo. It should be reproducible on some Windows machines with the demo.

### Screenshots:
CPU
![cpu](https://user-images.githubusercontent.com/21161525/86165381-7fbbac80-bb13-11ea-9939-b2e7fce0efd8.png)

GPU
![gpu](https://user-images.githubusercontent.com/21161525/86165387-80ecd980-bb13-11ea-837a-d399b0dc0598.png)

Wrong rendered app
![problem](https://user-images.githubusercontent.com/21161525/86165392-80ecd980-bb13-11ea-8352-2c53ffc9b103.png)

Correct rendered app
![screenshot_gui_welcome_win](https://user-images.githubusercontent.com/21161525/86165429-8b0ed800-bb13-11ea-9eec-db604372080a.PNG)

### Device (please complete the following information):
 - OS: Windows 10 Enterprise
 - Version: 1909
 - Go version: 1.14.4
 - Fyne version: 1.3.0 and develop

**Comment by andydotxyz** [comment]
(from slack conversation the develop version was 2 days ago).
Please can you confirm if this is still an issue on latest deveop - and confirm the commit hash (as develop is a moving branch rather than a tag).

**Comment by andydotxyz** [comment]
I noticed that there was another corner case as we wrapped up for release.
Please test the release/v1.3.x branch, as I think it will now be fixed.

**Comment by Ragin-LundF** [comment]
I've got a response of the guy today and it is still not working ;(.

**Comment by Ragin-LundF** [comment]
The App which has the problem is:
https://github.com/Ragin-LundF/k8s-jcasc-management-go/tree/v2.0.1

This tag uses the commit 952478cd4a37 of the release/1.3.x branch

Simply check out and execute `go run k8s-jcasc-mgmt.go`

**Comment by andydotxyz** [comment]
Is he using a version of Go that does not have modules enabled by default? Or has he turned them off? I’d so he may not have the same fyne version as your go.mod

**Comment by Ragin-LundF** [comment]
He is using Go 1.4.4.
He also starts the application with IntelliJ with mod support enabled.
But I can ask to execute a `go get -u` to update it.

**Comment by andydotxyz** [comment]
I don't think it can be 1.4.4 - did you mean 1.14.4?
Can you please try using the 1.3.1 release and launching from a terminal?
If it still doesn't work then the result of 'go env' (or 'fyne env') would be really helpful.

**Comment by Ragin-LundF** [comment]
You are right ;). It is 1.14.4.

Here you can see the `go env` output of the problematic computer:

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\kkot\AppData\Local\go-build
set GOENV=C:\Users\kkot\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\kkot\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Users\kkot\sdk\go1.14.4
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\kkot\sdk\go1.14.4\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\kkot\Desktop\projects\CLX-DevOps\k8s-jcasc-management-go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\kkot\AppData\Local\Temp\go-build182719154=/tmp/go-build -gno-record-gcc-switches
```

Today we had a small Hangouts session and we deleted all caches, tried it with the tags "no_native_menus" and "gles" but nothing helped.
I also updated yesterday the code to fyne 1.3.1.

**Comment by Ragin-LundF** [comment]
So, after updating to 1.3.2 and updates of the graphic drivers the issue was gone.
Seems like it was a problem with an older OpenGL driver of the onboard graphic card.
The Intel driver on this system was from 2017.

With this driver it finally worked:
![87303182-03fa3080-c513-11ea-868d-5847119d0ffb](https://user-images.githubusercontent.com/21161525/87338029-bd252e80-c544-11ea-8fb4-6ad98d4e0c6d.png)

Hope this helps with further issues with this problem.

It was also interesting, that Windows did not update the driver itself. Eventually, it is helpful to set OpenGL 4.6 as a prerequisite.
