### ISSUE TITLE
Setting FixedSize smaller than window content gives inconsistent results

### ISSUE THREAD

**Issue by RustamGamidov** [fyne-io/fyne#1154]
### Describe the bug:
Setting both window size and making window to be FixedSize cause next behavior:
- the window has size that was set
- as soon as it's dragged it's resized to fit the content (it's still FixedSize)
see code and screenshot below

### To Reproduce:
1. get `develop` branch with the #1138 applied
2. create simple application with the window and long text inside it
3. resize it so the width is definitely not enough for the text
4. set the window to be fixed size
5. start it
6. drag it

### Screenshots:
![image](https://user-images.githubusercontent.com/5964689/86257507-4db55380-bbc2-11ea-94fd-da4a25c0f3e4.png)

on the image from the top to the bottom:

1. resized and fixed size initially
2. resized and fixed size after i dragged it a bit (same binary)
3. resized and size is not fixed
4. not resized, fixed size

### Example code:
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	app := app.New()
	win := app.NewWindow("window title")
	win.Resize(fyne.NewSize(200, 100))
	win.SetFixedSize(true)

	win.SetContent(widget.NewHBox(
		widget.NewLabel("long text to exceed initial window width"),
	))
	win.ShowAndRun()
}

```

### Device (please complete the following information):
 - OS: windoows
 - Version: 10.0.18363.900
 - Go version: 1.13.8 windows/amd64, 1.14.4 windows/amd64
 - C,CPP compiler: x86_64-w64-mingw32\9.3.0
 - Fyne version: 1.3. develop https://github.com/fyne-io/fyne/commit/102ff9e4a866cf387f153d738d430570f45d0738

**Comment by RustamGamidov** [comment]
reverting #1138 locally is giving width based on the window content

**Comment by RustamGamidov** [comment]
can't reproduce on current develop 75cf46954c3bd0b36983a2f4565f30f54459d763
maybe because of #1162

**Comment by andydotxyz** [comment]
Oh that would be nice. Perhaps you could test today’s 1.3.1 release and maybe we can close this :)

**Comment by RustamGamidov** [comment]
Sure, i'll test. 
The thing is the root cause is still there, there's no decision if auto-sizing should be done for fixed size window. On the other hand there are no complains so auto-sizing is probably what users are happy with.

**Comment by RustamGamidov** [comment]
Checked on 44606fbe and i can confirm the old behavior is back.
Fixed size window resized to fit the content it explicitly set size is not enough.
