### ISSUE TITLE
Unable to overwrite file when using dialog.ShowFileSave

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1168]
### Describe the bug:
I am working on an application that exports some generated data as a .csv file. To do this I am using dialog.ShowFileSave(). If the file doesn't exist it works fine, but if it does URIWriteCloser.Write returns the error "Access denied".
You can work around this by retrieving the file name and then using os.Create, but it would be better to use the official way.

### To Reproduce:
Steps To Reproduce:
1. Write to a file using dialog.ShowFileSave
2. Write to the same file again

### Example code:
```go
package main

import (
	"bytes"
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/dialog"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Overwrite Bug")

	t := widget.NewEntry()

	w.SetContent(
		widget.NewHBox(
			t,
			widget.NewButton("Save", func() {
				dialog.ShowFileSave(func(writer fyne.URIWriteCloser, err error) {
					if writer == nil {
						return
					}
					if err != nil {
						panic(err)
					}
					defer writer.Close()
					buffer := bytes.NewBufferString(t.Text)
					n, err := writer.Write(buffer.Bytes())
					if err != nil {
						// This panic is called
						panic(err)
					}
					fmt.Println("Wrote", n, "bytes")
				}, w)
			}),
		),
	)

	w.ShowAndRun()
}

```

### Device:
 - OS: Windows 10
 - Version: 2004
 - Go version: 1.14.4
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
Well caught, you are quite right that this should work as expected.
Did the dialog prompt you to confirm the overwrite?

**Comment by PucklaMotzer09** [comment]
Yes. It prompted me to confirm the overwrite, but as mentioned above it didn't work.

**Comment by andydotxyz** [comment]
Thanks for the info, I managed to get the fix slipped into the release today :)
