### ISSUE TITLE
Dialogs do not work when overwritting using dialog.ShowFileSave

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1169]
### Describe the bug:
I am using dialog.ShowError and dialog.ShowInformation to tell the user if a file save failed or succeeded. When I am writing to a new file everything works fine, but when I am writing to an existing file. No dialogs pop up.

### To Reproduce:
Steps to reproduce the behaviour:
1. Use dialog.ShowError or dialog.ShowInformation anywhere in the callback of dialog.ShowFileSave
2. Create a new file using the FileSave dialog
3. See that everything displays correctly
4. Save to the same file again.
5. See that nothing pops up.

### Example code:
```go
package main

import (
	"bytes"
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/dialog"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Dialog Bug")

	t := widget.NewEntry()

	w.SetContent(
		widget.NewHBox(
			t,
			widget.NewButton("Save", func() {
				dialog.ShowFileSave(func(writer fyne.URIWriteCloser, err error) {
					if writer == nil {
						return
					}
					if err != nil {
						dialog.ShowError(err, w)
						fmt.Println(err)
						return
					}
					defer writer.Close()
					buffer := bytes.NewBufferString(t.Text)
					n, err := writer.Write(buffer.Bytes())
					if err != nil {
						dialog.ShowError(err, w)
						fmt.Println(err)
						return
					}
					dialog.ShowInformation("Success", fmt.Sprint("Wrote ", n, " bytes"), w)
					fmt.Println("Wrote", n, "bytes")
				}, w)
			}),
		),
	)

	w.ShowAndRun()
}

```

### Device:
 - OS: Windows 10
 - Version: 2004
 - Go version: 1.14.4
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
This was fixed in the 1.3.1 release :)
