### ISSUE TITLE
Calling .SetText() to an extended label didn't update the label until user resizing the window.

### ISSUE THREAD

**Issue by RoganMatrivski** [fyne-io/fyne#1170]
### Describe the bug:
Calling .SetText() to an extended label didn't update the label until user resizing the window. Calling .Refresh() on the extended label didn't update the label either. If one of the widgets in the app updates, the label didn't set the correct text, instead it stretches the label along the x axis until the window resized. For comparison, the built-in label widget updates as usual

### To Reproduce:
Steps to reproduce the behaviour:
1. Save and run the code below
2. Wait for ~3 Seconds
3. See the error

### Screenshots:
![image](https://user-images.githubusercontent.com/19743747/86723743-60aca580-c052-11ea-826c-60ee81481747.png)

### Example code:
```go
package main

import (
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

const (
	extendedLabelTextChangeDelay = time.Second * 1
	standardLabelTextChangeDelay = time.Second * 2
)

type tappableLabel struct {
	widget.Label
	onTapped func(*tappableLabel)
}

func newTappableLabel(str string, tapped func(*tappableLabel)) *tappableLabel {
	label := &tappableLabel{onTapped: tapped}
	label.ExtendBaseWidget(label)
	label.SetText(str)

	return label
}

func (l *tappableLabel) Tapped(_ *fyne.PointEvent) {
	if l.onTapped != nil {
		l.onTapped(l)
	}
}

var (
	appUI      fyne.App
	mainWindow fyne.Window
)

func main() {
	appUI = app.New()

	extendedLabel := newTappableLabel("aaaaaaaaaaaaaaaaaaaaaaaa", func(l *tappableLabel) {
		l.SetText("bbbbbbbbbbbbbbbbbbbbbbbb")
		l.Refresh()
	})

	go func(l *tappableLabel) {
		time.Sleep(extendedLabelTextChangeDelay)
		l.SetText("bbbbbbbbbbbbbbbbbbbbbbbb")
		l.Refresh()
	}(extendedLabel)

	standardLabel := widget.NewLabel("aaaaaaaaaaaaaaaaaaaaaaaa")

	go func(l *widget.Label) {
		time.Sleep(standardLabelTextChangeDelay)
		l.SetText("bbbbbbbbbbbbbbbbbbbbbbbb")
	}(standardLabel)

	container := fyne.NewContainerWithLayout(layout.NewVBoxLayout(), extendedLabel, standardLabel)

	mainWindow = appUI.NewWindow("Main")
	mainWindow.SetContent(container)
	mainWindow.Resize(fyne.NewSize(300, 100))

	mainWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Windows
 - Version: 20H2
 - Go version: 1.14.4
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
This should already be fixed in the v1.3.1 release that comes out today - if possible could you test Fyne from the ‘release/v1.3.x’ branch and verify?

**Comment by RoganMatrivski** [comment]
Seems like using the release/v1.3.x branch solves this problem. Thanks!

**Comment by andydotxyz** [comment]
Great, thanks for checking :)
