### ISSUE TITLE
Entry inside scroll container has incorrect mouse cursor on drag handles

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1172]
### Describe the bug:
Having an entry inside a scroll container leads to the mouse cursor being the text edit style when dragging over the drag handles for the scrolling. This seems incorrect and should possibly be changed to a drag style mouse.

### To Reproduce:
Steps to reproduce the behaviour using example code:
1. Type something into the entry.
2. Drag using the drag handles.

### Screenshots:
![incorrect-drag-handles](https://user-images.githubusercontent.com/25466657/86818669-f2cea100-c086-11ea-95b6-a7acf0a24fdc.gif)

### Example code:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Scroll handles wrong")

	w.SetContent(widget.NewScrollContainer(widget.NewMultiLineEntry()))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Solus (linux distro)
 - Version: Linux Kernel 5.6.18
 - Go version: 1.14.3
 - Fyne version: 1.3.0

**Comment by andydotxyz** [comment]
Available on develop for testing
