### ISSUE TITLE
Splash Window not centered, or centerable in 1.3.1

### ISSUE THREAD

**Issue by Crypta-Eve** [fyne-io/fyne#1174]
### Describe the bug:
When opening a new splash window it is not appearing centered on the monitor. Instead it is appearing in the locations as would happen for normal new windows. ie slightly down and right from the top left corner of the 'parent' app. It opens in a different location each time. This issue is not present in v1.3.0. I am running Debian testing with GNOME and Wayland.

### To Reproduce:
1. Clone the fyne repo as at `ebb8181`
2. cd to `cmd/fyne_demo`
3. `go run main.go`
4. Click the button to run the splash screen

### Screenshots:
[screenshot](https://imgur.com/RvAoIgV)

### Device (please complete the following information):
 - OS: [Linux Debian Testing
 - Version: `sid`
 - Go version: `1.14`
 - Fyne version: `1.3.1`

**Comment by andydotxyz** [comment]
Seems to be intermittent, probably relates to fixed size fixes 1-2 weeks back :(

**Comment by andydotxyz** [comment]
Fixed in v1.3.2

**Comment by gernotstarke** [comment]
May I re-open that issue: On MacOS, using the current 1.4 build, centering a splash screen does not work:

![image](https://user-images.githubusercontent.com/1233990/104339280-b7120980-54f7-11eb-8d10-cb2f64a67d93.png)

The "real" app window CAN be centered (see screenshot above).

Sample code see below.

I tried various combinations of resizing/no-resizing, changed the order of function calls - the result is always the same:
Main window gets centered, splash display lower-right part of screen.

Sidenote: Splash is (usually) displayed AFTER main window - despite time.Sleep
~~~~
func main() {
	a := app.New()

	createAndDisplaySplash()

	w := a.NewWindow("Hello Splash")

	container := fyne.NewContainerWithLayout(
		layout.NewHBoxLayout(),
		widget.NewLabel("some label"))

	w.SetContent(container)
	w.CenterOnScreen()
	w.Resize(fyne.NewSize(600, 200))
	w.ShowAndRun()
}

func createAndDisplaySplash()  {
	if drv, ok := fyne.CurrentApp().Driver().(desktop.Driver); ok {
		splashWindow := drv.CreateSplashWindow()

		splash := canvas.NewImageFromResource(resources.PDFnmbrrSplash)
		splash.Resize(fyne.NewSize(600, 540))
		splash.FillMode = canvas.ImageFillOriginal

		splashWindow.SetContent(splash)
		splashWindow.CenterOnScreen()
		splashWindow.Show()

		go func() {
			time.Sleep(time.Second * 3)
			splashWindow.Close()
		}()
	}
}
~~~~

**Comment by andydotxyz** [comment]
Splash windows are centered, you don't have to call center separately.

The problem you are encountering is the usage of ImageFillOriginal.
The size of the image is not known until loaded so it resizes the already centered window.
Removing that line should fix your problem
