### ISSUE TITLE
Fyne 1.3.1 not centering and screen not fully rendering on startup

### ISSUE THREAD

**Issue by Ariemeth** [fyne-io/fyne#1177]
### Describe the bug:

After updating from v1.3.0 to v1.3.1 my application starts and is not centered and half the window is not rendering.

### To Reproduce:
Steps to reproduce the behaviour:
1. Build with fyne v1.3.1
2. Start the program

### Screenshots:

application startup with fyne v1.3.0
![image](https://user-images.githubusercontent.com/541023/87079184-a81e6780-c1f3-11ea-8ace-41f58ebee7d8.png)

application startup with fyne v1.3.1
![image](https://user-images.githubusercontent.com/541023/87079324-dc922380-c1f3-11ea-850d-d46c77697555.png)

### Example code:
Application can be found here
https://github.com/Ariemeth/gearforce/tree/fyne_1.3.1_udpate

### Device (please complete the following information):
 - OS: Windows 10 WSL with Ubuntu 18.04.4 using MobaXterm v12.4  as a X11Server
 - Version: [e.g. 22]
 - Go version: 1.14.2
 - Fyne version: 1.3.1

**Comment by Ariemeth** [comment]
Simply moving the mouse over the window causes the application to refresh and display correctly

**Comment by andydotxyz** [comment]
The centering regression was fixed in v1.3.2 - I can not replicate the rendering issue, perhaps you could test and report back @Ariemeth ?

**Comment by Ariemeth** [comment]
Updated to v1.3.2, The centering issue has been resolved, but the rendering issue has not
I'm going to test on my macbook this afternoon and see if the issue occurs there as well

**Comment by Ariemeth** [comment]
I should have tested natively on windows before submitting the bug.  Building on windows with mingw64 the display renders fine.  Going to test on my mac and if that looks good as well I'll close this bug.  The half rendering on startup did not occur before 1.3.1 so it might be a sign of something really subtle, I don't know.

**Comment by Ariemeth** [comment]
Centering issue resolved on all platforms.  Will be splitting the rendering issue into its own issue.
