### ISSUE TITLE
Can't insert a SVG in NewImageFromFile("img.svg")

### ISSUE THREAD

**Issue by LuisFlahan4051** [fyne-io/fyne#1179]
The app don't show the img.svg when y try over the same example of https://developer.fyne.io/tour/canvas/image.html

The code:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Image")

	// image := canvas.NewImageFromResource(theme.FyneLogo())
	// image := canvas.NewImageFromFile("img.jpg") <-- this line works fine
    image := canvas.NewImageFromFile("img.svg") // <-- but this doesn't work
	// image := canvas.NewImageFromImage(src)
	image.FillMode = canvas.ImageFillOriginal
	w.SetContent(image)

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
This should work - can you share more details about what it looks like when it doesn’t work?

**Comment by dylandrush** [comment]
This code seems to work in Windows, but not Linux.

Code:
[svg.go.txt](https://github.com/fyne-io/fyne/files/4928372/svg.go.txt)

Code formatting didn't work but basically I just have the xml from the svg in a string and
 `bullResource := fyne.NewStaticResource("bull.svg", []byte(bullSvg))`
`image := canvas.NewImageFromResource(bullResource)`

I had the same problem with:
`image := canvas.NewImageFromFile("bull.svg")`

I expect and I get in Windows:
![Windows](https://user-images.githubusercontent.com/6423075/87607657-d86e7600-c6cb-11ea-9f15-e7a6951adc5f.png)


But I get the following in Ubuntu:
![Linux](https://user-images.githubusercontent.com/6423075/87607861-4a46bf80-c6cc-11ea-9d43-c9f461389c68.png)

**Comment by llorephie** [comment]
> This code seems to work in Windows, but not Linux.
> 
> Code:
> 
> ```
> package main
> 
> import (
> 	"fyne.io/fyne"
> 	"fyne.io/fyne/app"
> 	"fyne.io/fyne/canvas"
> )
> 
> func main() {
> 
> 	bullSvg := `<?xml version="1.0" encoding="utf-8"?>
> <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
> 	 viewBox="0 0 2218 1657.9141" enable-background="new 0 0 2218 1657.9141" xml:space="preserve">
> <g>
> 	<path d="M1569.4821,756.3787c167.0688,31.0914,340.3372,34.0774,398.8802-27.9609
> 		c52.1882-55.3039,12.3429-140.7786-46.7471-224.1246c-40.5529-58.7409-83.7411-117.9243-134.562-173.0084
> 		c-60.6146-65.6991-61.6538-133.8582-1.3108-209.7072c33.6063-43.1924,72.9994-77.0134,123.6398-92.6206
> 		c-62.1421,71.4389-59.4829,143.3604-3.0581,212.7654c52.1213,64.1116,137.8567,138.4986,220.1923,228.4933
> 		c75.1453,82.1354,73.8345,215.8237-28.8345,290.9688C1996.3132,832.2311,1811.1814,821.8126,1569.4821,756.3787z"/>
> 	<path d="M1439.8455,691.8228c-47.2252-69.2252-98.6542-233.7604-94.47-274.0397c0.3362-3.2361,4.1588-4.7489,6.6239-2.6256
> 		c95.0145,81.8394,193.0103,144.1442,296.3412,171.4895c131.3197,36.7415,235.7904,43.8434,248.6996-50.1331
> 		c60.6372,76.7186,69.5493,135.989,16.3833,174.3191c-104.9227,50.3553-267.4762,31.0848-459.0155-9.257
> 		C1448.4769,700.3267,1443.2612,696.8298,1439.8455,691.8228z"/>
> 	<path d="M648.518,756.3787c-167.0689,31.0914-340.3372,34.0774-398.8804-27.9609
> 		c-52.1882-55.3039-12.3429-140.7786,46.7472-224.1246c40.5529-58.7409,83.741-117.9243,134.562-173.0084
> 		c60.6145-65.6991,61.6538-133.8582,1.3107-209.7072c-33.6062-43.1924-72.9993-77.0134-123.6397-92.6206
> 		c62.1421,71.4389,59.4829,143.3604,3.0581,212.7654C259.5546,305.8341,173.8192,380.221,91.4836,470.2158
> 		c-75.1452,82.1354-73.8345,215.8237,28.8346,290.9688C221.6867,832.2311,406.8186,821.8126,648.518,756.3787z"/>
> 	<path d="M778.1545,691.8228c47.2252-69.2252,98.6542-233.7604,94.4699-274.0397c-0.3361-3.2361-4.1587-4.7489-6.6238-2.6256
> 		c-95.0145,81.8394-193.0103,144.1442-296.3412,171.4895c-131.3198,36.7415-235.7905,43.8434-248.6996-50.1331
> 		c-60.6372,76.7186-69.5493,135.989-16.3834,174.3191c104.9228,50.3553,267.4763,31.0848,459.0156-9.257
> 		C769.5231,700.3267,774.7388,696.8298,778.1545,691.8228z"/>
> 	<path d="M1463.5361,756.3787c-87.8148-35.0604-182.1831-240.1802-150.7271-346.0168
> 		c-63.0472-8.6763-120.3456-27.2895-172.353-55.0481l-12.1237,1024.9436h-19.66h-19.66l-12.1238-1024.9436
> 		c-52.0074,27.7586-109.3057,46.3718-172.353,55.0481c31.4561,105.8366-62.9121,310.9564-150.727,346.0168
> 		c-48.231,93.7338-59.9077,149.6456-25.558,157.9357c35.0604-70.4485,192.9961-65.8611,243.1292-19.0047
> 		c4.8883,69.9946-104.5259,114.6836-214.9498,74.0529c7.864,61.6014,109.4409,167.7657,186.1151,285.0707
> 		c41.9034,58.8145,67.6739,118.6497,55.7035,180.8723l3.4405-0.1638c-30.116,55.6479-30.8826,98.3822,8.7651,150.809
> 		c23.2811,30.7848,57.5153,43.0111,97.8906,43.0063H1109c40.3752,0.0048,74.6096-12.2216,97.8906-43.0063
> 		c39.6478-52.4268,38.8811-95.161,8.7651-150.809l3.4404,0.1638c-11.9703-62.2227,13.8002-122.0579,55.7035-180.8723
> 		c76.6742-117.3049,178.2511-223.4692,186.1151-285.0707c-110.424,40.6307-219.8381-4.0583-214.9498-74.0529
> 		c50.1332-46.8564,208.0688-51.4438,243.1293,19.0047C1523.4437,906.0243,1511.7671,850.1125,1463.5361,756.3787z
> 		 M1109.6554,1575.5472h-1.9661c-40.7294,0.5153-71.7592-25.5581-71.7592-70.4485c0-40.9584,30.2258-67.0015,72.7422-71.4315
> 		c42.5162,4.4301,72.7422,30.4731,72.7422,71.4315C1181.4146,1549.9891,1150.3846,1576.0625,1109.6554,1575.5472z"/>
> </g>
> </svg>
> `
> 	bullResource := fyne.NewStaticResource("bull.svg", []byte(bullSvg))
> 	myApp := app.New()
> 	w := myApp.NewWindow("Image")
> 	image := canvas.NewImageFromResource(bullResource)
> 	// Doing thie following worked in windows, but not ubuntu either
> 	// image := canvas.NewImageFromFile("bull.svg")
> 	image.FillMode = canvas.ImageFillOriginal
> 	w.SetContent(image)
> 
> 	w.ShowAndRun()
> }
> ```
> 
> I expect and I get in Windows:
> ![Windows](https://user-images.githubusercontent.com/6423075/87607657-d86e7600-c6cb-11ea-9f15-e7a6951adc5f.png)
> 
> But I get the following in Ubuntu:
> ![Linux](https://user-images.githubusercontent.com/6423075/87607861-4a46bf80-c6cc-11ea-9d43-c9f461389c68.png)

Seems to be Ubuntu's fault, as running fine under Wayland GNOME 3.36 session on Arch Linux.
SVG style slightly edited as I have 1920x1080, and window created slightly out of bounds:
![изображение](https://user-images.githubusercontent.com/3751049/87634240-8f5b0800-c745-11ea-98b5-0cb6fe44e32b.png)

**Comment by andydotxyz** [comment]
If you resize the Ubuntu window does it display correctly @llorephie?

The issue with it appearing larger on a different computer is probably due to the use of “canvas.ImageFillOriginal” - that is telling fyne to display a specific number of pixels - but different systems have different display densities and so it can create unexpected results. You probably want it to fill available space instead, and use “Contain”.

**Comment by llorephie** [comment]
> If you resize the Ubuntu window does it display correctly @llorephie?
> 
> The issue with it appearing larger on a different computer is probably due to the use of “canvas.ImageFillOriginal” - that is telling fyne to display a specific number of pixels - but different systems have different display densities and so it can create unexpected results. You probably want it to fill available space instead, and use “Contain”.

Provided SVG contains exact points to draw, company logo seems looking fine:
![изображение](https://user-images.githubusercontent.com/3751049/87679575-0794ee00-c785-11ea-8731-b509218f8f90.png)
![изображение](https://user-images.githubusercontent.com/3751049/87679596-0d8acf00-c785-11ea-8f2d-b4573e38174e.png)

BUT found another problem with SVG rendering: it ignores colors at all.
You can give a try with this SVG: https://raw.githubusercontent.com/llorephie/llorephie.github.io/master/assets/img/GNU_Linux.svg it renders like this:
![изображение](https://user-images.githubusercontent.com/3751049/87679835-55115b00-c785-11ea-8922-756dceaa9119.png)

But scales according to window size.

**Comment by andydotxyz** [comment]
Yes we currently do not have support for gradients or colour references. Colours will be respected if they are specified inline I think.
The library is a partial implementation based on what was needed initially. If you have a good (pure go) alternative say so and/or if you can help progress the project Fyne (and upstream) would be grateful https://github.com/srwiley/oksvg

**Comment by andydotxyz** [comment]
Worth noting: The exact X:Y coordinates don’t necessarily map to specific locations on a window as we have to scale canvas content according to device and user preference.

**Comment by dylandrush** [comment]
> If you resize the Ubuntu window does it display correctly @dylandrush
> 
> The issue with it appearing larger on a different computer is probably due to the use of “canvas.ImageFillOriginal” - that is telling fyne to display a specific number of pixels - but different systems have different display densities and so it can create unexpected results. You probably want it to fill available space instead, and use “Contain”.

No that didn't work for me.  Original code, I wasn't able to resize in Ubuntu.  Changing to "canvas.ImageFillContain" allows me to change the size of the window, but I still don't see anything.
![small](https://user-images.githubusercontent.com/6423075/87724366-55abf080-c789-11ea-94e5-0b6fdea65101.png)

![large](https://user-images.githubusercontent.com/6423075/87724371-5775b400-c789-11ea-92a0-7021f6ce67e5.png)

**Comment by andydotxyz** [comment]
And there are no errors in the console?
There is something else going on here as the content of the window cannot impact whether it can be resized or not...

**Comment by dylandrush** [comment]
No errors in the console when resizing with "canvas.ImageFillContain"

![NoErrors](https://user-images.githubusercontent.com/6423075/87731332-38325300-c798-11ea-8a15-b5ffa8b91ebc.png)

I can resize the window lager with "canvas.ImageFillOriginal" but I cannot make it smaller, and it is already larger than the desktop display.  Also, no errors when resizing larger or back to "original" in the console.

**Comment by andydotxyz** [comment]
Oh, I see what you mean - yes if you ask your window content to be larger than the desktop it won't manage I see what you mean. I guess that means that the file loads OK but simply does not display... which narrows things down I guess.

Would it be possible to print out the content of `Window.Content()` on a timer to see if sizes change? Something like:

```
go func() {
    time.Sleep(time.Second)
    log.Println(w.Content())
}()
```

It might help to understand what is happening (i.e. are we seeing a small portion of the content, or is it scaling but invisible).

**Comment by dylandrush** [comment]
> Oh, I see what you mean - yes if you ask your window content to be larger than the desktop it won't manage I see what you mean. I guess that means that the file loads OK but simply does not display... which narrows things down I guess.
> 
> Would it be possible to print out the content of `Window.Content()` on a timer to see if sizes change? Something like:
> 
> ```
> go func() {
>     time.Sleep(time.Second)
>     log.Println(w.Content())
> }()
> ```
> 
> It might help to understand what is happening (i.e. are we seeing a small portion of the content, or is it scaling but invisible).

Okay, so I did that, This is me resizing the window (with canvas.ImageFillContain), otherwise, it will just sit there repeating the first line
```
2020/07/17 17:13:11 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:12 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:13 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:14 &{{{1840 904} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:15 &{{{1840 904} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:16 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:17 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:18 &{{{1 1} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:19 &{{{313 151} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:20 &{{{495 237} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:21 &{{{495 237} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:22 &{{{495 237} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:23 &{{{495 237} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:24 &{{{688 436} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:25 &{{{779 495} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:26 &{{{869 606} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:27 &{{{717 567} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:28 &{{{345 317} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:29 &{{{172 148} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:30 &{{{64 61} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:31 &{{{59 57} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:32 &{{{657 363} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:33 &{{{1157 660} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:34 &{{{1339 721} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
2020/07/17 17:13:35 &{{{1339 721} {4 4} false {0 0} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 1 0}
```
Here is ImageFillOriginal, I let it sit there for a few seconds, and then I just kept trying to make the window larger:
```
2020/07/17 17:16:20 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:21 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:22 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:23 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:24 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:25 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:26 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:27 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:28 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:29 &{{{2218 1657} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:30 &{{{2248 1699} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:31 &{{{2335 1710} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:32 &{{{2434 1801} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:33 &{{{2435 1801} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:34 &{{{2435 1801} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:35 &{{{2435 1801} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:36 &{{{2751 2005} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:37 &{{{2829 2085} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:38 &{{{2829 2085} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:39 &{{{2829 2085} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:40 &{{{3237 2254} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:41 &{{{3438 2519} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:42 &{{{3438 2519} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:43 &{{{3438 2519} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:44 &{{{3841 2814} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:45 &{{{3841 2822} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:46 &{{{3841 2822} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:47 &{{{3841 2822} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:48 &{{{4023 3038} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:49 &{{{5245 3461} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:50 &{{{5259 3461} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:51 &{{{5259 3461} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:52 &{{{5259 3461} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
2020/07/17 17:16:53 &{{{5259 3461} {4 4} false {2218 1657} {{0 0} 0 0 0 0}}  0xc000093320 <nil> 0 2 0}
```

**Comment by andydotxyz** [comment]
Thanks so much for this. So it is "working" in terms of layout so the image is literally not displaying. This is a puzzle!
One last question - on the computer where this is failing can you share what happens if you just set content to `widget.NewLabel("testing")` instead?

Can you also please provide the version of Ubuntu / Gnome so we can try to replicate on another computer?

**Comment by dylandrush** [comment]
> Thanks so much for this. So it is "working" in terms of layout so the image is literally not displaying. This is a puzzle!
> One last question - on the computer where this is failing can you share what happens if you just set content to `widget.NewLabel("testing")` instead?
> 
> Can you also please provide the version of Ubuntu / Gnome so we can try to replicate on another computer?

Sure thing.  Everything worked no problem here. Resizing worked as expected.

I am using Ubuntu 20.04 LTS / Gnome 3.36.2

Note: this is a virtual machine.

![system](https://user-images.githubusercontent.com/6423075/87834896-9b37ee80-c859-11ea-92f2-24c16a9a807c.png)


Here is the log:
```
2020/07/17 17:57:00 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:01 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:02 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:03 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:04 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:05 &{{{58 29} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:06 &{{{437 111} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:07 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:08 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:09 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:10 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:11 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:12 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:13 &{{{494 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:14 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:15 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:16 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:17 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:18 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:19 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:20 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
2020/07/17 17:57:21 &{{{1121 139} {4 4} false 0xc00015e080 {{0 0} 0 0 0 0}} testing 0 0 {false false false} 0xc00014c090}
```

**Comment by andydotxyz** [comment]
Is it possible for @LuisFlahan4051 to confirm the system, version etc and the SVG file that is not working as well?

**Comment by andydotxyz** [comment]
> Sure thing. Everything worked no problem here. Resizing worked as expected.

Sorry this confused me @dylandrush you shared screenshots of it not working - so I'm not sure what is or isn't working and on which computer... Apologies if I missed something.

**Comment by dylandrush** [comment]
> > Sure thing. Everything worked no problem here. Resizing worked as expected.
> 
> Sorry this confused me @dylandrush you shared screenshots of it not working - so I'm not sure what is or isn't working and on which computer... Apologies if I missed something.

"One last question - on the computer where this is failing can you share what happens if you just set content to widget.NewLabel("testing") instead?"

That was working no problems, when the content was only a label, no svg, everything worked with no problems.  Resizing worked.

As a side note for me, I noticed that this isn't a problem with every svg file for me on Ubuntu.  Two of them that didn't work for me was the above bull example that I just randomly pulled off the internet, and another svg which I used some online tool to convert an png to svg.  However, I created my own svg in Inkscape, and that displayed without problem.

**Comment by LuisFlahan4051** [comment]
> Is it possible for @LuisFlahan4051 to confirm the system, version etc and the SVG file that is not working as well?

Sure!
This is my SVG:
[https://github.com/LuisFlahan4051/proyecto-registros/blob/master/src/luisflahan4051apps.svg](url)
And my system:
![Screenshot_20200723_201900](https://user-images.githubusercontent.com/38896070/88353193-316c8880-cd22-11ea-9804-cddee22a7600.png)

**Comment by andydotxyz** [comment]
THanks @LuisFlahan4051 on macOS I get the following image, becase we don't have support for gradient or text glyph in SVG yet:

<img width="400" alt="Screenshot 2020-07-24 at 10 04 03" src="https://user-images.githubusercontent.com/294436/88376381-2bfc5600-cd95-11ea-97ea-982f0b003dad.png">

Can you confirm what happens on your computer? Do you see this partial rendering or is it a blank window?

**Comment by LuisFlahan4051** [comment]
> THanks @LuisFlahan4051 on macOS I get the following image, becase we don't have support for gradient or text glyph in SVG yet:
> 
> <img alt="Screenshot 2020-07-24 at 10 04 03" width="400" src="https://user-images.githubusercontent.com/294436/88376381-2bfc5600-cd95-11ea-97ea-982f0b003dad.png">
> 
> Can you confirm what happens on your computer? Do you see this partial rendering or is it a blank window?

No, it just doesn't show anything.
I tried with another SVG and the same.

**Comment by andydotxyz** [comment]
Did you find a resolution to this issue @LuisFlahan4051?

**Comment by refaktor** [comment]
I tried to display SVG on Linux today and it also didn't display it to me if I used canvas.ImageFillContain or anything else than ImageFillOriginal. It's not a problem for me, just letting you know.

**Comment by andydotxyz** [comment]
Please don't comment in an old issue from 4 years ago that is closed.

If only Original "is working" then it's because you're packing the image into a container that forces it to MinSize. Images do not have the same coordinate system as the GUI and so they take up only the space you give them.
