### ISSUE TITLE
dialog.NewFileOpen() will clear the file contents in fyne@1.3.1

### ISSUE THREAD

**Issue by Dynamith** [fyne-io/fyne#1182]
### Describe the bug:
There is no problem when switching to version 1.3.0, it should be a new bug.
Hope to fix it as soon as possible, otherwise I can only use version 1.3.0.

### To Reproduce:
Steps to reproduce the behaviour:
1. Compile the fyne_demo in cmd.
2. Open the "File Open With Filter (.txt or .png)" in tab window
3. You will find the file contents are cleared.

### Screenshots:
![01](https://user-images.githubusercontent.com/64576195/87212739-b2a34300-c352-11ea-9266-afc8485a3b59.jpg)
![02](https://user-images.githubusercontent.com/64576195/87212742-b5059d00-c352-11ea-8b1c-77e8222451c0.jpg)

### Device (please complete the following information):
 - OS: [windows10 x64]
 - Version: [1909]
 - Go version: [1.14.4]
 - Fyne version: [1.3.1]

**Comment by RustamGamidov** [comment]
didn't manage to reproduce on:
 - fyne: 1f836a6f172934d9ddd54ffea912602ae1a25c5b
 - win10pro x64 10.0.18363
 - go: 1.14.4 windows/amd64

@Dynamith one silly question. Could it be miss-click with the *File Save*?

**Comment by Jacalz** [comment]
It could possibly be that you are using the old 1.3.1 that was released before the fix mentioned by @RustamGamidov and thus still is based on a commit before that one. Could try to download 1.3.1 again and see if it still is reproducible?

**Comment by Dynamith** [comment]
@RustamGamidov , @Jacalz 
I reinstalled it once, and compile and run fyne@1.3.1/cmd/fyne_demo, but it still does not work.
And maybe I have found the reason. There is no os.Open() in func openFile().


fyne@1.3.0\internal\driver\glfw\file.go
```
package glfw

import (
	"fmt"
	"os"
	"path/filepath"

	"fyne.io/fyne"
	"fyne.io/fyne/storage"
)

type file struct {
	*os.File
	path string
}

func (d *gLDriver) FileReaderForURI(uri fyne.URI) (fyne.URIReadCloser, error) {
	return openFile(uri, false)
}

func (f *file) Name() string {
	return filepath.Base(f.path)
}

func (f *file) URI() fyne.URI {
	return storage.NewURI("file://" + f.path)
}

type fileWriter struct {
	*os.File
	path string
}

func (d *gLDriver) FileWriterForURI(uri fyne.URI) (fyne.URIWriteCloser, error) {
	return openFile(uri, true)
}

func (f *fileWriter) Name() string {
	return filepath.Base(f.path)
}

func (f *fileWriter) URI() fyne.URI {
	return storage.NewURI("file://" + f.path)
}

func openFile(uri fyne.URI, create bool) (*file, error) {
	if uri.Scheme() != "file" {
		return nil, fmt.Errorf("invalid URI for file: %s", uri)
	}

	path := uri.String()[7:]
	f, err := os.Open(path)
	if err != nil && create {
		f, err = os.Create(path)
	}

	return &file{File: f, path: path}, err
}
```


fyne@1.3.1\internal\driver\glfw\file.go
```
package glfw

import (
	"fmt"
	"os"
	"path/filepath"

	"fyne.io/fyne"
	"fyne.io/fyne/storage"
)

type file struct {
	*os.File
	path string
}

func (d *gLDriver) FileReaderForURI(uri fyne.URI) (fyne.URIReadCloser, error) {
	return openFile(uri, false)
}

func (f *file) Name() string {
	return filepath.Base(f.path)
}

func (f *file) URI() fyne.URI {
	return storage.NewURI("file://" + f.path)
}

func (d *gLDriver) FileWriterForURI(uri fyne.URI) (fyne.URIWriteCloser, error) {
	return openFile(uri, true)
}

func openFile(uri fyne.URI, create bool) (*file, error) {
	if uri.Scheme() != "file" {
		return nil, fmt.Errorf("invalid URI for file: %s", uri)
	}

	path := uri.String()[7:]
	f, err := os.Create(path) // If it exists this will truncate which is what we wanted

	return &file{File: f, path: path}, err
}
```

**Comment by Dynamith** [comment]
I looked at the source code of 1.3.1 on github and it was correct.
But when I run "go get fyne.io/fyne" I get the error one, why?😂

**Comment by andydotxyz** [comment]
How did you remove it before retrying? I wonder if you have some caches they would need removed too?

**Comment by Dynamith** [comment]
@andydotxyz
Yes, you should remove "%GOPATH%/pkg/mod/cache", because it is download cache.

**Comment by Niek** [comment]
I have the same issue. Removed everything in `$GOPATH`, this is my setup:
```bash
→ grep fyne go.mod
	fyne.io/fyne v1.3.1
→ fyne version
fyne cli version v1.3.1
→ ls $GOPATH/pkg/mod/fyne.io/
fyne@v1.3.1
```
But I still get truncated files when opening. However, when I do:
```bash
go get fyne.io/fyne@master
```
So I'm pretty sure the last commit didn't get included in the v1.3.1 release.

**Comment by andydotxyz** [comment]
It looks like the standard go proxy has cached the broken v1.3.1 so we will have to roll v1.3.2 for module users. I will start that process today.

**Comment by andydotxyz** [comment]
V1.3.2 is now out with this fix firmly in!
