### ISSUE TITLE
SetFullScreen(true) gives black screen

### ISSUE THREAD

**Issue by gmlewis** [fyne-io/fyne#119]
If I run this program:

```go
	a := app.New()

	pixelFunc := func(x, y, w, h int) color.Color {
		return color.RGBA{R: 255, G: 0, B: 0, A: 255}
	}

	w := a.NewWindow("SetFullScreen(true)")
	w.SetFullScreen(true)
	w.SetContent(widget.NewVBox(
		canvas.NewRaster(pixelFunc),
		widget.NewButton("Quit", func() {
			a.Quit()
		}),
	))

	w.ShowAndRun()
```

I don't see the `Quit` button and all I get is a black screen.

This is on Linux.

**Comment by jadr2ddude** [comment]
I will attempt to reproduce once I have electricity

**Comment by jadr2ddude** [comment]
So I got this to work. It also changes my screen resolution to something tiny until i switch virtual desktops several times. I am going to test this in a nested X server to see if I can isolate it better.

**Comment by andydotxyz** [comment]
What happens if you call SetFullscreen() after SetContent()?

**Comment by gmlewis** [comment]
It appears to ignore the `SetFullScreen` altogether if it is moved after `SetContent`.

**Comment by jadr2ddude** [comment]
So far I have investigated and discovered that this works correctly when run without any window manager, but fails when using window managers.

**Comment by gmlewis** [comment]
OK, just FYI, I'm using Cinnamon on Linux Mint.

**Comment by jadr2ddude** [comment]
I run Cinnamon on Manjaro Linux, which is how I originally replicated it. I am testing in Xephyr w/ openbox because this messes up my monitor.

**Comment by andydotxyz** [comment]
It works perfectly fine with Gnome and openbox but it does not work if there is no window manager loaded. It also works correctly on Cinnamon.

The difference: I am calling this from a button callback...!

**Comment by andydotxyz** [comment]
Can you try applying this patch to Fyne and see if it fixes the issue? 
Works here :)
[fullscreen.diff.txt](https://github.com/fyne-io/fyne/files/2864102/fullscreen.diff.txt)

**Comment by gmlewis** [comment]
That works for me!  Thanks, @andydotxyz!
