### ISSUE TITLE
Widget freezes on frequent updates.

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1190]
I have a complex widget that contains an image that displays webcam video frames. The image object is added to a nested box after some delay (must be shown after we've got a video source process launched). After adding it we call `Widget.Refresh()`. Then the image starts to be updated for each frame (5/10 fps) calling `canvas.Refresh()`.

Now the problem is that on some Windows machines the image doesn't come up at all (not shown added to the box). Careful logging reveals that the widget is updated and the image is properly fed with frames, but it still does not appear. Eventually it comes up after 30-300 secs. On some machines this problem is never reproduced.

Can you suggest me directions to solve this problem? Does it sound like a Fyne bug? I understand that without the code it's hard to figure that out. Maybe I'll attach some of it, but it's far from being minimal, that's why I don't do it now.

Thanks in advance.

**UPDATE**: Adding 1 second sleep between widget refresh and image refreshes greatly reduces probability of such a freezing.

**Comment by andydotxyz** [comment]
Can you please add information about the versions you are using (the bug template should have asked).

**Comment by ababo** [comment]
Fyne: 5cfe49a5fc5aa05717b45f0ba5557746a33b87cc
OS: Windows 10 (6.3)
Golang: 1.14

**Comment by andydotxyz** [comment]
Thanks. From your description it sounds like it should work - but the refresh code you describe isn't quite right...
To refresh an image when a new one arrives it should just require `myImage.Refresh()`.
I suspect that either the box is packed in a way that on some systems the image does not appear, or that you are somehow overlaying lots and lots of images which on a slow graphics driver could cause problems.

Of course this is just an educated guess as there is no code to check.
I hope that helps.

**Comment by ababo** [comment]
It looks my first update isn't quite correct. Really strange things are happening. We use a package for sending analytics messages during the workflow. It tries to send HTTP message synchronously with a half-second timeout and if it fails, then queues the message to be sent asynchronously. It turns out that if we disable synchronous sending tries and just queue the messages the described window doesn't freeze at all.

**Comment by andydotxyz** [comment]
Ah yes, if you have synchronous network access in your UI code it could do bad things.
It sounds like this issue can be closed then?

**Comment by ababo** [comment]
@andydotxyz Did you read the whole message?

**Comment by andydotxyz** [comment]
Yes I did. You say that the code does not block rendering, OK - but what about image load, or frame download?
If the only change is not waiting for log calls then this really doesn't sound like a bug in the toolkit.
If you feel there is still an issue here then please provide a minimal code sample that reproduces the issue - otherwise I don't seee how else we can help :(

**Comment by ababo** [comment]
Have fixed that issue by replacing `box.Refresh()` with `Canvas.Refresh(box)`. @andydotxyz Should I close this issue, or you think that's unexpected behaviour?

**Comment by andydotxyz** [comment]
I'm glad that you fixed it but I can't think why that helps.
The issue remains as apps should not freeze. 
That said if you can't provide a minimal code that reproduces there isn't much that we can do sorry.
I'll leave it up to you :)

**Comment by andydotxyz** [comment]
No further activity so suspect there is no more to do

**Comment by don-nv** [comment]
Hello there

It seems like I've just entered the same issue. However there is a workaround, but it doesn't seem to be correct, since binding should provide stable reactive UI updates. It looks like a bug to me

The issue discovered on:
- Distributor ID:	Linuxmint
- Description:	Linux Mint 20.2
- Release:	20.2
- Codename:	uma

Here is a code to reproduce the problem

---

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
	"strconv"
	"time"
)

func main() {
	var app = app.New()

	var (
		labelText       = ""
		bindedLabelText = binding.BindString(&labelText)

		label = widget.NewLabelWithData(bindedLabelText)
	)

	var window = app.NewWindow("Canvas")

	var verticalBox = container.NewVBox(label)
	window.SetContent(verticalBox)

	go func() {
		for i := 0; ; i++ {
			var newLabelText = strconv.Itoa(i)
			if err := bindedLabelText.Set(newLabelText); err != nil {
				panic(err)
			}

			time.Sleep(time.Microsecond)

			// NOTE: the only thing, that helps prevent UI updates from freezes
			// canvas.Refresh(label)
		}
	}()

	window.ShowAndRun()
}

**Comment by andydotxyz** [comment]
I think if you try to drive a GUI with 1'000'000 frames per second you will hit considerable CPU constraints.
Can you try updating less frequently and see if the problem goes away?

**Comment by don-nv** [comment]
> I think if you try to drive a GUI with 1'000'000 frames per second you will hit considerable CPU constraints. Can you try updating less frequently and see if the problem goes away?

Thanks for the suggestion. It is interesting point of view, that I didn't consider. I've tried binding with the following delays:

`
// At some point, while app is running, counter still gets freeze
time.Sleep(time.Millisecond)
`

`
// No freezes at all
time.Sleep(10 * time.Millisecond)
`

But I wonder, if it's a real GPU constraint. As I mentioned before, `canvas.Refresh(label)` does the trick, even if I run the app, using `time.Nanosecond` delay. Doesn't it mean there's something deeper inside? As I can see from the top-level overview, `canvas.Refresh()` calls driver in use directly, while `binding.ExternalString{}.Set()` enqueues user interface update. It seems like there might be some kind of "soft locks"?

**Comment by don-nv** [comment]
> > I think if you try to drive a GUI with 1'000'000 frames per second you will hit considerable CPU constraints. Can you try updating less frequently and see if the problem goes away?
> 
> Thanks for the suggestion. It is interesting point of view, that I didn't consider. I've tried binding with the following delays:
> 
> ` // At some point, while app is running, counter still gets freeze
> 
> ```
> time.Sleep(time.Millisecond)
> ```
> 
> `
> 
> ` // No freezes at all
> 
> ```
> time.Sleep(10 * time.Millisecond)
> ```
> 
> `
> 
> But I wonder, if it's a real GPU constraint. As I mentioned before, `canvas.Refresh(label)` does the trick, even if I run the app, using `time.Nanosecond` delay. Doesn't it mean there's something deeper inside? As I can see from the top-level overview, `canvas.Refresh()` calls driver in use directly, while `binding.ExternalString{}.Set()` enqueues user interface update. It seems like there might be some kind of "soft locks"?

Sorry, I misled about direct refresh calls and binding enqueues. As I can see now, they're all use same queue implementation. But anyway, the main idea was about expected results equality between `canvas.Refresh()` and `binding.ExternalString{}.Set()` invocations as it purposed by its meaning (to my mind)

**Comment by andydotxyz** [comment]
I still don't really follow, sorry.
Calling `Set` on a data binding that is connected to a widget is sufficient to update it's visuals - no further calls to `Refresh` are needed.

**Comment by andydotxyz** [comment]
As you have bound to an external value you could also update it and use reload... `labelText = "new"; binding.Reload()`.
This is designed for when you have code that controls the data externally. If you are only using `Get` and `Set` then you'd be better using `binding.NewString()`.
