### ISSUE TITLE
Issue with Entry's Placeholder

### ISSUE THREAD

**Issue by antonmaju** [fyne-io/fyne#1193]
**Issue:**
If entry has both placeholder and text value, it will still render both text and placeholder initially.
This causes text to be hard to read.

**Expected:**
Entry won't render placeholder if text is present.

![image](https://user-images.githubusercontent.com/1287278/87817241-d276c180-c892-11ea-8b8a-d95d0b9665eb.png)

**Device Info**
 - OS: Tested on Windows 10 & Ubuntu 18.04
 - Go version: 1.14
 - Fyne version: 1.3.2

**Comment by andydotxyz** [comment]
Thanks for the report, not sure how this slipped in.
Does it fix if you resize, or only if you type something?

**Comment by antonmaju** [comment]
Hi @andydotxyz,
Performing resize doesn't fix the issue, but getting focus or calling FocusGained() manually fixes it

**Comment by andydotxyz** [comment]
For some reason I am struggling to replicate this sorry - can you share the code that exhibits that result please?

**Comment by antonmaju** [comment]
Hi @andydotxyz 

The example is like this
```
import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func TextBoxTest() {
	wApp := app.New()
	w := wApp.NewWindow("Fyne Test")
	w.Resize(fyne.Size{ Width: 400, Height: 300})
	w.SetFixedSize(true)
	lblTitle := widget.NewLabel("Title")
	txtTitle := widget.NewEntry()
	txtTitle.Text = "Test"
	txtTitle.SetPlaceHolder("Default text")
	//txtTitle.FocusGained()
	content := fyne.NewContainerWithLayout(layout.NewVBoxLayout(), lblTitle, txtTitle)
	w.SetContent(content)
	w.ShowAndRun()
}
```

Thanks !

**Comment by andydotxyz** [comment]
Oh thanks so much - our test utility was somehow not triggering this bug but now I can replicate/

**Comment by antonmaju** [comment]
HI @andydotxyz 

Sorry I just realized, if I use SetText method instead of Text property directly it works.

**Comment by andydotxyz** [comment]
Not a problem, that's a fix on `develop` now if you'd like to test :)

**Comment by Conan520** [comment]
I also had this problem, but I fixed it with SetText("")

**Comment by Conan520** [comment]
I also had this problem, but I fixed it with SetText(""), I don't know why
