### ISSUE TITLE
material2: Improve styling of dialogs

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1202]
### Describe the bug:
Current dialog styling is flat and could most certainly do with some improved styling in line with material design guidelines if possibly. This issue is a follow up to the material2 theme changes happening in Fyne :)

### Screenshots:

Like you can see, dialogs are basically just a coloured rectangle on top of the window contents. Could probably be improved to look better :)

![image](https://user-images.githubusercontent.com/25466657/88091457-58468580-cb8f-11ea-9f52-5ec4be781b88.png)

**Comment by Jacalz** [comment]
I don’t know how much can be done because she material guidelines are quite strict, but adding a shadow around it would be a great start 😁

**Comment by andydotxyz** [comment]
Yes, it feels like shadow is missing. They are present for the non-modal so this is just specific to the modal dialogs I think.

**Comment by andydotxyz** [comment]
Shadows done, looks much better :)

**Comment by Jacalz** [comment]
Thanks. Looks great now 👍
