### ISSUE TITLE
Add button icon placement that is not dependent on text length and not centered

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1203]
### Is your feature request related to a problem? Please describe:
While introducing the icons for favoruites in the file dialog I thought about introducing a new button placement constant to the button widget. Pretty much all file browsers (as an example, there are probably a lot more places where it makes sense) have the icons aligned in a row to the left and then text to the right. The thing about this is that icons are in the same place no matter how long the text it.

Currently, all icon placements seem to be centred. It has the following effect:

![image](https://user-images.githubusercontent.com/25466657/88092409-b7f16080-cb90-11ea-8638-b344850b8a28.png)

Notice how all the icons are a bit all over the place.

### Is it possible to construct a solution with the existing API?
I think so, yes. We would need to add a new constant to the ButtonPlacement code and update the layout of the button.

### Describe the solution you'd like to see:
Something like in nautilus file manager where icons are left-aligned in a row:

![image](https://user-images.githubusercontent.com/25466657/88092521-e40ce180-cb90-11ea-8345-d8c7b0fa088d.png)

**Comment by andydotxyz** [comment]
Can't you just set the button to leading alignment?
`myButton.Alignment = widget.ButtonAlignLeading`

**Comment by andydotxyz** [comment]
That already existed so just applied it to the file dialog :)

**Comment by Jacalz** [comment]
I almost certain that I tried it and it made no difference, but I guess that I must have done something wrong. Thanks for adding the simple fix :)
