### ISSUE TITLE
Add full-screen dialog

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1205]
### Is your feature request related to a problem? Please describe:
Some parts of a user interface makes sense to pop into a dialog, but some require a larger screen area than what a regular dialog can give. The solution now is to open a new window but there are situations where that doesn’t make sense, like on mobile or for stuff that is meant to cover the regular window contents.

### Is it possible to construct a solution with the existing API?
Yes. We could presumably add a dialog.ShowCustomFullScreen() function to satisfy the need. It might make sense to have an option in some places to add the option of making a dialog full screen like the file dialog.

### Describe the solution you'd like to see:
Something like the Material design spec on full screen dialog:
![image](https://user-images.githubusercontent.com/25466657/88163995-c339a000-cc13-11ea-81d8-c4991490b03a.png)

See the spec for more details: https://www.material.io/components/dialogs#usage

**Comment by andydotxyz** [comment]
That looks very much like a window (at least how we render them on mobile).
What do you think would be the key difference?

**Comment by Jacalz** [comment]
Probably how a you get a close button at the top and the ability of using it on desktop as well. I would very much like to have something like this where opening a new window just feels cluttered and unnecessary.

**Comment by andydotxyz** [comment]
Yes I suppose that's a fair point. 
But is a fullscreen dialog the right thing to do on desktop? Normally the windows will be a lot bigger...

**Comment by Jacalz** [comment]
Some windows are bigger yes, but some applications don't need to for example take up a 24" inch screen. In that situation it might make sense to have a dialog take up the whole window instead of changing the content with `w.SetContent()`. You could almost see it as a way of a quick way for changing the window contents and then going back to what was before, a bit like how a simple photo viewer might bring up a settings page.

**Comment by andydotxyz** [comment]
That's a good point but also quite tricky. It makes sense if the windows are small - but the user could feel free to expand it to fill that 24"...
I wonder perhaps if adapting to a fullscreen dialog if there is not sufficient room to float (or if it's above a certain percentage of the window size?).

**Comment by andydotxyz** [comment]
I think that this has been solved by `dialog.Resize()`

**Comment by ManuelReschke** [comment]
I think its not solved at all. I have a window with 550x600px and i create and resize a fileOpenDialog to 700x700 its just fill the hole window but its not the size we want. Why is the dialog not a seperate window? Or is it possible to use the system fileOpenDialog?

**Comment by andydotxyz** [comment]
Dialogs in Fyne draw into a window, that is how it works.
To use OS native file dialogs there are other libraries that you can invoke, or open a separate feature request.
