### ISSUE TITLE
Long text breaks dialog layout.

### ISSUE THREAD

**Issue by Torbilicious** [fyne-io/fyne#121]
Long multiline text seems to break the dialog layout:  

![dialog-bug](https://user-images.githubusercontent.com/1437095/52787572-949eb980-305e-11e9-9057-65f060507623.png)

I have created a simple repository to reproduce the bug [here](https://github.com/Torbilicious/fyne-popup-bug-reproduction).

**Comment by andydotxyz** [comment]
Good catch, thanks. MinSize is working but Layout is not - I will update the dialog base to fix
