### ISSUE TITLE
event callback too slow

### ISSUE THREAD

**Issue by dbv** [fyne-io/fyne#1214]
code example for this, when i click button, too quick click too slow label change and display. delayed to display
```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	myapp := app.New()
	w := myapp.NewWindow("box")

	lb := widget.NewLabel("abner")
	button := widget.NewButton("click", func() {
		if lb.Text == "abner" {
			lb.SetText("xiaohui")
		} else {
			lb.SetText("abner")
		}
	})
	box1 := widget.NewVBox(lb,button)
	w.SetContent(box1)
	w.ShowAndRun()
}
```

**Comment by Jacalz** [comment]
Hello @dbv. I haven’t had time to look at your issue yet, but please use the issue template in the future. It is there because it makes it much easier for us to help 🙂

**Comment by andydotxyz** [comment]
Like @Jacalz indicated this is missing information.
Can you please include your OS and version, Go version and Fyne version?

When run locally this code updates as quick as I would expect - just a fraction of a second (next frame is fasted at 1/60th second, possible it may take 2 frames).

Any more information would be helpful

**Comment by dbv** [comment]
@Jacalz please delete this issue, thanks.

**Comment by Jacalz** [comment]
Sorry @dbv, but there is no such thing as deleting GitHub issues.
Is the issue solved for you?
