### ISSUE TITLE
Window.Hide() crashes the application in Openbox

### ISSUE THREAD

**Issue by dfreet** [fyne-io/fyne#1215]
### Describe the bug:
When I call the Hide() function on any window, the application immediately crashes with the following error:
```Bash
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x40f273
  Serial number of failed request:  469
  Current serial number in output stream:  469
exit status 1
```
( the resource id and serial numbers are different every time )

This is one of the problems mentioned in #1115 , though the Quit() function exits cleanly without any errors.
I've run the same code on Openbox and i3, and the problem only occurs on Openbox, while the code behaves properly on i3

### Example code:
```go
package main

import (
	"time"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Hello")
	myWindow.SetContent(widget.NewVBox(
		widget.NewButton("quit", func() { myApp.Quit() }),
		widget.NewButton("hide", func() {
			myWindow.Hide()
			time.Sleep(time.Second * 2)
			myWindow.Show()
		}),
	))

	myWindow.ShowAndRun()
}
```

### Device:
 - OS: Arch Linux x86_64
 - WM: Openbox 3.6.1
 - Go version: 1.14.6
 - Fyne version: 1.13.2

**Comment by andydotxyz** [comment]
Can you confirm that the same happens if you don't block inside the button callback?

```go
func() {
	myWindow.Hide()
	go func() {
		time.Sleep(time.Second * 2)
		myWindow.Show()
	}
}
```

It's a bad idea to block when executing user actions, but I wasn't sure if it affected the crash or not..?

**Comment by postfinem** [comment]
Yes, it's the same behavior.  [this](https://developer.fyne.io/tour/basics/windows.html) example from the tour also causes the same error.

**Comment by andydotxyz** [comment]
I have found that the same issue is present in the Go GLFW demo app, so have escallated to their project go-gl/glfw#289

**Comment by Jacalz** [comment]
Is this still an issue with the latest version of Fyne?

**Comment by andydotxyz** [comment]
I could never replicate it sadly. Enough has changed there is a good chance it went away

**Comment by andydotxyz** [comment]
Let's
