### ISSUE TITLE
widget.Icon.iconRenderer not exported for embedding

### ISSUE THREAD

**Issue by carpetfuz** [fyne-io/fyne#1218]
### Describe the bug:

Per the advice on [this page](https://fyne.io/develop/tutorials/write-custom-widget) "it is entirely possible to re-use a renderer from another widget".

This is unfortunately not true for widget.Icon.  The renderer has been lowercased, meaning that it cannot be embedded externally.  Furthermore, it is not possible to follow the pattern of code within widget/icon.go because it imports BaseRenderer from internal; this is also not usable outside of the fyne framework.

### To Reproduce:
Attempt to extend functionality of widget.Icon.  Specifically, adjust functionality of only some of the functions of the renderer interface while leaving the others intact.

### Example code:
This example is trivial, but makes the point:

```go
import "fyne.io/fyne"
import "fyne.io/fyne/widget"

type NewIcon struct {
    widget.Icon
}

type NewIconRenderer struct {
    widget.iconRenderer
}

func (*NewIconRenderer) MinSize() fyne.Size {
    return fyne.NewSize(10, 10)
}
```

### Proposed Fix:
Change the case of iconRenderer to IconRenderer.

**Comment by andydotxyz** [comment]
By design we are not exposing the inner working of renderers.
You can, however, embed a renderer without the type being exported, the following code should be helpful:

```go
type tallLabel struct {
	widget.Label
}

func newTallLabel(label string) *tallLabel {
	ret := &tallLabel{}
	ret.ExtendBaseWidget(ret)
	ret.Text = label
	return ret
}

func (t *tallLabel) CreateRenderer() fyne.WidgetRenderer {
	r := t.Label.CreateRenderer()

	return &tallLabelRenderer{r}
}

type tallLabelRenderer struct {
	fyne.WidgetRenderer
}

func (t *tallLabelRenderer) MinSize() fyne.Size {
	return fyne.NewSize(t.WidgetRenderer.MinSize().Width, 100)
}
```

**Comment by carpetfuz** [comment]
Closed or not, your proposal for exposing the renderer is sadly of no help to me.  I need to change the behavior of the renderer.  Otherwise, what's the point?  Were the original one suitable, then I could use the original construct in its entirety.

I'd like to ask that you reconsider the policy: without renderer embedding, a developer is forced to recreate an entire renderer from scratch.  I only need to change behavior of one method.  I wish you would consider either exposing the widget renderers or the base renderer itself.  The example in Icon is dead simple, it's not like we're talking about something that exposes a large risk (granted, that is an opinion).

**Comment by carpetfuz** [comment]
Indirect, but I think I like it.   Thank you for the example - that's very helpful.
