### ISSUE TITLE
Extended progress bar does not update correctly

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1219]
### Describe the bug:
It seems like extending progress bars causes issues with refresh not working correctly among with some other issues that I have been seeing when using an extended progress bar in [wormhole-gui](https://github.com/Jacalz/wormhole-gui).

The example code seems to only refresh the widget when the window is resized, however in wormhole-gui it doesn't seem to want to do that either. Switching theme updates it there and I have seen some issue with it looking blurry and broken but I can't reproduce that right now.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code.
2. Notice how the widget gets refreshed only on window resize.

### Screenshots:

![progress](https://user-images.githubusercontent.com/25466657/88479907-e1c0d380-cf52-11ea-8a25-89555f881793.gif)

### Example code:

```go
package main

import (
	"time"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

type extProgress struct {
	widget.ProgressBar
}

func main() {
	a := app.New()
	w := a.NewWindow("Extended progress")

	p := &extProgress{}
	p.ExtendBaseWidget(p)

	p.Max = 10
	p.Min = 0

	go func() {
		for p.Value < p.Max {
			time.Sleep(time.Second)
			p.SetValue(p.Value + 1)
		}
	}()

	w.SetContent(p)
	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.6.18
 - Go version: 1.14.6
 - Fyne version: 1.3.2

**Comment by andydotxyz** [comment]
Fixed on develop - we forgot to call super() in Refresh calls in progressBar code

**Comment by andydotxyz** [comment]
Just patched it onto the release branch as well :)
