### ISSUE TITLE
Copy-paste via keyboard don't work translated keyboard mappings on Windows. 

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#1220]
### Describe the bug:
Copy-paste via keyboard don't work for non-English keyboards on Windows. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo
2. Select input tab from Widgets
3. Copy some text into clipboard
4. Change keyboard to something non-English via Alt-Shift
5. Try to paste
6. Nothing happens

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.13.5
 - Fyne version: current master - https://github.com/fyne-io/fyne/commit/aea152d547caebfc547dbad6ad0abdd35ad24b34

**Comment by andydotxyz** [comment]
Can you be more specific about "non-English"? We have been testing with German and AZERTY keyboards as well

**Comment by Kvaz1r** [comment]
I mean usual qwerty keyboard with non-English language pack, russian in my case.

**Comment by andydotxyz** [comment]
Thanks. The more detail we have the easier it is to track down.

**Comment by andydotxyz** [comment]
I just realised that the title on this may have been missleading.
Your keyboard is a standard english keyboard, but with an OS level re-mapping for Russian, is that correct?

**Comment by Kvaz1r** [comment]
Yes, that's correct.

**Comment by andydotxyz** [comment]
Is it also correct then that for shortcuts you are expecting the English character to be used, for the shortcut, but that when pressed normally the key should use the localised character?

**Comment by andydotxyz** [comment]
In essence it seems like the same issue that Firefox was wrangling with here: https://bugzilla.mozilla.org/show_bug.cgi?id=429180

**Comment by Kvaz1r** [comment]
> Is it also correct then that for shortcuts you are expecting the English character to be used, for the shortcut, but that when pressed normally the key should use the localised character?

Yeah. It's exactly what I expect. It's much easier to use one shortcut for most common operations (like selecting, pasting, copying, searching, ...). 

Yes it's quite popular issue =)

**Comment by andydotxyz** [comment]
Can you confirm what happens in a normal Windows app?
I have been trying to find documentation and many apps seem to recommend either right-click menus or switching layout to use shortcuts. 
Please let me know what normally happens :)

**Comment by Kvaz1r** [comment]
Same behaviour. Shortcuts(copy, paste) doesn't depends on input language in Notepad, Calculator, ...

**Comment by ababo** [comment]
The same problem is consistently reproduced on Mac OS.

**Comment by andydotxyz** [comment]
@ababo could you please provide reproduction steps for MacOS? This would be helpful as I think most of our devs are non-windows

**Comment by andydotxyz** [comment]
Resolved on `develop` branch, thanks @nullst
