### ISSUE TITLE
Slider rendering incorrectly when window maximized

### ISSUE THREAD

**Issue by RajaSrinivasan** [fyne-io/fyne#1223]
### Describe the bug:

The slider widget has displays an indicator at the current value of this slider. When the window size changes as in maximizing the window, the overall length of the slider adjusts correctly but the current value indicator does not.

### To Reproduce:
Steps to reproduce the behaviour:
Add a slider to a window with a small window size - with a default value. E.g. Slider(0.0,1.0) and a default of 0.5
Maximize the window

### Screenshots:

![image](https://user-images.githubusercontent.com/11705140/88640487-066c9680-d08c-11ea-9bc2-1f74ca971488.png)

when maximized:
![image](https://user-images.githubusercontent.com/11705140/88640599-1c7a5700-d08c-11ea-9192-37a4e9794ecb.png)

### Device (please complete the following information):

 - Fyne version: 1.3.2

**Comment by andydotxyz** [comment]
On `release/v1.3.3` branch for testing, should go out this week
