### ISSUE TITLE
Can't change the text of widget.FormItem

### ISSUE THREAD

**Issue by mondy** [fyne-io/fyne#1231]
### Describe the bug:
Can't change the text of widget.FormItem
Which object should I call Refresh on?

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the following code
2. Click on change button
3. 'foo' doesn't replace 'bar'

### Example code:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	application := app.New()
	window := application.NewWindow("")

	item := widget.NewFormItem("foo", widget.NewEntry())
	form := widget.NewForm(item)

	button := widget.NewButton("change", func() {
		item.Text = "bar"
		item.Widget.Refresh()
		form.Refresh()
		window.Content().Refresh()
	})

	window.SetContent(widget.NewVBox(
		button,
		form,
	))

	window.ShowAndRun()
}

```

### Device :
 - OS: Ubuntu 20.04
 - Go version: 1.14.3 linux/amd64
 - Fyne version: v1.3.2

**Comment by andydotxyz** [comment]
it should be `Form.Refresh()` - it looks like we missed it.

**Comment by andydotxyz** [comment]
In `release/v1.3.3` branch for testing, should go out this week.
