### ISSUE TITLE
theme changed the state of two apps at the same time

### ISSUE THREAD

**Issue by godcong** [fyne-io/fyne#1234]
### Describe the bug:

SettingsSchema changed the state of two apps at the same time

### To Reproduce:
When i wrote 2 apps(`APP1`,`APP2`),
using code from https://github.com/fyne-io/fyne/blob/master/cmd/fyne_settings/main.go
I changed light theme to dark theme from `APP1` 
The theme will also change at the same time from `APP2`

It seems to be the problem pointed to by SettingsSchema
This line of code all points to the same place,
I think we need a random value or give him an AppID:
```go
//app->settings.go
func (sc *SettingsSchema) StoragePath() string {
	return filepath.Join(rootConfigDir(), "settings.json")
}
```

### Device (please complete the following information):
 - OS: windows10
 - Version: 19041.388
 - Go version: go version go1.14.4 windows/amd64
 - Fyne version: fyne cli version v1.3.2

**Comment by andydotxyz** [comment]
Fyne_settings is an app for modifying the global fyne config. If you have copied code from it then you are likely manipulating global config - that is what is stored in settings.json. 
To store app specific config use App.Preferences(), this is a read/write API for local app values.

For an app specific theme override you can use App.Settings().SetTheme() which is a runtime override for the current application.

**Comment by godcong** [comment]
Thanks for the answer
