### ISSUE TITLE
dialog filter the dir name start with .

### ISSUE THREAD

**Issue by godcong** [fyne-io/fyne#1235]
### Describe the bug:

In the windows home directory
There are many directories starting with `.`
But dialog will filter it with a blank name 

This is the screenshot about the problems
![dialog](https://user-images.githubusercontent.com/2727298/89398064-3b8b7f80-d743-11ea-8b7a-5626bea8fdf4.png)

The real names are these:
![image](https://user-images.githubusercontent.com/2727298/89399100-9376b600-d744-11ea-8790-9a3304ebdbbb.png)

**Comment by Jacalz** [comment]
The issue template is there for us to more easily be able to help out with solving issues. Thus it should be filled out as much as possible to give more detail into what can be wrong. Please do so and use it in the future 🙂

**Comment by andydotxyz** [comment]
I put a fix that applies to folders and files in 88eb2294 - it's on `release//v1.3.3` branch if you're interested in testing...

**Comment by godcong** [comment]
> I put a fix that applies to folders and files in [88eb229](https://github.com/fyne-io/fyne/commit/88eb22949cd4f5777ed8e1210e85316753077bf0) - it's on `release//v1.3.3` branch if you're interested in testing...
There are some directories generated by `goland` under my screenshot, like this:
.GoLand2019.2
This plan will filter out his ending, and then become like this:
.GoLand2019

**Comment by andydotxyz** [comment]
Merged the two different changes to this bug, issue resolved on `release/v1.3.3` branch ready for release.
directory names now preserved, but filenames fixed. Thanks for the contribution
