### ISSUE TITLE
Wrapping of Entry does not work

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1241]
### Describe the bug:
No matter what you set for Wrapping, it does not change the default behaviour. It even resizes a window with a fixed size.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create an Entry
2. Set Wrapping to either TextTruncate, TextWrapBreak or TextWrapWord
3. See that nothing changes

### Example code:
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("TextWrap")

	entry := widget.NewEntry()
	entry.Text = "sdofihshsdfuisheifusehfiushefsiuefhsefhnsjkdfhseuifshefiushefjdkfng dfgdfg drgdrgjeriogj rit eritjaeritj aei rijeri tjeritj aeoirtjaertkljaer  aer"

	entry.Wrapping = fyne.TextWrapBreak

	w.SetContent(entry)

	w.SetFixedSize(false)
	w.Resize(fyne.Size{
		Width:  640,
		Height: 480,
	})

	w.ShowAndRun()
}
```

### Device:
 - OS: Windows 10
 - Go version: 1.14.6
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
You are asking to wrap a single line entry, there should be an error in the console like:
```
2020/08/10 12:31:42 Fyne error:  Entry cannot wrap single line
```

If you want the Entry to use multiple lines (and enable wrapping) you can set it with:
```go
entry.MultiLine = true
```

Or you could use the `widget.NewMultilineEntry()` constructor function.
