### ISSUE TITLE
Weird behaviour when resizing or minimizing a ScrollContainer containing a VBox

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1245]
### Describe the bug:
When you minimize a Window containing a ScrollContainer the VBox does not expand completely. The same thing happens if you resize the Window so that both the horizontal and vertical scroll bars appear.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a Vbox inside a ScrollContainer
2. Minimize or resize the Window as described above.
3. Resize the Window again.
4. Notice that the VBox does not expand.

### Screenshots:
![vbox_bug](https://user-images.githubusercontent.com/25499721/89869442-a5c57980-dbb4-11ea-92df-1c65fb0d7e24.png)

### Example code:
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("V Box")

	w.SetContent(
		widget.NewScrollContainer(
			widget.NewVBox(
				fyne.NewContainerWithLayout(layout.NewCenterLayout(), widget.NewLabel("VBoxElement 1")),
				fyne.NewContainerWithLayout(layout.NewCenterLayout(), widget.NewLabel("VBoxElement 2")),
				widget.NewButton("Hello World", nil),
				widget.NewEntry(),
			),
		),
	)

	w.Resize(fyne.NewSize(640, 480))

	w.ShowAndRun()
}

```

### Device:
 - OS: Windows 10
 - Go version: 1.14.6
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
Although the exact steps do not reproduce the issue on other platforms I had a suspicion that Windows was resizing the window to 0,0.

On other systems running the same code and resizing the window to less than the content minSize and size up again you can see the same issue.

**Comment by andydotxyz** [comment]
On looking at this I wanted to remove some possible complications... the following smaller code should also show the same outcome:

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("V Box")

	w.SetContent(
		widget.NewScrollContainer(
			fyne.NewContainerWithLayout(layout.NewGridLayout(2),
				widget.NewButton("Hello World", nil),
				widget.NewEntry(),
			),
		),
	)

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Moving this blocker to 1.4 as the team agreed we won't make another 1.3.x so we can focus on 1.4

**Comment by andydotxyz** [comment]
On develop for testing
