### ISSUE TITLE
Process doesn't close even if the main function has finished

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1252]
### Describe the bug:
Sometimes after closing all windows and terminating the app, the process is still open and uses a lot of processing power. This happens more often if the application is more complex. This may be Windows specific, but I noticed this because the debugger in VS Code wouldn't stop debugging even if the program has already finished.

### To Reproduce:
Steps to reproduce the behaviour:
1. Start any fyne application
2. Close it and reopen it a few times until you can see that it is still open.
3. You can see if it is still open by starting the app through the console and then noticing that the program doesn't exit.
4. If you look for the program in the task manager you can see that the application uses a lot of processing power. 

### Example code:
You probably need to start this example a few times, but even this simple application can cause this error.
```go
package main

import "fyne.io/fyne/app"

func main() {
	app.New().NewWindow("Stays Open").ShowAndRun()
}
```

### Device:
 - OS: Windows 10
 - Go version: 1.14.6
 - Fyne version: 1.3.3

**Comment by drognisep** [comment]
Well, basically I don't know what I don't know at this point since I'm pretty new to the framework, and I want to test the assumption that `go run main.go` is the same as `go build && ./myApp.exe` and `fyne package && ./myApp.exe`. It seems like it makes no real difference in this scenario.

This is also an interesting thing to test, because the test app doesn't seem to exhibit the same blocking behavior that we expect with `window.ShowAndRun()`, which makes sense in every situation except this specific one. :P

However, with manual testing, I've pretty well confirmed that this is probably a situation where the master window is not set or Hide() is used inappropriately. I tried to produce a minimal, testable example and `TestBothHide` fails in test because the test app doesn't block, but in reality hiding both windows (with or without `SetMaster`) leaves the app open, which is expected. See the gist below for an example (be nice, I'm a go/fyne newbie).
https://gist.github.com/drognisep/c7117502e2bb4ab1924bc1b618f66684

**Comment by drognisep** [comment]
@PucklaMotzer09 Can you try the example above and let us know if you see anything unexpected? I tried a few scenarios with and without setting the master window, and I'm not seeing anything unusual, but more eyes are always better. :)

**Comment by PucklaMotzer09** [comment]
In the fyne application I am currently working on I am setting the main window as the master and I also got this bug. But what I noticed when trying out the examples I above is that the hang doesn't occur when another window is opened. I also tested this with my application. I opened another window and closed the master window while the other window was still open and the hang never occured.

**Comment by PucklaMotzer09** [comment]
When I am debugging the application inside VS Code and then pause the debugging when the application hangs I get the following call stacks:
+ **internal/painter/svg_cache.go** line 51
+ **app/app.go** line 113
+ **app/settings_desktop.go** line 42
+ **internal/driver/glfw/canvas.go** line 506
+ **internal/painter/svg_cache.go** line 103

I am also getting some other call stacks from the go standard library itself and fsnotify:
+ **github.com/fsnotify/fsnotify/windows.go** line 381

**Comment by andydotxyz** [comment]
There was an issue resolved yesterday on `master` branch which may impact this.
Can you please update your Fyne code and see if you can still replicate this please?

**Comment by PucklaMotzer09** [comment]
Currently I do not have this issue anymore, but I am still using fyne 1.3.3.

**Comment by andydotxyz** [comment]
I don't think any of us can replicate this now, closing

**Comment by rew1nter** [comment]
This issue is still present in 2023 and window.SetMaster() does seem to work

**Comment by andydotxyz** [comment]
None of us were able to replicate the issue @rew1nter if you have new information please do provide it, otherwise there is not much we can do.
Perhaps you have enabled system tray, in which case an app will not exit normally unless you `Quit` it or `SetMaster` is called.

**Comment by antxv** [comment]
This is happening to me about 1% of the time I run my application. I am on Windows 11. It looks like `window.ShowAndRun()` is sometimes not returning, because I added some diagnostic code after that line in main, and it doesn't execute when this problem happens.  Below is what I see with pprof server after closing the only window. If this is hard for you to reproduce, let me know what kind of diagnostic code might help to add to my application.

```
goroutine profile: total 8
1 @ 0x7ff60d658431 0x7ff60d6bbe69 0x7ff60dd43373 0x7ff60d6c24e1
#	0x7ff60d6bbe68	os/signal.signal_recv+0x28	C:/Program Files/Go/src/runtime/sigqueue.go:152
#	0x7ff60dd43372	os/signal.loop+0x12		C:/Program Files/Go/src/os/signal/signal_unix.go:23

1 @ 0x7ff60d67a751 0x7ff60d6b92fd 0x7ff60da518f1 0x7ff60da51725 0x7ff60da4e54b 0x7ff60da67baf 0x7ff60da6865e 0x7ff60d939409 0x7ff60d93b304 0x7ff60d958b8e 0x7ff60d937905 0x7ff60d6c24e1
#	0x7ff60da518f0	runtime/pprof.writeRuntimeProfile+0xb0	C:/Program Files/Go/src/runtime/pprof/pprof.go:796
#	0x7ff60da51724	runtime/pprof.writeGoroutine+0x44	C:/Program Files/Go/src/runtime/pprof/pprof.go:755
#	0x7ff60da4e54a	runtime/pprof.(*Profile).WriteTo+0x14a	C:/Program Files/Go/src/runtime/pprof/pprof.go:377
#	0x7ff60da67bae	net/http/pprof.handler.ServeHTTP+0x52e	C:/Program Files/Go/src/net/http/pprof/pprof.go:272
#	0x7ff60da6865d	net/http/pprof.Index+0xdd		C:/Program Files/Go/src/net/http/pprof/pprof.go:389
#	0x7ff60d939408	net/http.HandlerFunc.ServeHTTP+0x28	C:/Program Files/Go/src/net/http/server.go:2294
#	0x7ff60d93b303	net/http.(*ServeMux).ServeHTTP+0x1c3	C:/Program Files/Go/src/net/http/server.go:2822
#	0x7ff60d958b8d	net/http.serverHandler.ServeHTTP+0x8d	C:/Program Files/Go/src/net/http/server.go:3301
#	0x7ff60d937904	net/http.(*conn).serve+0x624		C:/Program Files/Go/src/net/http/server.go:2102

1 @ 0x7ff60d6b6f1e 0x7ff60d6a3d0e 0x7ff60d6be3d7 0x7ff60d71f612 0x7ff60d74ccbb 0x7ff60d743bfb 0x7ff60d74495b 0x7ff60d805b05 0x7ff60d813c45 0x7ff60d9317d7 0x7ff60d6c24e1
#	0x7ff60d6be3d6	syscall.Syscall9+0x56				C:/Program Files/Go/src/runtime/syscall_windows.go:469
#	0x7ff60d71f611	syscall.WSARecv+0xb1				C:/Program Files/Go/src/syscall/zsyscall_windows.go:1294
#	0x7ff60d74ccba	internal/poll.(*FD).Read.func1+0x3a		C:/Program Files/Go/src/internal/poll/fd_windows.go:439
#	0x7ff60d743bfa	internal/poll.execIO+0x7a			C:/Program Files/Go/src/internal/poll/fd_windows.go:161
#	0x7ff60d74495a	internal/poll.(*FD).Read+0x29a			C:/Program Files/Go/src/internal/poll/fd_windows.go:438
#	0x7ff60d805b04	net.(*netFD).Read+0x24				C:/Program Files/Go/src/net/fd_posix.go:55
#	0x7ff60d813c44	net.(*conn).Read+0x44				C:/Program Files/Go/src/net/net.go:194
#	0x7ff60d9317d6	net/http.(*connReader).backgroundRead+0x36	C:/Program Files/Go/src/net/http/server.go:690

1 @ 0x7ff60d6ba4ee 0x7ff60d652a65 0x7ff60d6525f2 0x7ff60dd73c13 0x7ff60dd73b98 0x7ff60ddaf542 0x7ff60dd78b04 0x7ff60ddd1ae2 0x7ff60d68705d 0x7ff60d6c24e1
#	0x7ff60dd73c12	fyne.io/fyne/v2/internal/app.(*Lifecycle).WaitForEvents+0x112	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/app/lifecycle.go:120
#	0x7ff60dd73b97	fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run+0x97	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/driver.go:166
#	0x7ff60ddaf541	fyne.io/fyne/v2/app.(*fyneApp).Run+0x101			C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/app/app.go:77
#	0x7ff60dd78b03	fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun+0x63	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/window.go:217
#	0x7ff60ddd1ae1	main.main+0x441							d:/go/utterlyeditor/main.go:56
#	0x7ff60d68705c	runtime.main+0x27c						C:/Program Files/Go/src/runtime/proc.go:283

1 @ 0x7ff60d6ba4ee 0x7ff60d652a65 0x7ff60d6525f2 0x7ff60dd74af4 0x7ff60d6c24e1
#	0x7ff60dd74af3	fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).catchTerm+0x73	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/driver_desktop.go:210

1 @ 0x7ff60d6ba4ee 0x7ff60d652a65 0x7ff60d6525f2 0x7ff60dd7513c 0x7ff60dd736dc 0x7ff60d96b07f 0x7ff60dd73676 0x7ff60ddaf5b9 0x7ff60d6c24e1
#	0x7ff60dd7513b	fyne.io/fyne/v2/internal/driver/glfw.runOnMainWithWait+0xfb			C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/loop.go:53
#	0x7ff60dd736db	fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).DoFromGoroutine.func1+0x1b	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/driver.go:70
#	0x7ff60d96b07e	fyne.io/fyne/v2/internal/async.EnsureNotMain+0x3e				C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/async/goroutine.go:29
#	0x7ff60dd73675	fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).DoFromGoroutine+0x55		C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/driver/glfw/driver.go:69
#	0x7ff60ddaf5b8	fyne.io/fyne/v2/internal/app.(*Lifecycle).RunEventQueue+0x58			C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/app/lifecycle.go:111

1 @ 0x7ff60d6ba4ee 0x7ff60d67dc37 0x7ff60d6b9685 0x7ff60d742827 0x7ff60d743c85 0x7ff60d748205 0x7ff60d748536 0x7ff60d8079eb 0x7ff60d81c09b 0x7ff60d81b190 0x7ff60d93cdec 0x7ff60d93c9f1 0x7ff60ddd23f6 0x7ff60ddd23f7 0x7ff60d6c24e1
#	0x7ff60d6b9684	internal/poll.runtime_pollWait+0x84	C:/Program Files/Go/src/runtime/netpoll.go:351
#	0x7ff60d742826	internal/poll.(*pollDesc).wait+0x26	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84
#	0x7ff60d743c84	internal/poll.execIO+0x104		C:/Program Files/Go/src/internal/poll/fd_windows.go:177
#	0x7ff60d748204	internal/poll.(*FD).acceptOne+0x64	C:/Program Files/Go/src/internal/poll/fd_windows.go:946
#	0x7ff60d748535	internal/poll.(*FD).Accept+0x1b5	C:/Program Files/Go/src/internal/poll/fd_windows.go:980
#	0x7ff60d8079ea	net.(*netFD).accept+0x4a		C:/Program Files/Go/src/net/fd_windows.go:182
#	0x7ff60d81c09a	net.(*TCPListener).accept+0x1a		C:/Program Files/Go/src/net/tcpsock_posix.go:159
#	0x7ff60d81b18f	net.(*TCPListener).Accept+0x2f		C:/Program Files/Go/src/net/tcpsock.go:380
#	0x7ff60d93cdeb	net/http.(*Server).Serve+0x30b		C:/Program Files/Go/src/net/http/server.go:3424
#	0x7ff60d93c9f0	net/http.(*Server).ListenAndServe+0x70	C:/Program Files/Go/src/net/http/server.go:3350
#	0x7ff60ddd23f5	net/http.ListenAndServe+0x35		C:/Program Files/Go/src/net/http/server.go:3665
#	0x7ff60ddd23f6	main.main.func1+0x36			d:/go/utterlyeditor/main.go:20

1 @ 0x7ff60d6ba4ee 0x7ff60d6995f7 0x7ff60da1199f 0x7ff60d6c24e1
#	0x7ff60da1199e	fyne.io/fyne/v2/internal/async.(*UnboundedChan[...]).processing+0xde	C:/Users/MY_USERNAME/go/pkg/mod/fyne.io/fyne/v2@v2.7.0/internal/async/chan.go:43
```

**Comment by antxv** [comment]
Also, from the Windows Task Manager, the application is listed as a background process when this happens.

**Comment by andydotxyz** [comment]
Please don't comment on old issues to report a problem. This is 5 years old so the changes are it's a new issue.

Also it looks like you have a web server running which is not exiting - I would look there first. If you still think Fyne has a bug please open a new issue.

**Comment by antxv** [comment]
The web server listed was the pprof server used to get the output. I updated to just use stdout. New issue: https://github.com/fyne-io/fyne/issues/6021.
