### ISSUE TITLE
File Dialog Resize invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Cookie04DE** [fyne-io/fyne#1254]
### Describe the bug:
If you try to resize a file dialog on the develop branch you get this error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x1252b11]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/dialog.(*FileDialog).Resize(0xc000200180, 0x1f4, 0x1f4)
        D:/Programmieren Server/Go/src/fyne.io/fyne/dialog/file.go:321 +0x31
main.main()
        C:/Users/Max/go/src/github.com/Cookie04DE/pqsg/cmd/Mahnungen/main.go:31 +0x1d2
exit status 2
### To Reproduce:
Steps to reproduce the behaviour:
1. Create a window
2. Create new file open dialog
3. Call resize on the dialog
### Example code:
```go
package main

import (
	"fmt"
	"io/ioutil"

	"fyne.io/fyne/storage"

	"fyne.io/fyne/dialog"

	"fyne.io/fyne"

	"fyne.io/fyne/app"
)

var a fyne.App

func main() {
	a = app.New()
	w := a.NewWindow("Choose WinWord.exe")
	winWordOpen := dialog.NewFileOpen(func(readCloser fyne.URIReadCloser, err error) {
		if err != nil {
			Error(err)
			return
		}
		fmt.Println(readCloser.Name())
		readCloser.Close()
	}, w)
	winWordOpen.SetFilter(storage.NewExtensionFileFilter([]string{".exe"}))
	w.SetFixedSize(true)
	w.Resize(fyne.NewSize(500, 500))
	winWordOpen.Resize(fyne.NewSize(500, 500))
	winWordOpen.Show()
	w.ShowAndRun()
}

//Error shows a new window containing the error message
func Error(err error) {
	w := a.NewWindow("")
	w.Resize(fyne.NewSize(100, 100))
	dialog.ShowError(err, w)
	w.Show()
}
```

### Device:
 - OS: Windows 10
 - Go version: 1.15
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
On develop for testing
