### ISSUE TITLE
Android Duplicate Number Entry

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1256]
### Describe the bug:
Tapping on a number in the stock android keyboard results in two numbers being entered into the widget.Entry

### To Reproduce:
Steps to reproduce the behaviour:
1. Install fyne_demo
2. Click on Widgets -> Text
3. Tap Entry and insert numeric info

### Screen capture:
https://gophers.slack.com/archives/CB4QUBXGQ/p1598039652090300 (Github doesn't support uploading mp4)

### Device (please complete the following information):
 - OS: Android
 - Version: 10
 - Go version: go1.15 darwin/amd64
 - Fyne version: 6c9ed1b5aa618a55ef3051aca3f6806bdc74dbf7

**Comment by LuminousLizard** [comment]
I have the same issue on Android 9. I compiled the fyne_demo for android and only numeric input is doubled on all entry forms (standard, only numeric and multiline). I think its not a sensitivity problem because:

1. letters work correct

2. in landscape mode the numbers are insert correct (1 times), but if I rotate then to portrait mode, the previously entered numbers are displayed twice again.

Device:
    OS: Android
    Version: 9
    Go version: go1.15.5 linux/amd64
    Fyne version: b0e67eb

**Comment by andydotxyz** [comment]
Thannks @LuminousLizard which keyboard are you using? (different Android installs seem to ship with different defaults).

**Comment by LuminousLizard** [comment]
I'm using the Lineage OS AOSP keyboard, its shipped with the /e/ (an Lineage fork). I will try some other keyboard apps.

**Comment by LuminousLizard** [comment]
I tested "Simple keyboard" (https://github.com/rkkr/simple-keyboard) which is also based on AOSP and it has the same problems.

The second one is "Hackers Keyboard" (https://github.com/klausw/hackerskeyboard) is also based on AOSP but the issues are a little bit different xD
1. In portrait mode numbers are also inserted twice. But if I insert a number in landscape mode and rotated the phone back in portrait mode, then the numbers remain single (and are not shown doubled like tan with the other keyboards).
2. On this keyboard the remove key works. Not with the "standard Lineage OS AOSP keyboard" and the "simple keyboard". (Would also open an own issue if desired)

**Comment by LuminousLizard** [comment]
GBoard (standard google keyboard) has the same problems.

**Comment by andydotxyz** [comment]
Fix is merged into `release/v1.4.x`, tested with GBoard. If you are able to verify with AOSP that would help thanks @LuminousLizard

**Comment by LuminousLizard** [comment]
I will try it on the next release.
