### ISSUE TITLE
ListBox/ListView widget

### ISSUE THREAD

**Issue by Nv7-GitHub** [fyne-io/fyne#1260]
### Is it possible to construct a solution with the existing API?
I do not think so, without extending widgets. I am trying to do it with a vbox full of buttons within a scroll container and then a label saying what is selected when a button is selected, but with a large list this becomes very slow, especially when resizing the window, and it is also not very user-friendly to have a label saying what is selected, instead of just making an item blue (or something like that). 

### Describe the solution you'd like to see:
Imagine a vertical tabbed item view with text on the right of the icon taking up the whole screen. I want a list of items, hopefully with an Icon, In which you can select a single item with clicking and select multiple with shift-clicking. The multiple selection should be a different widget or there should be a method to disable it in a single one. You should be able to get an array of selected indexes from code by calling (for example)
```go
listItemView.GetSelected()
// [0, 2, 5]
```
A widget like this exists in Android (recycler view/list view) and tkinter (list box).
Here is an image of it in tkinter:
![tkinter listbox](https://i.stack.imgur.com/bwuZu.png)

**Comment by andydotxyz** [comment]
This was already requested in #156 and is being implemented in #1253

**Comment by Nv7-GitHub** [comment]
Thank you! This is very useful. I would suggest putting it in the widget list in the documentation, so that this doesn’t come up again.

**Comment by andydotxyz** [comment]
We will, once it is released :) We don't have a release date for 1.4 yet - I would guess its a month or two away - most major items are well under way.
