### ISSUE TITLE
TODO: Validation error reason should notify user (HelperText?)

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1269]
### Is your feature request related to a problem? Please describe:
The input validation has support for including a reason to the user as to why their input isn't valid. We need to have some good way of showing this to the user.

### Is it possible to construct a solution with the existing API?
Should be possible yes. How we do it is another issue entirely. Do we want HelperText per Material Design or something simpler?

### Describe the solution you'd like to see:
I think that I prefer HelperText, but it needs more thought.

**Comment by andydotxyz** [comment]
Design considerations - how does this fit with form labels etc.
Perhaps redesign of input functionality.

**Comment by andydotxyz** [comment]
On develop for testing :)
