### ISSUE TITLE
Double tapping generates Single Tap and Double Tap events

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1275]
### Describe the bug:
When a canvasobject implements Tappable and DoubleTappable, and the user taps twice, only DoubleTapped should be called, not Tapped.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a canvasobject that implements Tappable and DoubleTappable
2. Tap on canvasobject and see Tap event generated
3. Double tap on canvasobject and see Tap _and_ Double Tap events are generated

### Device (please complete the following information):
 - OS: MacOS
 - Version: Catalina
 - Go version: go1.15 darwin/amd64
 - Fyne version: 25ca356611beaa65ba09268aec218bea9a0aeaf5

**Comment by stuartmscott** [comment]
Please add `"fyne.io/fyne/test".DoubleTap(obj fyne.DoubleTappable)`

**Comment by stuartmscott** [comment]
@okratitan is there any remaining work, or can this be closed?

**Comment by okratitan** [comment]
Close it!

**Comment by stuartmscott** [comment]
Thanks, even though Tree no longer uses double tap, I appreciate the effort you put in to get this working well.
