### ISSUE TITLE
SetOnClosed function does not wait for completion

### ISSUE THREAD

**Issue by zapburp** [fyne-io/fyne#1276]
### Describe the bug:
When try to run exec.Command function from inside SetOnClosed function, It doesn't execute properly. There is no error. It seems like It doesn't reach end of execution. I've tried simple commands with ECHO, but it doesn't work too. And If add   some additional function like fmt.Println("Test") (**that doesn't connect with exec.Command output**) after the exec.Command it will be printed.

### Example code:
```
serviceWindow.SetOnClosed(func() {
disableProxy := `reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyEnable /t REG_DWORD /d 0 /f `
cmd, err := exec.Command("powershell", "/c", disableProxy).Output()
    if err != nil {
    fmt.Println(err)
}
fmt.Println(string(cmd))
})
```

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.14.6
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
Good catch, sorry for this!
