### ISSUE TITLE
File Dialog: toggle hidden files

### ISSUE THREAD

**Issue by kevingentile** [fyne-io/fyne#1278]
### Is your feature request related to a problem? Please describe:

The current file dialog does not give the option to show hidden files.

### Is it possible to construct a solution with the existing API?

Yes, hidden files are [skipped explicitly](https://github.com/fyne-io/fyne/blob/86d26ebe4d97a525aa5cf1b6720186fc76d3b669/dialog/file.go#L196).

### Describe the solution you'd like to see:

A way to toggle hidden files. Ideally a check box with a configurable default value.

**Comment by Jacalz** [comment]
Ideally, we should also support toggling this with a shortcut such as `ctrl + h` on Linux.

**Comment by kevingentile** [comment]
The draft above implements these changes, but the layout of the checkbox still doesn't feel right
<img width="677" alt="Screen Shot 2020-09-03 at 9 54 20 PM" src="https://user-images.githubusercontent.com/10604101/92193437-5599aa00-ee36-11ea-989d-1f4cd95db57a.png">

**Comment by andydotxyz** [comment]
The development of this was continued and landed for 2.0 release
