### ISSUE TITLE
Add low importance (flat) widget.Select as enhacement

### ISSUE THREAD

**Issue by Claudio08** [fyne-io/fyne#1279]
Hope that it will be possible to add an enhacement in "standard widget.Select" as in "standard widget.Button" the following:

type Select struct {
...
	HideShadow bool
...
}

func (b *Select) CreateRenderer() fyne.WidgetRenderer {
...
	shadowLevel := widget.ButtonLevel
	if b.HideShadow {
		shadowLevel = widget.BaseLevel
	}
...
    return &buttonRenderer{widget.NewShadowingRenderer(objects, shadowLevel) ...}
}	

So if "Select" is used in a ToolBar with "HideShadow = true" its appearence have a consistent view with the ToolBar widget.
I think that this addition can interest to other Fyne developers. 

I tried to customize CreateRenderer() Select but without success
due to compiler errors
func (s *mySelect) CreateRenderer() fyne.WidgetRenderer {
...

In the added image you can view two "standard Buttons" (not Toolbar standard buttons)
with "HideShadow = true", inserted in a Toolbar, that fit perfectly in the toolbar design 
and a "standard Select" widget that has not the HideShadow property

![tbs](https://user-images.githubusercontent.com/20372428/92104315-6b30b480-ede1-11ea-9883-211a357b991e.jpg)

**Comment by andydotxyz** [comment]
It might interest you to see that `HideShadow` is going away in PR #1277 - not sure if this affects your feature request

**Comment by Claudio08** [comment]
If i understood well, the "Flat" property will substitute the "HideShadow" but with the same visual effect to obtain a Flat Button. My request is to have the same also for Select. Thanks

**Comment by andydotxyz** [comment]
The API of button changed to `h.Importance = LowImportance` I suppose we can make this aa request for that to be added to select?

**Comment by andydotxyz** [comment]
This was replaced by a more input looking select widget in v2.0.0
