### ISSUE TITLE
Add Get/Set SelectedIndex in widget.Select

### ISSUE THREAD

**Issue by Claudio08** [fyne-io/fyne#1280]
Hope that it will be possible to add as enhancement in "standard widget.Select"
 the possibilty to select or retrive an option also by its index.
 I think that this addition can interest to other Fyne developers. 

 Sometimes is more immediate/usefull check a selected options 
 by its index instead of its text or select an options by its index instead of its text
 
 
 I made a mySelect widget and added this working functions, may be
 that a similar code can be added to standard Select widget:
 
```go
 //Return the position index in Options list of the selected option 
 func (s *mySelect) GetSelectedIndex() int {
	for i, option := range s.Options {
		if s.Selected == option {
            return i
		}
    }
    return -1   //not selected/found
}

//Set the Selected option by its index position in Options list  
func (s *mySelect) SetSelectedIndex(index int) {
    if index >= 0 && index <= len(s.Options) {
		s.SetSelected(s.Options[index])
    }
}
```

**Comment by andydotxyz** [comment]
Thanks. 
If you have written the code already, did you consider patching it into the library with a pull request?

**Comment by Claudio08** [comment]
I'm afraid I don't know how to do it. Better if this is pached by an expert Fyne person that know how to do. Thanks

**Comment by andydotxyz** [comment]
I hope #1287 embodies this code to your satisfaction :)

**Comment by andydotxyz** [comment]
On 'develop' branch for testing before 1.4 release. Thanks for your contribution.
