### ISSUE TITLE
Android compilation fails to install

### ISSUE THREAD

**Issue by Nv7-GitHub** [fyne-io/fyne#1283]
### Describe the bug:
I compiled the fyne demo using ```fyne-cross -targets=android -appID=TestMobile```
This succeeded with no errors. Output:

When I tried using ```adb install ___.apk``` with an AVD emulator, I got this output:
```
Performing Streamed Install
adb: failed to install TestMobile.apk: Failure [INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME: Invalid manifest package: must have at least one '.' separator]
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Navigate into the fyne_demo folder ($GOPATH/src/fyne.io/fyne/cmd/fyne_demo)
2. Run ```fyne-cross -targets=android -appID=TestMobile```
3.  Launch AVD emulator using Android Studio
4. Run adb install and pass an argument as the output APK
5. See error

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.5
 - Go version: 1.15
 - Fyne version: The latest

**Comment by andydotxyz** [comment]
The error message explains why: "Invalid manifest package: must have at least one '.' separator".
Our documentation should specify that the app Id should be a reverse-dns style globally unique identifier, which would satisfy this criteria. I will review the validation code for fyne package utility.

**Comment by Nv7-GitHub** [comment]
Oh, ok. I didn't realize that that was what the appID was for. Thank You, it is working now!
