### ISSUE TITLE
Add option to pick primary color

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1284]
In fyne_settings - a short list of colors that will match the UI aesthetic.

**Comment by andydotxyz** [comment]
On develop for testing :)

**Comment by noerw** [comment]
So how do we use this in an app?

**Comment by andydotxyz** [comment]
This option is in the fyne_settings app (or the File->Settings) menu item in fyne_demo.
It is not settable through an app API as this is a global user setting.
