### ISSUE TITLE
Expose OpenGL from Driver

### ISSUE THREAD

**Issue by niaow** [fyne-io/fyne#129]
For performance and compatibility reasons, as well as to include 3D content, it is sometimes necessary to get direct access to the OpenGL API. I think that we could accomplish this via the following:

1. Expose a concrete type of the Driver implementation, which the user can type-assert.
2. Add a function on the GL driver to allow the user to run code on the main thread.
3. Add a `gl.Render` `fyne.CanvasObject` inside of the driver package.

The `gl.Render` object would be similar to how rasters work, except that the return type of the callback would be different:
```
Render func(width, height int) uint32
```

It would be run on the main thread and return a texture ID, which would change ownership to the GL driver. This would enable drawing 3D content into a `fyne` canvas using render-to-texture.

Additional resources:
1. https://learnopengl.com/Advanced-OpenGL/Framebuffers
2. https://www.opengl-tutorial.org/intermediate-tutorials/tutorial-14-render-to-texture/

**Comment by andydotxyz** [comment]
That would be a nice addition. We would have to figure out how to expose something that is specific to the GL driver.
I don't think we would aim to get this in the upcoming 1.0 so have added "future" tag to it.

**Comment by andydotxyz** [comment]
We should be able to hide the thread complexity by calling the Render func on main internally.

Is there any requirement to expose the ability to run on main outside of render to satisfy this feature?

**Comment by andydotxyz** [comment]
Also if we are moving to GLES we should do that first - will it still be helpful enough to expose an ES Render instead of full OpenGL?

**Comment by andydotxyz** [comment]
We already have 3 different OpenGL implementations and not all future drivers will support it.
To be able to expose a 3D environment will probably require an abstraction that can be backed by OpenGL/Metal etc.
Closing this ticket as exposing OpenGL specifically does not match our goals here.
