### ISSUE TITLE
Add default extension to FileSaveDialog

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1293]
### Is your feature request related to a problem? Please describe:
I want the user to be able to omit the file extension. So that a default one is taken.

### Is it possible to construct a solution with the existing API?
Since FileDialog uses a URIWriteCloser you can't change the name or extension of the file. So it would only be possible to rename the file after the creation of it.

### Describe the solution you'd like to see:
I would like a FileSaveDialog to have a new member (e.g. ```DefaultExtension```). This extension should then be used when the user does not provide an extension. I don't know if this is an issue on mobile platforms, but on desktop it shouldn't be more than just changing the value of a string.

**Comment by andydotxyz** [comment]
I think that it is a little more complex than perhaps it seems on the surface.
Before automatically appending the extension we may need to ask the user if that is OK?

i.e. should "CHANGELOG" be "CHANGELOG.txt"?
Should "this.is.cool" be ignored if the extension is "jpeg" (as it has a .cool extension already).
etc.

We have not yet fully implemented the save dialog on mobile so it's hard to say for sure but I think we will not be able to support it in this manner.

Perhaps we could instead look at the exxtension or mime filter, and if one is set but does not match the file name then ask if it should be changed? This is more likely to be adoptable on mobile - but I do need to look in more detail in this area.

**Comment by andydotxyz** [comment]
This is closely related to a discussion on file extension validation, we will continue the discussion on #1044
