### ISSUE TITLE
Dialog Icon Extends Dialog Bounds

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1296]
### Describe the bug:
If a dialog is taller than it is wide, the icon can get rendered off the side of the dialog.

### Screenshots:
<img width="755" alt="Screen Shot 2020-09-09 at 7 50 23 AM" src="https://user-images.githubusercontent.com/1117080/92614654-22f61400-f271-11ea-9145-1a6972356e5c.png">

### Device (please complete the following information):
 - OS: MacOS
 - Version: Catalina
 - Go version: go1.15 darwin/amd64
 - Fyne version: 08d41f515f6e014cc02b7df1b5dd67694902257d

**Comment by andydotxyz** [comment]
Fixed on develop :)
