### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1297]
### Is your feature request related to a problem? Please describe:
Collection widgets such as List, Table, and Tree should use background colour to indicate cell state such as hovered, or selected, however most widget backgrounds default to an image of uniform colour, which overdraws the collection cell background.

### Is it possible to construct a solution with the existing API?
It is possible to set the theme background colour to transparent, but this is a visual API break.

### Describe the solution you'd like to see:
The default option being no background, with the ability for the dev to set a custom background colour or image.

**Comment by andydotxyz** [comment]
All collections now moved
