### ISSUE TITLE
manual declaration of uses-sdk in AndroidManifest.xml not supported

### ISSUE THREAD

**Issue by raifpy** [fyne-io/fyne#1298]
ı will try to create apk with AndroidManifest.xml (for some android permissions )

When i try , get this error :
  
    manual declaration of uses-sdk in AndroidManifest.xml not supported

My Bash Code:
fyne package -os android/arm -appID "codeksiyon.net.Nettest2t2" .

My Ls :
$ ls
-rw-rw-r-- 1 raif raif  1053 Eyl  9 23:39 AndroidManifest.xml
-rw-rw-r-- 1 raif raif 59032 Eyl  9 22:19 Icon.png
-rw-rw-r-- 1 raif raif   768 Eyl  9 23:07 main.go

My Manifest :
![image](https://user-images.githubusercontent.com/50047969/92652747-0a7c0d00-f2f6-11ea-8265-79242d3db815.png)

So , how can i add my manifest.xml ?

( i just edit fyne 's original manifest.xml  for add internet permission)

**Comment by andydotxyz** [comment]
Can you remove the uses-sdk element?

**Comment by raifpy** [comment]
![image](https://user-images.githubusercontent.com/50047969/92818879-dfb2b700-f3d0-11ea-8be7-8f3eebe61013.png)
My last xml . I disable uses-sdk and android:icon , thanks ...

**Comment by andydotxyz** [comment]
Great. Does that mean that the issue is resolved?

**Comment by raifpy** [comment]
Yes please :) 
Also i upload codes here https://github.com/codeksiyon/mobile/tree/master/golang/netTest 

Maybe someone use
