### ISSUE TITLE
where is input Password dialog？

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne#1304]
### Is your feature request related to a problem? Please describe:
I need to enter the password dialog box.

**Comment by Jacalz** [comment]
Hi there. You can get the password entry by either calling `widget.NewPasswordEntry() ` or by creating a regular entry and setting `entry.password = true`. Here is a link to the documentation: https://developer.fyne.io/api/v1.3/widget/entry.html#func--newpasswordentry

**Comment by andydotxyz** [comment]
It looks to me like the original question was about dialog based input.

If that is the case then there is not currently a password dialog, but you can add the PasswordEntry indicated in @Jacalz reply into a NewCustomConfirm dialog that will acheive the result you are looking for I think.

**Comment by AlbinoGeek** [comment]
@xfengw Code for doing this can be very simple

```golang
	pass := widget.NewPasswordEntry()
	dialog.ShowCustomConfirm("Title", "Confirm", "Cancel", widget.NewForm(
		widget.NewFormItem("Password", pass),
	), func(ok bool) {
		if ok {
			// use pass.Text
		}
	}, w)
```

That being said, there's a `ShowEntryDialog` so... why not have a `ShowPasswordEntryDialog` as well?

**Comment by andydotxyz** [comment]
There is a work in progress FormEntry, which probably supercedes this request so we can avoid having a new dialog for every input type. #1552
