### ISSUE TITLE
Closing a window should provide an event to children

### ISSUE THREAD

**Issue by paulhovey** [fyne-io/fyne#131]
.NET has [FormClosed](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.formclosed?view=netframework-4.7.2) or [HandleDestroyed](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.handledestroyed)

Not that .NET is gospel, but when a widget is running something in the background (infinite progress bar causes this, for example), it may want to stop the goroutine when the widget is destroyed.  Currently `Hide()` does not propagate down through controls, but I'm of the opinion there should be a separate `Closed()` or something akin to it.

**Comment by andydotxyz** [comment]
I agree this is probably needed. It could be used for cache control too ;).
Closed() implies window behaviour - Destroyed() would be reasonable.

Or maybe we should be using the Go idiom and io.Closer?
Also I suspect that this is on Widget not CanvasObject yes?
(A driver can clean up a primitive object itself - but widgets are where it gets complex).

Would putting it in WidgetRender be OK? That would keep it away from the main API.

**Comment by andydotxyz** [comment]
Thinking more about it a widget is "started" through Widget.CreateRenderer() so it would perhaps make sense that it is "stopped" through WidgetRenderer.Destroy()? that keeps it nicely hidden from the main developer-facing API.

**Comment by andydotxyz** [comment]
Adding from slack (not sure if it impacts or not) - either way the lifecycle should be set and documented:

One interesting point for discussion though… widgets / objects are visible by default (this is a good thing) but currently this is done without a “Show()” trigger. I wonder if it’s possible to maintain the same semantic but ensure that the Show() is called as part of the lifecycle. i.e. SetContent() or AddObject could call Show() and that would propagate..?

**Comment by andydotxyz** [comment]
how about this Widget lifecycle:

* constructed (New function or struct init)
* CreateRenderer() - called when the widget is rendered (visible)
(optional:)
* Hide() - will remove it from view
* Show() - re-add the widget using the same renderer
(/optional)
* (Renderer).Destroy() - when the widget is no longer needed in rendering
* garbage collected

In this regard a canvas, and any container widget, will need to clean up child widgets on window close.

**Comment by paulhovey** [comment]
I kinda like the idea of each widget being responsible for it's own cleanup, instead of relying on a parent to clean up children?  Seems like that's asking for leaks.

**Comment by andydotxyz** [comment]
Yes a widget should clean itself up - but we need to trigger that from somewhere. Options seem to be the parent (knowing that the child is going away) or the driver (by monitoring all widget states)
