### ISSUE TITLE
Split TabContainer

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1310]
### Is your feature request related to a problem? Please describe:
There are two main use cases for tabs:
- app navigation
  - limited tabs (3-7)
  - static data
  - bottom or leading placement
- content
  - unlimited tabs
  - dynamic data
  - top, bottom, leading, or trailing placement

### Is it possible to construct a solution with the existing API?
TabContainer is used for both use cases.

### Describe the solution you'd like to see:
Splitting TabContainer into two widgets each focusing on a specific use case:
- NavigationBar
  - displays NavigationItems
  - combination of [Navigation Rail](https://material.io/components/navigation-rail) and [Bottom Navigation](https://material.io/components/bottom-navigation)
  - tab overflow popup
- TabBar
  - displays TabItems
  - implementation of [Tabs](https://material.io/components/tabs)
  - all tabs popup

**Comment by stuartmscott** [comment]
It was proposed in a Slack discussion that Navigation and Tabs would be names

**Comment by stuartmscott** [comment]
Tabs could have in addition to a button which displays all tabs in a dropdown, a new tab button which triggers a callback

**Comment by stuartmscott** [comment]
Relevant prior issue: #1166 

container.Router is a shorter name than container.Navigation

**Comment by andydotxyz** [comment]
Router was an unfortunate name IMHO as it referred to the manner that you could pass a string/URL style component to navigate to a certain screen and they were all "mounted". Given that in some places it is used for that specific meaning it could be misleading.

**Comment by stuartmscott** [comment]
Updates:

1. Names changed to AppTabs, and DocTabs.

2. AppTabs will be for static data such as the pages/sections/areas/features of an app. TabItems within AppTabs will be rendered with icon (if any) above the text (if any), and will appear in the bar running along either the bottom, or leading edge of the container.

3. DocTabs will be for dynamic data such as open files/urls. TabItems within DocTabs will be rendered with icon (if any) leading the text (if any), and will appear in the bar running along any border. Tabs will include a close button if DocTabs.OnTabClosed != nil, where OnTabClosed is a `func(*TabItem) bool` callback provided by the developer. Returning false from this callback will abort the close, else the TabItem is removed from the container.

**Comment by andydotxyz** [comment]
Summary there is great.
However returning bool from an event callback is not easy to work with - the developer will likely want to show a dialog to ask for confirmation, and these show async. Instead why not use the same mechanism we have for the "CloseIntercept" on windows? This would better fit an async model rather than have developers coordinate blocking? (additionally blocking within an event callback is bad ;) ).

**Comment by stuartmscott** [comment]
Ah, I didn't understand the window implementation as well as I thought. After another read through this is how I understand it, please correct me; the design is that there are two callbacks, OnClose which just notifies the developer that the window closed, and OnCloseIntercepted which if not nil will be triggered instead of closing the window - it is up to the dev to ask the user and then maybe call window.Close()

**Comment by andydotxyz** [comment]
That's bang on :)

**Comment by andydotxyz** [comment]
Added the AppTabs rename as that API had just landed so now we're on the right path

**Comment by andydotxyz** [comment]
Moving out to 2.0, although AppTabs is a new API there are elements that will break the existing API.

**Comment by andydotxyz** [comment]
Remvoed deprecated old widget.TabContainer, further work will be in 2.1

**Comment by stuartmscott** [comment]
On develop for testing :)

The only major difference is that #1755 dropped the App Tab limit of 7. This decision can be revisited in future if needs arise.
