### ISSUE TITLE
Common Divider

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1314]
Accordion, List, and Tree all use a canvas.Rectangle of 1dp thickness, and theme.ShadowColor() to represent a divider.

Perhaps theme.DividerThickness() and theme.DividerColor() would be useful additions.

**Comment by andydotxyz** [comment]
Whilst we could add this in 1.4 I'm wondering if there is little benefit so pushing back to the theme review in 2.0

**Comment by stuartmscott** [comment]
@Tilo did a great job on #1438, so moving this to 1.4

**Comment by andydotxyz** [comment]
Just to capture part of a conversation from yesterday:

When using a custom layout you may want to resize a Separator widget. Whilst you widen or heighten this widget you should not do adjust both dimensions at the same time, so the recommended resize calls would be:

```go
separator.Resize(fyne.NewSize(newWidth, separator.MinSize().Height)) // make it wider
separator.Resize(fyne.NewSize(separator.MinSize().Width, newHeight)) // make it taller
```

In this way we can ensure that separators maintain a standard thickness and in 2.0 this will be theme controlled.

**Comment by andydotxyz** [comment]
Done, the theme change in 2.0 will make it configurable.
