### ISSUE TITLE
A Kiosk Mode where Mouse Cursor can be hidden

### ISSUE THREAD

**Issue by pachapman** [fyne-io/fyne#1315]
I am using fyne on a raspberry pi as an overpowered picture frame.  I have built a web service where i can control what is being shown and how through web service calls.  I am using fyne to display the images full-screen.  it works quite well, but the mouse cursor isn't hidden and is a bit of a bother.

It would be nice to have a desktop extension to turn off cursor in full screen. It a more generic option for “kiosk mode” that turns off cursor, sets fullscreen and maybe more.

**Comment by andydotxyz** [comment]
There is an open PR to hide the mouse cursor over certain widgets... #1548 - If you added a custom widget at the top level that requested this then it would solve for most - then any widgets that overlaying with their own widget (like `Entry`) could be extended to specify the invisible cursor again. I think that would solve this without needing to add specific Kiosk mode.

We may have a better solution in the future when touch controls are added to desktop driver, then I would expect the mouse cursor to be hidden unless a mouse device also is activated.
