### ISSUE TITLE
Add horizontal scrolling to ScrollContainer

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#132]
This requires some sort of scroller wheel horizontal or other key combination to signal the scrolling horizontally first

**Comment by asciifaceman** [comment]
note: shouldn't horizontal scrolling always be available if content exceeds visible width space (to support the lack of availability of horizontal scroll hardware)

**Comment by andydotxyz** [comment]
That probably depends on the platform. For desktop that's probably true, but on a touch interface people may expect the tap and drag from the content area instead...

**Comment by asciifaceman** [comment]
This is true, would we have the ability to do so, so desktop isn't left behind?

**Comment by andydotxyz** [comment]
Yes :)

**Comment by andydotxyz** [comment]
Added for testing in develop
