### ISSUE TITLE
hyperlink open blocks main thread

### ISSUE THREAD

**Issue by noerw** [fyne-io/fyne#1332]
### Describe the bug:

On linux, clicking a hyperlink will make the UI unresponsive until the browser is closed again.
This is only if a browser was not running previously.

### To Reproduce:
See above?

### Device (please complete the following information):
 - OS: Arch Linux
 - Go version: 1.15
 - Fyne version: 1.3.2

**Comment by andydotxyz** [comment]
Good catch - sorry about that.
Fixed on develop for testing and 1.4 release soon
