### ISSUE TITLE
Dialog Incorrect Rendering After Screen Rotation

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1334]
### Describe the bug:
When a dialog is displayed and the screen is rotated, the dialog does not update correctly.

### To Reproduce:
Steps to reproduce the behaviour:
1. Install Fyne Demo on Android
2. Open Demo, Go to 'Windows', Open Dialog
3. Rotate device

### Screenshots:
Before:
![screen-before1](https://user-images.githubusercontent.com/1117080/94181347-377f0280-fe54-11ea-9331-8ffc9deb9bcb.png)
After:
![screen-after1](https://user-images.githubusercontent.com/1117080/94181376-406fd400-fe54-11ea-90d4-7c324e652e09.png)

Before:
![screen-before2](https://user-images.githubusercontent.com/1117080/94181398-46fe4b80-fe54-11ea-8e55-ae689ba5125d.png)
After:
![screen-after2](https://user-images.githubusercontent.com/1117080/94181406-4cf42c80-fe54-11ea-8c83-bc900b88097d.png)

### Device (please complete the following information):
 - OS: Android
 - Version: 10
 - Go version: go version go1.15 darwin/amd64
 - Fyne version: fyne cli version v1.3.4-0.20200918231643-0a2fa00d4f28

**Comment by andydotxyz** [comment]
On develop for testing
