### ISSUE TITLE
fyne package: package directory

### ISSUE THREAD

**Issue by brent-soles** [fyne-io/fyne#1336]
### Is your feature request related to a problem? Please describe:

It seems I only have a choice of building/packaging a single binary for either the `-sourceDir` or `-executable` flag, however, I do have a need to package a `.dll` for a library which doesn't statically compile/link on windows.

### Is it possible to construct a solution with the existing API?

Not that I know of.

### Describe the solution you'd like to see:

A flag added to `fyne package` which would allow for packaging a directory with all necessary files.

An example of the process to package would be:
```shell
$> ls /my/project/cmd
main.go

$> GOOS="windows" go build -o /my/project/app-v0.1.1/app.exe /my/project/cmd/main.go

$> cp /my/project/deps/library.dll /my/project/app-v0.1.1

$> ls /my/project/app-v0.1.1
app.exe
library.dll

# Target functionality
$> fyne package -os windows -directory /my/project/app-v0.1.1 -release -icon /my/project/icon.png

$> ls /my/project
app-v0.1.1.exe
app-v0.1.1/
cmd/
dist/
```
Please let me know if there is any ambiguity about this feature request, and I would be happy to clear things up!

**Comment by andydotxyz** [comment]
Fyne package is designed to handle just the application bundle format.
On Windows this format is .exe.
To distribute a file alongside the .exe file will you not need some sort of installer system?

**Comment by brent-soles** [comment]
Closing this, as you are correct!

Thanks for fielding this, and apologies for the late response.

**Comment by andydotxyz** [comment]
Not a problem, glad it's sorted
