### ISSUE TITLE
Entry.Refresh re-trigger Validation

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1337]
### Is your feature request related to a problem? Please describe:
If entry validation depends on external sources, a valid entry could become invalid without being changed eg. in a user sign up flow where username must be unique - if two users try to register the same username, one of them will succeed, making the other invalid.

### Is it possible to construct a solution with the existing API?
It would be possible to clear and refill the entry to re-trigger the validation, however this is not ideal.

### Describe the solution you'd like to see:
Validation status could be determined in entry.Refresh

**Comment by Jacalz** [comment]
Available on develop for testing :)
