### ISSUE TITLE
Chance Background Image

### ISSUE THREAD

**Issue by raifpy** [fyne-io/fyne#1343]
Is there anyway to chance background image ?

**Comment by andydotxyz** [comment]
Change the background image of what?
If you want to configure a background image for a window then set it’s content to a container that uses MaxLayout and set the bgImage and Content to be its child elements.

**Comment by PucklaMotzer09** [comment]
There is really not a way to set a background image. You can't display widgets ontop of other items. You can only do this:
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Background Image")
	w.Resize(fyne.NewSize(360, 360))

	img := canvas.NewImageFromResource(theme.FyneLogo())
	img.FillMode = canvas.ImageFillOriginal

	w.SetContent(
		widget.NewVBox(
			img,
			widget.NewButton("Quit", a.Quit),
		),
	)

	w.ShowAndRun()
}

```

![background_image](https://user-images.githubusercontent.com/25499721/94398137-4b34ac80-0165-11eb-9dd9-058118d4fca7.png)

**Comment by andydotxyz** [comment]
Sorry to contradict you @PucklaMotzer09 but if you use the `MaxLayout` that I suggested above then it will indeed overlay one on top of another, as follows:

```go
package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w.SetContent(fyne.NewContainerWithLayout(layout.NewMaxLayout(),
		canvas.NewImageFromResource(theme.FyneLogo()),
		canvas.NewText("Hello Fyne!", color.White)))

	w.ShowAndRun()
}
```

![Uploading Screenshot 2020-09-28 at 13.17.58.png…]()

**Comment by andydotxyz** [comment]
I'm pretty sure this was answered - if not then please re-open.
