### ISSUE TITLE
Select area is not shown when the menu is opened in the entry

### ISSUE THREAD

**Issue by lusingander** [fyne-io/fyne#1354]
### Describe the bug:

If the menu is opened while area is selected in the entry, the selected area is not shown.
(It is only display and the selection area information does not disappear.)
I think that this is not the expected behavior.

#1318 made to occur by.

### To Reproduce:
Steps to reproduce the behaviour:
1. Select strings in the entry.
2. Right click to open the menu.

### Screenshots:

![201002](https://user-images.githubusercontent.com/31386431/94885898-7f350800-04ac-11eb-93a9-2e4f4c067ee3.gif)

### Device (please complete the following information):
 - OS: macOS
 - Version: 10.15.6
 - Go version: 1.13.4
 - Fyne version: latest develop (a67eb2f)

**Comment by toaster** [comment]
I think the bug here is that the entry does not show the selection unless it has focus.
IMO it should still show the selection but maybe in a somewhat less prominent colour.

**Comment by toaster** [comment]
We decided that it is wrong to call `FocusLost` on a focus manager switch.
I’ve got a fix in queue.

**Comment by andydotxyz** [comment]
Resolved on the develop branch (where it was noticed)
