### ISSUE TITLE
Select with many options is unable to tap the first and last option on Mobile

### ISSUE THREAD

**Issue by sorainnosia** [fyne-io/fyne#1358]
### Describe the bug:
In Android, when a Select widget is tap a popup will appear listing all the options. If the options is too many, the first option will be obscure by the Android top Drawer status bar text. Because Android renders its status (WIFI, signal etc) on top of an app area, while the first option of Select item is then covered by the status drawer.

This happen to the last option too which is covered by soft button, Home, Back, etc.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a new Select widget
2. Populate it with 100 items
3. Run the app
4. Click the widget to popup the list of items
5. First and Last option will be difficult to get tap event because of being obscured

### Screenshots:
No screenshot

### Example code:
No example code

### Device (please complete the following information):
 - OS: Android
 - Version: 10
 - Go version: 1.13
 - Fyne version: 1.2

**Comment by andydotxyz** [comment]
Good catch.

The generic issue here is “overlay not respecting screen insets” I think...

**Comment by sorainnosia** [comment]
Actually one more thing I want to add.

Android and iOS does drop show a context drop down when a Select object is click, but instead it pops up a full screen window with list of options.

Fyne in android behaves in desktop way that the list is shown as a context menu. I think Fyne has to re-think about its vision on how could Fyne be a cross platform toolkit.

Question like :
1. Select widget. Will Fyne keep current behavior which is desktop like on mobile?
2. Will Fyne introduce widget like bootstrap col-sm-12 col-md-6 which the widget behaves differently when the screen is mobile?
3. Fyne current Box, Border, Grid concept is more similar to desktop UI programming. Will Fyne introduce mobile layout? Honestly I havent encountered a use case which Fyne's layout cant fit in, its just the concept is leaning towards desktop development.

**Comment by andydotxyz** [comment]
These are good thoughts indeed. You're quite right that there is more adapting to mobile that we should be doing.
The layouts that exist are the building blocks and we will be adding higher level components that adapt better.
The first, for example, was AdaptiveGridLayout which changes based on orientation. Later will be a navigation style root container that shows fullscreen nav list on mobile and sidebar on desktop (this sort of thing is where we are heading).

Each time you see something that is not adapting well please do open a ticket and we will slowly get all of these working well. It's quite straight forward as the code is all there - for example see how a tab conatiner places the tabs on the short edge of mobile apps whereas desktop app developer has full control. More of these things will help the apps to feel more "at home" on mobile and/or touch based devices.

**Comment by andydotxyz** [comment]
There is a previous request for full-screen dialog but this is another example of where we should probably automatically adapt for apps rather than require developers to make such choices. #1205

**Comment by andydotxyz** [comment]
Resolved on develop for testing :)
