### ISSUE TITLE
fyne package command for packaging Android is signing the apk without using developer's cert

### ISSUE THREAD

**Issue by sorainnosia** [fyne-io/fyne#1359]
### Describe the bug:
fyne package command that creates apk is signing the apk with an unknown keystore and password. When I use jarsigner to sign my personal certificate and upload to Play Store, it complains that there are more than 1 cert is present.

Same certificate must be used during upgrading of the apk to a new version in Play store, and certificate ensure the originality of the creator of the apk. If fyne uses their own cert, the author of all fyne app will automatically be fyne instead of the individual developer

### To Reproduce:
fyne package -os android -appID com.johnkenedy.fourdanalysis -name "4D Analysis" -icon notes.png

above will produce an apk which is already sign. Fyne should provide options to include developer personal keystore and input password so that the apk versionCode can be upgraded later on in Play Console and make sure the app is owned by the developer.

### Screenshots:
No Screenshot

### Example code:
No Code

### Device (please complete the following information):
 - OS: Windows Machine to generate APK, APK is tested on Play Console
 - Version: 10
 - Go version: 1.13
 - Fyne version: 1.2

**Comment by andydotxyz** [comment]
Yes we need to fix some of the release process - currently package does some things that are really just suitable for development. We started with -release parameter, but the real solution is a proper release flow, proposed in #86 and targeting 1.4 so we can wrap this in.

**Comment by sorainnosia** [comment]
When will you release 1.4? And also I need fyne to release the allowing of minSdkVersion changes because play store now only allow API 29 above while fyne uses API 28.

I am planning to release my app soon but because of these two issues my app get delay

**Comment by andydotxyz** [comment]
According to Google the 29 requirement does not come into effect until November. 1.4 will be released before then.

From their announcement:
> This is a reminder that starting November 2, 2020, updates to apps and games on Google Play will be required to target Android 10 (API level 29) or higher.

The certification issue is a little more complex, before the release you can drop in your own certificate to `cmd/fyne/interrnal/mobile/build_androidapp.go` and then re-build the fyne tool. Not ideal I know, but if the release is holding you up it might help.

**Comment by sorainnosia** [comment]
> According to Google the 29 requirement does not come into effect until November. 1.4 will be released before then.
> 
> From their announcement:
> 
> > This is a reminder that starting November 2, 2020, updates to apps and games on Google Play will be required to target Android 10 (API level 29) or higher.
> 
> The certification issue is a little more complex, before the release you can drop in your own certificate to `cmd/fyne/interrnal/mobile/build_androidapp.go` and then re-build the fyne tool. Not ideal I know, but if the release is holding you up it might help.

how to pass in the keystore password? must extract private key from keystore file?

**Comment by andydotxyz** [comment]
Apologies I cannot remember the details! I think that you use the password to extract the certificate from the file.
Then use that certificate to add it to the `build_androidapp.go` file and rebuild.

Apologies for the lack of help here - we will be working on improving the release tools in the next few weeks before 1.4 release. There will be a much better solution in place shortly.
This page might help https://docs.oracle.com/javase/tutorial/security/toolsign/step5.html.

**Comment by andydotxyz** [comment]
On `develop` for testing :).

Use `fyne release -keyStore <path>`
