### ISSUE TITLE
SelectEntry Options cannot be set after creation

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1362]
### Describe the bug:
Options set through constructor works, but passing empty slice to constructor and calling SetOptions later does not update SelectEntry.

It also appears that passing empty slice to constructor causes the bottom line to not get rendered

**Comment by andydotxyz** [comment]
Looks like a glitch in Refresh, this works in the regular Select I think

**Comment by andydotxyz** [comment]
The test `TestSelectEntry_SetOptions` verifies that this does work.
Can you please provide a code sample that is not working?

**Comment by andydotxyz** [comment]
> It also appears that passing empty slice to constructor causes the bottom line to not get rendered

I can't replicate the bottom line issue but I do see a problem where the dropdown icon isn't rendered so I can fix that

**Comment by stuartmscott** [comment]
> The test TestSelectEntry_SetOptions verifies that this does work.

No it doesn't because it passes a non-empty slice to the constructor:
```go
e := widget.NewSelectEntry([]string{"A", "B", "C"})
```

> Can you please provide a code sample that is not working?

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	"log"
	"time"
)

func main() {
	a := app.New()
	w := a.NewWindow("Select Entry")
	s := widget.NewSelectEntry(nil)
	// or s := widget.NewSelectEntry([]string{})
	go func() {
		time.Sleep(5 * time.Second)
		s.SetOptions([]string{"a", "b", "c"})
		log.Println("Options Updated")
	}()
	w.SetContent(s)
	w.Resize(fyne.NewSize(300, 200))
	w.ShowAndRun()
}

```

Still trying to find a repo case for the bottom line dissappearing. I'm seeing it in some image tests I have for a Sign In dialog, but not sure what is unique about it. In the ss below "Alias" is the placeholder of a SelectEntry, but the bottom line is missing;
![sign_in](https://user-images.githubusercontent.com/1117080/95368812-79b03700-088b-11eb-8176-2ec8008ccf19.png)

**Comment by andydotxyz** [comment]
So, it did test that they can be set after creation.
But not if they were empty first. I see what you mean.
The fix is in the PR mentioned

**Comment by andydotxyz** [comment]
Landed. Does that resolve this ticket or do we still need to look into the underline?

**Comment by stuartmscott** [comment]
I'll sync and try again, but either way to should probably be a separate ticket
