### ISSUE TITLE
Dialog shadow does not resize after Refresh

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1370]
### Describe the bug:
If the contents of a dialog changes, the shadow is not resized

### Screenshots:
https://user-images.githubusercontent.com/1117080/95370444-9ea5a980-088d-11eb-9609-f3943a53c305.png

**Comment by Jacalz** [comment]
I have been seeing the same thing, but have not been able to replicate the issue in a reliable way.

**Comment by AlbinoGeek** [comment]
@Jacalz The code in #1545 can replicate this issue reliably.

**Comment by andydotxyz** [comment]
fixed on release branch
