### ISSUE TITLE
Fyne-demo bugs (Windows 10)

### ISSUE THREAD

**Issue by vmcrash** [fyne-io/fyne#1372]
### Describe the bug:
I'm trying fyne_demo on Windows 10 built with TDM-GCC-64.

- When starting fyne_demo.exe 2 windows open, a console window and the Fyne Demo window. There shouldn't start a console.
- The font is larger than the Windows default font.
- Clicking (and holding a menu) does nothing. With Win32 API this shows the menu. It is normal to click on, e.g. File, hold the mouse and release it over the menu item, e.g. Quit. This does not work in the Fyne Demo.
- Pressing Esc while a menu is shown should close it.
- Pressing F10 should open the left most menu.
- Mnemonics don't work, e.g. Alt+F for the File menu.
- No keyboard navigation is possible, except of in Widgets > Input or Widgets > Form.
- Even in Widgets > Input it is not possible to focus any radio button.
- In Widgets > Form the highlighted Submit button is neither triggered by pressing Enter nor Ctrl+Enter.
- Widgets > Buttons: it is necessary to change the focussed button when pressing Tab or Shift+Tab.
- In Containers > Scroll nothing happens when pressing Cursor Up or Down.
- In section Windows not dialog can be handled by Esc or Enter or Alt+F4.

**Comment by andydotxyz** [comment]
I'll try to respond to these. Those things that are deemed to be bugs should probably broken to individual issues or people will really struggle to work against it.

> When starting fyne_demo.exe 2 windows open, a console window and the Fyne Demo window. There shouldn't start a console.

This is a windows issue, if you use the "fyne package" tool it will resolve the issue. You also can apply the appropriate parameters as per the README: https://github.com/fyne-io/fyne/blob/master/README.md

> The font is larger than the Windows default font.

Can you provide a screenshot of this?

> Clicking (and holding a menu) does nothing.

We have opted for the click+hover version of the same interaction. It is more consistent across platforms, but we could probably support both

> Pressing Esc while a menu is shown should close it.

Thanks, good idea

> Pressing F10 should open the left most menu.

This is brand new to me, I have not heard of equivalent in macOS but you could open a feature request

> Mnemonics don't work, e.g. Alt+F for the File menu

Indeed, that is not yet implemented (#682 is tracking, we have a Shortcuts API that will be added to Menu)

> No keyboard navigation is possible

See #1074 

> Input it is not possible to focus any radio button

There is an open change, it will be in 1.4 this month

> Form highlighted Submit button is neither triggered by pressing Enter nor Ctrl+Enter.

True, this is surprisingly complicated, though Form is being improved in this release

> Buttons: it is necessary to change the focussed button when pressing Tab

see #1074 again

> Scroll nothing happens when pressing Cursor Up or Down

As far as I know that is not something that should be added universally as many scroll containers want to use Up / Down for other things (i.e. multiline text input).
Developers can easily add this feature to their apps if it's desired.

> In section Windows not dialog can be handled by Esc or Enter or Alt+F4.

I don't fully understand this point, but I think it is a combination of items above.

---

Thanks for your feedback, I hope there are aspects of the project that you found helpful.
Most items above are already in progress, a couple that remain can be tracked through GitHub, but perhaps we can open an issue per ticket? Monster items like this are pretty much impossible for a developer to work against.

**Comment by vmcrash** [comment]
OK, I wait for the progress of the other issues and may come back later to add further issues separating this one into smaller. But first it makes sense to wait until the existing ones got implemented.

**Comment by Jacalz** [comment]
I think it is best to close this as there are a lot of points and we should ideally try to keep each issue specific to one task. On top of that, it also seems to me like many of the noted points have been solved since this issue was opened.

If there are any points you think have not been resolved, please open new issues for each improvement suggestion.
