### ISSUE TITLE
app terminates when screensaver kicks in - Mac OSX

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#138]
- Run a fyne app

- Lock your screen

- When you log back in, you fyne app is terminated ?

**Comment by andydotxyz** [comment]
Is this on a particular desktop / window manager?
Is there any error reported at all?
I can't seem to replicate on my setup.

**Comment by steveoc64** [comment]
Will dig deeper when I get some mac time.  IIRC, it reports that the app received a kill signal, which is pretty weird.

Havent seen the issue on linux / KDE.

Then again, it could be a side effect of something else happening on my mac, which is admittedly under heavy load most of the day.  Will keep an eye on it.

**Comment by steveoc64** [comment]
Confirmed behaviour - turn on screensaver, go away for 10-15 mins, app has exited when you get back.  

Locking the screen, and immediately unlocking it == no problem.

No idea where the issue is.  Ill try running the app under delv and see what happens on sleep.

**Comment by andydotxyz** [comment]
Perhaps this is related to a memory leak - and the period of time?
If I trigger the screensaver manually and then dismiss it there is no problem.

I suspect this is the OS triggering a "release some memory" call which we are not responding to, so getting culled...

**Comment by steveoc64** [comment]
Its probably not a resource leak - Im memdebugging the app, and its not growing, according to my stats.

Meanwhile, VSCode chews up >64TB of memory and spins out all the cores on the mac, and it still gets a free pass ;)   Gotta love those electron apps.

I suspect it might be make of all things - I just had the thought this morning that Ive only been running the app from inside VSCode, invoked from `make run` in the integrated terminal ... and the "application killed" result is being returned from make.  Hoping thats it !!   Will try again in a few hours. Be good to close the issue without the need for any work.

**Comment by steveoc64** [comment]
Finally got around to testing this properly.

Ran examples - spin up a dozen pongs and lifes, then screensave it and .... go make a cup of tea.

on return - all good.
Repeat under delv - all good
Repeat under make - all good
Repeat under VSCode - all good

Repeat tests above with putting the mac to sleep - all good.

Im assuming that there is some other issue that was side effecting this. Maybe the version I was running when it was terminating had an actual bug that it hit and took out the app.

Either way, closing the issue now, its not something wrong with fyne, no work needed.
