### ISSUE TITLE
cmd/fyne: Refactoring packaging to use text/template for files

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1380]
### Is your feature request related to a problem? Please describe:
The current packaging code is quite large and all the files such as .desktop and makefiles are strings in code which makes it harder to change them in the future.

### Is it possible to construct a solution with the existing API?

Should be quite simple to fix :)

### Describe the solution you'd like to see:

My suggestion is to use `text/template` to move templates out to separate files and make it easier to maintain the code in the future.

**Comment by andydotxyz** [comment]
Pretty sure this is resolved
