### ISSUE TITLE
Dialog not returning to requested size

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1382]
A dialog with size set by Resize, but shrunk due to window resize, does not return to set size when window resizes.

https://slack-files.com/T029RQSE6-F01CAMDFG3U-5b40a55576

Recommended resolution is to save the size given to dialog.Resize, and regrow up to that size if window permits

**Comment by andydotxyz** [comment]
Fixed on `develop` and `release/v2.0.x`
