### ISSUE TITLE
How do I refresh the widget outside of the function that defines it?

### ISSUE THREAD

**Issue by yanyuxuanz** [fyne-io/fyne#1383]
How do I modify the widget's text content when I change this value outside this defined function?in other words,How do I refresh the widget outside of the function that defines it？thanks for your reply. I'm new to FYne and I don't know how to use it as well

**Comment by Jacalz** [comment]
Hi there. Most widgets that have some sort of text parameters should have a method that you can call on the variable that you created.

I don’t know if you are using an entry, label or something else, but here is an example for how you would do for label:
```go
label := widget.NewLabel(“Initial text”)
label.SetText(“Updated text”)
```

I would like to suggest that you could have a look at https://developer.fyne.io/ for a lot of helpful examples, documentation and other help. I hope that this comment answers your question :)

**Comment by yanyuxuanz** [comment]
just like document's Two-way binding,when changes one value and the same time  anthoer value will be changed automatically.

**Comment by Jacalz** [comment]
Hmm, bindings between widgets are set to be included in the 2.0 release. Right now you could for example do something along these lines:
```go
label := widget.NewLabel(“text”)
entry := widget.NewEntry()
entry.OnChanged = func(text string) {
    label.SetText(text)
}
```

**Comment by yanyuxuanz** [comment]
Can I according to the widget's titlie and then get that widget's object ,if get it,I can change the widget's value outside the widget's defined function..

**Comment by Jacalz** [comment]
I am not quite sure I follow, sorry. What specific widget are you referring to?

**Comment by andydotxyz** [comment]
You can perform any widget manipulation functions outside of the function creating them, yes.
You just need to store a reference to that widget outside of the scope of your function so that you can call it’s functions later. For example by storing them in a user type or in a file’s var declarations.

**Comment by andydotxyz** [comment]
Maybe watching this tutorial would help: https://m.youtube.com/watch?v=vSDtHyBvnXE&t=7s

**Comment by andydotxyz** [comment]
> Can I according to the widget's titlie and then get that widget's object ,if get it,I can change the widget's value outside the widget's defined function..

The toolkit does not provide any way to look up widgets based on some name or ID.
We prefer statically typed variables so you don't get runtime issues when the widget fails.
Storing a reference to the object created is normally the correct way forward.

**Comment by yanyuxuanz** [comment]
OK.thank you very much. I got it..

**Comment by Anmol-shrivastav** [comment]
> Maybe watching this tutorial would help: https://m.youtube.com/watch?v=vSDtHyBvnXE&t=7s

You Saved my life.
