### ISSUE TITLE
Runtime Release Flag

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1387]
### Is your feature request related to a problem? Please describe:
An app built in development mode is different to an app built in release mode that will be published to the general public. Often time behaviour is changed and/or different APIs are accessed. Ideally an app could lookup at runtime whether it is a development version, or release version.

### Is it possible to construct a solution with the existing API?
not that I can see

### Describe the solution you'd like to see:
The addition of `App.Settings.Release bool` which defaults to false for development builds, but is set to true by the future `fyne release` command.

**Comment by andydotxyz** [comment]
I was thinking more about this and have the following solution proposal:

```go
type BuildType int

const (
	StandardBuild BuildType = iota
	DebugBuild
	TestBuild
	ReleaseBuild
)
```

This way testApp.BuildType() will always return TestBuild.

The fyne "release" command (still in development) will cause the default implementation to change from returning StandardBuild to ReleaseBuild. I figure that at some point we will want debug info so that's in there too.

**Comment by stuartmscott** [comment]
The overall idea sounds good to me.

Though I'm not sure we need `StandardBuild` and `TestBuild` (tests should use `DebugBuild`).

The 0-value would be `DebugBuild`

```go
type BuildType int

const (
	DebugBuild BuildType = iota
	ReleaseBuild
)
```

The `fyne release` command would use a build tag and there would be two files;

```go
// +build !release

func (a *App) BuildType() BuildType {
    return DebugBuild
}
```

```go
// +build release

func (a *App) BuildType() BuildType {
    return ReleaseBuild
}
```

**Comment by andydotxyz** [comment]
Maybe I should add some more background context so we can gather all the previous discussions in this area.

* Debug mode has been requested to include things like outlining graphical components, printing layout sizing info etc
* Test mode is when our test suite is running the application in a non-visible way, but can still do image comparisons so needs to render in a theme-appropriate manner
* Release mode is where we perform additional certification and/or environment variable / flag tweaking for release.

According to the above the debug mode cannot be on by default, whichh is why it is not `0` in my proposal above.
Following the logic of all the above we need something that is neither debug nor test nor release, hence `StandardBuild` which was tough to name but I could not think of better - `DefaultBuild` was the only other that came to mind but we have previously discussed that, for example, `DefaultButton` usage has led to confusion in the past.

Thanks for the code snippet, as you might imagine I do have a working example of this that I progressed whilst looking for feedback and tags to play a part. "fyne release" command is up and running sans-certificates but I wanted to discuss the API before opening a PR.

**Comment by stuartmscott** [comment]
`StandardBuild` as the default sounds good if `DebugBuild` will include things like layout bounds, logging debug info, et al.

**Comment by andydotxyz** [comment]
From Slack:

> Re: #1387 is TestBuild necessary? Could leads to issues which only occur in non-test scenarios (eg. VW emissions scandal), I think it might be better to not let the code know it is being tested.

I don't have any code that shows it's necessity, if preferred we can leave that out for now.
Given the enum strategy instead of a `bool` we can extend it later if this becomes are requirement.

**Comment by andydotxyz** [comment]
On develop for  testing
