### ISSUE TITLE
Unable to overwrite file with FileSaveDialog

### ISSUE THREAD

**Issue by PucklaMotzer09** [fyne-io/fyne#1396]
### Describe the bug:
When trying to overwrite any file using a ```dialog.FileSave``` an error message saying ```Files cannot replace a directory, check the file name and try again``` is displayed. This has probably to do with #1379.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a new ```dialog.FileSave```
2. Click on any existing file
3. Click Save
4. See the error message

### Example code:
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/dialog"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("DialogTest")

	w.SetContent(widget.NewButton("Dialog", func() {
		dialog.ShowFileSave(func(writer fyne.URIWriteCloser, err error) {
			if writer == nil {
				return
			}
			if err != nil {
				dialog.ShowError(err, w)
				return
			}
			defer writer.Close()

			dialog.ShowInformation("File", writer.URI().String(), w)
		}, w)
	}))

	w.ShowAndRun()
	a.Quit()
}
```

### Device (please complete the following information):
 - OS: Windows 10
 - Go version: 1.15.2
 - Fyne version: v1.3.4-0.20201011201116-228c0cf7fcac

**Comment by andydotxyz** [comment]
Thanks for the fix @PucklaMotzer09 that's on `develop` now
