### ISSUE TITLE
error on go get

### ISSUE THREAD

**Issue by jkmpariab** [fyne-io/fyne#140]
hello
i getting this error when attempting to go get -u github.com/fyne-io/fyne

package github.com/fyne-io/fyne: code in directory /home/abed/go/src/github.com/fyne-io/fyne expects import "fyne.io/fyne"

libgl1-mesa-dev and xorg-dev are also installed
system: ubuntu 18.04
go1.12

**Comment by andydotxyz** [comment]
We changed import path - you need to:

    go get -u fyne.io/fyne

Where did you see the old import used?

**Comment by jkmpariab** [comment]
ok. that works
thank you
