### ISSUE TITLE
CheckGroup widget so we can support "Mutliple select" and "Required" validation

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1406]
With the addition of validations and the required state to Form it became clear that we don't really support a multiple selection. If we had a CheckGroup widget this could handle []string as the input value and also []string as the selected value.

In addition to this we could support Form.Required so that a CheckGroup multiple select would require at least one of them to be selected - this is the part that is not currently possible without a custom widget.

Like the Radio(Group) I think we should probably support Horizontal/Vertical layouts...

**Comment by stuartmscott** [comment]
Would this also support "parent and child checkboxes" aka "sub-selections"? https://material.io/components/selection-controls#checkboxes

**Comment by andydotxyz** [comment]
That was not in my mind @stuartmscott.
The proposal here is simply to group existing Check Widgets in a way that allows the new form controls to validate only when an item in a required set (at-least-one selection style) is checked.

**Comment by andydotxyz** [comment]
Relates to #1386.
Now we have RadioGroup this concept works better :)

**Comment by andydotxyz** [comment]
On `develop` for testing

**Comment by ronangithub** [comment]
my checks'length is big, , can we have a more flexible layout for checkGroup,like i have 12 check, mabey 3line 4col.

**Comment by andydotxyz** [comment]
Please don't raise new requests on closed issues.
