### ISSUE TITLE
Unable to run my code

### ISSUE THREAD

**Issue by DanDovhun** [fyne-io/fyne#1411]
I've been trying to run my program but whenever I try to run I get this message:

`
 fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw
cgo-builtin-prolog:1: stddef.h: No such file or directory
 fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
cgo-builtin-prolog:1: stddef.h: No such file or directory
C:\\Users\\myUsername\\go\\src\\fyne.io\\fyne\\vendor\\github.com\\go-gl\\gl\\v3.2-core\\gl\\conversions.go:12: stdlib.h: No such file or directory
`

I'm on Windows 10 running go 1.15

**Comment by andydotxyz** [comment]
Have you set up a C compiler as described at https://developer.fyne.io/started/?
It’s not ideal, but it allows the graphics access that makes this work across all platforms with the same application code.

**Comment by DanDovhun** [comment]
@andydotxyz yes. I installed TDM-GCC and still get the error

**Comment by Kvaz1r** [comment]
Does the C compiler seen in Path? Try run `gcc -v` from console.

**Comment by DanDovhun** [comment]
@Kvaz1r it's in the path

**Comment by andydotxyz** [comment]
Can you please reply to @Kvaz1r request for the gcc info?

> Try run gcc -v from console.

**Comment by andydotxyz** [comment]
It would also be really helpful if you could share the command you are running that is failing, in case it lends a hint to what is going wrong.

**Comment by andydotxyz** [comment]
Just pinging this thread - we can't help further without more information @DanDovhun.

**Comment by changkun** [comment]
I suspect this is an issue of cgo, which require C compiler to be set properly, see #911.

Close due to lack of response. Please speak out if the close is not a desired action.
