### ISSUE TITLE
Hidden files are shown by default in file dialog

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1421]
### Describe the bug:
On latest develop, all hidden files seem to be picked up and shown in the file dialog.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open a file dialog in a folder containing hidden files

### Screenshots:

![image](https://user-images.githubusercontent.com/25466657/96350672-23c36680-10b7-11eb-937b-07e05c381964.png)

### Example code:
File dialog in fyne_demo should be sufficient.

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.6.19
 - Go version: 1.15.3
 - Fyne version: ac86da0d068f and d2d475004db31edcae99d4554d40ca28d4f14611

**Comment by andydotxyz** [comment]
Wow, that was a bit of a mistake! This file dialog URI / favourites merge has not gone well.
Fixed
