### ISSUE TITLE
FileDilog can't find Downloads directory

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1423]
### Describe the bug:
On latest develop, my downloads folder is never picked up any more and results in the following error:
```
2020/10/17 20:29:19 Fyne error:  Getting favorite locations
2020/10/17 20:29:19   Cause: this computer does not have a DOWNLOADS folder
2020/10/17 20:29:19   At: /home/jacob/go/pkg/mod/fyne.io/fyne@v1.3.4-0.20201014180309-ac86da0d068f/dialog/file.go:173
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Open a file dialog
2. Notice that no downloads favourite is shown

### Screenshots:

![image](https://user-images.githubusercontent.com/25466657/96350905-591c8400-10b8-11eb-987d-09a36511b6f8.png)

### Example code:
File dialog in fyne_demo should be sufficient.

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.6.19
 - Go version: 1.15.3
 - Fyne version: ac86da0d068f and d2d475004db31edcae99d4554d40ca28d4f14611

**Comment by andydotxyz** [comment]
Do you have ~/Downloads, or is it a custom value set through XDG config somewhere?

**Comment by Jacalz** [comment]
I do have `~/Downloads` and it did all work before the changes to favourites handling was merged.

**Comment by andydotxyz** [comment]
OK that was embarassing.
1 commit at a time the PR made sense but looking at it fresh that was a mess.
I have tidied the code and found that "oh no the config file is missing" was being interpreted as an error and the errors were blocking fallbacks for some reason.

I've tested with and without `xdg-user-dirs` and both seem to work now.
Sorry.

**Comment by Jacalz** [comment]
Thanks for the fix. The change does appear to make the Downloads folder appear, but I am still getting the error:
```
2020/10/18 10:01:32 Fyne error:  Getting favorite locations
2020/10/18 10:01:32   Cause: this computer does not define a DOWNLOADS folder
2020/10/18 10:01:32   At: /home/jacob/go/pkg/mod/fyne.io/fyne@v1.3.4-0.20201017215228-4501db7e9a55/dialog/file.go:173
```

**Comment by andydotxyz** [comment]
Hmm, I suspect some assumptions went into this code. Can you help by providing the result of the following please?

`which xdg-user-dirs`
`cat ~/.config/user-dirs.dirs`

**Comment by Jacalz** [comment]
Sure. Here are the results:
```
jacob@pacman ~/go/src/github.com/Jacalz/sparta $ which xdg-user-dirs
which: no xdg-user-dirs in (/sbin:/bin:/usr/sbin:/usr/bin:/usr/share/avr/bin:/snap/bin)
jacob@pacman ~/go/src/github.com/Jacalz/sparta $ cat ~/.config/user-dirs.dirs
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
```

**Comment by andydotxyz** [comment]
Thanks so much. It would appear that DOWNLOADS should have been DOWNLOAD. Fixed on `develop`
