### ISSUE TITLE
Windows flags my application as a Trojan

### ISSUE THREAD

**Issue by alshdavid** [fyne-io/fyne#1433]
### Describe the bug:
Windows Defender believes my executable is a Trojan

![image](https://user-images.githubusercontent.com/12656294/96681090-65f3ed00-13c2-11eb-817a-ececce1cc085.png)

### To Reproduce:
Steps to reproduce the behaviour:
Using the hello world compiled using `fyne-cross` on Ubuntu 20.04

### Example code:
Using the demo code

### Device (please complete the following information):
 - OS: Ubuntu
 - Version: 20.04
 - Go version: 1.15.3
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
Other toolkits seem to be encountering something similar which is rather strange.
Can you please complete a virus scan of your windows computer and make sure it's not being infected after copying over?

**Comment by andydotxyz** [comment]
(Similar issue reported in electron https://github.com/electron-userland/electron-builder/issues/4878#issuecomment-614587486)

**Comment by james-portman** [comment]
This is still an issue

**Comment by Jacalz** [comment]
Like mentolens i
