### ISSUE TITLE
Add support for loading images from a url

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#144]
Add appropriate caching so that images can work offline and load faster

**Comment by AnkushJadhav** [comment]
@andydotxyz How would this be different from the existing `canvas.NewImageFromURI(fyne.URI) *Image` API ?

**Comment by andydotxyz** [comment]
That may be part of the solution, but currently our URI implementation does not have http or https support. Fixing that would probably satisfy the main requirement.

However as in one of the comments above we probably need to add caching as well otherwise calling Refresh will pull from the url every time.

**Comment by AnkushJadhav** [comment]
Yep, that makes sense, now that I have gone through the `Repository` interface and it's current implementations.

This is what I am currently thinking: Two implementations of the `Repository` interface (probably `HTTPRepository` and `HTTPSRepository`? I was originally thinking of something like `RemoteRepository`, but on second thought that sounds too generic and covers a lot of different schemes) that can be used to interact with resources at HTTP and HTTPS URIs.

Support will be added to the current `NewImageFromURI` API to accept HTTP and HTTPS URIs. The caching would be implemented on the Image itself.

What I am not yet able to decide is: what would be the right place/point to add these repositories to the `repositoryTable`.
Do let me know your thoughts, and whether I am heading in the right direction.

**Comment by andydotxyz** [comment]
This is now fixed on `develop` branch, thanks @AnkushJadhav
