### ISSUE TITLE
Ability to support mono-spaced type in entry widget

### ISSUE THREAD

**Issue by mikehawkes** [fyne-io/fyne#1447]
I would like to create a mono-spaced multi-line entry widget within a layout. In essence, a query editor that brings back nested results. While I can create an entry widget, it seems that I can't use a mono-spaced font within it.

**Comment by andydotxyz** [comment]
There is the TextGrid component that is built for monospaced presentation.
We don't really have a monospaced editor at this time.

If you are looking for markup support then we could consider edit capabilities for TextGrid, if however you just want plain text it would be a feature request to set style for Entry.

**Comment by mikehawkes** [comment]
Ok, thanks - that's a real shame. We're building a component that has a scripting requirement and this effectively rules out Fyne as a potential solution. Best of luck with this endeavour, however, I love the approach.

**Comment by andydotxyz** [comment]
I'm sorry we don't have a built-in solution.
If you like the toolkit for other reasons it is entirely possible to construct the widget you desire as all of the functionality can be combined or extended by developers without needing to modify the toolkit.

**Comment by mikehawkes** [comment]
I'd given it a try before asking; but got lost in the call-stack. No doubt I could rewrite the entry widget to handle it, but that pushes my timelines out compared to using Qt. I was considering moving from therecipe/qt to this because I think there's a faster build-path and easier learning curve for the dev team. But, if I have to (re)write widgets to get things working, it will take the team off core development and I can't justify the diversion. I would love to build using this as we're just starting a new project - but can't release something that won't scroll if you exceed component bounds or handle mono-spaced text. 

I absolutely get the design ethos in keeping things simple, but do think you're (with respect) missing a trick by not having a cascade for themes through the widget hierarchy. I could then apply theme settings for fonts, colours etc., to any widget. Everything would then work out of the box from a single 'theme setup' function. Having these settings selectively available makes it confusing - and difficult to determine what works where. When I first looked, I thought I could set up a theme and then apply it - when in fact, I can only apply selected theme elements to selected widgets. 

I genuinely wish the project well and will keep popping back to see how it's proceeding. Thanks for responding.

**Comment by andydotxyz** [comment]
Thanks for your message, I appreciate the time. I am not sure that setting an input box to monospace is a theme issue - it seems more like a developer choice or user preference. If you think I've misunderstood please say so.

After 1.4 we will probably be rebuilding the text handling of Entry/Label and possible some of canvas.Text so please feel free to get involved if you would like to help us get this right second time round :).

**Comment by mikehawkes** [comment]
I was thinking more along the lines of ... I have a theme defined for the app. I could then apply any control within that theme to any widget - so a text input could have a 'setBold' or 'setMonospace', where the theme elements would apply, but in a controlled way. It gives the consistency that every widget has the same interface for controlling the look and feel.

**Comment by andydotxyz** [comment]
I guess that is what `TextStyle` is for.
Though I'm not 100% sure that it should apply to `Entry` in the same way that `Label` allows multiple styles.
I guess we could be convninced.

**Comment by andydotxyz** [comment]
It looks like this might have been fixed by #1629 and in the `v1.4.3` release

**Comment by andydotxyz** [comment]
You can use Entry.TextStyle from v2.0.0 onwards
