### ISSUE TITLE
Multiline entry widget - scroll to show text as it's entered

### ISSUE THREAD

**Issue by mikehawkes** [fyne-io/fyne#1448]
I create a multiline entry widget and start typing - as per the text-editor demo. As I move out of the visible region into the 'scrollable area', I can't see what I'm typing because the entry widget doesn't scroll to ensure that the cursor remains visible: I type a long line, and the text disappears unless I manually move the scroll-bar.

The same issue when typing vertically - open the text editor demo app and enter a few lines of text - after you run out of space within the visible region, you can continue entering text, but it's off the screen. 

In the editor demo, I get to line 12 enter some text then manually move the scroll-bar so I can see line 12, enter line 13 then manually move the scroll-bar to see it ... and so on.

Can we have an automatic 'keep cursor visible' when entering multiline text please?

**Comment by andydotxyz** [comment]
This certainly needs to be added, It is complex and relates to a breaking change to move scroll capabilities into entry.
I think this is a duplicate of #471

**Comment by mikehawkes** [comment]
Yep, looks like it's in there. Happy to close this.
