### ISSUE TITLE
Custom colors for buildin light theme or custom doesn't work

### ISSUE THREAD

**Issue by LuminousLizard** [fyne-io/fyne#1464]
### Describe the bug:
If I change the color palette of the builtin light and dark themes, or create a new theme with custom color palette, then the colors are wrong. Are the colors of overlapping elements mixed ?

### To Reproduce:

If I change the button color of the builtin dark theme to e.g. orange, then the buttons of the app (also the demo) are displayed orange (not the 100% correct color, but ok).
But if I then also change the background to e.g. violet, then the buttons are white !

### Example code:
Modified color palette from theme.go:
```go
func DarkTheme() fyne.Theme {
	theme := &builtinTheme{
		//background: color.NRGBA{0x42, 0x42, 0x42, 0xff}, // original color
		background: color.RGBA{155, 89, 182, 1}, // violet

		//button:         color.NRGBA{0x21, 0x21, 0x21, 0xff}, // original color
		button:         color.RGBA{230, 126, 34, 1}, // carrot

		disabledButton: color.NRGBA{0x31, 0x31, 0x31, 0xff},
		text:           color.NRGBA{0xff, 0xff, 0xff, 0xff},
		disabledText:   color.NRGBA{0x60, 0x60, 0x60, 0xff},
		icon:           color.NRGBA{0xff, 0xff, 0xff, 0xff},
		disabledIcon:   color.NRGBA{0x60, 0x60, 0x60, 0xff},
		hyperlink:      color.NRGBA{0x99, 0x99, 0xff, 0xff},
		placeholder:    color.NRGBA{0xb2, 0xb2, 0xb2, 0xff},
		primary:        color.NRGBA{0x1a, 0x23, 0x7e, 0xff},
		hover:          color.NRGBA{0x31, 0x31, 0x31, 0xff},
		scrollBar:      color.NRGBA{0x0, 0x0, 0x0, 0x99},
		shadow:         color.NRGBA{0x0, 0x0, 0x0, 0x66},
		focus:          amethyst,
	}

	theme.initFonts()
	return theme
}
```
-->

### Device (please complete the following information):
 - OS: Linux Manjaro
 - Version: kernel 5.8.16-2
 - Go version: 1.15.2
 - Fyne version: 1.3.3

**Comment by LuminousLizard** [comment]
Error found !

color.RGBA{r, g, b, a}  doesn't work ... color.NRGBA{r, g, b, a} with hex value must be used.

Should be written in the documentation, that you have to use color.NRGBA.

**Comment by andydotxyz** [comment]
I think the error is really that you are using “1” to be fully opaque but that it should be “0xff”. These are all uint8 channels, not the CSS style (int, int, int, float).

**Comment by andydotxyz** [comment]
As for RGBA vs NRGBA, you can use either but as per go docs the former is alpha pre-multiplied meaning the rgb values cannot be more than the alpha. Combine that with the above issue that your alpha was 1/255 you were probably encountering many issues all at once.
