### ISSUE TITLE
Strange flickering in Tree

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1465]
### Describe the bug:
I was just checking out the Fyne Demo changes to use Tree instead of nested tabs. I am most of the time (not always) seeing a strange flicker when dragging the mouse over the nodes and branches.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open the new redesigned fyne demo
2. Open one of the branches and drag the mouse over
3. See strange flickering

### Screenshots:

![strange-flicker](https://user-images.githubusercontent.com/25466657/97106610-1adc2180-16c3-11eb-9dc5-f14221a409b7.gif)

### Example code:
See the https://github.com/fyne-io/fyne/pull/1452 PR.

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.6.19
 - Go version: 1.15.3
 - Fyne version: 7148c67c8ce9c21306d0e6fc29371c72c5aa15c4

**Comment by andydotxyz** [comment]
@Jacalz with latest Tree I think this is resolved - what do you reckon?

**Comment by Jacalz** [comment]
Yeah. Haven't seen this in ages honestly. Good catch
