### ISSUE TITLE
Severe flickering when resizing the text section in fyne_demo

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1466]
### Describe the bug:
There is a lot of black flickering when resizing the text section in the fyne demo application. I suspect that there might be the case that a lot of calls to wrap the text are blocking the rendering and causing the blackouts. The strange thing is that it happens even if I turn of wrapping so I suspect the wrapping might be happening even though it shouldn't as well.

Does not seem to happen on most of the other pages. A bit on the graphics tab, but not as severe. All other pages are mostly  fine.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to the text section under widgets or the graphics tab
2. Resize window
3. See black flickering

### Screenshots:

![black-flickering](https://user-images.githubusercontent.com/25466657/97106897-94c0da80-16c4-11eb-9e78-3289ab91e596.gif)

### Example code:
The fyne demo should suffice

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.6.19
 - Go version: 1.15.3
 - Fyne version: 1cd2903645fb867e4089493f771090042fe59475 and master (roughly fyne 1.3.3)

**Comment by Jacalz** [comment]
This seems to be an issue on the master branch as well. Not a blocker of fyne 1.4.

**Comment by dweymouth** [comment]
Closing this as it's certainly no longer relevant

**Comment by Jacalz** [comment]
Yeah, probably. I'll double check tomorrow to be sure though (if I remember)
