### ISSUE TITLE
How to align left to the Check widget

### ISSUE THREAD

**Issue by Deardrops** [fyne-io/fyne#147]
The Check widget struct only have these fields:
https://github.com/fyne-io/fyne/blob/85d74dc43f0b5642f7cf63c2308e646740aee2ee/widget/check.go#L69-L75
and in its `CreateRenderer` function, I found that alignment have been set to `Center`.
https://github.com/fyne-io/fyne/blob/85d74dc43f0b5642f7cf63c2308e646740aee2ee/widget/check.go#L133
So, How I change the align and set the alignment to left on Check widget?

-----
Addition question: I want to use a multiple checkbox like:
![image](https://user-images.githubusercontent.com/9463871/54246618-9467e000-4570-11e9-8d00-9d729296848b.png)

Is there any widget with similar function? or do I need wrap these Check Widget into a new widget by myself?

**Comment by andydotxyz** [comment]
I was considering changing the default checkbox/radio alignment to left for this next release - would that resolve your issue?

You can put multiple checkboxes in a VBox - is there additional functionality you would want from a CheckboxGroup widget?

**Comment by Deardrops** [comment]
> I was considering changing the default checkbox/radio alignment to left for this next release - would that resolve your issue?

Nice, But it's better to leave a option or a export field for set alignment.

> You can put multiple checkboxes in a VBox - is there additional functionality you would want from a CheckboxGroup widget?

Nope, I just want to get all checked checkboxes' names or indexs when click a button like `submit`. And  , adding some buttons like `select all` `inverse` and `deselect all`, but I think I can implement these by myself. So these is no additional functionality needed.

**Comment by andydotxyz** [comment]
Thanks for that. I agree that adding a feature to set the alignment would be better but we are in API freeze for 1.0 release so my choice is to leave it for later or to change the default alignment ;)

**Comment by damiantoczek** [comment]
Has been 2 years have you added the alignment feature? Where we can choose how we want to have the list aligned?

**Comment by andydotxyz** [comment]
The check widget has been left (or "Leading") aligned for a very long time.
If that is not what you are asking please open a new issue describing the problem or feature request.
