### ISSUE TITLE
Mobile simulation missing file / listable support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1470]
Fill in the blanks (would need to be windows/linux/macOS etc.
Probably re-using code in GLFW I would expect...

Working as `go run -tags mobile` the dialog file open/folder open code should work fully.

**Comment by charlesdaniels** [comment]
Note: this is pending on #1665

**Comment by andydotxyz** [comment]
This is fixed by #1768

**Comment by andydotxyz** [comment]
Now on `develop` for testing
