### ISSUE TITLE
SVG Rendering Bug

### ISSUE THREAD

**Issue by careless-uia** [fyne-io/fyne#1476]
### Describe the bug:
SVG images do not render properly when using canvas.NewImageFromFile() inside of a container.

When resizing the window, the SVG icons swap positions.
This can be duplicated with different layouts, grids, etc.

This issue is not present with PNG images. I believe it is an issue with SVG rendering.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create code sample below.
2. Save any two SVG images in the same directory as golang file.
3. Run program and resize window.
4. Witness the SVG icons swapping as the window resizes.

This issue can be further witnessed by adding more SVG images and rows.

### Example code:
How to reproduce:
```go

package main

import (
     "fyne.io/fyne"
     "fyne.io/fyne/app"
     "fyne.io/fyne/layout"
     "fyne.io/fyne/canvas"
)

func main(){

     app := app.New()
     w := app.NewWindow("SVG Render Bug")

     a := canvas.NewImageFromFile("./a.svg")
     b := canvas.NewImageFromFile("./b.svg")

     c := fyne.NewContainerWithLayout(layout.NewGridLayout(2), a, b)

     w.SetContent(c)
     w.ShowAndRun()
}
```

### Device:
 - OS: Linux Debian 10
 - Go version: 1.15
 - Fyne version: 1.3.3

**Comment by andydotxyz** [comment]
On the upcoming 1.4 release this swapping behaviour is no longer present.
However there is still something strange in the cache because it renders both images the same... Looking into it further.

**Comment by andydotxyz** [comment]
OK, cause found. Fix is on the way, but not sure if it will make the pending release of 1.4

**Comment by andydotxyz** [comment]
As this is not a new issue we decided it should not hold back this week's release, sorry.
The fix will be public right after the release and will appear in 1.4.1.

In the meantime you can use a workaround, `canvas.NewImageFromResource(res)`

**Comment by andydotxyz** [comment]
I had to roll an RC2 for 1.4, so was able to include this fix.
Therefore it should be out in a couple of days.
