### ISSUE TITLE
compile on ARM

### ISSUE THREAD

**Issue by beho1der** [fyne-io/fyne#1481]
I got compile on linux to rassberyPI:
$ GOOS=linux GOARCH=arm go build fyne.go 

Get ERROR:
../fyne.io/fyne/internal/painter/gl/gl_es.go:12:2: build constraints exclude all Go files in /home/captain/go/src/fyne.io/fyne/vendor/github.com/go-gl/gl/v3.1/gles2
../fyne.io/fyne/internal/driver/glfw/clipboard.go:6:2: build constraints exclude all Go files in /home/captain/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw

**Comment by gazhayes** [comment]
What command are you running to compile it?

**Comment by gazhayes** [comment]
Try using fyne-cross to compile it instead: https://github.com/fyne-io/fyne-cross

**Comment by beho1der** [comment]
Yes it works 
$ fyne-cross linux -arch=arm

But when i start on ARM platform i get err:
./tt: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./tt)

On platform  McGrath and Ulrich Drepper.
root@LicheePi:~# ldd --version
ldd (Debian GLIBC 2.19-18+deb8u7) 2.19

I make cros-compile on GLIBC 2.19 ?

**Comment by andydotxyz** [comment]
The original error is because you missed off `CGO_ENABLED=yes` - that is switched off by Go when you start to cross compile. See our doc at https://developer.fyne.io/started/cross-compiling.

**Comment by andydotxyz** [comment]
For the error you encountered with fyne-cross, it seems like you are using an unsupported version of Debian -  release 8 was end of lifed back in June I think.
If you want to open a ticket to explore adding support for older operating systems you can file a ticket over at the [fyne-cross](/fyne-io/fyne-cross) project.

**Comment by beho1der** [comment]
Thanks, I am try update to Debian 9

**Comment by beho1der** [comment]
I update to Debian 10
# ldd --version:
ldd (Debian GLIBC 2.28-10) 2.28

Example Work FINE! ALL Thanks
