### ISSUE TITLE
Announcement: font awesome icons for fyne

### ISSUE THREAD

**Issue by gazhayes** [fyne-io/fyne#1484]
I needed some better icons for something I'm working on so I packaged the entire font awesome library of icons here:

https://github.com/gazhayes/fycons

They can be used quite easily, just import and then they are all available as a `fyne.Resource` type and can be used as a drop in replacement for `theme.xxxxIcon()`.

Pull requests are welcome.

On a side note: if anyone knows how to force these icons to render with the correct aspect ratio please let me know!

**Comment by stuartmscott** [comment]
> Fycons

Great name!

The readme should link to the [gallery](https://fontawesome.com/icons?d=gallery) so potential users can see what is available, and should point out where the icons in this library differ from the source.

**Comment by gazhayes** [comment]
Thanks for the feedback @stuartmscott. I've updated the Readme.

**Comment by andydotxyz** [comment]
> On a side note: if anyone knows how to force these icons to render with the correct aspect ratio please let me know!

Aspect is controlled by the output rather than the data - as images have different fill modes.
You could use widget.Icon which assumes 1:1 aspect and imposes a standard minsize - perhaps this suits you better than (I assume you are using) canvas.Image?

**Comment by andydotxyz** [comment]
A great iconset, but I was not sure about the white vs black rendering mentioned in the readme.
Our icons are designed to draw in the theme.IconColor - so having two different colours seems counterintuitive.

**Comment by Jacalz** [comment]
That looks like a great icon package 👍

I saw that each file with icons are 6-7MB in size (according to GitHub). I wonder, how big are the fyne binaries built with this package?

**Comment by stuartmscott** [comment]
The separation of white and black icons contributes to the binary size and is extra work for the developer as they have to switch between white vs black icons depending on the user's choice of theme, instead you could use `theme.ThemedResource` to colourize icons appropriately based on the current theme.

**Comment by gazhayes** [comment]
@andydotxyz 
> Our icons are designed to draw in the theme.IconColor - so having two different colours seems counterintuitive.

Yeah I'm going to export them as a ThemedResource instead of a Resource and remove the different colours.

> You could use widget.Icon which assumes 1:1 aspect and imposes a standard minsize - perhaps this suits you better than (I assume you are using) canvas.Image?

I'm trying to use it in a `widget.TabItem`, for some reason the icons in `theme...` render 1:1 but these icons do not. I see that canvas.Image is used internally to render tab icons, but I've been trying to work out how the built in icons keep the 1:1 ratio here.

@Jacalz 
> I saw that each file with icons are 6-7MB in size (according to GitHub). I wonder, how big are the fyne binaries built with this package?

Each icon is exported individually so if you use the package it only pulls in the individual icons that are used (not the entire package or the entire set).

**Comment by andydotxyz** [comment]
Feel free to open an issue regarding the aspect ratio of images. We can probably help solve it with the appropriate information.
