### ISSUE TITLE
Bug while opening the fyne_demo (crashes sometimes)

### ISSUE THREAD

**Issue by Xefreh** [fyne-io/fyne#1487]
### Describe the bug:
The bug is happening when you execute the command fyne_demo in cmd.
the window no longer respond and then it crash.

### To Reproduce:
Open the fyne_demo application.

### Screenshots:
https://prnt.sc/va0xye

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.14
 - Fyne version: latest

**Comment by andydotxyz** [comment]
When it crashes is there any information printed to the terminal?
Can you please confirm what 'latest' means? A version number or git SHA so we can try and replicate.

**Comment by andydotxyz** [comment]
When you say that it crashes do you mean that it hangs, then the OS reports unresponsive, then the window is closed by the OS?
Can you please share the commands that you use to run it? I am struggling to understand how an unexpected exit can be caused without some logging information being printed.

**Comment by andydotxyz** [comment]
P.S. `go get` will return the latest version, which is why we ask for more information. Running `go get` this week will return a different build than last week as we have released 1.4. I guess that means that you were using `v1.3.3`.

**Comment by Xefreh** [comment]
yes it was v1.3.3

**Comment by Xefreh** [comment]
i've updated to 1.4.1 and I don't have any problem.

**Comment by andydotxyz** [comment]
Oh that’s great news thanks :)
