### ISSUE TITLE
Cannot simply replace deprecated boxes.

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1494]
While adopting my code to `1.4.0` I'm suggested to replace `widget.NewV/HBox()` with the corresponding `container.NewV/HBox()`, but that cannot always be performed, since the latter calls return `CanvasObject` rather than `Widget`. That contradicts to the package description
> Package container provides container widgets that are used to lay out and organise applications.

* Do you plan to address this problem?
* Should I wrap the returned container with `widget.BaseWidget` when I need widget?

**Comment by andydotxyz** [comment]
Yes I see how this could be a problem. I think the docs could be updated to help.
However all `fyne.Widget` are extension of `fyne.CanvasObject`. If you can change the variable that you are storing the `VBox` in to be that type instead the problem should go away.

Let me know if that helps!

**Comment by ababo** [comment]
No, I cannot change the variable type, since I have to implement an interface that relies on `fyne.Widget`.

**Comment by andydotxyz** [comment]
Can you provide any more information? The `fyne.Widget` is just `fyne.CanvasObject` with an additional `CreateRenderer` function that developers should not be calling anyway...

**Comment by ababo** [comment]
There're places where I need to pass top-level boxes as widgets, e.g. for `widget.Refresh()` and several others.

**Comment by andydotxyz** [comment]
The Refresh() function is defined for all `CanvasObject`s, so that should not be a problem.

**Comment by ababo** [comment]
In theory, but in practice it gives different effect on complex forms. Moreover I have several other abstractions that rely on Widgets, e.g. wrappers that modify existing widgets being applied to top-level boxes.

**Comment by andydotxyz** [comment]
Calling `Refresh()` on something that is a `CanvasObject` will call the widget refresh if the object is a `Widget` behind the scenes - if you see some different behaviours there is maybe a bug involved...

All of your customisations should work on the widgets that you have set up, the change would only be how you are passing them around after creation. Best practice is to use `CanvasObject` abstraction whenever you can so that API's don't accidentally become dependent on internal rendering details.

The one situation that this change won't support is if you have extended `widget.Box` to add customisations in that case you will need to spend the time between 1.4 and 2.0 adapting your code to use one of the new widgets. Unfortunately the old box implementation is flawed so supporting overridden versions of it is not possible into the `container` package.

I'm sorry if this is not straight forward. I'm pretty sure that the majority of cases this can be fixed by changing `fyne.Widget` to `fyne.CanvasObject`. I would be happy to explore your situation further if this is proving to be problematic.

**Comment by ababo** [comment]
Here is one circumstance that forces me to stay with deprecated `widget.Box`. I depend on a type for widget background color customisation:
```go
type backgroundColorRenderer struct {
	fyne.WidgetRenderer
	backgroundColor color.Color
}

func (bcg *backgroundColorRenderer) BackgroundColor() color.Color {
	return bcg.backgroundColor
}

type backgroundColorWrapper struct {
	fyne.Widget
	backgroundColor color.Color
}

func newBackgroundColorWrapper(widget fyne.Widget, base *widget.BaseWidget,
	backgroundColor color.Color) *backgroundColorWrapper {
	wrapper := &backgroundColorWrapper{widget, backgroundColor}
	base.ExtendBaseWidget(wrapper)
	return wrapper
}

func (bcw *backgroundColorWrapper) CreateRenderer() fyne.WidgetRenderer {
	return &backgroundColorRenderer{
		bcw.Widget.CreateRenderer(), bcw.backgroundColor}
}
```
This type *requires* source object to be a widget, since it overrides its renderer. In the most of the cases this type wraps outer `widget.Box` instances. Do you see a way to replace it keeping the corresponding functionality?

**Comment by andydotxyz** [comment]
Thanks for this illustration @ababo - this is indeed one of the things you can't directly port. 
However, you may notice that `WidgetRenderer.BackgroundColor` is also deprecated - in 2.0 we will not be drawing rectangles under widgets any more. And so this approach will break in the future.

However the good news is that there is a simple replacement for this use-case - add a background rectangle under the widget with a container and maxlayout:

```
bg := canvas.NewRectangle(color.NRGBA{R: 0xff, A: 0xff})
wid := widget.NewLabel("A label")
content := container.NewMax(bg, wid)
```

Code like this could be put in a `newBackgroundColorWrapper` where it takes a widget and a background color as parameters then just returns a `fyne.CanvasObject` - no custom types needed this way.

Sorry if this is a bigger change than you would like, but this approach will continue to work into the future!
It may not apply directly for all widgets during this transition but it will replace the background colored Box widgets you were trying to replace.

**Comment by ababo** [comment]
Thank you @andydotxyz, will try this approach soon. BTW do you plan removing the deprecated stuff some time? For instance on which release I should expect `widget.Box` going to be dropped?

**Comment by andydotxyz** [comment]
Deprecated API will be removed in 2.0. This will be the first release when we feel able to make incompatible changes.
For everything that is removed we will have some documentation about how to move over.
I expect that you have 2 - 3 months to make the change to a non-deprecated API if you want the 2.0 upgrade to go smoothly.
Some changes cannot be made without small breaks, but we will only make such changes when required for the future of the project.

**Comment by andydotxyz** [comment]
Going to close this as resolved - if there is an issue with the suggested replacement feel free to re-open
