### ISSUE TITLE
Go1.15 does not support darwin/arm anymore for iOS

### ISSUE THREAD

**Issue by MagicalTux** [fyne-io/fyne#1497]
### Describe the bug:
Building for iOS with go1.15+ will fail with:

go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=ios -- .]: exit status 2: cmd/go: unsupported GOOS/GOARCH pair darwin/arm

### To Reproduce:
Steps to reproduce the behaviour:
1. build with `-os ios` with go1.15+

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.7
 - Go version: 1.15.3
 - Fyne version: 1.4.0

### Solving the issue
In file `cmd/fyne/internal/mobile/build.go` on line 155:

    targetArchs = []string{"arm", "arm64"}

Could be replaced with:

    targetArchs = []string{"arm64"}

If 32bit support is still required, adding a command line flag to enable it or define the target archs would be nice.

**Comment by andydotxyz** [comment]
Thanks for reporting this. I had not upgraded to Go 1.15 on my mobile test rig and see the problem now.

**Comment by andydotxyz** [comment]
If possible can you try PR #1502?

Go modules should not be an issue as it's just a command line utility - apply the patch to your checkout of fyne and "go install" in `cmd/fyne` directory. You should then be able to build for iOS correctly.

**Comment by MagicalTux** [comment]
Tested PR #1502 and confirmed it works with Go1.15.3.

main is only arm64 as expected: `Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit executable arm64]`

**Comment by MagicalTux** [comment]
Tested further with the fix to #1498 and attempted to call `xcrun altool --upload-app`, got the following error:

    ERROR ITMS-90502: "Invalid Bundle. Your binary, 'com.shells.app', has a 64-bit architecture slice, so you must include the "arm64" value for the UIRequiredDeviceCapabilities key in your Xcode project. Learn more (https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW3)."

**Comment by andydotxyz** [comment]
Oh, great catch thanks for that. Fixed on the PR, that should work for you now.

**Comment by andydotxyz** [comment]
Agh, there was a typo.
Testing again locally for a final fix

**Comment by MagicalTux** [comment]
Apple servers are not complaining anymore, looking good.

**Comment by andydotxyz** [comment]
Thanks for your help. Now I just need a team PR review, and for the Travis servers to catch up. Probably will land tomorrow.

**Comment by MagicalTux** [comment]
Btw got a separate issue from Apple after the upload succeeded:

    ITMS-90713: Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle '...'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.

**Comment by andydotxyz** [comment]
Oh I have not seen that one before. But I have had an issue that Apple is failing my upload with no error - so maybe this is what I was missing and for some reason the emails are lost for me.
Are you able to look into this further for another PR? It is possible that we need to make the asset catalog and that's not something I am familiar with.

**Comment by MagicalTux** [comment]
I'll open a new issue for now and gather information

**Comment by andydotxyz** [comment]
On `develop` and `release/v1.4.x` branches ready for more testing :)
