### ISSUE TITLE
I would like to be able to disable widget.List

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1499]
Can this be done?

**Comment by andydotxyz** [comment]
We don't have this feature at present. What would a disabled List look / behave like?

**Comment by ababo** [comment]
Like disabled `widget.Radio`, i.e. gray and not responding to user interactions.

**Comment by andydotxyz** [comment]
I'm not sure what we can turn gray - in this instance all the contents are controlled by the app developer.
We could disable user input I suppose, just to stop the OnSelected callbacks from happening?

**Comment by stuartmscott** [comment]
Disabling user interaction for selection and hover would make sense, but I would be hesitant of disabling user interaction for scrolling.

How would this apply to future keyboard navigation/interactions?

**Comment by ababo** [comment]
I guess the disabled list should not be focusable, but I'm not sure.

**Comment by ababo** [comment]
@andydotxyz BTW Is there a master GitHub issue for keyboard navigation support? It looks like soon I will desperately need this features in my software, so I would like to see at least some spec as you maintainer guys see it. May consider to participate in this development.

**Comment by andydotxyz** [comment]
> Is there a master GitHub issue for keyboard navigation support?

Sadly we have not pulled one together, that is a good idea.
A lot of it is in progress but we don't want to miss anything. I'll try and pull this together. We will likely need another one for theme updates as we get into 2.0 development proper.

**Comment by andydotxyz** [comment]
I have now added the keyboard tag, that will gather keyboard nagivation issues :)

**Comment by dweymouth** [comment]
Worth noting that you can easily achieve this with an extended List, just adding the Disableable interface methods. By default this does nothing other than preventing it from being focused by the focus manager. This, combined with making your list items handle Tapped, can completely disable selection on the list. To make it grayed out when disabled, have your extended list render with a rectangle on top of the base list, which is semi-transparent gray for disabling, or hidden when not disabled.

**Comment by andydotxyz** [comment]
I'm tempted to close this now there is a known way to do it in user code. As posted earlier I don't really think there is a case for making standard widgets disabled that are not input widgets (or buttons)

**Comment by dweymouth** [comment]
I agree. Closing this as it's possible to achieve the desired behavior in user code.
