### ISSUE TITLE
Configurable cursor for widgets

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1505]
Currently I use the following code to show pointer cursor over buttons:
```go
// PointerButton is a button with pointer mouse coursor when enabled.
type PointerButton struct {
	widget.Button
}

// NewPointerButton creates a new button widget with the set label and tap
// handler.
func NewPointerButton(text string, onTapped func()) *PointerButton {
	btn := &PointerButton{}
	btn.ExtendBaseWidget(btn)
	btn.Text = text
	btn.OnTapped = onTapped
	return btn
}

// Cursor returns the cursor type of this widget.
func (b *PointerButton) Cursor() desktop.Cursor {
	if !b.Disabled() {
		return desktop.PointerCursor
	}
	return desktop.DefaultCursor
}
```
It would be nice it we supported this customisation out of the box.

**Comment by andydotxyz** [comment]
The design principle for the toolkit is that common use-cases are easy, and more niche ones are possible through extending widgets.
This way we keep the main API clean and simple. The code you have is the way we intend it to be used, unless you can define a "semantic reason" behind such a change. If you're wanting to make it look like a URL then use `wiget.NewHyperlink` instead

**Comment by andydotxyz** [comment]
Closing this as meeting our design - customisation is through extension not through direct manipulation.

**Comment by kargirwar** [comment]
I tried the solution of @ababo on Mac Monterey (Intel). It did not work. Changing the cursor name made no difference whatsoever.

**Comment by andydotxyz** [comment]
Please don't comment on closed issues. The functionality works as designed, if you think something is not working correctly open an issue or discuss on a support channel.
