### ISSUE TITLE
how to pack css\html\jpg in to apk, i want  creat a http services.

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#1512]
how to pack css\html\jpg in to apk, i want  creat a http services，thank you.

**Comment by andydotxyz** [comment]
We usually recomment using "fyne bundle" so your app can still work as a single executable like most Go apps.
https://developer.fyne.io/tutorial/bundle

**Comment by DiskGetor** [comment]
> 我们通常建议使用“ fyne捆绑包”，这样您的应用仍可以像大多数Go应用一样作为单个可执行文件运行。
> https://developer.fyne.io/tutorial/bundle

thank you,very good
