### ISSUE TITLE
Hello, fyne team, I need help with the construction of the interface output form, thank you very much！

### ISSUE THREAD

**Issue by cplasfwst** [fyne-io/fyne#1519]
### Is your feature request related to a problem? Please describe:

Hello from the fyne team, I very much hope to make such an interface output information (such as the interface I circled), but I can’t find the relevant components after studying for a long time. I used NewGridLayout to build a scroll bar, but I don’t know. How to fix the display frame size of the scroll bar, can you answer my questions? I will be very grateful, because it took me a long time to deal with it
![问题](https://user-images.githubusercontent.com/34654697/98710288-69c1d080-23be-11eb-861b-f4c6766288a2.png)
[main.go-and-picture.zip](https://github.com/fyne-io/fyne/files/5519252/main.go-and-picture.zip)

**Comment by cplasfwst** [comment]
![quesss](https://user-images.githubusercontent.com/34654697/98711365-d9848b00-23bf-11eb-847b-4202a838c9cb.png)

**Comment by cplasfwst** [comment]
![xzquess](https://user-images.githubusercontent.com/34654697/98711598-236d7100-23c0-11eb-9ccd-8f1b2feed02e.jpg)

**Comment by andydotxyz** [comment]
In 1.4 we introduced Table that best matches your request. Unfortunately it only supports equally-sized columns. We will be adding support for setting column size soon and then you should be able to build what you want.

**Comment by cplasfwst** [comment]
> In 1.4 we introduced Table that best matches your request. Unfortunately it only supports equally-sized columns. We will be adding support for setting column size soon and then you should be able to build what you want.

Really, I am waiting for your recovery. I can't rest without a solution. . . . . . . How are the related calls made? Can you tell me which related order is it? my English is not very good

**Comment by cplasfwst** [comment]
> In 1.4 we introduced Table that best matches your request. Unfortunately it only supports equally-sized columns. We will be adding support for setting column size soon and then you should be able to build what you want.

Can you post related commands for me to refer to, such as MinSize().Heightxxxx..............

**Comment by andydotxyz** [comment]
Documentation is at: https://developer.fyne.io/api/v1.4/widget/table.html

You can see it in action in: https://github.com/fyne-io/fyne/blob/0ca05dc12c03b8873d2f22caa6ce4c28988b3886/cmd/fyne_demo/tutorials/collection.go#L58

**Comment by cplasfwst** [comment]
> Documentation is at: https://developer.fyne.io/api/v1.4/widget/table.html
> 
> You can see it in action in:
> 
> https://github.com/fyne-io/fyne/blob/0ca05dc12c03b8873d2f22caa6ce4c28988b3886/cmd/fyne_demo/tutorials/collection.go#L58

thank you very much!
I used NewVBoxLayout, after putting NewTable into it, why would it become very small? How can I adjust the size of NewTable

**Comment by stuartmscott** [comment]
The size of a table cell is determined by the size of the template CanvasObject returned by `CreateCell`. If you can share your code, we'll be able to give better directions

**Comment by andydotxyz** [comment]
> I used NewVBoxLayout

Vertical box is designed to pack each item to the container full width at the minimum height.
If you want a widget to expand to fill space you should use a container that does this like the Border layout.
You can see them all at https://developer.fyne.io/started/layouts

**Comment by cplasfwst** [comment]
> The size of a table cell is determined by the size of the template CanvasObject returned by `CreateCell`. If you can share your code, we'll be able to give better directions

Thank you very much for your enthusiasm, I am very moved!

[thank,you.zip](https://github.com/fyne-io/fyne/files/5526017/thank.you.zip)

this is my code

**Comment by stuartmscott** [comment]
Replace:
```go
buju := fyne.NewContainerWithLayout(layout.NewGridLayoutWithRows(2), play, content)

neirong := fyne.NewContainerWithLayout(layout.NewVBoxLayout(), topUp, buju)

w.SetContent(neirong)
```
With:
```go
w.SetContent(container.NewBorder(topUp, content, nil, nil, play))
```

Additionally, consider using `widget.Toolbar` instead of;
```go
//工具栏
bt1 := widget.NewButtonWithIcon("主页", theme.InfoIcon(), func() {
	log.Println("点击了主页")
})
bt2 := widget.NewButtonWithIcon("关于", theme.InfoIcon(), func() {
	log.Println("点击了关于")
})
bt3 := widget.NewButtonWithIcon("帮助", theme.HelpIcon(), func() {
	log.Println("点击了帮助")
})

//顶部的上下布局
topUp := fyne.NewContainerWithLayout(layout.NewHBoxLayout(),
	bt1, bt2, layout.NewSpacer(), bt3)
```

**Comment by cplasfwst** [comment]
> Replace:
> 
> ```go
> buju := fyne.NewContainerWithLayout(layout.NewGridLayoutWithRows(2), play, content)
> 
> neirong := fyne.NewContainerWithLayout(layout.NewVBoxLayout(), topUp, buju)
> 
> w.SetContent(neirong)
> ```
> 
> With:
> 
> ```go
> w.SetContent(container.NewBorder(topUp, content, nil, nil, play))
> ```
> 
> Additionally, consider using `widget.Toolbar` instead of;
> 
> ```go
> //工具栏
> bt1 := widget.NewButtonWithIcon("主页", theme.InfoIcon(), func() {
> 	log.Println("点击了主页")
> })
> bt2 := widget.NewButtonWithIcon("关于", theme.InfoIcon(), func() {
> 	log.Println("点击了关于")
> })
> bt3 := widget.NewButtonWithIcon("帮助", theme.HelpIcon(), func() {
> 	log.Println("点击了帮助")
> })
> 
> //顶部的上下布局
> topUp := fyne.NewContainerWithLayout(layout.NewHBoxLayout(),
> 	bt1, bt2, layout.NewSpacer(), bt3)
> ```

Thank you very much for solving my previous problem. I followed your suggestion and used widget.Toolbar. How do you change the size of the widget.Toolbar button and the size of the picture? I feel a little bit small

**Comment by cplasfwst** [comment]
`topUp := widget.NewToolbar(
		widget.NewToolbarAction(theme.DocumentCreateIcon(), func() {
			log.Println("New document")
		}),
		widget.NewToolbarSeparator(),
		widget.NewToolbarAction(theme.ContentCutIcon(), func() {}),
		widget.NewToolbarAction(theme.ContentCopyIcon(), func() {}),
		widget.NewToolbarAction(theme.ContentPasteIcon(), func() {}),
		widget.NewToolbarSpacer(),
		widget.NewToolbarAction(theme.HelpIcon(), func() {
			log.Println("Display help")
		}),
	)`

For example, I want to make each button of the toolbar look longer and as big as the picture I need
![Uploading toobar.jpg…]()

**Comment by andydotxyz** [comment]
Sorry @cplasfwst toolbar, like other widgets, is set using the theme. It uses the theme icon size, matching the icons used on other buttons. You could override this with a custom theme I guess, but it will cause all buttons with icons to be larger.

**Comment by cplasfwst** [comment]
@andydotxyz 
Okay, I understand. The above question is also very grateful for your help. I paid special attention to your twitch and downloaded your notes for reference. . . I used go mod, and your project tips are as shown in the picture below:
![notes](https://user-images.githubusercontent.com/34654697/98933855-2b422800-251c-11eb-9b58-4bb8552c1006.jpg)

**Comment by andydotxyz** [comment]
When there are multiple files you can't just `go run main.go` because the note code is missing. 
Try `go run .` or `go run main.go note.go`.

**Comment by cplasfwst** [comment]
@andydotxyz
OK, no problem at all! Thanks, obviously I am a rookie haha. . Now I have learned knowledge again, thank you, I have solved all my current doubts

**Comment by andydotxyz** [comment]
Glad to hear it, closing this issue now

**Comment by cplasfwst** [comment]
> Glad to hear it, closing this issue now

ok,
Do I click to close the thread? I use GITHUB for the first time

**Comment by andydotxyz** [comment]
It is already closed
