### ISSUE TITLE
binary not work by fyne package on windows

### ISSUE THREAD

**Issue by Nigh** [fyne-io/fyne#1521]
### Describe the bug:

```
Program 'test.exe' failed to run: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for 
more detailAt line:1 char:1
+ .\OProgX.exe
+ ~~~~~~~~~~~~.
At line:1 char:1
+ .\OProgX.exe
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**!! After using ResHacker to remove the `Manifest` resourse, it could run normally.**

### To Reproduce:
Steps to reproduce the behaviour:
1. `fyne package -os windows`
2. `./test.exe` throw error
3. use ResHacker to remove `Manifest` resourse.
4. `./test.exe` works fine

### Device (please complete the following information):
 - OS: `Win10`
 - Version: `2004`
 - Go version: `1.15.2 windows/amd64`
 - Fyne version: `1.4`

**Comment by andydotxyz** [comment]
Is it possible to get more information as suggested in `Please see the application event log or use the command-line sxstrace.exe tool for more detail`?
It is likely an issue inside the manifest, hopefully the output has more.
We can't remove the manifest completely so unfortunately it's not a solution.

**Comment by tsoun** [comment]
I got the exact same issue. Upon deleting the Manifest, the *****.exe runs.

**Comment by andydotxyz** [comment]
Apologies, this has been resolved on `release/v1.4.x` branch, and will be in the 1.4.1 release soon.

**Comment by cplasfwst** [comment]
fyne package -os windows -appVersion 1.1.1

**Comment by cplasfwst** [comment]
Haha, I also encountered this problem, and then I solved it like this:
fyne package -os windows -appVersion 1.1.1

**Comment by andydotxyz** [comment]
Thanks for providing this information, that is a great workaround.
The problem was that version numbering is optional on package, but the fallback number was not Windows compatible.
Adding `-appVersion` is perfect until 1.4.1 is out.
