### ISSUE TITLE
Request: ability to capture keys on widget.Entry

### ISSUE THREAD

**Issue by MagicalTux** [fyne-io/fyne#1522]
I have a form with `widget.Entry` fields. I'd like to be able to catch the following keys:

* Tab: so I can send the focus to the next widget
* Enter: so I can submit the form

I'm not sure if something exists. I've tried setting SetOnTypedKey() on the parent, but it doesn't catch events sent to the `widget.Entry` which has the focus. Let me know if there is a way I can catch events sent to a given widget.

**Comment by Jacalz** [comment]
I think this might be what you are looking for. It is a tutorial on how to handle key presses in entry.

https://developer.fyne.io/tutorial/keypress-on-entry

**Comment by andydotxyz** [comment]
As @Jacalz says this is possible already. The API design allows these events to be listened to by any widget. If you want to add event handling to an existing widget you can extend it - as the example shows.

This way we can keep the widget API simple whilst keeping them open for extension.

**Comment by MagicalTux** [comment]
Tested and confirmed, thanks for the pointer!
