### ISSUE TITLE
mac -> windows , MAC system, how to compile into Windows

### ISSUE THREAD

**Issue by Xuzan9396** [fyne-io/fyne#1526]
![image](https://user-images.githubusercontent.com/24741439/98971262-e0d89f80-254b-11eb-9a4d-89b07addb932.png)

GOOS=windows go build -x -v  -o windows/v1.1_wechat.exe ./client_gui/main.go

**Comment by andydotxyz** [comment]
Check out https://developer.fyne.io/started/cross-compiling - I think you missed `CGO_ENABLED=1`

**Comment by andydotxyz** [comment]
Assuming the suggestion / documentation resolves the issue - please re-open if there are still problems.
