### ISSUE TITLE
Disable `Form` labels when the element it applys to is disabled

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1530]
### Is your feature request related to a problem? Please describe:

When creating forms (which currently, I can't use the `Form` type properly, covered in another issue); I would like to be able to "Disable" (grey out, just like with `Entry` fields) Labels corresponding to values which can no longer be modified.

#### Example:
![image](https://user-images.githubusercontent.com/1910461/99146001-b90b3980-2628-11eb-8a86-04ec93db4e64.png)
(Notice how the `Label` visually seems very out of place when its corresponding `Entry` is disabled?)

### Is it possible to construct a solution with the existing API?
Yes

### Describe the solution you'd like to see:
Make `Label` `Disablable` like `Check` and `Entry` already are.
The text would go grey, just like `Check` and `Entry` already do.

**Comment by andydotxyz** [comment]
I have a feeling that this might be more of a `Form` feature than a label widget feature.

**Comment by AlbinoGeek** [comment]
To my understanding, the `widget` itself has to support that method `Disable` or `Enable`, or be `Disablable` in the current `widget` system, but I could be wrong.

e.g: the reason you can't add non-`FormItem` to a `Form` currently (whether by design or otherwise) is (to the compiler) because they are missing the `Hide()` method.

I had tested implementing this on my own extended widget and a `Form` technically lets me add arbitrary widgets this way.

**Comment by andydotxyz** [comment]
FormItem is the metadata for a row in a form. It's `Widget` field is a `fyne.CanvasObject` that can be anything.
On the left hand side (the` Label`) our `Form` code could decide to use something other than `Label` to display the text.

**Comment by andydotxyz** [comment]
The `Form` API is based around form features. If you want to arrange custom elements like a form then use `fyne.NewContainerWithLayout(layout.NewFormLayout(), ...)`

**Comment by andydotxyz** [comment]
In form this makes sense and can be handled automatically by the widget - updating title to reflect

**Comment by AlbinoGeek** [comment]
Sounds good! This does make quite a bit of sense, as `Form` was exactly the context of usage (at the time.)

**Comment by andydotxyz** [comment]
Feel free to give the PR a test :)

**Comment by andydotxyz** [comment]
In `release/v2.0.x` branch for testing before v2.0.4 release
