### ISSUE TITLE
Properly align `Label` in a `FormItem`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1531]
### Is your feature request related to a problem? Please describe:
When you have a `Label` and an `Entry` in a `FormItem`, the `Label` is missing top-padding required to bring its text in line with the `Entry`'s text.

#### Example:
![image](https://user-images.githubusercontent.com/1910461/99146001-b90b3980-2628-11eb-8a86-04ec93db4e64.png)
```golang
	updatePeriod := widget.NewEntry()
	updatePeriod.SetText(getUpdateDuration().String())
	// ...
	window.SetContent(widget.NewVBox(
		widget.NewGroup("Updates",
			widget.NewForm(
				widget.NewFormItem("Time Between Checks", updatePeriod),
			),
		),
	))
	// ...
```

### Is it possible to construct a solution with the existing API?
Yes.

### Describe the solution you'd like to see:
Add 3-5 pixels of top padding to `Label` inside a `FormItem`

The baseline of the two pieces of text should match horizontally.

**Comment by stuartmscott** [comment]
This may not be specific to `widget.Form`, instead we may want `canvas.Text` to be drawn in the vertical center of the texture (currently `d.Dot = freetype.Pt(0, height-face.Metrics().Descent.Ceil())`)

**Comment by AlbinoGeek** [comment]
I think that may even fix the issue with `Button` and `Label` alignment if that were the case.

**Comment by andydotxyz** [comment]
On develop for testing :)
