### ISSUE TITLE
Feature request: expose custom cursors 

### ISSUE THREAD

**Issue by MagicalTux** [fyne-io/fyne#1537]
### Is your feature request related to a problem? Please describe:

Fyne currently has a [cursorable desktop api](https://github.com/fyne-io/fyne/blob/master/driver/desktop/cursor.go) that allows overriding the cursor for a given object, using standard cursors created via `glfw.CreateStandardCursor`.

### Describe the solution you'd like to see:

glfw has a `glfw.CreateCursor` api that takes a `image.Image` plus hotspot coordinates, which could allow widgets to expose a custom cursor. Fyne could cache cursors based on either the image.Image address, or using a value that the developer would need to provide (cache id?).

**Comment by andydotxyz** [comment]
It looks like #1548 makes this possible without exposing driver specific capabilities.
