### ISSUE TITLE
Add support for passing custom build tags

### ISSUE THREAD

**Issue by Stoyvo** [fyne-io/fyne#1538]
### Describe the bug:
Fyne offers a package command, however package is also building. In my case, I need to compile my binary with TAGLIB, I use the following:
`go build --tags "darwin libtag" -v`

Fyne package should be responsible for the certificate, versioning, packaging, and the building should be optional, or provide a way to allow additional tags to be configured.

**Comment by andydotxyz** [comment]
You can do this by telling the `fyne` tool that the binary already exists with the `-executable` parameter.
If that file is found it should not trigger a build.

**Comment by Stoyvo** [comment]
@andydotxyz Yes, but the `fyne` tool has its own parameters for windows builds, Eg:
https://github.com/fyne-io/fyne/blob/master/cmd/fyne/commands/build.go#L24
```
	if goos == "windows" {
		if b.release {
			cmd = exec.Command("go", "build", "-ldflags", "-s -w -H=windowsgui", ".")
		} else {
			cmd = exec.Command("go", "build", "-ldflags", "-H=windowsgui", ".")
		}
	} else {
		if b.release {
			cmd = exec.Command("go", "build", "-ldflags", "-s -w", ".")
		} else {
			cmd = exec.Command("go", "build", ".")
		}
	}
```

If we provide that path, these flags aren't set unless we specify them specifically?

**Comment by andydotxyz** [comment]
Yes that is correct. Currently you either build manually, or you get fyne to handle it for you.

**Comment by andydotxyz** [comment]
Perhaps this ticket changes from a bug "Unable to package with custom build tags" to a feature request "Add support for passing custom build tags"?

**Comment by andydotxyz** [comment]
This could be related to https://github.com/fyne-io/fyne-cross/issues/5

**Comment by Stoyvo** [comment]
> Perhaps this ticket changes from a bug "Unable to package with custom build tags" to a feature request "Add support for passing custom build tags"?

@andydotxyz I agree with this, or we can track this as a documentation enhancement to better define what parameters are required for each OS.
