### ISSUE TITLE
[FEATURE REQUEST] `fyne.TextStyle` having a `Face` or similar "Font" property

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1542]
### Is your feature request related to a problem? Please describe:
Currently, we have a lot of elements which you cannot change the FontFace / FontSize of, only the Style.

### Is it possible to construct a solution with the existing API?
No

### Describe the solution you'd like to see:
```golang
// Modify one setting of a default font, for one control
// Copy or Clone, to not edit all instances of the default font
bigFont := theme.DefaultFont().Clone()
bigFont.SetSize(24) // px

// Ability to set the font of any given widget with text
myLabel.SetFont(bigFont)

// Create new Fonts, to load new Faces from the system
monoFont, err := theme.NewFont("Lucidia Console", 24) // Face, Size
if err != nil {
  monoFont, _ = theme.NewFont("monospace", theme.DefaultFont().Size) // fallback
}
myEntry.SetFont(monoFont)
```

### Related:
https://github.com/fyne-io/fyne/issues/1447 - Monospace fonts on `Entry`
https://github.com/fyne-io/fyne/issues/1543 - Ability to load non-system fonts

**Comment by andydotxyz** [comment]
We are exploring an enhanced theme API for 2.0 that will offer better font handling.
However we intent to stick to a semantic API, so `widget.SetFont` may not be our preferred approach.
Instead perhaps adding more detail to `TextStyle` such as `Heading`, `SubHeading` etc, that way your app would remain true to the theme but have more depth to it's display.
Would that satisfy the use-case behind this ticket?

**Comment by AlbinoGeek** [comment]
Of course! `TextStyle` right now only having bools for `Bold` and `Italic` is rather limiting.

That being said, it may be difficult to implement "Styles" inside of `TextStyle` if that makes sense,

Perhaps it would make more sense to reverse that association?

```golang
style := fyne.TextStyle{
  Bold: true,
  Face: "Calibri",
  // no more "Monospace" required if "Face" were a thing
  Size: 24,
}
myTheme.HeadingStyle = style

style.Size = 18
myTheme.SubHeadingStyle = style

// or "Regular" or however you'd refer to "Standard"
myTheme.ParagraphStyle = fyne.TextStyle{
  Face: "Cambria",
  Size: 12,
}
```

**Comment by andydotxyz** [comment]
That is an interesting approach, but it would create a lot more API breakage than we intended with the theme upgrade.
I suspect that a happy-medium might be that the theme API could have some sort of style API that is used to define the setup, but widgets can continue to use a semantic TextStyle.
We need to consider that mobile or web drivers, for example, may wish to interpret the theme and if we reverse the definition that will be impossible

**Comment by AlbinoGeek** [comment]
Totally fair, and Material Design in general does ask for a consistent use of fonts across an application, so it does make sense to set these more-or-less globally (across the theme) -- hence the above concept. With the following exceptional use-case being an issue, without a work-around that I can see:

A `SelectEntry` or `List` of `Label`s each with their own Font Face...)

Think: "Font Dropdown" in a document editor such as Word.

![image](https://user-images.githubusercontent.com/1910461/99183084-495f8200-26ee-11eb-8d2c-95b56fe7660d.png)

Or even a number of `Card` or `Label` showing off fonts.

Think: "Font Preview" in the "Gnome Fonts" program.

![image](https://user-images.githubusercontent.com/1910461/99183054-069daa00-26ee-11eb-9795-c8aeca2321f7.png)

**Comment by AlbinoGeek** [comment]
[ This Use-Case flies in the face of the previous reasoning not to have specifically-customized things: https://github.com/fyne-io/fyne/issues/255 ]

**Comment by andydotxyz** [comment]
I don't see why a feature request to be able to set fonts invalidates our decision to not support per-widget-instance application of custom styles.
Perhaps you can explain your reasoning?

**Comment by AlbinoGeek** [comment]
The application examples I showed cannot be replicated with `fyne` without the ability to arbitrarily set the font of individual elements, at least, not without a considerable work-around.

The lists themselves could be made without this feature, by pre-generating the sample font into images (not using `fyne`), then drawing the results of each font render directly onto a `Canvas` (eww, but it would work.)

What doesn't work at all, are applications that rely on multiple fonts in the same context, a great example would be rich text editors in general such as Microsoft PowerPoint/Word, LibreOffice Impress/Writer, even WordPad. -- These explicitly require some ability to set different fonts to individual elements within the same application (unless say... you go the route of pre-rendering every edit element, which would get clunky fast in the context of a rich text editor.)

**Comment by andydotxyz** [comment]
How does this relate to #255? That is what confused me about your previous comment.

**Comment by AlbinoGeek** [comment]
The relation to #255 was the original ask for a `TextFont() Resource` -- and a quote about consistency made by you some time ago (which found its way into StackOverflow and such, that `fyne`'s basic design principles were consistency over customization.) -- That being said, I cannot find the exact quote at the moment -- so can chalk that up to "not related".

**Comment by andydotxyz** [comment]
I'm going to push  this discussion back to #808 as it discusses the underlying `Text` implementation which needs work in v2.0
