### ISSUE TITLE
[FEATURE REQUEST] `LoadFont(name, uri)`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1543]
### Is your feature request related to a problem? Please describe:
Please see the base issue, linked below.

### Is it possible to construct a solution with the existing API?
No

### Describe the solution you'd like to see:
```golang
// Some method of loading new fonts (such as those bundled with the program)
// URI matches the format that fyne already uses, content:// for embedded, file:// for real files
err = theme.LoadFont("Custom", "content://custom.ttf") // Name, URI
customFont := theme.NewFont("Custom", 12)
myButton.SetFont(customFont)
```

### Related:
https://github.com/fyne-io/fyne/issues/1542 - Ability to `SetFont` on widgets

**Comment by andydotxyz** [comment]
Fonts are embedded as a `Resource` - the `storage.LoadResourceFromURI` function can load them from a `URI` providing the function you show above.

**Comment by AlbinoGeek** [comment]
Wonderful! Then assuming there was a way to refer to these within a `TextStyle` as we spoke in the other issue, this request would be solved with that + `storage.LoadResourceFromURI`

**Comment by andydotxyz** [comment]
Cool. At this time theme is the only thing that can set font, but that I guess is the ongoing conversation in #1542
