### ISSUE TITLE
Why is `release/1.4.x` ahead of `master` and behind `develop`?

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1544]
This seems like an interesting organizational choice, is there a particular reason for this?

When I include (via `go get`) `fyne`, which branch am I really getting?

**Comment by andydotxyz** [comment]
Master tracks the latest release, `go get` will use this branch and always access the latest release.
The `release/xxx` branches track development towards a future release, once that is final it is merged to master.

This is pretty much "Git Flow" https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by andydotxyz** [comment]
This way we can keep release preparation on a branch and mainline development on another (`develop`) without impacting the stability of to developers who are still using GOPATH and accessing the head of our default branch.

**Comment by AlbinoGeek** [comment]
Ahh, this makes more sense now. I was confused as the `main` status said "1.4" was stable, then leading me to believe that `release/1.4.x` might be said stable.
