### ISSUE TITLE
Feature request: add invisible cursor to options

### ISSUE THREAD

**Issue by MagicalTux** [fyne-io/fyne#1548]
### Is your feature request related to a problem? Please describe:
This is linked to #1537 but should be trivial to implement and will allow a workaround for that issue in the meantime

The idea would be to create a new EmptyCursor or NullCursor or TransparentCursor (take your pick) option that would be just a transparent image

This would allow working around custom cursors by using a canvas to show the cursor on screen, and would also be useful for games/etc when in fullscreen

**Comment by andydotxyz** [comment]
On `develop` for testing and release in whatever the next major release.
We could consider cherry-picking it into 1.4.2 if folk think this is a bug-fix release sort of addition
