### ISSUE TITLE
fyne_demo does not start in macos

### ISSUE THREAD

**Issue by claudio-ortega** [fyne-io/fyne#1555]
### Bug description:
fyne_demo crashes on start

### Reproducing steps:
1. produce fyne_demo on a mac development environment following the site instructions, exactly as follows
            (@develop)
            go get fyne.io/fyne/cmd/fyne_demo
2. verify the executable is produced under ~/go/bin
            (@develop)
            file ~/go/bin/fyne_demo
            /Users/clortega/go/bin/fyne_demo_2: Mach-O 64-bit executable x86_64
3. execute ~go/bin/fyne_demo, verify it comes up just fine
            (@develop)
            ~/go/bin/fyne_demo
            (no stderr/out, and the ui shows up just fine)
4. copy ~go/bin/fyne_demo into a second mac os with no development environment.
            (@develop)
            scp ~/go/bin/fyne_demo clortega@target:~/tmp
5. in the non-development environment execute fyne_demo
            (@ target)
            cd ~/tmp
            chmod +x fyne_demo
            ./fyne_demo
6. expected: the same result as in the development environment
    observed: the GUI does not come up, output to console follows 

console output begin -----
./fyne_demo 
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /Users/facundoortega/jambridge2/./fyne_demo (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
dyld: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /Users/facundoortega/jambridge2/./fyne_demo (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
SIGABRT: abort
PC=0x55603ba m=0 sigcode=0
signal arrived during cgo execution
...
clip()
...
console output end -----

### Device
 - OS: 
development (@develop)
   macOS Catalina 10.15.7
   (go and Xcode were both installed as described in Fyne site)
target non-development (@target)
   (macOS Mojave 10.14.6  (no go neither Xcode were installed in here)

 - Go version:
development: (@development)   go1.15.3 darwin/amd64
non-development: (@target) none

 - Fyne version: 1.4.0

find ~/go | fgrep fyne | fgrep .mod | fgrep "@" | cat -n
     1	/Users/clortega/go/pkg/mod/cache/download/fyne.io/fyne/@v/v1.4.0.mod
     2	/Users/clortega/go/pkg/mod/cache/download/github.com/fyne-io/mobile/@v/v0.1.1.mod
     3	/Users/clortega/go/pkg/mod/fyne.io/fyne@v1.4.0/go.mod
     4	/Users/clortega/go/pkg/mod/github.com/fyne-io/mobile@v0.1.1/go.mod

**Comment by andydotxyz** [comment]
I think this relates to a known issue where you will have to specify the older macOS target version in compile options if you want to simply copy the file to another computer.

**Comment by andydotxyz** [comment]
It would help if you include the command you used to compile as well

**Comment by andydotxyz** [comment]
I think duplicate of #1327

**Comment by claudio-ortega** [comment]
Hi Andy,
Congratulations on this achievement. This library is exactly what a lot of people, myself included, are looking for.
Reading on #1327 looks like the issue was fixed and the fix will also solve my problem. Is that correct understanding?
If that would be the case, I wonder why the issue remains open. 
My apologies if I missed it, but is there anywhere in the doc any mention of how to build for all macOS platforms starting at a certain version? (ie: the info included and referenced from #1327). I would consider that info essential given the fact that we really do not have a clue on how our users are spread out on all macOS versions out there.

**Comment by claudio-ortega** [comment]
forgot to mention, I will follow #1327 and update this ticket with the result

**Comment by claudio-ortega** [comment]
the fix in #1327 fixed the  issue
repeated the test on 10.13.6 High Sierra, and also worked fine
you may close the ticket

**Comment by claudio-ortega** [comment]
closing, seems fixed.
