### ISSUE TITLE
Cygwin compile not found

### ISSUE THREAD

**Issue by archistico** [fyne-io/fyne#1560]
### Describe the bug:
Compile not found in Cygwin, TDM, Mingw... 

### To Reproduce:
go get fyne.io/fyne/cmd/fyne_demo

> fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:
go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function 'createMonitor':
go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function 'wcscpy' [-Wimplicit-function-declaration]
   68 |     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
      |     ^~~~~~
go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function '_glfwPlatformIsSameMonitor':
go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
  228 |     if (wcslen(first->win32.displayName))
      |         ^~~~~~
go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
  229 |         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
      |                ^~~~~~
> fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

go: failed to remove work dir: GetFileInformationByHandle C:\Users\Archemi\AppData\Local\Temp\go-build883489594\NUL: Funzione non corretta.

### Device (please complete the following information):
 - OS: Windows 10
 - Version: 10 Pro
 - Go version: 1.13.1
 - Fyne version: last

**Comment by andydotxyz** [comment]
This looks like a very old version of fyne

**Comment by archistico** [comment]
after:
> go get -u all

> fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

go: failed to remove work dir: GetFileInformationByHandle C:\Users\Archemi\AppData\Local\Temp\go-build190635918\NUL: Funzione non corretta.

**Comment by andydotxyz** [comment]
It looks like you might have installed a unix GCC instead of the windows one - can you confirm the output of 
```
gcc -dumpmachine
```

**Comment by andydotxyz** [comment]
Additionnally following hints aat `https://github.com/golang/go/issues/36000` it is possible you have an unsupported path somewhere, though I can't see one in the output you pasted

**Comment by benitogf** [comment]
maybe there should be a link to https://jmeubank.github.io/tdm-gcc/download/ in the windows installation instructions?

**Comment by andydotxyz** [comment]
It is listed at https://developer.fyne.io/started/ @benitogf - which page do you think lacks it?

**Comment by benitogf** [comment]
@andydotxyz my bad, didn't see it here https://developer.fyne.io/index.html

**Comment by andydotxyz** [comment]
Looks like this was not an issue

**Comment by archistico** [comment]
"Install Gcc" it seems the simplest thing but it is not
In Win10 is not simply, dependency, path, 32/64, lib, ...

**Comment by andydotxyz** [comment]
There are some more hints at our getting started page - https://developer.fyne.io/started/.
If you want more details there is an appendix on setting up compilers in the Fyne book https://www.packtpub.com/product/building-cross-platform-gui-applications-with-fyne/9781800563162

**Comment by archistico** [comment]
Is possible problem execute this command  "pacman -S --needed base-devel mingw-w64-x86_64-toolchain" after installation MSYS2 with MingW-w64?
:: Retrieving packages...
error: failed retrieving file 'mingw-w64-x86_64-libiconv-1.16-2-any.pkg.tar.zst' from downloads.sourceforge.net : Operation timed out after 10005 milliseconds with 0 out of 0 bytes received
 mingw-w64-x86_64...   744.5 KiB   313 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...   101.4 KiB   441 KiB/s 00:00 [#####################] 100%
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.36.1-1-any.pkg.tar.zst' from downloads.sourceforge.net : Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
 mingw-w64-x86_64...     7.1 MiB   562 KiB/s 00:13 [#####################] 100%
error: failed retrieving file 'mingw-w64-x86_64-headers-git-9.0.0.6105.f3855e2c-1-any.pkg.tar.zst' from downloads.sourceforge.net : Operation timed out after 10003 milliseconds with 0 out of 0 bytes received
 mingw-w64-x86_64...     5.2 MiB   784 KiB/s 00:07 [#####################] 100%
 mingw-w64-x86_64...     3.2 MiB   794 KiB/s 00:04 [#####################] 100%
 mingw-w64-x86_64...   870.6 KiB   814 KiB/s 00:01 [#####################] 100%
 mingw-w64-x86_64...   501.7 KiB   822 KiB/s 00:01 [#####################] 100%
 mingw-w64-x86_64...   357.1 KiB   685 KiB/s 00:01 [#####################] 100%
 mingw-w64-x86_64...    72.7 KiB   727 KiB/s 00:00 [#####################] 100%
 mingw-w64-x86_64...    29.4 KiB  1470 KiB/s 00:00 [#####################] 100%
 mingw-w64-x86_64...   756.8 KiB   788 KiB/s 00:01 [#####################] 100%
 mingw-w64-x86_64...    12.9 KiB  1289 KiB/s 00:00 [#####################] 100%
error: failed retrieving file 'mingw-w64-x86_64-winpthreads-git-9.0.0.6105.f3855e2c-1-any.pkg.tar.zst' from downloads.sourceforge.net : Operation timed out after 10008 milliseconds with 0 out of 0 bytes received

**Comment by andydotxyz** [comment]
This is a server / network issue. Please wait and try later.

**Comment by archistico** [comment]
It work!!!!!!!! Ole

all:
`download msys2-x86_64-20210215.exe`
install
In "MSYS2 MSYS"
`pacman -Syu`
`pacman -Su`
`pacman -S --needed base-devel mingw-w64-x86_64-toolchain` x2 in my case
close "MSYS2 MSYS"
open "MSYS2 MinGW 64-bit"
`echo 'export PATH=/c/Go/bin:$PATH' >> ~/.bashrc`
`pacman -S git`
`go get fyne.io/fyne/v2`
`go get fyne.io/fyne/v2/cmd/fyne_demo`
`cd /c/Users/---USERNAME WINDOWS---/go/src/fyne.io/fyne/v2/cmd/fyne_demo`
`go run main.go`
