### ISSUE TITLE
how to view big json text

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#1563]
![image](https://user-images.githubusercontent.com/19886504/99353603-cf8eea80-28df-11eb-8a15-835749e91014.png)

**Comment by AlbinoGeek** [comment]
Have you tried wrapping your multiline entry in a `VScrollContainer` ?

```golang
widget.NewVScrollContainer()

**Comment by DiskGetor** [comment]
> 您是否尝试过将多行条目包装在中`VScrollContainer`？
> 
> ```go
> 小部件。NewVScrollContainer（myEntry）
> ```

i will try,thank you very much.

**Comment by DiskGetor** [comment]
> 您是否尝试过将多行条目包装在中`VScrollContainer`？
> 
> ```go
> 小部件。NewVScrollContainer（myEntry）
> ```

H or V is not well to me, so i set fix size, but it do not work for me.

fix := container.NewScroll(e)
			fix.Resize(fyne.Size{
				Width:  600,
				Height: 600,
			})
			return container.NewTabItem("json",
				container.NewVBox(b, fix))

![image](https://user-images.githubusercontent.com/19886504/99369061-ebea5180-28f6-11eb-88ae-fabd55c0301b.png)

**Comment by andydotxyz** [comment]
The size of the container is set by it's parent, at least the widget minimum size.
Once you have placed the text inside `container.NewScroll` the container that it iss within will set the current size.
It looks like you are using a VBox, which will always shrink height - so perhaps try Border layout instead?
The different arrangement can be seen at https://developer.fyne.io/started/layouts

**Comment by DiskGetor** [comment]
> 容器的大小由其父项设置，至少是小部件的最小大小。
> 将文本放置在`container.NewScroll`其所在的容器内后，将设置当前大小。
> 看起来您正在使用VBox，它将始终缩小高度-因此，也许可以尝试使用Border布局？
> 可以在[https://developer.fyne.io/started/layouts中](https://developer.fyne.io/started/layouts)看到不同的安排[](https://developer.fyne.io/started/layouts)

thank you very much ,i will try.

**Comment by DiskGetor** [comment]
> 容器的大小由其父项设置，至少是小部件的最小大小。
> 将文本放置在`container.NewScroll`其所在的容器内后，将设置当前大小。
> 看起来您正在使用VBox，它将始终缩小高度-因此，也许可以尝试使用Border布局？
> 可以在[https://developer.fyne.io/started/layouts中](https://developer.fyne.io/started/layouts)看到不同的安排[](https://developer.fyne.io/started/layouts)

good,you are very cool,thank you again.
![image](https://user-images.githubusercontent.com/19886504/99390466-a2f4c600-2913-11eb-88e4-dacb99c3fe0b.png)
