### ISSUE TITLE
[BUG] VBox + Wrapping = Large Vertical Gap

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1565]
### Summary

Creating a VBox that contains a `Label` with wrapped text, results in the VBox taking on the minimum height as if the text were not wrapped, resulting in a large blank space shown below it. This happens inside a window, modal, or dialog all the same.

### Code
```golang
func (w *windowSettings) openLogin() {
	user := widget.NewEntry()
	pass := widget.NewPasswordEntry()

	warning := widget.NewLabel("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.")
	warning.Wrapping = fyne.TextWrapWord
	// tried resizing the warning itself, and the space cannot be removed

	vbox := widget.NewVBox(
		warning,
		widget.NewForm(
			widget.NewFormItem("Email", user),
			widget.NewFormItem("Password", pass),
		),
	)
	// tried to resize it here, and the space cannot be removed
	
	dlg := dialog.NewCustomConfirm("Login to sc2replaystats", "Login", "Cancel", vbox, func(ok bool) {
		if ok {
		}
	}, w)

	// if we resize it any earlier, the vertical space cannot be removed
	vbox.Resize(fyne.NewSize(999, 300)) // only the height is respected, not the width!

	// the dialog also needs to be resized now as a result
	// only resizing the dialog does not work, the vbox (due to Label) forces height otherwise
	dlg.Resize(fyne.NewSize(420, 300)) // both values respected here
	dlg.Show()
}
```

### Result
![image](https://user-images.githubusercontent.com/1910461/99366142-0e378d00-286d-11eb-8dd3-b66f31584911.png)

**Comment by andydotxyz** [comment]
What space are you referring to? The image provided seems correct to me

**Comment by andydotxyz** [comment]
Remember, resizing a widget that is contained within a parent layout will do nothing, as the container is controlling the size of the child widgets.

**Comment by andydotxyz** [comment]
Perhaps I misunderstood - "results in the VBox taking on the minimum height as if the text were not wrapped" - I imagined you were saying that the content were not tall enough.
Can you please remove all the Resizes and re-post the code with a descrition of what is not correct.

**Comment by andydotxyz** [comment]
*Update*

I cannot replicate this in the content of a window, which was listed as one of the ways it is broken above.

**Comment by AlbinoGeek** [comment]
Without the resizes, the result is the screen-shot -- which is what I was trying to show (and didn't explain clearly.)

I have stopped using wrap across the application, I will have to try and see again if this happens in a window.

If not, that would make this a Dialog/Modal issue.

**Comment by andydotxyz** [comment]
Once you have investigated can you please post the minimal code to replicate the issue.
It is not clear how the code above would be used, or which lines should be removed as well.
Anything that makes it easier for us to see the problem makes it easier to resolve ;)

**Comment by AlbinoGeek** [comment]
#1570 may well get to the root of this bug -- but in the off chance these are actually two different bugs, I won't close this yet. I have included full reproduction code in that post, and will work on paring down the issue to reply here specifically to this issue.

**Comment by andydotxyz** [comment]
I can no longer replicate this on `develop`, we re-wrote some text handling code which probably fixed it, so closing.
