### ISSUE TITLE
Some errors accured when i run the demo

### ISSUE THREAD

**Issue by jzyzxx** [fyne-io/fyne#1567]
### Describe the bug:

when i run the demo,there are some errors ,there are logs:
# fyne.io/fyne/vendor/golang.org/x/image/vector
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:142: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:144: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:215: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:217: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:330: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:332: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:366: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:368: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:460: unrecognized instruction "PABSD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:462: unrecognized instruction "PMINUD"
..\..\vendor\golang.org\x\image\vector\acc_amd64.s:494: unrecognized instruction "PABSD"
asm: too many errors
# fyne.io/fyne/driver/desktop
..\..\driver\desktop\shortcut.go:21:9: undefined: strings.Builder
# fyne.io/fyne/storage
..\..\storage\uri.go:29:10: undefined: strings.ReplaceAll
..\..\storage\uri.go:30:10: undefined: strings.ReplaceAll
# fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ..\..\vendor\github.com\go-gl\gl\v3.2-core\gl\package.go:27:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.3/glfw
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ./glfw/src/win32_platform.h:68,
                 from ./glfw/src/internal.h:186,
                 from ./glfw/src/context.c:30,
                 from ..\..\vendor\github.com\go-gl\glfw\v3.3\glfw\c_glfw.go:4:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
# fyne.io/fyne/layout
..\..\layout\gridlayout.go:63:13: undefined: math.Round

### Device (please complete the following information):
 - OS: windows 10
 - Version: latest
 - Go version: 1.9.7
 - Fyne version: latest

**Comment by andydotxyz** [comment]
We require Go 1.12, as described at https://developer.fyne.io/started/

**Comment by jzyzxx** [comment]
> We require Go 1.12, as described at https://developer.fyne.io/started/

at least version 1.12,should  golang version be larger than 1.12?
