### ISSUE TITLE
Dynamic library dependency issue

### ISSUE THREAD

**Issue by objarni** [fyne-io/fyne#1571]
### Describe the bug:

When building Hello World app on Ubuntu 20.04 I got this error message:

```
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status
```

I managed to work-around this issue by doing this:

```
sudo apt install libxxf86vm-dev
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Follow steps in https://www.youtube.com/watch?v=-v1vz_NcWng
2. go run main.go
3. Crash

### Example code:

```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("hello")
	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Ubuntu (linux/amd64)
 - Version: 20.04 (up-to-date as of 2020-11-17)
 - Go version: 1.13.8
 - Fyne version: [e.g. 1.2.0 or git SHA]

**Comment by andydotxyz** [comment]
That should have been installed by the `apt-get install` command that is listed at https://developer.fyne.io/started/.
This is just a development dependency and is not required by the users of your app.

**Comment by objarni** [comment]
Thank you for your response.

I used this command line to install fyne:

    go get fyne.io/fyne

Is that not supposed to be sufficient?

**Comment by andydotxyz** [comment]
The command you post prepares the library, however if you don't have developer tools installed it can fail to compile.
On most operating systems that should work out of the box, but Linux is a little complicated and needs the developer libraries installed as listed in the documentation.

**Comment by objarni** [comment]
Thanks again for pointing me in right direction.

Could you elaborate on this one:

"This is just a development dependency and is not required by the users of your app."

If I distribute the binary "hello" would others not need to install development dependencies?

**Comment by andydotxyz** [comment]
> If I distribute the binary "hello" would others not need to install development dependencies?

Yes this is exactly correct.
The reason you need development dependencies to run the hello world is because the "go get" command is building it from source. Distributed apps will typically be compiled and packaged, meaning no need for go tools or dependencies.

**Comment by objarni** [comment]
Ok, is there a go command to make the distributable version of hello binary then?

**Comment by andydotxyz** [comment]
`go build` will build a binary file you can share. 
If you want to package a full desktop app with metadata etc then `fyne package` is your friend, see https://developer.fyne.io/started/distribution

**Comment by Jacalz** [comment]
Just to clarify. The development dependencies are statically linked into the binary. That’s rather technical, but the consequence is basically that the compiled binary includes the needed dependencies. That is why they are only needed when you are compiling 🙂

**Comment by objarni** [comment]
@Jacalz thank you for explaining this even clear. This will help people googling about this behaviour in the future 🌱

**Comment by objarni** [comment]
To summarize this for future reference:

1. -dev libraries are needed when using "go run" and "go build" commands, since the static libraries are included in the result binary/executable.
2. Therefore, running the resulting binary/application on another machine does not require those librarie / dev packages.

FYI - the resulting "main" executable was 17 mb on my machine, and it was possible to run it even after `sudo apt-get remove libgl1-mesa-dev xorg-dev`, as expected. I also found the "upx-ucl" utility for Ubunto to compress the binary, so it is now down to 9 mb. Nice!
