### ISSUE TITLE
When i run the demo,there are some erros accoured.

### ISSUE THREAD

**Issue by jzyzxx** [fyne-io/fyne#1572]
### To Reproduce:
Steps to reproduce the behaviour:

### Example code:

go run main.go,then some error accoured,there are logs:
```
PS D:\gopath\src\fyne.io\fyne\cmd\fyne_demo> go run main.go
# github.com/go-gl/glfw/v3.3/glfw
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from ./glfw/src/win32_platform.h:68,
                 from ./glfw/src/internal.h:186,
                 from ./glfw/src/context.c:30,
                 from C:\Users\DELL\go\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20200625191551-73d3c3675aa3\c_glfw.go:4:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
# github.com/go-gl/gl/v3.2-core/gl
In file included from D:/MinGW/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from D:/MinGW/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:\Users\DELL\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20190320180904-bf2b1f2f34d7\v3.2-core\gl\package.go:27:
D:/MinGW/mingw64/x86_64-w64-mingw32/include/winnt.h:1554:11: fatal error: x86intrin.h: No such file or directory
 # include <x86intrin.h>
           ^~~~~~~~~~~~~
compilation terminated.
```

### Device (please complete the following information):
 - OS: windows10
 - Version: latest
 - Go version: 1.15
 - Fyne version: latest

**Comment by andydotxyz** [comment]
Can you please confirm the architecture / CPU of the computer?

Also please confirm which GCC is being invoked and how long ago you installed mingw_w64?
It looks like this file failure is deep within your mingw install and not a bug in Fyne I'm sorry to say.

**Comment by jzyzxx** [comment]
> Can you please confirm the architecture / CPU of the computer?
> 
> Also please confirm which GCC is being invoked and how long ago you installed mingw_w64?
> It looks like this file failure is deep within your mingw install and not a bug in Fyne I'm sorry to say.

Here is my go env:set GO111MODULE=on
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOCACHE=C:\Users\DELL\AppData\Local\go-build
set GOENV=C:\Users\DELL\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\DELL\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\DELL\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\DELL\AppData\Local\Temp\go-build403236854=/tmp/go-build -gno-record-gcc-switches
