### ISSUE TITLE
How to extend a Container or Layout?

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1574]
I would like to dynamically fill a container or layout with information that updates with a given datasource, in a self-managed way, where I can simply create and call the component with my datasource in its constructor.

Originally, I was going to replicate this with a `Table`, but noticed fairly quickly that this was not possible to mutate the cells within (does not expose them, so I am left to keep references upon `Update`, because `Create` doesn't tell me the Col/Row...) -- I was also limited to exactly one kind of widget.

---

Instead, I need to make a list with various kinds of widgets, an example layout might be:

```
| ButtonWithIcon Label Label             ButtonWithIcon |
```

I can current create this layout using a `ContainerWithoutLayout` (manually sizing and positioning everything), which I wouldn't mind if I could re-use it (e.g: by extending a Container or Layout.)

![image](https://user-images.githubusercontent.com/1910461/99630057-07845380-29ee-11eb-850f-4db5856cd3ac.png)

The result itself still leaves quite a lot to wish for, like being able to pack them closer together, highlight rows, etc -- the things that you would normally get from a `Table` in another UI framework.

```golang
	// region is generated dynamically, but the below is an example value
	region := map[string]string{"1": "NA","2": "EU","3": "KR"}

	// tl is generated dynamically, but the below is an example value
	tl := map[string][]string{"80577413":[]string{"1-S2-1-3815961", "2-S2-1-6240001", "3-S2-1-6868608"}, "sdf":[]string{"S-1-foo", "S-2-bar", "S-3-baz"}}

	accList := fyne.NewContainerWithLayout(
		layout.NewVBoxLayout(),
	)

	for acc, list := range tl {
		accList.Add(widget.NewLabelWithStyle(fmt.Sprintf("Account #%s", acc), fyne.TextAlignLeading, fyne.TextStyle{Bold: true}))
		for i, toon := range list {
			vis := widget.NewButtonWithIcon("", theme.VisibilityIcon(), func() {
				fmt.Printf("Hide/Show [%s][%d]\n", acc, i)
			})
			vis.Resize(fyne.NewSize(24, 24))
			vis.Move(fyne.NewPos(2, 2))

			parts := strings.Split(toon, "-")

			tLabel := widget.NewLabel(region[parts[0]])
			tLabel.Move(fyne.NewPos(vis.Size().Width+8, 0))

			aLabel := widget.NewLabel("Unknown Account")
			for _, p := range players {
				if parts[len(parts)-1] == strconv.Itoa(int(p.Player.CharacterID)) {
					aLabel.SetText(p.Player.Name)
				}
			}
			aLabel.Move(fyne.NewPos(64, 0))

			del := widget.NewButtonWithIcon("", theme.DeleteIcon(), func() {
				fmt.Printf("Delete [%s][%d]\n", acc, i)
			})
			del.Resize(fyne.NewSize(32, 32))
			// ! 420 because I can't get the window's width... w.Canvas().Size() returns 0,0 !
			del.Move(fyne.NewPos(420-del.Size().Width-16, -2))

			container := fyne.NewContainerWithoutLayout(vis, tLabel, aLabel, del)
			accList.Add(container)
		}
	}
	
	tc := container.NewAppTabs(
		container.NewTabItemWithIcon("Accounts", theme.VisibilityIcon(),
			accList,
		),
	)
	w.SetContent(tc)
```

**Comment by andydotxyz** [comment]
The design for table is that if you want to change a cell (due to data changes one assumes) you call `Table.Refresh()` which will then call `Update` for each of the visible cells. If the cells you are changing are visible the callback will fire - if they are not you don't have to do anything.
This is how the collection widgets (list, table, tree) are designed. If you know specificaly which cell yuou want to update I suppose we could expose a call to update a single cell. We don't expose them, or recommend retaining a reference, beccause of the way they are re-used in the caching mechanism.

This is a break from how other, smaller, widgets work because of the data sizes that they are designed to handle.

**Comment by andydotxyz** [comment]
> - I was also limited to exactly one kind of widget.

We intend to fix this over the coming releases - all three collection widget types could benefit from "header", "divider" or just different types of content. We just need to figure out how to handle multiple cell caches and identify which to use.

**Comment by andydotxyz** [comment]
In answer to your question, however. Layouts are trivial and cannot be extended - you can drop your own one in simply, just follow the docs at https://developer.fyne.io/tutorial/custom-layout.

Looking at your example image I would recommend a `container.NewVBox` where each item in the container is either the `Label` header, or a `container.NewBorder()` that builds the row, some icons on the left, some on the right and the content label filling the middle.
And then if you imagine the list being long you could wrap the whole thing in a `container.NewScroll`

**Comment by AlbinoGeek** [comment]
Your recommendation on using `container.NewBorder()` has gotten me closer, although the fact that `Label`, `Entry` and `Button` do not share baseline makes it look rather messy:

There is also even more dead space than when I was using a manual layout, too much padding overall.

I may have to use a Custom Layout for this -- but the reason I asked to extend a layout, is otherwise I want it to act 99% like an existing layout, whereby I only modify one property (such as padding, or overriding `MinSize`, etc.)

### Result

![image](https://user-images.githubusercontent.com/1910461/99719344-080a0200-2a61-11eb-965b-5e5dfc43ca57.png)

### Code

```golang
			accList.Add(
				container.NewBorder(nil, nil,
					// Left
					container.NewHBox(
						widget.NewButtonWithIcon("", theme.VisibilityIcon(), func() {
							fmt.Printf("Hide/Show [%s][%d]\n", acc, i)
						}),
						widget.NewLabel(region[parts[0]]),
					),
					// Right
					widget.NewButtonWithIcon("", theme.DeleteIcon(), func() {
						fmt.Printf("Delete [%s][%d]\n", acc, i)
					}),
					// Middle
					aLabel,
				),
			)
```

### What I mean about baselines

![baseline](https://user-images.githubusercontent.com/1910461/99719791-a26a4580-2a61-11eb-88d8-cf5675f796e4.png)

**Comment by andydotxyz** [comment]
Layout only has 2 methods, MinSize and Layout. If you want to build your own layout and only override one of these you can embed the layout you wish and return it's answer where appropriate. Layouts retain no state so this should be simple.

The baselines should be tidied up with theme overview in 2.0 to be more consistent - Entry will be overhauled so we did not want to do it before.

The "dead space" is padding, set by the theme. If you want items to be less padded then you could load a custome theme with a smaller padding value. By design however this will impact your whole app.

**Comment by AlbinoGeek** [comment]
Solved in other issues:

- Collection widget sizing
- Problem with Card MinSize

Open in other issues:

- Baseline padding mismatch
