### ISSUE TITLE
why table lost one row?

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#1575]
![image](https://user-images.githubusercontent.com/19886504/99631719-064b3900-2a77-11eb-9713-344c05810b61.png)
package UI

import (
	"fmt"
	"fyne.io/fyne"
	"fyne.io/fyne/container"
	"fyne.io/fyne/widget"
)

func softWindow(w fyne.Window) fyne.CanvasObject {
	soft := &widget.Table{ //创建模板?
		BaseWidget: widget.BaseWidget{},
		Length: func() (int, int) {
			o := widget.TableCellID{
				Row: 8, //行
				Col: 7, //列
			}
			return o.Row, o.Col
		},
		CreateCell: func() fyne.CanvasObject {
			return widget.NewButton("默认", func() {})
		},
		UpdateCell: func(id widget.TableCellID, template fyne.CanvasObject) {
			b := template.(*widget.Button)
			//00 01 02
			//10 11 12
			//20 21 22
			switch id { //操作第一排
			case widget.TableCellID{Row: 0, Col: 0}:
				b.SetText("排0")
			case widget.TableCellID{Row: 0, Col: 1}:
				b.SetText("排1")
			case widget.TableCellID{Row: 0, Col: 2}:
				b.SetText("排2")
			case widget.TableCellID{Row: 0, Col: 3}:
				b.SetText("排3")
			case widget.TableCellID{Row: 0, Col: 4}:
				b.SetText("排4")
			case widget.TableCellID{Row: 0, Col: 5}:
				b.SetText("排5")
			case widget.TableCellID{Row: 0, Col: 6}:
				b.SetText("排6")
			case widget.TableCellID{Row: 0, Col: 7}:
				b.SetText("排7")
			case widget.TableCellID{Row: 0, Col: 8}:
				b.SetText("排8")

			default:
				b.SetText("R" + fmt.Sprint(id.Row) + " C" + fmt.Sprint(id.Col))
			}
		},
		OnSelected: func(id widget.TableCellID) {
			switch id.Col {
			case 0:
				//dialog.ShowColorPicker("ok", "ok", nil, w)
			}
		},
		OnUnselected: func(id widget.TableCellID) {

		},
	}
	return container.NewAppTabs(
		container.NewTabItem("软件", soft),
		//container.NewTabItem("网站", soft),
	)
}

**Comment by okratitan** [comment]
Columns are horizontal and using table you specified Cols: 7 so this is accurate. Rows are vertical.

**Comment by DiskGetor** [comment]
> 列是水平的，并且使用表指定了列：7，因此很准确。行是垂直的。

thank you

**Comment by andydotxyz** [comment]
> Columns are horizontal and using table you specified Cols: 7 so this is accurate. Rows are vertical.

I think this is the wrong way round. But the point is correct, you asked for 7 columns, which is what was rendered.
