### ISSUE TITLE
container.NewAppTabs over flow

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#1576]
![image](https://user-images.githubusercontent.com/19886504/99667905-00ba1700-2aa8-11eb-8be9-21e58aedb9d1.png)

**Comment by andydotxyz** [comment]
The BorderLayout `MinSize()` will return the total required to display the child elements correctly, this is not a bug.
The problem displayed above is that your window is not large enough to contain the content defined.
Normally you could add a `container.NewScroll` - but it looks like that might be a tab container in use.
You probably require a fix that we are working on: #371 (this will know when there is no space left, and add extra tabs to an overflow menu)

**Comment by andydotxyz** [comment]
Probably duplicate of #371

**Comment by DiskGetor** [comment]
yeah,container.NewAppTabs.
