### ISSUE TITLE
`Header` / `BigLabel`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1582]
### Is your feature request related to a problem? Please describe:
I find myself (ab)using `widget.NewCard("Title","",nil)` a lot to draw a big `Label`

### Describe the solution you'd like to see:
```golang
// Either 1) A new widget
widget.NewHeader("Foo")

// 2) A new widget with a more straight-forward name
widget.BigLabel("Foo")

// 3) Something about TextStyle controlling size...
widget.NewLabelWithStyle("Foo", theme.TextStyleHeader)
```

**Comment by andydotxyz** [comment]
Yes, this is the intention of additional text styles we will be adding in 2.0, see https://github.com/fyne-io/fyne/wiki/Theme-API-2.
This will allow new sizes to be added to the theme which currently cannot be done without breaking the backward compatibility

**Comment by stuartmscott** [comment]
Does bolding the label suffice until 2.0 is released?
```go
widget.NewLabelWithStyle(text, fyne.TextAlignLeading, fyne.TextStyle{Bold:true})
```

**Comment by AlbinoGeek** [comment]
@stuartmscott Well, it doesn't make the text any larger-- but this does (my current workaround):

```golang
func newHeader(text string) fyne.CanvasObject {
	return widget.NewCard(text, "", nil)
}
```

**Comment by andydotxyz** [comment]
You could also use `canvas.Text` which support custom size and styles - but you would need to manage the padding and colours according to the loaded theme for it to match the other `Label` elements in your app.

This is because the `canvas` package is the draw technology whereas the `widget` package is the standard components implemented to match the loaded theme.

**Comment by stuartmscott** [comment]
Underneath the hood Card is using canvas.Text and explicitly sets it up as Andy says;
```go
header := canvas.NewText(title, theme.TextColor())
header.TextSize = int(float32(theme.TextSize()) * 1.7)
header.TextStyle.Bold = true
```

**Comment by AlbinoGeek** [comment]
I would say this is solved, I've wrapped `canvas.NewText` for convenience functions, and that has worked well.
