### ISSUE TITLE
Add Missing Icons

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1583]
Specifically, these are icon groups that already exist, but were missing 1-2 icons each:

**Document**
- ~~[ ] `DocumentNew`~~ ( `document-create` already exists )

**Folder**
- ~~[ ] `FolderUp` (traversing to `..`)~~ ( Material Design doesn't have this icon. )

**Media**
- [ ] `MediaStop`

**Other**
- [ ] `Upload`

**Comment by andydotxyz** [comment]
No reason, other than nobody thought to add it, nor asked.
Adding to the queue now.

**Comment by AlbinoGeek** [comment]
Should I make issues for each icon request, or a checklist of icons and rename the issue?

I've found other core missing icons (where others in the same group exist)

E.g: `MediaStopIcon` is also missing.

**Comment by andydotxyz** [comment]
Feel free to make a list in this ticket - as long as they were just overlooked we can add them all.
Adding feature request for a new group if icons would belong in another issue I think.

Of course you'd be welcome top open a pull request to add them as well - we just download them from the matrial design icon collection and embed them in the theme package :)

**Comment by AlbinoGeek** [comment]
Updated* Added icons for existing groups.

Will make a new issue for new groups.

Will dive into code to see if PR would be trivial.

**Comment by andydotxyz** [comment]
`MediaFastRewind` is the opposite of `MediaFastForward` - it is probably the icon you are looking for.
You can preview them in fyne_demo -> "Theme Icons"

**Comment by AlbinoGeek** [comment]
Hmm, it doesn't look like you guys are using the latest material icons -- the SVG argument order, etc is different.

### Material 4.0 `src/download/materialiconssharp/24px.svg` (a.svg)

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>
```

### Fyne `theme/icons/download.svg` (b.svg)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="black" width="18px" height="18px"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>
```

### Diff

```diff
1,2c1,2
< <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
< <path d="M0 0h24v24H0V0z" fill="none"/>
---
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="black" width="18px" height="18px">
> <path d="M0 0h24v24H0z" fill="none"/>
```

The `V0` was optional in this glyph, as it produces the same result without -- but the different width/height (+ explicit px) and the coded fill colour are different. ( Vertical Line draw from cursor to 0 )

![image](https://user-images.githubusercontent.com/1910461/99737080-701a1180-2a7c-11eb-9d49-cdfa1a462c21.png)

---

Should I reformat Material's icons to match that of `fyne` (incl. the 18x18 size) when adding them in my PR?

**Comment by AlbinoGeek** [comment]
Actually, after further investigation, `Download` is one of the only `18px * 18px` icons in `fyne` !

**Comment by AlbinoGeek** [comment]
This was fixed by a PR ... not sure why GitHub didn't auto-close the issue.

**Comment by andydotxyz** [comment]
It wasn't closed beause it was not landed to the default branch.
It will not auto-close until the release is cut, so we normally close manually with a note about which branch it's on
