### ISSUE TITLE
Fyne APP's icon is always bad with different resolution

### ISSUE THREAD

**Issue by apieceof** [fyne-io/fyne#1587]
Hi all Fyne experts,

I am a Fyne and Golang beginner. I am making an APP TOOL for my company. 
I encounter a problem that the APP's ICON appearing on the left corner is always unclear and jagged all the time no matter I shrink(250 x 150) or enlarge(1280 x 1280) image resolution. 
Please check the below cropped simple illustration.
![TEST ONLY_app](https://user-images.githubusercontent.com/74761853/99774890-5bf01600-2b49-11eb-9ee3-e34c3dcd3135.png)

The process I implemented the icon is 
1. Make our company icon (in 1280 x 1280 px) become a StaticResource from "fyne bundle <image_file>" to generated a GO file
2. Simply use Fyne's app libraries to set the resource as icon with app.SetIcon(StaticResource)
3. The icon is so small and unclear. 

Are there any good ways to improve the icon resolution on Fyne?? 
Any advice is highly appreciated. 

[Environment Setup]
VS code: Version: 1.51.1 
Go Version: go1.14.2 windows/amd64
Fyne Version: v1.4.0-3-g0ca05dc1
ICON resolution and format: 1280 *1280, PNG 

Thanks everyone!!

**Comment by andydotxyz** [comment]
Image scaling is complicated and providing more pixels will probably make the result worse.
This icon should be a square (1:1 aspect) and for use in window borders it's likely that 64x64 is large enough.

**Comment by apieceof** [comment]
Hi @andydotxyz , 

Thanks for your comment. I tried your suggestion(64*64 px)  and also other nearest resolution. These results are better than my previous post. 
Thanks!

**Comment by andydotxyz** [comment]
Thanks for confirming, I guess this issue is resolved, though perhaps we could add some way for developers to specify multiple resolutions then the toolkit could do a better job at picking the right one.

**Comment by apieceof** [comment]
Hi Andy, 

Yes. I think so. Maybe the coming future if more similar cases happened, you could add options for users to choose. 
But thanks a lot anyway.

BR
