### ISSUE TITLE
Add some hover effect to widgets

### ISSUE THREAD

**Issue by boussou** [fyne-io/fyne#159]
What about adding some nice hover effect on some of the widgets like the button for the next realease?
As you know, it is when mouse is over some of the widgets, the control background darkens or ligthens.

As they are, the widgets looks fine & sharp but the feel a bit joyless  ;-)

**Comment by andydotxyz** [comment]
This is a great suggestion, thanks.
One reason we have held off is that the core toolkit is designed to be platform independent.
What you have described sounds like a desktop specific feature - do you think it has an equivalent on mobile or mouse-less devices as well?

**Comment by boussou** [comment]
You right.
Btw on desktop I can see nucular [()](https://github.com/aarzilli/nucular) doing it.
It would just be nice to have, I fully agree there are other items far more important (like the scroller for content that goes outside the visible screen).

**Comment by andydotxyz** [comment]
I agree, a nice to have. Let's keep an eye on other things and maybe pull this in or open it for someone to contribute.

For the scrolling though you can use widget.ScrollContainer - that can contain any item that is larger than the space you would like it to occupy...

**Comment by boussou** [comment]
Ok, I did not know. Based on the demo I supposed it was not possible.

**Comment by andydotxyz** [comment]
It is relatively recent - in the demo under "Widgets" -> "Scroll". Can also be seen in the "Input" panel from fyne_demo.

**Comment by andydotxyz** [comment]
I am adding a desktop extension for mouse hover events in #141, perhaps after that we could add support for hover visuals for when applications run on a desktop platform?

**Comment by boussou** [comment]
That would be great.

**Comment by andydotxyz** [comment]
This is available for testing on develop branch https://youtu.be/9klh7PinQ2A

**Comment by boussou** [comment]
Nice !
