### ISSUE TITLE
WebGL Support?

### ISSUE THREAD

**Issue by Geo25rey** [fyne-io/fyne#1598]
### Is your feature request related to a problem? Please describe:

It seems to me that GLFW has support for WebGL and WebAssembly. I'm curious to see why Fyne doesn't support this as well.

### Is it possible to construct a solution with the existing API?

I think this would require some changes to the build tags, but otherwise initial support should be easy? It might be useful to add some emscripten specific functions, though. I found these helpful: [Building WebAssembly with Go](https://github.com/golang/go/wiki/WebAssembly#getting-started),  [small example project](https://github.com/13rac1/starter-wasm-webgl-opengl), and [Emscripten installation instructions](https://emscripten.org/docs/getting_started/downloads.html).

**Comment by andydotxyz** [comment]
Are you sure GLFW has that support? Could you point us to some documentation of how it is used?

**Comment by Geo25rey** [comment]
It looks like GLFW has been compiled with limited support for Emscripten, see [here](https://emscripten.org/docs/porting/emscripten-runtime-environment.html?highlight=glfw)

**Comment by andydotxyz** [comment]
It looks more like the other way round - emscripten has found a way to control GLFW?

**Comment by Geo25rey** [comment]
Emscripten is more like an operating system built on WebAssembly. So, GLFW is compiled to run within Emscripten and then Emscripten runs within a virtual machine AKA the web browser.

**Comment by andydotxyz** [comment]
If you could find any documentation for us we could look into this further.
Apart from a compile flag in GLFW I cannot find any information on how it is supposed to work, sorry.

**Comment by Noofbiz** [comment]
It's actually pretty easy to do without GLFW, you just make an html canvas equal to the dimensions of the window and get the render target and everything from that. The GLFW/Emscripten stuff would be awesome, since it would have just one Go-side API to do everything, but I haven't really seen any go libraries do that.

**Comment by Bluebugs** [comment]
There is some fundamental difference between WebGL and how we use GLFW at the moment. Also the bridge is not a trivial things. There are go library that provide a GLFW API on top of WebGL, but we still need to update our use of GLFW to make this work (Basically WebGL doesn't allow multiple windows and we have no control over the only window being created, it is closer to the mobile logic). GLFW would have to explicitly support WebGL to have it working like they explicitly support Linux, Windows and Mac as it is a difference environment. Compiling GLFW with emscripten is just a first step in that direction and I do not know if the GLFW is going to continue the necessary work to get this working.

**Comment by andydotxyz** [comment]
Closing in favour of #1646, we can track the appropriate implementation details there
