### ISSUE TITLE
Cursor and underline not rendered for embeded Entry

### ISSUE THREAD

**Issue by buck54321** [fyne-io/fyne#1624]
When embedding an `Entry`, the cursor and underline are not displayed. 

```
func main() {
	a := app.New()
	w := a.NewWindow("Hello There")
	w.Resize(fyne.NewSize(1024, 768))
	entry := &myEntry{widget.NewEntry()}
	w.SetContent(container.NewVBox(entry))
	w.ShowAndRun()
}

type myEntry struct {
	*widget.Entry
}
```

When not embedded, I get

![image](https://user-images.githubusercontent.com/6109680/101099756-f0676900-358a-11eb-9b23-c91ad51f38d4.png)

but when embedded, I get

![image](https://user-images.githubusercontent.com/6109680/101099805-0ffe9180-358b-11eb-8a35-0f72f678e71a.png)

I stumbled upon https://github.com/fyne-io/fyne/issues/537 and thought I had found the answer, but adding 

`entry.ExtendBaseWidget(entry)`

made no difference.

On Linux Mint 18.3, Go 1.15, Fyne master

**Comment by buck54321** [comment]
Ah. It's because `ExtendBaseEntry` is called in `NewEntry`. Instantiating with `&widget.Entry{}` instead seems to have fixed it. Please close as you see fit.

**Comment by andydotxyz** [comment]
For best results the embedded Entry should not be a pointer. If you take the “*” off the declaration in your struct you don’t have to manage the construction of the embedded element.
