### ISSUE TITLE
Initializing NewRadio Question

### ISSUE THREAD

**Issue by njmullen** [fyne-io/fyne#163]
I'm having some trouble getting NewRadio to initialize properly.

I get inputting the options, but how am I supposed to pass the changed function? I tried typing a function right in the declaration, passing a function, but I can't seem to get it to work. I couldn't find any examples in any of the example code. I'd really appreciate some help!

Here is my radio declaration
var speed = widget.NewRadio(speedOptions, speedFunc(string))

func speedFunc(changed string){
 fmt.Println(changed)
}

**Comment by andydotxyz** [comment]
You need to pass the function reference - without the parameter list.

i.e.: widget.NewRadio(speedOptions, speedFunc)

There should be an example in the fyne repository: cmd/fyne_demo/widget.go - but that uses an inline function - either will work.
