### ISSUE TITLE
Add AppendText to Entry widget

### ISSUE THREAD

**Issue by viduq** [fyne-io/fyne#1631]
Hi and thank you for creating Fyne!
I am trying to put a logging window into my application and I expect a lot of incoming events that shall be logged.

Now I am trying to solve this with an Entry widget, with MultiLine enabled and the widget itself disabled, so it can only be read.
However, in the documentation I can only find the SetText method.
I could use a string to which I append the text that shall be logged, and then I could use SetText to update the Entry widget.

But I believe this is not the best way, because each time it would update the whole text, although only one line has been added.

Maybe a better approach would be to have an AppendText method.

Or should I rather use a List for a task like this instead?

**Comment by andydotxyz** [comment]
I would recommend using `container.NewVBox` and a collection of `widget.Label` objects.
The `widget.Entry` is not currently optimised for massive, or fast changing, text.

**Comment by viduq** [comment]
Thanks for the support! 
I will close the issue.
