### ISSUE TITLE
Data Binding refresh from external bound variables

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1645]
The calls `data.binding.BindXxx[Yyy]` calls connect an existing variable into a data binding.
At this time external changes to that data are not immediately reflected in the data, (though `Get()` will function correctly).
We want to ensure that external changes trigger the internal refresh including value adjustments and callbacks.

# Scope
## Affects

BindXxx, BindXxxList, BindUntypedMap and BindStruct

## Does not affect

NewXxx, BindPreferenceXxx, NewXxxList, NewUntypedMap, external implementations of the Xxx and XxxList, DataItem, DataList or DataMap type interfaces.

Developers can implement their own data bindings, doing so does not require this additional consideration as they will trigger data binding when their data source has changed.

# Requirements

## Primitive

This is not a problem when the data source is internal (NewXxx) or in some other programmatic source (such as a conversion or widget binding).

We should inform of changes in the variable, rather than simply returning from Getter when requested.
```
f := 5.0
b := BindFloat(&f)
f = 6.2 // does not trigger change
```

## Lists 

This is not a problem when the list is managed intermally such as NewXxxList.

BindXxxList should ensure changes of the slice size (1), or ordering (2), or individual elements changed (3);
```
strings := []string{"hi"}
b := BindStringList(&strings)

strings = append(strings, "d") // (1)
strings[0], strings[2] = strings[2], strings[1] // (2)
strings[0]+="aa" // (3)
```

## Maps 

This is not a problem when the map is managed internally such as NewUntypedMap.

BindUntypedMap (which connects binding to a `map[string]interface{}` type) should check if maps items have been added (1) or removed (2), or individual elements changed (3);
```
vals := map[string]interface{}{
	"foo": "bar",
	"val": 5,
	"bas": 0.2,
}
b := BindUntypedMap(&vals)

vals["key"] = 4.3 // (1)
delete(vals, "key") //  (2)
vals["foo"] = "hi" // (3)
```

## Structs

BindStruct (which connects a struct to the data binding system) should check which of the items have changed (1);
```
s := struct {
	Foo string
	Val int
	Bas float64
}{
	"bar",
	5,
	0.2,
}
b := BindStruct(&s)

s.Foo = "Hello" // (1)
s.Val = 3 // (1)
```

# Proposals

The aim of these possible approaches is to enable the data to be updated when it changes from an external source (specifically for the BindXxxType calls - not needed for NewXxxType or third party implementations). The solution should ensure that the API can trigger change event propagation but it should not introduce potentially confusion in what is a minimal API.

## Adding function to base DataItem

Alongside the `AddListener` and `RemoveListener` we could have a method `CallListeners` (or similar).
When the external data changes, the `CallListeners` is called to trigger any listeners of this data.

**Pros**
The simplest implementation, no additional types and remains consistent.

**Cons**
This adds the method to all type bindings, so `NewInt` would have additional `CallListeners` despte it not being needed. This approach does not imply any internal logic, so listners may be called when nothing changed.

## Export new type extending the `Type` interfaces that exports `Reload`

With this approach we see `BindXxx` return `ExternalInt` (or similar) in place of current `Int`, that indicates the return has different semantics.
Calling `Reload` on the new type can check the data, and make appropriate set / trigger calls.

**Pros**
This approach minimises the potential confusion of the new method, it is only exported on types that might need to have it called.

**Cons**
It introduces many new types, people may not understand how `ExternalInt` relates to `Int`.

## Monitor for changes internally

With this approach there is no new API. We check regularly (*very* regularly) for each data to have changed, and update bindings if that is the cae.

**Pros**
No additional work for the developers, no additional APIs

**Cons** 
Performance, to check regularly enough to be transparent we need to do so many times a second, at least 10, up to 60. Unfortunately as we implemented lists of structs we realised that this could mean thousands, or higher, pointer/value comparisons on every single change.
Consider this inside a table or list data source and you see how slow it can get.

**Comment by andydotxyz** [comment]
My preference is for "Export new type". I want to keep the API clean and obvious, and I think that a new type avoids providing public methods that will either not apply or could imply a lack of automatic 2-way sync that we actually support for most binding types.

The automatic detection solution seemed excellent, but once it scales up the overhead becomes problematic so large tables of bound data could become unworkable.

**Comment by stuartmscott** [comment]
I think the downside of adding `ExternalXXX` binding types (essentially doubling the public API) is far greater than the downside of adding `CallListeners` (or `Reload` or `Notify` as per [Observer Pattern](https://en.wikipedia.org/wiki/Observer_pattern)) to the base binding - it already exists as `trigger`, so the concern is that if it were exported, devs may call it unnecessarily although this is no more likely than a dev calling `canvasobject.Refresh` unnecessarily and can be resolved with clear documentation.

Polling is incredibly inefficient, and will not be able to handle custom dev-defined bindings - eg how will fyne be able to poll a remote database to check for changes?

**Comment by andydotxyz** [comment]
The `DataItem` already fulfils the observer pattern, internally what we are talking about is exposing the requirement to notify in certain situations.
If we add this to the base item then every single binding that will be defined, by developers internal and external, must implement it. This will include validators, converters etc etc. Every step in the chain will expose this method when it only applies to the very root, in the situation that the variable is outside the binding control.

I do not think it doubles the surface of the API -the document above illustrates when it would add and when it would not. At this time it looks like a large increase. As we add more types of binding the number of those with an exterrnal trigger functionn does not go up, so if your concern is ther percentage of new methods this goes down, over time. If you add it to the top level we have no new types but every single new binding exposes an unnecessary method.

**Comment by andydotxyz** [comment]
The closest parallel that I can come up with is the `Disablable` interface that some widgets implement.
We could have put `Disable()` as a method on `fyne.Widget` because most widgets are disablable. Instead we introduced a new type `Disablable` so that widgets to whom this applies can opt-in to the behaviour.

Similarly it is my opinion that the bindings which encapsulate external data should have this type of behaviour marked, instead of applying to all bindings that will ever exist.

**Comment by andydotxyz** [comment]
After chat on Slack with @Jacalz and @AlbinoGeek we realised that map and list Set was not actually supporting setting the data directly, so we fixed this so that the 👎 vote option of "no reload, just use Set" actually works.

Having worked through this all there is a lot of reason that just using `Set` would be easy to express.
However if the external variable is updated and then set is called the system does not see the changes.
So... we could trigger setters on all list and map subitems... or make a copy of the data so it can be compared and minimise the child listeners fired.
Either way it still seems like binding to external variables is valuble, and calling set in this situation seems overkill.
If we want to use it just for initialising but not write back we could make the BindXxx to be a copy from value rather than storing pointer... but in that case it's really just a shortcut to NewXxx.Set() - and might imply a variable connection that would not exist.

Just documenting where we got to in the chat session. I don't think it changes the requirement or available options for how it's data change would be detected and propagated.

**Comment by stuartmscott** [comment]
Seems we are agreed that binding implements the Observable pattern, where a piece of data is being observed and changes are reported to concerned stakeholders. Converters, and Validators (though they don't yet exist), are special cases of bindings. All of these have the ability to add and remove listeners as per the DataItem interface. All of these also have the ability to notify their listeners, though this is implicit and not part of the public API.

There are situations in which this ability needs to be explicit and part of the public API in order for bindings to remote data sources to be notified when data is changed.

It is not possible/feasible/efficient for bindings to automatically detect such changes and thus an explicit notification is required. We can therefore rule out "Monitor for changes internally".

### Add `Reload` to `DataItem`

This is by far the simplest approach as it involves adding a single function to an interface and renaming `func (b *base) trigger() {` with `func (b *base) Reload() {`. The existing behaviour of notifying listeners is now exposed and all bindings embedding `base` will be unchanged.

> This adds the method to all type bindings, so NewInt would have additional CallListeners despte it not being needed.

This is simply not true. `binding.Int` embeds `binding.DataItem`, and `binding.boundInt` embeds `binding.base` so there is no change to its public API other than the addition of `Reload` which is needed when notifying listeners that the bound int's value has changed.

>  This approach does not imply any internal logic, so listners may be called when nothing changed.

Yes this is the only downside - the developer may call Reload unnecessarily, however this can be resolved with clear documentation that it is only required when binding to a pointer, or external data source that has changed outside of the context of the binding.

### Export new types extending the Type interfaces that exports Reload

This approach introduces an interface defining `Reload`, an `ExternalXXX` type for every `XXX` primitive type (currently Bool, Float, Int, Rune, String), as well as adding `Reload` definitions to List and Map bindings. Worst still is that most implementations will simply be;

```go
func (b ExternalXXX) Reload() {
    b.trigger()
}
```

It also introduces the need for type cast checks when used in larger codebases;

```go
func somefunc(b binding.DataItem) {
    // Do some work that changes data
    if r, ok.(binding.ReloadableBinding); ok {
        r.Reload()
    }
}
```

The code changes required for this approach are big, though pales in comparison to the cognitive overhead for new developers.

**Comment by andydotxyz** [comment]
> There are situations in which this ability needs to be explicit and part of the public API in order for bindings to remote data sources to be notified when data is changed.

I don't think it's all remote data sources - this consideration is specifically about data that is internal to the application or libraries, can be modified directly without knowledge of the data binding code.
Other types of external data, such as DB or web service it is not needed - because the data binding code will be responsible for the sync schedule or methodology, and so to applications this is databinding managed code and can be triggered internally.

My characterisiation of:

> This adds the method to all type bindings

Is the same, in differrnt words, as your assertion:

> no change to its public API other than the addition of Reload

These two are saying the same thing - so I am confused that you classify my presentation as `This is simply not true`.
When I discuss API additions I mean  *exported* API additions. Internal or unexposed are not of any matter to our API users.  

To say that `Reload` is just a wrapper around `trigger` is to trivialise it's intent. we have already seen that there is a big difference between calling trigger on a collection and on the items it contains. If we `Reload` a `StringList` then we can see whether or not it's length has changed - if this is unchanged then all we need to do is examine/trigger the child nodes. If we blindly trigger then we are telling the widgets or consumers of this data that they must completely re-load the data and in many cases this may be completely unnecessary.

> It also introduces the need for type cast checks when used in larger codebases;

I don't think this is true. The only person who knows that this is `ExternalFloat` instead of `Float` is the code that bound it in the first place - every consumer of this `DataItem` or `Float` implementation will "just work" if the data source is managed correctly.

**Comment by andydotxyz** [comment]
To try and reinforce what I attempt to explain above - this is a challenge when binding, at the source end of a binding, to a variable that can be changed be our code outside of the scope of binding APIs. The following table attempts to illustrate usages:

| data type | internally managed | requires reload | notes |
|---|---|---|---|
| Float (etc) | NewFloat | BindFloat | |
| StringList (etc) | NewStringList | BindStringList | |
| UntypedMap (etc) | NewUntypedMap | BindUntypedMap | |
| Struct | n/a | BindStruct | (just a map internally, keys won't change) |
| ...ToString | IntToString | n/a | |
| StringTo... | StringToFloat | n/a | |
| Preferences | BindPreferenceBool | n/a | preference listener handles callbacks |
| **Possible additions** |
| Validation (#1704) | ValidatedString | n/a | |
| Clock (simple test) | BindClock | n/a | could use an Untyped internal and call Set or implement from scratch |
| MySQL (dev code) | BindQuery | n/a | DB management code will decide when changes checked and will therefore set changes when required |

As we can see from this the increase in types required for managing app data is increased, but all other uses of data binding have no use for this method. To include an un-used method in every instance that implements our APIs will be overhead for these developers and the users of their APIs.

---

Aside:

I can see that, should we want at some point in the future, expose a BaseBinding type then being able to tell the triggers to execute will be important. This is, however, a completely different use-case. Because all of the currently exposed types are interfaces a developer can implement custom binding sources, filters etc without needing this functionality. It is possible for developers to internally use an existing binding type (for example if I had a custom data source I could use a standard `Float` internally and return that from my constructor) and make use of the `Set` function instead of having to manage triggers manually.

**Comment by AlbinoGeek** [comment]
@andydotxyz 

It seems like you would solve both use-cases by having `Reload` added to all bind interfaces.

Types that won't use it out of the box, it doesn't stop the developer from wrapping it and using that.

e.g: Say I loaded someone's name from the database, returning a `binding.String` -- and I want to explicitly refresh their name (because I know it has changed, such as when I pushed a change to the database and want it reflected)-- I would call `Reload` on that "wrapped name" (`binding.String`) -- and it would call my implementation of `Reload`, which would then call `trigger()` internally (hence, it should be exported, yes.)

---

@stuartmscott 

Thus far, I'm liking the idea to add `Reload` to `DataItem` but wonder how this works for simpler types, `string, float, int` etc, do they also get to benefit from `Reload` in this case?

**Comment by andydotxyz** [comment]
> Say I loaded someone's name from the database, returning a binding.String -- and I want to explicitly refresh their name (because I know it has changed, such as when I pushed a change to the database and want it reflected)

In a database binding I would expect that calling `Set` on a value will case it to be stored, or at least written to a cache for later write-back. If you, the application developer, find that you need to inform a storage layer of a change to data, forcing a refresh, then re-reading then we have seriously broken our abstraction.

As the consumer of a data binding you or your widgets should not have to worry about where the data comes from, that's a significant part of the design. It could have gone through validation, or conversions - by the time you see a `String` type any attached `Reload` should be meaningless. This, as illustrated in the table above, only applies at the source, not further down the tree.

**Comment by andydotxyz** [comment]
As posted in the votes channel this has not reached concensus and it does not seem to be heading that way.
The vote expored with one vote for option 2, one for option 1 and one for "no need, we can just call Set".
We did get a community vote for option 2 as well, though that does not technically change the outcome.

Therefore, and in a situation I hope does not repeat soon, I have decided to call the decision so that the project can move on. We will progress with option 2 of 3.
Thanks everyone for your input on this issue and apologies for the amount of time it has taken to reach this outcome.

**Comment by stuartmscott** [comment]
I am disappointed in you Andrew.

**Comment by okratitan** [comment]
I voted for option one in the slack -  I just think anything else is over complicating this.  By the very nature of interfaces you may have certain methods that are pointless, or useless ... We see this frequently - for instance with our mouse interfaces where we may only want mouse move and thus ignore mouse down, mouse up.  Interfaces are generic in nature meant to satisfy a large usecase and the specific implementations may not everything the interface provides, and that is normal.  A Reload() that has no effect is not a big deal - especially with good documentation.  Option 3 would be ideal but has performance issues in the end.  Option 2 is sweeping changes and confusing to devs, even to me at certain points, so I don't think it is good design.

**Comment by andydotxyz** [comment]
Sorry @okratitan we did not get your vote until around 6 hours outside the window, I already have a PR under way. Perhaps you could take a look in shortly and see what you think.

I maintain that introducing methods for specific cases is less confusing than adding it to *all* binding types. It only applies at the source, in special situations. This is not like mouse callbacks where you opt in - the main conversation here has been between forcing every binding, ever, to provide probably no/op methods vs having some additional types for data source where it maters (see my table above).

**Comment by andydotxyz** [comment]
The PR #1717 is a completely functional implementation of the proposed approach.
It aims to trigger as few listeners as possible. List and Map will not trigger at the container level unless they have to.
Work still needs to complete to avoid calling the listeners for primitive values if Reload is called when the data has not changed.
That is just an optimistion, but it seems like an important one to be able to provide the most accurate representation of the data change events.

**Comment by andydotxyz** [comment]
Optimisations all in now - the listeners will only be triggered if data has changed. If a list grows the container is triggered, if not then it won't be. If only 1 item in a list is changed then when `Refresh` is called it will only trigger that one callback.

**Comment by andydotxyz** [comment]
On develop for testing
