### ISSUE TITLE
Delete/Backspace key repeat cycle not working

### ISSUE THREAD

**Issue by gangachris** [fyne-io/fyne#165]
I'm not sure if I'm missing something, but pressing the delete key (Mac) without releasing does not delete text the on demo forms. It only deletes the first character before the cursor and stops. One has to press, release and press for continuous deletion

**Comment by andydotxyz** [comment]
Looks like KeyTyped() does not repeat but RuneTyped() does - that should probably be resolved

**Comment by andydotxyz** [comment]
Apologies I missed that this was not actually merged to master - the fix is now public:

`go get -u fyne.io/fyne`

:)
