### ISSUE TITLE
File browser issues / reqeusts

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#1651]
Hi,
the current file browser widget is too painful to use,
specially if you are looking into a directory with too many files; (listed per priority)
1. files are only listed in a grid view, it would be much better to have a list view too
2. there is no search option
3. the scroll becomes too slow 
4. some files names are not shown clearly (i guess this is over all the app not just this widget)

**Comment by andydotxyz** [comment]
Thanks for your suggestions, my thoughts:

1. We plan to add this in the future
2. Search is complex - would it search just the current folder or more? We would struggle to offer system search from this toolkit level.
3. Yes, large directories can cause slowness - we need to add suitable caching like List/Table/Tree
4. Can you give more information on this please?

With regards to 4 it feels like a bug report, so including the system information and screenshot / details like the bug report template would be really helpful.

**Comment by s77rt** [comment]
2. just for the current folder
4. i meant for utf-8 files names, which is an issue for the whole fyne apps

**Comment by andydotxyz** [comment]
Does the utf-8 issue that you say is across fyne relate to missing font rather than broken unicode?

**Comment by s77rt** [comment]
@andydotxyz 
for 3: the issue is apparently exactly as #446

**Comment by andydotxyz** [comment]
Thanks for the confirmation.
We have moved FileDialog design discussion to https://github.com/fyne-io/fyne/wiki/File-Dialog-Design.
I'm closing this to move discussions there - I think your requests have been captured in it.
