### ISSUE TITLE
Tree widget performance

### ISSUE THREAD

**Issue by benoitkugler** [fyne-io/fyne#1655]
### Describe the bug:
Tree widget triggers too many layouts, which affects performances. 
The user experience with a large tree is then not pleasant at all...

### To Reproduce:
Run the sample code below. 

For a size of 1000 entries, the `isBranch` is called over 1_000_000 times.
Investigating a bit, I found that it comes from `Tree.walkAll,` itself called in `treeContentRenderer.Layout`, which seems to be called around 1000 times.

As an aside, the List widget handles the same number of entries without any issues.

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Tree test")

	w.Resize(fyne.NewSize(600, 600))
	content := tree()

	w.SetContent(content)
	w.ShowAndRun()
}

func tree() fyne.CanvasObject {
	var count int
	childUIDs := func(uid widget.TreeNodeID) (c []widget.TreeNodeID) {
		fmt.Println("isBranch called ", count, "times")
		if uid == "" {
			out := make([]string, 1000)
			for i := range out {
				out[i] = fmt.Sprintf("node_%d", i)
			}
			return out
		} else if uid[0] == 'n' {
			return []string{"kid" + uid}
		} else {
			return nil
		}
	}
	createNode := func(branch bool) (o fyne.CanvasObject) {
		return widget.NewLabel("")
	}
	isBranch := func(uid widget.TreeNodeID) (ok bool) {
		count++
		return uid == "" || uid[0] != 'k'
	}
	updateNode := func(uid widget.TreeNodeID, branch bool, node fyne.CanvasObject) {
		node.(*widget.Label).SetText(uid)
	}

	return widget.NewTree(childUIDs, isBranch, createNode, updateNode)
}

```

### Device (please complete the following information):
 - OS: Linux
 - Version: Ubuntu 20.10
 - Go version:  1.15.3
 - Fyne version: 1.4.2

### Misc 
Fyne looks really promising, I'm looking forward to replace all my Go/Qt code !

**Comment by andydotxyz** [comment]
Thanks for reporting this.
Do you see the layouts happening that many times simply to display this code example, or were you performing a user action?

**Comment by benoitkugler** [comment]
Yes, just launching the app triggered the layouts. It should probably be checked, since I only did a basic "fmt.Println" debugging.
From my very basic tests, it seems that additional user action, like hovers, also triggered layout, but this seems natural. Maybe it is not ?

**Comment by andydotxyz** [comment]
Thanks for this. Hover should not be triggering layout either.
It should only ne necessary for Layout to run if the widget is resized or it's content changes size somehow.

**Comment by fpabl0** [comment]
I can confirm that Layout is called at least twice with the same size on any container or widget. And at app launching, every Layout method is triggered at least 4 times with no size changes.

**Comment by andydotxyz** [comment]
There are a lot of calls to isBranch, but 100* less than reported in this (more like 2-4 per row).
This could clearly be improved by caching, but I don't think this is a performance issue any more.
In 2.4.0 we released many improvements in Tree speed so I think this could be marked resolved.
