### ISSUE TITLE
Add headers to table/tree widget

### ISSUE THREAD

**Issue by benoitkugler** [fyne-io/fyne#1658]
### Is your feature request related to a problem? Please describe:
I would like to title the columns of a table and to (externally) sort the rows when the header is clicked.

### Is it possible to construct a solution with the existing API?
I think we can build a pseudo header with a second table, but it's not very clean. Especially, the possible horizontal scrolling need to synchronized.

### Describe the solution you'd like to see:
The possibility to add headers (possibly both horizontal and vertical) to the table widget.
Ideally, horizontal headers could also be added to the tree widget.

They should provide a way to handle tap events, so that we can then sort the data, or maybe select all the column/row.
The sorting (or any other event handling) should probably stay external to keep things simple and allow maximum customization, I mentioned it as an example/motivation.

**Comment by PaulWaldo** [comment]
I have created an implementation that is helping me to achieve this, please see 
https://github.com/PaulWaldo/fyne-headertable.  
It's a bit rough around the edges, but it may help.  If you have any suggestions to better it, please let me know.

**Comment by cristim** [comment]
@PaulWaldo I wanted to use your little library, seemed neat, but then I realized it's distributed under GPL so it can't be used for non-GPL software. Too bad.

**Comment by andydotxyz** [comment]
Headers are now in, and can be tapped if you insert Buttons using `CreateHeader` and `UpdateHeader` callbacks which will replace the default
