### ISSUE TITLE
Tree failing to call UpdateNode on manual refresh

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#1663]
Hi,
is it possible to change a node label text in a tree widget?

thank you)

**Comment by andydotxyz** [comment]
Yes, the UpdateNode callback is the place to apply your data to the template. If your data changes call Tree.Refresh() and the callbacks will fire again

**Comment by s77rt** [comment]
Can you please include an example, i believe i have done what you were referring to but the text didn't change after calling Refresh (v1. 4.2)

**Comment by s77rt** [comment]
```
package main

import (
	"fmt"
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/widget"
)

type tree_data struct {
	tree *widget.Tree
	dynamic_value int
}

func (tree_data *tree_data) Init() {
	tree_data.Plant()
	tree_data.dynamic_value = 10
}

func (tree_data *tree_data) Plant() {
	tree_data.tree = widget.NewTreeWithStrings(
		map[string][]string{
			"": {"Dynamic", "Static"},
		},
	) 

	tree_data.tree.UpdateNode = func(uid string, branch bool, node fyne.CanvasObject) {
		if uid == "Dynamic" {
			node.(*widget.Label).SetText(fmt.Sprintf("%s (%d)", uid, tree_data.dynamic_value))
		} else if uid == "Static" {
			node.(*widget.Label).SetText(uid)
		}
	}
}

func main() {
	a := app.New()
	w := a.NewWindow("Fyne Tree")
	tree_data := &tree_data{}
	tree_data.Init()
	w.SetContent(
		container.NewGridWithColumns(2,
			tree_data.tree,
			widget.NewButton("Increase", func() {
				tree_data.dynamic_value++
				tree_data.tree.Refresh()
			}),
		),
	)
	w.ShowAndRun()
}
```

After a click on the Increase button, i'm expecting the node text to change but it is not changing

**Comment by andydotxyz** [comment]
Thank you for sharing the code, there is indeed a bug in there that somehow had not been noticed.
I have a fix locally that could work but I need to review it in the morning.
Apologies for the inconvenience.

**Comment by andydotxyz** [comment]
@s77rt The fix is available on #1667 if you're interested in picking the code and testing.
My apologies for the trouble this caused.

**Comment by andydotxyz** [comment]
Fixed on release branch

**Comment by shangdan1987** [comment]
@andydotxyz fyne v2.3.4 ,The tree did not trigger the update of data content. The simplified example is as follows
package main
import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

var Data_P map[string][]string

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")

	Data_P = map[string][]string{
		"":          {"publish", "subScribe"},
		"publish":   []string{"123", "456", "789"},
		"subScribe": []string{"1234", "4564", "7894"},
	}
	tree := widget.NewTreeWithStrings(Data_P)
	tree.OnSelected = func(id string) {
		fmt.Println("Tree node selected:", id)
	}
	tree.OpenBranch("publish")
	myWindow.SetContent(container.NewBorder(nil, nil, tree, nil, widget.NewButton("add", func() {
		Data_P = map[string][]string{
			"":          {"publish", "subScribe"},
			"publish":   []string{"123", "456", "789", "0000"},
			"subScribe": []string{"1234", "4564", "7894", "1000"},
		}
		tree.Refresh()
	})))
	myWindow.Resize(fyne.NewSize(400, 300))
	myWindow.ShowAndRun()
}

**Comment by andydotxyz** [comment]
Please don't comment on closed issues @shangdan1987 also please avoid pinging me - we have a community of developers here who are all very capable.

Lastly your issue is not this same issue (which was fixed) and is also not an issue at all. You have initiated a Tree with a static string data. Changing the source of that data will not change what the tree has access to - you need to use the standard `NewTree` to refresh from some data source.
