### ISSUE TITLE
Is there some way to create a multiline text with Canvas ?

### ISSUE THREAD

**Issue by SuperKirik** [fyne-io/fyne#1664]
Is there some way to create a multiline text (the text that will be wrapped and constraint with some width value) with Canvas ?

Now I'm creating label like this:

```
label := canvas.NewText("Long long text. Long long text. Long long text. Long long text. Long long text. Long long text.", &color.RGBA{0xff, 0xff, 0xff, 0xff})
label.TextSize = 12
```
(obviously, this always shows in one line, and stretch the window if it doesn't fit)

**Comment by andydotxyz** [comment]
Currently not, the wrap logic is in the Label / Entry widget.
container.NewVBox(text1, text2) will look the same if you can figure out where to break the string.

**Comment by SuperKirik** [comment]
@andydotxyz Thank you for your reply!
You mean something like this ?:

```
line1 := canvas.NewText("Long long text", &color.RGBA{0xff, 0xff, 0xff, 0xff})
line1.TextSize = 12
line1.Alignment = fyne.TextAlignCenter

line2 := canvas.NewText("Long long text", &color.RGBA{0xff, 0xff, 0xff, 0xff})
line2.TextSize = 12
line2.Alignment = fyne.TextAlignCenter

...etc

myWindow.SetContent(
  container.NewVBox(
    line1,
    line2,
))
```

**Comment by andydotxyz** [comment]
Yup, should look like you wanted?

**Comment by SuperKirik** [comment]
@andydotxyz yes, know it looks like it was planned.
 The only thing, that it would be extremely inconvenient to do this with a large text (e g if it contains more then a couple of lines).

**Comment by andydotxyz** [comment]
It's a tough one. The `canvas` package is designed for low-level operations so handling large data, caching etc is not something it aims to do. It just needs to be performant and to enable things on top.
The handling of many lines is more the realm of `widget.Label` (which we know could be more performant) as the label package is where more complex use-cases are handled.

In short I suppose I agree that it is inconvenient, but think that our text re-vamp sometime after 2.0 is probably the solution.
Text is complex - especially large amounts!

**Comment by andydotxyz** [comment]
I think this solves the original request. When we refactor text support it may be possible to promote some elements to the canvas, but it is unlikely given the reasons outlined above.
