### ISSUE TITLE
Inconsistent table rendering on resize with dynamic text alignment

### ISSUE THREAD

**Issue by maddie** [fyne-io/fyne#1666]
### Describe the bug:
When using a `widget.Table` with dynamic text alignment (returning a `widget.Label` as content and setting its `Alignment` property), everything renders perfect at first, but the result becomes inconsistent when rapidly resizing the window both horizontally and vertically (dragging the corners).

### To Reproduce:
Steps to reproduce the behaviour:
1. Set text alignment of `widget.Label` within the table dynamically on the callback
2. Open the window with a large table within
3. Drag the corners and resize rapidly
4. See the error

### Screenshots:

At launch (correctly rendered):

![Screen Shot 2020-12-18 at 15 30 40](https://user-images.githubusercontent.com/221872/102586990-10c82380-4146-11eb-9440-fecac89a8d88.jpg)

After resizing (wrong text alignments all over the place):

![Screen Shot 2020-12-18 at 15 30 47](https://user-images.githubusercontent.com/221872/102587011-1cb3e580-4146-11eb-8b9f-b59021c514bd.jpg)

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	application := app.New()

	w := application.NewWindow("Table Bug")

	// populate 20 rows of data
	data := populateData(20)

	// create table widget
	table := widget.NewTable(func() (int, int) {
		return len(data), len(data[0])
	}, func() fyne.CanvasObject {
		// make the initial cell size a bit larger
		return widget.NewLabel("123456789012345")
	}, func(id widget.TableCellID, object fyne.CanvasObject) {
		val := data[id.Row][id.Col]
		label := object.(*widget.Label)
		label.SetText(val)

		// set the bottom half to be center aligned
		if id.Row > len(data)/2 {
			label.Alignment = fyne.TextAlignCenter
		}
	})

	w.SetContent(table)

	w.Resize(fyne.NewSize(1400, 700))
	w.CenterOnScreen()
	w.SetMaster()
	w.ShowAndRun()
}

func populateData(size int) [][]string {
	var cols []string
	for i := 0; i < size; i++ {
		cols = append(cols, fmt.Sprintf("value %d", i))
	}

	var rows [][]string
	for i := 0; i < size; i++ {
		rows = append(rows, cols)
	}
	return rows
}

```

### Device:
 - OS: macOS Big Sur
 - Version: 11.0.1
 - Go version: 1.15.5
 - Fyne version: 1.4.2

**Comment by andydotxyz** [comment]
I think there is an issue in the code whereby the label is not refreshing after the alignment is set. If you change widget properties directly you need to call `Refresh()` to apply them. So either add the Refresh call or (probably faster) set it before calling `SetText()`, as that method will refresh the widget after changing the content.

So, one of the following
```go
func(id widget.TableCellID, object fyne.CanvasObject) {
		val := data[id.Row][id.Col]
		label := object.(*widget.Label)

		// set the bottom half to be center aligned
		if id.Row > len(data)/2 {
			label.Alignment = fyne.TextAlignCenter
		}
		label.SetText(val)
	}
```
OR
```go
func(id widget.TableCellID, object fyne.CanvasObject) {
		val := data[id.Row][id.Col]
		label := object.(*widget.Label)
		label.SetText(val)

		// set the bottom half to be center aligned
		if id.Row > len(data)/2 {
			label.Alignment = fyne.TextAlignCenter
		}
		label.Refresh()
	}
```

**Comment by maddie** [comment]
Tested both fixes, and unfortunately the alignment is still not correct.

**Comment by andydotxyz** [comment]
Ah, I found another issue...
As these cells are recycled you can't expect the usual defaults to apply if you might have changed them for previous cells.
Sort answer - you need to set the other align state...

```go
		// set the bottom half to be center aligned
		if id.Row > len(data)/2 {
			label.Alignment = fyne.TextAlignCenter
		} else {
			label.Alignment = fyne.TextAlignLeading
		}
```

**Comment by maddie** [comment]
Makes sense! Thanks!

**Comment by ddkwork** [comment]
how to dynamic add table row?

**Comment by Jacalz** [comment]
> how to dynamic add table row?

Please avoid asking unrelated questions on old issue that have been closed already. If you want to ask questions, I suggest doing so on the slack channel instead.
