### ISSUE TITLE
Move Test Markup to Files

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1669]
### Is your feature request related to a problem? Please describe:
Updating XML markup tests is tedious as deltas need to be copied from the test output to a specific place inside the test files.

### Is it possible to construct a solution with the existing API?
No. Golden image tests are simpler to update as they only require copying the test output file to the golden image file.

### Describe the solution you'd like to see:
Move XML markup to files under `testdata/`, and write test output markup under `testdata/failed` so that updating a test is as simple as copying a file.

**Comment by andydotxyz** [comment]
This would make it much easier to make large changes if required.

**Comment by stuartmscott** [comment]
Assigned to the subject matter expert :)

**Comment by andydotxyz** [comment]
On develop for testing :) (thanks @toaster)
