### ISSUE TITLE
Intermittent clipboard test failure on Windows

### ISSUE THREAD

**Issue by adrianre12** [fyne-io/fyne#1679]
### Describe the bug:
I am having trouble reliably running tests on windows. It seems to go through phases of passing multiple times then failing multiple times (like 10 times in a row)
I run 
$ go clean -testcache ./...
$ go test ./...

When it fails I get the error
`2020/12/22 17:36:47 Fyne error:  Failed to focus object which is not part of the canvas’ content, menu or overlays.
2020/12/22 17:36:47   At: C:/Users/Adrian/go/src/github.com/adrianre12/fyne/internal/driver/glfw/canvas.go:85
2020/12/22 17:36:48 Fyne error:  Main menu must have at least one child menu
2020/12/22 17:36:48   At: C:/Users/Adrian/go/src/github.com/adrianre12/fyne/internal/driver/glfw/menu.go:9
2020/12/22 17:36:54 PlatformError: Win32: Failed to open clipboard: Access is denied.
--- FAIL: TestWindow_Clipboard (0.05s)
    window_test.go:864:
                Error Trace:    window_test.go:864
                Error:          Not equal:
                                expected: "My content from test window"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -My content from test window
                                +
                Test:           TestWindow_Clipboard
FAIL
FAIL    fyne.io/fyne/internal/driver/glfw       14.288s`

I suspect the Access Denied is to do with resource locking, but so far I have not been able to identify a reliable repeatable success or failure scenario.

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.15.5
 - Fyne version: v1.4.2 and develop

**Comment by adrianre12** [comment]
I have dug deeper. In glfw.go
`// GetClipboardString returns the contents of the system clipboard, if it
// contains or is convertible to a UTF-8 encoded string.
//
// This function may only be called from the main thread.
func GetClipboardString() string {
	cs := C.glfwGetClipboardString(nil)
	if cs == nil {
		acceptError(FormatUnavailable)
		return ""
	}
	return C.GoString(cs)
}`

Does the call `acceptError(FormatUnavailable)` FormatUnavailable is defined as
`	// FormatUnavailable is the error code used for both window creation and
	// clipboard querying format errors.
	//
	// If emitted during window creation, the requested pixel format is not
	// supported. This means one or more hard constraints did not match any of
	// the available pixel formats. If your application is sufficiently
	// flexible, downgrade your requirements and try again. Otherwise, inform
	// the user that their machine does not match your requirements.
	//
	// If emitted when querying the clipboard, the contents of the clipboard
	// could not be converted to the requested format. You should ignore the
	// error or report it to the user, as appropriate.
	FormatUnavailable ErrorCode = C.GLFW_FORMAT_UNAVAILABLE`

In acceptError(codes ...ErrorCode)

`// acceptError fetches the next error from the error channel, it accepts only
// errors with one of the given error codes. If any other error is encountered,
// a panic will occur.
//
// Platform errors are always printed, for information why please see:
//
//  https://github.com/go-gl/glfw/issues/127
//
func acceptError(codes ...ErrorCode) error {
	// Grab the next error, if there is one.
	err := fetchError()
	if err == nil {
		return nil
	}

	// Only if the error has the specific error code accepted by the caller, do
	// we return the error.
	for _, code := range codes {
		if err.Code == code {
			return err
		}
	}

	// The error isn't accepted by the caller. If the error code is not a code
	// defined in the GLFW C documentation as a programmer error, then the
	// caller should have accepted it. This is effectively a bug in this
	// package.
	switch err.Code {
	case platformError:
		log.Println(err)
		return nil
	case notInitialized, noCurrentContext, invalidEnum, invalidValue, outOfMemory:
		panic(err)
	default:
		fmt.Println("GLFW: An invalid error was not accepted by the caller:", err)
		fmt.Println("GLFW: Please report this bug in the Go package immediately.")
		panic(err)
	}
}`

We can see it prints out platformErrors. Looking at the issue [ https://github.com/go-gl/glfw/issues/127](url) it seems, in the end, they decided to print out platformErrors so people could report them. 
Other googling seems to suggest this is due to clipboard locking and the solution is to have a retry.

**Comment by andydotxyz** [comment]
This was fixed, thanks
