### ISSUE TITLE
Memory Leakage of widget.NewProgressBarInfinite

### ISSUE THREAD

**Issue by kkleejoe** [fyne-io/fyne#168]

**Comment by paulhovey** [comment]
Can you give any description?  Steps to reproduce?

**Comment by kkleejoe** [comment]
------------------------------------
main.go 
------------------------------------
package main
import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)
func main() {
	win := app.New().NewWindow("Demo")
	win.SetContent(widget.NewVBox(
		widget.NewProgressBarInfinite(),
	))
	win.ShowAndRun()
}
------------------------------------
tested in win64 platform, it consume 3~4 MB RAM per second

**Comment by andydotxyz** [comment]
On Linux I see a 1MB growth every 3 seconds. Not quite as bad but still a bug - let's get this fixed.

**Comment by steveoc64** [comment]
Tested using memdebug - doesnt seem to be a leak as much as it putting things up for GC.

Using master, which includes the fixes to progressbar ... cant see a memleak now.  Running infiniteprogressbar demo for 1 minute - memory usage goes up and down by about a Kb.

**Comment by steveoc64** [comment]
I believe that after applying https://github.com/fyne-io/fyne/pull/203

**Comment by andydotxyz** [comment]
Leaving this and #203 open for now as that introduces an API change so I wonder if we can find a better approach...

**Comment by andydotxyz** [comment]
Whilst there is still work to do in this area I am pretty sure that the leak reported here is now fixed
