### ISSUE TITLE
How to get screen size for Windows MacOS or Linux?

### ISSUE THREAD

**Issue by wejoy** [fyne-io/fyne#1685]
For example, I want to create a cross-platform Fyne App for Windows MacOS and Linux, and It should be in the half size of screen width and height, how to do it? Could fyne add that feature? In fyne.Device maybe?

**Comment by wejoy** [comment]
Oh, I find maybe I can get that from glfw, never mind

**Comment by andydotxyz** [comment]
Desktop / screen operations (except FullScreen) are not exported. Manually manipulating windows is not supported on many platforms - the user can position windows using the window manager or desktop environment features.
