### ISSUE TITLE
Information.SetOnClosed doesn't work

### ISSUE THREAD

**Issue by encendre** [fyne-io/fyne#1687]
Hi,
When closing an information popup, the callback registered with `SetOnClosed` is not called.
 
```go
	a := app.New()
	w := a.NewWindow("Test")

	w.Resize(fyne.NewSize(400, 400))

	d := dialog.NewInformation("Test", "this is a test", w)
	d.SetOnClosed(func() {
		fmt.Println("closed.")
	})

	w.ShowAndRun()
```
### Device (please complete the following information):
 - OS: Linux 5.9.14-zen1-1-zen x86_64 GNU/Linux
 - Go version: 1.15
 - Fyne version: 1.4.2

**Comment by encendre** [comment]
By looking in the source code I managed to solve the problem, it was enough to call `d.Show()` before closing the popup, despite the fact that it is already shown without it.
Maybe the documentation should be clarified

**Comment by andydotxyz** [comment]
This is a known issue on 1.4.x, sorry, the fix is already on ‘develop’ branch ready for 2.0. we could not back-port the fix as it is a breaking behaviour change.
