### ISSUE TITLE
Text selection color

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1688]
### Is your feature request related to a problem? Please describe:
No

### Is it possible to construct a solution with the existing API?
Yes, it is possible.

### Describe the solution you'd like to see:
Currently, the theme.FocusColor() is used as the color for the text selection, however I think the text selection must have a fixed color (the common one could be color.RGBA{R: 179, G: 215, B: 255, A: 255}). Otherwise, that color will change with the focus color and it doesn't look very well with all colors.

**Comment by andydotxyz** [comment]
The colour should be set by the theme. In 2.0 we are updating the theme and intend that the selected colour should be different to focused.
That should resolve this issue.

**Comment by fpabl0** [comment]
> The colour should be set by the theme. In 2.0 we are updating the theme and intend that the selected colour should be different to focused.
> 
> That should resolve this issue.

Great, may I know when will the v2.0 be released? I have been using this library for 7 days now, and it is really great. Thanks.

Could I propose some redesigns for widgets like entry and form? I don't know if the new API will have those, is there any documentation about the new features the new release will have?

**Comment by andydotxyz** [comment]
v2.0 is scheduled for 22nd Jan.
The new design is based on https://github.com/fyne-io/fyne/wiki/Theme-API-2, though the implementation is now landed on `develop`.

Design help would be hugely appreciated thanks :)

**Comment by fpabl0** [comment]
@andydotxyz Based on the new focus colors (that are lighter than the primary color), should we revert the text selection color to be the focus color again? (not the cursor just the selection)

**Comment by andydotxyz** [comment]
I don't think it is worth making an intermediate change. What we should do is add the `SelectionColor` for `Aberlour` as discussed and fix this, along with others, at the same time.

**Comment by fpabl0** [comment]
Fair enough. It is just that applications that use a dark primary color, text selection is hard to see :(. It is the case for the purple primary color defined in fyne_settings:

<img width="456" alt="Captura de Pantalla 2021-03-08 a la(s) 10 24 45" src="https://user-images.githubusercontent.com/12239342/110341741-ad3cec00-7ff8-11eb-8bdc-12352edb9183.png">

It would look really good if it adopts the focus color that is very similar to progress bar background color.

**Comment by andydotxyz** [comment]
I don't disagree that this should be changed. 
I do disagree that we shuld move selection from primary to focus when we intend to add a selection colour.
Let's just fix it right.

**Comment by andydotxyz** [comment]
Updated to use the selection colour we added on `develop`
