### ISSUE TITLE
MacOS Notifications are not shown on subsequent app runs after first run due to duplicate identifier

### ISSUE THREAD

**Issue by AdityaHirapara** [fyne-io/fyne#1699]
### Describe the bug:
On MacOS, an incremental counter is used for notification identifier. So, app shows notifications on first run, but in subsequent runs notifications are assigned same identifier from `0`. If notifications with these identifiers are already present in the notification center, mac doesn't show these notifications as popup again and replaces old notification content with a new one inside the notification center itself.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the mac app with notifications
2. Don't interact with notifications, let them go in the notification center
3. Quit app and restart
4. Notifications won't popup on second run

### Device:
 - OS: MacOS
 - Version: 11.1
 - Go version: 1.15.5
 - Fyne version: 1.4.2

**Comment by andydotxyz** [comment]
Fixed on `develop` and also picked to `release/v1.4.x` ready for release in a few days
