### ISSUE TITLE
[develop] Data Binding - `widget.CheckWithData` does not set `Checked`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1702]
### Describe the bug:
If you create a bound Checkbox to a `true`, the `.Checked` property is not set by data binding, even though the Check is visually checked when the program loads.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a `binding.Bool`
1. Set the bool `true`
1. Create a `widget.CheckWithData`
1. See the `check.Checked` is `false` (should be `true`)

### Screenshots:
![image](https://user-images.githubusercontent.com/1910461/103391532-cf812d80-4ace-11eb-8212-dd9253694180.png)

### Example code:
```go
	// Unwrapped "boundCheck" (see... it's not really that "custom")
	b := binding.NewBool()
	b.Set(true)

	e := widget.NewCheckWithData("Automatically Download Updates?", b)

	// The actual issue:
	fmt.Printf("%v\n", e.Checked) // false
```

### Device (please complete the following information):
 - OS: Linux (Fedora Workstation)
 - Version: 33
 - Go version: go1.15.6 linux/amd64
 - Fyne version: 170ee4f6662a

**Comment by AlbinoGeek** [comment]
** Closed because I thought I had gotten this line wrong:
```golang
	settings.checkUpdatesCheck.OnChanged(settings.checkUpdatesCheck.Checked)
```

** Re-opened because this was not the source of the issue / did not help the issue.

**Comment by AlbinoGeek** [comment]
Found the source of the issue:

```go
	// ...

	settings.checkUpdates, settings.checkUpdatesCheck = settings.boundCheck("update.check.enabled", "Check for Updates Periodically?")

	// ...

	// Sanity Check:
	r, _ := settings.checkUpdates.Get()
	fmt.Printf("settings.checkUpdatesCheck.Checked = %v = %v = %v\n", viper.GetBool("update.check.enabled"), r, settings.checkUpdatesCheck.Checked)
	// settings.checkUpdatesCheck.Checked = true = true = false           ( THIS IS NOT CORRECT )
```

**Comment by andydotxyz** [comment]
I don't know how to work with this, there is so much custom code and partial methods that I can't get a reproduction of the issue locally.
I suspect that the issue lies in the way you are using both bindings and `OnChanged` - that is not how this should be used so I think it's broken some of the binding code somehow.

If you want to bind to a custom data source like your `*settings` data source you will be better off adding binding support or a bridge, rather than hacking into the widget. Binding a checkbox to preference should look as simple as:

```go
data := binding.BindPreferenceBool('myKey')
check := widget.NewCheckWithData(data)
```

Literally nothing else should be required. You don't need widget change listeners or large `Get`/`Set` calls.

To bind to your own data source you might want to look into the `BindPreferenceBool` but basically you just need to implement `binding.Bool`. That's it :)

**Comment by andydotxyz** [comment]
In response to the original bug report:

> 4. Set the OnChanged of the bound Check to Enable/Disable the second widget

Don't do this. Curently data binding and OnChanged are mutually exclusive, once bound to data you should add any listeners required in the data scope not the widget.

**Comment by AlbinoGeek** [comment]
"Custom code and partial methods" -- `*settings` is the "Settings Page" of my UI, not some custom method/widget. There are no custom widgets in this demonstration / issue. The only custom method was for creating the bound fields, because there is so much boilerplate code otherwise. I have unrolled the custom method in the following example so the issue is more clear.

```go
	// Unwrapped "boundCheck" (see... it's not really that "custom")
	settings.checkUpdates = binding.NewBool()
	settings.checkUpdates.Set(true) // simplification for this issue

	settings.checkUpdatesCheck = widget.NewCheckWithData("Automatically Download Updates?", settings.checkUpdates)

	// The actual issue:
	fmt.Printf("%v\n", settings.checkUpdatesCheck.Checked) // false
```

**Comment by AlbinoGeek** [comment]
I can move code away from `OnChanged`, but this presents different issues (such as: Having to call all my binding `.Set` after my UI is drawn, otherwise the `DataListener`s won't trigger, it turns my program into a Chicken//Egg//Horse//Cart problem.) -- Either way, separate from this issue thread (with the core issue outlined above.)

**Comment by andydotxyz** [comment]
The custom code that is still tripping me up is `viper.GetBool("update.check.enabled")` -  if that returned a bound data element the rest would be trivial. So if you had a new `BindViberBool(key) Bool` that could bridge it in your own code.

> such as: Having to call all my binding .Set after my UI is drawn

I don't understand this either. Widgets render with the current state of a data binding. 

> Binding a Check leads to the .Checked property not being updated.

As far as I can see this is incorrect. Calling `CheckWithData` or `Check.Bind` will setup callbacks that keep `Checked` and the data in sync.

**Comment by andydotxyz** [comment]
Perhaps you can post what you are trying to do?
Data binding should be trivial - I think you are fighting it but I cannot figure out what it is that you want to do that it cannot already provide.

**Comment by andydotxyz** [comment]
If I drop your code into a basic window and run it I see the following:

![Uploading Screenshot 2020-12-31 at 13.22.30.png…]()

**Comment by AlbinoGeek** [comment]
Yeah, we talked through this on the channel.

While the Check is visually Checked, programmatically the `.Checked` property is not `true` unless a delay (1 second for example) is added before checking.

But I understand this is semi-intentional now after we discussed it.

**Comment by AlbinoGeek** [comment]
Anyone finding this later:

Basically, data binding takes effect on the widgets **after a delay, not in the constructor**

So... don't rely on it to be set, use the binding variable directly instead.

**Comment by andydotxyz** [comment]
> While the Check is visually Checked, programmatically the .Checked property is not true unless a delay (1 second for example) is added before checking.

Hmm more like 50ms, but yes. If you are using data binding don't ask widget for state :)
