### ISSUE TITLE
darwin-386 build fails: cannot use _Ctype_long(i) (type _Ctype_long) as type _Ctype_int

### ISSUE THREAD

**Issue by polarctos** [fyne-io/fyne#1706]
### Describe the bug:
Building a fyne application for darwin-386, e.g. with fyne-cross fails:

```
[i] Target: darwin/386
(...)
[i] Packaging app...
[i] Building binary...
# fyne.io/fyne/internal/driver/glfw
vendor/fyne.io/fyne/internal/driver/glfw/menu_darwin.go:175:42: cannot use _Ctype_long(i) (type _Ctype_long) as type _Ctype_int in assignment
vendor/fyne.io/fyne/internal/driver/glfw/menu_darwin.go:183:51: cannot use _Ctype_long(i) (type _Ctype_long) as type _Ctype_int in assignment
vendor/fyne.io/fyne/internal/driver/glfw/menu_darwin.go:187:41: cannot use _Ctype_long(i) (type _Ctype_long) as type _Ctype_int in assignment
[✗] exit status 2
```

32-bit macos might be not that relevant in the future, but it is at listed as supported for [fyne-cross](https://github.com/fyne-io/fyne-cross/blob/master/README.md#fyne-cross)

As it looks like the actual issue is in the fyne code itself, I opened the issue here.

### To Reproduce:
Steps to reproduce the behaviour:
1. Use a small sample app
2. Build for darwin/386, e.g. with: `fyne-cross "darwin" -arch="386"`
3. See error

### Device:
 - OS: MacOS
 - Version: 10.15.7 
 - Go version: (build via fyne-cross 1.0.0)
 - Fyne version: fyne.io/fyne v1.4.2

**Comment by polarctos** [comment]
The go version used in the fyne-cross 1.0.0 containers is [1.4.13](https://github.com/fyne-io/fyne-cross/blob/v1.0.0/docker/base/Dockerfile#L17), this is the reason why it starts to build at all.

As of go [1.15](https://golang.org/doc/go1.15) this `darwin/386` combination is not supported anymore anyway, thus maybe nothing that should be fixed here.

**Comment by andydotxyz** [comment]
Can you try building with Go directly? If not it would be better to raise this in the fyne-io/fyne-cross project.

**Comment by polarctos** [comment]
Building directly with ``go version go1.14.13 darwin/amd64`` I get these errors: 
```
env GOOS=darwin GOARCH=386 go build -o dist/bin ./...
../../../pkg/mod/fyne.io/fyne@v1.4.2/internal/painter/gl/gl_core.go:11:2: build constraints exclude all Go files in /Users/x/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.2-core/gl
../../../pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/clipboard.go:6:2: build constraints exclude all Go files in /Users/x/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3
```
But these might be issues with my general machine setup for cross-compiling applications using fyne.io for ``arch=386``, that is why I directly used ``fyne-cross``.

As ``darwin/386`` is not supported in go 1.15 anymore anyway, I'll close this.

**Comment by andydotxyz** [comment]
It looks like your local build omitted the required `CGO_ENABLED=1` flag
