### ISSUE TITLE
error: brackets expression not supported on this target

### ISSUE THREAD

**Issue by prologic** [fyne-io/fyne#1708]
### Describe the bug:

- Basically following the "Getting Started" and "Your first app" guides. Those worked fine on macOS.
- Then followed "Mobile Packaging" guide at https://developer.fyne.io/started/packaging-mobile which fails with numerous build errors I don't understand (yet):

```#!sh
prologic@Jamess-iMac
Fri Jan 01 21:52:01
~/tmp/hello-fyne
 0
$ fyne package -os ios -appID com.example.myapp -icon mobileIcon.png
go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=ios -- .]: exit status 2: go: downloading github.com/fyne-io/mobile v0.1.2-0.20201127155338-06aeb98410cc
# runtime/cgo
gcc_arm64.S:27:16: error: brackets expression not supported on this target
 stp x19, x20, [sp, #-16]!
               ^
gcc_arm64.S:28:16: error: brackets expression not supported on this target
 stp x21, x22, [sp, #-16]!
               ^
gcc_arm64.S:29:16: error: brackets expression not supported on this target
 stp x23, x24, [sp, #-16]!
               ^
gcc_arm64.S:30:16: error: brackets expression not supported on this target
 stp x25, x26, [sp, #-16]!
               ^
gcc_arm64.S:31:16: error: brackets expression not supported on this target
 stp x27, x28, [sp, #-16]!
               ^
gcc_arm64.S:32:16: error: brackets expression not supported on this target
 stp x29, x30, [sp, #-16]!
               ^
gcc_arm64.S:33:2: error: unknown use of instruction mnemonic without a size suffix
 mov x29, sp
 ^
gcc_arm64.S:35:2: error: unknown use of instruction mnemonic without a size suffix
 mov x19, x0
 ^
gcc_arm64.S:36:2: error: unknown use of instruction mnemonic without a size suffix
 mov x20, x1
 ^
gcc_arm64.S:37:2: error: unknown use of instruction mnemonic without a size suffix
 mov x0, x2
 ^
gcc_arm64.S:39:2: error: invalid instruction mnemonic 'blr'
 blr x20
 ^~~
gcc_arm64.S:40:2: error: invalid instruction mnemonic 'blr'
 blr x19
 ^~~
gcc_arm64.S:42:16: error: brackets expression not supported on this target
 ldp x29, x30, [sp], #16
               ^
gcc_arm64.S:43:16: error: brackets expression not supported on this target
 ldp x27, x28, [sp], #16
               ^
gcc_arm64.S:44:16: error: brackets expression not supported on this target
 ldp x25, x26, [sp], #16
               ^
gcc_arm64.S:45:16: error: brackets expression not supported on this target
 ldp x23, x24, [sp], #16
               ^
gcc_arm64.S:46:16: error: brackets expression not supported on this target
 ldp x21, x22, [sp], #16
               ^
gcc_arm64.S:47:16: error: brackets expression not supported on this target
 ldp x19, x20, [sp], #16
               ^
```

### To Reproduce:

1. `mkdir hello-fyne`
2. `cd hello-fyne`
3. `go mod init hello-fyne`
4. `pbpaste > main.go`
5. `cp /path/to/some/icon.png mobileIcon.png`
6. `fyne package -os ios -appID com.example.myapp -icon mobileIcon.png`

`main.go`:

```#!go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: macOS Cataline
 - Version: 10.15.7
 - Go version: 1.14.6
 - Fyne version: v1.4.2

**Comment by andydotxyz** [comment]
This has happened before with stale items in the cache. I’m not certain why or how, but if you clear the cache and remove any temporary binary files in the current directory and try again it should be ok.

**Comment by prologic** [comment]
Which cache ?

**Comment by andydotxyz** [comment]
The go build cache.

**Comment by prologic** [comment]
🤣 TIL: There exists a `go clean` command!

After running `go clean` I now get a different error (_possibly unrelated?_):

```#!sh
$ fyne package -os ios -appID com.example.myapp -icon mobileIcon.png
failed to look up certificate : exit status 44
```

**Comment by andydotxyz** [comment]
This is indeed unrelated. It is looking for the apple developer certificate to sign the binary, perhaps you do not have one installed?

**Comment by prologic** [comment]
> This is indeed unrelated. It is looking for the apple developer certificate to sign the binary, perhaps you do not have one installed?

You are correct, I do not have one installed, nor do I have an Apple Developer account. I would have to pay Apple I suppose right, get a certificate and put it somewhere?

Thanks for your help, the `go clean` worked!

**Comment by andydotxyz** [comment]
> I would have to pay Apple I suppose right, get a certificate and put it somewhere?

Yes, unfortunately to install on devices or prepare for App Store upload you need an Apple provided certificate.
Installing it is simple, but you do need to join the developer program and pay the fee, sorry.
