### ISSUE TITLE
How do I close or effectively hide a popup modal?

### ISSUE THREAD

**Issue by vesche** [fyne-io/fyne#1709]
I tried to follow the advice [here](https://fyne.io/support/) to join the `#fyne` channel on Slack, but the invite link seems to be down? https://invite.slack.golangbridge.org/

I'm trying to close or hide a popup modal, I looked all thru the documentation / issues and just simply can't figure it out.

Here's a slimmed down example of what I'm doing:
```go
package main

import (
    "fyne.io/fyne"
    "fyne.io/fyne/app"
    "fyne.io/fyne/widget"
)

func runPopUp(w fyne.Window) {
    widget.ShowModalPopUp(
        widget.NewVBox(
            widget.NewLabel("bar"),
        ),
        w.Canvas(),
    )
}

func main() {
    a := app.New()
    w := a.NewWindow("Test")
    button := widget.NewButton("foo", func() { runPopUp(w) })
    w.SetContent(button)
    w.Resize(fyne.NewSize(1024, 768))
    w.ShowAndRun()
}
```

Once the button is pressed and modal is popped up, how do I close the popup and return to the button? I can figure out how to hide the content (`NewVBox`) of the popup modal but I want the entire thing to go away, like a normal popup would.

**Comment by AlbinoGeek** [comment]
Use `NewModalPopUp` instead of `ShowModalPopUp` ?

```go
func runPopUp(w fyne.Window) *widget.PopUp {
    modal := widget.NewModalPopUp(
        widget.NewVBox(
            widget.NewLabel("bar"),
        ),
        w.Canvas(),
    )
    modal.Show()
    return modal
}
```
Then later you can call `modal.Hide()`

**Comment by vesche** [comment]
Hi @AlbinoGeek thank you so much for the fast response!! Unfortunately, I've tried something similar to what you recommended there. It doesn't work and I'm getting an error with that code.

```
$ go run test.go
# command-line-arguments
./test.go:13:48: undefined: modal
```

I believe this is because `widget.NewButton("Close", func() { modal.Hide() }),` the button in the modal pop-up can't reference itself when it's created because it doesn't exist yet? And the button outside of the modal can't be pressed to close it. So I'm not sure how to fix that problem.

Thanks again for the help.

**Comment by AlbinoGeek** [comment]
That's why I put this in main:

```go
    var modal *widget.PopUp
```

**Comment by vesche** [comment]
The code you wrote in your first comment doesn't work?
I'm talking about what's in the `runPopUp` function.

```
func runPopUp(w fyne.Window) *widget.PopUp {
    modal := widget.NewModalPopUp(
        widget.NewVBox(
            widget.NewLabel("bar"),
            widget.NewButton("Close", func() { modal.Hide() }),
        ),
        w.Canvas(),
    )
    modal.Show()
    return modal
}
```

This won't run because modal isn't defined yet? Sorry if I'm misunderstanding.

**Comment by AlbinoGeek** [comment]
Ahh, sorry, I see what I did there. You are correct. I misunderstood entirely what you were saying.

```go

func runPopUp(w fyne.Window) (modal *widget.PopUp) {
	modal = widget.NewModalPopUp(
		widget.NewVBox(
			widget.NewLabel("bar"),
			widget.NewButton("Close", func() { modal.Hide() }),
		),
		w.Canvas(),
	)
	modal.Show()
	return modal
}
```

The signature can be changed to make this work.

**Comment by vesche** [comment]
Thank you so much!!! It works @AlbinoGeek I really appreciate the help.

**Comment by colourdelete** [comment]
Hi, sorry for jumping in, but `NewModalPopUp` seems to be deprecated in v1 and cannot be used in v2. Since `ShowModalPopUp` doesn't return anything, is there any other way to close/hide a modal popup?

https://pkg.go.dev/fyne.io/fyne/v2/widget@v2.0.0#ShowModalPopUp

**Comment by andydotxyz** [comment]
It was deprecated due to a behaviour change pending.
There is a new `NewModalPopUp` in v2.

**Comment by colourdelete** [comment]
Hi, Thanks for the info!

**Comment by kargirwar** [comment]
I had to change widget.NewVBox to container.NewVBox.
