### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1718]
### Describe the bug:
When updating to the latest develop version, I noticed that dragging the slider in wormhole-gui's settings caused a panic due to a fatal error. This did not occur a week or two back on develop before I updated.

### To Reproduce:
I have yet to narrow it down in a smaller code example, but it seems to be related to the change listeners.
The best way is to just draw the slider **fast** under the settings tab in [wormhole-gui](https://github.com/Jacalz/wormhole-gui/tree/develop), on latest develop.
![fatal-error](https://user-images.githubusercontent.com/25466657/103580996-70ab2200-4edb-11eb-82ac-598dc4df6d2f.gif)

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.10.4
 - Go version: 1.15.6
 - Fyne version: 5fc52fcc1b31fd8dbbbe06bf58a65faab221f208

I have successfully managed to track down that it probably is caused by https://github.com/fyne-io/fyne/commit/77a198529eed3100e070b7c6b66c351c6a2e12e8.

**Comment by Jacalz** [comment]
The whole error output can be found here: https://gist.github.com/Jacalz/d9fb147095fe54871565647fa7b1a287

**Comment by andydotxyz** [comment]
On `develop` for testing
