### ISSUE TITLE
ProgressBar SetValue not updating UI

### ISSUE THREAD

**Issue by ShayBox** [fyne-io/fyne#172]
Similar to #8 but for SetValue, don't want to make the PR because I'm a new go user and don't completely understand it, just wanted to let you know :+1:
![image](https://user-images.githubusercontent.com/9505196/54862820-8f482500-4d16-11e9-939d-aff19af3620d.png)

**Comment by andydotxyz** [comment]
Unfortunately this is behaving correctly. The window.ShowAndRun() (or driver.Run()) function will not return until the application exits. This means that SetValue(0.5) is being called after the window closes.

Try "go bar.SetValue(0.5)" instead and it will probably do what you want...

Do you think the documentation needs to be improved to make this clearer?

**Comment by ShayBox** [comment]
Yeah, I didn't think that ShowAndRun could be blocking, but that would do it, probably a mention about it somewhere would be nice, thanks :+1:
