### ISSUE TITLE
canvas.NewImageFromFile() gives "image: unknown format" for non-existing paths

### ISSUE THREAD

**Issue by gernotstarke** [fyne-io/fyne#1721]
### Describe the bug:

Loading images on a canvas produces errors, instead of displaying the images:

```
2021/01/05 15:09:14 Fyne error:  image err
2021/01/05 15:09:14   Cause: image: unknown format
2021/01/05 15:09:14   At: /Users/gernotstarke/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/painter/image.go:94
2021/01/05 15:09:14 Fyne error:  image err
2021/01/05 15:09:14   Cause: image: unknown format
2021/01/05 15:09:14   At: /Users/gernotstarke/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/painter/image.go:94
2021/01/05 15:09:14 Fyne error:  SVG Load error:
2021/01/05 15:09:14   Cause: invalid argument
2021/01/05 15:09:14   At: /Users/gernotstarke/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/painter/image.go:50

```

The images I used here are the official GO logos from https://blog.golang.org/go-brand,
therefore I assume they are "valid". 
I can successfully open them in Chrome, Firefox, Safari and a number of image editing tools...

I tried different images (mostly jpg and png) - some can be displayed, others can't. 

For the code, see below.

### To Reproduce:

See sample code below

### Screenshots:
![image](https://user-images.githubusercontent.com/1233990/103656089-76027e00-4f68-11eb-922d-55145ec71555.png)

The images I try to display:
![Go-Logo_Fuchsia](https://user-images.githubusercontent.com/1233990/103656550-05a82c80-4f69-11eb-9a00-66c9e2cb0391.jpg)

### Example code:

```go

func main() {
	a := app.New()
	w := a.NewWindow("Hello Image")


	appLogo1 := canvas.NewImageFromFile( "./GO-Logo-Fuchsia.png")
	appLogo1.FillMode = canvas.ImageFillStretch

	appLogo2 := canvas.NewImageFromFile( "./GO-Logo-Fuchsia.jpg")
	appLogo2.FillMode = canvas.ImageFillStretch

	appLogo3 := canvas.NewImageFromFile( "./GO-Logo-Fuchsia.svg")
	appLogo3.FillMode = canvas.ImageFillStretch

	container := fyne.NewContainerWithLayout(
		layout.NewGridLayout(3),
		appLogo1,
		appLogo2,
		appLogo3,
	)

	w.SetContent(container)
	w.ShowAndRun()
}
```

It makes no difference if I use `canvas.ImageFillOriginal`
-->

### Device (please complete the following information):
 - OS: MacOS 
 - Version: 10.15.7
 - Go version: go version go1.15.6 darwin/amd64

 - Fyne version: 1.14

**Comment by AlbinoGeek** [comment]
@gernotstarke I think it's a valid issue, but I'd rename it (change the title.)
Perhaps... `canvas.NewImageFromFile() gives "image: unknown format" for relative/non-exist path`

**Comment by andydotxyz** [comment]
Thanks. I updated the title again as this does not relate to relative paths, only when files are not found. 
Relative paths are relative to the current directory.
It is best practice, however, to bundle your assets so that the app can move around and not need files alongside.
https://developer.fyne.io/tutorial/bundle

**Comment by AlbinoGeek** [comment]
@andydotxyz Right, but this is not always possible. For example, I was hitting this error a few hundred times yesterday when implementing a `DesktopProvider` (related to the Fynedesk Launcher) -- Where system Desktop Entries specify an icon by name (most of the time*) and you have to go and find it using $XDG_ICON_PATHS and such.

This leads to some icons which don't exist.

```
2021/01/05 15:09:14 Fyne error:  image err
2021/01/05 15:09:14   Cause: image: unknown format
```

Is not a useful error message whatsoever in regards to a non-existing file.

You would not even know as a developer, seeing this error, that it meant the file didn't exist.

**Comment by andydotxyz** [comment]
Oh absolutely, I did not want to dismiss this - it is a good change to make.
We need to add the ability to understand the difference from an unknown []byte from an empty []byte I think.

**Comment by fpabl0** [comment]
Fixed on `develop`. Closing this.
