### ISSUE TITLE
Remove deprecations from v1.4.x and earlier

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1724]
This is just a reminder and blocker task to make sure that we don't release 2.0 without dropping all the deprecations.

**Comment by andydotxyz** [comment]
Thanks, I had just been tracking it locally. I think the remaining list is:

- [ ] Canvas.Scale (#1713)
- [ ] Widget.Background (#1656)
- [ ] ./app/app.go:// Deprecated: Developers should not specify a driver manually but use NewAppWithID()
- [ ] ./widget/tabcontainer.go
- [ ] widget package Renderer and Refresh
- [ ] ./widget/check.go:// Deprecated: this method will be removed as it is no longer required, widgets do not expose their focus state.
- [ ] ./widget/splitcontainer.go
- [ ] ./widget/box.go
- [ ] ./widget/scroller.go
- [ ] ./widget/radio_item.go:// Deprecated: Use fyne.Canvas.Focused() instead.
- [ ] ./widget/radio.go:// Deprecated: Use RadioGroup instead.
- [ ] ./widget/group.go:// Deprecated: Consider using the Card instead.
- [ ] ./widget/entry.go ReadOnly
- [ ] ./widget/entry.go:// Deprecated: this method will be removed as it is no longer required, widgets do not expose their focus state.
- [ ] ./widget/accordion.go remove AcccordionContainer name
- [ ] ./widget/button.go remove Primary and HideShadow
- [ ] ./widget/select.go:// Deprecated: internal detail, don’t use
- [ ] ./test/testcanvas.go:// Deprecated
- [ ] ./driver/desktop/mouse.go:	// Deprecated: use MouseButtonPrimary which will adapt to mouse configuration.
- [ ] ./driver/desktop/mouse.go:	// Deprecated: use MouseButtonSecondary which will adapt to mouse configuration.
- [ ] ./layout/fixedgridlayout.go:// Deprecated: use the replacement NewGridWrapLayout. This method will be removed in 2.0.
- [ ] ./internal/driver/gomobile/canvas.go:// Deprecated: Settings are now calculated solely on the user configuration and system setup.
- [ ] ./internal/driver/glfw/device.go:// Deprecated: SystemScaleForWindow provides an accurate answer, this method may return incorrect results!
- [ ] ./internal/driver/glfw/canvas.go:// Deprecated: Settings are now calculated solely on the user configuration and system setup.
- [ ] ./device.go:	// Deprecated: Use SystemScaleForWindow instead - system scale can vary depending on window placement
- [ ] ./dialog/progressinfinite.go
- [ ] ./dialog/entry.go
- [ ] ./dialog/progress.go
- [ ] ./canvasobject.go Focused
- [ ] ./settings.go:// Deprecated: Automatic scaling is now handled in the drivers and is not a user setting.
- [ ] ./theme/theme.go:// Deprecated: Use theme.Foreground colour instead
- [ ] ./theme/theme.go:// Deprecated: Use DisabledColor() instead
- [ ] ./uri.go:	// Deprecated, use URI().Name() instead
- [ ] ./container.go (remove old constructors)
- [ ] ./canvas.go:	// Deprecated: Settings are now calculated solely on the user configuration and system setup.
- [ ] Canvas.Overlay()
- [ ] ./internal/driver/gomobile/canvas.go (as above)
- [ ] ./internal/driver/glfw/canvas.go (as above)

**Comment by andydotxyz** [comment]
Another question is - should we absolutely remove everything?
Elements that are not holding us back could stay unttil 3.0 - especially if it was marked deprecated very recently.
The more agressive the removal the trickier it will be to argue for the automatic 1.4 -> 2.0 upgrade path we were looking to take.

**Comment by Jacalz** [comment]
We can probably save a few where there is no reason to remove it, but at the same time it would have to stay until 3.0, so it requires some consideration. Fyi, the last five items in the list are deprecations added in 2.0 and can not be removed now anyway.

**Comment by andydotxyz** [comment]
Done :)
