### ISSUE TITLE
Entry doesn't draw custom `ActionItem`

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1732]
### Describe the bug:
I attempted to add a ButtonWithIcon (very similar to how the password entry adds a button) -- a simple "clear" button as seen in search bars in a variety of applications as a convenience. I was also going to test with microphones and other such icons, but found while they do take up space, they do not render.

### To Reproduce:
Steps to reproduce the behaviour:
1. Make an Entry
2. Assign to Entry's ActionItem
3. Refresh the Entry

### Screenshots:
![image](https://user-images.githubusercontent.com/1910461/103858324-f7433900-506c-11eb-8297-98ca68a11c32.png)
( Everything is at its MinSize, empty space in Entry on right = the ActionItem )

### Example code:
```go
	entry.SetPlaceHolder("PlaceHolder")
	entry.ActionItem = widget.NewButtonWithIcon("", theme.CancelIcon(), func() {
		entry.SetText("")
	})
	entry.Refresh()
```

### Device (please complete the following information):
 - OS: Fedora Linux
 - Version: Workstation 33
 - Go version: 1.15.6 linux/amd64
 - Fyne version: ab0568914435

**Comment by fpabl0** [comment]
@AlbinoGeek  I think it is because a ButtonWithIcon is bigger than a simple Icon, and widget.Entry min size only takes in account the IconSize. ButtonWithIcon has a padding (that in theory increase its size) so maybe that is the reason why it is not renderer.

**Comment by AlbinoGeek** [comment]
@fpabl0 Same result if I use an icon-sized image alone:

```go
	icon := canvas.NewImageFromResource(theme.CancelIcon())
	icon.SetMinSize(fyne.NewSize(24, 24))
	entry.ActionItem = icon
	entry.Refresh()
```

**Comment by fpabl0** [comment]
@AlbinoGeek icon size must be (theme.IconInlineSize(), theme.IconInlineSize()). Try with it, I think that is the problem.

**Comment by AlbinoGeek** [comment]
@fpabl0 Same results.

```go
	icon := canvas.NewImageFromResource(theme.CancelIcon())
	icon.SetMinSize(fyne.NewSize(theme.IconInlineSize(), theme.IconInlineSize()))
	entry.ActionItem = icon
	entry.Refresh()
	entry.ActionItem.Refresh()
```

**Comment by fpabl0** [comment]
@AlbinoGeek try with Resize instead of SetMinSize

**Comment by AlbinoGeek** [comment]
Doesn't change the result.

Also, looking into the code for `Entry` I can see that they force resize the element to `IconInlineSize` anyways.

**Comment by fpabl0** [comment]
@AlbinoGeek Yes, you are right, my mistake. However, I was not able to reproduce your error, I have no problems adding an action item in widget.Entry: 

<img width="300" alt="Captura de Pantalla 2021-01-07 a la(s) 21 33 24" src="https://user-images.githubusercontent.com/12239342/103967441-017a3b80-5130-11eb-8758-6c17b6defc7c.png">

**Comment by AlbinoGeek** [comment]
@fpabl0 Interesting, and this is also the case on `develop` with `DarkTheme()` ?

**Comment by fpabl0** [comment]
@AlbinoGeek  Yes, it is.
<img width="348" alt="Captura de Pantalla 2021-01-07 a la(s) 22 27 34" src="https://user-images.githubusercontent.com/12239342/103971027-8c126900-5137-11eb-9462-81d42ca56aa6.png">

**Comment by AlbinoGeek** [comment]
@fpabl0 

Thank you for testing/showing this. I've clearly broken something 👍🏻 

I'll close this until I can find the root cause and reproduction.

**Comment by hello-sucess** [comment]
I also encountered this problem on mac
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31380144/152507800-7f159219-6d06-4fb0-af30-f29acfd22ea2.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/31380144/152507833-361cf838-121c-45ed-9e8d-951bf8d390e1.png">

**Comment by andydotxyz** [comment]
I think this is unrelated @hello-sucess - I cannot figure out what you are reporting as the code is about `Button` but the content is `Entry`.
Please open a new issue if you have found a problem.
