### ISSUE TITLE
Close the window, the process cannot exit normally

### ISSUE THREAD

**Issue by Areturn** [fyne-io/fyne#1733]
### Describe the bug:

The code in the button does not stop, close the window, and the process cannot exit normally.
### Screenshots:

https://user-images.githubusercontent.com/25275823/103908643-a8190900-513d-11eb-8d99-1e92f93086f9.mp4

### Example code:

	a := app.New()
	w := a.NewWindow("test")
	w.SetContent(container.NewVBox(widget.NewButton("test", func() {
		for {
			;
		}
	})))
	w.ShowAndRun()

### Device (please complete the following information):
 - OS: Kali
 - Version: 2.0
 - Go version: 1.15.2
 - Fyne version: 1.4.2

**Comment by Jacalz** [comment]
Removing the infinite loop inside the button function should make your application close correctly. The callbacks run on the same goroutine as the application/rendering code and will thus block anything else from working. If you want a long running process to run, you’d have to run it inside a separate goroutine. Going to close this as it isn’t an issue with Fyne itself.
