### ISSUE TITLE
The font in widget.NewTextGrid method does not take effect and Chinese cannot be displayed.

### ISSUE THREAD

**Issue by Areturn** [fyne-io/fyne#1736]
### Describe the bug:

The font in widget.NewTextGrid method does not take effect and Chinese cannot be displayed.

### Screenshots:

![image](https://user-images.githubusercontent.com/25275823/103975019-1bf2fa00-51ae-11eb-9f24-855f486ce84d.png)

### Example code:

package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/widget"
	"github.com/flopp/go-findfont"
	"os"
)

func main() {
	filePath, _ := findfont.Find("DroidSansFallbackFull.ttf")
	_ = os.Setenv("FYNE_FONT", filePath)

	a := app.New()
	w := a.NewWindow("测试")
	w.SetContent(container.NewVBox(widget.NewButton("测试", func() {
			;
	}),widget.NewTextGridFromString("测试")))

	w.ShowAndRun()
}

### Device (please complete the following information):
 - OS: kali
 - Version: 2.0
 - Go version: 1.15.2
 - Fyne version: 1.4.2

**Comment by andydotxyz** [comment]
for textgrid you need a monospaced font, this is overridden with env `FYNE_FONT_MONOSPACE`.

**Comment by andydotxyz** [comment]
Closing as it looks like this question was answered
