### ISSUE TITLE
Cursor does not go down to next line with wrapping

### ISSUE THREAD

**Issue by Areturn** [fyne-io/fyne#1737]
### Describe the bug:

What's happening here?

### Screenshots:

https://user-images.githubusercontent.com/25275823/103982939-6335b680-51bf-11eb-8c3b-91a1ca7a24e7.mp4

### Example code:

	entryLoremIpsum := widget.NewMultiLineEntry()
	entryLoremIpsum.SetText("11111111111111111111111")
	entryLoremIpsumScroller := container.NewVScroll(entryLoremIpsum)

	entryLoremIpsum.Wrapping = fyne.TextWrapWord
	w.SetContent(entryLoremIpsumScroller)
	w.ShowAndRun()

### Device (please complete the following information):
 - OS: kali
 - Version: 2.0
 - Go version: 1.15.2
 - Fyne version: 1.14.2

**Comment by andydotxyz** [comment]
Well found.
I think we must be missing tests for Entry with word wrap turned on!

**Comment by andydotxyz** [comment]
This is being worked on by @aayush420

**Comment by aayush420** [comment]
@Jacalz I'm using this test to verify the bug. 
```
func TestEntry_CursorColumn_Wrap2(t *testing.T) {
	entry := widget.NewMultiLineEntry()
	entry.Wrapping = fyne.TextWrapWord
	entry.Resize(fyne.NewSize(64, 64))
	entry.SetText("1234")
	entry.CursorColumn = 3
	test.Type(entry, "a")
	test.Type(entry, "b")
	test.Type(entry, "c")
	assert.Equal(t, 1, entry.CursorColumn)
	assert.Equal(t, 1, entry.CursorRow)
	w := test.NewWindow(entry)
	w.Resize(fyne.NewSize(70, 70))
	test.AssertImageMatches(t, "dummyfile.png", w.Canvas().Capture())
}
```
Here's the `dummyfile.png` which shows the required output.
![dummyfile](https://user-images.githubusercontent.com/16898783/104158169-cff4bf00-5412-11eb-9638-c0c967a4b38f.png)

**Comment by aayush420** [comment]
PR at https://github.com/fyne-io/fyne/pull/1766

**Comment by andydotxyz** [comment]
Merged, thanks for the help on this @aayush420 :)
