### ISSUE TITLE
Error compiling fyne on Apple M1 arm64

### ISSUE THREAD

**Issue by sirkon** [fyne-io/fyne#1739]
Cannot compile fyne_demo on Apple M1 (if it matters).

I am following the procedure described at the [tour](https://developer.fyne.io/started/#run-demo), got an error message:

```
GO111MODULE=on go get fyne.io/fyne/cmd/fyne_demo
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200625191551-73d3c3675aa3
# github.com/go-gl/gl/v3.1/gles2
go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.1/gles2/package.go:38:11: fatal error: 'KHR/khrplatform.h' file not found
 #include <KHR/khrplatform.h>
          ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Device (please complete the following information):
 - OS: MacOS
 - Version: Big Sur 11.1
 - Go version: go version go1.16beta1 darwin/arm64
 - Fyne version: v1.4.3

**Comment by andydotxyz** [comment]
Do you have Xcode and the command line tools all installed?

We have not yet tested compiling on an M1 so this may be a new issue.
It refers to missing graphics headers, but it is possible that Apple removed them from the toolking in the transition to their new sillicon.

**Comment by Jacalz** [comment]
Can you please update the issue with the contents from the issue template. The issue template is there for us to more easily be able to help. More specifically,  I am curious about your Go version here. Go 1.16 is the first release with M1 support and the older versions do not support compilation for that target.

**Comment by sirkon** [comment]
Added system and Golang info. 

> Do you have Xcode and the command line tools all installed?

Sure, everything is installed.

**Comment by andydotxyz** [comment]
Hmm, looking closer it seems we are trying to load a GLES driver because it’s an arm machine. Apple must, if at al, be using core OpenGL for compatibility so we need an M1 specific compile option.
If you could try running any other OpenGL content it might confirm this suspicion.

**Comment by sirkon** [comment]
Yeah, I can. Could you point an example to check this idea with?

**Comment by andydotxyz** [comment]
I don't have a list personally - but I saw a few listed on Reddit: https://www.reddit.com/r/macgaming/comments/jvlpmi/stardew_valley_an_opengl_game_runs_fine_on_apple/

**Comment by sirkon** [comment]
Used this tutorial and it compiles and works well: https://kylewbanks.com/blog/tutorial-opengl-with-golang-part-1-hello-opengl

**Comment by Jacalz** [comment]
It looks like glfw isn't working just yet. See this PR for more info: https://github.com/glfw/glfw/pull/1833

**Comment by ipfans** [comment]
I think it is a long life time issue https://github.com/go-gl/gl/issues/125

**Comment by andydotxyz** [comment]
> I think it is a long life time issue [go-gl/gl#125](https://github.com/go-gl/gl/issues/125)

It might be the opposite issue - on that ticket they want to use GLES but it's not included, whereas the issue here we have is that when on arm we auto-detect GLES but we want to use OpenGL proper.

Could you please help us @sirkon, by inverting the "arm" flag in `internal/painter/gl/gl_es.go` and `gl_core.go` so just to test whether it works when it's switched to full GL instead of GLES?

**Comment by ipfans** [comment]
@andydotxyz @sirkon With inverting the "arm" and "arm64" flag in internal/painter/gl/gl_es.go and gl_core.go, the program can build success, but still not start normally: it does not show main screen with some warning and error:

```
# fyne.io/fyne/v2/app
app_darwin.m:10:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:11:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:17:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:18:32: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:37:5: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:37:66: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:118:12: note: 'NSUserNotificationCenter' has been explicitly marked deprecated here
app_darwin.m:43:5: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
app_darwin.m:43:61: warning: 'NSUserNotification' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
2021/01/27 14:16:00 PlatformError: Cocoa: Failed to find service port for display
2021/01/27 14:16:00 Fyne error:  window creation error
2021/01/27 14:16:00   Cause: APIUnavailable: NSGL: OpenGL ES is not available on macOS
2021/01/27 14:16:00   At: /Users/user/Desktop/fyne_demo/vendor/fyne.io/fyne/v2/internal/driver/glfw/window.go:1306

```

**Comment by sirkon** [comment]
@andydotxyz confirm @ipfans report, it compiles but no GUI is shown with the same error message: "OpenGL ES not available on macOS"

**Comment by sirkon** [comment]
BTW, finally reach my intel machine. Really like the overall feel of the library, just what is needed for my tasks. Hope to see working M1 sooner than later :)

**Comment by Virgil-N** [comment]
I have this problem too. I'm using mac M1.

**Comment by andydotxyz** [comment]
If anyone is able to share access to an M1 it may get fixed sooner - because none of the developers currently have access.
(Sorry to ask! Otherwise we need to finance a purchase from our sponsorship contributions)

**Comment by andydotxyz** [comment]
@ipfans Ah, there were more build tags - can you try toggling the `arm` value in the flags of `./internal/driver/glfw/glfw_es.go` and `./internal/driver/glfw/glfw_core.go` as well, that might work...?

**Comment by sirkon** [comment]
And it works!

https://user-images.githubusercontent.com/56399/107146684-c6e80680-695a-11eb-995c-11e3768609f0.mp4

PS A bit harder than just toggling arm tags. Got an idea though, just managed to enable _core and disable _es and that worked.

**Comment by sirkon** [comment]
> If anyone is able to share access to an M1 it may get fixed sooner - because none of the developers currently have access.
> (Sorry to ask! Otherwise we need to finance a purchase from our sponsorship contributions)

Is it possible without the public IP? I guess I can share an access if it is possible somehow without a public address.

**Comment by andydotxyz** [comment]
> And it works!

This is fantastic news, thanks. Can you please share the diff here so we can work with it?
I would normally ask if you can open a PR but there is probably more work to do as this was mostly just to test what would work rather than the final solution.

> Is it possible without a public IP? I

Not really, but don't worry - you have it working, so we can work with your differences and if you're able to test a patch once we have a PR shaped up that's just as good as direct access!

**Comment by sirkon** [comment]
Made a PR: https://github.com/fyne-io/fyne/pull/1922

**Comment by sirkon** [comment]
Made a PR https://github.com/fyne-io/fyne/pull/1922
Check it please

**Comment by andydotxyz** [comment]
Fixed on `develop`

**Comment by daiwhea** [comment]
For my old MBP, develop won't work. I created a vendor directory, and download develop branch in it. Then run commands below. 

go mod vendor reports nothing. but when I try to run it, there is an error output below. 

> daiwhea$ go mod vendor
 daiwhea$ go run GoStock.go
 \#github.com/go-gl/gl/v3.2-core/gl
vendor/github.com/go-gl/gl/v3.2-core/gl/package.go:40:11: fatal error: 'KHR/khrplatform.h' file not found
 #include <KHR/khrplatform.h>
          ^~~~~~~~~~~~~~~~~~~
1 error generated.

![image](https://user-images.githubusercontent.com/163152/123231406-c1a2e700-d50a-11eb-9685-75839ff0e8c6.png)

**Comment by andydotxyz** [comment]
Go mod vendor overwrites your vendor folder. And it is not needed for go 1.16. You need to update the version in your go.mod to head of develop branch and it should just work

**Comment by andydotxyz** [comment]
FYI this may relate to #2282 - by calling "go mod vendor" locally you will probably find that it is removing the file (do git status). If that is the case then just "get checkout (path to missing file)" and it will work again. I have filed an issue upstream #go-gl/gl/issues/140.
