### ISSUE TITLE
hyperlink color in light-theme (yellow) is nearly invisible

### ISSUE THREAD

**Issue by gernotstarke** [fyne-io/fyne#1749]
### Is your feature request related to a problem? Please describe:
The bright yellow hyperlink is nearly invisible in light theme.

imho it should be blueish

### Is it possible to construct a solution with the existing API?
Theme colors need to be adjusted

### Describe the solution you'd like to see:
make hyperlinks in light theme blue instead of yellow

**Comment by andydotxyz** [comment]
The yellow primary colour probably needs work in general as text can be subtle as well.
The hyperlink re-uses the same user preference color as primary. It does need work to be clearer, but I don't think we intend to go back to when certain widgets assert their own colors as it would not match the rest of the theme.

**Comment by dweymouth** [comment]
This is no longer relevant - Primary color is light blue in the default theme with light variant, and there is a theme.HyperlinkColor constant since 2.4 to customize Hyperlink specifically
