### ISSUE TITLE
a panic occurred after pushing a Quit button

### ISSUE THREAD

**Issue by kemokemo** [fyne-io/fyne#175]
Hi! 😃 
I found this awesome product yesterday and love this.

## procedure

1. `go get fyne.io/fyne`
1. create `main.go` like below

```go
package main

import (
	"fyne.io/fyne/widget"
	"fyne.io/fyne/app"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))

	w.ShowAndRun()
}
```

## result

1. `go run main.go`
2. After pushing the `Quit` button, a panic occurrs below:

```
panic: close of closed channel

goroutine 1 [running, locked to thread]:
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc00000e720)
	/Users/kemokemo/go/src/fyne.io/fyne/driver/gl/loop.go:92 +0x405
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc00000e720)
	/Users/kemokemo/go/src/fyne.io/fyne/driver/gl/driver.go:57 +0x43
fyne.io/fyne/app.(*fyneApp).Run(0xc000068080)
	/Users/kemokemo/go/src/fyne.io/fyne/app/app.go:47 +0x81
main.main()
	/Users/kemokemo/go/src/github.com/kemokemo/fyne-app/main.go:20 +0x24d
exit status 2
```

When pushing the window's close button, this issue did not occur.

### note

1. First, in the `gLDriver.Quit` method, the `gLDriver.done` channel is closed.
    - [link](https://github.com/fyne-io/fyne/blob/13b392f2d56e4421133b19582c1ba5ae809231be/driver/gl/driver.go#L50)
1. Then, in the `gLDriver.runGL` method, the `gLDriver.done` channel is closed again.
    - [link](https://github.com/fyne-io/fyne/blob/13b392f2d56e4421133b19582c1ba5ae809231be/driver/gl/loop.go#L90)

### environment

- OS
    - macOS Mojave Ver. 10.14.3
    - Windows 10 1809 (64 bit)
- go
    - 1.12.1
- branches
    - master 13b392f2d56e4421133b19582c1ba5ae809231be
    - develop 290584a55d81e0093255a078b30ece5d72ed347e
    - tag: v1.0.0 d8ddc74bc20dffab4f9ac8db486046c92185d5fa

Thank you!

**Comment by andydotxyz** [comment]
Thanks for the report - the detail is very helpful.
For some reason this does not happen on Linux (and also our automated tests missed it).
I will ensure this gets fixed and rolled out today

**Comment by kemokemo** [comment]
Thank you so much for your fixing! 😄
