### ISSUE TITLE
MenuItem support Icon

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1752]
### Is your feature request related to a problem? Please describe:
MenuItem supports text, but does not support Icon.

### Is it possible to construct a solution with the existing API?
no

### Describe the solution you'd like to see:
The addition of `MenuItem.Icon fyne.Resource` to be displayed next to the existing `MenuItem.Label string`

**Comment by andydotxyz** [comment]
This was merged for v2.2.0
