### ISSUE TITLE
MenuItem support Selection Indication

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1753]
### Is your feature request related to a problem? Please describe:
MenuItem cannot indicate that it is currently selected.

### Is it possible to construct a solution with the existing API?
no

### Describe the solution you'd like to see:
A way to indicate that a MenuItem within a Menu or PopUp is selected.

The main use case I have for this is showing which option within a PopUp is currently selected eg. the currently selected option of a Select or SelectEntry, or the current tab in an AppTab overflow PopUp or DocTab all tabs PopUp.

**Comment by andydotxyz** [comment]
On `develop` for testing :)
