### ISSUE TITLE
need a method for load font from byte

### ISSUE THREAD

**Issue by wyx0k** [fyne-io/fyne#1756]
hello, it is a common sence to use a non builtin font by fyne, use tempfile and envVar is not so match convinent, so... can fyne provide a method for load font from **byte**,it cound not be better

**Comment by andydotxyz** [comment]
Using your byte content create a resource using `fyne.NewStaticResource` with an appropriate name as well.
Then it can be used in place of other font resources.

**Comment by andydotxyz** [comment]
I believe this was answered, please reopen if that is not the case

**Comment by wyx0k** [comment]
thankyou for your answered, imeant that is load font by a single function not a whole theme. now, i use "mytheme" is just work fine,em....it just a suggestion for that ,by the end thanks again.
