### ISSUE TITLE
Can't type in entry if text pasted, unless entry is clicked

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1759]
### Describe the bug:

After the recent entry changes in `develop` branch, it looks like right-clicking and pasting content into the entry no longer properly focuses the entry.  Pasting anything into the entry does not let me type anything unless the entry is clicked again.

### To Reproduce:
Steps to reproduce the behaviour:
1. Copy something (this line perhaps?)
2. Right-click on entry and choose "paste"
3. Try to type or remove anything from the entry
4. Notice that nothing happens
5. Click on the text in entry
6. Try to type or remove anything from the entry
7. Notice that it works

### Screenshots:

![issue-with-entry](https://user-images.githubusercontent.com/25466657/104131657-0d583e80-5378-11eb-9bc5-a6c346240f5d.gif)

### Example code:
Use any entry or select entry in fyne_demo.

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.10.5
 - **Go version:** 1.15.6
 - **Fyne version:** dbf027921f90

cc @andydotxyz as you touched the entry code recently

**Comment by andydotxyz** [comment]
Fixed on `develop` now
