### ISSUE TITLE
 Failed to cross compile 

### ISSUE THREAD

**Issue by YinYongTao** [fyne-io/fyne#1770]
./glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory

![image](https://user-images.githubusercontent.com/26930834/104295519-8502a680-54fb-11eb-97b3-102c77c004c0.png)

**Comment by andydotxyz** [comment]
If you have not already, check the setup in https://developer.fyne.io/started/
Some systems do not have the right header files installed for a developer to build Fyne apps.

**Comment by andydotxyz** [comment]
To help further we would need information about the host computer, command to compile etc. The full bug template has the appropriate fields requested.

**Comment by andydotxyz** [comment]
Closing due to no response from OP
