### ISSUE TITLE
Clicking multiple entry fast allows multiple widgets to look focused

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1774]
### Describe the bug:

Spam clicking multiple entry widgets in succession causes a lot of them to look focused at the same time. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to fyne_demo and the entry or form screen
2. Click fast on multiple entry widgets
3. See multiple focused entry widgets

### Screenshots:

![focus-issues-two](https://user-images.githubusercontent.com/25466657/104369126-45e54d00-551d-11eb-8c21-4fca2ff03fd8.gif)

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.10.5
 - **Go version:** 1.15.6
 - **Fyne version:** develop @ 7dc8e30bc8a4e0aa65754d345558b1960b64217f

**Comment by andydotxyz** [comment]
Fixed :)
