### ISSUE TITLE
Cursor anim. sometimes distorts the text

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1778]
### Describe the bug:

This bug seems to be sporadic and related  to the cursor animation, because it appeared when animation was added.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo.
2. Go to any tab with an Entry.
3. Write and delete quickly.

### Screenshots:

https://user-images.githubusercontent.com/12239342/104426037-662dff80-554f-11eb-9db5-c5b18b26a7a3.mp4

https://user-images.githubusercontent.com/12239342/104426055-6b8b4a00-554f-11eb-92b3-04957106917f.mp4

### Device (please complete the following information):
 - **OS:** MacOS 
 - **Version:** 10.15.4 Catalina 
 - **Go version:** 1.15.6 
 - **Fyne version:** develop @ ee882d72

**Comment by andydotxyz** [comment]
On develop, will be in 2.0.1
