### ISSUE TITLE
Buttons does not have a click animation

### ISSUE THREAD

**Issue by danieldaeschle** [fyne-io/fyne#178]
Is there something in progress or a way to implement it?

**Comment by andydotxyz** [comment]
Do you think this is the same as #159?

**Comment by danieldaeschle** [comment]
Not exactly but it also wants Animation

**Comment by andydotxyz** [comment]
I see thanks. To do properly would require #36 and that was voted down in the 1.1 planning so it’s not in the short term roadmap.

What sort of animation were you envisaging? Is it the click ripple? https://medium.com/@jh3y/how-to-create-the-ripple-effect-from-google-material-design-c6f993e1d39

**Comment by danieldaeschle** [comment]
Ripple as example

**Comment by andydotxyz** [comment]
This will be in 2.0 :)
