### ISSUE TITLE
Right-click menu allows multiple entries to look focused

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1780]
### Describe the bug:

Right-click on an Entry and moving to another one allows multiple Entry widget to look focused.
Related to #1774 

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo.
2. Go to any tab that have more than one entry.
3. Click on one Entry and right-click on it.
4. Click on other Entry.
5. See error

### Screenshots:

https://user-images.githubusercontent.com/12239342/104434419-31bf4100-5559-11eb-9b52-6bc9fc981786.mp4

### Device (please complete the following information):
 - **OS:** MacOS 
 - **Version:** 10.15.4 Catalina 
 - **Go version:** 1.15.6 
 - **Fyne version:** develop @ ee882d72

**Comment by andydotxyz** [comment]
Fixed :)
