### ISSUE TITLE
Wrong colour in scrolling entry when deleting text

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1786]
### Describe the bug:

Deleting text from an entry widget from the far right show a different colour behind the widget.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to the entry or form page in `fyne_demo`
2. Paste a long piece of text into the entry (ctrl + a and ctrl + v on this page perhaps?).
3. Hold down backspace to delete text
4. Notice how the background is broken

### Screenshots:

![entry-delete](https://user-images.githubusercontent.com/25466657/104481258-db3c1c00-55c5-11eb-9ec2-4cd01a2d2af4.gif)

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.10.5
 - **Go version:** 1.15.6
 - **Fyne version:** develop @ f111a10583880fd238c32c7fdcf178f58a0fb41a

**Comment by andydotxyz** [comment]
I think this will go away when we get #1656 landed

**Comment by andydotxyz** [comment]
This should now be resolved on `develop`

**Comment by Jacalz** [comment]
Indeed. Works as expected.
