### ISSUE TITLE
Entry no longer supports TextWrapOff

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1793]
### Describe the bug:
Entry content is now wrapped in a scroller meaning it will no longer expand to fit the text content and instead hides it which is more like TextTruncate.

Full discussion: https://gophers.slack.com/archives/CK5U4BU87/p1610561504440100

### Screenshots:
https://gophers.slack.com/archives/CK5U4BU87/p1610563330454500

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** Big Sur
 - **Go version:** 1.15
 - **Fyne version:** f2c3fb0c

**Comment by stuartmscott** [comment]
Marking as blocker as this is a change in behaviour

**Comment by andydotxyz** [comment]
Adding scroll to Entry was always going to be a break in behaviour, but yes lets add this.
What I can't figure out is the default value. We could leave it as NoWrap - but it would be non-obvious that to enable scrolling you need to set Truncate.

Instead I would prefer setting Truncate - with some documentation that for Entry truncate means scroll-horizontal.
Then setting it to NoWrap enables developers to get the old behaviour...?

Sound OK @stuartmscott?

**Comment by stuartmscott** [comment]
Sounds OK, tho I think the default for Entries used in Dialogs should be NoWrap

**Comment by andydotxyz** [comment]
I was wondering the same thing - but there are complaints that the dialogs get too big for window when typing - so I would have to think hard about that.
Can we land a fix that defaults to scrolling then consider dialogs separately perhaps?

**Comment by andydotxyz** [comment]
On `develop` now :)
