### ISSUE TITLE
Entry scroller inset

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1794]
### Describe the bug:
Entry scroller is inset from the leading and trailing edges by theme.Padding, resulting in an aesthetically displeasing location of the gradient.

### Screenshots:
https://gophers.slack.com/archives/CK5U4BU87/p1610563330454500
<img width="455" alt="Screen Shot 2021-01-13 at 14 41 08" src="https://user-images.githubusercontent.com/1117080/104518913-6230ca80-55ad-11eb-9507-46e0eac50759.png">

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** Big Sur
 - **Go version:** 1.15
 - **Fyne version:** f2c3fb0c

**Comment by andydotxyz** [comment]
Merged into develop
