### ISSUE TITLE
Entry content rendered under validation icon

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1795]
### Describe the bug:
Entry content gets rendered underneath the validation icon

### Screenshots:
https://gophers.slack.com/archives/CK5U4BU87/p1610563330454500

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** Big Sur
 - **Go version:** 1.15
 - **Fyne version:** f2c3fb0c

**Comment by AlbinoGeek** [comment]
For reference, the correct behaviour (from MD spec) is to have the icon push away text (padding equiv. to the Entry's edge.):
![image](https://user-images.githubusercontent.com/1910461/104578939-2bd86700-5610-11eb-934a-30c490e8a05d.png)

**Comment by andydotxyz** [comment]
Strange. This was working a week ago. I wonder what changed!

**Comment by andydotxyz** [comment]
Merged into develop
