### ISSUE TITLE
Radio focus circle cutoff

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1796]
### Describe the bug:
The circle behind radio indicating focus gets cut off.

### Screenshots:
<img width="210" alt="Screen Shot 2021-01-13 at 14 45 21" src="https://user-images.githubusercontent.com/1117080/104519238-f864f080-55ad-11eb-919c-2f4f5eab5bec.png">

### Device (please complete the following information):
- OS: MacOS
- Version: Big Sur
- Go version: 1.15
- Fyne version: f2c3fb0

**Comment by fpabl0** [comment]
I think this is related to the `FocusIndicator` color, currently it is `theme.BackgroundColor` (when not focused) but maybe it is better to set it to `color.Transparent`?

**Comment by AlbinoGeek** [comment]
@fpabl0 That's because `fyne` currently actively avoids using `color.Transparent` (well, any sort of alpha really) in the core UI due to the performance requirements (afaik they are not using glshaders yet.)

**Comment by fpabl0** [comment]
> That's because fyne currently actively avoids using color.Transparent

Oh I see, I didn't know sorry.

**Comment by andydotxyz** [comment]
This was due to the offsets changing leading to the next radio item in the list drawing its background over the previous item.

with background colour gone for widgets this is no longer visible but does still indicate a potential layout issue.

**Comment by andydotxyz** [comment]
I'm going to close as this is not evident any more
