### ISSUE TITLE
Add option to disable UI animations

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1813]
This should not turn off all animation usage, but should be made available to UI so that animations that think they are optional can opt out of displaying and just show the last frame instead.

For example:
* Tab indicator
* Text cursor
* Buttton taps

Non-optional:
* progress bar

**Comment by nemunaire** [comment]
On Linux without graphical acceleration (eg. in VM/Docker container), animations like cursor blinking acts as a cpuburn. When there is no animation involved, this is perfect, but as soon as we entered text in a field (the cursor blink), `llvmpipe`, the mesa fallback library when there is no acceleration available, consume 100% CPU. The interface is still reactive through.

**Comment by andydotxyz** [comment]
This will be in v2.4.0, can be tested on develop already :)
