### ISSUE TITLE
develop: Test_gLDriver_AbsolutePositionForObject fail

### ISSUE THREAD

**Issue by adrianre12** [fyne-io/fyne#1814]
### Describe the bug:
Windows10 and a linux Mint 20 VM are both failing with the following error
--- FAIL: Test_gLDriver_AbsolutePositionForObject (0.98s)
    --- FAIL: Test_gLDriver_AbsolutePositionForObject/a_row (0.00s)
        driver_test.go:103: 
            	Error Trace:	driver_test.go:103
            	Error:      	Not equal: 
            	            	expected: fyne.Position{X:4, Y:66}
            	            	actual  : fyne.Position{X:4, Y:74}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,3 +2,3 @@
            	            	  X: (float32) 4,
            	            	- Y: (float32) 66
            	            	+ Y: (float32) 74
            	            	 }
            	Test:       	Test_gLDriver_AbsolutePositionForObject/a_row
    --- FAIL: Test_gLDriver_AbsolutePositionForObject/an_overlay_item (0.00s)
        driver_test.go:103: 
            	Error Trace:	driver_test.go:103
            	Error:      	Not equal: 
            	            	expected: fyne.Position{X:79, Y:85}
            	            	actual  : fyne.Position{X:79, Y:81}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,3 +2,3 @@
            	            	  X: (float32) 79,
            	            	- Y: (float32) 85
            	            	+ Y: (float32) 81
            	            	 }
            	Test:       	Test_gLDriver_AbsolutePositionForObject/an_overlay_item
    --- FAIL: Test_gLDriver_AbsolutePositionForObject/the_overlay_content (0.00s)
        driver_test.go:103: 
            	Error Trace:	driver_test.go:103
            	Error:      	Not equal: 
            	            	expected: fyne.Position{X:79, Y:52}
            	            	actual  : fyne.Position{X:79, Y:40}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,3 +2,3 @@
            	            	  X: (float32) 79,
            	            	- Y: (float32) 52
            	            	+ Y: (float32) 40
            	            	 }
            	Test:       	Test_gLDriver_AbsolutePositionForObject/the_overlay_content
FAIL
--- FAIL: TestWindow_DragObjectThatMoves (0.22s)
    window_test.go:392: 
        	Error Trace:	window_test.go:392
        	Error:      	Not equal: 
        	            	expected: &fyne.DragEvent{PointEvent:fyne.PointEvent{AbsolutePosition:fyne.Position{X:10, Y:10}, Position:fyne.Position{X:7, Y:7}}, Dragged:fyne.Delta{DX:2, DY:2}}
        	            	actual  : &fyne.DragEvent{PointEvent:fyne.PointEvent{AbsolutePosition:fyne.Position{X:10, Y:10}, Position:fyne.Position{X:6, Y:6}}, Dragged:fyne.Delta{DX:2, DY:2}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -7,4 +7,4 @@
        	            	   Position: (fyne.Position) {
        	            	-   X: (float32) 7,
        	            	-   Y: (float32) 7
        	            	+   X: (float32) 6,
        	            	+   Y: (float32) 6
        	            	   }
        	Test:       	TestWindow_DragObjectThatMoves
It started with the commit
commit 4dae40950b12c69d4dbdb8553a866804e907dddb 
Merge: 52e110dc 3c0cbd76
Author: Tilo Prütz <tilo@pruetz.net>
Date:   Thu Jan 14 11:40:56 2021 +0100

    Merge pull request #1712 from toaster/feature/keyboard_controllable_main_menu
    
    Feature/keyboard controllable main menu

### To Reproduce:
go test ./... -count=1

### Device (please complete the following information):
 - **OS:** Linux and Windows
 - **Version:** Mint 20 and Windows 10
 - **Go version:** 1.15.6
 - **Fyne version:** develop HEAD

**Comment by toaster** [comment]
The origin of the `TestWindow_DragObjectThatMoves` is described in #1818.

**Comment by toaster** [comment]
The specified origin is wrong. The failure goes back to b71fa2f32a83d0e683618d8086f1978e81ea8165 of #1767.

**Note**: it might be necessary to disable the loop’s window closed handling (lines 103-148 of glfw/loop.go) to ensure that the test runs do not exit prematurely.

**Comment by andydotxyz** [comment]
Yes it turns out that this was not updated when Label got taller. 
I have pushed the updated numbers and all is well
