### ISSUE TITLE
develop: TestWindow_DragIntoNewObjectKeepingFocus & TestWindow_HoverableOnDragging fail

### ISSUE THREAD

**Issue by adrianre12** [fyne-io/fyne#1815]
### Describe the bug:
Windows10 and a linux Mint 20 VM are both failing with the following errors
--- FAIL: TestWindow_DragIntoNewObjectKeepingFocus (0.88s)
    window_test.go:306: 
        	Error Trace:	window_test.go:306
        	Error:      	Not equal: 
        	            	expected: *desktop.MouseEvent(&desktop.MouseEvent{PointEvent:fyne.PointEvent{AbsolutePosition:fyne.Position{X:19, Y:9}, Position:fyne.Position{X:15, Y:5}}, Button:1, Modifier:0})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestWindow_DragIntoNewObjectKeepingFocus
    window_test.go:316: 
        	Error Trace:	window_test.go:316
        	Error:      	Expected nil, but got: &desktop.MouseEvent{PointEvent:fyne.PointEvent{AbsolutePosition:fyne.Position{X:19, Y:9}, Position:fyne.Position{X:1, Y:5}}, Button:1, Modifier:0}
        	Test:       	TestWindow_DragIntoNewObjectKeepingFocus
FAIL
--- FAIL: TestWindow_HoverableOnDragging (0.96s)
    window_test.go:377: 
        	Error Trace:	window_test.go:377
        	Error:      	Expected nil, but got: &desktop.MouseEvent{PointEvent:fyne.PointEvent{AbsolutePosition:fyne.Position{X:8, Y:8}, Position:fyne.Position{X:4, Y:4}}, Button:1, Modifier:0}
        	Test:       	TestWindow_HoverableOnDragging
FAIL

Started with commit
commit bb4c70a554d62478e6897e8fbc2368eb47c3d834
Author: Andy Williams <andy@andywilliams.me>
Date:   Wed Jan 13 20:21:17 2021 +0000

    move drag init into mouse moved

### To Reproduce:
go test ./... -count=1

### Device (please complete the following information):
 - **OS:** Linux and Windows
 - **Version:** Mint 20 and Windows 10
 - **Go version:** 1.15.6
 - **Fyne version:** develop HEAD

**Comment by toaster** [comment]
Note: it might be necessary to disable the loop’s window closed handling (lines 103-148 of glfw/loop.go) to ensure that the test runs do not exit prematurely.

**Comment by andydotxyz** [comment]
Fixed now, sorry missed this before
