### ISSUE TITLE
Ubuntu 18.04 - Readme Example Works but Throws Errors

### ISSUE THREAD

**Issue by benwinding** [fyne-io/fyne#182]
I'm getting a strange error when I run the example in the readme. It seems to run fine, but throws this output in terminal.

```
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Environment
- Linux 4.15.0-46-generic
- Ubuntu 18.04
- Go 1.12.1

Please let me know if you need any other information to resolve this.

**Comment by andydotxyz** [comment]
These are compile warnings from the graphics library that we use - you can ignore them. We could be patching the upstream project but I think they are most of the way through development of the next major release.

**Comment by rootVIII** [comment]
This one was throwing me off as well. Actually I have the exact same setup as @benwinding ... However I though mine was just crashing as it takes a while for the UI to actually appear/open. I was assuming that it just didn't work until I didn't pay attention for a moment (and the GUI eventually appeared). Well there's always ```go run main.go 2> /dev/null``` haha

**Comment by andydotxyz** [comment]
Ah yes, first run can be slow as it's got a lot of compiling to do!
I may update the docs to do a "go build" on first compilation so that it doesn't look like the app is slow ;)

This warning is now fixed on our develop branch.

**Comment by rootVIII** [comment]
Awesome thank you!
