### ISSUE TITLE
'NSUserNotification' has been explicitly marked deprecated here

### ISSUE THREAD

**Issue by J7mbo** [fyne-io/fyne#1833]
### Describe the bug:

When running a standard Fyne app, the following warnings appear in the console:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:24:12: note: 'NSUserNotification' has been explicitly marked deprecated here
```

### Screenshots:

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/2657310/105071932-7ed57280-5a85-11eb-9c97-fc731d0d720a.png">

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** Big Sur 11.0.1
 - **Go version:** go1.13.5 darwin/amd64
 - **Fyne version:** 1.4.3

Thanks for a fantastic fun tool!

**Comment by andydotxyz** [comment]
On `develop` for testing, ready for 2.1
