### ISSUE TITLE
Creating a window shows it before calling .Show() and .Hide() does not work

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1835]
### Describe the bug:

Creating a second window and building using the mobile driver shows the second window without every calling `.Show()` on the second window. The only way to avoid showing the window is to explicitly close it. Calling `.Hide()` leaves the first window not rendering at all.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code using `go run -tags mobile main.go`
2. Close the second window by adding `w2.Close()`
3. Run the modified example code using `go run -tags mobile main.go`
4. Change the `w2.Close()` call to `w2.Hide()`
5. Run the modified example code using `go run -tags mobile main.go`

### Screenshots:

![image](https://user-images.githubusercontent.com/25466657/105168527-8b57da80-5b1a-11eb-983f-ffce8b335310.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w2 := a.NewWindow("Second")
	w2.SetContent(widget.NewLabel("Second window"))

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux (-tags mobile) and Android have been tested
 - **Version:** 5.10.6
 - **Go version:** 1.15.6 and 1.13.8
 - **Fyne version:** 2.0.0-rc5

**Comment by andydotxyz** [comment]
On `develop` and will be in 2.0.1 release
