### ISSUE TITLE
Error in form example in tour

### ISSUE THREAD

**Issue by mmpx10** [fyne-io/fyne#1839]
Error when trying to run the code example from https://developer.fyne.io/tour/widget/form.html

**form.go :**
```go
package main

import (
	"log"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Form Widget")

	entry := widget.NewEntry()
	textArea := widget.NewMultiLineEntry()

	form := &widget.Form{
		Items: []*widget.FormItem{ // we can specify items in the constructor
			{"Entry", entry}},
		OnSubmit: func() { // optional, handle form submission
			log.Println("Form submitted:", entry.Text)
			log.Println("multiline:", textArea.Text)
			myWindow.Close()
		},
	}

	// we can also append items
	form.Append("Text", textArea)

	myWindow.SetContent(form)
	myWindow.ShowAndRun()
}
```

**When runnning the code:**
```sh
go run form.go
# command-line-arguments
./form.go:19:17: too few values in "fyne.io/fyne/widget".FormItem literal
```

### Device (please complete the following information):
 - **OS:** archlinux
 - **Version:** 5.10.7-arch1-1
 - **Go version:** go1.14.6 linux/amd64
 - **Fyne version:** ? //other error
```
go get fyne.io/fyne
fyne version
could not retrieve version information (ensure module support is activated and build again)
```

**Comment by Jacalz** [comment]
Good catch. This is because of a change in fyne 1.4 that added an extra field to the form item struct. I removed the bug label (it is added automatically) as this isn't a bug in Fyne, just a little change in behavior where you need to use specify the fields. I think we'll also need to get most of the code on the developer site updated for the fyne 2.0 update tomorrow.

**Comment by Jacalz** [comment]
Again, thanks for noticing. This should now be fixed once https://github.com/fyne-io/developer.fyne.io/pull/21 lands.
