### ISSUE TITLE
`test` funcs for Desktop and Mobile driver inputs

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1842]
### Is your feature request related to a problem? Please describe:
I have a custom widget which implements `desktop.Hoverable`, `desktop.Mousable` and `mobile.Touchable` separately with slightly different behaviours each (to adjust for what feels most natural for the given input methods.)

However, the `test` package (and even `test.NewDriver()`) do not appear to provide `MouseDown` or `MouseUp` funcs, nor is there a func that would trigger the implemented `mobile.Touchable` (as it is not `Tap`-compatible.)

### Is it possible to construct a solution with the existing API?
Not sure.

### Describe the solution you'd like to see:

I'm torn, because you wouldn't want to force an import by a function accepting things from the specific driver packages, I do not know of a good solution to this problem. Specifically, for `MouseDown` and `MouseUp` one may want to inject a custom `MouseEvent`, or simply set the `desktop.MouseButton` and `desktop.Modifier`, either way requiring an import of `desktop`.

**Comment by andydotxyz** [comment]
Can't you just call MouseDown on the widget directly? The `Tap` and `Type` helpers abstract the details - but in this case you are testing the details.

**Comment by AlbinoGeek** [comment]
Humm, I'm not entirely sure why there would be an abstraction for `Tap` and not the others, unless it's as simple as the separation of the drivers (mobile/desktop v.s. "no explicit driver import requirement")

I suppose I'll close this one as a... "explicit driver implementation require no-hands-holding manual testing"

---

Also worth noting that I never got `test.MouseMove` to trigger my hover actions either.

Goes back to the `AbsolutePositionFor...` not working at all #1841

**Comment by andydotxyz** [comment]
> Humm, I'm not entirely sure why there would be an abstraction for Tap and not the others,

It's because `Tapped` is an abstraction, so `test` has support for it. `desktop.MouseMoved` is not an abstraction - it a driver specific requirement that should not be exposed through the general purpose test helpers, IMHO.

**Comment by AlbinoGeek** [comment]
Thanks for the explanation :)

I did not think `Tapped` was an abstraction, I can write a manual call to `Tapped` the same way as I can `desktop.MouseMoved` -- so unless you mean that "it's abstracted because it's in the `fyne` package", which then totally explains why the comment about drivers.

**Comment by andydotxyz** [comment]
`Tapped` is abstracted in that it does not relate to an explicit hardware interaction, hence abstracted.
The test framework was supposed to focus on these types of behaviours rather than device specific actions (as that is the focus of the toolkit).

**Comment by AlbinoGeek** [comment]
Ahhhh, okay, gotcha.
