### ISSUE TITLE
Device Orientation Mode

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1846]
### Is your feature request related to a problem? Please describe:

I cannot force the platform to always use the sensor's orientation for my application. (Example: AR)

### Is it possible to construct a solution with the existing API?

No. (Although, adding a method to `App` would be non-breaking, because afaik, users are not supposed to extend `App`.)

### Describe the solution you'd like to see:

You should be able to change the OrientationType such that the following modes are supported:

As documented by both iOS (at least in Xamarin and XCode examples) and Android:

|Mode|Summary
|-|-
|Locked|Only hinted orientations are allowed
|Sensor|Orientation is forced to sensors (regardless of user setting)
|User|Orientation respects user's lock settings, following hints otherwise

**Comment by andydotxyz** [comment]
We chatted on slack and (at least at this time) there is not much of a use-case to allow apps to over-ride the user specified "auto rotate" OS configuration (and I think only Android allows this).
