### ISSUE TITLE
Cant get seticon to work

### ISSUE THREAD

**Issue by fishfishfish2104** [fyne-io/fyne#185]
I've tried window.seticon and app.seticon and neither seem to change the icon of the app in either the task bar or on the window itself and neither give any errors currently tried on arch linux kde as de can give example code too

**Comment by fishfishfish2104** [comment]
https://hastebin.com/gaguhacude.go as example code resourceIcon is defined in a file created with fyne bundle

**Comment by andydotxyz** [comment]
It is possibly related to the image format. One thing that fyne could possibly do better is to hide the complexity of supported image types for your desktop environment by converting them on the fly.

Do you have an example image or details of the format?

**Comment by fishfishfish2104** [comment]
I have used jpg and svg none seem to work I don't mind converting but it might be useful to document that it only supports whatever is supported though converting them on the fly sounds good too could you tell me the supported formats in the meantime

**Comment by fishfishfish2104** [comment]
png doesn't seem to work either

**Comment by andydotxyz** [comment]
PNG is the best to use - that is what we have tested with.

Can you confirm what icon you see? Is it the Fyne icon or something else?

**Comment by fishfishfish2104** [comment]
I see the fyne icon just tested with png didn't seem to work for me does it have to be a specific size?

**Comment by fishfishfish2104** [comment]
I just got the default icon by ioutil.WriteFile("defaultIcon", app.Icon().Content(), 0666) and rotated it by 90 degrees and used that in my program to test it still didn't work

**Comment by fishfishfish2104** [comment]
![rotated](https://user-images.githubusercontent.com/16485618/54979075-10e5ce80-5007-11e9-98a0-92c150ea0c23.png)

this is the icon i tried setting my program to

**Comment by andydotxyz** [comment]
Can you test one of the examples that does have a custom icon just so we can eliminate potential blind alleys?

`go get github.com/fyne-io/examples/cmd/solitaire`

then run the solitare command? It has a custom icon - does it appear for you?

**Comment by fishfishfish2104** [comment]
sure try that now

**Comment by fishfishfish2104** [comment]
still get default icon weird

**Comment by fishfishfish2104** [comment]
what should it look like

**Comment by andydotxyz** [comment]
https://github.com/fyne-io/examples/blob/develop/img/icon/solitaire.png

**Comment by fishfishfish2104** [comment]
Im talking about the icon that shows up in the taskbar and top left corner of the window sorry for any confusion

**Comment by andydotxyz** [comment]
I tested on Arch linux with Gnome and XFCE and both work. I don't have KDE to hand but it seems unlikely to be the WM picking up the *wrong* custom icon - I could understand if it was showing no custom icon.

Have you downloaded Fyne recently?
The only other random thought is that the custom icon you have packaged is not what you thought?...
Do you have the "fyne bundle command" that you were using?

**Comment by fishfishfish2104** [comment]
i downloaded fyne earlier this week the command i was using for fyne bundle was fyne bundle icon.png > icon.go then when i ran the program i ran it with go run main.go icon.go

**Comment by andydotxyz** [comment]
This is very strange indeed. Can you clear out any go build caches etc?
Also it might be worth running "go build main.go icon.go" then running the binary file...

I'm running out of thoughts sorry! It sounds mostly like somehow the data you have compiled is not getting set.
Looking at the code I have found an issue with the window.SetIcon - but app.SetIcon should be working just fine...

**Comment by fishfishfish2104** [comment]
hmmm ok i'll try everthing in a new folder see if that helps

**Comment by fishfishfish2104** [comment]
doesn't help I might try it in gnome see if that works just to check

**Comment by fishfishfish2104** [comment]
never mind don't have a gnome iso handy

**Comment by andydotxyz** [comment]
I installed KDE here and ran the fyne examples app. The icon successfully updated as expected. I have updated it so that each app window shows a different icon - it should be a good test app for you now.

**Comment by fishfishfish2104** [comment]
I will try this out when i get home thanks for all the help

**Comment by fishfishfish2104** [comment]
still doesn't seem to work for me which is very weird I might try to test on my laptop which is running awesomewm see if it works there

**Comment by fishfishfish2104** [comment]
doesn't seem to work on my laptop either

**Comment by andydotxyz** [comment]
If you update fyne (`go get -u fyne.io/fyne`) and then update to the latest examples repo as well - what icons do you see for each of the windows  (they should all be different).

**Comment by fishfishfish2104** [comment]
I see the icons on my laptop I will test on my computer when I get home

**Comment by fishfishfish2104** [comment]
It Works! thanks for all your help I appreciate it
