### ISSUE TITLE
Complete support for Wayland clients

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#1851]
Currently in testing with `-tags wayland`, this needs a checklist of work to complete.

- [x] Scale detection does not work correctly
~- [ ] Window is not always filled when first shown (resize fixes)~ (this is not a Wayland specific issue - #4964)
~- [ ] Menu bar can be moved up under titlebar, perhaps when window minsize shrinks~ (cannot reproduce any more)
- [x] Find a solution for the window decorations... Request SSD or render something like FyneDesk?
- [x] Read scale information from the environment

Discussed on a recent call, wayland is not quite ready to be default on and auto-switch, but we will complete support in v2.5.x and test thoroughly with it defaulting on in v2.6.0 estimated.

~- [ ] Requires -tags wayland, update GLFW once that is removed and update our code accordingly~

**Comment by brianredbeard** [comment]
As a note for anyone who comes along, you'll also need the headers for `xkbcommon` (e.g. `libxkbcommon-devel` in RPM based distros, `libxkbcommon-dev` in DEB based ones, etc).

**Comment by brianredbeard** [comment]
Also, affected by go-gl/glfw#316:

```bash
[~/Projects/golang/src/fyne.io/fyne/v2/cmd/fyne_demo]$ go build -o fyne_demo-wayland -tags wayland . ;  echo $?
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:190,
                 from ./glfw/src/context.c:30,
                 from ../../../../../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210311203641-62640a716d48/c_glfw.go:4:
./glfw/src/wl_platform.h:60:10: fatal error: wayland-xdg-decoration-client-protocol.h: No such file or directory
   60 | #include "wayland-xdg-decoration-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
2
```

**Comment by andydotxyz** [comment]
Thanks for noticing this. Fix is now on `release/v2.0.x` branch ready for 2.0.3 release

**Comment by brianredbeard** [comment]
Definitely getting some weird behavior.  Presently thinking through how to record a short video to demonstrate, but at a minimum the following errors are thrown on Fedora 33 using Wayland + GNOME3:

```
[~/Projects/golang/src/fyne.io/fyne/v2/cmd/fyne_demo]$ ./fyne_demo-wayland 
2021/05/05 14:34:29 PlatformError: Wayland: Focusing a window requires user interaction
2021/05/05 14:34:29 PlatformError: Wayland: Setting window icon not supported
2021/05/05 14:34:29 PlatformError: Wayland: Focusing a window requires user interaction
2021/05/05 14:34:29 PlatformError: Wayland: Window position retrieval not supported
```

**Comment by andydotxyz** [comment]
Those errors should not impact how your application works. Though we do need to remove the issues they hint at.

**Comment by iMonZ** [comment]
Anything new here?

**Comment by andydotxyz** [comment]
That is a good question, what are we short of?
As far as I know it's just the border decorations, I was hoping there would become an official way to request SSD so we didn't have to impose our (FyneDesk?) borders on other desktops...

**Comment by Lewiscowles1986** [comment]
> I was hoping there would become an official way to request SSD

For anyone as confused as I was, [SSD is server side decorations](https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/) where server, refers to a display server; which Wayland is.

**Comment by Lewiscowles1986** [comment]
Bizarre as it may be I did some light reading and found that there are three options.

CSD: Client-side decorations
SSD: Server-side decorations
DWD: Dynamic Window decorations [link to article announcing as jumping in point](https://kver.wordpress.com/2014/10/25/presenting-dwd-a-candidate-for-kde-window-decorations/)

While the acronyms/initialisms are unhelpful at best; maybe some of the findings help?

**Comment by andydotxyz** [comment]
Yeah, I agree that SSD with the ability for app to add items to some extent is probably the best way to go for consistency (good UX) and some flexibility to promote controls etc.

Enlightenment played with this a little by allowing modules to place things like volume control into the window title bar.

**Comment by Jacalz** [comment]
For consistency though, wouldn’t it make the most sense to render the same decorations as the desktop environment? I mean rendering the same style of decoration as if it was running in X11?

**Comment by andydotxyz** [comment]
> For consistency though, wouldn’t it make the most sense to render the same decorations as the desktop environment? I mean rendering the same style of decoration as if it was running in X11?

That is basically what SSD is

**Comment by Jacalz** [comment]
Haha, alright. In my mind, I must have had them flipped 😅

**Comment by iMonZ** [comment]
> For consistency though, wouldn’t it make the most sense to render the same decorations as the desktop environment? I mean rendering the same style of decoration as if it was running in X11?

That’s not possible with Mutter :(
Maybe someone can create an issue and they add this issue.
But for me I like ssd more especially because I can use my own custom cursor instead of the app provided one.

**Comment by Bluebugs** [comment]
There won't be ever a consensus on SSD with Wayland as this is seen by most of the community as a move backward in term of performance (battery saving being a big one here) and toolkit are supposed to be "themable" enough that the distribution can provide a consistent theme across all toolkit (a bit of hand waving there).

The other error reported here (focus and window position) are also not available and won't be under Wayland. One reason is security, as you do not want an application to have the ability to grab focus without the user consent and consent is built via interaction. For the window positioning problem, the logic is that Wayland should has a protocol work the same way if you decide you window manager is displaying your window in a 3D VR environment for example.

**Comment by andydotxyz** [comment]
Trying to capture the TODO list, adding it to the top of the issue so it doesn't get lost in the content here.

**Comment by andydotxyz** [comment]
We want to move forward with 2.4, and won't let the GLFW dep hold things back, so this will need to be pushed again

**Comment by Jacalz** [comment]
Status update: Fyne v2.5.0 will have much improved Wayland support. Upstream GLFW has solved the window decoration issues and I made sure to silence some of the platform warnings that was printed to the terminal.

**Comment by andydotxyz** [comment]
I cannot see anything more that needs done, working great for me :)
