### ISSUE TITLE
[Q] Purpose of Milestones

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1854]
What is the differentiator between the following milestones purposes?

[13: 2.0.x - bugfixes since binding, storage, animation addition](https://github.com/fyne-io/fyne/milestone/13)
[14: Aberlour (next release)](https://github.com/fyne-io/fyne/milestone/14)

I would have assumed that this meant all bugs introduced in or before 2.0.x would end up in milestone 13, whereas anything new (features, changes, etc) otherwise that could come before 3.x and feel like short wins ends up in milestone 14?

However, this assumption does not match the reality of the contents of the milestones, hence my question.

**Comment by andydotxyz** [comment]
Aberlour is the next planned/big release (I.e. not patch) which we will be doing approx 3 per year, we are planning what goes into it. The 2.0.x is anything small that could/should be fixed before then.
The 3.0 milestone is an old placeholder for things we want to do but are not yet planned. There may be many releases between 2.0 and 3.0.

**Comment by AlbinoGeek** [comment]
Sounds good, thank you for that explanation :).

I remember Aberlour from the call, but didn't know what the 2.0.x branch might specifically hold.
