### ISSUE TITLE
`fyne.LogError` uses hard-coded PC?

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1856]
Is it intentional that `fyne.LogError` not make use of the `xerrors` package you vendored in?

https://github.com/fyne-io/fyne/blob/master/log.go

I could see this providing more context to the developer.

( However, I also understand if due to the structure of `fyne`, that calls to `LogError` may not have a legible stack, e.g: could be completely unrelated to user code. )

**Comment by andydotxyz** [comment]
This attempts to balance useful information with not-huge-stack.
If developers want more info they can breakpoint on LogError to get the full details.

**Comment by AlbinoGeek** [comment]
Humm... and I suppose `LogError` is only exported because other packages in fyne use it?

**Comment by andydotxyz** [comment]
Any developer can use it - if they would like a short summary of errors being logged to the console without a full stack dump.
Unless documented otherwise our exported methods are exported for public use.

**Comment by AlbinoGeek** [comment]
Gotcha, okay. I wasn't sure when it prefixed them with `fyne error` whether end-developers were expected to use it or not. I wouldn't exactly call a "only-to-console, only-errors" facility a fully-fledged logger, but it would definitely be "more than enough" when testing things locally, scaffolding, etc etc.

It's a great func for quick-starting PoCs then :).

**Comment by andydotxyz** [comment]
> I wouldn't exactly call a "only-to-console, only-errors" facility a fully-fledged logger,

Neither would I, which is why I didn't :(.
