### ISSUE TITLE
exec.Command and widget.Button combination not working

### ISSUE THREAD

**Issue by ekanna** [fyne-io/fyne#1857]
### exec.Command making entire window as a button:
I have few files in one folder. I want to open that folder when a user clicks on `widget.Button` using native FileOpenDialog.  First click is working fine but after second click, **wherever** i click on window, it is only opening folder!

### To Reproduce:
Steps to reproduce the behaviour:
1. Click on hello button it will open native fileOpenDialog
2. Close that DialogBox
3. Now click anywhere on the window it will open only FileOpenDialog

### Video:

https://slack-files.com/T029RQSE6-F01L1LDM857-4ba662ff80

### Example code:
```go
package main

import (
	"os/exec"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func exploreDirectory() {
	cmd := exec.Command("open", ".") // open current directory
	cmd.Start()
}

func main() {
	a := app.New()
	w := a.NewWindow("foo")

	b := widget.NewButton("Open", func() {
		//fmt.Println("Hai")
		exploreDirectory()
	})
	title1 := widget.NewLabel("Hello")
	title2 := widget.NewLabel("World")
	k := container.NewVBox(title1, b, title2)
	w.SetContent(k)
	w.Resize(fyne.NewSize(200, 200))
	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:**  MacOS
 - **Version:** 10.14.3
 - **Go version:** 1.15.2
 - **Fyne version:** 1.14 and 2.0

**Comment by nick-remeeting** [comment]
+1. I've seen this bug in the context of a button opening a webpage. It seems like if (any?) new window is opened by a button click, clicking back into the Fyne window will trigger that button click again.

The only way to get focus back on the Fyne window appears to be to click the title bar of the window.

**Comment by andydotxyz** [comment]
Hmm, I see this too now.
This is not for any new window, it is for any new window in a different application.
So it seems like we are not resetting the button/mouse states correctly when the app loses focus.

**Comment by andydotxyz** [comment]
This is now ready for testing on `release/v2.0.x` branch
