### ISSUE TITLE
[Feature] MeasureTextDistanceToBaseline function

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1859]
### Is your feature request related to a problem? Please describe:

Not really, but it would be interesting to have a way to measure the distance from the top of the canvas.Text to its baseline (for alignment purposes in the future), as the current function `fyne.MeasureText` only returns the ideal size to be drawn and it has some "padding" on top and bottom.

### Is it possible to construct a solution with the existing API?

Yes, it is possible, although it means introducing a new function.
### Describe the solution you'd like to see:

Maybe there could be an internal function called `RenderedTextDistanceToBaseline` or something like it, it could be implemented with the functions used to implement `RenderedTextSize`:

```
func RenderedTextDistanceToBaseline(size float32, style fyne.TextStyle) float32 {
	var opts truetype.Options
	opts.Size = float64(size)
	opts.DPI = TextDPI
	face := CachedFontFace(style, &opts)
	return float32(face.Metrics().Ascent.Ceil())
}
```

Then there could be a public function called `fyne.MeasureTextDistanceToBaseline` that could be implemented just like `fyne.MeasureText`:

```
func MeasureTextDistanceToBaseline(size float32, style TextStyle) Size {
	return CurrentApp().Driver().RenderedTextDistanceToBaseline(size, style)
}
```

**Comment by andydotxyz** [comment]
> function `fyne.MeasureText` only returns the ideal size to be drawn and it has some "padding" on top and bottom.

There should not be any extra padding: https://github.com/fyne-io/fyne/blob/ec966e729738083602e632c4092dfc35be65ed6f/internal/painter/font.go#L28

Perhaps we should return more information from the driver call?
I'm not sure that I would automatically add a new top-level function to return this, it doesn't seem like it will be used by many devs in day-to-day development.

**Comment by fpabl0** [comment]
> There should not be any extra padding:

Yes, I know, that's why I use quotes, however the returned size by `fyne.MeasureText` is just the ideal to graph it in the canvas. But it doesn't give us any information about its baseline.

> I'm not sure that I would automatically add a new top-level function to return this, it doesn't seem like it will be used by many devs in day-to-day development.

In fact, it would not be used by the developers in the current state, however if baseline alignment is desired, this function is needed and also a new interface that should be implemented by widgets that have text inside and need to expose how they would be aligned based on its baseline (related to draft #1840)

**Comment by andydotxyz** [comment]
> In fact, it would not be used by the developers in the current state, however if baseline alignment is desired, this function is needed and also a new interface that should be implemented by widgets that have text inside and need to expose how they would be aligned based on its baseline (related to draft #1840)

Perhaps this relates more to the text refactor that we are planning, it would be better there so widget can embed/extend without adding new methods to the `fyne` package without real need.

**Comment by fpabl0** [comment]
> Perhaps this relates more to the text refactor that we are planning, it would be better there so widget can embed/extend without adding new methods to the fyne package without real need.

Oh that's a good point. Yes, this method can be included as part of text refactor and it would be more helpful :)

**Comment by andydotxyz** [comment]
This was added as detailed above - Driver.RenderedTextSize
