### ISSUE TITLE
How to run Fyne??

### ISSUE THREAD

**Issue by dufuqsls** [fyne-io/fyne#1862]
Hello!

First, Thank for your Fyne

I used to fyne before upgrade 2.0 to Fyne

I do "$ go get fyne.io/fyne/v2" then it show the error

### ERROR
cannot find package "github.com/fredbi/uri" in any of:
	D:\khj\go\src\fyne.io\fyne\v2\vendor\github.com\fredbi\uri (vendor tree)
	D:\ProgramFiles\Go\src\github.com\fredbi\uri (from $GOROOT)
	D:\khj\go\src\github.com\fredbi\uri (from $GOPATH)go

So i download github.com/fredbi/uri and then attach the file(../url) in vendor folder by myself

Now it's Running.

but Why? how can to build or run automatly??

**Comment by Jacalz** [comment]
I ran into this a few days ago as well and had to go get the uri package. I think there might be an issue where the uri package wasn’t correctly vendored as I did not have any issues when I don’t use the vendor folder (witch is pretty much always).

**Comment by dufuqsls** [comment]
> I ran into this a few days ago as well and had to go get the uri package. I think there might be an issue where the uri package wasn’t correctly vendored as I did not have any issues when I don’t use the vendor folder (witch is pretty much always).

Thx!

**Comment by Jacalz** [comment]
I still however think that this might be an issue with the vendor folder not having been updated. Let’s open again for now.

**Comment by dufuqsls** [comment]
Yes, I re-download fyne, but i can't still run automately, too

**Comment by andydotxyz** [comment]
That should be fixed now, sorry for missing this in the release process
