### ISSUE TITLE
How to release resources before closing the fyne application?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#1865]
Before I clicked the close button, I wanted to delete some temporary files under the fyne directory and reset the preferences.json，May I ask how I should operate it？

**Comment by Jacalz** [comment]
For doing something on closing the window, I would use the `window.SetOnClosed()` (window being the window you have created) function and then having a function there that does what you want to do and then calls `window.Close()` at the end.

For deleting files, I would just use the standard `os.Remove()` function. Resetting the preferences can either be done by deleting all values you have stored by calling `app.Preferences().RemoveValue(key string)` for each of your keys. Another approach could be to just overwrite the preferences file to be empty.

**Comment by stuartmscott** [comment]
Also note that app.Run() and window.ShowAndRun() are blocking, so any code after those calls will be executed when the app exits;

```go
func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()

	// **** Free resources here ****
}
```

**Comment by AlbinoGeek** [comment]
> Resetting the preferences can either be done by deleting all values you have stored by calling `app.Preferences().RemoveValue(key string)` for each of your keys. Another approach could be to just overwrite the preferences file to be empty.

Right, but this goes back to `app.Preferences()` having no `Walk` or `List` type func, so I don't even know what keys there are to remove. Also, what if I'm testing and I want to wipe out `fyne`'s global preferences too (like app scaling, primary color and theme variant selection.)

**Comment by andydotxyz** [comment]
Good software is generally written to pair open/close create/destroy where one scope has responsibility over both.
Whatever code adds a preference should be responsible for removing it, if that is required.
Listing all stored metadata so it can be cleaned up later sounds like there may be untidy code elsewhere...

If you are doing testing then the `test.App` will provide an in-memory preferences that has no persistence - built for unit testing :).
Your unit tests should not obliterate a system preferences. In this instance once again `test.App` provides settings that do not relate to the system user configuration.

**Comment by AlbinoGeek** [comment]
Right, I was thinking more from a user-data-control perspective.

Users have the right to view and destroy their own data, which requires (for example) the `fyne_settings` or related application to be able to list out and walk the preferences, per app, where the user would be able to go and remove erroneous or sensitive information about themselves.

Other examples include: "I set scale to 4 and now I can't load the `fyne_settings` app to change it back, because it doesn't fit on my screen." (I did this multiple times during development.)

And of course: "I'm a developer, and I want to reset all my preferences, to try what a user's first experience looks like."

**Comment by andydotxyz** [comment]
> which requires (for example) the fyne_settings or related application to be able to list out and walk the preferences, per app

I don't see why. if fyne_settings should add a feature to remove user data we can do that per-app.
Exposing the internal details of an application configuration seems like overstepping and/or not necessary.

**Comment by andydotxyz** [comment]
Anyhow, I think this has stepped beyond the question that @smp12345 was asking.
If you feel there is a missing feature please add a new ticket.

**Comment by smp12345** [comment]
Thank you very much. I will close this issue
