### ISSUE TITLE
SelectTab method does not in all cases correctly set the blue underline to the selected tab

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#1872]
### Describe the bug:
Remove the last tabitem of a tab-container, then add a new tabitem and select it as the currently selected tab. The blue underline remains  on the previous tabitem

### To Reproduce:
Steps to reproduce the behaviour: run the example code

### Example code:
package main

import (
    "fyne.io/fyne/v2" 
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/widget"
    "fyne.io/fyne/v2/layout"
    "fyne.io/fyne/v2/container"
)

var del_button     *widget.Button
  
func main() {
  var container_tab  *container.AppTabs
  a := app.New()
  w := a.NewWindow("container")
  
  del_button = widget.NewButton ("delete", func() {
      container_tab.Remove (container_tab.CurrentTab())
      item := container.NewTabItem("Delete", make_delete_container() )
      container_tab.Append(item)
      container_tab.SelectTab (item)
  })

  container_tab = container.NewAppTabs(
      container.NewTabItem("List", widget.NewButton ("list", func() {})),
      container.NewTabItem("Delete", make_delete_container()),
  )
  container_tab.SelectTabIndex(0)    
  w.SetContent (container_tab)
  w.ShowAndRun()
}

func make_delete_container () *fyne.Container {
    return fyne.NewContainerWithLayout(layout.NewMaxLayout(), del_button)
}

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:**Debian 10
 - **Go version:** 1.15.6
 - **Fyne version:** 2.0

**Comment by AlbinoGeek** [comment]
You can format code by placing it within backticks:

```go
This is a code block
```

\```go
This is a code block
\```

**Comment by andydotxyz** [comment]
Fixed on `develop` branch for next v2.0.1 release
