### ISSUE TITLE
How do I rename the fyne directory?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#1876]
The system will automatically create a "fyne" folder under your home directory to save "preferences.json". How can I rename the fyne directory to something else?
Can I customize the folder name?

**Comment by andydotxyz** [comment]
The "fyne" folder should not appear directly under your home directory - it should be within a standard configuration location.

Please provide the system / version etc information - the bug template should have been filled in so that we can better help with your issue.

**Comment by smp12345** [comment]
What you said is right, this is not a bug, my system is win10, my directory C :\ \ users\ XXXX \AppData\fyne, I just want to change "fyne" directory to other name, I can customize the folder name?

**Comment by andydotxyz** [comment]
No, this cannot be changed. Why do you need this to be changed? It is a folder that contains fyne toolkit configuration...

**Comment by smp12345** [comment]
Because I want to install it on the user's computer, the user does not know what the "fyne" directory is, and it is often deleted by mistake. I want to use my own software name as the folder name, and I hope to be able to support custom directory names

**Comment by andydotxyz** [comment]
This folder will be used by any Fyne apps, not just your own.
If your app has an ID set and uses the preferences API then your users could see your app name inside the folder, thus clarifying it's need.

**Comment by andydotxyz** [comment]
Closing this issue because we can't rename global config folder to be application specific.
