### ISSUE TITLE
Tree widget does not render correctly (may caused by card widget does not entend correctly)

### ISSUE THREAD

**Issue by wenhsinhsieh** [fyne-io/fyne#1877]
### Describe the bug:

Use a custom card widget as the tree node causing it render incorrectly. Please see the screenshot and sample code.

### Screenshots:

![treebug](https://user-images.githubusercontent.com/3656867/106117471-0447d980-618e-11eb-9a26-d51c83ce14ce.png)

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

type TapLabel struct {
	widget.Label
}

func newTapLabel(txt string) *TapLabel {
	label := &TapLabel{}
	label.ExtendBaseWidget(label)
	label.Text = txt
	return label
}

func (t *TapLabel) Tapped(pe *fyne.PointEvent) {
	fmt.Println("left click", pe.Position.X, pe.Position.Y)
}

func (t *TapLabel) TappedSecondary(pe *fyne.PointEvent) {
	fmt.Println("right click", pe.Position.X, pe.Position.Y)
}

type NodeCard struct {
	widget.Card

	Label1 *TapLabel
	Label2 *TapLabel
}

func newNodeCard() *NodeCard {
	card := &NodeCard{}
	card.ExtendBaseWidget(card)

	card.Label1 = newTapLabel("aa")
	card.Label2 = newTapLabel("bb")
	content := container.New(layout.NewVBoxLayout(), card.Label1, card.Label2)
	card.Content = content
	return card
}

type dataEntry struct {
	parent      string
	children    []string
	displayName string
}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Toolbar Widget")

	data := map[string]dataEntry{
		"":   {children: []string{"A", "B"}},
		"A":  {children: []string{"A1", "A2"}, displayName: "Root", parent: ""},
		"B":  {children: []string{"B1", "B2"}, displayName: "Root", parent: ""},
		"A1": {displayName: "Leaf", parent: "A"},
		"A2": {displayName: "Leaf", parent: "A"},
		"B1": {displayName: "Leaf", parent: "B"},
		"B2": {displayName: "Leaf", parent: "B"},
	}

	tree := &widget.Tree{
		ChildUIDs: func(uid string) []string {
			return data[uid].children
		},
		IsBranch: func(uid string) bool {
			tmp, ok := data[uid]
			return ok && len(tmp.children) > 0
		},
		CreateNode: func(branch bool) fyne.CanvasObject {
			return newNodeCard()
		},
		UpdateNode: func(uid string, branch bool, obj fyne.CanvasObject) {
			tmp, ok := data[uid]
			if !ok {
				// TBD: handle error
				fyne.LogError("Unknown node: "+uid, nil)
				return
			}
			card := obj.(*NodeCard)
			if len(tmp.parent) == 0 {
				// this is node group
				card.Title = "Root"
				card.Subtitle = "root"
			} else if len(tmp.children) == 0 {
				// this is node
				card.Title = "Leaf"
				card.Subtitle = "leaf"
			} else {
				// error, should not reach here
				card.Title = "UNKNOWN"
			}
		},
	}

	myWindow.SetContent(tree)
	myWindow.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 10
 - **Go version:** 1.14.6
 - **Fyne version:** 2.0

**Comment by andydotxyz** [comment]
Unfortunately your template is not large enough for the content you add later.
The call to `newNodeCard` is not filling out the title and subtitle, so no space is reserved. 
Consider doing the following change:

```go
	card := &NodeCard{}
	card.Title = "Title"
	card.Subtitle = "Subtitle"
	card.ExtendBaseWidget(card)
```

**Comment by wenhsinhsieh** [comment]
I tried as you suggested and it works now.
However I notice that changing the title (or content) later does not affect the height of node at all, so I guess the Tree does not have the ability to adjust the height of node depends on the actual content. Is it by design or a bug?
I'm trying to make a tree with two levels, and the first level has different height with the second level (because the contents are differnet). Is this possible with the current release?

**Comment by andydotxyz** [comment]
> so I guess the Tree widget does not have the ability to adjust the height of node depending on the actual content. Is it by design or a bug?

This is design - for Tree, Table and List to behave super-fast with large data the templates are re-used and the height is asserted to remain constant.

Tree is slightly special as you can style branch and leaf differently. If that maps to your "two levels" then you are in luck.
