### ISSUE TITLE
MenuItem display shortcut

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1881]
### Is your feature request related to a problem? Please describe:
MenuItems and shortcuts are disconnected, for example File -> Save and Command+S may do the same operation but this cannot be surfaced in the UI. This makes it harder for users to discover shortcuts.

### Is it possible to construct a solution with the existing API?
Unfortunately not, even if the menu item text was updated to display "Save (Command+S)" this would not appear correctly in native menus such as MacOS X

### Describe the solution you'd like to see:
The ability to associate a shortcut with a menu item so that tapping the menu item, or typing the shortcut would trigger the same action and the menu item would display the associated shortcut.

**Comment by rrartale** [comment]
I would like that option.

**Comment by andydotxyz** [comment]
This is already on our list, being tracked at #682 , closing as duplicate
