### ISSUE TITLE
URI Bindings

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1882]
### Is your feature request related to a problem? Please describe:
It is not possible to pass URI through the binding API.

### Is it possible to construct a solution with the existing API?
Yes, the URI can be converted to a string, passed through the string bindings, and parsed back into a URI at the other end, though this is inefficient.

### Describe the solution you'd like to see:
Additional bindings generated for fyne.URI

**Comment by andydotxyz** [comment]
On `develop` fo testing
