### ISSUE TITLE
README Images taken without focus?

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#1884]
### Describe the bug:

It would appear the images within the README were screen shots taken without the window in focus. Among other slight differences in our Widgets (and how they might look with or without focus), the most jarring difference is that the Mac OS X stoplights which normally decorate the window title are grey circles, which simply looks out of place.

<div align="center"><table><tr><td><img src="https://raw.githubusercontent.com/fyne-io/fyne/master/img/hello-light.png" alt="Fyne Hello Light Theme"/></td><td><img src="https://raw.githubusercontent.com/fyne-io/fyne/master/img/hello-dark.png" alt="Fyne Hello Dark Theme"/></td></tr></table></div>

**Comment by andydotxyz** [comment]
There is nothing focusable in these widgets (Label and Button).
The window borders are how they look on my computer.
These are window captures directly from my computer - I am not sure what the bug is...

**Comment by AlbinoGeek** [comment]
Why are the stop lights grey and not red,yellow,green ?

Is there a new "monochrome" Mac OS X system theme I'm not aware of?

**Comment by andydotxyz** [comment]
That has been a us we setting for many years.
