### ISSUE TITLE
Image in a custom widget doesn't update until window resize

### ISSUE THREAD

**Issue by sxvghd** [fyne-io/fyne#1886]
### Describe the bug:

canvas.Image inside of a custom widget won't refresh until the window gets resized.
I haven't looked "under the hood" yet, but I feel like #1480 is of similar origin. 
### Screenshots:

http://0x0.st/-o8B.mp4

### Example code:

```go
package main

import (
	"fmt"
	"image/color"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
	"github.com/fogleman/gg"
)

type Clicker struct {
	widget.BaseWidget
	Image *canvas.Image

}

func (g *Clicker) Tapped(a *fyne.PointEvent) {
	fmt.Println("Click!")
	if g.Image.Image == nil {
		im, _ := gg.LoadPNG(g.Image.File)
		c := gg.NewContextForImage(im)
		c.DrawCircle(100, 100, 100)
		c.SetRGB(0, 255, 255)
		c.Fill()
		g.Image = canvas.NewImageFromImage(c.Image())
		g.Image.FillMode = canvas.ImageFillStretch
		g.Image.Refresh()
	}
	return
}

func NewClicker(s string) (*Clicker, error) {
	ret := &Clicker{}
	ret.ExtendBaseWidget(ret)
	ret.Image = canvas.NewImageFromFile(s)
	ret.Image.FillMode = canvas.ImageFillStretch
	return ret, nil
}

func (g *Clicker) CreateRenderer() fyne.WidgetRenderer {
	return &clickerRenderer{clicker: g}
}

type clickerRenderer struct {
	clicker *Clicker
}

func (g *clickerRenderer) BackgroundColor() color.Color {
	return color.Transparent
}

func (g *clickerRenderer) Destroy() {
}

func (g *clickerRenderer) Layout(size fyne.Size) {
	g.clicker.Image.Resize(size)
}

func (g *clickerRenderer) MinSize() fyne.Size {
	return fyne.NewSize(1, 1)
}

func (g *clickerRenderer) Objects() []fyne.CanvasObject {
	return []fyne.CanvasObject{g.clicker.Image}
}

func (g *clickerRenderer) Refresh() {
	g.clicker.Image.Refresh()
}

func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	i, _ := NewClicker("test.png")
	w.SetContent(i)
	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.10.11;
 - **Go version:** 1.15.7
 - **Fyne version:** 2.0

**Comment by andydotxyz** [comment]
If you want the system to see that your widget has added new objects to its renderer you will need to call g.Refresh() instead of g.Image.Refresh() (by updating the image that you created nothing triggers a widget refresh which is when it declares the new child object)

**Comment by sxvghd** [comment]
Yeah, I had that initially, but it has the exact same outcome - no refresh.

**Comment by andydotxyz** [comment]
Can you please share that version of your code so it can be examined? I’m not aware of any issues like you’re describing, we add and remove images to widgets in many tests.

**Comment by sxvghd** [comment]
It's the thing I posted.
It just had g.Refresh() instead of g.Image.Refresh() in Tapped().
I just tested it and indeed I'm getting the same result.

**Comment by andydotxyz** [comment]
It looks like something strange is happening because you are replacing the object internally outside of the render process.
Perhaps relating to the fact that the widget size is not changing, so Layout is not called, but you create a new element, drop it into the renderer but do not configure it.

Easier would be to re-use the `Image` that you have loaded already, i.e.:
```go
//		g.Image = canvas.NewImageFromImage(c.Image()) // instead of this line, you could do:
		g.Image.File = ""
		g.Image.Image = c.Image()
```

**Comment by sxvghd** [comment]
Wow, that does work actually!
I tried that before, but I didn't clear out the `File` var, so that's probably why it was still showing me the previous `Image`.
Thanks for the help, not a bug I guess?
