### ISSUE TITLE
Need to reset the scroll position of table widget

### ISSUE THREAD

**Issue by wenhsinhsieh** [fyne-io/fyne#1892]
### Is your feature request related to a problem? Please describe:

When the length of the table widget is changed, calling refresh function doesn't reset the scroll position, so if the number of row becomes less after refresh, the scroll position becomes out of bound, which doesn't look right.

### Is it possible to construct a solution with the existing API?

No

### Describe the solution you'd like to see:

Having a way to reset the scroll position to the top.

**Comment by andydotxyz** [comment]
Just like #2105 we should probably expose some of the scrolll functions to allow this to happen.

**Comment by andydotxyz** [comment]
This probably applies to all 3 collections:

- [ ] List
- [x] Table (#2195)
- [ ] Tree

**Comment by nealmcc** [comment]
The two pull requests combined should resolve this issue

**Comment by andydotxyz** [comment]
On `develop` for testing and will be in the `v2.1` release
