### ISSUE TITLE
Strange rectangle appearing for password entry since v2.0.0.

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1894]
After migrating to v2.0.0. I noticed a strange visual artefact just near the eye-icon began to appear for `widget.PasswordEntry`. Is that intended and for what reason if it is?

<img width="184" alt="Screenshot 2021-02-02 at 16 40 30" src="https://user-images.githubusercontent.com/503292/106624700-3d10f580-6576-11eb-8b1d-c0c6ae8b28e8.png">
<img width="182" alt="Screenshot 2021-02-02 at 16 40 34" src="https://user-images.githubusercontent.com/503292/106624250-bbb96300-6575-11eb-92ca-1d3962db4083.png">

Platform: `OS X 11.1`
Go version: `go1.14.1 darwin/amd64`
Fyne version: `v2.0.0`

**Comment by andydotxyz** [comment]
It looks like a scrollbar might be appearing.
Can you please share the code so we can replicate? (As I don't see this problem with the password entry in demo)

**Comment by ababo** [comment]
```go
func newPINPageContext(
	data *pageData, finished chan<- *pageError) *pinPageContext {
	ctx := new(pinPageContext)
        ...
	ctx.pin = widget.NewPasswordEntry()
	ctx.pin.PlaceHolder = "PIN code"
	ctx.pin.OnChanged = func(text string) { handleTestPinChange(ctx) }
        ...
	return ctx
}

func createPINPageContent(cg *util.CancelGroup,
	data *pageData, finished chan<- *pageError) fyne.CanvasObject {
	...
	ctx := newPINPageContext(data, finished)

	pinSize := fyne.Size{pinPagePINWidth, pinPagePINBoxHeight}
	unlockSize := fyne.Size{pinPageUnlockWidth, pinPagePINBoxHeight}

	ctx.pinbar = fynecont.NewHBox(
		fyne.NewContainerWithLayout(
			layout.NewGridWrapLayout(pinSize),
			ctx.pin,
		),
		...
	)

	details := fynecont.NewVBox(
		...
		ctx.pinbar,
	)
	...
	panels := fynecont.NewHBox(
		...
		fynecont.NewVBox(
			wrapPanel(details),
			...
		),
	)
        ...
	vbox := fynecont.NewVBox(
		newPageTitle("Select Test"),
		newRichText(text),
		fynex.NewVerticalMargin(pinPagePanelMargin),
	)

	go func() { // Avoid ugly expanding of the test list panel.
		time.Sleep(pinPageDelay)
		vbox.Add(panels)
	}()

	...

	return vbox
}
```

**Comment by andydotxyz** [comment]
It looks like you're making this happen in your code:
```go
	pinSize := fyne.Size{pinPagePINWidth, pinPagePINBoxHeight}
```

combined with

```go
		fyne.NewContainerWithLayout(
			layout.NewGridWrapLayout(pinSize),
			ctx.pin,
		),
```

Seems to be forcing the PasswordEntry into a space too small to display, so scroll bars appear.
As mentioned in the `GridWrapLayout` docs this does not respect widget MinSize and should be used with care.

**Comment by ababo** [comment]
Confirm that, thanks!
