### ISSUE TITLE
android compile don't install and package show error no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#1895]
hey 
i code an project after use 
there are 2 problems
when i use
fyne package -os android -appID something.com
it show error 
no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME
on compile
when i use
fyne-cross android
apk build but never install on android

**Comment by Jacalz** [comment]
Have you followed the mobile packaging documentation? https://developer.fyne.io/started/packaging-mobile

**Comment by madaxemad** [comment]
> Have you followed the mobile packaging documentation? https://developer.fyne.io/started/packaging-mobile

hey yea i installed all sdk ndk but it asks
no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

**Comment by andydotxyz** [comment]
Can you call `which adb` so we can see if the NDK is installed?

**Comment by madaxemad** [comment]
> Can you call `which adb` so we can see if the NDK is installed?

hey my ndk version installed ver 22.0.7026061

i could fix 
fyne-cross must enter code like this 
fyne-cross android -app-id "(whatever with atleast one .)" -tags appID="(whatever with atleast one .)" ...
it compiles and install on any android arm x86 .... and lunch if code be ok
but still android package show error no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME
i installed ndk through SDK it placed
maybe it fixs with environment variable on windows if add right path but i have no idea how to insert it right

**Comment by AlbinoGeek** [comment]
on Windows you add environment variables as so:

https://stackoverflow.com/questions/39591551/how-to-set-ndk-environment-variable-in-windows

**Comment by andydotxyz** [comment]
> Can you call which adb so we can see if the NDK is installed?

I meant can you call the command to check that `adb` is in the path.
It does sound like your environment variables are not set up correctly.

Fyne_cross does not use your installed Android system, that is why it shows no error (it is designed to package the tools inside Docker images).

**Comment by Gys** [comment]
> hey my ndk version installed ver 22.0.7026061

> but still android package show error no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

I had the same problem. Setting the env var took a bit experimenting. This works for me:
`ANDROID_NDK_HOME=/Users/XXXXX/Library/Android/sdk/ndk/22.0.7026061 fyne package -os android -appID com.example.myapp -icon icon.png`

**Comment by Gys** [comment]
But see also https://github.com/fyne-io/fyne/issues/1912

**Comment by madaxemad** [comment]
> on Windows you add environment variables as so:
> 
> https://stackoverflow.com/questions/39591551/how-to-set-ndk-environment-variable-in-windows

@Gys thanks from @AlbinoGeek problem for compile with fyne solved for me 
but adding environment variables is a little different on link 
must add it where can have a name not only it path
also try NDK versions too i could extract with 19.2.5345600 version

**Comment by DiskGetor** [comment]
i have same problem, when i build on android, then build it on notebook,because i do not known install android sdk ndk on arm64 manjaro linux.

![Screenshot_20210418_192741_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/115143840-2d388600-a07c-11eb-9245-402ed2a8222a.jpg)

**Comment by andydotxyz** [comment]
There should be plenty of documentation online about installing Android NDK, or you could read the Fyne book which details it in the appendix.
