### ISSUE TITLE
how to path a folder on android for app

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#1899]
hey 
for example i want create a .txt file on android device on internal storage how do i path it on a Specific folder?
file, err := os.Create("(path)")
"(path)" ?
thanks

**Comment by AlbinoGeek** [comment]
In theory:

https://pkg.go.dev/fyne.io/fyne/v2/storage

```golang
func OpenFileFromURI(uri fyne.URI) (fyne.URIReadCloser, error)
func SaveFileToURI(uri fyne.URI) (fyne.URIWriteCloser, error) 
```

**Comment by AlbinoGeek** [comment]
Maybe `app.Storage().RootURI()` ?

**Comment by andydotxyz** [comment]
@AlbinoGeek is right you should not use `os` and other file utils in a cross-platform app - they will not work as expected.

```go
childUR, _ := storage.Child(app.Storage().RootURI(), "test.txt")
write, _ := storage.Writer(childURI)
```

may work, depending on your intended usage.
For more information about doing file handling correctly please see https://www.youtube.com/watch?v=qadrKxvM05g&t=2s

**Comment by madaxemad** [comment]
> @AlbinoGeek is right you should not use `os` and other file utils in a cross-platform app - they will not work as expected.
> 
> ```go
> childUR, _ := storage.Child(app.Storage().RootURI(), "test.txt")
> write, _ := storage.Writer(childURI)
> ```
> 
> may work, depending on your intended usage.
> For more information about doing file handling correctly please see https://www.youtube.com/watch?v=qadrKxvM05g&t=2s

work great Thanks guys

**Comment by andydotxyz** [comment]
You are ignoring errors which is a bad thing to do...

```
write, _ := storage.Writer(childURI)
```

Parameter 2 is `error` and should be checked.

**Comment by madaxemad** [comment]
> You are ignoring errors which is a bad thing to do...
> 
> ```
> write, _ := storage.Writer(childURI)
> ```
> 
> Parameter 2 is `error` and should be checked.
os work on android really easy with no problem
`pathstore := a.Storage().RootURI().Path() + "ms.txt"
	println(pathstore)
	file, _ := os.Create(pathstore)
	file.WriteString("hello")
	file.Close()
	file1, _ := os.OpenFile(pathstore, os.O_RDWR|os.O_CREATE, 0644)
	f1 := bufio.NewScanner(file1)

	print(a.Storage().RootURI().Path())
	strtemp1 := ""
	for f1.Scan() {
		strtemp1 += (f1.Text())
	}
	file1.Close()`

**Comment by andydotxyz** [comment]
You should not assume that `a.Storage().RootURI().Path()` refers to a filesystem path. URIs encode many ways for accessing data, the path parameter will not always refer to your file system.
Additionally the `storage` package handles security and permission issues that the `os` package does not.
