### ISSUE TITLE
Text rendering issue in list

### ISSUE THREAD

**Issue by adrianre12** [fyne-io/fyne#1902]
### Describe the bug:
When scrolling up and down in a list box whose items are canvas.Text I am seeing the wrong items being rendered and the font size varying. Strangely scrolling down seems to make the font big, and scrolling up makes it small.
As the mouse moves over the items they are corrected.
It seems to be worse the shorter each line of text is.
If you keep the cursor off the items, either on the scroll bar or outside the window. It is possible to scroll repeatedly up and down and see the same errors appearing. 
Another strange effect is when slowly resizing vertically the bottom two lines rapidly switch back and forth, presumably at the rate at which the ScrolUp() and ScrollDwon() get called

I had seen this effect occasionally with widget.Label and 200K lines, but since upgrading to 2.0 I have not been able to reproduce it.

### Screenshots:
Scrolling down
![image](https://user-images.githubusercontent.com/20552436/106926183-bd676000-6708-11eb-8f7e-753299bfe50a.png)

Scrolling up
![image](https://user-images.githubusercontent.com/20552436/106926230-cc4e1280-6708-11eb-84f1-37fefedb231e.png)

### Example code:
```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Test")

	data := []string{}
	for i := 0; i < 1000; i++ {
		line := fmt.Sprintf("%d", i)
		data = append(data, line)
	}
	list := widget.NewList(
		func() int { return len(data) },
		func() fyne.CanvasObject {
			return canvas.NewText("placeholder", theme.ForegroundColor())
		},
		func(i int, o fyne.CanvasObject) {
			textCanvas := o.(*canvas.Text)
			textCanvas.Text = data[i]
		},
	)

	myWindow.SetContent(list)
	myWindow.Resize(fyne.NewSize(400.0, 400.0))
	myWindow.Show()
	myApp.Run()
	tidyUp()
}

func tidyUp() {
	fmt.Println("Exited")
}
```

### Device (please complete the following information):
 - **OS:** Windows 10, Linux Mint 20
 - **Go version:** 1.15.6
 - **Fyne version:** 2.0

**Comment by stuartmscott** [comment]
Refresh the canvas.Text after updating its fields;

Either
```go
textCanvas.Text = data[i]
textCanvas.Refresh()
```
Or
```go
textCanvas.SetText(data[i])
```

**Comment by adrianre12** [comment]
Geee, look at that, it works perfectly now, bleeding obvious now you tell me.
Thanks, Stuart

**Comment by stuartmscott** [comment]
Anytime mate 👍
