### ISSUE TITLE
Cannot disable container.TabItem

### ISSUE THREAD

**Issue by pohanlSUM** [fyne-io/fyne#1904]
### Is your feature request related to a problem? Please describe:
We cannot disable container.TabItem using attribute inside container.TabItem

### Is it possible to construct a solution with the existing API?
if tabs.CurrentTabIndex() != 0 && someCondition {
	fmt.Println("Disable!")
	tabs.SelectTab(tabs.Items[0])
}

### Describe the solution you'd like to see:
There is an attribute in container.TabItem named "Disable", default value is false.
When Disable is set to true, user cannot select this tab

**Comment by pohanlSUM** [comment]
widget.treeNode has same problem

**Comment by andydotxyz** [comment]
Good request for TabItem. However TreeNode is not the same, that is just an ID and it’s up to the developer to manage the presentation of the tree nodes.

**Comment by Aakash-Jakhmola** [comment]
@andydotxyz This needs to be closed.

**Comment by andydotxyz** [comment]
On develop ready for v2.3.0
