### ISSUE TITLE
`fyne` doesn't remove temporary binary from `src`

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1910]
### Describe the bug:
After running `fyne get <package>` a binary is left in the `src` directory.

### To Reproduce:
Steps to reproduce the behaviour:
1. `fyne get aletheiaware.com/spacefynego/cmd/spacefyne`
2. Go on $GOPATH/src/aletheiaware/spacefynego
3. Either run `git status` or `ls cmd/spacefyne`
4. See the `spacefyne` binary

### Device (please complete the following information):
 - **OS:** Ubuntu & MacOS
 - **Version:** 20.04 Focal & Big Sur
 - **Go version:** go1.15.7 linux/amd64 & go1.15 darwin/amd64
 - **Fyne version:** 9a0f87ce

**Comment by Jacalz** [comment]
Seems to apply to the whole build command in itself when  trying to package an application. Compiling with `--release` does not use a release compiled binary unless the one there is removed first.

**Comment by stuartmscott** [comment]
Is `--release` different from `fyne release`?

**Comment by Jacalz** [comment]
Yes `fyne package —release` basically strips the debug symbols form the binaries and not much more, I think.

**Comment by stuartmscott** [comment]
Oh thanks. It would be great if `fyne release` stripped debug symbols too. We also probably don't need two commands for creating releases. Though both of these should be separate tickets.

**Comment by Jacalz** [comment]
Yeah. We might want to have it as `--strip-debug` instead, or something along those lines. Like you say though, something for another ticket.

**Comment by andydotxyz** [comment]
`fyne release` also strips symbols. 
The difference between `fyne release` and `fyne package —release` is only the build artefact, in all other ways they are the same. The release mode is expected for distribution through official stores, package is for local instal or sharing on ad-hoc systems.

**Comment by andydotxyz** [comment]
On `release/v2.0.x` for testing
