### ISSUE TITLE
OnTapped callback for widget.Tree

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1913]
### Is your feature request related to a problem? Please describe:
I want to create a simple nav bar with Tree, just like the one in the fyne_demo, however I want that the branches toggle when I tap in any place of a Node (not just by clicking on the arrow). This is because, I don't want to have something like a "home page" for every branch. 

### Is it possible to construct a solution with the existing API?
Hmm, a new field for widget.Tree maybe would be needed.

### Describe the solution you'd like to see:
IMHO, a simple solution would be to add a new callback called OnTapped in widget.Tree, that will be trigger every time user clicks on a Node (OnSelected is triggered only when selection changes), then users who want the above behavior can call:

```go
tree.OnTapped = func(uid widget.TreeNodeID) {
	tree.ToggleBranch(uid)
}
```
Another alternative could be add a boolean field, something like `ToggleOnTap`.
```go
tree.ToggleOnTap = true
```

**Comment by andydotxyz** [comment]
If you want the nodes of your tree to have a `Tapped` handler then you should use a widget that implements `Tappable` IMHO. A tree node is no different to any other widget...

**Comment by fpabl0** [comment]
Maybe the title I used for this issue is confusing. I just wanted to have a way to get the following behavior:

https://user-images.githubusercontent.com/12239342/107151156-1adcf600-692f-11eb-84f5-1c6801d7c6a5.mp4

**Comment by andydotxyz** [comment]
I remember now that @okratitan and @stuartmscott had discussed something similar and there was a general agreement for their proposed approach, what I don't remember was what it was to be.

**Comment by Jacalz** [comment]
> If you want the nodes of your tree to have a `Tapped` handler then you should use a widget that implements `Tappable` IMHO. A tree node is no different to any other widget...

I think this has been the usual answer in recent issues mentioning the same. I'll close this but feel free to reopen if necessary.
