### ISSUE TITLE
Entry widget mouse drag selection offset when scrolled

### ISSUE THREAD

**Issue by bezrazli4n0** [fyne-io/fyne#1916]
### Describe the bug:

Text selection not working properly if entry widget scroll(horizontal or vertical). Selection not appeared under cursor.

### To Reproduce:
Steps to reproduce the behaviour:
1. Input long text in entry widget
2. Scroll and try to select last parts of text

### Screenshots:

https://user-images.githubusercontent.com/56516965/107147337-8b4f3b80-695e-11eb-8a76-7ef7e569e7b5.mp4

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w.SetContent(container.NewVBox(
		widget.NewEntry(),
	))

	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10 Pro
 - **Go version:** 1.15.2 windows/amd64
 - **Fyne version:** 2.0.0

**Comment by andydotxyz** [comment]
Well found. I updated the title for clarity but we should try and resolve this before next bugfix release.

**Comment by andydotxyz** [comment]
On `develop` for testing. Needs merging to release branch as well
