### ISSUE TITLE
default location for ShowFolderOpen (and probably others)

### ISSUE THREAD

**Issue by shawnbutts** [fyne-io/fyne#1921]
I'd like to ShowFolderOpen to start is a specific folder.  Perhaps the a current preference or a well know default location for a file.

I'm guessing this would be handy for other "Open" dialogs.

**Comment by Jacalz** [comment]
This is already possible. You can create the dialog `open := NewFolderOpen(...)` and then call `open.SetLocation(...)` before shoring it, and passing a `fyne.ListableURI` to it. The same works for all the folder and file dialogs. https://pkg.go.dev/fyne.io/fyne/v2/dialog#FileDialog.SetLocation
