### ISSUE TITLE
How can i make a video player using fyne?

### ISSUE THREAD

**Issue by mateors** [fyne-io/fyne#1942]
### Describe the solution you'd like to see:

Media player using fyne

**Comment by Jacalz** [comment]
I think https://github.com/fyne-io/fyne/issues/449 contains most of the information regarding this. In general, I think it boils down to that we don't currently have any multimedia support integrated to work in Fyne. It is a very complicated task to fix given that very few multimedia or video players offer suitable licenses for our use case or requires to be installed externally to the computer and thus not fitting with the goals of the project. We are looking for a good way to solve this and plan to have it solved for a 3.0 update of fyne.

**Comment by andydotxyz** [comment]
Indeed, closing as duplicate as indicated

**Comment by xaionaro** [comment]
Just in case, until fyne has a better solution, I've made a hello-world-y video player with libav for video decoding and fyne for video display in here: https://github.com/xaionaro-go/player/blob/main/cmd/player/main.go (use `backend` value `builtin` in the CLI flags)
