### ISSUE TITLE
Installing not working

### ISSUE THREAD

**Issue by Mr-SinaYeganeh** [fyne-io/fyne#1945]
**Hello! whene I want to install this package I see this error:**
```
package fyne.io/fyne/v2: unrecognized import path "fyne.io/fyne/v2": https fetch: Get "https:
//fyne.io/fyne/v2?go-get=1": net/http: TLS handshake timeout
```
**I write this command to install:**
```
go get fyne.io/fyne/v2
```
*Please help me!*

**Comment by andydotxyz** [comment]
It looks like a (temporary) issue with the network somewhere between you and GitHub.
Try again later perhaps? As far as I can see the systems are all working as expected.

**Comment by Mr-SinaYeganeh** [comment]
It fixed! thank :)
