### ISSUE TITLE
Cells are not getting draw in correct location after column resize.

### ISSUE THREAD

**Issue by zdima** [fyne-io/fyne#1951]
### Describe the bug:

After calling SetColumnWidth the cells are not getting draw in correct location.
The table.Refresh() doesn't help.
The column's border is properly displayed and selection highlight correct.
This is tested with development branch due to Apple M1 (github.com/sirkon/fyne/v2 v2.0.1-0.20210209074931-f93d4e04b627).

### To Reproduce:
Steps to reproduce the behaviour:
Run provided test program.
After 5 second delay the columns border is changed.
The Cells widgets are not moved to correct location.
Try select individual cells, the selection marks are displayed properly.

### Screenshots:

![Screen Shot 2021-02-12 at 1 14 59 PM](https://user-images.githubusercontent.com/298260/107810946-72b69b00-6d3b-11eb-8389-d777904ac095.png)

![Screen Shot 2021-02-12 at 1 15 05 PM](https://user-images.githubusercontent.com/298260/107810999-8235e400-6d3b-11eb-95fd-55b3e569d156.png)

### Example code:

```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Examples")
	w.SetContent(newTable())
	w.Resize(fyne.Size{Width: 800, Height: 300})
	w.ShowAndRun()
}

func newTable() fyne.CanvasObject {
	var data map[int][]string = make(map[int][]string, 1)
	var colWidth []float32 = make([]float32, 3)
	data[0] = []string{"Header 1", "Header 2", "Header 3"}
	var table *widget.Table
	table = widget.NewTable(func() (int, int) {
		return len(data), 3
	}, func() fyne.CanvasObject {
		l := widget.NewLabel("")
		l.Resize(fyne.Size{Width: 200, Height: 20})
		return l
	}, func(tci widget.TableCellID, co fyne.CanvasObject) {
		if label, ok := co.(*widget.Label); ok {
			col := tci.Col
			label.Text = data[tci.Row][col]
			label.Refresh()
			width := label.MinSize().Width
			if colWidth[col] < width {
				colWidth[col] = width
				// Options A
				// go func() {
				// 	table.SetColumnWidth(col, colWidth[col])
				// 	table.Refresh()
				// }()
			}
		}
	})

	table.SetColumnWidth(0, 200)
	table.SetColumnWidth(1, 200)
	table.SetColumnWidth(2, 200)

	table.OnSelected = func(id widget.TableCellID) {
		fmt.Printf("Select col %d row %d\n", id.Col, id.Row)
	}

	// Options B
	go func() {
		time.Sleep(time.Second * 5)
		table.SetColumnWidth(0, 100)
		table.SetColumnWidth(1, 100)
		table.SetColumnWidth(2, 100)
		table.Refresh()
	}()

	return table
}
```

go.mod for Apple M1:
```
module table-test

go 1.16

replace fyne.io/fyne/v2 => github.com/sirkon/fyne/v2 v2.0.1-0.20210209074931-f93d4e04b627

require fyne.io/fyne/v2 v2.0.0-00010101000000-000000000000
```

### Device (please complete the following information):
 - **MacOS:** 
 - **11.2:** 
 - **go1.16rc1:** 
 - **2.0 (dev):**

**Comment by andydotxyz** [comment]
On `develop` for testing
