### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by Mr-SinaYeganeh** [fyne-io/fyne#1953]
Hi! Whene i install fyne go say:
```
code in directory C:\Users\User\go\src\github.com\fyne-io\fyne expects import "fyne.io/fyne/v2"
```
So I imported that like this: **`fyne.io/fyne/v2`**
but I get error . . . Together I imported like this: **`fyne.io/fyne/app`** / **`fyne-io/fyne/app`** and . . .

<hr>

Please help me in this problem :)

**Comment by andydotxyz** [comment]
Please complete the bug template, or at minimum provide the requested versions for go and fyne etc.

The import paths now all start “fyne.io/fyne/v2” - if you are upgrading read this document as well https://developer.fyne.io/api/v2.0/upgrading

**Comment by Mr-SinaYeganeh** [comment]
Thank Again 😊

**Comment by billgates2020** [comment]
please help somebody!

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Hello")
	w.SetContent(
		widget.NewVBox(
			widget.NewLabel("Hello Fyne!"),
			widget.NewLabel("This is sample application!"),
		),
	)

	w.ShowAndRun()
}
```

```
# command-line-arguments
.\hello.go:13:3: undefined: "fyne.io/fyne/v2/widget".NewVBox
```

**Comment by Jacalz** [comment]
> please help somebody!
> 
> ```
> package main
> 
> import (
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/widget"
> )
> 
> func main() {
> 	a := app.New()
> 
> 	w := a.NewWindow("Hello")
> 	w.SetContent(
> 		widget.NewVBox(
> 			widget.NewLabel("Hello Fyne!"),
> 			widget.NewLabel("This is sample application!"),
> 		),
> 	)
> 
> 	w.ShowAndRun()
> }
> ```
> 
>  ```
> # command-line-arguments
> .\hello.go:13:3: undefined: "fyne.io/fyne/v2/widget".NewVBox
> ```

I suggest that you have a look at the API documentation. The widget.VBox was deprecated a long while ago and removed in 2.0.0. The upgrade tips are to be found here: https://developer.fyne.io/api/v2.0/upgrading.html.

Btw, please don’t comment on old issues that have been solved and/or are unrelated to the new comment. This issue tracker is mostly for reporting bugs and feature requests. For support and help, I would suggest look to https://fyne.io/support/.
