### ISSUE TITLE
HBox display problem with multiple entries but single visible entry.

### ISSUE THREAD

**Issue by mrjrieke** [fyne-io/fyne#1955]
### Describe the bug:
Edit widget displays poorly in HBox if all but one canvas object are hidden.  It is desirable that a visible element encompass the entire available area of the HBox, but presently it only occupies a small slice.  There doesn't seem to be a way to get it to occupy the entire area.  Since there is technically only one widget, it seems it should be able to occupy the entire available area of the widget.

### To Reproduce:
Run the example code and observe display.

### Screenshots:
![image](https://user-images.githubusercontent.com/20530495/107851914-22cee700-6dc2-11eb-9de7-591b999679a7.png)

### Example code:
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	objects := []fyne.CanvasObject{}

	text := canvas.NewText(string("Give all the power to the many, they will oppress the few. Give all the power to the few, they will oppress the many."), theme.TextColor())
	text.Hide()
	objects = append(objects, text)

	entry := widget.NewEntry()
	entry.Text = "Men give me credit for some genius. All the genius I have lies in this; when I have a subject in hand, I study it profoundly. Day and night it is before me. My mind becomes pervaded with it. Then the effort that I have made is what people are pleased to call the fruit of genius. It is the fruit of labor and thought."
	entry.SetPlaceHolder("Men give me credit for some genius. All the genius I have lies in this; when I have a subject in hand, I study it profoundly. Day and night it is before me. My mind becomes pervaded with it. Then the effort that I have made is what people are pleased to call the fruit of genius. It is the fruit of labor and thought.")
	objects = append(objects, entry)

	w.SetContent(container.NewHBox(objects...))

	w.ShowAndRun()
}

### Device (please complete the following information):
OS: Linux
Version: Debian Buster
Go version: 1.15.8
Fyne version: 2.0

**Comment by andydotxyz** [comment]
`HBox` will compress all objects to minimum width, this is how it is designed.
The entry has scrolling so it's minimum size is small.
To expand your content across the space please use a layout that expands - if you want to switch between items, one visible at a time, try `container.Max()`.

**Comment by mrjrieke** [comment]
Sounds good.  :+1:
