### ISSUE TITLE
Any functional To Do list android / ios app example?

### ISSUE THREAD

**Issue by hiqsociety** [fyne-io/fyne#1959]
Any functional To Do list android / ios app example?

**Comment by andydotxyz** [comment]
One of the chapters in https://www.packtpub.com/product/building-cross-platform-gui-applications-with-fyne/9781800563162 is a task list app.
All the examples in the book work on Android/mobile and desktop alike.

**Comment by andydotxyz** [comment]
In addition to that comment all Fune apps are capable of running as ios or android apps.

If you find an app you like then just `fyne package -os ios` (some other parameters may be required) then copy the `.app` to your iPhone. Android similar.
