### ISSUE TITLE
Form validation doesn't enable submit button

### ISSUE THREAD

**Issue by alexrudd** [fyne-io/fyne#1965]
### Describe the bug:
When creating a form with entries that include validation methods, typing valid input into those entries does not enable the form's submit button. However, typing input, deleting that input, and then typing it again does enable the form's submit button

### To Reproduce:
Steps to reproduce the behaviour:
1. Create form with entries that include validation and an `OnSubmit` function
2. Render the form
3. Type valid input into the form's entries
4. Observe that the submit button stays disabled
5. Delete and then re-enter the valid input
6. Observe that the submit button is now enabled

### Screenshots:
![formbug](https://user-images.githubusercontent.com/3588652/108135998-0e843600-70b1-11eb-91a5-cc0bdd3c4940.gif)

### Example code:

Code from the above gif:

```go
username := widget.NewEntry()
username.SetPlaceHolder("username")
username.Validator = func(s string) error {
    if s == "" {
        return errors.New("please specifiy a username")
    }

    return nil

}

password := widget.NewPasswordEntry()
password.SetPlaceHolder("password")
password.Validator = func(s string) error {
    if s == "" {
        return errors.New("please specifiy a password")
    }

    return nil
}

rememberCheck := widget.NewCheck("Remember my password", nil)

form := widget.NewForm(
    widget.NewFormItem("Username", username),
    widget.NewFormItem("Password", password),
    widget.NewFormItem("", rememberCheck),
)

form.SubmitText = "Login"
form.OnSubmit = func() {
    username.Disable()
    password.Disable()
    rememberCheck.Disable()
    defer username.Enable()
    defer password.Enable()
    defer rememberCheck.Enable()

    success := pres.Login(username.Text, password.Text, rememberCheck.Checked)
    if success {
        onSucess()
    }
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10.0.19042
 - **Go version:** go1.15.8
 - **Fyne version:** v2.0.0

**Comment by Jacalz** [comment]
Fixed on the develop branch as of 7d2b239e946b97096c660c2799194e04f3d54873.
