### ISSUE TITLE
can support  embedded linux ？

### ISSUE THREAD

**Issue by hvritual** [fyne-io/fyne#197]
If you can support embedded Linux,architecture as  arm,  I may not use qt + golang for my app。I see the source code, only few points using gl，limit not build arm, add gl to support arm is difficult？

**Comment by andydotxyz** [comment]
We would need to change (or add) the driver to use OpenGL ES - this is part of the plan as supporting mobile or smaller target devices requires it...

We have not scheduled this work yet

**Comment by hvritual** [comment]
ok ，thanks。

**Comment by jadr2ddude** [comment]
We do support ARM I thought, and this will work depending on how you define embedded.

**Comment by jadr2ddude** [comment]
Oh wait nvm i just saw the build tag

**Comment by andydotxyz** [comment]
Ah yes, I cannot remember why those build tags were set now.
I will try and find an arm device with OpenGL in my collection and test.

**Comment by hvritual** [comment]
Maybe you can use qemu for arm device test

**Comment by hvritual** [comment]
> Oh wait nvm i just saw the build tag. If we remove the build tag, it should work on most ARM devices with GPUs, as support for full OpenGL is fairly common.

just remove build !arm? , let me try!  thanks

**Comment by andydotxyz** [comment]
I tried on my raspberryPi but unfortunately raspbian still ships Go 1.7 and we require 1.10...
Has anyone had success upgrading to the testing OS or otherwise got a newer Go on the rPi?

**Comment by ohir** [comment]
@andydotxyz `GOOS=linux GOARCH=arm GOARM=7`
https://gist.github.com/dlsniper/3b88e4f28f1ce5f3349483a96032d6c9
_It is strongly discuraged to use Go packaged by some distro maintainer._

Cross compiling underlying C layers is a separate story though.

**Comment by andydotxyz** [comment]
Thanks @ohir, I will see what I can manage. If I get the target setup to compile then we can not worry about cross compiling for this specifically.

**Comment by andydotxyz** [comment]
This is now working on the develop branch. Feel free to test and/or use.
It will be included in 1.2 but the release is not yet scheduled.
