### ISSUE TITLE
Keys aren't recognized

### ISSUE THREAD

**Issue by BenoitPingris** [fyne-io/fyne#1971]
### Describe the bug:
Some "special" keys (like space, backspace, delete) aren't interpreted by Fyne/GLFW:
```
Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode                                                                         
│   6     return l2021/02/17 21:11:51   At: /home/benoitp/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/glfw/loop.go:221
```
This seems to be related to this  [issue](https://discourse.glfw.org/t/invalid-scancode-error-on-key-entry/1713/2) but I can't find more information.
Do you have more information about this issue?
Thanks

### Device (please complete the following information):
 - **OS:** Manjaro Linux
 - **Version:** 20.2.1
 - **Go version:** go1.15.8 linux/amd64
 - **Fyne version:** v2.0.0

**Comment by andydotxyz** [comment]
Can you please provide more information about your keyboard hardware and configuration? Obviously this normally works, so it probably relates to some combination we have not understood yet.

**Comment by BenoitPingris** [comment]
Ok so, I was looking for my keyboard configuration to send it to you, and saw that I was in QWERTY (normal), **but** I had an AZERTY layout as a secondary one.
I removed it from my layouts (so now I only have the QWERTY one available on m system), and now it works. A bit weird I guess I'll open an issue to GLFW.

Thanks
