### ISSUE TITLE
Weighted layout

### ISSUE THREAD

**Issue by sirkon** [fyne-io/fyne#1972]
Haven't managed to find similar issues here, so asking for a feature

### Is your feature request related to a problem? Please describe:
Needed to build a new widget recently, designed to choose between available users who are not numerous. Wanted to make something like

```
|<dropdown>|+|
```

i.e. dropdown list on the left and a button to add new users who are entered with a credentials user:password dialog initiated by the button.

* Used `container.NewHBox` at first, but it was off as I wanted the widget to be stretched to the full width. Unfortunately,`widget.HBox` enforces `MinSize` policy for its children widgets and the widget just won't take full width of the martent container.
* Then tried grid, which didn't satisfied me either as I want MinSize policy for the button. Was seeing dropdown and button having the same width.

In the end just did my own layout making what I needed.

### Is it possible to construct a solution with the existing API?

Nothing in predefined set of containers or layouts I have tried didn't help me to achieve an objective: 

* Widget should take the full width of its parent container
* Button on the right should have its minimal size
* Dropdown list should take the rest of width left after button.

### Describe the solution you'd like to see:

Would like to see something like this:

```go
cnt := container.NewHWeighted().With(100, selector).With(50, entry).Shy(button).Build()
// Shy(w) is a shortcut for With(0, w)
```

This means:

* `button` should have the minimal size
* The rest of space is splitted between `selector` and `entry`, where the `selector` takes 2/3 of the rest of width and `entry` takes 1/3.

Should be careful though, once the computed width is less than one in a MinSize the MinSize should be used, this means a recalculation of widths for the rest.

**Comment by andydotxyz** [comment]
> In the end just did my own layout making what I needed.

I think you should ahve used `container.NewBorder(nil, nil, nil, button, select)`

**Comment by andydotxyz** [comment]
I think this was a simple oversight or lack in documentation, closing
