### ISSUE TITLE
utf8 support

### ISSUE THREAD

**Issue by amirex128** [fyne-io/fyne#1976]
please support utf8

**Comment by AlbinoGeek** [comment]
Sorry, as I'm sure you saw, this is a duplicate of an existing feature request.
UTF-8 (Unicode) support is already tracked for the future.

You can find out more by subscribing to the issues: 
- #573 Emoji Support requires Unicode
- #598 Displaying other languages requires Unicode
- #659 Unicode decoding on fonts not working
- #1579 Unicode characters not showing
