### ISSUE TITLE
Fyne command v2 404

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1980]
404s are being returned when using `fyne get` to install S P A C E possibly due to the v2.0.0:

```
$> fyne get aletheiaware.com/spacefynego/cmd/spacefyne
package fyne.io/fyne/v2/storage/repository: unrecognized import path "fyne.io/fyne/v2/storage/repository": reading https://fyne.io/fyne/v2/storage/repository?go-get=1: 404 Not Found
package fyne.io/fyne/v2/storage: unrecognized import path "fyne.io/fyne/v2/storage": reading https://fyne.io/fyne/v2/storage?go-get=1: 404 Not Found
package fyne.io/fyne/v2/container: unrecognized import path "fyne.io/fyne/v2/container": reading https://fyne.io/fyne/v2/container?go-get=1: 404 Not Found
```

@winksaville can you share info about your OS & Version, and the results of running `go version` and `fyne version`?

**Comment by winksaville** [comment]
$ inxi -Fxz
System:    Kernel: 5.10.16-arch1-1 x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6 Distro: Arch Linux 
Machine:   Type: Desktop Mobo: ASRock model: X570 Creator serial: <filter> UEFI: American Megatrends v: P2.10 date: 12/16/2019 
CPU:       Topology: 12-Core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP arch: Zen 2 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 182492 
           Speed: 2799 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 3894 2: 2042 3: 2199 4: 2196 5: 3364 6: 1875 7: 1987 
           8: 2194 9: 2198 10: 2200 11: 2200 12: 2199 13: 1991 14: 2198 15: 2198 16: 2196 17: 2191 18: 2199 19: 2197 20: 2199 
           21: 2200 22: 2199 23: 2199 24: 2198 
Graphics:  Device-1: NVIDIA TU116 [GeForce GTX 1660] vendor: Micro-Star MSI driver: nvidia v: 460.39 bus ID: 7c:00.0 
           Display: x11 server: X.org 1.20.10 driver: nvidia unloaded: modesetting resolution: <xdpyinfo missing> 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:     Device-1: NVIDIA TU116 High Definition Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel bus ID: 7c:00.1 
           Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio vendor: ASRock driver: snd_hda_intel v: kernel 
           bus ID: 7e:00.4 
           Sound Server: ALSA v: k5.10.16-arch1-1 
Network:   Device-1: Intel I211 Gigabit Network vendor: ASRock driver: igb v: kernel port: b000 bus ID: 71:00.0 
           IF: enp113s0 state: down mac: <filter> 
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: b000 bus ID: 72:00.0 
           IF: wlp114s0 state: down mac: <filter> 
           Device-3: Aquantia AQC107 NBase-T/IEEE 802.3bz Ethernet [AQtion] vendor: ASRock driver: atlantic v: kernel 
           port: a000 bus ID: 77:00.0 
           IF: enp119s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: docker0 state: down mac: <filter> 
Drives:    Local Storage: total: 465.76 GiB used: 173.90 GiB (37.3%) 
           ID-1: /dev/nvme0n1 vendor: Sabrent model: Rocket 4.0 500GB size: 465.76 GiB 
           ID-2: /dev/nvme1n1 vendor: Sabrent model: Rocket 4.0 500GB size: 465.76 GiB 
Partition: ID-1: / size: 491.15 GiB used: 173.83 GiB (35.4%) fs: ext4 dev: /dev/dm-2 
           ID-2: /boot size: 1.86 GiB used: 71.9 MiB (3.8%) fs: vfat dev: /dev/nvme0n1p1 
Swap:      ID-1: swap-1 type: file size: 512.0 MiB used: 0 KiB (0.0%) file: /swapfile 
Sensors:   System Temperatures: cpu: 48.1 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 487 Uptime: 55m Memory: 31.28 GiB used: 5.12 GiB (16.4%) Init: systemd Compilers: gcc: 10.2.0 
           clang: 11.1.0 Shell: bash v: 5.1.4 inxi: 3.1.03

**Comment by stuartmscott** [comment]
> $ fyne version
> Could not retrieve version information. Please ensure module support is activated and build again

Could you set the environment variable "GO111MODULE" to "on", and try again?

**Comment by winksaville** [comment]
```
wink@3900x:~
$ GO111MODULE=on fyne version
Could not retrieve version information. Please ensure module support is activated and build again
wink@3900x:~
$ GO111MODULE=on
wink@3900x:~
$ echo $GO111MODULE 
on
wink@3900x:~
$ fyne version
Could not retrieve version information. Please ensure module support is activated and build again
```

**Comment by andydotxyz** [comment]
Out of date website config fixed

**Comment by stuartmscott** [comment]
@winksaville you may need to reinstall Fyne after setting that flag
```
go get -u fyne.io/fyne/cmd/fyne
```

**Comment by winksaville** [comment]
> @winksaville you may need to reinstall Fyne after setting that flag
> 
> ```
> go get -u fyne.io/fyne/cmd/fyne
> ```

```
wink@3900x:~
$ go get -u fyne.io/fyne/cmd/fyne
package fyne.io/fyne/cmd/fyne
	go/src/fyne.io/fyne/cmd/fyne/vendor.go:17:2: use of internal package fyne.io/fyne/v2/cmd/fyne/internal/util not allowed
```

**Comment by stuartmscott** [comment]
Oh my bad
```
go get -u fyne.io/fyne/v2/cmd/fyne
```

**Comment by winksaville** [comment]
Better but still not quite enough, do I need to do something else?
```
$ go get -u fyne.io/fyne/v2/cmd/fyne
wink@3900x:~
$ fyne version
could not retrieve version information (ensure module support is activated and build again)
```

**Comment by stuartmscott** [comment]
So I think what happened it that it built with the old fyne, so you may want to remove the `src` and `bin` artifacts for both fyne and spacefyne under your go path, and then run again.

```
$> go get -u fyne.io/fyne/v2/cmd/fyne
$> fyne get aletheiaware.com/spacefynego/cmd/spacefyne
```

**Comment by winksaville** [comment]
Note: on Arch Linux I needed to execute `fyne get aletheiaware.com ...` with `sudo` as it installed `spacefyne` in `/usr/local/bin` which needs `root` permissions.
