### ISSUE TITLE
Cinnamon cannot recognize apps installed by Fyne

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1981]
Apps installed by `fyne get` are compiled and the resulting binary is put in the right place for command line execution, however it is not recognized by the desktop environment.

@winksaville can you share info about your OS & Version, and the results of running go version and fyne version? I haven't used Cinnamon so I'm not sure what the expected behaviour is, could you provide some info about how apps normally appear in Cinnamon, is there an app listing? Does the app also not appear in a search?

**Comment by andydotxyz** [comment]
Sounds like the `/usr/local/bin/` executable is in but that the `.desktop` file (in `/usr/local/share/applications/` may not be looked up by the cinnamon config?

**Comment by stuartmscott** [comment]
I think this might have been due to a missing 'v2' when running 'go get' to install fyne. @winksaville did it work better the second time?

**Comment by winksaville** [comment]
Yes, but I needed to use `sudo` on my system. Also, there should be "progress" feed back as the install took maybe a full minute to install and looked like it was "hung".
```
wink@3900x:~/go/pkg/linux_amd64
$ sudo fyne get aletheiaware.com/spacefynego/cmd/spacefyne
[sudo] password for wink: 
wink@3900x:~/go/pkg/linux_amd64
$ which spacefyne
/usr/local/bin/spacefyne
wink@3900x:~/go/pkg/linux_amd64
$ spacefyne
2021/02/19 12:30:49 crypto.go:245: Generating RSA-4096bit Public/Private Key Pair
...
```

**Comment by andydotxyz** [comment]
This was discussed on our developer channel yesterday.
The Go tools, as with many developer tools, don't output information in success criteria.
The longest part of this is the build process, so if the go compiler adds progress in the future we would mirror that.
`fyne get` is basically a developer tool - the `apps` GUI has progress bar etc as it is more user focused.

**Comment by andydotxyz** [comment]
I'm not sure if there is still an issue to track here, should it be closed?

**Comment by winksaville** [comment]
Please leave open for now. I'll provide my system info and versions this weekend. I'll also check how cinnamon handles `.desktop` files.

I'd like to suggest having feed back is important even if it's just a "spinner", just something to indicate it's not hung. It can even default to "quiet" mode and the developer can instruct the user to use "verbose" mode when they know the install will likely take a long time.

**Comment by andydotxyz** [comment]
Any more info that we can work with @winksaville ?

**Comment by winksaville** [comment]
@stuartmscott I think I should uninstall the current version of the app and tools and reinstall everything using the correct instructions and latest versions. Please advise.

**Comment by stuartmscott** [comment]
Unfortunately `fyne uninstall` doesn't exist yet (https://github.com/fyne-io/fyne/issues/1906)

For now tho it should be sufficient to `rm $(whereis spacefyne)`. There may also be a binary in the source directory for some reason, can just blow it all away `rm -r $GOPATH/src/aletheiaware.com/` and the next commands will re-download anything that is needed.

There's a new version of Fyne so you can update it with `go get -u fyne.io/fyne/v2/cmd/fyne` then `fyne get aletheiaware.com/spacefynego/cmd/spacefyne`

**Comment by winksaville** [comment]
I uninstalled and re-installed and `spacefyne` and it is now properly seen as a desktop app. I'm not sure what changed as the `spacefyne.desktop` file is the only `.desktop` file installed in `/usr/local/share/applications/` on my system which previously led me to feel `fyne.io` was installing it at an unusual place. But from what I've read [here](https://wiki.archlinux.org/index.php/XDG_Base_Directory#System_directories) and [here](https://wiki.archlinux.org/index.php/desktop_entries#Application_entry) `/usr/local/share/applications/` is valid and if there is a problem it's on the system side.

So I think this can be closed.

**Comment by andydotxyz** [comment]
Great to hear this is working now, thanks @winksaville
