### ISSUE TITLE
MultilineEntry with text wrapping panics when removing letters (cursor wrong position)

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#1989]
### Describe the bug:

MultilineEntry with text wrapping panics when removing letters, because it suddenly move the cursor to a invalid position.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code.
2. Scroll down the Entry until the bottom.
3. Try to remove the last line.
4. Cursor will be moved to an invalid position.
5. Press `Backspace` key again.
6. Panics.

### Screenshots:

https://user-images.githubusercontent.com/12239342/108588068-42679180-7325-11eb-9ec5-76ab161d0958.mp4

### Example code:

```go
func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	w.Resize(fyne.NewSize(200, 200))

	e := widget.NewMultiLineEntry()
	e.Wrapping = fyne.TextWrapWord
	e.SetText("Hello\ntesting\ntesting\ntesting\ntesting...")
	w.SetContent(container.NewVBox(e))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** MacOS 
 - **Version:** 10.15.4 Catalina 
 - **Go version:** 1.16 
 - **Fyne version:** develop @ 8a67b5f84

**Comment by andydotxyz** [comment]
Fixed on `develop`
