### ISSUE TITLE
Does Fyne support visual drag controls?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#1993]
Is fyne similar to a tool like qtdesigner, dragging control layout?

**Comment by Jacalz** [comment]
I think you might want to check out https://github.com/andydotxyz/fynebuilder. It’s an in development gui designer.

**Comment by andydotxyz** [comment]
If you are looking for a GUI designer then the link from @Jacalz is closest to what we have.
If your question is about the different controls and layouts in Fyne then consider running fyne_demo (https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo) and seeing what widgets are included.

**Comment by smp12345** [comment]
This Builder is a little simple, and many functions have not been realized. If I click "Save", the corresponding functions have not been realized. Can't I transfer the GO code?
