### ISSUE TITLE
Entrys painful bugs

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#2004]
### Describe the bug:
there are 2 bugs for entrys 
### **1 :**
if you click right on pixel where line you want type and type fast after first cursor blinking ,cursor blink jump 2 or more letters  back depends on your typing speed
if entry don't be empty this bug annoy more
### **2 :**
if you click with small distance pixel from line you want type cursor blink  jumps on first and after first cursor blinking it jumps first again 

### 1 :
![1](https://user-images.githubusercontent.com/77942735/108719120-71078700-7534-11eb-8313-2a9614538a0f.gif)

### 2 :
![2](https://user-images.githubusercontent.com/77942735/108719219-8977a180-7534-11eb-9b52-036602ce720e.gif)

### Example code:
```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {


	a := app.New()
	w := a.NewWindow("Messenger")

	entry := widget.NewMultiLineEntry()

	w.SetContent(entry)
	w.ShowAndRun()
}

```

 - **OS:** windows 10
 - **Go version:** 1.16
 - **Fyne version:** 2

**Comment by andydotxyz** [comment]
These are already being fixed on `develop` branch.
Duplicates of #1778 and #1937
