### ISSUE TITLE
Compilation error for windows on latest develop branch

### ISSUE THREAD

**Issue by alexrudd** [fyne-io/fyne#2005]
### Describe the bug:
There's a compilation error in the latest develop branch: `app\app_windows.go:82:62: undefined: appName`

Looks like it was introduced [here](https://github.com/fyne-io/fyne/commit/1ac1d1d0b71799f9f2a5f075802f70efe06c7d09#diff-470828120a89a3d406dfee128f81cf0e53ff7993f451eebedd27a03a24bfd39fR82). Variable should probably be `appID`

**Comment by andydotxyz** [comment]
Oh how embarassing, thanks for pointing that out.
It is fixed now.
