### ISSUE TITLE
Extending Entry Widget disable the v2 scroll ability

### ISSUE THREAD

**Issue by Godrigos** [fyne-io/fyne#2007]
### Describe the bug:
I am extending the entry widget so it only accepts floats and discard at typing any character that do not mach such pattern.
By doing so the entry widget behaves as the previous version (1.x) and do not auto scroll and get larger and larger as you type. I only changed the TypedRune method as can be seen in the code bellow.
Probably it is not a bug but some bad coding of mine, if you may help I will be gratefull.

### To Reproduce:
1. Extend the Entry widget
2. Add regex filter to TypedRune method
3. See the v2 auto scroll feature “disables”

### Example code:
```go
package main

import (
	"regexp"
	"strings"

	"fyne.io/fyne/v2/widget"
)

type floatEntry struct {
	widget.Entry
}

func newFloatEntry() *floatEntry {
	entry := &floatEntry{}
	entry.ExtendBaseWidget(entry)
	return entry
}

// TypedRune receives text input events when the Entry widget is focused.
// It filters input so only numbers and a single '.' are allowed with a
// maximum of 4 decimal places.
// Implements: fyne.Focusable
func (e *floatEntry) TypedRune(r rune) {
	reg := regexp.MustCompile(`[0-9]|[.]`)
	if !reg.MatchString(string(r)) {
		return
	}

	reg2 := regexp.MustCompile(`[.]`)
	if reg2.MatchString(e.Text) && r == '.' {
		return
	}

	if len(strings.SplitAfter(e.Text, ".")) > 1 {
		if len([]rune(strings.SplitAfter(e.Text, ".")[1])) > 3 {
			return
		}
	}

	e.Entry.TypedRune(r)
}
```

### Device:
 - Ubuntu 20.04.2
 - Go 1.15.8
 - Fyne 2.0.0

**Comment by fpabl0** [comment]
Hello @Godrigos, try this:
```go
func newFloatEntry() *floatEntry {
	entry := &floatEntry{}
	entry.Wrapping = fyne.TextTruncate // 👈 add this line
	entry.ExtendBaseWidget(entry)
	return entry
}
```
By default Wrapping mode is Off and it won't provide you any scrolling capabilities, by adding `TextTruncate` you enable it.

**Comment by andydotxyz** [comment]
Good tip @fpabl0 but wrong way round. The OP wants to disable scrolling, which is on by default for 2.0.x - you can remove it as follows:

```go
entry.Wrapping = fyne.WrapOff
```

**Comment by Godrigos** [comment]
Actually I was looking for @fpabl0's idea. The wrapping is being desabled when I extend the widget and I wanted it to be enabled. `fyne.WrapOff` seems to also disables it, at least at my testing.
Thank you all  for the fast answer.
`entry.Wrapping = fyne.TextTruncate` did the trick.

**Comment by andydotxyz** [comment]
Oh, sorry for misreading - and thanks @fpabl0 for the correct answer.
Glad you got it fixed.
