### ISSUE TITLE
I want to scroll the log to the screen. Is there any good way

### ISSUE THREAD

**Issue by xbc563771383** [fyne-io/fyne#2010]

**Comment by andydotxyz** [comment]
We don't have an "auto scroll" widget - but you can use a VBox of Label widgets, inside a container.Scroll and when you add new elements you can call Scroll.ScrollToBottom().

**Comment by xbc563771383** [comment]
thanks, I'll try

**Comment by Ran-Xing** [comment]
@xbc563771383 Did you address this need? I have encountered a similar problem recently, and I need to print the log to the desktop, similar to the cli server of vue

**Comment by Ran-Xing** [comment]
![image](https://user-images.githubusercontent.com/73819467/175825667-8ec13007-3eae-4065-b6c0-6a902df8f41d.png)
