### ISSUE TITLE
make ( scroll ) scrolling smooth ( make it easeinout easein easeout )

### ISSUE THREAD

**Issue by madaxemad** [fyne-io/fyne#2020]
hey 
how make scrolling smooth 
make scroll moving ease in , ease out , ease in out  ?

**Comment by andydotxyz** [comment]
Please expand on this issue. It is not clear how this would apply - scrolling happens in response to mouse scroll or drag events.
As before please provide more information about the platform and details of what you are trying to do.

If you want to ask short questions of the community please join `gophers` Slack server #fyne room, that is an appropriate place for one-line questions.
