### ISSUE TITLE
Is there any mobile widget support view html page?

### ISSUE THREAD

**Issue by kcmvp** [fyne-io/fyne#2021]
### Is your feature request related to a problem? Please describe:
Right now I am going to build mobile app. some of functions are web based. I knew there are webview in native Android/ios.
Not sure fyne has the similar widget or not?

**Comment by Jacalz** [comment]
Sorry, there is no support for that. See #116 for the reasons why we most likely can’t add one of those widgets as it stands currently. I am going to close this as a duplicate.
