### ISSUE TITLE
Label UI design

### ISSUE THREAD

**Issue by xines** [fyne-io/fyne#2029]
### Describe the solution you'd like to see:

Would be pretty cool for fyne to have these types of labels ui :)
- Also ty for all the hard work.

![GitHub Logo](https://i.imgur.com/9tBrhlH.png)

**Comment by andydotxyz** [comment]
I think this may be a duplicate of #1861

**Comment by AlbinoGeek** [comment]
@xines Are you asking for:

A) These colour/states (as seen in #1861)
B) These rounded boxes: [Material Design Chips](https://material.io/go/design-chips)

**Comment by xines** [comment]
@andydotxyz Well yes and no.
More as a simpel way to have text labels boxed in coloured labels with RGBA support or preset colours if thats a issue.
Opens posibility to be further developed into @AlbinoGeek 's option B) chips later in time or buttons expansion? :)

**Comment by andydotxyz** [comment]
To box in content use the `canvas.Rectangle` behind your `canvas.Text` or `widget.Layout`.
The `canvas` APIs allow you to specify colours, but the widgets expose semantic APIs, as requested in #1861.
Going to close as duplicate
