### ISSUE TITLE
How to adjust Gridlayou element spacing?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2033]
Is it possible to customize the spacing of elements?I feel the gap between 1,2,3 is too wide
```
	myApp := app.New()
	myWindow := myApp.NewWindow("Grid Layout")

	text1 := canvas.NewText("1", color.Black)
	text2 := canvas.NewText("2", color.Black)
	text3 := canvas.NewText("3", color.Black)
	grid := container.New(layout.NewGridLayout(3), text1, text2, text3)
	myWindow.SetContent(grid)
	myWindow.ShowAndRun()
```

![1](https://user-images.githubusercontent.com/50661521/109303516-e1d0db00-7875-11eb-9d92-bf8fe79540e0.png)

**Comment by andydotxyz** [comment]
The grid layout stretches the content into equal columns.
Try using `canvas.Rectangle` instead of text and you will see it's even.

**Comment by smp12345** [comment]
Rectangle can write words and pictures on it. Can I put a click on it?

**Comment by andydotxyz** [comment]
No, I was not recommending you use a rectangle in your app. I was using it to show that the grid layout is even and that the difference in spacing between text is not related to the grid.

a grid evenly splits the space available. If you want to use less space you need to put it inside another container that uses less space. Or replace Grid with HBox which does not allocate available space but shrinks to fit. See layouts available at https://developer.fyne.io/started/layouts

**Comment by smp12345** [comment]
Well, thank you
