### ISSUE TITLE
Checkbox labels are not rendered correctly

### ISSUE THREAD

**Issue by sirkon** [fyne-io/fyne#2034]
Haven't find such issue here, so filling a new one

### Describe the bug:
Checkbox labels are not rendered correctly, a label renders a bit higher than a checkbox. Same on Linux and MacOS.

### To Reproduce:

Just build an example

### Screenshots:

<img width="136" alt="Снимок экрана 2021-02-26 в 21 55 27" src="https://user-images.githubusercontent.com/56399/109343072-d2559000-787d-11eb-9e0b-6375865c4b11.png">

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
		widget.NewCheck("checkbox", func(b bool) {}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux and MacOS
 - **Version:** Ubuntu 20.04, macOS Big Sur 11.2.1
 - **Go version:** go 1.16
 - **Fyne version:** v2.0.1-0.20210220181336-05b7688b9afe

**Comment by andydotxyz** [comment]
Please update to the latest version of the `develop` branch, this should be fixed already.

**Comment by sirkon** [comment]
Yeah, fixed. 

PS This, `fyne.io/fyne` is a bit annoying to update to a particular branch via

```shell
go get fyne.io/fyne/v2@develop # this won't work, a valid semver is needed
```

May be to put `vX.Y.Z-pre-....` tags on develop branch?

**Comment by andydotxyz** [comment]
We normally tag once a release process starts, yes. Before then it’s best to use SHA for the commits, though not that easy to discover I guess...

**Comment by sirkon** [comment]
> though not that easy to discover I guess...

A bit tricky. The easiest approach I know is to 

```
go get github.com/fyne-in/fyne/v2@develop
```

at first.

It will fail due to a mismatch of the repo requested and module name, but will show a pseudo-semver. Can use it with

```
go get fyne.in/fyne/v2@v2…
```

IMO this deserves a mention in the README.

**Comment by AlbinoGeek** [comment]
> ..
@sirkon You can also simply do:

`go get -u fyne.io/fyne/v2`

This will automatically fetch the tagged version (in this case `v2.0`) -- If you intended to test the "latest development version" then you would use the second form (which specifies a branch):

`go get -u fyne.io/fyne/v2@develop`

**Comment by sirkon** [comment]
Didn't know that, thought `-u` is gone with modules, will know, thank you.
