### ISSUE TITLE
uri.Extension() only returns the last one

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2038]
### Describe the bug:

I noticed that the new storage changes in fyne 2.0.0 introduced an issue with the extensions for uris. If you create a uri from `archive.tar.gz`, I would certainly expect the extension to be ".tar.gz", but calling `uri.Extension()` only returns ".gz". This does not only have the effect that the output is wrong, it also breaks any file extension filters that tries to filter `.tar.xx` filenames for example.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code below.

### Example code:

```go
uri := storage.NewFileURI("archive.tar.gz")
fmt.Println(uri.Extension())
```

### Device (please complete the following information):
 - **OS:**  Linux
 - **Version:**  5.10.15
 - **Go version:**  1.16.0
 - **Fyne version:**  2.0.0

**Comment by andydotxyz** [comment]
I don’t think this is a bug, it matches the Go `filepath` package.

https://play.golang.org/p/F7HWl2t11KD

**Comment by Jacalz** [comment]
Agreed. Not a bug...

**Comment by AlbinoGeek** [comment]
A thought after the discussion in Slack, if you decide you want multiple extensions supported (for example, in the file open dialog/filter) -- you can simply **remove the basename** to get "all extensions (multiple dots)" in a reliable way, while still supporting single extension/dots as normal.
