### ISSUE TITLE
Should we add borderless window mode?

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#204]
This is desktop specific so should we add it?
Not certain about this one so opening a ticket to track interest...

Note that fullscreen windows are borderless by definition so this is only for "windowed" windows without the decorations...

**Comment by okratitan** [comment]
Borderless non-fullscreen windows are a rare need and I think best left up to A. The window manager and B. The end user who can tell his window manager to draw it borderless.

**Comment by andydotxyz** [comment]
Great, I will close this. It may need to be implemented in the backend depending on how we handle popover widgets (menus etc)

**Comment by sanguohot** [comment]
It is very useful to hide titlebar and menubar.

**Comment by andydotxyz** [comment]
If you can describe the use-case here we can look at it again, bearing in mind that it seems like a desktop extension and not something for a core API. @sanguohot

**Comment by sanguohot** [comment]
Well, I have just figured it out, just one line before creating a window.
`glfw.WindowHint(glfw.Decorated, 0)`

Now I initialize two windows using the same canvas object, one of them is borderless, but only one could be shown everytime.
It works well.

![reader_withborder](https://user-images.githubusercontent.com/25117034/70494680-30963600-1b47-11ea-8606-1b5725f99509.png)
![reader_borderless](https://user-images.githubusercontent.com/25117034/70494681-3429bd00-1b47-11ea-9ef0-1ee57f4ceffa.png)

Thanks.
