### ISSUE TITLE
widget.ToolbarItem SetIcon

### ISSUE THREAD

**Issue by xines** [fyne-io/fyne#2040]
### Is your feature request related to a problem? Please describe:
At the moment ToolBarItem does not have a SetIcon function like widget buttons even tho toolbars are buttons under the hood.
So as a workaround to set the icon it's required to store the fyne.resource icon into variable and re-update content accordingly.

### Is it possible to construct a solution with the existing API?
Yes

### Describe the solution you'd like to see:
```
toolBarItem = widget.NewToolbarAction(theme.FyneLogo(), func() {})
toolBarItem.SetIcon(theme.QuestionIcon())
```

**Comment by andydotxyz** [comment]
You can currently do this:

```go
toolbarItem.Icon = theme.QuestionIcon()
toolbar.Refresh()
```

**Comment by xines** [comment]
> You can currently do this:
> 
> ```go
> toolbarItem.Icon = theme.QuestionIcon()
> toolbar.Refresh()
> ```
Using newest dev branch i get this.
![GitHub Logo](https://i.imgur.com/L85a5sn.png)

Interface have no icon so explains why.
https://developer.fyne.io/api/v2.0/widget/toolbaritem.html

**Comment by andydotxyz** [comment]
I'm sorry - I forgot that the return type is the interface.

```go
toolbarItem.(*widget.ToolbarAction).Icon = theme.QuestionIcon()
toolbar.Refresh()
```

**Comment by xines** [comment]
Yes i see, tyvm @andydotxyz
- I still believe SetIcon to be a great addition. 👍

**Comment by adzo261** [comment]
I would like to do this one. 


> ### Describe the solution you'd like to see:
> ```
> toolBarItem = widget.NewToolbarAction(theme.FyneLogo(), func() {})
> toolBarItem.SetIcon(theme.QuestionIcon())
> ```
@xines I think this way it won't be possible since `ToolbarItem` is an interface and not a struct. <br> 
Also, we can't add `SetIcon` to the `ToolbarItem` interface since multiple toolbar items are of the same type (e.g spacers, separators, etc.)
A workaround can be something like -
```func SetIcon(toolbarItem ToolbarItem , icon fyne.Resource){...}```

But I think since we have `SetIcon` in different packages and it is invoked by some struct object, it would be inconsistent with that pattern.


Another thing we can do is to implement `SetIcon` on `t *ToolbarAction` as follows:
```
func (t *ToolbarAction) SetIcon(icon fyne.Resource) {
	t.Icon = icon
	t.ToolbarObject().Refresh()
}
```

But then we will have to cast the interface to specific type while using it - 
```
toolbarItem.(*widget.ToolbarAction).SetIcon(theme.QuestionIcon())
```

@andydotxyz @xines Any pointers on how can we implement this ?

**Comment by andydotxyz** [comment]
Or `NewToolbarAction` could return a `ToolbarAction` instead of `ToolbarItem`...? That could have a `SetIcon()` function

**Comment by adzo261** [comment]
> Or `NewToolbarAction` could return a `ToolbarAction` instead of `ToolbarItem`...? That could have a `SetIcon()` function

Yes, we can do that too as `NewToolbar` accepts `ToolbarItem`s. But again, it is inconsistent with the existing code. Currently, every concrete toolbar item constructor is returning a generic `ToolbarItem` interface.
Can I know what is the idea behind such a design, as I am fairly new to Golang?
Meanwhile, I will implement it as you said and run tests to see if anything else breaks.

**Comment by andydotxyz** [comment]
> Can I know what is the idea behind such a design, as I am fairly new to Golang?

I was also very new to Go when I wrote that code, so it may not be the right way to do it ;).
In general I think they promote accepting interfaces (in function parameters) and return concrete types.

**Comment by xines** [comment]
> In general I think they promote accepting interfaces (in function parameters) and return concrete types.

Yeah indeed they do.
- Just stay away from 'interface pollution' hehe.

> as I am fairly new to Golang

Id highly recommend giving this a look :) https://go-proverbs.github.io/

**Comment by andydotxyz** [comment]
On `develop` for testing, thanks :)
