### ISSUE TITLE
Documentation barely usable

### ISSUE THREAD

**Issue by chmike** [fyne-io/fyne#2045]
### Describe the bug:

The splitting of the source code into packages make it difficult to locate information in the documentation. 

The referenced documentation is here: https://pkg.go.dev/fyne.io/fyne/v2 but the functions defined in the different packages are not accessible from this page. It makes navigation into the documentation impossible. The problem might be the pkg.go.dev service. But providing links to the documentation of the different packages could help. 

I needed to locate an example close to what I would like to do and reverse engineer it to find out how to do what I wanted to do. 

### To Reproduce:
Go to https://pkg.go.dev/fyne.io/fyne/v2, the reference provided in the README, and try to access the functions/methods define in the package `canvas`. 

### Device (please complete the following information):
 - **OS:** Ubuntu
 - **Version:** 20.04
 - **Go version:** 1.16
 - **Fyne version:** v2.0.0

**Comment by chmike** [comment]
OOps, my bad. One has to go to `Directories` to navigate in the packages subdirectories.

**Comment by andydotxyz** [comment]
You could also use the site https://developer.fyne.io which has a search function across all of the packages
