### ISSUE TITLE
the driver does not appear to support opengl?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2046]
I test in VBox, found that the prompt does not support OpenGL, I would like to ask, how many graphics cards do not support OpenGL now?

**Comment by AlbinoGeek** [comment]
You need to enable Hardware Acceleration in VirtualBox settings under the Graphics tab.

**Comment by smp12345** [comment]
My host is Win10, and the virtual machine is Win7. I enable 3D Acceleration, but I still cannot support it

**Comment by andydotxyz** [comment]
You may also have to update your graphics drivers, the OpenGL support is provided by them

**Comment by smp12345** [comment]
Is there an easy way to determine whether OpenGL is supported or not?Are there any graphics cards that don't support OpenGL?

**Comment by andydotxyz** [comment]
This is operating system specific and I'm no expert on Windows.
However the only cards that I know that do not support OpenGL are the embedded, low power, graphics chips that come alongside higher power ones in laptops. I am not aware of any standard release computers that do not support it.
The version we use was released in 2008.

**Comment by smp12345** [comment]
OK, thank you for your help

**Comment by AlbinoGeek** [comment]
I have a Windows 7 (with Service Pack 1 mind you) guest **with VirtualBox Guest Additions installed** and **3D Acceleration Enabled** on a Fedora 33 Workstation Host successfully running `fyne` applications.

Applications also run in Windows 7 SP1 installed in Gnome Boxes (where 3D Acceleration is enabled by default on supported guests.)

Please note however that according to Microsoft: **Support for Windows 7 ended on January 14, 2020**

**Comment by smp12345** [comment]
我测试vbox win7 sp1的确可以支持opengl，win7 sp0不受支持，sp1界面显示效果好差，没有宿主机效果显示好。尽管win7已经暂停支持了，但还有不少用户仍然在使用win7

**Comment by smp12345** [comment]
I test VBox Win7 SP1 can indeed support OpenGL, Win7 SP0 is not supported, SP1 interface display effect is poor, not as good as the host effect display.Although Win7 support has been suspended, there are still many users using Win7

**Comment by andydotxyz** [comment]
Unfortunately it is not really practical for us to support combinations of virtual machines and OS that are no longer supported by the upstream vendors.
If anyone wanted to contribute it that would be great, but it's just too difficult for our team to do so.
