### ISSUE TITLE
Add Resizable Panel Widget

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#205]
Would be nice to create panels that can resize (with min/max size) within the layout it resides.

**Comment by andydotxyz** [comment]
Like GTK Paned?
https://developer.gnome.org/gtk3/stable/GtkPaned.html

**Comment by pbarnum** [comment]
Yes, exactly! Thanks for the link 🙂

**Comment by andydotxyz** [comment]
Ok cool. We will need to land mouse move event handling first but will explore getting this into 1.1

**Comment by andydotxyz** [comment]
The prerequisites are done, let's see if we can get it into 1.2

**Comment by stuartmscott** [comment]
@pbarnum does the split widget introduced in #789 resolve this issue for you?

**Comment by andydotxyz** [comment]
Let's assume that the widget on develop satisfies this unless we hear otherwise
