### ISSUE TITLE
Fyne packagae: Why we need "appID" windows's release version

### ISSUE THREAD

**Issue by prashantaeroqual** [fyne-io/fyne#2053]
### Describe the bug:
I try to compile my windows' app using "fyne package" and I use the "--release" flag to have the release version. However, it prompts an error that  "Missing appID parameter for package".

Based on the help section of "fyne package --help" the appID is only meant for Darvin or iOS. 

> 
>  -appID string
>         For ios or darwin targets an appID is required, for ios this must
> 

However, when I see the source code of the Fyne package (line 192). It seems for only release version you need App ID
Link: https://github.com/fyne-io/fyne/blob/c29a0624ed96ba1b8f45d903b6941824d50e0502/cmd/fyne/commands/package.go#L192 

Additionally in the  "[package-windows.go](https://github.com/fyne-io/fyne/blob/master/cmd/fyne/commands/package-windows.go)" file the appID never used.

### To Reproduce:
appVersion=1.0.0
env GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc fyne package --name "Utility" --icon "icon.png" --appVersion "$appVersion" --executable "test.exe" --release

### Device (please complete the following information):
Go version: 1.16
Fyne version: c29a062

**Comment by andydotxyz** [comment]
There is a difference between "fyne package" and "fyne release".
The old "fyne package -release" sits between the two, somewhat uneasily.
Can I ask what the intent was in using "package -release" instead of just "release" command so we can better understand?

**Comment by Jacalz** [comment]
I think this has been answered. Can it be closed?

**Comment by andydotxyz** [comment]
The documentation was fixed in the newer command line parse code for `v2.1`, moving to that milestone and marking closed.
