### ISSUE TITLE
The problem of VBox height

### ISSUE THREAD

**Issue by xbc563771383** [fyne-io/fyne#2057]
logEntry := container.NewVBox(widget.NewLabel("温馨提示"))
logBox := container.NewScroll(logEntry)
content := container.NewVBox(nameBox, passwordBox, typeBox, keyBox, beginBtn, logBox, stopBtn, sumBox, timesBox)

myWin.SetContent(content)
myWin.ShowAndRun()

![image](https://user-images.githubusercontent.com/26474658/109795774-54fd9700-7c52-11eb-9323-7278fd6a951a.png)

How to raise the height

**Comment by andydotxyz** [comment]
VBox is designed to collapse height to minimum value. If you want to have the content expand try a different container - like Border?
