### ISSUE TITLE
fyne_demo: [Android 11] Theme Doesn't Save

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#2059]
### Describe the bug:

Changing the theme does not result in it being saved. (I don't know if this feature was ever implemented in the first place?)

### To Reproduce:

Steps to reproduce the behaviour:

1. Run the fyne demo from the appstore
1. Change the theme
1. Force quit the fyne demo
1. Re-open the fyne demo

### Screenshots:

https://user-images.githubusercontent.com/1910461/109857042-11356e00-7c0f-11eb-9cfd-8c133b80e2df.mp4

### Device (please complete the following information):
 - **OS:** Android 11 - Samsung Galaxy S20+ Ultra 5G
 - **Go version:** N/A
 - **Fyne version:** v2.0.0 ?

![image](https://user-images.githubusercontent.com/1910461/109856957-f531cc80-7c0e-11eb-8ca2-41ebef7afe63.png)

**Comment by AlbinoGeek** [comment]
Alright, can this one. The theme saves if I change it from the `Settings` page, but nowhere else.

Feels intentional now.

**Comment by andydotxyz** [comment]
Yes, the "Light" and "Dark" buttons are just for user to get a feel for it.
