### ISSUE TITLE
Add Accordion Widget

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#206]
Accordions are great for displaying Parent/Child data relationships

**Comment by andydotxyz** [comment]
Can you add some use cases or descriptions of how a thing like this may work? There are various examples around the web but I would like to understand what we think it would provide.

**Comment by pbarnum** [comment]
Accordians provide a nice way to display headers with subsequent detail, while also clearing the clutter of too much text on the screen at once. The default functionality should be opening a header to reveal it's information, clicking another header should close the first section while at the same time open the new one. Some options can be provided like having a section opened by default, or keeping multiple sections open at the same time. Helper functions like `GetOpened()` or `OpenAll()/CloseAll()` would be nice.

Some use cases would be like FAQs, Navigation sections, sections and subsections of data about one or many topics. The underlying functionality could also be used to create hidden panels that open and close with a "+" icon.

**Comment by andydotxyz** [comment]
On develop for testing - thanks @stuartmscott
