### ISSUE TITLE
fyne_demo: [Android 11] Delay entering first demo

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#2060]
### Describe the bug:

The first demonstration loaded after fyne demo app has opened has a noticeable delay to open. However, after navigating to a demo, all demos load faster (until force stop, where the same behaviour can be reproduced again with a different demo.)

The delay is between a half and full second.

### To Reproduce:

Steps to reproduce the behaviour:

1. Install fyne demo from appstore
1. Force quit fyne demo
1. Run fyne demo
1. Tap "Advanced"

### Screenshots:

https://user-images.githubusercontent.com/1910461/109858020-2959bd00-7c10-11eb-9e52-9fabf8975fe4.mp4

### Device (please complete the following information):
 - **OS:** Android 11 - Samsung Galaxy S20+ Ultra 5G
 - **Go version:** N/A
 - **Fyne version:** v2.0.0 ?

![image](https://user-images.githubusercontent.com/1910461/109856957-f531cc80-7c0e-11eb-8ca2-41ebef7afe63.png)

**Comment by andydotxyz** [comment]
It is possible that this is an instance of the previously discussed failure to refresh.
Please check the new version of the app or `v2.0.1-rc2`.

**Comment by andydotxyz** [comment]
I can no longer replicate since v2.0.1 release
