### ISSUE TITLE
fyne_demo: [Android 11] No redraw entering "Windows" if first navigation

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fyne#2061]
### Describe the bug:

If you tap "Windows" as your first destination after starting the fyne demo fresh (force stopping it) -- you will find the screen is not repainted until you tap again, which will lead you to the "Fixed Window" demo. Basically, the "Windows" screen was never rendered.

This cannot be reproduced if you navigate to another demo first.

### To Reproduce:

Steps to reproduce the behaviour:

1. Install fyne demo from appstore
1. Force quit fyne demo
1. Run fyne demo
1. Tap "Windows"
1. Wait multiple seconds, no redraw, tap again
1. You are now on "Fixed Window" Demo

### Screenshots:

https://user-images.githubusercontent.com/1910461/109858445-b00e9a00-7c10-11eb-8552-d1f4b6f1803d.mp4

### Device (please complete the following information):
 - **OS:** Android 11 - Samsung Galaxy S20+ Ultra 5G
 - **Go version:** N/A
 - **Fyne version:** v2.0.0 ?

![image](https://user-images.githubusercontent.com/1910461/109856957-f531cc80-7c0e-11eb-8ca2-41ebef7afe63.png)

**Comment by andydotxyz** [comment]
Pretty sure this is resolved in the most recent version of the app (on `develop`, `release/v2.0.x` branches and also on Google Play)

**Comment by andydotxyz** [comment]
It was resolved as https://github.com/fyne-io/fyne/pull/2054
