### ISSUE TITLE
Duplicate symbol error when compiling for Android with NDK 23

### ISSUE THREAD

**Issue by mythril** [fyne-io/fyne#2064]
### Describe the bug:
Attempting to compile the fyne_demo (or my own fyne app) for android errors out with a duplicate symbol message.

### To Reproduce:
in the fyne_demo repo / subdir
run:
```
$ ANDROID_NDK_HOME=~/Android/Sdk/ndk/23.0.7123448/ fyne package -os android -appID com.example.myapp -icon ./data/fyne_scene_light.png 
```
see error:
```
go build -buildmode=c-shared -o /tmp/gomobile-work-971507893/lib/armeabi-v7a/libfyne_demo.so fyne.io/fyne/v2/cmd/fyne_demo failed: exit status 2
# github.com/fyne-io/mobile/app
ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.go:38 (/home/###/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:38)
>>>            $WORK/b175/_x002.o:(.bss+0x0)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.go:39 (/home/###/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:39)
>>>            $WORK/b175/_x002.o:(.bss+0x4)

ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.c:146
>>>            $WORK/b175/_x004.o:(.bss+0x18)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.c:147
>>>            $WORK/b175/_x004.o:(.bss+0x1C)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### OS:
```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
#### Go version:
```
$ go version
go version go1.16 linux/amd64
```

#### Fyne version:
~ c29a0624ed96ba1b8f45d903b6941824d50e0502

**Comment by fpabl0** [comment]
Hello @mythril, it seems that this is related to #1912 (if not the same) and golang/go#44121. As a workaround, could you please try downgrading your NDK version to v21.x.x? That should solve the issue :)

**Comment by andydotxyz** [comment]
This should be fixed after merging a fix to our `gomobile` fork.
Can you please test `develop` branch?

**Comment by mythril** [comment]
@andydotxyz Seems to fail with a different issue but it doesn't directly complain about `fyne` code afaict:

```
$ ANDROID_NDK_HOME=~/Android/Sdk/ndk/23.0.7123448/ fyne package -os android -appID com.example.myapp -icon ./../fyne_settings/Icon.png 
/home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm /tmp/gomobile-work-124400139/lib/armeabi-v7a/libfyne_demo.so: fork/exec /home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm: no such file or directory
```

**Comment by equisde** [comment]
> @andydotxyz Seems to fail with a different issue but it doesn't directly complain about `fyne` code afaict:
> 
> ```
> $ ANDROID_NDK_HOME=~/Android/Sdk/ndk/23.0.7123448/ fyne package -os android -appID com.example.myapp -icon ./../fyne_settings/Icon.png 
> /home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm /tmp/gomobile-work-124400139/lib/armeabi-v7a/libfyne_demo.so: fork/exec /home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm: no such file or directory
> ```

i'm getting this same issue tried downloading ndk and setting it on system variables and also i tried installing through android studio but i'm getting the no such file or directory error what should i do?

**Comment by andydotxyz** [comment]
To get the fix you'll need to use the unreleased (`develop`) version of Fyne, the fix rolls out in v2.1 next month.

**Comment by andydotxyz** [comment]
> > @andydotxyz Seems to fail with a different issue but it doesn't directly complain about `fyne` code afaict:
> > ```
> > $ ANDROID_NDK_HOME=~/Android/Sdk/ndk/23.0.7123448/ fyne package -os android -appID com.example.myapp -icon ./../fyne_settings/Icon.png 
> > /home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm /tmp/gomobile-work-124400139/lib/armeabi-v7a/libfyne_demo.so: fork/exec /home/###/Android/Sdk/ndk/23.0.7123448/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm: no such file or directory
> > ```
> 
> i'm getting this same issue tried downloading ndk and setting it on system variables and also i tried installing through android studio but i'm getting the no such file or directory error what should i do?
> 
> edit: i'm on windows
> edit 2: i got it working downgrading ndk to version 21.4.7075529

Apologies this got dropped... We need to support the latest build tools, so I opened #2498 to track it.

**Comment by andydotxyz** [comment]
For anyone that isn't able to remove the gomobile dependency from your project (usually due to transitive dependencies) there is another solution!

Fyne has a gomobile-bridge project that maps the gomobile APIs into a Fyne runtime: https://github.com/fyne-io/gomobile-bridge
