### ISSUE TITLE
Append to radio group

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#208]
It would be a nice feature to be able to add more radio options dynamically. I have a form where depending on how you fill it out, determines the amount of options available in the radio group.

**Comment by andydotxyz** [comment]
Quite right, apologies for the omission

**Comment by andydotxyz** [comment]
I can add this, but in the meantime you can do it manually:

	radio.Options = append(radio.Options, "New Option")
	widget.Refresh(radio)

**Comment by pbarnum** [comment]
Oh wow, I misunderstood the procedure because I did this but didn't `Refresh` after. Thanks for the heads up!

**Comment by pbarnum** [comment]
Your temporary solution worked (using `Refresh`) but I found that my container wasn't reflecting the change, but did when I resized the window. So my solution for that was the following
```
// Refresh did not work
// widget.Refresh(scrollContainer)
scrollContainer.Resize(scrollContainer.Size())
```

**Comment by andydotxyz** [comment]
You have a good point. This used to work but in rectifying some Windows sizing issues the re-layout-every-frame approach was removed. 

For now it remains a known issue that children who’s MinSize increases do not force the parent to re-layout...
