### ISSUE TITLE
Rendering can stop working in a long running application

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#2084]
Unclear what is going on here.
It is possible that the UI stops responding.
The app continues to work (i.e. buttons tap, console logs etc) just the UI stops changing.

May relate to #950.
May be caused by some GPU constraints - does not seem to be a traditional memory leak as plenty free RAM.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run any app for a long time
2. See that UI can stop responding

### Device (please complete the following information):
 - **OS:** Arch Linux
 - **Version:** latest
 - **Go version:** 1.15
 - **Fyne version:** 2.0.1

**Comment by fpabl0** [comment]
> Run any app for a long time

Hmm does the app need to be focused or not?

**Comment by andydotxyz** [comment]
It does not seem to matter if it is foreground or not

**Comment by fpabl0** [comment]
I can't reproduce it. I have run the fyne_demo for almost 6 hours, and it still works great.

**Comment by andydotxyz** [comment]
Hmm, that is good to hear, in a way.

Perhaps this is specific to:
* Running on (arch) linux?
* Having FyneDesk running
* A problem with my Arch linux install or ageing XPS laptop

**Comment by fpabl0** [comment]
Yes, it could be, although now I realized that I tested it on `develop` branch, could it be that this is fixed on `develop` but not in `2.0.1`?

**Comment by andydotxyz** [comment]
I have seen this happen since late development of v2.0.0, so I think it is present in all the branches you listed

**Comment by andydotxyz** [comment]
I thought it was a bug in FyneDesk but then it occurred on another app.

**Comment by fpabl0** [comment]
Hmm, do they have something in common?

**Comment by andydotxyz** [comment]
The only thing that seems to apply to both is the computer they were running on honestly.

I have done a complete OS update and restart and will see if the same occurs, this may have been a red herring and/or less common issue than I thought.

**Comment by andydotxyz** [comment]
A whole day running and it's not happened again. Closing unless anyone else experiences this
