### ISSUE TITLE
BoxLayout inspired from W3c Grid layout

### ISSUE THREAD

**Issue by IGLOU-EU** [fyne-io/fyne#2086]
### Is your feature request related to a problem? Please describe:
Actual `container.New...` is very confuse (to me), request to using tricks or multiples level of container.
With given (to me) a confused documentation and source code.

### Is it possible to construct a solution with the existing API?
I don't know

### Describe the solution you'd like to see:
A grid layout like CSS can be very powerful.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout

With like
`container.NewGrid()` or `container.NewNamedGrid()`
`grid.Template("a a a" 20% "c b b" auto, 50px fr)`
`grid.Add("a", widget.Entry)`
`grid.Add("c", widget.Entry)`
`grid.Add("b", widget.Entry)`

**Comment by andydotxyz** [comment]
Multiple levels of container is expected and encouraged.
This means we can build complex layouts from simple components.
https://developer.fyne.io/started/layouts

It sounds to me like you are requesting "Weighted grid"? Maybe we could add a feature so that the grid we have built could be non-uniform.
Does that satisfy the requirement?

**Comment by IGLOU-EU** [comment]
Sorry my English is not perfect, and I don't know what is a "Weighted grid" :s

I add some explanation about
Actually if you want 
```
 _________________________
| Full width              |
 --------------------------
| Free width       | 50px |
 --------------------------
|  A big   |  Free width  |
|  box     | -------------|
|----------|  Multi line  |
| ...                     |
| ...                     |
 --------------------------
| Full width              |
 --------------------------
```
This is tricky to achieve with Fyne, you need to use multiple "simple components" with empty parts ...
I'm not a CSS fan, but a lot of work in W3Consortium can be instructive. And can avoid repeating GUI building error.

So, in CSS you can define a grid with number of Col and Row.
After that you can set where a content start and where is ending with Col/Row coordinate.
Something like that can be awesome I think.

**Comment by andydotxyz** [comment]
> This is tricky to achieve with Fyne, you need to use multiple "simple components" with empty parts ...

You should not need to pad the UI with empty elements, combining containers should work to create complex applications without such workarounds. Perhaps there is a better combination of layouts that could be used in your app?

The concept of a "content grid" that has been popular in CSS for a long time is OK for document-based presentation and that is where the web sits. However (and as web developers are finding) it is not the catch-all solution as interfaces can vary so much in size, orientation etc. Therefore we have gone with the concept of composing user interfaces from simpler components. It is then possible, at any level, to alter what is/isn't visible or how it is layed out based on the space avaialble.

**Comment by andydotxyz** [comment]
> Sorry my English is not perfect, and I don't know what is a "Weighted grid" :s

I was meaning that columns in a grid could be allocated sizes other than an equal split of all available space. That has been considered before (but never got up the priority list).

**Comment by andydotxyz** [comment]
Other grid / layout discussions exist, let's close this one as copying CSS/HTML in general does not create the API we design for
