### ISSUE TITLE
How to set the button disabled state?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2088]
I have multiple buttons under window. These buttons are mutually exclusive and do not support repeated clicking. After clicking A button (the button is gray and disabled), the user cannot click B button.
At present, I manually control it through the logo, which feels troublesome. Is there a simple method?

**Comment by Jacalz** [comment]
You should just be able to call `button.Disable()` to disable and `button.Enable()` to enable it. The `widget.Button` type is a `DisableableWidget` and exposes the following functions: https://github.com/fyne-io/fyne/blob/ec966e729738083602e632c4092dfc35be65ed6f/widget/widget.go#L182-L218

Have you tried using that?

**Comment by smp12345** [comment]
Thank you for your answer. It has been solved through your way

**Comment by Jacalz** [comment]
Good. I’ll close this then.
