### ISSUE TITLE
Please release him after creating the memory.

### ISSUE THREAD

**Issue by chenyalyg** [fyne-io/fyne#209]
Please release him after creating the memory.
fyne/driver/gl/draw.go:99 gl.GenVertexArrays(1, &vao)
fyne/driver/gl/draw.go:104 gl.GenBuffers(1, &vbo)
fyne/driver/gl/gl.go:48 gl.GenTextures(1, &texture)

Test from demo "life" version 1.0.0

**Comment by andydotxyz** [comment]
Thanks for the report. I think Textures from gl.go:48 are cleared in loop.go:120 - this could be made more obvious.

The others need to be cleaned up, I am looking in to it.
