### ISSUE TITLE
databinding external list - on change

### ISSUE THREAD

**Issue by bikedel** [fyne-io/fyne#2091]
hello

sorry for the basic question...

how do i return the label from a databinding list?

thanks

	data := binding.BindStringList(
		
		&[]string{"Tags"},
	)

	myTags := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})

	myTags.OnSelected = func(id widget.ListItemID) {
		   // fmt.Println("my tags selected : ", myTags[id])

**Comment by andydotxyz** [comment]
I don't quite understand - the Label is used for display, so why are you trying to return it?

You can get the `string` by keeping a reference to the data... like:

```go
data := []string{"tags"}
myTags := widget.NewListWithData(data.BindStringList(&data),
...
)
myTags.OnSelected = func (id widget.ListItemID) {
    fmt.Println("my tags selected:", data[id])
}
```

**Comment by bikedel** [comment]
Hello

Thank you very much for your response.

I am trying to append data to a list and on selected show me the data item.

In Example A  below
 I get this error:  //main.go:35:44: invalid operation: data[id] (type binding.ExternalStringList does not support indexing)
 I can append data but can’t figure out how to reference the data onSelect

In Example B below
 I think as your email suggests.
 I am able to reference the data but  am unsure how to append data. How do I refresh the list or binding?


Could you please  point me in the right direction. 
Thanks



Example A


package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")

	data := binding.BindStringList(
		&[]string{"Item 1", "Item 2", "Item 3"},
	)

	list := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})

	add := widget.NewButton("Append", func() {
		val := fmt.Sprintf("Item %d", data.Length()+1)
		data.Append(val)
	})

//main.go:35:44: invalid operation: data[id] (type binding.ExternalStringList does not support indexing)
	list.OnSelected = func (id widget.ListItemID) {
	    fmt.Println("my tags selected:", data[id])
	}

	myWindow.SetContent(container.NewBorder(nil, add, nil, nil, list))
	myWindow.ShowAndRun()
}





Example B


package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)



func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")

    data := []string{"tags"}
    
    data = append(data,"yes")

	list := widget.NewListWithData(binding.BindStringList(&data),
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})

	add := widget.NewButton("Append", func() {
		data = append(data,"new")
		list.Refresh()
        

		fmt.Println("data - ", data)
	})

	list.OnSelected = func (id widget.ListItemID) {
	    fmt.Println("my tags selected:", data[id])
	}

	myWindow.SetContent(container.NewBorder(nil, add, nil, nil, list))
	myWindow.ShowAndRun()
}

**Comment by andydotxyz** [comment]
With example B you can append as follows:

```go
data = append(data, <new item>)
list.Refresh()
```

With example A you could also access the data like:
```go
item, err := data.Get(id)
```

So you can use either approach - it really depends on preference and/or who else you wish to provide with access to the data.

**Comment by bikedel** [comment]
I have example A working. 

Thank you very much for your help.
