### ISSUE TITLE
Can the button on the dialog box be set to disabled state?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2093]
I need to confirm whether the dialog box is submitted according to the user's input. If the information entered by the user is not verified, the YES button will be disabled. Can I realize this?

Here is the sample code:
```
func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	dlg := container.NewVBox(
		hello,
		widget.NewEntry(),
	)
	dialog.NewCustomConfirm("test win", "yes", "no", dlg, func(b bool) {

	}, w)
	w.Resize(fyne.NewSize(300,300))
	w.ShowAndRun()
}
```

![button_disabled](https://user-images.githubusercontent.com/50661521/111311458-37d8b780-8699-11eb-9922-b6fb5d605a20.png)

**Comment by andydotxyz** [comment]
If you use `dialog.ShowForm` and add a `Validator` to an `Entry` inside the `FormItem`s what you describe will occur.

**Comment by smp12345** [comment]
I want to make the YES button gray and disabled, is that OK?It can't be activated until a certain condition is met.My current business code has been implemented, but it's a bit complicated.Similar to Button.disabled (), but I found that the initials are lowercase and not accessible from outside

**Comment by Jacalz** [comment]
Like @andydotxyz said, just use the `dialog.ShowForm` with setting a validator to the `entry.Validator` field in the entry.  When the validator returns an error, your "yes" button is going to be disabled and when it does not return an error, it is going to be enabled.

**Comment by smp12345** [comment]
Can you write an example for me? Thank you very much

**Comment by smp12345** [comment]
Okay, I'll upgrade to 2.0

**Comment by Jacalz** [comment]
> Can you write an example for me? Thank you very much

I think this should serve as a good starting point: https://github.com/fyne-io/fyne/blob/d8f29c2237970efed84564b5dd8a32e6c504be46/dialog/form_test.go#L84-L110

**Comment by smp12345** [comment]
Thank you. Let me have a look

**Comment by smp12345** [comment]
I have tested that button disabling can be achieved. At present, there are only two buttons in the bottom line, namely Cancel and Submit. Can I also customize the number of buttons?Like adding a new button

**Comment by smp12345** [comment]
![20210317223557](https://user-images.githubusercontent.com/50661521/111487036-f6b4d600-8772-11eb-92a9-a59ba9b8715d.png)

**Comment by Jacalz** [comment]
> I have tested that button disabling can be achieved. At present, there are only two buttons in the bottom line, namely Cancel and Submit. Can I also customize the number of buttons?Like adding a new button

No that is not currently possible. You’d have to make your own custom dialog, I think.

I’ll close this now as it looks to me like the question has been answered. I recommend you to join the #fyne channel on the gopher slack. It works better for questions than what GitHub does.

**Comment by smp12345** [comment]
Thank you for you help
