### ISSUE TITLE
DragEnd Crashes the Application From Entry

### ISSUE THREAD

**Issue by mathaou** [fyne-io/fyne#2095]
### Describe the bug:

Dragging and releasing the mouse on an Entry widget I have created crashes the application.

### To Reproduce:
Steps to reproduce the behaviour:
Run the code included below and drag over the Entry control

### Example code:

```go
// main.go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	ui "processVisualizer/elements"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(640, 480))

	pif := ui.NewProcessInputField()

	entryWidget := container.NewHBox(pif.RootProcessForm, pif.ProcessFormSubmit)
	w.SetContent(container.NewBorder(
		widget.NewForm(
			&widget.FormItem{
				Text:     "Label",
				Widget:   entryWidget,
			}),nil,nil,nil,
	))

	w.ShowAndRun()
}
```

```go
//elements/processInput.go
package elements

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

type modifiedEntry struct {
	*widget.Entry
}

type ProcessInputField struct {
	rootProcess binding.String
	RootProcessForm modifiedEntry
	ProcessFormSubmit *widget.Button
}

func (pif modifiedEntry) MinSize() fyne.Size {
	return fyne.NewSize(200, 40)
}

func (pif modifiedEntry) DragEnd() {
        // never gets hit
	fmt.Println("asdf")
}

func NewProcessInputField() (ret *ProcessInputField) {
	ret = &ProcessInputField{
		rootProcess: binding.NewString(),
	}

	ret.ProcessFormSubmit = widget.NewButton("Visualize!", func(){
		val, _:= ret.rootProcess.Get()
		fmt.Println(val)
	})

	ret.RootProcessForm = modifiedEntry{
		widget.NewEntryWithData(ret.rootProcess),
	}

	return ret
}
```

console output:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0xf96ce4]

goroutine 19 [running]:
fyne.io/fyne/v2/widget.(*entryContent).DragEnd(0xc0000560a0)
        C:/Go/pkg/mod/fyne.io/fyne/v2@v2.0.1/widget/entry.go:1312 +0x124
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0xc0003b0000)
        C:/Go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/window.go:1247 +0x83
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/window.go:1271 +0x10d

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:**  10.0.17763
 - **Go version:** 1.16
 - **Fyne version:** 2.0.1

**Comment by fpabl0** [comment]
I think you are not extending the Entry widget correctly, you should follow this tutorial: 
https://developer.fyne.io/tutorial/extending-widgets

**Comment by mathaou** [comment]
> I think you are not extending the Entry widget correctly, you should follow this tutorial:
> https://developer.fyne.io/tutorial/extending-widgets

Yeah it was my bad. Thanks for clearing that up.

**Comment by fpabl0** [comment]
You're welcome :)

**Comment by andydotxyz** [comment]
Glad it's sorted :)
