### ISSUE TITLE
Cross compilation from Linux to Windows, mthread instead of pthread for GCC

### ISSUE THREAD

**Issue by metal3d** [fyne-io/fyne#2097]
### Describe the bug:
I try to cross-compile a simple app from Linux to Windows executable.

```
fyne package -os windows
# runtime/cgo
gcc: error: unrecognized command-line option '-mthreads'; did you mean '-pthread'?

Error building application: exit status 2
```

### To Reproduce:
1.simply try to compile...

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Fedora 33
 - **Go version:** go1.15.8
 - **Fyne version:** 2.0.1

**Comment by metal3d** [comment]
Note: I also tried to mingw64-gcc on my computer (mingw64-gcc-10.2.1-2) and same issue.

Note2: Fyne is very cool 😄

**Comment by andydotxyz** [comment]
When cross compiling you need to instruct which C compiler to use (with the `CC` environment).
See more at https://developer.fyne.io/started/cross-compiling.
You have installed the gcc which is great, just missed the configuration step.

The error you are seeing is Go trying to build a windows executable using a Linux gcc.

> Note2: Fyne is very cool 😄

Many thanks!

**Comment by metal3d** [comment]
Ha OK... that was not exactly what I see in https://developer.fyne.io/started/packaging, I only readed this page... sorry.
```
# worked
CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 fyne package -os windows
```
