### ISSUE TITLE
Scrolling API for List Widget

### ISSUE THREAD

**Issue by Altiano** [fyne-io/fyne#2105]
### Is your feature request related to a problem? Please describe:

As new items appended to the List widget until it has the scroll, it probably better for UX when she see that newly created item at the bottom of the list. 

### Is it possible to construct a solution with the existing API?

Probably. From what I see, the `List` widget has `scroller` API in it but just not exposed yet.

### Describe the solution you'd like to see:

```
list.ScrollToBottom()
```

or event better
```
list.ScrollToIndex(elementIndexToBeShown)
```

**Comment by andydotxyz** [comment]
This is on `develop` for testing
