### ISSUE TITLE
Mobile: entry "onsubmited" event is not sent

### ISSUE THREAD

**Issue by metal3d** [fyne-io/fyne#2106]
### Describe the bug:
I'm using the "OnSubmited" function to launch some actions. It works on computer but not on mobile (I need a button to submit).

### To Reproduce:
Create a simple entry with "OnSubmitted()" event handler. Compile for Android and install apk on emulator or device. The event is not sent.

### Example code:

```go
entry := widget.NewEntry()
entry.OnSubmitted = func(q string){
    d := dialog.NewInformation("example", q, win)
    d.Show()
}
```

### Device (please complete the following information):
 - **OS:** Linux and Android
 - **Version:** Fedora 33
 - **Go version:** 1.15.8
 - **Fyne version:** develop v2.0.2-0.20210319215240-17b9c647d7c9

**Comment by andydotxyz** [comment]
I think this must be Android specific, and may relate to the keyboard you have configured.
Can you please confirm what keyboard you are using?

**Comment by metal3d** [comment]
I use google board and I also tried with Samsung keyboard.

But submit action works with other apps.

**Comment by andydotxyz** [comment]
> I use google board and I also tried with Samsung keyboard.

OK thanks. My question may have been a bit random - but the code works on our mobile simulator, so it is not a simple failure in the mobile driver but something related to keyboard events that are device specific I think.

> But submit action works with other apps.

Oh for sure this is a Fyne bug :)

**Comment by metal3d** [comment]
Ha ok. I'm using an emulator and a real device :)

The problem is the same for both. Can you tell me what is the emulator API version (and if you use an image with Google APIS because I can't use an emulator with it, too slow whatever I do)

If you can give me your emulator spec, maybe I can find the version that fails ;)

There are also some differences between my device and emulator (BorderLayout "bottom" section is not at the bottom on my device) So there is possibly a specific version problem with the system image.

**Comment by andydotxyz** [comment]
Sorry by "our mobile simulator" I meant `go run -tags mobile .` which tests using mobile driver without loading Android or iOS frameworks.

**Comment by metal3d** [comment]
Right, but `go run -tags mobile .` I can't use keyboard :)

**Comment by andydotxyz** [comment]
Ah, yes - you're on Linux I forgot (another known bug).
I will try on my android and see. We have had issues with GBoard before, but not samsung keyboard - hmm.

**Comment by andydotxyz** [comment]
For my testing this is working with `v2.1.0-rc1` - it would be great if you could confirm @metal3d
