### ISSUE TITLE
Does the text above the Label control support copying?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2113]
Does the text on the widget.label support copy?For example, right mouse button copy or Ctrl + V

**Comment by andydotxyz** [comment]
It doesn't - labels are for UI comopnents rather than user interaction.
You could use a disabled `Entry` widget instead.
However be aware that this is not a very discoverable UI feature, so I would propose the addition of a "copy" button that is easier to see (and operate) for users.

**Comment by smp12345** [comment]
After the entry setting is disabled, the text inside the text box appears gray and is not very clear. Can I customize the text color?

**Comment by smp12345** [comment]
The font is gray, which is not clear to the user. If I can adjust the color, it would be better. The user may feel that this color cannot be copied and is in the disabled state
```
        a := app.New()
	w := a.NewWindow("Hello")

	entry := &widget.Entry{}
	entry.SetText("1111")
	entry.Disable()
	w.SetContent(container.NewVBox(entry))
	w.ShowAndRun()
```
![gray](https://user-images.githubusercontent.com/50661521/112780720-0d650200-907c-11eb-9aaf-e014385d5a38.png)

**Comment by andydotxyz** [comment]
> Can I customize the text color?

The standard widgets use the current theme. If you think the disabled text is too dim we could update the `theme.DisabledColor()` value.

> The user may feel that this color cannot be copied and is in the disabled state

This is confusing me. First you've asked if a label, which offers no hint of interaction, can be copied (which it can't) and now when I suggest Entry you are concerned that it may not look like it can be used, when disabled (i.e. read-only).
If you are concerned about making something clear to your app users I return you to my previous thought:

> I would propose the addition of a "copy" button that is easier to see (and operate) for users.

**Comment by smp12345** [comment]
My preferred control is the Label, because the Label doesn't have any style and just displays it. I'm just showing the information so the user can copy it. If the Label doesn't interact, I have to select Entry, but that's the problem I mentioned above.I want to be able to customize the color to make the text appear clearer

**Comment by andydotxyz** [comment]
If you need to alter the theme you can call `App.Settings().SetTheme(...)` passing your own version of the theme that has a different disabled color. Be sure to support both light and dark variants of course.
https://developer.fyne.io/tutorial/custom-theme
