### ISSUE TITLE
Feature request: Datepicker, Advanced Select

### ISSUE THREAD

**Issue by archistico** [fyne-io/fyne#2114]
**Datepicker**

for example
https://bootstrap-datepicker.readthedocs.io/en/latest/

**Advanced Select with filter search, multiselect** 

example
https://select2.org/appearance

Unfortunately I don't know how to program it without your help. I am willing to make a donation to you
sorry for my bad english

**Comment by andydotxyz** [comment]
I think that #888 captures the need for a date picker widget.

Please update this issue with details about what "advanced select" should do, that `Select` widget does not already do.
We have a standard "feature request" template that would have helped to fill out these details.

**Comment by archistico** [comment]
> 
> 
> I think that #888 captures the need for a date picker widget.
> 
> Please update this issue with details about what "advanced select" should do, that `Select` widget does not already do.
> We have a standard "feature request" template that would have helped to fill out these details.

#888 the same
I search datepicker and not date input widget... :) thank you
