### ISSUE TITLE
reversed for a right-to-left language like Hebrew or Arabic and Persian

### ISSUE THREAD

**Issue by amirex128** [fyne-io/fyne#2115]
when i use widget layout is reversed for a right-to-left language like Hebrew or Arabic
for example text must be like this :
سلام علیکم
but i see this
ک ی ل ع م ا ل س

i use this code for set font 
 os.Setenv("FYNE_FONT", "./assets/fonts/vazir_regular.ttf")

**Comment by andydotxyz** [comment]
Yes, we do not yet support right to left languages, sorry.
This is expected to be added in version 3.0 next year.
I think this is a duplicate of #90

**Comment by javad-majidi** [comment]
i have made a simple farsi/arabic [package](https://github.com/javad-majidi/farsi-reshaper) that solves this issue

**Comment by javad-majidi** [comment]
i have made a simple farsi/arabic [package](https://github.com/javad-majidi/farsi-reshaper) that solves this issue

**Comment by dweymouth** [comment]
Closing as duplicate of #90
