### ISSUE TITLE
File-I/O on Android

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2118]
### Describe the bug:

Develop Branch, Version pre 2.0.2

Write data to a file and reading it later does not read the same data that was written. This happens e.g. if characters []{} are used. This issue does not occur on Linux, however on Android.

### To Reproduce:
Steps to reproduce the behaviour:
Use the code example provided below. Then:
Enter the following text in the top Entry Widget:
[
  {
    a:b,
  }
]
The press "Store". The data ist stored on file. Next press "Read". The data is read from file
and displayed in the bottom Entry Widget.  It displays:
[
  {
    a:b,
  }
]]

This is different from the data written to the file.

### Screenshots:
![Screenshot_20210325-135731](https://user-images.githubusercontent.com/66474515/112524230-e10d6500-8d9f-11eb-8697-27ead72d5a87.jpg)

### Example code:

```go
package main

import (
        "fmt"
        "fyne.io/fyne/v2"
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/storage"
        "fyne.io/fyne/v2/widget"
        "io/ioutil"
        "log"
)

type taskApp struct {
        fyneapp fyne.App
        uri     fyne.URI
        e1, e2  *widget.Entry
}

/* --------------------------------------------------------------------------------------------------- */
func main() {

        log.Println("mdu: Starting...")
        app := app.NewWithID("Test_File") // --> Linux: RootURI returns /home/opc/.config/fyne/Test_File/
        //app := app.New()                               // --> Linux: RootURI returns /tmp; not allowed on Android
        w := app.NewWindow("Test")

        uri, err := storage.Child(app.Storage().RootURI(), "test.txt")
        if err != nil {
                log.Println("mdu: error: ", err)
                log.Println("mdu: exiting ...")
                app.Quit()
        }
        a := &taskApp{fyneapp: app,
                uri: uri,
        }
        w.SetContent(a.makeUI())
        w.ShowAndRun()
}

func (a *taskApp) makeUI() fyne.CanvasObject {
        a.e1 = widget.NewMultiLineEntry()
        a.e2 = widget.NewMultiLineEntry()
        b1 := widget.NewButton("Store", func() {
                a.Store()
        })
        b2 := widget.NewButton("Read", func() {
                a.Read()
        })
        return container.NewVBox(a.e1, b1, b2, a.e2)
}

func (a *taskApp) Store() {
        proc_name := "MyStore: "

        log.Println(proc_name, "URI: ", a.uri.String())
        v, err := storage.CanWrite(a.uri)
        if v == false || err != nil {
                log.Println(proc_name, "Error E1: ", err)
                return
        }
        storer, err := storage.Writer(a.uri)

        if err != nil {
                log.Println(proc_name, "Error: E2: ", err)
                return
        }
        defer storer.Close()

        b := []byte(a.e1.Text)
        n, err := storer.Write(b)
        if err != nil {
                log.Println(proc_name, "Error: E3")
                return
        }

        s := fmt.Sprintf("%d Bytes written: <%s>", n, string(b))
        log.Println(proc_name, s)

        a.e2.Text = ""
}

func (a *taskApp) Read() {
        proc_name := "MyRead: "

        log.Println(proc_name, "URI: ", a.uri.String())
        v, err := storage.CanRead(a.uri)
        if v == false || err != nil {
                log.Println(proc_name, "Error E21: ", err)
                return
        }
        reader, err := storage.Reader(a.uri)
        if err != nil {
                log.Println(proc_name, "Error: E22: ", err)
                return
        }
        defer reader.Close()

        data, err := ioutil.ReadAll(reader)
        if err != nil {
                log.Println(proc_name, "Error: E23: ", err)
                return
        }

        a.e2.Text = string(data)
        a.e2.Refresh()
}
```

### Device (please complete the following information):
 - **OS:**  Android
 - **Version:**  Android Version 10
 - **Go version:**   1.15.6
 - **Fyne version:**

**Comment by midu-SA** [comment]
I did some more tests. The bug is not dependent on the characters entered. 
The bug occurs when the file (where data is written to) exists already. It seems that a write operation writes new data at the beginning of an existing file (overwrite mode). However, the existing data (following the written data) is not deleted. Hence, when the file is read, the old data following the written data is already read.

**Comment by midu-SA** [comment]
Misspelling: ...Hence, when the file is read, the old data following the written data is **also** read.

**Comment by midu-SA** [comment]
![Screenshot_20210326-052002](https://user-images.githubusercontent.com/66474515/112576842-666e3500-8df3-11eb-9e2f-cd88633b8f59.jpg)

**Comment by andydotxyz** [comment]
This is now fixed on `develop` and the pending release at `release/v2.0.x` branch - thanks for the helpful steps.
