### ISSUE TITLE
storage.Delete not supported on Android/iOS

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2120]
### Describe the bug:
This bug is related to bug "File-I/O on Android #2118"

In order to create a work around for bug 2118, I tried to delete the existing file before writing the new data to it.
The method "storage.Delete (uri)" produces on Android the error
"operation not supported for this URI"

### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - **OS:**   Android
 - **Version:**   Android 10
 - **Go version:**   1.15.6
 - **Fyne version:**   Develop branch, pre 2.0.2

**Comment by andydotxyz** [comment]
Fixed on develop and cherry-picked for v2.4.5
