### ISSUE TITLE
Can I customize the number of buttons under the dialog?

### ISSUE THREAD

**Issue by smp12345** [fyne-io/fyne#2127]
The default button under the dialog box is 2 or 1, one is OK and the other is cancel. Can I continue to increase the number of buttons?

```
	a := app.New()
	w := a.NewWindow("Hello")

	label := widget.NewLabel("Content")
	label.Alignment = fyne.TextAlignCenter
	dlg:=dialog.NewCustom("Title", "OK", label, w)
	dlg.Show()
	w.ShowAndRun()
```
![button](https://user-images.githubusercontent.com/50661521/112780267-10abbe00-907b-11eb-825f-6c3fd43cbf33.png)

**Comment by andydotxyz** [comment]
The standard dialogs include a standard set of buttons.
We don't really have an API for adding additional buttons at this time, perhaps you can expand on this to indicate what sort of dialog would find this useful? Maybe we can add the functionality to the custom dialog type.

**Comment by smp12345** [comment]
I expect to be able to increase the number of custom Button interfaces, thanks. There are a lot of use scenarios, such as a user registration dialog box to increase the use of user registration, user login, password recovery and many other functions, but currently only button support callback function

**Comment by andydotxyz** [comment]
Perhaps this issue could be re-worked as a feature request that shows how it could be presented?

It may be less trivial than suggested as the "extra" buttons may want to be visually separate from the "standard" ones, which may imply that central positioning is not right going forward...

**Comment by Jacalz** [comment]
We have discussed improving custom dialogs. I will work on that feature and intend to do something about this at the same time.

**Comment by Jacalz** [comment]
I have opened https://github.com/fyne-io/fyne/pull/3703. Feel free to test and see if it suits your use cases.

**Comment by Jacalz** [comment]
I will close this as completed now that the PR has been merged into the `develop` branch.
