### ISSUE TITLE
Container Within Table Cell Doesn’t Show/Hide Properly

### ISSUE THREAD

**Issue by thebenwaters** [fyne-io/fyne#2128]
### Describe the bug:

Currently to be able to support multiple different widgets within a single cell in a table I create a table with a container for each cell, hiding the checkbox (as most cells use text and not a check)

And then in update I do a type switch to check the row/column to show / hide based on it

When scrolling around the table, even though the code is producing the condition as true, the checkbox is visible in the wrong places

### To Reproduce:
Steps to reproduce the behaviour:
1. Implement code above
2. Run with enough data to force table to scroll

### Screenshots:

<img width="1284" alt="Screen Shot 2021-03-31 at 16 55 47" src="https://user-images.githubusercontent.com/696445/113156316-8910ab80-9242-11eb-985f-6f7b6461465c.png">

### Example code:

```go
func (t *internalTransactionTable) createCell() fyne.CanvasObject {
	button := widget.NewCheck("", func(c bool) {
		log.Println("Clicked")
	})
	button.Hide()
	return container.NewMax(widget.NewLabel(""), button)
}
```

```go
func (t *internalTransactionTable) update(location widget.TableCellID, cell fyne.CanvasObject) {
	c := cell.(*fyne.Container)
	for _, obj := range c.Objects {
		switch typedObj := obj.(type) {
		case *widget.Label:
			if location.Row == 0 {
				row, _ := t.headers()
				headers := row[location.Col]
				typedObj.SetText(headers)
			} else {
				row, _ := t.getDataRow(location.Row)
				rowMap := row.GetTransactionAsMap()
				rowOfHeaders, _ := t.headers()
				header := rowOfHeaders[location.Col]
				value := rowMap[header]
				typedObj.SetText(value)
			}
		case *widget.Check:
			row, _ := t.getDataRow(location.Row)
			rowMap := row.GetTransactionAsMap()
			rowOfHeaders, _ := t.headers()
			header := rowOfHeaders[location.Col]
			value := rowMap[header]
			if location.Row > 0 && location.Col == len(rowOfHeaders)-1 {
				log.Println("HERE", location.Row, location.Col, value)
				typedObj.Show()
			}
		}
	}
}
```
https://github.com/thebenwaters/ynab-desktop-importer/blob/v2/transactions.go

### Device (please complete the following information):
 - **OS:**  MacOS
 - **Version:**  10.42
 - **Go version:**  1.16
 - **Fyne version:**  2.0

**Comment by andydotxyz** [comment]
Happy to help, but it is possibly relating to cell reuse and the state not being setup correctly. Could you please post the code for your table? (particularly the `UpdateCell` callback that is used to apply new data to a re-used cell).

**Comment by thebenwaters** [comment]
I’m reworking with the new understanding of the flow of create/update cycle as well as making sure i’m not having state issues ( i have a feeling i’m misusing maps)

**Comment by thebenwaters** [comment]
Fixed,

My state now uses a map with pointers and I update appropriately (ran into issues with loops, maps, and pointers). Also I treat the update function that it doesn’t know the previous state so ensuring that hide/show is called for every “branch”

Thanks for all the help in slack @andydotxyz !!
