### ISSUE TITLE
Two radio options with same text

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#213]
I'm not sure if this is a bug, but if I have two radio buttons that use the same text, selecting one of them will select both options.

While it doesn't make sense to me to have two radio buttons with the same text, I don't think they should both be selected when clicked. This would change the underlying structure of how the Radio widget works. Another option could be to have some validation or extra characters to make it a separate option.

Thoughts?

**Comment by andydotxyz** [comment]
This is a good point. I think the simplest approach would be to de-duplicate the options? Essentially it would mean that identical items would not be displayed and that would resolve this issue?

What do you think?

**Comment by pbarnum** [comment]
I see three solutions to this
1. Creating an underlying struct for the radio button that holds id and value (big refactor but easily extendable in the future)
2. Alter the new radio button's value by adding a number at the end (easier to implement, but now dictates how the programmer's application runs)
3. Prevent it from happening ever, build error and runtime error

I think the first option is the best way to go, but option two is also good *temporarily*. I could make an attempt at this issue.

**Comment by andydotxyz** [comment]
Let's turn it around and think about the user experience. Identical labels won't make sense as they cannot tell which to click. If we append a number it is no longer duplicate but it does not make things clearer for the user.

Unless you can think of situation where this makes sense I think that option 3 is the only suitable solution?

**Comment by pbarnum** [comment]
When you put it that way, option 3 does make the most sense. Thanks for pointing that out!
