### ISSUE TITLE
container: Tab animation is too slow vertically and starts too high

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2135]
### Describe the bug:

I initially noted this in wormhole-gui when using the mobile branch. There I see that the tab animation starts way too high on the screen an then  slowly falls down to where it should be. That happens a bit too fast in the code example below to be noticeable enough, but it can be seen when resizing the window (the animation var does not stay with the tab).

### To Reproduce:
Steps to reproduce the behaviour:
1. Resize window with tab bar at the bottom
2. Or: Start application with tab bar at the bottom.

### Screenshots:

The refresh rate on the gif is a bit too slow to see the full effect:
![falling-tabs](https://user-images.githubusercontent.com/25466657/113512366-a4422a80-9564-11eb-9c5d-289c0ebeb776.gif)

The example code resizing:
![falling-tabs-example](https://user-images.githubusercontent.com/25466657/113512420-db184080-9564-11eb-8465-384006005006.gif)

### Example code:
```go
// Package main loads a very basic Hello World graphical application.
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	tabs := container.NewAppTabs(container.NewTabItem("Test", hello))
	tabs.SetTabLocation(container.TabLocationBottom)

	w.SetContent(tabs)
	w.Resize(fyne.NewSize(200, 600))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.11.9
 - **Go version:** 1.16.2
 - **Fyne version:** 2.0.2

**Comment by andydotxyz** [comment]
On `release/v2.0.x` for testing
