### ISSUE TITLE
Dialog with a callback function and only one "Confirm" button

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2138]
### Is your feature request related to a problem? Please describe:

Sometimes it is necessary to let the user confirm something and execute some code after the confirmation is done.
However the ShowInformation dialog does not provide a callback. 
You could use the ShowConfirm dialog, however there are 2 buttons (No and Yes). For my use case, a single button would be sufficient.

The following figure shows the use case: https://github.com/midu-SA/Taskmgr/blob/main/screenshots/Taskmgr-Sync-Tab.png
The user shall confirm the success. Afterwards some more code is executed in the callback.

### Is it possible to construct a solution with the existing API?
Not that I'm aware of.

### Describe the solution you'd like to see:
Either a new dialog with a callback and a sinlge button. Preferred if even the button text could be provided in the method.

Alternatively an extension of the ShowConfirm dialog, where both button strings can be provided. If one string is empty, the button is not shown.

**Comment by fpabl0** [comment]
The current API let you create custom "dialogs" by using `widget.PopUp`:
```go
modal = widget.NewModalPopUp(content, win.Canvas())
modal.Show()
```
`content` is a `CanvasObject` so you can use any container and any widget, for example you can have `Button` and then add the action you need in the OnTapped callback.
Would this be enough for your use case?

**Comment by andydotxyz** [comment]
The `Information` does provide a callback - you can set `OnClosed` if you use `NewInformation` and `Show` instead

**Comment by midu-SA** [comment]
Thanks for the replys. I found the corresponding API description. Great.
So pls close the issue.
