### ISSUE TITLE
No keyboard popup on Android in disabled Entry Widget

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2139]
### Is your feature request related to a problem? Please describe:
My app shows a long help text in a new window, containing a MultiLineEntry widget within a scroll container. Because the text shall not be changeable, the entry widget is disabled.
On an Android phone it is almost impossible to grab the scrollbar and scroll the help text. Instead, with every touch (try) to get the narrow scrollbar, the keyboard pops up.
There is no need to let the keyboard pop up if the widget is disabled.

### Is it possible to construct a solution with the existing API?
not that I'm aware of

### Describe the solution you'd like to see:
If possible on Android, popup of the keyboard should be prevented (or possible to prevent) for a disabled Entry widget.

**Comment by fpabl0** [comment]
Thanks for reporting this.

**Comment by andydotxyz** [comment]
On develop for testing

**Comment by midu-SA** [comment]
I retried today and it works in my Taskmgr app :-)
Great!
Thanks!

**Comment by andydotxyz** [comment]
This is now on `release/v2.0.x` ready for `v2.0.3` release
