### ISSUE TITLE
Resize of file selection dialog

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2144]
I checked a few open issues, but could not find one desribing my point. Sorry, if I missed it and the issue is doubled.

### Is your feature request related to a problem? Please describe:
Attached are two figures. The smaller window shows the windows size when the app is started. If a file dialog is opened, it has the same width. If the window size is increased and the file dialog again is opened, it still has the same size.

On large screens it should be possible to have a bigger file selection dialog bigger.
The file selection dialog always has the size of the app window when it was started. 
Increasing the window size afterwards is possible, however, if then a file dialog is opened, it still has the original small size.

### Is it possible to construct a solution with the existing API?
I do not know (and would be happy if there is an easy solution)

### Describe the solution you'd like to see:
I'd like to have the file selection dialog have the same size (or at least same width or same heigth) as the window has, when the file selection dialog is opened.

![Screenshot_1](https://user-images.githubusercontent.com/66474515/113826279-43903900-9782-11eb-976a-fee733c09f85.png)
![Screenshot_2](https://user-images.githubusercontent.com/66474515/113826281-4428cf80-9782-11eb-805d-af7c60b13b24.png)

**Comment by andydotxyz** [comment]
Dialogs normally are displayed at their minimum size. When we added file dialogs we made them a little larger, with the ability to shrink a certain amount if the window was too small.
Obviously we don't want their default size to be full-window but you can ask it to be larger in your code.

```go
d := dialog.NewFileDialog(...)
d.Resize(...)
d.Show()
```

In this way it will try to be as big as you asked instead of the standard size.

**Comment by andydotxyz** [comment]
I think this may be a duplicate of #1212

**Comment by midu-SA** [comment]
Great, your code snipplet helped. Thanks!
