### ISSUE TITLE
FolderOpen Dialog crashes app when Cancel is pressed

### ISSUE THREAD

**Issue by metal3d** [fyne-io/fyne#2145]
### Describe the bug:

Pressing "cancel" button in a directory dialog crashed the application:

```
2021/04/07 13:18:34 Fyne error:  Getting favorite locations
2021/04/07 13:18:34   Cause: uri is not listable
2021/04/07 13:18:34   At: /home/metal3d/.local/share/go/pkg/mod/fyne.io/fyne/v2@v2.0.2-0.20210406102126-59234e585db7/dialog/file.go:218
```

### To Reproduce:

```go
	selectFolderButton := widget.NewButton("Select target folder", func() {
		dialog.NewFolderOpen(func(dir fyne.ListableURI, err error) {
			if err == nil && dir.Name() != "" {
			   fmt.Println(dir.Name())
			}
		}, win).Show()
	})
```

### Screenshots:

![fyne-crash](https://user-images.githubusercontent.com/100080/113858731-5ca9e180-97a4-11eb-858a-31429449f51a.png)

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Fedora 33
 - **Go version:** go1.15.8 linux/amd64
 - **Fyne version:** fyne.io/fyne/v2 v2.0.2-0.20210406102126-59234e585db7

**Comment by Jacalz** [comment]
You are not checking if directory is `nil`. I am pretty sure that it is the source of the crash. I would do something like this (though you might want to handle the error separate from `dir == nil` if you want to log it).
```go
	selectFolderButton := widget.NewButton("Select target folder", func() {
		dialog.NewFolderOpen(func(dir fyne.ListableURI, err error) {
			if dir == nil || err != nil {
                           return
			}
			
			fmt.Println(dir.Name())
		}, win).Show()
	})
```
The error pasted at the top of the issues does not seem to be connected to the crash and I also can’t see it being printed in the gif.

**Comment by Jacalz** [comment]
The error that is printed looks more like it stems from it not being able to find your favorite locations. Can you share the full path to your downloads folder?

**Comment by andydotxyz** [comment]
I think that the error log does not match the crash reason.
I agree with @Jacalz that there is a missing `nil` check in your code - dialogs are called with a nil response if cancelled.

**Comment by metal3d** [comment]
OK, check if "dir" is nil fixed the problem. But... that's a bit confusing, I expected that "err" was not nil or dir.Name() was empty in case of canceling.
I can close the issue, or maybe you want to reopen if you feel that something can be enhanced.

Thanks to all of you 😄
