### ISSUE TITLE
more 2D Graphics canvas support 

### ISSUE THREAD

**Issue by chewie54** [fyne-io/fyne#2146]
I asked a long time ago for more 2d graphics support.
 
- Dashed lines
- Polygons with fills
- text with subscripts and superscripts
- Bezier curves

Any chance these can be added in the future?

Thanks,
Dan

**Comment by andydotxyz** [comment]
I gues this is just an addition to #856, comments moved to there so we can track it with a single issue.
All of these could be added in the future, and contributions are welcome :).

**Comment by andydotxyz** [comment]
Closing in preference of the earlier request issue
