### ISSUE TITLE
Dynamic Menus

### ISSUE THREAD

**Issue by Serverfrog** [fyne-io/fyne#2147]
### Is your feature request related to a problem? Please describe:
We have the Possibility to use Bindings to change dynamically the, except the Menu and MenuItem's.
These have only have a initial Value for Label's and after that no Possibility to change without recreating the Structure of the Application (Window or restarting the application)

### Is it possible to construct a solution with the existing API?
I'm not sure how in the back end it is possible to rerender Item's but due to the fact that the widget.* Components have the possibility it should not be impossible to do.

### Describe the solution you'd like to see:
This could be in two ways.

- The "WidgetWay" with `fyne.NewMenuItem()` and `fyne.NewMenuItemWithData`
- a Method where someone can Change the Label and its rerender then handled there `SetTitle()`

**Comment by andydotxyz** [comment]
I think a lower impact change would be to use the current structures but to support re-reading the changes.
Perhaps `fyne.Menu.Refresh()` would do this, but we have to reflect in our internal menu as well as the macOS native ones.
