### ISSUE TITLE
how to change the theme from light to dark

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/fyne#2149]
how to change the theme from light to dark can you please let me know
### Describe the bug:

i am facing a issue like i am not getting how to change the theme from light to dark it is for a dekstop application.

### To Reproduce:
Steps to reproduce the behaviour:
1. please show me for the below code.

### Device (please complete the following information):
 - **OS:** 10.15.5
 - **Version:**  catalina
 - **Go version:** 1.14.1
 - **Fyne version:** 1.4.3

**Comment by andydotxyz** [comment]
The light/dark theme selection is a user preference that defaults to the OS settings if it can be dectected.
User can override by setting `FYNE_THEME` environment or by running the `fyne_settings` application to edit their preferences.
For example https://developer.fyne.io/started/firstapp

**Comment by rajkumarks7** [comment]
when i do FYNE_THEME=dark it is not working getting the same  i tryed it in the terminal.
please can you help me out.

**Comment by andydotxyz** [comment]
You will have to share more information about what you did. Try copying the whole commands in. That should work everywhere.

**Comment by rajkumarks7** [comment]
below are the commands i have used
1)" go run ./ FYNE_THEME=dark"
2) "FYNE_THEME=dark"

**Comment by rajkumarks7** [comment]
got it thank you for your help.

**Comment by rajkumarks7** [comment]
1)" export FYNE_THEME=dark"
2) "go build ./ "
getting same light theme when i use the above sequence.

**Comment by andydotxyz** [comment]
Those are build steps, the user configuration is read at runtime.

**Comment by rajkumarks7** [comment]
yes i am build the application it should relfect in the build right when i export to dark ?. i am not getting this one.
it is working fine when i do "go run ./"

**Comment by andydotxyz** [comment]
User prefences are not baked into the application.
Are you trying to force the end user to not be able to choose - you want your app to ignore their preferences?

**Comment by rajkumarks7** [comment]
yes

**Comment by rajkumarks7** [comment]
like i want to set dark theme for my build file
how can i achive it?

**Comment by andydotxyz** [comment]
If you really want to break the ability for users to have a preference then you can use `App.Settings().SetTheme(theme.DarkTheme())`.

**Comment by rajkumarks7** [comment]
in the code ? directly 
can you explain me with a example. sorry for asking these many questions

**Comment by rajkumarks7** [comment]
got it thank you for your help.
