### ISSUE TITLE
KeyEnd desired outcome for text input is not what's expected

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#215]
It seems when you enter the `KeyEnd` input, it moves the cursor to an incorrect value. It instead should send the cursor to the current row's length.

Generated via https://github.com/fyne-io/fyne/pull/214#issuecomment-480570976

**Comment by paulhovey** [comment]
Can you check this against the devlelop branch?  I think I fixed this in https://github.com/fyne-io/fyne/pull/195/files#diff-d24fdc118a436633c817dd7891922b6bR318 :)

**Comment by pbarnum** [comment]
You're right, thanks for pointing that out in #213!
