### ISSUE TITLE
requirements for target platforms

### ISSUE THREAD

**Issue by Gys** [fyne-io/fyne#2154]
I compiled an app on macOS Big Sur to use on another MacBook. The resulting app could not run on that machine because `You can't use this version of the application "MyApp" with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later."`.

I tried to lookup here and in the docs what minimum OS versions are supported for each platform, but could not find anything. It would be useful if that was more clear. If I missed it, I looked for 'target', 'platform' and 'requirements'.

In case this depends on certain libraries, meaning that if omitted a lower OS version would be supported, then that info would also be very helpful.

**Comment by andydotxyz** [comment]
You did not say how your app was built...

calling “fyne package” should have created a .app package that is portable to older macOS versions.

**Comment by Gys** [comment]
Sorry, I just wrote 'compiled' but I indeed called `fyne package` to create a '.app'. Strange. So you mean the app should run on macOS 10.15.7?

**Comment by andydotxyz** [comment]
Yes, it should work back to 10.11

**Comment by Jacalz** [comment]
Were you by any chance using an M1 MacBook?

**Comment by Gys** [comment]
No, it was an old MacBook Air from 2012. I can access it again in a week or so and will try again with a hello world app.

**Comment by andydotxyz** [comment]
It would be good to get the spec for the macbook if possible.
I'm not sure if all of those produced were 64 bit or not...

**Comment by Gys** [comment]
I found what is happening.

Delete the files `myapp` and `myapp.app`.
Build a new version doing `go build` and then `fyne package`.
Move the resulting myapp.app to the Macbook Air.
The app now shows a 'no access' image on top of its icon and double click triggers the message `You can't use this version of the application "MyApp" with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later."`. 

Delete the files `myapp` and `myapp.app`.
Build a new version *only* doing `fyne package`.
Move the resulting myapp.app to the Macbook Air.
The app works as expected.

Fyne: cli v2.0.0
Go: go1.16.3 darwin/amd64
Build machine is Macbook Pro: hardware version 2018, macOS 11.2.1
Target machine is Macbook Air: hardware version mid-2012, macOS 10.15.7 (latest for this hardware).

The myapp.app works locally (Macbook Pro) always as expected. The difference (using `go build`) is only relevant when copying the app to the Macbook Air.

**Comment by andydotxyz** [comment]
Do not run `go build` before `fyne pckage`. If the executable is already built then the build flags we know how to set will not be applied because it’s already compiled.

**Comment by Gys** [comment]
Is that documented? The book says:
“Before packaging, it is a good idea to confirm that your application builds successfully using the go build command. When your app is ready, simply execute the fyne package command and it will process your app and metadata to create the platform-appropriate output.”

Then again, I should probably have used `fyne release` to build a version for another computer? I did not test, but maybe using `go build` and then `fyne release` might work?

BTW, it seems possible to check which flags were used to build a Go executable. I found this: https://stackoverflow.com/questions/44148449/how-to-check-whether-golang-binary-is-compiled-with-ldflags-s-w/44168916
Might be something to consider adding to the fyne cli.

**Comment by andydotxyz** [comment]
I don’t know what checking the parameters would help with? We’ve made the assumption that someone building the exe instead of letting Fyne do it for them has done so for a reason.

Can you please say which section of which book you are using? These things move on and we may need to make an errata.

**Comment by Gys** [comment]
> We’ve made the assumption that someone building the exe instead of letting Fyne do it for them has done so for a reason.

Yes, the reason is to check if the exe builds correctly ;-)

Checking for specific build flags could help to see if the exe was compiled with the correct build flags. As per your previous comment, specific build flags are applied for packaging. If the fyne cli would give a message explaining specific build tags are needed then I would know its relevancy.

The citation is from Chapter 9 -> Packaging applications (desktop and mobile) -> Packaging for your current computer

**Comment by andydotxyz** [comment]
You’re right that is misleading sorry. The command used to be less capable and that page should have been updated. 
I’ll try and put an errata on the book page.

**Comment by andydotxyz** [comment]
I opened #2203 PR when I realised that we could assume that found exe files that were not manually specified could be overwritten. This should fix the issue so the book examples work correctly.

**Comment by Jacalz** [comment]
Has this been resolved already? Can we close it?

**Comment by andydotxyz** [comment]
Yes I think I should have closed this ages ago, good catch.
