### ISSUE TITLE
Entry widget showing big file is extremly slow

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2163]
Sorry if I missed a similar issue, could not find one in open issues

### Is your feature request related to a problem? Please describe:
Tested with 2.0.2 and develop branch (12.04.2021)

I'm showing the content of a text file in an disabled entry widget, which is embedded in a scroll container. If the file is big (approx. 80.000 bytes or more, approx. 1500 lines), scrolling is very slow. I can move the pressed mouse (holding the scrollbar) down quickly, but the scrollbar follows slowly, with each move updating the content in the entry widget.

### Is it possible to construct a solution with the existing API?
No idea

### Describe the solution you'd like to see:
I don't know how it is implemented today... Maybe some of the following ideas are already in ...
- Is it possible to implement some caching as done for big lists and tables?
- Is it possible not to update the content of the entry widget for each moved position if the scrollbar, if it can be detected that the scrollbar has moved futher down (or up) already?
- Maybe add a small timer (few msecs) and wait: than take the position of the scrollbar and update the content according to the current position of the scrollbar.
- if there is a callback called when the scrollbar is moved: can this callback check if the scrollbar has moved further in between and fetch the new position?

**Comment by andydotxyz** [comment]
Part of the next release will be to speed up large text areas.
However to be able to make use of these improvements you will need to remove the scroll container you have manually added.
You have not reported fyne version or any other details (please use bug report template in the future).
Ensure that you are using Fyne v2.0.2 and the Entry will provide the scroller.

**Comment by midu-SA** [comment]
Yes, its in: first line: Tested with 2.0.2 and develop branch (12.04.2021)

**Comment by midu-SA** [comment]
Oh, I did not know if it was a bug. Therefore I wrote this as an issue ;-)

**Comment by andydotxyz** [comment]
Thanks for the clarification.
Can you please remove the extra scroll container that you added and report back if things change.

**Comment by midu-SA** [comment]
I removed it. A bit better, but still slow, if the file is big.

P. S.
I did not know that the Entry widget has its own scroll functionality and removed the scroll container also in the sync tab of my TaskMgr app. Just commit to github. Thanks for the hint!

**Comment by andydotxyz** [comment]
I'm glad it helped a bit.
The real fix will be in 2.1 as it requires a lot of work still. We are stating to plan how to optimise  text rendering this week - then development will begin on it.
I would expect we have something to test in around 1 month.
Sorry for the delay bit this is a very complex topic.
And it will enable a rich text widget once done correctly :)

**Comment by midu-SA** [comment]
Great, thanks. 
Not a big issue right now. 
Looking forward to the next release then ...
