### ISSUE TITLE
NewFolderOpen: incomplete filenames

### ISSUE THREAD

**Issue by midu-SA** [fyne-io/fyne#2165]
Sorry, if this is a double. I still do not know how to search efiiciently in open issues :-(
Also, it is not a bug. But behaviour could be improved.

### Is your feature request related to a problem? Please describe:
Tested with Fyne develop branch (12.04.21) on Linux (screen is big enough)

Use dialog.NewFolderOpen resp. dialog.ShowFolderOpen. 
If filenames are a bit longer, you cannot distinguish the files (directory icons and beginning of filenames are identical). 
See screenshot

### Is it possible to construct a solution with the existing API?

No. Increasing the dialog window does not help.

### Describe the solution you'd like to see:

Proposal: 
Add another option to show "filenames only" instead of "icon plus filename". If this option is used, a  list shows the filenames under each other (with a scrollbar if there are many). This gives more space for the filenames (almost the width of the dialog).

The user can switch the view via the options if the filenames are too long for the current view.

![Screenshot_incomplete_filenames](https://user-images.githubusercontent.com/66474515/114430086-59589080-9bbe-11eb-9fef-b40eed85a5ae.png)

**Comment by andydotxyz** [comment]
Let's look at wrapping at least to a second line to get more on.
Also likely need ellipsis to show incomplete render

**Comment by andydotxyz** [comment]
Working on `develop` branch now :)
