### ISSUE TITLE
List item elements are sometimes wrongly rendered left-aligned when scrolling

### ISSUE THREAD

**Issue by doingodswork** [fyne-io/fyne#2172]
### Describe the bug:

When creating a simple list with some left and some right-aligned elements (thanks to a separator in the middle), and then scrolling through the list, sometimes the right-aligned elements are rendered left-aligned, basically overlapping the existing ones. This appears and disappears while scrolling, so it also leads to kind of a flickering.

### To Reproduce:
Steps to reproduce the behaviour:
1. Use the example code below
2. Scroll

### Screenshots:

![image](https://user-images.githubusercontent.com/60071482/114769817-f821f000-9d6a-11eb-916f-454d981129fa.png)

### Example code:

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Flickering list")
	w.Resize(fyne.NewSize(400, 300))

	length := func() int { return 100 }
	createItem := func() fyne.CanvasObject {
		return container.NewHBox(widget.NewLabel("Left"), layout.NewSpacer(), widget.NewLabel("Right"))
	}
	updateItem := func(i int, obj fyne.CanvasObject) {
		obj.(*fyne.Container).Objects[0] = widget.NewLabel("Left" + fmt.Sprintf("%v", i))
		obj.(*fyne.Container).Objects[2] = widget.NewLabel("Right" + fmt.Sprintf("%v", i))
	}
	list := widget.NewList(length, createItem, updateItem)

	w.SetContent(list)
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows 
 - **Version:** 10 
 - **Go version:** 1.16.2 
 - **Fyne version:** 2.0.2

**Comment by andydotxyz** [comment]
Your `update` callback is not correct. The objects that you are adding will float around as they are not in the container layout you have specified.
Instead of `NewLabel` use `label.SetText` and your code will work fine.

**Comment by fpabl0** [comment]
As @andydotxyz said, the right way to do it is:
```go
updateItem := func(i int, obj fyne.CanvasObject) {
	cont := obj.(*fyne.Container)
	cont.Objects[0].(*widget.Label).SetText("Left" + fmt.Sprintf("%v", i))
	cont.Objects[2].(*widget.Label).SetText("Right" + fmt.Sprintf("%v", i))
}
```
In that way, you will get the right behavior and you are not creating labels multiple times.
Your first code can work just by adding:
```go
updateItem := func(i int, obj fyne.CanvasObject) {
	obj.(*fyne.Container).Objects[0] = widget.NewLabel("Left" + fmt.Sprintf("%v", i))
	obj.(*fyne.Container).Objects[2] = widget.NewLabel("Right" + fmt.Sprintf("%v", i))
        obj.Refresh() // added
}
```
**BUT** you will waste (unnecessarily) lot of ram, and you would not be benefited from the caching feature of the `widget.List`.

**Comment by doingodswork** [comment]
Thanks both of you, it works great with `SetText` (and similar calls for other widgets)! I missed that somehow.

Closing the issue.
