### ISSUE TITLE
theme color exception

### ISSUE THREAD

**Issue by HZHgagaga** [fyne-io/fyne#2176]
### Describe the bug:
This code is implemented Theme interface, and  it uses DarkTheme().Color(n, v) , but it's always show lightTheme on my system, and It's normal when I use v1 fyne.
```go
func (*myTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return theme.DarkTheme().Color(n, v)
}
```

### Screenshots:
![image](https://user-images.githubusercontent.com/39078600/114880630-cd9c6980-9e34-11eb-88ad-f8066ac5cefa.png)

### Example code:
https://github.com/lusingander/fyne-font-example

 - **OS:** Windows10
 - **Go version:** 1.13
 - **Fyne version:** v2.0.2

**Comment by andydotxyz** [comment]
This is strange, have you implemented all of the theme methods and called `App.Settings().SetTheme(&myTheme{})`?

**Comment by HZHgagaga** [comment]
> 这很奇怪，您实现了所有主题方法并调用了`App.Settings().SetTheme(&myTheme{})`吗？


I'm quite sure
I used this code verification
```go
type myTheme struct{}

var _ fyne.Theme = (*myTheme)(nil)

// return bundled font resource
func (*myTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return theme.DarkTheme().Font(s)
	}
	if s.Bold {
		if s.Italic {
			return theme.DarkTheme().Font(s)
		}
		return resourceMplus1cBoldTtf
	}
	if s.Italic {
		return theme.DarkTheme().Font(s)
	}
	return resourceMplus1cRegularTtf
}

func (*myTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return theme.DarkTheme().Color(n, v)
}

func (*myTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DarkTheme().Icon(n)
}

func (*myTheme) Size(n fyne.ThemeSizeName) float32 {
	return theme.DarkTheme().Size(n)
}

```

if I use App.Settings().SetTheme(theme.DarkTheme()), the color display is normal.
if I use App.Settings().SetTheme(&myTheme{}), the black theme is invalid.

**Comment by fpabl0** [comment]
@HZHgagaga themes (by default) always use the user preference variant (light or dark). If you want to force a variant (ignoring user preference), then you could do:
```go
func (*myTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(n, theme.VariantDark) // 👈 force dark variant
}
```
`theme.DarkTheme()` and `theme.LightTheme()` force this behavior only if you passed them directly to the `SetTheme` function as you already noted.
Using `theme.DarkTheme().Color(n, theme.VariantDark)` you will have the same result, but it is quite confusing, so I would recommend to use `theme.DefaultTheme()` instead as it is more clear.

**Comment by HZHgagaga** [comment]
> @HZHgagaga themes (by default) always use the user preference variant (light or dark). If you want to force a variant (ignoring user preference), then you could do:
> 
> ```go
> func (*myTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
> 	return theme.DefaultTheme().Color(n, theme.VariantDark) // 👈 force dark variant
> }
> ```
> 
> `theme.DarkTheme()` and `theme.LightTheme()` force this behavior only if you pass them directly to the `SetTheme` function as you already noted.
> Using `theme.DarkTheme().Color(n, theme.VariantDark)` you will have the same result, but it is quite confusing, so I would recommend to use `theme.DefaultTheme()` instead as it is more clear.

It's been successful. Thank you very much
