### ISSUE TITLE
How to theme window title bar?

### ISSUE THREAD

**Issue by kitepad** [fyne-io/fyne#2184]
Select dark theme, but window title bar is not themed. My OS (win 10) system theme is dark mode.

### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** Enterprise build 19042
 - **Go version:** 1.16
 - **Fyne version:** 2.0.2

**Comment by Jacalz** [comment]
Could you please fill out all of the issue template? Using the issue template makes it much easier for us to understand, diagnose, and try to resolve the issues.

**Comment by kitepad** [comment]
OS: Win 10
Version: Enterprise build 19042
Go version: 1.16
Fyne version: 2.0.2

Open fyne_demo.exe, and select Dark theme, but window's title bar is not themed. 
My expectation is window title bar should be colored as black. I know some gui toolkit can set color for window's title bar background, some not. I cann't find document about this in fyne, can I don't know is fyne design constraint or bug. If fyne can change title bar's background, pls give me some advice.

Below is image:
![image](https://user-images.githubusercontent.com/28701482/115203323-eacd8280-a129-11eb-949e-d2bc58204709.png)

**Comment by andydotxyz** [comment]
This  should happen automatically, I wonder if it is something to do with how we are setting up the Window.
With your OS in dark mode can you please confirm what other windows with a standard border look like? (For example the command prompt app or powershell)?

**Comment by kitepad** [comment]
My os setting is dark mode, and command prompt and powershell window are rendered in dark mode. Like this :
![image](https://user-images.githubusercontent.com/28701482/115323439-b950c780-a1ba-11eb-9b86-f91d14f0c1a2.png)

**Comment by Jacalz** [comment]
I checked and I am seeing the same thing on my Windows 10 machine. Dark or light theme has no difference.
![image](https://user-images.githubusercontent.com/25466657/115359958-73e2c900-a1bf-11eb-859e-943727ea174f.png)

**Comment by RustamGamidov** [comment]
Here is a small app that can be an investigation starting point: https://github.com/ysc3839/win32-darkmode
See `RefreshTitleBarThemeColor` in the `DarkMode.h`
I suppose it should be done somewhere at glfw level but could be a local workaround as well

**Comment by Jacalz** [comment]
A permalink to that for ease of discover: https://github.com/ysc3839/win32-darkmode/blob/cc26549b65b25d6f3168a80238792545bd401271/win32-darkmode/DarkMode.h#L107-L123

**Comment by kitepad** [comment]
I know win32-darkmode, but I don't have good idea to integrate with fyne and ensure don't break fyne design principle.
It's better if fyne have native support for this.

**Comment by andydotxyz** [comment]
Thanks for all of these hints, it is such a shame this doesn't just work.
Let's try and pull something into the next release.

**Comment by RustamGamidov** [comment]
Looks like there's no pure c++ API  to handle this and _win32-darkmode_ is not able to do what it states at least on my PC (win10 20H2 build 19042.928) and i see other oldschool apps like notepad++ q-dir, conemu are using white titlebar. 

There's quite common workaround though. It's possible to create headless windows and draw titlebar at the toolkit level, basically a toolbar. This way is safer than the _https://docs.microsoft.com/en-us/windows/win32/gdi/wm-ncpaint_ handling.

**Comment by kitepad** [comment]
Maybe DWM api is best. This sample use dwm api to draw title bar.
https://stackoverflow.com/questions/40017484/an-aero-caption-title-bar-issue-using-dwm-api-on-the-windows-10
https://docs.microsoft.com/en-us/windows/win32/dwm/customframe

**Comment by RustamGamidov** [comment]
Yes, DWM is pretty similar to the NCPaint approach and it allows to extend the titlebar but the main problem is the consistency. I can draw custom colors for the title but there are window buttons and they are not redrawn. They can look differently basing on Windows OS setup and version.

Maybe i'm wrong but i believe to achieve the goal the whole window controls set should be recreated. The question is where:
 1. fragile winapi code in glfw + to convince glfw to accept that PR
 2. same fragile winapi code but with winapi hooks in the fyne
 3. frameless window with fyne toolbar that mimics window controls set
The third one looks like easier to implement and more flexible

**Comment by andydotxyz** [comment]
Our solution needs to look and behave identically to the system title bars.
I really hope that there is a better workaround than re-drawing the whole thing. 
Is it possible that we are missing something more obvious?

**Comment by RustamGamidov** [comment]
It's always possible that something is missing and i'm not an expert there so could be wrong so i would treat that as my vision. I'm basing on the several items:
 - 'dark mode is not for win32 apps but for UWP only' is quiet often met during googling
 - numerous apps are drawing their own controls instead of using winapi (firefox, vivaldi broser, sublime-text,...)
 - pre-wpf win32 styling toolkits were replacing whole framesets

**Comment by kitepad** [comment]
I have tested some win32 sdk approach.  In my win32 c++ app my choice is : Create main window without caption, and create theme-able title bar control to replace system title bar even I need to implement mouse drag, window resize and system menu.

**Comment by RustamGamidov** [comment]
That's what i mean. And in my version of reality it's much easier and flexible to do this using fyne controls and this trick:
https://stackoverflow.com/questions/33052651/glfw-how-to-drag-undecorated-window

**Comment by andydotxyz** [comment]
That PR should fix the problem for WIndows 10 users, please let me know if it works for you :)

**Comment by kitepad** [comment]
I tested it. It's work, but can not switch back to light in time, I have to restart it after I changed demo settings.

**Comment by andydotxyz** [comment]
Unfortunately we do not yet have a way to be told when the operating system theme changes.

**Comment by andydotxyz** [comment]
Marking as closed as the dark mode fix is in `release/v2.0.x` ready for 2.0.4
