### ISSUE TITLE
The font has been set, but textgrid still encodes incorrectly

### ISSUE THREAD

**Issue by ErosHel** [fyne-io/fyne#2186]
### Describe the bug:

The font has been set separately. Other widget fonts are normal, only textgrid error

### Screenshots:

![image](https://user-images.githubusercontent.com/34891860/115368555-c50fae80-a1f9-11eb-9b35-73f5a53a2a22.png)

### Example code:
```go
widget.NewTextGridFromString("一二三")
```

### Device (please complete the following information):
 - **OS:** MacOS m1
 - **Version:** 11.3
 - **Go version:** 1.16.3
 - **Fyne version:** 2.0.2

**Comment by andydotxyz** [comment]
Please confirm how the font has been set
