### ISSUE TITLE
zsh: command not found: fyne

### ISSUE THREAD

**Issue by surendrakandel** [fyne-io/fyne#2191]
### Describe the bug:
fyne command is not working 

### To Reproduce:
Steps to reproduce the behaviour:
1.  go get -u fyne.io/fyne/v2/cmd/fyne

### Screenshots:
$ fyne
zsh: command not found: fyne

### Device (please complete the following information):
 - **OS:** macOS Big Sur
 - **Version:** 11.2.3
 - **Go version:** go1.16.3 darwin/amd64
 - **Fyne version:** 2

**Comment by Jacalz** [comment]
Have you set $GOPATH/bin to your path so that the operation system is aware of the binary? https://github.com/golang/go/wiki/SettingGOPATH#zsh

**Comment by Jacalz** [comment]
Closing this due to lack of answer. I think my previous comment explains why this most likely isn’t an issue with Fyne.

**Comment by wobsoriano** [comment]
it is assumed to be `$HOME/go` on Unix systems btw

**Comment by Jacalz** [comment]
Indeed. This simply isn't an issue with Fyne (regardless of all the thumbs down on my previous comment). See https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit for more information.

**Comment by Jacalz** [comment]
Btw, feel free to reopen if you don't agree with me. That should have been in my initial comment when I closed this.
