### ISSUE TITLE
Moving canvas items (e.g. Images) does not cause canvas repaint

### ISSUE THREAD

**Issue by pwiecz** [fyne-io/fyne#2205]
### Describe the bug:
Calling `Move` on a canvas item such as `canvas.Image` does not cause canvas to automatically repaint.
Actually there does not seem to be a clean way to just cause canvas to repaint, without recreating the underlying canvas objects
(e.g. calling `image.Refresh` will also recreate the texture created from the image which may be costly).

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a custom widget with a `canvas.Image` as one or several of its constituent objects
2. Add a `Dragged()` method which moves the widget's images, but does not call Refresh on them.
3. Run the app, and try to drag the image.
4. Nothing happens, expected the images to move.

### Example code:
```go
package main

import (
	"image"
	"image/color"
	"image/draw"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
)

type testWidget struct {
	widget.BaseWidget
	background *canvas.Rectangle
	images     []*canvas.Image
	objects    []fyne.CanvasObject
}

func NewTestWidget() *testWidget {
	w := &testWidget{}
	w.ExtendBaseWidget(w)
	w.background = canvas.NewRectangle(color.White)
	img := image.NewNRGBA(image.Rect(0, 0, 256, 256))
	draw.Draw(img, img.Bounds(), &image.Uniform{color.Black}, image.ZP, draw.Src)

	w.objects = []fyne.CanvasObject{w.background}
	for ix := 0; ix < 16; ix++ {
		cImg := canvas.NewImageFromImage(img)
		cImg.Move(fyne.Position{float32((ix % 4) * 257), float32((ix / 4) * 257)})
		cImg.Resize(fyne.Size{256, 256})
		w.images = append(w.images, cImg)
		w.objects = append(w.objects, cImg)
	}
	return w
}
func (w *testWidget) CreateRenderer() fyne.WidgetRenderer { return w }
func (w *testWidget) Layout(size fyne.Size)               { w.background.Resize(size) }
func (w *testWidget) MinSize() fyne.Size                  { return fyne.Size{800, 600} }
func (w *testWidget) Refresh()                            {}
func (w *testWidget) Objects() []fyne.CanvasObject        { return w.objects }
func (w *testWidget) Destroy()                            {}
func (w *testWidget) Dragged(event *fyne.DragEvent) {
	dx, dy := event.Dragged.DX, event.Dragged.DY
	for _, img := range w.images {
		position := img.Position()
		img.Move(fyne.Position{position.X + dx, position.Y + dy})
		// img.Refresh() // uncommenting this line makes animation junky
	}
	// w.background.Refresh() // uncommenting this line seems to work, but seems hacky
}
func (w *testWidget) DragEnd() {}

func main() {
	a := app.New()
	w := a.NewWindow("Test dragging")
	w.SetContent(NewTestWidget())
	w.ShowAndRun()
}
```
-->

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.4.0
 - **Go version:** 1.16.2
 - **Fyne version:** 2.0.2

**Comment by andydotxyz** [comment]
Thanks for this, I think perhaps we should add a flag to the canvas that repaint should be done after a Move call (Resize triggers other repaint events).

**Comment by fpabl0** [comment]
Maybe should be enough having this (after sharing code between the two drivers):

`canvas/base.go:`
```go
// Repaint repaints the containing canvas.
func Repaint(obj fyne.CanvasObject) {
	if fyne.CurrentApp() == nil || fyne.CurrentApp().Driver() == nil {
		return
	}

	c := fyne.CurrentApp().Driver().CanvasForObject(obj)
	if c != nil {
		c.(interface{ SetDirty(bool) }).SetDirty(true)
	}
}
```

And then just call this in canvasobject.Move and in BaseWidget implementation.

**Comment by andydotxyz** [comment]
I think if there were to be a `canvas.Repaint` it would be for a `Canvas` parameter not `CanvasObject`.
Then we could have the rest of the helper (looking up the canvas) as a private bit of code in the package.

**Comment by andydotxyz** [comment]
This needs to be in 2.2 as we don't add API in fixes sorry for the confusion

**Comment by andydotxyz** [comment]
Working on it now. Should not have been moved to a point release sadly as noted above due to new api requirement.

**Comment by andydotxyz** [comment]
Thanks to the suggestion by @fpabl0 there is a version of this fix without a new API, so trying to get it in to next point release.
