### ISSUE TITLE
compile error in windows environment

### ISSUE THREAD

**Issue by consititine** [fyne-io/fyne#2211]
### bug descripbe
I try to to run the demo on my windows10 enviroment( by doc i thought it's platform-crossed).but i got this error:

 cmd/go: unsupported GOOS/GOARCH pair windows/386

### To Reproduce:
1 using the win10  go1.13.5
2 using dependencies "fyne.io/fyne/v2/app" "fyne.io/fyne/v2/container" "fyne.io/fyne/v2/widget"
3 compile
3.1 32bit mode
```
go run main.go
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```
3.2 64 bit mode
```
set GOOS=windows GOARCH=386& go run main.go
cmd/go: unsupported GOOS/GOARCH pair windows GOARCH=386/amd64
```

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

int main(){
    Window()
}

func Window(){
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
If you could provide the information about your computer that was removed from the bug template it would help to answer the question.

To compile 32bit from a 64bit computer (or the other way round) you will need a C compiler that supports both.

In your 32bit example (`3.1`) you don't show `GOARCH` but in your 64bit example (`3.2`) you are specifying a 32bit architecture so the compiler is confused.

**Comment by consititine** [comment]
i didn't enable the CGO_ENABLED switch before, now it works;3ks for helping.

**Comment by andydotxyz** [comment]
Great :)

**Comment by consititine** [comment]
i didn't enable the CGO_ENABLED switch before, now it works;3ks for helping.
