### ISSUE TITLE
Inexpected risizing of window when removing labels

### ISSUE THREAD

**Issue by marco-zanon** [fyne-io/fyne#2214]
### Describe the bug:

I was reading one of the examples of the tour provided in your website (this: https://developer.fyne.io/tour/container/box.html) and decided to play around with the example and add some functionality in order to explore it.
So I added the possibility of removing labels (besides "adding labels", which was already there). Here is my (altered) code of the tour:

```

package main

import (
	"strconv"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Entry Widget")

	content := container.NewVBox(
		widget.NewLabel("The top row of the VBox"),
		container.NewHBox(
			widget.NewLabel("Label 1"),
			widget.NewLabel("Label 2"),
		),
	)
	counter := 1
	labels := []*widget.Label{}
	content.Add(widget.NewButton("Add more items", func() {
		labels = append(labels, widget.NewLabel("Added #"+strconv.Itoa(counter)))
		content.Add(labels[len(labels)-1])
		counter++
		myWindow.Resize(content.MinSize())
	}))
	content.Add(widget.NewButton("Remove items", func() {
		if len(labels) != 0 {
			content.Remove(labels[len(labels)-1])
			labels = labels[:len(labels)-1]
			counter--
			myWindow.Resize(content.MinSize())
		}
	}))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}


```
What I noticed is that when I add a label, the window is resizing as expected, but when I remove a label, the resizing is kinda unexpected, rather the program is creating a blank field in the upper area in my first remove (with buttons clicking area kinda messy) and for subsequent removes, the blank field goes to the bottom area. (I expexted there would be no blank field at all at any time)

My configuration:
OS: Windows 10
Go version: 1.15.7
Fyne version: V2

### Screenshots:

After adding labels (woked as expected):
![image](https://user-images.githubusercontent.com/66091150/116933026-60147980-ac39-11eb-9172-44c22304cbfc.png)

After first removal - blank field in the upper area of window, also button clicking area messy (unexpected behaviour):
![image](https://user-images.githubusercontent.com/66091150/116933105-77ebfd80-ac39-11eb-98aa-5711282663bc.png)

After remaining removals  - blank field goes to the bottom area of window (unexpected behaviour):
![image](https://user-images.githubusercontent.com/66091150/116933180-9225db80-ac39-11eb-90f6-33450c1cfa18.png)

**Comment by andydotxyz** [comment]
I am confused about the title of the issue, you say that the window resize is unexpected, but your code is asking the window to resize...
Whilst a window will expand to the minimum size it will not shrink if the content size reduces.

However I think I do see a bug in our `container.Remove` code. Can you confirm whether this works if you add a call to `content.Refresh()` after you remove the elements?

**Comment by marco-zanon** [comment]
I’m sorry, I was not precise enough in the title. It should be more like
“unexpected behavior while resizing” (I didn’t really want to say “wrong
resizing”, as I might be the one doing something wrong since I’m just
starting using Fyne).

And yes, I was trying to make the window reduce its size while I was
removing labels. That’s why I was using window.resize (minsize of
container) after removing an item (shouldn’t it resize to the min size of
the container?)

I just added a content.Refresh() after removing an item and it didn’t seem
to do anything different.

Em ter, 4 de mai de 2021 às 07:41, Andy Williams ***@***.***>
escreveu:

**Comment by andydotxyz** [comment]
The refresh was just a random idea - the pull request #2219 should fix your issue

**Comment by andydotxyz** [comment]
It's now in `develop` and `release/v2.0.x` branches for whichever release is next
