### ISSUE TITLE
Mobile simulator does not close

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2225]
### Describe the bug:

On develop branch (for Aberlour), pressing the close button on the mobile simulator windows does not close it. This seems to be a regression as it works as expected in the 2.0.x point releases.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open the mobile simulator (in fyne_demo or any other code of your choice).
2. Try to close the windows using "x" in the corner.

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.11.12
 - **Go version:** 1.16.4
 - **Fyne version:** develop @ https://github.com/fyne-io/fyne/commit/9f38927599d0339ab5d42e6a422e962618d5f5d9

**Comment by andydotxyz** [comment]
In my testing this has never closed the app, because the lifecycle of mobile apps is to not close if the window goes away (part of the iOS and Android contract).
We could put simulator-specific code in there, but this is not a regression.

**Comment by Jacalz** [comment]
It has never closed the app before, with the process sticking around in the terminal, but the window closed before when pressing the close button. Now, pressing the close button does absolutely nothing. I would still call that a regression.

**Comment by fpabl0** [comment]
Just as reference, in `develop` @ 56d46ca09 everything seems to work normally, so maybe the issue was introduced after it?

**Comment by fpabl0** [comment]
Hmm at least in MacOS everything is working ok (even in last commit with develop branch), maybe this is is a Linux-only issue?

**Comment by Jacalz** [comment]
Might be. Will take another look tomorrow.

**Comment by andydotxyz** [comment]
Yes, confirmed that macOS is fine at this end as well.
I also see a hang in the window from Linux. Looks like a deadlock trying to close the window.
