### ISSUE TITLE
cmd/fyne: error on compiling

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#2227]
fyne.io/fyne/v2 v2.0.3-rc2.0.20210508113912-349c6f8e9d4e

![image](https://user-images.githubusercontent.com/19886504/117542167-10ea9200-b007-11eb-81dc-9c5b039d2d1f.png)

**Comment by Jacalz** [comment]
We have been over this before. Please fill out the required templates (bug in this case) when opening issues. As it stands right now, we have nothing to go on other than a screenshot.

**Comment by Jacalz** [comment]
If I understand the image right, it looks like the issues are in https://github.com/go-ole/go-ole and not here. We don't depend on that library as far as I know.

**Comment by Jacalz** [comment]
If I understand the image right, it looks like the issues are in https://github.com/go-ole/go-ole and not here. We don't depend on that library as far as I know. After looking some more, it seems to be a duplicate of https://github.com/go-ole/go-ole/issues/202.

**Comment by DiskGetor** [comment]
i am sorry, the build fyne env are:
manjaro linux xfce latest
Go 1.17
fyne develop latest
I cloned fyne and then cd cmd/fyne for build...

**Comment by Jacalz** [comment]
Are you on an arm machine by any chance?

**Comment by Jacalz** [comment]
Ah, we do use this on `develop` branch. Reopened, though it most likely is a duplicate of the issue mentioned above.

**Comment by andydotxyz** [comment]
Yes it would be really helpful to know what architecture you are building on @DiskGetor

**Comment by andydotxyz** [comment]
I pushed a possible fix, as these files are only required on Windows

**Comment by DiskGetor** [comment]
Good

**Comment by Jacalz** [comment]
>  Are you on an arm machine by any chance?

Even though we have the fix, I think the question still is very relevant. Are you on an arm/arm64 based architecture? @DiskGetor

**Comment by DiskGetor** [comment]
> > 你一臂机通过任何机会吗？
> 
> 即使我们有解决，我认为这个问题仍然是非常相关的。 你一臂/arm64（基础结构？ @DiskGetor

good. It work now

**Comment by DiskGetor** [comment]
> 是的，它会很有帮助的知道什么样的建筑，你正在建立 @DiskGetor

You are very cool,it work now.

**Comment by Jacalz** [comment]
> > > 你一臂机通过任何机会吗？
> 
> > 
> 
> > 即使我们有解决，我认为这个问题仍然是非常相关的。 你一臂/arm64（基础结构？ @DiskGetor
> 
> 
> 
> good. It work now

Sorry, but that doesn't quite answer my question. What CPU architecture does your computer use? Is it arm/arm64?

**Comment by DiskGetor** [comment]
> > > > 你一臂机通过任何机会吗？
> > 
> > 
> > > 
> > 
> > 
> > > 即使我们有解决，我认为这个问题仍然是非常相关的。 你一臂/arm64（（基础结构？ @DiskGetor
> > 
> > 
> > 好的。 它现在的工作
> 
> 对不起，但这并不相当回答我的问题。 什么CPU结构没有你的计算机使用？ 这是手臂/arm64（?

Yes, my system is manjaro arm64 linux on Android.

This is cpu info:

![Screenshot_20210509_223152_com android settings](https://user-images.githubusercontent.com/19886504/117575924-6e213900-b116-11eb-9123-34677def7e85.jpg)


This is system info:

![Screenshot_20210509_223201_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/117575970-8f822500-b116-11eb-8061-a2d05031e3f8.jpg)

**Comment by DiskGetor** [comment]
And if not updata fyne develop, the same problem was happened on Intel i3 cpu notebook, i was tested it yesterday, so i think that pkg import problem is nothing with cpu.

**Comment by Jacalz** [comment]
Are you sure that you saw the same thing on an i3 machine? I have not seen this on my i7 Linux computer and it looked, from the issue mentioned above, like this is related to the package missing arm support.

**Comment by DiskGetor** [comment]
> Are you sure that you saw the same thing on an i3 machine? I have not seen this on my i7 Linux computer and it looked, from the issue mentioned above, like this is related to the package missing arm support.

 I am sure
