### ISSUE TITLE
Wrong position on animated AppTabs indicator

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#2229]
### Describe the bug:
AppTabs indicator does not have a correct position in a special situation.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo.
2. Go to Containers > AppTabs.
3. Select "Tab 2 bigger"
4. Select Leading position.
5. Select Top position.
6. See the error.

### Screenshots:

https://user-images.githubusercontent.com/12239342/117548927-265abe80-affd-11eb-8488-5a30ba567835.mp4

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 10.15.7 Catalina 
 - **Go version:** 1.16.3
 - **Fyne version:** develop @ 9ec9882d71c0da85ce3b414ab8933101b594d67a

**Comment by andydotxyz** [comment]
I have managed to replicate this with mobile jumping second tab from bottom to top position.

**Comment by andydotxyz** [comment]
Fixed on develop, thanks @s77rt
