### ISSUE TITLE
Form builder

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#223]
I think a form builder would be useful for any GUI framework/library so do you have any plan/consideration about it? 

In any case thanks for project, it's great to have opportunity write GUI with Go.

**Comment by andydotxyz** [comment]
Can you expand on what you mean by a form builder? There is the widget.Form component but I expect you found that so maybe you mean something else?

**Comment by Kvaz1r** [comment]
Yeah - RAD tool for making GUI design from editor window.  For example [wxFormBuilder](https://github.com/wxFormBuilder/wxFormBuilder) for wxWidgets.

It's funny not only I thought in this direction - https://github.com/fyne-io/fyne/issues/227

**Comment by andydotxyz** [comment]
Ah thanks. I will close this as #227 has a more descriptive title
