### ISSUE TITLE
Goroutine leaked, big text show

### ISSUE THREAD

**Issue by DiskGetor** [fyne-io/fyne#2231]
Hello, i have 2 problem for teaching you.

1.fyne app goroutine was okay on any linux,
But if i build it as apk, the app was look like 
Leaked gouroutine, i do not think about any way for debug it.
![Screenshot_20210510_011429_com ddk KeyGen](https://user-images.githubusercontent.com/19886504/117581127-dc252a80-b12d-11eb-979a-78c8a99fb2d4.jpg)
![Screenshot_20210510_011443_com ddk KeyGen](https://user-images.githubusercontent.com/19886504/117581133-df201b00-b12d-11eb-9d15-1766b3384652.jpg)

I was rewited this api as error info, big text,but i can not found bug for goroutine.
https://gitee.com/ddkwork/library/blob/master/Check/Check.go

2.how to show big text as error info, it looks like not well.

![Screenshot_20210510_011443_com ddk KeyGen](https://user-images.githubusercontent.com/19886504/117581171-18f12180-b12e-11eb-927a-fa4c07ec9473.jpg)

Sorry my bad English.

**Comment by andydotxyz** [comment]
1. I do not understand why you think goroutines are being leaked.
The error you have posted does not seem to be a Fyne error.

2. To display larger text use `canvas.Text`. The `widget.Label` component shows at a standard size, set by theme.
