### ISSUE TITLE
Preferences file gets unexpectedly cleared

### ISSUE THREAD

**Issue by jsawo** [fyne-io/fyne#2241]
### Describe the bug:
When reading preferences, sometimes the `preferences.json` file gets suddenly cleared. This does not seem to happen if the app window is displayed as in most cases it would be. I stumbled on this when trying to add simple CLI flags that would show stored preferences without displaying normal GUI. What's weird is that it often works as expected (prefs are read successfully) and only once in a couple of runs the preferences file gets destroyed. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Read preferences without showing app window
2. Execute the app a couple of times
3. See the preferences file

### Screenshots:
Here I'm running the attached sample code a couple of times before the prefs file gets emptied:
![fyne-prefs-bug](https://user-images.githubusercontent.com/1294706/118271932-37ef0b00-b4c2-11eb-86a1-65f2cc118949.gif)

### Example code:
This code assumes that preferences file is already available at `~/.config/fyne/com.example.fyne.prefs/preferences.json` with content like: `{"FOO":"BAR"}`

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
)

func main() {
	a := app.NewWithID("com.example.fyne.prefs")
	p := a.Preferences()

	if val := p.String("FOO"); val != "" {
		fmt.Println("setting found:", val)
	}
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Ubuntu 20.10 
 - **Go version:** 1.16.3
 - **Fyne version:** 2.0.3

**Comment by andydotxyz** [comment]
This is fixed on `release/v2.0.x` branch ready for 2.0.4
