### ISSUE TITLE
TestWindow_HandleOutsideHoverableObject is failing

### ISSUE THREAD

**Issue by AmanitaVerna** [fyne-io/fyne#2243]
### Describe the bug:
When I run package tests in internal/driver/glfw (or directly run this test), TestWindow_HandleOutsideHoverableObject fails, saying "Expected value not to be nil" on line 291 of window_test.go. I debugged it, and while walking the tree of objects FindObjectAtPositionMatching in internal/driver/util.go finds the hoverable ListItem and saves it to found and foundPos in a very side-effecty way, and then later it finds a non-hoverable (but draggable?) Entry and saves that to found and foundPos, overwriting the saved ListItem, with the result that it ends up setting no mouseOver. This is with no changes to the code which is currently on fyne-io/develop (I was getting it with the code I wrote to fix #2222 too, and was trying to figure out how I could have caused it, but then when I ran the test with just the code on fyne-io/develop, it still happened). 

I have no idea why this is happening for me when I run the tests, but didn't happen during the tests that were run on the last commit to develop, though. I did just upgrade to Go 1.16.4 today, but from following the code the test runs, it looks like it's just a bug in fyne?

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the test TestWindow_HandleOutsideHoverableObject in internal/driver/glfw/window_test.go.

### Device (please complete the following information):
 - **OS:** Windows 10 Pro
 - **Version:** 20H2
 - **Go version:** 1.16.4
 - **Fyne version:** 6b7d4bf6f0ed3864d3f650fcda23e06c24be3a38

**Comment by fpabl0** [comment]
Hello @AmanitaVerna that test is sensible to mouse position changes (hover), so if you move your mouse while the test is going on, you will receive that error. Try to not move your mouse while doing the test and the test should pass.

**Comment by AmanitaVerna** [comment]
It is still happening even when I run the test from powershell or cmd without touching my mouse at all, and continue to not touch my mouse until it finishes.

**Comment by fpabl0** [comment]
Oh you are right, it seems that https://github.com/fyne-io/fyne/pull/2223 introduced this bug. Thanks for reporting this :)

**Comment by AmanitaVerna** [comment]
no problem :)

**Comment by andydotxyz** [comment]
This fix was landed, thanks @fpabl0  @AmanitaVerna
