### ISSUE TITLE
Can I design with adobe XD? Just like XD to Flutter.

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne#2256]
Can I design with adobe XD? Just like XD to Flutter.

**Comment by Jacalz** [comment]
No, that's not possible at this point in time. The only similar tool is https://github.com/andydotxyz/fynebuilder which is work in progress at the moment.

**Comment by xfengw** [comment]
It is recommended to make an XD plug-in, such as XD to Flutter

**Comment by Jacalz** [comment]
I think we prefer open source tools when possible. Not sure that there will be anyone working in a plug-in like that for the time being.

**Comment by andydotxyz** [comment]
I agree that plugins to proprietary tools are unlikely to be built by the current community as we are focused on open source and tools that can benefit developers around the whole world.
Of course some of our developers are available for hire / sponsorship and can build such things for people looking to pay for closed-source work.
