### ISSUE TITLE
Refocus Previous Window on window close

### ISSUE THREAD

**Issue by pbarnum** [fyne-io/fyne#226]
The previous window that had focus should regain the focus when the currently focused window is closed.

This also makes me think about another issue, is there anyway we can reference the main window when we don't hold reference to it anymore? Like from the `app` object?

**Comment by andydotxyz** [comment]
This may be down to the desktop manager. When a dialog is opened and then closed the focus will return to the parent window. When an application contains many windows it is usually down to the desktop to decide what to do...

Do you have a specific setup where it is not working as expected?

**Comment by andydotxyz** [comment]
As for accessing the main window reference that could be a handy idea. What particularly were you trying to do?

**Comment by pbarnum** [comment]
This doesn't seem to work on my Mac, I haven't tried other operating systems. For the second idea, I was trying to figure out how I can reference the main window to manually refocus it but found out I couldn't. Thought it sounded like a good idea.

**Comment by andydotxyz** [comment]
I wasn't sure about this but looking at other applications I think you are right.
On macOS and on Linux Gnome an application is entitled to re-focus another window if one is closed (it seems). Perhaps we should re-add this behaviour?

If so should we also be tracking the order that windows were last focused so we can re-focus in the same order?

**Comment by pbarnum** [comment]
Yes definitely, that's how I was thinking it would work.

**Comment by andydotxyz** [comment]
OK, moving to 1.2 as we have other window support work to do for mobile which impacts this.
Sorry for the constant pushing it back :(

**Comment by andydotxyz** [comment]
The mobile window management became just a stack so this is only for the GLFW driver :smile:

**Comment by rubensayshi** [comment]
not sure if this would be considered related or not but;

on MacOS when the focused window is closed, it should kinda just release the focus back to the previously focused window, regardless of which application.  

ie. if I do a little popup using fyne over my browser, after closing the window the focus should be on the browser window again.  
but it kinda "lingers", I can see my titlebar having the title "main" (my process name) instead ...

**Comment by andydotxyz** [comment]
Yes that probably is related - but I'm not sure how!

**Comment by rubensayshi** [comment]
ye that sounds clear enough, so my best bet is either closing the process that runs the window ( I guess my daemon could spawn a subprocess that managed the window ), or do something like `osascript -e 'tell application "Terminal" to activate'` to reactive the terminal window (in 99% of my usage thats the previous app anyway)

**Comment by pbarnum** [comment]
It seems like this is something the driver/os should be handling, otherwise rouge apps could retain focus. Do we know if setting the focus of the window via fyne would be overwritten by the focus given by the os? Perhaps it's a non-issue?

**Comment by rubensayshi** [comment]
most macOS apps will exit entirely when you close the last open window (which solves the issue), there's a few macOS apps that keep the application open and they have the same behaviour as my "issue". including the (builtin) Finder app.

I guess its the responsibility of the application to return to the background in someway when the last window is closed and if it doesn't want to exit entirely.  
or to have a background process running and open a new process for the GUI stuff and then exit that process entirely when done.   

I don't think that its the responsibility of fyne to provide this functionality ...

for an easy fix (my use case is just a small tool for our dev team, so easy 90% fix > hard 100% fix), I ended up using `osascript` to determine the active window before I steal focus and to return to it once I close the window, seems to work fairly well.

```go
func getFocusedWindow() string {
    cmd := exec.Command("osascript", "-e", "tell application \"System Events\"\n"+
        "name of first application process whose frontmost is true\n"+
        "end tell")

    res, err := cmd.Output()
    if err != nil {
        fmt.Printf("getFocusedWindow output: %v \n", err)
        return ""
    }

    return strings.TrimSpace(string(res))
}

func altTabTo(window string, logger loggo.Logger) {
    logger.Child("alttab").Debugf("alttab to [%s]", window)
    err := exec.Command("osascript", "-e", fmt.Sprintf("tell application \"%s\" to activate", window)).Run()
    if err != nil {
        fmt.Printf("altTabTo err: %v \n", err)
    }
}

```

**Comment by andydotxyz** [comment]
I think that it still has 1 remaining area that should be improved... On macOS when a Fyne app has many windows then closing one does not bring the previous forward. This seems not to be handled by the OS (though it is on some Linux systems) so we should probably still insert a "please focus" request as we work back through the window stack.
Agreed?

**Comment by pbarnum** [comment]
I don't think this an appropriate fix for what seems to be a non issue, or at least not aligned with the original issue. MacOS also does not return focus to another application when the last window is closed, notice that there title bar doesn't change after close. This is also functionality provided by the is, windows for instance is opposite as it will bring the next application in the stack into focus.

Window focus I believe should not leave the context of this framework and should not try to fight against the natural focus provided by the os. It certainly shouldn't call out to an external command as that now binds the framework to specific environmental dependencies.

As for the issue originally presented, this could be solved by using a stack to hold reference to all created windows. Focusing different fyne windows will set them at the top of the stack. We would also need to set parent/child relations so we could tell children to close if the parent closes before it. For example, if closing the main window, close all child windows. Another example is with a dialog window that refuses to give up focus until it's close/ok button is clicked.

**Comment by andydotxyz** [comment]
I think I agree with that all.
We are not tracking parent/child but instead allow a single "master window" that, if closed, would exit the app.
Dialogs are all inside the canvas (at least for now) so that isn't an issue really.
So it's just back to the original issue and the stack you propose as a good solution I think.

**Comment by andydotxyz** [comment]
Could fall back to master window if there is one :)

**Comment by andydotxyz** [comment]
I opted for "most recently opened or master" which is slightly better than "master or window 0".
It's not perfect for 3 or more windows, but in most situations I think we agreed it's good enough to move on.

**Comment by andydotxyz** [comment]
Finally this is on develop branch for testing. Sorry for the delay!
