### ISSUE TITLE
scroller bar disappear after changing content

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#2268]
### Describe the bug:
a scroller container have a content (and depending on that content a scrollbar may appear)
after changing the content, the scrollbar will never appear again

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code below
2. you will notice that we have a scrollbar (because the content is too big, that's expected; no problem here)
3. after clicking on the change content button, the content will be changed
4. however the scrollbar is not there, it's gone and won't appear again at all, even if you change the content back to the first content

### Example code:
```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Scroller Issue")

	d1 := container.NewVBox(
		widget.NewLabel("Data A1"),
		widget.NewLabel("Data A2"),
		widget.NewLabel("Data A3"),
		widget.NewLabel("Data A4"),
		widget.NewLabel("Data A5"),
		widget.NewLabel("Data A6"),
		widget.NewLabel("Data A7"),
		widget.NewLabel("Data A8"),
		widget.NewLabel("Data A9"),
		widget.NewLabel("Data A10"),
	)
	d2 := container.NewVBox(
		widget.NewLabel("Data B1"),
		widget.NewLabel("Data B2"),
		widget.NewLabel("Data B3"),
		widget.NewLabel("Data B4"),
		widget.NewLabel("Data B5"),
		widget.NewLabel("Data B6"),
		widget.NewLabel("Data B7"),
		widget.NewLabel("Data B8"),
		widget.NewLabel("Data B9"),
		widget.NewLabel("Data B10"),
	)

	s := container.NewScroll(d1)

	b := widget.NewButton("Change Content", func() {
		if s.Content == d1 {
			s.Content = d2
		} else {
			s.Content = d1
		}
		s.Refresh()
	})

	w.SetContent(container.NewGridWithRows(2,
		s,
		b,
	))

	w.Resize(fyne.NewSize(500, 400))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Go version:** go1.16.2
 - **Fyne version:** 12d020ec2dd30646a9d2a7944edd97298c7d3d28

**Comment by s77rt** [comment]
after a little search i found that this may be intended?
is it intended to have a scrollable object with no scrollbar? as i see this is the case with DocTabs

**The initial fix:**
changing this line:
https://github.com/fyne-io/fyne/blob/12d020ec2dd30646a9d2a7944edd97298c7d3d28/internal/widget/scroller.go#L368
to:
`r.BaseRenderer.Objects()[0] = r.scroll.Content`

fixes my issue, but this also means that DocTabs will have a scrollbar _(is it supposed to not have a scrollbar?)_

**IMHO:**
Changing Scroll.Content should have nothing to do with the scrollbar

**Comment by Jacalz** [comment]
Hmm, I doubt it would be intended. Sounds more like an oversight that led to a bug 🐛

**Comment by andydotxyz** [comment]
It is very strange because those lines should be equivalent. This probably requires more thought.
I agree that anything that can be scrolled should have a scroll bar

**Comment by s77rt** [comment]
The baserenderer includes 7 objects:
The content itself
2 scrollbars (horizontal and vertical)
4 shadows (top left right bottom)

That's why the old line replaces all those objects with just the content, while the new line replaces only the content with a new content.


Side personal note: DocTabs looks better without the scrollbar

**Comment by andydotxyz** [comment]
Oh, excellent catch, I see your point on the difference

**Comment by s77rt** [comment]
so, what do you think?
should we use just apply the fix mentioned above?

**Comment by andydotxyz** [comment]
Yes I think that is correct

**Comment by andydotxyz** [comment]
In `v2.0.4-rc1` for testing
