### ISSUE TITLE
Gui editor support?

### ISSUE THREAD

**Issue by xzzh999** [fyne-io/fyne#227]
Hi~ 
Great work!

Is there any plans for ```a WYSIWYG editor```? just like [***QtCreator***](https://github.com/qt-creator/qt-creator) or [***wxFormbuilder***](https://github.com/wxFormBuilder/wxFormBuilder) to auto generate gui code?

**Comment by andydotxyz** [comment]
It is planned at some point! The widget structure is designed to support this but first we need to implement #5 and then load widgets from a file/resource. 

That seems better than generating Go code but we don’t have much work done yet.

**Comment by andydotxyz** [comment]
Work has begun at [github.com/andydotxyz/fynebuilder/](/andydotxyz/fynebuilder/)

**Comment by andydotxyz** [comment]
Closing as the project is now progressing at the link above
