### ISSUE TITLE
How to package an executable binary package into the program?

### ISSUE THREAD

**Issue by juchao1989** [fyne-io/fyne#2272]
How to package an executable binary package into the program?
such as:
go code: exec.Command("/bin/bash", "-c","./hello")//hello is an executable binary file
How to pack this 'hello' binary into fyne for use?
My purpose is not to let users see two executable files, and pack one binary file into another fyne!
Any solution, please give me ideas, thank you very much

**Comment by andydotxyz** [comment]
This is not recommended, such things will likely be detected as malware.
That said using Go 1.16 embed, or "fyne bundle" you can embed anything - though you will have to extract it to be able to execute.

**Comment by Jacalz** [comment]
I’ll close this as the question has been answered and the issue has been stale since.
