### ISSUE TITLE
how to set list Height ?

### ISSUE THREAD

**Issue by tiends** [fyne-io/fyne#2278]
![image](https://user-images.githubusercontent.com/85164819/120760355-9b5edc80-c546-11eb-9b02-cd5f2417ae63.png)

```
w.SetContent(container.NewVBox(
		container.NewHBox(widget.NewLabel("please select file !"), btn),
		widget.NewSeparator(),
		InitUploadList(),
))

func InitUploadList() *widget.List {
	list := widget.NewList(func() int {
		return 100
	}, func() fyne.CanvasObject {
		return widget.NewLabel("hello word")
	}, func(id widget.ListItemID, object fyne.CanvasObject) {

	})
	return list
}
```

**Comment by andydotxyz** [comment]
Widget size is always controlled by the parent container. You are using VBox which requests minimum height for all widgets. Consider another that will space items out, such as Border.
https://developer.fyne.io/faq/layout

**Comment by aztack** [comment]
Still don't know how to stretch the list after read the doc.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/782871/194810227-590317f9-7107-42e4-8291-c919619ff274.png">

The layout is like:
```
<vbox>
  <label>Available Versions</label>
  <list>
    <list-item>1.1.1</list-item>
    <list-item>1.1.0</list-item>
  </list>
  <hbox>
    <button>Download</button>
    <button>Skip</button>
  </hbox>
<vbox>
```

**Comment by Jacalz** [comment]
@aztack I would suggest having a look at https://developer.fyne.io/explore/layouts and especially the video at the bottom. It should give you all the answers that you need.

**Comment by andydotxyz** [comment]
Forcing height with a MinSize rectangle is a bad idea in general as the user can no longer make something smaller.
I think that Jacob was proposing border so you could put the buttons at the bottom and the list in the center avoiding any size hacks and the container would then fill the window again.
