### ISSUE TITLE
Problem building under Windows 10 using MingW 64

### ISSUE THREAD

**Issue by serge-hulne** [fyne-io/fyne#228]
The error message when attempting to build the simples example is 👎 

# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

Is it a problem with Golang ? OpenGl, or MingW ?

**Comment by okratitan** [comment]
Even when installing mingw 64 you have to select the 64 bit compiler when you are installing it instead of the 32 bit one. It seems you still installed 32 bit.

**Comment by serge-hulne** [comment]
Yes, you're right !

My apologies, I'm not used to work with MingW (I usually use gcc under Mac
or Linux).

Thank your very much for your help and congratulations for Fyne : it seems
vers promising.

Serge.

**Comment by andydotxyz** [comment]
Glad you got it sorted
