### ISSUE TITLE
Cursor blink should be user-controllable

### ISSUE THREAD

**Issue by mark-summerfield** [fyne-io/fyne#2281]
The fyne_demo's text editing widgets (Entry, etc.) all have blinking cursors. For almost everyone this is expected and desirable since most people find this useful.

But a tiny minority (including me) can't work with blinking cursors. Microsoft recognized this issue more than 20 years ago and in Windows 2000 allowed users to globally switch off cursor blink. AFAIK Apple don't offer this. For Linux it seems to be toolkit dependent: easy with Tk and Qt4, possible with wx and Qt 5 and Gtk. (See also https://jurta.org/en/prog/noblink to see that it isn't just me.)

So I hope you'll add an option to either respect the user's settings or allow cursor blink to be disabled.

**Comment by andydotxyz** [comment]
Perhaps this could be addressed by #1813?

**Comment by andydotxyz** [comment]
Closing as duplicate, as disabling animation will suit this purpose
