### ISSUE TITLE
Add a detail view mode mode to FileDialog

### ISSUE THREAD

**Issue by tktkc72** [fyne-io/fyne#2284]
### Is your feature request related to a problem? Please describe:

The current method of displaying FileDialog icons is limited in the number of items that can be displayed at one time, and file names can only be displayed in a short range, making it inefficient when selecting files.

### Is it possible to construct a solution with the existing API?

It isn't possible to construct a solution with the existing API.

### Describe the solution you'd like to see:

Add an option to change the FileDialog to a VBox layout like Windows Detail View.

**Comment by andydotxyz** [comment]
Do you mean like the #2251 PR?

**Comment by tktkc72** [comment]
That's right.
I'm sorry I missed it.
I'm looking forward to it being added.

**Comment by andydotxyz** [comment]
Not a problem. It has now landed, so you can test on the `develop` branch if you like.
