### ISSUE TITLE
List text wrapping doesn't adjust cell line

### ISSUE THREAD

**Issue by IvoryJam** [fyne-io/fyne#2289]
### Describe the bug:
When settings a list item with fyne.TextWrapBreak the lines stay the same and make it hard to read

### Screenshots:
![image](https://user-images.githubusercontent.com/35709713/122307484-b0812700-cec7-11eb-8b45-f8045506c631.png)

### Example code:
```go
	ruleMap := []string{"short one", "a really long item aaaaaa bbbbbb ccccc ddddd eeeee", "short one again"}
	ruleList := widget.NewList(
		func() int { return len(ruleMap) },
		func() fyne.CanvasObject { return widget.NewLabel("template") },
		func(i widget.ListItemID, o fyne.CanvasObject) {
			o.(*widget.Label).Wrapping = fyne.TextWrapWord
			o.(*widget.Label).SetText(ruleMap[i])
		},
	)

```

### Device:
 - **OS:** Linux
 - **Version:** Linux manjaro 5.10.42-1-MANJARO
 - **Go version:** go1.16.5 linux/amd64
 - **Fyne version:** v2.0.3

**Comment by andydotxyz** [comment]
List cells are uniform - they are all the size of your `template` above.
A future version of the API may support multiple heights, but for now the caching used in List for performance does not support it.
If your data set is small you could use `cointainer.VBox` instead, which adjusts every cell to it's appropriate size.

**Comment by ddkwork** [comment]
![Screenshot_20210710_072413_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/125144278-eeccd780-e14f-11eb-87be-ec5ce7ebe9dc.jpg)

I have same2 problem, if warp is break, the layout with be change more bigger. If wrap is word, the message will seed on last not begin message.

**Comment by andydotxyz** [comment]
As said above list uses same-height-rows for performance. To use varying height consider VBox container instead
