### ISSUE TITLE
Custom formatting for data binding

### ISSUE THREAD

**Issue by valpo** [fyne-io/fyne#2290]
### Is your feature request related to a problem? Please describe:

I like the data binding very much, esp the automatic type conversion. It is already possible to add a format string for the conversion. IMHO it would be nice to also have the possibility to provide a custom conversion function. 

### Is it possible to construct a solution with the existing API?

It is easy to avoid using the automatic data conversion. It is just a small enhancement. 

### Describe the solution you'd like to see:

In addition to 
`func IntToStringWithFormat(v Int, format string) String`
I would like to see a function like
`func IntToStringWithConversion(v Int, func conv(v Int) String) String`
which does the same thing but instead of applying the format it calls the user supplied conv function for doing the conversion. 

Mathias

**Comment by andydotxyz** [comment]
If you are writing user supplied code then you can do this by writing a new binding.
You can embed a `String` binding and override the `Get` function to return the result of your custom conversion.
You may look to overload `Set` as well, if you want to receive updated data in the custom format.

**Comment by Jacalz** [comment]
It looks to me like the answer makes this feature unnecessary. Can this be closed?

**Comment by andydotxyz** [comment]
Agreed, I think this is one of those cases where the unsatisfied cases are corners that can be pushed to developer code to keep the API slim.
