### ISSUE TITLE
Can we detect a window focus gained/lost?

### ISSUE THREAD

**Issue by daiwhea** [fyne-io/fyne#2291]
**Is your feature request related to a problem? Please describe:**

   When we create a window, we can define SetOnClosed/SetCloseIntercept. Can we set a func for window focus gained/lost?

**Is it possible to construct a solution with the existing API?**

  I don't know how to detect a window got or lost focused.

**Describe the solution you'd like to see:**

	w.SetOnFocusGained(func())
	w.SetOnFocusLost(func())

Or how can I detect a window focus gained or lost?

Thanks.

**Comment by andydotxyz** [comment]
In 2.1 we have introduced a new API called application lifecycle, this includes the Foreground/Background notification which should satisfy your requirement.

You can try it now on the `develop` branch or read more at #1053

**Comment by daiwhea** [comment]
Thanks. You are doing great work.
