### ISSUE TITLE
How to set focus and mouse cursor enter to the widget Entry field

### ISSUE THREAD

**Issue by cvq** [fyne-io/fyne#2292]
I want to set focus and mouse cursor enter to the widget Entry field.
myEntry.FocusGained() does not help. I still have to click manually into myEntry field before typing.
Pls. Hep.

**Comment by andydotxyz** [comment]
Call `Window.Canvas().Focus(myEntry)`. This will focus the element. You cannot manually move the mouse cursor.

**Comment by cvq** [comment]
Thank you **andydotxyz**. This is what i want: Window.Canvas().Focus(myEntry)

**Comment by Jacalz** [comment]
Closing this as it seems to be resolved.
