### ISSUE TITLE
Please consider adding id to BaseWidget

### ISSUE THREAD

**Issue by mrjrieke** [fyne-io/fyne#2293]
Please add an id field to BaseWidget in order to make all widget instances uniquely identifiable.

### Is it possible to construct a solution with the existing API?
I guess you can kind of use widget references, but this seems clumsy and non obvious.

### Describe the solution you'd like to see:
type BaseWidget struct {
    id  <some id type that probably doesn't have to be too large>
   size     fyne.Size
...
}

**Comment by andydotxyz** [comment]
The problem of ID references is that they are not type safe and lead to annoying runtime issues.
We’ve designed this to be code-first meaning that you pass pointers, objects or use data binding to keep your app up to date. This means that apps are more stable by default :).

**Comment by justmax437** [comment]
> The problem of ID references is that they are not type safe and lead to annoying runtime issues.

Can you explain this one? How could a simple embedded user-assigned uint number or string be unsafe?

**Comment by andydotxyz** [comment]
> Can you explain this one?

Certainly, all widgets have a strong type, using object references means that the compiler can check everything, using IDs breaks this safety. Allow me to illustrate, the `ref1` shows type is known, in `ref2` we must tell the compiler what is happening - that is where the safety is in question.

```go
	b := widget.NewLabel("Hello")
	ref1 := b
	log.Println("ref1 text:", ref1.Text)

	ref2 := objectForID("someID")
	log.Println("ref2 text:", ref2.Text) // compile error
	log.Println("ref1 text:", ref2.(*widget.Label).Text) // potentially unsafe type assertion
```

**Comment by justmax437** [comment]
> using IDs breaks this safety

Can't this safety be regained by having a second parameter of `objectForID`, which describes which type is expected, that is checked in runtime via reflect? If widget with specified ID is found and it's type matches, than this widget or its pointer is returned as safe-to-convert `interface{}` value. If either widget not found at all or type mismatched, `nil` is returned indicating that no such widget exists.

```go
        b := widget.NewLabel("Hello")
        b.SetWidgetID("someID")
	ref1 := b
	log.Println("ref1 text:", ref1.Text)

	ref2 := objectForID("someID", widget.Label{}) //Matches and returns handle to label
        ref3 := objectForID("someID", interface{}) //Interface types are prohibited and should panic
	log.Println("ref2 text:", ref2.(*widget.Label).Text) // ref2 is safe to cast as Label now
```

Certainly, this is not as good as compile-time static checks, but having a way of looking up certain widget or uniquely identify one is too useful to leave behind either

**Comment by andydotxyz** [comment]
There are many ways that you can provide this information to the compiler, and your idea would add some syntactic sugar.
However it still suffers the same problem that if you happen to get it wrong you'll get panics or other app problems.
I would much prefer that we can encourage people to use objects instead - that is what a compiled, typed, language is best at.

**Comment by justmax437** [comment]
@andydotxyz just as I said, this is still no static checking, yes. I understand the problem. Can upcoming go1.18 generics help in improving type safety in such case then?

**Comment by justmax437** [comment]
@andydotxyz also, having ID in widgets even without a way of looking them up by it still has its uses, like when you going throughout a list of children in a container looking for a specific one.

**Comment by zdima** [comment]
@justmax437 I had a similar issue. In my case I was using a List where each item is a container with multiple widgets. To populate values from update function for those widgets is tricky. I accomplish this by creating a new type for each widget:
```
type myName struct { widget.Label }

func create() fyne.CanvasObject {
	var *name = &myName{Label: widget.Label{Text: "ABC", Alignment: fyne.TextAlignLeading, TextStyle: fyne.TextStyle{}}}
	name.ExtendBaseWidget(name)
...
	return container.NewHBox( widget.NewLabel("Name:"), name...
}
```
**Note:** don't forget to ExtendBaseWidget or have a new function to simplify this.

In update function I use type select with new type to assign values.
```
func update(i ListItemID, co fyne.CanvasObject) {
	r := getRecord(i)
	switch co := co.(type) {
	case *myName:
		co.SetText(r.Name)

```
Other option is to create a new widget, like a form, to keep pointers to each item in container, and that way you have an address for each widget you need to update or access.

**Comment by justmax437** [comment]
@zdima exactly my case, and
> Other option is to create a new widget, like a form, to keep pointers to each item in container

was exactly what I did. But that feels extremely ineffective and cumbersome.

**Comment by andydotxyz** [comment]
In some places it is necessary to write a little more code to ensure type safety and compiler checks.
Once you leave the idea of `id` behind you could even see the benefits of this approach ;).
OK it is not always going to be best for everyone, but it is the design approach we have taken.
