### ISSUE TITLE
no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

### ISSUE THREAD

**Issue by cchuster** [fyne-io/fyne#2297]
Hi! I am on Linux and am trying to build an android app. 

After running the `fyne package` command, I get the error in the title. This was after I already ran the command `export ANDROID_NDK_HOME=/opt/android-ndk`. I even ran `echo $ANDROID_NDK_HOME` which provided this output `/opt/android-ndk`.

Any help would be greatly appreciated!

**Comment by andydotxyz** [comment]
Are you sure that `ANDROID_NDK_HOME` has been exported in the same terminal as `fyne package` is running?
Perhaps you can confirm what is in `/opt/android-ndk` so we can check it's the correct location?

**Comment by cchuster** [comment]
After running `ls /opt/android-ndk`, it gave me an output of `build  CHANGELOG.md  meta  ndk-build  ndk-gdb  ndk-lldb  ndk-stack  ndk-which  NOTICE  NOTICE.toolchain  prebuilt  python-packages  README.md  shader-tools  simpleperf  source.properties  sources  toolchains  wrap.sh`. For some extra info, I run Manjaro and installed the `android-ndk` package from the AUR.

**Comment by andydotxyz** [comment]
what about `ls $ANDROID_NDK_HOME`? just to be sure :) - here is what happens for me, fresh installation.
![ndk](https://user-images.githubusercontent.com/294436/123253020-df5d5580-d4e4-11eb-81ec-2524c970a9f2.png)

**Comment by cchuster** [comment]
Here is the output of `ls $ANDROID_NDK_HOME`:

![Screenshot_2021-06-24_10-40-22](https://user-images.githubusercontent.com/26616243/123308498-97d0cc80-d4d8-11eb-8f35-4d1a747e9ffb.png)

**Comment by andydotxyz** [comment]
And the compile command followed by output? Is it still the same as the original error?

**Comment by cchuster** [comment]
Yes the same error.

**Comment by andydotxyz** [comment]
Something is not working on your console as it should be. I have reviewed the code, and all it does is check that the directory in ANDROID_NDK_HOME exists and is readable. So either all that I can think of is:
*) There is a typo somewhere in your paths
*) The user you are running the command as does not have permission to read
*) The export is in a different terminal

You seem reluctant to share the whole console with setup/command/output and without that I cannot think what else to suggest.

**Comment by cchuster** [comment]
Hi! Sorry if I seemed reluctant, I was just trying to be concise with the information I provided. For some reason, re-adding `$GOPATH/bin` to my `$PATH` fixed it and now it makes the APK successfully. Thanks for your help anyways!

**Comment by BertBR** [comment]
I have the same problem.
![Screenshot_20230201_233948](https://user-images.githubusercontent.com/29619309/216217822-2791ffb0-a682-4c9b-a701-08fffdf1beab.png)

My  `.zshrc` has the following envs
```bash
#Android NDK
ANDROID_NDK_HOME=$HOME/Android/ndk-bundle
PATH=$PATH:$ANDROID_NDK_HOME
```
