### ISSUE TITLE
fyne cannot package for Android from aarch64 Linux

### ISSUE THREAD

**Issue by ddkwork** [fyne-io/fyne#2302]
### Describe the bug:
fyne not supported ndk aarch64 version.

### To Reproduce:
Steps to reproduce the behaviour:

1. Download fyne develop branch,goto fyne/cmd,go build and copy binary to /bin dir.

2.install aarch64 Android sdk and ndk.

3. Cd fyne demo and setup command: fyne package -os android/arm64 -appID com.ddk.KeyGen

4. See error:panic: unsupported GOARCH: arm64

### Screenshots:

![Screenshot_20210627_162521_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/123537865-52c0ca80-d764-11eb-8bba-ef434194bee4.jpg)
### Device (please complete the following information):
 - **OS:** manjaro arm64
 - **Version:** latest
 - **Go version:** 1.17
 - **Fyne version:** 
Develop latest

Hello,I'm use fyne develop to build apk on aarch64 linux, when i go to fyne source /cmd/fyne, then build it for build apk with crash. So  please support fyne build tool for aarch64.this is crash log.

?? ddk@localhost ?? /media/sd/Download/manjarolinux/Desktop/gopher/branch/ReverseEngineering/datarecovery/keygen/ui/androidkeygen ?? source apk.sh
panic: unsupported GOARCH: arm64

goroutine 1 [running]:
fyne.io/fyne/v2/cmd/fyne/internal/mobile.archNDK(...)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/env.go:291
fyne.io/fyne/v2/cmd/fyne/internal/mobile.(*ndkToolchain).Path(0x40001777d0, {0x400022c0e0, 0x1b}, {0x4564aa, 0x5})
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/env.go:319 +0x78
fyne.io/fyne/v2/cmd/fyne/internal/mobile.envInit()
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/env.go:107 +0x1b0
fyne.io/fyne/v2/cmd/fyne/internal/mobile.buildEnvInit()
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/env.go:76 +0x2f4
fyne.io/fyne/v2/cmd/fyne/internal/mobile.runBuildImpl(0x794540)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/build.go:93 +0x3c
fyne.io/fyne/v2/cmd/fyne/internal/mobile.runBuild(...)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/build.go:74
fyne.io/fyne/v2/cmd/fyne/internal/mobile.RunNewBuild({0x7fcb19d584, 0xd}, {0x7fcb19d599, 0xe}, {0x400020e380, 0x76}, {0x400002c064, 0xd}, {0x455ff0, 0x5}, ...)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/mobile/build.go:274 +0x20c
fyne.io/fyne/v2/cmd/fyne/internal/commands.(*Packager).packageAndroid(...)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/commands/package-mobile.go:18
fyne.io/fyne/v2/cmd/fyne/internal/commands.(*Packager).doPackage(0x4000216b60)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/commands/package.go:222 +0x500
fyne.io/fyne/v2/cmd/fyne/internal/commands.(*Packager).Package(0x4000216b60)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/commands/package.go:168 +0x44
fyne.io/fyne/v2/cmd/fyne/internal/commands.Package.func1(0x400020cd80)
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/internal/commands/package.go:104 +0x28
github.com/urfave/cli/v2.(*Command).Run(0x400021b560, 0x400020c840)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x648
github.com/urfave/cli/v2.(*App).RunContext(0x4000222680, {0x4f6b50, 0x40000280d0}, {0x40000201e0, 0x6, 0x6})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x764
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/ddk/go/pkg/mod/fyne.io/fyne/v2@v2.0.3-rc2.0.20210626204313-16a63520250f/cmd/fyne/main.go:38 +0x2a8
 ?? ddk@localhost ?? /media/sd/Download/manjarolinux/Desktop/gopher/branch/ReverseEngineering/datarecovery/keygen/ui/androidkeygen ??

**Comment by Jacalz** [comment]
Again, please use the issue templates when opening issues. It is apparent that you selected the template and then removed the contents. I am sorry for having to say this, but we have been over this multiple times in the past. Not using the tramples makes it much harder for us to look into and replicate potential issues.

**Comment by DiskGetor** [comment]
> Again, please use the issue templates when opening issues. It is apparent that you selected the template and then removed the contents. I am sorry for having to say this, but we have been over this multiple times in the past. Not using the tramples makes it much harder for us to look into and replicate potential issues.

Sorry my bad English

**Comment by andydotxyz** [comment]
I think that your Go version is incorrect, and may be the source of confusion. Please double check with 'go version'.

> * **Go version:** 1.17

On my computer it works just fine
```
$ fyne package -os android/arm64 -appID io.fyne.hello -icon ../../theme/icons/fyne.png
$ unzip hello.apk
$ file lib/arm64-v8a/libhello.so
lib/arm64-v8a/libhello.so: ELF 64-bit LSB shared object, ARM aarch64, ...
```

Also note that instead of "go build then copy to bin" you can use `go install` for the `fyne` cmd.

**Comment by DiskGetor** [comment]
> I think that your Go version is incorrect, and may be the source of confusion. Please double check with 'go version'.
> 
> > * **Go version:** 1.17
> 
> On my computer it works just fine
> 
> ```
> $ fyne package -os android/arm64 -appID io.fyne.hello -icon ../../theme/icons/fyne.png
> $ unzip hello.apk
> $ file lib/arm64-v8a/libhello.so
> lib/arm64-v8a/libhello.so: ELF 64-bit LSB shared object, ARM aarch64, ...
> ```
> 
> Also note that instead of "go build then copy to bin" you can use `go install` for the `fyne` cmd.



> I think that your Go version is incorrect, and may be the source of confusion. Please double check with 'go version'.
> 
> > * **Go version:** 1.17
> 
> On my computer it works just fine
> 
> ```
> $ fyne package -os android/arm64 -appID io.fyne.hello -icon ../../theme/icons/fyne.png
> $ unzip hello.apk
> $ file lib/arm64-v8a/libhello.so
> lib/arm64-v8a/libhello.so: ELF 64-bit LSB shared object, ARM aarch64, ...
> ```
> 
> Also note that instead of "go build then copy to bin" you can use `go install` for the `fyne` cmd.

hello,
![Screenshot_20210705_190539_com termux](https://user-images.githubusercontent.com/19886504/124462693-8931c180-ddc4-11eb-830b-684fca2cfcce.jpg)

**Comment by andydotxyz** [comment]
Oh I see - you mean that you cannot build *on* Android arm64, not that you cannot build *for* Android arm64.

**Comment by DiskGetor** [comment]
> Oh I see - you mean that you cannot build _on_ Android arm64, not that you cannot build _for_ Android arm64.

Oh ha, very very sorry my bad English. If fyne supposed aarch64 ndk, we can build apk on Android mobile phone any time not use notebook or computer, it is very cool for us.thank you our teacher.

**Comment by andydotxyz** [comment]
Can you check if this is a problem for desktop builds as well?
Does `fyne package -os linux` complete successfully?

**Comment by DiskGetor** [comment]
> Can you check if this is a problem for desktop builds as well?
> Does `fyne package -os linux` complete successfully?

It work well

**Comment by DiskGetor** [comment]
> Can you check if this is a problem for desktop builds as well?
> Does `fyne package -os linux` complete successfully?

hello,how to go install fyne.io/fyne/v2/cmd/fyne with develop beach ?

**Comment by andydotxyz** [comment]
The easiest way is to check out the project to a convenient directory, then:
```
$ cd fyne/cmd/fyne
$ git checkout develop
$ go install
```

You can then confirm it installed correctly, as `fyne version` should report "(develop)".

**Comment by DiskGetor** [comment]
> 最简单的方法是检查项目的一个方便的目录，则：
> 
> ```
> $ cd fyne/cmd/fyne
> $ git checkout develop
> $ go install
> ```
> 
> 然后你可以确认它的正确安装，正如 `fyne version` 该报告"(发展)".



> The easiest way is to check out the project to a convenient directory, then:
> 
> ```
> $ cd fyne/cmd/fyne
> $ git checkout develop
> $ go install
> ```
> 
> You can then confirm it installed correctly, as `fyne version` should report "(develop)".

Thank you.  And another problem is :

1: how to set font size when mouse in and out on button text? If do this for tree,list,tab...all widget's text, will very cool.

2: how  to set a png as app background image?

**Comment by andydotxyz** [comment]
These questions have been asked and answered before, please check old issues and our documentation (for example https://github.com/fyne-io/fyne/issues/1343).
As @Jacalz has mentioned before GitHub issues is not a support community, if you want to ask for help please join the #fyne channel on gophers Slack or Discord servers.

**Comment by andydotxyz** [comment]
We have since found that android NDK is just not available for linux arm64, so you will need to use fyne-cross, sorry.

**Comment by ddkwork** [comment]
> We have since found that android NDK is just not available for linux arm64, so you will need to use fyne-cross, sorry.

no,please check this:

https://github.com/Lzhiyong/termux-ndk/releases

the SDK and ndk was worked on manjaro arm64

**Comment by andydotxyz** [comment]
I don't think that is an official Android distribution is it?
