### ISSUE TITLE
How to use Tree Widget to implement file system browser

### ISSUE THREAD

**Issue by llxwj** [fyne-io/fyne#2305]
The file system data is dynamic. After entering the directory, click on the subdirectory to continue to enter the next subdirectory,
Is there no programming model similar to MVC?

**Comment by llxwj** [comment]
https://github.com/fyne-io/fyne-x/blob/master/widget/filetree.go

**Comment by Jacalz** [comment]
How about https://github.com/fyne-io/fyne-x/blob/master/widget/filetree.go?

**Comment by llxwj** [comment]
Yes, 

> How about https://github.com/fyne-io/fyne-x/blob/master/widget/filetree.go?
