### ISSUE TITLE
How can we refresh a custom Widget properly?

### ISSUE THREAD

**Issue by daiwhea** [fyne-io/fyne#2316]
This is just a question. I need some helps with custom widget. Maybe the developer docs need some more deep introductions about the custom widget. Custom widget should be the only way for Some complex logic. The tutorial : [https://developer.fyne.io/tutorial/write-custom-widget](url) is not enough for some complex situations.

**My use case is:**
I need a keyboardGenius, which will be the background container for my app, and it will listen to the keyboard events. When it detected a keypress, it will popup another custom AutoComplete widget and **make the Entry in the AutoComplete widget focused without a click in it**.

**My problems are:**
1. If I hide the popup first, I can't show it via a keypress. The only way I can make it visible after a keypress is to resize the app window.
2. I don't know how to make the Entry in the popup focused.

**My questions are:**
1. If just some objects visible, should I return all the objects or just visible objects in Objects() method?
2. When and why the WidgetRenderer.Layout/Objects will be called? Can we force invoke it at some time after CreateRenderer() ?
3. How to refresh a custom widget properly? Or how to make a custom widget which can be refreshed properly?
4. I want an Entry focused, but seems there is only w.Canvas().Focus(Focusable) can do it. It's a pain to pass w.Canvas().Focus down to the widget need it. Can a widget request for focus easily?

**demo codes:**
```
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type GeniusPosition int

const (
	GeniusPositionCenter GeniusPosition = iota
	GeniusPositionTopLeft
	GeniusPositionTopRight
	GeniusPositionBottomLeft
	GeniusPositionBottomRight
)

type keyboardGenius struct {
	widget.BaseWidget
	geniusPosition GeniusPosition
	geniusObject   fyne.CanvasObject
	mainContent    fyne.CanvasObject
}

func NewKeyboardGenius(
	geniusPosition GeniusPosition,
	mainContent, geniusObject fyne.CanvasObject,
) *keyboardGenius {
	kg := &keyboardGenius{
		geniusPosition: geniusPosition,
		geniusObject:   geniusObject,
		mainContent:    mainContent,
	}
	kg.ExtendBaseWidget(kg)
	return kg
}

type keyboardGeniusRenderer struct {
	kg *keyboardGenius
}

func (kg *keyboardGenius) CreateRenderer() fyne.WidgetRenderer {
	r := &keyboardGeniusRenderer{
		kg,
	}
	// I need geniusObject invisible at first, after keypressed, it's visible
	kg.geniusObject.Hide()
	fmt.Println("CreateRenderer")
	return r
}
func (r *keyboardGeniusRenderer) Destroy() {}

func (r *keyboardGeniusRenderer) Layout(size fyne.Size) {
	fmt.Println(">>> enter Layout")
	if r.kg.geniusObject != nil && r.kg.geniusObject.Visible() {
		fmt.Println("  genius visible in Layout")
		genius := r.kg.geniusObject
		switch r.kg.geniusPosition {
		case GeniusPositionBottomRight:
			geniusMinSize := genius.MinSize()
			geniusMinSize.Width = 80
			fmt.Println("geniusMinSize", geniusMinSize)
			genius.Move(fyne.NewPos(size.Width-geniusMinSize.Width, size.Height-geniusMinSize.Height))
		}
	}
}

// MinSize returns the minimum size of the widget that is rendered by this renderer.
func (r *keyboardGeniusRenderer) MinSize() fyne.Size {
	return r.kg.mainContent.MinSize()
}

// Objects returns all objects that should be drawn.
func (r *keyboardGeniusRenderer) Objects() []fyne.CanvasObject {
	fmt.Println(">>> enter Objects")
	objs := []fyne.CanvasObject{r.kg.mainContent}
	// I want just return objects visible. I'm not sure is this right?
	if r.kg.geniusObject != nil && r.kg.geniusObject.Visible() {
		fmt.Println("   genius visible")
		objs = append(objs, r.kg.geniusObject)
	}
	return objs
}

func (r *keyboardGeniusRenderer) Refresh() {
}
func (e *keyboardGenius) Tapped(ev *fyne.PointEvent) {
	fmt.Println("mouseIn", ev)
}

func (e *keyboardGenius) FocusGained() {
	fmt.Println("Focus gained")
}
func (e *keyboardGenius) FocusLost() {
	fmt.Println("Focus lost")
}
func (e *keyboardGenius) TypedKey(key *fyne.KeyEvent) {
	fmt.Println("KeyEvent", key)
}
func (e *keyboardGenius) TypedRune(r rune) {
	fmt.Println("rune", r)
	// this won't work. it's still invisible.
	e.geniusObject.Show()
	// even with e.geniusObject.Refresh() it won't work
	e.geniusObject.Refresh()
	e.Refresh()
}

func main() {
	a := app.New()
	a.Lifecycle().SetOnEnteredForeground(func() { fmt.Println("focused") })
	w := a.NewWindow("Fyneui Test")
	w.Resize(fyne.NewSize(624, 428))
	runKeyboardGenius(w)
	w.CenterOnScreen()
	w.ShowAndRun()
}

func runKeyboardGenius(w fyne.Window) {
	mainContent := widget.NewLabel("mainContent")
	geniusContent := container.NewVBox(widget.NewLabel("Genius"), widget.NewEntry())
	kg := NewKeyboardGenius(
		GeniusPositionBottomRight,
		mainContent,
		geniusContent,
	)
	w.SetContent(kg)
	// key point.
	w.Canvas().Focus(kg)
}
```

Thanks for Any suggestions.

**Comment by andydotxyz** [comment]
To answer your questions:

1) Return all objects, only the visible ones will be drawn
2) The Objects is called when a widget is Refreshed, the Layout is called when it is resized. Calling these through forced methods is not supported but should never be needed.
3) Call myWidget.Refresh(). If your widget is not refreshing correctly perhaps you need to add some refresh logic into your widget? You can overload the Refresh method and call BaseWidget.Refresh() inside your widget.
4) No, a widget cannot request focus - it must be assigned by the canvas

I see that you have an empty `Refresh` method. This may be why things are not refreshing - as you are not telling Fyne what should change.

If you are trying to build some autocomplete popup then consider checking out the fyne-x `CompletionEntry` https://github.com/fyne-io/fyne-x/blob/master/widget/completionentry.go

**Comment by daiwhea** [comment]
```
I see that you have an empty Refresh method. This may be why things are not refreshing - as you are not telling Fyne what should change.
```
Thanks @andydotxyz 

Now I made it works. The popup show/hide works. But I have another question. When I clicked the popup Entry, then the keyboardGenius lost focus. How can I make keyboardGenius refocused again after pressed KeyEscape?

I'm try to figure out some more things. I'll feed back later, so let this issue keep open.

**Comment by andydotxyz** [comment]
To focus again use Canvas.Focus(…) as before.

Each issue should have one purpose, so let’s not keep it open. For random questions please consider connecting on Slack or Discord instead.
