### ISSUE TITLE
Add API to control cursor position in Entry

### ISSUE THREAD

**Issue by daiwhea** [fyne-io/fyne#2318]
### Describe the bug:
There is an Entry e, after e.SetText("xxx") and w.Canvas().Focus(e). The entry focused, but the cursor is at the beginning. Should we put the cursor at the content tail? Or can we set the cursor position? So we can type without moving cursor.

### To Reproduce:
Steps to reproduce the behaviour:
1. run demo code
2. cilck setText button
3. See cursor is at the content beginning.

### Screenshots:

https://user-images.githubusercontent.com/163152/125189644-ac002200-e26b-11eb-94b8-95c4ba655e54.mp4

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Fyneui Test")
	w.Resize(fyne.NewSize(624, 428))
	w.CenterOnScreen()
	entry := widget.NewEntry()
	w.SetContent(container.New(
		layout.NewFormLayout(),
		widget.NewButton("setText", func() {
			entry.SetText("wahaha")
			w.Canvas().Focus(entry)
		}),
		entry,
	))
	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 10.13.6
 - **Go version:** go1.16.5 darwin/amd64
 - **Fyne version:** v2.0.3-rc2.0.20210626204313-16a63520250f
 

Thanks.

**Comment by andydotxyz** [comment]
I don't think that setting the text should change the cursor position (unless it has to, like the text getting shorter).
Calling SetText is not the same as simulating typing (there is a test package, `test.Type` for example).
Perhaps this is a feature request for setting cursor position?

**Comment by daiwhea** [comment]
Yes, it should be titled as feature request for setting cursor position.

**Comment by andydotxyz** [comment]
This should be satisfied by `Entry.CursorRow` and `Entry.CursorColumn`, you can set these then call `Refresh()`
