### ISSUE TITLE
Allow some CanvasObjects to expand to fill available space inside Containers (VBox/HBoxes)

### ISSUE THREAD

**Issue by hkparker** [fyne-io/fyne#2322]
### Is your feature request related to a problem? Please describe:

I'd like to add widgets to a Container (specifically working with a VBox right now) and have some of them auto fill as the window is resized.  I find myself very limited without this.  For example, imagine:

```
+---VBox-------------+
|  +-------------+  |
|  |  HBox       |  |
|  +-------------+  |
|                   |
|  +-------------+  |
|  | Scroll      |  |
|  |             |  |
|  |             |  |
|  +-------------+  |
|                   |
|  +-------------+  |
|  | Entry       |  |
|  +-------------+  |
+-------------------+
```

I'd like to be able to have the `HBox` and `Entry` stay at their minimum allowed size, while having the `Scroll` (as well as the `VBox`) take up the rest of the available space as the window grows.  If ASCII doesn't suffice for this explanation I can write a little demo app.

I thought I could accomplish this by wrapping widgets in a `container.Max` but this does not appear to be the case within a Vbox or HBox.  In the above example, wrapping the Scroll in Max and the VBox in Max still results in the VBox taking up minimum space.

Running Fyne 2.0.3 (and tested with the head of master) on Arch Linux.  Go 1.16.

### Is it possible to construct a solution with the existing API?

Not that I'm aware of.  Splits will default to giving each widget equal space and letting the user drag to resize, but the goal is for certain widget to take as much space as possible, and all others to default to as little as possible, within a non-user-adjustable box.

### Describe the solution you'd like to see:

Perhaps some property on the BaseWidget, like an `.AutoExpand()` that can be called on the widgets that should fill as much space as possible.

**Comment by jsawo** [comment]
I believe that this behavior can currently be implemented with `BorderLayout`:

```
+---Border----------+
|  +-------------+  |
|  |  HBox       |  |
|  +-------------+  |
|                   |
|  +--Scroll-----+  |
|  |  VBox       |  |
|  |             |  |
|  |             |  |
|  +-------------+  |
|                   |
|  +-------------+  |
|  | Entry       |  |
|  +-------------+  |
+-------------------+
```

Something like this:
```go
myContainer := container.New(
	layout.NewBorderLayout(topElement, bottomElement, nil, nil),
	topElement,
	bottomElement,
	container.NewVScroll(
		container.NewVBox(
			canvas.NewText("test", &color.Black),
			...
			canvas.NewText("test", &color.Black),
		),
	),
)
```

**Comment by andydotxyz** [comment]
@jsawo is correct, the container/layout controls the size of widgets inside them.
VBox is designed so that all items inside are packed at the minimum height, with the same width (full-width), so you are seeing the correct behaviour.

You can see previews up at https://developer.fyne.io/started/layouts (note which fill the space and which don't).

**Comment by hkparker** [comment]
Awesome, thank you!  My apologies for missing something in the documentation.

**Comment by hkparker** [comment]
Ok I've been making good use of all the layout options but ran into a situation I can't figure out how to achieve with the existing layouts.  I want to have two containers that are allowed to grow as much as is supported by the window, but have them stacked together at the top of the window.  Sort of like a grid with one column and two rows, but rather than having them spaced evenly, have them stuck together at the top.  Perhaps I'm not being creative enough with the current layouts, is such a thing currently possible?

**Comment by andydotxyz** [comment]
That sounds like `container.NewVBox`

**Comment by hkparker** [comment]
Ah yeah sorry I forgot part of the explanation.  Like a VBox, but I want Scrolls in there that don't always shrink to their MinSize, but instead sorta apply "pressure" to the box.  So, thinking about what this means in Fyne, I guess what I'm really asking for is for Scroll's MinSize to be larger if the overall size of the window supports it.

I think I know enough Fyne now to try implementing this myself.  I'll override Scroll to have the MinSize inspect the window its in and if there's available room to grow, it can expand its MinSize until it no longer needs to scroll.

I'll report back here when I give this a try and post an example if it goes well.

**Comment by andydotxyz** [comment]
You should never prop an interface open by larger MinSize values - this stops the UI from scaling well to smaller screens. Your approach would also stop the user from making the window smaller after resizing it to be large.
If you want item `a` to be at top and `b` to take up the rest of the space then a `Border` is the approach `container.NewBorder(a, nil, nil, nil, b)`

**Comment by andydotxyz** [comment]
@hkparker You should also see:

> You can see previews up at https://developer.fyne.io/started/layouts (note which fill the space and which don't).

When designing your UI you must think about where you want spare space to be allocated. Once you know that it should be easy.

**Comment by hkparker** [comment]
I feel pretty comfortable with the layouts at this point, I'm pretty sure what I'm imagining is just impossible.  It's sorta hard to explain though, it's like having a stack of `Max` containers where the content is justified to the top.  You're right, my earlier suggestion would mean that once the window containing one of these scrolls was resized to get larger, it could never get smaller.  That won't do.  It's fine though, I can come up with a good UX using the existing layouts so there's really nothing to do here.

**Comment by andydotxyz** [comment]
Justification is not the same as sizing. A max container components will fill the space - where the content is positioned is up to the widget.
Beyond this I don't know what to suggest, perhaps a picture will clarify what you mean and/or describe what is not seeming to be possible once you have tried the different approaches suggested.
You can overlay items using Max and top align with VBox, if you use them in the right combination what I think you are describing should be possible.

**Comment by hkparker** [comment]
Ok, here it goes... this is going to be long, I'm sorry :laughing: 

Let's start with a simple VScroll.

```go

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	demo := app.New()
	window := demo.NewWindow("Demo")
	window.SetMaster()

	content := container.NewVScroll(
		container.NewVBox(
			widget.NewLabel("thing 1"),
			widget.NewLabel("thing 2"),
			widget.NewLabel("thing 3"),
			widget.NewLabel("thing 4"),
			widget.NewLabel("thing 5"),
			widget.NewLabel("thing 6"),
		),
	)

	window.SetContent(content)
	window.Show()

	demo.Run()
}
```

We get a window, and when we take that down to it's minimum height we see this:

![fyne1](https://user-images.githubusercontent.com/2918615/126592758-52796f5d-0590-45a3-9123-c476c8040060.png)

Cool.  We can drag it down and the scroll expands, because the scroll widget is taking up as much space as it is given.

![fyne2](https://user-images.githubusercontent.com/2918615/126592808-782930da-ac50-466a-98dc-3519b6ccb02d.png)

Eventually, we expand the window all the way and we can see everything and the scroll bar disappears.

![fyne3](https://user-images.githubusercontent.com/2918615/126592848-362affe3-7f44-469b-acb6-3b86a27f54a4.png)

So far so good.  But now I want _two_ scrolls, one above the other, that do the same thing.

Let's try putting them in a VBox.

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	demo := app.New()
	window := demo.NewWindow("Demo")
	window.SetMaster()

	content := container.NewVBox(
		container.NewVScroll(
			container.NewVBox(
				widget.NewLabel("thing 1"),
				widget.NewLabel("thing 2"),
				widget.NewLabel("thing 3"),
				widget.NewLabel("thing 4"),
				widget.NewLabel("thing 5"),
				widget.NewLabel("thing 6"),
			),
		),
		container.NewVScroll(
			container.NewVBox(
				widget.NewLabel("thing 7"),
				widget.NewLabel("thing 8"),
				widget.NewLabel("thing 9"),
				widget.NewLabel("thing 10"),
				widget.NewLabel("thing 11"),
				widget.NewLabel("thing 12"),
			),
		),
	)

	window.SetContent(content)
	window.Show()

	demo.Run()
}
```

At the minimum height...

![fyne4](https://user-images.githubusercontent.com/2918615/126593152-d157a070-950a-4747-a2db-89725e801eae.png)

...as expected.  And when I drag the window out more...

![fyne5](https://user-images.githubusercontent.com/2918615/126593179-c004756a-c04f-4431-bc5d-6e1e2dbceadd.png)

well that's not what I wanted!  They both stayed at their minimum height.  But of course they did, that's what a VBox does, it keeps each container at it's minimum height and stacks them, while letting them expand horizontally.

Hmm.  I can get the "lower" scroll to expand though, by using a border layout!

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	demo := app.New()
	window := demo.NewWindow("Demo")
	window.SetMaster()

	scrollOne := container.NewVScroll(
		container.NewVBox(
			widget.NewLabel("thing 1"),
			widget.NewLabel("thing 2"),
			widget.NewLabel("thing 3"),
			widget.NewLabel("thing 4"),
			widget.NewLabel("thing 5"),
			widget.NewLabel("thing 6"),
		),
	)

	scrollTwo := container.NewVScroll(
		container.NewVBox(
			widget.NewLabel("thing 7"),
			widget.NewLabel("thing 8"),
			widget.NewLabel("thing 9"),
			widget.NewLabel("thing 10"),
			widget.NewLabel("thing 11"),
			widget.NewLabel("thing 12"),
		),
	)

	content := container.New(
		layout.NewBorderLayout(scrollOne, nil, nil, nil),
		scrollOne,
		scrollTwo,
	)

	window.SetContent(content)
	window.Show()

	demo.Run()
}
```

At the minimum size, we're still looking the same

![fyne6](https://user-images.githubusercontent.com/2918615/126593465-14014ac2-1e42-4807-a1dd-5e33f162e9f1.png)

We start to expand and, as expected, only the "bottom" one (really the "central" one) expands.  What I'm looking for is for both of them to expand equally.

![fyne8](https://user-images.githubusercontent.com/2918615/126593537-abe804df-ba7a-4919-93b8-2c4697812cc7.png)

Finally when we're all the way expanded the bottom one is expanded all the way and it's still "glued" to the top (because the top one is the top border, and the bottom one is just taking up the available space).

![fyne9](https://user-images.githubusercontent.com/2918615/126593724-50d8d371-263c-41ea-9d51-4005ad91a995.png)

Ok, I got it.  Grid!  I'll make a grid with one column.

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	demo := app.New()
	window := demo.NewWindow("Demo")
	window.SetMaster()

	scrollOne := container.NewVScroll(
		container.NewVBox(
			widget.NewLabel("thing 1"),
			widget.NewLabel("thing 2"),
			widget.NewLabel("thing 3"),
			widget.NewLabel("thing 4"),
			widget.NewLabel("thing 5"),
			widget.NewLabel("thing 6"),
		),
	)

	scrollTwo := container.NewVScroll(
		container.NewVBox(
			widget.NewLabel("thing 7"),
			widget.NewLabel("thing 8"),
			widget.NewLabel("thing 9"),
			widget.NewLabel("thing 10"),
			widget.NewLabel("thing 11"),
			widget.NewLabel("thing 12"),
		),
	)

	content := container.NewGridWithColumns(
		1,
		scrollOne,
		scrollTwo,
	)

	window.SetContent(content)
	window.Show()

	demo.Run()
}
```

Let's see...

![fyne10](https://user-images.githubusercontent.com/2918615/126594141-634dde34-c161-4856-8894-b923e18200dc.png)

Off to a good start.

![fyne11](https://user-images.githubusercontent.com/2918615/126594158-7a704662-ac04-4d33-99d6-b8dd5396eb47.png)

Off to a GREAT start...

![fyne12](https://user-images.githubusercontent.com/2918615/126594184-ce78923a-cf50-4e1b-9c9a-efbdcd23ad09.png)

Ah, crap.  The bottom one isn't "glued" to the top one.  They are being spaced evenly, because of course they are, because that's what a grid does!

What I've been trying to find all this time is if it's possible to vertically arrange _multiple_ VScrolls such that they expand (and contract) with the window size as needed, but still stay vertically stacked and don't space out like a grid.

Apologies for the long winded story but this was super hard to explain, and hopefully what I'm looking for is clear now.

**Comment by andydotxyz** [comment]
There is no concept of a maximum size, so the scroll cannot communicate upward that its content is all visible.
If that is what you want to do it will need to be a custom layout that interrogates the scroll child to see what height it's content is.
This problem is scroll container specific and does not relate to how any other objects work.

**Comment by hkparker** [comment]
Yeah, definitely a scroll-only behavior concern.  I haven't written a custom layout yet but when I need this behavior I'll definitely give that a try and post my results!
