### ISSUE TITLE
Feature Request: option to reverse the behavior of enter/shift+enter in MultiLineEntry

### ISSUE THREAD

**Issue by hkparker** [fyne-io/fyne#2323]
### Is your feature request related to a problem? Please describe:

Most chat applications I'm used to working with bind the enter key to sending a message.  Multi-line messages are achieved by holding the shift key while pressing enter.  The default behavior of MultiLineEntry is the opposite: the enter key creates a newline, and shift+enter actives `OnSubmitted`.

Perhaps this is a fine default, but I'd like the option to reverse it.

### Is it possible to construct a solution with the existing API?

No, I believe [this line](https://github.com/fyne-io/fyne/blob/9b5a176fe1dc80beae72a3074d0d5cd2b409637c/widget/entry.go#L573) would need to be altered to the following condition to reverse the behavior: `!selectDown && onSubmitted != nil`.

### Describe the solution you'd like to see:

Either an exported variable on the struct that lets a user assign a behavior constant (say `entry.SubmitCondition = fyne.SubmitOnEnter` vs. `entry.SubmitCondition = fyne.SubmitOnSelectEnter`), or some function that lets the user pass in a function that determines the submit condition based on the state of the entry and the key (`entry.SubmitOn(func(*widget.entry, *fyne.KeyEvent) {})`

If either of these suggestions are approved I'd be happy to follow up with a quick PR, this is an easy one.

**Comment by andydotxyz** [comment]
I don't think that this is the sort of thing that should be configured in applications.
Users have no way of discovering what configuration is used and so no hints about what to expect.
If our defaults are wrong we can fix them, if not then they should remain.

We based the current code on usage of Slack, other examples as you hinted at could be helpful.

**Comment by hkparker** [comment]
Oh ok, I assumed there was some demand for this behavior and preserving it was important.  For example, you might want chat entries to automatically submit on enter, but say on a window where you are editing your bio, you would only want to submit when the "save" button was pressed.  I figured the behavior could be hinted to the user based on context, even if they can't directly discover it, and as a developer I'd like to have the option to use both styles.  If that's not the case than it's a single character change, just reversing the check of `selectDown`.  That will have MultiLineEntry behaving like slack or any other chat application's chat message entry.

**Comment by hkparker** [comment]
This is pretty hacky but if we wanted to reverse the behavior, and a user wanted the enter key to not behave as submit, they could set the onSubmitted function to just write a newline character into the entry's text.  That would let a developer achieve the flow I mentioned above while still having a non-configurable submit behavior for MultiLineEntry.

**Comment by hkparker** [comment]
Actually, looking closer, if no `OnSubmitted` is set then hitting enter on a MultiLineEntry will just add a newline, so the above suggestion is nonsense, and changing the behavior seems like a good idea.

I've opened #2326, happy to follow up there if there's anything else you'd like to see in the PR.

**Comment by andydotxyz** [comment]
A mentioned in the PR this was deemed to be the right behaviour.
This is because single and multiple lines have different expectations.
The confusion comes when looking to make an Entry that starts as single line but grows - as this is custom code then custom Enter/OnSubmit handling would be needed also.
