### ISSUE TITLE
"Show Another Windows" shows nothing

### ISSUE THREAD

**Issue by cvq** [fyne-io/fyne#2328]
Hi everybody,
My app has two windows: "Main Windows" and "Another Windows". My goal:
1. Run app, it opens Main Windows with a button "Show Another Windows"
2. Click this button will open "Another windows" and Hide the Main Windows.
3. Close "Another Windows" (click "X") will return back to "Main Windows"
This is ok so far.
4. **When I try to click again "Show Another Windows" button, there is nothing on the screen**.

My platform:
- Windows 11
- Golang 1.16.6
- IDE: VS code
My code:
var (
	a               fyne.App
	mainW, anotherW fyne.Window
)
func main() {
	a = app.New()
	mainW = a.NewWindow("Main windows")

	anotherW = fyne.CurrentApp().NewWindow("Another Windows")

	go anotherW.SetOnClosed(func() {
		mainW.Show()
	})

	showAnotherWindowsButton := widget.NewButtonWithIcon("Show Another Windows", theme.ComputerIcon(), func() {
		mainW.Hide()
		anotherW.Show()
	})

	content := container.New(layout.NewHBoxLayout(), showAnotherWindowsButton)
	mainW.SetContent(content)
	mainW.ShowAndRun()
}
 
Please help to fix.
Thank you.

**Comment by fpabl0** [comment]
Hello @cvq, "anotherW" is not shown again because when the user close a windows it is destroyed (it is not the same when you just hide it), so if you would need to create a new "anotherW" also inside your button callback.

**Comment by cvq** [comment]
Thank you fabl0

**Comment by cvq** [comment]
Hi fpabl0,
Hi fpabl0,
As you said, I add new func:
func createAnotherW() {
	anotherW = fyne.CurrentApp().NewWindow("Another Windows")
}
But when I Close "Another Windows", there is nothing showing as before.

**Comment by fpabl0** [comment]
What I meant before is that you would need to create the window inside the button callback, something like this:
```go
func main() {
	a := app.New()
	mainW := a.NewWindow("Main windows")

	showAnotherWindowsButton := widget.NewButtonWithIcon("Show Another Windows", theme.ComputerIcon(), func() {
		mainW.Hide()
                 // create anotherW inside the button callback
		anotherW := fyne.CurrentApp().NewWindow("Another Windows")
		anotherW.SetOnClosed(func() {
			mainW.Show()
		})
		anotherW.Resize(fyne.NewSize(200, 200))
		anotherW.CenterOnScreen()
		anotherW.Show()
	})

	content := container.New(layout.NewHBoxLayout(), showAnotherWindowsButton)
	mainW.SetContent(content)
	mainW.ShowAndRun()
}
```

**Comment by cvq** [comment]
Thank you very much **fpabl0**.
I got it.

**Comment by andydotxyz** [comment]
Thanks for the answer here @fpabl0 :).
If the window should be re-used you could make use of the `SetCloseIncercept` and then you could ask the window to `Hide()` instead of `Close()`. However for most cases the solution provided above is the way to go.
