### ISSUE TITLE
Feature Request: widget.NewSelect with TextAlignment for options

### ISSUE THREAD

**Issue by michael-nischt** [fyne-io/fyne#2329]
### Is your feature request related to a problem? Please describe:

There's no way to set the text alignment for options for a `widget.Select` similar to a label. It seems to me centering the options would be a common use case.

### Is it possible to construct a solution with the existing API?

I'm not sure. I might be but if only with considerable effort? (for something which should trivial)

### Describe the solution you'd like to see:

[widget.Select](https://developer.fyne.io/api/v2.0/widget/select.html) with a `Alignment fyne.TextAlign` field similar to [widget.Label](https://developer.fyne.io/api/v2.0/widget/label.html).

(feature request as recommended on [twitter](https://twitter.com/Fyne_io/status/1412052734791008257))

**Comment by andydotxyz** [comment]
I guess this could be added. We agreed that `Label` should have this but `Entry` should not.
As a result the `SelectEntry` should not support it either (which is OK as it extends `Entry`). So should `Select`? I suppose there is not a strong reason not to.

**Comment by michael-nischt** [comment]
Thx for details. I can totally see a load of problems / edge cases with text input (`Entry` + `SelectEntry`). 
If you don't expected / notice any problems for `Select`, I would appreciate the addition. 🙂

**Comment by andydotxyz** [comment]
There is a proposed implementation in the PR linked above @michael-nischt

**Comment by michael-nischt** [comment]
awesome @andydotxyz ! looks great to me but ofc I lack a lot of detail knowledge. :relaxed:

**Comment by andydotxyz** [comment]
This is now landed on `develop` branch if you'd like to use it before 2.1 release
