### ISSUE TITLE
[Suggestion] Kivy

### ISSUE THREAD

**Issue by mantielero** [fyne-io/fyne#233]
Just to point out [Kivy](https://kivy.org/#home) as an inspiration. This is a python toolkit that works on mobile also and I think it follows a similar approach as Fyne.

The code probably cannot be reused, but I would check their ideas, given that it is very mature.

**Comment by andydotxyz** [comment]
What in particular do you like about their approach?
With so much there it's hard to know where to start :)

**Comment by mantielero** [comment]
First, bear in mind I am not a professional developer so I will probably say many stupid things :S.

Kivy started as Natural User Interface toolkit to develop mostly games. But its flexibility has demostrated that is good for normal user interfaces also.

I will start with the "bad thing" about kivy. For me, it is a pity not having kivy as a clear C library with bindings and wrapping in Cython. That would enable using the a C Kivy library directly from Go or Julia.

The good things about Kivy in my opinion is its flexibility and how easy it is to use it and expand it. More about this later.

Nonetheless, my suggestion was more in the sense of reimplementing in Go the Cython bits for the UI. I got the feeling that this might be easier than rethinking a complete UI from scratch. Given that Go is not OOP, there is no need for the wrapping into Python objects.

Kivy has the [KV language](https://kivy.org/doc/stable/guide/lang.html) which is much easier than HTML to describe an UI (while you still can describe the UI programmatically).

By reimplementing Kivy UI bits in go, another advantage would be reusing "other" widgets already developped for kivy which are mostly defined in the KV language plus normal python. For example, it would be brilliant it we were able to reuse [KivyMD](https://github.com/HeaTTheatR/KivyMD), which are Material Design widgets mostly defined with the KV language. You can see how KivyMD widgets look [here](https://github.com/HeaTTheatR/KivyMD/wiki/MDUserAnimationCard). I have used them in the desktop, but they follow a mobile first design and they are reactive. 

> I think somebody asked in the issues for an [accordeon](https://github.com/HeaTTheatR/KivyMD/wiki/MDAccordionListItem) widget.

There is some space for improvement (for both kivy and fyne). I recommend reading [Elm architecture](https://guide.elm-lang.org/architecture/), [here](https://dennisreimann.de/articles/elm-architecture-overview.html). Basically the UI is consequence of a defined state. The state is only modified (in Elm architecture, you get a complete new state, because the state is immutable) by means of update functions. The UI is calling those update functions. This is more clear looking at this [javascript example](https://medium.com/javascript-inside/elm-architecture-for-react-951b383fcd65).

In go, it would be nice to have something like the following for the state:

```go
type formstate struct {
  name string `fyne:"entry_name"`,
  age   int   `fine:"entry_age"`
}
```
The UI defined by means of something similar to the KV language. The tagging atttached to the struct could be use as Id's for the entries defined in the KV language. The widgets would call update functions that would update the structs.

**Comment by andydotxyz** [comment]
There are a lot of nice things in there but I don't really see Fyne going with a scripted UI definition. We picked a typed language with a strong API so that the APIs would be used to create, lay out, and control the widgets and user interfaces.

Data binding definitely should be done some how, this is tracked in #135 and we want to make sure it is possible to dynamically drive widgets without losing the strong typing and unit testable approach we have taken this far.

Does that make sense, or do you think I have missed something from your suggestion?

**Comment by mantielero** [comment]
Yes it does. Thanks for your explanations.

**Comment by andydotxyz** [comment]
Thanks, closing this issue as I don't think there are any actionable points remaining on this ticket that are not tracked elsewhere.
