### ISSUE TITLE
How to adjust table row height for multiline text?

### ISSUE THREAD

**Issue by skmonir** [fyne-io/fyne#2334]
I was trying to implement table with only texture value. But the table cell has text bleeding issue for multiline text. How to solve this?

<img width="730" alt="Screenshot 2021-07-21 at 7 28 20 PM" src="https://user-images.githubusercontent.com/15253593/126497035-a2a758dd-9374-40f9-8266-7ba6bf805ae3.png">

**Comment by andydotxyz** [comment]
Table (like List and Tree) are designed for presentation of large datasets and to do so it limits to homogeneous widgets, i.e. all the same size.
At this time to achieve the speed each row therefore is the same size.
In a future version we may find a way to allow individual rows to expand without slowing the overall calculations.

**Comment by williambrode** [comment]
Yeah, this has been a challenge for me as well.  I'm trying to find a workaround at least - I guess I could construct the table and a page counter and swap out the table each time they move to the next page?

But I assume there is a way to make a template object with a minimum height that is large enough to handle the max multiline text value right?  Guess I'll post my solution if I figure it out.

**Comment by williambrode** [comment]
Okay, using this as my template expanded the height of the rows to 3 lines of text:
```
return widget.NewLabel("1\n2\n3")
```
Then you can adjust the column length of each column with:
```
t.SetColumnWidth(0, 500)
```
So this is a good enough workaround for what I'm doing.  It would be cool to resize the height dynamically but I understand why that's more difficult.

**Comment by andydotxyz** [comment]
Yup, the template cell sets the standard size as you say.

**Comment by Jacalz** [comment]
I think the question has been answered. Closing.

**Comment by andydotxyz** [comment]
For anyone following, there is now a `Table.SetRowHeight` call
