### ISSUE TITLE
Delay to show message

### ISSUE THREAD

**Issue by cvq** [fyne-io/fyne#2335]
Hi all, 
My goal: If there is an error in my app, I want to:
- show error message
- and then terminate the app.

My code:
````
err := errors.New("error")
if err != nil {
    dialog.ShowError(err, w)    
    os.Exit(1)
}
````
But there is no error message showing

I modified my code:
````
err := errors.New("error")
if err != nil {
    dialog.ShowError(err, w)
    time.Sleep(3 * time.Second)
    os.Exit(1)
}
````
Now the app shows the message before Quit
My question is: Adding delay using time.Sleep is correct way?
Thank you

**Comment by andydotxyz** [comment]
To add a delay time.Sleep is correct. However in this instance surely you want to know that the user read the message? Using the 'dialog.SetOnClosed' is probably more desirable https://developer.fyne.io/api/v2.0/dialog/dialog.html.

Also note that app.Quit may not operate on mobie devices where lifecycle is controlled by the operating system.

**Comment by cvq** [comment]
Thank you **andydotxyz**. 
I try using **SetOnClosed**, but not succeed. 
Here is my code:
````
err := errors.New("error")
d := dialog.NewError(err, w)
	d.Show()
	d.SetOnClosed(func() {
		time.Sleep(3 * time.Second)
	})
os.Exit(1)
````
Can you fix for me.
Thank you.

**Comment by andydotxyz** [comment]
```
err := errors.New("error")
d := dialog.NewError(err, w)
	d.Show()
	d.SetOnClosed(func() {
		os.Exit(1)
	})
```

**Comment by cvq** [comment]
Thank you so much **andydotxyz**
