### ISSUE TITLE
canvas.ImageFillOriginal causing the window to be non-responsive

### ISSUE THREAD

**Issue by notAxion** [fyne-io/fyne#2337]
### Describe the bug:

when I have an image in `canvas.ImageFillOriginal` mode, possibly with the `canvas.NewImageFromFile`  (cause with `canvas.NewImageFromResource` it works fine)
**Resizing the window doesn't work as expected**
sometimes if the image is around or bigger than 1080p the window just stay not responsive and goes to not-responding window and never recovers
for smaller picture like 500x300 the window stays responsive and works as expected for some time but if i try to resize the window couple of time it goes to not-responding window as well

### To Reproduce:
Steps to reproduce the behaviour:
1. i was trying `canvas.NewImageFromFile` from [this](https://developer.fyne.io/tour/canvas/image.html) tour example
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Image")

	// image := canvas.NewImageFromResource(theme.FyneLogo())
	// image := canvas.NewImageFromURI(uri)
	// image := canvas.NewImageFromImage(src)
	// image := canvas.NewImageFromReader(reader, name)
	image := canvas.NewImageFromFile("space.jpg")
	image.FillMode = canvas.ImageFillOriginal
	w.SetContent(image)

	w.ShowAndRun()
}

```
2. resizing the window doesn't work as expected specially the corner ones

### Screenshots:

![image](https://user-images.githubusercontent.com/67577744/126678200-faf51093-756a-4673-96b5-6a301370d7a9.png)

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:**  Version - 21H1 Build - 19043.1110
 - **Go version:**  go1.16 windows/amd64
 - **Fyne version:**  v2.0.3

**Comment by andydotxyz** [comment]
Fix is on `release/v2.0.x` for testing.
