### ISSUE TITLE
Can you implement a port that can display same ui by remote webbrowser

### ISSUE THREAD

**Issue by runsys** [fyne-io/fyne#2342]
Can you implement a port that can display same ui by remote webbrowser

**Comment by andydotxyz** [comment]
Is this a duplicate of the request for a driver to display a Fyne app? #1646

**Comment by Jacalz** [comment]
This looks very much like a duplicate issue requesting html/css support for showing websites inside the ui. It is also an invalid feature request as it doesn't use the issue templates.

**Comment by andydotxyz** [comment]
Not convinced they want to show a website inside the UI - I think they want the UI inside a website...

**Comment by andydotxyz** [comment]
It’s a duplicate of one or the other :) and no update so closing
