### ISSUE TITLE
TextGrid - How to keep the bottom text displayed

### ISSUE THREAD

**Issue by wsndshx** [fyne-io/fyne#2343]
I use TextGrid to simulate the output of the terminal, which is the code I use: 

```go
for {
	// Gets the contents of the log output to the file.
	log, err := fs.ReadFile(core.LogFS, "log")
	if err != nil {
		dialog.ShowError(err, myWindow)
		return
	}

	// Display the content on the analog terminal.
	Terminal.SetText(string(log))
	time.Sleep(time.Duration(1) * time.Second)
}
```
However, there is a problem, that is, when the output log is out of the window range, it cannot automatically scroll down to the last line, it can only be scrolled manually by the user.

How should I keep the analog terminal always displaying the last line?

**Comment by andydotxyz** [comment]
I’m guessing you have put it in a ScrollContainer? After setting longer text try caking `Scroller.ScrollToBottom()`

**Comment by wsndshx** [comment]
> I’m guessing you have put it in a ScrollContainer? After setting longer text try caking `Scroller.ScrollToBottom()`

Oh, thank you. After I did what you said, it succeeded.
