### ISSUE TITLE
Use atomics for internal data items

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2359]
### Is your feature request related to a problem? Please describe:

It could be a good idea to try and use atomic instructions for data bindings where we have internal control of the variables, i.e. not binding to external ones. This should allow us to get rid of a lot of slow mutexes and decrease lock contention; resulting in better performance.

### Is it possible to construct a solution with the existing API?

It should theoretically be possible. The standard library is currently lacking atomic functions for a lot of types, so we might want to either use https://pkg.go.dev/go.uber.org/atomic or wait until more are implemented in the standard library. I think the latter is the best solution as there is talk about expanding the standard library, see https://github.com/golang/go/discussions/47141#discussioncomment-994417.

### Describe the solution you'd like to see:

Replacing mutexes with atomics where it makes sense and can be done in a clean way.

**Comment by Jacalz** [comment]
@changkun Is this something that you would be interested in looking at? If it even is possible (if it isn't we can of course close this)?

**Comment by changkun** [comment]
Thanks for CC me on this. Yes, I've tried many different changes lately that switch from mutex to atomics because of #2509. Uber's atomic package is an option however as it is an external dependency and the standard library is also aiming for that support (although I think it won't happen at least before 1.19), it might not be necessary to use as we already have `atomic.Value`.

The current problem for me is I don't know if we could send PRs incrementally for this or should I combine all changes in a single PR because this will also be a large change although it is an internal change. More suggestions on this would be appreciated. Otherwise, I could send my private changes incrementally soon.

**Comment by Jacalz** [comment]
I think it could make sense in one PR with different commits separating out parts of the change but I don't know what would be desired. Perhaps @andydotxyz has an opinion?

**Comment by changkun** [comment]
For example: https://github.com/fyne-io/fyne/compare/develop...changkun:internalAtomics?expand=1

**Comment by Jacalz** [comment]
Ah, I see what you meant now. I think you might have misinterpreted this issue. It was specific to the data bindings where they are not linked to an external data source, i.e. internal data bindings.

**Comment by changkun** [comment]
Only inside data/binding? That's a simple change. I can send a PR soon.

**Comment by Jacalz** [comment]
Looking at your proposed changes. How about splitting it into three different PRs? One for data bindings (which can neatly close this), one for the `internal/` packages and lastly one for everything else?

**Comment by changkun** [comment]
> Looking at your proposed changes. How about splitting it into three different PRs? One for data bindings (which can neatly close this), one for the `internal/` packages, and lastly one for everything else?

Sure I can continue the separation of the rest changes into two parts, they remain large changes. For instances:

- internal stuff: https://github.com/fyne-io/fyne/compare/develop...changkun:internalAtomic?expand=1
- the rest: https://github.com/fyne-io/fyne/compare/develop...changkun:pubAtomic?expand=1

Furthermore, there may be more changes that are not yet included, which are under experiment and will definitely be other PRs than these. Should I send the existing two?

**Comment by Jacalz** [comment]
I personally think that it's sensible to do it that way but I don't know what preference the others have on the matter.

**Comment by andydotxyz** [comment]
Agreed, sounds sensible.
When the binding one is landed I guess that is a good sign for the others to have PRs opened :).

**Comment by changkun** [comment]
Close because this is resolved in develop branch.
