### ISSUE TITLE
Race condition preventing to show an icon widget after window creation?

### ISSUE THREAD

**Issue by amo13** [fyne-io/fyne#2360]
### Describe the bug:
I try to run a few initializations before showing the actual content of my app. On an initialization screen (window content) I would like to show the success or failure of the initialization steps with an icon. In the code below, you can see that for the first step which checks for an internet connection.
I've noticed that sometimes the icon would show and sometimes it would not. I added a few seconds sleep so we can make the behavior more apparent. If we put the sleep statement outside of the goroutine (e.g. right after it), the icon will show up. 

I found the issue #1028 but I am not sure if this is related or not.

Is there a way to solve or work around this? Or would another approach to my initialization screen be better?

Any help would be greatly appreciated. I am still very new to go and fyne was one main reason I chose to learn go :)

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"

	"fmt"
	"net/http"
	"time"
)

var a fyne.App
var w fyne.Window

var Icon_success_internet *widget.Icon
var Icon_failure_internet *widget.Icon

func initScreen() fyne.CanvasObject {
	Lbl_init_internet := widget.NewLabel("Internet connection")
	Icon_success_internet = widget.NewIcon(theme.ConfirmIcon())
	Icon_success_internet.Hide()
	Icon_failure_internet = widget.NewIcon(theme.CancelIcon())
	Icon_failure_internet.Hide()
	Container_init_internet := container.NewHBox(
		layout.NewSpacer(), Icon_success_internet, Icon_failure_internet,
		Lbl_init_internet, layout.NewSpacer(),
	)

	return container.NewCenter(Container_init_internet)
}

func StatusCode(url string) (code string, err error) {
	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	return resp.Status, nil
}

func initApp() (bool, error) {
	status_code, err := StatusCode("https://raw.githubusercontent.com/fyne-io/fyne/master/README.md")
	// This <nil> print makes it visible in the terminal when the goroutine has come this far
	fmt.Println(err)
	if err != nil {
		return false, err
	}
	if status_code == "200 OK" {
		Icon_success_internet.Show()
	} else {
		Icon_failure_internet.Show()
		return false, nil
	}
	Icon_success_internet.Refresh()

	return false, nil
}

func main() {
	a = app.New()

	w = a.NewWindow("Test")
	w.SetMaster()

	w.Resize(fyne.NewSize(692, 272))
	w.SetFixedSize(true)

	w.SetContent(initScreen())

	go func() {

		// Put this Sleep after this goroutine
		// and the icon shows up
		time.Sleep(3*time.Second)

		success, err := initApp()
		if err != nil {
			fmt.Println(err)
		}
		if success {
			// This is where I would simply change the window content
			// w.SetContent(mainScreen())
		}
	}()

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Arch Linux
 - **Version:** 5.10.53
 - **Go version:** 1.16.6
 - **Fyne version:** 2.0.4

**Comment by andydotxyz** [comment]
This does not look like a race condition to me. When you hide / show elements the container that they are within needs to be updated (because hidden items are not included in the layout). There are two solutions.

1) Use the reference to the parent container and refresh it (`Container_init_internet.Refresh()`)
2) Use one icon but change the `Resource` directly when the icon is found.

Option 2 is preferable as it is far faster (layout code can be slow).
Something like the following:

Change the creation of your layout to:
```
var Icon_internet *widget.Icon

func initScreen() fyne.CanvasObject {
	Lbl_init_internet := widget.NewLabel("Internet connection")
	Icon_internet = widget.NewIcon(nil) // no icon resource to start
	Container_init_internet := container.NewHBox(Icon_internet, Lbl_init_internet)

	return container.NewCenter(Container_init_internet)
}
```
(you don't need the spacers because you are using the `Center` container.

and the status read code to:
```
	if status_code == "200 OK" {
		Icon_internet.SetResource(theme.ConfirmIcon())
	} else {
		Icon_internet.SetResource(theme.CancelIcon())
	}

```

**Comment by andydotxyz** [comment]
Closing as not an issue

**Comment by amo13** [comment]
Ah, amazing! Thank you so much for your friendly and fast response!
That was very helpful.
