### ISSUE TITLE
How to get "fyne" to get hwnd under windows 

### ISSUE THREAD

**Issue by qianniancn** [fyne-io/fyne#2363]
I want to get hwnd without changing the fyne code

**Comment by andydotxyz** [comment]
Sorry, we don't expose OS window access, it would break the cross-platform guarantee of our code.
If there is a feature you are struggling to complete without it maybe we can help with that instead?

**Comment by qianniancn** [comment]
@andydotxyz  Is there any way to obtain HWND

**Comment by andydotxyz** [comment]
Not using Fyne code there isn't - the OS details are driver specific and we don't expose any driver info as we need to be able to change it over time.
In theory I guess you could put Windows specific code into your application and search through the windows belonging to your process ID.

**Comment by qianniancn** [comment]
@andydotxyz 
I want to get the handle of the'fyne' window when the'fyne' window was created
I am still unable to get the window handle after modifying the code of'fyne', can you help me?

**Comment by andydotxyz** [comment]
Sorry @qianniancn this is just not supported.
If you can expand on /why/ you want to do it we may be able to help further.

**Comment by qianniancn** [comment]
![20210811220049](https://user-images.githubusercontent.com/5478237/129043438-a86def03-9a18-40b9-a8b2-2252884a1409.png)
![20210811220304](https://user-images.githubusercontent.com/5478237/129043471-d1850db0-12de-4280-9cf5-ad95753e48de.png)
![20210811220336](https://user-images.githubusercontent.com/5478237/129043496-89a95056-8d70-42bb-9d9e-29208cc02e9f.png)

I enumerate the window by process ID, but what I get is not the handle to the FYne window

**Comment by qianniancn** [comment]
> In theory I guess you could put Windows specific code into your application and search through the windows belonging to your process ID.

I got the window handle through the process ID. Thank you for your comments.
