### ISSUE TITLE
Add image support to rich text

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#2366]
### Is your feature request related to a problem? Please describe:
New RichText needs more features :)

### Is it possible to construct a solution with the existing API?
You could split a RichText into two and place an image between them - but that won't support inline images

### Describe the solution you'd like to see:
Block and inline images as part of the RichText Segment APIs

**Comment by lugu** [comment]
+1 This feature can greatly benefit markdown support.

**Comment by vlanse** [comment]
+1 for MD support with images

**Comment by LainNetWork** [comment]
+1 we need it~

**Comment by andydotxyz** [comment]
Done for release
