### ISSUE TITLE
iOS: Opening file dialog crashes on 10.3

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#2369]
On that old version of iOS we get a crash with InternalInconsistencyException - it requires iCloud entitlements that are not needed with newer iOS versions.

### To Reproduce:
* install fyne_demo on an old iOS device
* Go to Dialogs -> File open (or save, or folder)
* See console log for crash

### Device (please complete the following information):
 - **OS:** iOS
 - **Version:** 10.3
 - **Go version:** 1.14
 - **Fyne version:** 2.0.4

**Comment by changkun** [comment]
Are we still targeting iOS 10? It was released six years ago.

**Comment by andydotxyz** [comment]
Yes, it is the last release to support 32bit iOS devices, which are supported by Go 1.14, which we still support.

**Comment by changkun** [comment]
That's a little bit unfortunate. Working to the support seems to have much less return, as they are deprecating soon.

**Comment by Jacalz** [comment]
Should we close this now that Go 1.17 is the minimum supported version in the upcoming v2.4.0?

**Comment by andydotxyz** [comment]
Yes I think that makes sense. We really should write down the versions we support back to which we can review each year.

**Comment by Jacalz** [comment]
Maybe a "Supported platforms" page on our developer site would be a good idea?

**Comment by andydotxyz** [comment]
Since we no longer support 32bit iOS this is not an issue any more - all 64bit devices can upgrade to iOS 12 at least
