### ISSUE TITLE
Scroller inside grid is tiny, and cannot be resized

### ISSUE THREAD

**Issue by Sobeston** [fyne-io/fyne#237]
`		grid := fyne.NewContainerWithLayout(layout.NewFormLayout())`
...
`		scroller := widget.NewGroupWithScroller("my scroller",
			widget.NewLabel("111111"),
			widget.NewLabel("222222"),
			widget.NewLabel("333333"),
			widget.NewLabel("444444"),
			widget.NewLabel("555555"),
		)
		scroller.Resize(fyne.Size{Width: 200, Height: 800})

		scrollervbox := widget.NewVBox(scroller)
		scrollervbox.Resize(fyne.Size{Width: 200, Height: 800})`
...
`		grid.AddObject(scrollervbox)`

![image](https://user-images.githubusercontent.com/15335529/56768494-75cb4a80-67a6-11e9-8f57-ffc23b75ce37.png)

**Comment by okratitan** [comment]
I've also seen scroller sizing weirdness both with a vbox and with a fixed grid.  I think scroller needs improvements in how it resizes dynamically when it's child changes sizes.

**Comment by andydotxyz** [comment]
The issue here was due to code outside this that was squashing the scroller to a small size and not a bug with the scrollcontainer

**Comment by Strosel** [comment]
I'm having the same issue with a scrollcontainer in a tab, how can this be fixed?

**Comment by andydotxyz** [comment]
The most likely situation is that you have packed the scrollcontainer into a layout that collapses to a minsize. Either change the layout to one that expands (such as BorderLayout), promote it to the content of the tab, or set a minSize somehow. Without knowing your exact situation it's hard to say what's right.
