### ISSUE TITLE
Perhaps receive widget.Label instead of canvas.Text

### ISSUE THREAD

**Issue by ReactionaryFuture** [fyne-io/fyne#2375]
https://github.com/fyne-io/fyne/blob/1f05de7da27eaaf9dbf358ebe235ea306864ce76/widget/button.go#L56

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. Thanks for understanding.

**Comment by ReactionaryFuture** [comment]
Sorry. I don't know what that means.

**Comment by andydotxyz** [comment]
When you open an issue github populates the template. As far as I know the only way to not see this is if you force the "open a blank issue" which may be what happened.
