### ISSUE TITLE
Whether you can add the border rounded corner attribute

### ISSUE THREAD

**Issue by qianniancn** [fyne-io/fyne#2376]
Add rounded edges to make buttons, input boxes, and other components rounded

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. Thanks for understanding.

**Comment by qianniancn** [comment]
Okay, I'll resubmit it

**Comment by Jacalz** [comment]
You didn’t have to resubmit it. You could have just updated the description).

**Comment by andydotxyz** [comment]
Probably duplicate of #1090
