### ISSUE TITLE
Allow explicit sizing of Height, Width and Padding of widgets and containers

### ISSUE THREAD

**Issue by luciferchase** [fyne-io/fyne#2379]
### Is your feature request related to a problem? Please describe:

Allow explicit resizing of various widgets and containers as well as inner and outer padding. Existing solutions are very primitive and difficult to use for a big project.

### Is it possible to construct a solution with the existing API?

Yes with `layout.NewSpacer()` one can achieve something like this but more explicit controls would be better.

### Describe the solution you'd like to see:

New functions like `SetWidth()`, `SetHeight()`, `SetPadX()`, `SetPadY()` as is used in other GUI libraries for eg. [Tkinter in Python](https://docs.python.org/3/library/tkinter.html?#packer-options)

**Comment by andydotxyz** [comment]
This is not how we have designed layouts - the widget size and position is controlled by the container it is within.
The provided layouts and containers should fit most use-cases, for those that are more complex you can add your own layout https://developer.fyne.io/tutorial/custom-layout.

We will not allow widgets to force size on their parents as this put significant limitations on how GUI will adapt to different screens and environments.

**Comment by andydotxyz** [comment]
Closing because this is not how the toolkit works.
If you find a situation that is impossible with the current solution then please feel free to re-open with a new description or create specific issues for the missing use-case.
