### ISSUE TITLE
SVG theme with bundled resource not rendered correctly on button when Disabled 

### ISSUE THREAD

**Issue by stuartdd** [fyne-io/fyne#2381]
### The bug:
I have created a bundle.go and have a theme that uses the imported SVG images.

I have a Button that uses the resources but I am having issues with the image displayed.

In the SVG there is an initial 'ellipse'. This is NOT rendered when the button is Disabled!

The original file was generated using [Draw.io](https://draw.io) and exported to an SVG file. This produces a reasonable size file. I tried Inkscape and LibreOffice Draw but [Draw.io](https://draw.io) produced compatible and reasonably compact SVG files.

Note that I am using SVG only because I could not get a .png bundle resource to work properly. 
I was able to bundle the png file but every time it is rendered I would get a stream of errors to the console indicating that it could not read the SVG data so it was 'falling back'. The image in the button was however rendered correctly. I will detail this issue in another Issue when I have more details (unless you think it is related?)

### To Reproduce:
I have included code snippets and a screen shot. Please let me know if you require more detail

### Screenshots:
![Screenshot from 2021-08-16 17-14-01](https://user-images.githubusercontent.com/20523458/129595682-1c99ec7b-d5f5-4397-b972-52bd4735f34a.png)

### Example code:
The bundle resource:
```go
var resourceLinkDarkSvg = &fyne.StaticResource{
	StaticName: "LinkDark.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" width=\"102px\" height=\"102px\" viewBox=\"-0.5 -0.5 102 102\"><defs/><g><ellipse cx=\"51\" cy=\"51\" rx=\"50\" ry=\"50\" fill=\"#000000\" stroke=\"#ffffff\" stroke-width=\"2\" pointer-events=\"all\"/><path d=\"M 51 1 L 51 101 M 101 51 L 1 51 M 51 1 C 67.76 12.12 77.83 30.89 77.83 51 C 77.83 71.11 67.76 89.88 51 101 C 34.24 89.88 24.17 71.11 24.17 51 C 24.17 30.89 34.24 12.12 51 1 Z M 16 86 C 36.92 70.98 65.08 70.98 86 86 M 16 16 C 36.92 31.02 65.08 31.02 86 16\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" /></g></svg>"),
}
```
The theme Icon method
```go
func (m MyTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	if name == theme.IconNameContentUndo {
		return resourceLinkDarkSvg
	}
	return theme.DefaultTheme().Icon(name)
}
```
Please ignore the naming I am experimenting with the Link image using a ContentUndo button

### Device (please complete the following information):

- **OS:** Linux Mint 20.2 Cinnamon
- **Version:** 5.11.0-25-generic
- **Go version:** go version go1.16.7 linux/amd64
- **Fyne version:** fyne.io/fyne/v2 v2.0.4

**Comment by andydotxyz** [comment]
Apologies, we seemed to miss ellipse support when we were transforming the fill for disabled/primary colorization.
Fixed on `develop`.
