### ISSUE TITLE
allow bluetooth(at least in AndroidManifest.xml)

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#2382]
I'm sorry if it already exist....
### Is your feature request related to a problem? Please describe:
1. On the internet exists many API for bluetooth for example https://github.com/tinygo-org/bluetooth but in android it need allow in manifest... .
2. from 1. task is cleary that: I will other ....xml than my neighbor.... .

### Is it possible to construct a solution with the existing API?
1. At least manifest Yes yet and until sometime(maybe never) Yes it will posible.
2. Yes it is small change.

### Describe the solution you'd like to see:
1. I sugest: Add to manifest line or lines allow yet and until sometime(maybe never) add some library to bluetooth.
2. I sugest: Add to tool "fyne" or "fyne-cross" (I do'nt know what is newer or what is defferent) option `-manifest string:"path/.../AndroidManifest.xml"`

**Comment by andydotxyz** [comment]
If you have an `AndroidManifest.xml` file in the project that will be used instead of the generated one, no additional parameters are required.

**Comment by MatejMagat305** [comment]
ach sorry
