### ISSUE TITLE
Container.Insert(befor int)

### ISSUE THREAD

**Issue by A1311981684** [fyne-io/fyne#2383]
I think provide a method that allows us to insert some item into a Container object list is quit useful.

**Comment by Jacalz** [comment]
I think this most likely is a duplicate of https://github.com/fyne-io/fyne/pull/1867. The comment https://github.com/fyne-io/fyne/pull/1867#issuecomment-768187191 contains reasoning as to why this hasn’t been implemented.

As a side note, please use the issue templates when opening new issues the next time. The templates are designed to help us save time and give us all the necessary information related to the issue. Thanks for understanding.

**Comment by A1311981684** [comment]
Ok, thank you very much!
