### ISSUE TITLE
readonly entry

### ISSUE THREAD

**Issue by mhf-ir** [fyne-io/fyne#2384]
How to readonly entry?

**Comment by andydotxyz** [comment]
Entry.Disable()

**Comment by mhf-ir** [comment]
Disable is not readonly, on readonly you can copy from input area.

**Comment by andydotxyz** [comment]
I know that in many toolkits both exist, but I don't believe that is a requirement.
In fyne widgets update their look to reflect state. A widget that has no difference in look should not have a difference in state.
Therefore an entry that looks like you can interact should be interactive.

Text that cannot be interacted is `widget.Label` text that you want to interact with, but cannot change, is `Disabled`.

**Comment by Jacalz** [comment]
I think this kind of use case could be entirely avoided by being able use selection in widget.Label. Not necessarily by default, but it could be a useful thing in some cases.

**Comment by andydotxyz** [comment]
Why is a selectable Label more desirable than a disabled Entry? It still does not offer any user indication that the text can be interacted with.

In previous situations it's been because developers wanted to have a copy-to-clipboard on a regular workflow and in such situations the "copy button" approach is much more discoverable.

**Comment by mhf-ir** [comment]
Think about simple log that generate in UI, how to display to user, that user cannot modify it but can copy it.

**Comment by andydotxyz** [comment]
I don’t understand why a disabled entry does not satisfy this use-case

**Comment by mhf-ir** [comment]
It's essential difference between disabled and readonly.
https://html.spec.whatwg.org/multipage/input.html#the-readonly-attribute
You can copiable disabled field but it's seems anipattern

**Comment by andydotxyz** [comment]
I'm going to go back to our design ethic that behaviour should be backed by a visual hints.
A read-only entry has no cue that it is different to a regular one, a disabled one sets the expectation that it cannot be edited.
We are trying to shake off some of the old ways that don't hold real value - the difference between read-only and disabled seems like one of those things.
I'm going to close this as answered (`Entry.Disable()`)

**Comment by D1360-64RC14** [comment]
Sorry by opening this issue again, but I think a read-only Entry is useful in some use-cases.

My use case: a Serial Interface reader, where the user can select the data, but can't edit. That grayish color in the `Entry.Disable()` text makes the user think that the connection isn't open, or something else.

I see two solutions: an `bool Entry.editable` field, or an `TextLog` (or `ReadonlyEntry`) widget.

**Comment by andydotxyz** [comment]
The recommended approach to copy text that a user cannot otherwise modify is a "copy text" button as you see in many material design apps. This is a lot more usable than forcing selection, and it demonstrates to the user the expected interaction.

**Comment by D1360-64RC14** [comment]
Hmm, maybe I could use this, but it's not perfect, as sometimes people want to copy just a single line, not the whole content.

**Comment by sefgit** [comment]
Don't fight **design ethic** ;)
work around it by defining your own theme so that "disabled" widgets are "readable" [side note: another ethical issue might rise ;)]

I followed this instruction and it works like a charm:
[fyne custom them](https://developer.fyne.io/extend/custom-theme)

**Comment by moxianfeng** [comment]
just handle OnChange and reset text, for example

	entry.OnChanged = func(string) {
		entry.SetText("")
	}

**Comment by matwachich** [comment]
Check how I did it in https://github.com/matwachich/fynex-widgets

**Comment by lordofscripts** [comment]
There are cases where you want Read-only where an Entry is more suitable than a Label. And as the OP replied, Disabled is not Read-only. Usually, Disable has consequences like a Grayed color to denote it is disabled, but again, what the OP wants is to present information in a meaningful manner, something as simple as a read-only text with yellow background.

**Comment by andydotxyz** [comment]
Please don't comment on closed issues - you can read above the design reasons for not progressing with this.

**Comment by jithin-kg** [comment]
Hi @andydotxyz  and Fyne team

I'd like to highlight a use case for a read-only entry that does not appear disabled. In applications like log viewers (terminal application history/output view), users need to view and copy data without editing it. A disabled appearance often suggests the content is not actionable, which can be misleading. Allowing a read-only mode that retains the standard entry appearance would clarify that the data is live and selectable, enhancing user interaction.


Thank you for considering this feedback.

**Comment by andydotxyz** [comment]
> In applications like log viewers (terminal application history/output view), users need to view and copy data without editing it

This is not the simple use-case that you imply. I'm not really sure that using an Entry widget as the output of a terminal app is really a smart move. Perhaps you'd be more interested in the [terminal](/fyne-io/terminal) project, which actually implements all the things that a terminal would need.

You'll notice that more rich log browsing apps that are not just based on terminal output use a more complete UI like a list/table view which are much better suited to the high throughput, large data that a log can create.

**Comment by chengsh** [comment]
```
type MyReadOnlyEntry struct {
	*widget.Entry
	text string
}

func NewReadOnlyEntry(entry *widget.Entry) *MyReadOnlyEntry {
	e := MyReadOnlyEntry{
		Entry: entry,
	}
	e.OnChanged = func(string) { e.Entry.SetText(e.text) }
	return &e
}

func (e *MyReadOnlyEntry) SetText(text string) {
	e.text = text
	e.Entry.SetText(e.text)
}
```
it can work.

**Comment by andydotxyz** [comment]
Don't extend widgets by embedding another instance - just extend `widget.Entry` (no star) and the code will be much simpler.

That said disabling is better because this approach will flicker and also bring up a keyboard on mobile...
