### ISSUE TITLE
Packaging Android without NDK and SDK

### ISSUE THREAD

**Issue by Mi-Sanchez** [fyne-io/fyne#2386]
### Is your feature request related to a problem? Please describe:
I use an arm64 linux-system where android ndk and sdk are not available.

### Describe the solution you'd like to see:
An alternative way to build android apps on arm64 linux-systems e.g. with less comfort.

**Comment by MatejMagat305** [comment]
no compile without ndk or sdk is in pactical imposible...
you are probably in termux, so you theoritically 

> try copy some ndk .apk unpackage it with command  `unzip someApk.apk -o dirApk` or with apktool `apktool -d someApk.apk ...` 
> install golang `pkg install golang git clang ; go get .../v2/fyne/...`  
>  try to build .so file link to other .so file, which get `ldd fyneOriginalApp.so`, (I have try it but I was failed if you are sussces you will tell me please) 
> when it will be compiled you will be able replace fyneOriginalApp.so with your but you need have same name than before otherwise your apk will crashed at install. 

> I was made all step, but I was'nt be able compile...(please if somebody know how...., write)

**Comment by Mi-Sanchez** [comment]
Thank you for your help.

I found that "android-sdk-build-tools (29.0.3+3)" is available in the package sources. Could this possibly help?

And maybe I could do it without ADB and transfer the APK e.g. via bluetooth?

**Comment by MatejMagat305** [comment]
Yes, it could help..., 
absolutely yes, you can transfer apk or app (I have only ios 5 and I was be able install non-oficial, but I'm not certean) via bluetooth and install on device from storage

**Comment by andydotxyz** [comment]
Android and linux-arm are different platforms. If you want to build Android apps you will have to have SDK/NDK (that is how compilers work). However you can build linux-arm apps like you would any other Go app, using GOOS and GOARCH.

Which of these are you trying to do?

**Comment by andydotxyz** [comment]
Alternatively you can use the [fyne-cross](/fyne-io/fyne-cross/) project which bundles the SDK into a docker image.

**Comment by Mi-Sanchez** [comment]
@MatejMagat305 & @andydotxyz thank you for your answers.

> Which of these are you trying to do?

I'm trying to build an android app.
I'll take a closer look at your fyne-cross project, thanks.

**Comment by andydotxyz** [comment]
> I'm trying to build an android app.
> I'll take a closer look at your fyne-cross project, thanks.

Great. If you want to build Android you'll need SDK/NDK either through fyne-cross or by installing manually - does Android studio simply not work on linux-arm64?

**Comment by Mi-Sanchez** [comment]
> does Android studio simply not work on linux-arm64?

Android studio is unfortunately not available for Raspberry Pi OS.

And developer.android.com only offers an arm64 version for the Mac ;-(

**Comment by andydotxyz** [comment]
> And developer.android.com only offers an arm64 version for the Mac ;-(

Oh, that sucks. Sounds like fyne-cross is the right solution then.
