### ISSUE TITLE
Entry widget can adjust its size according to its Text or PlaceHolder

### ISSUE THREAD

**Issue by Slory7** [fyne-io/fyne#2388]
I wanna a form layout, left part is the label, and right part is the entry, the entry's size is auto extended by its text or place holder.

This can work before 2.0 version. 

Tell me how to do this in the new version, thank you!

**Comment by andydotxyz** [comment]
`Entry.Wrapping = fyne.TextWrapOff`.
We replaced the default expand with scrolling.
