### ISSUE TITLE
zsh: command not found: fyne

### ISSUE THREAD

**Issue by MintCollie** [fyne-io/fyne#2389]
### Describe the bug:

fyne command is not working

### To Reproduce:
Steps to reproduce the behaviour:
1. go get fyne.io/fyne/v2
2. go install

### Screenshots:
[https://imgur.com/a/2YdUZdF](url)

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.0 21A5304g
 - **Go version:** go1.16.6
 - **Fyne version:** 2

### Additional comment:
I made sure my GOPATH has been set properly as directed here [https://github.com/golang/go/wiki/SettingGOPATH#zsh](url) 
I can run the fyne program manually by going to my GOPATH but `fyne install` gives me the error `Missing application icon at "/Users/mint/go/bin/Icon.png"`

**Comment by andydotxyz** [comment]
You need `go get fyne.io/fyne/v2/cmd/fyne`

**Comment by andydotxyz** [comment]
> `fyne install` gives me the error `Missing application icon at "/Users/mint/go/bin/Icon.png"`

This is a separate issue, each Fyne app either needs `Icon.png` or you pass an `-icon <path>` parameter for the file location.
