### ISSUE TITLE
Cannot select leaf nodes programatically in a Tree. Not sure if bug or feature request

### ISSUE THREAD

**Issue by stuartdd** [fyne-io/fyne#2391]
### Describe the bug (not sure if really a bug):
I have a Tree that displays a hierarchy defined by a JSON tree.

**See screen shot below:**

Selecting any Container Node or Leaf Nodes displays an page (to the right) showing details (held elsewhere) about that node.

This all works well and I have no issues here. The problem is I cannot programmatically select any of the Leaf Nodes.

In the code below (func makeNavTree) there is a fmt.Printf that displays the uid of the selected Node.

When I update the tree (add a Leaf Nodes), rebuild the JSON, create a new Tree and display I am unable to select the new Leaf Nodes I have just created programmatically. If I create a Container Node I can select it programmatically.

The second code snippet below:
1. Creates a new Tree
2. Opens the Container Node node (the one containing the new  Leaf Node)
3. Selects the Leaf Node

Step 3 fails!
The Selected uid (from the fmt.Printf("Selected %s\n", uid)) would contain UserA.Hints.Mail

The Select uid (from navTree.Select(uid)) contains the same!

So the uid I capture in the 'makeNavTree-->OnSelected: func' is the same one used in the 'navTree.Select(uid)' but the Select fails.

If I shorten the Select to remove the leaf (E.g. 'navTree.Select("UserA.Hints")') the Select works but of course selects the parent node.

### Screenshots:
Notes, Mail, Zoom and Shiny are ALL Leaf Nodes 
UserA, UserB and Hints are all Container Nodes
![Screenshot from 2021-08-21 18-27-03](https://user-images.githubusercontent.com/20523458/130330950-ef8d485b-ff2a-4920-991b-0775fa922321.png)

### Example code:
Code originally from fyne example code.
```go
func makeNavTree(setPage func(detailPage gui.DetailPage)) *widget.Tree {
	return &widget.Tree{
		ChildUIDs: func(uid string) []string {
			id := dataRoot.GetNavIndex(uid)
			return id
		},
		IsBranch: func(uid string) bool {
			children := dataRoot.GetNavIndex(uid)
			return len(children) > 0
		},
		CreateNode: func(branch bool) fyne.CanvasObject {
			return widget.NewLabel("?")
		},
		UpdateNode: func(uid string, branch bool, obj fyne.CanvasObject) {
			t := gui.GetDetailPage(uid, dataRoot.GetDataRootMap())
			obj.(*widget.Label).SetText(t.Title)
		},
		OnSelected: func(uid string) {
			currentSelection = uid
			fmt.Printf("Selected %s\n", uid) // Print the UID of the selected node
			t := gui.GetDetailPage(uid, dataRoot.GetDataRootMap())
			setPage(t)
		},
	}
}
```
Code that tries to re-select the node or select a new node. 
'uid' is the selected node (e.g. UserA.Hints.Mail).
'node' is the parent node (e.g. UserA).

```go
fmt.Printf("Select %s\n", uid)
navTree = makeNavTree(setPage)
navTree.OpenBranch(node)
// Select the node
navTree.Select(uid)
```
JSON example for the tree structure 
```json
{
    "": [
        "UserA",
        "UserB"
    ],
    "UserA": [
        "UserA.notes",
        "UserA.Hints"
    ],
    "UserA.Hints": [
        "UserA.Hints.Mail",
        "UserA.Hints.Zoom"
    ],
    "UserB": [
        "UserB.notes",
        "UserB.Hints"
    ],
    "UserB.Hints": [
        "UserB.Hints.Mail",
        "UserB.Hints.Shiny"
    ]
}
```
### Device (please complete the following information):
- **OS:** Linux Mint 20.2 Cinnamon
- **Version:** 5.11.0-25-generic
- **Go version:** go version go1.16.7 linux/amd64
- **Fyne version:** fyne.io/fyne/v2 v2.0.4

**Comment by andydotxyz** [comment]
I cannot follow your description, please provide a single code example and steps to run so we can replicate the issue. From what is above it is not clear what bug you are registering.

**Comment by stuartdd** [comment]
Hi.

It will take me some time to do that but I will give it a go and get back to you.

To explain further: 

Given the above Tree:
If I click on ANY tree node the OnSelected function for the tree is executed and passed a uid.
 
If I click on the UserA node (which is a container node) the uid for that node is 'UserA'
If I execute navTree.Select("UserA") the same node is selected. This is expected behaviour.

If I click on the Hints node (which is a container node) the uid for that node is 'UserA.Hints'
If I execute navTree.Select("UserA.Hints") the same node is selected. This is expected behaviour.

If I click on the Mail node (which is a leaf node) the uid for that node is 'UserA.Hints.Mail'
If I execute navTree.Select("UserA.Hints.Mail") the same node is NOT selected. **I think it should be and that this is a bug**.

Hope this helps

I will let you know when I have some code to show.

Stuart

**Comment by andydotxyz** [comment]
> If I click on the Mail node (which is a leaf node) the uid for that node is 'UserA.Hints.Mail'
> If I execute navTree.Select("UserA.Hints.Mail") the same node is NOT selected. **I think it should be and that this is a bug**.

Goodness that does sound like a bug. What does happen when you pass that uid to `Select`?

**Comment by stuartdd** [comment]
Yep that's what I thought 🤠Nothing happens. No exception, no errors, nothing! Do you still need me to do a demo of the issue?RegardsStuartOn 21 Aug 2021 22:32, Andy Williams ***@***.***> wrote:

If I click on the Mail node (which is a leaf node) the uid for that node is 'UserA.Hints.Mail'
If I execute navTree.Select("UserA.Hints.Mail") the same node is NOT selected. I think it should be and that this is a bug.

Goodness that does sound like a bug. What does happen when you pass that uid to Select?

**Comment by andydotxyz** [comment]
> Do you still need me to do a demo of the issue?

Yes please, I cannot replicate using the information above. `Tree.Select(uid)` always seems to select the requested node in my code.

**Comment by stuartdd** [comment]
So I wrote a test application a you requested! And you are correct I can find nothing wrong with the Select method. 

So I guess this one is NOT a bug!

I include the test for ref.

For me it's back to my code to find what is going on! 

Thanks for the help, sorry to have wasted your time on this one. I will write test apps for any other potential bugs I encounter.
 
Regards
Stuart

```go
package main

//______________________________________________________________________________

import (
	"fmt"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

//______________________________________________________________________________

var tree *widget.Tree
var data map[string][]string
var input1 *widget.Entry
var input2 *widget.Entry

//______________________________________________________________________________

func main() {
	data = makeData()

	myApp := app.New()
	myWindow := myApp.NewWindow("List")

	tree = makeTree()
	input1 = widget.NewEntry()
	input2 = widget.NewEntry()
	bottom := container.NewVBox(input1, input2,
		widget.NewButton("Select in tree", updateList))
	content := container.NewBorder(
		widget.NewLabel("Items' list::"),
		bottom,
		nil, nil,
		tree)
	myWindow.SetContent(content)
	myWindow.Resize(fyne.NewSize(480, 600))
	myWindow.ShowAndRun()
}

func updateList() {
	tree.Select(input2.Text)
}

//______________________________________________________________________________

func makeTree() *widget.Tree {
	return &widget.Tree{
		ChildUIDs: func(uid string) []string {
			return data[uid]
		},
		IsBranch: func(uid string) bool {
			children := data[uid]
			return len(children) > 0
		},
		CreateNode: func(branch bool) fyne.CanvasObject {
			return widget.NewLabel("?")
		},
		UpdateNode: func(uid string, branch bool, obj fyne.CanvasObject) {
			list := strings.Split(uid, ".")
			if branch {
				obj.(*widget.Label).SetText(fmt.Sprintf("branch:  %s", list[len(list)-1]))
			} else {
				obj.(*widget.Label).SetText(fmt.Sprintf("  leaf:  %s", list[len(list)-1]))
			}
		},
		OnSelected: func(uid string) {
			input2.SetText(input1.Text)
			input1.SetText(uid)
		},
	}
}

func makeData() map[string][]string {
	return map[string][]string{
		"": {
			"UserA",
			"UserB",
		},
		"UserA": {
			"UserA.Notes A",
			"UserA.Hints A",
		},
		"UserA.Hints": {
			"UserA.Hints.Mail A",
			"UserA.Hints.Zoom A",
		},
		"UserB": {
			"UserB.Notes B",
			"UserB.Hints B",
		},
		"UserB.Hints": {
			"UserB.Hints.Mail B",
			"UserB.Hints.Zoom B",
		},
	}
}

```

**Comment by andydotxyz** [comment]
OK, Glad we figured out there was not an issue, sorry it means more work at your end to work it out.
Closing as not an issue
