### ISSUE TITLE
Size executable of hello app

### ISSUE THREAD

**Issue by renlite** [fyne-io/fyne#2393]
Hi,
the "hello.exe" from "Getting started" has a size of 16 MB. This seems to be a big size for a minimum app.
Is this common or are there compiler/build options to reduce the footprint?

**Comment by andydotxyz** [comment]
It depends which platform you are building for. Basic app is around 8MB due to the go runtime and some embedded resources. It will be larger if you are packaging for multiple OS architectures.

For a more detailed response please complete the bug template with os/version and commands used

**Comment by MatejMagat305** [comment]
use command `go build -ldflags "-w -s -H=windowsgui"` (ordinary only few kilobite, but it remove console),
and if you do not need fast start you can use `upx --ultra-brute ...`, it together comprest to 2.8 MB ............., but I do not recomend it to use on android apk......... .

**Comment by andydotxyz** [comment]
Please use the fyne tools (`fyne package`) and report back.
We cannot help what the go build phase outputs but there are various flags and improvements applied through the `fyne` command.

**Comment by MatejMagat305** [comment]
it is similar https://github.com/fyne-io/fyne/issues/1097

**Comment by 1-bytes** [comment]
> 使用命令`go build -ldflags "-w -s -H=windowsgui"`- 将大小减少到大约。8(7.8) MB（一般`-H=windowsgui`只有几千字节，但它去掉了控制台），
> 如果你不需要快速启动，你可以使用`upx --ultra-brute ...`，它加起来压缩到 2.8 MB ........，但是我不建议在 android apk 上使用 upx .......

I agree with you :)

**Comment by renlite** [comment]
`go build -ldflags "-w -s -H=windowsgui"` helped to reduce the size to 8 MB.
Thanks

**Comment by andydotxyz** [comment]
Just FYI for others landing here, those parameters are set if you use `fyne package` instead of the go build.
