### ISSUE TITLE
Need advice: App launched by clicking on binary or from terminal? (linux)

### ISSUE THREAD

**Issue by amo13** [fyne-io/fyne#2394]
### Is your advice request related to a problem? Please describe:
On linux, I need to execute other binaries (android platform tools: adb, fastboot) with sudo. Technically, this is because I do not wish to assume that the users know how to and did correctly setup udev rules for their connected android devices (using sudo bypasses udev rule restrictions). Unfortunately, it requires the user to be able to input their sudo password.

### Describe the strategy you have adopted:
My strategy is to let the app find out if it was launched from a terminal or simply by double-clicking on the binary in a desktop environment. In the latter case, the app could display a polite message asking the user to launch the app in a terminal so the sudo password could be entered. (Another implementable option would be a command line parameter telling the app not to use sudo because the user confirms that udev rules are correctly set up.) 

I have found two way to test if a go application has been launched in a terminal or not:
1:
```go
_, err := os.Stdin.Stat()
if err != nil {
    Lbl_init_infotext.Text = "Stdin not available."
} else {
    Lbl_init_infotext.Text = "Stdin available."
}
```
but this one always says Stdin is available, even when it is not (not started from a terminal).

2:
```go
stdout, _ := Cmd("[ -t 0 ] && printf \"true\" || printf \"false\"")
if stdout == "true" {
	Lbl_init_infotext.Text = "STDIN available."
} else {
	Lbl_init_infotext.Text = "STDIN not available."
}
```
but this one always says Stdin is not available, even when launched from a terminal.

---

Linking similar discussion (for mac): #1265

I'd greatly appreciate any ideas on how I could accomplish this. Or, of course, any idea for an alternative strategy.

**Comment by andydotxyz** [comment]
There is no provided way to do this.
However I would not recommend a GUI app ask user to switch to terminal to enter information - this is a pretty bad user experience.
However you can ask for the user password in your app, then send it to the sudo command.
There are many articles about this online, but in essence you need the `-S` parameter so the password is read from stdin.

**Comment by amo13** [comment]
Thank you a lot for your answer.
I see. Then, I guess, this is how I will do it.
I will need the dialog asking for sudo password to block the execution of the application though. My idea for this would be to open a channel and receive from that channel (which blocks execution) right after the code for the dialog. The dialog would send to that channel once closed.
Is there a cleaner built-in way to make a dialog block?

**Comment by andydotxyz** [comment]
Forget about blocking - that is over complicated and can make UI unresponsive.
Instead put the code in the callback instead.
i.e. in a confirm dialog you have a callback with a `ok bool`. In there check that `ok` is `true` and if so then execute your code.
No need for waiting or channels.

If you want to think in blocks then remember you can pass around function references.
