### ISSUE TITLE
fyne bundle ignores -name flag in windows

### ISSUE THREAD

**Issue by luciferchase** [fyne-io/fyne#2395]
### Describe the bug:

I tried to package my application like this
```bash
fyne package -name "Result Converter" -sourceDir src/gui -os windows -icon src/gui/assets/icon.png
```
However, instead of "Result Converter.exe", the app is named as simply "gui.exe":
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23/08/2021  11:58 AM                assets
d-----        19/08/2021  08:10 PM                custom
-a----        23/08/2021  12:26 PM       19361274 gui.exe
-a----        23/08/2021  12:16 PM           5575 main.go
```
Interestingly, if I go to properties of "gui.exe", the name of the program is stated as "Result Converter" there:

![properties](https://user-images.githubusercontent.com/48217707/130404184-a002ebb9-6f49-492e-ad91-7ab62c80a82e.png)

### To Reproduce:
Steps to reproduce the behaviour:
1. Make a folder "test"
2. Copy the code below to main.go
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```
3. From the **root** folder, package the application like this
```bash
fyne package -name "Custom Name" -sourceDir test -os windows
```
4. Instead of "Custom Name.exe", a "test.exe" will be generated in the "test" folder

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:**  10
 - **Go version:**  1.17 (should work with 1.16 too I think)
 - **Fyne version:**  2.04

**Comment by andydotxyz** [comment]
Good find. It seems to be as a result of the windows packaging not creating a new, final, file after the build - it just overwrites the .exe. This should be fixed.

**Comment by andydotxyz** [comment]
That should be fixed on develop now :)

**Comment by luciferchase** [comment]
Awesome thanks for the fix
