### ISSUE TITLE
Question: Skia / (GLFW)OpenGL

### ISSUE THREAD

**Issue by renlite** [fyne-io/fyne#2400]
What are the reasons for using GLFW and not Skia (like Flutter or AvaloniaUI) for rendering?

**Comment by andydotxyz** [comment]
GLFW is not used for rendering, it is for opening the GL context and handling window management and events.
So maybe your question is why use `OpenGL` instead of `skia` - basically because it supports more and older devices, and it is an industry standard.

**Comment by renlite** [comment]
I thought Skia is also a wrapper and can use GL as backend.

Does it mean?
a) Later you can switch to eg Vulkan or support another renderer.
b) On mobile you needn't embed GL to the app (eg APK), what Flutter must do with Skia. 

Why did you choose "Go" for this project compared with other compiled languages like Rust, Vim, Zig or D.

**Comment by andydotxyz** [comment]
Go is an excellent language for building graphical apps - the combination of type safety, modern language features and a fantastic community makes it hard to beat. I wrote a book that covers this and explores the toolkits available (it is a few https://www.packtpub.com/product/hands-on-gui-application-development-in-go/9781789138412

This issue tracker is to manage the development of our platform and track issues, if you want to talk more please use one of our support channels - https://fyne.io/support/ or https://fyne.io/#contact.
