### ISSUE TITLE
Scroll missing in SelectEntry widget

### ISSUE THREAD

**Issue by FredSoftwares** [fyne-io/fyne#2404]
Hi,

The right scroll is missing in  SelectEntry widget in Fyne v2.0.5-0.20210825130215-83ca35d98be7. As a result the list is truncated.
To see the bug, use the following code and compile it with fyne 2.04 and fyne 2.05. In the last version, it is not possible to see the entire list (see screenshot attached)

```
package main

import (
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test Button")
	data := buildData()
	x := widget.NewSelectEntry(data)
	x.SetText("select")
	content := container.NewVBox(x)
	w.SetContent(content)
	w.Resize(fyne.Size{100, 500})
	w.ShowAndRun()
}

func buildData() []string {
	var data []string
	for i := 0; i < 100; i++ {

		data = append(data, strconv.Itoa(i))
	}
	return data
}
```
![selectEntry_noScroll](https://user-images.githubusercontent.com/26299514/130974283-a7998440-576e-4c81-815a-b9983ef9fe88.png)

**Comment by toaster** [comment]
This bug was introduced with cf30adabfa433c093e0cf95e9411a591aba9254a.

**Comment by andydotxyz** [comment]
Fixed on `develop` - thanks so much @toaster
