### ISSUE TITLE
Runtime panic because out of touchID

### ISSUE THREAD

**Issue by changkun** [fyne-io/fyne#2407]
### Describe the bug:

While debugging #2406 , a runtime panic crashes the app. Here is a stack trace:

```
panic: out of touchIDs

goroutine 1 [running, locked to thread]:
github.com/fyne-io/mobile/app.sendTouch(0x130127b98, 0x10404a2a0, 0x30127b98, 0x1)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:182 +0x184
github.com/fyne-io/mobile/app._Cfunc_runApp()
	_cgo_gotypes.go:201 +0x38
github.com/fyne-io/mobile/app.main(0x130114760)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/darwin_ios.go:75 +0x58
github.com/fyne-io/mobile/app.Main(...)
	/Users/changkun/go/pkg/mod/github.com/fyne-io/mobile@v0.1.3-0.20210811181917-d62fb16c28ec/app/app.go:21
fyne.io/fyne/v2/internal/driver/gomobile.(*mobileDriver).Run(0x13011b450)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/driver.go:138 +0x64
fyne.io/fyne/v2/internal/driver/gomobile.(*window).ShowAndRun(0x104329ae0)
	/Users/changkun/dev/changkun.de/fyne/internal/driver/gomobile/window.go:187 +0x3c
main.main()
	/Users/changkun/dev/changkun.de/fyne/iosrend/main.go:46 +0x2a0
```

It looks like sendTouch may happen concurrently. Adding an RWMutex would be a quick fix.

### To Reproduce:

1. run the reproducer in #2406 
2. keep clicking the button
3. if lucky, the problem occurs

### Device (please complete the following information):
 - **OS:** iOS 15
 - **Version:** beta 6
 - **Go version:** gotip based on CL 344969
 - **Fyne version:**  develop 83ca35d98be7cf401579c2f78b53dabd7aea250a

**Comment by changkun** [comment]
@andydotxyz I just encountered the problem again. It looks like the issue is not yet fixed. Let's reopen it again...

**Comment by andydotxyz** [comment]
Make sure to double check it was built with `v2.1.0-rc1` :)

**Comment by changkun** [comment]
What just happened?

**Comment by andydotxyz** [comment]
It got auto-closed because the issue we thought resolved it hit master. I’ve unresolved it

**Comment by andydotxyz** [comment]
This will be rolling out in v2.1.1 :)
