### ISSUE TITLE
how touch event work on android?

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#2410]
### Describe the bug:
on the github in example pipes touch event work right on linux and windows, but in mobile do'nt work 2 from 4 direction, the goal was only try how it work, do'nt try find any deep meaning...,
it is simple game ("try to have the longest pipes") the game's board is devide to 4 section(which have own color, the pipes schould spread to direction, which I klick or touch...

### To Reproduce:
you can install from git, or compile..
Steps to reproduce the behaviour:
1. Open app
2. Try all section
3. See error

### Screenshots:
on the github

### Example code:
https://github.com/MatejMagat305/oneCode_many_bins_fyne

### Device (please complete the following information):
Android 7 on sm-T819

**Comment by andydotxyz** [comment]
> on the github in example pipes touch event work right on linux and windows, but in mobile do'nt work 2 from 4 direction, the goal was only try how it work, do'nt try find any deep meaning...,

I'm sorry it is not easy to understand this sentence. I am not sure what this issue is struggling with.

Widgets in Fyne can get Tapped events and it works the same on desktop and mobile.
It is not clear what touch events on Windows and Linux you are referring to - are these touch screen devices?

**Comment by MatejMagat305** [comment]
I'm sorry for unclear I was borrow struct game from your example "life" and I ask to why on pc is "tapped"(clicked) from mouse working well and tapped on android not working....
`func (g *Game) Tapped(ev *fyne.PointEvent) {
	if g.Board == nil {
		return
	}
	min := len(*g.Board) * len((*g.Board)[0])
	for _, direction := range g.fourDirections {
		d := direction.RP.DistanceOf(int(ev.AbsolutePosition.X), int(ev.AbsolutePosition.Y))
		if d < min {
			g.snake.direct = direction.D.Clone()
			min = d
		}
	}
`

**Comment by andydotxyz** [comment]
Does it work if you use `Position` instead of `AbsolutePosition`?
What version of Fyne are you using? It seems you removed half of the bug report template - that information would have been helpful.

**Comment by MatejMagat305** [comment]
probably I do not understand something, because I call :
```
func (g *GameRenderer) draw(w, h int) image.Image {
	pixDensity := g.game.pixelDensity()
	pixW, pixH := g.game.cellForCoord(w, h, pixDensity)
	g.game.InitDirections(pixW, pixH, w, h)                            // <- this function 
	..........
```
```

func (g *Game) InitDirections(w int, h int, rW, rH int) {
	if (g.fourDirections) != (nil) {
		return
	}
	centerX, centerY, rCenterX, rCcenterY := (w)/2, (h)/2, rW/2, rH/2
	g.fourDirections = make([]*coords.PointDirect, 0, 4)
	g.fourDirections = append(g.fourDirections, coords.NewPointDirect(coords.NewPoint(w, centerY),
		coords.NewDirect(1, 0), coords.NewPoint(rW, rCcenterY)))
	g.fourDirections = append(g.fourDirections, coords.NewPointDirect(coords.NewPoint(0, centerY),
		coords.NewDirect(-1, 0), coords.NewPoint(0, rCcenterY)))
	g.fourDirections = append(g.fourDirections, coords.NewPointDirect(coords.NewPoint(centerX, h),
		coords.NewDirect(0, 1), coords.NewPoint(rCenterX, rH)))
	g.fourDirections = append(g.fourDirections, coords.NewPointDirect(coords.NewPoint(centerX, 0),
		coords.NewDirect(0, -1), coords.NewPoint(rCenterX, 0)))
	for i, rgba := range vars.C {
		g.fourDirections[i].C = rgba
		fmt.Println(g.fourDirections[i].RP)
	}
}
```
and I have too big coords:
```
&{{584 351}}
&{{0 351}}
&{{292 702}}
&{{292 0}}
```

**Comment by andydotxyz** [comment]
The life game works correctly on mobile, so perhaps some maths you have added is not working?

> and I have too big coords:

What do you mean they are too big?

**Comment by MatejMagat305** [comment]
so it is my fault, you can close....,
the coords (292, 700) never can achieve in event...

**Comment by andydotxyz** [comment]
You are converting from Fyne coordinates into pixel coordinates.
Those "sizes" are certainly less than all of the pixels on your device.

It is not clear what you are doing with those coordinates later, however if you are using them within Fyne don't use pixel values.
Coordinates in Fyne (any place fyne.Position or fyne.Size) are used are device independent pixels.

My suspicion is that your code will also break if you move the app on desktop to a retina/HiDPI screen where SCALE != 1.
