### ISSUE TITLE
Add support for ico file when compiling for windows

### ISSUE THREAD

**Issue by zivoy** [fyne-io/fyne#2412]
### Is your feature request related to a problem? Please describe:
It is currently not possible to use a .ico file as an icon for the app using the `fyne.Window.SetIcon` function, though this might be a bit harder to do on OS's that are not Windows.
**BUT** when compiling for windows you also can't use a .ico file, it tries to make a .ico file from a format it can read (png)

![img](https://cdn.discordapp.com/attachments/837686172494725160/881224545833472010/unknown.png)

### Is it possible to construct a solution with the existing API?
You can use a png as the app icon and as the desktop icon

### Describe the solution you'd like to see:
At least when compiling for Windows and you supply a .ico file it should use it instead of trying to make a new one

### Note:
This was discussed [here](https://discord.com/channels/118456055842734083/837686172494725160/881224551067942962) on the [Discord Gophers](https://discord.gg/0f1SbxBZjYq9jLBk) discord

**Comment by andydotxyz** [comment]
This issue mentions a couple of different items.
It was discussed to day that:

* Fyne (and fyne-cross too) should support packaging with a windows icon 
* `SetIcon` does not have to process windows icon files as it uses Go image decoders, and all images should be cross-platform formats, or a custom image decoder loaded in your app.

So we will progress with fixing the packaging issue.

**Comment by andydotxyz** [comment]
On develop for v2.2.0
