### ISSUE TITLE
"Fyne error: Failed to set dark mode" loading fyne_demo

### ISSUE THREAD

**Issue by williambrode** [fyne-io/fyne#2426]
### Describe the bug:
When I load the fyne_demo on windows I get this:

```
2021/09/01 09:30:20 Fyne error:  Failed to set dark mode
2021/09/01 09:30:20   Cause: The operation completed successfully.
2021/09/01 09:30:20   At: <path>/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/internal/driver/glfw/window_windows.go:25
```
It does load in dark mode so I don't think its actually a problem - just some error spam that's not really an error.

### To Reproduce:
Steps to reproduce the behaviour:
1. Double click fyne_demo.exe on windows.
2. Note the error in the log.

### Screenshots:
Not applicable

### Example code:
Not applicable

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** N/A
 - **Fyne version:** 2.0.4

**Comment by williambrode** [comment]
I get this error on my app too - so its not specific to the fyne_demo.  I'm assuming its something to do with my PC's settings that fyne doesn't handle properly.

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by williambrode** [comment]
I did use the issue template but I didn't realize you cared about headers for empty fields.  Will not remove them in future.

**Comment by Jacalz** [comment]
I might have looked over the issue a bit too quickly without realising that it was just good enough to test fyne_demo. Just trying to get the word out about using the templates :)

**Comment by williambrode** [comment]
I've just found out that clicking the `Windows->New Window` and the other windows demos also logs this error.  So it seems to occur whenever creating a new window.

**Comment by andydotxyz** [comment]
Is your windows install running in dark mode @williambrode ?
If you change your windows setup from light to dark or dark to light then open a Fyne app does it match the OS variant?

**Comment by Jacalz** [comment]
I know that the dark mode support doesn't work on some of the older versions of Windows 10. I've had the issue personally back when I had my school laptop where updates were managed by the organisation. Could you please confirm your Windows 10 version?

**Comment by williambrode** [comment]
I have my windows install running in dark mode.  The Fyne demo loads in dark mode for me with this set.  Changing it to "Light" in windows caused fyne demo to load in light mode.  So that all seems to be working fine.  But even in light mode, the fyne demo still logs that error on startup and when any new window is created.

I'm on windows 10 build 18363.

**Comment by andydotxyz** [comment]
This is strange. I wonder if there is an error code that we should ignore perhaps.
Can you please print the return code after line 23 on `internal/driver/glfw/window_windows.go`? 
Perhaps there is a value that is non-0 which we should be ignoring?

**Comment by shellhazard** [comment]
I've also run into this issue. The return value as logged:
```
fmt.Printf("Return value: %v\n", ret)
Return value: 2147942487
```

Perhaps worth mentioning that the copy of Windows I used was not activated, so it doesn't allow me to change global theme settings.

**Comment by andydotxyz** [comment]
Upgrade or activate windows?

**Comment by lucor** [comment]
I had the same behavior with a VM running Windows 10 (activated).
The returned value is `2147942487` with error string `The operation completed successfully`
Note: as reported above the demo application is able to switch between theme modes correctly.
@williambrode @shellhazard are you by any chance using a VM too ?

**Comment by williambrode** [comment]
No, I'm not running it in a VM.

**Comment by andydotxyz** [comment]
Should be correctly ignored on `develop` - it seems there are many reasons for that code and none of them indicate that the call failed.

**Comment by williambrode** [comment]
Thanks @andydotxyz!
