### ISSUE TITLE
Application freezing when theme is changing 

### ISSUE THREAD

**Issue by tandem97** [fyne-io/fyne#2432]
### Describe the bug:
Application freezing when i changing app theme. But when i delete select from application it stop freezing . So I am thinking that the problem is in select

### To Reproduce:
Steps to reproduce the behaviour:
1. Run this code and try to change theme with help of buttons several times
2.  Comment select in code 
3.  Run to make sure that freezing disappeared

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {

	app := app.New()

	mainWindow := app.NewWindow("Hello")
	mainWindow.CenterOnScreen()
	mainWindow.Resize(fyne.NewSize(800, 400))
	mainWindow.SetIcon(theme.FyneLogo())

	select1 := widget.NewSelect([]string{}, func(s string) {})
	select1Layout := container.New(layout.NewPaddedLayout(), select1)

	button4 := widget.NewButton("dark", func() {
		app.Settings().SetTheme(theme.DarkTheme())
	})

	button5 := widget.NewButton("light", func() {
		app.Settings().SetTheme(theme.LightTheme())
	})

	menuGroup := container.New(layout.NewGridLayout(1), select1Layout, button4, button5)
	menuLayout := container.New(layout.NewCenterLayout(), menuGroup)

	mainLayout := container.New(layout.NewBorderLayout(nil, nil, nil, menuLayout), menuLayout)

	mainWindow.SetContent(mainLayout)
	mainWindow.ShowAndRun()
}

```

### Device (please complete the following information):
 - Windows
 - 21H1
 - Go 1.17
 - Fyne version: 2.0.4

**Comment by andydotxyz** [comment]
I cannot replicate this on the upcoming release of v2.1 - perhaps you can test against `develop` branch to verify?

**Comment by tandem97** [comment]
> I cannot replicate this on the upcoming release of v2.1 - perhaps you can test against `develop` branch to verify?

That's true, me too. When i change version back to the last release, the problem returns. So in develop version it's okey.

**Comment by andydotxyz** [comment]
Thanks. Closed as resolved in next release.
