### ISSUE TITLE
When trying to compile the Fyne examples, I got : 'KHR/khrplatform.h' file not found

### ISSUE THREAD

**Issue by serge-hulne** [fyne-io/fyne#2434]
When trying to compile the Fyne examples, I got : 'KHR/khrplatform.h' file not found

```
- go version go1.17 darwin/arm64
- System Version:	macOS 11.5.2 (20G95)
- Kernel Version:	Darwin 20.6.0
```

```
ls
AUTHORS		README.md	data.go		go.sum		textedit
Icon.png	bugs		fractal		img		vendor
LICENSE		clock		go.mod		main.go		xkcd
sergehulne@Serges-Mac-mini examples % go build
go: downloading fyne.io/fyne/v2 v2.0.0
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200625191551-73d3c3675aa3
go: downloading golang.org/x/image v0.0.0-20200618115811-c13761719519
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading golang.org/x/text v0.3.3
# github.com/go-gl/gl/v3.1/gles2
../../../../../go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.1/gles2/package.go:38:11: fatal error: 'KHR/khrplatform.h' file not found
 #include <KHR/khrplatform.h>
          ^~~~~~~~~~~~~~~~~~~
1 error generated.

```

**Comment by changkun** [comment]
It may be a problem with the glfw version, does the following steps help you resolve the problem?

1. Manually replace glfw version in `go.mod`:

```diff
-github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200625191551-73d3c3675aa3
+github.com/go-gl/glfw/v3.3/glfw v0.0.0-20210410170116-ea3d685f79fb
```

2. Then try the following commands:

```
go clean -cache
go mod tidy
go build
```

**Comment by serge-hulne** [comment]
Do you mean in go.sum ?

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. In particular, could you please say what version of Fyne you are using?

With the formalities out of the way, I am pretty sure that this should have been fixed a while ago unless it has crept up again. If that is the case, it should either way have been fixed upstream in go-gl/gl, I think. https://github.com/go-gl/gl/pull/141

cc @andydotxyz

**Comment by andydotxyz** [comment]
It was indeed fixed in the Fyne repo a while back.
However the error of vendoring required a fix in GLFW repo, so other repos would get the file.
I have back-ported the change to `fyne-io/examples` repo so it should work now, and after v2.1 it should not happen again.

**Comment by serge-hulne** [comment]
ERRATUM 

- I made a fresh installation of the latest version of Fyne 
```go get fyne.io/fyne/v2```

- removed the version of OpenGL I had separately installed via "brew"
```arch -arm64 brew uninstall glfw  ```

- made a fresh clone of github.com/fyne-io/examples
```git clone https://github.com/fyne-io/examples```

 and all the examples from https://github.com/fyne-io/examples work fine now.

**Comment by andydotxyz** [comment]
That is probably because I fixed `examples` repo as mentioned above ;)
