### ISSUE TITLE
Can not SetBackgroundColor for box

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2443]
I need Each box has its own background color，bug I find the setBackgroundColor, it is private function

**Comment by andydotxyz** [comment]
All containers are transparent. You add a background by drawing a rectangle behind it.
For example add both items to a `container.Max`

**Comment by owner888** [comment]
Ok, thanks for the info :)

> All containers are transparent. You add a background by drawing a rectangle behind it.
> For example add both items to a `container.Max`

Ok, thanks for the info :)
