### ISSUE TITLE
Change the size of the window, failed assertion...

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2444]
### Describe the bug:
Drag the mouse to change the size of the window, failed assertion A command encoder is already encoding to this command buffer

### To Reproduce:
Steps to reproduce the behaviour:

### Screenshots:
![2021-09-08 at 4 00 PM](https://user-images.githubusercontent.com/4317332/132479765-70d27463-1349-46e4-8ee7-b5e9b2221e8e.png)

### Device (please complete the following information):
 - **OS:** MacOS, Apple M1
 - **Version:** Big Sur 11.5.2
 - **Go version:** go1.16.6 darwin/arm64
 - **Fyne version:** 2.0.4

**Comment by andydotxyz** [comment]
We are working on this, it has come up a few times #2188.
Closing as duplicate - please re-open if you disagree.
