### ISSUE TITLE
Interacting with another app when window.SetFullScreen(true) will cause the application to hide itself.

### ISSUE THREAD

**Issue by bartimus-primed** [fyne-io/fyne#2448]
I was asked to open a report for this from the slack channel.

### Describe the bug:
When setting window.SetFullScreen(true), the window will hide itself when focusing another window.

### To Reproduce:
1. Set up normal application.
2. Set window.SetFullScreen(true)
3. Click any other application on the taskbar or on another monitor.
4. The fyne app will hide and needs to be alt+tabbed or clicked on to be shown again.

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10 (current)
 - **Go version:** 1.17
 - **Fyne version:** v2.0.4

**Comment by andydotxyz** [comment]
Fixed on `develop` ready for testing and v2.1
