### ISSUE TITLE
Can u support SplitBox for fixed on the left window, and the right window is adaptive

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2451]
### Is your feature request related to a problem? Please describe:
Most desktop applications are fixed on the left window, and the right window is adaptive, but I found that this can only be achieved with a split window, but it cannot achieve my effect.

### Describe the solution you'd like to see:
![111111](https://user-images.githubusercontent.com/4317332/132761213-80379766-e9f2-4f91-985a-55c9b3d07e0e.png)

**Comment by andydotxyz** [comment]
Use a `Border` container, put the left element in the left position and the rest in the center. i.e.
`container.NewBorder(nil, nil, left, nil, content)`

**Comment by andydotxyz** [comment]
Beware of fixing items to a "px" size - be sure it adapts to different platforms not just your desktop.

**Comment by owner888** [comment]
> Use a `Border` container, put the left element in the left position and the rest in the center. i.e.
> `container.NewBorder(nil, nil, left, nil, content)`

thank u, but use NewBorder I can not change left size for use mouse

**Comment by andydotxyz** [comment]
I don't understand - why talk about using the mouse if you want it to be fixed?

**Comment by owner888** [comment]
> I don't understand - why talk about using the mouse if you want it to be fixed?

Because the desktop program needs to adjust the window size
![11111](https://user-images.githubusercontent.com/4317332/132909277-36efc350-f1bf-452f-8146-c1b34fb54ac9.png)

**Comment by andydotxyz** [comment]
The mouse will adjust the content size for the main area as you requested.
The left size will be at the minimum width required to fill the content, which is defined by the content you put in it.

**Comment by owner888** [comment]
> The mouse will adjust the content size for the main area as you requested.
> The left size will be at the minimum width required to fill the content, which is defined by the content you put in it.

oh thank u, I see
