### ISSUE TITLE
Can I SetColor for the box, like the picture

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2458]
### Is your feature request related to a problem? Please describe:
Can I SetColor for the box, like the picture

### Describe the solution you'd like to see:
![2021-09-12 at 1 06 AM](https://user-images.githubusercontent.com/4317332/132957173-6a376007-1125-4538-a2f9-87612e6e5285.png)

**Comment by andydotxyz** [comment]
Yes, you can add background colours by putting a rectangle behind your widget/container.
So adding a new parent container using Max layout and a bg rectangle along with your original content would do what you hope...

```go
container.NewMax(
		canvas.NewRectangle(color.Black),
		container.NewVBox(
			widget.NewLabel("Line 1"),
			widget.NewLabel("Line 2"),
		),
	)
```

**Comment by owner888** [comment]
> Yes, you can add background colours by putting a rectangle behind your widget/container.
> So adding a new parent container using Max layout and a bg rectangle along with your original content would do what you hope...
> 
> ```go
> container.NewMax(
> 	canvas.NewRectangle(color.Black),
> 	container.NewVBox(
> 		widget.NewLabel("Line 1"),
> 		widget.NewLabel("Line 2"),
> 	),
> )
> ```

u are so good, thank u very much.

**Comment by andydotxyz** [comment]
> u are so good, thank u very much.

:) you are welcome.

**Comment by owner888** [comment]
> > u are so good, thank u very much.
> 
> :) you are welcome.

Sony I have the new question, How to change NewButtonWithIcon color

**Comment by andydotxyz** [comment]
Buttons are standard widgets, they follow the theme.
The only colour is the "Primary" colour which is applied to buttons where `Importance = widget.HighImportance`.
The user can change what primary colour is, so don't make any assumptions about which colour will be used.
