### ISSUE TITLE
navigating in entry quickly with ctrl key

### ISSUE THREAD

**Issue by zivoy** [fyne-io/fyne#2462]
### Is it possible to construct a solution with the existing API?
You can make a custom entry with key binds for ctrl + left and right arrows and move the curser using it, but this should be a base feature

### Describe the solution you'd like to see:

When in an entry, you should be able to use the ctrl + left/right arrow keys to quickly naviage by jumping between spaces (or other characters) instead of moving one character at a time.
you should also be able to hold ctrl + shift + an arrow key to select a word

**Comment by andydotxyz** [comment]
Thanks @dweymouth for resolving this (on develop) for v2.4.0 :)
