### ISSUE TITLE
Long text in select item causes weird issue on hover

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2476]
### Describe the bug:

I initially noticed in wormhole-gui that the drop down expanded strangely once I had opened it and hovered the mouse over the items. From my test code, it seems that the issue only happens when the first item (possibly other items as well, haven't tested) are significantly longer than the other. It also happens only once the mouse hovers over the items.
![image](https://user-images.githubusercontent.com/25466657/133601737-ed7c1005-8e8f-4893-a9d0-36ae55dccad1.png)

### To Reproduce:
Steps to reproduce the behaviour:
1. Compile the example code
2. Click on the select widget
3. Hover the mouse over the items
4. See that the drop down expands

5. Change the first item in _themes_ to something short, like "Blue".
6. Hover over and notice that the drop down doesn't expand as above.

### Screenshots:

![image](https://user-images.githubusercontent.com/25466657/133602331-71ff8635-9348-4120-9b23-ef6ffb7bd56d.png)
![image](https://user-images.githubusercontent.com/25466657/133602411-49443cfd-d55b-4000-9a34-d868ad0caf79.png)

![image](https://user-images.githubusercontent.com/25466657/133602461-b448a21f-29a3-4e6b-bebb-05e6a8e78655.png)
![image](https://user-images.githubusercontent.com/25466657/133602487-f477b815-ee9e-4ee2-991f-ebfc00b49853.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Layouts")

	themes := []string{"A very fancy long theme", "Light", "Dark"}
	selectTheme := &widget.Select{Options: themes, Selected: themes[0]}

	w.SetContent(container.NewVBox(selectTheme))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Fedora 35 with Gnome 40.4.0
 - **Go version:** 1.16.6
 - **Fyne version:** v2.1.0-rc1

**Comment by andydotxyz** [comment]
Resolved on develop, will tag a new release candidate
