### ISSUE TITLE
window.Resize not working with window.SetFixedSize

### ISSUE THREAD

**Issue by taglme** [fyne-io/fyne#248]
When I call window.Resize(mysize) and then window.SetFixedSize(true)  window have not desired size. 
```golang
func main() {
	app := app.New()
	window := app.NewWindow("Test")
	label := widget.NewLabel("Test")
	window.SetContent(label)
	window.Resize(fyne.NewSize(600, 400))
	window.SetFixedSize(true)
	window.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Thanks for the report. Does it work as expected if you change the order of the Resize and SetFixedSize?

**Comment by taglme** [comment]
No, if I change the order of the Resize and SetFixedSize result is same, window have not desired size.
