### ISSUE TITLE
Missing clicks inside file dialog

### ISSUE THREAD

**Issue by alexballas** [fyne-io/fyne#2484]
### Describe the bug:
My app is missing clicks when inside the file dialog. At first I thought it was my idea. I tried a different mouse and started clicking fast the various predefined locations to the left (Home/Computer/Documents etc) or just select files. Not all my clicks will trigger the buttons.

### Steps to reproduce:
- Open file dialog
- Client randomly (and quickly) the various buttons or files.
- You'll notice that some clicks wont go through
- Click speed seems to affect this. Keeping a delay between my mouse clicks seems to not cause any misses

### Device (please complete the following information):
 - **OS:** Ubuntu 18.04
 - **Go version:** 1.7.1
 - **Fyne version:** 2.1.0

I dont have the same issue with release 2.0.3

**Comment by tandem97** [comment]
![image](https://user-images.githubusercontent.com/82098282/133940525-398020e2-ae75-4c5e-8d13-46aac8c01116.png)
Have the same problem on win 10

**Comment by alexballas** [comment]
Raised PR https://github.com/fyne-io/fyne/pull/2492

**Comment by andydotxyz** [comment]
Thanks for the fix @alexballas , this is now on develop for wider testing.
