### ISSUE TITLE
Can u support right mousedown menu for Tree

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2485]
### Is your feature request related to a problem? Please describe:
Can u support right mousedown menu for Tree

### Describe the solution you'd like to see:
![2021-09-20 at 2 21 AM](https://user-images.githubusercontent.com/4317332/133940224-9814c911-1b2b-49b3-a126-e41432391559.png)

**Comment by andydotxyz** [comment]
Items in a tree can register for this by adding the `TappedSecondary` function like any other widget.
It doesn't make sense to add this at the tree level, as the operation is on the objects inside the nodes

**Comment by owner888** [comment]
> Items in a tree can register for this by adding the `TappedSecondary` function like any other widget.
> It doesn't make sense to add this at the tree level, as the operation is on the objects inside the nodes

Oh i see, thank you
