### ISSUE TITLE
MacOS Panic

### ISSUE THREAD

**Issue by mdonahue-godaddy** [fyne-io/fyne#2488]
### Describe the bug:
uncaught exception 'NSInternalInconsistencyException'

### To Reproduce:
$ fyne_demo
2021/09/17 17:46:33 Lifecycle: Started
2021/09/17 17:46:33 Lifecycle: Entered Foreground
2021/09/17 17:47:05 Lifecycle: Exited Foreground
2021/09/17 17:47:09 Lifecycle: Entered Foreground
2021-09-17 17:47:32.684 fyne_demo[36358:1665499] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff205731db __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff202acd92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2059b8e6 -[NSException raise] + 9
	3   AppKit                              0x00007fff22d2aeb2 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22d4c0e4 -[NSWindow _commonMinMaxSizeChanged] + 23
	5   fyne_demo                           0x000000000456b7be _glfwPlatformSetWindowSizeLimits + 94
	6   fyne_demo                           0x000000000406eb50 runtime.asmcgocall + 112
)
libc++abi: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff203d292e m=11 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff203d292e
stack: frame={sp:0x7000026d37b8, fp:0x0} stack=[0x700002655350,0x7000026d4f50)
00007000026d36b8:  00007000026d3a00  0000000000000000 
00007000026d36c8:  0000000004ec3000  00007000026d3700 
00007000026d36d8:  00007fff20229667  0000000000000000 
00007000026d36e8:  00007000026d3720  0000000000000001 
00007000026d36f8:  0000000000000000  0000000032aaaba2 
00007000026d3708:  0000000000000000  0000000000000000 
00007000026d3718:  00007000026d38e0  0000000000000000 
00007000026d3728:  0000000032aaaba2  0000000000000000 
00007000026d3738:  0000000000000000  0000000000000000 
00007000026d3748:  0000000000000000  0000000000000000 
00007000026d3758:  0000000000000000  0000000000000000 
00007000026d3768:  0000000000000003  0000000000000000 
00007000026d3778:  0000000000000000  00007fff806f92c0 
00007000026d3788:  00007fff8072d4e0  00007fff2030f886 
00007000026d3798:  0000000000000000  00007000026d37e0 
00007000026d37a8:  00007fff203122b6  0000000000000000 
00007000026d37b8: <00007fff204015bd  0000000000000003 
00007000026d37c8:  00007fff8072dae0  00007000026d5000 
00007000026d37d8:  00007000026d37f8  00007000026d3820 
00007000026d37e8:  00007fff20356406  ee34ed6fe4d70083 
00007000026d37f8:  00007000fffff9df  ffffffff8072dae0 
00007000026d3808:  00007000026d3900  00007fff203c7fd1 
00007000026d3818:  00007000026d3830  00007000026d3930 
00007000026d3828:  00007fff203c4ef2  0000000000000000 
00007000026d3838:  00007fff203c802c  00007fff7b88a065 
00007000026d3848:  00007fff202c9c08  00007fff7b88a070 
00007000026d3858:  ffffffffffffffc9  0000000000000390 
00007000026d3868:  0000000004ecd600  00007000026d3900 
00007000026d3878:  00007fff2022d663  0000000000000000 
00007000026d3888:  0000000000000000  0000000000000000 
00007000026d3898:  000000000d15bfb0  0000000600000000 
00007000026d38a8:  0000000000000039  00007000026d3930 
runtime: unknown pc 0x7fff203d292e
stack: frame={sp:0x7000026d37b8, fp:0x0} stack=[0x700002655350,0x7000026d4f50)
00007000026d36b8:  00007000026d3a00  0000000000000000 
00007000026d36c8:  0000000004ec3000  00007000026d3700 
00007000026d36d8:  00007fff20229667  0000000000000000 
00007000026d36e8:  00007000026d3720  0000000000000001 
00007000026d36f8:  0000000000000000  0000000032aaaba2 
00007000026d3708:  0000000000000000  0000000000000000 
00007000026d3718:  00007000026d38e0  0000000000000000 
00007000026d3728:  0000000032aaaba2  0000000000000000 
00007000026d3738:  0000000000000000  0000000000000000 
00007000026d3748:  0000000000000000  0000000000000000 
00007000026d3758:  0000000000000000  0000000000000000 
00007000026d3768:  0000000000000003  0000000000000000 
00007000026d3778:  0000000000000000  00007fff806f92c0 
00007000026d3788:  00007fff8072d4e0  00007fff2030f886 
00007000026d3798:  0000000000000000  00007000026d37e0 
00007000026d37a8:  00007fff203122b6  0000000000000000 
00007000026d37b8: <00007fff204015bd  0000000000000003 
00007000026d37c8:  00007fff8072dae0  00007000026d5000 
00007000026d37d8:  00007000026d37f8  00007000026d3820 
00007000026d37e8:  00007fff20356406  ee34ed6fe4d70083 
00007000026d37f8:  00007000fffff9df  ffffffff8072dae0 
00007000026d3808:  00007000026d3900  00007fff203c7fd1 
00007000026d3818:  00007000026d3830  00007000026d3930 
00007000026d3828:  00007fff203c4ef2  0000000000000000 
00007000026d3838:  00007fff203c802c  00007fff7b88a065 
00007000026d3848:  00007fff202c9c08  00007fff7b88a070 
00007000026d3858:  ffffffffffffffc9  0000000000000390 
00007000026d3868:  0000000004ecd600  00007000026d3900 
00007000026d3878:  00007fff2022d663  0000000000000000 
00007000026d3888:  0000000000000000  0000000000000000 
00007000026d3898:  000000000d15bfb0  0000000600000000 
00007000026d38a8:  0000000000000039  00007000026d3930 

goroutine 146 [syscall]:
runtime.cgocall(0x456fa80, 0xc000192e08, 0x42bc100)
	/usr/local/opt/go/libexec/src/runtime/cgocall.go:154 +0x5b fp=0xc000192dd8 sp=0xc000192da0 pc=0x4006f3b
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwSetWindowSizeLimits(0xd149d40, 0x90000000c0, 0x90000000c0)
	_cgo_gotypes.go:2306 +0x45 fp=0xc000192e08 sp=0xc000192dd8 pc=0x44d1ec5
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSizeLimits.func1(0xc0000beb40, 0xc0, 0x90, 0xc0, 0x90)
	/Users/mdonahue/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:505 +0x7d fp=0xc000192e40 sp=0xc000192e08 pc=0x44d7e5d
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetSizeLimits(0xc0000beb40, 0xc0, 0x90, 0xc0, 0x90)
	/Users/mdonahue/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:505 +0x57 fp=0xc000192e78 sp=0xc000192e40 pc=0x44d5c97
fyne.io/fyne/v2/internal/driver/glfw.(*window).fitContent(0xc000442600)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:305 +0x196 fp=0xc000192ed0 sp=0xc000192e78 pc=0x44e12b6
fyne.io/fyne/v2/internal/driver/glfw.(*window).SetFixedSize(0xc000442600, 0x4334000043700001)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:210 +0x53 fp=0xc000192ef0 sp=0xc000192ed0 pc=0x44e0a93
fyne.io/fyne/v2/cmd/fyne_demo/tutorials.windowScreen.func3.1(0xc009696301)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/cmd/fyne_demo/tutorials/window.go:34 +0x3f fp=0xc000192f20 sp=0xc000192ef0 pc=0x454329f
fyne.io/fyne/v2/widget.(*Check).SetChecked(0xc009696360, 0x86fa1101)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/widget/check.go:152 +0x57 fp=0xc000192f38 sp=0xc000192f20 pc=0x448dff7
fyne.io/fyne/v2/widget.(*Check).Tapped(0xc009696360, 0xc00448d9a0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/widget/check.go:193 +0x5f fp=0xc000192f80 sp=0xc000192f38 pc=0x448e23f
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:885 +0x38 fp=0xc000192fa0 sp=0xc000192f80 pc=0x44ea4f8
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc000442600)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/window.go:58 +0x66 fp=0xc000192fd8 sp=0xc000192fa0 pc=0x436f206
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000192fe0 sp=0xc000192fd8 pc=0x406eec1
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:1388 +0x11c

goroutine 1 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0000a6c80)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:96 +0x175
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0000a6c80)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/driver.go:83 +0x3a
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0001bc000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:461 +0x45
main.main()
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/cmd/fyne_demo/main.go:66 +0x4d0

goroutine 6 [chan receive]:
fyne.io/fyne/v2/test.NewApp.func1(0xc0000a82a0, 0xc000032980)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/test/testapp.go:113 +0x48
created by fyne.io/fyne/v2/test.NewApp
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/test/testapp.go:111 +0x2f1

goroutine 7 [syscall]:
syscall.syscall6(0x45063c0, 0x4, 0x0, 0x0, 0xc000196e88, 0xa, 0x4d838b0, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:41 +0x2e
golang.org/x/sys/unix.kevent(0x4, 0x0, 0x0, 0xc000196e88, 0xa, 0x4d838b0, 0x0, 0x0, 0x0)
	/Users/mdonahue/go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/zsyscall_darwin_amd64.go:276 +0x98
golang.org/x/sys/unix.Kevent(0x4, 0x0, 0x0, 0x0, 0xc000196e88, 0xa, 0xa, 0x4d838b0, 0x0, 0x0, ...)
	/Users/mdonahue/go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/syscall_bsd.go:429 +0x71
github.com/fsnotify/fsnotify.read(0x4, 0xc000196e88, 0xa, 0xa, 0x4d838b0, 0xc000196e88, 0x0, 0xa, 0x0, 0x0)
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:511 +0x6e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00008d200)
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:274 +0x81b
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:62 +0x199

goroutine 8 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0xc00008d200, 0xc00002e500, 0x46, 0xc000438dd0, 0xc000438de0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/app/settings_desktop.go:42 +0x5a
created by fyne.io/fyne/v2/app.watchFile
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/app/settings_desktop.go:41 +0xef

goroutine 19 [syscall]:
syscall.syscall6(0x45063c0, 0xa, 0x0, 0x0, 0xc00005c688, 0xa, 0x4d838b0, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:41 +0x2e
golang.org/x/sys/unix.kevent(0xa, 0x0, 0x0, 0xc00005c688, 0xa, 0x4d838b0, 0x0, 0x0, 0x0)
	/Users/mdonahue/go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/zsyscall_darwin_amd64.go:276 +0x98
golang.org/x/sys/unix.Kevent(0xa, 0x0, 0x0, 0x0, 0xc00005c688, 0xa, 0xa, 0x4d838b0, 0x0, 0x0, ...)
	/Users/mdonahue/go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/syscall_bsd.go:429 +0x71
github.com/fsnotify/fsnotify.read(0xa, 0xc00005c688, 0xa, 0xa, 0x4d838b0, 0xc00005c688, 0x0, 0xa, 0x0, 0x0)
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:511 +0x6e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0001a20c0)
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:274 +0x81b
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/mdonahue/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:62 +0x199

goroutine 45 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan.func1(0xc0051c0fd0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_func.go:33 +0x2ef
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_func.go:25 +0xb8

goroutine 20 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0xc0001a20c0, 0xc00019e100, 0x36, 0xc0001a6010, 0xc0001a6020)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/app/settings_desktop.go:42 +0x5a
created by fyne.io/fyne/v2/app.watchFile
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/app/settings_desktop.go:41 +0xef

goroutine 21 [runnable, locked to thread]:
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowBlendFunc(0x7fff6bd01e6b, 0x30300000001)
	_cgo_gotypes.go:3472 +0x45
github.com/go-gl/gl/v3.2-core/gl.BlendFunc(...)
	/Users/mdonahue/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20210813123233-e4099ee2221f/v3.2-core/gl/package.go:8861
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).glDrawTexture(0xc0007a9980, 0x3f80000000000115)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/painter/gl/gl_core.go:323 +0x13c
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawTextureWithDetails(0xc0007a9980, 0x4763678, 0xc0000e96c0, 0xc00a6434a0, 0x4383e40044970000, 0x4000000040000000, 0x4434f00044988000, 0x0, 0x3f800000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/painter/gl/draw.go:30 +0x16c
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawGradient(0xc0007a9980, 0x4763678, 0xc0000e96c0, 0xc00a6434a0, 0x4383e40044970000, 0x4434f00044988000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/painter/gl/draw.go:55 +0xcf
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawObject(0xc0007a9980, 0x4763678, 0xc0000e96c0, 0x4383e40044970000, 0x4434f00044988000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/painter/gl/draw.go:107 +0x15f
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Paint(0xc0007a9980, 0x4763678, 0xc0000e96c0, 0x4383e40044970000, 0x4434f00044988000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/painter/gl/painter.go:69 +0x98
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0xc00a0f1080, 0x4383e40044970000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/canvas.go:279 +0xdd
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1(0x4763678, 0xc0000e96c0, 0x4383e40044970000, 0x0, 0x4f0000004f000000, 0x4d54900)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/canvas.go:418 +0x142
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763678, 0xc0000e96c0, 0x43671c0043826600, 0x4764278, 0xc00019caa0, 0x43671c0043826666, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:169 +0x482
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4764278, 0xc00019caa0, 0x43651c0043816600, 0x47644b8, 0xc00081be00, 0x43651c0043816666, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x47644b8, 0xc00081be00, 0x4313c40043816600, 0x4763498, 0xc00a0c7540, 0x4313c40043816666, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763498, 0xc00a0c7540, 0x42b4b000437ccc00, 0x4764518, 0xc008e10a80, 0x42b4b000437ccccd, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4764518, 0xc008e10a80, 0x42b4b000437ccc00, 0x4763498, 0xc00a0c7a80, 0x42b4b000437ccccd, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763498, 0xc00a0c7a80, 0x42b4b000437ccc00, 0x4763498, 0xc0001c2080, 0x42b4b000437ccccd, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763498, 0xc0001c2080, 0x40800000437ccc00, 0x4763498, 0xc0001c2300, 0x40800000437ccccd, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763498, 0xc0001c2300, 0x4080000040800000, 0x4763b58, 0xc00047c8c0, 0x4080000040800000, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0x4763b58, 0xc00047c8c0, 0xcca37900, 0x0, 0x0, 0x0, 0x0, 0x4f0000004f000000, 0xc00a643d08, 0xc00a643ce0, ...)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:190 +0x3ff
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree(0x4763b58, 0xc00047c8c0, 0xc00a643d08, 0xc00a643ce0, 0x406a368)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/util.go:134 +0x94
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc0001b0120, 0xc00007e4c0, 0xc00a643de0, 0xc00a643db0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/canvas.go:439 +0x15c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0001b0120, 0xc00a643de0, 0xc00a643db0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/canvas.go:351 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc0001b0120, 0x4434f00044988000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/canvas.go:293 +0x118
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:174 +0x93
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0001bc000, 0xc00a643e90)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:1329 +0x58
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000a6c80, 0xc0001bc000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:165 +0x65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000a6c80, 0xc000182180, 0xc000180050)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:228 +0x2f1
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/loop.go:192 +0xbd

goroutine 22 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc0001bc000)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/window.go:57 +0x9d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:1388 +0x11c

goroutine 23 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan.func1(0xc0001a6060)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:35 +0x34f
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:27 +0xb8

goroutine 14 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan.func1(0xc006906d40)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:35 +0x34f
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:27 +0xb8

goroutine 46 [chan receive]:
fyne.io/fyne/v2/data/binding.queueItem.func1.1()
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/data/binding/queue.go:18 +0x65
created by fyne.io/fyne/v2/data/binding.queueItem.func1
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/data/binding/queue.go:17 +0x51

goroutine 11 [chan receive]:
fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations.func1(0xc000208140, 0xc0000a6cd0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/animation/runner.go:69 +0x27b
created by fyne.io/fyne/v2/internal/animation.(*Runner).runAnimations
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/animation/runner.go:67 +0x56

goroutine 53 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/opt/go/libexec/src/runtime/time.go:193 +0xd2
fyne.io/fyne/v2/cmd/fyne_demo/tutorials.canvasScreen.func1(0xc009698300)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/cmd/fyne_demo/tutorials/canvas.go:25 +0x45
created by fyne.io/fyne/v2/cmd/fyne_demo/tutorials.canvasScreen
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/cmd/fyne_demo/tutorials/canvas.go:23 +0x145

goroutine 48 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc000442200)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/common/window.go:57 +0x9d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/window.go:1388 +0x11c

goroutine 56 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan.func1(0xc000438c60)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:35 +0x34f
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:27 +0xb8

goroutine 49 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan.func1(0xc002470ce0)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:35 +0x34f
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:27 +0xb8

goroutine 147 [chan receive]:
fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan.func1(0xc0031eda40)
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:35 +0x34f
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
	/Users/mdonahue/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/async/chan_canvasobject.go:27 +0xb8

rax    0x0
rbx    0x7000026d5000
rcx    0x7000026d37b8
rdx    0x0
rdi    0x6203
rsi    0x6
rbp    0x7000026d37e0
rsp    0x7000026d37b8
r8     0x7000026d3680
r9     0x0
r10    0x0
r11    0x246
r12    0x6203
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7fff203d292e
rflags 0x246
cs     0x7
fs     0x0
gs     0x0

### Screenshots:
Not available

### Example code:
fyne_demo

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:**  BigSur 11.6
 - **Go version:** go version go1.16.5 darwin/amd64
 - **Fyne version:** Latest GitHub from 9/19/2021 (2.1.0)

**Comment by andydotxyz** [comment]
I think I figured out what was going on - can you test #2489 and see if it helps @mdonahue-godaddy ? Thanks

**Comment by andydotxyz** [comment]
Pretty sure this was resolved :)
