### ISSUE TITLE
TextGrid background color can show gaps in render

### ISSUE THREAD

**Issue by vit1251** [fyne-io/fyne#2493]
Vertical space in TextGrid rendering with Black background color

![Some vertical space](https://imgur.com/M0IGALG.png)

How to fix problem?

**Comment by andydotxyz** [comment]
Thanks for clarifying, this is a bug on TextGrid, we will have to fix it in our widget maths / layout precision.

**Comment by vit1251** [comment]
OK. Thanks for answer. I isolate this component in separate repository for better debugging https://github.com/vit1251/fyne-viewer

**Comment by andydotxyz** [comment]
Resolved on `develop` ready for a v2.1.1 release
