### ISSUE TITLE
`go get` module is deprecated error on Go v1.17.1 Mac OSX

### ISSUE THREAD

**Issue by ookangzheng** [fyne-io/fyne#2496]
### Describe the bug:
I try to do go get install latest version via terminal and I get `go get` module is deprecated error. 

### To Reproduce:
```
❯ go get fyne.io/fyne/v2/cmd/fyne
go: downloading fyne.io/fyne/v2 v2.1.0
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/Kodeworks/golang-image-ico v0.0.0-20141118225523-73f0f4cfade9
go: downloading github.com/josephspurrier/goversioninfo v0.0.0-20200309025242-14b0ab84c6ca
go: downloading github.com/lucor/goinfo v0.0.0-20210802170112-c078a2b0f08b
go: downloading github.com/jackmordaunt/icns v0.0.0-20181231085925-4f16af745526
go: downloading github.com/BurntSushi/toml v0.4.1
go: downloading github.com/akavel/rsrc v0.8.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 11.5.2
 - **Go version:** 1.17.1
 - **Fyne version:** 2.1

**Comment by andydotxyz** [comment]
No need to do that, 1.17 works just fine.

**Comment by ookangzheng** [comment]
hmm, still I won't able to install fyne on my Mac `go get fyne.io/fyne/v2/cmd/fyne` 
Any hint?

**Comment by andydotxyz** [comment]
The first time it installed successfully - the deprecation warning is not an error.
What makes you say it is not installed?

**Comment by ookangzheng** [comment]
First time install is not successful. I'm on a whole new machine.

**Comment by andydotxyz** [comment]
Please expand on how you know it was not successful?
* Was there an error message?
* Was the app not found after install?
* Does something crash?

**Comment by ookangzheng** [comment]
There is no error, app `cmd not found` after install, no crash. 
After couple times of trying. I install go with `asdf` instead of Golang.org pkg way. 
And everything work as expected.

https://user-images.githubusercontent.com/6301735/134337677-041be617-d642-4416-824e-261fd99a21ea.mp4

**Comment by andydotxyz** [comment]
Hmm. `asdf` should not be required. Is it possible that before installing that your `PATH` did not include `$GOBIN`?

**Comment by andydotxyz** [comment]
If $GOBIN is empty it will default, to $GOPATH/bin.
The bin you have in your PATH is the $GOROOT/bin, which is where Go tools are - the other is where installed binaries reside, you need both on your path. Setting GOBIN to GOROOT/bin runs the risk of installs overwriting system tools, which is dangerous!
