### ISSUE TITLE
How about enable GitHUB disscussions for component developer may collaborate

### ISSUE THREAD

**Issue by vit1251** [fyne-io/fyne#2500]
How about enable GitHUB disscussions for collaborate component developers?

**Comment by andydotxyz** [comment]
So far we have done all collaboration on the gophers Slack server - #fyne for user facing discussion and #fyne-contributors for working on the toolkit.
What do you think github discussions would add?

**Comment by vit1251** [comment]
Slack is a wonderful tool for online interaction, but it mixes topics up into a big mess.
Discussions are grouped by topic and this allows you to be digress for an period without lost threading.

**Comment by changkun** [comment]
GitHub discussion is IMO quite limited (still) as people (users) tend to mix up the usage of the issue tracker and discussion panel. Nothing really prevents people from opening an issue for discussion-only purposes.

Good use at the moment might follow how Go team is using, which retracts the permission from the public where only team members can open a discussion thread, to involve discussion and poll, etc. But so far the need for that seems also quite limited.

**Comment by andydotxyz** [comment]
I prefer discussions attached to the issue they relate to - this is much more searchable than going through chat as well.
Remember we use GitHub to discuss Fyne development, not it’s usage. General support belongs on other channels like Slack, Discord or eMail.

**Comment by vit1251** [comment]
> Remember we use GitHub to discuss Fyne development, not it’s usage

Yep. How about extending base components it still fyne development or using? I think people may contribute to fyne by make brand new component like chart or some no so common and exists.

**Comment by andydotxyz** [comment]
> Yep. How about extending base components it still fyne development or using?

If developers would like to make custom components that is their work, if they would like to contribute them to fyne-x then that is discussion that would happen on GitHub through PRs.
