### ISSUE TITLE
Fyne error:  Attempt to access current Fyne app when none is started

### ISSUE THREAD

**Issue by josephbudd** [fyne-io/fyne#2502]
### Describe the bug:
In this simple example app when I open the editor panel I get the error. The app runs as if there is no error. The other panels don't generate the error.

The code is zipped and attached.

### To Reproduce:
Just unzip the code, build it and run it.

### Screenshots:
nil@NIL:~/go/src/github.com/josephbudd/fynepanels$ ./fynepanels 
2021/09/25 20:39:07 BuildEditPanel completed
2021/09/25 20:39:16 EditPanel.Show() completed
2021/09/25 20:39:16 Fyne error:  Attempt to access current Fyne app when none is started
2021/09/25 20:39:16   At: /home/nil/go/pkg/mod/fyne.io/fyne@v1.4.3/app.go:79
nil@NIL:~/go/src/github.com/josephbudd/fynepanels$ 

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Ubuntu 18.04.6 LTS
 - **Go version:** go version go1.17.1 linux/amd64
 - **Fyne version:** fyne.io/fyne/v2
[fynepanels.zip](https://github.com/fyne-io/fyne/files/7230532/fynepanels.zip)

**Comment by andydotxyz** [comment]
Your code is probably loading widgets or icons as global variables, before `app.New` has been started.
This is no longer supported because the theme has not been set up so the widgets may load in incorrect state.

**Comment by josephbudd** [comment]
# You are correct. This is not an Issue

## It was caused by my imports

I had various imports from **/fyne/** not from **/fyne/v2/**.
