### ISSUE TITLE
Mac system - ldflags - H = Windows GUI error reporting

### ISSUE THREAD

**Issue by zhangxianweihebei** [fyne-io/fyne#251]
Ld-My:main a1$ go build -ldflags -H=windowsgui
# _/Users/a1/work/github/testGo/main
libc_pthread_attr_init: initialize bounds (0 < 8)
libc_pthread_attr_setstacksize: initialize bounds (0 < 8)
libc_pthread_attr_setdetachstate: initialize bounds (0 < 8)
libc_pthread_create: initialize bounds (0 < 8)
libc_exit: initialize bounds (0 < 8)
libc_raise: initialize bounds (0 < 8)
libc_open: initialize bounds (0 < 8)
libc_close: initialize bounds (0 < 8)
libc_read: initialize bounds (0 < 8)
libc_write: initialize bounds (0 < 8)
libc_mmap: initialize bounds (0 < 8)
libc_munmap: initialize bounds (0 < 8)
libc_madvise: initialize bounds (0 < 8)
libc_error: initialize bounds (0 < 8)
libc_usleep: initialize bounds (0 < 8)
libc_mach_timebase_info: initialize bounds (0 < 8)
libc_mach_absolute_time: initialize bounds (0 < 8)
libc_gettimeofday: initialize bounds (0 < 8)
libc_sigaction: initialize bounds (0 < 8)
libc_pthread_sigmask: initialize bounds (0 < 8)
libc_sigaltstack: initialize bounds (0 < 8)
/usr/local/go/pkg/tool/darwin_amd64/link: too many errors

**Comment by andydotxyz** [comment]
Why are you using windows build parameters on macOS? Are you trying to cross compile? What are your GOOS and GOARCH environment variables?

**Comment by zhangxianweihebei** [comment]
Mac boot also has CMD window. I want to hide it.

**Comment by andydotxyz** [comment]
Mac applications launched directly will start in a terminal. You need to package the application to access it as a graphical app. See the “fyne” tool, specifically “Fyne package”. https://fyne.io/develop/distribution.html

**Comment by zhangxianweihebei** [comment]
Thank you very much.
