### ISSUE TITLE
Fail to adjust the size and position of the table in a window

### ISSUE THREAD

**Issue by aimin-git** [fyne-io/fyne#2511]
### Describe the bug:

I fail to adjust the size and position of the table in a window

### To Reproduce:
Steps to reproduce the behaviour:

### Screenshots:

The generated window is also full of the table, I intend to draw the table as part of my window.
![image](https://user-images.githubusercontent.com/59191430/135084833-b4e4ed43-8a53-4c53-a372-80d32b46b226.png)

### Example code:

	table := widget.NewTable(
		func() (int, int) { return len(sdk.GetTunnelClient().Policies), 3 },
		func() fyne.CanvasObject {
			return widget.NewLabel("http, 192.168.100.1, 8080")
		},
		func(id widget.TableCellID, cell fyne.CanvasObject) {
			label := cell.(*widget.Label)
			if (id.Row == 0 && id.Col == 0) {
				label.SetText("协议")
			}
			if (id.Row == 0 && id.Col == 1) {
				label.SetText("服务器")
			}		
			if (id.Row == 0 && id.Col == 2) {
				label.SetText("端口")
			}
			/*if (id.Row == 0) {
				label.SetText("协议, 服务器, 端口")
			}*/
			if (id.Row > 0) {
				if (sdk.GetTunnelClient().Policies[id.Row-1].Protocol == 1) {
					if id.Col == 0 {
						label.SetText("http")
					} else if id.Col == 1 {
						label.SetText(sdk.GetTunnelClient().Policies[id.Row-1].IP)
					} else {
						label.SetText(strconv.Itoa(sdk.GetTunnelClient().Policies[id.Row-1].Port))
					}
				} else {
					if id.Col == 0 {
						label.SetText("https/tcp")
					} else if id.Col == 1 {
						label.SetText(sdk.GetTunnelClient().Policies[id.Row-1].IP)
					} else {
						label.SetText(strconv.Itoa(sdk.GetTunnelClient().Policies[id.Row-1].Port))
					}
				}				
			}
		})
		
	table.SetColumnWidth(0, 150)
	table.SetColumnWidth(1, 200)
	table.SetColumnWidth(2, 100)
	table.BaseWidget.Move(fyne.NewPos(219, 209))
	//tableRender := table.CreateRenderer()
	table.BaseWidget.Resize(fyne.NewSize(452, 254))

	//container := fyne.NewContainer(bg, lbg, rbg, lLine, mPage, mLink, mPermits, mSet, imgData, linkIcon1, linkText, linkIcon2, permitsText, linkButton, table)
	//container := fyne.NewContainer(table)

	win.SetContent(table)

	win.Show()
### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 
 - **Go version:** 1.16.6
 - **Fyne version:** 2.1.0

**Comment by Jacalz** [comment]
I would suggest using a layout instead of moving the size manually. Unless the widget is inside a `container.NewWithoutLayout`, the position and size will be controlled by the parent layout. This is not a bug in Fyne but actually part of how the layouts work. I think it is a good idea reading the Layouts FAQ (https://developer.fyne.io/faq/layout) and my talk about layouts during this year's FyneConf: https://www.youtube.com/watch?v=LWn1403gY9E.
