### ISSUE TITLE
OpenGL runtime crash

### ISSUE THREAD

**Issue by drrob1** [fyne-io/fyne#2513]
fyne 2.1.0 on linux pop-os 20.04 fully up to date.  Compiling the program at https://play.golang.org/p/96RPKLiS4ZB
results in a runtime error on this linux system:
2021/09/27 18:10:36 Fyne error:  window creation error
2021/09/27 18:10:36   Cause: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
2021/09/27 18:10:36   At: /home/rob/go/pkg/mod/fyne.io/fyne/v2@v2.1.0/internal/driver/glfw/driver.go:121

The same code runs without errors on a computer running Win10 21H1.  This makes it unlikely that the issue is in my code.  I did not have any issues when I was compiling w/ fyne 2.0.4.

**Comment by Jacalz** [comment]
Ah, sorry. Didn't notice that it was on the developer site issue tracker.

**Comment by andydotxyz** [comment]
Are you able to check what window size it is requesting?
Your code that limits to `maxWidth` and `maxHeight` assumes a scale of 1 (1pt = 1px) which may not be the default on your OS config or monitor DPI.
Please print out the window size before you request it display.
It would also be helpful to know your output scale, so open fyne_demo and see the display info on "Advanced" tab.

**Comment by drrob1** [comment]
Trying to run fyne_demo gives the same error from openGL, about GLX having a bad value.  How do I print out the window size before requesting it to display?

**Comment by drrob1** [comment]
Before these compiled programs were crashing, I was getting this message upon exit 
"Xlib: extension "NV-GLX" missing on display ":0".

I don't know what that means

**Comment by andydotxyz** [comment]
I think the two are unrelated, the otherr issue sounds like #1160 .

Out of curiosity have you recently done a system upgrade and/or tried rebooting?

**Comment by drrob1** [comment]
I have done a system upgrade.  I'll reboot soon and test.
But I have another clue, this line does not seem to be doing anything now : in func loadTheImage, where I have globalW.Show()

That is, the larger or smaller image is not being displayed on Windows.  
And, I took the compiled binary that would not run on this pop-os computer, and tried it on a LinuxMint 20.2 computer.  It ran, but also did not update the image when the size change keys are hit.
Does that also suggest an issue w/ the internal fyne code that displays a window?

**Comment by andydotxyz** [comment]
> But I have another clue, this line does not seem to be doing anything now : in func loadTheImage, where I have globalW.Show()

I don't understand this point - you show the window when the program runs, calling it a second time would not do anything?

**Comment by drrob1** [comment]
I keep my system updated for it's version number.  I keep to long term releases.
I rebooted, and the error did go away.
How interesting.
I'm still getting "Xlib: extension "NV-GLX" missing on display ".0"
but you already wrote that you believe that to be a known issue that is separate

**Comment by andydotxyz** [comment]
Thanks for updating this. It is not the first time we have seen that an upgrade pending reboot has broken apps.
Hopefully the problem can be resolved by the distributions or their upgrade software.
