### ISSUE TITLE
Need advice about packaging

### ISSUE THREAD

**Issue by amo13** [fyne-io/fyne#2514]
I'd like to package my application for Linux, MacOS and Windows. I understand that running `fyne package -release` should do the magic. But I have two questions about it:

1. I see [here](https://github.com/fyne-io/fyne/pull/2398) that there should be a convenient possibility to specify the packaging metadata in a My-App.toml file. But how do I tell the `fyne` command to read and use it? I have tried `fyne package -release My-App.toml` but it does not work.
2. I run/build my application with `go build -ldflags "-X main.BuildDate=$(Get-Date -format 'u')" .` so it always includes the build date. Is there a way to use the ldflags part with fyne while packaging? I understand that I should let `fyne package ...` build the application instead of building it myself and pointing `fyne package -executable ...` to the previously built executable, but is there a way to pass the ldflags?

### Device:
 - **OS:** Linux, MacOS and Windows
 - **Go version:** 1.17.1
 - **Fyne version:** 2.1

Thank you a lot in advance for any help with this!

**Comment by andydotxyz** [comment]
1. The file is `FyneApp.toml`, there is no way to specify the file name, it will simply use that one if it exists.
2. We don't currently support additional ldflags, but it has been mentioned before. If you want to compile the executable using Go and your manual flags you can then tell `fyne package` to use this instead of building again by passing the `-exe <file>` flag.

**Comment by amo13** [comment]
Thank you very much!

What is the disadvantage of specifying `-exe <file>` instead of letting `fyne package ...` build it?

**Comment by andydotxyz** [comment]
Just more commands really. You should end up with the same package, you just have the additional step.

**Comment by amo13** [comment]
Thank you very much for your answers!
