### ISSUE TITLE
Can u Add TableCellID param to CreateCell

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2516]
Can u Add TableCellID param to CreateCell Function,  Because I found that the cell size will be initialized according to the CanvasObject size returned by CreateCell, I will first calculate the longest row in each column and use it as the initial label content, otherwise, like fyne_demo, some content will be cut off xD.

CreateCell   func() fyne.CanvasObject
UpdateCell   func(id TableCellID, template fyne.CanvasObject)
OnSelected   func(id TableCellID)

### Describe the solution you'd like to see:

![2021-09-30 at 12 57 AM](https://user-images.githubusercontent.com/4317332/135323332-2554e482-680b-464a-ba02-2ebdb8c7d12a.png)

**Comment by andydotxyz** [comment]
This is not how table works. Cells are created to be put in a cache - when created they do not know what content they will show.
All cells in a tree are the same size unless you call `Table.SetColumnWidth`, which you can see being used for the first column in that example.

**Comment by owner888** [comment]
> This is not how table works. Cells are created to be put in a cache - when created they do not know what content they will show. All cells in a tree are the same size unless you call `Table.SetColumnWidth`, which you can see being used for the first column in that example.

No bro, I have try CreateCell func()
t := widget.NewTable(
        func() (int, int) { return rowsNum, colsNum },
        func() fyne.CanvasObject {
            return widget.NewLabel("Cell 000, 000")
        }

return widget.NewLabel("Cell 000, 000")
return widget.NewLabel("Cell")

The initial width of the table they generate in the above two lines is different, because I can’t judge the cell size based on the string length，But I found that the size of the fyne.CanvasObject that generates the CreateCell callback function can change the size of the cell

**Comment by andydotxyz** [comment]
I'm not sure why you are disagreeing with me, I was trying to explain how table works.
If you want a column to have a different width then use `Table.SetColumnWidth` otherwise all cells will be the same size.
The size of a cell is set by the minimum size of the template you create. Template cells can be re-used to draw any cell. They will update to fit inside the column width they are used in.

**Comment by owner888** [comment]
> I'm not sure why you are disagreeing with me, I was trying to explain how table works.
> If you want a column to have a different width then use `Table.SetColumnWidth` otherwise all cells will be the same size.
> The size of a cell is set by the minimum size of the template you create. Template cells can be re-used to draw any cell. They will update to fit inside the column width they are used in.

Oh I see, I was wrong, there is no cellID before the cell is generated. thanks bro

**Comment by andydotxyz** [comment]
Perhaps this blog post explains better: https://fynelabs.com/2022/12/30/building-complex-tables-with-fyne/
