### ISSUE TITLE
does the table widget's content is only support Label object ,any cell's type can be diffrent

### ISSUE THREAD

**Issue by yanyuxuanz** [fyne-io/fyne#2517]
Does the table widget's content is only support Label object  ? any table cells has different widget type.like  cell 1 type as image. row 2 as checkbox .row 3 as label text  and row 3 as other types.

**Comment by andydotxyz** [comment]
The contents of a Table cell can be any type, it is set by the `CreateCell` callback function.
However, Table (like List and Tree) require all cells to be of the same type (at this time).
This constraint is how they maintain high performance. We are exploring how it could be possible to balance the two in future releases.
