### ISSUE TITLE
Placeholder of Text in entry is not placed correctly after applying theme

### ISSUE THREAD

**Issue by aimin-git** [fyne-io/fyne#2518]
### Describe the bug:

Placeholder of Text in entry is not placed correctly after applying theme

### To Reproduce:
Steps to reproduce the behaviour:

### Screenshots:

After I applying them, by 
 App.Settings().SetTheme(newCustomTheme())

![image](https://user-images.githubusercontent.com/59191430/135401692-4223702f-5bdc-4926-8eff-5169068c0b87.png)

Before I applying theme:
![image](https://user-images.githubusercontent.com/59191430/135402407-e3d486e9-5327-45d3-8184-d2a7509dc606.png)

### Example code:

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

var (
	purple = &color.NRGBA{R: 128, G: 0, B: 128, A: 255}
	orange = &color.NRGBA{R: 198, G: 123, B: 0, A: 255}
	grey   = &color.Gray{Y: 123}
)

// customTheme is a simple demonstration of a bespoke theme loaded by a Fyne app.
type customTheme struct {
}

var _ fyne.Theme = (*customTheme)(nil)

func (customTheme) Color(c fyne.ThemeColorName, _ fyne.ThemeVariant) color.Color {
	switch c {
	case theme.ColorNameBackground:
		return purple
	case theme.ColorNameButton, theme.ColorNameDisabled:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 255}
	case theme.ColorNamePlaceHolder, theme.ColorNameScrollBar:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 150}
	case theme.ColorNameInputBackground:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 50}
	case theme.ColorNamePrimary, theme.ColorNameHover, theme.ColorNameFocus:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 100}
	case theme.ColorNameShadow:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 150}
	case theme.ColorNameForeground:
		return &color.RGBA{R: 15, G: 78, B: 221, A: 255}
	default:
		return color.White
	}
}

func (customTheme) Font(style fyne.TextStyle) fyne.Resource {
	return theme.DarkTheme().Font(style)
}

func (customTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (customTheme) Size(s fyne.ThemeSizeName) float32 {
	switch s {
	case theme.SizeNamePadding:
		return 8
	case theme.SizeNameInlineIcon:
		return 20
	case theme.SizeNameScrollBar:
		return 10
	case theme.SizeNameScrollBarSmall:
		return 5
	case theme.SizeNameText:
		return 14
	case theme.SizeNameHeadingText:
		return 30
	case theme.SizeNameSubHeadingText:
		return 25
	case theme.SizeNameCaptionText:
		return 15
	case theme.SizeNameInputBorder:
		return 2
	default:
		return 0
	}
}

func newCustomTheme() fyne.Theme {
	return &customTheme{}
}
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:**  LTSC
 - **Go version:** 1.16.8
 - **Fyne version:** 2.1.0

**Comment by andydotxyz** [comment]
I think the issue here may be that the Entry widget is not expanding correctly, but either way it should be fixed

**Comment by aimin-git** [comment]
When could I get the fix? Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyne-io/fyne"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Placeholder of Text in entry is not placed correctly after applying theme (#2518)





 
I think the issue here may be that the Entry widget is not expanding correctly, but either way it should be fixed
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andydotxyz** [comment]
I don't know. This project is run by volunteers and we work on what we can, when we can.
If you would like someone to work on this sooner please consider checking out our sponsorship levels.

**Comment by aimin-git** [comment]
How can I make sure my Entry widget is expanded correctly? Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyne-io/fyne"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Placeholder of Text in entry is not placed correctly after applying theme (#2518)





 
I think the issue here may be that the Entry widget is not expanding correctly, but either way it should be fixed
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jacalz** [comment]
This is mostly a bug tracker for the development of Fyne. I would suggest the #fyne channel on Gophers Slack for questions and help with development.

**Comment by andydotxyz** [comment]
What you have found appears to be a bug. We will fix it.
The most likely workaround is to set the theme before you create any widgets, most theme bugs are due to loading the theme after the widgets were created.

**Comment by aimin-git** [comment]
I tried fyne 2.0.4, no such issue, appears broken in 2.1.0.
Both 2.0.4 and 2.1.0 have issue that input background color and input border line are not set correctly for entry widget.



发自我的iPhone


------------------ Original ------------------
From: Andy Williams ***@***.***&gt;
Date: Fri,Oct 1,2021 6:20 AM
To: fyne-io/fyne ***@***.***&gt;
Cc: aimin-git ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fyne-io/fyne] Placeholder of Text in entry is not placed correctly after applying theme (#2518)





 
What you have found appears to be a bug. We will fix it.
 The most likely workaround is to set the theme before you create any widgets, most theme bugs are due to loading the theme after the widgets were created.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andydotxyz** [comment]
Following your instructions I added the following code:

```go
func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	e1 := widget.NewEntry()
	e1.SetPlaceHolder("Hello")
	e2 := widget.NewEntry()
	e2.SetPlaceHolder("E2")
	w.SetContent(container.NewVBox(
		e1, e2,
	))

	a.Settings().SetTheme(newCustomTheme())
	w.ShowAndRun()
}
```

and I get the following result - not sure why it doesn't look like your example - but I suspect you may have missed out some information?

![Screenshot 2021-11-15 at 20 48 10](https://user-images.githubusercontent.com/294436/141851701-a56124ae-ec5d-47b7-b13f-21199b7e1100.png)

For now I cannot replicate the issue.

**Comment by andydotxyz** [comment]
It was not possible to replicate this, and given that we have replaced most of the text measurement / layout code it is probably no longer an issue.
