### ISSUE TITLE
Getting empty screen 

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/fyne#2520]
### Describe the bug:

when i am doing the robotogo.MaxWindow(pidfd) 

https://github.com/go-vgo/robotgo/blob/v0.100.0/robotgo.go#L1499
i am using the above function to make the screen maximize after closing the screen made using the fyne by clicking the close button. but when i use the above function to get it back getting blank screen any solution for it,

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to '1.15'

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:** 10
 - **Go version:** 1.15
 - **Fyne version:** 2.0

**Comment by andydotxyz** [comment]
> i am using the above function to make the screen maximize after closing the screen made using the fyne

I don't understand this issues sorry. If you want to full screen a Fyne window use `Window.SetFullScreen(true)`. If you are talking about another window then I'm not sure that this is a Fyne bug...

**Comment by Jacalz** [comment]
Closing due to lack of information. Feel free to reopen with more information if if this still is an issue.
