### ISSUE TITLE
Looking forward to achieving the perfect UI effect like the flutter framework

### ISSUE THREAD

**Issue by qinjinze** [fyne-io/fyne#2523]
Looking forward to achieving the perfect UI effect like the flutter framework，
If the whole framework is used in go language, it is better and easier to understand and maintain

**Comment by andydotxyz** [comment]
Can you please be more specific?
There does not seem to be any actionable bug or feature request in this ticket...

**Comment by MatejMagat305** [comment]
it look like compliment ...........

**Comment by Jacalz** [comment]
Compliments are certainly very helpful and make our effort worthwhile but I don't quite think they fit in on the bug and feature tracker. I would suggest posting compliments on the Slack channel instead :)

**Comment by qinjinze** [comment]
&nbsp;Thank you very much for your reply


&nbsp; &nbsp;The application software that consumers use every day is the software of big companies, such as: facebook, google, microsoft, the software they design is very beautiful, so consumers are used to beautifully designed application software, and I use fyne to try to design something like this software, it is difficult to achieve such an effect


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyne-io/fyne"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月5日(星期二) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Looking forward to achieving the perfect UI effect like the flutter framework (#2523)





 
Can you please be more specific?
 There does not seem to be any actionable bug or feature request in this ticket...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andydotxyz** [comment]
> and I use fyne to try to design something like this software, it is difficult to achieve such an effect

Fyne is split into two main areas of graphical presentation - the `canvas` and `widget` packages. The standard widgets are designed to make great looking standard APIs very fast and easily.
If you want to make your own design then the canvas APIs may be what you need - you can make anything here using a combination of drawing primitives and images.
