### ISSUE TITLE
No Fyne binary

### ISSUE THREAD

**Issue by johnlarfour** [fyne-io/fyne#253]
I use `go get fyne.io/fyne` but in my $GOPATH/bin don't have fyne binary.
I have also tried `go get -u fyne.io/fyne`

**Comment by andydotxyz** [comment]
That command is used to install the toolkit library required to compile your apps. To install the fyne command which is used to assist in packaging and other tasks use:

    go get -u fyne.io/fyne/cmd/fyne

That will install the command to your $GOPATH/bin

**Comment by FObersteiner** [comment]
the up-to-date way is probably `go install fyne.io/fyne/v2/cmd/fyne@latest`

**Comment by EndangeredNayla** [comment]
> the up-to-date way is probably `go install fyne.io/fyne/v2/cmd/fyne@latest`

Still works from 2024
