### ISSUE TITLE
Tree control

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#254]
A tree control displays its items in a tree like structure.
Each item has a label and optional an icon. Item may be either collapsed when children are not visible or expanded when children are visible.

**Comment by okratitan** [comment]
File this in with a data model and list object

**Comment by andydotxyz** [comment]
Placing on 2.0 as 1.3 based data widgets are likely already more than enough to work through.

**Comment by stuartmscott** [comment]
On develop for testing
