### ISSUE TITLE
broken data binding in Entry

### ISSUE THREAD

**Issue by tandem97** [fyne-io/fyne#2542]
### Describe the bug:
Data binding in Entry widget return empty string when entry has onChanged func

### To Reproduce:
run code with comment/uncomment onChanged func

### Example code:
```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()

	mainWindow := app.NewWindow("Hello")
	mainWindow.CenterOnScreen()
	mainWindow.Resize(fyne.NewSize(800, 400))

	dbstring := binding.NewString()

	testentry := widget.NewEntryWithData(dbstring)
	testentry.OnChanged = func(s string) { fmt.Println(s) }

	testbutton := widget.NewButton("test", func() { fmt.Println(dbstring.Get()); fmt.Println(testentry.Text) })

	grid := container.NewVBox(testentry, testbutton)

	mainWindow.SetContent(grid)

	mainWindow.ShowAndRun()
}

```

### Device (please complete the following information):
 - OS: Win10
 - GO: 1.16.6
 - Fyne: 2.1.0

**Comment by Jacalz** [comment]
Looking at the code, the data binding hijacks the OnChanged function to update the value each time it is changed, see https://github.com/fyne-io/fyne/blob/bc52c98e246893551b9dc50011fdd4e298903f3f/widget/entry.go#L163. With that being said however, I think we might need better documentation about this.
