### ISSUE TITLE
Cannot build for windows on linux

### ISSUE THREAD

**Issue by PaulIRL** [fyne-io/fyne#2545]
### Describe the bug:
Cannot package an app for windows from linux

### To Reproduce:
Try to package a fyne app for windows form linux

The terminal shows the following error
` fyne package -os windows`
`# runtime/cgo`
`gcc: error: unrecognized command-line option ‘-mthreads’; did you mean ‘-pthread’?`

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.14
 - **Go version:** 1.17
 - **Fyne version:* 2.1

**Comment by andydotxyz** [comment]
Answered I think, thanks Jacob
