### ISSUE TITLE
Provide changelog for users (developers)

### ISSUE THREAD

**Issue by kravemir** [fyne-io/fyne#256]
This is a promising GUI library for Go (which isn't just wrapped electron, or similar, communicating between GUI and backend via TCP,.. that leads to memory hungry apps).

However, it is still in its early phases feature wise. Providing a changelog allows users to see:

* the effort of developers had put into software from its start (good for new users),
* new available features since last used version,
* upcoming unreleased features.

One good example how to keep a changelog is: https://keepachangelog.com/en/1.0.0/

For example, for me regarding UX related features, it is not yet good enough. As good UX for GUI requires structured styling mentioned in #255.

**Comment by kravemir** [comment]
I see, that changelog is provided via releases: https://github.com/fyne-io/fyne/releases. So, there's something :+1: 

Anyway, it would be nice to have it also as part of sources.

**Comment by andydotxyz** [comment]
I'm not really a fan of duplication but I understand that the release notes may not be the best format. What do you imagine when you say "part of the sources" and how should it differ from the release notes we have currently?

**Comment by andydotxyz** [comment]
Another consideration to add to this thought is: The GitHub wiki and documentation is aimed at contributors and people looking to extend the Fyne toolkit.

General documentation for developers that use Fyne in their application is on our website: https://fyne.io/develop/. I'm not sure which of these target audiences would find the information most useful but it may indicate where we should have such a Changelog?

**Comment by kravemir** [comment]
> What do you imagine when you say "part of the sources" and how should it differ from the release notes we have currently?

By "part of the sources" I mean, that it's present in git repository as `CHANGELOG.md`, or `RELEASE-NOTES.md`, or similar,.. 

GitHub release notes are GitHub specific, and this information is only available on GitHub. The information gets lost on forks, or when project is moved, or backed up using git,..

When release notes (or changelog) is present in sources, then it's also present in distribution native packages (Debian, Fedora,..), git-based backups,.. Basically, release notes are contained within distribution archives.

**Comment by andydotxyz** [comment]
Thanks. As a library that is statically compiled I don't imagine that this will be packaged or distributed in that way. However the thought of thoughts and a living record that is not stored on the hosting provider I get your point, thanks.

**Comment by kravemir** [comment]
> As a library that is statically compiled I don't imagine that this will be packaged or distributed in that way. 

If the library gets adopted by applications, which get packaged to official repositories of Linux distributions, then yes - it will get distributed as release tarballs.

For example, consider debian main repository component:

> The main archive area comprises the Debian distribution. Only the packages in this area are considered part of the distribution. None of the packages in the main archive area require software outside of that area to function. Anyone may use, share, modify and redistribute the packages in this archive area freely [2].
> 
> Every package in main must comply with the DFSG (Debian Free Software Guidelines). [3]
> 
> In addition, the packages in main
> 
>  - **must not require or recommend a package outside of main for compilation or execution** (thus, the package must not declare a Pre-Depends, Depends, Recommends, Build-Depends, Build-Depends-Indep, or Build-Depends-Arch relationship on a non-main package unless that package is only listed as a non-default alternative for a package in main),
>  - must not be so buggy that we refuse to support them, and
>  - must meet all policy requirements presented in this manual.

See:

* https://wiki.debian.org/SourcesList#Component
* https://www.debian.org/doc/debian-policy/ch-archive#s-main

**Comment by andydotxyz** [comment]
Applications using Fyne do not need it to be present on the target system to run. All the libraries and assets are compiled into the resulting binary.
This is common for Go applications.

**Comment by kravemir** [comment]
> All the libraries and assets are compiled into the resulting binary.

Yes, that's true, and it doesn't matter whether fyne is needed as install dependency, or not.

In Debian, build of each (application) package needs to depend only on source tarball and existing packages in Debian. In other words, if you've got installed Debian, and had available only Debian repository with binary and source packages, and no other internet access, then you should be able to build each Debian package. So, also compile-only dependencies must be first packaged, then an application itself can be packaged.

You don't need to worry about packaging.. However, it's good to keep in mind policies of distribution's packaging, when developing library intended to be used by desktop applications, which usually get packaged as official distro's packages in order to make them easily available to users, and get better adopted.
