### ISSUE TITLE
Save (and restore) current window size to storage

### ISSUE THREAD

**Issue by dougwinsby** [fyne-io/fyne#2563]
### Is it possible to construct a solution with the existing API?
No. You can Resize a window, but the current window size if adjusted by the user (viewport?) is not available.

### Describe the solution you'd like to see:
An api to store the window size might get complicated. You'd need to also store a window id ("title"?), and it doesn't make sense to store a "fullScreen" window size.

So it might be best to simply export a function that returns a window's current dimensions as a fyne.Size, Then we could do what we want with that.

**Comment by Jacalz** [comment]
This seems to me like something that preferably should be handled by the window manager, not in the application.
