### ISSUE TITLE
Rich text from markdown can get newlines wrong

### ISSUE THREAD

**Issue by drognisep** [fyne-io/fyne#2589]
### Describe the bug:

I was following the youtube video [here](https://youtu.be/viKut3CsmgA) to make a markdown editor, and I noticed that when adding exclamation points in a header, like in "Hello!!!", the first is put on the next line, while the second and third are added to the header.

### To Reproduce:
Steps to reproduce the behaviour:

Type the text as shown into the editor panel on the left.

### Screenshots:

![image](https://user-images.githubusercontent.com/8890988/138801007-bb6e16ce-840d-4f3c-9668-27ca18f3bc72.png)

### Example code:

This is the code I used to create the HSplit markdown editor. Pretty much exactly what was shown in the video except for window sizing.
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Markdown editor")
	w.Resize(fyne.NewSize(640, 480))

	edit := widget.NewMultiLineEntry()
	rich := widget.NewRichTextFromMarkdown("")
	edit.OnChanged = rich.ParseMarkdown

	w.SetContent(container.NewHSplit(edit, rich))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 21H1, build 19043.1288
 - **Go version:** 1.16 windows/amd64
 - **Fyne version:** (from go.mod) fyne.io/fyne/v2 v2.1.1

**Comment by jfjensen** [comment]
If I run the above example code and type in `**hello**` then no emphasis is added. The emphasis only appears when I add another `*`. I tried looking into this myself but I'm not familiar with the inner workings of the Markdown Renderer.

![Screen Shot 05-13-22 at 10 40 PM](https://user-images.githubusercontent.com/2771076/168386325-8c4503ea-cd09-461f-8d34-eeb8dc97432b.PNG)

**Comment by andydotxyz** [comment]
This issue is closed @jfjensen - please open a new one
