### ISSUE TITLE
Keyboard opens on widget.select on mobile

### ISSUE THREAD

**Issue by Prim69** [fyne-io/fyne#2598]
### Describe the bug:
When opening a widget.select on android (tested on android 11) it opens your keyboard

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a widget.select
2. Open it on android

### Screenshots:

![image](https://user-images.githubusercontent.com/13991048/139518050-f7a0f48b-5d2e-47ea-beb8-7905ad786376.png)

### Device (please complete the following information):
 - **OS:** Android
 - **Version:** 11
 - **Go version:** 1.17.2
 - **Fyne version:** 2.1.1

**Comment by Jacalz** [comment]
This is a good catch. I think this is because of the implemented keyboard control for the focus on desktop.

**Comment by andydotxyz** [comment]
Yes, interestingly I just noticed this yesterday too. We changed the contract for focusable so it did not automatically focus on tap - but that was only done on Desktop driver, needs to be mirrored in the mobile code.

**Comment by Prim69** [comment]
Another thing, the widgets get pushed up when the keyboard is opened

https://user-images.githubusercontent.com/13991048/139558444-2c36ca53-ac0f-4371-bb33-a1fb71465d3b.mp4

**Comment by andydotxyz** [comment]
> Another thing, the widgets get pushed up when the keyboard is opened

This seems to vary based on device, can you please provide more information about your device make/model and Android variant?

**Comment by Prim69** [comment]
> > Another thing, the widgets get pushed up when the keyboard is opened
> 
> This seems to vary based on device, can you please provide more information about your device make/model and Android variant?

Samsung Galaxy M31 (SM-M315F/DSN)

**Comment by Prim69** [comment]
Any chance this'll be merged soon?

**Comment by Jacalz** [comment]
Things take time. Hold on to your hat and it will land when it lands.

**Comment by andydotxyz** [comment]
Fixed on `release/v2.1.x` ready for v2.1.2 release

**Comment by andydotxyz** [comment]
Prepping for release :)
