### ISSUE TITLE
Text wrapping is not working in dialogs

### ISSUE THREAD

**Issue by HashimTheArab** [fyne-io/fyne#2602]
### Is your feature request related to a problem? Please describe:
When adding a label in dialog.CustomShow, if it's too long it'll go off the screen but if its wrapped it'll be a long vertical list
Normal
![image](https://user-images.githubusercontent.com/13991048/139598722-b1e8360c-909d-4104-8737-920c7bb9fca2.png)
That same string wrapped with fyne.TextWrapWord
![image](https://user-images.githubusercontent.com/13991048/139598940-20b93ea4-35b4-4875-8d19-28ee369c12e9.png)

### Describe the solution you'd like to see:
It would be nice to have it wrapped but not be constrained to a narrow vertical list, something like this
![image](https://user-images.githubusercontent.com/13991048/139598850-eb1f3625-f448-442b-85a9-a8e262dc0b57.png)
That image is photoshopped to show what it would look like

**Comment by Jacalz** [comment]
I think this might be considered more of a bug than a feature, so I changed this to a bug instead. Also, I think this is related to https://github.com/fyne-io/fyne/pull/1001 as well.

**Comment by williambrode** [comment]
I'm not sure what `dialog.CustomShow` is that the reporter is referring to.  Doesn't seem to exist in the code base and they didn't include code.

For the broader subject of text wrapping not working - can we just add `dialog.ShowErrorLong` that uses a vertical scroll and TextWrapBreak?  That is what I think most people actually want the behavior to be.

**Comment by andydotxyz** [comment]
> I'm not sure what `dialog.CustomShow` is that the reporter is referring to. Doesn't seem to exist in the code base and they didn't include code.

Probably a typo for `dialog.ShowCustom`

> For the broader subject of text wrapping not working - can we just add `dialog.ShowErrorLong` that uses a vertical scroll and TextWrapBreak?

Simply inserting the scroll would cause it to collapse down, so we need to something extra to determine what a sensible size would be for content that could be scrolled. Either way making this change suffers the same bug that is demonstrated above - as in there is no defined and sensible minimum when you can wrap/scroll.

In summary I think adding scroll does not help the reported problem.

**Comment by williambrode** [comment]
From testing I believe this does what I want:

```go
func ShowErrorLong(msg string, win *fyne.Window) {
	label := widget.NewLabel(msg)
	label.Wrapping = fyne.TextWrapBreak
	scroll := container.NewVScroll(label)
	errDialog := dialog.NewCustom("Error", "OK", container.NewMax(scroll), *win)
	factor := float32(0.40)
	winSize := (*win).Content().Size()
	errDialog.Resize(fyne.NewSize(winSize.Width*factor, winSize.Height*factor))
	errDialog.Show()
}
```

Where factor sets the percentage of the window size to use for the error dialog.  Still would like the

**Comment by andydotxyz** [comment]
Setting a percentage of the window may make sense but why 40%? Won’t this get really tiny on an iPhone? Not sure the same factor applies to height and width as a portrait window will look super weird with this maths.

**Comment by matwachich** [comment]
Why not using a percentage, but just
dlgSize = winSize - dlgShadowSize

so the dialog will have the maximum possible size to cover the entire window and show the gradient border

**Comment by andydotxyz** [comment]
On larger screens this will look very strange.
I don't think there is a "simple" formula - probably some threshold where below it is max and above it is a percent.

**Comment by matwachich** [comment]
What is sure is that a dialog should never be wider/higher than the parent window.

**Comment by williambrode** [comment]
I forgot about this issue but just hit it again trying to use `dialog.NewInformation`.  I imagine this must be a common problem for people right?  Since the only way its not an issue is if the text width is less than the window width - right?  Or perhaps people are inserting newline characters into their text directly?

**Comment by andydotxyz** [comment]
We need to get this resolved - some algorithm to wrap where required - and use "most?" of the screen width instead of just the height...
$250 is currently allocated for eligible contributors completing this work (see [Contributing: Membership](https://github.com/fyne-io/fyne/wiki/Contributing%3A-Membership)).
