### ISSUE TITLE
Entry Background is not aligned when using VBox

### ISSUE THREAD

**Issue by fpabl0** [fyne-io/fyne#2616]
### Describe the bug:

Entry Background is not aligned when placing multiple Entries into a VBox container. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code.

### Screenshots:

<img width="243" alt="Captura de Pantalla 2021-11-04 a la(s) 03 00 38" src="https://user-images.githubusercontent.com/12239342/140278079-24d682d9-a546-4077-baf5-1b8666a9e625.png">

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w.SetContent(container.NewVBox(
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
		widget.NewEntry(),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** MacOS 
 - **Version:** 11.5.1 Big Sur 
 - **Go version:** 1.17.2 
 - **Fyne version:** develop @ 1c0e05f066d

**Comment by andydotxyz** [comment]
Can you check the rendering scale (easiest in fyne_demo -> Advanced)

**Comment by fpabl0** [comment]
Yes, this is:
<img width="515" alt="Captura de Pantalla 2021-11-04 a la(s) 04 22 40" src="https://user-images.githubusercontent.com/12239342/140289028-d2a886bc-7037-489b-8793-07b0e0186700.png">

The bug can be seen inside fyne_demo too:
<img width="204" alt="Captura de Pantalla 2021-11-04 a la(s) 04 22 57" src="https://user-images.githubusercontent.com/12239342/140289089-1f8ae726-2743-4d70-8a8a-a86c35c18556.png">

The problem is in this function:
```go
func fixed266ToFloat32(i fixed.Int26_6) float32 {
	return float32(float64(i) / (1 << 6))
}
```
It should be re-written to:
```go
func fixed266ToFloat32(i fixed.Int26_6) float32 {
	const shift, mask = 6, 1<<6 - 1
	return float32(i>>shift) + float32(i&mask)/100
}
```

However, that means lot of testing files changes 😞

**Comment by fpabl0** [comment]
This is maybe related to #2518

**Comment by fpabl0** [comment]
After some tests, it seems that the solution is to come back to previous precision on `fixed266ToFloat32` function:
```go
func fixed266ToFloat32(i fixed.Int26_6) float32 {
	return float32(i.Ceil())
}
```
Was there a problem with the previous precision (no fractional part at all) that made it need to be updated to handle more decimals?

**Comment by andydotxyz** [comment]
> Was there a problem with the previous precision (no fractional part at all) that made it need to be updated to handle more decimals?

Yes (I don't think we often make changes without reason :-p).
When you use integer precision you cannot address the pixels that are between device-independent positions. So on a 4x devices (such as the high end Android) you then have 3 pixel "jump" between each position. This makes both animations and text layout look very uneven or lacking polish.

**Comment by andydotxyz** [comment]
I tried to replicate in Linux but cannot, it must be down to the texture scale in macOS. We are probably rounding to something that is not sub-DP enough for correct rendering.
i.e. rounding to "whole pixel" but on macOS it should be "whole pixel / texScale"
