### ISSUE TITLE
storage.List doesn't return complete URI on Android for "content:" scheme

### ISSUE THREAD

**Issue by lugu** [fyne-io/fyne#2619]
When trying to list the child of an URI (i.e. the content of the directory) which has the `content:` scheme on Android, the child URI are truncated.

In my case the file picker returns a directory the URI :
> content://com.android.externalstorage.documents/tree/primary:Android/media/Cards

And when listing the file within this directory with `storage.List()`, the children are missing half of their URI like
> primary:Android/media/Cards/test.md

Instead of
> content://com.android.externalstorage.documents/tree/primary:Android/media/Cards/test.md

### Device (please complete the following information):
 - **OS:** Android
 -  **Version:** 10
 - **Go version:**1.16.9
 - **Fyne version:** master, develop

**Comment by andydotxyz** [comment]
Resolved on `develop` and will be merged to release branch before v2.1.2
