### ISSUE TITLE
Can't package android

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2624]
### Describe the bug:
go build -buildmode=c-shared -o /var/folders/f5/dc50fc4n7nb6fg9dz3yv17hm0000gn/T/gomobile-work-136780427/lib/armeabi-v7a/libfyne.so github.com/owner888/fyne failed: exit status 2 github.com/go-gl/glfw/v3.3/glfw
In file included from ../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:188:
./glfw/src/x11_platform.h:33:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>

### To Reproduce:
1. fyne package -os android -appID my.domain.kalifyne

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.0.1 Monterey
 - **Go version:** go1.16.6
 - **Fyne version:** 2.1.1

**Comment by andydotxyz** [comment]
That is not how you package for Android. Use `fyne package -os android`

**Comment by owner888** [comment]
> That is not how you package for Android. Use `fyne package -os android`

$fyne package -os android
Missing appID parameter for package

**Comment by andydotxyz** [comment]
> Missing appID parameter for package

Yes a mobile app requires an appID parameter - I forgot to include it in the example sorry.

**Comment by owner888** [comment]
> > Missing appID parameter for package
> 
> Yes a mobile app requires an appID parameter - I forgot to include it in the example sorry. Consider reading https://developer.fyne.io/started/packaging-mobile for more information

Thanks bro, but isn't fix it...


fyne package -os android -appID com.example.myapp -icon Icon.png 
go build -buildmode=c-shared -o /var/folders/f5/dc50fc4n7nb6fg9dz3yv17hm0000gn/T/gomobile-work-392591585/lib/armeabi-v7a/libfyne.so github.com/owner888/fyne failed: exit status 2
# fyne.io/fyne/v2/internal/driver/mobile
android.c:50:9: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
android.c:67:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:71:55: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:122:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:125:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:181:50: warning: passing 'char *' to parameter of type 'jbyte *' (aka 'signed char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
android.c:191:48: warning: passing 'char *' to parameter of type 'const jbyte *' (aka 'const signed char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
# fyne.io/fyne/v2/app
app_mobile_and.c:46:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:49:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:85:30: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:98:33: warning: incompatible pointer to integer conversion passing 'JNIEnv *' (aka 'const struct JNINativeInterface **') to parameter of type 'uintptr_t' (aka 'unsigned int') [-Wint-conversion]
app_mobile_and.c:42:36: note: passing argument to parameter 'jni_env' here
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:188:
./glfw/src/x11_platform.h:33:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.

**Comment by andydotxyz** [comment]
Please try cleaning your project cache. It should not be trying to include GLFW or X11 for a mobile build.

**Comment by owner888** [comment]
> Please try cleaning your project cache. It should not be trying to include GLFW or X11 for a mobile build.

Got it and fix, but have other prob:

fyne package -os android -appID com.example.myapp -icon Icon.png                            
/Users/kaka/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-nm /var/folders/f5/dc50fc4n7nb6fg9dz3yv17hm0000gn/T/gomobile-work-609922778/lib/armeabi-v7a/libfyne.so: fork/exec /Users/kaka/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-nm: no such file or directory

**Comment by owner888** [comment]
> Please try cleaning your project cache. It should not be trying to include GLFW or X11 for a mobile build.

Fix it，thanks bro
