### ISSUE TITLE
Build failure on -tags mobile when updating to Fedora 35

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2625]
### Describe the bug:
I recently updated to Fedora 35 and it seems that I no longer can run the mobile simulator using `-tags mobile`. I am now getting the following error:
```go
# fyne.io/fyne/v2/internal/driver/mobile/app
x11.c: In function ‘new_window’:
x11.c:40:9: error: unknown type name ‘XVisualInfo’; did you mean ‘VisualID’?
   40 |         XVisualInfo visTemplate;
      |         ^~~~~~~~~~~
      |         VisualID
x11.c:41:20: error: request for member ‘visualid’ in something not a structure or union
   41 |         visTemplate.visualid = vid;
      |                    ^
x11.c:43:9: error: unknown type name ‘XVisualInfo’; did you mean ‘VisualID’?
   43 |         XVisualInfo *visInfo = XGetVisualInfo(x_dpy, VisualIDMask, &visTemplate, &num_visuals);
      |         ^~~~~~~~~~~
      |         VisualID
x11.c:43:32: warning: implicit declaration of function ‘XGetVisualInfo’ [-Wimplicit-function-declaration]
   43 |         XVisualInfo *visInfo = XGetVisualInfo(x_dpy, VisualIDMask, &visTemplate, &num_visuals);
      |                                ^~~~~~~~~~~~~~
x11.c:43:54: error: ‘VisualIDMask’ undeclared (first use in this function); did you mean ‘VisualID’?
   43 |         XVisualInfo *visInfo = XGetVisualInfo(x_dpy, VisualIDMask, &visTemplate, &num_visuals);
      |                                                      ^~~~~~~~~~~~
      |                                                      VisualID
x11.c:43:54: note: each undeclared identifier is reported only once for each function it appears in
x11.c:52:61: error: request for member ‘visual’ in something not a structure or union
   52 |         attr.colormap = XCreateColormap(x_dpy, root, visInfo->visual, AllocNone);
      |                                                             ^~
x11.c:61:52: error: request for member ‘depth’ in something not a structure or union
   61 |                 x_dpy, root, 0, 0, w, h, 0, visInfo->depth, InputOutput,
      |                                                    ^~
x11.c:62:24: error: request for member ‘visual’ in something not a structure or union
   62 |                 visInfo->visual, CWColormap | CWEventMask, &attr);
      |                        ^~
x11.c:65:9: error: unknown type name ‘XSizeHints’
   65 |         XSizeHints sizehints;
      |         ^~~~~~~~~~
x11.c:66:18: error: request for member ‘width’ in something not a structure or union
   66 |         sizehints.width  = w;
      |                  ^
x11.c:67:18: error: request for member ‘height’ in something not a structure or union
   67 |         sizehints.height = h;
      |                  ^
x11.c:68:18: error: request for member ‘flags’ in something not a structure or union
   68 |         sizehints.flags = USSize;
      |                  ^
x11.c:68:27: error: ‘USSize’ undeclared (first use in this function)
   68 |         sizehints.flags = USSize;
      |                           ^~~~~~
x11.c:69:9: warning: implicit declaration of function ‘XSetNormalHints’ [-Wimplicit-function-declaration]
   69 |         XSetNormalHints(x_dpy, win, &sizehints);
      |         ^~~~~~~~~~~~~~~
x11.c:70:9: warning: implicit declaration of function ‘XSetStandardProperties’ [-Wimplicit-function-declaration]
   70 |         XSetStandardProperties(x_dpy, win, "App", "App", None, (char **)NULL, 0, &sizehints);
      |         ^~~~~~~~~~~~~~~~~~~~~~

```

### To Reproduce:
Steps to reproduce the behaviour:
1. Compile `cmd/hello` using `-tags mobile`.

### Example code:

Compile any Fyne app, for example `cmd/hello` or `cmd/fyne_demo`.

### Device (please complete the following information):
 - **OS:**  Fedora Linux 35
 - **Version:**  5.14.15
 - **Go version:**  1.16.8
 - **Fyne version:**  2.1.1 and on 2.1.x branch.

**Comment by Jacalz** [comment]
It's weird. The `libx11` version (not the xorg server, just the libraries) has not changed between Fedora 34 and 35.
https://src.fedoraproject.org/rpms/libX11

**Comment by andydotxyz** [comment]
Yes this is most strange. The structure is defined as part of libx11...
Perhaps the path changed and our setup cannot find it any more? Does pkgconfig find x11?

**Comment by Jacalz** [comment]
I honestly have no idea. I think pkgconfig manages to find it at least:
```
[jacob@fedora hello]$ pkgconf --path x11
/usr/lib64/pkgconfig/x11.pc
```
It is so strange. I tried to mess with the linker flags in the corresponding `.go` file but with no luck. Will update my desktop workstation in a week or two hopefully and might see then if I run into the same issue there.

**Comment by andydotxyz** [comment]
Any update on this? Would be great to resolve or mark as not an issue ;)

**Comment by Jacalz** [comment]
Unfortunately not. With a fully updated Fedora 35 install on my laptop, this is still occurring. I am planning on upgrading my workstation to Fedora 35 in a week or two when I have finished a project that I am working on for a company (in case anything breaks). Will report back as soon as I have tested on that machine as well :)

**Comment by Jacalz** [comment]
Looks like I indeed am getting the exact same error on my workstation :(

**Comment by andydotxyz** [comment]
Does anything on your system provide `XUtil.h`?

**Comment by Jacalz** [comment]
I suppose not. Running the following commands does not find anything.
```
[jacob@dhcp-10-253-214-54 ~]$ rpm -q --whatprovides 'XUtil.h'
no package provides XUtil.h
[jacob@dhcp-10-253-214-54 ~]$ dnf whatprovides 'XUtil.h'
Error: No Matches found
```

**Comment by Jacalz** [comment]
I could be running the commands wrong but I thought at least one of them would search the entire package catalog, not just locally. I have no idea which package would be needed to installed to get it.

**Comment by rathann** [comment]
I'm pretty sure you don't have `libX11-devel` installed if compilation cannot find `Xutil.h`.

**Comment by Jacalz** [comment]
> 

Thanks, but it is already installed unfortunatelly.
```
[jacob@dhcp-10-253-214-54 ~]$ sudo dnf install libX11-devel
[sudo] password for jacob: 
Last metadata expiration check: 3:21:23 ago on Fri 03 Dec 2021 09:16:47 CET.
Package libX11-devel-1.7.2-3.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by andydotxyz** [comment]
The reddit folk seemed to think it should have been provided there as well - were you able to see what the results were with lower case 'u'?
`rpm -q --whatprovides 'Xutil.h'`

**Comment by Jacalz** [comment]
No luck there :(
```
[jacob@dhcp-10-253-214-54 ~]$ rpm -q --whatprovides 'Xutil.h'
no package provides Xutil.h
```

**Comment by andydotxyz** [comment]
I just did a fresh install of Fedora 35 and followed the install steps on the developer.fyne.io docs.
Then searching for `Xutil.h` I find: `/usr/include/X11/Xutil.h`.
Sounds like something may have broken in your upgrades?

**Comment by andydotxyz** [comment]
Oh, and:

```
$ rpm -q --whatprovides '/usr/include/X11/Xutil.h'
libX11-devel-1.7.2-3.fc35.x86_64
```

**Comment by Jacalz** [comment]
It sounds then as if something broke during the update. Running the same command has the same output on my side as well though, which I find strange.
```
[jacob@fedora ~]$ rpm -q --whatprovides '/usr/include/X11/Xutil.h'
libX11-devel-1.7.2-3.fc35.x86_64
```

**Comment by andydotxyz** [comment]
Can you reinstall the package and see if the file reappears?

**Comment by Jacalz** [comment]
The file is there, just as it should. It is just somehow not getting picked up. I find that very strange. Shouldn't the same file/files be used by the `glfw` package as well? Seems strange the our mobile build would fail but not the desktop driver.

**Comment by andydotxyz** [comment]
What file system (and with what options) are you using on the partition that hosts the header file?

**Comment by Jacalz** [comment]
It should not be anything out of the ordinary. It is, as this is a Fedora 34 install from the start, a Btrfs file system with transparent file system  compression using Zstd. 
![image](https://user-images.githubusercontent.com/25466657/145236406-10dab05e-3b32-4202-964b-ac9d98ca0033.png)

What do you get in your Fedora 35 VM if you check out the pkgconf file?
```
cat $(pkg-config --path x11)
```
The above command gets me this:
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

xthreadlib=-lpthread

Name: X11
Description: X Library
Version: 1.7.2
Requires: xproto kbproto
Requires.private: xcb >= 1.11.1
Cflags: -I${includedir} 
Libs: -L${libdir} -lX11
Libs.private: -lpthread
```

I am asking this because I tried loading X11 using pkg-config now again and I get the same error using that method as well.

**Comment by Jacalz** [comment]
I did a reinstall of all packages using the following command. It unfortunatelly made no difference.
```
sudo dnf reinstall gcc libXcursor-devel libXrandr-devel mesa-libGL-devel libXi-devel libXinerama-devel libXxf86vm-devel
```

**Comment by andydotxyz** [comment]
> What do you get in your Fedora 35 VM if you check out the pkgconf file?

Exactly the same

**Comment by andydotxyz** [comment]
What happens if you add
```
#include <X11/Xutil.h>
```
to `./internal/driver/mobile/app/x11.c`

**Comment by Jacalz** [comment]
@andydotxyz You are a genius! That works perfectly :)
