### ISSUE TITLE
Tree widget is randomizing tree display data

### ISSUE THREAD

**Issue by drognisep** [fyne-io/fyne#2628]
### Describe the bug:

I'm trying to create a custom tree view over an existing data model using a model adapter. This means there are a few working components used to satisfy the `widget.Tree` way of doing things and to adapt it to the existing model. I can verify that the model is in an expected state because the app can print the model state, but the reported state of the `widget.Label`s is not what is shown, and appear to show random values that exist in the model.

See this playground link:
https://play.golang.org/p/fm63Fy0G92O

I really hope I'm just doing something silly, but I've been beating my head against this all day to no avail. I've tried 3 different ways of initializing the tree widget:
1. Using `widget.NewTree(...)` and extending it with `TreeModel`.
  * This one was weird because the performance was not good and it seemed like refreshing the widget didn't work all the time.
2. Using `&widget.Tree{}` by assigning functions and extending it with `TreeModel`.
  * This worked best and exhibits the described bug behavior, but I'm assuming this isn't the expected approach, even if it's what `widget.NewTree` does.
3. Creating the `widget.Tree` and NOT extending it with the `TreeModel`. Just using a getter to get the widget.
  * This exhibited the same behavior as approach 2 but it was a bit clunky to use.

### To Reproduce:
Steps to reproduce the behaviour:
1. Download the code from https://play.golang.org/p/fm63Fy0G92O
2. Run the file and reduce the size of the window obscuring some of the tree nodes
3. Expand the window size again and note that the data changes to a different node's data or even duplicating data. This doesn't happen *every* time, but reducing and expanding a few times (<10) will reliably reproduce the bug.
4. Double-click on any tree node to verify the state of the model and node. Note that the reported label text is not what is shown, but *it is what it should be* according to the model data.

### Screenshots:

![image](https://user-images.githubusercontent.com/8890988/140679827-0129b4e8-28bb-43f9-accd-336efebdf534.png)
![image](https://user-images.githubusercontent.com/8890988/140679846-e0d3828e-c2d8-4a0d-bfc7-4f3c40b36f4a.png)

### Example code:
See this playground link.
https://play.golang.org/p/fm63Fy0G92O

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 21H1 19043.1288
 - **Go version:** go version go1.16 windows/amd64
 - **Fyne version:** fyne.io/fyne/v2 v2.1.1

**Comment by drognisep** [comment]
**Copied from Slack**

@andydotxyz 

> @drognisep that is a lot of code, not really a minimal example. Clearly Tree does not normally randomise data so can you help us narrow down what is the key difference in your code?

@drognisep 

> Agreed, here are the different components:
> * `Data` is a hierarchical piece of information related to the business logic of the application. It's expected to be mutated by interactions with the tree.
> * `TreeModel` adapts a hierarchy of `Data` to a structure easy to use by a `widget.Tree`.
>     * It is expected to handle all mutations triggered by interactions with the `treeNode` or externally to the widget.
> * `treeNode` extends `widget.Label` and maintains a reference to a model ID (`widget.TreeNodeID`) and the `TreeModel`, and uses these to get/change the model state of the `Data`.
>     * The `TreeModel`'s `prototype` function will create a blank `treeNode` and `update` will provide the ID and `Data` so it can set the `widget.Label`'s text.
>     * This is designed to be a dumb view component that forwards interaction events to `TreeModel`.
> 
> The problem is that setting the `widget.Label` in `update` does actually change the `widget.Label.Text` field, but that isn't represented in the visible state of the tree. I noticed that resizing the window will result in `update` calls, so I started with that to test the data flow. If you run what's there and double-click on any node in the tree it will show the state that's expected - including the label and model state - but it just plain won't always/consistently reflect that.

**Result of testing with `release/v2.1.x` branch**
Same results, here's what's shown.
![image](https://user-images.githubusercontent.com/8890988/140707429-49aef521-b2f3-4cba-8469-63faa6e65b1c.png)

**Debug info printed by double-clicking the first node**
![image (1)](https://user-images.githubusercontent.com/8890988/140707542-ea5639d0-9702-44c5-806e-06c23b52c801.png)

**Verifying ordering in `Data`**
![image (2)](https://user-images.githubusercontent.com/8890988/140707636-aeaf19fa-58ad-466b-9970-ecbd74b9ac23.png)

**Verifying ordering in child map**
![image (3)](https://user-images.githubusercontent.com/8890988/140707716-82b5b31a-205c-4b23-8b82-e40fd70c740f.png)

**Comment by Jacalz** [comment]
It would really be good with a small code example, as @andydotxyz said. Per the bug issue template:
"Please refrain from adding screenshots of code, links to other projects or very long code examples."

**Comment by drognisep** [comment]
Checked `widget.Label.SetText` results in the tree update context and all seems good there. In all cases when a Label is set the Text field is too.

**Comment by drognisep** [comment]
> It would really be good with a small code example, as @andydotxyz said. Per the bug issue template: `"Please refrain from adding screenshots of code, links to other projects or very long code examples."`

@Jacalz 
I totally agree with the sentiment. I'll try to trim it down to see if removing something fixes the problem, but I also feel that this is a legit usage pattern for a custom tree - which happens to be verbose. It accomplishes a few core things.
* My business-logic-based data model (`Data`) can be a tree model (through `TreeModel` in this case, which handles adapting calls).
* I can interact with tree nodes with clicks for context menus or whatever (thus the need for `treeNode`).
* The structure of the tree can be dynamic, so I can add new nodes (through `TreeModel` and delegating event handlers from `treeNode`s).

Do you know of a more succinct way to accomplish those things? I'm not being cheeky, I'd love to trim this down and get the same functionality.

**Comment by drognisep** [comment]
@Jacalz @andydotxyz 
In trying to simplify I noticed that removing the tree node (and the ability to handle events) made the problem disappear. I'm using `release/2.1.x` code, so it should include the Label bug fix. This raises a few questions:
* Am I doing something wrong extending `widget.Label`? I need that to handle click events.
* Is there a better pattern to implement a mutable custom tree adapted to an existing model?

Here's the [new code](https://play.golang.org/p/nsaxwDDTeVU) and the diff:
```diff
diff --git a/cmd/customtree/main.go b/cmd/customtree/main.go
index 269796f..f797aee 100644
--- a/cmd/customtree/main.go
+++ b/cmd/customtree/main.go
@@ -23,46 +23,6 @@ type Data struct {
 type idDataMap = map[widget.TreeNodeID]*Data
 type idChildMap = map[widget.TreeNodeID][]widget.TreeNodeID
 
-var _ fyne.DoubleTappable = (*treeNode)(nil)
-
-// treeNode is the widget displayed within the model. Its sole job is to lookup its state from the model and update the widget.Label.
-type treeNode struct {
-	*widget.Label
-
-	mux   sync.Mutex
-	ID    widget.TreeNodeID
-	model *TreeModel
-}
-
-func newTreeNode(id widget.TreeNodeID, model *TreeModel) *treeNode {
-	lbl := widget.NewLabel("")
-	node := &treeNode{
-		Label: lbl,
-		ID:    id,
-		model: model,
-	}
-	node.ExtendBaseWidget(node)
-	return node
-}
-
-func (n *treeNode) update(id widget.TreeNodeID, _ bool, val *Data) {
-	n.mux.Lock()
-	defer n.mux.Unlock()
-	n.ID = id
-	n.Label.SetText(val.Data)
-	n.Label.Refresh()
-}
-
-// Debugging handler to print the node and model state.
-func (n *treeNode) DoubleTapped(_ *fyne.PointEvent) {
-	n.PrintState()
-	n.model.PrintState()
-}
-
-func (n *treeNode) PrintState() {
-	log.Printf("Node state: ID='%s', LabelText='%s'\n", n.ID, n.Text)
-}
-
 // TreeModel maintains the registry of nodes within the model and allows for state mutations.
 type TreeModel struct {
 	*widget.Tree
@@ -140,15 +100,15 @@ func (t *TreeModel) isBranch(id widget.TreeNodeID) bool {
 }
 
 func (t *TreeModel) prototype(_ bool) fyne.CanvasObject {
-	return newTreeNode("", t)
+	return widget.NewLabel("")
 }
 
 func (t *TreeModel) update(id widget.TreeNodeID, isBranch bool, cachedProto fyne.CanvasObject) {
 	t.mux.Lock()
 	defer t.mux.Unlock()
-	node := cachedProto.(*treeNode)
+	node := cachedProto.(*widget.Label)
 	spec := t.idMap[id]
-	node.update(id, isBranch, spec)
+	node.SetText(spec.Data)
 }
 
 func (t *TreeModel) init(base *Data) {

```

**Comment by drognisep** [comment]
Interesting! It looks like it's the extension happening in `widget.NewLabelWithStyle` that's causing the problem!

I copied in the `widget.Label` creation from `widget.NewLabelWithData` with the constants from `widget.NewLabel` - *without* the extension call - and it's working fine! :D

**Comment by drognisep** [comment]
I'm not sure about what's happening beyond the point of `ExtendBaseWidget`, but at least that's a starting point for debugging.

On a related note, to get the tree extension working I *also* had to create the struct directly instead of using `widget.NewTree`. Is that expected, or should `widget.NewTree` work also?

**Comment by drognisep** [comment]
This ended up being a documentation issue. The result of widget constructors may not be used as the basis for extension.

See:
https://github.com/fyne-io/developer.fyne.io/pull/56
