### ISSUE TITLE
Fyne app on Windows VM displays blank window

### ISSUE THREAD

**Issue by wiseworld** [fyne-io/fyne#2633]
Hi, I have two Windows 10 virtual machines on ESXi and my simple application using fyne displays okay on one but is blank on the other (shows window with title bar ok, but contents blank even if resized). I built it using fyne-cross on the Windows machine it does not display on. The one it works on has a slightly older driver, and ESXi video options are the same on both machines. Any idea what the difference might be and why its not working. Sounds like a bug in that the app isn't complaining the environment is wrong, but not sure what info you might need to track it down. Thanks!

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

Do you have GPU acceleration enabled for the VMs? I know there are many issues with drivers within virtual machines running Windows.

**Comment by wiseworld** [comment]
OK, sorry, new to this one.

### Describe the bug:
I have two Windows 10 virtual machines on ESXi and my simple application using fyne displays okay on one but is blank on the other - the app shows the window with the title bar ok, but contents are blank. If resized, the original white background is padded with black. 

### To Reproduce:
Build the sample using fyne-cross on the Windows machine that it does not display on. Copy the exe to other machine and it displays ok.

### Example code:
package main
import (
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"
)

func main() {
    a := app.New()
    w := a.NewWindow("Hello")
    hello := widget.NewLabel("Hello World!")
    w.SetContent(container.NewVBox(
        hello,
    ))
    w.ShowAndRun()
}

### Device (please complete the following information):
Details of VM that fails to display the window...
 - Windows 10 Pro
 - 20h2
 - Go version: 1.17.1
 - Fyne version: 2.1.0

Working o/s was 21h1, so have since updated non-working machine to 21h1 and still doesn't work (should've spotted this difference before!).

The VMWare console for the two machines is identical. I've tried with "Enable 3D Support" on and off, it makes no difference. I also checked the Windows Device Manager and both machines are using the VMware SVGA3D 8.17.2.14 driver. 
I tried downloading and running the DirectX tool to find out what OpenGL is supported, as per some blog piece, but the tool I found doesn't look the same and told me nothing.

**Comment by andydotxyz** [comment]
Is there any information in the console when you launch from the command line?

**Comment by wiseworld** [comment]
When launched from a CMD shell, the window pops up and you get back to the prompt in the shell without any other output there.

**Comment by andydotxyz** [comment]
Do you mean after closing the window you see no output - or that the window appears and disappears without any interaction, returning you to the shell?

**Comment by wiseworld** [comment]
Open the shell. Type name of exe file, hit return. Fyne app window appears. Look behind it, command shell app has 'exited' with no output and you're back to the command prompt. Checking with ProcMon, the EXE is launched by CMD and it then detaches from the shell and continues running.
This is the same as happens on the working VM.

**Comment by Jacalz** [comment]
Have you built the binaries with or without the linker flags that doesn't open it in the terminal (`-H windowsgui` I think it is)?

**Comment by andydotxyz** [comment]
Actually more useful would be to get the output if you use `go run .` because that will avoid any windows complications.
If the app "detaches" as you describe then the logs will be in a system console or log file somewhere that can be hard to track down.

**Comment by wiseworld** [comment]
OK, as it happens the app doesn't work on the VM being used to compile it (using fyne-cross). So using VSCode, in the terminal window, typing "go run main.go" the same thing happens - GUI window appears blank white, no output in the terminal window, but it doesn't return to a prompt. No other output in the Problems, Output or Debug tabs.

**Comment by Jacalz** [comment]
Fyne-cross builds with the linking tag mentioned above, by default. That is why you are not seeing any prompt. If you have to build using Fyne-cross please try to add the -console flag.

**Comment by wiseworld** [comment]
Using VSCode on Windows here, so FYNE_THEME=dark go run . just gives an error. What's the windows equivalent? Tried shoving the theme on the end instead and it run but made no difference.
Cross compiling with -console then running the EXE from a CMD still doesn't work and produces no console output, but the app no longer detaches from the shell. 
Didn't explicitly build any binaries, but I take it that -console with fyne-cross is the same thing.

**Comment by andydotxyz** [comment]
Sadly windows environment syntax varies based on the command line shell. For CMD I think it is:
```
set FYNE_THEME "dark"
go run .
```

**Comment by wiseworld** [comment]
Had a bit of a breakthrough. Discovered a difference between the working and non-working machines. Didn't have VMWare Tools installed on the non-working one, installed them and it starts working.

**Comment by Jacalz** [comment]
That's great information. Great to hear that you solved it.

**Comment by wiseworld** [comment]
Great support, thanks folks.

**Comment by shadow1163** [comment]
I also met this issue when using Remote Desktop. Switch to ESXi VM Console, it's work.
