### ISSUE TITLE
New Widget not responding to mouse interactions (Tappable)

### ISSUE THREAD

**Issue by stuartdd** [fyne-io/fyne#2638]
### Describe the bug:
I have written a new Widget that contains a circle (mentioned in #2632). It looks correct visually so I implemented the Tappable interface, however no amount of tapping invokes the Tapped(*fyne.PointEvent) function. 

I have also added TappedSecondary and DoubleTapped. (I read on one blog that you needed Tapped and TappedSecondary to get this to work so I added all three) None of these respond to mouse tapping.

I also included the Disableable interface with Disabled() bool { return false } just in case taps were only passed to Enabled wigets. This has no effect on the issue.

I have tried many, many things, including not passing the circle. I thought the circle might be picking up the mouse interactions but again no result. 

Can someone please tell me what I am doing wrong or if this is a bug?

Regards

Stuart
### To Reproduce:
1. Implement a widget with a renderer. 
2. Add the Tappable interface with println statements in the Tapped function 
3. Run the test and tap the widget
4. Check the console for messages

### Screenshots:

![Screenshot from 2021-11-11 15-50-20](https://user-images.githubusercontent.com/20523458/141327762-2d65134d-0218-4547-a5a5-15731cd80b35.png)

### Example code:
```go
package main

import (
	"fmt"
	"image/color"
	"math/rand"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
)

var _ fyne.WidgetRenderer = (*MyWidgetRenderer)(nil)

type MyWidgetRenderer struct {
	dataSource *MyWidget
}

func (r *MyWidgetRenderer) Layout(s fyne.Size) {
}

func (r *MyWidgetRenderer) MinSize() fyne.Size {
	return r.dataSource.MinSize()
}

func (r *MyWidgetRenderer) Refresh() {
}

func (r *MyWidgetRenderer) Objects() []fyne.CanvasObject {
	o := make([]fyne.CanvasObject, 0)
	o = append(o, r.dataSource.circ1)
	return o
}

func (r *MyWidgetRenderer) Destroy() {
}

func NewMyWidgetRenderer(ds *MyWidget) *MyWidgetRenderer {
	return &MyWidgetRenderer{dataSource: ds}
}

// Test interfaces!
var _ fyne.CanvasObject = (*MyWidget)(nil)
var _ fyne.Widget = (*MyWidget)(nil)
var _ fyne.Tappable = (*MyWidget)(nil)
var _ fyne.SecondaryTappable = (*MyWidget)(nil)
var _ fyne.DoubleTappable = (*MyWidget)(nil)
var _ fyne.Disableable = (*MyWidget)(nil)

type MyWidget struct {
	widget.BaseWidget
	circ1 *canvas.Circle
}

// Adding Disableable Does not solve the issue
func (mc *MyWidget) Enable()        {}
func (mc *MyWidget) Disable()       {}
func (mc *MyWidget) Disabled() bool { return false }

func NewMyWidget() *MyWidget {
	fmt.Println("NewMyWidget")
	w := &MyWidget{circ1: &canvas.Circle{
		StrokeWidth: rand.Float32() * 8,
		StrokeColor: color.White,
		FillColor:   color.Transparent,
	}}
	w.ExtendBaseWidget(w)
	return w
}

// Does not respond to DoubleTapped, TappedSecondary or Tapped
func (mc *MyWidget) DoubleTapped(*fyne.PointEvent) {
	fmt.Println("***** MyWidget:DoubleTapped")
}
func (mc *MyWidget) TappedSecondary(*fyne.PointEvent) {
	fmt.Println("***** MyWidget:TappedSecondary")
}
func (w *MyWidget) Tapped(*fyne.PointEvent) {
	fmt.Println("***** MyWidget:Tapped")
}

func (w *MyWidget) CreateRenderer() fyne.WidgetRenderer {
	w.ExtendBaseWidget(w)
	return NewMyWidgetRenderer(w)
}

func (w *MyWidget) MinSize() fyne.Size {
	return fyne.NewSize(100, 100)
}

func (w *MyWidget) Resize(s fyne.Size) {
	w.circ1.Resize(s)
}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Hello")
	myWindow.SetContent(NewMyWidget())
	myWindow.ShowAndRun()
}
```
Device (please complete the following information):

    OS: Linux Mint 20.2 Cinnamon
    Version: Linux 5.11.0-38-generic
    Go version: (From go.mod) go 1.17
    Fyne version: (From go.mod require) fyne.io/fyne/v2 v2.1.2-0.20211031145856-de7b91f69111

**Comment by andydotxyz** [comment]
Ah I see now, you have a custom `Resize` method which overrides the `BaseWidget.Resize`.
If you want to keep it like this then the method will need to have the following line added:
```go
	w.BaseWidget.Resize(s)
```

However as you are using it to resize the graphical elements your code would be better moved to the `WidgetRenderer.Layout`. Either would fix your issue.
