### ISSUE TITLE
window size does not grow if content's minSize gets bigger (aka “The minSize bug”)

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#264]
If the minSize of the content of a window gets bigger than the window, the window does not grow.
Also it is possible to reducde the window's size to its former minSize after enlarging it manually.

**Comment by toaster** [comment]
Until we have a signalling mechanism for signalling minSize changes from the changed widgets to the containers, we need some kind of update method for the window.

I propose `Refresh()`.

Any objections?

**Comment by andydotxyz** [comment]
Sorry I’m not quite sure I understand - how does window.Refresh fix the bug? 

Signalling as you say could be one way, another could be to always query MinSize and then re-layout if it changes, but this is slow and so would probably require caching the MinSize in each widget (and canvasobject) perhaps this is part of the BaseWidget discussion as well? https://github.com/fyne-io/fyne/wiki/Simplify-widget-creation

**Comment by toaster** [comment]
> … how does window.Refresh fix the bug?

If I change the content, I can notify the window via `window.Refresh()`.
Of course I prefer a signalling solution over another method in the `Window` interface.

> … another could be to always query MinSize and then re-layout if it changes

When is “always”? Is this polling? Polling is a sure way to doom.

Regarding caching of `MinSize`: I vote for it. I think ATM there are a lot of computations done unnecessarily again and again.

**Comment by toaster** [comment]
After a long discussion of the signal handling topic we decided to go for the easiest solution for now:

Extending the existing refresh mechanism by MinSize growth detection and triggering a refresh up the object tree within the driver functions.

**Comment by andydotxyz** [comment]
Now on develop for testing
