### ISSUE TITLE
SelectEntry Does Not Truncate Correctly for Very Large Strings

### ISSUE THREAD

**Issue by mathaou** [fyne-io/fyne#2641]
### Describe the bug:

I had a Selected Entry in the center of a borderpane, inside of a VBox. It contained a string array that had very large strings, and it expanded the window to an unacceptable width.

### To Reproduce:
Steps to reproduce the behaviour:

Create a sample app with a border. The center widget should contain a VBOX and a selectEntry
The select entry should have very large strings in it

### Device (please complete the following information):
 - **OS:** 
 - **Version:** 
 - **Go version:** 
 - **Fyne version:**

**Comment by Jacalz** [comment]
Please fill out the entire issue template when opening issues.

**Comment by andydotxyz** [comment]
Fixed on `release/v2.1.x` branch ready for 2.1.2
