### ISSUE TITLE
M1 Macbook Can't Packaging for Windows and Linux Desktop

### ISSUE THREAD

**Issue by owner888** [fyne-io/fyne#2644]
### Describe the bug:

M1 Macbook Can't Packaging for Windows and Linux Desktop

### Screenshots:

![2021-11-15 at 7 29 PM](https://user-images.githubusercontent.com/4317332/141782422-d5b06018-77f9-4342-adef-3ffda763a869.png)

### Example code:

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Hello")
	myWindow.SetContent(widget.NewLabel("Hello"))

	myWindow.Show()
	myApp.Run()
	tidyUp()
}
func tidyUp() {
	fmt.Println("Exited")
}
```

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.0.1  Monterey
 - **Go version:** go1.17.2 darwin/arm64
 - **Fyne version:** 2.1.1

**Comment by changkun** [comment]
I think you may have to use https://github.com/fyne-io/fyne-cross

**Comment by Jacalz** [comment]
I suggest that you read https://developer.fyne.io/started/cross-compiling. You can’t just cross compile normally with CGo like you do without.
