### ISSUE TITLE
widget.Entry shrinks in size

### ISSUE THREAD

**Issue by shofster** [fyne-io/fyne#2649]
a widget.Entry that begins as the width of its placeholder shrinks down in size when the placeholder is replaced with new characters. To me, there doesn't seem to be a reason for allowing the min size to be less than the placeholder length (regardless of word wrap / scrolling). Makes for a jumpy visual experience.

func main() {
	a := app.New()
	w := a.NewWindow("entry")
	e := widget.NewEntry()
	e.PlaceHolder = "Place Holder # 1"
	e.SetText(e.PlaceHolder)
	f := widget.NewEntry()
	f.PlaceHolder = "Place Holder # 2"
	f.SetText(f.PlaceHolder)
	e.Wrapping = fyne.TextWrapOff
	f.Wrapping = fyne.TextWrapOff
	ef := container.NewHBox(e, f)
	w.SetContent(container.NewVBox(ef))
	w.Resize(fyne.NewSize(200, 200))
	w.ShowAndRun()
}

Using a grid layout makes it bearable, but not letting min size be less than theme.characterwidth * len(placeholder) + padding would work in situations where grid or border layouts are cumbersome / complex / unworkable / ugly.

**Comment by andydotxyz** [comment]
You are using `container.NewVBox` which instructs the Entry to be as small as it can.
You should use a layout that instead allows the widget to be large enough for your usage and it will no longer change size based on content.
https://developer.fyne.io/started/layouts

p.s. `e.SetText(e.PlaceHolder)` is a strange thing to do.
