### ISSUE TITLE
initial scaling wrong on external MacOS displays

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#265]
When starting a fyne app on an external MacOS display (with another resolution than the internal one) the window is not scaled correctly until the first move of the window.

Side effect: on the first move the window gets rescaled and the effects of #264 are fixed (until the next minSize change).

**Comment by toaster** [comment]
This does not happen for fyne_demo's main window. But it still happens for its subwindows

**Comment by andydotxyz** [comment]
I cannot replicate this on my Mac Pro tower with external displays. What is the setup that you are using? I have a laptop around that I will try out as well, when I can find the right adapters ;)

**Comment by toaster** [comment]
- MBP 13" TouchBar late 2016
- MacOS 10.12 (Sierra)
- OWC Thunberbolt 3 Dock
- DELL 2408WFP connected to the dock via DisplayPort

**Comment by andydotxyz** [comment]
It is possible that this is a Sierra related issue, I do not have such an OS installation. Is anyone else able to replicate this issue?

**Comment by toaster** [comment]
I can test later with another Sierra installation on a MBP 2013 and with a HighSierra installation on a MBP 2010.

**Comment by toaster** [comment]
My old laptops are passed down the line :).

**Comment by andydotxyz** [comment]
Thanks. I can now replicate it on a Mojave MBP with an external screen. It seems to start at the internal display resolution and then correct itself when moved.

We can work with this :)

**Comment by andydotxyz** [comment]
Is this still an issue? (my test rig is in another place that I won't be at for 4 days...)

**Comment by toaster** [comment]
No, I cannot replicate the issue any more.
