### ISSUE TITLE
There is an error using bundled.go

### ISSUE THREAD

**Issue by cvq** [fyne-io/fyne#2651]
### To Reproduce:
Steps to reproduce the behaviour:
1. Run bundle: fyne bundle survey.png > bundled.go
2. In my main.go:
img := canvas.NewImageFromResource(resourceSurveyPng)
3. Run app: go run main.go
4. See error: # command-line-arguments
.\main.go:35:37: undefined: resourceSurveyPng

### Screenshots:

my bundled.go look like this:
![image](https://user-images.githubusercontent.com/18697826/142369342-5afac8d7-0c66-4fe8-9245-7effde2a5103.png)

my code:
![image](https://user-images.githubusercontent.com/18697826/142371098-113d76d7-5c5a-402d-a6d3-a726eec7fa32.png)

### Device (please complete the following information):
 - **OS:** Windows 11
 - **Version:** Windows 11
 - **Go version:** 1.17.3
 - **Fyne version:** 2.1.0

Please help to fix

**Comment by zSnails** [comment]
That's not an error with the file, you're telling go to only run `main.go`

Instead try `go run .`

**Comment by cvq** [comment]
OMG. Thank you so much **zSnails**.

**Comment by Jacalz** [comment]
Closing per the above comments. Thanks @zSnails for helping out.
