### ISSUE TITLE
install error need some guidence on the missing module

### ISSUE THREAD

**Issue by ArkAngeL43** [fyne-io/fyne#2652]
### Describe the bug:
install failed, no such file directory <X11/extensions/Xrandr.h>

### Screenshots:

```
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/c_glfw.go:4:
./glfw/src/x11_platform.h:39:10: fatal error: X11/extensions/Xrandr.h: No such file or directory
   39 | #include <X11/extensions/Xrandr.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Device (please complete the following information):
 - **OS:** 
 - **Version:** 
 - **Go version:** 
 - **Fyne version:** 

i have had errors like this before but after spending some time looking on google and some old forums i could not find anything for X11, no guide on how to install it, evcen after someone said

```
sudo apt install libx11-dev
```
it said it was installed and still got the same error then tried some others installing modules that may have something to do 

```
sudo apt-get install libx11-dev ; sudo apt-get install mesa-common-dev ; sudo apt-get install libglu1-mesa-dev ; sudo apt-get install libxrandr-dev ; sudo apt-get install libxi-dev

```
but still no luck, please let me know if you can help me :D, really looking forward to using your module!

**Comment by Jacalz** [comment]
Havs you folkleden the installera steps on https://developer.fyne.io/started/? Can you also please fill out the device information in the issue template?

**Comment by ArkAngeL43** [comment]
i did not, i just ran the install and everything worked out fine! thank you for the link :sunglasses:

**Comment by Jacalz** [comment]
Great!
