### ISSUE TITLE
Update Linux/XDG app settings to delegate theme to new fd.o color-scheme

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#2657]
Updating the `app/app_xdg.go` function `defaultVariant` to look up the value now defined "globally" https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml#L33-L45

**Comment by Jacalz** [comment]
We might possibly also be able to read the gsettings value for `org.gnome.desktop.interface gtk-theme` and see if it contains "dark". This is, as an example, how you would set dark theme on Gnome using the terminal:
```
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
```

**Comment by Jacalz** [comment]
I have dug a bit deeper and this appears to be a proper freedesktop specification now  that should be supported in Gnome 42 and ElementaryOS 6.1 (probably KDE Plasma in the future as well). This link has pretty much all the details: https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/

**Comment by andydotxyz** [comment]
That blog post is helpful, but I still cannot find any documentation that is not in a gnome blog post or wiki ;)

**Comment by Jacalz** [comment]
True. That part is a bit weird but I think the above link should have most of what is needed to implement it. I did found out about this from the elementary OS 6.1 release notes though: https://blog.elementary.io/elementary-os-6-1-available-now/.

**Comment by andydotxyz** [comment]
Don't they get it for free from using the latest Gnome libs? i.e. it may still be proposed at the Gnome side rather than ratified standard...

**Comment by Jacalz** [comment]
Maybe. Seems like they really want it to be a standard though. Maybe the standard just hasn't been published yet? Seems like they have good intentions for making it a standard either way. We are probably closer now than we ever have been with this.

**Comment by metal3d** [comment]
I made an implementation here: https://github.com/fyne-io/fyne-x/pull/48

**Comment by Jacalz** [comment]
@metal3d Would you care to bring the functionality specific to this issue into the main code base here? We already follow light/dark themes on Windows/macOS and it would be great if we do so on Linux as well :)

**Comment by metal3d** [comment]
Yes, I can propose the theme here.

Of course, as you see, I found ways to follow dark/light theme on Linux, but I think there is a few of decision to take on what I did.
But we can discuss on the PR.

Let me a few minute to make the PR 😄

**Comment by metal3d** [comment]
This is done here: https://github.com/fyne-io/fyne/pull/3410

**Comment by Jacalz** [comment]
I think there was a misunderstand here. I meant the part about only switching the default FyneTheme between dark and light (exactly what this issue relates to), not bringing in everything about icons and such (at least not yet).

**Comment by andydotxyz** [comment]
I think #3414 should be what you were considering @Jacalz ?

**Comment by Jacalz** [comment]
Ah, I see. I missed that one, it seems. Thanks :)

**Comment by andydotxyz** [comment]
Not at all, it is new this morning after some chat in contributor channel last night

**Comment by andydotxyz** [comment]
Nicely completed, thanks @metal3d
