### ISSUE TITLE
Ability to generate Android Application Bundle - .aab

### ISSUE THREAD

**Issue by agajdosi** [fyne-io/fyne#2663]
### Is your feature request related to a problem? Please describe:

Since August 2021 the Play Store requires new applications to be delivered as .aab. However the fyne only compiles to .apk.

### Is it possible to construct a solution with the existing API?

It is not possible to output .aab with fyne right now.

### Describe the solution you'd like to see:

Fyne should be able to compile to .aab format.

**Comment by andydotxyz** [comment]
Just a comment here that application updates can still be delivered using .apk.
No excuse not to support .aab, just added info.

**Comment by andydotxyz** [comment]
Sorry for the delay, PR is finally open and my first .aab was uploaded to Google Play :).

**Comment by agajdosi** [comment]
@andydotxyz Great news, thank you for the effort!

**Comment by andydotxyz** [comment]
Landed and ready for testing on `develop` branch
