### ISSUE TITLE
Wrong Widgets or....

### ISSUE THREAD

**Issue by wwderw** [fyne-io/fyne#2681]
### Describe the bug:
I seem to be having a speed concern with using SQLite and rendering that result using Fyne.

I have used a table view, list view, and just regular labels and buttons rendered in a HScroll. The later being the most performant, but still takes a full 2 min to render. The other 2 were upwards of 6 min and some change.

It is rendering a lot of items in the master list (about 2400), so I don't know if these widgets are optimized for handling that large of data via SQLite. The examples that I have seen using these various widgets are either hard coded or they deal with json files. I haven't seen an example using SQLite, so I just don't know if there is a reason for that or I'm just doing something wrong.

Like with so many things, I tend to just know enough to cause damage.

Thanks for the help.

### Example code:

```fileMenu1 := fyne.NewMenuItem("Master List", func() {

		db, err := sql.Open("sqlite", "otrDB.db")
		if err != nil {
			log.Fatal(err)
		}
		rows, _ := db.Query("SELECT Name FROM SQLite_master ORDER BY 1 ASC")
		defer rows.Close()

		for rows.Next() {
			var name string
			rows.Scan(&name)
			//shows := widget.NewButton(name, func() { println(name) })
			shows := widget.NewLabel(name)
			listLayout.Add(shows)

		}
		db.Close()

		listLayout.Refresh()
		mainLayout.Refresh()
	})
```

### Device (please complete the following information):
OS: KDE Neon based on Ubuntu 20.4
Go v: 1.17.4
Fyne v: 2.1

EDIT: The only thing that I can think of that I didn't do right was that I attached the snippet versus embedding it (that always seems to get me, some projects actually want it attached and not embedded, so I get used to that).

I think that is all that I didn't do correctly, let me know if there is more info that I need to add.

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by andydotxyz** [comment]
Looking at the code it is clear that you are creating a widget for every item in your response. This will never be performant.
Instead when using `List` or `Table` you create template objects and then assign data to them when they are being displayed.
That is how you get performance in high volume data applications.
Go check out the docs or the Fyne book on how to use List more effectively, and post more questions&code&details here if you can't figure it out.

**Comment by wwderw** [comment]
I think that's what was getting me, when actually creating the template, because both List and Table were actually less performant compared to the snippet above.

Back over the docs again and see what I can come up with.

Thanks!

**Comment by andydotxyz** [comment]
When used correctly the List widget will create around 10 Label widgets instead of len(data) which could be 10000.

**Comment by wwderw** [comment]
Ok, so it is for sure my just knowing enough to cause damage.  It's how to handle it in the rows.Next() loop.

Above and outside the loop, I have:

`listView := widget.NewList(func() int { return rowFinalCount }, nil, nil)`

I used nil, because I didn't think I would be able to handle the content and the update outside of the Next() loop.

Inside the Next() loop, I tried:

```
listView.CreateItem(func() fyne.CanvasObject { return widget.NewLabel(name) })

```
I actually tried different things within () in CreateItem(), but I would always get an error on that.  I didn't try listView.UpateItem() as I am sure that would follow the same schema as CreateItem(), unless I am just totally out there in lala land with what I'm trying.

I would imagine it would be the same process for table view outside of returning two ints in the first function.

**Comment by andydotxyz** [comment]
Do not pass `nil` for the callbacks, they need to be the "create" and "update" functions, as specified in the tutorial.
You cannot call `CreateItem` yourself, it is used by the list to create enough items at runtime.

Basically you are thinking about it backwards. These collection widgets (List, Table, Tree) all operate on dynamic data. They will create items as required and apply data to them based on the callback functions.
To get this working consider accessing the data rows from inside the "Update" function. Once that is working you can look at caching strategies for even better performance.

**Comment by wwderw** [comment]
Oh ok.  That makes sense.
I'll give that a shot and see how that goes.

**Comment by wwderw** [comment]
So this is what my NewList widget is:
```
listView := widget.NewList(
			func() int { return rowFinalCount },
			func() fyne.CanvasObject {

				return widget.NewLabel("")
			},
			func(lii widget.ListItemID, co fyne.CanvasObject) {

				for rows.Next() {
					var name string
					rows.Scan(&name)
					println(name)
					co.(*widget.Label).SetText(name)

				}
			
			},
		)
```

The println(name) outputs to the console exactly what I expect to see.  However, what is displayed is the last entry, followed by quite a lot of blank entries and the last entry, and just rinse and repeat.

Performance was instantaneous.

It seems to be returning the NewLabel string from the 2nd callback, along with just the final entry:
![listview](https://user-images.githubusercontent.com/24878362/145331066-320e32d4-5aae-4e6c-bb8d-b5f357c34b6a.png)

Now, that was the initial update when everything updates originally.  If I were to scroll down and go back up, it will all be blank lines (or whatever I had in the string portion of the 2nd callback).

This happened with both List and table view.

My table snippet:

```
tableView := widget.NewTable(
			func() (int, int) { return rowFinalCount, 1 },
			func() fyne.CanvasObject {

				return widget.NewLabel("")
			},
			func(tci widget.TableCellID, co fyne.CanvasObject) {
				for rows.Next() {
					var name string
					rows.Scan(&name)
					println(name)

					co.(*widget.Label).SetText(name)
				}

			},
		)
```

**Comment by andydotxyz** [comment]
Don't iterate in the "Update" callback. It is telling you the row that it wants to populate (`tci widget.TableCellID`).
You need to get the data for that specific row. Just that row - not all of them.
Your current code is iterating all DB rows for the first label, then for all the others there is no "next" so they are blank.

**Comment by wwderw** [comment]
Success.  Got it to work in a ListView. 

Thanks for the help and the patience, I really do appreciate it.

**Comment by andydotxyz** [comment]
Glad you got it working.
If you have future questions I would recommend joining our #fyne channel on gophers Slack or Discord - there are lots of people there who can help.
