### ISSUE TITLE
Floats bound with a format fail to validate with correct input

### ISSUE THREAD

**Issue by turtletowerz** [fyne-io/fyne#2684]
### Describe the bug:
With both dialog.ShowForm and widget.Form, entries that contain data-bound floats and the format `%0.2f` fail to validate even if the input is valid. When first created the entries will have the checkmark icon, but if the text is changed in any way it will error, even if the new input is valid.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create a new data binding entry using `FloatToStringWithFormat` and have the format be `%0.2f`
2. Render that entry in any form (or potentially any window)
3. Attempt to change the default input value

### Screenshots:
Screenshots are in order of their code snippets below
![2021-12-09_16-26-14](https://user-images.githubusercontent.com/29441515/145478261-229f68ba-259e-422c-8ba7-85a97433f64a.png)
![2021-12-09_16-30-47](https://user-images.githubusercontent.com/29441515/145478761-48644bab-bd32-4312-91eb-02f67b114960.png)
In both of these screenshots an error is shown despite 0.84 and 0.58 matching the `%0.2f` format. In the dialog screenshot the confirm box is greyed out as well.

### Example code:
The first code snippet is a standalone example of dialog.ShowForm producing this error, while the second example is a widget.Form

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(350, 250))
	w.CenterOnScreen()
	w.SetMaster()

	testFloat := 0.64
	entry := widget.NewEntryWithData(binding.FloatToStringWithFormat(binding.BindFloat(&testFloat), "%0.2f"))
	content := []*widget.FormItem{widget.NewFormItem("Test", entry)}

	btt := widget.NewButton("Test", func() {
		dialog.ShowForm("Example Dialog", "Confirm", "Cancel", content, nil, w)
	})

	w.SetContent(btt)
	w.ShowAndRun()
}
```
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test 2")
	w.Resize(fyne.NewSize(300, 150))
	w.CenterOnScreen()
	w.SetMaster()

	testFloat := 0.64
	entry := widget.NewEntryWithData(binding.FloatToStringWithFormat(binding.BindFloat(&testFloat), "%0.2f"))
	form := widget.NewForm(widget.NewFormItem("Test 2", entry))

	w.SetContent(form)
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 20H2
 - **Go version:** 1.14+ has been tested
 - **Fyne version:** 2.0.4 and 2.1.2

**Comment by andydotxyz** [comment]
I cannot replicate this with Fyne v2.1.2.
I can make EOF appear but only if I add more characters (i.e. 1.234)

**Comment by andydotxyz** [comment]
Oh no, maybe format should have been "%.2f".
https://yourbasic.org/golang/fmt-printf-reference-cheat-sheet/

**Comment by turtletowerz** [comment]
Interesting... Go Playground formats the two the same way [seen here](https://play.golang.com/p/_vx2dW_Iulu), but this may just be the way _fmt_ works. I'll close this because it seems like an issue at my end
