### ISSUE TITLE
Text and links in markdown are rendered in each other

### ISSUE THREAD

**Issue by SKBotNL** [fyne-io/fyne#2695]
### Describe the bug:
Text and links in markdown are rendered in each other

### Screenshots:
![image](https://user-images.githubusercontent.com/68018116/146408805-3298ad24-9b2a-4e0d-b081-38e84a28e2fb.png)

### Example code:
```go
container.NewTabItem("Example", container.New(
			layout.NewGridLayout(2),
			widget.NewRichTextFromMarkdown("Text [a link](https://github.com/fyne-io/fyne) more text [another link](https://github.com/fyne-io/fyne)"),
			)),
```

### Device:
 - **OS:** Windows
 - **Version:** 11
 - **Go version:** 1.17.3
 - **Fyne version:** 2.1.2

**Comment by Jacalz** [comment]
Thanks for opening the issue. In the future though, please provide a full code example and not a snippet.

**Comment by andydotxyz** [comment]
It looks like the bug relates to layout (minsize is OK) when a link is the last thing on a line.
Adding "." seems to fix it. This narrows down the issue :)
![foo](https://user-images.githubusercontent.com/294436/146441941-25cc41c7-121a-43af-9751-a3ddc9ea7cab.png)

**Comment by andydotxyz** [comment]
On `release/v2.1.x` for testing
