### ISSUE TITLE
keep rendering while moving window - on Windows

### ISSUE THREAD

**Issue by mk931** [fyne-io/fyne#270]
Hello,
I've noticed that when you move the UI window, the rendering stops until you release it
OS: Windows 10 1903
Steps to reproduce: Load fyne_demo, load a window with a progress bar, drag and drop it and see what happens

The same bug can be noticed with progressbar while rendering, thus making the UX less enjoyable

**Comment by andydotxyz** [comment]
This is not a limitation of Fyne as a toolkit but may be a bug in the windows driver code.
MacOS had a similar issue but I think we resolved that already. 
Hopefully that sort of change can be replicated.

It's usually due to the window event hander freezing during move or resize...

**Comment by paulhovey** [comment]
FWIW I just tested this on debian + KDE using the latest develop branch and it works as expected (meaning the progress bar moves while the window is moved), so it seems to be a Windows-only problem (assuming the comment about OS X is correct :slightly_smiling_face:  )

**Comment by andydotxyz** [comment]
I have re-tested on macOS and it does indeed render as expected whilst moving.
The “workaround” added for the Mac is about resizing and it can be seen as the canvas refreshes every time the window changes size until released. For most use cases this works however you can notice the progress bar speed changes when resizing... there may be additional work to do here!

**Comment by andydotxyz** [comment]
There is a fix on develop for the 1.1 release.
It is not perfect - we can repaint each time the window moves.

A better fix is theoretically possible but it will require collaboration with the GLFW project upstream I think.
