### ISSUE TITLE
 APIUnavailable: WGL: The driver does not appear to support OpenGL

### ISSUE THREAD

**Issue by jahid01711** [fyne-io/fyne#2700]
everything here is working except this error 
the pics have all the info.
the moment I try to run fyne demo or fyne exe this happens. 

ERROR INFO 
 "
E:\All_Programming_Work\GOLANG> go run fyne.io/fyne/v2/cmd/fyne_demo
2021/12/20 20:58:43 Lifecycle: Started
2021/12/20 20:58:43 Fyne error:  window creation error
2021/12/20 20:58:43   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2021/12/20 20:58:43   At: C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/driver.go:123
2021/12/20 20:58:43 Lifecycle: Stopped

E:\All_Programming_Work\GOLANG>go version
go version go1.17.5 windows/amd64    "
![Screenshot (11)](https://user-images.githubusercontent.com/54137658/146788384-ce0033fa-8f26-4747-a2a8-4603f5cae0a3.png)

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues in the future. The templates are designed to help us save time and give us all the necessary information related to the issue (and does so in a standardised and readable way).

What graphics hardware do you have? Are you running this inside a virtual machine? I think the error most likely is right in that the correct OpenGL support is missing in some way or another.

**Comment by jahid01711** [comment]
sorry about that 
 here are the pics gaving graphics info .
i am using my pc . no vm 
![Screenshot (14)](https://user-images.githubusercontent.com/54137658/146792703-fcd6e4b0-948a-4c56-9b07-b0d122b8fb66.png)
![Screenshot (13)](https://user-images.githubusercontent.com/54137658/146792713-01c9f812-2baf-48cf-b526-ad6251f79c52.png)

**Comment by Jacalz** [comment]
From some Googling on that graphics chipset (Intel G41), it does indeed look like it is an issue with OpenGL support in newer Windows versions (seems to be issues with 8 and up). Maybe https://msfn.org/board/topic/174272-intel-g41etc-video-chipsets-no-opengl-support-fix/ could solve your issue.

I'm sorry, but this is not an issue with Fyne and I don't think there is much we can do about it. I sincerely hope that the link above solves your problem.

**Comment by jahid01711** [comment]
I managed to solve the open gl issue but still haveing this error. how to fix this
![Screenshot (16)](https://user-images.githubusercontent.com/54137658/146974949-012216af-28b3-4209-97d5-f84521c9b4cd.png)
![Screenshot (17)](https://user-images.githubusercontent.com/54137658/146974962-4d262117-fe09-4554-8ccf-ccaaa0223613.png)
![Screenshot (18)](https://user-images.githubusercontent.com/54137658/146975168-29419790-dfc8-4474-8d8b-d7edd7d4eb99.png)
?

**Comment by andydotxyz** [comment]
Did you restart after the driver fix?
I would also recommend clearing the Go build cache in case the old driver somehow is still hooked into the cached build

**Comment by jahid01711** [comment]
yes, i have restarted after the driver update and also cleared the go cache still having the same issue 
the error says something like this . which is also previously mentioned in the pics 


E:\All_Programming_Work\GOLANG>fyne_demo
2021/12/22 22:15:06 Lifecycle: Started
2021/12/22 22:15:06 Fyne error:  failed to initialise OpenGL
2021/12/22 22:15:06   Cause: glBindFramebuffer
2021/12/22 22:15:06   At: C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/painter/gl/gl_core.go:104
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x7ff7444a44b0, 0xc0003cbdc0)
        C:/Program Files/Go/src/runtime/cgocall.go:156 +0x4a fp=0xc0003cbd98 sp=0xc0003cbd60 pc=0x7ff743fe468a
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowCreateShader(0x0, 0x8b31)
        _cgo_gotypes.go:5509 +0x5a fp=0xc0003cbdc0 sp=0xc0003cbd98 pc=0x7ff7442ba27a
github.com/go-gl/gl/v3.2-core/gl.CreateShader(...)
        C:/Users/jahid/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20210813123233-e4099ee2221f/v3.2-core/gl/package.go:9301
fyne.io/fyne/v2/internal/painter/gl.compileShader({0x7ff7448ef2ef, 0xd0}, 0x444090a6)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/painter/gl/gl_core.go:114 +0x4a fp=0xc0003cbe68 sp=0xc0003cbdc0 pc=0x7ff7442d5a2a
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Init(0xc000094330)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/painter/gl/gl_core.go:201 +0x33 fp=0xc0003cbea8 sp=0xc0003cbe68 pc=0x7ff7442d5d73
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func2()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:1464 +0x6b fp=0xc0003cbee0 sp=0xc0003cbea8 pc=0x7ff74442b2cb
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc000382400, 0xc0000e02a0)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:1349 +0x4f fp=0xc0003cbef8 sp=0xc0003cbee0 pc=0x7ff74442a64f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/loop.go:232 +0x14c fp=0xc0003cbfe0 sp=0xc0003cbef8 pc=0x7ff74442188c
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0003cbfe8 sp=0xc0003cbfe0 pc=0x7ff744044f81
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/loop.go:224 +0xef

goroutine 1 [select, locked to thread]:
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc000054fc0)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/loop.go:119 +0x16b
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc000382400)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/driver.go:85 +0x30
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc000382400)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:475 +0x2f
main.main()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/cmd/fyne_demo/main.go:66 +0x45e

goroutine 6 [chan receive]:
fyne.io/fyne/v2/test.NewApp.func1()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/test/testapp.go:113 +0x45
created by fyne.io/fyne/v2/test.NewApp
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/test/testapp.go:111 +0x305

goroutine 7 [syscall, locked to thread]:
syscall.Syscall6(0x7ffed55a5dd0, 0x5, 0x224, 0xc00004bd60, 0xc00004bd00, 0xc00004bdb0, 0xffffffff, 0x0)
        C:/Program Files/Go/src/runtime/syscall_windows.go:497 +0xfa
syscall.getQueuedCompletionStatus(0x0, 0xc00004bd60, 0xc00004bd00, 0xc00004bdb0, 0xffffffff)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:836 +0xb4
syscall.GetQueuedCompletionStatus(0xc00034ff40, 0xc000096000, 0xc00004bd64, 0xfff, 0x0)
        C:/Program Files/Go/src/syscall/syscall_windows.go:1239 +0x45
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00034ff40)
        C:/Users/jahid/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:381 +0x7a
created by github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/jahid/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:46 +0x1db

goroutine 8 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/app/settings_desktop.go:42 +0x6c
created by fyne.io/fyne/v2/app.watchFile
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/app/settings_desktop.go:41 +0x10f

goroutine 10 [syscall, locked to thread]:
syscall.Syscall6(0x7ffed55a5dd0, 0x5, 0x234, 0xc0003cfd60, 0xc0003cfd00, 0xc0003cfdb0, 0xffffffff, 0x0)
        C:/Program Files/Go/src/runtime/syscall_windows.go:497 +0xfa
syscall.getQueuedCompletionStatus(0xc0003cfd08, 0xc0003cfd60, 0xc0003cfd00, 0xc0003cfdb0, 0xffffffff)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:836 +0xb4
syscall.GetQueuedCompletionStatus(0xc00034ffc0, 0xc00001aa80, 0xc0003cfd64, 0xfff, 0x0)
        C:/Program Files/Go/src/syscall/syscall_windows.go:1239 +0x45
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00034ffc0)
        C:/Users/jahid/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:381 +0x7a
created by github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/jahid/go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/windows.go:46 +0x1db

goroutine 11 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1()
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/app/settings_desktop.go:42 +0x6c
created by fyne.io/fyne/v2/app.watchFile
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/app/settings_desktop.go:41 +0x10f

goroutine 13 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc000382400)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/common/window.go:57 +0x7d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:1408 +0x15b

goroutine 14 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedCanvasObjectChan).processing(0xc0003bdb90)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/async/chan_canvasobject.go:47 +0xe5
created by fyne.io/fyne/v2/internal/async.NewUnboundedCanvasObjectChan
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/async/chan_canvasobject.go:24 +0xfd

goroutine 21 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.runOnDraw(0xc000382400, 0xc0000e02a0)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/loop.go:71 +0xeb
fyne.io/fyne/v2/internal/driver/glfw.(*window).create(0xc000382400)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:1462 +0xb1
sync.(*Once).doSlow(0x0, 0x7ff744020f25)
        C:/Program Files/Go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        C:/Program Files/Go/src/sync/once.go:59
fyne.io/fyne/v2/internal/driver/glfw.(*window).doShow(0xc000382400)
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:394 +0x87
created by fyne.io/fyne/v2/internal/driver/glfw.(*window).Show
        C:/Users/jahid/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/driver/glfw/window.go:382 +0x5b
rax     0xc0003cc000
rbx     0xc0003cbdc0
rcx     0x8b31
rdi     0xc0003cc000
rsi     0xc00003c820
rbp     0xc0003cbd88
rsp     0x71a05ffc68
r8      0xc000046800
r9      0x0
r10     0xc000122101
r11     0x12
r12     0xc0003cbe40
r13     0x0
r14     0xc0002e8ea0
r15     0x40
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
![Screenshot (16)](https://user-images.githubusercontent.com/54137658/147122649-8fbedb90-9174-4c51-982a-46d01ca9c5e9.png)

**Comment by andydotxyz** [comment]
Do you have multiple graphics chips / cards @jahid01711?

**Comment by jahid01711** [comment]
No i dont have any graphics card , its integrated one probably with mother bord or cpu .

**Comment by andydotxyz** [comment]
In the "OpenGL Extensions Viewer" there is a "Renderer" drop-down at the top. What items does this list contain?

**Comment by jahid01711** [comment]
I just tried Fyne in a Dell laptop with intel UHD 300 graphics where it supports open gl 4.0  having windows 11 but this pc it just doesn't want to load things.

now as you asked its shows 2.0 in the render window
![Screenshot (19)](https://user-images.githubusercontent.com/54137658/147320264-911079f0-7b23-4816-acdf-abcabf945d63.png)
.

**Comment by jahid01711** [comment]
update I was able to run the demo and the hello fyne thanks to mesa 3d. I just paste the masa 3d 64-bit dll to the exe folder and it's working smoothly. the only thing that I hate is that I have to paste dll where exe is.
thanks, everyone but you can add something to help load the fyne with mesa 3d. and find the real error or some alternative to solve these issues. 




![Screenshot (20)](https://user-images.githubusercontent.com/54137658/147322964-2cfd97b9-6654-4243-82a0-92395a0c52ab.png)
.

**Comment by Jacalz** [comment]
Something is really strange there. You shouldn't have to put any mesa3d doll in the folder to get it working. The thing that I find even more confusing is the fact that Mesa, Linux graphics drivers, exist in some form on Windows. My Windows 10 pc has an Nvidia GTX 1060 but I have no issues there. Something strange going on with your Intel graphics?

**Comment by jahid01711** [comment]
my pc doesn't have any graphics card. as you prementioned I check and I realize my latest graphics driver that comes with windows 10 or I sometimes download from Driver booster don't support open gl. then I found a media accelerator driver its old but it was made for windows 7/8 and it supports Windows 10 and also supports open gl 2.1 / 2.0. at least that's what I saw in open gl extension viewer. Even so, I use GPU caps viewer to test 3d demos of open gl . I was able to render a few open gl demos which was from open gl2.0 . still doing so fyne wasn't working so then I used mesa and olla it's working. 
I used this site and only 64bit works with fyne and 32bit DLL doesn't work.
https://fdossena.com/?p=mesa/index.frag

about the rest of the part, I also want to what's happening here and I also didn't know mesa was a Linux driver if you want you can look into my pc and we both might try to figure out what's happening . ??

**Comment by Jacalz** [comment]
> about the rest of the part, I also want to what's happening here and I also didn't know mesa was a Linux driver if you want you can look into my pc and we both might try to figure out what's happening . ??

I appreciate the idea, but I wouldn’t be of much help given that I’m mainly a Linux user these days. Let’s see if someone else has better ideas about what could be wrong.

**Comment by jahid01711** [comment]
Recently changed linux anyways i was digging into this more and i found some documentation where few have suggested and was able to use fyne using directx rather then open gl . I didnt read the whole part and yet there were few stuff that i dont nothing of but looks  like some gold mine is over there   . You can look into this or if you know how to fyne with directx .

https://docs.google.com/document/d/1mqquznil9fR2amtb3eTC2ObCx3A8Af_5INqKjO-pKDg/edit#

https://github.com/fyne-io/fyne/issues/911

**Comment by jahid01711** [comment]
> > about the rest of the part, I also want to what's happening here and I also didn't know mesa was a Linux driver if you want you can look into my pc and we both might try to figure out what's happening . ??
> 
> I appreciate the idea, but I wouldn’t be of much help given that I’m mainly a Linux user these days. Let’s see if someone else has better ideas about what could be wrong.

Recently changed linux anyways i was digging into this more and i found some documentation where few have suggested and was able to use fyne using directx rather then open gl . I didnt read the whole part and yet there were few stuff that i dont nothing of but looks  like some gold mine is over there   . You can look into this or if you know how to use fyne with directx ??

https://docs.google.com/document/d/1mqquznil9fR2amtb3eTC2ObCx3A8Af_5INqKjO-pKDg/edit#

The issue was discussed here : https://github.com/fyne-io/fyne/issues/911

**Comment by andydotxyz** [comment]
> In the "OpenGL Extensions Viewer" there is a "Renderer" drop-down at the top. What items does this list contain?

This piece of information is really needed to understand what might be happening.
