### ISSUE TITLE
Window can not reopen on Mac

### ISSUE THREAD

**Issue by Purelightme** [fyne-io/fyne#2705]
### Describe the bug:
thanks for fyne first.It is a great gui tool.But i found a bug (or my code error) :
At first time,i click "launch window2",window2 opened correctly,Then i click system close button to close window2, i cannot open window2 again through button "launch window2".
If i close window2 through click "hide window2",i can open window2 again.
What is wrong with my code?i want to open window2 multiple times even through i close it through system close button.

### To Reproduce:
Steps to reproduce the behaviour:
1. go run main.go
2. Click on 'launch window2'
3. Close window2 through system close button
4. I cannot open wndow2 again

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

	w1 := a.NewWindow("window1")

	w2 := a.NewWindow("window2")
	w2.SetContent(widget.NewLabel("This is window2"))

	content := container.NewVBox(
		widget.NewButton("hide window2", func() {
			w2.Hide()
		}),
		widget.NewButton("launch window2", func() {
			w2.Show()
		}),
		)

	w1.SetContent(content)
	w1.Resize(fyne.NewSize(200,200))
	w1.ShowAndRun()
}
```
-->

### Device (please complete the following information):
 - **OS:** MACOS
 - **Version:** Bug Sur 11.5.2
 - **Go version:** go1.15.6 darwin/amd64
 - **Fyne version:** 2.1.2

**Comment by Jacalz** [comment]
I think this is because the window is being destroyed when you press the close button. The workaround (or perhaps the right way) is to add a close intercept that hides the window instead of closing it.
```go
w2.SetCloseIntercept(w2.Hide)
```
I hope this works for you.

**Comment by Purelightme** [comment]
I got it.Thank you so much.i will close it.

**Comment by Jacalz** [comment]
Happy to help. I'm glad that it solved the issue for you.
