### ISSUE TITLE
Is there any widgets which can embedd other application like bash/cmd/powershell?

### ISSUE THREAD

**Issue by blackfox1983** [fyne-io/fyne#2706]
### Is your feature request related to a problem? Please describe:

I want to implement an integrated terminal software,  similar to vscode terminal or goland terminal which actually call the terminal of the system, but the effect seems to be embedded inside. fyne-io/terminal is not active and updated, and i cannot find a similar component in fyne.

**Comment by Jacalz** [comment]
Not that I am aware of. I think fyne-io/terminal is your best bet. Not sure that I’d go as far as saying that that project isn’t alive and updated though.

**Comment by andydotxyz** [comment]
Fyne-io/terminal is the solution and it is also active. The widget is used in our terminal app and Defyne IDE project.
