### ISSUE TITLE
DocTabs scrolling not working in fyne demo

### ISSUE THREAD

**Issue by xines** [fyne-io/fyne#2708]
### Describe the bug:

DocTabs [***] menu scrolling not working correctly.

### To Reproduce:

Open fyne_demo and select -> containers -> doctabs -> add enough tabs for scrolling -> menu scrolling not working for "bottom", "leading", "trailing", but works for top.

### Device:
 - **OS:** Windows 10
 - **Go version:** 1.17.5
 - **Fyne version:** v2.1.2-rc2.0.20211224183324-531f14545ce7

**Comment by Jacalz** [comment]
Could you please clarify what "not working" is on your end? I can replicate that there is something wrong, in my case the scroll seems to reset to the start as soon as it reaches the end. This is obviously wrong, but I don't see any difference between the tab placements. Are you sure that it works as expected on top for you?

It works if you scroll by dragging the bar, but using the touchpad (and, I assume, using a mouse as well) just scrolls forever. On develop however, I see that dragging the bar doesn't work either. I but this as a blocker for now.

**Comment by xines** [comment]
@Jacalz Here made a quick video of the few issues, hope it helps.

https://user-images.githubusercontent.com/4853844/147592879-fbc7f44d-6a88-490f-8ad0-56259f6328ec.mp4

**Comment by andydotxyz** [comment]
Thanks for the clarity. It looks like the scroller is resetting as the selected item would appear...
The pop-up menu indeed does seem to have issues as well, this is even stranger as it should work the same irrespective of where it is loaded!

**Comment by andydotxyz** [comment]
Same with AppTabs, so must be in the common code - or even in the menu handling.

**Comment by andydotxyz** [comment]
The mentioned PR should fix the issues, feel free to check it out and see :)

**Comment by xines** [comment]
> The mentioned PR should fix the issues, feel free to check it out and see :)

Tested on win10 works, gj.

Only issue i seem to have if it's not intended behavior, is on the main scroller choosing a tab resets the view position to the start?

**Comment by andydotxyz** [comment]
> Only issue i seem to have if it's not intended behavior, is on the main scroller choosing a tab resets the view position to the start?

This is not intended. I don't know if it is related or not but I will look at it further.

**Comment by andydotxyz** [comment]
Fixed, thanks for pointing that out :)

**Comment by xines** [comment]
> Fixed, thanks for pointing that out :)

Very nice.

- Happy new year to the team :)

**Comment by Jacalz** [comment]
Happy new year to you as well :)

I'll go ahead and review the PR later today hopefully.

**Comment by Jacalz** [comment]
> Fixed, thanks for pointing that out :)

I can't seem to find the commit that fixes this. Am I missing something or did you miss to push the change?

**Comment by andydotxyz** [comment]
> > Fixed, thanks for pointing that out :)
> 
> I can't seem to find the commit that fixes this. Am I missing something or did you miss to push the change?

Sorry, issues with a stale branch, should be in now.

**Comment by Jacalz** [comment]
I'll close hat now that the PR is merged. Thanks for opening this issue. The fix should be released with v2.1.3, sometime next year.
