### ISSUE TITLE
Entry does not scale with GUI

### ISSUE THREAD

**Issue by Lewiscowles1986** [fyne-io/fyne#2711]
### Describe the bug:

When resizing an Entry. There seems to be no capacity outside of the `FYNE_SCALE` to alter the font size. This does possibly relate to #21 although it only requires a sub-set of the features.

For now I can work-around this using an SVG image as something to draw that will scale.

Oddly enough, this behavior could be correct in some cases, and a bug in others. If for example I had a dense medical input screen. I might not want the entire UI to scale up. In this case the GUI is in a game and using a Grid to auto-stretch controls. As long as an aspect ratio is respected, I'd like to be able to scale and stretch. This may not be an "Entry" problem, but rather a problem when constraining to grid.

### To Reproduce:

1. Setup the SudokGo repo to run
2. Resize the screen
3. Note that fonts stay the same size

#### FYNE_SCALE=2.5

![image](https://user-images.githubusercontent.com/2605791/147658074-844a3253-59fe-4885-a6a5-b1150c2161bb.png)

This is exactly what I'd want to happen if I took the screen to this size.

#### FYNE_SCALE=1

![image](https://user-images.githubusercontent.com/2605791/147658130-10373838-5d19-42e1-af8d-ca6d7c342919.png)
Initial starting size
![image](https://user-images.githubusercontent.com/2605791/147658167-cf315c55-5e0e-4b16-80e9-9539705aee03.png)
Scaled up size, which has tiny text.

Perhaps this would not be for an entry, but a layout to decide to scale on resize.

### Example code:

Looking at the design of Fyne; this may be non-trivial to overcome. For-now, I'm just not using Entry, and instead managing selection of a custom widget, very similar to chess; drawing an SVG image, which does resize as the grid resizes, can maintain aspect ratio etc.

### Device (please complete the following information):

 - **OS:** Windows 10 x64 (should be the same on all devices)
 - **Version:** 21H2 build 19044.1415
 - **Go version:** 1.16
 - **Fyne version:** 2.1.2 (was same in 1.4.3)

**Comment by andydotxyz** [comment]
This is correct, standard widgets should not scale their text based on the space available.
The theme is in place to ensure consistency in colour, icons and size - so adjusting dynamically does not make sense.
A custom widget would be able to what you want, but it won't be a feature of the standard library.
