### ISSUE TITLE
proposal: expose runOnMain

### ISSUE THREAD

**Issue by changkun** [fyne-io/fyne#2716]
# proposal: expose `runOnMain`

proposal document: https://github.com/changkun/fyne-proposals/blob/runOnMain/expose-runOnMain.md

## Background

I wrote a [hotkey](https://github.com/golang-design/hotkey) package for public use. However, there is a limitation on plugging that package into any other GUI framework, such as fyne.

The main limitation is that the hotkey registration APIs from OS (i.e. darwin) must be executed on the main thread. For individual usage, a self-occupied mainthread scheduling, such as [mainthread](https://github.com/golang-design/mainthread) package works nicely, but this will require to call `[NSApp run]` that runs the Cocoa's main event loop, which completely conflicts with the fyne's window boot process. Two of them are impossible to live together.

Until recently, @ventsislav-georgiev reports [a fyne-based application](https://github.com/ventsislav-georgiev/prosper) could not collaborate with golang-design/hotkey package unless forking it, see https://github.com/golang-design/hotkey/issues/7#issuecomment-1003099355.

The mentioned reason fundamentally limits potential third-party authors to extend some unimplemented OS features that require to be called on the main thread.

## API Design

Calling on the main thread functionality is implicitly exposed via
type assertion. For drivers that supports running on the main thread,
developers can assert if an `fyne.App` implements `CallOnMainThread(func())` method. For instance,

```go
ap, ok := fyne.CurrentApp().(interface{ CallOnMainThread(func()) })
if !ok {
    panic("fyne: current driver does not support call on the main thread")
}

ap.CallOnMainThread(func() {
    println("this function is called on the main thread")
})
```

## Implementation

An implemented prototype can be found in: https://github.com/changkun/fyne/tree/exposeRunOnMain.
Here is the main change:

```diff
commit 9dcc94ba480cc02f54fddb234a9492efc4234fa7
Author: Changkun Ou <hi@changkun.de>
Date:   Sun Jan 2 11:04:09 2022 +0100

    app: expose CallOnMainThread implicitly

diff --git a/app/app.go b/app/app.go
index 50f241db..ea21f123 100644
--- a/app/app.go
+++ b/app/app.go
@@ -97,6 +97,15 @@ func (a *fyneApp) Lifecycle() fyne.Lifecycle {
 	return a.lifecycle
 }

+func (a *fyneApp) CallOnMainThread(f func()) {
+	if ap, ok := a.driver.(interface{ CallOnMainThread(func()) }); ok {
+		ap.CallOnMainThread(f)
+		return
+	}
+
+	panic("fyne: CallOnMain is not supported in the current driver.")
+}
+
 // New returns a new application instance with the default driver and no unique ID
 func New() fyne.App {
 	internal.LogHint("Applications should be created with a unique ID using app.NewWithID()")
diff --git a/internal/driver/glfw/driver.go b/internal/driver/glfw/driver.go
index 8e1cbaf4..f48c867b 100644
--- a/internal/driver/glfw/driver.go
+++ b/internal/driver/glfw/driver.go
@@ -132,6 +132,17 @@ func (d *gLDriver) initFailed(msg string, err error) {
 	}
 }

+// CallOnMainThread schedules the given function f to be executed on the main
+// thread. This method blocks until the called function is returned.
+//
+// This method is implicitly exposed to the public. For developers who would
+// like to call a function on the main thread, one can assert if the current
+// fyne.App have the support. For example,
+//
+// 	if ap, ok := fyne.CurrentApp().(interface{ CallOnMainThread(func()) }); ok {
+// 		ap.CallOnMainThread(func() { println("calls on the main thread")})
+// 	}
+func (d *gLDriver) CallOnMainThread(f func()) { runOnMain(f) }
+
 func goroutineID() int {
 	b := make([]byte, 64)
 	b = b[:runtime.Stack(b, false)]
```

## A Minimum Example

See an example at https://github.com/changkun/demos/blob/main/hotkeys/fyneapp/main.go.

**Comment by andydotxyz** [comment]
I'm not so sure about this. What threading is available sounds like a fundamental design for someones app. To be able to only do this on "some" drivers (in this case implicitly only works on desktop) feels like very likely cause for many future support requets.
The code passed to this function will runtime crash in a mobile context which feels like going against our design principles.
Namely:

* The same code should function on any devices, where possible
* Our library should never crash a developers app (except for fatal setup failure)

Just my take on the matter of course, other opinions would be helpful.

**Comment by changkun** [comment]
> To be able to only do this on "some" drivers

This impression is essentially not true. We do not expose it as a public interface method in fyne.App, this makes us retain the possibility that we could still remove it in the future without breaking the public APIs as this is only for very rare use cases. If we moved in the direction that more drivers need the support, retaining the mainthread in fyne is easy to implement as we only have to send event loop and draw loop to non-main threads and schedule mainthread calls, which leads to consistent call behavior across all drivers. Hence the first concern does not exist.

For the second, using build constraints might be another option. This means such an API is only callable when //go:build darwin is activated (despite I believe Android needs this too).

**Comment by andydotxyz** [comment]
I appreciate that you describe different ways to solve the same problem, but I guess I am not expressing well that I don't think we should have API changes per-operating system.
If thread management is something we need to support then we should do so for all apps on all platforms. Otherwise I strongly think we should not try to support it.
macOS, Linux, Windows all have different threading models, this is not even stepping into the issue that on some the main thread may do draw commands and on others it will not.

**Comment by changkun** [comment]
> thread management

The framing of thread management support seems to be less accurate as we only need the communication of the mainthread. Any other threads can be self-maintained using the runtime ability `runtime.LockOSThread`.

> we should do so for all apps on all platforms

I agree that we need a mainthread scheduling for all platforms so that we can deliver consistent API behaviors. That means, fyne occupies the mainthread internally and provides a consistent API such as `app.RunOnMainThread` or `fyne.RunOnMainThread`.

> issue that on some the main thread may do draw commands and on others it will not

It seems that drawing calls on different threads does not impact the behavior of exposing runOnMain, because they are isolated calls.

**Comment by Bluebugs** [comment]
I am not familiar enough with Fyne at the moment, but doesn't that interface introduce a risk that user code can lock or introduce jitter in the rendering if the main thread get to busy.

**Comment by andydotxyz** [comment]
On some platforms it could cause these graphical issues, on others it could cause interruptions in window / event code. It varies based on driver / OS.
Of course the same is technically true of any callback code :).

**Comment by changkun** [comment]
It's true that such an API has a danger of misuse, but I would argue it's also the price to pay for access to that ability. Hence a proper document is necessary for the usage of the API.

**Comment by andydotxyz** [comment]
I think that makes sense. We would need a lot of documentation or large work on our own API thread handling. Maybe there is another way to support the use-case?
