### ISSUE TITLE
Is there any simple way to access motion sensors on mobile? 

### ISSUE THREAD

**Issue by mrhdias** [fyne-io/fyne#2717]
I'm developing an application in fyne for remote control, but I can't find a simple way to access the gps, gyroscope and accelarometer.
Does anyone have an idea how I can do this?

**Comment by andydotxyz** [comment]
Currently we don’t have APIs for this in Fyne, so you’d need to use another Go library or access the iOS/Android code via CGo

**Comment by MatejMagat305** [comment]
you can try this: https://github.com/rakyll/sensors

**Comment by andydotxyz** [comment]
I think that is now at https://pkg.go.dev/golang.org/x/mobile/exp/sensor
