### ISSUE TITLE
How do I set margins between components

### ISSUE THREAD

**Issue by melf-xyzh** [fyne-io/fyne#2719]
How do I set margins between components

**Comment by Jacalz** [comment]
You can either create a new theme and change the padding value there (will affect everything, so might not be the perfect solution) or you could add items into a `container.NewPadded` (or the corresponding layout). Another option would be to create a custom layout, see https://developer.fyne.io/extend/custom-layout for more information. Creating a layout is fairly simple. It just requires some clever thinking and getting the math to work out as expected.

**Comment by andydotxyz** [comment]
It would be best to visit one of our support channels https://fyne.io/support/.
Please don't open a feature request to ask a question - this GitHub project tracks development and bugs for toolkit.
