### ISSUE TITLE
Extending Line canvas element fails to draw the element

### ISSUE THREAD

**Issue by chippyash** [fyne-io/fyne#2720]
### Describe the bug:
Extending Line canvas element fails to draw the element.

If I create a canvas element based on Line, calling its Refresh() function does not draw the because the underlying Line canvas object is not present in the cache.

### To Reproduce:
Steps to reproduce the behaviour:
1/ See code attached
2/ The DataChanged() function is fired by my application and I see debug info printed out
3/ The issue is when s.Refresh() is called.  This is a proxy to Line.Refresh() which in turn calls canvas.Refresh()
L108 of calls canvas.Refresh()
```go
c := fyne.CurrentApp().Driver().CanvasForObject(obj)
```
returns nil, as the Sweep object is not in cache.

I looked in the code to see if there was a way to manually add the Sweep to the cache but cannot find anything as all the code that handles it is in the fyne/internal module and not accessible.  Looking at the code for Line, there is nothing obvious that tells me how a Line gets into cache.

changing `s.Refresh()` to `s.Line.Refresh()` does not work either.

Either I am missing something, (there is nothing the docs - "extending Fyne" does not have a section on extending canvas objects unfortunately), this is not currently possible, or there is a bug somewhere in the library code.  Any help is appreciated.

### Example code:
```go
package components

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/data/binding"
	"image/color"
	"math"
	C "on-my-radar/constants"
)

// Declare conformity with CanvasObject interface
var _ fyne.CanvasObject = (*Sweep)(nil)

//
// STATE
//

//Sweep is a radar sweep state object
type Sweep struct {
	*canvas.Line
	sweepAngle binding.ExternalFloat
	parent *Radar
}

func NewSweep(color color.Color, sweepAngle binding.ExternalFloat, parent *Radar) *Sweep {
	s := &Sweep{
		Line:       canvas.NewLine(color),
		sweepAngle: sweepAngle,
		parent: 	parent,
	}

	s.sweepAngle.AddListener(s)
	return s
}

//DataChanged implements DataListener interface
func (s *Sweep) DataChanged() {
	min := float32(math.Min(float64(s.parent.Size().Height), float64(s.parent.Size().Width)))
	centre := min / 2
	s.Position1 = fyne.Position{X: centre, Y: centre}
	angle, _ := s.sweepAngle.Get()
	t := C.PI_HALF * angle
	radius := centre - C.BEZEL_WIDTH
	cx := float64(centre)
	cy := float64(centre)
	x := cx + math.Cos(t) * float64(radius)
	y := cy + math.Sin(t) * float64(radius)
	s.Position2 = fyne.Position{X: float32(x), Y: float32(y)}
	s.Refresh()
	println("Sweep: %f, $f - %f, %f", centre, centre, x, y)
}
```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** Ubuntu 20.04.3 LTS
 - **Go version:** go1.15.15 linux/amd64
 - **Fyne version:** 2.1.2

**Comment by Jacalz** [comment]
The issue could theoretically be that you are extending `*canvas.Line` and not `canvas.Line` inside your struct. I would suggest trying that (I am currently on mobile, can’t test myself).

I might be entirely wrong with this, so take this with a grain of salt, but I am not sure if we support extending the canvas primitives. It might only be widgets.

**Comment by chippyash** [comment]
@Jacalz 
> The issue could theoretically be that you are extending `*canvas.Line` and not `canvas.Line` inside your struct.

Ok, so tried that
```go
type Sweep struct {
	canvas.Line
	sweepAngle binding.ExternalFloat
	parent *Radar
}

func NewSweep(color color.Color, sweepAngle binding.ExternalFloat, parent *Radar) *Sweep {
	s := &Sweep{
		Line:       *canvas.NewLine(color),
		sweepAngle: sweepAngle,
		parent: 	parent,
	}

	s.sweepAngle.AddListener(s)
	return s
}
```

Same result I'm afraid.

**Comment by stuartmscott** [comment]
AFAIK Canvas objects cannot be extended, only widgets (@andydotxyz to confirm)

**Comment by andydotxyz** [comment]
That is correct, canvas objects cannot be extended - they are just data passed to renderer.
To add new types of line it must be coded into all of the different renderers in the Fyne internals.

**Comment by andydotxyz** [comment]
I would recommend looking into `BaseWidget` and `SimpleRenderer` as it's not much code to turn a canvas primitive into a widget.

**Comment by chippyash** [comment]
Thanks chaps for the input. At least I know now why it doesn't work.  

One thought; Whilst I was digging into the code, I noted that the cache package has ```func GetCanvasForObject(obj fyne.CanvasObject) fyne.Canvas``` which is called by the driver ```func CanvasForObject(obj fyne.CanvasObject) fyne.Canvas```.  cache also has a ```func SetCanvasForObject(obj fyne.CanvasObject, canvas fyne.Canvas)```. However driver does not expose this in a similar proxy function. Given that I could get the canvas object from my parent (Radar widget), would it be worth adding the proxy call to the driver so that we could then set the canvas object for such extended canvas elements such as the Sweep?  e.g.
```go
func NewSweep(color color.Color, sweepAngle binding.ExternalFloat, parent *Radar) *Sweep {
	s := &Sweep{
		Line:       *canvas.NewLine(color),
		sweepAngle: sweepAngle,
		parent: 	parent,
	}

	cnv := fyne.CurrentApp().Driver().CanvasForObject(parent)
	fyne.CurrentApp().Driver().SetCanvasForObject(s.Line, cnv)
	
	s.sweepAngle.AddListener(s)
	return s
}
```

The use case is that the extended element *is* going to be drawn on a known canvas that we can get from an existing element ( a widget in this case). I don't know if this would cause further complications but maybe it's a simple change that would help?

Regards

**Comment by andydotxyz** [comment]
It would be possible to force your item into the cache, but that won’t fix the problem.
The type ‘myCustomLine‘ does not have any associated render routines in our driver, so it still will not be able to draw.

**Comment by chippyash** [comment]
@andydotxyz "It would be possible to force your item into the cache, but that won’t fix the problem."

Why not?- Separate answer required

I'm not asking this to be belligerent, but to figure out why. 

Use Case: I have used this same paradigm to test out many drawing/gui packages. React and Vue come recently to mind. They both support  d3 and state control

**Comment by stuartmscott** [comment]
Maybe this will help; a custom canvas doesn't appear in this switch statement https://github.com/fyne-io/fyne/blob/master/internal/painter/gl/draw.go#L91, so the driver will ignore it and never get to the point where it tries to pull something out the cache.

**Comment by andydotxyz** [comment]
Yes exactly, I thought I had explained it with the other half of my message:

> The type ‘myCustomLine‘ does not have any associated render routines in our driver, so it still will not be able to draw.

To support super-fast drawing of canvas primitives the objects do not encode information about how they will be rendered.
The way that Fyne does it is require that you create a widget that adds behaviour, using the `Line` primitive to do the drawing. It's essentially the same but organised in a different way.

Simplest definition: `canvas` package is for just drawing - to add behaviour you need to create a `Widget` or extend something in `widget`. That is how it works here. What you describe is possible, but you need to code it slightly differently.
