### ISSUE TITLE
Make menu shortcuts appear more decent

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#2722]
@andydotxyz had an idea regarding the appearance of (non-native) menu shortcuts (https://github.com/fyne-io/fyne/pull/2715#issuecomment-1005334488):
> the menu shortcut text is as clear as the menu text (and disabled appropriately) but should it be more subtle? (I think I have seen some places do that).
> Would having the shortcut hints be in the disabled colour too light? do we need a "caption" colour that would make sense or similar?

I think the idea is worth to be discussed and that mock-ups should be created to show the visual effect.

**Comment by matwachich** [comment]
Another thing about the shortcut text format.
I don't think that ^A or !A or +A id understandable by common users, especially on Windows, where it is more common to see Ctrl+A or Alt+A or Shift+A

**Comment by andydotxyz** [comment]
Fixed on develop :)
