### ISSUE TITLE
[BUG] Error in `github.com/go-gl/glfw/v3.3/glfw` package when run basic example

### ISSUE THREAD

**Issue by koddr** [fyne-io/fyne#2728]
### Describe the bug:

Hi,

I ran into a confusing issue. Took the very first example from your documentation, installed the dependencies and ran the application. But an error has occurred, most likely somehow related to macOS.

### To Reproduce:
Steps to reproduce the behaviour:
1. Create `main.go` with this:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

2. Install dependencies
3. Run `go run main.go`
4. See error:

```console
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../.go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/native_darwin.go:7:
In file included from ./glfw/include/GLFW/glfw3native.h:95:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                         ~~~~~~~~~~~~~~                                                                       ^                  ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~
1 error generated.

Compilation finished with exit code 2
```

### Device (please complete the following information):
 - **OS:** macOS Big Sur
 - **Version:** 11.6.2 (20G314), Intel, x86_64
 - **Go version:** 1.17.5
 - **Fyne version:** 2.1.2

**Comment by andydotxyz** [comment]
Are you running the very latest XCode (13.2.x)? (Any XCode updated in the last 3 weeks)
It seems that many projects have been hit by some non-compatible change in the latest API macro definitions.

It seems that this may be resolved by removing the XCode that was upgraded from older (12.5 or before), and re-installing it clean: https://github.com/facebook/infer/issues/1535.

**Comment by koddr** [comment]
@andydotxyz yes, after updating Command Line Tool (`xcode-select --install`) the error no longer occurs! Thanks for the tip 👍
