### ISSUE TITLE
exec.Cmd implementations could be made testable

### ISSUE THREAD

**Issue by asciifaceman** [fyne-io/fyne#274]
`exec.Cmd` lines such as this can be made testable.

https://github.com/fyne-io/fyne/blob/333d28aabf7276b2f8cd88635870b0d9d765caf1/app/app_darwin.go#L10-L15

# Example

### In Code
```
var execCmd = exec.Command

func (app *fyneApp) OpenURL(url *url.URL) error {
	cmd := execCommand("open", url.String())
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd.Run()
}
```

### In test

```
// stub the exec command and tell it  to return whatever we want
func stubExecCmd(command string, args ...string) *exec.Cmd {
	fmt.Println("Sub executable called")
	cs := []string{"-test.run=TestHelperProcess", "--", command}
	cs = append(cs, args...)
	cmd := execCmd(os.Args[0], cs...)
	cmd.Env = []string{"GO_WANT_HELPER_PROCESS=1"}
	return cmd
}

func TestOpenURL(t *testing.T) {
     execCmd = stubExecCmd // Subvert with stubbed execution
     defer func() { execCmd = exec.Command }() // restore functionality after test is complete
     ...
     err := a.OpenURL(someUrl)
     if err != nil {
         t.Errorf("expected no error but got: %v", err)
    }
}

func TestHelperProcess(t *testing.T){
    if os.Getenv("GO_WANT_HELPER_PROCESS") != "1" {
        return
    }
    // some code here to check arguments perhaps, return different  codes based on that?
    defer os.Exit(0)

    args := os.Args
    for len(args) > 0 {
        if args[0] == "--" {
            args = args[1:]
            break
        }
        args = args[1:]
    }
    if len(args) == 0 {
        fmt.Fprintf(os.Stderr, "No command\n")
        os.Exit(2)
    }
    // etc etc
}
```

Sorry I wrote this in the  github issue so formatting might be a little wonky 

# Conclusion
One of the best  results of this is we can tell the stub command to return whatever we want, meaning we can test error and success returns trivially without actually touching the command in question

I'm willing to implement this, I just wanted to put it up for discussion first.

**Comment by andydotxyz** [comment]
A good suggestion, thanks. I wonder if there is a way that could avoid the global variable?

**Comment by asciifaceman** [comment]
I believe it could be wrapped with a struct.

```
type commandOp struct {
    execCmd exec.Command
}

co := &commandOp{execCmd: exec.Command}

co := &commandOp{execCmd: stubExecCmd} // etc

co.execCmd(...)
```

But it also feels tedious

**Comment by andydotxyz** [comment]
yeah a bit tedious.
Is there a sensible way that dependency injection could work in our favour here perhaps?
As the test is internal to the package perhaps a private field on fyneApp?

**Comment by asciifaceman** [comment]
I tried out a private field in fyneApp with the method I mentioned in chat 

```
reset := app.SetExec(testCmd)
defer reset()
```

But I ran into an issue where testApp refused to conform as it was expecting  `fyne.setExec`  rather than `setExec` which was confusing

**Comment by andydotxyz** [comment]
Is that due to a clash in naming with the package perhaps?

**Comment by asciifaceman** [comment]
I don't fully know, I'll revisit it in the near future

**Comment by asciifaceman** [comment]
@andydotxyz 🥇
