### ISSUE TITLE
Add multi window support to the web driver

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2740]
### Is your feature request related to a problem? Please describe:
The web driver currently only support one window. It is an unexpected requirement on Fyne application that should be lifted to get the web driver out of alpha.

### Is it possible to construct a solution with the existing API?
The goal of this issue is to make sure that existing API work properly on the web driver, so no new API should be added.

### Describe the solution you'd like to see:
The idea would be to reproduce the same logic the mobile driver use and instead of having multiple real window, we reuse the only window we can create and stack all requested window on top. It might be possible to refactor the mobile code somehow and reuse it for this feature.

**Comment by andydotxyz** [comment]
$250 is currently allocated for eligible contributors completing this work (see [Contributing: Membership](https://github.com/fyne-io/fyne/wiki/Contributing%3A-Membership)).

**Comment by andydotxyz** [comment]
Landed for the v2.5.0 release that will have rc1 published today
