### ISSUE TITLE
Add mouse wheel support to web driver

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2744]
### Is your feature request related to a problem? Please describe:
Current web driver doesn't handle properly the mouse wheel that lead to it being disable under some condition.

### Is it possible to construct a solution with the existing API?
There should not be any new API.

### Describe the solution you'd like to see:
Most likely the problem is that the mouse wheel catcher should be on the canvas and not the window. Need to review how that work and solve it.

**Comment by Dorbmon** [comment]
Do you know under which condition, behavior will be inconsistent in listening on the window and listening on the canvas?

**Comment by andydotxyz** [comment]
Fixed ready for v2.5.0
