### ISSUE TITLE
How can binding.UntypedList data  be displayed by list method

### ISSUE THREAD

**Issue by LiuYanJan** [fyne-io/fyne#2745]
### Is your feature request related to a problem? Please describe:

I recently encountered a problem. The data（type binding.UntypedList） searched from the beginning is displayed through the list method.
data like this  [{id:1, mess:"Jack", age:14}, {id:1, mess:"Miki", age:10}]

list := widget.NewListWithData(su.Result,
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {

			o.(*widget.Label).Bind(i.(binding.map).["id"])// It is wrong!
		})
### Is it possible to construct a solution with the existing API?

I'm looking forward to your earliest reply.  Thanks!

**Comment by andydotxyz** [comment]
When using `binding.UntypedList` and `ListWithData` the items are each `Untyped`, so do something like:

```go
o.(*widget.Label).Bind(i.(binding.Untyped)…)
```

but bear in mind that label Bind requires a string so there will be some additional work required to convert, but that is in your code somewhere I guess?

**Comment by andydotxyz** [comment]
If you have questions please try to use one of our support channels (https://fyne.io/support). This bug tracker is for issues and feature requests in the toolkit.

**Comment by LiuYanJan** [comment]
> When using `binding.UntypedList` and `ListWithData` the items are each `Untyped`, so do something like:
> 
> ```go
> o.(*widget.Label).Bind(i.(binding.Untyped)…)
> ```
> 
> but bear in mind that label Bind requires a string so there will be some additional work required to convert, but that is in your code somewhere I guess?

Ohhhhhhhhhhhhh  I get， Thank you!
