### ISSUE TITLE
Require latest go version for compiling web assembly

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2751]
### Is your feature request related to a problem? Please describe:
The goal would be to disable with a clear error message web assembly as a target when the go compiler is to old.

### Is it possible to construct a solution with the existing API?
No new API should be needed.

### Describe the solution you'd like to see:
Checking the go version against a hard coded one and exiting fyne command if that version is to old. Currently only 1.17 is to be supported.

**Comment by Bluebugs** [comment]
That might be an idea, but I was hoping for a more user friendly error message. Also I see that as a first step toward the the dual gopherjs/wasm web package where we would have to detect both go and gopherjs to enable the relevant part of the generated web site.

**Comment by Jacalz** [comment]
No longer an issue. We only support Go 1.17 and up and soon that will be 1.19 and up.
