### ISSUE TITLE
Failed to load TTC font: freetype: invalid TrueType format: bad TTF version

### ISSUE THREAD

**Issue by ipfans** [fyne-io/fyne#2761]
### Describe the bug:

When I trying to load font with `FYNE_FONT` env but it failed with error.

### To Reproduce:

`go run main.go`. Code as Example Code.

### Screenshots:

```
2022/02/03 10:28:18 Fyne error:  font load error
2022/02/03 10:28:18   Cause: freetype: invalid TrueType format: bad TTF version
2022/02/03 10:28:18   At: /Users/User/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/internal/painter/font.go:27
```

### Example code:

```go
package main

import (
	"os"
	"runtime"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"github.com/flopp/go-findfont"
)

func main() {
	paths := findfont.List()
	for _, path := range paths {
		if runtime.GOOS == "darwin" {
			if strings.Contains(path, "PingFang.ttc") {
				os.Setenv("FYNE_FONT", path)
				break
			}
		}
	}
	a := app.New()
	w := a.NewWindow("Hello World")
	w.SetFixedSize(true)
	w.Resize(fyne.NewSize(300, 300))
	w.SetContent(widget.NewLabel("你好，世界!"))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** macOS
 - **Version:** 12.1
 - **Go version:** Go 1.17.6
 - **Fyne version:** 2.1.2

**Comment by Bluebugs** [comment]
Does the license of the font allow you to share it with us? Or can you point us to a website where we can get it?

**Comment by andydotxyz** [comment]
There is no need to see the file - you can tell from the extension that it is not a TTF file. That is the only type of font file we support (as the error shows).

**Comment by ZHOUYue67** [comment]
> There is no need to see the file - you can tell from the extension that it is not a TTF file. That is the only type of font file we support (as the error shows).

There's a simple implementation: now fyne use "font.ParseTTF" to load a single font, you can simply change it to "font.ParseTTC" and choose the first one. "ParseTTC" works for both ttf and ttc. There's no way to choose which font in ttc using this method though.
