### ISSUE TITLE
Check license of dependencies as part of Fyne PR/release process

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2767]
### Is your feature request related to a problem? Please describe:
To make sure that we do not inadvertently depend on a module with the wrong license it would be nice to integrate a tool in our github action that does check all the license for compatibility purpose (License compliance)

### Is it possible to construct a solution with the existing API?
No new API should be necessary for this as this will just be part of our github workflow.

### Describe the solution you'd like to see:
@lucor pointed out tools like: https://github.com/google/go-licenses for this purpose.

**Comment by Bluebugs** [comment]
Thanks for your work! This looks good. I think we can start with this list of license and if the need arise, we can discuss adding additional license.

**Comment by andydotxyz** [comment]
In :)
