### ISSUE TITLE
How to use  button in list?

### ISSUE THREAD

**Issue by LiuYanJan** [fyne-io/fyne#2768]
## Needs
I need use a button in list, like "delete button", but I can not get the widget.ListItemID as  button's func() defineded before widget.ListItemID.

## Code
```
list1 := widget.NewList(
		func() int{
			return len(su.Result[0])
		},
		func() fyne.CanvasObject{
			hbox := container.NewGridWithColumns(ldd)
			for i :=0; i < ldd; i++{
				if i == 3{
					hbox1 := container.NewGridWithColumns(2)
					hbox1.Add(widget.NewLabel("table"))
					hbox1.Add(widget.NewButton("Delete", func(){
                                          // Can't  get  the widget.ListItemID  there !!!
					}))
					hbox.Add(hbox1)

				}else{
					hbox.Add(widget.NewLabel("table"))
				}

			}

			return hbox
		},
		func(li widget.ListItemID, o fyne.CanvasObject) {
			box := o.(*fyne.Container)
			for i := 0; i < ldd; i++{
				if i == 3{
					box1 := box.Objects[i].(*fyne.Container)
					lb1 := box1.Objects[0].(*widget.Label)
					lb1.SetText(su.Result[i][li])
					lb2 := box1.Objects[1].(*widget.Button)
					lb2.SetText("Delete")

				}else{
					lb1 := box.Objects[i].(*widget.Label)
					lb1.SetText(su.Result[i][li])
				}

			}
		},
	)


```
## Is there some func() I haven't found？

Hope your answer， Thank You!!!

**Comment by andydotxyz** [comment]
In the last callback function when you load the data you can set the button tapped function.

`lb2.OnTapped = buttonCallback(li)`

**Comment by jhaoheng** [comment]
hi there

I use `widget.NewTable()`
and when I set the Cell to  `*fyne.Container` type.
It broke.
the error log show `panic: interface conversion: fyne.CanvasObject is *widget.Label, not *fyne.Container`
Does the cell only accept `*widget.Label` type?

Thanks.

**Comment by Jacalz** [comment]
@jhaoheng Please don't post off-topic questions on issues. If you have a question, you should open a new discussion on GitHub (likely the right thing for you this time) or a new issue if it is a bug. I will hide these two messages as off-topic.

**Comment by andydotxyz** [comment]
Going to close this as it's asking a question that doesn't really fit - those callbacks shouldn't really be looping through all data. If anyone else is confused by this or wants to know more consider reading the list tutorial first https://developer.fyne.io/widget/list
