### ISSUE TITLE
error: 'dlfcn.h' file not found  (when running code which used to work)

### ISSUE THREAD

**Issue by serge-hulne** [fyne-io/fyne#2772]
### Describe the bug:
Trying to run a simple Fyne example (which used to compile), I got errors, so I reinstalled the dependencies
```
rm go.*               
sergehulne@Serges-Mac-mini fyne1 % go mod init f1        
go: creating new go.mod: module f1
go: to add module requirements and sums:
	go mod tidy
sergehulne@Serges-Mac-mini fyne1 % go mod tidy           
go: finding module for package fyne.io/fyne/v2/layout
go: finding module for package fyne.io/fyne/v2/app
go: finding module for package fyne.io/fyne/v2
go: finding module for package fyne.io/fyne/v2/canvas
go: finding module for package fyne.io/fyne/v2/container
go: found fyne.io/fyne/v2 in fyne.io/fyne/v2 v2.1.2
go: found fyne.io/fyne/v2/app in fyne.io/fyne/v2 v2.1.2
go: found fyne.io/fyne/v2/canvas in fyne.io/fyne/v2 v2.1.2
go: found fyne.io/fyne/v2/container in fyne.io/fyne/v2 v2.1.2
go: found fyne.io/fyne/v2/layout in fyne.io/fyne/v2 v2.1.2

sergehulne@Serges-Mac-mini fyne1 % go build      
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../../../../go/bin/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:184:
./glfw/src/cocoa_platform.h:28:10: fatal error: 'dlfcn.h' file not found
#include <dlfcn.h>
         ^~~~~~~~~
1 error generated.
# github.com/go-gl/gl/v3.2-core/gl
../../../../../go/bin/pkg/mod/github.com/go-gl/gl@v0.0.0-20210813123233-e4099ee2221f/v3.2-core/gl/conversions.go:12:11: fatal error: 'stdlib.h' file not found
 #include <stdlib.h>
 ```

### Example code:
Trivial Fyne snippet:

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
)

func main() {
	myApp := app.New()

	myWindow := myApp.NewWindow("Grid Layout")

	rect1 := canvas.NewRectangle(color.Black)
	rect2 := canvas.NewRectangle(color.Black)
	rect3 := canvas.NewRectangle(color.Black)

	rect4 := canvas.NewRectangle(color.Black)
	rect5 := canvas.NewRectangle(color.Black)
	rect6 := canvas.NewRectangle(color.Black)

	rect2.FillColor = color.White

	grid := container.New(layout.NewGridLayout(3), rect1, rect2, rect3, rect4, rect5, rect6)

	myWindow.SetContent(grid)

	myWindow.Resize(fyne.NewSize(400, 350))
	myWindow.CenterOnScreen()
	myWindow.ShowAndRun()

}
```

### Device (please complete the following information):
 - **OS:**  MacOS darwin/arm64
 - **Version:** Monterey 12.0.1 (Mac mini M1 chip)
 - **Go version:** go version go1.17 
 - **Fyne version:** latest

**Comment by Jacalz** [comment]
FYI, I fixed the formatting for the code blocks for you to make them a bit more readable as well as adding go formatting to the code.

What Fyne version do you use? We prefer to avoid using “latest” as it is unclear wether it is the latest stable release (2.1.2 at the time of writing) or any new development version. It will also become out of date and misleading in the future.

As for the issue, I’m not sure what would be the cause. Looks like a missing file. I wonder if it’s the same issue we had before with files being removed when vendoring?

**Comment by serge-hulne** [comment]
Thanks for reformatting the code! 👍 

I reinstalled Fyne today. How can I check the version more precisely? (I know how to do it with Go itself ("go version")), but I don't know how to check the Fyne version from the command line.

**Comment by serge-hulne** [comment]
I should have guesses !

**Comment by andydotxyz** [comment]
Updating the title to reference the true error cause.

**Comment by andydotxyz** [comment]
The missing file is a standard Apple header as far as I can see.
If you recently upgraded your mac did you make sure to re-install Xcode and the commandline tools?
macOS has an annoying habbit of breaking cmdline builds on OS upgrade.

**Comment by serge-hulne** [comment]
The error messages mentions both headers files.

**Comment by serge-hulne** [comment]
I’ll check Xcode now.

**Comment by andydotxyz** [comment]
> The error messages mentions both headers files.

But I see only one instance of the phrase "fatal error" so I updated to indicate that was the problem.

**Comment by serge-hulne** [comment]
All right.

**Comment by serge-hulne** [comment]
The version of Xcode and Xcode command line installed is : 
Version 13.2.1 (13C100)
to make sure it works, I have compiled a "Hello world" in C and it works.

I also requested the (unnecessary) inclusion of "dlfcn.h" and the compiler does not complain, so I guess that file is not missing in the include path 

`
#include <stdio.h>
#include <dlfcn.h>

int main() {
    printf("Hello from C\n");
    return 0;
}
`

**Comment by serge-hulne** [comment]
I think I have found the source of errors:

```
sergehulne@Serges-Mac-mini Webview % clang -v
Homebrew clang version 13.0.1
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
sergehulne@Serges-Mac-mini Webview % brew remove llvm
Error: Refusing to uninstall /opt/homebrew/Cellar/llvm/13.0.1
because it is required by crystal, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies llvm
```

**Comment by serge-hulne** [comment]
Thank you very much for your help.
