### ISSUE TITLE
Problem with winodws 10 pe

### ISSUE THREAD

**Issue by davideginna** [fyne-io/fyne#2778]
### Describe the bug:
I run helloworld.exe fyne in windows 10 pe distro but when i do double click program do not start. 
I also launched the program via console and with debug prints, but I don't see any logs

### To Reproduce:
Steps to reproduce the behaviour:
1. Download winpe form https://www.hirensbootcd.org/
2. execute helloworld compiled in exe

### Device (please complete the following information):
 - **OS:** winpe
 - **Version:** v1.0.2
 - **Go version:** 1.17.7
 - **Fyne version:** latest at 02/13/2022

**Comment by Jacalz** [comment]
Do you have any anti virus software that is active in the background?

**Comment by andydotxyz** [comment]
Debug / error information is printed to the console. Can you please try opening `cmd` and running the application from there, so we see the command line output?
The chances are that WinPE does not have OpenGL support, which Fyne currently requires.
