### ISSUE TITLE
Tab rendering issue when assigned to grid.

### ISSUE THREAD

**Issue by 0x42424242** [fyne-io/fyne#278]
### Bug
A basic hello world tab container example was created and added to a grid layout. This consisted of two tabs, "Hello" and "World", each displaying the associated text. In the first example when clicking on the "World" tab the content would not render, however all future interactions between tabs rendered correctly. 

**Code used to reproduce**
https://gist.github.com/0x42424242/1fb31db730bc0a5336d560a4889e6122

**GIF of the unexpected behavior**
![behaviour](https://user-images.githubusercontent.com/10124857/58518833-212b4d00-81f4-11e9-8804-29057fe7f6e6.gif)
_Note: The initial click on the world tab is the first time the tab has been interacted with._

### Working Example
At the suggestion of Andrew Williams in Slack, I tried assigning the tab container directly instead of placing it within a grid layout. This successfully eliminated the bug, suggesting it may be tied to the grid container in some way. 

**Code used to generate an example with expected behavior**
https://gist.github.com/0x42424242/3d9d90178f8efa910cdfb91939ee7766

**GIF of the expected behavior**
![behaviour_working](https://user-images.githubusercontent.com/10124857/58518976-e2e25d80-81f4-11e9-89ed-0092307d6b95.gif)
_Note: The initial click on the world tab is the first time the tab has been interacted with._

**Comment by andydotxyz** [comment]
This is resolved on develop for the 1.1 release
