### ISSUE TITLE
fyne package command deleting main.go file

### ISSUE THREAD

**Issue by 50Cale** [fyne-io/fyne#2786]
### Describe the bug:
When running command `fyne package` or `fyne install` it will error out with error `no Go files in /fynetest Error building application exit status 1`

Before the error appears the main.go will be deleted, and since the main.go is deleted, the error appears showing "no GO files"

I am following the documentation found here 
https://developer.fyne.io/started/packaging

I have encountered no other recognizable errors while using Fyne and `go build` with any of my Fyne Applications work great.

### To Reproduce:
1. Create main.go
2. go mod init main.go
3. paste example code from readme/getting started
4. `go mod tidy`
5. `go run main.go` + `go run build` to test | this is successful
6. add any icon for package | i use 24kb file of golang gopher as test
7. `fyne package` | this is not successful

### Screenshots:
![fyneerror](https://user-images.githubusercontent.com/66532987/154147990-5680c231-2f5d-4e69-bed1-8f182c9cab7b.gif)

### Example code:

Using default example code in fyne readme under Getting Started, but this happens with any project I have tried

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):

I have tried this on multiple devices + go versions while troubleshooting
 - **OS:** Linux, MacOS
 - **Version:** MacOS 12.2.1; Arch Linux 5.16.8-arch1-1
 - **Go version:** 1.16.14; 1.17.7
 - **Fyne version:** fyne cli version: v2.1.2

Thank you.

**Comment by andydotxyz** [comment]
I cannot replicate this problem, I don't know what is special about your demo.
One thing stands out - can you change `go mod init main.go` to `go mod init mypackage` just in case that is confusing things?
I suspect that there is a conflict between the package name and file name, as the package is normally a name or URL-like namespace...

**Comment by andydotxyz** [comment]
Additionally I suspect that if you ran `go build` without the `-o fynetest` parameter you would see similar conflict.
In such you could do `fyne package -name fynetest` to perform similar override.

**Comment by 50Cale** [comment]
Changing the go mod init to {packagename} from main.go fixed it. Thank you very much sir, I was banging my head against a wall on this one.
