### ISSUE TITLE
Relative width and height, like 100%

### ISSUE THREAD

**Issue by igoracmelo** [fyne-io/fyne#2787]
### Is your feature request related to a problem? Please describe:

No.
Just a feature.

### Is it possible to construct a solution with the existing API?

I am not sure.

### Describe the solution you'd like to see:

Be able to set, for example, a HBox to span the whole width setting its horizontal size do 100%.

**Comment by andydotxyz** [comment]
The default size for an `HBox` is 100%. All widgets / containers take all available space by default.
Layouts can choose to use less space, but the default is maximum - so everything is already relative to the 100% available.

So I'm not sure what this issue is asking for.

**Comment by igoracmelo** [comment]
@andydotxyz I was making this layout:
VBox
|__ HBox
|____ Label
|____ Entry
|____ Button
|__ HBox
|____ Label
|____ Entry
|____ Button
|__ Button

But for some reason HBox'es weren't taking full horizontal space.

![image](https://user-images.githubusercontent.com/85039990/154379840-dc3d4f35-18b5-47fa-98c9-e75f0e615211.png)

**Comment by andydotxyz** [comment]
Yes, the Hboxes are taking full space. The things inside them are not, because HBox packs items at minimum width. https://developer.fyne.io/faq/layout

**Comment by andydotxyz** [comment]
Footnote: you probably want border layout instead for your rows

**Comment by igoracmelo** [comment]
@andydotxyz Thanks. Just a last question if I may.
Is there a detailed example of how to use the layouts?

I mean, there is the examples repo, but most of them are games or grid layouts.
I would like to see how common layouts are made.
I already have some experience is this field, but with CSS.

**Comment by andydotxyz** [comment]
The script that generates the images at the linked page can be viewed at https://github.com/fyne-io/developer.fyne.io/blob/master/_gen/genlayouts.go.
For info on how to build a layout see https://developer.fyne.io/extend/custom-layout .
