### ISSUE TITLE
How to cancel the full screen control of the application window?

### ISSUE THREAD

**Issue by LiuYanJan** [fyne-io/fyne#2793]
### Is your feature request related to a problem? Please describe:

No,
How to cancel the full screen control of the application window? This control is the rectangular box in the upper right corner. 

### Is it possible to construct a solution with the existing API?

No, or some func() I didn't find?

### Describe the solution you'd like to see:

Sorry i can't upload pictures， but I don't know how to cancel the function of this control, I need a fixed interface size.

**Comment by andydotxyz** [comment]
Use `Window.SetFixedSize(true)`

**Comment by LiuYanJan** [comment]
> Window.SetFixedSize(true)

ah, so embarrassing, I set it to be false........
