### ISSUE TITLE
Calling dialog.NewFileOpen causes an error : Downloads: operation not permitted

### ISSUE THREAD

**Issue by serge-hulne** [fyne-io/fyne#2799]
Calling dialog.NewFileOpen() causes an error : Downloads: operation not permitted

### To Reproduce:
1. Simply running the snippet hereunder on Mac (*with or without sudo*) triggers the error.

```
2022/02/21 11:51:48 Fyne error:  Getting favorite locations
2022/02/21 11:51:48   Cause: open /Users/sergehulne/Downloads: operation not permitted
```

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {

	myApp := app.New()
	w := myApp.NewWindow("Label Widget")
	w.Resize(fyne.Size{400, 300})

	dialog := dialog.NewFileOpen(func(r fyne.URIReadCloser, e error) {
		if e != nil {
			println("Oops")
		}
	}, w)

	button := widget.NewButton("Click", func() { dialog.Show() })
	label := widget.NewLabel("Click on the button to open file manager")
	content := container.NewVBox(button, label)
	w.SetContent(content)
	w.ShowAndRun()

}
```

### Device :
 - Mac OS 12.2.1 on M1 chip
 -  12.2.1 Monterey
 - **Go version:** go version go1.17 darwin/arm64
 - **Fyne version:** fyne.io/fyne/v2 v2.1.2

**Comment by andydotxyz** [comment]
My guess is that it relates to macOS new security restrictions, as /Users/sergehulne/Downloads is a protected folder (IIRC).
If you package the app (using fyne package) and run the resulting app does it request a permission and continue as expected?

Another possible issue is if you accidentally refused permission earlier - if this might be true can you look into your system settings and see if there are some strange settings specific to this application?

**Comment by serge-hulne** [comment]
Hi, In fact when the executable is package as an app (using fyne package), then then app when run requests a permission to access the Download directory and no error message is issued.

Thanks!
