### ISSUE TITLE
Add select box to widgets

### ISSUE THREAD

**Issue by indeedhat** [fyne-io/fyne#28]
Having a drop down box to use in forms would be really nice to have.
Features i would propose for this:

**Essential** 

- List of key:value pairs (this could be as simple as a  map[int]widget.Label)
- Ability to assign an optional OnChange callback in the form of something like func(key int)

**Nice to have**

- Seperator/Inactive elements
- Multi Select functionality
- values of any type (interface{})

**Comment by ajwillia-ms** [comment]
Great suggestion (we may need basic popup or stacking support first, not sure).

I like the idea of interface{} for types, but could we use Stringer instead (to guarantee a sensible visual?)

I’m not sure if the key mapping is truly required. If OnChange was func(value interface{}) instead we could remove that requirement I think?

**Comment by indeedhat** [comment]
I think you are probably right with using Stringer, although having interface{} values would be nice its really not a neccesity and i do feel like it has the potential to cause more problems than it solves.

It is true that the key mapping isnt really necesarry but it is definatly something that would (in my opinion) be really nice to have as it allows for greater flexibility and would allow for more ideomatic usage such as making your changes based on a int constant.

I realise that this is not as simple as just adding a new widget, as you say i think you would need popup support to make it work nicely, for the time being i can make do with other widgets for the time being.

Thanks for the wuick response by the way :)

**Comment by ajwillia-ms** [comment]
Ah I see - you were meaning the int index is useful for changing data.
The way that Fyne is designed you can set data structures to initialise a widget but if you change it at runtime you should use method calls (to avoid having to do manual refresh calls etc). Do you think something like SetIItem(int, Stringer/interface{}) would accomplish what you were aiming for? (with some sanity checking around boundary values)

**Comment by ajwillia-ms** [comment]
In theory setting data then calling refresh is fine - it's just that calling setters will handle the refresh automatically.

There is not currently support for removing components that are no longer needed - that will need to be added and could be the cause of what you are seeing. Whether it is or is not feel free to open a new issue with a screenshot so I can help sort it out.

**Comment by andydotxyz** [comment]
Does the new radio widget help somewhat?

**Comment by indeedhat** [comment]
I ended up using gtk3 bindings for the project i was origionally trying to do and have been waiting for this lib to mature a bit more before i try use it again, i havnt been keeping up on the updates recently but im planning on having a play about this weekend to see how things have changed.

although radio widgets would definatly do for the situation i was needing a select box would be preferable

**Comment by andydotxyz** [comment]
Requires #155

**Comment by andydotxyz** [comment]
Current work in progress, happy to get feedback :)
![Screenshot from 2019-05-05 23-05-55](https://user-images.githubusercontent.com/294436/57201000-a0798800-6f8a-11e9-9b56-4049cdb44357.png)

**Comment by andydotxyz** [comment]
This is now available on the develop branch for testing

**Comment by therealbill** [comment]
Sweet, will try to check it out this week!

**Comment by therealbill** [comment]
Looks good minus one thing: if the select widget's expanded list goes beyond the bottom of the window, you don't get to see anything below the cutoff point.

For example:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/467499/57415862-58917580-71c3-11e9-84ec-bfc0d57d18a1.png">

That is only the first of three items in the select list. I've tried it in a Grid layout as well as added to a form and both result in the above.  In your screenshot, assuming that is the whole window, adding 2-3 more entries should demonstrate it. ;)

(On a probably unrelated note that I should probably make an issue for: if the text in that input box in the screenshot goes beyond the right side of the window, it doesn't scroll within the Entry, meaning you can't see what you typed until/unless you resize the window itself).

**Comment by andydotxyz** [comment]
That should now be resolved too, please let me know if there is anything else
