### ISSUE TITLE
The list/table supports Select() operations

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2818]
### Is your feature request related to a problem? Please describe:
I'm developing a table processing software similar to excel using the component table / list. I hope I can use the key(up, down, left and right) to control the movement of table/list elements. 
After I extend list/table with Focusable, I found the component lack of  method Select(), which call select listItem of List or tabelCell of Table.
At the same time, I also found that the elements of these two components cannot be extended. For example, listItem in List / tableCell in Table belongs to private struct. I think the only solution is to re implement the two components of table / list, which is too much work. I'm not sure if there's another solution.

### Describe the solution you'd like to see:
1. List/Table add a Select() method, similar to DocTab.SelectIndex()

**Comment by andydotxyz** [comment]
I don't understand this, there is already `Table.Select()` method.

**Comment by BabySid** [comment]
> I don't understand this, there is already `Table.Select()` method.

Sorry, I didn't describe it clearly.

What I want to say is the lack of interface that similar to doctab Selectedindex(). However, after your reply, I found that a similar effect can be achieved according to the current OnSelect interface.

The problem is solved. Thank you very much for your inspiration~
