### ISSUE TITLE
Create dialogs for opening files, selecting colors, and selecting fonts

### ISSUE THREAD

**Issue by dzwvip** [fyne-io/fyne#282]
没发现有 打开文件、选择颜色、字体选择这些常用的对话框，尤其是文件选择对话框 很常用的

**Comment by andydotxyz** [comment]
Google translate:
Title:
I didn't find any common dialogs for opening files, selecting colors, and selecting fonts.
Comment:
I have not found any common dialogs such as opening files, selecting colors, and selecting fonts. Especially the file selection dialog is very common

**Comment by andydotxyz** [comment]
Yes, these do not exist yet. Some individual tickets have been added including #225.
I have proposed to add the file dialogs at least in 1.2 which we will start work on in July.

**Comment by andydotxyz** [comment]
File dialogs now on develop branch for testing

**Comment by stuartmscott** [comment]
Color Picker in progress: #1300

**Comment by andydotxyz** [comment]
I am going to close this as complete.
Font selection is a complex topic and relates to theming and customisation in discussion elsewhere.
Adding a font selector dialog at this time would provide no benefit to users/developers as they cannot be used.
