### ISSUE TITLE
macOS Monterey - File Open in demo leads to endless loop

### ISSUE THREAD

**Issue by carlca** [fyne-io/fyne#2824]
When I run the demo app under macOS 12.2 Monterey on a Mac Mini M1, I find that when I click the menu option for "File Open", I get a macOS dialog asking me to allow access to files in my Documents folder. When I answer yes, The same thing happens again and again.

![Screenshot 2022-03-06 at 15 40 38](https://user-images.githubusercontent.com/260612/156930363-fdfe688b-6e8f-479b-a149-bb506555c21a.png)

 - macOS
 - 12.2
 - go1.18beta2
 - Fyne 2.1.3

**Comment by andydotxyz** [comment]
How many times does this happen. In the text you say "Documents" but the screenshot says "Desktop" Are you sure it's not just iterating through 4 or 5 shared folders that have security checks behind them?

**Comment by carlca** [comment]
I've just tried it again. The pattern is exactly the same each time. It starts off referencing `Documents`, then `Downloads`, then `Desktop`. It repeats this pattern 4 times before referring to `Documents` and `Downloads` each 1 more time, but finally opening the dialog.

This is occurring for all file operations: `File Open With Filter (.jpg or .png)`, `File Save` and 'File Open'.

As you can imagine, my `Documents` and `Downloads` folders are in constant use, not so much my Desktop. I've not noticed anything similar from any other applications, so I wouldn't have thought there were any security checks set up on them...

**Comment by carlca** [comment]
As a temporary measure I changed the permissions of my `Documents`, `Downloads` and `Desktop` folders to `Read`, `Write` and `Execute` for all user types, `Owner`, `Group` and `Everyone`. Still the same results...

**Comment by andydotxyz** [comment]
Ah sorry, permissions is not quite the right thing - the OS has additional security checks.
Some have reported that going to the privacy section, finding the named app and removing all reference and starting it afresh has helped - can you try that?

**Comment by carlca** [comment]
Thanks for that! I went into System Preferences and unchecked the 3 relevant options. 

![Screenshot 2022-03-06 at 19 46 50](https://user-images.githubusercontent.com/260612/156939641-ecd0eea8-775b-47f7-942f-5b39439251ae.png)


When I ran the demo, I had to grant the options as before. I then went back into System Preferences and saw that the 3 items had been re-checked. I then ran the demo again, hoping that it would work. Sadly not...

**Comment by andydotxyz** [comment]
Hmm, thanks for this.

Perhaps it relates to how the app is being run... Is this a packaged app (using "fyne package") or from a command-line execution?

**Comment by leofigy** [comment]
Right, that's the expected behavior, the restriction is being applied to your shell where you invoke the demo app 
because it's trying to access a protected folders.

<img width="1331" alt="Screen Shot 2022-03-23 at 16 16 03" src="https://user-images.githubusercontent.com/49299001/159805263-56b6d76b-19aa-41d4-843a-d4cdc11628cf.png">

**Comment by andydotxyz** [comment]
I don't know how this happened but it got fixed by clearing some config, so the issue seems like it may relate to the terminal or some stale state.

Unless there are strong feelings otherwise I'd consider this not an issue in Fyne.
