### ISSUE TITLE
Card widget expands to its maximum height

### ISSUE THREAD

**Issue by arma7x** [fyne-io/fyne#2825]
### Describe the bug:
Card widget expands to its maximum height

### To Reproduce:
Steps to reproduce the behaviour:
1. Clone https://github.com/mudler/edgevpn-gui & build
2. Then add new VPN

### Screenshots:
https://i.imgur.com/CrPDySf.png
Expected result: https://user-images.githubusercontent.com/2420543/147854904-09d96991-8752-421a-a301-8f0bdd9d5542.png

### Example code:
1. https://github.com/mudler/edgevpn-gui/blob/master/gui/dashboard.go#L151-L175
2. https://github.com/mudler/edgevpn-gui/blob/master/gui/dashboard.go#L66-L72
3. https://github.com/mudler/edgevpn-gui/blob/master/gui/vpn_ui.go#L264

### Device (please complete the following information):
 - **OS:** Lubuntu 
 - **Version:** 18.04.6 LTS
 - **Go version:** go1.17.7 linux/amd64
 - **Fyne version:** v2 v2.1.2

**Comment by arma7x** [comment]
https://github.com/mudler/edgevpn-gui/issues/2

**Comment by Jacalz** [comment]
Can you please produce a minimum code example that reproduces this issue? With large code bases like these, there are a lot of factors that can go wrong. It would make things much easier for us to reproduce.

**Comment by arma7x** [comment]
https://go.dev/play/p/U8p2vsjvMkH

**Comment by Jacalz** [comment]
Thanks a lot 👍

**Comment by andydotxyz** [comment]
This is correct - all widgets will expand to the full height given to them.
If you want something to shrink to MinSize vertically then you can wrap it in a `container.NewVBox` which is designed to do just that.

**Comment by arma7x** [comment]
@andydotxyz like this _container.NewVBox(Card)_ ?

**Comment by arma7x** [comment]
Thanks, solve by container.NewVScroll(container.NewVBox(container.NewAdaptiveGrid()))
