### ISSUE TITLE
TappedSecondary for widget.List items make them not to render

### ISSUE THREAD

**Issue by e1fueg0** [fyne-io/fyne#2828]
### Is your feature request related to a problem? Please describe:

I create a list with the content as follows:
```golang
	list := widget.NewList(
		func() fyne.CanvasObject {
			return container.NewBorder(nil, nil, widget.NewCheck("", func(bool) {}),
				nil, canvas.NewText("", color.White))
		},
```
and I want the whole list item area to process TappedSecondary.

So I rewrote the list to be created as follows:
```golang
	list := widget.NewList(
		func() fyne.CanvasObject {
			return newListItem(container.NewBorder(nil, nil, widget.NewCheck("", func(bool) {}),
				nil, canvas.NewText("", color.White)))
		},
...

type listItem struct {
	fyne.CanvasObject
}

func (b *listItem) TappedSecondary(e *fyne.PointEvent) {
	widget.ShowPopUpMenuAtPosition(
		fyne.NewMenu("", fyne.NewMenuItem("Copy", func() { fmt.Println("context menu copy") })),
		fyne.CurrentApp().Driver().CanvasForObject(b), e.AbsolutePosition)
}

func newListItem(si fyne.CanvasObject) *listItem {
	i := &listItem{CanvasObject: si}
	return i
}

```

and now, though the context menu works well, the items don't render at all.

I investigated the source code (not too deeply) and I doubt whether this is a bug, or a feature. Mb I'm doing something wrong. Is there a way to get the desired behavior?

### Is it possible to construct a solution with the existing API?

I didn't find any.

### Describe the solution you'd like to see:

I want both the context menu to work, and the list items to render.

**Comment by andydotxyz** [comment]
You're extending an empty object here, there is nothing to render.
We only support extending Widgets - the generic CanvasObject or Container cannot be extended in this way (as you say, there is nothing to see).
So you could make a custom widget, or you could add an overlay like the one you created over the content using `container.NewMax(items, overlay)`.
