### ISSUE TITLE
FolderOpenDialog prints error msg when open disk C

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2838]
### Describe the bug:
I create a FolderOpenDialog and open disk C where OS is installed, then i found some errors printed by fyne.
```
2022/03/10 11:51:52 Fyne error:  Error getting file attributes 
2022/03/10 11:51:52   Cause: The process cannot access the file because it is being used by another process. 
2022/03/10 11:51:52   At: C:/Users/app/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/dialog/file_windows.go:78           
2022/03/10 11:51:52 Fyne error:  Error getting file attributes                                               
2022/03/10 11:51:52   Cause: The process cannot access the file because it is being used by another process. 
2022/03/10 11:51:52   At: C:/Users/app/go/pkg/mod/fyne.io/fyne/v2@v2.1.2/dialog/file_windows.go:78         
```
After debugging and reproduce, I found this error is due to accessing the system file in disk C, such as ```C:/pagefile.sys``` which is used by Windows.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the code below
2. Click on C: 

### Example code:
```go
func main() {
	myApp := app.NewWithID("go-fyne")

	myWindow := myApp.NewWindow("Widget")
	btn := widget.NewButton("Go", func() {
		fo := dialog.NewFolderOpen(func(uri fyne.ListableURI, err error) {
			if uri != nil {
				fmt.Println(uri.Path())
			}
		}, myWindow)
		fo.Show()
	})

	content := container.NewVBox(
		widget.NewEntry(),
	)

	myWindow.Resize(fyne.NewSize(800, 600))
	myWindow.SetContent(container.NewBorder(btn, nil, nil, nil, content))
	myWindow.CenterOnScreen()
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows10
 - **Version:** 19044
 - **Go version:** go1.17.5
 - **Fyne version:** 2.1.3

**Comment by Jacalz** [comment]
Does this happen when you click on the C drive, or when selecting a specific file? Or is it for all files on the drive?

If the error comes when selecting a file like the one mentioned above (sounds like something used by the system), it seems fair that it would give that error if it being used somewhere else.

**Comment by BabySid** [comment]
Yes. That's true. At present, it will happen only when the C disk is opened. Because this system file is located in Disk C, it will not happend for other disks or directories.

What puzzles me is that the file browser of the system or other software will not print such errors. Do they hide such errors?

I don't know.

Just personally, I like to keep the 0 error mode. It may be the habit of code cleanliness. :)

**Comment by Jacalz** [comment]
Do you get the same error when just opening the file using the regular `os.Open()` function? If so, I’d suggest filing an issue with the Go compile instead.

**Comment by BabySid** [comment]
I get the same error with the code below. 
```
panic: open c:/pagefile.sys: The process cannot access the file because it is be
ing used by another process.

goroutine 1 [running]:
main.main()
        D:/projects/go/src/demo/run.go:8 +0x57

Process finished with the exit code 2

```

```go
package main

import "os"

func main() {
	f, e := os.Open("c:/pagefile.sys")
	if e != nil {
		panic(e)
	}
	f.Close()
}
```

**Comment by Jacalz** [comment]
Thanks for confirming. I'll say then that the issue doesn't lie with us. If you want to go through with it, I'd suggest instead opening an issue at https://github.com/golang/go. I'm not entirely sure how much they can do much about it either though, but I must admit that it's strange that only Go complains.

**Comment by jwill0182** [comment]
I got the same the behavior. Question: Is there any possibility to catch the terminal output and pump it into a logfile?

**Comment by andydotxyz** [comment]
Absolutely - you can do anything you want with stdout either using terminal redirect or the Go `os.StdOut` Writer...

**Comment by jwill0182** [comment]
Could you please provide me some line of code how to catch the terminal output of `"fyne.io/fyne/v2/dialog"` ?

**Comment by andydotxyz** [comment]
It's like I said before you just need to work with `os.StdOut` like any other logger/output...

```go
W := newMyWriter()
os.StdOut = w
os.StdErr = w
```

**Comment by jwill0182** [comment]
All sent outputs to terminal e.g. via fmt.println command are perfectly well piped and can be red in over ioutil.ReadAll() except the outputs of file_dialog. Do you still have any solution or at least a hint? 

`old := os.Stdout
r, w, _ := os.Pipe()
os.Stdout = w
os.Stderr = w

fmt.Println("Hello, playground") // this gets captured
file_dialog = dialog.NewFolderOpen(func(uri fyne.ListableURI, err error) {}, pMyWindow) //this doesn´t get captured
w.Close()

out, _ := ioutil.ReadAll(r)
os.Stdout = old

tmp := string(out[:])

M.Log.Println("Captured:" + tmp) // prints: Captured: Hello, playground`

**Comment by Jacalz** [comment]
I would like to point out that this is the wrong place to have the discussion. It would be better to move the discussion somewhere else as it isn't related to the issue above.
