### ISSUE TITLE
Button icons do not center align if button label is empty string

### ISSUE THREAD

**Issue by jamhales** [fyne-io/fyne#284]
Buttons with icons will only stay center aligned/justified if the button label is not an empty string.

With Labels:

![buttonsGood](https://user-images.githubusercontent.com/51208313/58650178-f74d5580-82db-11e9-93c6-691efe377e0b.jpg)

And without Labels:

![buttonsBad](https://user-images.githubusercontent.com/51208313/58650191-0207ea80-82dc-11e9-93e2-9bae295d88bf.jpg)

Here's the code to reproduce:
```go
package main

import (
    "fyne.io/fyne"
    "fyne.io/fyne/app"
    "fyne.io/fyne/layout"
    "fyne.io/fyne/theme"
    "fyne.io/fyne/widget"
)

func main() {
    a := app.New()

    w := a.NewWindow("")

    btn01 := widget.NewButtonWithIcon("", theme.ContentClearIcon(), nil)
    btn02 := widget.NewButtonWithIcon("", theme.ContentCutIcon(), nil)
    btn03 := widget.NewButtonWithIcon("", theme.ContentPasteIcon(), nil)

    container := fyne.NewContainerWithLayout(layout.NewGridLayout(3), btn01, btn02, btn03)

    w.SetContent(container)
    w.ShowAndRun()
}
```

**Comment by okratitan** [comment]
We are currently deciding on the implementation of an IconButton that has no text and only has an icon that stretches to fill the entire button.  I think this is what would work for your use case the best.  Though the icon should still probably center in this case when there is no text.
