### ISSUE TITLE
widget.NewListWithData don't refresh when the same len of data is updated

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2843]
### Describe the bug:
As the title describes, I use widget.NewListWithData and bind a array to the list,  when i set new value which has the same length with the old one to the binding array, the list does't update unless i call the list.Refresh() method.
After I debug the code, I found the info below, I hope it can be helpful for fyne-authors to analyze and solve problems
```go
func (l *boundStringList) doReload() (retErr error) {
    ...
    err = item.(*boundStringListItem).doSet((*l.val)[i])
    ...
}
...
func (b *boundStringListItem) doSet(val string) error {
	(*b.val)[b.index] = val

	b.trigger() // here.  len(b.listeners) == 0, Maybe that's the reason for the problem
	return nil
}
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the code below

### Screenshots:
![图片](https://user-images.githubusercontent.com/6658943/158025227-09ffdc66-9969-482b-8af1-8221fdf89e15.png)

### Example code:
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
	"math/rand"
	"os"
	"time"
)

func main() {
	rand.Seed(time.Now().UnixNano())

	myApp := app.NewWithID("go-fyne")
	myWindow := myApp.NewWindow("Widget")

	data := binding.NewStringList()

	list := widget.NewListWithData(
		data,
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			txt, _ := i.(binding.String).Get()
			o.(*widget.Label).SetText(txt)
		})

	btn := widget.NewButton("Go", func() {
		strs := make([]string, 5)
		for i := 0; i < 5; i++ {
			strs[i] = fmt.Sprintf("%d", rand.Intn(100))
		}
		data.Set(strs)
		fmt.Println(data.Get()) // here I print the data and It was found that the data was indeed updated

		//list.Refresh()
	})

	myWindow.Resize(fyne.NewSize(800, 600))
	myWindow.SetContent(container.NewBorder(
		btn, nil, nil, nil, list,
	))
	myWindow.CenterOnScreen()
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows10
 - **Version:** 19044
 - **Go version:** go1.17.5
 - **Fyne version:** 2.1.2

**Comment by andydotxyz** [comment]
When you use ListWithData the items can be updated directly. When the length has not changed there is no need for the list to update. Your code is accidentally ignoring these per-item changes because you are not using the data passed in to the update function completely.

Replace 
```
		func(i binding.DataItem, o fyne.CanvasObject) {
			txt, _ := i.(binding.String).Get()
			o.(*widget.Label).SetText(txt)
		})
```
with
```
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})
```
That way your label will update when the individual data items change.

**Comment by BabySid** [comment]
Thank you for your correction.

One more question, in my application, the type of list element is a widget.hyperlink, and this class does not find the bind method. Does i have to call list.Refresh()?

**Comment by andydotxyz** [comment]
> One more question, in my application, the type of list element is a widget.hyperlink, and this class does not find the bind method. Does i have to call list.Refresh()?

Ah, no we missed that. There is no URL binding type yet. It could use the URI binding but that would probably be a bit strange.
In the meantime instead of bind directly you can do `i.(binding.String).AddListener` and then you can do the appropriate `Get` code when the callback runs. Remember of course to `RemoveListener` if you are about to re-use - widgets would normally take care of this so you might have to maintain some reference, sorry.

**Comment by BabySid** [comment]
Thanks very much~

But it sounds a little complicated. I still call list.Refresh() for the time being. This is at least relatively simple when the amount of data is small, the performance is acceptable. A similar problem is that when there are many components in the list (such as label, button，hyperlist...),  i have not found similar examples to bind so many components. I expect fyne to support more complex components-binding in the future.

**Comment by BabySid** [comment]
Problem has resolved. close this issue.

**Comment by andydotxyz** [comment]
> This is at least relatively simple when the amount of data is small, the performance is acceptable

When the data grows it will not get slower, as we only refresh what is visible.

> I expect fyne to support more complex components-binding in the future.

Yes we are planning to extend Table/List/Tree to support multiple different rows/cells etc. It is tough to do whilst maintaining the performance!

**Comment by xujieqiang** [comment]
I  run the program with your code ,   the program start  and  refresh data by push the button . It  does not have problem.  
my code is below:
`package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

var sss = binding.NewStringList()

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Simple")
	w.Resize(fyne.NewSize(800, 700))

	temp := []string{"aaa", "bbbb", "ccccc"}
	sss.Set(temp)

	//var allw []fyne.CanvasObject
	source, _ := sss.Get()

	cc := widget.NewListWithData(sss, func() fyne.CanvasObject {
		return widget.NewLabel("")
	}, func(di binding.DataItem, co fyne.CanvasObject) {
		txt, _ := di.(binding.String).Get()
		co.(*widget.Label).SetText(txt)
	})
	for _, val := range source {

		fmt.Println(val)

	}

	kk := widget.NewButton("ok", func() {
		ttt := []string{"good  ", "=====>", "bad", "lucy"}
		Change(ttt)
	})

	content := container.NewBorder(nil, kk, nil, nil, cc)
	w.SetContent(content)
	w.ShowAndRun()
}

func Change(st []string) {
	sss.Set(st)
}
`
