### ISSUE TITLE
Nothing happens when running the example

### ISSUE THREAD

**Issue by WhyNotHugo** [fyne-io/fyne#2849]
### Describe the bug:

The example does nothing. No window, no stdout, nothing.

### To Reproduce:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

```sh
go mod init gui
go mod tidy
go run main.go
```

### Screenshots:

Nothing. No window, stdout says nothing.

### Device (please complete the following information):
 - **OS:** Linux 5.16.12-arch1-1 GNU/Linux
 - **Go version:** go version go1.17.8 linux/amd64
 - **Fyne version:** v2.1.3

**Comment by WhyNotHugo** [comment]
Ah, just needed to be patient! Thanks!

**Comment by andydotxyz** [comment]
Yeah, first time build can take a few minutes as it’s a lot of code. Future builds will all be pretty quick
