### ISSUE TITLE
Wayland Scaling support: sizes and distances are scaled wrong

### ISSUE THREAD

**Issue by WhyNotHugo** [fyne-io/fyne#2850]
### Describe the bug:

I'm using desktop scaling, and elements and distances are not scaled correctly. The mouse cursor is also twice the regular size.

Hovering and clicking on items does not work correctly. To click on a button one must click in a very different position (as far as I can tell, the position where the button WOULD be if the window is scale properly).

However, because rendering and mouse events aren't consistent, UIs are entirely unusable with a mouse.

### To Reproduce:

On a desktop with scaling enabled, run the example code (see below).

### Screenshots:

With scaling:

![image](https://user-images.githubusercontent.com/730811/158333009-13852074-9c30-4e83-96fc-c18bddd1ea3d.png)

The same sample ran via XWayland, where scaling is not done by the client. the compositor stretches the image instead (hence the blurryness):

![image](https://user-images.githubusercontent.com/730811/158333468-87ea2cbf-76ee-44e7-ac1a-4eadb82b93e6.png)

### Example code:

Use `go run -tags wayland ./main.go`:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** `Linux 5.16.12-arch1-1 GNU/Linux`
 - **Go version:** `go version go1.17.8 linux/amd64`
 - **Fyne version:** v2.1.3

I'm using `swaywm` as a wayland compositor. I haven't tried GNOME.

**Comment by andydotxyz** [comment]
> On a desktop with scaling enabled, run the example code (see below).

Because of how fragmented Linux is we would need more information. Can you please be specific about how the settings are found, and applied?

**Comment by WhyNotHugo** [comment]
It's part of the core Wayland protocol. The compositor will announce the scaling factor for an output using [`wl_output::scale`](https://wayland.app/protocols/wayland#wl_output:event:scale).

Looking at the logs, it seems that my sample code above actually receives the event, and replies indicating that its surface will have scaling applied by using [`wl_surface::set_buffer_scale`](https://wayland.app/protocols/wayland#wl_surface:request:set_buffer_scale):

```console
$ WAYLAND_DEBUG=1 go run -tags wayland ./main.go 2>&1 | grep scale
[4188969.808] wl_output@15.scale(2)
[4189209.683]  -> wl_surface@21.set_buffer_scale(2)
```

Configuring the scaling factor is compositor-specific. I believe GNOME and KDE have a GUI for that. I can't find any documentation for either online so can't provide better pointers. [Sway uses the `output WL-1 scale 3` command](https://man.archlinux.org/man/sway-output.5).

Sway can be run nested inside another compositor, so might be a better target for experimentation.

**Comment by andydotxyz** [comment]
Thanks this is very helpful. I guess our wayland code does not pick it up yet, as we use the older X11 based DPI detection to get the appropriate scale.

**Comment by metal3d** [comment]
see #2897 for my solution

**Comment by andydotxyz** [comment]
Fixed on `develop`

**Comment by nickjwhite** [comment]
Just tested, works great and looks *so* much better on HiDPI screens on Wayland now, great job!

**Comment by andydotxyz** [comment]
Excellent, thanks for checking :)
