### ISSUE TITLE
Checked menu items are not creatable in an unchecked state

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#2851]
This is related to #1975. The way it is implemented, a checkable menu item can not be created in a non-checked state; that is, "Is a checkable menu item" == "Is in a checked state".  

### Is your feature request related to a problem? Please describe:
I would like to be able to create menus with checkable menu items with *initial* unchecked states. 

### Is it possible to construct a solution with the existing API?
The work-around is to create the UI, render it (with `ShowAndRun()`) and *then* uncheck the menu items.

### Describe the solution you'd like to see:
Separation of the quality of being a checkable menu item, and the state of whether or not the item is checked.

**Comment by xxxserxxx** [comment]
This may be a completely separate issue, and if so I'll file a separate ticket, but the checked menu items aren't uncheckable; I've tested this in the fyne_demo as well.

**Comment by andydotxyz** [comment]
Can you be more specific about the code that is not working?
In Fyne menus a checked item is checked, a regular item is not checked.
There isn't a "checkable not checked" item... items that should toggle do so in code when clicked.

**Comment by andydotxyz** [comment]
P.S. this sounds like a bug report, but you've used the feature request template, so it does not have any of the usual info about reproduction steps, versions etc that would really help to understand the problem.

**Comment by xxxserxxx** [comment]
I'm going to explain this for other people finding it; close it; then open a new request.

It boils down to the fact that to update menus, you have to call `window.SetMainMenu()` again; there's no other way to trigger a refresh. Changing text, changing checked status... any attribute changes can only be refreshed by calling `SetMainMenu()` again.

*All* `MenuItems` are potentiially check-able. To make them checked, you set `item.Checked = true`, usually in the menu item callback in response to a user event. You then have to re-add the main menu to the window, so the closure has to keep track of those as well.

Example code:

```go
var window *fyne.Window
var mainMenu *fyne.MainMenu
var item *fyne.MenuItem
item := fyne.NewMenuItem("Check-able", func() {
    // Toggle the check-mark; it's hidden (not a check-box, just a check) unless this
    // attribute is true
    item.Checked = !!item.Checked
    // This is how to refresh any menu changes
    window.SetMainMenu(mainMenu)
})
mainMenu = fyne.NewMainMenu(fyne.NewMenu("File", item))
window.SetMainMenu(mainMenu)
```

Hopefully this will clarify this aspect of menus.
