### ISSUE TITLE
storage.List() returns list with nil elements for empty directories

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#2858]
On Android, calling storage.List() on an empty directory returns a nil error and a list with one element, which is nil.

A compilable bug report is in https://github.com/xxxserxxx/fynelistbug

### Device (please complete the following information):
 - **OS:** Android
 - **Version:** Confirmed on Samsung Android 12 and an emulator with android-32
 - **Go version:** go1.18
 - **Fyne version:** v2.1.4

**Comment by andydotxyz** [comment]
I think this should have been fixed by `3e3183b`
