### ISSUE TITLE
Problem displaying some svg files

### ISSUE THREAD

**Issue by Bl4cksunLtd** [fyne-io/fyne#2864]
### Describe the bug:

Displaying a number of svg images from the internet within a fyne app, most display without issue, some produce errors on the console but display without issue others produce an error on the console and produce no image on screen.
Error logged is as follows:
Fyne error:  SVG Load error:
Cause: Param mismatch
At: /src/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/painter/image.go:78

### To Reproduce:

svg file attached that generates the error and doesn't display as per the following screenshot.

### Screenshots:

The problem can been seen with horse number 7.
![image](https://user-images.githubusercontent.com/27490959/159343786-cce40238-e860-490c-b275-23f686978baa.png)

### Example code:

```go
silk *canvas,Image
uri,err:=fyne.LoadResourceFromURLString("http://176.58.114.32:8091/silks?s=60859")
if err==nil	{
	silk.Resource=uri 
}	else 	{
	log.panic(" ParseURI failed ",err, " Setting to NR")
}
			
```

### Device (please complete the following information):
 - **OS:**  Windows 
 - **Version:** 10 
 - **Go version:**  1.17.7 windows/amd64
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
Can you please attach the images @Bl4cksunLtd ? The URLs are not working any more.
Or inline the SVG content perhaps?

**Comment by Bl4cksunLtd** [comment]
![303722](https://user-images.githubusercontent.com/27490959/166282921-3e1e1f59-558d-4e20-ab4c-a5a2f22e28d3.svg)
svg file that generates the error and doesn't display.

**Comment by Bl4cksunLtd** [comment]
Further updates, I looked further into the files and it looks like there is a problem with them. Although they display correctly in the few svg viewers I've tried, including chrome, the image displayed is not 100% correct. However, fyne just rejects the file completely.

**Comment by cedy** [comment]
Here is were we have error by oksvg [https://github.com/srwiley/oksvg/blob/master/path_cursor.go#L221](https://github.com/srwiley/oksvg/blob/master/path_cursor.go#L221) , because provided svg has incorrect element
```svg
<path fill="#ffff00" stroke="none" d="hoop"/>
```
d value is incorrect and nowhere in svg specs I could find that coordinates could be described as words

To be able to display svgs with such bad elements, we need to have support of ignoring such errors in oksvg. I've created PR for that there [https://github.com/srwiley/oksvg/pull/39](https://github.com/srwiley/oksvg/pull/39)
Then update dependency & add option of `oksvg.WarnErrorMode` here [https://github.com/fyne-io/fyne/blob/master/internal/svg/svg.go#L46](https://github.com/fyne-io/fyne/blob/master/internal/svg/svg.go#L46
)

**Comment by Jacalz** [comment]
Nicely done @cedy 👍

**Comment by cedy** [comment]
Thank you @Jacalz! This was interesting bug to fix 😃

**Comment by andydotxyz** [comment]
Thanks to @cedy this should now be fixed on `develop` ready for `v2.3.0` later this year.

**Comment by mrusme** [comment]
I seem to be experiencing a similar issue with the following SVG file:

```xml
<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><rect x="32" y="128" width="448" height="320" rx="48" ry="48" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/><path d="M144 128V96a32 32 0 0132-32h160a32 32 0 0132 32v32M480 240H32M320 240v24a8 8 0 01-8 8H200a8 8 0 01-8-8v-24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>
```

```
2026/02/05 21:54:29 Fyne error:  Failed to load image
2026/02/05 21:54:29   Cause: param mismatch
2026/02/05 21:54:29   At: ~/.go/pkg/mod/fyne.io/fyne/v2@v2.7.2/canvas/image.go:147
```

The SVG in question is downloaded from [here](https://ionic.io/ionicons).

**Comment by andydotxyz** [comment]
Please open a new issue @mrusme, this one was resolved and closed.
