### ISSUE TITLE
Text entry widget not filling the horizontal space

### ISSUE THREAD

**Issue by wizche** [fyne-io/fyne#2866]
### Describe the bug:
Text entry widget is not taking the whole space when inside a `NewHBoxLayout` with a label.

### To Reproduce:
1. Use the given layout
2. Run the application
3. Text entry is too small, it should fill the horizontal space

### Screenshots:
![image](https://user-images.githubusercontent.com/1062939/159790802-e89683b4-b4a2-4b4c-b5a8-fd35b3b0fa7b.png)

### Example code:
Following layout results in the contentTypeEntry being very small (see screenshot). Kind of a workaround, disabling text wrapping with `TextWrapOff` makes the entry field fit the size of the string.

```go
	myApp := app.New()
	myWindow := myApp.NewWindow("Network Simulator")

	httpResponse := widget.NewMultiLineEntry()
	httpResponse.SetPlaceHolder("Put your response body here")
	httpResponse.SetText("@_@")

	statusCodeSelect := widget.NewSelect([]string{"200", "400", "404", "500"}, func(value string) {
		log.Println("Status code set to", value)
	})
	statusCodeSelect.SetSelectedIndex(0)

	contentTypeEntry := widget.NewEntry()
	contentTypeEntry.SetText("text/html")

	content := container.New(
		layout.NewGridLayoutWithRows(2),
		container.New(
			layout.NewGridLayout(2),
			widget.NewLabel("Trigger"),
			container.New(
				layout.NewVBoxLayout(),
				widget.NewLabel("Default Response"),
				container.New(
					layout.NewHBoxLayout(),
					widget.NewLabel("Status Code"),
					statusCodeSelect,
				),
				container.New(
					layout.NewHBoxLayout(),
					widget.NewLabel("Content-Type"),
					contentTypeEntry,
				),
				widget.NewLabel("Body"),
				httpResponse,
			),
		),
		container.New(
			layout.NewGridLayout(2),
			generateDnsRequestLayout(&appState),
			generateHttpRequestLayout(&appState, myWindow),
		))

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
```

### Device 
 - **OS:** Linux (Debian)
 - **Version:** Debian Bullseye
 - **Go version:** 1.18
 - **Fyne version:** 2.1.4

**Comment by Jacalz** [comment]
This is actually working as intended. The HBox (and VBox) layouts are designed to shrink their contents to their MinSize. When you have no wrapping, it basically has to account for all the text inside the entry but with it enabled, you can scroll and it thus doesn’t need to account for it. The solution here is to choose a different layout that expands content, such as a BorderLayout and perhaps combine that with something else as needed.

I would suggest having a look at this talk about layouts: https://www.youtube.com/watch?v=LWn1403gY9E

**Comment by wizche** [comment]
Thanks a lot @Jacalz , 
I choose a Form layout and it work as intended. Thanks for the video suggestion, will check it out!

**Comment by woohsi** [comment]
<img width="685" alt="image" src="https://github.com/user-attachments/assets/a3dc3525-0b23-4120-ab7a-875344c7ce39" />

Instead of HBox Layout:

```
container.New(
	layout.NewHBoxLayout(),
	widget.NewLabel("Content-Type"),
	contentTypeEntry,
),
```

What you need is Border Layout:

```
container.NewBorder(
	nil,
	nil,
	widget.NewLabel("Content-Type"),
	nil,
	contentTypeEntry,
),

```
