### ISSUE TITLE
Error occurred when fyne package into a windows binary file

### ISSUE THREAD

**Issue by CloudLasting** [fyne-io/fyne#2868]
### Describe the bug:

`fyne package -os windows`
```
# runtime/cgo
gcc_libinit_windows.c:8:10: fatal error: 'windows.h' file not found
```

### Screenshots:
<!-- If applicable, add screenshots or gifs to help explain your problem. --
<img width="482" alt="image" src="https://user-images.githubusercontent.com/11511934/160054905-0825f69c-4ecc-466c-9365-ef74f89d6df3.png">

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.3
 - **Go version:** 1.18
 - **Fyne version:** 2.1.4

**Comment by hutiquan** [comment]
CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 fyne package -os windows，You need to splice environment variables first.
