### ISSUE TITLE
Size reduction on minSize change

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#288]
While #280 fixed the adjustments to a growing minSize, reducing the minSize of an objects still leads to missing refreshes of the container.

If the shrinking widget is part of a box, there is empty space up to the next refresh of the box.
If this box is in a scroll container, the refresh will happen on the next scroll.

I think the fixes made in #280 can be extended to handle this case, too. But this probably requires a `minSizeChanged` flag on the canvas object.

**Comment by andydotxyz** [comment]
Is this resolved on develop now?

**Comment by toaster** [comment]
fixed by #308
