### ISSUE TITLE
widget.Select truncates option

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2881]
### Describe the bug:
As the title describes, when widget.Select is shown, it's option cannot be displayed completely.
As the comment in the code shows: 
- At present, the options can only be displayed completely only if Select.PlaceHolder is set.

Is it better for widget.Select to automatically select the longest option element?

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the code below

### Screenshots:
![图片](https://user-images.githubusercontent.com/6658943/160878837-8d05ff7f-b5f3-420b-9e54-4aef5cd45959.png)

### Example code:
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	sel := widget.NewSelect([]string{
		"2006-01-02 15:04:05",
		"2006/01/02 15:04:05",
		"2006-01-02",
		"2006/01/02",
		"15:04:05",
	}, nil)
	//sel.PlaceHolder = sel.Options[0]
	sel.SetSelectedIndex(0)

	btn := widget.NewButton("Test", func() {
		fmt.Println(sel.SelectedIndex())
	})

	add := widget.NewButton("Add", func() {
		sel.Options = append(sel.Options, "2006-01-02 15:04:05.000")
		//sel.PlaceHolder = "2006-01-02 15:04:05.000"
	})

	w.SetContent(container.NewBorder(sel, container.NewHBox(btn, add), nil, nil, layout.NewSpacer()))

	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** windows10
 - **Version:** 19044
 - **Go version:** 1.17.5
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
> Is it better for widget.Select to automatically select the longest option element?

It used to, but the behaviour was not desirable as the options could be very, very long.
If you want it to take more space you can make changes in the parent layout to allocate the space.
