### ISSUE TITLE
widget.Form do not show buttons even if OnSubmit is not nil

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2882]
### Describe the bug:
As the following code shows, if param of NewForm is empty, the button(Submit) will not be shown.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the code below

### Screenshots:
![图片](https://user-images.githubusercontent.com/6658943/160881041-b8e4b3e8-48ce-4c15-83d9-dcaed479bc15.png)

### Example code:
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	f := widget.NewForm()
	f.Append("Item1", widget.NewEntry())
	f.Append("Item2", widget.NewEntry())
	f.OnSubmit = func() {
		fmt.Println("submit")
	}

	w.SetContent(
		container.NewBorder(nil, nil, nil, nil, f))

	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 19044
 - **Go version:** 1.17.5
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
If you change the fields of a widget directly (i.e. using `thing.Property = ...`) you need to call `Refresh()`. Helpers such as `SetText(...)` would do this for you.
Calling refresh fixes the issue in my testing. Alternatively set `OnSubmit` before appending - as those helper methods will refresh the form.
