### ISSUE TITLE
widget.SelectEntry support filter-option

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2887]
### Is your feature request related to a problem? Please describe:
When entering text in the entry of SelectEntry, if the content matches the option, I hope pop up the option-menu automatically. 
At present, I still need to click the drop-down button on the right to select, which is not convenient for users to use.

### Is it possible to construct a solution with the existing API?
No.
because the member popUp is private.  The only way is to re implement this component.

### Describe the solution you'd like to see:
I prefer SelectEntry to provide a method like `ShowPopUp()` to let user decide when to show the popup.

Of course, it would be better if SelectEntry supports filter-option via a control-option

**Comment by BabySid** [comment]
Yes, This component seems to meet my needs. But there is a bug: [This component seems to meet my needs](https://github.com/fyne-io/fyne-x/issues/34). :(

**Comment by Jacalz** [comment]
Let’s close this then and try to get the bug fixed there instead :)
