### ISSUE TITLE
support more image formats

### ISSUE THREAD

**Issue by maddin200** [fyne-io/fyne#2888]
could be:

- pbm / pgm
- bmp

**Comment by andydotxyz** [comment]
I'm not sure if such support should be baked into Fyne, as they are not really cross platform formats.
If you have a golang package you can decode an image and load it in as a standard golang image to display within Fyne (like how FyneDesk handles .xmp files).

**Comment by Jacalz** [comment]
I agree with @andydotxyz on this.

I must admit that I see very little point in adding support for image formats that are platform specific or not generally used. If we should add any new image format to the list of supported ones, it should, in my opinion, be one that is part of an ISO standard (or similar), not patent encumbered, provide something that other formats don’t while also being widely used. The only formats that I can think of that match that criteria would be AVIF or HEIF (once they start gaining a little more traction).

**Comment by Arsen6331** [comment]
It is worth noting that there are a lot of image formats not in the standard library that are already implemented in golang.org/x/

BMP: https://pkg.go.dev/golang.org/x/image/bmp
TIFF: https://pkg.go.dev/golang.org/x/image/tiff
WEBP: https://pkg.go.dev/golang.org/x/image/webp
VP8: https://pkg.go.dev/golang.org/x/image/vp8
VP8L: https://pkg.go.dev/golang.org/x/image/vp8
CCITT: https://pkg.go.dev/golang.org/x/image/ccitt

There are more in other repos:

PSD: https://pkg.go.dev/github.com/oov/psd
PBM/PGM/PPM: https://pkg.go.dev/github.com/jbuchbinder/gopnm

There is also Canvas. While that is not an image format, it can render to fyne and can import SVGs and other formats: https://pkg.go.dev/github.com/tdewolff/canvas

And, of course, PNG, JPG, and GIF are in the standard library.

With all these available image formats, I don't think there's any reason to add image formats to fyne itself.

**Comment by maddin200** [comment]
Thanks for help !
