### ISSUE TITLE
Entry displays the check mark when binding a data

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#2889]
### Describe the bug:
In the current fyne implementation, when widget.Entry uses data binding, a check mark will be displayed. 
But from the user's point of view, this will look strange (do I need to pay attention to any format? Or some rules?).
In fact, from the perspective of developers, I understand that this is a implementation mainly to solve the problem of data transmission. This should not be perceived by users.  I think it is not reasonable to show that mark unless there are clear verification rules.

### Screenshots:
![图片](https://user-images.githubusercontent.com/6658943/161374994-5bc137d1-6070-447f-9f6d-6e4bd722be49.png)

**Comment by andydotxyz** [comment]
The validation is turned on by default as binding is able to return conversion errors.
If you want to disable it you can set `Entry.Validator = nil`

**Comment by BabySid** [comment]
Thanks very much. It works.

Close this issue.
