### ISSUE TITLE
Add binding.NewStringWithFormat

### ISSUE THREAD

**Issue by PaulDotSH** [fyne-io/fyne#2890]
### Is your feature request related to a problem? Please describe:
I.e. in my game, I have a word that the user needs to do something with, so I would want to show them something like
"Generated word: $word", instead of just $word

### Is it possible to construct a solution with the existing API?
Shouldn't be very hard to implement since we have the same thing for int and floats

### Describe the solution you'd like to see:
binding.NewStringWithFormat, working similar to binding.NewIntWithFormat

**Comment by Bluebugs** [comment]
Something that might satisfy you need would be binding.NewSprintf that is currently in the developer branch. It take a string like Sprintf, a series of data bindings and provide a string data binding. It will automatically update the content of the string if any of the source data binding change and if the string is set, it will parse it with scanf and update the source data binding accordingly.

You can have a look at https://github.com/fyne-io/fyne/blob/develop/data/binding/sprintf.go#L23 .

**Comment by andydotxyz** [comment]
Good point @Bluebugs - I wonder if `NewStringWithFormat` would be a helpful wrapper for the Sprintf binding that takes a single string, to fit with the FloatWithFormat pattern?

**Comment by Bluebugs** [comment]
@andydotxyz indeed for discoverability and matching developers expectation, might be a good idea to propose `NewStringWithFormat` as a wrapper on top of the Sprintf binding.

**Comment by andydotxyz** [comment]
Resolved with the less attractive but matching name of `StringToStringWithFormat`.
A shorthand could be added but we have no precedent for that...
Will be in v2.2.0
