### ISSUE TITLE
fyne.Container should be canvas.Container

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#290]
The `fyne.Container` should really be a `canvas.Container`.
This has no known (dis)advanteges besides the better package structure.

I propose to copy `fyne.Container` to `canvas.Container` and deprecate the former for removal in 2.0.

**Comment by andydotxyz** [comment]
Thinking more about this I'm not sure I agree. The canvas is full if drawing components that require a driver to implement. Whereas the container is purely logical and works without a driver or rendering...

**Comment by toaster** [comment]
With my proposal on widget/renderer architecture and the further ideas explained there, the container would match the (overhauled) widget interface and could go into `widget`.

**Comment by andydotxyz** [comment]
I'm not sure that `widget` is the right place for it. An app that wishes to just use canvas primitives should not have to import the `widget` package. Without the Container type (or widgets) it is not possible to add more than a single canvasObject to a canvas.

**Comment by andydotxyz** [comment]
I'm not sure where we got to with this one. I think the general consensus was that there's not strong enough reason to move it at this time?
