### ISSUE TITLE
[Mobile] Allow FYNE_SCALE loading 

### ISSUE THREAD

**Issue by Koumbaya** [fyne-io/fyne#2905]
### Is your feature request related to a problem? Please describe:
Maybe I'm wrong, (in which case please do close this) but we can't easily set the FYNE_SCALE for Android so that it is read when creating the main app.
Being able to overload it in the Settings (like the theme) could allow to resize apps (at least on reboot).

### Is it possible to construct a solution with the existing API?
I believe it could be easy, by having an exported function that could save the setting. Or maybe in Preferences since it doesn't seem to be saved ?

### Describe the solution you'd like to see:
A way to setup the scale other than with the env variable.

**Comment by metal3d** [comment]
see #2897 for my solution

**Comment by Koumbaya** [comment]
> see #2897 for my solution

I don't think that works on android. I've tried os.SetEnv on the first line of my main, doesn't work.

**Comment by metal3d** [comment]
Oh sorry, I haven't seen that you speak about Android, I though you were speaking about "OS Settings"

**Comment by changkun** [comment]
Not entirely sure that's needed here. FYNE_SCALE is only supported for desktops at the moment. For mobile, the scaling is defined by default using device DPI:

https://github.com/fyne-io/fyne/blob/master/internal/driver/mobile/device_android.go
https://github.com/fyne-io/fyne/blob/master/internal/driver/mobile/device_ios.go

And it is also not an option for iOS to have the FYNE_SCALE environment variable (did I miss anything?)

If one seeks a way to customize scaling, isn't cmd/fyne_settings an example to show how to do this?

**Comment by Koumbaya** [comment]
> Not entirely sure that's needed here. 
Yeah I'm not sure the env variable is the right way to do it, but anyway making an app and everything being small to the point of being unreadable without a way to scale everything is painful imho :)

**Comment by andydotxyz** [comment]
Apps should not be unreadably small - the font size should match the OS.
If the font is not correct then please open an issue. Defaults should always be appropriate for user configuration on the device.

**Comment by Koumbaya** [comment]
Alright :) Should I close this ?

**Comment by andydotxyz** [comment]
If there is an issue with the scale being wrong this could be re-purposed. But as a feature request it does seem like it was a workaround and probably not needing to stay open.

**Comment by Koumbaya** [comment]
> If there is an issue with the scale being wrong this could be re-purposed. But as a feature request it does seem like it was a workaround and probably not needing to stay open.

yeah, make sense.
