### ISSUE TITLE
Changing the Makefile template to respect freedesktop and local installation

### ISSUE THREAD

**Issue by metal3d** [fyne-io/fyne#2909]
### Is your feature request related to a problem? Please describe:
Looking on the template file:
https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/templates/data/Makefile

There are 2 majors problems if we want to install on Linux inside the "HOME" directory using the freedesktop standard.

Using; `make install PREFIX=~/.local`

1.  the icons is not placed in the freedesktop standard `~/.local/share/icons` directory
2. the `Exec` directive needs to be set with the absolute path to the binary

At this time, installing locally results on a desktop file which is not found in menu or activity menu, and the icon is not set.

### Is it possible to construct a solution with the existing API?
At this time no, I need to fix the Makefile

### Describe the solution you'd like to see:
I can propose 3 solutions as PR:

1. The first one is to respect all condition of freedesktop by using `sed` to replace the `Exec` directive with the absolute path to the binary, and place the icon file in `share/icons` instead of `share/pixmaps`, whatever if we install globally or locally
2. The second solution is to add "user-install" and "user-uninstall" directive (that can be mixed with the third solution below) which decide to install on `~/.local` and place files and make the `sed` commands
3. The second solution is to detect if the PREFIX is set to `~/.local`and make the replacement.
For example, I do this for my "nyrd" application:

```Makefile
# If PREFIX isn't provided, we check for $(DESTDIR)/usr/local and use that if it exists.
# Otherwice we fall back to using /usr.

LOCAL != test -d $(DESTDIR)/usr/local && echo -n "/local" || echo -n ""
LOCAL ?= $(shell test -d $(DESTDIR)/usr/local && echo "/local" || echo "")
PREFIX ?= /usr$(LOCAL)
HOME_INSTALL ?= $(shell [ "$(shell realpath $(PREFIX))" == "$(HOME)/.local" ] && echo "true" || echo "false")

default:
	# For simple users:
	# Run "make install PREFIX=~/.local" to install the application on your home directory.
	# Run "make uninstall PREFIX=~/.local" to uninstall the application on your home directory.
	#
	# Or globally:
	# Run "sudo make install" to install the application.
	# Run "sudo make uninstall" to uninstall the application.

install:
	install -Dm00644 usr/local/share/applications/nyrd.desktop $(DESTDIR)$(PREFIX)/share/applications/nyrd.desktop
	install -Dm00755 usr/local/bin/nyrd $(DESTDIR)$(PREFIX)/bin/nyrd
ifeq ($(HOME_INSTALL),true)
	install -Dm00644 usr/local/share/pixmaps/nyrd.png $(DESTDIR)$(PREFIX)/share/icons/nyrd.png
	sed -i 's,Exec=,Exec=$(HOME)/.local/bin/,' $(DESTDIR)$(PREFIX)/share/applications/nyrd.desktop
else
	install -Dm00644 usr/local/share/pixmaps/nyrd.png $(DESTDIR)$(PREFIX)/share/pixmaps/nyrd.png
endif 

uninstall:
	-rm $(DESTDIR)$(PREFIX)/share/applications/nyrd.desktop
	-rm $(DESTDIR)$(PREFIX)/bin/nyrd
	-rm $(DESTDIR)$(PREFIX)/share/pixmaps/nyrd.png
ifeq ($(HOME_INSTALL),true)
	-rm $(DESTDIR)$(PREFIX)/share/icons/nyrd.png
endif

# we can add this:
user-install:
	$(MAKE) install PREFIX=~/.local

user-uninstall:
	$(MAKE) uninstall PREFIX=~/.local
```

When the solution is accepted, I can of course make a pull request :)

**Comment by metal3d** [comment]
Some precisions:
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

> Icons and themes are looked for in a set of directories. By default, apps should look in $HOME/.icons (for backwards compatibility), in $XDG_DATA_DIRS/icons and in /usr/share/pixmaps (in that order). 

- That means that `~/.local/share/pixmaps` is not used
- And that means that "pixmaps" subdir is the "last one to use".

The best place is, IMHO, the `icons` subdir to place the icons.

That means that the template for Makefiles can only be changed to `sed` the `Exec` attribute to the absolute path. We can put the icon inside the standard `PREFIX/share/icons` directory to make it work for all installation type.

**Comment by Bluebugs** [comment]
I kind of like a solution that detect everything for the user over asking the user to figure more things. It make me lean more toward 3, I guess.

**Comment by Jacalz** [comment]
This sounds like a good improvement. I’d vote for the third option.

**Comment by metal3d** [comment]
Let's go to the third so

**Comment by Jacalz** [comment]
The PR was merged into develop a while ago. Will be in the v2.2.0 release tomorrow if everything goes to plan.
