### ISSUE TITLE
fyne package -os error

### ISSUE THREAD

**Issue by hongbook** [fyne-io/fyne#2916]
### Describe the bug:

fyne package -os linux -icon icon.png
```shell
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
```

fyne package -os windows -icon icon.png
```shell
# runtime/cgo
gcc_libinit_windows.c:8:10: fatal error: 'windows.h' file not found
```

### Device (please complete the following information):
 - **OS:** MacOs
 - **Version:** 11.6.2
 - **Go version:** 1.18
 - **Fyne version:** 2.1

**Comment by Jacalz** [comment]
I suspect that this is the same issue as in https://github.com/fyne-io/fyne/issues/2545. 

Go cannot cross-compile CGo without the proper headers and compilers installed. You might want to use https://github.com/fyne-io/fyne-cross or follow https://developer.fyne.io/started/cross-compiling.

**Comment by andydotxyz** [comment]
Agreed, the environment was missing some information / compiler.
I think we can do better (discussion has started at fyne-io/fyne-cross#107).
Closing as not an issue as @Jacalz suggested, but we will improve it so developers don't have to consult the documentation.

**Comment by andydotxyz** [comment]
Cross-platform packaging is possible, I did not wish to imply that it was not.
If you follow the documentation it should work.

**Comment by Jacalz** [comment]
Cross-platform package is still very much possible, just not without the right compilation toolchain. If the documentation says anything different, we really should fix that.

**Comment by Jacalz** [comment]
You can also use https://github.com/fyne-io/fyne-cross to automate it for you.
