### ISSUE TITLE
problem with table.ScrollToBottom

### ISSUE THREAD

**Issue by dimitrove** [fyne-io/fyne#2918]
When the table is long and only part of it is displayed, then ScrollToBottom works fine.
When the table is short and is displayed in full, then ScrollToBottom fails.

The test bellow works with "go run . 12" and fails with "go run . 4"

```go
package main

import (
	"os"
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"
)

var tableTest *widget.Table
var theApp fyne.App
var theWindow fyne.Window

// -----
func onSomeCellSelected(id widget.TableCellID) {
	tableTest.ScrollToBottom()
}


// ----- main
func main() {
	arg := os.Args[1]
	len, _ := strconv.Atoi(arg)

	theApp = app.New()
	theWindow = theApp.NewWindow("test")
	theWindow.Resize(fyne.NewSize(200, 300))

	data := []string{"00", "01", "02", "03", "04", "05", "06", "07",
		"08", "09", "10", "11", "012", "013", "14", "15"}

	tableTest = widget.NewTable(
		func() (int, int) { return len, 1 },
		func() fyne.CanvasObject {
			return widget.NewLabel("****")
		},
		func(i widget.TableCellID, obj fyne.CanvasObject) {
			// i is index with i.Col and i.Row
			obj.(*widget.Label).SetText(data[i.Row])
		},
	)
	tableTest.OnSelected = onSomeCellSelected

	theWindow.SetContent(container.NewBorder(
		nil, nil, nil, nil, tableTest))
	theWindow.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
I don't understand this part:

`When the table is short and is displayed in full, then ScrollToBottom fails.`

What would the expected outcome be if there is nothing to scroll? In what way is it failing?

**Comment by dimitrove** [comment]
> I don't understand this part:
> 
> `When the table is short and is displayed in full, then ScrollToBottom fails.`
> 
> What would the expected outcome be if there is nothing to scroll? In what way is it failing?

It crashes. It panics.

**Comment by dimitrove** [comment]
Actually, it (the table) asks the provided function for value for a cell with negative row number. Which causes the provided function to crash because of using a negative array index.

**Comment by andydotxyz** [comment]
Ah I see thanks. This is jogging something of my memory but I cannot find an issue.
Can you please confirm that you are on v2.1.4 so we're not missing any fixes?

**Comment by dimitrove** [comment]
> Ah I see thanks. This is jogging something of my memory but I cannot find an issue. Can you please confirm that you are on v2.1.4 so we're not missing any fixes?

Yes, I am on v2.1.4. It looks like the ScrollToBottom tries to place the bottom row at the last visible line. And it calculates the row number for the first visible line. Because the number of rows is less than the number of visible lines, the row number for the first visible line becomes negative.

**Comment by andydotxyz** [comment]
Ah I see, this is a crash from -1? That was not clear from the description.
Can you please include the stack trace from the panic? It will be a lot easier to confirm and fix with that info @dimitrove

**Comment by dimitrove** [comment]
This is it.
[trace.txt](https://github.com/fyne-io/fyne/files/8505829/trace.txt)

**Comment by dimitrove** [comment]
Yes, it works with 2.2.1
