### ISSUE TITLE
SelectEntry cause UI hang

### ISSUE THREAD

**Issue by shvc** [fyne-io/fyne#2925]
### Describe the bug:
Click SeletEntry's dropdown icon cause UI hang.
Manual input or not input(not click dropdown icon) is fine.

### To Reproduce:
Steps to reproduce the behaviour:
1. Select a Value from SelectEntry or just Clict SeletEntry's dropdown icon
2. Click on 'Enter'
3. Click on 'Back'
4. UI hang

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("cc.select")
	w := a.NewWindow("SelectEntry")
	user := widget.NewSelectEntry([]string{"a1", "a2", "a3"})
	var enter, body *fyne.Container
	enter = container.NewVBox(user,
		widget.NewButton("Enter", func() {
			w.SetContent(body)
			w.Resize(fyne.NewSize(200, 100))
			w.Show()
		}),
	)
	top := container.NewHBox(
		widget.NewButtonWithIcon("Back", theme.NavigateBackIcon(), func() {
			w.SetContent(enter)
			w.Resize(fyne.NewSize(300, 180))
			w.Show()
		}),
	)
	body = container.NewBorder(top, nil, nil, nil, top)
	w.SetContent(enter)
	w.Resize(fyne.NewSize(300, 180))
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux, MacOS 
 - **Version:** MacOS11.6.5, and Ubuntu20.04.3 LTS (Focal Fossa)
 - **Go version:** 1.17, 1.18
 - **Fyne version:** v2.1.4

**Comment by andydotxyz** [comment]
The `top` is being passed to Border container twice which does not seem right.
I don’t know if that relates to the problem.
Also not sure why you have window.Show calls - the window must be visible if the button was pressed :)

**Comment by shvc** [comment]
window.Show and Border container removed
the UI still hang if click SeletEntry's dropdown icon
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("cc.select")
	w := a.NewWindow("SelectEntry")
	user := widget.NewSelectEntry([]string{"a1", "a2", "a3"})
	var enter, body *fyne.Container
	enter = container.NewVBox(user,
		widget.NewButton("Enter", func() {
			w.SetContent(body)
			w.Resize(fyne.NewSize(200, 100))
		}),
	)
	body = container.NewHBox(
		widget.NewButtonWithIcon("Back", theme.NavigateBackIcon(), func() {
			w.SetContent(enter)
			w.Resize(fyne.NewSize(300, 180))
		}),
	)
	w.SetContent(body)
	w.Resize(fyne.NewSize(300, 180))
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
This is now fixed on `develop` branch ready for next release
