### ISSUE TITLE
fyne on M1  dyld errors

### ISSUE THREAD

**Issue by JackySmith** [fyne-io/fyne#2940]
Just run the fyne demo,and edit with an arg[1], if arg[1] == 1 , I will let the demo run on mac desktop terminal, and if arg[1]== 2, I will let the demo do something else on mac recovery terminal , that has no relation with fyne, because when on mac recovery terminal ,fyne is without support

when build, CGO_ENABLED=1 is added, go version = v1.16.5 or v1.18.1  ,the same errors

on Mac Desktop terminal, it run well on intel and arm model , I can see a fyne windows. 
on Mac Recovery terminal, it run well on intel model, but it can not run on arm M1 model,

the errors:

dyld[327]: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications
  Referenced from: /Volumes/TEST/M1
  Reason: tried: '/System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications' (no such file), '/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications' (no such file)
Abort trap: 6
-bash-3.2# 

I think that is some relations with fyne version, because this is not happed on fyne 1.4

my test code :

```
package main

import (
	"fmt"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"os"
)

func main() {
	if os.Args[1] == "1" {
		a := app.New()
		w := a.NewWindow("Hello")

		hello := widget.NewLabel("Hello Fyne!")
		w.SetContent(container.NewVBox(
			hello,
			widget.NewButton("Hi!", func() {
				hello.SetText("Welcome :)")
			}),
		))

		w.ShowAndRun()
	}else {
		fmt.Println("now args[1]=",os.Args[1] )
	}

}
```

Device (please complete the following information):
OS: MacOS
Version: 12.3
Go version: 1.16.5 / 1.18.1
Fyne version: 2.1.4

**Comment by andydotxyz** [comment]
> I think that is some relations with fyne version, because this is not happed on fyne 1.4

We had to add new frameworks to support the ever-evolving macOS definition of notifications (3 different frameworks now!)
The old version of Fyne you reference would not have worked on M1 at all.

Can anyone replicate the issue with M1? It is strange because fyne_demo runs and it uses notifications right?

**Comment by JackySmith** [comment]
I am very sure old version of fyne1.4 worked on M1 ,although there are many alert infomation,but it worked, last month I update fyne app to 2.14 because some radio and dialog problem.

also this error not appear when app run on m1 desktop, It run well , but in m1 recovery terminal,it has the error

I google the error, many peope have the same issue on ios app , and the same,notifications not be  used but has the error, they solved this problem by change some build options on xcode , set the framework from require to optional. 

but we compile fyne not in xocde , Is there a way  such as add some target when compile to aviod the notifications

**Comment by andydotxyz** [comment]
> but in m1 recovery terminal,it has the error

Can you please expand on what this means? If the app works normally but not under this situation then what is the difference?

I am not sure what the recovery terminal is, or if we even expect it to work (does it have OpenGL enabled?) What are the replication steps to get this to happen?

**Comment by Jacalz** [comment]
We have done a lot of improvements on the M1/M2 support lately. Is this still an issue?

**Comment by andydotxyz** [comment]
There was a notifications API issue a long time ago and the M1 didn't support the old framework we were using.
Given this was about 2.1.4 I think we can close until hearing otherwise - information has been pending for over a year now.
