### ISSUE TITLE
Readme document should update?

### ISSUE THREAD

**Issue by HDHChris** [fyne-io/fyne#2941]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/76725654/165508093-e5a9a24b-ea48-4503-ac4e-cead5d079be3.png">

**Comment by HDHChris** [comment]
Yeah, I found that the official website has correct and updated:
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/76725654/165509682-d9062ba4-e1ce-40fa-a563-e3350cde812c.png">

**Comment by andydotxyz** [comment]
This seems like a good report, why was it closed?
