### ISSUE TITLE
Add metadata support to gopherjs backend

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2944]
### Is your feature request related to a problem? Please describe:
gopherjs does not support ldflags and can't handle the -X flag used with the default go compiler. We need to figure out an alternative method.

### Is it possible to construct a solution with the existing API?
Ideally there should not be any new API.

### Describe the solution you'd like to see:
No idea on how to enable this at the moment.

**Comment by andydotxyz** [comment]
Adding Bowmore as ideally we would get this in with the main API addition.

**Comment by andydotxyz** [comment]
Done on the proposed release :)
