### ISSUE TITLE
Inquiry about payment gateway integration in fyne

### ISSUE THREAD

**Issue by ccpplinux** [fyne-io/fyne#2948]
I am developing a mobile app in fyne. I need to integrate payment gateway of India in fyne. Is it possible? If yes then how? The payment gateway that I want to integrate in fyne is at https://razorpay.com/docs/payments/server-integration/go/install/. Its support is available for golang based websites. Is it possible to integrate it in mobile app developed using fyne?

**Comment by Jacalz** [comment]
I guess it depends on what their API does and what kind of data it exposes. If it is just sending and receiving data from for example text fields and such, I don’t see any specific reason as to why it wouldn’t work. From what I know, no one in our team has used that library and I guess we probably can’t help with how you should use their library with Fyne.

**Comment by ccpplinux** [comment]
Thanks for reply. When my mobile app will send data to that API then it will display a webpage for selection of bank. After selection of bank, the control will go to the bank website. Then again control will come back from bank website to this API and then from this API to mobile app. Since fyne is not having support of webview and so how it will be possible to display the content of webpage generated by this API as well as content of bank website?

**Comment by Bluebugs** [comment]
Hi @ccpplinux , your question are, I feel, not really in the scope of issues opened here. Maybe you would be better served by going via a commercial support as you can find here: https://fyne.io/support/ . It seems to me this require to start understand the payment API needs and how to do the integration with Fyne.

**Comment by andydotxyz** [comment]
I agree, this is a request for support which is not what our issue tracker is for.
We don't have support for embedding web views, but even if we did an external API would not automatically launch it.
I recommend looking in to the library code, trying to work out how web callbacks work and see if it can be done.
If you have questions or need help the support link that @Bluebugs provided is the best place to go.

I note also that this same request has been posted to two Discord servers as well as our email account - please don't do this - the same people are working to handle all these responses.
