### ISSUE TITLE
tappable canvas

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#2951]
This is at half request and half question.... <br> 

### Is your feature request related to a problem? Please describe:
missing area to easy draw with fyne canvasobjects  with tappable all areas

### Is it possible to construct a solution with the existing API?
without tappable yes, but with tappable no or very difficult 

### Describe the solution you'd like to see:

I have created tappable extended of  BaseWidget and widget.BaseRenderer, acording to ProgressBar and progressRenderer, because I want have something like canvas at one widget ......, I want to see something like first picture of https://github.com/fyne-io/fyne/issues/2949 and I have created this https://github.com/MatejMagat305/fyne/pull/1/files,
I have created only request to my repo, because it have still bugs, it display only first object (at beginning rectangle (background)
and after add first object etc.) and that is question, why it does not working? I m sorry for annoying, but I really think, the "drop and drag" is the most meaningful on similar canvas

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"image/color"
	"math/rand"
)

var size = float32(700.0)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	rand.Seed(0)

        //my widget
	c := widget.NewMcanvas(color.White, fyne.NewSize(size, size))
        // setting function on my widget
	c.SetOnTap(func(event *fyne.PointEvent) {
		fmt.Println(event.Position, "   ", event.AbsolutePosition)
		addOnPosition(event.Position, c)
	})
         // 

	w.SetContent( container.NewVBox(widget.NewLabel("Hello Fyne!"), c))
	w.ShowAndRun()
}

func addOnPosition(event fyne.Position, c *widget.Mcanvas) {
	newCircle := canvas.NewCircle(
		color.RGBA{
		R: uint8(rand.Int31n(250)),
		G: uint8(rand.Int31n(250)), 
		B: uint8(rand.Int31n(250)),
		A: uint8(rand.Int31n(250)),
	})
	s := fyne.NewSize(float32(rand.Int31n(int32(size/2))), float32(rand.Int31n(int32(size/2))))
	newCircle.Resize(s)
	newCircle.Move(fyne.NewPos(event.X-s.Width/2, event.Y-s.Height/2))
	c.Add(newCircle)
	c.Refresh()
}
```

**Comment by Jacalz** [comment]
Isn’t this basically asking the very same things that https://github.com/fyne-io/fyne/issues/2924 already touched on? That issue was closed with the motivation being mentioned mostly in https://github.com/fyne-io/fyne/issues/2924#issuecomment-1100756925. It seems to me like (apart from the `fc` integration) that answer kind of applies here as well.

**Comment by andydotxyz** [comment]
In addition to what @Jacalz said the code above would depend on your `NewMcanvas` declaring `MinSize`... You have added all contents to a `VBox` which squashes item to their minimum height. Thus if your canvas experiment is not defining a min size that is what you want it won't be visible or behave correctly. Consider using a different way to pack items on to screen when you're looking to make use of available space (like Border).
