### ISSUE TITLE
Dropdown menus have no scroll bars on Android

### ISSUE THREAD

**Issue by Aquarian-Age** [fyne-io/fyne#2955]
On Android, dropdown menus don't have a scroll bar on the right
There is indeed a right scroll bar on PC Linux systems

https://gophers.slack.com/files/UK8V6RSLB/F03DKGVGHEH/screenshot_20220501_200845.png

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by Aquarian-Age** [comment]
I adjusted the font size of the theme and the problem is solved
It is very likely that the length of the drop-down content is exactly the same as the height of the screen, and the scroll bar on the right is not displayed. This should not be a bug
![Screenshot_20220502-205009](https://user-images.githubusercontent.com/36611556/166239173-f1b16885-eee3-4224-bcea-b1e2a4b2694e.jpg)
