### ISSUE TITLE
TextGrid.SetStyleRange - one before last line is not styled properly

### ISSUE THREAD

**Issue by adamwasila** [fyne-io/fyne#2957]
### Describe the bug:

`TextGrid.SetStyleRange` does not set style to last full line.

### To Reproduce:

1. Run an app shown below.
2. Observe results (3rd line is not styled while it should be)

### Screenshots:

![example](https://user-images.githubusercontent.com/1942279/166646387-3a565fa6-1c51-496c-987f-2bbafcacfd71.png)

### Example code:

```
func main() {
	a := app.New()
	w := a.NewWindow("textgrid bug")

	tg := widget.NewTextGridFromString("aaaaaaaa\nbbbbbbbb\ncccccccc\ndddddddd")

	tg.SetStyleRange(0, 0, 3, 3, &widget.CustomTextGridStyle{
		FGColor: colornames.Red,
		BGColor: colornames.Brown,
	})

	w.SetContent(tg)
	w.ShowAndRun()
}
```

### Device (please complete the following information):

(skipped that one - I have fix already, publishing PR, this is high-level bug in logic so this is irrelevant)

 - **OS:** N/A
 - **Version:** N/A
 - **Go version:** N/A
 - **Fyne version:** develop

**Comment by andydotxyz** [comment]
This was merged for v2.2.0
