### ISSUE TITLE
Fyne error:  window creation error

### ISSUE THREAD

**Issue by GitVVV** [fyne-io/fyne#2959]
I was trying to run fyne app but got crash
```
2022/05/04 13:33:22 Fyne error:  window creation error
2022/05/04 13:33:22   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2022/05/04 13:33:22   At: C:/Users/VVV/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/driver.go:123
```
fyne version v2.1.4
go version go1.18.1 windows/amd64
Windows 10 Pro x64 21H2 19044.1682
Laptop DELL Vostro V131
CPU Intel Core i5-2410M
Video driver Intel HD Graphics 3000 version 9.17.10.4459 2016/05/19 - latest available version

**Comment by andydotxyz** [comment]
Can you please confirm which OpenGL version is supported by the graphics driver loaded? (there should be some driver info or utility app for that card)

**Comment by andydotxyz** [comment]
According to Intel it seems that they do not support this chip on Windows 10 (or 11) and it does not support OpenGL 3.2, which we require.
For context the chip was released in 2011...
https://www.intel.co.uk/content/www/uk/en/support/articles/000005526/graphics.html

**Comment by GitVVV** [comment]
> Can you please confirm which OpenGL version is supported by the graphics driver loaded? (there should be some driver info or utility app for that card)

OpenGL version 3.1.0 build 9.17.10.4459

> According to Intel it seems that they do not support this chip on Windows 10 (or 11) and it does not support OpenGL 3.2, which we require. For context the chip was released in 2011... https://www.intel.co.uk/content/www/uk/en/support/articles/000005526/graphics.html

The problem has no solution?

**Comment by andydotxyz** [comment]
It would seem not, the chip is not capable of running Fyne apps.
In the future we may make a driver that connects to Windows APIs directly which may help, but there is every chance that the DirectX (or similar) that we use would not be supported either. That chip is quite old now and not supported by Intel or Microsoft and I expect not Dell either?

**Comment by GitVVV** [comment]
DirectX 9, 10.1
Shaders 4.1

OK thanks!
Close the issue

**Comment by Crushtain** [comment]
Видмо графический процессор не поддерживает fyne.
Скачайте последний релиз здесь - https://github.com/pal1000/mesa-dist-win/releases
Assets --> mesa3d-23.1.9-release-msvc.7z (смотря какая там будет версия) 
После скачивания этого файла разархивируйте и запустите systemwidedeploy.cmd
Затем нажмите 1 (первый пункт)
Всё заработает!

**Comment by Jacalz** [comment]
@Crushtain Please stick to English for discussions within this project.

**Comment by mpkondrashin** [comment]
https://github.com/pal1000/mesa-dist-win/releases Assets --> mesa3d-23.1.9-release-msvc.7z

I have tried. Now it complains on absence of vulcan-1.dll. Is there solution?

**Comment by mpkondrashin** [comment]
I could not make it run for Windows 11 arm in my VMware  Fusion Player on MacBook Pro M2.

I found solution to put OpenGL dll aside to the fyne executable:
https://downloads.fdossena.com/geth.php?r=mesa64-latest
