### ISSUE TITLE
Panic in line renderer on develop branch

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#2962]
It looks like line renderer is crashing quite reliably (possibly related to existing bug, I could not find it).

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to fyne_demo
2. Click on Canvas
3. Panic

### Device (please complete the following information):
 - **OS:** macOS
 - **Version:** Big Sur / Intel 64
 - **Go version:** 1.17/1.18
 - **Fyne version:** develop

**Comment by Bluebugs** [comment]
The crash is happening in internal/painter/gl/draw.go inside drawLine when calling DrawArrays. Removing that line or setting the size to 0 make it not crash. I have checked the vbo and it looks correct (size, stride and offset). The code is very similar to drawTextureWithDetails, but something must be different to lead to that crash. Kind of missing it at the moment.

**Comment by Bluebugs** [comment]
I can't figure out what is going on. This look really correct, but somehow isn't. @toaster if you do have some time to look at it, this would be great.

**Comment by toaster** [comment]
> I can't figure out what is going on. This look really correct, but somehow isn't. @toaster if you do have some time to look at it, this would be great.

I’ll do.

**Comment by toaster** [comment]
Cool, @changkun found the issue and fixed it with #2965.

**Comment by changkun** [comment]
It should not be an issue in the dev branch now as https://github.com/fyne-io/fyne/pull/2965 is merged. Close.
