### ISSUE TITLE
Slider drag handle is clipped off at minimum size

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2966]
### Describe the bug:

Something is strange with the MinSize of the slider widget and I don't quite know why. It results in part of the drag handle being cut of at the sides. I can't replicate this on all my screens. It is the most apparent on my 15" laptop screen.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code below.
2. Look in the top left corner.

### Screenshots:

![image](https://user-images.githubusercontent.com/25466657/167258069-767ee3eb-1df6-489a-b7de-fca8bc8216bd.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	w.SetContent(container.NewVBox(
		widget.NewSlider(0, 5),
	))

	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Fedora Linux
 - **Version:** 35 with the Linux Kernel 5.17.5
 - **Go version:** 1.16.15
 - **Fyne version:** v2.1.4 and develop

**Comment by andydotxyz** [comment]
From that app screenshot it looks like the whole widget is offset from where it should be drawn - which may be the cause of this glitch

**Comment by itsjustdel** [comment]
Trying to replicate this I saw some different issues, perhaps it is linked:

If I run the app with any resolution and scaling at 100% I see a shortened bar
![image](https://user-images.githubusercontent.com/45520351/184889534-bad41110-9318-47e6-a5fe-e85fd85f5d3b.png)

As soon as I resize the window, it fixes itself, even just adding 1 pixel to the height. (Moving the slider does not resize the bar)
![image](https://user-images.githubusercontent.com/45520351/184889668-adeea95a-d719-40d2-a6d6-1fce0e5bae16.png)

When using any value over 100% scaling I do not see any issues

I have been unable to replicate the side of the ball being cropped

`Windows 10` `Go 1.18.1` `v2.1.4`

**Comment by itsjustdel** [comment]
@Jacalz Does the cropping disappear if you resize the window?

**Comment by Jacalz** [comment]
Sorry for the late reply @itsjustdel. No, it seems to be consistently clipped off for me. See attached screen recording.
[Screencast from 26-08-22 12:59:04.webm](https://user-images.githubusercontent.com/25466657/186889989-56bd2bdb-3fc4-40f2-828c-24a009d7cfc6.webm)
.

**Comment by Jacalz** [comment]
This looks to have been fixed with the new theme changes. I will close it but potentially reopen if the issue occurs again.
![image](https://user-images.githubusercontent.com/25466657/187027153-66b28b34-6ba8-4cb3-a636-2dc855716341.png)
