### ISSUE TITLE
How to set FYNE_FONT with an TTF file, I need to show some Chinese messages, Can you show an Example?

### ISSUE THREAD

**Issue by hongliu9527** [fyne-io/fyne#297]

**Comment by andydotxyz** [comment]
It is an environment variable. Depending on your operating system how this is set varies.
An example would be:

```bash
$ FYNE_FONT=/path/to/file.ttf go run myapp.go
```

**Comment by hongliu9527** [comment]
thanks a lot



------------------ 原始邮件 ------------------
发件人: "Andy Williams"<notifications@github.com>; 
发送时间: 2019年6月6日(星期四) 凌晨3:00
收件人: "fyne-io/fyne"<fyne@noreply.github.com>; 
抄送: "洪流"<635781500@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fyne-io/fyne] How to set FYNE_FONT with an TTF file, I need toshow some Chinese messages, Can you show an Example? (#297)




It is an environment variable. Depending on your operating system how this is set varies.
 An example would be:
 $ FYNE_FONT=/path/to/file.ttf go run myapp.go

**Comment by ACXNX** [comment]
> go run myapp.go



> $ FYNE_FONT=/path/to/file.ttf go run myapp.go


> thanks a lot
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Andy Williams"<notifications@github.com>; 发送时间: 2019年6月6日(星期四) 凌晨3:00 收件人: "fyne-io/fyne"<fyne@noreply.github.com>; 抄送: "洪流"<635781500@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [fyne-io/fyne] How to set FYNE_FONT with an TTF file, I need toshow some Chinese messages, Can you show an Example? (#297) It is an environment variable. Depending on your operating system how this is set varies. An example would be: $ FYNE_FONT=/path/to/file.ttf go run myapp.go — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Has your problem been solved
