### ISSUE TITLE
Build Constraint when build for arm64

### ISSUE THREAD

**Issue by mattkasun** [fyne-io/fyne#2973]
### Describe the bug:
build for arm64 has build constraint
builds properly for amd64 and on arm64 if gui component is disabled.

### To Reproduce:
Steps to reproduce the behaviour:
ec2-ec2-user@ip-172-31-26-9 netclient % env GOARCH=arm64 go build -tags gui .
package github.com/gravitl/netmaker/netclient
	imports github.com/gravitl/netmaker/netclient/gui
	imports fyne.io/fyne/v2/app
	imports fyne.io/fyne/v2/internal/driver/glfw
	imports fyne.io/fyne/v2/internal/driver/common
	imports fyne.io/fyne/v2/internal/painter/gl
	imports github.com/go-gl/gl/v3.2-core/gl: build constraints exclude all Go files in /Users/ec2-user/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20210813123233-e4099ee2221f/v3.2-core/gl

### Screenshots:
N/A

### Device (please complete the following information):
OS: MacOS
Version: Darwin ip-172-31-26-9.ec2.internal 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
Go version: go version go1.18.1 darwin/amd64
Fyne version: fyne.io/fyne/v2 v2.1.4

**Comment by andydotxyz** [comment]
You are cross compiling, Go removes CGo support so you will have to add CGO_ENABLED=1... 
More info at https://developer.fyne.io/started/cross-compiling
