### ISSUE TITLE
How to change multiLineRows?

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [fyne-io/fyne#2980]
```go
label := canvas.NewText("label：", nil)
text := := widget.NewMultiLineEntry()
container.New(layout.NewFormLayout(),label, text)
```

I use form layout. in this container, i use multiline entry. 
But multiline entry only show 3 rows. I think its too short. I want it to show 15 rows.

I saw fyne.io/fyne/v2/widget/entry.go multiLineRows=3. How can I change it to make this value bigger?

**Comment by andydotxyz** [comment]
At this time widgets fill the space available, so providing more space is normally the way to go.
If the user resizes their window should the input get bigger? 15 lines is a very large minimum considering that is longer than most phone screens (once keyboard is up)...

**Comment by AelxRmoan** [comment]
Emm... you can just go there and change it to 15, compile your app and then return 3,)

**Comment by andydotxyz** [comment]
If it truly requires more lines visible you can now set `MinRowsVisible` on `Entry`.

**Comment by Jacalz** [comment]
FYI: Please use discussions for questions. Issues are for bug reports and feature requests.
