### ISSUE TITLE
Tap event permeates the surface that hide a button

### ISSUE THREAD

**Issue by fuintis** [fyne-io/fyne#299]
Using a GroupWithScroller widget the hidden buttons by the scroller still can be tapped. Do you need an example code?

My env is: Virtualized Linux cross compiling to Windows amd64 .exe using mingw-w64

Many thanks for your work!!

**Comment by andydotxyz** [comment]
A small sample would be very helpful thank you. I think I know what you describe but it would be great to have a trivial example to validate.

**Comment by andydotxyz** [comment]
This is now on develop for testing
