### ISSUE TITLE
Image should not call Refresh from inside the Render thread

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#2991]
### Is your feature request related to a problem? Please describe:
Calling Refresh from within the Render thread expose race condition between the Render thread and the user of Fyne API that are out of the user control. It also means that it require multiple iteration in the render thread to have the proper layout when loading an image.

### Is it possible to construct a solution with the existing API?
This is an open question here, but the logical things to do would be to have an image open the image, read the image dimension, apply minsize, call Refresh on the canvas, render thread would pick up the open file and finalize the loading of image.

For doing that flow, we might either need to introduce a new field in the image structure or maybe introduce a shadow structure internal to the canvas API.

### Describe the solution you'd like to see:
Until it is tried, I do not have a really good idea of what the solution to this is.

**Comment by andydotxyz** [comment]
> This is an open question here, but the logical things to do would be to have an image open the image, read the image dimension, apply minsize, call Refresh on the canvas, render thread would pick up the open file and finalize the loading of image.

Wouldn't this have to be a blocking operation? Either way it would slow the render I think, reading the image before proceeding to allow it to render.
Perhaps we can just invalidate the texture directly instead of calling Refresh?

**Comment by Bluebugs** [comment]
I am guessing, that the concern is with blocking operation in the render thread. This issue does not solve the fact that the image decoding itself would be done in the rendering thread. I think that it is an orthogonal problem to solve actually. As during the image Refresh, we could spin a goroutine that start to do the decoding without blocking both the application thread nor the render thread.

Invalidating the texture will not provide additional safety concerning file race condition.

Doing the header decoding of the image in the application thread is most likely still necessary, but maybe we just need to open the file and could move the header reading to a goroutine that precede the rendering thread. This might introduce additional thread safety concern that we might need to be careful with.
