### ISSUE TITLE
Table doesn't fill the window

### ISSUE THREAD

**Issue by NotAzay** [fyne-io/fyne#2995]
### Describe the bug:

The table shrunks together.

### To Reproduce:
Steps to reproduce the behaviour:
1. Copy the example code of table.
2. Modify the second func of widget.NewTable to return widget.NewLabel("")

### Screenshots:

![Table](https://user-images.githubusercontent.com/104895344/169514971-caa5971a-46dc-4fc8-bc24-8a6571a80610.PNG)

![Table2](https://user-images.githubusercontent.com/104895344/169515483-494ac4f0-bca9-4048-8e2a-4861a88c2904.PNG)

### Example code:

```go

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

var data = [][]string{[]string{"top left", "top right"},
	[]string{"bottom left", "bottom right"}}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Table Widget")

	list := widget.NewTable(
		func() (int, int) {
			return len(data), len(data[0])
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(i widget.TableCellID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(data[i.Row][i.Col])
		})

	myWindow.SetContent(list)
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Windows 10 Profession
 - **Version:** 19041.572
 - **Go version:** 1.18.2
 - **Fyne version:**  2.1.4

**Comment by andydotxyz** [comment]
This seems to be specific to Windows.
We ask the window to be small, but it is created larger than expected.

**Comment by matwachich** [comment]
From my tests, it seems for me that it has something to do with Cell width calculation.
Width is calculated at Cell creation (create() callback), and not recalculated on update().

Replace `return widget.NewLabel("")` with `return widget.NewLabel("............")` to partially solve the probleme

**Comment by andydotxyz** [comment]
Closing as resolved, re-open if that is not the case
