### ISSUE TITLE
No way to scroll through lists

### ISSUE THREAD

**Issue by cbehopkins** [fyne-io/fyne#30]
Actually more of a question than an issue:
As my trial of this gui I'm doing a quick file manager. Slight issue, I build a long list in the window and while it does render there is no way to scroll through it. I can work around this, but I wondered if there was a plan to support scroll bars in the future before I spend too long on it. Is that sort of gui toolkit functionality even within scope?

**Comment by ajwillia-ms** [comment]
You're right there is no way to do this yet.
It is in scope and should be completed for the basic milestone. There was a "card" registered in the [current project](/fyne-io/fyne/projects/2) which I have updated to ticket #31. I'd like to close this issue as a duplicate of that (newer) one, if that seems sensible.

**Comment by cbehopkins** [comment]
Sounds grand to me. Thanks
