### ISSUE TITLE
Window with fixed size changes size when un-minimized - Windows

### ISSUE THREAD

**Issue by fuintis** [fyne-io/fyne#300]
Window with fixed size change his size when maximize after minimize

If you set a fixed size of a window by this code:

window.Resize(fyne.NewSize(857, 395))
window.SetFixedSize(true)
window.Show()

With an window that uses the BorderLayout and have no children (or containing very few or empty widgets) when you restore after minimized the size of the window is recalculated.

Can i prevent this?
Many thanks in advance.

**Comment by andydotxyz** [comment]
Can you please confirm the operating system and/or desktop environment that you are using?

**Comment by fuintis** [comment]
I run the app under Windows 10 amd64, but i build it under Linux using a mingw-w64 cross compiler.

**Comment by andydotxyz** [comment]
Thanks. I will see if we can replicate on WIndows reliably.
This will be put to one side for a few days as there are fixes being worked on in this area for 1.1. We will ensure this is sorted for the next release.

**Comment by andydotxyz** [comment]
I think this is resolved on the develop branch which we will release next week.
If possible can you please test it, otherwise we can return to this after release. I cannot replicate the issue any more.

**Comment by drakbar** [comment]
I am getting this issue under 1.1

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
)

func main() {
	a := app.New()

	win := a.NewWindow("Minimize")
	win.Resize(fyne.Size{300, 400})

	win.SetFixedSize(true)

	win.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Are you also running on Windows 10 @drakbar?
After un-minimise what size is the window?

**Comment by drakbar** [comment]
Yes windows 10. It appears to be the minimal size, as if the window was
resized with 1 by 1 as the parameters.

**Comment by andydotxyz** [comment]
I have not managed to replicate this yet. Do you see this behaviour with any of our example apps?

**Comment by drakbar** [comment]
I have tested this on two different Windows 10 machines, and observed this on both.

I have not seen this particular behavior in any of the apps. However,  I have noticed that the fyne_demo will completely crash if the advanced tab is selected and you minimize the window. I am not sure that these two issues are related though.

**Comment by andydotxyz** [comment]
Thanks I see this now. Working to resolve :)

**Comment by andydotxyz** [comment]
On develop for testing, we will cherry pick it to the 1.1.1 release shortly
