### ISSUE TITLE
Font cutoff with bold italics

### ISSUE THREAD

**Issue by itsjustdel** [fyne-io/fyne#3001]
### Describe the bug:

Last letter of text cropped when using bold italic google font Poppins

### To Reproduce:
Steps to reproduce the behaviour:
1. Download Poppins font family [Poppins](https://fonts.google.com/specimen/Poppins)
2. Extract OpenSans-BoldItalic.ttf
3. Bundle with ```fyne bundle Poppins-BoldItalic.ttf >> bundled.go```
4. Run and look at top right of the the last letter

### Screenshots:

![ddddd](https://user-images.githubusercontent.com/45520351/169818585-c887fa79-df69-4ba1-b7ac-9fe38ce8f56d.png)

### Example code:

```package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
)

type myTheme struct{}

func (m myTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(name, variant)
}

func (m myTheme) Font(style fyne.TextStyle) fyne.Resource {

	return resourceStaticFontsPoppinsBoldItalicTtf
}

func (m myTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func (m myTheme) Size(name fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(name)
}

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Text")

	text := canvas.NewText("DDDDdd", color.White)
	text.TextSize = 42

	var _ fyne.Theme = (*myTheme)(nil)
	myApp.Settings().SetTheme(&myTheme{})

	vBox := container.NewVBox(
		container.NewCenter(text),
	)

	w.SetContent(vBox)
	w.Resize(fyne.NewSize(240, 360))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** 1.8
 - **Fyne version:** 2.1.4

**Comment by andydotxyz** [comment]
It seems to be possible to cause this to happen without the custom font...

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Text")

	text := canvas.NewText("DDDDdd", color.White)
	text.TextStyle.Bold = true
	text.TextStyle.Italic = true
	text.TextSize = 42

	vBox := container.NewVBox(
		container.NewCenter(text),
	)

	w.SetContent(vBox)
	w.Resize(fyne.NewSize(240, 360))

	w.ShowAndRun()
}
```

**Comment by itsjustdel** [comment]
So it can, same behaviour on Windows
![image](https://user-images.githubusercontent.com/45520351/169864213-ffc1be35-0362-447c-bf3c-1ed0c235965b.png)

**Comment by andydotxyz** [comment]
This is now on `develop` branch for testing prior to `v2.2.0` release
