### ISSUE TITLE
Horizontal CheckGroup overlap when having long text

### ISSUE THREAD

**Issue by aynakeya** [fyne-io/fyne#3005]
### Describe the bug:
Horizontal CheckGroup overlap when having long text.

### To Reproduce:
Using fyne-demo, set one item to have longer length.
```
checkGroup := widget.NewCheckGroup([]string{"CheckGroup Item 1AAAAAAAAA", "CheckGroup Item 2"}, func(s []string) { fmt.Println("selected", s) })
checkGroup.Horizontal = true
```

### Screenshots:
![image](https://user-images.githubusercontent.com/32156054/170374804-23256cff-d1b0-4913-b988-39ba1f06caf5.png)
![image](https://user-images.githubusercontent.com/32156054/170374945-9f2c7fc7-5c96-41aa-9f38-1cd65dd15276.png)

### Example code:
```
checkGroup := widget.NewCheckGroup([]string{"CheckGroup Item 1AAAAAAAAA", "CheckGroup Item 2"}, func(s []string) { fmt.Println("selected", s) })
checkGroup.Horizontal = true
```

### Device (please complete the following information):
 - **OS:**  Windows
 - **Version:** 10
 - **Go version:** 1.16
 - **Fyne version:** v2.1.4

**Comment by andydotxyz** [comment]
What is the desirable outcome here?

**Comment by chaunsin** [comment]
Leave a mark ，Me too
### Device (please complete the following information):
- OS: Mac
- Version: 12.6
- Go version: 1.18
- Fyne version: v2.3.4

**Comment by Jacalz** [comment]
I suppose that this needs the same fix as https://github.com/fyne-io/fyne/issues/3386.

**Comment by andydotxyz** [comment]
Fixed on develop and release branch ready for v2.3.5
