### ISSUE TITLE
How to set the screen not to go to sleep mode?

### ISSUE THREAD

**Issue by cCRD1989** [fyne-io/fyne#3007]
How to set the screen not to go to sleep mode?   Mobile Android 

### Device (please complete the following information):
OS: Android
Version: API31/Pixel2
Go version: go 1.18
Fyne version: v2.1.4

**Comment by xaionaro** [comment]
@cCRD1989 : Just curious if you found any answer.

**Comment by andydotxyz** [comment]
In the upcoming 2.5 release you can call SetDisableScreenBlanking on the Driver interface.
