### ISSUE TITLE
All pictures cannot be displayed after the project is packaged

### ISSUE THREAD

**Issue by HDHChris** [fyne-io/fyne#3009]
### Describe the bug:
All pictures cannot be displayed after the project is packaged，But it works normally without packaging. Everything is normal.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to 'project root directory'.
2. Execute `fyne package -os darwin -icon myapp.png` command.(There are already myapp pictures in the root directory of the project).
3. The package is successful, and the package file is output normally.
4. Double click the package file to run the output.
5. It is found that all pictures on the interface cannot be displayed normally, including those in PNG and SVG formats. (but everything is normal when running without packaging).

### Screenshots:
Effect of running after packaging：
<img width="626" alt="image" src="https://user-images.githubusercontent.com/76725654/170605772-6ec0fe59-97a0-4f91-9ead-4075bf1e76f9.png">

Effects of running directly in the project without packaging:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/76725654/170605833-39d04395-baf0-4421-9d2e-00d5d2432baa.png">

The path where the picture is stored in the project：
<img width="348" alt="image" src="https://user-images.githubusercontent.com/76725654/170605912-bf92ce89-2ac7-4c0f-94f9-1b02685b754a.png">

### Device (please complete the following information):
 - **OS:** MacOS
 - **Version:** 12.2.1
 - **Go version:** 1.17
 - **Fyne version:** 2.1.4

**Comment by Jacalz** [comment]
I suspect that you load the icons using `os.Open()` with a relative path and thus the packaged icon doesn't pick them up. However, this is very hard to debug given that the issue doesn't contain any example code. You should consider bundling your icons using the `fyne bundle` (installed using `go install fyne.io/fyne/v2/cmd/fyne@latest`) command and then use the icons that are bundled into your executable.

**Comment by HDHChris** [comment]
> I suspect that you load the icons using `os.Open()` with a relative path and thus the packaged icon doesn't pick them up. However, this is very hard to debug given that the issue doesn't contain any example code. You should consider bundling your icons using the `fyne bundle` (installed using `go install fyne.io/fyne/v2/cmd/fyne@latest`) command and then use the icons that are bundled into your executable.



> I suspect that you load the icons using `os.Open()` with a relative path and thus the packaged icon doesn't pick them up. However, this is very hard to debug given that the issue doesn't contain any example code. You should consider bundling your icons using the `fyne bundle` (installed using `go install fyne.io/fyne/v2/cmd/fyne@latest`) command and then use the icons that are bundled into your executable.

thank you
I found out what the problem is, or is it because I have too little experience... If I copy the packaged executable to a directory other than the project root directory, the image will not load. But as long as it is still executing in the project root directory, everything is fine. This means that the executable itself does not include images imported from outside. I wonder if there is any way to type all the resources into a file or installation package?

**Comment by Jacalz** [comment]
> I wonder if there is any way to type all the resources into a file or installation package?

There is. See the part about `fyne bundle` in my previous comment. You can use that to bundle specific files or a whole folder.

**Comment by HDHChris** [comment]
> There is. See the part about `fyne bundle` in my previous comment. You can use that to bundle specific files or a whole folder.

year,thank you . i fint its document at [here](https://developer.fyne.io/extend/bundle).
I used the `fyne bundle` command to customize fonts, but I didn't understand how it worked at the time, and now I do. Thank you very much!

**Comment by HDHChris** [comment]
> There is. See the part about `fyne bundle` in my previous comment. You can use that to bundle specific files or a whole folder.

I would also like to ask: if I do not package all the picture writing resources into a pure go binary file, but use other tools similar to the installer to make an installation package, when the user installs, can I copy the executable and its supporting resource files to the installation directory specified by the user?
But another problem that I have been concerned about comes out again: whether it is an installation package or a pure binary file, when users are already using my application, what should I do if I want to update the version? Just as we usually use any other client software, they will prompt you that the version has been updated. Does **Fyne** have any specific support tools in this area? Or does it need to be completely self realized? 
Thank you for your time.

**Comment by andydotxyz** [comment]
> when the user installs, can I copy the executable and its supporting resource files to the installation directory specified by the user?

This only works for some operating systems, so we discourage it.
In fact installers should not be needed for Fyne apps at all.

> Does Fyne have any specific support tools in this area? Or does it need to be completely self realized?

This is not something the Fyne supports directly (it is expecting store based distribution, or other package mangers I guess? I can share that @FyneLabs is looking at this area so you may see some news from us soon :).

**Comment by HDHChris** [comment]
Thanks， I get it！
