### ISSUE TITLE
Container with no Layout and using fixed sized and absolute positionning for his children. Is this possible?

### ISSUE THREAD

**Issue by fuintis** [fyne-io/fyne#301]
Is there a way that can i set the absolute position of a widget inside a container? Until now the size of the children and finally the size of the window vary according the text content of the widgets. Can a window be less "liquid"? If i have a very dynamic content (that changes with every tap) the window change his size and layout proportions very often. This issue is pretty disturbing for me.

Any suggestions?
Many thanks in advance.

**Comment by andydotxyz** [comment]
What you desire can be done - this would be controlled by a custom layout.
Does that make sense?
I think that we should change the default container (no layout specified) to leave the positioning up to the developer - would that help with what you are trying to do?

**Comment by andydotxyz** [comment]
The 1.1 release as updated NewContainer() (without layout) will not assert any position or size on it's child objects. This leaves you able to implement a layout or manipulate the objects from elsewhere.

**Comment by fuintis** [comment]
In this new layoutless container: what happend with the text that Is bigger than the owner widget? The text will crop? Wrap? Overflows the widget boundaries? This behavior will be parametrized?

**Comment by andydotxyz** [comment]
The container will not cause any change in size or render in the layoutless container.
If an item overflows then it may appear outside the container - depending on what is next to the container.
It will clip if there is a scroller just like any other content.
Wrap will not be caused as the container is not telling the item that it is too big (this requires a layout).
