### ISSUE TITLE
Tap event on any widget?

### ISSUE THREAD

**Issue by fuintis** [fyne-io/fyne#302]
Can i capture a tap event in a widget that not have this role (like a label, for example)?

Thanks to all!!

**Comment by andydotxyz** [comment]
This is not possible with the standard widgets.
You can extend a widget and add this functionality by implementing the fyne.Tappable interface.

What are you trying to achieve, perhaps we can suggest an easier way?

**Comment by fuintis** [comment]
> What are you trying to achieve, perhaps we can suggest an easier way?

I don't know. I'll try implement the fyne.Tappable interface.

Many thanks for your time.

**Comment by fuintis** [comment]
I'm trying implement fyne.Tappable interface but it didn't work. Here the very simple code:

    import (
    	"fyne.io/fyne"
    	"fyne.io/fyne/widget"
    )
    
    
    type TapLabel struct {
    	*widget.Label
    
    	OnTapped func() `json:"-"`
    }
    
    func (mc *TapLabel) Tapped(*fyne.PointEvent) {
    	if mc.OnTapped != nil {
    		mc.OnTapped()
    	}
    }
    
    
    func NewTapLabel(text string, tapped func()) *TapLabel {
    	return NewTapLabelWithStyle(text, fyne.TextAlignLeading, fyne.TextStyle{}, tapped)
    }
    
    func NewTapLabelWithStyle(text string, alignment fyne.TextAlign, style fyne.TextStyle, tapped func()) *TapLabel {
    	return &TapLabel{
    		widget.NewLabelWithStyle(text, alignment, style),
    		tapped,
    	}
    }

Any suggestions?

**Comment by okratitan** [comment]
You added the Tapped method, but not the TappedSecondary method. You must add both for Tappable to be implemented, even if you dont use one of them.  So you just need to add:

func (mc *TapLabel) TappedSecondary(*fyne.PointEvent) {
	}
