### ISSUE TITLE
# github.com/go-gl/glfw/v3.3/glfw /usr/bin/ld: cannot find -lXxf86vm collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#3021]
### Describe the bug:

# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status

### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - **OS:**  ubuntu
 - **Version:** 20.04
 - **Go version:** 1.18
 - **Fyne version:** last

**Comment by Jacalz** [comment]
Was that not installed when following the steps on https://developer.fyne.io/started/?
