### ISSUE TITLE
Java swing like panel widget

### ISSUE THREAD

**Issue by hismailbulut** [fyne-io/fyne#3022]
Hi I would like to see a java swing like panel widget (or container) with customizable borders and layout. I know current container system gives most of the features what panel gives but I just want some borders around my layout. And I also know I can create it myself but it should be in standard lib in my opinion. This is just my opinion and a suggestion. If you don't like it, of course I respect it.

**Comment by matwachich** [comment]
I think this kind of discussion should happen in discord before opening an issue.

**Comment by hismailbulut** [comment]
Hey sorry for late response and templates. I like the card widget and I didn't know it can be used without labels. Thanks :)
