### ISSUE TITLE
top Table elements become invisible after window maximization

### ISSUE THREAD

**Issue by cmitsakis** [fyne-io/fyne#3034]
### Describe the bug:
The top elements (that were hidden because of scrolling) do not appear when you maximize the window (see screenshot). But when you click at those hidden elements they appear.

Similar to #3013 

### To Reproduce:
1. Create a window with a table with number of rows high enough that there is scrolling but low enough that there is no scrolling when the window is maximized
2. Scroll to the bottom of the table
3. Click on a random element
4. Maximize window

### Screenshots:

![2022-06-03-232150_406x374_scrot](https://user-images.githubusercontent.com/8564595/171946360-0b3bcde7-cb64-4a50-8ff0-79a5a9686023.png)

### Example code:
```go
package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("table")
	t := createTable()
	w.SetContent(t)
	w.Resize(fyne.NewSize(640, 480))
	go func() {
		time.Sleep(time.Second)
		t.ScrollToBottom()
		time.Sleep(time.Second)
		t.Select(widget.TableCellID{Row: 15, Col: 1})
		time.Sleep(time.Second)
		w.SetFullScreen(true)
	}()
	w.ShowAndRun()
}

func createTable() *widget.Table {
	rowData := []string{"c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10"}
	data := make([][]string, 0)
	const numOfRows = 20
	for i:=0; i<numOfRows; i++ {
		data = append(data, rowData)
	}
	t := widget.NewTable(
		func() (int, int) {
			return len(data), len(data[0])
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("asdfghjkl")
		},
		func(cellID widget.TableCellID, obj fyne.CanvasObject) {
			obj.(*widget.Label).SetText(data[cellID.Row][cellID.Col])
		})
	return t
}

```

### Device (please complete the following information):
 - **OS:** Linux
 - **Version:** 5.17.9
 - **Go version:** 1.18.2
 - **Fyne version:** 3c1f987

**Comment by thh9** [comment]
I also met , in m1 macbook pro

**Comment by andydotxyz** [comment]
Does https://github.com/fyne-io/fyne/pull/3035 fix it for you @thh9 ?

**Comment by thh9** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/28970107/182121568-9e6c2288-b74c-44f4-a5fe-ced6a9c6cb58.png">



> Does #3035 fix it for you @thh9 ?



> Does #3035 fix it for you @thh9 ?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/28970107/182121618-5045b2cd-708a-4114-8e43-01dde65abcd4.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/28970107/182122374-ff02ef83-fed5-42e9-a9ab-222310cba04b.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/28970107/182122446-c600643a-48e2-4683-8bcf-12f60fbcafc5.png">

I build use workspace , but  #3035 is useless.

**Comment by andydotxyz** [comment]
This is fixed on develop I am pretty sure. Please re-open if not.

**Comment by cmitsakis** [comment]
> This is fixed on develop I am pretty sure. Please re-open if not.

It is not fixed. Please re-open.
