### ISSUE TITLE
Add new theme updates

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#3042]
Previews and possible API considerations to be added here, this is a placeholder issue.

**Comment by andydotxyz** [comment]
The full design needs to be exported, but here are some details to show what is being worked on:
<img width="620" alt="Screenshot 2022-07-11 at 13 01 48" src="https://user-images.githubusercontent.com/294436/178260186-714a1d09-f142-44e5-a271-16904af9617f.png">
<img width="621" alt="Screenshot 2022-07-11 at 13 02 03" src="https://user-images.githubusercontent.com/294436/178260192-6056778a-e321-42fc-9837-bf2914084fe2.png">
<img width="339" alt="Screenshot 2022-07-11 at 13 02 28" src="https://user-images.githubusercontent.com/294436/178260200-50409442-70e3-4674-9dea-30c26a248c09.png">
<img width="336" alt="Screenshot 2022-07-11 at 13 02 37" src="https://user-images.githubusercontent.com/294436/178260206-1c7782d2-e5b2-4bfc-a555-f6125d8c9861.png">
<img width="622" alt="Screenshot 2022-07-11 at 13 03 02" src="https://user-images.githubusercontent.com/294436/178260209-ffc77680-58fc-43e3-9b21-727871e6e58c.png">
<img width="622" alt="Screenshot 2022-07-11 at 13 03 18" src="https://user-images.githubusercontent.com/294436/178260212-f2089042-a5cd-4cb0-8588-5c782391ad9e.png">

**Comment by ErrorNoInternet** [comment]
Will there be rounded corners? :eyes:

**Comment by c1ngular** [comment]
well done , looks refreshing .

**Comment by ddkwork** [comment]
good,  i want change the button text size when mouse in and out,but i found
the text style not export this field.

**Comment by andydotxyz** [comment]
>  i want change the button text size when mouse in and out,but i found
the text style not export this field.

That is not supported by the standard button. 
To do this you would need to add your own button that altered size based on desktop events.

**Comment by Jacalz** [comment]
Just adding it here that we discussed this during the last call. It seems like the text selection colour for dark theme is incorrect (too dark) and the section colour used in tree is still the old one for light theme. We need to check this through before closing as entirely done.

**Comment by Jacalz** [comment]
An update on things that remain to be done (as far as I know):
- [ ] Update the selection colour for the light theme with new colour.
- [ ] Update the text selection colour in the dark theme to have better contrast.
- [ ] Make sure that the images in our README.md file are all updated (as well as those on the website of course).

**Comment by nickjwhite** [comment]
I just tested the latest version of fyne on the develop branch, and overall the new theme looks great.

One thing I don't like (and let me know if you'd rather have this conversation in a separate issue) is how light the border around unchecked checkboxes & radio buttons are now. They're basically invisible, which makes things less discoverable. Likewise disabled widgets are hard to see and read too, as they're *so* light now. It's fine with the dark theme, this mostly just affects the light one.

**Comment by andydotxyz** [comment]
I think this is complete. I get your point @nickjwhite but what we have done is to the design that was created.
Would you be able to open a ticket to investigate the less discoverable input areas and we can look at it further?
