### ISSUE TITLE
Windows missing version metadata when packaged

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3046]
### Description

Packaged Windows binaries are missing version information when viewing the details inside Explorer.
![A95713CD-E96F-4D0E-8CC3-8ACC38F8FDA5](https://user-images.githubusercontent.com/25466657/172450829-b7c6eff3-1c75-4554-8813-a451cbf0b2d9.png)

### Reproduction
1. Package the Windows binary using `fyne package`.
2. Right-click on the binary and open up the properties viewer.
3. Navigate to the “Details” tab.
4. Notice that the version information is missing.

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** 1.18
 - **Fyne version:** 2.1.4

### Describe the bug:

on Windows using MSYS2.
According to https://github.com/fyne-io/fyne/pull/2813, "fyne package" is better than "go build". The latter does not show icon for exe. But the former does not show for fprint(). No version info can be shown for details of the exe (in explorer). So actually, one issue is print and the other is version info. The version problem is probably rooted in Go and all I know is to use "-ldflags -X main.Ver=..." to pass it to the code and cannot show it in Explorer. However fyne package can make it show as 0.0.0. This is puzzling me.
Thank you.
I have FyneApp.toml for Website,Icon, Name, ID.

### To Reproduce:
Steps to reproduce the behaviour:
1. fyne package --os windows --appVersion 5.0.0 --appBuild 1 --tags main.Ver=5.0.0,Bld=1
6. run the exe in MINGW command window. it can print into terminal.
7. run the exe in Windows command line. it **cannot** print into terminal.
8. check detail of exe in Explorer. the file version of it shows 0.0.0.0
9. in my code (package main), Ver & Bld are both "". How to pass a variable?

**Comment by andydotxyz** [comment]
The version info should appear - this seems like a bug thanks.

The trouble with printing is down to how your OS will launch graphical apps. macOS has the same issue. You see the console when developing but launching a complete graphical app will go to your system console not the terminal you started from.

> in my code (package main), Ver & Bld are both "". How to pass a variable?

The usage of tags are not the same as ldflags. Go build tags just control which files will be included, they do not set variables.

**Comment by Jacalz** [comment]
@bon-ami Can you please stick to one topic per issue in the future? Multiple things going on in one issue makes it a lot harder to read.

I added some more information to the description, which I think should make it a bit easier to track the issue that we need to fix here. Thanks for opening this issue.

**Comment by andydotxyz** [comment]
Fixed on develop and will release in v2.2.2 as well
