### ISSUE TITLE
Tab buttons stop working after removing a tab

### ISSUE THREAD

**Issue by leprechaun33** [fyne-io/fyne#3050]
### Describe the bug:

When removing a tab from AppTabs the tabs that are to the right of the removed tab cannot be selected with mouse clicks.
If there are tabs 1, 2, 3, 4 and tab 2 is removed then the tab buttons for 3 and 4 will not respond to mouse clicks.  If tabs 5 and 6 are then added, the buttons for tabs 5 and 6 will still work like normal.

### To Reproduce:
Steps to reproduce the behaviour:
Running the below code, go to File -> New Tab two or three times.
Then select a tab that is not the last tab and click the "Close Tab" button, after this the tab buttons of tabs to the right of the removed tab will not work.
If another tab is added then removed then the last tab will be selected.

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow()
	t := buildTabsCont()
	w.SetMainMenu(buildMenu(t))

	w.SetContent(t)
	w.ShowAndRun()
}

func buildMenu(t *container.AppTabs) *fyne.MainMenu {
	nt := fyne.NewMenuItem("New Tab", func() { newTab(t) })
	file := fyne.NewMenu("File", nt)
	m := fyne.NewMainMenu(file)
	return m
}

func buildTabsCont() *container.AppTabs {
	at := container.NewAppTabs(
		container.NewTabItem("Welcome", widget.NewLabel("Welcome info here")),
	)
	at.SetTabLocation(container.TabLocationTop)
	return at
}

func newTab(t *container.AppTabs) {
	b := widget.NewButton("Close Tab", func() { t.RemoveIndex(t.SelectedIndex()) })
	t.Append(container.NewTabItem("Tab Name", b))
}
```

### Device:
 - **OS:** Linux/Pop_OS
 - **Version:** 22.04
 - **Go version:** 1.18.1
 - **Fyne version:** v2.1

**Comment by Jacalz** [comment]
The latest version of Fyne is v2.2.0. Can you please try with the new version and see if the issue still persists?

**Comment by d4x1** [comment]
I think it's root cause it here: https://github.com/fyne-io/fyne/blob/develop/container/apptabs.go#L341-L349. When you remove a tab, the index bind to the tab button is not updated.

You can replace the codes like this, and it will work.

```
        item := r.appTabs.Items[i]
	index := i // capture
	button := &tabButton{
		onTapped: func() { r.appTabs.SelectIndex(index) },
	}
	r.buttonCache[item] = button

```


Do you have any ideas about how to fix it elegantly? @Jacalz

**Comment by Jacalz** [comment]
Hmm. Nice catch @d4x1. The best fix would probably be to stop using indexes all together and find a better solution but I suspect that your fix might work as well.

**Comment by d4x1** [comment]
After reading the codes, a more convenient way to fix it is use `r.appTabs.Select(item)`  when a tab is active.  I can will make a PR to fix this later.

**Comment by andydotxyz** [comment]
Thanks so much @d4x1, this is now on `develop` and `release/v2.2.x` for the next release
