### ISSUE TITLE
Unexpected stuttering when refreshing image

### ISSUE THREAD

**Issue by asegs** [fyne-io/fyne#3052]
### Describe the bug:
I am generating images using `image.NewRGBA` in the Go library.  I have a function that every frame, extends a red line down the middle of the image.  This line should get longer every frame, and it does.  However, on my machine, the line appears to stutter heavily, refreshing at a rate closer to 5-10 FPS than 60.  I have reduced this down to the simplest sample code I could, and included a video reference.

### To Reproduce:
Run provided code.  Change dimensions for smaller screens, but this is most apparent on 1080p + displays.

### Screenshots:
![example](https://user-images.githubusercontent.com/54863852/172901328-46dfbf9e-3440-4b6f-ba7c-2a53c6f5af5a.gif)

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"image"
	"image/color"
	"time"
)

var width = 1920
var height = 1080

var lineWidth = 100
var fps = 60

func main () {
	topLeft := image.Point{0, 0}
	bottomRight := image.Point{width, height}

	rgbaImage := image.NewRGBA(image.Rectangle{topLeft, bottomRight})

	red := color.RGBA{255, 0, 0, 0xff}

	mainApp := app.New()
	imageWindow := mainApp.NewWindow("Images")

	canvasToWrite := canvas.NewImageFromImage(rgbaImage)
	imageWindow.SetContent(canvasToWrite)
	imageWindow.Resize(fyne.NewSize(float32(width), float32(height)))

	drawImageRed := func(x int) {
		for i := 0 ; i < lineWidth ; i++ {
			rgbaImage.Set(x + 100,100 + i,red)
		}
	}

	go func() {
		pos := 0
		for true {
			drawImageRed(pos)
			pos ++
			canvas.Refresh(canvasToWrite)
			time.Sleep(time.Duration(1000 / fps) * time.Millisecond)
		}
	}()

	imageWindow.ShowAndRun()
}
```
-->

### Device (please complete the following information):
 - **OS:** Ubuntu
 - **Version:** 20.04
 - **Go version:** `go1.13.8 linux/amd64`
 - **Fyne version:** 2.2.0

**Comment by asegs** [comment]
Just for clarify, I have a feeling this is similar to https://github.com/fyne-io/fyne/issues/2209, I'll see if I can understand the suggested solutions there.  Didn't find that issue when searching at first.

**Comment by asegs** [comment]
Ha - `canvasToWrite := canvas.NewRasterFromImage(rgbaImage)` works perfectly.
![short_smooth](https://user-images.githubusercontent.com/54863852/172907280-e9b7fca6-507a-49d1-855b-ffe1d687ef33.gif)
.

Very satisfying.  I plan to use your toolkit as one of several frontends for an open-source Go multi-user dungeon game engine.  This will be the front end for the isometric view.  Not just a pipe dream lol, I already have ~5000 LOC in a repo here.  Maybe I'll post some screenshots when I get isometrics working.  Thanks Andy!

**Comment by Jacalz** [comment]
That sounds like a very cool project. Looking forward to seeing more about it :)
