### ISSUE TITLE
suggestion for customizable parameter for "fyne package"

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3055]
### Is your feature request related to a problem? Please describe:

(#3046 is the failure of setting exe version number by "fyne package".)
I've been using `go build -race -ldflags "-X main.Ver=...` to pass the version number to my code, before using fyne.
Now, if I use "go build", the icon of the exe is not shown in Windows Explorer. If I use "fyne package", on the other hand, I cannot pass the version to my code as a command line parameter.

### Is it possible to construct a solution with the existing API?
I tried to take advantage of the "tag" param, but it is not for this purpose. And after checking the code of Build, I can tell the current design of "fyne package" does not support my aim.

### Describe the solution you'd like to see:
I'd like to see a param of "fyne package" that I can pass to "go build" directly. Thank you for your work.

**Comment by andydotxyz** [comment]
If you set your version inside `FyneApp.toml` it will automatically get included with "fyne package" https://developer.fyne.io/started/metadata. Subject to #3046 of course...
This is equivalent to `appID` build parameter which is required for some OS once you use "fyne release" and optional in package mode

**Comment by bon-ami** [comment]
@andydotxyz , I am aware of the appID and toml. But it is for the build process, and I cannot pass it to my code. `-ldflags "-X main.Ver` can pass the value of this Ver to the variable in my go code.
In https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/commands/build.go, around line 180, there has been usage of -ldflags without exposing it as a parameter of "fyne package". My suggestion is to extend a param so that we can use whatever parameters we want, to "go build"
Thank youl.

**Comment by andydotxyz** [comment]
Unfortunately what you are asking for does not work cross platform. Some OS that fyne targets now do not support ldflags, so we have needed to find other ways.
Fixing the version passed needs done (as noted in the other issue) - what is the new use case?

**Comment by bon-ami** [comment]
@andydotxyz , I can understand not all OS's support ldflags, so I am asking for a parameter to be passed to `go build` directly. For example, `fyne package -args ABC` will result in `go build ... ABC`.
In my case, my go code needs to know and show app version. Thank you again.

**Comment by andydotxyz** [comment]
But the app version issue is #3046

**Comment by bon-ami** [comment]
@andydotxyz , #3046 is about the version not shown in Explorer, and this is about how my code can know the version. (Furthermore, some other building variables if needed.)

**Comment by andydotxyz** [comment]
In v2.2 the version information is available in App.Metadata() https://developer.fyne.io/api/v2.2/appmetadata.html.

If this is not sufficient you will need to expand on "if needed" - we don't add functionality based on speculative need because we need to consider carefully how everything will work for each OS we support.

**Comment by bon-ami** [comment]
> In v2.2 the version information is available in App.Metadata() https://developer.fyne.io/api/v2.2/appmetadata.html.
> 
> If this is not sufficient you will need to expand on "if needed" - we don't add functionality based on speculative need because we need to consider carefully how everything will work for each OS we support.

It has satisfied my needs for now. Thank you.

**Comment by andydotxyz** [comment]
OK, thanks - between this info and the #3046 bug tracking the rest I think we can consider this resolved

**Comment by jhaoheng** [comment]
@bon-ami 

I use `go embed` to bundle the `env.yaml`
And the read file in the main.go
And then use GitHub Action to build the `env.yaml`

```
//go:embed env.yaml
var env embed.FS

func init() {
	b, err := env.ReadFile("env.yaml")
	if err != nil {
		panic(err)
	}
	if err := yaml.Unmarshal(b, &config); err != nil {
		panic(err)
	}
}
```
