### ISSUE TITLE
Image cannot be read correctly

### ISSUE THREAD

**Issue by qinjinze** [fyne-io/fyne#3057]
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"fyne.io/fyne/v2/theme"
)

func main() {
	fmt.Println()
	a := app.NewWithID("id")
	a.Settings().SetTheme(theme.LightTheme())
	w := a.NewWindow("form")
	icons(w)

	w.Resize(fyne.NewSize(1000, 800))

	w.ShowAndRun()
	fmt.Println("close")
}
var icn []byte

func icons(w fyne.Window) {
	resource:=fyne.NewStaticResource("head.jpeg",icn)
	icon1:=widget.NewIcon(resource)
	
	fi:=widget.NewFileIcon(nil)
	fi.SetSelected(true)
	fi.SetURI(fyne.CurrentApp().Storage().RootURI())
	//w.SetIcon(resource)
	c := container.NewVBox(icon1,fi)
	w.SetContent(c)
}
```

D:\project\src\go\fyne\icon>go run icon.go

2022/06/10 22:41:18 Fyne error:  image err
2022/06/10 22:41:18   Cause: image: unknown format
2022/06/10 22:41:18   At: D:/project/src/fyne.io/fyne/v2/internal/painter/image.go:122
close

Image opens in normal preview in windows

D:\project\src\go\fyne\icon>go version
go version go1.16.13 windows/amd64

**Comment by andydotxyz** [comment]
Please use the bug report template, it is there for a reason.
From what you have pasted I would agree `[]byte` is not a valid image - you need to read in the resource...
