### ISSUE TITLE
Error running the "getting started" example.

### ISSUE THREAD

**Issue by sky-2002** [fyne-io/fyne#3060]
### Describe the bug:

I came to know about fyne package and then tried to run the example given in the getting started section of the README.md and copied the same code. But it gives errors for the code below.

code :
```go
hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to the README.md file of the fyne package ([link](https://github.com/fyne-io/fyne))
2. Scroll down to Getting Started section.
3. Copy the code and run it.
4. The following error appears - 

### Screenshots:

![Screenshot (108)](https://user-images.githubusercontent.com/84656834/173176420-6b62899e-3b17-49e6-8bc6-cba22557e205.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Windows 11
 - **Version:** 10.0.22000 Build 22000
 - **Go version:**  1.18.1
 - **Fyne version:** 2.2.0

**Comment by sky-2002** [comment]
I do not know the exact reason why this happened. But this same code is working fine now😅.

**Comment by Jacalz** [comment]
It looks from the error messages like you had an import of `fyne.io/fyne` (without `/v2`) lying around.

**Comment by sky-2002** [comment]
@Jacalz , Yeah exactly. I then added that v2 and everything worked fine , Thanks a lot !😇
