### ISSUE TITLE
Click the Cancel button in the pop-up box, the computer will crash and the computer will restart

### ISSUE THREAD

**Issue by qinjinze** [fyne-io/fyne#3061]
### Describe the bug:
dialog click cancel button program and computer crash，The computer crashed 10 times after the program was tested, and only one error message was obtained.

### To Reproduce:
Steps to reproduce the behaviour:
1. go run dialog.go
2. Click on "show dialog"
3. Click the "Cancel" button
4. See error：
main.saveFile.func1(0x0, 0x0, 0x0, 0x0)
        D:/project/src/go/fyne/NewEntryDialog/dialog.go:46 +0x32
fyne.io/fyne/v2/dialog.(*fileDialog).makeUI.func3()
        D:/project/pkg/mod/fyne.io/fyne/v2@v2.2.0/dialog/file.go:183 +0x109
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc00010c320, 0xc0038dae80)
        D:/project/pkg/mod/fyne.io/fyne/v2@v2.2.0/widget/button.go:194 +0x77
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
        D:/project/pkg/mod/fyne.io/fyne/v2@v2.2.0/internal/driver/glfw/window.go:634 +0x3f
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0xc0000021e0)
        D:/project/pkg/mod/fyne.io/fyne/v2@v2.2.0/internal/driver/common/window.go:35 +0x55
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        D:/project/pkg/mod/fyne.io/fyne/v2@v2.2.0/internal/driver/glfw/window.go:942 +0x105
exit status 2

### Example code:
```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Dialog")
	saveFile(w)
	w.Resize(fyne.NewSize(500, 500))
	w.ShowAndRun()
	fmt.Println("Closed")
}

func saveFile(w fyne.Window) {
	lblMsg := widget.NewLabel("")

	dl := dialog.NewFileOpen(func(uc fyne.URIReadCloser, err error) {
		lblMsg.SetText(uc.URI().Path())
	}, w)
	btn := widget.NewButton("show dialog", dl.Show)
	c := container.NewVBox(lblMsg, btn)
	w.SetContent(c)
}

```

### Device (please complete the following information):
OS: Window
Version: 10
Go version: 1.16.10 and 1.18.3
Fyne version: 2.2.0

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue.

You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

**Comment by andydotxyz** [comment]
When a file dialog cancels it will call with a nil `URIReadCloser`.
It looks like this is the line of your code that is crashing. You should handle the possible error passed in and the nil case.

**Comment by Jacalz** [comment]
@qinjinze Are you sure about the “the computer will crash and the computer will restart” part? An application crashing shouldn’t bring down the whole computer. If the computer is crashing, there is likely something else that’s very wrong somewhere.

**Comment by qinjinze** [comment]
> @qinjinze您确定“计算机将崩溃，计算机将重新启动”部分吗？应用程序崩溃不应导致整台计算机瘫痪。如果计算机崩溃，则可能是某处出现了其他非常错误的问题。

This code runs anywhere on my computer. According to the reproduction steps, the probability of the computer restarting is 90%.
I'm not sure if computer hardware compatibility is related

**Comment by qinjinze** [comment]
This code runs anywhere on my computer. According to the reproduction steps, the probability of the computer restarting is 90%.
I'm not sure if computer hardware compatibility is related

> @qinjinze您确定“计算机将崩溃，计算机将重新启动”部分吗？应用程序崩溃不应导致整台计算机瘫痪。如果计算机崩溃，则可能是某处出现了其他非常错误的问题。


This code runs anywhere on my computer. According to the reproduction steps, the probability of the computer restarting is 90%.
I'm not sure if computer hardware compatibility is related

**Comment by qinjinze** [comment]
> 



> 当文件对话框取消时，它将使用 nil 调用`URIReadCloser`。 看起来这是您正在崩溃的代码行。您应该处理传入的可能错误和 nil 情况。



> When a file dialog cancels it will call with a nil `URIReadCloser`. It looks like this is the line of your code that is crashing. You should handle the possible error passed in and the nil case.

It is recommended to click the "Cancel" dialog button, the program only prompts an error, but the program should not crash
