### ISSUE TITLE
 Cannot set width and height independently

### ISSUE THREAD

**Issue by xiaoshengduan** [fyne-io/fyne#3068]
How to set the width and height of buttons separately, so that multiple buttons in the same row have different widths and heights and independent positions

**Comment by andydotxyz** [comment]
Widgets do not control their own size or position, this is the purpose of a container's layout.
https://developer.fyne.io/explore/container

Please do not use this bug tracker to ask questions but follow the link it prompted for our support channels.
https://fyne.io/support/
