### ISSUE TITLE
Make everything exportable 

### ISSUE THREAD

**Issue by HashemJaafar** [fyne-io/fyne#3071]
You library is good but we can't extend your library with our code . It is difficult to make new features to the library without changing the source code or without rewrite the source code. The solution is  to make everything exportable

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. You don’t need to close this and open a new one. Just update the issue description with all the relevant information from the issue template. Thanks for understanding.

> You library is good but we can't extend your library with our code . It is difficult to make new features to the library without changing the source code or without rewrite the source code.

I don't think this statement is entirely true. You can already extend existing widgets (see https://developer.fyne.io/extend/extending-widgets) and there are lots more examples in the "Extending Fyne" section on the same page. If there is something in particular that you want to make more configurable then please open an issue about that instead.

> The solution is to make everything exportable

I think that might be taking it too far. If there are any APIs that are too restrictive, we should instead work on improving them. We can't just make everything exportable as that would be a terrible API experience. The whole point of [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) is basically to hide internal state to make the API robust and easy-to-use for the developer.

**Comment by Bluebugs** [comment]
There is the beginning of an extension registry: https://addons.fyne.io/ that can give you some more idea.

Also I would like to point out that any public API has to be stable for the full major release cycle. The more is exposed of the internal, the more difficult it is to do any change upstream as the amount of potential user of the API increase and so increase the potential for API break.

**Comment by andydotxyz** [comment]
Sorry I'm going to close this as won't fix - this is not the right approach as @Jacalz says.
There is a carefully designed extension API already, and there are many examples of custom widgets like @Bluebugs points out.
If you look at most Fyne applications you will see that people have extended or created custom widgets.
Internal items are private for a reason. If one of these is causing you a problem then please open a new issue describing what you cannot do and we will try to resolve it.
