### ISSUE TITLE
Extending Entry widget adds space below it, when inside a Form

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3076]
### Describe the bug:
When extending the Entry widget, there is some space

### To Reproduce:
Just run the example code, and see the difference between the CustomEntry inside a Form and inside a VBox

### Screenshots:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1791230/174196517-b20ecc8f-7bf4-4ddc-b199-73e6caa8d7ab.png">

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("TEST")

	content := container.NewGridWithColumns(2,
		widget.NewForm(
			widget.NewFormItem("Standard Entry 01", widget.NewEntry()),
			widget.NewFormItem("Custom Entry", NewCustomEntry()),
			widget.NewFormItem("Standard Entry 02", widget.NewEntry()),
		),
		container.NewVBox(
			widget.NewEntry(),
			NewCustomEntry(),
			widget.NewEntry(),
		),
	)
	content.Objects[0].(*widget.Form).OnSubmit = func() {
		println("Submit...")
	}

	w.SetContent(content)
	w.Resize(fyne.NewSize(800, 500))
	w.CenterOnScreen()
	w.ShowAndRun()
}

type CustomEntry struct {
	widget.Entry
}

func NewCustomEntry() *CustomEntry {
	ce := &CustomEntry{}
	ce.ExtendBaseWidget(ce)
	return ce
}
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Version:** 10.0.18363.2212
 - **Go version:** 1.18.2
 - **Fyne version:** 2.2.0

**Comment by andydotxyz** [comment]
I think this relates to the validation, perhaps the default setup is not proving a clean setup...
Thanks for opening, we should try and figure this out - though it may relate to #2964

**Comment by andydotxyz** [comment]
Ah yes, this is helpful thanks

**Comment by matwachich** [comment]
Some new information: setting a non nil Validator to a standard Entry gives the same effet.
So it is definitly related to Validation. It's like something says to the layout that a custom Entry is like an Entry with a Validator.
