### ISSUE TITLE
Is there any way to customize fyne.Container?

### ISSUE THREAD

**Issue by SuperLiveYou** [fyne-io/fyne#3080]
I want to customize the container and let it handle some layout mess for me. I try to copy fyne The container interface is implemented, but I find that this will prevent me from displaying my components

**Comment by SuperLiveYou** [comment]
The copied content is exactly the same, with only the Fyne prefix added

**Comment by SuperLiveYou** [comment]
Like this
`package mlcontainer

import (
	"fyne.io/fyne/v2"
)

var _ fyne.CanvasObject = (*Container)(nil)

type Container struct {
	size     fyne.Size
	position fyne.Position
	Hidden   bool

	Layout  fyne.Layout
	Objects []fyne.CanvasObject
}

func NewContainerWithoutLayout(objects ...fyne.CanvasObject) *Container {
	ret := &Container{
		Objects: objects,
	}

	ret.size = ret.MinSize()
	return ret
}
func NewContainer(objects ...fyne.CanvasObject) *Container {
	return NewContainerWithoutLayout(objects...)
}
func New(layout fyne.Layout, objects ...fyne.CanvasObject) *Container {
	ret := &Container{
		Objects: objects,
		Layout:  layout,
	}

	ret.size = layout.MinSize(objects)
	ret.layout()
	return ret
}

func (c *Container) Hide() {
	if c.Hidden {
		return
	}
	c.Hidden = true
}

func (c *Container) MinSize() fyne.Size {
	if c.Layout != nil {
		return c.Layout.MinSize(c.Objects)
	}

	minSize := fyne.NewSize(1, 1)
	for _, child := range c.Objects {
		minSize = minSize.Max(child.MinSize())
	}

	return minSize
}

func (c *Container) Move(pos fyne.Position) {
	c.position = pos
}

func (c *Container) Position() fyne.Position {
	return c.position
}

func (c *Container) Refresh() {
	c.layout()

	for _, child := range c.Objects {
		child.Refresh()
	}
	o := fyne.CurrentApp().Driver().CanvasForObject(c)
	if o == nil {
		return
	}
	o.Refresh(c)
}

func (c *Container) Resize(size fyne.Size) {
	if c.size == size {
		return
	}

	c.size = size
	c.layout()
}

func (c *Container) Show() {
	if !c.Hidden {
		return
	}
	c.Hidden = false
}

func (c *Container) Size() fyne.Size {
	return c.size
}

func (c *Container) Visible() bool {
	return !c.Hidden
}
func (c *Container) layout() {
	if c.Layout == nil {
		return
	}
	c.Layout.Layout(c.Objects, c.size)
}

func (c *Container) Remove(rem fyne.CanvasObject) {
	if len(c.Objects) == 0 {
		return
	}

	for i, o := range c.Objects {
		if o != rem {
			continue
		}

		removed := make([]fyne.CanvasObject, len(c.Objects)-1)
		copy(removed, c.Objects[:i])
		copy(removed[i:], c.Objects[i+1:])

		c.Objects = removed
		c.layout()
		return
	}
}

func (c *Container) RemoveAll() {
	c.Objects = nil
	c.layout()
}

func (c *Container) Add(add fyne.CanvasObject) {
	if add == nil {
		return
	}

	c.Objects = append(c.Objects, add)
	c.layout()
}

func (c *Container) AddObject(o fyne.CanvasObject) {
	c.Add(o)
}
`

**Comment by SuperLiveYou** [comment]
Like this
---------------------------------------------------------------
import (
	"fyne.io/fyne/v2"
)

var _ fyne.CanvasObject = (*Container)(nil)

type Container struct {
	size     fyne.Size
	position fyne.Position
	Hidden   bool

	Layout  fyne.Layout
	Objects []fyne.CanvasObject
}

func NewContainerWithoutLayout(objects ...fyne.CanvasObject) *Container {
	ret := &Container{
		Objects: objects,
	}

	ret.size = ret.MinSize()
	return ret
}
func NewContainer(objects ...fyne.CanvasObject) *Container {
	return NewContainerWithoutLayout(objects...)
}
func New(layout fyne.Layout, objects ...fyne.CanvasObject) *Container {
	ret := &Container{
		Objects: objects,
		Layout:  layout,
	}

	ret.size = layout.MinSize(objects)
	ret.layout()
	return ret
}

func (c *Container) Hide() {
	if c.Hidden {
		return
	}
	c.Hidden = true
}

func (c *Container) MinSize() fyne.Size {
	if c.Layout != nil {
		return c.Layout.MinSize(c.Objects)
	}

	minSize := fyne.NewSize(1, 1)
	for _, child := range c.Objects {
		minSize = minSize.Max(child.MinSize())
	}

	return minSize
}

func (c *Container) Move(pos fyne.Position) {
	c.position = pos
}

func (c *Container) Position() fyne.Position {
	return c.position
}

func (c *Container) Refresh() {
	c.layout()

	for _, child := range c.Objects {
		child.Refresh()
	}
	o := fyne.CurrentApp().Driver().CanvasForObject(c)
	if o == nil {
		return
	}
	o.Refresh(c)
}

func (c *Container) Resize(size fyne.Size) {
	if c.size == size {
		return
	}

	c.size = size
	c.layout()
}

func (c *Container) Show() {
	if !c.Hidden {
		return
	}
	c.Hidden = false
}

func (c *Container) Size() fyne.Size {
	return c.size
}

func (c *Container) Visible() bool {
	return !c.Hidden
}
func (c *Container) layout() {
	if c.Layout == nil {
		return
	}
	c.Layout.Layout(c.Objects, c.size)
}

func (c *Container) Remove(rem fyne.CanvasObject) {
	if len(c.Objects) == 0 {
		return
	}

	for i, o := range c.Objects {
		if o != rem {
			continue
		}

		removed := make([]fyne.CanvasObject, len(c.Objects)-1)
		copy(removed, c.Objects[:i])
		copy(removed[i:], c.Objects[i+1:])

		c.Objects = removed
		c.layout()
		return
	}
}

func (c *Container) RemoveAll() {
	c.Objects = nil
	c.layout()
}

func (c *Container) Add(add fyne.CanvasObject) {
	if add == nil {
		return
	}

	c.Objects = append(c.Objects, add)
	c.layout()
}

func (c *Container) AddObject(o fyne.CanvasObject) {
	c.Add(o)
}
---------------------------------------------------------------
I don't know what caused the problem. There are no error messages

**Comment by SuperLiveYou** [comment]
Like this
--------------------------------------------------------
![image](https://user-images.githubusercontent.com/68497295/174454182-ed33b320-d831-4bd4-9e63-aeff7f57842c.png)
--------------------------------------------------------
I don't know what caused the problem. There are no error messages

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues. The templates are designed to help us save time and give us all the necessary information related to the issue. For questions, we prefer other support methods: https://fyne.io/support/.

I find it a bit hard to figure out exactly what you are trying to do, but I can at least point out that `fyne.Container` is a struct and not an interface. That being said, you can’t implement it like you do with interfaces. I suspect that you might want to write a [custom layout](https://developer.fyne.io/extend/custom-layout).
