### ISSUE TITLE
Expose a storage.ErrNotExists for non existing documents

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3083]
### Is your feature request related to a problem? Please describe:

My code cannot check an error returned by, such as app.Storage().Save() with errors.Is()

### Is it possible to construct a solution with the existing API?

Such as `return os.ErrNotExist` for `document with name * does not exist`

### Describe the solution you'd like to see:

Please use standard errors from Go packages instead of using errors.New()

**Comment by Jacalz** [comment]
We might want tot just create our own `storage.ErrNotExists` variable (or similar) and then just return that instead. That would solve the issue presented here.

**Comment by bon-ami** [comment]
> We might want tot just create our own `storage.ErrNotExists` variable (or similar) and then just return that instead. That would solve the issue presented here.

sounds great

**Comment by andydotxyz** [comment]
Ready for next release on `develop` branch
