### ISSUE TITLE
Replace Quit menu item with developer code

### ISSUE THREAD

**Issue by Licoy** [fyne-io/fyne#3085]
### Is your feature request related to a problem? Please describe:
about desktop system menu

### Is it possible to construct a solution with the existing API?
https://github.com/fyne-io/fyne/blob/91c74db9c61b8277a9d89b9a792fc8eac6c42229/internal/driver/glfw/driver_desktop.go#L81

No,Hopefully this is controlled by the developers

### Describe the solution you'd like to see:
```go
fyne.NewMenu(
	"default",
	fyne.NewMenuItem("Panel", func() {
		//todo
	}),
	fyne.NewMenuItem("Quit", func() {
		//todo
	}),
)
```

**Comment by andydotxyz** [comment]
Many platforms do not allow developers to control app lifecycle - which is why we built it this way.
What is your desired outcome of replacing the `Quit` menu item?

**Comment by Licoy** [comment]
For example, I need to display "Quit" in Chinese, or make a second inquiry before closing, or other operations.

It is recommended to add a CustomMenu, if it is this type, the "Quit" menu will not be automatically registered.

**Comment by andydotxyz** [comment]
Displaying in a different language is required, and will be added in a future version. I also recommend that you look at `Window.SetCloseIntercept` which can block window close so you can ask user to save etc.

If you still want to replace it then I recommend seeing #1982 where it was made possible.

**Comment by brucealthompson** [comment]
I assume I have a fairly common use case not covered in this discussion. I will not necessarily have ANY windows open or even created when a user selects "Quit" from the system tray menu. I believe there is a simple fix for this. Provide a SetCloseIntercept() method on fyne.Desktop.App object. After all, the system tray menu is created using the fyne.Desktop.App object, not the fyne.Window object.

**Comment by andydotxyz** [comment]
@brucealthompson this ticket was asking for translations of the "Quit" menu item - I don't think your comment relates and you should probably open a new issue.

**Comment by brucealthompson** [comment]
Created the following:
Need to hook the fyne generated "Quit" menu item in fyne system tray menu #4670
https://github.com/fyne-io/fyne/issues/4670
