### ISSUE TITLE
Custom shortcuts with fyne.KeyTab is not working

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3087]
### Describe the bug:

I have noticed that using `fyne.KeyTab` doesn't work when using the `desktop.CustomShortcut` type. My idea is that something with our handling of tabs is treating the window canvas as not accepting tabs. Other buttons seem to be working fine on my end.

### To Reproduce:
Steps to reproduce the behaviour:
1. Run the example code below.
2. Press Ctrl + Tab on keyboard.
3. Notice that nothing happens.
4. Press Ctrl + Space on keyboard.
5. Notice that it works.

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
)

func main() {
	a := app.New()
	w := a.NewWindow("Custom Shortcut")

	ctrlTab := &desktop.CustomShortcut{KeyName: fyne.KeyTab, Modifier: fyne.KeyModifierControl}
	w.Canvas().AddShortcut(ctrlTab, func(shortcut fyne.Shortcut) {
		println("We tapped Ctrl+Tab")
	})

	ctrlSpace := &desktop.CustomShortcut{KeyName: fyne.KeySpace, Modifier: fyne.KeyModifierControl}
	w.Canvas().AddShortcut(ctrlSpace, func(shortcut fyne.Shortcut) {
		println("We tapped Ctrl+Space")
	})

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:**  Fedora Linux
 - **Version:**  35 with kernel 5.17.14
 - **Go version:**  1.16.15
 - **Fyne version:**  2.2.1

**Comment by edwinclement08** [comment]
Facing the same Issue.

**Comment by Jacalz** [comment]
Fixed now on develop. Thanks @edwinclement08.
