### ISSUE TITLE
Do not close app when last window is closed but systrayMenu exists

### ISSUE THREAD

**Issue by d1ss0nanz** [fyne-io/fyne#3092]
I'm looking for a reliable way to have a systray app that has no visible window.
When there is no hidden window, the app closes after the last visible window is closed.

The systrayMenu is already offering a "Quit" entry, so we should not count windows.

**Comment by d1ss0nanz** [comment]
#3094

**Comment by Jacalz** [comment]
Please use the issue templates when opening new issues in the future. The templates are designed to help us save time and give us all the necessary information related to the issue.

**Comment by d1ss0nanz** [comment]
I did. What information is missing?

**Comment by Jacalz** [comment]
It’s not so much about missing information but about using the actual template (https://github.com/fyne-io/fyne/blob/master/.github/ISSUE_TEMPLATE/feature_request.md). The idea with the template is that you fill it in and not just answer the questions and delete the rest. It’s not something important for this issue (you don’t need to update this one for the sake of it) but I always try to mention it to avoid users opening issues without using the template.
