### ISSUE TITLE
Add native look and feel option to widgets

### ISSUE THREAD

**Issue by programmingkidx** [fyne-io/fyne#3097]
Currently the Fyne framework displays widgets in a mostly black, white, and grey color set. This look might be ok for some people but for those who want a more native look and feel this can be disappointing. This is why I suggest a feature be added to Fyne that gives the user the option to set the look and feel of the widgets to the native environment. This would lead to Fyne applications that look more at home on Windows and Mac OS.

**Comment by Bluebugs** [comment]
Fyne is following material design with a bit of adaptation which define how things are designed, their interactions, look and feel. Trying to emulate native OS look and feel is a huge permanently ongoing task as each OS like to change their look and feel for each release, and you easily fall into an uncanny valley where it almost looks like it is, but it isn't and feel wrong.

But we do recognize that their is potential room for improvements that do not necessarily require to go that far. There is work coming hopefully in the next 2.3 release to improve the look and feel of Fyne application by revamping both default theme. Their are also experimentation to pick color from the OS theme and apply them on your application done by @metal3d that might be able to address some of what people might feel like a better integration with the host OS. I hope that this direction will fit your need. If you have other ideas on how to address those look and feel need within material design constraint, don't hesitate to share them!

**Comment by andydotxyz** [comment]
Thanks for the great explanation @Bluebugs. I will close this as won't fix, because this is not something we plan to do.
