### ISSUE TITLE
Can Fyne support cross platform system volume setting

### ISSUE THREAD

**Issue by lllwan** [fyne-io/fyne#3099]
### Is your feature request related to a problem? Please describe:
I need a way to set the system volume.

### Is it possible to construct a solution with the existing API?
I'm not sure

**Comment by Jacalz** [comment]
This doesn’t seem to me like something that is in the scope of Fyne. Far from all applications need support for Audio. I think you might be better off looking at cross platform audio libraries instead but that’s just my opinion.
