### ISSUE TITLE
Function "Remove" or "RemoveItem" on binding lists

### ISSUE THREAD

**Issue by Solander** [fyne-io/fyne#3100]
### Is your feature request related to a problem? Please describe:
When working with binded lists you can Append and Prepend items, but it's not possible to Remove them. 
This makes using binded lists more difficult.

### Is it possible to construct a solution with the existing API?
You can "Get" the list, manipulate it outside and then "Set" the new list.

### Describe the solution you'd like to see:
A "Remove" function which accept an index of the item that should be removed.

**Comment by andydotxyz** [comment]
Good idea, let's try and get this in

**Comment by Jacalz** [comment]
We might also want a `RemoveAll` function. Mentioned in https://github.com/fyne-io/fyne/discussions/3298.

**Comment by Utsav-Ladani** [comment]
Hello @andydotxyz and @Jacalz, I like to work on these functionalities. The code will look like below:

* `Remove` method for `StringList`
	```go
	func (l *boundStringList) Remove(index int) (string, error) {
		l.lock.Lock()
		defer l.lock.Unlock()
	
		if index < 0 || index >= len(*l.val) {
			return "", errOutOfBounds
		}
	
		removed := (*l.val)[index]
		*l.val = append((*l.val)[:index], (*l.val)[index+1:]...)
	
		return removed, l.doReload()
	}
	```

* `RemoveAll` method for `StringList`
	```go
	
	func (l *boundStringList) RemoveAll() ([]string, error) {
		l.lock.Lock()
		defer l.lock.Unlock()
	
		old := *l.val
		*l.val = []string{}
	
		return old, l.doReload()
	}
	```

Can I raise a PR?

**Comment by andydotxyz** [comment]
This has landed on develop branch and will be in release v2.5.0
