### ISSUE TITLE
Image not showing since fyne update

### ISSUE THREAD

**Issue by amo13** [fyne-io/fyne#3102]
### Describe the bug:
Since I updated fyne from 2.1.4 to 2.2.1 the image in my application is not showing any more.
Here is a small example where I'd expect to see the image in the application but it doesn't appear:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/container"
)

func main() {
	a := app.NewWithID("my.app")
	w := a.NewWindow("MyApp")
	w.SetMaster()

	w.Resize(fyne.NewSize(562, 226))
	w.SetContent(initScreen())

	w.ShowAndRun()
}

func initScreen() fyne.CanvasObject {
	logo := canvas.NewImageFromFile("logo.png")
	logo.FillMode = canvas.ImageFillOriginal

	leftside := container.NewVBox(layout.NewSpacer(), logo, layout.NewSpacer())
	rightside := container.NewVBox(layout.NewSpacer())

	grid := container.New(layout.NewGridLayout(2), leftside, rightside)
	return container.NewVBox(layout.NewSpacer(), grid, layout.NewSpacer())
}
```
I use this [logo.png](https://user-images.githubusercontent.com/6617661/175939659-b5c53e99-4bdc-467c-98e4-fd793010ec74.png) file. The issue is the same if I bundle it.

 - **OS:** At least linux and windows
 - **Go version:** 1.18.3
 - **Fyne version:** 2.2.1

Any help would be greatly appreciated. I am probably only missing something trivial, but I can't see it...

**Comment by andydotxyz** [comment]
Just out of interest I think `container.NewVBox(layout.NewSpacer(), logo, layout.NewSpacer())` is the same as `container.NewCenter(logo)`

**Comment by andydotxyz** [comment]
It seems to be that `ImageFillOriginal` is not rendering in `v2.2.1` for some reason!

**Comment by amo13** [comment]
Thanks a lot for addressing this so fast!
