### ISSUE TITLE
DocTabItem update text doesn't update the underline select bar (graphic glitch)

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3106]
### Describe the bug:
When modifiying the text of a TabItem with a longer text, the underline blue bar (tab select mark) length doen't update to cover the entire tabitem length, until the item is clicked.

### To Reproduce:
Run the code, and click the button

### Screenshots:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1791230/176160998-d2405e71-04b4-432b-8425-a08d340befc3.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/1791230/176161047-0466eb91-ec15-4d93-94c0-94f31469b6ef.png">

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("TEST")

	tab := container.NewDocTabs()
	tab.Append(&container.TabItem{
		Text: "Test",
		Content: container.NewCenter(
			widget.NewButton("Set Text", func() {
				tab.Items[0].Text = "Longer text to show the bug"
				tab.Refresh()
			}),
		),
	})

	w.SetContent(tab)

	w.Resize(fyne.NewSize(800, 500))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10.0.18363.2212
 - **Go version:** 1.18.2
 - **Fyne version:** 2.2.1

**Comment by dweymouth** [comment]
This got fixed awhile ago in #3159  but forgot to close out the ticket
