### ISSUE TITLE
How do I set the size and position of the window? 

### ISSUE THREAD

**Issue by HeyDon-Lee** [fyne-io/fyne#311]
I want to set the size and position of the window. 
Either it can't be found or it doesn't work.

**Comment by andydotxyz** [comment]
To set the size use Window.Resize().
There is currently no support for setting window position (it is not possible to support that on all platforms so we don’t include it).

**Comment by HeyDon-Lee** [comment]
@andydotxyz 
Window.Resize () has failed.
Maybe I wrote the wrong code. Can you give me an example?

**Comment by andydotxyz** [comment]
Window.Resize(fyne.NewSize(200, 300)) should be all you need.
If this is not working can you provide some more information?

**Comment by HeyDon-Lee** [comment]
Sometimes the size of the generated window is successful, and sometimes what is the failure? 
![image](https://user-images.githubusercontent.com/16282726/59244439-08d11e80-8c47-11e9-89e2-54498b76b9be.png)

**Comment by HeyDon-Lee** [comment]
OS：Windows 10 v1903
Go version：go1.12.5 windows/amd64
GCC version：6.2.0

**Comment by andydotxyz** [comment]
Ah, thank you. There is a known bug that means sometimes the window does not use the size requested. We are fixing it and will have the resolution public in the release next week.

**Comment by HeyDon-Lee** [comment]
Can the author get help from this code?

```go
package main

import (
	"github.com/lxn/walk"
)

func main() {
	window, _ := walk.NewMainWindow()
	window.SetWidth(400)
	window.SetHeight(200)

	// Set position
	window.SetX(500)
	window.SetY(500)

	window.Show()
	window.Run()
}
```

**Comment by andydotxyz** [comment]
Thanks but we do not use the walk backend. It's GLFW but the resize issues are partly due to internal Fyne code that we are working on right now for 1.1 release.

**Comment by sanguohot** [comment]
@andydotxyz I don't want all the platforms to support this feature, just macOS and windows10 are ok for me now. 
So I need to export the `github.com/go-gl/glfw/v3.2/glfw.Window`, then `GetPos` and `SetPos` can be used by `fyne.Window`.
Now it works, I think it is not so ideal, but I don't have time to wait for your official release.

**Comment by xiemeilong** [comment]
Should  setPos and GetPos be added to the desktop package?

**Comment by J7mbo** [comment]
Hi @sanguohot, did you have a fork containing your changes?

**Comment by andydotxyz** [comment]
@J7mbo `Window.Resize` was added to the public API a long time ago

**Comment by J7mbo** [comment]
@andydotxyz Resize yes but I was referencing window positioning with `SetPos`.

**Comment by LucasNoga** [comment]
On fyne/v2 you have this method `window.CenterOnScreen()`

**Comment by lukas-wr** [comment]
https://github.com/fyne-io/fyne/compare/master...lukas-wr:fyne:position

**Comment by J7mbo** [comment]
Looks like that is an invalid commit unfortunately @lukx33.

To bring this back up: we're looking for a way to set a window position on the screen. Not it's size (we can already do that), but providing X and Y coordinates to the window to have it be placed (or moved to) those coordinates.

That does not mean centering the window, btw.
