### ISSUE TITLE
『Feature』Add Demo 

### ISSUE THREAD

**Issue by Ran-Xing** [fyne-io/fyne#3110]
Clash x is a beautiful and easy-to-use proxy tool. [Clash x](https://github.com/yichengchen/clashX)

I'm an ordinary network security engineer. I want to write a tool. I have read your Demo warehouse and searched for a large number of Git warehouses. The development standards are quite different. I hope you can provide a separate warehouse, which only needs the appearance of 'Clash X.Dashboard', but the functions are not needed. If you can, please add a switch button and make more comments(/* Demo */ // Demo). Thank you.

**Comment by andydotxyz** [comment]
I think this is the wrong project for that issue

**Comment by Ran-Xing** [comment]
@andydotxyz Excuse me, I want to use fyne to write tools. Is there a recommended git repo?

**Comment by Ran-Xing** [comment]
What I need is a demo of a standard tool, and java has many beautiful demos.

**Comment by Ran-Xing** [comment]
The tools provided by official website are too single. Your demo, my mac 15.0 installation error, I also want to contribute to the community.

**Comment by Ran-Xing** [comment]
There is another blank place in your secondary menu that is not controlled by the container, under the title and above the container.

**Comment by Ran-Xing** [comment]
I hope you can download clash/clashx windows to experience it.

**Comment by andydotxyz** [comment]
Have you looked at the standard demo (https://github.com/fyne-io/fyne/tree/master/cmd/fyne_demo) or the apps at https://apps.fyne.io?

**Comment by Ran-Xing** [comment]
@andydotxyz I've seen this. I can only read the code, but I can't run it.

**Comment by andydotxyz** [comment]
Perhaps instead of opening a "Add demo" feature request you could share the problem you are experiencing so we can help fix it @Ran-Xing?

**Comment by Ran-Xing** [comment]
Because I searched some fyne related demos on the Google search engine, but the effect they did was not the one I wanted, and then I did it myself, and the effect was very ugly. So if you have the relevant demo to provide, you can reduce a lot of problems. 

My ability is limited, and I don't want to keep asking questions that you think are simple.

**Comment by Ran-Xing** [comment]
Most open source products are maintained by everyone. Thanks to the great open source, I'll try it myself again.

**Comment by andydotxyz** [comment]
> Because I searched some fyne related demos on the Google search engine, but the effect they did was not the one I wanted, and then I did it myself, and the effect was very ugly. So if you have the relevant demo to provide, you can reduce a lot of problems.

The links above take you to around 50 different applications - I can't guess what is more relevant than what might be available there. 

> My ability is limited, and I don't want to keep asking questions that you think are simple.

Consider one of our support channels (https://fyne.io/support) - this issue tracker is not meant for support questions.
