### ISSUE TITLE
cross platform modal

### ISSUE THREAD

**Issue by TudorHulban** [fyne-io/fyne#3112]
I believe Lazarus with Object Pascal supports modal cross platform.
saw #291 but please consider that it is a standard issue for desktop apps. 

### Describe the solution you'd like to see:
cross platform modal window existing in Delphi for 25 years.

**Comment by Jacalz** [comment]
The other issue was closed because we knew that it would be hard to do cross-platform. If there is anything to be added then we should clot obey the discussion there. I’ll close this as a duplicate.

**Comment by andydotxyz** [comment]
It is worth noting for posterity or search engines, that Fyne provides `widget.NewModalPopop` as a helper, this uses our overlay stack to draw over the app.
Doing so with separate windows is not as cross-platform as you may consider.
