### ISSUE TITLE
Container.Remove() from multiple goroutines causes panic

### ISSUE THREAD

**Issue by ErrorNoInternet** [fyne-io/fyne#3113]
### Describe the bug:
Calling Container.Remove() from multiple goroutines at the exact same time causes a panic
Container.Add() seems to be working fine (unless you're trying to add 10k+ items on a 2 fps display then it crashes)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x7bd2b9]

goroutine 78 [running]:
fyne.io/fyne/v2/layout.(*boxLayout).Layout(0xc0003b19d8, {0xc0004e8000, 0x7d, 0xc000167250?}, {0x48732e?, 0x0?})
        /home/ryan/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/layout/boxlayout.go:63 +0x399
fyne.io/fyne/v2.(*Container).layout(...)
        /home/ryan/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/container.go:186
fyne.io/fyne/v2.(*Container).Remove(0xc00037fe40, {0xb0fe98?, 0xc0003f9e00})
        /home/ryan/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/container.go:139 +0x1fb
main.removeLater({0xb0fe98, 0xc0003f9e00})
        /home/ryan/Downloads/FyneContainerCrash/main.go:43 +0x54
created by main.main
        /home/ryan/Downloads/FyneContainerCrash/main.go:29 +0xf0
exit status 2
```

### To Reproduce:
Example code here: https://go.dev/play/p/pSAsuB7XU-5

Steps to reproduce the behaviour:
1. Create a container
2. Add a ton of objects to that container
3. Launch a goroutine for each object
4. Have each goroutine remove an object from the container at the same time
5. Panic

### Device (please complete the following information):
 - **OS:** Linux (amd64)
 - **Version:** 5.18.7-arch1-1
 - **Go version:** 1.18.3
 - **Fyne version:** 2.2.1

**Comment by cedy** [comment]
I've looked into this, and it seems like race condition happens here https://github.com/fyne-io/fyne/blob/master/container.go#L133-L138
```golang
		removed := make([]CanvasObject, len(c.Objects)-1)
		copy(removed, c.Objects[:i])
		copy(removed[i:], c.Objects[i+1:])

		c.Objects = removed
```
So, there are two solutions that I see, first is to put mutex around that code. Second, is to assign nil to the removed object index. With second approach, we'll also need to check if child is not nil in every layout. 
Both solutions have tradeoffs, and I don't know which one fits fyne philosophy, so I'd appreciate some input from authors/maintainers. 
I have a bit of spare time and would like to contribute somehow.

**Comment by ErrorNoInternet** [comment]
Fixed by https://github.com/fyne-io/fyne/pull/3136
