### ISSUE TITLE
Running a program with root privileges resulted in the runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by FizLast** [fyne-io/fyne#3120]
### Describe the bug:
I need to run program with root privileges for execution some bash command in runtime, but if program has system tray support It crushes. 

### To Reproduce:
1. Compile the code with command "sudo go run main.go"
2. See error

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Linux Ubuntu
 - **Version:** 22.04 LTS (Jammy Jellyfish)
 - **Go version:** go1.18.1
 - **Fyne version:** v2.2.1

**Comment by Jacalz** [comment]
Would you mind sharing the stack trace as well? Without it, we don’t know what or where it is crashing.

Also, I would suggest against running `sudo go run` as you are running both the compilation step and the execution with `sudo`. It is better to build the binary normally and then run with `sudo` if you have to.

**Comment by FizLast** [comment]
Oh, I'm sorry, there is stack trace: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x8cfb76]

goroutine 1 [running, locked to thread]:
github.com/godbus/dbus/v5.(*Conn).export(0xc0005f3860?, 0xc0005f3830?, {0xa138af?, 0x6?}, {0xa1b4de?, 0x10?}, 0xb?)
        /home/fizlast/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/export.go:383 +0x36
github.com/godbus/dbus/v5.(*Conn).exportMethodTable(0x984a80?, 0xc0005f3a88?, {0xa138af?, 0x13?}, {0xa1b4de?, 0x1a?}, 0x30?)
        /home/fizlast/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/export.go:367 +0x11b
github.com/godbus/dbus/v5.(*Conn).ExportSubtreeMethodTable(...)
        /home/fizlast/go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/export.go:346
fyne.io/systray/internal/generated/notifier.ExportStatusNotifierItem(0x0?, {0xa138af, 0x13}, {0xb0bb20?, 0x117bcd0})
        /home/fizlast/go/pkg/mod/fyne.io/systray@v1.10.1-0.20220621085403-9a2652634e93/internal/generated/notifier/status_notifier_item.go:192 +0x338
fyne.io/systray.nativeStart()
        /home/fizlast/go/pkg/mod/fyne.io/systray@v1.10.1-0.20220621085403-9a2652634e93/systray_unix.go:168 +0x69
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003e0620)
        /home/fizlast/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/driver/glfw/loop.go:117 +0xdb
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0000003c0?)
        /home/fizlast/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/driver/glfw/driver.go:164 +0x33
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0000003c0)
        /home/fizlast/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/driver/glfw/window.go:230 +0x2c
main.main()
        /home/fizlast/projects/temp/main.go:26 +0x236
And thanks for the advice.

**Comment by Jacalz** [comment]
Hmm. It looks to me like the crash is in https://github.com/godbus/dbus. Does the same crash happen if you remove the system tray? If it doesn't you can try sending a notification (using `app.SendNotification`).

**Comment by andydotxyz** [comment]
My guess would be that due to a security model the root user cannot connect to the dbus service.
We should not crash in this scenario, good to know if notifications suffers the same as you say @Jacalz.

**Comment by Jacalz** [comment]
Thanks for helping us narrowing down the issue. I suspect that there is some check that notifications are doing but systray doesn't.

**Comment by Bluebugs** [comment]
The notification code is slightly simpler as it is only a one of call. So it connect and check the connection before each notification. Less trouble there.

It might be possible to have a process running as root access the same dbus path, but really it doesn't feel right. I would recommend building things in a two process way. One not root running the UI and one running as root, and making them communicate via some kind of protocol (could be the input/output of a process, a socket, ...). That would be a bit more align with Linux security practice.

**Comment by godstanis** [comment]
If you **_really want_** to run tray app with root privileges on Linux without changing any global dbus/system configs, you can hack your way through (tested on Ubuntu ARM with more complex application, should work on other distros too) with `setuid(1000)` while initializing the application. But the correct way is to run a privileged helper, root GUI is a security issue:

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func downgradePrivileges() {
	if runtime.GOOS != "linux" {
		return
	}

	// sudo adds SUDO_UID env variable with original user id
	if os.Getenv("SUDO_UID") == "" {
		log.Fatal("not running with sudo")
	}
	usrUID, err := strconv.Atoi(os.Getenv("SUDO_UID"))
	if err != nil {
		log.Fatal(fmt.Errorf("sudo_uid is not int: %q: %w", os.Getenv("SUDO_UID"), err))
	}
	if err := syscall.Setuid(usrUID); err != nil {
		log.Fatal(fmt.Errorf("setuid(%d): %w", usrUID, err))
	}
}

func resetPrivileges() {
	if runtime.GOOS != "linux" {
		return
	}

	if err := syscall.Setuid(0); err != nil {
		log.Fatal(err)
	}
}

func main() {
	downgradePriviledges()
	a := app.New()
	w := a.NewWindow("SysTray")
	a.Lifecycle().SetOnStarted(func() {
		resetPriviledges()
	})

	// Set up and run the app normally
}
```

Then you can run the app with modified privileges like this:
```bash
go build -o app .; chmod u+s ./app; sudo -E ./app
```
