### ISSUE TITLE
Iphone incorrect click coordinates in zoomed screen view

### ISSUE THREAD

**Issue by cedy** [fyne-io/fyne#3122]
### Describe the bug:

When using a zoomed display zoom view on IOS, click positions registered in fyne apps are incorrect relative to actual user clicks. Simply, when I click in the center of the screen, fyne registers the click a bit to the top left.
### To Reproduce:
Steps to reproduce the behaviour:
1. Set zoomed view in Settings -> Display & Brightness -> View -> Zoomed
2. Get fyne calc from app store.
3. Click on the top section of any button.
4. See that click is not registered on button clicked. For example, clicking on top section of button with number `5` in fyne calc, you will get button with number `8` clicked.

### Screenshots:

N/A

### Example code:

I believe the bug is in internal driver code, so all fyne IOS apps are susceptible to the bug.

### Device (please complete the following information):
 - **OS:** IOS
 - **Version:** 15.5
 - **Go version:** go1.17.1 darwin/amd64
 - **Fyne version:** v2.2.1 and develop

**Comment by andydotxyz** [comment]
This is now resolved on develop and ready for v2.2.3 as well, thanks @cedy

**Comment by cedy** [comment]
fixed by #3127
