### ISSUE TITLE
Func for deleting item in checkboxes

### ISSUE THREAD

**Issue by tiredsosha** [fyne-io/fyne#3124]
Hello, I'm want to make an app for my home usage. I've added few select boxes and amout of items in checkboxes depends on selected choose. 
I find on API that you can add, but can't delete
Is there any possibility you can add this staff? Or maybe you can help me come up with different solution?
![image](https://user-images.githubusercontent.com/42004251/177422058-6f6d9842-70f0-4bd8-9e89-36de59a7c876.png)
![image](https://user-images.githubusercontent.com/42004251/177422427-cfa74145-4605-431a-abf2-42222027490c.png)

**Comment by andydotxyz** [comment]
Do you mean the `CheckGroup` type?
Yes we could add `Remove` - but in the meantime you can alter the slice directly at `CheckGroup.Options`.

**Comment by Jacalz** [comment]
This has been solved now and is available on the `develop` branch.
