### ISSUE TITLE
Regression in 2.2.2 : Preferences are not parsed at program start

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3125]
### Describe the bug:
Preferences are not read at program startup. Was working just fine in 2.2.1

### To Reproduce:
Run the example program, set some preferences keys/vals. Then restart the program and try to read the keys set before : you get nothing!

### Example code:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("com.example.app")
	w := a.NewWindow("Test")

	key := widget.NewEntry()
	val := widget.NewEntry()

	w.SetContent(container.NewVBox(key, val, container.NewGridWithColumns(2,
		widget.NewButton("Set", func() {
			a.Preferences().SetString(key.Text, val.Text)
		}),
		widget.NewButton("Get", func() {
			val.SetText(a.Preferences().String(key.Text))
		}),
	)))

	w.ShowAndRun()
}
```

### Device (please complete the following information):
 - **OS:** Windows 10
 - **Go version:** 1.18.2
 - **Fyne version:** 2.2.2

**Comment by andydotxyz** [comment]
Resolved ready for a speedy `v2.2.3`
