### ISSUE TITLE
[question] why the apps made by this UI toolkit are not really Material Design alike as it claims to be ? 

### ISSUE THREAD

**Issue by c1ngular** [fyne-io/fyne#3128]
it says "Cross platform GUI in Go inspired by Material Design" , but the demo apps look not really "Material Design" alike ?  even the official one , i have compared with Flutter Demo and Gio demo app , later two look a lot nicer ? 

thanks

**Comment by junmaqiang** [comment]
you're right

**Comment by Bluebugs** [comment]
It is mostly in the details and we got a design review from a professional designer of Fyne toolkit that should help us address those for next release.

**Comment by andydotxyz** [comment]
The words "inspired by" do not mean "implementation of", there is no promise that a Fyne app will be exactly what Google defined. Some times it is subjective but some times the design just does not adapt well to cross-platform.
In future releases, as @Bluebugs says, it will diverge more.

**Comment by c1ngular** [comment]
@Bluebugs @andydotxyz I am excited that a professional designer is getting involved , not nessecerily to be aligned with Material design or standards , but always nice to see its getting more visually beautiful .
