### ISSUE TITLE
How to set widget with a custom size

### ISSUE THREAD

**Issue by nzx824** [fyne-io/fyne#3133]
I know the FYNE  can't set widget width and height in a normal way,
but if this project has 17.6k stars ,that should be a way make people accept this lib,
I truely think that set custom size widget is a necessity to a ui lib,
so, is there anyone who can tell me how to set a  custom widget?
after to read the document, i can not find a good way to set it freedom,
I can't belive a ui lib has 17.6k stars ,is really hard to use...

**Comment by andydotxyz** [comment]
The size of all items is set by the parent container's layout. You can read more at https://developer.fyne.io/explore/container.

**Comment by nzx824** [comment]
> The size of all items is set by the parent container's layout. You can read more at https://developer.fyne.io/explore/container.
> 
> This means if you're looking for different sizes on your widget then you might want a different container.

I see this answer in other issue,too!!! but the content of this url, do not tell me how to set a custom size of the parent container!!!
Is the funtion named Moveto that can set the custom size?
Although I have not to test this MoveTo func ,but I think it is not what I want

**Comment by nzx824** [comment]
> 	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	ctn := container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	)
	w.SetContent(ctn)

	w.ShowAndRun()


come on! JUST TELL ME How to set the var "ctn" 's width or height please!

**Comment by andydotxyz** [comment]
Every container is, just like widget, controlled in size and position by its parent. This is true for all items up to the one at the window content, which will always be the full width and height of the window.

**Comment by andydotxyz** [comment]
No that is not what I mean.
In Fyne the way we layout out components is to decide how space should be used - where should things be minimum size, where should they fill? Then there are things like Grid which split evenly and Split which give user control. https://developer.fyne.io/explore/layouts

If you want further support please consider one of our support channels, this issue tracker is for feature requests and bug reports.
