### ISSUE TITLE
table dynamic AddColumn method

### ISSUE THREAD

**Issue by ddkwork** [fyne-io/fyne#3138]
### Is your feature request related to a problem? Please describe:

can  not dynimac  add table  AddColumn 

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see:

![image](https://user-images.githubusercontent.com/19886504/179123837-4ec59db8-2855-429f-a45c-a3291ebd7656.png)

![image](https://user-images.githubusercontent.com/19886504/179124333-9bac327b-02a6-448c-8124-793884a22b30.png)

**Comment by andydotxyz** [comment]
Yes you can add columns dynamically - just add them to the data (return a higher number of the column value in your first "size" callback).
If you change the data backing table then call `Refresh()` it will update accordingly. Table, like List and Tree are backed by data and so will reflect any change you make in the underlying data.

**Comment by ddkwork** [comment]
> Yes you can add columns dynamically - just add them to the data (return a higher number of the column value in your first "size" callback). If you change the data backing table then call `Refresh()` it will update accordingly. Table, like List and Tree are backed by data and so will reflect any change you make in the underlying data.

thank you . and i have a problem is the table layout in apptable page is  show non full screen. sorry my bad english, 
so please see this gif.

[screenshots.zip](https://github.com/fyne-io/fyne/files/9118169/screenshots.zip)

https://github.com/ddkwork/gui
