### ISSUE TITLE
Disabled low priority button should not have background color changed

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3139]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Not really a bug, rather a visual enhacement/modification:

Low priority button, when disabled, should not have its background color modified (grayed), bit only its Text and/or Icon.

This is in adequation with material specs.

### How to reproduce

NA

### Screenshots

<img width="74" alt="unknown" src="https://user-images.githubusercontent.com/1791230/179261402-c4e305d1-1f7e-43ad-81b5-c2fcb897be9b.png">
<img width="99" alt="unknown-1" src="https://user-images.githubusercontent.com/1791230/179261415-6f710bbf-6455-4e3b-abd7-bc67aad38eee.png">
<img width="595" alt="unknown-2" src="https://user-images.githubusercontent.com/1791230/179261426-a80d05a9-2e95-4391-8150-c7e556c861a2.png">
<img width="585" alt="unknown-3" src="https://user-images.githubusercontent.com/1791230/179261439-a3ca0476-3f7f-497f-944d-7f7c501d56e4.png">

### Example code

NA

### Fyne version

2.2.3

### Go compiler version

1.18.2

### Operating system

Windows

### Operating system version

10

**Comment by Jacalz** [comment]
This is seems like a great idea to me. I think this should be easily solvable.

**Comment by Jacalz** [comment]
This is now fixed on the develop branch. Thanks for the suggestion 🙂
