### ISSUE TITLE
Scroller Mouse Out While Dragging

### ISSUE THREAD

**Issue by okratitan** [fyne-io/fyne#314]
If there has been a mouse down without a mouse up and the scroller is current dragging, it needs to avoid mouse out events.  If you are dragging and you mouse out on the scrollbar current, the scrollbar shrinks and dragging stops.

**Comment by toaster** [comment]
If this is possible we should keeping the dragging state for the whole screen, i.e. if the scrollbar is dragged the mouse may move out of the (wide) scrollbar area and even out of the window without stopping the dragging.
This is how it works for native scrollbars and for the VSCode scrollbars (which I suspect to be non-native), too.

**Comment by andydotxyz** [comment]
Resolved on develop ready for release
