### ISSUE TITLE
how to create webview

### ISSUE THREAD

**Issue by passerbyo** [fyne-io/fyne#3143]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

how to create webview

### Describe the solution you'd like to see.

how to create webview

**Comment by matwachich** [comment]
Not possible yet

**Comment by Jacalz** [comment]
I suspect that this likely is a duplicate, in one way or another, of https://github.com/fyne-io/fyne/issues/116. There is not any plan from our side of implementing any web widget but it should likely be possible if someone wants to.

For questions, please consider using one of the channels described at https://fyne.io/support. We prefer to keep this issue tracker related to bugs and feature requests only.

**Comment by af913337456** [comment]
@andydotxyz  @Jacalz Hi, sir, if i can add the webview to this project successfully, can i push a request and merge to the master branch?

**Comment by Bluebugs** [comment]
I think a web view is a big project in itself that would make sense to have its own repository under fyne.io umbrella.

**Comment by matwachich** [comment]
A simple widget to display html content, without buttons forms or other kind of interactions could a nice addition?

**Comment by andydotxyz** [comment]
If it isn't interactive in any way would it not be nicer to use Markdown? (which we already support)
The benefit of marked up content in that way is that it will match your app instead of looking like a web page embedded in an app :)

**Comment by lukas-wr** [comment]
duplicate #744 

WebView like widget in pure Go without GTK+ dependency => https://github.com/danfragoso/thdwb/blob/master/browser/main.go

**Comment by Fire-Dragon-DoL** [comment]
> If it isn't interactive in any way would it not be nicer to use Markdown? (which we already support) The benefit of marked up content in that way is that it will match your app instead of looking like a web page embedded in an app :)

As a heads up, a webview is useful for when you need to renser content as a webpage because handled by the user. A classic example of this is an email message.

**Comment by andydotxyz** [comment]
> As a heads up, a webview is useful for when you need to renser content as a webpage because handled by the user. A classic example of this is an email message.

Yes, email is a good use-case. When you dig into it you'll find that web for email and web for the internet are not actually the same, though a huge overlap of course.

Personally I have an interest in more safely (and efficiently) rendering semantic email rather than the exact HTML that is received. This is because the way it works right now has so many security risks and accessibility problems!

**Comment by Fire-Dragon-DoL** [comment]
> > As a heads up, a webview is useful for when you need to renser content as a webpage because handled by the user. A classic example of this is an email message.
> 
> Yes, email is a good use-case. When you dig into it you'll find that web for email and web for the internet are not actually the same, though a huge overlap of course.
> 
> Personally I have an interest in more safely (and efficiently) rendering semantic email rather than the exact HTML that is received. This is because the way it works right now has so many security risks and accessibility problems!

I mean, yes, but a dedicated email web view seems even less likely 😂

**Comment by andydotxyz** [comment]
I wrote a bit of a rant about this - maybe you can see where it's heading ;) https://andy.xyz/2024/02/12/dont-control-my-font-size/
