### ISSUE TITLE
How to tell if a window is showing

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#3144]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

yes

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

I create a new window, and I hope to determine whether it has been created before creating a new window. If it has been created, I don't need to recreate it.

**Comment by Jacalz** [comment]
Assuming that I understand your feature request correctly, this is already possible without any more additions to the API.

You create a new window and then hook up the close intercept to just hide it instead. When you want to reuse it, you can simply update the contents in the window and call `.Show()` to make it visible again.

I have an implementation of it available at https://github.com/Jacalz/rymdport/blob/0647d486ea9b4d002c9214f1a6b14e5c9b3804fe/internal/transport/display.go#L36. The code above contains some code that is specific to my application but should give an idea about how it works.

**Comment by junmaqiang** [comment]
thank you @Jacalz
