### ISSUE TITLE
How to draw rounded corners with canvas

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#3145]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

yes

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

<img width="783" alt="99" src="https://user-images.githubusercontent.com/1819457/179399006-96ba4337-aca5-4fa6-854d-9431fe5c3a07.png">

**Comment by Jacalz** [comment]
There is an open PR for adding rounded edges support to Rectangle. See https://github.com/fyne-io/fyne/pull/3121 for more information.

For questions, please consider using one of the channels described at https://fyne.io/support. We prefer to keep this issue tracker related to bugs and feature requests only.
