### ISSUE TITLE
fyne 2.2.0 web driver “fyne serve”  cant start fyne example for test

### ISSUE THREAD

**Issue by kcyx** [fyne-io/fyne#3147]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Is there any web driver “fyne serve” demo to run?
Can't start fyne example for browser test.

### How to reproduce

1, fyne/cmd/fyne_demo# fyne serve fail

### Fyne version

Fyne 2.2.3

### Go compiler version

1.18.3

### Operating system

Linux

### Operating system version

Ubuntu 20.04

**Comment by Bluebugs** [comment]
What error message does `fyne serve` return?

**Comment by kcyx** [comment]
1, For fyne_demo return like below:
2022/07/19  Fyne error:  Failed to inject metadata init file, omitting metadata
2022/07/19  Cause: fyne version not found

2, Other example go run just fine, but serve like:
Missing application icon at "fyne-example/widget/tabcontainer/Icon.png"

Adding Icon.png just won't work

**Comment by Bluebugs** [comment]
That first error message seems like you are using an older version of fyne or that the code is an older version. Please update both first.

**Comment by kcyx** [comment]
Sorry to make a mistake using old version demo.
After update to the newest fyne demo, I encounter the same issue as #3120.
Then I remove the system tray, the demo run fine using go run.
But fyne serve has the following error:
GopherJS 1.17.2+go1.17.9 requires a Go 1.17.x distribution, but found version go1.18.3
GopherJS 1.17.2+go1.17.9 requires a Go 1.17.x distribution, but found version go1.18.3
error building application: exit status 1

Version:
go 1.18.3
fyne  v2.2.3

**Comment by Bluebugs** [comment]
For GopherJS, you need to follow the details of https://github.com/gopherjs/gopherjs and it requires to have a double Go installation. From there README, they recommend the following at the moment:
```
go get golang.org/dl/go1.17.1
go1.17.1 download
export GOPHERJS_GOROOT="$(go1.17.1 env GOROOT)"  # Also add this line to your .profile or equivalent.
```

**Comment by kcyx** [comment]
Thanks for the guidance, after downgraded to go 1.17.1, fyne serve finally works. Maybe it will be more convenient to add these requirement on document pages for users who need run web apps.

However, the web version is significantly slow than other platform that many its components are not working properly, like the widgets, collections and containers sub-tabs.
As far as I know, others golang GUI such as go-app, gio run fast on browser.
Is there any technical implementation that fyne can borrowed from others to fix it?

**Comment by Bluebugs** [comment]
It seems the documentation from gopherjs need to indeed be reproduced into fyne documentation. Will put that on the todo list.

The web version is still in beta as wasm is also in beta at this point. We know performance has to be improved and that some of the widget also need to be ported to the web too. This is on the todo list at the moment. We also would like to see Chrome get a better support of wasm as at the moment we have to fallback to GopherJS (which is an amazing technology, but wasm has potential for more optimization).

**Comment by kcyx** [comment]
Thanks for your guys‘ hard jobs and great work.
Looking forward to the formal release of web platform so that can used it in our projects soon.
Please don't hesitate to let me know if anything I can do for the development. (myself mainly back end developer)

**Comment by Bluebugs** [comment]
You can look at open issue with the label `driver: web`. At the moment, the focus would be more on the features parity as you will see from that list of open issues.

**Comment by xfengw** [comment]
go 1.22.5  fyne 2.5.0
PS F:\Blocking\blockClient> fyne serve 
# blockClient
d:\gocache\82\82f54618f27335c32dd92007286964ecee0a22566768a97292f33d1ccd6471bc-d(app.syso): unsupported arch 11

error building application: exit status 1

**Comment by xfengw** [comment]
> What error message does `fyne serve` return?

go 1.22.5 fyne 2.5.0
PS F:\Blocking\blockClient> fyne serve
d:\gocache\82\82f54618f27335c32dd92007286964ecee0a22566768a97292f33d1ccd6471bc-d(app.syso): unsupported arch 11

**Comment by andydotxyz** [comment]
Please open a new issue instead of commenting on old, unrelated items.
