### ISSUE TITLE
Auto Complete on SelectEntry

### ISSUE THREAD

**Issue by mhkarimi1383** [fyne-io/fyne#3149]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I would love to be able to have auto complete in SelectEntry field or other fields with a custom function

### Is it possible to construct a solution with the existing API?

Yes, changing place holder dynamically 

### Describe the solution you'd like to see.

Hint on placeholder while user is typing using Fuzzy Search

**Comment by matwachich** [comment]
Check fyne-x, there is an autocompletion Entry custom widget.
It's very simple to implement

**Comment by mhkarimi1383** [comment]
> Check fyne-x, there is an autocompletion Entry custom widget. It's very simple to implement

I have tried that but it's showing me all of the selections when calling `ShowCompletion` function

**Comment by Jacalz** [comment]
There is an example in the fyne-x repository about using it (see https://github.com/fyne-io/fyne-x#completionentry).  If you find any bugs using it, you should consider opening a bug over there :)

However, I still think this feature request is a good one. We may want to implement this at some point.

**Comment by mhkarimi1383** [comment]
I have made this by using a Fuzzy Search Library and changing items dynamically using OnChange. Sorry I was unavailable for some time
