### ISSUE TITLE
When creating an Entry with Monospace style, the initial text is not displayed as monospace until Entry is clicked

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3150]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Monospace Entry with initial Text doesn't display correctly until clicked.

### How to reproduce

Create an Entry and set Monospace style, then set some initial Text to the Entry.
Run the program and you see that at first, the text is displayed in standard font, then it is converted to Monospace when you tap the Entry.

### Fyne version

2.2.3

### Go compiler version

1.18.2

### Operating system

Windows

### Operating system version

10

**Comment by andydotxyz** [comment]
Can you provide the code which is alluded to please? It will help to ensure we can replicate and resolve.

**Comment by matwachich** [comment]
Issue closed.
Was here to add reproducer code and I saw that the issue has been adressed somehow...
