### ISSUE TITLE
Adding adjustable column width using clickable handles

### ISSUE THREAD

**Issue by anclancy** [fyne-io/fyne#3152]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I am only a couple months in to using Fyne and really appreciate the effort that has been put forth in building a Golang GUI based on Material design. I am building out a Golang application with a GUI and decided to use Fyne as a solution for my project. Coming from web applications. I found the Fyne SDK faster to ramp up on then other options out there. All the feature in the current release have met my requirements for the application except the table widget. This is the primary widget for my application as the user manages all the task by selection from the table widget.
Table widget is still at a basic x and y list level. Needs to be a more robust table widget to handle enterprise solution. For example, in addition to sorting and header enhancements as mentioned in Issue #1658 “Add headers to table/tree widget #1658” adding adjustable column width and cell word wrap to manage extended text within a cell.
Thank you

### Is it possible to construct a solution with the existing API?

I have also built a pseudo header with a second table, but it's not very clean. Horizontal scrolling needs to be synchronized to improve user experience when columns exceed width of window. Also, will be writing click events in pseudo header to handle sorting, at this time I am manually handling the column widths with static units. 

### Describe the solution you'd like to see.

In addition to sorting and table header adding adjustable column width using clickable handles on each side of the column and cell word wrap for extended text length within a table cell.

**Comment by ddkwork** [comment]
col and row ontapevent,sort,col sep hide,header,always top cell etc feature need add.
see

**Comment by andydotxyz** [comment]
Please don't add multiple requests in one ticket. These are not similar issues.
Additionally word wrap causing dynamically different size cells will never be baked into Table as it breaks the caching.
a feature request for `SetRowHeight` would allow you to do it in your app code if desired.

**Comment by rkmpa** [comment]
@anclancy I recently had to implement a solution for the clickable handles to adjust colum width of a table. I ended up implementing the table as a collection of lists that are glued together with `HSplit` containers. It works reasonably well for small tables although I haven't tested out various edge cases. I may build a widget for the draggable handles this week and will update the ticket here.

**Comment by andydotxyz** [comment]
> a feature request for `SetRowHeight` would allow you to do it in your app code if desired.

Just for reference that element is added for v2.3.0, making some slightly more custom table rendering. Though the main topic of this ticket is still quite pertinent.

**Comment by andydotxyz** [comment]
This has landed on develop and will be in v2.4.0
