### ISSUE TITLE
fyne table not refreshing inside a tab

### ISSUE THREAD

**Issue by Wilm0rien** [fyne-io/fyne#3169]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

It seems that fyne does not update tables inside tabs. see [02:37](https://youtu.be/eYUNjsDTSl8?t=157)
Note that this problem occurs only after the app is open for a while (for example 120 seconds).

### How to reproduce

Note: reproduction only with windows OS

1. compile example code below
2. open some of the tabs and see all tables refreshing normally
3. then wait some time (120s)
4. go through all tabs again. this time you will see tables not being refreshed correctly (see  [02:37](https://youtu.be/eYUNjsDTSl8?t=157) in the video)

### Screenshots

https://user-images.githubusercontent.com/20628481/184477944-3af332e4-d5bf-4e20-8072-05824f72c113.mp4

### Example code

```
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
	"image/color"
)

func main() {
	app := app.New()
	tabPtr := container.NewAppTabs(make([]*container.TabItem, 0, 5)...)
	tabPtr.SetTabLocation(container.TabLocationLeading)
	maintab := container.New(
		layout.NewGridLayout(1), tabPtr)
	windowPtr := app.NewWindow("reproduce table refresh problem")
	windowPtr.SetContent(maintab)
	windowPtr.Resize(fyne.NewSize(1790, 800))
	windowPtr.SetMaster()
	app.Settings().SetTheme(theme.DarkTheme())
	app.Settings().Scale()
	for i := 0; i < 5; i++ {
		tabName := fmt.Sprintf("testTab%d", i)
		tabPtr.Items = append(tabPtr.Items, container.NewTabItem(tabName, createTab(i)))
	}
	tabPtr.Refresh()
	windowPtr.Show()
	windowPtr.ShowAndRun()
}

func createTab(tabId int) fyne.CanvasObject {
	docTab := container.NewDocTabs(make([]*container.TabItem, 0, 5)...)
	for i := 0; i < 5; i++ {
		subtabName := fmt.Sprintf("subtab%d", i)
		newTab := container.NewTabItem(subtabName, createtable(tabId, i))
		docTab.Append(newTab)
	}
	return docTab
}

func createtable(tabId int, subtabId int) fyne.CanvasObject {
	rows := 10
	columns := 5
	mainTable := widget.NewTable(
		func() (int, int) { return rows, columns },
		func() fyne.CanvasObject {
			newText := canvas.NewText("", color.NRGBA{0, 0x80, 0, 0xff})
			//newText.Alignment = fyne.TextAlignCenter
			return newText
		},
		func(id widget.TableCellID, cell fyne.CanvasObject) {
			text := cell.(*canvas.Text)
			txt, col := GetCellStr(id.Row, id.Col, tabId, subtabId)
			text.Color = col
			text.Text = txt
		})
	for i := 0; i < columns; i++ {
		mainTable.SetColumnWidth(i, 200)
	}
	return container.NewBorder(nil, nil, widget.NewLabel("test"), nil, mainTable)
}

func GetCellStr(rowIdx int, colIdx int, tabId int, subtabId int) (string, color.NRGBA) {
	redValue := 0xff
	greenValue := 0xff
	blueValue := 0xff
	colValue := (rowIdx + 2) * 10
	if colValue > 255 {
		colValue = 255
	}
	if subtabId%2 == 0 {
		redValue = colValue
	} else {
		greenValue = colValue
	}
	if tabId%2 == 0 {
		blueValue = colValue
	} else {
		redValue = colValue
	}
	col := color.NRGBA{uint8(redValue), uint8(greenValue), uint8(blueValue), 0xff}
	txt := fmt.Sprintf("row %d, col %d tab %d, subtab %d", rowIdx, colIdx, tabId, subtabId)
	return txt, col
}


```

### Workaround

to workaround this problem every time a tab is created the OnSelected() callback of the tab object needs to be implemented to call a recursive search function with the item parameter
```
	docTab.OnSelected = func(item *container.TabItem) {
		recurseRefresh(item)
	}
```

recurseRefresh recursively searches for all tables inside the item hierarchy to find a table. 

note that refreshing the table does not solve the problem: instead Hide() and Show() need to be called in succession to make the table fully visible again.

```
func recurseRefresh(item *container.TabItem) {
	if _, ok := item.Content.(*fyne.Container); ok {
		recurseRefreshTable(item)
	} else if cont3, ok2 := item.Content.(*container.DocTabs); ok2 {
		for _, subTabItem := range cont3.Items {
			recurseRefreshTable(subTabItem)
		}
	} else if cont5, ok4 := item.Content.(*container.AppTabs); ok4 {
		for _, subTabItem := range cont5.Items {
			recurseRefreshTable(subTabItem)
		}
	} else if tab, ok := item.Content.(*widget.Table); ok {
		tab.Hide()
		tab.Show()
	}
}

func recurseRefreshTable(item *container.TabItem) {
	if cont, ok := item.Content.(*fyne.Container); ok {
		recurseRefreshContainer(cont)
	} else if _, ok2 := item.Content.(*container.DocTabs); ok2 {
		recurseRefresh(item)
	} else if _, ok4 := item.Content.(*container.AppTabs); ok4 {
		recurseRefresh(item)
	} else if tab, ok := item.Content.(*widget.Table); ok {
		tab.Hide()
		tab.Show()
	}
}

func recurseRefreshContainer(cont *fyne.Container) {
	for _, object := range cont.Objects {
		if cont2, ok := object.(*fyne.Container); ok {
			recurseRefreshContainer(cont2)
		} else if cont3, ok2 := object.(*container.DocTabs); ok2 {
			for _, subTabItem := range cont3.Items {
				if cont4, ok3 := subTabItem.Content.(*fyne.Container); ok3 {
					recurseRefreshContainer(cont4)
				}
			}
		} else if cont5, ok4 := object.(*container.AppTabs); ok4 {
			for _, subTabItem := range cont5.Items {
				if cont6, ok5 := subTabItem.Content.(*fyne.Container); ok5 {
					recurseRefreshContainer(cont6)
				}
			}
		}
		if tab, ok := object.(*widget.Table); ok {
			tab.Hide()
			tab.Show()
		}
	}
}

```

### Fyne version

2.2.3

### Go compiler version

go 1.18

### Operating system

Windows

### Operating system version

Windows 10.0.19043

**Comment by andydotxyz** [comment]
Can you please create a small code sample that shows the error so we can eliminate all your app specific code?
Is it right to assume that you're saying `Table.Refresh()` works for a while but then stops working?

**Comment by Wilm0rien** [comment]
ok sure, I'll provide the code sample. 
Currently I can only tell the problem only appears when switching between tabs which contain tables after some time delay has passed. Then the table appears empty inside the selected tab as shown in the video.

**Comment by Wilm0rien** [comment]
hi @andydotxyz !

I created the code sample as requested and updated the description above! Let me know if this is sufficient for you!

BR
Wilm0rien

**Comment by andydotxyz** [comment]
There have been some fixes in table, can you still replicate this using the latest version on "develop" branch?

**Comment by Wilm0rien** [comment]
I just did 
`go get fyne.io/fyne/v2@develop
` 
and run the code snippet again: _but the problem remains the same._

additionally I found that the dev branch is actually making it worse: additionally to the original problem now only the first column of a table is visible when you open a tab with a table in it. if you want to see more cells you have to click in the table. 

In the meantime I implemented a workaround which works for me and added it to the description.

**Comment by andydotxyz** [comment]
Would it be possible to test against latest develop please? There have been more fixes to caching on table...

**Comment by Wilm0rien** [comment]
it looks better now! the initial problem seems to be solved!

I used version 2.2.5-0.20221127133934-a1875102133d

however **the example code above did not initially display the full table:** it became visible after clicking on a cell. 

see results [here](https://www.youtube.com/watch?v=4itwt_5CkQk)

**Comment by andydotxyz** [comment]
I cannot replicate this on develop using Windows (or other OS)
