### ISSUE TITLE
Add a Scaling Container

### ISSUE THREAD

**Issue by mike-ward** [fyne-io/fyne#3171]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Sometimes I want to make parts of my UI smaller than what is standard. For instance, the toolbar is too big, comparatively speaking, to other elements in the UI for my purposes. I find myself wanting to scale down the toolbar in those instances. I'm pretty new to Fyne so maybe there's a way to do this but it's not apparent to me. Also, I'm not talking about scaling the whole app, I see there's support for that, just a portion.

### Is it possible to construct a solution with the existing API?

Again, I'm new to Go and Fyne so I haven't been able to work out a way of scaling a portion of my app.

### Describe the solution you'd like to see.

Couple of thoughts here.

- A scaling container. Works like NewMax() but has a scaling property.
- Modify NewMax() to have a scaling property

Kind of new at this UI framework and coming from Avalonia/WPF so I tend to still think in those terms.

**Comment by andydotxyz** [comment]
I'm not sure about this request. The point of a standard set of widgets, and standard metrics, is that the items will always be scaled according to the user settings / OS configuration - and will magically line up when packed into containers. 
https://developer.fyne.io/architecture/widgets#content-padding

By adding scaling into a portion of the API this breaks.
That said, the toolbar is super simple - you could implement one in your app that does not conform to the standard widget layout and loaded theme if that is what you desire.

**Comment by andydotxyz** [comment]
Alternatively if you believe the toolbar design is wrong and should be smaller, feel free to open a ticket to discuss that topic ;)

**Comment by mike-ward** [comment]
The https://developer.fyne.io/architecture/widgets#content-padding link answers a lot of questions. The framework makes much more sense to me now. Focus on behavior and leave the rendering to us (kind of  sounds like a musical jingle).

One feature request I encounter frequently is an adjustable font size. Users tend to be fussy about that for whatever reason. I see there's a `fyne_settings` app that changes the scale globally but that probably won't work for my users. Is there a way to change scaling on a per-app basis? (I can open a separate discussion on this if desired)

**Comment by andydotxyz** [comment]
Instead of `fyne_scale` you can set the environment `FYNE_SCALE` where 1.0 is normal, 0.8 is smaller text and 1.2 is bigger
