### ISSUE TITLE
Cleanup for Cloud Preferences

### ISSUE THREAD

**Issue by itsjustdel** [fyne-io/fyne#3173]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Whilst running multiple tests for CloudPreferences my code fails as the context cannot be cleaned before a new instance is setup

### Is it possible to construct a solution with the existing API?

It is not possible as far as I'm aware to construct a solution with the existing API.

### Describe the solution you'd like to see.

A `Cleanup` hook for `CloudPreferences`  which would allow code to tidy up resources.

**Comment by andydotxyz** [comment]
This was resolved on develop
