### ISSUE TITLE
Packaging issue when installing fyne.io/fyne/v2/cmd/fyne@latest

### ISSUE THREAD

**Issue by kangnade** [fyne-io/fyne#3180]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

System: MAC OS
Editor: VSCode with GO Extension
In Terminal:
`go install fyne.io/fyne/v2/cmd/fyne@latest`
after installing, and then execute below command
`which fyne`
result yields:
`fyne not found`

I have also tried below command:
`go get -u fyne.io/fyne/v2/cmd/fyne@latest`
still getting
`fyne not found`

Any suggestion as how to fix it?

Thanks!

### How to reproduce

1. Type: `go install fyne.io/fyne/v2/cmd/fyne@latest`
2. Type: `which fyne`
3. `go get -u fyne.io/fyne/v2/cmd/fyne@latest`
4. Type: `which fyne`

### Example code

1. Type: `go install fyne.io/fyne/v2/cmd/fyne@latest`
2. Type: `which fyne`
3. `go get -u fyne.io/fyne/v2/cmd/fyne@latest`
4. Type: `which fyne`

### Fyne version

V2

### Go compiler version

1.19 darwin

### Operating system

macOS

### Operating system version

macOS Monterey 12.5

**Comment by Jacalz** [comment]
You likely don’t have the GOBIN path added to your PATH variable. I suspect it is https://github.com/golang/go/issues/39531 that comes back to bite you.

**Comment by kangnade** [comment]
> You likely don’t have the GOBIN path added to your PATH variable. I suspect it is [golang/go#39531](https://github.com/golang/go/issues/39531) that comes back to bite you.

Yes sir, it appears that my go env PATH variable is very messed up that it is not pointing to (go env GOPATH)/bin, but now I am having trouble resetting that PATH….

**Comment by Jacalz** [comment]
Thanks for confirming. I’ll go ahead and close this then. I suspect that you might want to follow something like http://stackoverflow.com/questions/28741651/ddg#28741724.
