### ISSUE TITLE
Window.Fullscreen() return false on window close

### ISSUE THREAD

**Issue by blaize** [fyne-io/fyne#3192]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I want to save if the window is fullscreen or not before closing the application, and restore this state on next startup.
The function Window.Fullscreen() always return false in the Window.SetCloseIntercept() function callback.
The width and height are correct.

### How to reproduce

* Create an app, then a window.
* SetCloseIntercept() on this windows to print Fullscreen() result
* Run the application.
* Set the application in fullscreen.
* Close the app.
* It print false.

### Example code

```
a := app.New()
w := a.NewWindow("fullscreen test")

w.SetCloseIntercept(func() {
	fmt.Println(w.FullScreen())
	w.Close()
})
w.ShowAndRun()
```

### Fyne version

fyne.io/fyne/v2 v2.2.3

### Go compiler version

1.18.4

### Operating system

Windows

### Operating system version

Windows 11

**Comment by andydotxyz** [comment]
I cannot replicate here.
How are you setting the window to full screen?

**Comment by blaize** [comment]
I just click on the square between the X and the - at the top right of the window.

**Comment by andydotxyz** [comment]
Ah, that is not full screen - that is maximised.
The to set fullscreen call `Window.SetFullScreen(true)` and you'll see the difference.

**Comment by blaize** [comment]
Ah ok, thanks for the reply.
And there is a way to catch the maximised state of the window ?

**Comment by andydotxyz** [comment]
No we don't expose any of the APIs for maximise/minimise. 
Perhaps this ticket is what you really want? https://github.com/fyne-io/fyne/issues/554
