### ISSUE TITLE
Resizing tables in UI

### ISSUE THREAD

**Issue by Cookie04DE** [fyne-io/fyne#3199]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Sometimes the user of an app wants to change the width of table columns (to concentrate on of them at a time or ignore one temporarily). Currently they are unable to do so.

### Is it possible to construct a solution with the existing API?

No, you can only change the width programmatically. There is no UI element for the user to do so.

### Describe the solution you'd like to see.

Add a way for the user to change the width of a table column by dragging the column border similar to the split container.

**Comment by Jacalz** [comment]
I think this likely is a duplicate of https://github.com/fyne-io/fyne/issues/3152.

**Comment by Cookie04DE** [comment]
Yes it is. Sorry for bothering you
