### ISSUE TITLE
use the theme change the text size when mouse in every time has a panic result.

### ISSUE THREAD

**Issue by ddkwork** [fyne-io/fyne#3205]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

use the theme change the text size when mouse in every time,panic:

fatal error: concurrent map writes

////////////////////////////////////
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 20 [running, locked to thread]:
fyne.io/fyne/v2/internal/painter.CachedFontFace({0x0, 0x0, 0x0, 0x0, 0x0}, 0xc000299780)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:70 +0x46d
fyne.io/fyne/v2/internal/painter.measureText({0xc0025cb258, 0x3}, 0x25cb258?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:145 +0xdd
fyne.io/fyne/v2/internal/painter.RenderedTextSize({0xc0025cb258, 0x3}, 0xb070d0d4?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:122 +0x9d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize(0x7ff7b1760fca?, {0xc0025cb258?, 0xc0002998b8?}, 0xb0ac8748?, {0x0, 0x0, 0x0, 0x0, 0x0})      
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/driver.go:71 +0x57
fyne.io/fyne/v2.MeasureText({0xc0025cb258, 0x3}, 0x3?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/text.go:47 +0x88
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds.func1({0xc0004025c0?, 0x1, 0x7ff7b072ca2c?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/richtext.go:398 +0x748
fyne.io/fyne/v2/widget.(*RichText).updateRowBounds(0xc000452160)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/richtext.go:411 +0x103
fyne.io/fyne/v2/widget.(*RichText).Refresh(0xc000452160)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/richtext.go:89 +0x1e
fyne.io/fyne/v2/widget.(*Label).Refresh(0xc00044c240)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/label.go:97 +0x13e
fyne.io/fyne/v2/internal/app.ApplyThemeTo({0x7ff7b18727d8?, 0xc00044c240?}, {0x7ff7b1874748?, 0xc00044a000?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:29 +0x123
fyne.io/fyne/v2/internal/app.ApplyThemeTo({0x7ff7b1871ff8, 0xc000424300}, {0x7ff7b1874748, 0xc00044a000})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:23 +0x245
fyne.io/fyne/v2/internal/app.ApplyThemeTo({0x7ff7b1871ff8, 0xc000424480}, {0x7ff7b1874748, 0xc00044a000})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:23 +0x245
fyne.io/fyne/v2/internal/app.ApplyThemeTo({0x7ff7b1871ff8, 0xc000424740}, {0x7ff7b1874748, 0xc00044a000})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:23 +0x245
fyne.io/fyne/v2/internal/app.ApplyThemeTo({0x7ff7b1871ff8, 0xc000424c80}, {0x7ff7b1874748, 0xc00044a000})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:23 +0x245
fyne.io/fyne/v2/internal/app.ApplySettingsWithCallback({0xc000299f90?, 0xc000299f30?}, {0x7ff7b18742a8?, 0xc0003a2770?}, 0x7ff7b17a9d28)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/app/theme.go:43 +0xca
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/loop.go:241 +0x197
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/loop.go:226 +0xea

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable

goroutine 6 [chan receive, 1 minutes]:
fyne.io/fyne/v2/test.NewApp.func1()
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/test/testapp.go:117 +0x45
created by fyne.io/fyne/v2/test.NewApp
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/test/testapp.go:115 +0x351

goroutine 7 [syscall, 1 minutes, locked to thread]:
syscall.SyscallN(0xc000051c10?, {0xc000051c28?, 0xc000042000?, 0x4?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:557 +0x109
syscall.Syscall6(0x0?, 0xc00005a000?, 0x0?, 0xc000051cd0?, 0x3?, 0xc000396280?, 0x0?, 0xe00000003a6cd?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:501 +0x50
syscall.getQueuedCompletionStatus(0xc000051d10?, 0x7ff7b06c66fd?, 0xc00005e780?, 0xc000051e40?, 0xffffffff)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:836 +0x8a
syscall.GetQueuedCompletionStatus(0xc000396280?, 0xc00001cb40?, 0xc000051d6c, 0xfff?, 0x0?)
        C:/Program Files/Go/src/syscall/syscall_windows.go:1277 +0x45
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000396280)
        C:/Users/Admin/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/windows.go:398 +0x7a
created by github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/Admin/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/windows.go:48 +0x1d6

goroutine 8 [chan receive, 1 minutes]:
fyne.io/fyne/v2/app.watchFile.func1()
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/app/settings_desktop.go:42 +0x111

goroutine 18 [syscall, 1 minutes, locked to thread]:
syscall.SyscallN(0xc00042dc10?, {0xc00042dc28?, 0xc000042000?, 0x4?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:557 +0x109
syscall.Syscall6(0x0?, 0xc00005a000?, 0x0?, 0xc00042dcd0?, 0x3?, 0xc000424000?, 0x0?, 0x1a00000001bc69?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:501 +0x50
syscall.getQueuedCompletionStatus(0xc00042dd10?, 0x7ff7b06c66fd?, 0xc000422060?, 0xc00042de40?, 0xffffffff)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:836 +0x8a
syscall.GetQueuedCompletionStatus(0xc000424000?, 0xc00040c150?, 0xc00042dd6c, 0xfff?, 0x0?)
        C:/Program Files/Go/src/syscall/syscall_windows.go:1277 +0x45
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000424000)
        C:/Users/Admin/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/windows.go:398 +0x7a
created by github.com/fsnotify/fsnotify.NewWatcher
        C:/Users/Admin/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/windows.go:48 +0x1d6

goroutine 19 [chan receive, 1 minutes]:
fyne.io/fyne/v2/app.watchFile.func1()
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/app/settings_desktop.go:43 +0x6c
created by fyne.io/fyne/v2/app.watchFile
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/app/settings_desktop.go:42 +0x111

goroutine 21 [select]:
fyne.io/fyne/v2/internal/async.(*UnboundedFuncChan).processing(0xc000416150)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/async/chan_func.go:45 +0xf1
created by fyne.io/fyne/v2/internal/async.NewUnboundedFuncChan
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/async/chan_func.go:22 +0xf8

goroutine 22 [chan receive]:
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/common/window.go:34 +0x4d
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window.go:942 +0x136

goroutine 658 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc003270140)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/loop.go:71 +0x111
fyne.io/fyne/v2/internal/driver/glfw.(*window).RescaleContext(0xc00043e000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window.go:909 +0x56
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).reloadScale(0xc00044a000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/canvas.go:193 +0x113
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1.1
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/loop.go:247 +0x85

goroutine 1 [running, locked to thread]:
fyne.io/fyne/v2/internal/painter.CachedFontFace({0x0, 0x0, 0x0, 0x0, 0x0}, 0xc00278b680)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:70 +0x46d
fyne.io/fyne/v2/internal/painter.measureText({0x7ff7b1869850, 0x1}, 0xb0b05566?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:145 +0xdd
fyne.io/fyne/v2/internal/painter.RenderedTextSize({0x7ff7b1869850, 0x1}, 0x349a40?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/painter/font.go:122 +0x9d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).RenderedTextSize(0xc00278b7c8?, {0x7ff7b1869850?, 0xc00278b7b8?}, 0xb099e491?, {0x0, 0x0, 0x0, 0x0, 0x0})      
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/driver.go:71 +0x57
fyne.io/fyne/v2.MeasureText({0x7ff7b1869850, 0x1}, 0x43c300?, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/text.go:47 +0x88
fyne.io/fyne/v2/widget.(*RichText).charMinSize(0x0?, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/richtext.go:130 +0x85
fyne.io/fyne/v2/widget.(*entryRenderer).MinSize(0xc000424580)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/entry.go:1316 +0x75
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0xc00044fa00?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/widget.go:90 +0x2e
github.com/fpabl0/sparky-go/swid.(*TextField).MinSize(0xc00044fa00)
        C:/Users/Admin/go/pkg/mod/github.com/fpabl0/sparky-go@v0.0.0-20220803072144-1a0971955531/swid/text_field.go:71 +0x34
github.com/fpabl0/sparky-go/swid.(*formFieldRenderer).MinSize(0xc00009c070)
        C:/Users/Admin/go/pkg/mod/github.com/fpabl0/sparky-go@v0.0.0-20220803072144-1a0971955531/swid/form_field.go:146 +0x31
fyne.io/fyne/v2/widget.(*BaseWidget).MinSize(0x7ff7b1736ae0?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/widget/widget.go:90 +0x2e
fyne.io/fyne/v2/layout.(*gridLayout).MinSize(0xc00041c1a0, {0xc000424340, 0x4, 0x7ff7b09fe726?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/layout/gridlayout.go:135 +0x326
fyne.io/fyne/v2.(*Container).MinSize(0xc00041c19b?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/container.go:84 +0x72
fyne.io/fyne/v2/layout.(*boxLayout).MinSize(0xc00041c19b, {0xc000416b70?, 0x3, 0xc00278bad8?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/layout/boxlayout.go:140 +0x15d
fyne.io/fyne/v2.(*Container).MinSize(0xc00041c5f0?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/container.go:84 +0x72
fyne.io/fyne/v2/layout.(*gridLayout).MinSize(0xc00041c5f0, {0xc00043c8c0, 0x2, 0x7ff7b09fe726?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/layout/gridlayout.go:135 +0x326
fyne.io/fyne/v2.(*Container).MinSize(0xc00041cd10?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/container.go:84 +0x72
fyne.io/fyne/v2/layout.(*boxLayout).MinSize(0xc00041cd10, {0xc00043d460?, 0x2, 0xc0000856c0?})
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/layout/boxlayout.go:140 +0x15d
fyne.io/fyne/v2.(*Container).MinSize(0xc00278bcd8?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/container.go:84 +0x72
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).MinSize(0xc00044a000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/canvas.go:72 +0x9f
fyne.io/fyne/v2/internal/driver/glfw.(*window).minSizeOnScreen(0xc00043e000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window.go:47 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).fitContent(0xc00043e000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window_desktop.go:221 +0x66
fyne.io/fyne/v2/internal/driver/glfw.(*window).rescaleOnMain(0xc00043e000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window_desktop.go:621 +0x37
fyne.io/fyne/v2/internal/driver/glfw.(*window).RescaleContext.func1()
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window.go:910 +0x1d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc0003a2700)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/loop.go:129 +0x1cc
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc00043e000?)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/driver.go:164 +0x33
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc00043e000)
        C:/Users/Admin/go/pkg/mod/fyne.io/fyne/v2@v2.2.4-0.20220722155227-638ae24e4beb/internal/driver/glfw/window.go:230 +0x2c
main.main()
        D:/codespace/workspace/src/librarygo/src/hardwareIndo/cmd/man.go:20 +0xb1

Process finished with the exit code 2

### How to reproduce

add this pkg:
https://github.com/ddkwork/librarygo/blob/main/src/fynelib/fyneTheme/interface.go

then go install this:
https://github.com/ddkwork/librarygo/blob/main/src/hardwareIndo/cmd/man.go

### Screenshots

![screenshots](https://user-images.githubusercontent.com/19886504/184474231-a1d7b541-7ca9-468d-b03f-06184dd4c5cd.gif)

### Example code

then go install this:
https://github.com/ddkwork/librarygo/blob/main/src/hardwareIndo/cmd/man.go

### Fyne version

latest

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

win11

**Comment by andydotxyz** [comment]
"Latest" is not a version we can test against as it is ways changing. Please test with 2.2.3 and let us know if you can replicate the issue.

If it is an issue there then a minimal code example would be very helpful so we can more quickly convert to tests and validate.
