### ISSUE TITLE
Android RootURI may not exist when used for storage

### ISSUE THREAD

**Issue by PaulDotSH** [fyne-io/fyne#3207]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When creating a new file on storage.Child(ROOTURI, "file.json"), on desktop this works as expected but on mobile this uri links to app.pkg.id/fyne/file.json instead of app.pkg.id/file.json

### How to reproduce

Try to write to a file in android and desktop version of a fyne app using something similar to
storage.Child(fyne.CurrentApp().Storage().RootURI(), "foo.json")

### Example code

```
func saveState() error {
	uri, e := storage.Child(fyne.CurrentApp().Storage().RootURI(), "foo.json")

	if e != nil {
		return e
	}
	return writeToFile(uri, []byte("Foo"))
}

func writeToFile(path fyne.URI, content []byte) error {
	w, e := storage.Writer(path)

	if e != nil {
		return e
	}
	_, e = w.Write(content)
	if e != nil {
		return e
	}
	return nil
}

func init() {
fmt.Println(saveState()) //file:///.... pkg.app.id/fyne/foo.json not found
}
```

### Fyne version

2.2.2 (latest at the time of writing this)

### Go compiler version

1.19

### Operating system

Other (specify below)

### Operating system version

Arch Linux and Android 10, replicated on android 8 too

**Comment by andydotxyz** [comment]
Updated the title as the issue here is that it does not exist rather than it is wrong. If you look at how desktop works there is also a "fyne" directory in the path to avoid collisions. It is further up the path because we don't have to handle sandboxes.
To fix this we should ensure the storage exists for apps that are not using preferences (as that would create it).

**Comment by andydotxyz** [comment]
Resolved for next release
