### ISSUE TITLE
scroll bar color

### ISSUE THREAD

**Issue by shofster** [fyne-io/fyne#3208]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

scroll bar is dark when dark theme

### Describe the solution you'd like to see.

change the color of the scroll bar to be theme color - or anything that contrasts with "dark"

**Comment by shofster** [comment]
I did a myTheme and for the color name "scrollBar" tried forcing it to VariantDark or VariantLight - no change -----------
func (m myTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	switch name {
	case "scrollBar":
		//return theme.DefaultTheme().Color(name, theme.VariantLight)
		return theme.DefaultTheme().Color(name, theme.VariantDark)
	}

**Comment by shofster** [comment]
made it work -

**Comment by shofster** [comment]
my mistake(s)

**Comment by andydotxyz** [comment]
I wonder if we should, by default, have a higher contrast scroll bar though... Should we re-open this as address with the theme review in v2.3?

**Comment by shofster** [comment]
I fixed by always using the primary color.Seems to fit with the current
underline and the futute (?) border.

func (m myTheme) Color(name fyne.ThemeColorName, variant
fyne.ThemeVariant) color.Color {
   switch name {
   case "scrollBar":
      return theme.PrimaryColor()
   }
   return theme.DefaultTheme().Color(name, variant)
}

BTW - is Bill Kennedy as much an arrogant ass as he seems in videos?

**Comment by shofster** [comment]
for review in new theme

**Comment by andydotxyz** [comment]
This is resolved on develop ready for v2.3.0
