### ISSUE TITLE
Image is not being updated

### ISSUE THREAD

**Issue by Edenshaw** [fyne-io/fyne#3209]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When clicking on button that loads a new image and refreshing the container, the new image is not being updated

### How to reproduce

When loading the code, the fyne logo is displayed, but when the button is pressed the new image is not shown

### Example code

```
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("My Window")
	myWindow.Resize(fyne.NewSize(600, 600))
	myWindow.CenterOnScreen()

	imageCanvas := &canvas.Image{}
	mainContainer := &fyne.Container{}
	content2 := &fyne.Container{}
	centered := &fyne.Container{}
	
	btnWidget := widget.NewButton("Render Image", func() {
		imageCanvas = canvas.NewImageFromFile("/tmp/image.png")
		imageCanvas.FillMode = canvas.ImageFillOriginal
		imageCanvas.Refresh()
		content2.Refresh()
		centered.Refresh()
		mainContainer.Refresh()
	})

	imageCanvas = canvas.NewImageFromResource(theme.FyneLogo())
	imageCanvas.FillMode = canvas.ImageFillOriginal
	imageCanvas.Refresh()
		
	content2 = container.New(layout.NewHBoxLayout(), layout.NewSpacer(), imageCanvas, layout.NewSpacer())
	centered = container.New(layout.NewHBoxLayout(), layout.NewSpacer(), btnWidget, layout.NewSpacer())
	mainContainer = container.New(layout.NewVBoxLayout(), centered, content2)
	
	myWindow.SetContent(mainContainer)
	myWindow.ShowAndRun()
}
```

### Fyne version

v2@v2.2.3

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

Windows 10

**Comment by gavinwade12** [comment]
The problem is that you've created `content2` with `imageCanvas` being `canvas.NewImageFromResource(theme.FyneLogo())`.

Even though `imageCanvas` is a pointer and _updates to the struct's fields would be reflected in the UI after a Refresh()_, re-assigning `imageCanvas` to a new pointer, e.g. with `canvas.NewImageFromFile("/tmp/image.png")`, will not affect the image instance you've passed to the container.

You could try swapping out the old instance with the new one you've created:

```go
btnWidget := widget.NewButton("Render Image", func() {
    imageCanvas = canvas.NewImageFromFile("/tmp/image.png")
    imageCanvas.FillMode = canvas.ImageFillOriginal
    content2.Objects[1] = imageCanvas
    mainContainer.Refresh()
})
```

**Comment by Edenshaw** [comment]
Thanks a lot for your comment @gavinwade12, it works without any issue!
