### ISSUE TITLE
CanvasObject doesn't refresh until Scroll has scrolled

### ISSUE THREAD

**Issue by neflyte** [fyne-io/fyne#3216]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I've run into a case where I can't get a widget to repaint itself unless the Scroll that contains it has scrolled at least once.

I have a GridWrap container inside a VScroll. The GridWrap container has 10 custom widgets in it, all exactly the same. Each widget contains a `Label` and a `Rectangle`, and logic to capture desktop `MouseUp` events. When I click on a widget, the rectangle either shows or hides as if it was being selected. However, the rectangles don't start appearing until I scroll my mouse wheel once. I've tried playing with focus and refreshes but nothing has worked so far.

I would expect the custom widget to repaint itself without scrolling the container. Hopefully this is just something I've done incorrectly.

BTW: I'm totally loving the experience so far with fyne :smile:  It's awesome! :heart: 

### How to reproduce

Execute the provided sample code.

### Example code

`main.go`:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
)

func main() {
	a := app.New()
	w := a.NewWindow("Click Test")
	squares := make([]fyne.CanvasObject, 10)
	for x := 0; x < 10; x++ {
		squares[x] = NewSquare()
	}
	w.SetContent(container.NewVScroll(container.NewGridWrap(
		fyne.NewSize(100.0, 100.0),
		squares...,
	)))
	w.Resize(fyne.NewSize(250.0, 250.0))
	w.ShowAndRun()
}
```

Custom widget - `widget.go`:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
	"image/color"
)

var _ fyne.Widget = (*Square)(nil)
var _ desktop.Mouseable = (*Square)(nil)

type Square struct {
	widget.BaseWidget
	selected   bool
	selectChan chan bool
}

func NewSquare() *Square {
	s := &Square{
		selectChan: make(chan bool, 1),
	}
	s.ExtendBaseWidget(s)
	return s
}

func (s *Square) MouseDown(_ *desktop.MouseEvent) {}

func (s *Square) MouseUp(_ *desktop.MouseEvent) {
	s.selected = !s.selected
	s.selectChan <- s.selected
}

func (s *Square) CreateRenderer() fyne.WidgetRenderer {
	renderer := &squareRenderer{
		layout:     layout.NewMaxLayout(),
		rect:       canvas.NewRectangle(color.Transparent),
		label:      widget.NewLabel("Click Me"),
		selectChan: s.selectChan,
	}
	renderer.rect.StrokeColor = color.White
	renderer.rect.StrokeWidth = 2.0
	renderer.rect.SetMinSize(fyne.NewSize(100.0, 100.0))
	renderer.rect.Hide()
	renderer.canvasObjects = []fyne.CanvasObject{renderer.label, renderer.rect}
	go renderer.watchChannel()
	return renderer
}

type squareRenderer struct {
	layout        fyne.Layout
	canvasObjects []fyne.CanvasObject
	rect          *canvas.Rectangle
	label         *widget.Label
	selectChan    chan bool
}

func (s *squareRenderer) Destroy() {}

func (s *squareRenderer) Layout(size fyne.Size) {
	s.layout.Layout(s.Objects(), size)
}

func (s *squareRenderer) MinSize() fyne.Size {
	return s.label.MinSize() // Make the minimum size the same as the label
}

func (s *squareRenderer) Objects() []fyne.CanvasObject {
	return s.canvasObjects
}

func (s *squareRenderer) Refresh() {
	s.Layout(s.MinSize())
}

func (s *squareRenderer) watchChannel() {
	for {
		select {
		case selected := <-s.selectChan:
			if selected {
				s.rect.Show()
			} else {
				s.rect.Hide()
			}
			s.rect.Refresh()
		}
	}
}
```

### Fyne version

2.2.3

### Go compiler version

1.18.2

### Operating system

Linux

### Operating system version

Ubuntu 22.04

**Comment by andydotxyz** [comment]
If you want your widget to refresh after changing the internal state you will need to call `Refresh()`.
The scroll is triggering that for you I guess, which is why it seems delayed.

**Comment by andydotxyz** [comment]
Ah yes, sorry I see now. 
It may be to do with your `Refresh` simply calling `Layout`. 
Just guessing now as i'm not super sure, but maybe calling Refresh on the widget would trigger a complete refresh

**Comment by andydotxyz** [comment]
The general workflow is that state management is done in the widget code, and when that changes we call refresh and the renderer updates. By putting state monitoring in the renderer I am not sure exactly where the issue has emerged.
