### ISSUE TITLE
Prevent Multiple Instances of an Application

### ISSUE THREAD

**Issue by yanccqq** [fyne-io/fyne#3217]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When I click the app repeatedly it opens multiple windows, but generally I only need one window

### Describe the solution you'd like to see.

When you click for the second time, the already opened window will be displayed, and no new window will be opened.

**Comment by andydotxyz** [comment]
I don't know how others feel, but this seems like something the application will need to do.

On macOS this is already the default behaviour (it is set up by the OS) but on Windows and Linux it is not expected.
Because we are building apps that will work as expected on all OS forcing this behaviour does not seem desirable...

**Comment by mcosta74** [comment]
My thought here.

It should not be a default behaviour (there are cases where having multiple instances makes sense), bout could be an option explicitly enabled by the developer.

**Comment by matwachich** [comment]
The default behaviour should be not allowing multiple instances, one possible problem would be concurent access to config files.

But there should be an option (env var?) to allow multiple instances

**Comment by yanccqq** [comment]
> 

What I mean is that preventing multiple instances is optional, not the default behavior, in some cases launching multiple instances will cause concurrency problems

**Comment by yanccqq** [comment]
I found in some Electron applications, when the second click, the application will be reactivated and displayed on the top layer of the desktop, I think this implementation works very well

**Comment by yanccqq** [comment]
I can't find any good way to judge that the application is running and let the first click to open the application display the top layer of the user's desktop

**Comment by andydotxyz** [comment]
> I can't find any good way to judge that the application is running and let the first click to open the application display the top layer of the user's desktop

Indeed, you would need to add some code to do that. And do so in a way that does not hit the concurrency problems you mention above I guess.

**Comment by andydotxyz** [comment]
Some relevant information for the major OS:

| OS | App tested | Click/open | Launch from cmdline |
| ----|----------- | ----------- | --------------------- |
| Windows | calc.exe | New instance | New instance |
| macOS | Calculator.app | Same instance | New instance |
| Linux | lxterminal | New instance | New instance |
| iOS | Calendar | Same instance | n/a |
| Android | Mail | Same instance | n/a |

The table above lists the standard behaviours for the most common platforms.
Fyne apps match in every regard, I will close this ticket as not planned.
If you would like to make a helper that allows apps to force same-instance launches perhaps consider contributing it to fyne-x where such extensions make sense?

**Comment by aohanhongzhi** [comment]
I need single instance fyne app like `windows 11 task manager`

**Comment by dweymouth** [comment]
This is something you can do yourself with fsnotify or fslock and a little creativity. It does not need to be a part of the Fyne framework. You can see here how I've made my Fyne app single-instance: https://github.com/dweymouth/supersonic/blob/main/backend/app.go#L58

**Comment by mevdschee** [comment]
I wrote another package that allows you to run a single instance and it even allows the first instance to be notified when a second instance starts, see: https://github.com/mevdschee/pidfile
