### ISSUE TITLE
Content is not refreshed when wrapped in a Card widget

### ISSUE THREAD

**Issue by hismailbulut** [fyne-io/fyne#3223]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Refreshing window content does not refresh content of card widget

### How to reproduce

Create a label in card widget

### Screenshots

![image](https://user-images.githubusercontent.com/73897211/186899399-336810cb-279d-4668-a29d-36db8a2558a3.png)
![image](https://user-images.githubusercontent.com/73897211/186899422-1199121e-a415-45c6-907d-9ba9285d2e56.png)

### Example code

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

const markdown = `
# H1
## H2
### H3
---
**bold text**
*italicized text*
> blockquote
---
1. First item
2. Second item
3. Third item
---
- First item
- Second item
- Third item
`

var variant = theme.VariantLight

func main() {
	a := app.New()
	a.Settings().SetTheme(&myTheme{})
	w := a.NewWindow("markdown text issue")
	w.SetContent(
		container.NewVBox(
			widget.NewCard("", "",
				container.NewVBox(
					widget.NewRichTextFromMarkdown(markdown),
					widget.NewLabel("This is a label."),
				),
			),
			widget.NewButton("Switch Variant", func() {
				if variant == theme.VariantDark {
					variant = theme.VariantLight
				} else {
					variant = theme.VariantDark
				}
				w.Content().Refresh()
			}),
		),
	)
	w.ShowAndRun()
}

type myTheme struct{}

func (m myTheme) Color(name fyne.ThemeColorName, _ fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(name, variant)
}

func (m myTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func (m myTheme) Font(style fyne.TextStyle) fyne.Resource {
	return theme.DefaultTheme().Font(style)
}

func (m myTheme) Size(name fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(name)
}
```

### Fyne version

2.2.3

### Go compiler version

1.18.4

### Operating system

Windows

### Operating system version

11

**Comment by andydotxyz** [comment]
I can replicate it with the code above, but not with a unit test that uses `SetTheme`.
This makes me realise that `App.Settings().SetTheme()` is doing something internally that `Refresh` alone does not do.
I'm not surprised as `SetTheme` walks the widget tree, but Refresh is per-widget - so card is not cascading.
If you move to use `SetTheme` in your code does the issue go away?

**Comment by hismailbulut** [comment]
Yes SetTheme works fine but I had to create two themes, one with only Light colors and the other with only Dark colors. It would be nice to be able to override the variant of DefaultTheme maybe with a SetVariant method. But in any case my problem is solved. Thank you.

**Comment by andydotxyz** [comment]
Fixed on develop
