### ISSUE TITLE
Split Container does not respect item's Visible status

### ISSUE THREAD

**Issue by PaulWaldo** [fyne-io/fyne#3232]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When an item in a Split container is hidden, the split should should act is if there is nothing there for that item.  Neither the `Layout` nor the `MinSize` function examine the `Visible` status of the items.

### How to reproduce

1. Run the attached code, which is a Split container with buttons on the left and a Label on the right
2. Drag the slider around to verify it works properly.  Note that if you drag the slider right to the MinSize of the Label, the pointer moves, but the slider does not.  While still holding the click, drag the slider back to the left and you can see that the pointer and the slider handle become out of sync.
3. Click the Hide button 
4. Drag the slider around.  Note that it behaves exactly the same, but with the label hidden.  I would expect that with the label hidden, I could drag the slider all the way to the right edge of the window

### Screenshots

![CleanShot 2022-08-29 at 16 23 39](https://user-images.githubusercontent.com/12105941/187291995-b8ec4845-7e8b-4082-8378-4ce2553560e0.gif)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Form Layout")

	label := widget.NewLabel("I am a longish label that just sits here")

	buttons := container.NewVBox(
		widget.NewButton("Show", func() {label.Show()}),
		widget.NewButton("Hide", func() {label.Hide()}),
	)

	c := container.NewHSplit(buttons, label)

	myWindow.SetContent(c)
	myWindow.Resize(fyne.NewSize(500, 300))
	myWindow.ShowAndRun()
}
```

### Fyne version

2.2.3

### Go compiler version

go version go1.19 darwin/amd64

### Operating system

macOS

### Operating system version

Monterey 12.5.1

**Comment by andydotxyz** [comment]
This was resolved ready for v2.3.0 release
