### ISSUE TITLE
Add dots when label.Wrapping = fyne.TextTruncate

### ISSUE THREAD

**Issue by cmarmonier** [fyne-io/fyne#3243]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When user read a label, he doesn't know if text is wrapped or not

### Is it possible to construct a solution with the existing API?

I don't know

### Describe the solution you'd like to see.

When text is wrapped, add "..." at the end of the label. 
ie : "hello, h.." for "hello, how are you?" if label size is 10 characters

**Comment by Jacalz** [comment]
Thanks for opening the feature request. It is indeed a good improvement. However, the technical term for … is [ellipsis](https://en.m.wikipedia.org/wiki/Ellipsis) and there is an open issue for that already. See https://github.com/fyne-io/fyne/issues/1659.

I will close this as a duplicate but thanks for open the issue. The issue above is currently aimed at the next big release. I’m not sure if it will make it in but we are aiming for that to happen.
