### ISSUE TITLE
Possibility to support opentype fonts?

### ISSUE THREAD

**Issue by rongcuid** [fyne-io/fyne#3245]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

An earlier, related issue: #400

Some fonts I want to use comes with only Opentype (ttc) format, and Fyne doesn't load it. I don't know the underlying architecture as I am just trying this framework out, but it seems like `golang.org/x/image/font/opentype` already supports both formats. Is there a reason Fyne is not using it?

### Describe the solution you'd like to see.

Support TTF and OTF fonts.

Bonus if Fyne bundles fonts for CJK languages and all languages on earth :)

**Comment by andydotxyz** [comment]
> it seems like golang.org/x/image/font/opentype already supports both formats. Is there a reason Fyne is not using it?

Thanks for the request, we are in the middle of moving to the [go-text](https://github.com/go-text) project for text handling and so what is supported will be set by that instead. At this time there is only .TTF support there I think, but once ported over we can work to expand that.

> Bonus if Fyne bundles fonts for CJK languages and all languages on earth :)

We would love to do this, but it would make every application > 200MB on last count. We are trying to find a better approach.

**Comment by rongcuid** [comment]
I think native GUI kits do something like "load system font". And maybe there can be a stack of fallbacks.

**Comment by andydotxyz** [comment]
Indeed, the challenge is for consistency, and amount of platform code required.
To add support for system font lookup we have to land the code for macOS, Windows, Linux, BSD, Android and iOS, with more coming. We do intend to look at this, but it is a tremendous amount of work and so was pushed back to when we focus on internationalisation as that is where the focus shifts to this area.

**Comment by dweymouth** [comment]
The issue title refers to OpenType support but the conversation here also relates to tracking TrueType Collection (.ttc) support, just commenting for clarity. Also there is .otc (OpenType Collection) as well

**Comment by andydotxyz** [comment]
Support for ".otf" is in on `develop` branch.
