### ISSUE TITLE
Add a way to get the system's locale

### ISSUE THREAD

**Issue by elie-g** [fyne-io/fyne#3249]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I can't get the system locale on android cause the [RunOnJVM](https://github.com/fyne-io/fyne/blob/6e90820ea9ca4df836db5a99384c51073415571e/internal/driver/mobile/app/android.go#L86) function isn't accessible anymore.

See [jeandeaual/go-locale](https://github.com/jeandeaual/go-locale#os-support)

### Is it possible to construct a solution with the existing API?

I don't think it is possible.

### Describe the solution you'd like to see.

Either make the [RunOnJVM](https://github.com/fyne-io/fyne/blob/6e90820ea9ca4df836db5a99384c51073415571e/internal/driver/mobile/app/android.go#L86) function accessible or implement a way to access the system's locale.

See [jeandeaual/go-locale](https://github.com/jeandeaual/go-locale#os-support)

**Comment by Jacalz** [comment]
Looks like something that would be implemented as part of https://github.com/fyne-io/fyne/issues/605.

**Comment by andydotxyz** [comment]
This is now on develop
