### ISSUE TITLE
Calling app.Quit() does not seem to fully shut down the gui process

### ISSUE THREAD

**Issue by sloumdrone** [fyne-io/fyne#3265]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am using fyne within my interpreted programming language as the bundled in gui library. I have created a set of bindings for calling various parts of the fyne api. It mostly works really well. I recently tried calling a function that creates an image viewing window from the repl (as opposed to a one of program run), which worked (my image viewer loaded a window and showed an image). Then the window is closed the function returns. Yay! So far so good. Now, if I try to call the same function again, it just hangs at the terminal. My guess is this relates to the following from the docs:

> An application should only have one runloop and so you should only call Run() once in your code

As such this may or may not be a bug. It seems like since the run loop has been terminated there would not be a second run loop acting at the same time and that this _might_ not apply since I am not trying to run them concurrently... I also tried using `app.Quit()` with the hopes that it would do a more full teardown before trying a new app run (on a separate app instance), to no avail.

I definitely understand this is a non-standard and potentially odd thing I am wanting to do, but I believe it makes sense in the context of running from a repl (that I use as my main shell a lot of the time).

I am guessing that my use case of creating multiple (but not concurrent) apps within a single thread that continues past the life of an individual app is just not possible with fyne? If there is a work-around for this it would be very helpful to me. If not, is there a place in the code where a custom build of fyne might be able to solve this problem? (Im not asking for it to be solved, but am mostly just wanting a point in the right direction if it might be possible).

### How to reproduce

I am not running this directly from golang, as stated above, but the step to recreate would be to run `myFirstApp.Run()`, then after it exits run more code from the main golang func then try to run a new app via `mySecondApp.Run()` or the like. THen once that exits exit the full program.

### Example code

``` go
func gui() {
    myApp := app.New()
    myWindow := myApp.NewWindow("Hello")
    myWindow.SetContent(widget.NewLabel("Hello"))
    myWindow.ShowAndRun()
}

func main() {
    gui() // exits on the close of the main window...

    // ... other code ...

    gui() // Run again
}
```

### Fyne version

2.1.3

### Go compiler version

1.16.4

### Operating system

Linux

### Operating system version

Ubuntu 18.04 / Gnome3 / amd64

**Comment by andydotxyz** [comment]
You're right this is not supported, as the documentation you found outlines. 
You should have 1 application insurance and can then show and hide as many windows as you want.

By juggling different run loops (even if they are not concurrent) we cannot effectively manage the underlying graphics and OS event systems.

**Comment by andydotxyz** [comment]
Referring to the topic again, the GUI "process" does exit, or you would not get a return, but the graphics have been initialises and the OS thread set - this cannot be done a second time in the same runtime.

**Comment by sloumdrone** [comment]
Thank you for the clear and quick answer!
