### ISSUE TITLE
Android - Entry - OnSubmitted is not working

### ISSUE THREAD

**Issue by apiotrowski312** [fyne-io/fyne#3267]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

OnSubbmited event is not firing when pressing `Enter` key on Android keyboard

Keyboard image:
![image](https://user-images.githubusercontent.com/22003852/190849757-f8b61930-5f94-466d-a60e-662d8b947887.png)

### How to reproduce

1. Run code on Android
2. Press Enter
3. Nothing happens (no logs in logcat for example)

### Example code

```go
func main() {
	a := app.NewWithID("example")

	w := a.NewWindow("example")
	cntr := widget.NewEntry()
	cntr.OnSubmitted = func(s string) {
		fmt.Println("SUBMITTED: ", s)
	}

	w.SetContent(cntr)

	w.Resize(fyne.NewSize(640, 480))
	w.ShowAndRun()
}
```

### Fyne version

2.2.3 and also develop

### Go compiler version

go1.18 linux/amd64

### Operating system

Android

### Operating system version

Lineage OS

**Comment by andydotxyz** [comment]
On `develop` for next release, thanks so much @apiotrowski312
