### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by vkuznet** [fyne-io/fyne#3269]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

On some occasion when I run my app I experience the following issue: 
```
fatal error: concurrent map writes
...
goroutine 42 [running]:
fyne.io/fyne/v2/internal/painter.CachedFontFace({0x0, 0x0, 0x0, 0x0, 0x0}, 0xc000fcd1b8)
    /Users/vk/Work/Languages/Go/gopath/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/painter/font.go:70 +0x4a5
```
or
```
fatal error: concurrent map read and map write
...
fyne.io/fyne/v2/internal/painter.CachedFontFace({0x0, 0x0, 0x0, 0x0,0x0}, 0xc0005eb2e0)
   /Users/vk/Work/Languages/Go/gopath/pkg/mod/[2]fyne.io/fyne/v2@v2.2.3/internal/painter/font.go:64 +0x314
```

Upon code inspection, I found that indeed I see that the following lines:
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L59
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L64
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L70
will lead to this issue since the update in map is not protected.

### How to reproduce

There is no clear way to reproduce the problem, but upon code inspections it is clearly see where the bug is, see
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L59
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L64
https://github.com/fyne-io/fyne/blob/master/internal/painter/font.go#L70
which will lead to unprotected map updates.

### Example code

There is no clear way to reproduce the issue.

### Fyne version

v2.2.3

### Go compiler version

1.19

### Operating system

macOS

### Operating system version

11.6.8

### Additional Information

The code itself reveals the issue as used map is not protected on read/write operations and will lead to aforementioned issue in concurrent environment.

**Comment by andydotxyz** [comment]
It looks like this should be fixed already on the develop branch
