### ISSUE TITLE
form.Disable() dosen't prevent OnSubmit callback be called when click the submit button.

### ISSUE THREAD

**Issue by nononocat** [fyne-io/fyne#3270]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

My code want to do some background task after the form's submit button be clicked.
So, I put  the related code to OnSubmit callback of form widget. And I use form.Disable() to disable the submit button, preventing the submit buttom be clicked and the OnSubmit callback be called before my background task finished.  

But here's the weird thing is when I click the disabled submit button, the OnSubmit callback still be called....

### How to reproduce

trying to click the disabled submit button of form widget will reproduce the problem

### Screenshots

When I click the disabled submit button, the callback still be fired.

![t](https://user-images.githubusercontent.com/30766333/190936106-aaba69d1-8756-4a0e-b00d-b2729dad2183.gif)

### Example code

```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	w := app.NewWindow("foo")
	w.Resize(fyne.Size{Width: 240, Height: 240})

	entry := widget.NewEntry()

	form := widget.NewForm(
		&widget.FormItem{
			Text:     "foo",
			Widget:   entry,
			HintText: "",
		},
	)
	form.SubmitText = "OK"
	
	form.OnSubmit = func() {
		form.Disable()
		time.Sleep(time.Second * 2)
		fmt.Println("Hello World")
		form.Enable()
	}

	w.SetContent(form)
	w.ShowAndRun()
}
```

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

Windows 11 21H2

**Comment by Jacalz** [comment]
This sounds like it should be a relatively easy thing to fix (and something trivial that was overlooked). Thanks for reporting.

**Comment by nononocat** [comment]
Thank you very much!!!

**Comment by Jacalz** [comment]
This has not been resolved. Let's keep it open until then

**Comment by andydotxyz** [comment]
I actually don't think this is an issue. The example code is not doing what you think it is. The callback blocks the event thread - so what is really happening...

* Tap button
* Disable
* Stop processing events for 2 seconds
* Enable
* Start processing events again
* Tap button (which has become enabled)

Really you'd need to disable it and start a timer to re-enable, at which point you will see it work as expected.

**Comment by Jacalz** [comment]
Good point. I missed that earlier. Just disable the form directly after us is created and it should not handle any events on the submit button.

**Comment by nononocat** [comment]
> I actually don't think this is an issue. The example code is not doing what you think it is. The callback blocks the event thread - so what is really happening...
> 
>     * Tap button
> 
>     * Disable
> 
>     * Stop processing events for 2 seconds
> 
>     * Enable
> 
>     * Start processing events again
> 
>     * Tap button (which has become enabled)
> 
> 
> Really you'd need to disable it and start a timer to re-enable, at which point you will see it work as expected.

Thank you very much for your reply!!!

You means that even the form is disabled, the "event queue" of the submit button still can receive the tap event when I tap the disabled submit button, but do not trigger the callback of the submit button. Then, when 2 seconds passed, my code enable the form, and the submit button receive the tap event from the event queue again, even the tap event happened almost 2 seconds ago.

Do I understand it correctly?

What I really want to do is checking the database healthy in the callback of the form's submit button, if the database is connectable, my code will start a restful API based on the database. If the database can't be connected, my code will enable the form again, in order the user can correct the database address he typed in the entry.
But I found that if I give a invalid database address in the form's entry, when I tap the submit button 10 times, the DB healthy check will perform 10 times... even the submit button seems disabled when  I click the submit button first time....

**Comment by andydotxyz** [comment]
Your summary is sort of right, but sort of not.
Widgets do not queue events, but in your code you have stopped the application from processing events (`time.Sleep(time.Second * 2)`) which means we cannot do anything to process them. So when you allow the processing to continue the events arrive but the form is no longer disabled.

Pauses and background activity should happen in a different goroutine so that the GUI can continue to function whilst it processes.

Just to sumarise, a disabled button cannot be clicked, and a disabled form cannot be submitted, but in your code you block Fyne from knowing that events arrived at the time it was disabled.
