### ISSUE TITLE
Sensitive region when selecting with the mouse in an Entry is shifted

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#3271]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When selecting text inside an `Entry` with the mouse, the sensitive region is somewhat shifted to the top.
I’d expect to be able to klick and hold onto the text, then move the mouse (horizontally) and select some text.
This only works if I click a little bit higher (not really above the text).
This is confusing and one might think the selection does not work at all.

### How to reproduce

1. Start `fyne_demo`
2. Go to “Widgets -> Entry”
3. Try to select the disabled text with the mouse cursor aligned vertically to the line of text.

### Screenshots

![entry_selection](https://user-images.githubusercontent.com/73959/190958939-77ca530c-3d19-44a1-8e54-c6f561cc8a0a.gif)

### Example code

-

### Fyne version

develop

### Go compiler version

1.18

### Operating system

macOS

### Operating system version

Catalina

**Comment by andydotxyz** [comment]
Good catch - looks like I missed / broke some offset code with the new theme changes

**Comment by andydotxyz** [comment]
Fixed on `develop`
