### ISSUE TITLE
Cursor does not keep position in text on resize of wrapping Entry

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#3272]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The cursor is not placed correctly when resizing a multi-line `Entry` in a way that changes the line of the cursor position.

I’d expect the cursor to keep its position in the text, i.e. wrap with the text on resize.

### How to reproduce

1. Start `fyne_demo`
2. Go to “Widgets -> Text”
3. Place the cursor at beginning of line 2 of the `Entry` at the bottom
4. Make the window wider -> the cursor stays at the beginning of line 2 while the text moves to line 1
5. Place the cursor at the end of line 3
6. Make the window smaller -> the cursor vanishes while the text moves to line 4

### Screenshots

![entry_cursor_on_resize](https://user-images.githubusercontent.com/73959/190995553-47a2aba4-42eb-47c5-b9e0-625118a8190b.gif)

### Example code

-

### Fyne version

develop

### Go compiler version

1.18

### Operating system

macOS

### Operating system version

Catalina

**Comment by matwachich** [comment]
https://github.com/fyne-io/fyne/issues/3024

**Comment by andydotxyz** [comment]
Yup it looks like a duplicate
