### ISSUE TITLE
file creation on external storage of Android

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3274]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

described in #3255. As discussed in Slack, there seems to be necessary to add API for the need.

### Is it possible to construct a solution with the existing API?

I can only use dialog.ShowFileSave(), which starts activity with Intent.ACTION_CREATE_DOCUMENT. That creates files in which way I cannot through fyne API?

### Describe the solution you'd like to see.

to add an API to get external storage URI for Android, and storage.Writer() can use it to create a file.

**Comment by andydotxyz** [comment]
From mobile apps the sandbox permission scheme means that (often) it is necessary to get user permission to write into certain spaces. The file save dialog takes care of this automatically.
What space were you attempting to write to that was not permitted directly?

**Comment by bon-ami** [comment]
@andydotxyz , it's a file under /sdcard/ directly or under a sub-directory.

**Comment by andydotxyz** [comment]
But what URI are you using? There are multiple ways of accessing things on Android, and some of them are more controlled than others. For example `file:///sdcard/...` should work just fine.

**Comment by andydotxyz** [comment]
I think the reason we have not added an external storage API is that it has little meaning on most platforms. The `app.Storage().RootURI()` provides an always-writable space that an app can use. All of the documents storage is based on this location https://developer.fyne.io/api/v2.2/storage

**Comment by bon-ami** [comment]
> But what URI are you using? There are multiple ways of accessing things on Android, and some of them are more controlled than others. For example `file:///sdcard/...` should work just fine.

storage.Writer(storage.NewFileURI("/sdcard/a")) uses file:///sdcard/a and bumps into error "no repository registered for scheme 'file'"

**Comment by andydotxyz** [comment]
Something else must be wrong in your code, the fyne App constructor absolutely does load a file:// repository.

**Comment by bon-ami** [comment]
> Something else must be wrong in your code, the fyne App constructor absolutely does load a file:// repository.

I really tried again with following code piece and got the error on my Android phone.
```
	uri := storage.NewURI("file:///sdcard/a")
	//uri := storage.NewFileURI("/sdcard/a")
	wr, err := storage.Writer(uri)
```
both fail

**Comment by andydotxyz** [comment]
Are you calling this before `app.New`?

**Comment by bon-ami** [comment]
> Are you calling this before `app.New`?

Solved. I have to give the app permission of storage in Settings.
The question now is how to self-grant it or ask user to allow it.

as a ref., here's my code
```
	myApp := app.NewWithID("a")
	myWin := myApp.NewWindow("a")
	var but1 *widget.Button
	var sw bool
	but1 = widget.NewButton("StrFlw", func() {
		var uri fyne.URI
		if sw {
			uri = storage.NewURI("file:///sdcard/a")
			sw = false
		} else {
			uri = storage.NewFileURI("/sdcard/a")
			sw = true
		}
		wr, err := storage.Writer(uri)
		if err != nil {
			but1.SetText(err.Error() + uri.String())
		} else {
			but1.SetText("OK")
			wr.Close()
		}
	})
	myWin.SetContent(but1)
	myWin.ShowAndRun()
```

**Comment by andydotxyz** [comment]
That permission should have been granted by the app bundle.
Is your android set up to have that off by default somehow? Or is it a custom manifest you are bundling?

**Comment by bon-ami** [comment]
> That permission should have been granted by the app bundle. Is your android set up to have that off by default somehow? Or is it a custom manifest you are bundling?

As discussed in Slack, I guess "android:targetSdkVersion="29"" in default manifest, which does declare this permission, makes it needs explicit user permission

**Comment by andydotxyz** [comment]
Ah yes, it does seem to be a limitation of the OS according to the docs.
The dialog will allow this to work, to specify a location in code that actually is not permitted will probably need your app to handle the error and show a dialog appropriately telling the user to enable writing to the location.
It is not very "platform agnostic" but I guess as you are hard coding an Android path you know this is platform specific already.
