### ISSUE TITLE
Can't set custom CGO_CFLAGS and CGO_LDFLAGS with "fyne package" on darwin

### ISSUE THREAD

**Issue by cra1nbow** [fyne-io/fyne#3276]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

in Darwin, can't custom CGO_CFLAGS and CGO_LDFLAGS

`go run` and `go build` works well

### How to reproduce

1. clone https://github.com/zergon321/reisen
2. install ffmpeg `brew install ffmpeg --build-from-source`
3. CGO_CFLAGS="-I/opt/homebrew/Cellar/ffmpeg/5.1.1/include" CGO_LDFLAGS="-L/opt/homebrew/Cellar/ffmpeg/5.1.1/lib/" go run examples/player/main.go working well
4. CGO_CFLAGS="-I/opt/homebrew/Cellar/ffmpeg/5.1.1/include" CGO_LDFLAGS="-L/opt/homebrew/Cellar/ffmpeg/5.1.1/lib/" fyne package doesn't work (because fyne overwrite CGO_CFLAGS and CGO_LDFLAGS)

### Example code

https://github.com/zergon321/reisen

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

macOS

### Operating system version

MacOSX Ventura 13.0

### Additional Information

https://github.com/fyne-io/fyne/blob/638ae24e4bebfc0b6dbaabf8db5807eeabfafc61/cmd/fyne/internal/commands/build.go#L197

**Comment by Aklscc** [comment]
Hi, I use an `CGO_LDFLAGS` on windows in Makefile:
```makefile
build:
	CGO_LDFLAGS="-H=windowsgui" \
	go build -x -o $(EXE) .
```
And then, I got an error:
`gcc.exe: error: unrecognized command line option '-H=windowsgui'; did you mean '
-mwindows'?`

But If I put it in `go build`, run successfully.
`go build -ldflags -H=windowsgui -o main.exe .` 

What's the difference between them?

**Comment by cra1nbow** [comment]
> Hi, I use an `CGO_LDFLAGS` on windows in Makefile:
> 
> ```makefile
> build:
> 	CGO_LDFLAGS="-H=windowsgui" \
> 	go build -x -o $(EXE) .
> ```
> 
> And then, I got an error: `gcc.exe: error: unrecognized command line option '-H=windowsgui'; did you mean ' -mwindows'?`
> 
> But If I put it in `go build`, run successfully. `go build -ldflags -H=windowsgui -o main.exe .`
> 
> What's the difference between them? @cra1nbow

I think `ldflags` in `go build` is option for golang, not CGO
CGO_LDFLAGS is injected in `gcc` command, `-ldflags` is injected in `go build` command

hiding windows is controlled by golang compiler, so if you want to hide gui, use -ldflags

```makefile
build: go build -ldflags -H=widnowsgui -x -o $(EXE) .
```

**Comment by andydotxyz** [comment]
Also the windows hiding issue is completely handled by `fyne package` so you don't have to learn the details https://developer.fyne.io/started/packaging

**Comment by andydotxyz** [comment]
Fixed on `develop` ready for next release, thanks @PucklaMotzer09
