### ISSUE TITLE
Fyne apps stopped running with `Package gl was not found in the pkg-config search path.`

### ISSUE THREAD

**Issue by s3vt** [fyne-io/fyne#3277]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I was able to run fyne apps on my machine couple of weeks back, but lately upon running I get error as below
```
$ go run cmd/main.go 
  # pkg-config --cflags  -- gl gl
  Package gl was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gl.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gl', required by 'virtual:world', not found
  Package 'gl', required by 'virtual:world', not found
  pkg-config: exit status 1
  # github.com/go-gl/glfw/v3.3/glfw
  In file included from ../../../gowork/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/native_linbsd.go:10:
  ./glfw/include/GLFW/glfw3native.h:114:11: fatal error: GL/glx.h: No such file or directory
    114 |  #include <GL/glx.h>
        |           ^~~~~~~~~~
  compilation terminated.
```

Only changes to the system since last fyne good run are package updates with dnf.

### How to reproduce

1. Write sample fyne app
1. Try to run with `go run main.go`
1. Error occurs

### Example code

```go
package main
import (
  "fyne.io/fyne/v2/app"
)

func main() {
  myapp := app.New()
  mywind := myapp.NewWindow("Window")
  mywind.ShowAndRun()
}
```

### Fyne version

fyne.io/fyne/v2 v2.2.3

### Go compiler version

1.19.1

### Operating system

Linux

### Operating system version

Fedora 36   5.19.9-200.fc36.x86_64

### Additional Information

Only changes to the system since last known good fyne run is package updates with dnf

**Comment by Jacalz** [comment]
That is a compile error and not a runtime error. I think you need to verify that the installed packages are correct. Please see https://developer.fyne.io/started/ for necessary packages
