### ISSUE TITLE
crash in widget.(*textGridRenderer).Layout

### ISSUE THREAD

**Issue by secsys-go** [fyne-io/fyne#3288]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We used the Fuzz engine to modify some Test(TestTextGridRender_WhitespaceTab) data, and then the following crash appeared. After passing in an unreasonable size, there is a problem in processing.

### How to reproduce

The simplified test code is in **Example code**

### Screenshots

CrashLog
```
panic: runtime error: index out of range [5] with length 4 [recovered]
        panic: runtime error: index out of range [5] with length 4

goroutine 79 [running]:
testing.tRunner.func1.2({0x87e8c0, 0xc0001760c0})
        /home/zjx/.local/go/src/testing/testing.go:1211 +0x24e
testing.tRunner.func1()
        /home/zjx/.local/go/src/testing/testing.go:1214 +0x218
panic({0x87e8c0, 0xc0001760c0})
        /home/zjx/.local/go/src/runtime/panic.go:1038 +0x215
fyne.io/fyne/v2/widget.(*textGridRenderer).Layout(0xc000020740, {0x432930, 0xc0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:501 +0x185
fyne.io/fyne/v2/widget.(*BaseWidget).Resize(0xc000432930, {0x432930, 0xc0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/widget.go:61 +0x13e
fyne.io/fyne/v2/widget.(*TextGrid).Resize(0xc000432930, {0x4, 0x0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:84 +0x25
fyne.io/fyne/v2/widget.TestTextGridRender_WhitespaceTab(0x0)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid_test.go:192 +0x4c
```

### Example code

```go
//part of the Test Code
	grid := NewTextGridFromString("\xEF\xBF\xBD\x60")
	grid.ShowWhitespace = true
	grid.Resize(fyne.NewSize(56,1.0938328e+20))
```

### Fyne version

commit 638ae24e4bebfc0b6dbaabf8db5807eeabfafc61 (HEAD -> master, origin/master, origin/HEAD)

### Go compiler version

1.17.8

### Operating system

Linux

### Operating system version

OS: Linux r920 4.15.0-159-generic #167-Ubuntu

**Comment by andydotxyz** [comment]
This doesn't crash any more. Though it will spend a *long* time trying to draw that many rows.
In the future the text grid will only draw what is visible and the performance issue still present will go away.
