### ISSUE TITLE
crash in widget.(*textGridRenderer).setCellRune

### ISSUE THREAD

**Issue by secsys-go** [fyne-io/fyne#3289]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We used the Fuzz engine to modify some Test(TestTextGridRender_WhitespaceTab) data, and then the following crash appeared. It also happens after passing in an unreasonable size, very similar to #3288, but crashes in a different location.

### How to reproduce

The simplified test code is in **Example code**

### Screenshots

CrashLog
```
panic: runtime error: index out of range [13] with length 12 [recovered]
        panic: runtime error: index out of range [13] with length 12

goroutine 15 [running]:
testing.tRunner.func1.2({0x87e8c0, 0xc000024120})
        /home/zjx/.local/go/src/testing/testing.go:1211 +0x24e
testing.tRunner.func1()
        /home/zjx/.local/go/src/testing/testing.go:1214 +0x218
panic({0x87e8c0, 0xc000024120})
        /home/zjx/.local/go/src/runtime/panic.go:1038 +0x215
fyne.io/fyne/v2/widget.(*textGridRenderer).setCellRune(0xc0005c2740, 0x1, 0x5, {0x973f48, 0xc0001d01c0}, {0x0, 0x0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:365 +0x310
fyne.io/fyne/v2/widget.(*textGridRenderer).refreshGrid(0xc0005c2740)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:450 +0x3ff
fyne.io/fyne/v2/widget.(*textGridRenderer).Refresh(0xc0005c2740)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:529 +0xe5
fyne.io/fyne/v2/widget.(*BaseWidget).Refresh(0xc000490930)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/widget.go:138 +0x2e
fyne.io/fyne/v2/widget.(*TextGrid).Resize(0xc000490930, {0x4, 0x0})
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid.go:85 +0x2f
fyne.io/fyne/v2/widget.TestTextGridRender_WhitespaceTab(0x0)
        /home/zjx/workspace/gowork/src/purelib/crashConfirm/fyne/widget/textgrid_test.go:192 +0x4c
```

### Example code

```go
//part of the Test Code
	grid := NewTextGridFromString("\x79\x30\x30\x0A")
	grid.ShowWhitespace = true
	grid.Resize(fyne.NewSize(56,5.717635e+34))
```

### Fyne version

commit 638ae24e4bebfc0b6dbaabf8db5807eeabfafc61 (HEAD -> master, origin/master, origin/HEAD)

### Go compiler version

1.17.8

### Operating system

Linux

### Operating system version

OS: Linux r920 4.15.0-159-generic #167-Ubuntu

**Comment by andydotxyz** [comment]
This is an overflow in `int(math.Max(...))` and occurs when you have > maxInt32 number of rows.
I think it isn't a problem worth fixing
