### ISSUE TITLE
The progress bar in the table column is displayed incorrectly

### ISSUE THREAD

**Issue by faunel** [fyne-io/fyne#3306]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If you make a progress bar in the column of the table, then with very slow scrolling, everything is displayed correctly.
But if you scroll faster, the progress bar is shown in other columns

Sorry for my English

### How to reproduce

Run the program
Start scrolling

### Screenshots

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/18446512/193663756-cf15a8a0-2d38-4e85-b163-e379a82fb113.png">
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/18446512/193663902-d52f309b-e81a-41fa-9dc5-799a605ca7b5.png">

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"strconv"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(1200, 800))
	w.CenterOnScreen()
	w.SetFixedSize(true)

	var header = [][]string{{"Category", "Url", "Count"}}
	var body [][]string

	for i := 1; i < 50; i++ {
		body = append(body, []string{"Notebook", "http://notebook/", strconv.Itoa(i)})
		body = append(body, []string{"TV", "http://tv/", strconv.Itoa(i)})
		body = append(body, []string{"Games", "http://games/", strconv.Itoa(i)})
	}

	data := append(header, body...)

	table := widget.NewTable(nil, nil, nil)

	table.Length = func() (int, int) {
		return len(data), len(data[0])
	}
	table.CreateCell = func() fyne.CanvasObject {
		label := widget.NewLabel("")
		progress := widget.NewProgressBar()
		progress.Hidden = true
		return container.NewMax(label, progress)
	}
	table.UpdateCell = func(id widget.TableCellID, template fyne.CanvasObject) {
		container := template.(*fyne.Container)
		label := container.Objects[0].(*widget.Label)
		progress := container.Objects[1].(*widget.ProgressBar)

		if id.Col != 2 || id.Row == 0 {
			label.SetText(data[id.Row][id.Col])
		} else {
			progress.Min = 0
			progress.Max = 50
			val, _ := strconv.ParseFloat(data[id.Row][id.Col], 32)
			progress.Value = val
			progress.Hidden = false
		}
	}
	table.SetColumnWidth(0, 200)
	table.SetColumnWidth(1, 200)
	table.SetColumnWidth(2, 100)
	w.SetContent(container.NewMax(table))
	w.ShowAndRun()
}
```

### Fyne version

2.2.3

### Go compiler version

1.18.2

### Operating system

macOS

### Operating system version

Monterey

**Comment by andydotxyz** [comment]
As far as I can see you're not hiding the progress bar for cells that shouldn't have one.
