### ISSUE TITLE
Widget concurrency crashes adding buttons

### ISSUE THREAD

**Issue by nateupstairs** [fyne-io/fyne#333]
I'm attempting to add buttons based on some HTTP goroutines. I'm running into pretty expected errors adding those buttons outside of my render loop. I can add `widget.NewLabel("text")`, but a `widget.NewButton(statusText, func() {})` crashes immediately, I suspect because of addition of the button's callback.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4405cd8]`

Again, I basically expected that. But I expected to then find the method of combating the concurrent access.

However, I can't find any documentation or examples that deals with concurrency and I don't seem to be able to locate a Wrap() or mutex of any sort so I can safely add content to my GUI. Is there something hidden away that I'm missing? Or am I skipping over something obvious.

**Comment by andydotxyz** [comment]
Hi, Fyne aims to handle all concurrency internally so you can do exactly what you are trying to do. It should not error even when setting up callbacks etc.

Is it possible to provide a little more information, for example the complete log/stack output? The line you provided does not tell me where in the code the problem was hit.

**Comment by steveoc64** [comment]
Also @nateupstairs - are you running off the master branch, or develop ?

But yeah - full stack trace, and any relevant snippets of your app code, and we can definitely make it work for you.

**Comment by nateupstairs** [comment]
So in an attempt to create a more limited version of this I could post without all of my proprietary stuff in it, I managed to find the issue. It seems as though one of my switch statements was falling though and I was assigning an empty string `""` to a button text. So i guess an empty button text crashes out every time?

`
goroutine 37 [running]:
fyne.io/fyne/widget.(*buttonRenderer).Layout(0xc00036c630, 0x0, 0x0)
	/Users/nateupstairs/go/pkg/mod/fyne.io/fyne@v1.0.1/widget/button.go:57 +0x228
fyne.io/fyne/widget.NewButton(0x0, 0x0, 0x4651c50, 0x6)
	/Users/nateupstairs/go/pkg/mod/fyne.io/fyne@v1.0.1/widget/button.go:199 +0xf0
main.getApps()
	/Users/nateupstairs/Projects/hyp/cmd/gui/main.go:67 +0x24e
created by main.main
	/Users/nateupstairs/Projects/hyp/cmd/gui/main.go:35 +0x1a9`

**Comment by andydotxyz** [comment]
That is great information thanks.
This is now fixes on develop branch which will be released as 1.1 in 1 or 2 days
