### ISSUE TITLE
Add custom hyperlink callback for rich text hyperlinks

### ISSUE THREAD

**Issue by jasmaa** [fyne-io/fyne#3335]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I am working on a graphical browser for the Gemini protocol, and I am using the rich text widget to display page content. When I click a hyperlink in the rich text, I want to load the page within my application. However current behavior opens URL in the web browser by default with no way to customize the behavior for rich text hyperlinks AFAIK.

### Describe the solution you'd like to see.

I think it would be useful to have custom callbacks within rich text hyperlinks. Currently, while the Hyperlink widget supports a custom callback (https://github.com/fyne-io/fyne/issues/2979), this is not supported for HyperlinkSegments in the RichText widget.

One solution would be to add an `OnTapped` field to HyperlinkSegment (following the design for Hyperlink) and pass it to the Hyperlink that gets generated in `HyperlinkSegment.Visual()`:
```go
type HyperlinkSegment struct {
	Alignment fyne.TextAlign
	Text      string
	URL       *url.URL

        // add
	OnTapped  func()
}
```

Example usage:
```go
content := widget.NewRichTextFromMarkdown(`
[link 1](example.com)
[link 2](example.com)
`)

// Set callback for all top-level hyperlink segments
for _, s := range content.Segments {
  if link, ok := s.(*HyperlinkSegment); ok {
    link.OnTapped = func() {
      fmt.Println(link.URL)
    }
  } 
}

```

**Comment by Jacalz** [comment]
One thing I can think of with this is to have a different scheme for the link and register a handler in a similar way to the custom storage repository. Instead of hyperlinks taking a `net.URL`, we can use a `fyne.URI` and register a handler for opening. The default for `https` can then be to open the web browser and other schemes can call out to some OS lookup.

**Comment by andydotxyz** [comment]
If we were to take that approach it should have (or can still?) go into the Hyperlink widget.
This ticket should probably mimic the approach for the main widget I think.

**Comment by Jacalz** [comment]
Yes, that was what I was thinking. I totally agree with you 👍

**Comment by andydotxyz** [comment]
Added on develop
