### ISSUE TITLE
NewEntry widget size problem

### ISSUE THREAD

**Issue by ISeeWorld** [fyne-io/fyne#3337]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

when  put NewLabel, NewEntry , NewButton widget in the same NewHBox, NewEntry size is very small ,Very narrow，

### How to reproduce

```go
func main() {
	a := app.New()
	w := a.NewWindow("PingTest")
	w.Resize(fyne.NewSize(270, 160))

	label := widget.NewLabel("IP:  ")
	input := widget.NewEntry()
	input.SetPlaceHolder("Please Input IP")

	pinglabel := widget.NewMultiLineEntry()
	btn := widget.NewButton("PING", func() {
		fmt.Println("PING...")
	})
	V1 := container.NewHBox(layout.NewSpacer(), label, input, btn, layout.NewSpacer())
	V2 := container.NewHBox(pinglabel)
	content := container.NewVBox(V1, V2)

	w.SetContent(content)
	w.ShowAndRun()

}
```

### Screenshots

![image](https://user-images.githubusercontent.com/10086694/196183306-95dd2bf5-7129-4009-8a4b-230303b13ce6.png)

### Example code

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("PingTest")
	w.Resize(fyne.NewSize(270, 160))

	label := widget.NewLabel("IP:  ")
	input := widget.NewEntry()
	input.SetPlaceHolder("Please Input IP")

	pinglabel := widget.NewMultiLineEntry()
	btn := widget.NewButton("PING", func() {
		fmt.Println("PING...")
	})
	V1 := container.NewHBox(layout.NewSpacer(), label, input, btn, layout.NewSpacer())
	V2 := container.NewHBox(pinglabel)
	content := container.NewVBox(V1, V2)

	w.SetContent(content)
	w.ShowAndRun()

}
```

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

windows10

**Comment by Jacalz** [comment]
This is not a bug with the Entry widget but an effect of how the `HBox` and `VBox` layouts work. They show the widgets at their minimum size (the `MinSize()` method) and will thus not always be the best option for a layout. For the kind of layout you are using, it is usually better to use `container.Border`.

I recommend reading https://developer.fyne.io/faq/layout and looking at https://www.youtube.com/watch?v=LWn1403gY9E.

**Comment by ISeeWorld** [comment]
Thank you for your answer,now i found the reason . may it is a bug .when i use fyne 1.4.3 version ,just use the same code,NewEntry widget size is just ok.I think may fyne 2.2.3 version function  incompatible with fyne 1.4.3 .however thank you for your help.
===========================================
my code 
===========================================
package main

import (
	"fmt"
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("PingTest")
	label := widget.NewLabel("IP:  ")
	input := widget.NewEntry()
	input.SetPlaceHolder("Please Input IP")
	pinglabel := widget.NewMultiLineEntry()
	btn := widget.NewButton("PING", func() {
		fmt.Println("PING...")
	})
	V1 := container.NewHBox(layout.NewSpacer(), label, input, btn, layout.NewSpacer())
	V2 := container.NewHBox(pinglabel)
	content := container.NewVBox(V1, V2)
	w.SetContent(content)
	w.ShowAndRun()

}
===========================================

**Comment by Jacalz** [comment]
This is not a difference between Fyne v1.4.3 and v2.2.3 as far as I know. The code should function just the same. The reason is, as I stated above, because of the wrong layouts being used

**Comment by ISeeWorld** [comment]
Thank you for your answer.The code should function just the same,but in fact different,1.4.3 is ok .

**Comment by andydotxyz** [comment]
The difference is that before fyne v2 the entry did not manage to scroll text, so the widget would grow to fit the content. That is not the default now that the content can be larger than the box.
Either way the right solution is to use a layout that makes the entry fill the space desired, such as Border.

**Comment by andydotxyz** [comment]
By sticking with 1.4 you will have other problems, which is why we changed the default behaviour. Most in v2 onwards it scrolls by default but you can force the old behaviour by setting the wrap mode off. (So your UI will continue to grow as text is entered, like in 1.4).

**Comment by ISeeWorld** [comment]
Thank you very much.fyne is cool ,i will learn more about it.

**Comment by ISeeWorld** [comment]
Thank you very much.I need your help,i have three widgets,and i want to put in the sameHBox,code: V1 := container.NewHBox(layout.NewSpacer(), label, input, btn, layout.NewSpacer()) 
and middle widget is NewEntry,i want NewEntry can expand,how could i write the code,thanks.

**Comment by ISeeWorld** [comment]
> By sticking with 1.4 you will have other problems, which is why we changed the default behaviour. Most in v2 onwards it scrolls by default but you can force the old behaviour by setting the wrap mode off. (So your UI will continue to grow as text is entered, like in 1.4).

how to "setting the wrap mode off"? Thank you very much.

**Comment by andydotxyz** [comment]
> Thank you very much.I need your help,i have three widgets,and i want to put in the sameHBox,code: V1 := container.NewHBox(layout.NewSpacer(), label, input, btn, layout.NewSpacer()) and middle widget is NewEntry,i want NewEntry can expand,how could i write the code,thanks.

Please do use one of our support channels (https://fyne.io/support/) or a GitHub discussion rather than asking questions through bug reports.

The code you need is essentially `container.NewBorder(nil, nil, label, btn, input)` see the docs at https://developer.fyne.io/container/border

**Comment by andydotxyz** [comment]
> how to "setting the wrap mode off"? Thank you very much.

Try `Entry.Wrapping = TextWrapOff` see https://developer.fyne.io/api/v2.2/widget/entry.html.
