### ISSUE TITLE
Update to go-text renderer

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#3338]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We should update to a go-text based renderer for the newly shaped text.
Our internal one is not so great, let's get collaborating on this solution instead.
It doesn't exist yet of course, so work required there first...

### How to reproduce

See we have our own text rendering code, which we should probably not

### Example code

n/a

### Fyne version

v2.3.0-alpha

### Go compiler version

1.18

### Operating system

macOS

### Operating system version

Monterey

**Comment by dweymouth** [comment]
I think this work is all done now
