### ISSUE TITLE
Add ability to expand entry box to fill all available space

### ISSUE THREAD

**Issue by odddollar** [fyne-io/fyne#3341]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I'm writing an app that uses a button to select a folder. The selected path is then filled into an entry box, also allowing users to manually type in the path. I've positioned the button next to the entry widget, but I can't get the entry widget to expand to fill the available width of the window while still maintaining the minimum size button. 

To demonstrate my problem I've pasted some sample code from my app. I would like the button to stick to the right of the window and the entry to fill the remaining space
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	window := app.NewWindow("Hello")

	path := widget.NewEntry()
	path.SetPlaceHolder("Enter a path")

	folderSelect := widget.NewButton("...", func() {})

	window.SetContent(container.New(
		layout.NewHBoxLayout(),
		path,
		folderSelect,
	))

	window.Show()
	window.Resize(fyne.NewSize(300, 50))
	app.Run()
}
```

### Describe the solution you'd like to see.

I would like to request a feature (or an explanation of how to implement this request with existing features) that allows entry boxes to expand to fill all the available width when a button is positioned next to them, or the ability to add a button to the right-hand-side of an entry widget.

**Comment by Jacalz** [comment]
Seems similar to https://github.com/fyne-io/fyne/issues/3337. This is not a feature that needs to be implemented but merely a matter of the wrong layout being used. See response in the other issue: https://github.com/fyne-io/fyne/issues/3337#issuecomment-1280906520
