### ISSUE TITLE
FileDialog - Closing out FileDialog without selecting an item crashes with 'SIGSEGV'

### ISSUE THREAD

**Issue by KomoGit** [fyne-io/fyne#3345]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The bug happened on two different Fyne Projects I have created. I was unable to find the same issue affecting other developers (not on github or any other source) hence why I assume this to be a bug.  Here is an example code that I use for my fileDialogs

```
selectIco := widget.NewButton("Select Icon (OPTIONAL)", func() {
                file_Dialog := dialog.NewFileOpen(
                        func(r fyne.URIReadCloser, e error) {
                                icoLocation = r.URI().String()
                        }, w)
                file_Dialog.SetFilter(storage.NewExtensionFileFilter([]string{".png"})) 
                file_Dialog.Show()
        })
```

Trying to add null safety to icoLocation = r.URI().String() didn't solve the issue. 
```
if(r.URI() != nil){
     icoLocation = r.URI().String()
}else{
      return
}
```

### How to reproduce

1 ) Clicking on a button responsible for opening a FileDialog.
2) Pressing cancel before choosing an item(This could be any item even though code above filters .png files)

This will cause the application to crash out with the following error printed out to terminal:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x92bade]

goroutine 36 [running]:
main.generateUI.func3.1({0x0?, 0x0?}, {0x8bd86e?, 0xc0001ca840?})
 /mnt/sdb1/Personal Files/Programming Projects/GO/LinuxDesktopGen/main.go:73 +0x1e
fyne.io/fyne/v2/dialog.(*fileDialog).makeUI.func3()
 /home/user/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/dialog/file.go:183 +0xff
fyne.io/fyne/v2/widget.(*Button).Tapped(0xc0003e41e0, 0xc0000ac001)
/home/user/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/widget/button.go:194 +0x53
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
/home/user/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:634 +0x26
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
/home/user/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/common/window.go:35 +0x3e
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
/home/user/go/pkg/mod/fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:942 +0x136
exit status 2

```

### Screenshots

![image](https://user-images.githubusercontent.com/63106963/196782309-08e4ad33-b1ef-462b-afdd-4e1bb9e65c4d.png)

### Example code

```
selectIco := widget.NewButton("Select Icon (OPTIONAL)", func() {
                file_Dialog := dialog.NewFileOpen(
                        func(r fyne.URIReadCloser, e error) {
                                icoLocation = r.URI().String()
                        }, w)
                file_Dialog.SetFilter(storage.NewExtensionFileFilter([]string{".png"})) 
                file_Dialog.Show()
        })
```

### Fyne version

v2

### Go compiler version

1.19.2

### Operating system

Linux

### Operating system version

Fedora 36

### Additional Information

Please know that this is my first ever bug report. If i have made any mistakes please do correct me. Thank you.

**Comment by andydotxyz** [comment]
I'm guessing you realised, or read, that it's the `URIReadCloser` that will be nil?

**Comment by KomoGit** [comment]
Toootally. Im an idiot.
