### ISSUE TITLE
app.Storage.Open() to return a known error when file not exist

### ISSUE THREAD

**Issue by bon-ami** [fyne-io/fyne#3353]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

similar to #3083 , I suggest Open() to use an exported error for users to compare.
Android. fyne 2.2.3
Thank you.

### Is it possible to construct a solution with the existing API?

Currently Open() returns "resource not found at URI", which is hard to compare for users.

### Describe the solution you'd like to see.

[internal/driver/mobile/file_android.go](https://github.com/fyne-io/fyne/blob/a83492533a2c9f56dc3e7e1d100ca9b4216edfb6/internal/driver/mobile/file_android.go)
`return nil, errors.New("resource not found at URI")`
to return some error we can match to

**Comment by Bluebugs** [comment]
That's a good point, shouldn't we just return the os.ErrNotExist?

**Comment by andydotxyz** [comment]
> That's a good point, shouldn't we just return the os.ErrNotExist?

No, @bon-ami is right, we added a new storage type for the linked issue as it was not specifically an `os` or `fs` error.

**Comment by LilJohny** [comment]
Can I take it ?

**Comment by andydotxyz** [comment]
Yes please :)

**Comment by LilJohny** [comment]
I prepared a PR, but due to problems with OpenGL on M1 Macs I am not able to test it properly, please take a look.

**Comment by vivekprm** [comment]
Is it still open? Can I work on it?

**Comment by andydotxyz** [comment]
You can see on the linked PR that @LilJohny is working on it. 

Maybe they are not able to finish it and you can try instead?

**Comment by LilJohny** [comment]
Fill free to, I am busy with other things at the moment

**Comment by aditya14as** [comment]
Can I take it?

**Comment by andydotxyz** [comment]
Seems like it's open to be completed, just make sure to read the PR comments so far.

**Comment by 26tanishabanik** [comment]
@andydotxyz , can I take up this issue?
I have gone through the PR comments

**Comment by andydotxyz** [comment]
I don't know - @aditya14as only recently picked it up. Perhaps they can confirm if they are not progressing it?

**Comment by aditya14as** [comment]
Sorry for the delay. @26tanishabanik you can pick it up I’m currently occupied on some other high priority tasks

**Comment by pierrec** [comment]
Fixed in PR 5151.
