### ISSUE TITLE
Install command for fyne command line tool doesn't work ( or the readme is misleading / incomplete )

### ISSUE THREAD

**Issue by manuel-koch** [fyne-io/fyne#3355]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I tried to follow the snippet of fyne readme to install the fyne commandline tool:

```
$ go get fyne.io/fyne/v2/cmd/fyne
$ fyne install
```

Afterwards I can't find the `fyne` tool ?

I have tried the following

```
$ go get fyne.io/fyne/v2/cmd/fyne
go: downloading github.com/urfave/cli/v2 v2.4.0
go: downloading github.com/go-ole/go-ole v1.2.6
go: downloading github.com/jackmordaunt/icns/v2 v2.2.1
go: downloading github.com/lucor/goinfo v0.0.0-20210802170112-c078a2b0f08b
go: downloading github.com/josephspurrier/goversioninfo v1.4.0
go: downloading github.com/mcuadros/go-version v0.0.0-20190830083331-035f6764e8d2
go: downloading golang.org/x/mod v0.4.2
go: downloading github.com/BurntSushi/toml v1.1.0
go: downloading golang.org/x/tools v0.1.8-0.20211022200916-316ba0b74098
go: downloading github.com/akavel/rsrc v0.10.2
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.1
go: downloading github.com/russross/blackfriday/v2 v2.1.0

$ fyne --help
zsh: correct 'fyne' to 'bye' [nyae]? %                                                                                                                                                                                                  

$ rehash

$ fyne --help
zsh: correct 'fyne' to 'bye' [nyae]? n
zsh: command not found: fyne

$ which fyne
fyne not found
```

What am I missing ? Is there any hidden command that needs to be run to actually make "fyne" available ?

After searching a little more I found out that it seems to work when doing the following instead
- just "go get" only seem to fetch the tools sources, but don't build it
- I don't have "." in my PATH and hence need to explicitly select the executables path

```
$ go get fyne.io/fyne/v2/cmd/fyne
$ go build fyne.io/fyne/v2/cmd/fyne
$ ./fyne --help
```

### How to reproduce

1. run the suggested install command `go get fyne.io/fyne/v2/cmd/fyne`
2. execute `fyne` tool
3. `fyne` is not available

### Example code

see description above

### Fyne version

fyne.io/fyne/v2 v2.2.3

### Go compiler version

go version go1.19.2 darwin/arm64

### Operating system

macOS

### Operating system version

MacOS Monterey 12.6 (Apple M1 Pro)

**Comment by andydotxyz** [comment]
It looks like your PATH does not include the $GOPATH/bin. This would normally be set up by the installer.

**Comment by manuel-koch** [comment]
Hm, even if that were in my PATH, it doesn't exist:
```
$ find $GOPATH/bin
find: /Users/manuelkoch/go/bin: No such file or directory
```

**Comment by manuel-koch** [comment]
Seems like `go get` is deprecated in the go version I'm using: https://go.dev/doc/go-get-install-deprecation
It states `In Go 1.18, go get will no longer build packages`, which explains why my go environment (go1.19.2) behaves like it does.

**Comment by andydotxyz** [comment]
Oh gees, I didn't realise that 2 point releases later they had turned off deprecated functionality...
