### ISSUE TITLE
Adding arguments to functions linked to buttons

### ISSUE THREAD

**Issue by TheBrainScrambler** [fyne-io/fyne#336]
```go
s := "You clicked me !"
button := widget.NewButton("Click me", func(s string) {
  fmt.Println(s)
})
```
Would be great if we could do something like this.

**Comment by andydotxyz** [comment]
I expect that the example above is just a trivial example, because you could just do:

s := "You clicked me !"
button := widget.NewButton("Click me", func() {
  fmt.Println(s)
})

Assuming that you wanted to do something more complex that is not currently possible can you explain the aims?

**Comment by TheBrainScrambler** [comment]
Sorry for the inactivity.
I want to pass arguments to the function triggered by clicking a button. It is currently not possible because widget.NewButton() needs a func() as argument, a func(string) for example is not allowed. So can you implement something to do this ?

**Comment by TheBrainScrambler** [comment]
My example was bad. I wanted to pass a separate function with arguments to the button that it will launch when clicked. So something like this :

```go
func toLaunch(s string) {
  fmt.Println(s)
}

button := widget.NewButton("Click me", toLaunch("You clicked me !")
```
Actually not possible because toLaunch is a func(string) and NewButton needs func()

**Comment by skrater** [comment]
@TheBrainScrambler you can do something like:

```golang
func toLaunch(s string) func() {
  return func() {
     fmt.Println(s)
  }
}

button := widget.NewButton("Click me", toLaunch("You clicked me !"))
```

It's pretty common to do stuff like that using the http library in go.

**Comment by andydotxyz** [comment]
I think that here you can make use of Go's function passing, something like:

```
button := widget.NewButton("Click me", func() {toLaunch("You clicked me !")})
```

This way we can avoid adding additional type parameters to the callback functions

**Comment by TheBrainScrambler** [comment]
That is what I searched for, thank you for the help !

**Comment by MeghrajBhanu** [comment]
Hey can we stle the button and dropdown list to look something like this 
![image](https://user-images.githubusercontent.com/65539500/117147102-8de0f600-add2-11eb-8e0a-4853c08bcf35.png)

**Comment by Jacalz** [comment]
@MeghrajBhanu Please stick to the topic of the issues in question. I would recommend asking questions in the #fyne channel on Gophers slack instead.
