### ISSUE TITLE
Bump up GLFW dependency to 3.3.8

### ISSUE THREAD

**Issue by vazub** [fyne-io/fyne#3362]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Latest version of this dependency fixes some issues under OpenBSD and also introduces a lot of Wayland improvements. 

### Describe the solution you'd like to see.

Please update the glfw dependency to the latest stable tag - https://github.com/go-gl/glfw/commit/55e207c401ad9f8f19b7719272b98fed91b6e091

**Comment by andydotxyz** [comment]
This was already completed on `develop` branch ready for v2.3.0 https://github.com/fyne-io/fyne/pull/3131
