### ISSUE TITLE
[Developer Version] Entry Copy/Paste etc. does not work

### ISSUE THREAD

**Issue by EinsKatze** [fyne-io/fyne#3368]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Shortcuts like CTRL + A, CTRL + C, CTRL + V and CTRL + Backspace are not working in Entries.
It does work in the v2.2.3, however in the develop version it does not work.

Pasting/Copying with the Right Click Menu does work.

### How to reproduce

1. Create a Entry in your Window
2. Try to use the shortcuts

### Example code

Hopefully this code does show you that its not working.
```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/container"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	window := a.NewWindow("Pasting Bug Report")
	window.Resize(fyne.NewSize(150, 100))

	entry := widget.NewEntry()
	content := container.New(
		layout.NewVBoxLayout(),
		entry,
	)
	window.SetContent(content)
	window.ShowAndRun()
}
```

### Fyne version

v2.2.4-0.20221029195242-d2811be4b980

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

22H2

### Additional Information

For further Information i will try to give them here in the issue.
To contact me privately you can send a message on Discord (EinsKatze²#9444).

**Comment by Jacalz** [comment]
I think I know what caused this. Will get this fixed.

**Comment by andydotxyz** [comment]
Should be working again, sorry about that!

**Comment by EinsKatze** [comment]
> Should be working again, sorry about that!

It does. Thank you for fixing it!
