### ISSUE TITLE
Release 1.1 - Page up/down in an Entry is ignored

### ISSUE THREAD

**Issue by jestor** [fyne-io/fyne#338]
Expected behaviour:
Single line: The cursor should jump to the start/end of the line and any text selection should be hidden.
Multi line: The cursor should jump a page up or down in the Entry, where a page is determined by the amount of visible rows. Any text selection should be hidden.

**Comment by andydotxyz** [comment]
Agreed, with the exception that the page size should probably be slightly less than the visible rows - we need to retain some context when making such a jump.

**Comment by andydotxyz** [comment]
The basics are in, will need more work once #471 is in to handle pages of content when the widget is smaller than the content
