### ISSUE TITLE
RagioGroup miscalulates label widths in horizontal mode

### ISSUE THREAD

**Issue by grkuntzmd** [fyne-io/fyne#3386]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When long labels are used in the RagioGroup in horizontal mode, they overlap.

### How to reproduce

`go run  .`

### Screenshots

![image](https://user-images.githubusercontent.com/703718/200319477-ff4b62da-fe28-4a5c-b522-d0ccdab83950.png)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Radio Group Bug")

	rg := widget.NewRadioGroup([]string{"Easy", "Medium", "Hard", "Expert"}, func(s string) {})
	rg.Horizontal = true

	w.SetContent(rg)
	w.ShowAndRun()
}
```

### Fyne version

2.2.3

### Go compiler version

1.19.3

### Operating system

Windows

### Operating system version

Windows 11 Pro Version	22H2

**Comment by vinser** [comment]
It's a pity but the bug still is being on. Why it's marked as Unverified?

In horizontal mode Layout method calculates average width size for radioGroup items/ 
```go
// Layout the components of the radio widget
func (r *radioGroupRenderer) Layout(_ fyne.Size) {
	count := 1
	if r.items != nil && len(r.items) > 0 {
		count = len(r.items)
	}
	var itemHeight, itemWidth float32
	minSize := r.radio.MinSize()
	if r.radio.Horizontal {
		itemHeight = minSize.Height
		itemWidth = minSize.Width / float32(count) // HERE IS THE BUG
	} else {
		itemHeight = minSize.Height / float32(count)
		itemWidth = minSize.Width
	}

	itemSize := fyne.NewSize(itemWidth, itemHeight)
	x, y := float32(0), float32(0)
	for _, item := range r.items {
		item.Resize(itemSize)
		item.Move(fyne.NewPos(x, y))
		if r.radio.Horizontal {
			x += itemWidth
		} else {
			y += itemHeight
		}
	}
}

```
The bug makes horizontal items to overlap if they have different width and it looks poor :(
 
![image](https://user-images.githubusercontent.com/14954512/227704939-ee8745b4-bea0-4dda-b687-2d9a12e06b74.png)
 
Should I make a PR to eliminate the bug or someone have done this already?

**Comment by andydotxyz** [comment]
Fixed on develop
