### ISSUE TITLE
Release 1.1 - Entry loses focus if the mouse leaves an Entry during a drag text selection

### ISSUE THREAD

**Issue by jestor** [fyne-io/fyne#339]
This prevents any further keyboard interaction with the Entry until is is given focus again.

**Comment by andydotxyz** [comment]
The solution here may relate to the work that was done for scrollbar dragging?

**Comment by jestor** [comment]
Focus is lost when the mouse up event is sent. If the mouse button is held during a selection drag then keyboard events will be sent correctly to the Entry where the drag event started.
