### ISSUE TITLE
Text wrapping and truncation simultaneously

### ISSUE THREAD

**Issue by Elara6331** [fyne-io/fyne#3391]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I have a very long string of text. I'd like to be able to apply `TextWrapWord` to it, but also have it truncate when it can't go down anymore because it will overflow the widget it's in.

### Is it possible to construct a solution with the existing API?

The only way I can see to do this is to wrap it in a VScroll layout, but I do not want to allow scrolling, so that isn't really helpful.

### Describe the solution you'd like to see.

I'd like either some new text wrapping methods that also truncate the text once it gets too long vertically (probably the better way), or a layout that cuts everything off like VScroll, but without scrolling support.

**Comment by phllpmcphrsn** [comment]
Sounds like a good feature to have. Do you have an example of the issue that you can show?

**Comment by Arsen6331** [comment]
![Image of text overflowing element](https://user-images.githubusercontent.com/41810442/201263325-56cd69be-dde5-4c06-8d1f-58aa17dedc34.png)

As you can see, the text is wrapped when it's going to overflow horizontally, but I want it to also truncate when it's going to overflow vertically.

**Comment by Jacalz** [comment]
I think this is resolved now. What do you recon @andydotxyz?

**Comment by andydotxyz** [comment]
Agreed, I forgot this ticket existed!
