### ISSUE TITLE
Systray apps on macOS can only be terminated via the systray menu quit button

### ISSUE THREAD

**Issue by d1ss0nanz** [fyne-io/fyne#3395]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Systray apps on macOS can only be terminated by clicking on the systray Quit button.

This even interupts restart and shutdown of the OS (see screenshot).

### How to reproduce

Try to quit the attached program by either clicking Quit in the dock or using the "Restart..." or "Shut Down..." function of macOS.
Neither will work.

### Screenshots

![Screenshot 2022-11-12 at 21 22 42](https://user-images.githubusercontent.com/7532776/201493189-94348a6b-b78d-4f80-b985-58ae6158ecc5.png)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")
	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.Hide()

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetCloseIntercept(func() {
		w.Hide()
	})
	a.Run()
}
```

### Fyne version

2.2.4

### Go compiler version

1.18.4

### Operating system

macOS

### Operating system version

13.0.1

### Additional Information

Tried with different (older) macOS versions. Same result.

**Comment by andydotxyz** [comment]
I have finally tracked this down...

GLFW terminates an app by closing all the windows.
And we have told an app with systray to not close when the windows are shut.

Not yet sure how to resolve this, probably some more complex fix to GLFW required...

**Comment by andydotxyz** [comment]
Fixed on `develop`
