### ISSUE TITLE
Initial text rendering is blurry on develop

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3402]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I noticed when testing `cmd/hello ` for #3401 that the initial text that is rendered on start-up seems to be blurry but resizing or updating the window in some other way, such as pressing the button, makes it redraw without being blurry.

### How to reproduce

1. Compile and run two versions of `cmd/hello` at the same time.
2. Resize, or press the button, in one of the windows.
3. Notice that the text initially is blurry but then gets sharper (and slightly brighter) after the window is updated.

### Initial draw:
![Screenshot from 2022-11-13 19-30-52](https://user-images.githubusercontent.com/25466657/201538262-afc778a0-0a8a-41e2-a98d-5169bcf39e0d.png)

### Window resized:
![image](https://user-images.githubusercontent.com/25466657/201538301-ac505e73-0d6d-46e2-814e-e656da2c98a3.png)

### Button pressed:
![image](https://user-images.githubusercontent.com/25466657/201538314-ecb615a4-192d-4ff7-8755-37893f561bea.png)

### Example code

Just use `cmd/hello` for tests.

### Fyne version

4c67d93aa35be8646ba9c4354acb0492d5115f4d

### Go compiler version

1.18.7

### Operating system

Linux

### Operating system version

Fedora 36

**Comment by Bluebugs** [comment]
I can definitively reproduce this one. Will see if I can figure out what is going on, but it seems like the initial texture size doesn't match the surface size it is drawn to by maybe 1 pixel and then things get correct.

**Comment by Bluebugs** [comment]
Just to add here, it is possible to resize the window back to its original minimal size and the rendering in that case is sharp. Investigation on to why blurry is still going on.

**Comment by Bluebugs** [comment]
This seems to be due to an imprecision of the canvas size at start somehow. Resize correct the canvas size as it get directly that size from the pixels value.

**Comment by andydotxyz** [comment]
Resolved on develop thanks @Bluebugs
