### ISSUE TITLE
Use struct to encapsulate CanvasObject and set Content not to display

### ISSUE THREAD

**Issue by josexy** [fyne-io/fyne#3404]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Originally I wanted to embed the `CanvasObject` into the struct and set the display content through `SetContent`, but when using the created struct object, the `CanvasObject` cannot be displayed. For example, in the following code, the `CanvasObject` (actually `widget.Label`) is saved through the `wrapper`, but `w.SetContent(newWrapper())` cannot successfully display the Label

### How to reproduce

1. Compile go code 
2. Switch the comment `SetContent` and recompile, and compare the running results

### Screenshots

the label display 
<img width="193" alt="1" src="https://user-images.githubusercontent.com/30660121/201611191-e89f185f-ecf0-4dba-a477-a3e8fece5198.png">

the label don't display
<img width="212" alt="2" src="https://user-images.githubusercontent.com/30660121/201611294-9afaaa39-98cb-4923-a6f2-4ee41f94a84b.png">

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

type wrapper struct {
	fyne.CanvasObject
}

func newWrapper() *wrapper {
	return &wrapper{
		CanvasObject: widget.NewLabel("hello world"),
	}
}

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	// w.SetContent(widget.NewLabel("Hello World!"))
	w.SetContent(newWrapper())

	w.ShowAndRun()
}

```

### Fyne version

2.2.4

### Go compiler version

1.19.3

### Operating system

macOS

### Operating system version

13.0

**Comment by andydotxyz** [comment]
Only `Widget`s can be extended in this way.
https://developer.fyne.io/extend/extending-widgets
What you are doing would work if you change the type to `widget.Label` or `widget.BaseWidget` and then call `ExtendBaseWidget` as per the doc above.

**Comment by josexy** [comment]
Thanks for your answer. I'm using fyne for the first time. How can I modify the code in the example above?

**Comment by andydotxyz** [comment]
That's what I tried to explain in my last message - what's not working for you?

**Comment by josexy** [comment]
Ok, I will do that.
