### ISSUE TITLE
something suggestions

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3409]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Two suggestions

1. Add an app method app. requestWindowFeature (Window. FEATURE_NO_TITLE) to hide the app Window

2. It should support custom app background theme (icon jpg png jpeg gif), etc

You can add the widget or app method widget SetBackTheme() widget.Canavs.SetBackTheme()

The author is very good Thank you

### Describe the solution you'd like to see.

Two suggestions

1. Add an app method app. requestWindowFeature (Window. FEATURE_NO_TITLE) to hide the app Window

2. It should support custom app background theme (icon jpg png jpeg gif), etc

You can add the widget or app method widget SetBackTheme() widget.Canavs.SetBackTheme()

The author is very good Thank you

**Comment by andydotxyz** [comment]
I think you might find the splash window in desktop driver useful. Example at https://stackoverflow.com/questions/62383370/how-to-create-fyne-splash-screen-i-dont-find-any-widget-in-fyne-gui-toolkit.

**Comment by andydotxyz** [comment]
To set a background image is not part of a theme, but can be set in your app - add an image and the app content to a the window using a Max container:

`SetContent(container.NewMax(bg, Content))`

**Comment by hq-zhonger** [comment]
w.SetContent(container.NewMax(fromResourceBg, container.NewHBox(tabs, label)))&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 上午6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fyne-io/fyne] something suggestions (Issue #3409)





 
To set a background image is not part of a theme, but can be set in your app - add an image and the app content to a the window using a Max container:
 
SetContent(container.NewMax(bg, Content))

**Comment by hq-zhonger** [comment]
Thank you, boss. I have been able to set the background theme. Is there a built-in method to directly adjust the brightness or virtualization of the background color?
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 上午6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fyne-io/fyne] something suggestions (Issue #3409)





 
To set a background image is not part of a theme, but can be set in your app - add an image and the app content to a the window using a Max container:
 
SetContent(container.NewMax(bg, Content))

**Comment by andydotxyz** [comment]
The background colour is part of the theme. You can provide a custom theme that overrides this colour:

https://developer.fyne.io/extend/custom-theme

**Comment by Jacalz** [comment]
I just want to quickly point out that we prefer issues to only contain one feature/bug per issue (per the second checkbox at the top of your issue description). Please open separate issues in the future
