### ISSUE TITLE
new windows randomly blank(white) until resized

### ISSUE THREAD

**Issue by roffe** [fyne-io/fyne#3423]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

At random times non master windows will just render as white content. I have not been able to reproduce it and i have tried changing order of resize, show, layout and tried everything I can to solve it

![image](https://user-images.githubusercontent.com/5434736/203597856-3c8bd538-d590-4a6a-8a50-7a60c5e44dcb.png)

if I resize the defunct window the content starts showing

![image](https://user-images.githubusercontent.com/5434736/203597986-3c694d0c-5125-4ca8-a0da-38824a40c258.png)

### How to reproduce

clone EEP repo
go run .
press settings or help button and sometimes they will randomly be completely white inside and resizing them makes them show content again

### Example code

Code for project is here

https://github.com/Hirschmann-Koxha-GbR/eep/tree/master/gui

### Fyne version

v2.2.4

### Go compiler version

go1.19.3

### Operating system

Windows

### Operating system version

Windows 11 22H2 Build 22621.819

**Comment by roffe** [comment]
It seems that it's some race condition in starting the app. once i get the white window effect. resizing it makes it paint, then i close it and open it again but now it's white with the new window size

![image](https://user-images.githubusercontent.com/5434736/204010149-402ad40b-1855-44e9-8fbd-ec4e1ec6eb36.png)

![image](https://user-images.githubusercontent.com/5434736/204010171-8fb61974-9219-4ca5-b4a9-661fa51194a9.png)

![image](https://user-images.githubusercontent.com/5434736/204010195-dc964ef3-819d-407e-afca-95a52facfb41.png)

![image](https://user-images.githubusercontent.com/5434736/204010217-b57b2e01-1a9b-4072-b83b-c5e14572ad96.png)

**Comment by roffe** [comment]
hmm it seems windows that i create new works but the re-used windows like settings and help which i Hide() instead of close is the ones bugging out

**Comment by andydotxyz** [comment]
> hmm it seems windows that i create new works but the re-used windows like settings and help which i Hide() instead of close is the ones bugging out

Oh interesting, how does the window get re-shown after it is hiden?

**Comment by roffe** [comment]
on app start i have some structs like the following to create my windows

```go
type settingsWindow struct {
	e                *EEPGui
	w                fyne.Window
	ignoreError      *widget.Check
	readSliderLabel  *widget.Label
	readSlider       *widget.Slider
	writeSliderLabel *widget.Label
	writeSlider      *widget.Slider
	updateButton     *widget.Button
}
```

when i then want to show them i call the .w.Show() function and then i have a onclose interceptor that Hide() the window so i can re-use it to be shown again

**Comment by roffe** [comment]
Im making some experiments where i always create new windows and assign the window to my pointer while it's open, and then i check if that pointer is != nil then i call .SetFocus() to get the window to the foreground instead of opening a new

**Comment by andydotxyz** [comment]
I understand that this cannot be reliably reproduced, but is there a minimal code sample that you can share where you've seen this behaviour?

**Comment by roffe** [comment]
Since I stopped trying to re-use windows with Show() and Hide() and always create a new one it it's not happened anymore. 

I will try to see if I can make some code to try to trigger it

**Comment by xbojer** [comment]
On my computer with roffe's software this bug always happen

**Comment by andydotxyz** [comment]
Is this shown with both the light and dark themes?

**Comment by andydotxyz** [comment]
Looking more at it there is a lot of custom painting going on here. If you use a standard dialog does the problem go away?

And/or can you provide the code that creates the erroneous screen? (Not just a link to a whole repository).

**Comment by andydotxyz** [comment]
Does it work as expected without your custom theme?

**Comment by andydotxyz** [comment]
Then I'm guessing the PCs that it doesn't work on have a different theme variant default (light vs dark) compared to your working PC.
Your custom theme is missing some colours that the toolkit is providing - my guess is that `ColorNameOverlayBackground` would be most likely.

Closing as not an issue.

**Comment by andydotxyz** [comment]
Sorry I'm not sure what "theme generator" you are referring to - but if you are using a third party to generate code you will need to make sure the version it is designed for matches the version your app uses. I guess they are not up to date with our latest release...

**Comment by vinser** [comment]
Hi 
I have the same issue on Windows 10 22H2
When the app starts the single base window is empty. 
When the window is resized or when it is minimized and then maximized, all elements in the window become visible.
No matter what theme is used custom or default.
I built the app using MSYS2 and TDM-GCC the result was the same.
On my SBC with Ubuntu arm64 it builds and works fyne.

**Comment by vinser** [comment]
In my case this happens when current folder is empty so grid gets zero size

**Comment by andydotxyz** [comment]
Please avoid commenting on closed issues. In the future if you want to report an issue open a new ticket.
