### ISSUE TITLE
Layout recompute when widgets are hidden

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#343]
Consider the case of a HBox that contains a number of buttons

```
[Button A] [Button B] [Button C] [Button D]
```

If, say, [Button B] is hidden by programmatically calling `buttonB.Hide()`, expected behaviour would be that the hbox layout renders the remaining buttons without gaps. 

```
[Button A] [Button C] [Button D]
```

Observed behaviour is instead
```
[Button A]           [Button C] [Button D]
```

Task:   Fix the layout calculations so that they dont consider hidden elements.

Having said that, It would be nice to support both behaviours with a minimal change to the API if thats possible.

I do have at least 1 case where the current observed behaviour is actually preferrable over the expected behaviour ... so maybe we can do both ?

**Comment by steveoc64** [comment]
Testing:

- Add tests to prove the behaviour
- Is it just HBox / VBox, or are all layouts affected ?

**Comment by okratitan** [comment]
Hidden items should not be accounted for in layout calcs so definitely need a fix here.

**Comment by andydotxyz** [comment]
This is proving to be a little more complicated.
A tab container calculates it's minSize based on all the tabs so that it does not resize as tabs change.
With this change that no longer works as the hidden tabs are now ignored.

Not sure what to do now... what do people think?

**Comment by andydotxyz** [comment]
Removing from 1.1.1 as I am not certain this is the right approach yet.

**Comment by andydotxyz** [comment]
With #384 merged this is worth revisiting, trying to see if I have my old patch to hand

**Comment by andydotxyz** [comment]
Assuming we are happy to land the visibility changes into 1.1.1 then this bug too should be landed for that release.

**Comment by andydotxyz** [comment]
ready for testing on develop
