### ISSUE TITLE
Window's canvas doesn't detect keyboard events until mouse clicks canvas

### ISSUE THREAD

**Issue by neetle** [fyne-io/fyne#344]
Hi! 

I really appreciate the work you're putting in on this, it's made my life a lot easier while writing my [diary](https://github.com/neetle/diary)!

I'm currently seeing that immediately after launching the application in osx, the window assumes focus but the associated canvas doesn't seem to be picking up keyboard events. 

tidbits found while poking around: 
 - This issue seems to resolve itself after clicking on the canvas. Given how I want this application to work (hotkey, type, close) this is a dealbreaker. 
 - From what I can see via `osascript`, the application is assuming keyboard focus on startup so the issue doesn't seem to be there. 

If you've any idea on where the problem could lie and/or you're open to PR's, I'm happy to pitch in where I can.

**Comment by andydotxyz** [comment]
This certainly should not happen. Can you please confirm the version of macOS you are using?

**Comment by andydotxyz** [comment]
I just tested (on High Sierra) the calculator example (in examples repo execute `go run . -calculator`) and it seemed to work fine.
This may be a macOS version issue but perhaps there is something with your code? Feel free to share a small example code that demonstrates the issue if you'd like us to look into it.

**Comment by neetle** [comment]
On Mojave the calculator example works too. It's just my code. Oops. 

On closer inspection, it looks like the calculator example is using 
```go
	c.window.Canvas().SetOnTypedRune(c.typedRune)
	c.window.Canvas().SetOnTypedKey(c.typedKey)
```

whereas my code is using ([here](https://github.com/neetle/diary/blob/afd1d060012c819c2ff08a5204d978bae7438ad6/view/core.go#L55))
``` go 
         box := widget.NewMultiLineEntry()
	box.OnChanged = func(content string) {
		m.out.Publish(intent.ContentUpdated(content))
	}
	[...]
	box.FocusGained()
```

Do I need to use the `window.SetOnTypedRune`/`window.SetOnTypedKey` api instead?

**Comment by neetle** [comment]
Looks like throwing in a 
``` go 
	w.Canvas().SetOnTypedRune(func(rune) {
		log.Println("dong")
	})
	w.Canvas().SetOnTypedKey(func(*fyne.KeyEvent) {
		log.Println("ding")
	})
```
works as you described too...

**Comment by andydotxyz** [comment]
Ah this makes sense. The answer is it depends :)
MultiLineInput (like other input fields) needs focus to get events. If you want to have multiple inputs and/or allow the user to interact with other fields (which is usually the case) then you are using the correct widget.
Using inputs the focus is normally obtained by tapping - if you want it to be focused by default then you could use w.Canvas().Focus(myWidget).
