### ISSUE TITLE
Multiple Tables in a container do not refresh properly initially

### ISSUE THREAD

**Issue by PaulWaldo** [fyne-io/fyne#3441]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If two tables are placed in a container and the window size is small enough to require scrollers, the initial rendering results in blank cells

### How to reproduce

1. Run the code below
2. Note that the top table is not fully drawn (some cells are blank)
3. Scroll or resize and note that the previously blank cells are rendered
4. Change the initial window size to 600, 600 and note the problem does not occur

### Screenshots

Window when initially run

![CleanShot 2022-11-30 at 12 18 30@2x](https://user-images.githubusercontent.com/12105941/204864787-76779be9-888e-41a6-b89f-69c78e9b65cc.png)

Window after clicking on a cell

![CleanShot 2022-11-30 at 12 19 22@2x](https://user-images.githubusercontent.com/12105941/204865032-22df0b20-0ccb-4b18-80f0-26ebacbc5aeb.png)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type Data struct {
	f1, f2, f3, f4 string
}

func main() {
	data := []Data{
		{f1: "f1row1", f2: "f2row1", f3: "f3row1", f4: "f4row1"},
		{f1: "f1row2", f2: "f2row2", f3: "f3row2", f4: "f4row2"},
		{f1: "f1row3", f2: "f2row3", f3: "f3row3", f4: "f4row3"},
		{f1: "f1row4", f2: "f2row4", f3: "f3row4", f4: "f4row4"},
	}

	a := app.New()
	w := a.NewWindow("Table Tester")
	t1 := widget.NewTable(
		func() (int, int) { return len(data), 4 },
		func() fyne.CanvasObject { return widget.NewLabel("sample") },
		func(tci widget.TableCellID, co fyne.CanvasObject) {
			s := "unknown"
			switch tci.Col {
			case 0:
				s = data[tci.Row].f1
			case 1:
				s = data[tci.Row].f2
			case 2:
				s = data[tci.Row].f3
			case 3:
				s = data[tci.Row].f4
			}
			l := co.(*widget.Label)
			l.SetText(s)
		},
	)
	t2 := widget.NewTable(
		func() (int, int) { return len(data), 4 },
		func() fyne.CanvasObject { return widget.NewLabel("sample") },
		func(tci widget.TableCellID, co fyne.CanvasObject) {
			s := "unknown"
			switch tci.Col {
			case 0:
				s = data[tci.Row].f1
			case 1:
				s = data[tci.Row].f2
			case 2:
				s = data[tci.Row].f3
			case 3:
				s = data[tci.Row].f4
			}
			l := co.(*widget.Label)
			l.SetText(s)
		},
	)
	// w.SetContent(container.NewVBox(t1, t2))
	w.SetContent(container.NewBorder(t1, nil, nil, nil, t2))

	w.Resize(fyne.NewSize(200, 200))
	w.ShowAndRun()
}
```

### Fyne version

2.2.4

### Go compiler version

1.19.2

### Operating system

macOS

### Operating system version

Monterey

**Comment by andydotxyz** [comment]
I think this does not relate to multiple tables - it seems to be when one table is larger than its content.
A new issue that was also reported with a simpler replicating steps in #3443
