### ISSUE TITLE
New light theme has some elements that are far too low contrast

### ISSUE THREAD

**Issue by nickjwhite** [fyne-io/fyne#3444]
The new light theme looks much better, but there are some regressions in clarity and accessibility. I mentioned this in #3042, but was advised to open a new bug for it.

The borders around radio items and checkboxes, as well as any disabled text or buttons, are really so light as to be almost indistinguishable even with good eyesight. I suspect it looks even worse on my monitor as it's HiDPI so the borders are also very thin.

New theme:
![t1](https://user-images.githubusercontent.com/4385492/205033926-a3b0eed0-0659-4d61-82ae-2300d18f13bf.png)
Old theme for comparison:
![t3](https://github.com/fyne-io/fyne/raw/master/img/widgets-light.png)

Using a darker grey would fix the issue, and the theme wouldn't need to be any less aesthetically pleasing.

### How to reproduce

1. `git clone https://github.com/fyne-io/fyne`
2. `git checkout origin/develop`
3. `go run ./cmd/fyne_demo`
4. Navigate to Widgets -> Button & Widgets -> Input and squint to find the disabled button, disabled radio, and the checkboxes and radios

### Fyne version

dbdb9fc26091aa11aa05fb2ff7067589f63bfedd

### Go compiler version

go1.20-a4844eb377

### Operating system

Linux

### Operating system version

Debian 11.5

**Comment by nickjwhite** [comment]
I just found that the issue is much more noticeable on my external monitor than my laptop screen. Not sure why, I guess it may because my laptop screen is OLED so does a better job of displaying the colours, or my monitor is doing some unwelcome processing of the image. Even if the latter is true, though, this is still not great; we don't want to rely on users having perfect quality screens to get a good experience (and it's still quite faint even on my laptop).

**Comment by andydotxyz** [comment]
I think the background colour being added to the inner part of the item was aimed to mean it could be less obvious on the outline. We probably need to get some more thoughts on this.
Do you think it would be possible to show how low-contrast it is on your hardware by photographing the screen?

**Comment by nickjwhite** [comment]
I'm attaching a photo of how terrible it looked on my monitor (taken with a digital camera).
![badcontrast](https://user-images.githubusercontent.com/4385492/206724269-6190069c-a28f-4fcc-bdda-43ce3f92434c.jpg)

This turned out to be a great way to improve the settings of the monitor, though, as it was a perfect test case of "processing doing terrible things". Turned out that turning the "contrast" setting DOWN from 90 to 65 made it all much better, see this photo:
![bettercontrast](https://user-images.githubusercontent.com/4385492/206724310-b4f49f3c-4b60-4dc4-8364-aa2cbd882c88.jpg)

As I said, the older theme was fine with both - I guess it's a combination of lighter colours and thinner lines got caught in some dodgy processing pipeline. I do think that being more resilient to these sorts of things - as well as more resilient to impaired eyesight - by using somewhat darker lines or whatever would be worthwhile, but I'm certainly relieved to find that the new theme is nowhere near as ususable as I'd initially experienced it!

**Comment by andydotxyz** [comment]
Thanks. We should improve on this, but let's not call it a blocker now :)

**Comment by andydotxyz** [comment]
Subtle colour updates for the pending v2.3.5 - if you like you can test the branch release/v2.3.x already.
Let me know if that works :)

**Comment by nickjwhite** [comment]
Yeah it looks good, I'm happy for it to be closed, thanks!
