### ISSUE TITLE
Weird behavior when looping through widget.Entry slice

### ISSUE THREAD

**Issue by brokenarmor451** [fyne-io/fyne#3446]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When i loop through a slice of widget.Entry to set OnSubmitted function of every widget.Entry item. And when i write something to a entry except last one then i press enter, the last widget.Entry's OnSubmitted function is running. The actual entry's OnSubmitted is not working.

### How to reproduce

Go to any text editor
Write the code which i present
Run the code
Then write something to any entry except last one
Then press enter
You will see the last entry's OnSubmitted function is running

### Example code

```go
package main

import (
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	
	w := a.NewWindow("Some Practice")
	
	w.Resize(fyne.NewSize(400, 400))
	
	entries := []fyne.CanvasObject{widget.NewEntry(), widget.NewEntry()}
	
	for i, entry := range entries {
		entry.(*widget.Entry).OnSubmitted = func(a string) {
			entry.(*widget.Entry).SetText(strconv.Itoa(i))
		}
	}
	
	c := container.NewVBox(entries...)
	
	w.SetContent(c)
	
	w.ShowAndRun()
}
```

### Fyne version

2.2.4

### Go compiler version

1.19.3

### Operating system

Linux

### Operating system version

Ubuntu 22.04

**Comment by Jacalz** [comment]
This is not a bug in Fyne. Run `go vet` on the code and it should likely report an error warning you that you are capturing a loop variable that will change each iteration of the loop. You need to capture the variable outside of the anonymous function so that all anonymous functions don't read from the loop variable. I would suggest saving the string inside the for loop for each iteration but you can also just capture the index into another variable.

**Comment by andydotxyz** [comment]
The cause of the problem is correct - but the variable you need to capture is the `Entry`.
The correct callback is firing - but it has the wrong pointer so it is calling `SetText` on the wrong `Entry`

**Comment by Jacalz** [comment]
Yeah, good point. I missed that one. Either way, you might want to save the string as it is unnecessary to create a new one each time the entry is submitted.

**Comment by brokenarmor451** [comment]
I am sorry opening an issue for this, i opened issue because i thought that this is a bug but i was wrong. And i i strived for hours to fix this. 

this is fixed my issue, thanks for help

```
package main

import (
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	
	w := a.NewWindow("Some Practice")
	
	w.Resize(fyne.NewSize(400, 400))
	
	entries2 := []fyne.CanvasObject{widget.NewEntry(), widget.NewEntry(), widget.NewEntry(), widget.NewEntry(), widget.NewEntry()}
	
	for i, entry := range entries2 {
	tempI := i
		entry.(*widget.Entry).OnSubmitted = func(a string) {
			entries2[tempI].(*widget.Entry).SetText(strconv.Itoa(tempI))
		}
		
		
	}
	
	c := container.NewVBox(entries2...)
	
	w.SetContent(c)
	
	w.ShowAndRun()
}
```
