### ISSUE TITLE
RequestFocus

### ISSUE THREAD

**Issue by junlicn** [fyne-io/fyne#3451]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I open two windows, but the second one does not stay focus top on parent windows like  file/folder open dialog.
I use this for progressbar to stay on the parent windows, but the latest version had Deprecated the dialog.progressbar instead a widget, but the widget need a stay foucsed window.

### How to reproduce

run code below

go run demo.go

### Screenshots

![image](https://user-images.githubusercontent.com/14213863/205442273-102b0eb4-6346-46c3-906a-faa6652d7777.png)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")
	w.SetContent(widget.NewLabel("Hello World!"))
	w.Show()

	w2 := a.NewWindow("Larger")
	c2 := container.NewVBox(widget.NewLabel("More content"), widget.NewEntry())
	w2.SetContent(c2)
	w2.Resize(fyne.NewSize(100, 100))
	w2.Show()
	a.Run()
	w2.RequestFocus()
}


```

### Fyne version

2.2.4

### Go compiler version

1.18.1

### Operating system

Windows

### Operating system version

windows 10

**Comment by andydotxyz** [comment]
If you want content to stay on top and block user interaction you should use the `dialog` package instead of creating a new window.
