### ISSUE TITLE
package macOS app with appID unidentified

### ISSUE THREAD

**Issue by eliranwong** [fyne-io/fyne#3452]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I started developed a fyne app at https://github.com/eliranwong/gobible

I created app id in my Apple developer account.  I added certificates.

I packaged the app with the following command

> fyne package -os darwin -appID app.myid -icon gobible.png

however, when my app users download the executable file to their computer, the following warning prevent my users from opening the app:

cannot be identified because it is from an unidentified developer

### How to reproduce

Below is the instructions I gave to my app users

1) download https://github.com/eliranwong/gobible/archive/refs/heads/main.zip

2) double-click the downloaded zip file to unzip it

3) double-click "GoBible.app" in the unzipped folder

when they open it, the warning comes up ... preventing its opening

### Example code

 fyne package -os darwin -appID app.myid -icon gobible.png

### Fyne version

2.2.4

### Go compiler version

1.19.3

### Operating system

macOS

### Operating system version

Ventura 13.0.1

**Comment by andydotxyz** [comment]
Apple is clamping down on "unsigned executables" - to avoid the warning you have to sign the app.

Otherwise you'll have to add to your instructions how users can go to System Preferences -> Security to allow the app to run.

**Comment by eliranwong** [comment]
okay, I now signed it with altool and it works now.  Thank you.

**Comment by hotafrika** [comment]
@eliranwong How do you sign the code with altool?
