### ISSUE TITLE
linked words within a text to trigger script other than url

### ISSUE THREAD

**Issue by eliranwong** [fyne-io/fyne#3454]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I found current text feature in fyne is very limited in terms of interacting with other widgets.

First, fyne has no webview.  In flutter webview, for example, I can use hyperlink to trigger other scripts via a channel.

Second, though widget.Hyperlink offers OnTapped feature, I don't find the same in widget.HyperlinkSegment

I hope I can use hyperlink within a text and that link can trigger go functions rather than online url.

### Is it possible to construct a solution with the existing API?

widget.NewRichTextFromMarkdown(`words **bold words** words words words [Link than can run script](fyne://my_go_func) words words words words *Italic* words`)

### Describe the solution you'd like to see.

widget.NewRichTextFromMarkdown(`words **bold words** words words words [Link than can run script](fyne://my_go_func) words words words words *Italic* words`)

I would like to see when users click the hyperlink, a go function can be triggered to interact with other fyne widgets or elements.

**Comment by andydotxyz** [comment]
This has already been implemented, but after our code freeze so it will not make it into v2.3.0. See PR https://github.com/fyne-io/fyne/pull/3392.

Closing as duplicate
