### ISSUE TITLE
selectable text

### ISSUE THREAD

**Issue by eliranwong** [fyne-io/fyne#3455]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

current text widgets, other than text entries, do not allow text selection.  that's a big problem for an app which has a lot of text materials to be displayed.  Users need to select part of the text to be copied, share, etc.

### Is it possible to construct a solution with the existing API?

widget.NewLabel("select text here")

### Describe the solution you'd like to see.

widget.NewLabel("select text here")

I hope I can select text display with text labels or other widgets displaying text

**Comment by andydotxyz** [comment]
It would be quite an anti-pattern for all text to be selectable.
Mostly this is an expectation when people come from a web background, but is not common in GUI frameworks.

Perhaps you can describe the use-case where a specific item should be selectable?
Often a disabled entry is sufficient as that shows the user that interaction is supported (UI hints show this is an "input" element).

**Comment by eliranwong** [comment]
Thanks for reply.

I am doing a desktop GUI app, not a web app.

I tried disabled input, but it is not an option, as all text is dim, too hard for reading.

Please allow me to explain more about why I need selectable text in desktop applications, not a web one.

I have a qt-based desktop GUI app, written in python, at https://github.com/eliranwong/UniqueBible

I am transferring everything in go.  Fyne is an appealing choice at first, which I started to use and place at https://github.com/eliranwong/gobible 

My project has a lot of reading materials and references which are in text format, for examples, bibles, reference books, dictionaries, encyclopedia, etc.  also, I need to set up a lot of hyperlinks to link up different kinds of materials, for example, select a word and look up in a dictionary, or search in a reference book.

Very often users select "part" of the text for further lookup, copy or share via message or email.  With qt, I can select a word or a few words, right click and open a context menu to work further ... I can also set hyperlinks of a word or some words within a passages ... to interact with other scripts or materials.

However, in Fyne, I encountered three main issues, which stop me from moving forward:

1) text in non-input widget is not selectable

2) text holding in label widget within table cells cannot be wrapped properly

3) cannot set hyperlinks for a particular word or some words within a passage to trigger other go functions rather than internet url

I really appreciate your work Fyne is very quick to start things, but very limited in terms of widget features, especially when it comes to text.  I hope I can use fyne to finish the project, though I am thinking to use other frameworks if there is no new breakthroughs.

**Comment by eliranwong** [comment]
> Why not just an extended Entry widget that "discards" all TypedRune events?
> Also, at your place I would use a List widget to display all the text elements (versets).

I also tried the List widget.  Honestly the list widget in fyne is very simple too.  I have a flutter project two years ago https://github.com/eliranwong/DartBible-Flutter The List Widget in flutter can contain selectable text widget, with good wrapping, allowing me to set hyperlinks on particular words within text inside the text widget.  I found that I can do none of them in fyne.  I hope go has a capable gui framework for desktop and mobile softwares.

**Comment by eliranwong** [comment]
> > The List Widget in flutter can contain selectable text widget, with good wrapping
> 
> There is no limit to the type of widgets you can put into a list (with the exception I suppose that you should avoid something scrolling inside something that scrolls). In v2.3.0 we add API that allows varying height rows which should mean your wrapping can be better accommodated as well.
> 
> > I hope go has a capable gui framework for desktop and mobile softwares.
> 
> Thankfully it has a variety of them. We are working away on the most popular one here - but others are of course available.

Thank you very much for your good work.  I am looking forward to the upcoming updates.

**Comment by eliranwong** [comment]
would you also consider to make text appears to be normal when entry is disabled.  Text in current entry widget is too dim to be read when the widget is disabled.

**Comment by andydotxyz** [comment]
> 3\. cannot set hyperlinks for a particular word or some words within a passage to trigger other go functions rather than internet url

Sorry I missed this before - what you ask for absolutely can be done... Use `RichText` instead of `Label`.

**Comment by andydotxyz** [comment]
> would you also consider to make text appears to be normal when entry is disabled. Text in current entry widget is too dim to be read when the widget is disabled.

Normal no, brighter maybe. We want to make it clear the difference. The new theme in 2.3 will be a good place to see how things are for future releases.

**Comment by eliranwong** [comment]
> > 3. cannot set hyperlinks for a particular word or some words within a passage to trigger other go functions rather than internet url
> 
> Sorry I missed this before - what you ask for absolutely can be done... Use `RichText` instead of `Label`.

with regards to hyperlinks, I mean hyperlinks to trigger a go function instead of an online url

**Comment by andydotxyz** [comment]
> > > 3. cannot set hyperlinks for a particular word or some words within a passage to trigger other go functions rather than internet url
> > 
> > 
> > Sorry I missed this before - what you ask for absolutely can be done... Use `RichText` instead of `Label`.
> 
> with regards to hyperlinks, I mean hyperlinks to trigger a go function instead of an online url

You probably mean this then? https://github.com/fyne-io/fyne/pull/3392

**Comment by eliranwong** [comment]
> > > > 5\. cannot set hyperlinks for a particular word or some words within a passage to trigger other go functions rather than internet url
> > > 
> > > 
> > > Sorry I missed this before - what you ask for absolutely can be done... Use `RichText` instead of `Label`.
> > 
> > 
> > with regards to hyperlinks, I mean hyperlinks to trigger a go function instead of an online url
> 
> You probably mean this then? #3392

wonderful, much appreciate your work

**Comment by eliranwong** [comment]
> > would you also consider to make text appears to be normal when entry is disabled. Text in current entry widget is too dim to be read when the widget is disabled.
> 
> Normal no, brighter maybe. We want to make it clear the difference. The new theme in 2.3 will be a good place to see how things are for future releases.

If no for entry widget, would you consider add a selectable text widget?

**Comment by eliranwong** [comment]
Do you think text-selection is an uncommon action?  anyway ...

**Comment by eliranwong** [comment]
Interesting!  I now understand why fyne is so limited in potential.

Anyway, fyne is a good package for very very basic use.

Thank you once again for your good work.

**Comment by matwachich** [comment]
Sorry to say but youbare totally wrong, widgets extenfing and custom
renderers permits you to make nearly anything you want. I'm currently
developping a complex (closed source) app and the only thing that is
lackint for me now is tooltips. But even this, you can make it with (but I
found it a little bit complicated for now...)

Le mer. 14 déc. 2022 à 10:58, Eliran Wong ***@***.***> a
écrit :

**Comment by andydotxyz** [comment]
> Do you think text-selection is an uncommon action?  anyway ...

I feel like you read something into my message that was not there. When asking how we would make this clear to users I was not saying we should not do it - I was asking how we would.
When asking for a use-case I was not dismissing but asking the question...

Selectable text should not be the default but at no point did I dismiss it. The issue seems to have been closed instead of continuing the conversation. Rather than criticising our project please consider helping with what I was asking and maybe the functionality can be added?

**Comment by andydotxyz** [comment]
It looks like a disabled Entry widget to me... won't that work for you?

To put colours or highlights into that widget would need a rich text editor which isn't going to be completed soon.

**Comment by JaviLib** [comment]
> It looks like a disabled Entry widget to me... won't that work for you?
> 
> To put colours or highlights into that widget would need a rich text editor which isn't going to be completed soon.

Thanks, what I'm thinking is just adding a "copy" button and then open a pop up window to edit the content. Because I'm going to add a filter which can reduce the amount of data copied, this is probably better than a disabled entry.
With Rich text at least I have the option to bold errors and warnings, with disabled entry I don't think I have any option to highlight errors and warnings.
I think RichText edit and colors is a must for Fyne, without it you limit a lot what you can do with text. Any ETA?

**Comment by andydotxyz** [comment]
> I think RichText edit and colors is a must for Fyne, without it you limit a lot what you can do with text. Any ETA?

We don't have ETA for anything except the next release, which is v2.5.0 due shortly (see https://github.com/fyne-io/fyne/wiki/Releases)

If you want to influence when things are available we welcome feature sponsorship - https://github.com/sponsors/fyne-io/
