### ISSUE TITLE
cmd/fyne package can't find FyneApp.toml when -src option has given

### ISSUE THREAD

**Issue by hismailbulut** [fyne-io/fyne#3459]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am trying to build project with fyne cmd but I get an error:
`Missing application icon at "cmd\myapp\Icon.png"`

My project structure is like this:
```
root
--cmd
----myapp
------assets
--------icon.png
------main.go
--pkg
--FyneApp.toml
--Makefile
```

FyneApp.toml
```
Website = "https://www.example.com"

[Details]
  Icon = "cmd/myapp/assets/icon.png"
  Name = "myapp"
  ID = "com.myapp.app"
  Version = "0.1.0"
  Build = 50
```

I am running this command in the root but it doesn't work and gives the error:
`fyne package -release -os windows -src cmd/myapp`

I tried moving icon to cmd/myapp/Icon.png but it also doesn't work

Moving FyneApp.toml to cmd/myapp and running command `fyne package -release -os windows` in cmd/myapp works so I think the problem happens only with -src option

What I want is fyne should look FyneApp.toml in cwd and load it from there so I can put FyneApp.toml to root and run fyne package in root

### How to reproduce

1. Create a project with same structure like above
2. Run `fyne package -release -os windows -src cmd/myapp` in root

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

11

**Comment by andydotxyz** [comment]
I'm not too sure about this and would appreciate others feedback on this.
Currently our tooling assumes that `FyneApp.toml` is in the same location as the application files (i.e. "srcDir").
This includes things like the apps installer and "fyne get" command.
If this is to be changed it would need to still support this standard way.

What do others think about the request?

**Comment by hismailbulut** [comment]
After spending some time with cmd/fyne I agree with you that FyneApp.toml should be in the srcdir. Thats because multiple main fyne applications can be in same project. But the issue still needs to be fixed.

**Comment by andydotxyz** [comment]
Thanks. Nice summary. Yes we still need to resolve the issue :)
