### ISSUE TITLE
fyne_demo icons - drop down / search input

### ISSUE THREAD

**Issue by mainiak** [fyne-io/fyne#346]
Hi, could you please add drop down and/or search box next to "previous" and "next" icons?
Or please create some list like this - https://semantic-ui.com/elements/icon.html

**Comment by mainiak** [comment]
![image](https://user-images.githubusercontent.com/691076/60234282-6032d980-9858-11e9-9990-d7395dbcbfc2.png)

**Comment by andydotxyz** [comment]
A great idea. I will update it with our new Select widget.

**Comment by andydotxyz** [comment]
This is on develop for testing.
It will probably require additional work on the widget to introduce scrolling to make it completely useful.

**Comment by mainiak** [comment]
Thanks @andydotxyz, it works. Yes scrolling would be great 🤣
