### ISSUE TITLE
Entry text "flickering" while typing

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3461]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When tapping on an Entry widget, text is slightly flickering.

I have the feeling that it is related to float rounding...

### How to reproduce

Type on any Entry widget

### Screenshots

![kissemr_nLoKLSIAtC](https://user-images.githubusercontent.com/1791230/206261273-1474a8aa-ce6d-42bc-9094-4b97532b83c3.gif)

### Example code

Any simple code with an Entry widget

### Fyne version

2.3.0-rc1 and 2.2.3

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

10

**Comment by andydotxyz** [comment]
I wanted to call this a blocker, but if it was the same in 2.2.3 that puts it down a peg.
Still it's pretty bad and we should fix it!

**Comment by andydotxyz** [comment]
As I was working on font render issues I think this has been addressed as well. Should be in for rc2

**Comment by matwachich** [comment]
I confirm that the bug is....... different!
Less present ideed, but it's different
Look

https://user-images.githubusercontent.com/1791230/208653777-f8b08c97-c941-4c9b-9e64-08b7d30958a6.mp4

**Comment by andydotxyz** [comment]
Thanks for the update. I think what you report is an old issue appearing again whereby a text refreshes to screen with the new size but the old texture (so it appears stretched). I will try and dig up the other issue and relate it to this one

**Comment by matwachich** [comment]
Just a little bump hoping this issue hasn't been forgotten...
The flicker makes app a little unprofessional imho :)

**Comment by Jacalz** [comment]
The issue has been closed as completed. What do you mean with forgotten?

**Comment by andydotxyz** [comment]
If it is still an issue on develop it should be re-opened. I guess I couldn't find the original issue...

**Comment by princessmortix** [comment]
Tested on develop and still an issue, not on entry thoght.
For me it happens with newrichtextfrommarkdown:

![image](https://github.com/fyne-io/fyne/assets/47502554/3f04ca63-caaa-4630-9c49-05653a65e3ac)

I think i'll open a new issue soon.

**Comment by andydotxyz** [comment]
I think that may be a different issue to this original report.
The prior was due to horizontal spacing but yours shoes, I think, a breakdown in the pixel alignment during paint.

**Comment by abentas** [comment]
This issue is still present in 2.4.5, looks like the color of the text and the length of the whole entry is changing slightly.

**Comment by andydotxyz** [comment]
Sounds like it could be a regression, as this was resolved some time ago.
If you can open a new issue with current information that would be helpful.
