### ISSUE TITLE
New 2.3.0 theme suggestions

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3462]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

There are some little things that I think should be improved in the new theme:

Check mark should be white
![image](https://user-images.githubusercontent.com/1791230/206261762-59f8d3b0-9205-4469-9f2c-c09ea4bbcc5f.png)

Menu items and buttons should have a little more right-padding to by symmetrical
![image](https://user-images.githubusercontent.com/1791230/206261862-631ffc23-4800-4911-8614-c7ba0dd1eca8.png)
![image](https://user-images.githubusercontent.com/1791230/206261891-550d486f-5db2-487f-a52c-b45f356bd6ac.png)

### Describe the solution you'd like to see.

![image](https://user-images.githubusercontent.com/1791230/206262113-9249f4a7-cfa6-4172-b0fb-909ca38e30be.png)

**Comment by andydotxyz** [comment]
After discussion we agreed the button padding is correct. Let's update:

- [ ] Contrast on checked box
- [ ] Padding on right of menu items

**Comment by andydotxyz** [comment]
Fixes for the issue listed all on the PR linked, we will add another rc once this is in

**Comment by matwachich** [comment]
Another one
![image](https://user-images.githubusercontent.com/1791230/207119124-198143dd-6c70-4c0e-902f-ce3d3727c037.png)

**Comment by Jacalz** [comment]
I wonder, should we perhaps improve how the focused high importance button looks?
![image](https://user-images.githubusercontent.com/25466657/207136826-cc5e0613-f960-4f24-a95a-acf9c38531f1.png)

**Comment by andydotxyz** [comment]
That's all the items we discussed landed on latest release
