### ISSUE TITLE
Off center items in new theme

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#3469]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

- Animation on button with `+` in fyne_demo/data bindng/item* seems off center (to much on the left)
- Same problem is also visible in fyne_demo/widgets/input/select drop down button
- Check box circle seems also off center (to much up)
- Same problem is also visible in fyne_demo/widgets/input/Check*

### How to reproduce

Seems to be irrelevant of scales and visible on all button with icon and all checkbox anywhere.

### Example code

fyne_demo is enough to reproduce the problem.

### Fyne version

develop ahead of 2.3.0-rc1 (c0cde7ab1c251bba361c130eec24b68fe89e7d34)

### Go compiler version

1.19.4

### Operating system

Linux

### Operating system version

Arch Linux

**Comment by andydotxyz** [comment]
I can't see a check circle being off - which one do you mean and/or how would I best see if it is centered or not?

**Comment by andydotxyz** [comment]
Thanks, fixed and as discussed on Slack all covered :)
