### ISSUE TITLE
Memory spikes and lag when resizing window

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3471]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When using v2.3.0 on development, I am seeing very laggy and slow window resize. It is almost as if whole sizes of the widow are skipped. I am sometimes seeing large spikes in memory usage increases right at the same time as the window resize slows down.

A similar issue occurs when running under Wayland but there is less skipping of frames and more just general slowness.

### How to reproduce

1. Open up fyne_demo.
2. Resize the window up and down. Very large changes in size seems to how the most effect.
3. Notice that the window sometimes lags and stutters when trying to resize.

### Screenshots

[laggy-resize-x.webm](https://user-images.githubusercontent.com/25466657/207436227-fa4c6e13-d4e6-41fd-b25a-5d0581547933.webm)

### Example code

It is eneough to use fyne_demo for this

### Fyne version

c0cde7ab1c251bba361c130eec24b68fe89e7d34

### Go compiler version

1.19.3

### Operating system

Linux

### Operating system version

Fedora 37

**Comment by Jacalz** [comment]
Some interesting notes. Using v2.2.4, it kind of lags a bit sometimes but generally feels a lot better than it does now. Building using `-tags wayland` did initially show slight issues but having trouble replicating there now

**Comment by andydotxyz** [comment]
Should be addressed by #3481

**Comment by Jacalz** [comment]
Were there further optimizations to do in the future? If so, should we leave this open after merging that PR?

**Comment by andydotxyz** [comment]
> Were there further optimizations to do in the future? If so, should we leave this open after merging that PR?

There are always more optimisations to be done. If my PR resolves the title "Memory spikes and lag when resizing window" then I think we should close this ticket accordingly.

**Comment by Jacalz** [comment]
Sure. I'll make sure to review the PR this evening. If we close this then, we should probably make sure to open a new issue to track further improvements :)

**Comment by andydotxyz** [comment]
The PR was merged a while back, is there more required work in this space for the next release?

**Comment by Jacalz** [comment]
Looks great on master and develop. Closing as done :)
