### ISSUE TITLE
Calling List.SetItemHeight inside UpdateItem blocks

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3473]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

As the title says

### How to reproduce

Run the code, it gets stuck on the w.SerContent call.
Comment out the call to SetItemHeight in UpdateItem and it runs just fine.

### Example code

```go
package main

import (
    "math/rand"
    "strings"

    "fyne.io/fyne/v2"
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"
)

func main() {
    a := app.New()
    w := a.NewWindow("Test")

    str := "a line of data\n"
    var data []string
    for i := 1; i <= 1000; i++ {
        data = append(data, strings.TrimSpace(strings.Repeat(str, rand.Intn(7)+1)))
    }

    var lst *widget.List
    lst = widget.NewList(
        func() int {
            return len(data)
        },
        func() fyne.CanvasObject {
            return widget.NewLabel("")
        },
        func(id widget.ListItemID, co fyne.CanvasObject) {
            co.(*widget.Label).SetText(data[id])
            lst.SetItemHeight(id, co.(*widget.Label).MinSize().Height)
        },
    )

    w.SetContent(lst) // code execution stops here
    w.Resize(fyne.NewSize(600, 400))
    w.CenterOnScreen()
    w.ShowAndRun()
}
```

### Fyne version

2.3.0-rc1

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

10

**Comment by andydotxyz** [comment]
Resolved on develop before we cut release
