### ISSUE TITLE
Grid and GridWrap layouts with large number of images has high CPU use

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3475]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If filling a Grid or GridWrap layout with a large (few hundred) amount of images, and anything else on the screen other than the grid is periodically redrawing itself, CPU use is consistently high even if the window is not being interacted with. This is true regardless of whether the grid/wrap is placed within a scroll container or just drawn to the window directly.

I would expect that CPU load should indeed increase with large amounts of images in these containers, but only when the application window or the grid element is being interacted with (scrolling, resizing, moving, etc.) It would also be acceptable for the memory use to increase though it seems memory consumption is not very affected.

### How to reproduce

Run the toy app provided, which loads 200 random images and displays them in a gridwrap in a scroll container, along with a small status bar label on the bottom of the window which is a simple incrementing counter.

Wait until the window title says "done loading 200 images", then let the app continue to run in a steady state. Note that the CPU use is high even when the window or the scroll container are not being manipulated.

### Example code

```go
package main

import (
	"fmt"
	"log"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/storage"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	window := app.NewWindow("loading images...")

	l := widget.NewLabel("hello world")
	g := container.NewGridWrap(fyne.NewSize(200, 200))
	s := container.NewVScroll(g)
	content := container.NewBorder(nil, l, nil, nil, s)
	window.SetContent(content)

	go func() {
		counter := 0
		for {
			time.Sleep(100 * time.Millisecond)
			l.SetText(fmt.Sprintf("counter %d", counter))
			l.Refresh()
			counter++
		}
	}()

	go func() {
		count := 0
		for count < 200 {
			uri, _ := storage.ParseURI("https://picsum.photos/200")
			im := canvas.NewImageFromURI(uri)
			g.Objects = append(g.Objects, im)
			count++
			g.Refresh()
			window.SetTitle(fmt.Sprintf("loading images (%d of 200)...", count))
		}
		log.Println("done loading 200 images")
		window.SetTitle("done loading 200 images")
	}()
	window.ShowAndRun()
}
```

### Fyne version

2.2.4

### Go compiler version

1.19.4 linux/amd64

### Operating system

Ubuntu

### Operating system version
22.04.1 LTS

**Comment by andydotxyz** [comment]
What happens if you remove the text that updates 10% per second from the top?

**Comment by dweymouth** [comment]
CPU use settles down if nothing on the screen is being redrawn (i.e. if you remove the goroutine that updates the label). I haven't looked into the internal architecture but I'm guessing that Fyne is redrawing or re-laying out the entire screen when any component needs to redraw? If so there could be some optimizations to be implemented down the road to track and then rerender only the components within the window that need updating.

Also the scroll container could have optimizations to only re-render what is visible, but this seems like potentially an even more difficult task (again I haven't dug into the internals).

**Comment by andydotxyz** [comment]
> I haven't looked into the internal architecture but I'm guessing that Fyne is redrawing or re-laying out the entire screen when any component needs to redraw? If so there could be some optimizations to be implemented down the road to track and then rerender only the components within the window that need updating.

You're guessing wrong here. We do all we can to avoid redrawing or re-calculating layout.
The refreshing of the layout will trigger a screen refresh (there is no partial-redraw) but everything apart from your label will be drawn from texture cache.

The scroll container does not do anything to draw what is visible - more complex collection widgets such as List, Tree and Table do exactly this - it is only possible because they know the content - scroll does not know anything about what it contains.

**Comment by dweymouth** [comment]
> The scroll container does not do anything to draw what is visible - more complex collection widgets such as List, Tree and Table do exactly this

In this case it could be nice in the future to have a widget that is kind of a combo of List and GridWrap - i.e. lay the child objects out like gridwrap inside a scrollable pane, but with the optimizations of List/Tree/Table to only draw what's visible.

For context, for the project I've just started working on - a client for self-hosted music servers - I was going to have an infinitely scrollable list of album covers using GridWrap + ScrollContainer, but I think I'll switch to a paginated view for now, or I may dig into the List widget to see how complex it would be to modify it for a grid layout.

**Comment by dweymouth** [comment]
Just want to update to say that it was surprisingly easy to implement a GridWrapList. I had to do it in my own fork of Fyne though to access the internal scroller. Probably 95% of the code was directly lifted from List and GridWrapLayout. Still have a small bug to work out (the last partially filled row is not drawing) but performance-wise it's great. I ran the image loading toy app loading 500 images into the GridWrapList and resizing/scrolling is smooth and performant. CPU goes up a bit as expected when resizing, scrolling, or even mousing over the grid, but drops right back down to steady state afteward.

Side note: I need to expose an API to know when the list is scrolled near the bottom so I can fetch more data. I hope to keep it as consistent with the rest of the Fyne API as possible (so maybe the GridWrapList can be merged in sometime down the line :) So @andydotxyz if you feel like weighing in, do you have a suggestion? (no pressure!)

**Comment by Jacalz** [comment]
Well done. Someone worked one a few years ago but it did never really materialise. Feel free to open a PR, we’ll happily review it :)

**Comment by andydotxyz** [comment]
> Side note: I need to expose an API to know when the list is scrolled near the bottom so I can fetch more data. I hope to keep it as consistent with the rest of the Fyne API as possible (so maybe the GridWrapList can be merged in sometime down the line :) So @andydotxyz if you feel like weighing in, do you have a suggestion? (no pressure!)

I'm not sure this extra API would be needed. If it is then maybe keep it separate as we would apply it to List/Tree/Table at the same time.
The reason I think it may not be needed is you get the `Update` callback with `ListItemID` (or whatevery the `GridWrap` equivalent would be) as the user scrolls, so your code will know when it is approaching the length of your data...

**Comment by dweymouth** [comment]
I am going to close this as not planned since I have no problems with CPU use with my custom GridWrapList that uses the widget cache-and-reuse mechanism of List and Table. I still see background CPU use being a bit high in my app, likely related to #2506.

**Comment by Jacalz** [comment]
Do you have any plans to upstream that GridWrapList? It would be a great inclusion for fyne-x.

**Comment by dweymouth** [comment]
> Do you have any plans to upstream that GridWrapList? It would be a great inclusion for fyne-x (and likely here in fyne as well).

Yes, I would like to contribute it to Fyne eventually. It uses the internal scroller so unfortunately it cannot be merged into fyne-x. I still have some tweaks I'd like to get around to making (mainly to try to adjust the scroll position if necessary when it reflows to keep as many of the previously visible items still visible). Also I haven't written tests for it and haven't even manually tested the APIs that I don't use in my app, like ScrollToItem. But it's here if you felt like taking a look! https://github.com/dweymouth/fyne/blob/add-gridwraplist/widget/gridwraplist.go

**Comment by Jacalz** [comment]
Cool. That sounds great. Don't hesitate to ask if there is anything that we can do help or ease the transition. You're more than welcome to join the slack channel (if not already there) for discussions and collaborations :)

**Comment by andydotxyz** [comment]
> It uses the internal scroller so unfortunately it cannot be merged into fyne-x.

The Scroller also has a public API, it should be possible to do what you describe without requiring internal APIs.

**Comment by dweymouth** [comment]
> > It uses the internal scroller so unfortunately it cannot be merged into fyne-x.
> 
> The Scroller also has a public API, it should be possible to do what you describe without requiring internal APIs.

Is there a public API to make something scrollable with a scroll bar? There is the public Scrollable API but I don't think there's a public API to get the scroll bar rendered with your own widget?

**Comment by andydotxyz** [comment]
Yes, place your content within `container.NewScroller`

**Comment by dweymouth** [comment]
I can look into that, but I was under the impression that the `ScrollContainer` was for widgets that render the entire area, and the scrollcontainer clips it to a visible window.

**Comment by andydotxyz** [comment]
I don't understand sorry. What sort of scroll behaviour do you want that does not clip the item to the scrolling region?

**Comment by dweymouth** [comment]
I may just not be understanding the full use cases of ScrollContainer. I used the internal scroller because I was basically copying `widget.List` but adding the layout logic from `container.GridWrap`. If it makes sense, the scroll bar for `widget.List` and my GridWrapList suggests a larger area than actually "exists" due to the cache-and-reuse mechanism. I wasn't sure if ScrollContainer could do the same thing. Implementing GridWrapList was also pretty much my first exposure to Fyne since it was a prerequisite for being able to build my app at all. So it's definitely possible it could have been done in a better way with public APIs.

**Comment by andydotxyz** [comment]
I still don't understand sorry. The internal `Scroll` container and `container.Scroll` are identical (literally, one is an alias of the other). It exists only to avoid import loops in our widget code.

**Comment by dweymouth** [comment]
Yep, I didn't realize that! I will move my GridWrapList to fyne-x then!
