### ISSUE TITLE
List with different item heights selection bug (blocker?)

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3477]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Selecting an item in a list with many (scroll active) items with differents heights makes the list scroll out of selected item view.

Must have something to do with item offset calculation (bet that the calculation is always assuming equal heights items).

### How to reproduce

A list with many different heights items, scroll somewhere to the middle of the list and select some item.

### Example code

```go
package main

import (
	"math/rand"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	var data []string

	var lst *widget.List
	lst = widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(id widget.ListItemID, co fyne.CanvasObject) {
			co.(*widget.Label).SetText(data[id])
		},
	)

	str := "a ligne of data\n"
	lbl := widget.NewLabel("")
	for i := 1; i <= 1000; i++ {
		data = append(data, strings.TrimSpace(strings.Repeat(str, rand.Intn(7)+1)))
		lbl.SetText(data[i-1])
		//lst.SetItemHeight(i-1, lbl.MinSize().Height)
	}

	w.SetContent(container.NewBorder(widget.NewLabel("Test"), nil, nil, nil, lst))
	w.Resize(fyne.NewSize(600, 400))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.3.0-rc1

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

10

**Comment by andydotxyz** [comment]
Fixed on develop
