### ISSUE TITLE
widget.Table does not have an "OnScrolled" method. 

### ISSUE THREAD

**Issue by AristeH** [fyne-io/fyne#3485]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

widget.Table does not have an "OnScrolled" method. 

### Describe the solution you'd like to see.

widget.Table does not have an "OnScrolled" method.

**Comment by Jacalz** [comment]
What is the use case for wanting to have this included? You have only provided the sentence "widget.Table does not have an "OnScrolled" method." without further explanation.

**Comment by AristeH** [comment]
I have 2 tables. When scrolling the first table, I want automatic scrolling of the second table.

**Comment by andydotxyz** [comment]
You'll find that the request is not sufficient - as there is no "ScrollTableToPosition" on the other side.
Can you expand on what the use-case is, rather than why you want this code to be added?

**Comment by Jacalz** [comment]
Sena like a duplicate of https://github.com/fyne-io/fyne/issues/3442 if I understand correctly?

**Comment by andydotxyz** [comment]
Maybe, it could depend on the use-case. That issue seems to be really asking for a table sticky-header solution

**Comment by AristeH** [comment]
Yes I want the table to have a header and a footer

**Comment by andydotxyz** [comment]
Thanks, closing as duplicate
