### ISSUE TITLE
Enhance scroll wheel/touchpad scroll on desktop

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3492]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The scrolling using mouse wheel (or laptop touchpad) is too slow, comparing to other applications with the same mouse (obviously).

### Describe the solution you'd like to see.

Increase scrolling speed/pages per scroll or any other solution you see is good.

**Comment by matwachich** [comment]
https://www.codeproject.com/articles/1042516/custom-controls-in-win-api-scrolling

I don't know how it works on other plateforms, but this could bring usefull informations

**Comment by Jacalz** [comment]
I don't know to what extent we follow operating system values for touchpad/mouse scroll speed. I guess we want to match that as much as possible.

**Comment by dweymouth** [comment]
I'd like to raise attention to this issue. Scrolling with the mouse wheel is very annoyingly slow on some systems (Ubuntu and Windows, MacOS doesn't actually seem that bad but still a little slow).

**Comment by dweymouth** [comment]
I've [tweaked](https://github.com/fyne-io/fyne/commit/ca8ffa6896d61a11feed2169d70b78f7f1378306) scrolling speed in an OS-specific way for my project, leaving the scroll speed values as-is for Mac OS and increasing them for Windows and Linux, which gives much better behavior in my testing. I'm sure they could be improved even a bit more.

(I have not tested on BSD and my app doesn't target BSD, but I'd be inclined to think that BSD should also use the windows and linux scroll values, and it's Mac OS that's the odd one out due to its builtin momentum scrolling)

**Comment by andydotxyz** [comment]
That looks like a nice improvement until we get actual OS level config matching for speed. Would you consider opening a PR so we can test and discuss?

**Comment by dweymouth** [comment]
Opened #3757

**Comment by andydotxyz** [comment]
Ready on develop for next release, thanks @dweymouth

**Comment by lordofscripts** [comment]
Is there an example of extending ANY widget so that it can capture the mouse scroll wheel DX/DY to use those values accordingly to the purpose of the widget (i.e. not necessarily for scrolling the widget. It could be to adjust brightness of the image or whatever.

**Comment by andydotxyz** [comment]
Please don't comment on closed issues to ask a question.

However, you can use the information for whatever purpose you want if your widget implements fyne.Scrollable.
To find usages of this search a code repository like GitHub or ask your IDE.
