### ISSUE TITLE
Mac OS: Scrolling widgets (List, ScrollContainer, etc.) do not scroll if window not focused

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3495]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

A Fyne window containing a scrollable widget (List, Table, anything in a ScrollContainer etc) is unable to be scrolled if the window does not have focus. The expected behavior (at least on Mac OS but I think for all the desktop OSes) is for content in unfocused windows to still be scrollable if the mouse cursor is positioned over the scrollable element.

### How to reproduce

1. Launch a simple Fyne app with a scrollable element
2. Focus a different window in your desktop environment, but make sure the Fyne app is still visible on screen
3. Mouse over the scrollable element in the Fyne app but do not focus the window
4. Scroll using the scroll wheel
5. The content should scroll even when the window is unfocused, but it does not.

### Example code

fyne demo is sufficient if you shrink the window to its minimum size (to make the list on the left scrollable)

### Fyne version

2.2.4

### Go compiler version

1.19.2 darwin/amd64

### Operating system

macOS

### Operating system version

Monterrey 12.6.1

**Comment by dweymouth** [comment]
Edit: I tested this on Ubuntu and the unfocused window is scrollable. The bug may only be present on Mac OS. Do not have a Windows machine to test on.

**Comment by andydotxyz** [comment]
Confirmed this happens on macOS but not Linux

**Comment by dweymouth** [comment]
I think this may have gotten inadvertently fixed somewhere along the line :) At least for Apple Silicon macs

**Comment by dweymouth** [comment]
I am going to close this as I think it was "accidentally" resolved somehow as it doesn't seem to reproduce anymore on M2 mac at least

**Comment by andydotxyz** [comment]
Nice :) it must have been a GLFW update that fixed this
