### ISSUE TITLE
TextWrapWord will cause crash in RichText

### ISSUE THREAD

**Issue by aynakeya** [fyne-io/fyne#3498]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If a label in a Scroll container have its text starts with a space.  and its Wrapping equals `TextWrapWord`.

eg
```
l :=widget.NewLabel(" AAAA")
l.Wrapping = fyne.TextWrapWord
```

Then program will crash at `RichText.go` with index out of range -1

![image](https://user-images.githubusercontent.com/32156054/209456184-86811807-90cb-4c92-8805-b5bb7f2c74a0.png)

### How to reproduce

Run code in Example code will cause program to crash

### Screenshots

![image](https://user-images.githubusercontent.com/32156054/209456140-cb32de6d-4a23-4323-b662-c4beede930ee.png)

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	texts := make([]fyne.CanvasObject, 32)
	for i := 0; i < len(texts); i++ {
		l := widget.NewLabelWithStyle(
			" AAAA",
			fyne.TextAlignCenter, fyne.TextStyle{})
		l.Wrapping = fyne.TextWrapWord
		texts[i] = l
	}
	vbox := container.NewVBox(texts...)
	scroll := container.NewScroll(vbox)
	w.SetContent(scroll)
	w.Resize(fyne.NewSize(360, 540))
	w.ShowAndRun()
}
```

### Fyne version

v2.2.4

### Go compiler version

1.19

### Operating system

Windows

### Operating system version

Windows 10

**Comment by aynakeya** [comment]
Maybe its the same problem as #3291

**Comment by andydotxyz** [comment]
Please can you test against v2.3.0 which was released yesterday. Lots of text code was upgraded.

**Comment by aynakeya** [comment]
> Please can you test against v2.3.0 which was released yesterday. Lots of text code was upgraded.

Problem still exists in v2.3.0
![image](https://user-images.githubusercontent.com/32156054/209735816-eeaa9ab8-42b7-4f35-af91-6154c4828d24.png)

**Comment by andydotxyz** [comment]
Fixed on develop, thanks @alexballas
