### ISSUE TITLE
widget.ImageSegment can't be aligned.

### ISSUE THREAD

**Issue by alexballas** [fyne-io/fyne#3505]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When using the new widget.ImageSegment functionality, I can't seem to be able to define the alignment for it or control its position. When I resize the window text seems to align fine as per my code example, but image stays on the same position.

### How to reproduce

check description, code examples and screenshot

### Screenshots

![Screenshot from 2022-12-27 01-09-16](https://user-images.githubusercontent.com/11015965/209587785-7aa4ae38-82f3-4e21-ba50-1b41317461a5.png)

### Example code

```go
package main

import (
	fyne "fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

var currentmfolder string

func main() {

	myApp := app.New()
	myWindow := myApp.NewWindow("Test Dialog")
	richhead := widget.NewRichTextFromMarkdown(`
![Go2TV](go2tv-icon-small.png)

Cast your media files to UPnP/DLNA Media Renderers and Smart TVs

---
`)
	for i := range richhead.Segments {
		if seg, ok := richhead.Segments[i].(*widget.TextSegment); ok {
			seg.Style.Alignment = fyne.TextAlignCenter
		}

	}
	myWindow.SetContent(richhead)
	myWindow.ShowAndRun()
}
```

### Fyne version

v2.3.0

### Go compiler version

1.19.4

### Operating system

Linux

### Operating system version

Ubuntu 18.04

**Comment by andydotxyz** [comment]
Resolved (on develop) for v2.4.0 :)
