### ISSUE TITLE
regression since v2.2.3 - window is max size at all times

### ISSUE THREAD

**Issue by kirides** [fyne-io/fyne#3507]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Before (937991b51f4d951474b346075aae110d61ffc016)
![image](https://user-images.githubusercontent.com/13602143/209653652-6f56401b-ae1c-4bab-bb59-8b0e949b0c6a.png)

After (2a54f832544fbfc8c4333023c69247b3871c83d3)
![image](https://user-images.githubusercontent.com/13602143/209653565-13afd55d-5800-47c9-a88e-db2a1ccf5818.png)

### How to reproduce

1. Install fyne, any version >= `fyne.io/fyne/v2 v2.2.2-rc3.0.20220706192957-2a54f832544f`, e.g. `v2.2.3`
2. Use code from example
3. Observe wonky height.
4. Height only can be corrected by switchig to richt-text tab and back to other tabs.
  - at this point resizing starts to work again

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {

	a := app.New()

	w := a.NewWindow("Issue")
	w.Resize(fyne.NewSize(740, 430))

	mainContainer :=
		container.NewAppTabs(
			container.NewTabItem("Something", widget.NewEntry()),
			container.NewTabItem("Attributions", newTabCredits()),
		)

	w.SetContent(mainContainer)
	w.CenterOnScreen()
	w.ShowAndRun()
}

func newTabCredits() fyne.CanvasObject {
	lbl := widget.NewRichTextFromMarkdown(`## cmd\gametts\Icon.png

Creative Commons License (2021)

"Text to speech" By Trevor Dsouza, IN

----
`)
	lbl.Wrapping = fyne.TextWrapWord
	return lbl
}
```

### Fyne version

2.2.3+

### Go compiler version

1.19.4

### Operating system

Windows

### Operating system version

Windows 11 22H2 Build 22621.963

**Comment by andydotxyz** [comment]
Thanks to @alexballas this is fixed on `develop` and we'll pop it in the next point release too.
