### ISSUE TITLE
Widget.NewEntry() could not enter the Unicode character.

### ISSUE THREAD

**Issue by HeyDon-Lee** [fyne-io/fyne#351]
I want to use non-English text in the input box.

**Comment by andydotxyz** [comment]
You may need to load a font that supports the language you are inputting.
This is currently only supported using the FYNE_FONT environment variable.
Look at #297 as I think this is a duplicate.

**Comment by HeyDon-Lee** [comment]
```
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\12526\AppData\Local\Temp\go-link-110965187\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
```

**Comment by HeyDon-Lee** [comment]
Unable to compile successfully after setting.

**Comment by andydotxyz** [comment]
Setting that environment variable does not change how Fyne compiles (you can just specify it at runtime). It looks like your mingw installation is trying to compile for 32 bits on a 64 bit system.

**Comment by HeyDon-Lee** [comment]
How to solve this problem?

**Comment by netsharkgithub** [comment]
//解决fyne gui库中文乱码
func init() {
	os.Setenv("FYNE_FONT", "C:\\windows\\Fonts\\simfang.ttf")
}
不过制表符还是乱码

**Comment by andydotxyz** [comment]
Translation through Google Translate: 
“But the tab characters are still garbled”

**Comment by andydotxyz** [comment]
Yes, there is no support for parsing tab characters at the moment, sorry.
We are working on improved text handling for 1.3 release.
