### ISSUE TITLE
Form.Append() does not support HintText

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#3512]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The widget.FormItem() object now includes the field HintText which displays additional text about the data to be entered in the Widget object. Unfortunately, Form.Append() which adds a FormItem object to a Form does not include a HintText parameter.

### Is it possible to construct a solution with the existing API?

You can create a widget.FormItem() object using the NewFormItem() function. The fields of the FormItem object can then be initialized using assignments. the FormItem object can be added to a widget.Form object using Form.AppendItem()

### Describe the solution you'd like to see.

Add an additional parameter to Form.Append() which includes a string for the HintText field.

**Comment by Jacalz** [comment]
Actually, I think there isn't much to do about this. We already have https://github.com/fyne-io/fyne/blob/8c2509518b2df442a6b748d9b07754739592e6d7/widget/form.go#L72 that can be used to add an entire `*widget.FormItem`.

> Add an additional parameter to Form.Append() which includes a string for the HintText field.

This would be a breaking change. It would also open up the floodgates with people wanting more fields to be added to `Append()` in the future in case we add more features.

**Comment by Jacalz** [comment]
We have decided to close this as it can be done already with the `AppendItem()` method. I understand that it is simpler to just use the append method but it would be a breaking change.
