### ISSUE TITLE
Removing an array entry from widget.Form.Items[] and calling Form.Refresh() causes a panic in Fyne

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#3513]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The Form object does not support a Form.Remove() method which would remove a FormItem object from Form.Items[]. I tried to perform a work around by removing an element from Form.Items[] manually. I then got a panic from the fyne toolkit when I called Form.Refresh().

### How to reproduce

Create a Form with mutiple Form.Items[]. Remove the last item from the form. Call Form.Refresh()

### Example code

Here is some example code:
if len(Form.Items) > 0 {
   Form.Items = Form.Items[:len(Form.Items)-1]
}
Form.Refresh()

### Fyne version

latest

### Go compiler version

go version go1.19.4 windows/amd64

### Operating system

Windows

### Operating system version

Windows 0

**Comment by Jacalz** [comment]
Can you please add a full code example instead of a snippet (also wi  thin a code block)? It would also be great if you could include the stack trace of the crash.

**Comment by andydotxyz** [comment]
This issue is old and we didn't get a response last time of asking, it should have been closed.
Feel free to re-open if repro steps and a stack trace are found.
