### ISSUE TITLE
org.freedesktop.portal.Desktop not exist

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne#3515]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

it is not fatal bug, but I have tried 2.2 vs 2.3 version on termux-proot-arch (except litle bit bigger binary 13M vs 16M) I have found interasting log:    `org.freedesktop.portal.Desktop not exist...`

### How to reproduce

1. run andronix-proot on termux
2. compile current version
3. see log

### Screenshots

![Screenshot_20221229_201438_VNC Viewer](https://user-images.githubusercontent.com/61238240/210003324-3ae7955b-1019-4286-b2cc-aa85920d868e.jpg)

### Example code

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}
```

### Fyne version

2.3

### Go compiler version

1.19

### Operating system

Linux

### Operating system version

arch (android 13 on sm-p619)

### Additional Information

version show neofetch ....

**Comment by andydotxyz** [comment]
Fixed on develop, thanks
