### ISSUE TITLE
Grey theme

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3526]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

After the version is updated, a. Settings(). SetTheme (theme. DarkTheme()) is not as beautiful as the original one, and the original effect is more gray. I hope the author can roll back and add theme. GreyTheme() as the original theme. I think it is very beautiful. I love fyne very much. Pay two contrast pictures of the former and the current DarkTheme

before
![image](https://github.com/hq-zhonger/goland-theme/blob/main/1.PNG)

now
![image](https://github.com/hq-zhonger/goland-theme/blob/main/2.PNG)

It's too dark，Hope to get the support of the author

### Describe the solution you'd like to see.

a.Settings().SetTheme(theme.GreyTheme())

**Comment by alexballas** [comment]
One option could be to create a custom theme and apply the different color yourself. I did something similar both for the Light and Dark theme.

```go
type customTheme struct {
	Theme string
}

func (m customTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	switch m.Theme {
	case "Dark":
		variant = theme.VariantDark
		switch name {
		case theme.ColorNameDisabled:
			return color.NRGBA{R: 0x55, G: 0x55, B: 0x55, A: 0xff}
		case theme.ColorNameBackground:
			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff}
		case theme.ColorNameButton:
			return color.NRGBA{R: 0x44, G: 0x44, B: 0x44, A: 0xff}
		case theme.ColorNameDisabledButton:
			return color.NRGBA{R: 0x26, G: 0x26, B: 0x26, A: 0xff}
		case theme.ColorNameOverlayBackground:
			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff}
		case theme.ColorNameMenuBackground:
			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff}
		}

	case "Light":
		variant = theme.VariantLight
		switch name {
		case theme.ColorNameDisabled:
			return color.NRGBA{R: 0xab, G: 0xab, B: 0xab, A: 0xff}
		case theme.ColorNameInputBorder:
			return color.NRGBA{R: 0xf3, G: 0xf3, B: 0xf3, A: 0xff}
		case theme.ColorNameDisabledButton:
			return color.NRGBA{R: 0xe5, G: 0xe5, B: 0xe5, A: 0xff}
		}
	}

	return theme.DefaultTheme().Color(name, variant)
}

func (m customTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func (m customTheme) Font(style fyne.TextStyle) fyne.Resource {
	return theme.DefaultTheme().Font(style)
}

func (m customTheme) Size(name fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(name)
}
```
and then just
```go
fyne.CurrentApp().Settings().SetTheme(customTheme{"Dark"})
```

**Comment by hq-zhonger** [comment]
ohh,thinks&nbsp;That's great







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyne-io/fyne"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月31日(星期六) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fyne-io/fyne] Grey theme (Issue #3526)





 
One option could be to create a custom theme and apply the different color yourself. I did something similar both for the Light and Dark theme.
 type customTheme struct { 	Theme string } func (m customTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color { 	switch m.Theme { 	case "Dark": 		variant = theme.VariantDark 		switch name { 		case theme.ColorNameDisabled: 			return color.NRGBA{R: 0x55, G: 0x55, B: 0x55, A: 0xff} 		case theme.ColorNameBackground: 			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff} 		case theme.ColorNameButton: 			return color.NRGBA{R: 0x44, G: 0x44, B: 0x44, A: 0xff} 		case theme.ColorNameDisabledButton: 			return color.NRGBA{R: 0x26, G: 0x26, B: 0x26, A: 0xff} 		case theme.ColorNameOverlayBackground: 			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff} 		case theme.ColorNameMenuBackground: 			return color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff} 		} 	case "Light": 		variant = theme.VariantLight 		switch name { 		case theme.ColorNameDisabled: 			return color.NRGBA{R: 0xab, G: 0xab, B: 0xab, A: 0xff} 		case theme.ColorNameInputBorder: 			return color.NRGBA{R: 0xf3, G: 0xf3, B: 0xf3, A: 0xff} 		case theme.ColorNameDisabledButton: 			return color.NRGBA{R: 0xe5, G: 0xe5, B: 0xe5, A: 0xff} 		} 	} 	return theme.DefaultTheme().Color(name, variant) } func (m customTheme) Icon(name fyne.ThemeIconName) fyne.Resource { 	return theme.DefaultTheme().Icon(name) } func (m customTheme) Font(style fyne.TextStyle) fyne.Resource { 	return theme.DefaultTheme().Font(style) } func (m customTheme) Size(name fyne.ThemeSizeName) float32 { 	return theme.DefaultTheme().Size(name) }
 
and then just
 fyne.CurrentApp().Settings().SetTheme(customTheme{"Dark"})

**Comment by andydotxyz** [comment]
I think the suggestion above is the best. We are removing support of developers specifying the theme preferring it a user choice. You can install custom themes as a user or a developer but the toolkit won't be shipping alternatives other than the current theme in the various "variants" that an OS or user can influence (light/dark currently).
