### ISSUE TITLE
Enter/Label Chinese words is Messy Code, don't support it yet?

### ISSUE THREAD

**Issue by conero** [fyne-io/fyne#353]
*When I used Widget `Enter/Label`，enter some Chinese words is show like messy code. Then I try Label it's still. If I missed something about or don't support.*

![微信截图_20190703091843](https://user-images.githubusercontent.com/19564821/60556452-f5136680-9d73-11e9-8030-4a2f289ed2ad.png)

**Comment by andydotxyz** [comment]
You need to load a Chinese font to support these characters.
Described in #351

**Comment by ACXNX** [comment]
I have this problem too.
