### ISSUE TITLE
Font's not working with 2.3.0

### ISSUE THREAD

**Issue by alx3dev** [fyne-io/fyne#3534]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

~~With version **2.2.4** everything work as expected, fonts are embedded in custom theme with `//go:embed MyFont.ttf`, and not-supported characters are replaced automatically. Now with version **2.3.0**, incorrect sign `?` is shown.~~  

Font's are not loaded with 2.3.0, giving the error:
```
2023/01/02 17:31:47 Fyne error:  failed to read theme variant from D-Bus
2023/01/02 17:31:47   Cause: Requested setting not found
2023/01/02 17:31:47   At: /home/username/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/app/app_xdg.go:51
```

This error is triggered always with **2.3.0**, with or without custom theme.

### How to reproduce

You can reproduce it with any example that use font's, or with my repo:
https://github.com/alx3dev/Wireless-UV-Station

### Example code

This is how theme is implemented:

```
package theme

import (
	_ "embed"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

//go:embed MyCyrillicfont.ttf
var font []byte

var my_font = &fyne.StaticResource{
	StaticName:    "MyCyrillicFont.ttf",
	StaticContent: font,
}

//go:embed logo.ico
var logo []byte

var Ico = &fyne.StaticResource{
	StaticName:    "logo.ico",
	StaticContent: logo,
}

type MyTheme struct {
	Theme string
}

var _ fyne.Theme = (*MyTheme)(nil)

func (m *MyTheme) Font(_ fyne.TextStyle) fyne.Resource {
	return my_font
}

func (m *MyTheme) Size(n fyne.ThemeSizeName) float32 {
	if n == theme.SizeNameScrollBar {
		return 0
	}
	if n == theme.SizeNameScrollBarSmall {
		return 0
	}
	return theme.DefaultTheme().Size(n)
}

func (m *MyTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch m.Theme {
	case "Тамна", "Dark":
		v = theme.VariantDark

	case "Светла", "Light":
		v = theme.VariantLight
	}
	return theme.DefaultTheme().Color(n, v)
}

func (m *MyTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

```

### Fyne version

2.3.0

### Go compiler version

1.19.4

### Operating system

Linux

### Operating system version

Linux Mint 20.2

**EDIT:**
Renamed this issue after I found it's not only about Cyrillic font's.

**Comment by andydotxyz** [comment]
Do you get the same problem with FYNE_FONT environment set instead of using embedding?

**Comment by alx3dev** [comment]
Yes, same result.

**Comment by andydotxyz** [comment]
Where can "MyCyrillicFont.ttt" be found? This should be working and our tests with various fonts have passed so need to figure what we missed.

**Comment by alx3dev** [comment]
I can't share font, because it's private one (not mine).
I tried with OpenSans, everything works because all characters are there (but error log in terminal). [https://www.1001fonts.com/open-sans-font.html](url)  
When I try this font from password-generator, it show error sign [https://github.com/Bisns/password-generator/blob/master/theme/PingFang.ttf](url)  
In font that I want to use, one character is missing, so it show `?`, same like with `PingFang.ttf`.
But even without any font, error is there when app is launched. Not sure why, but you would notice it, so it's probably something system related (my best guess).

**Comment by andydotxyz** [comment]
If we test with that font what string shows the error?

**Comment by alx3dev** [comment]
Њ - Serbian cyrillic **W**
Љ - Serbian cyrillic **Q**

**Comment by alx3dev** [comment]
Things got weird a little bit more, it looks like font is not loaded at all. I didn't noticed it at first, probably because I just removed that font during development. Does anyone else have this problem?

**Comment by andydotxyz** [comment]
> Font's are not loaded with 2.3.0, giving the error:
> 
> ```
> 2023/01/02 17:31:47 Fyne error:  failed to read theme variant from D-Bus
> 2023/01/02 17:31:47   Cause: Requested setting not found
> 2023/01/02 17:31:47   At: /home/username/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/app/app_xdg.go:51
> ```

Just a note that this error is not related to fonts. It has been removed from v2.3.1 (upcoming) as it was causing confusion.

**Comment by Jacalz** [comment]
Is this still an issue?

**Comment by alx3dev** [comment]
I gave up with fyne becuase of too many problems I wasn't able to solve quickly, but I can check and let you guys know.

**Comment by alx3dev** [comment]
Start error is gone after `v2.3.1`.  
When using Cyrillic and some characters are not supported, still show `?` instead of default font. (`v2.3.4`)

Since the issue was about DBUS error, i guess it can be closed.
