### ISSUE TITLE
Empty File Created, Not Deleted Using dialog.NewFileSave() and storage.NewExtensionFileFilter

### ISSUE THREAD

**Issue by bionicVonRack** [fyne-io/fyne#3535]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I try to use dialog.NewFileSave() with a filter applied to prevent saving files with an incorrect file extension, I'm getting a 0 byte file left on my Macintosh.

I found this behavior while working through Trevor Sawler's Udemy course - Building GUI Applications With Fyne and Go (Golang). We create a markdown application that contains an EditWidget and PreviewWidget. Text entered in the EditWidget is rendered in markdown in the PreviewWidget. The user can save the resulting file. The application has a menu item to perform a "save as" operation. The dialog for saving has a filter applied to prevent saving files without a ".md" extension. When the user enters an incorrect file name, e.g., "junk", and presses the "Save" button, an error dialog is displayed and a 0 byte file is left on my system. The file is not removed upon return of the callback method. I'm able to remove the file in my code but I think fyne code is the more appropriate place to handle this. The developer and app user may not be aware that this behavior is occurring and their system is being cluttered with unwanted files.

In my debugger, during the execution of NewFileSave() a call is made to .../fyne.io/fyne/v2@v2.3.0/internal/repository/file.go  Writer() - return openFile(u, true) ~ line 127. Stepping into openFile(), in the same file.go file, I can see a call to os.Create() which results in a 0 byte "junk" file.

I've enclosed a sample markdown file that can be used to reproduce the issue.
[savebug.md](https://github.com/fyne-io/fyne/files/10333567/savebug.md)

I've enclosed code for a sample application in the "Example code" area. I have not been able to figure out how to produce a unit test for a dialog. My fyne knowledge path has just begun.

### How to reproduce

1. Start the enclosed app and select the "Open" menu item and in the dialog, navigate to a folder with the markdown file (save bug.md) I enclosed above.
2. Click in the file name input widget and enter a filename without a ".md" file extension, e.g., "junk".
3. Navigate to where you wish to save the file. 
4. Click on the "Save" button. An error dialog with a message to chose a file name with a ".md" extension appears and a 0 byte file ("junk") is on the system.

### Example code

```go
/*
Code that demonstrates NewFileSave() leaves a 0 byte file on the system
when the user attempts to save a file without the required file extension.

This code is largely based on code from Trevor Salwer's Udemy class:
Bulding GUI Applications with Fyne and Go (Golang).
Modified by Philip Rackley
*/
package main

import (
	"io/ioutil"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/storage"
	"fyne.io/fyne/v2/widget"
)

type config struct {
	EditWidget    *widget.Entry
	PreviewWidget *widget.RichText
	CurrentFile   fyne.URI
}

var cfg config

func main() {
	// create a fyne app
	a := app.New()

	// create a window for the app
	win := a.NewWindow("Markdown")

	// get the user interface
	edit, preview := cfg.makeUI()
	cfg.createMenuItems(win)

	// set the content of the window
	win.SetContent(container.NewHSplit(edit, preview))

	// show window and run app
	win.Resize(fyne.Size{Width: 800, Height: 500})
	win.CenterOnScreen()
	win.ShowAndRun()
}

func (app *config) makeUI() (*widget.Entry, *widget.RichText) {
	edit := widget.NewMultiLineEntry()
	preview := widget.NewRichTextFromMarkdown("")

	app.EditWidget = edit
	app.PreviewWidget = preview

	edit.OnChanged = preview.ParseMarkdown

	return edit, preview
}

func (app *config) createMenuItems(win fyne.Window) {
	openMenuItem := fyne.NewMenuItem("Open...", app.openFunc(win))

	saveAsMenuItem := fyne.NewMenuItem("Save as...", app.saveAsFunc(win))

	fileMenu := fyne.NewMenu("File", openMenuItem, saveAsMenuItem)

	menu := fyne.NewMainMenu(fileMenu)

	win.SetMainMenu(menu)
}

var filter = storage.NewExtensionFileFilter([]string{".md", ".MD"})

func (app *config) saveAsFunc(win fyne.Window) func() {
	return func() {
		saveDialog := dialog.NewFileSave(func(write fyne.URIWriteCloser, err error) {
			if err != nil {
				dialog.ShowError(err, win)
				return
			}

			if write == nil {
				// user canceled
				return
			}

			if !strings.HasSuffix(strings.ToLower(write.URI().String()), ".md") {
				dialog.ShowInformation("Error", "Please name your file with a .md extension!", win)
				return
			}

			// save file
			write.Write([]byte(app.EditWidget.Text))
			app.CurrentFile = write.URI()

			defer write.Close()

			win.SetTitle(win.Title() + " - " + write.URI().Name())

		}, win)
		saveDialog.SetFileName("untitled.md")
		saveDialog.SetFilter(filter)
		saveDialog.Show()
	}
}

func (app *config) openFunc(win fyne.Window) func() {
	return func() {
		openDialog := dialog.NewFileOpen(func(read fyne.URIReadCloser, err error) {
			if err != nil {
				dialog.ShowError(err, win)
				return
			}

			if read == nil {
				// user canceled
				return
			}

			defer read.Close()

			data, err := ioutil.ReadAll(read)
			if err != nil {
				dialog.ShowError(err, win)
				return
			}

			app.EditWidget.SetText(string(data))

			app.CurrentFile = read.URI()

			win.SetTitle(win.Title() + " - " + read.URI().Name())

		}, win)
		openDialog.SetFilter(filter)
		openDialog.Show()
	}
}
```

### Fyne version

v2.3.0

### Go compiler version

go1.19.4

### Operating system

macOS

### Operating system version

MacOS Ventura 13.0.1

**Comment by andydotxyz** [comment]
When you are showing the error that the file extension is wrong the file write operation has already begun.
If you want to revert the user request of creating it you will have to close the open file and then delete it.

I'm guessing this issue is what you really want to see implemented? https://github.com/fyne-io/fyne/issues/1044

**Comment by bionicVonRack** [comment]
Yes. If the file name isn't valid, don't leave a corresponding file on the system. An application developer (me) could close the file and delete it, but the developer needs to know an empty file was created and that behavior was/is not obvious at least to me.

**Comment by andydotxyz** [comment]
Well I guess the docs could be explicit about it - they say the file will be created but not exactly when I suppose. But you are being passed a `Writer`, this cannot be to a file that does not exist yet...

Implementing the linked issue should resolve the confusion.

**Comment by bionicVonRack** [comment]
I take it that when the fyne team implements a solution for issue #1044 my issue #3535 will be resolved, correct? 

In the meantime, before a solution is provided, a kludge workaround could be in my code where I check the file suffix. The empty file has been created at that point. The kludge would involve checking for the file's existence and removal, ugh.

Any idea when work on #1044 might be started?

**Comment by andydotxyz** [comment]
The ticket is not scheduled at this time.

You don't need a kludge to check for existence - the callback from Save is guaranteed to have created the file if there is no error passed in.
