### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by suhaib68** [fyne-io/fyne#3545]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

when i run it shows this:
# pkg-config --cflags  -- gl gl
pkg-config: exec: "pkg-config": executable file not found in $PATH
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.

### How to reproduce

just wont run

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

### Fyne version

v2.3.0

### Go compiler version

1.18.3

### Operating system

Other (specify below)

### Operating system version

Ubuntu 22.04.1 LTS

**Comment by andydotxyz** [comment]
Try the getting started docs https://developer.fyne.io/started/ - it sounds like some of the development dependencies are missing.

**Comment by andydotxyz** [comment]
I assume following the developer setup resolved this.
Feel free to re-open if you think there is an ongoing issue
