### ISSUE TITLE
 You are using macos 10.13.6. The app requires macos 10.14 or higher.

### ISSUE THREAD

**Issue by CatchZeng** [fyne-io/fyne#355]
![15_31_31__07_04_2019](https://user-images.githubusercontent.com/10027281/60650882-9a633300-9e77-11e9-88ae-8e50d0d6ff3d.jpg)

How to set the minimum supported Mac OS version？

I tried

```
<key>LSMinimumSystemVersion</key>
<string>10.13</string>
```
and
```
<key>LSEnvironment</key>
<dict>
     	<key>MinimumSystemVersion</key>
     	<string>10.3</string>
</dict>
```

but it didn’t work.

**Comment by andydotxyz** [comment]
Fyne apps should not require any specific macOS version.
I test on 10.13 all the time and it works for me.

How did you build the app? Did you use the fyne package tools or is it a custom manifest file included?

**Comment by CatchZeng** [comment]
package tools

**Comment by andydotxyz** [comment]
Are you building on a different computer to the one it’s running on?

**Comment by CatchZeng** [comment]
I developed and packaged on macos 10.14, this works, but the tester found this problem on macos 10.13.6.  
I want to know how to package a app compatible with macos 10.13.6 on macos 10.14. Thanks!

**Comment by andydotxyz** [comment]
Thanks. It seems you have found a bug with the way that the package command works.
I think we can look into this further.

**Comment by andydotxyz** [comment]
The solution is to build the binaries for older macOS version using MACOSX_DEPLOYMENT_TARGET environment variable. Like this:

`MACOSX_DEPLOYMENT_TARGET=10.12 go build`

and then package it in the normal manner.
I cannot think of a way that we can make this process easier, sorry.
