### ISSUE TITLE
Allow Disable and Enable for Slider widget

### ISSUE THREAD

**Issue by ObaraEmmanuel** [fyne-io/fyne#3551]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I often use the slider widget as input and it's not possible to disable and enable it out of the box.

### Is it possible to construct a solution with the existing API?

The only work around is creating a custom slider widget and that is a huge inconvenience for such a simple feature. It requires one to extend not only the widget but also the renderer to provide the necessary disabled state styling. Things get messy fast.

### Describe the solution you'd like to see.

It would be nice if the Slider widget like other input widget could implement the Disableable interface right out the box. I believe it is not such a huge fix, I could even offer to send in a PR for it.

**Comment by dweymouth** [comment]
Fixed on develop for 2.5.0
