### ISSUE TITLE
How to hide the command window under windows?

### ISSUE THREAD

**Issue by Thonpson2019** [fyne-io/fyne#356]

**Comment by Kvaz1r** [comment]
compile with  **_-ldflags -H=windowsgui_**

**Comment by edwinclement08** [comment]
Adding a note here. ``
The solution above mentioned by @Kvaz1r helps with hiding that initial cmd prompt that is opened alongside the go app.
If, however, you use `cmd.Run` from `os/exec`, that spawns a new prompt for each invocation.
To hide that window, you should set up `cmd.Run` as follows:
```
cmd := exec.Command("fyne")

var out bytes.Buffer
var errorStream bytes.Buffer
cmd.Stdin = strings.NewReader("")
cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
cmd.Stdout = &out
cmd.Stderr = &errorStream
```
