### ISSUE TITLE
Fyne bundle creates invalid files

### ISSUE THREAD

**Issue by SKBotNL** [fyne-io/fyne#3564]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When using `fyne bundle` the tool creates invalid files.
In issue #986 I've read that it seems to create UTF-16 (LE BOM) files instead of UTF-8 files, which causes Go to error and return `go: reading bundled.go: unexpected NUL in input`.
After converting the file to UTF-8 there are two errors that I've gotten while testing:
JPG:
```
Fyne error:  failed to paint image
Cause: failed to decode image: invalid JPEG format: bad Huffman code
At: C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/image.go:56
```
PNG:
```
Fyne error:  failed to paint image
Cause: failed to decode image: png: invalid format: invalid checksum
At: C:/Users/Sven/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/image.go:56
```

### How to reproduce

1. Use `fyne bundle`
2. Create a new image from a resource
3. Build the program

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
)

func main() {
	a := app.New()
	w := a.NewWindow("Image")

	image := canvas.NewImageFromResource(<insert resource here>)
	w.SetContent(image)

	w.ShowAndRun()
}
```

### Fyne version

2.3.0

### Go compiler version

1.19.5

### Operating system

Windows

### Operating system version

Windows 11 22H2

**Comment by Jacalz** [comment]
Can you specify exactly which `fyne bundle` command you are using? I believe there is a problem with Powershell doing bad encoding when you are redirecting input through it.

I would suggest using the `-o` flag and also try running your command in `cmd` instead.

**Comment by SKBotNL** [comment]
> Can you specify exactly which `fyne bundle` command you are using? I believe there is a problem with Powershell doing bad encoding when you are redirecting input through it.

I'm running `fyne bundle [insert image here] >> bundled.go

**Comment by andydotxyz** [comment]
It's the `>>` in some Windows terminals that breaks things. Use `-o` as @Jacalz suggested instead and it should work as expected.

**Comment by Bluebugs** [comment]
Does anyone know if there is any way to detect the type of the terminal and generate an error?

**Comment by SKBotNL** [comment]
> It's the `>>` in some Windows terminals that breaks things. Use `-o` as @Jacalz suggested instead and it should work as expected.

Got it, I will try this tomorrow.

**Comment by SKBotNL** [comment]
That indeed fixes it, maybe add this to the documentation?

**Comment by andydotxyz** [comment]
Updated now, thanks. https://developer.fyne.io/extend/bundle
