### ISSUE TITLE
Expose string position from Entry's cursor row and cursor column values

### ISSUE THREAD

**Issue by idroz** [fyne-io/fyne#3581]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Consider a MultilineEntry with a `TextWrapBreak` wrapping property.

It may be desirable to insert a custom character (e.g. \n\t) with a key press (e.g. return) at the current cursor position.

This involves extending Entry's `TypedKey` method and manually inserting a substring into the Text string. However it is very challenging to get the precise cursor position in this string.

### Is it possible to construct a solution with the existing API?

There is already a private method here: https://github.com/fyne-io/fyne/blob/8c2509518b2df442a6b748d9b07754739592e6d7/widget/entry.go#L790

### Describe the solution you'd like to see.

I would like to see the `cursorTextPos` method as public.

**Comment by andydotxyz** [comment]
I don't think you have to override anything - you can just call `TypedKey` or `TypedRune` and it will insert at the cursor position.

**Comment by idroz** [comment]
Cool - thanks!
