### ISSUE TITLE
Hovered background in List widget isn't reset when scrolling reuses an existing list item

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3584]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If scrolling a list widget with a lot of data and a row was hovered when scrolling began, every several rows will incorrectly have the hover background set when it reuses the listItem for the row that was originally hovered.

### How to reproduce

Run the example code, resize the window so a small handful of list rows are visible, hover over one, and start scrolling. Continue scrolling and note that some rows have the hover background set as they scroll by.

### Example code

```go
package main

import (
	"strconv"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List scrolling bug")

	l := widget.NewList(
		func() int { return 100 },
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(id widget.ListItemID, lbl fyne.CanvasObject) {
			lbl.(*widget.Label).SetText(strconv.Itoa(id))
		})
	myWindow.SetContent(l)
	myWindow.ShowAndRun()

}```

### Fyne version

2.3.0

### Go compiler version

go1.19.4 darwin/amd64

### Operating system

macOS

### Operating system version

Big Sur 11.4

### Additional Information

_No response_

**Comment by andydotxyz** [comment]
Fixed on develop
