### ISSUE TITLE
Ability to scroll to bottom with Entry widget

### ISSUE THREAD

**Issue by syllith** [fyne-io/fyne#3590]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to create a console, similar to command prompt, where I can append text to the Entry widget and it will automatically scroll with the last line that was added.

### Is it possible to construct a solution with the existing API?

If there is, I am not seeing any way to do it.

### Describe the solution you'd like to see.

I have looked but I don't see any way to control the scroll position of the Entry widget at all. If you could add a simple function that will let me scroll to the bottom of the Entry widget, that would be fantastic.

Even better would be the ability to auto scroll to the bottom EXCEPT when I have scrolled up to view previous entries in the log. This way when I go to view previous entries, it won't constantly scroll on me. But if I scroll back down to the bottom to view the latest entries, it will stay at the bottom and I can watch it in real time. A sort of "console mode" if you will. Or even simpler, if you had a way where I can simply check the scroll position of the widget, I can write my own logic to do this. I have done this in C# by tweaking the RichTextBox element, but I cannot find any way to do this with the existing Entry widget in Fyne.

**Comment by syllith** [comment]
I actually figured this out! This is only my second day learning Fyne and I had a misunderstanding of how everything worked. I believe I came up with a pretty good way of doing this. The following code will create "console" like behavior as I described in the original feature request, except this has a "threshold" built in, which limits the number of lines that can be in the console (so it doesn't just fill forever)

```
var ConsoleBuffer []string
var Console *widget.Entry = &widget.Entry{
	Wrapping:  fyne.TextWrapOff,
	TextStyle: fyne.TextStyle{Monospace: true},
	MultiLine: true,
}
var ConsoleContainer = container.NewScroll(Console)

func appendToLog(text string) {
	if len(ConsoleBuffer) > 100 {
		copy(ConsoleBuffer[0:], ConsoleBuffer[0+1:])
		ConsoleBuffer[len(ConsoleBuffer)-1] = ""
		ConsoleBuffer = ConsoleBuffer[:len(ConsoleBuffer)-1]
	}

	ConsoleBuffer = append(ConsoleBuffer, text)
	Console.SetText(strings.Join(ConsoleBuffer, "\n"))
	consoleHeight := Console.Size().Height - ConsoleContainer.Size().Height
	offset := ConsoleContainer.Offset.Y

	if consoleHeight-offset < 30 {
		adjust := Console.MinSize().Height - ConsoleContainer.Size().Height
		ConsoleContainer.Offset = fyne.NewPos(0, adjust)
		ConsoleContainer.ScrollToBottom()
	}
}
```

The only thing I don't quite understand is why calling ConsoleContainer.ScrollToBottom() by itself doesn't work? I have to have the 2 lines above it to work as well. But either way, it's working and I'm happy. If anyone has a better idea on how to do this, I'm all ears.

**Comment by andydotxyz** [comment]
The `ScrollToBottom()` call should always scroll to the bottom.
Perhaps it is a timing issue and the setting text is taking longer than your request to scroll.

What you will discover when logs get long is that joining them with newline and calling `SetText` will get very slow - you are using string parsing to do your layout for you. Instead I would recommend appending new Label widgets for each row, which will be much faster to append, and probably will avoid the issue you describe above with having to add the maths code.

**Comment by syllith** [comment]
You're already ahead of me. I am experiencing slow behavior and even freezing, I'm just a bit confused on exactly how I need to go about doing this. You said to append a new label widget for each row, but I'm not quite sure how to do that. Am I right in thinking that I should have a sort of "cyclical buffer" that gets rid of the oldest entries and only keeps a certain number of lines in the entry widget? Would it get slow if I just kept infinitely adding labels?

If it's not too much trouble, could you give me a tiny little code sample or perhaps a bit more detail on how I should do this in the way you recommended? Fyne has a workflow I'm not very used to yet and it's not making a lot of sense to me. Sorry for my ignorance

**Comment by andydotxyz** [comment]
There are lots of examples of this sort of thing if you look around the community. Adding rows "indefinitely" may slow eventually but no where near as fast. A buffer as you say is best, like we provide in List widget. But may not be needed depending on your usecase.

**Comment by syllith** [comment]
Am I still going to use the entry widget for this? Does the entry widget support Labels being appended to it? The only way I can see to append anything is by using `SetText()` but this only accepts a string input. My problem is that I still don't have enough of an understanding to even formulate a google search or know what I'm looking for in it. What should I even be searching for?

This program is intended to run for long periods of time with information being written to the console very fast, so if you could make a recommendation based on that, I'd appreciate it. 

Sorry for all the questions and thanks for being patient with me. I really need to figure this out but I'm quite lost right now.

**Comment by andydotxyz** [comment]
> Am I still going to use the entry widget for this? Does the entry widget support Labels being appended to it? 

No, you would use a container of some sort. The entry widget is for editing text (like a multiline text entry in HTML) - not for appending lots of data to like a log viewer.
