### ISSUE TITLE
Scrolling enhancement: Add PageUp and PageDown functions to all scrollable widgets/containers

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3591]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

As far as I can tell, there is no way to hook up keyboard controls like the PgUp/Down keys or arrow keys to scrolling content. Exposing a programmatic PageUp/Down API to scrollable widgets and containers would allow the app developer to set up keyTyped event hooks to call these APIs.

### Is it possible to construct a solution with the existing API?

Not that I can see.

### Describe the solution you'd like to see.

All scrollable widgets and containers should expose a `PageUp` and a `PageDown` function, which scrolls the item by roughly one visible area's worth of offset (probably a little less than a full visible area). The scroll should also be animated, at least by default (so it appears the same as if the user were using the scroll wheel/trackpad to scroll), and either the theme API or the PageUp/Down functions directly could allow configuration of the animation speed.

It would also be nice for the distance scrolled to be configurable at the API call, either completely arbitrary or just two options 1. scroll a small fraction of the visible area like a quarter-page (e.g. to connect to Up/Down arrows), and 2. scroll nearly a full visible area worth (e.g. to connect to PageUp/Down keys)

**Comment by andydotxyz** [comment]
Instead of exposing more APIs would it not be better to simply implement the expected key behaviour in the widgets?

**Comment by dweymouth** [comment]
Maybe, but to some extent I think it should be configurable as well. At a minimum I think the application should have a way of connecting window-level key events to the scroll behavior. E.g. if there is only one scrollable item in an app and it is the main UI element (e.g. a markdown viewer, file browser, etc), it's reasonable for up/down to scroll the view if nothing has focus. But this wouldn't be desirable for all apps.

**Comment by andydotxyz** [comment]
I don't understand how that relates to adding page up / down to a scroll container?

Meeting your "at a minimum" is already possible as you can indeed respond to key events at the top level of your app when no other widget has focus. Look at `Canvas.AddOnTypedKey`

**Comment by dweymouth** [comment]
There's no appropriate API to connect the canvas key event to, which is why I was suggesting new `PageDown/Up` APIs to be exposed on scrollable widgets. The current scroll API for List is `ScrollTo(itemID)` and `ScrollToBottom/Top` - these scrolls are also not animated. As far as I can tell, the only way to implement arrow key scrolling right now is to extend the scrollable widgets to expose such an API, or to simulate sending GLFW scroll events in the onTypedKey handler at the Window canvas. I will eventually try the former in my Fyne fork, but I have a feeling it would be useful in general and not just for my app, which was why I was suggesting it as a feature request.

**Comment by andydotxyz** [comment]
Sorry, I had thought there were two different things going on. To my earlier point:

> would it not be better to simply implement the expected key behaviour in the widgets?

Does this not hold true? Implementing the behaviour instead of exposing more APIs is our usual approach.

> Every scrollable canvasObject (List, Table, ScrollContainer, etc) could add the .Scroller() function

Surprisingly it is not that simple. Not all scrollable items are always scrollable (notably Entry but I seem to recall there are others too. Exposing the scroller directly then requires us to always support it whereas the preferred approach is to expose behaviour not graphical composition. I.e. if we expose a `Scroller` instead of scroll behaviours then we can never remove the scroller in preference for the widget to optimise with its own implementation.

> The current scroll API for List is ScrollTo(itemID) and ScrollToBottom/Top - these scrolls are also not animated

Feel free to open a feature request that we animate this scroll. Sounds like a nice enhancement.

**Comment by dweymouth** [comment]
> Feel free to open a feature request that we animate this scroll. Sounds like a nice enhancement.

Will do! Note that I think it should be optionally animated. To be backward compatible, there could be a new property `AnimateScrolls bool` on the list struct, which if set to true animates ScrollToItem/Top/Bottom.

> would it not be better to simply implement the expected key behaviour in the widgets?

It could be nice to implement the key behavior in the widget while it's focused, though I think a scroll container/list/table etc should *not* provide a visual indicator of being focused because it would look out of place for a blue rectangle to be drawn around what may be almost the entire UI. Also, if the app wants to allow it to be keyboard scrollable even if it isn't focused, it would have to manually call the widget's TypedKey/TypedRune, which I suppose is doable, but feels a bit like a workaround.

Feel free to close this if you think it doesn't warrant further discussion

**Comment by andydotxyz** [comment]
> Feel free to close this if you think it doesn't warrant further discussion

I don't think it should be closed - even if the discussion wraps up it seems like there is a feature request in here! I would suggest we add the key handling to all scroll widgets first and take it from there, but it seems worth checking that making all scroll areas focusable is desirable. I have mixed feelings now I think about it. Seems like Entry is an obvious need, and we now have that for List/Table/Tree as well, but the generic scroller I'm not sure...

**Comment by dweymouth** [comment]
I think generic ScrollContainer should definitely have some way to support keyboard-based scrolling. The exact form that should take is still an open question

**Comment by dweymouth** [comment]
I knew a lot less about Fyne when I originally reported this issue. Circling back on it my thoughts now are:

* List, Table, Tree, GridWrap, and Entry should respond to PageUp/Page Down KeyEvents when focused, and do an animated scroll
   * This should be relatively easy to add and requires no new APIs
   * It's also easy for the app developer to connect a canvas-level key event to whatever scrollable collection widget in their app that should be scrolled when page up/page down are done at the window level, by just calling TypedKey on that widget
* However it would still be nice for my use case at least to be able to do a smaller sized animated scroll when regular up/down arrow keys are pressed at the window canvas level. This is less clear how to achieve without a new HalfPageDown/HalfPageUp API or similar, since obviously when the collection widget is focused the arrow keys have a different purpose - namely moving between the individual collection items.

**Comment by andydotxyz** [comment]
This sounds good at the page up/down level. Animating optionally I think applies to all scroll operations and might even have a separate feature request.

> However it would still be nice for my use case at least to be able to do a smaller sized animated scroll

I think this is a separate problem - even defining `HalfPageUp` only works if the "smaller sized" amount is half. Instead we should look at how the `ScrollTo` combined with `Offset` could be supported. I think if you own the `Scroll` container this is already possible, but for those with embedded scrollers we need more thought.

**Comment by dweymouth** [comment]
> I think this is a separate problem - even defining HalfPageUp only works if the "smaller sized" amount is half. Instead we should look at how the ScrollTo combined with Offset could be supported. I think if you own the Scroll container this is already possible, but for those with embedded scrollers we need more thought.

We have ScrollToOffset APIs now. I think that is all that's needed, user code could theoretically animate a scroll using fyne.NewAnimation and ScrollToOffset

**Comment by andydotxyz** [comment]
Related to this is a feature request for all scroll APIs to animate #3595.
I'm a little lost in what is and is not still needed with this - @dweymouth can you summarise where you think this has got to?
Thanks

**Comment by dweymouth** [comment]
I've come to think that animating scrolls is not a high-priority feature request at all, especially since user code now has all the APIs it needs to animate scrolls itself. And not every scroll should be animated, so knowing *when* to animate by default would be a challenge in and of itself. (EG PageUp/PageDown generally do *not* animate in most apps). I think this ticket could be repurposed to track the request:

* **Collections widgets should respond to PageUp/PageDown keys when focused**

**Comment by dweymouth** [comment]
Closing as duplicate of #4695
