### ISSUE TITLE
Extending table capabilities

### ISSUE THREAD

**Issue by bq-wrongway** [fyne-io/fyne#3594]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Its more of a suggestion, https://github.com/fyne-io/fyne/issues/1658 here is a request for table headers, i want to expand on this.

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

At the moment table has very basic functionality, extending this would make table widget much more usable and enjoyable.
In the issue that i [linked](https://github.com/fyne-io/fyne/issues/1658)  there is request for the headers, i will expand on this a bit : 

1) Columns should be able to be pinned 

2)Rows should be able to be pined 
(pinning a row, makes further scrolling down the table possible, while not losing the focus of current row ) same for column
especially usefull when there are a lot of rows/columns and we must scroll

3)Rows should be able to be marked somehow (different color, it would make searching and comparing data easier,)
(example, all rows containing X value in column Y should be red)

4)Sorting of the table out of the box

5)Clicking on cell in a row should Highlight whole row, this makes following the row with your eyes much easier, and less error prone,

6)Pagination (scrolling table is great, but with larger amount of data pagination is much more useful)

**Comment by andydotxyz** [comment]
Thanks for the feedback / suggestions - but can you please try and keep it to 1 request per ticket? It is difficult to add different resolutions to a single issue.

With regards to the items suggested I think it is important to outline that a toolkit like Fyne is not going to implement all the features of a widget - we want to make sure that we enable everything that you want, but may not actually deliver every feature as a core part of the toolkit. On specifics of your requests above this means:

3) marking items in a column somehow is entirely possible and can be done in your code - you control what is shown in each cell.
4) Table is a collection widget that asks the developer to manage data, therefore we cannot sort out of the box as we have no idea what data you are managing. This is also already possible in your own code.
6) Pagination is not part of a table widget. You can paginate any data and then refresh the widget to show a different window on your data. There may be space for a feature request for a standard pagination control that could be used in conjunction with table, but it does not make sense as a feature of Table itself.

This leaves us with 1, 2 and 5.
Request 1 and 2 both refer to "pinning" - which as I understand it is a feature of headers... I don't think it makes sense to force any other row or column to remain visible as you scroll - so it would be implemented along with the header feature request that you linked to.
5) highlight a row/column when clicking a cell. I can see this being good standard behaviour for a header - but not for any "standard" cell. If you feel differently for the use-case of your app then you can add that behaviour by hooking into the `OnSelected` callback and adding some "other item is selected" indicator in your table content widgets.

I hope that this response is helpful. Having gone through the items you listed I am not sure what remains as a feature request for the core Table widget separate to the header feature request that already existed.

**Comment by andydotxyz** [comment]
I should have a PR for the items 1 and 2 at least pretty soon

**Comment by andydotxyz** [comment]
Option 5 has not been included as the default headers are not buttons. 
The code of an app could implement it through a button header and iterating on data to select
