### ISSUE TITLE
List, Table: Animate scrolling when ScrollToTop/Bottom/Item is called

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3595]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Scrolls initiated programmatically with `ScrollToTop/Bottom/Item` are not animated.

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

It would be nice to optionally animate scrolling when calling the `ScrollToTop/Bottom/Item` APIs in List (and Tree/Table? not as familiar with those widgets). A new property on the widget `AnimateScrolling bool` could allow the app to set whether the scroll should be animated or not.

**Comment by andydotxyz** [comment]
Why would this be optional set by developer? Would it not more likely be a user preference? We have previously discussed a global "disable animations" feature that seems like it could apply here as well?

**Comment by dweymouth** [comment]
I would think it would depend on the type of user interaction whether it should be animated or not, and the app would know that best. e.g. if a "Go to item" dialog allows the user to quickly jump to a particular row, that maybe shouldn't be animated, but if the list rows themselves allow for keyboard navigation, scrolls should maybe be animated

**Comment by dweymouth** [comment]
I can give one case where animation would definitely not be desired - being able to create a new list that is immediately scrolled to a specific item.

**Comment by andydotxyz** [comment]
> I can give one case where animation would definitely not be desired - being able to create a new list that is immediately scrolled to a specific item.

Hmm, I guess I'm not sure that I would agree that this should never have animation. An animation gives user context and so shows what is happening. Without it in this instance they won't have the same hint of where / how far the new item is compared to where they were positioned before adding.

**Comment by dweymouth** [comment]
> > I can give one case where animation would definitely not be desired - being able to create a new list that is immediately scrolled to a specific item.
> 
> Hmm, I guess I'm not sure that I would agree that this should never have animation. An animation gives user context and so shows what is happening. Without it in this instance they won't have the same hint of where / how far the new item is compared to where they were positioned before adding.

Maybe *never* was too strong of a word, but I do think there are cases where animation would not be desired. Imagine a music player app like Spotify where users can create playlists. In the playlist view they can secondary tap a track and select "Show in album" from a context menu. Imagine the track also came from a box set album so the album's tracklist is large. I'd think the expected behavior would be for the album page to be shown with the tracklist already scrolled to the given track, and that row being selected. The tracklist rows already show the track number so the context of how far along in the list they are is already there (plus the scrollbar visual cue as well).

The scrolls that definitely should be animated according to Fyne preferences are any keyboard-driven scrolling.

**Comment by dweymouth** [comment]
I guess this could be mitigated by adding a new constructor for List/Table/Tree that allows specifying the initial item that should be scrolled to (and the scroll is not animated in this case b/c the widget is initially rendered with the position already being set beforehand).

**Comment by andydotxyz** [comment]
> I guess this could be mitigated by adding a new constructor for List/Table/Tree that allows specifying the initial item that should be scrolled to (and the scroll is not animated in this case b/c the widget is initially rendered with the position already being set beforehand).

Good point, but I think you don't even need this complexity.
If you specify something to be scrolled before it is rendered for the first time the animation would not occur anyway (I would expect?)...

**Comment by dweymouth** [comment]
Actually it seems you have to render the list before it even gets a scroller currently. I forked the list widget to add GetScrollPosition and ScrollToPosition APIs (which I need to be able to re-create a list widget from the data model + scroll position, so it appears exactly as it looked when the state was saved and the original widget destroyed). I need to call Refresh() before I can call ScrollToPosition

**Comment by dweymouth** [comment]
I am having second thoughts about whether scrolls should animate by default. If scroll animation is added, perhaps it should be up to the app on a case by case basis whether a scroll should animate. I would consider this request to be very low priority especially now with ScrollToOffset being released in 2.5 which can give user code all it needs to do animated scrolls themselves.

**Comment by andydotxyz** [comment]
Given it was your requests and you're not sure it's useful I'd be happy for you to close this ;)
