### ISSUE TITLE
macOS (arm64): Package gl was not found in the pkg-config search path

### ISSUE THREAD

**Issue by Klaus-Tockloth** [fyne-io/fyne#3598]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Cross compilation 'macOS (arm64) -> linux (amd64)' fails:

```
% sh build-linux.sh  

# renew vendor content
go mod vendor

# compile for 'linux'
CC=x86_64-linux-musl-cc GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build --ldflags '-extldflags "-static"' -o build/linux-amd64/hello-world
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from vendor/github.com/go-gl/glfw/v3.3/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

### How to reproduce

```
#!/bin/sh

set -o verbose

# renew vendor content
go mod vendor

# compile for 'linux'
CC=x86_64-linux-musl-cc GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build --ldflags '-extldflags "-static"' -o build/linux-amd64/hello-world
```

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")
	w.Resize(fyne.NewSize(200, 200))
	hello := widget.NewLabel("Hello World!")
	w.SetContent(hello)
	w.ShowAndRun()
}
```

### Fyne version

v2.3.0

### Go compiler version

go1.19.5 darwin/arm64

### Operating system

macOS

### Operating system version

Ventura 13.1 (Apple M1 Pro)

### Additional Information

Issue maybe related to #3545.

Prerequisites (fresh) installed:

- go version go1.19.5 darwin/arm64
- Xcode 14.2
- Command Line Tools
- x86_64-linux-musl-cc

**Comment by Klaus-Tockloth** [comment]
Thanks for looking into this. The installation of ...
```
brew install mesalib-glw
brew install freeglut
```
... solves the first problem concerning "Package gl was not found in the pkg-config search path."

But I'm still unable to cross-compile (macOS -> Linux), because the X11 headers couldn't be found by the C compiler:
```
CC=x86_64-linux-musl-cc GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build --ldflags '-extldflags "-static"' -o build/linux-amd64/gvsc
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from vendor/github.com/go-gl/glfw/v3.3/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
These headers are installed on my system, but it seems that the C compiler "x86_64-linux-musl-cc" couldn't find them.
Perhaps a C compiler issue / missing configuration concerning the include path for the headers. The headers are installed on my system (see /opt/homebrew/include/X11/Xlib.h):
```
sudo find / -name "Xlib.h"
...
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/System/Volumes/Data/opt/homebrew/include/X11/Xlib.h
/System/Volumes/Data/opt/homebrew/Cellar/libx11/1.8.3/include/X11/Xlib.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/Xlib.h
/opt/homebrew/include/X11/Xlib.h
/opt/homebrew/Cellar/libx11/1.8.3/include/X11/Xlib.h
...
```
It seems that cross-compilation from macOS to Linux is difficult concering the required tools, libraries, headers and configuration. Fyne-cross makes this much easier and I was able to cross-compile via Docker container.

Ideas concering the "missing X11 header problems" are welcome. But if nodoby has one, please close this issue. The solution via Docker container (fyne-cross) is appropriate for me.

**Comment by andydotxyz** [comment]
It is possible that we are not correctly reading paths from pkg-config of the x11 library. Do you have a copy of the .pc file that home brew ships for the package that contained X11.h?

**Comment by Klaus-Tockloth** [comment]
'/opt/homebrew/lib/pkgconfig/' contains two '.pc' aliases concerning X11:

/opt/homebrew/Cellar/libx11/1.8.3/lib/pkgconfig/x11.pc
```
prefix=/opt/homebrew/Cellar/libx11/1.8.3
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

xthreadlib=

Name: X11
Description: X Library
Version: 1.8.3
Requires: xproto kbproto
Requires.private: xcb >= 1.11.1
Cflags: -I${includedir} 
Libs: -L${libdir} -lX11
Libs.private: 
```

/opt/homebrew/Cellar/libx11/1.8.3/lib/pkgconfig/x11-xcb.pc 
```
prefix=/opt/homebrew/Cellar/libx11/1.8.3
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: X11 XCB
Description: X Library XCB interface
Version: 1.8.3
Requires: x11 xcb
Cflags: -I${includedir}
Libs: -L${libdir} -lX11-xcb
```

**Comment by Mr-BeanSir** [comment]
Has the problem been resolved? I hope to compile on armv7, but the same issue occurred
`go build github.com/go-gl/gl/v3.1/gles2:
# pkg-config --cflags  -- gl gl
pkg-config: exec: "pkg-config": executable file not found in %PATH%
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188:0,
                 from ./glfw/src/context.c:30,
                 from ..\..\pkg\mod\github.com\go-gl\glfw\v3.3\glfw@v0.0.0-20221017161538-93cebf72946b\c_glfw.go:4:
./glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.`

**Comment by andydotxyz** [comment]
Did you install the X11 headers into your windows setup? As mentioned above you either need the required libraries locally or you should use `Fyne-cross` which will prepare the environment in a container for you.
I don't think this is related to the X11 header location on macOS that seems to be the cause of this issue.

**Comment by Mr-BeanSir** [comment]
> Did you install the X11 headers into your windows setup? As mentioned above you either need the required libraries locally or you should use `Fyne-cross` which will prepare the environment in a container for you. I don't think this is related to the X11 header location on macOS that seems to be the cause of this issue.

I didn't add X11 under Windows. I now use Docker to install arm32v7/ubuntu, and everything is configured. But I have waited more than ten minutes for it to be compiled. I don't know whether this is normal, because it is the first time I compile it. Now I use go build - x main.go to check the input to determine whether it is working. Please wait a moment and I will reply whether it succeeds or fails

**Comment by andydotxyz** [comment]
Fyne-cross uses Docker internally, you should not have to set up anything manually. It just takes care of the whole process like a regular build tool, it just needs a Docker instance (or podman).

**Comment by Mr-BeanSir** [comment]
> Fyne-cross uses Docker internally, you should not have to set up anything manually. It just takes care of the whole process like a regular build tool, it just needs a Docker instance (or podman).

I have tried fyne-cross, but unfortunately it did not run. The program prompts not found, but it does exist

**Comment by andydotxyz** [comment]
> I have tried fyne-cross, but unfortunately it did not run. The program prompts not found, but it does exist

That sounds like setup issue on your computer - join one of the channels for support or open a ticket if you feel we've broken something. It certainly should work.

**Comment by Mr-BeanSir** [comment]
> > I have tried fyne-cross, but unfortunately it did not run. The program prompts not found, but it does exist
> 
> That sounds like setup issue on your computer - join one of the channels for support or open a ticket if you feel we've broken something. It certainly should work.

Yes, it is true that I am missing the environment because I successfully compiled it under ubuntu in armv7. However, it is dynamically linked, and it seems that only statically linked can run. Can you tell me how to package fyne into a static program? Thank you.

**Comment by andydotxyz** [comment]
> However, it is dynamically linked, and it seems that only statically linked can run.

What do you mean only statically linked can run? Fyne apps should all run for the target machines they are built for.

Statically compiling a graphical app completely is a really bad idea. We link in everything we can statically, but if yo my try to compile in the graphics drivers etc you'll make an app that only works on the current computer and graphics adapter configuration...

**Comment by Mr-BeanSir** [comment]
> > However, it is dynamically linked, and it seems that only statically linked can run.
> 
> What do you mean only statically linked can run? Fyne apps should all run for the target machines they are built for.
> 
> Statically compiling a graphical app completely is a really bad idea. We link in everything we can statically, but if yo my try to compile in the graphics drivers etc you'll make an app that only works on the current computer and graphics adapter configuration...

May be a cross compilation tool issue, I am trying a new one. Does fyne support gtk+2? My device seems to only have gtk2+

**Comment by andydotxyz** [comment]
Fyne does not use GTK or any other toolkit libraries.
Like I said above there are 0 runtime dependencies other than a working graphics driver.

**Comment by Mr-BeanSir** [comment]
> Fyne does not use GTK or any other toolkit libraries. Like I said above there are 0 runtime dependencies other than a working graphics driver.

I tried to compile, but encountered an error using cross compilation:
```
#Github. com/go gl/glfw/v3.3/glfw
In file included from/ Glfw/src/international. h: 188,
From/ Glfw/src/context. c: 30,
From/root/go/pkg/mod/github. com/go gl/glfw/v3.3/ glfw@v0.0.0-20221017161538-93cebf72946b /C_ Glfw. go: 4:
./glfw/src/x11_ Platform. h: 33:10: Fatal error: X11/Xlib. h: No such file or directory
33 | # include<X11/Xlib. h>
|^~~~~~~~~~~~
Compilation terminated
#Github. com/go gl/gl/v3.1/gls2
/Root/go/pkg/mod/github. com/go gl/ gl@v0.0.0-20211210172815-726fda9656d6 /V3.1/ges2/procadr. go: 62:18: fatal error: GL/glx. h: No such file or directory
62 | # include<GL/glx. h>
|^~~~~~~~~~
Compilation terminated
```
This is a pre built version of the Toolchain: https://github.com/koreader/koxtoolchain I hope fyne runs on the Kindle. I have installed all the required files but it still reports an error while building. Can you help me?
This is the system I am using `Linux 87f31cbb9b7c 5.10.16.3-microsoft standard WSL2 # 1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_ 64 x86_ 64 x86_ 64 GNU/Linux`, running on Docker

**Comment by andydotxyz** [comment]
Cross-compiling a GUI app is a little complicated as the compiler needs the system libraries for the target system - this is X11 not GTK which is required. You can find more docs at https://developer.fyne.io/explore/compiling.

If this is causing problems for you I would recommend using Fyne-cross instead https://github.com/fyne-io/fyne-cross.
