### ISSUE TITLE
disable -H=windowsgui for windows debug builds

### ISSUE THREAD

**Issue by hismailbulut** [fyne-io/fyne#3604]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Currently fyne build, package and release commands doesn't give access to ldflags and it always sets `-H=windowsgui`. This is not something I want because sometimes I need the console and I need to build with fyne build or package because it adds metadata and this metadata is needed for debug builds also.

This is also related to #3472, static flag is not universal and adding flag to every need will bloat these fyne commands in future. The ldflags is very important for build processes and getting users to change this would really increase these commands usefulness. It is also known by every go developer so we don't need to document it.

You may also want to add `-gcflags`

### Is it possible to construct a solution with the existing API?

This is straightforward to implement and very similar to other flags, especially to `-tags`

### Describe the solution you'd like to see.

We will add a new command to fyne build, package and release commands and this flag will override ldflags of our go build process. Yeah this will override -release but only when it is given. We directly take user supplied ldflags and give it to go build command without changing anything.

**Comment by andydotxyz** [comment]
We are not comfortable adding these publicly as it is not supported on all platforms. If you want to override it just for your development purposes I think you can set `GOFLAGS`.
There were some bugs in how this was handled that were fixed recently so you may need to use the develop branch of Fyne until v2.3.1 is released (soon).

**Comment by hismailbulut** [comment]
Thanks, I can use GOFLAGS with latest release
But there is no way to disable `-H=windowsgui`
It would be nice to just add this only when given the -release flag

**Comment by hismailbulut** [comment]
I am not against this behaviour, I only want it can be disabled because I can't see the debug output while debugging the application. I can't also use direct go build because fyne injects metadata to the application and it is also needed for debugging. Both package and install has -release option and it can be set when this option given.

For -ldflags, I don't have specific reason right now. It has wide range of options which can be useful for debugging and also sometimes needed when we link against c libraries. But it not has to be added if fyne can parse and use it from GOFLAGS in go build.

**Comment by andydotxyz** [comment]
Good answer, thanks.
Go run should still work though, what's the error?

**Comment by hismailbulut** [comment]
As I said go run and fyne package works, there is no error. But I can not use go run because my app mostly relies on the metadata fyne injects. But this time I can't see the debug output because fyne package adds `-H=windowsgui`. In my opinion it should only be added when we supply `-release` to `fyne package` I know this issue is related to ldflags but because fyne now can extract it from GOFLAGS it is not a problem anymore. I don't know your opinion though. I requested -ldflags first because I thought I can override the default ldflags the fyne injects.

**Comment by andydotxyz** [comment]
There is a drawback to both I guess. Without the flags you can't really run it from a start menu or app install... that's why we do it not just for release. "Fyne install" doesn't require release mode, but it does need to be packaged without cmdline.

Enabling raw ldflags leads to apps that we can't package without makefiles and/or makes builds less reproducible which can cause problems too, which is why we have standardised metadata.

Maybe "fyne build" should not enable this, so debugging can be done - but all other package commands do build gui packages as designed?

**Comment by hismailbulut** [comment]
Ok, than maybe we can add a flag something like `-nowindowsgui` to `fyne build` if you like. This will solve this issue.

**Comment by hismailbulut** [comment]
Or as you said it may be default only for fyne build, seems better

**Comment by idy** [comment]
-ldflags is useful to embed some data at compile time, e.g. the build number of the CI system. 

GOFLAGS are space sperated flags, and it does not support for embeding something like: `-ldflags -X main.build_number=123`.

**Comment by andydotxyz** [comment]
As I'm sure you know ldflags don't work on every platform. This is why we have a more complete metadata solution that we recommend using.

https://developer.fyne.io/started/metadata

**Comment by andydotxyz** [comment]
I think this has moved in the direction of being a duplicate to #3781
