### ISSUE TITLE
showing a popup calls MouseOut while moving within the widget.

### ISSUE THREAD

**Issue by kendellfab** [fyne-io/fyne#3608]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

While working on a charting library, I've added a custom widget (a bar type). I want to display the value contained in a bar via a popup. I've added Hoverable to the bar widget. However, while moving the mouse inside of the bar widget, the mouse in and mouse out calls are called consecutively and repeatably without ever leaving the actual widget.

The example can be found here: https://github.com/high-creek-software/fynecharts/blob/main/example/bar.go

### How to reproduce

1. The library with example can be found here: https://github.com/high-creek-software/fynecharts/blob/main/example/bar.go
2. Run this bar.go example and mouse over the bar item.
3. The console output with show mouse in and mouse out logs as well as the popup will flash continually.

### Screenshots

![customwidget-hoverable](https://user-images.githubusercontent.com/1508163/214735887-475b72cf-b2ce-4bac-821f-fa8f8d1dd9a4.gif)

This may look a little weird, but it is just an artifact of ffmpeg converting it to a gif.

### Example code

```go
type bar struct {
	widget.BaseWidget
	canvas fyne.Canvas

	value float64
	pop   *widget.PopUp
}

func (b *bar) MouseIn(event *desktop.MouseEvent) {
	log.Println("Mouse in", event)
	if b.pop != nil {
		return
	}
	if b.canvas != nil {
		lbl := widget.NewLabel(fmt.Sprintf("%.1f", b.value))
		b.pop = widget.NewPopUp(lbl, b.canvas)
		b.pop.ShowAtPosition(event.AbsolutePosition.SubtractXY(0, lbl.MinSize().Height+10))
	}
}

func (b *bar) MouseMoved(event *desktop.MouseEvent) {

}

func (b *bar) MouseOut() {
	log.Println("Mouse out")
	if b.pop == nil {
		return
	}
	b.pop.Hide()
	b.pop = nil
}
```

### Fyne version

2.3.0

### Go compiler version

1.19.5

### Operating system

Linux

### Operating system version

Arch Linux - Kernel 6.1.17

### Additional Information

I also see this on the latest MacOS with apple silicon.

**Comment by andydotxyz** [comment]
You are showing a popup - the overlay will indeed cause a "mouse out" of the layer below it.

Try to avoid popup if you don't want the context to change.

**Comment by kendellfab** [comment]
OK. That does make sense if the popup takes over precedence of the pointer. My hope was to make charts that could be interactive, a popup seeded like a good initial way to do this.  What would you recommend in place of a popup for a similar effect?

**Comment by dweymouth** [comment]
I was looking to do something similar for tool tips - also interested in the recommended alternative to popups.

**Comment by andydotxyz** [comment]
You can draw one item over another without popups - just put them later in the list of items displayed in a container.

**Comment by Bluebugs** [comment]
@andydotxyz I don't think this solution work as the overlay will intercept event. At the application level, I would think you would have to embed everything into a layout where you can then stack your application and then your tooltip. A generic solution that doesn't require an application modification would be the introduction of an overlay that does intercept any input. That could be used by both drag and drop and tooltip.

**Comment by andydotxyz** [comment]
My instruction was to not use overlay - so why is it a concern that overlay will intercept? I don't understand.

**Comment by Bluebugs** [comment]
Sorry, I should have added more context. It was concerning the question for tooltip where you can not have them inside the parent object boundary limit.

**Comment by andydotxyz** [comment]
> Sorry, I should have added more context. It was concerning the question for tooltip where you can not have them inside the parent object boundary limit. 

It can be done that way if your app is able to add a tooltip layer to the canvas. I think that is what others have done...

**Comment by bryantbunderson** [comment]
" I think that is what others have done..." Is there an example of how to add a tooltip to widgets in Fyne? I would love to use them in my desktop apps.
