### ISSUE TITLE
Can the project add some `version` relation constants that make us can use in app

### ISSUE THREAD

**Issue by conero** [fyne-io/fyne#361]
*Sometime I Want add the information about version in my app. But I can't found any const for it， and try `fyne.VERSION` or else. I want add those because I can easy read version from my app but need by watch place what the package installed.*

**Comment by andydotxyz** [comment]
I don't know how this would work. When you compile your application it uses the version of Fyne that you are compiling with. It does not load any libraries at runtime.

If I did not understand can you please explain more what adding this would allow you to do?

**Comment by conero** [comment]
_I mean like this_

![20190714210232](https://user-images.githubusercontent.com/19564821/61184000-e2a20280-a67a-11e9-9a32-42e4853577c4.png)

> Add the fyne version information. So I need the constant by it. Like golang `runtime.Version()`

**Comment by andydotxyz** [comment]
Oh, is this purely for displaying?

**Comment by lucor** [comment]
If you are using Go modules, you'd get it with something like:

```go
func fyneVersion() string {
	bi, ok := debug.ReadBuildInfo()
	if ok {
		for _, mod := range bi.Deps {
			if mod.Path == "fyne.io/fyne" {
				return mod.Version
			}
		}
	}
	return "unknown"
}
```

Credits: inspired by [Caddy server](https://github.com/caddyserver/caddy/blob/master/caddy/caddymain/run.go#L285)

**Comment by conero** [comment]
@andydotxyz yep, I think let help me or the other user to know it. When I have many built-app, I can read some useful information.

**Comment by conero** [comment]
@lucor Thank you man! I am not used to used `Go modules` for reasons, maybe it's time to migrate.
