### ISSUE TITLE
crashed when minimize a window which contains a entry?

### ISSUE THREAD

**Issue by BabySid** [fyne-io/fyne#3611]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

panic: runtime error: slice bounds out of range [:-416]

goroutine 18 [running, locked to thread]:
golang.org/x/image/vector.(*Rasterizer).setUseFloatingPointMath(0xc00113a9c0, 0x1?)
        C:/Users/admin/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:143 +0x125
golang.org/x/image/vector.(*Rasterizer).Reset(0x10?, 0xc001493580?, 0x7ff7125442d0?)
        C:/Users/admin/go/pkg/mod/golang.org/x/image@v0.0.0-20220601225756-64ec528b34cd/vector/vector.go:123 +0x65
github.com/srwiley/rasterx.(*ScannerGV).SetBounds(...)
        C:/Users/admin/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20210519020934-456a8d69b780/scan.go:166
github.com/srwiley/rasterx.NewScannerGV(0xd?, 0x0?, {0x7ff712dc36a8?, 0xc0000bcc40}, {{0x0?, 0xc001493600?}, {0x7ff712313651?, 0x0?}}) 
        C:/Users/admin/go/pkg/mod/github.com/srwiley/rasterx@v0.0.0-20210519020934-456a8d69b780/scan.go:173 +0x69
fyne.io/fyne/v2/internal/painter.DrawRectangle(0xc000400ae0, 0x40400000, 0xc001493668)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/draw.go:90 +0x16c
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlStrokedRectTexture(0xc0000bc140, {0x7ff712dc60e0?, 0xc000400ae0?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:156 +0xa5
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlRectTexture(0x7ff712c5c800?, {0x7ff712dc60e0?, 0xc000400ae0?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:146 +0x4e
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc0000bc140, {0x7ff712dc60e0, 0xc000400ae0}, 0xc001493830)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc0000bc140, {0x7ff712dc60e0?, 0xc000400ae0?}, 0xc001493838?, {0x12313651?, 0x7ff7?}, {0x0?, 0x0?}, {0x1493850?, 0xc0?}, ...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:134 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawRectangle(0xc0000bc140, 0xc000400ae0, {0x3d400?, 0xc0?}, {0x122d478a?, 0x7ff7?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:104 +0x17e
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0x128686f0?, {0x7ff712dc60e0?, 0xc000400ae0?}, {0x122dc0bd?, 0x7ff7?}, {0x12c118c0?, 0x7ff7?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/draw.go:86 +0x16d
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0x7ff7122de37f?, {0x7ff712dc60e0, 0xc000400ae0}, {0x122dc0bd?, 0x7ff7?}, {0x12c118c0?, 0x7ff7?}) 
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/painter/gl/painter.go:84 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0x7ff712543d91?, {0x1254441c?, 0x7ff7?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:284 +0x102
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0x7ff712dc60e0?, 0xc000400ae0}, {0x400ae0?, 0xc0?}, {0xb81e0?, 0xc0?}, {0xa24e2acd?, 0xe?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff712dc60e0, 0xc000400ae0}, 0x0, {0x7ff712dc65c0, 0xc0000b81e0}, {0x1493b18?, 0xc0?}, {0x0?, 0x0?}, {0x40c00000?, ...}, ...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:169 +0x29b
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff712dc65c0, 0xc0000b81e0}, 0x0, {0x7ff712dc5e40, 0xc0000ac050}, {0x12c2fce0?, 0x7ff7?}, {0x1947250?, 0xc0?}, {0xf09fb0?, ...}, ...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x7ff712dc5e40, 0xc0000ac050}, 0x0, {0x0, 0x0}, {0x12313651?, 0x7ff7?}, {0x0?, 0x0?}, {0x1493c88?, ...}, ...)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:190 +0x41d
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x7ff712dc5e40?, 0xc0000ac050?}, 0xc0000841a0?, 0x200000003?) 
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc0011311c0, 0xc001493dd0, 0xc001493da0)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000ba000, 0xc001493da0?, 0x7ff712839d06?)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc0000ba000, {0x0?, 0x0?})
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/canvas.go:296 +0xfe
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:203 +0x8f
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x7ff712818226?, 0xc001493e80)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000ba000?, 0x0?)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:194 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*window).platformResize.func1()
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window_notlinux.go:17 +0x48
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc001493f90?, 0xc001a610a0)
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:903 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:234 +0x13b
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        C:/Users/admin/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:226 +0xea

### How to reproduce

1. run the code as below
2. run app and click the minimize button of window

### Screenshots

![image](https://user-images.githubusercontent.com/6658943/215302106-55f1fdf2-f395-45b2-83de-ddefe665d098.png)

### Example code

```
type Data struct {
	Name binding.String
	ID   string
}

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	listBinding := binding.NewUntypedList()
	list := widget.NewListWithData(
		listBinding,
		func() fyne.CanvasObject {
			return widget.NewLabel("")
		},
		func(data binding.DataItem, item fyne.CanvasObject) {
			o, _ := data.(binding.Untyped).Get()
			d := o.(*Data)
			item.(*widget.Label).Bind(d.Name)
		},
	)

	curID := -1
	list.OnSelected = func(id widget.ListItemID) {
		curID = id
		fmt.Println(curID)
	}

	b := widget.NewButton("button", func() {
		str := binding.NewString()
		str.Set(fmt.Sprintf("Name_%s", time.Now()))
		data := &Data{Name: str}
		listBinding.Append(data)
		list.Select(listBinding.Length() - 1)
	})

	t := widget.NewEntry()
	w.SetContent(
		container.NewBorder(t, b, nil, nil, list),
	)

	w.CenterOnScreen()
	w.Resize(fyne.NewSize(400, 300))
	w.ShowAndRun()
}
```

### Fyne version

 fyne.io/fyne/v2 v2.3.0

### Go compiler version

go 1.19

### Operating system

Windows

### Operating system version

Windows 10

**Comment by BabySid** [comment]
Not sure if it is the same issue as https://github.com/fyne-io/fyne/issues/3553 https://github.com/fyne-io/fyne/issues/3552

**Comment by BabySid** [comment]
Confirm. 

Ths code as above run OK with fyne.io/fyne/v2 v2.2.0

**Comment by andydotxyz** [comment]
At a glance it looks identical to #3553, what makes you think they are different?

**Comment by BabySid** [comment]
> At a glance it looks identical to #3553, what makes you think they are different?

I am not sure... It may be due to different containers involved (border vs vbox)

if they have the same root cause, i'll close this issue. :)
