### ISSUE TITLE
Memory leak with glfw desktop driver

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#3616]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

This is here to not loose track of it, but currently once a canvas object is added to a canvas, it end up in the canvases map in fyne/internal/cache/canvases.go . There is no logic in place to remove this canvas object from that map. It means that every object and there resource ever created once associated with a canvas can not be GC from memory.

### How to reproduce

Any application will show this problem, but most of them would not be significantly impacted by it as Fyne recycle canvas object so effectively that we normally do not create and delete object that much.

### Example code

Use fyne_demo windows to create and delete window along with pprof to track memory allocation.

### Fyne version

2.3.0

### Go compiler version

1.19.4

### Operating system

Android

### Operating system version

Windows, Linux, FreeBSD, MacOS

### Additional Information

The main challenge is on detecting when an object is removed from the slice of a container. A first step would be to at least delete all the object associated with the canvas of a window that get closed, but as I expect most Fyne application this day to be single window, it won't be that much of a pay of.

To fix it properly, you would have to be able to do a diff between the previous slice of object associated with a container and the new slice. Then you would be able to do a "diff" between the two and remove the deleted object.

**Comment by dweymouth** [comment]
> There is no logic in place to remove this canvas object from that map. It means that every object and there resource ever created once associated with a canvas can not be GC from memory.

This seems like a pretty big issue. Will this impact apps that create and release a lot of widgets (e.g. because the user can cycle through different pages/views), or does Fyne re-use widgets or renderers when application code calls a widget constructor?

**Comment by andydotxyz** [comment]
It's not as bad as it sounds because overall we re-use when we can. However this is certainly an area we need to work on.
To some extent it depends on how your widgets are being released.
Having a container full of items and disposing them by setting `Containers.Objects = nil` is the main situation that we are not currently catching. The other, which Cedric mentions, relates to windows - if you create and close windows a lot it might be better to re-use (with Hide and Show) instead - until we address this issue.

**Comment by andydotxyz** [comment]
Overall re-use where it makes sense and configuring existing widgets over replacing them is highly recommended from a CPU point of view as well, it makes a big difference and is why the `List`, `Tree` and `Table` have the re-use model that they do instead of just creating items for every node.

**Comment by dweymouth** [comment]
If the Remove/RemoveAll method is called on the container as opposed to just setting the slice directly, does that (at least partially) mitigate this issue?

**Comment by andydotxyz** [comment]
> If the Remove/RemoveAll method is called on the container as opposed to just setting the slice directly, does that (at least partially) mitigate this issue?

It certainly should. But perhaps @Bluebugs found that we were missing that code?

**Comment by Bluebugs** [comment]
Indeed, it is not currently possible even when using Remove/RemoveAll to have the canvas know that those objects were removed.

**Comment by dweymouth** [comment]
Oof.. do you have any ETA on a fix for this? (next release?) No one is really using my app yet (except me :) so it doesn't matter that much but I'm wondering if I should add widget pooling to my app vs waiting for a fix on this issue. I have noticed the memory use creep up over time.

**Comment by andydotxyz** [comment]
Hopefully we can address the container issues in the next release - it should be just internal changes. Along with the window close freeing version of the bug as well.
We are shaping up a bugfix release right now so maybe we can work to get it in...

**Comment by andydotxyz** [comment]
Upon further inspection this cache will be cleared by a timeout when objects are not referenced for a time period (currently 1 minute).
So there is much less of a problem here than we thought.
I will, however, be proceeding with the fixes to clear the cache sooner when we know an object is not being used.

**Comment by andydotxyz** [comment]
> There is no logic in place to remove this canvas object from that map. It means that every object and there resource ever created once associated with a canvas can not be GC from memory.

I have determined that this is not true.
* Windows closing will call `cache.CleanCanvas()` which removes all items from the map.
* Items that are no longer needed for any other reason will be removed due to the timeout code above.

Closing as not an issue.
