### ISSUE TITLE
Add internal shadow object to keep internal state associated with canvas object

### ISSUE THREAD

**Issue by Bluebugs** [fyne-io/fyne#3617]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

A few open issue require to be able to maintain internal state as a copy of the last Refresh call of the exported state. This include fixing race condition (to have a different data being accessed while rendering/checking input), memory leak both with the texture cache and the canvas object cache.

Maintaining an internal state associated with the canvas object would make it easier to keep all the information related to the rendering of an object. Ideally this should not be requiring to expose the painter internal.

### Is it possible to construct a solution with the existing API?

The canvas and painter are insulated from the canvas object through an interface. There is no API for the canvas to attach an internal data to a canvas object or the reverse for a canvas object to find its internal data as seen from the painter.

I can see two possible way to implement a solution to this problem. Either the canvas object get the data attached from the canvas, or the canvas object request the associated data from the canvas. The code that call request to the canvas to get the associated data, doesn't need to be in the Refresh code of the widget, but at minima it need to be triggered every time canvas.Refresh is called and make sure that the data in the object are the one set on the internal state.

Considering that the data to associate will be different per class of widget and we likely do not want to multiply entry point, we will likely have to rely on interfaces. As resolving interfaces for each Refresh will be in the hot path, it would be best to move that out of the way.

Also it is to be noted that call to `canvasObject.Refresh()`, even if the documentation says you must call it is not enforced and only `canvas.Refresh()` has been enforced in practice.

### Describe the solution you'd like to see.

Most of this problem are internal to Fyne, but need to be expose in some form of exported API due to crossing module boundary. With all of that in mind, I do propose to add the following to the fyne.CanvasObject interface:

```
// CanvasRegister is called by the canvas when a canvas object is added to a canvas
CanvasRegister(canvas fyne.Canvas, internal interface{})
// CanvasUnregister is called by the canvas when a canvas object is removed from a canvas
CanvasUnregister()
// CanvasSynchronize is called by the canvas when an object Refresh function is called and the internal state given during register must be updated
CanvasSynchronize()
// CanvasActive return the currently active canvas associated with an object
CanvasActive() fyne.Canvas
```

This would only be called by the canvas for type that get painted and for WidgetRenderer. The internal interface{} will be converted to a known internal state by casting once on CanvasRegister and Synchronize will know exactly what to synchronize as the code will be located in the canvas object. The painter, render thread and input would then operate on the internal state data only.

**Comment by andydotxyz** [comment]
I don't think this belongs as a feature request. It is a potential solution to solve an internal issue. It seems like the proposals process would be more appropriate.

**Comment by Bluebugs** [comment]
Are you referring to the fyne-io/proposal repository? They did seems used for more user facing features actually and to solve complex problems. If you think this should be discussed there, I can make a PR there.

**Comment by andydotxyz** [comment]
Haha yes, as this is related to race conditions in the toolkit I am not sure of much more complex problems, it seems perfect.
I expect that it will take many iterations to get to the best solution so that process seems perfect.
