### ISSUE TITLE
Tree Widget not refreshing when .Refresh() is called after updating the backing store. 

### ISSUE THREAD

**Issue by edwinclement08** [fyne-io/fyne#3618]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I would like to have a navigation panel much like fyne_demo package where I can dynamically add and remove entries.
To this end, I copied the source from [fyne_demo/main.go](https://github.com/fyne-io/fyne/blob/9b5a176fe1dc80beae72a3074d0d5cd2b409637c/cmd/fyne_demo/main.go#LL132) and added code for inserting new labels.

I am faced with this baffling issue that the Tree is not updating when I press the `Add new leaf Node`. 
Meanwhile, if I switch tabs to Welcome2, the tree is updated.
It also updates If I switch the theme of the app from Light to dark.

### How to reproduce

1. Go to Welcome Tab
2. Press `Add new leaf Node`
3. New node is not added
4. Switch Tabs
5. Viola!! Tab appears magically

### Screenshots

![image](https://user-images.githubusercontent.com/9532892/215568967-fc4cc140-7863-403f-8394-139a9064d67a.png)
![image](https://user-images.githubusercontent.com/9532892/215569014-6d9034b2-374d-446a-98be-abfb8f2aceb9.png)
![image](https://user-images.githubusercontent.com/9532892/215569042-f45452a1-4e87-42d6-bba2-5cf482dd6d42.png)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type Tutorial struct {
	Title, Intro string
	View         func(w fyne.Window, f func()) fyne.CanvasObject
	SupportWeb   bool
}

func unsupportedTutorial(t Tutorial) bool {
	return !t.SupportWeb && fyne.CurrentDevice().IsBrowser()
}

var (
	// Tutorials defines the metadata for each tutorial
	Tutorials = map[string]Tutorial{
		"welcome":  {"Welcome", "", welcomeScreen, true},
		"welcome2": {"Welcome2", "", welcomeScreen, true},
	}
	// TutorialIndex  defines how our tutorials should be laid out in the index tree
	TutorialIndex = map[string][]string{
		"": {"welcome", "welcome2"},
	}
)

func testScreen(_ fyne.Window, addToTutorials func()) fyne.CanvasObject {
	return container.NewCenter(container.NewVBox(
		widget.NewLabelWithStyle("Welcome to the test facility", fyne.TextAlignCenter, fyne.TextStyle{Bold: true}),
	))
}

func welcomeScreen(win fyne.Window, addToTutorials func()) fyne.CanvasObject {
	return container.NewCenter(container.NewVBox(
		widget.NewLabelWithStyle("Welcome to the Fyne toolkit demo app", fyne.TextAlignCenter, fyne.TextStyle{Bold: true}),
		widget.NewButton("Add new leaf Node", func() {
			addToTutorials()
			win.Content().Refresh() // a hack, need to figure out a better way
		}),
		widget.NewLabel(""), // balance the header on the tutorial screen we leave blank on this content
	))
}

var CountAdds int = 0

func addToTutorials() {
	if CountAdds == 0 {
		fmt.Println("Updating tutorials")
		Tutorials["Added"] = Tutorial{"Test", "", testScreen, true}
		TutorialIndex[""] = append(TutorialIndex[""], "Added")
		MainTree.Refresh()
		fmt.Println(Tutorials)
		fmt.Println(TutorialIndex)
		CountAdds += 1
	}
}

var MainTree widget.Tree
var MainWindow fyne.Window

func makeNav(setTutorial func(tutorial Tutorial, addtoTutorials func()), loadPrevious bool) *widget.Tree {
	tree := widget.Tree{
		ChildUIDs: func(uid string) []string {
			return TutorialIndex[uid]
		},
		IsBranch: func(uid string) bool {
			children, ok := TutorialIndex[uid]

			return ok && len(children) > 0
		},
		CreateNode: func(branch bool) fyne.CanvasObject {
			return widget.NewLabel("Collection Widgets")
		},
		UpdateNode: func(uid string, branch bool, obj fyne.CanvasObject) {
			t, ok := Tutorials[uid]
			if !ok {
				fyne.LogError("Missing tutorial panel: "+uid, nil)
				return
			}
			obj.(*widget.Label).SetText(t.Title)
			if unsupportedTutorial(t) {
				obj.(*widget.Label).TextStyle = fyne.TextStyle{Italic: true}
			} else {
				obj.(*widget.Label).TextStyle = fyne.TextStyle{}
			}
		},
		OnSelected: func(uid string) {
			if t, ok := Tutorials[uid]; ok {
				if unsupportedTutorial(t) {
					return
				}
				// a.Preferences().SetString(preferenceCurrentTutorial, uid)
				setTutorial(t, addToTutorials)
			}
		},
	}
	MainTree = tree

	return &tree
}

func setupConfigWindow(window fyne.Window) {
	content := container.NewMax()
	title := widget.NewLabel("Component name")
	intro := widget.NewLabel("An introduction would probably go\nhere, as well as a")
	intro.Wrapping = fyne.TextWrapWord
	setTutorial := func(t Tutorial, addToTutorials func()) {
		title.SetText(t.Title)
		intro.SetText(t.Intro)

		content.Objects = []fyne.CanvasObject{t.View(window, addToTutorials)}
		content.Refresh()
	}
	tutorial := container.NewBorder(
		container.NewVBox(title, widget.NewSeparator(), intro), nil, nil, nil, content)
	split := container.NewHSplit(makeNav(setTutorial, true), tutorial)
	split.Offset = 0.2
	window.SetContent(split)
	window.Resize(fyne.NewSize(640, 460))
	window.ShowAndRun()
}

func main() {
	a := app.NewWithID("com.edwinclement08.fyne-tree-bug")
	w := a.NewWindow("Fyne Tree Bug")
	MainWindow = w

	setupConfigWindow(w)
}
```

### Fyne version

2.3.0

### Go compiler version

1.19.5

### Operating system

Windows

### Operating system version

Windows 11

### Additional Information

I have tried refreshing `w.Content().Refresh()` and that doesn't work either.
I suspect I have written something that makes the refresh read from the cache. This problem seems reminiscent to React state updates not reflecting in UI

**Comment by edwinclement08** [comment]
After investigating a lot, turns out the problem is that the Tree Widget should be called via `widget.NewTree` and NOT like `tree := widget.Tree`

I don't know the exact difference here, but that's the issue.
I still decided to put this issue up for others to find the solution until fyne_demo is updated to use `NewTree`.

**Comment by andydotxyz** [comment]
Both should work. The problem seems to be you are calling it `widget.Tree` instead of `*widget.Tree` (which is what is passed back from the constructor function.

This often causes a problem if passing it around as you'll end up making copies (pass-by-value).
