### ISSUE TITLE
Are you seriously spamming my inbox from GitHub ?!

### ISSUE THREAD

**Issue by arobase-che** [fyne-io/fyne#3620]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I got an email from Andy Williams for help with the project only because I starred the project.
I never subscribe to any of your mailing list.

Please, explain.

### How to reproduce

You can't I guess.

### Screenshots

![2023-02-01-163203_1848x1034_scrot](https://user-images.githubusercontent.com/2202307/216087714-a453d15f-5cd8-423e-8acc-000113554989.png)

### Example code

You are spamming, there is no code.

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system

macOS

### Operating system version

iDontcare version fu

**Comment by arobase-che** [comment]
Quick reply from @andydotxyz:

![2023-02-01-164548_1784x1014_scrot](https://user-images.githubusercontent.com/2202307/216091833-86478ac3-f16d-4755-82fb-857d887dd6eb.png)

Will close the issue.

**Comment by andydotxyz** [comment]
I'm really sorry you were not happy to get the email. I was looking to get more feedback on project direction.
Clearly this was not the best way to go about it... Thanks for your understanding.
