### ISSUE TITLE
Fishing attempt or mail campaign gone wrong?

### ISSUE THREAD

**Issue by zuckschwerdt** [fyne-io/fyne#3622]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I just received a mail claiming to be a "Fyne Heros" badge. Supposedly sent from Andrew?
The linked github organization (https://github.com/FyneHeros) does not seem related to Fyne.
I would have expected to see @andydotxyz in that org already.

A fishing attempt or mail campaign gone wrong?

In case of the later, I have never used or even heard of Fyne -> where did you scape my username or mail from?

### How to reproduce

-

### Screenshots

```
Hi there Fyne developer,
Thanks so much for showing an interest in the Fyne project on GitHub, we re=
ally appreciate every developer that uses the toolkit. I hope you don=E2=80=
=99t mind me reaching out to say thanks and see if you have a moment to spa=
re to help make the project better.
The purpose of this email is to ask a simple question:
What can we do to improve Fyne?
As the founder of the Fyne project I appreciate you taking the time to help=
 us out! To share my thanks I would like to invite you to the " https://git=
hub.com/FyneHeros Fyne Heros " organisation which means you get this shiny =
badge on your GitHub profile!

Many thanks for your time and have a great day, Andrew

Don't want to stay in touch? https://zcv4-zcmp.maillist-manage.eu/ua/optout...
```

### Example code

-

### Fyne version

-

### Go compiler version

-

### Operating system

Android

### Operating system version

-

**Comment by zuckschwerdt** [comment]
Thanks for the feedback. To clarify: the mail looked scammy comming from an untrusted sender and containing only obfuscated (tracking) links. Didn't see you or any official participation in the org – might have been my mistake.

I have never interacted with Fyne, not even sure what it is (a ui framework or widget toolkit or theme layer?) and I never used Go anyway. But I might have contributed to projects built in Go, maybe you scraped 3rd party projects?

Perhaps keep this issue open for a few days to let other people confused by this know. Resolved for me, though.

**Comment by andydotxyz** [comment]
Thanks for the info. It's a real puzzle as I didn't scrape any 3rd parties or follow any dependencies.
My best guess is that you collaborated with someone who did star Fyne and somehow I read the wrong email :(.

**Comment by ripienaar** [comment]
Here's a basic rule about appologising "I am sorry you feel this way" is not an appology.

You have broken GitHub API rules and EU opt-in rules.  As someone formerly from the EU and currently from a country with strong privacy rules you are well aware of this.  Responses here and those sent in emali pointing out this issue has gone very short of actually owning the mistake.

**Comment by andydotxyz** [comment]
Hi @ripienaar, I don't think the context you pasted was here on GitHub?
I believe you are referring to my inability to apologise for the email that I sent. We already are having a conversation about this over email - perhaps we can conclude it there, to avoid punishing the community for my mistake.

**Comment by Jacalz** [comment]
Closing this now. I believe this has been dealt with.
