### ISSUE TITLE
no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

### ISSUE THREAD

**Issue by BertBR** [fyne-io/fyne#3625]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have the same problem reported on issue [#2297](https://github.com/fyne-io/fyne/issues/2297). But can't solve it.

My  `.zshrc` has the following envs
```bash
#Android NDK
ANDROID_NDK_HOME=$HOME/Android/ndk-bundle
PATH=$PATH:$ANDROID_NDK_HOME
```

When I tried to run the following:
`fyne package -os android -appID com.example.myapp -icon icon.png`

I have that error message "no Android SDK found..."

When i run `ls $ANDROID_NDK_HOME` i got correct files (like screenshot above)

### How to reproduce

1. Run `fyne package -os android -appID com.example.myapp -icon icon.png`

### Screenshots

![Screenshot_20230201_233948](https://user-images.githubusercontent.com/29619309/216217822-2791ffb0-a682-4c9b-a701-08fffdf1beab.png)

### Example code

there`s no code necessary to reproduce this error

### Fyne version

2.3.0

### Go compiler version

1.19.5

### Operating system

Linux

### Operating system version

Linux fedora 6.1.7-200.fc37.x86_64

**Comment by andydotxyz** [comment]
Out of interest did you find the cause which led you to closing the ticket?

**Comment by BertBR** [comment]
> Out of interest did you find the cause which led you to closing the ticket?

Yes. Sorry!
For some unknown reason, even when I applied my environment variables in my `.zshrc` and reloading my zsh with `source ~/.zshrc`, it's not worked. So, I just ran `export ANDROID_NDK_HOME=$HOME/Android/ndk-bundle` and it works.

**Comment by andydotxyz** [comment]
Strange, but I'm glad you got it sorted.

**Comment by vladislav14141** [comment]
I have same problem. I download NDK from https://formulae.brew.sh/cask/android-ndk. I make `export ANDROID_NDK_HOME="$HOMEBREW_PREFIX/share/android-ndk"` and it fix my problem.
