### ISSUE TITLE
Fyne install/package fails when build constraints are used 

### ISSUE THREAD

**Issue by rew1nter** [fyne-io/fyne#3626]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Putting this at the top of the file `//go:build linux && darwin` throws this error if you try to package or install:
```
runtime.main_main·f: function main is undeclared in the main package

error building application: exit status 2
```
Things work as expected again when you remove the build constraint

### How to reproduce

1. Create a fyne app
2. Put a build constraint and try to build
3. It should fail

### Example code

```go
//go:build linux && darwin
package main

func main() {
.....

```

### Fyne version

v2.3.0

### Go compiler version

go1.19.5 linux/amd64

### Operating system

Linux

### Operating system version

Manjaro KDE

**Comment by andydotxyz** [comment]
I think you have a mistake in the build header - there is no system that matches "linux && darwin". Perhaps you mean "linux || darwin"?

**Comment by Jacalz** [comment]
I just want to quickly say that if this wasn’t incorrectly configured build constraints, it would likely have been a Go compiler bug and not a problem on our end. It is the compiler that handles build constraints :)
