### ISSUE TITLE
panic: runtime error: slice bounds out of range when pressing full screen button

### ISSUE THREAD

**Issue by Aukstkalnis** [fyne-io/fyne#364]
D:\Projects\Go_Projects\GoPath\src\fyne.io\fyne\cmd\fyne_demo>fyne_demo.exe
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
image/draw.drawGlyphOver(0xc000066f00, 0xfffffffffffffffe, 0xfffffffffffffff1, 0x0, 0xfffffffffffffffe, 0xc00063c050, 0xc000066f40, 0x0, 0xec4)
        C:/go/src/image/draw/draw.go:484 +0x2b4
image/draw.DrawMask(0x98ca20, 0xc000066f00, 0xfffffffffffffffe, 0xfffffffffffffff1, 0x0, 0xfffffffffffffffe, 0x98c1a0, 0xc00063c050, 0x0, 0x0, ...)
        C:/go/src/image/draw/draw.go:150 +0xb8b
fyne.io/fyne/vendor/golang.org/x/image/font.(*Drawer).DrawString(0xc000537568, 0xc0003d8a80, 0xc)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/vendor/golang.org/x/image/font/font.go:178 +0x167
fyne.io/fyne/internal/driver/gl.(*glCanvas).newGlTextTexture(0xc000128000, 0x98e7a0, 0xc000093030, 0xc0007ce790)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/gl_common.go:127 +0x383
fyne.io/fyne/internal/driver/gl.getTexture(...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/gl_common.go:35
fyne.io/fyne/internal/driver/gl.(*glCanvas).drawText(0xc000128000, 0xc000093030, 0x121, 0x3d, 0x381, 0x231)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/draw.go:156 +0x2a8
fyne.io/fyne/internal/driver/gl.(*glCanvas).drawObject(0xc000128000, 0x98e7a0, 0xc000093030, 0x121, 0x3d, 0x381, 0x231)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/draw.go:181 +0x5c5
fyne.io/fyne/internal/driver/gl.(*glCanvas).paint.func1(0x98e7a0, 0xc000093030, 0x121, 0x3d, 0x0, 0x0, 0x7fffffff, 0x7fffffff, 0xc0003f4a20)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/canvas.go:279 +0x1eb
fyne.io/fyne/internal/driver.walkObjectTree(0x98e7a0, 0xc000093030, 0x98eb60, 0xc0003f4a20, 0x117, 0x33, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:52 +0x2aa
fyne.io/fyne/internal/driver.walkObjectTree(0x98eb60, 0xc0003f4a20, 0x98e440, 0xc0003e6e10, 0x117, 0x33, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:59 +0x1d3
fyne.io/fyne/internal/driver.walkObjectTree(0x98e440, 0xc0003e6e10, 0x98e860, 0xc000116ae0, 0x73, 0x33, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:59 +0x1d3
fyne.io/fyne/internal/driver.walkObjectTree(0x98e860, 0xc000116ae0, 0x98ee00, 0xc0003e6e60, 0xa, 0x33, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:59 +0x1d3
fyne.io/fyne/internal/driver.walkObjectTree(0x98ee00, 0xc0003e6e60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:59 +0x1d3
fyne.io/fyne/internal/driver.WalkObjectTree(0x98ee00, 0xc0003e6e60, 0xc000537bf8, 0xc000537be8, 0x3f8101013f018284)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/util.go:25 +0x84
fyne.io/fyne/internal/driver/gl.(*glCanvas).walkTree(0xc000128000, 0xc000537bf8, 0xc000537be8)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/canvas.go:296 +0x57
fyne.io/fyne/internal/driver/gl.(*glCanvas).paint(0xc000128000, 0x381, 0x231)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/canvas.go:289 +0xcd
fyne.io/fyne/internal/driver/gl.(*gLDriver).runGL.func1()
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/loop.go:108 +0x90
fyne.io/fyne/internal/driver/gl.(*window).runWithContext(0xc0000de240, 0xc000537d50)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/window.go:1009 +0x3f
fyne.io/fyne/internal/driver/gl.(*gLDriver).runGL(0xc000060600)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/loop.go:101 +0x407
fyne.io/fyne/internal/driver/gl.(*gLDriver).Run(0xc000060600)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/driver.go:77 +0x4a
fyne.io/fyne/internal/driver/gl.(*window).ShowAndRun(0xc0000de240)
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/internal/driver/gl/window.go:354 +0x5f
main.main()
        D:/Projects/Go_Projects/GoPath/src/fyne.io/fyne/cmd/fyne_demo/main.go:67 +0x874

**Comment by andydotxyz** [comment]
Does this happen every time or just some times?
Can you provide more information about the computer and version of Windows you are using?

**Comment by Aukstkalnis** [comment]
My OS: windows 10 Version 10.0.17134 Build 17134
It happen once. I didn't try again.

**Comment by andydotxyz** [comment]
Can you confirm the version of Fyne you are using? We fixed a similar issue in the 1.1 release so it may be an old issue. Thanks

**Comment by andydotxyz** [comment]
It looks like you were working with an old version of the `develop` branch.
Is it possible to test with an updated version so we can see if the problem still exists?

**Comment by Aukstkalnis** [comment]
Ok, since I am not shure about the version that I used, I think we can close this case. If I will be able reproduce this, then we can reopen this.
