### ISSUE TITLE
new container tabs

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3647]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

It is not convenient to use tabs for security tool development using fyne. I hope the author can provide tabs that belong to the java swing or javaFX framework in the next version.

### Describe the solution you'd like to see.

this is a java swing tabs
![111](https://user-images.githubusercontent.com/78897251/217970724-afadaaed-87ea-4bd5-bbcf-dd4193becc18.PNG)

**Comment by andydotxyz** [comment]
How is this different to the DocTabs container?

**Comment by hq-zhonger** [comment]
Sorry, I’m sorry to bother you again, although apptabs and doctabs often look good, but how can I cancel the red line under the tabs
![222](https://user-images.githubusercontent.com/78897251/218113937-10a36792-39b3-4607-a257-baf3f3a2ddaa.PNG)

**Comment by andydotxyz** [comment]
> Sorry, I’m sorry to bother you again, although apptabs and doctabs often look good, but how can I cancel the red line under the tabs

That is what the widgets look like - it shows the user which tab is selected.
If you want a tab widget that looks different you can extend the widget and provide your own `WidgetRenderer` from the `CreateRenderer` call.
