### ISSUE TITLE
API request: add OnChangeEnded API to the Slider widget

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3652]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

In some apps it is necessary to differentiate ValueChanged events to a slider that are occurring during a drag action, vs a ValueChanged that occurs at the end of a user interaction, in order to trigger backend logic only in the 2nd case.

### Is it possible to construct a solution with the existing API?

Yes, by extending Slider, overriding `DragEnd` (and later overriding `Tapped` as well once tap-to-set support lands in the slider widget), to keep track of when the user interaction ends yourself

### Describe the solution you'd like to see.

A new callback API to the slider widget `OnChangeEnded func()` which allows application code to be notified when a user interaction that is changing the slider value has completed. Maybe the signature should be `OnChangeEnded func(float)` where the last set value is passed as well

**Comment by dweymouth** [comment]
Actually maybe we should consider adding an `OnChangeStarted func()` as well - a callback invoked when a single user interaction begins that may last for some time and change the value multiple times. I had forgot that I had custom logic in my extended slider to handle this as well, since I needed to stop automatically updating the play time label while a slider drag was going on

**Comment by Jacalz** [comment]
I have actually thought about if we instead should try to change the behavior to trigger the `OnChanged` at the drag end. My personal opinion is that the user hasn't actually "selected" a value until the drag has ended. I not so sure that adding more `OnChangedXyz` functions is the best option.

**Comment by dweymouth** [comment]
In some cases it's useful to respond to valueChanged during the drag. e.g. a color slider, or in my app's case, a volume slider that can update the volume during a drag. (my seek slider only invokes the action on drag end though). Andy and I discussed this a bit in Discord

**Comment by Jacalz** [comment]
Hmm. Interesting. I have never personally found any use for having it update continuously but your usage seems very sensible. Having a `OnChangeEnded func(float)` seems like it could be a sensible addition in that case :)

**Comment by Jacalz** [comment]
I'm also adding the `performance` tag as this can be useful for developers to avoid having many `OnChanged` calls when it isn't necessary to do so.

**Comment by andydotxyz** [comment]
Landed on `develop` thanks @dweymouth
