### ISSUE TITLE
Support extending containers

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#3657]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Currently people expect containers to support being extended just like widgets, but it results in content not being visible.

### Is it possible to construct a solution with the existing API?

No

### Describe the solution you'd like to see.

Support extending the container type to add custom functionality (like Tapping etc).

marked as 3.0 as it will require API breaks

**Comment by andydotxyz** [comment]
I have explored this locally and found that it’s not possible without API changes (as the current container definition includes Field access that would need moved to an interface.

**Comment by Jacalz** [comment]
Is it that desirable to be able to extend containers?  I kind of think that this change isn't quite worth it and that we instead should move the idea of https://github.com/fyne-io/fyne-x/pulls?q=is%3Apr+is%3Aclosed into the standard Fyne domain instead of being part of extras.

**Comment by andydotxyz** [comment]
I think that might be the wrong link?

**Comment by Jacalz** [comment]
Yep. Strange. I meant this one: https://github.com/fyne-io/fyne-x/pull/37
The wrappers for making containers (or other widgets) implement specific interfaces works well in my opinion.

**Comment by andydotxyz** [comment]
Except what you linked does not work for containers, only widgets.

**Comment by Jacalz** [comment]
It becomes widgets at the end, yes, but the functions still take in CanvasObjects so it should be possible to do it for containers as well.

I'm not sold on the idea of extending. It just feels like a lot of work and a lot of deprecation as well as changes for something that should be done with a widget and a simple renderer instead.

If we make containers extendable then people are probably going to want canvas primitives extendable as well (expecting everything to be extendable). On top of that, I am also not entirely happy the ExtendBaseWidget() calls (we would probably need something similar here) idea but I can't come up with any better solution.

Sorry for the long and rambling message. Just trying to get my opinions down :)

**Comment by Jacalz** [comment]
In short, I just don't think it is worth it. I'd prefer that we spend the time making widget creation and extension simpler instead of making the lower parts like containers extendable as well.

**Comment by andydotxyz** [comment]
Yeah that's fair. The wrappers work on more varied inputs than I realised too.
