### ISSUE TITLE
add polygon and bezier curve to canvas draw functions 

### ISSUE THREAD

**Issue by chewie54** [fyne-io/fyne#366]
Can polygon and bezier curve be added to the draw canvas items?   

Thanks,
Dan Fabrizio

**Comment by andydotxyz** [comment]
There is no reason that they could not be added, we just have not had much demand for them.

If you want to use these elements in your application then you can always use a 2D drawing package to create a Go image in memory and use NewImageWithImage or NewRasterWithImage to show it in your application.

**Comment by windexlight** [comment]
I second the request for polygon and bezier curve to be added, and would like to suggest that circular arc would be helpful also.

**Comment by andydotxyz** [comment]
There is more detail in the more recent request #856, closing this as a duplicate
