### ISSUE TITLE
List not updating correctly

### ISSUE THREAD

**Issue by jojosboomstick** [fyne-io/fyne#3664]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Hello.
I'm trying to make a list with alternating colors. Almost done, but there is a problem. If you change the size of the window, the colors start to appear in the wrong order. How can I solve this problem or is it just not a viable solution?
Thank you.

### How to reproduce

1. Resize window

### Screenshots

![screenshot](https://user-images.githubusercontent.com/66790655/218957044-8f2756ef-6287-4a8a-8bed-38c9d32e32b4.PNG)

### Example code

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Window")
	l := []string{"1", "2", "3", "4", "5", "6"}

	list := widget.NewList(
		func() int {
			return len(l)
		},
		func() fyne.CanvasObject {
			return container.New(
				layout.NewMaxLayout(),
				widget.NewLabel("default"),
				canvas.NewRectangle(color.RGBA{144, 0, 0, 0}),
			)
		},
		func(lii widget.ListItemID, co fyne.CanvasObject) {
			if lii%2 == 0 {
				co.(*fyne.Container).Objects[1].(*canvas.Rectangle).FillColor = color.RGBA{0, 0, 177, 0}
			} else {
				co.(*fyne.Container).Objects[1].(*canvas.Rectangle).FillColor = color.RGBA{144, 0, 0, 0}
			}
			co.(*fyne.Container).Objects[0].(*widget.Label).SetText(l[lii])

		},
	)

	list.UnselectAll()

	/* I remove this code and everything works wrong. Colors are displayed out of order. */
	/*
		go func() {
			for {
				list.Refresh()
				time.Sleep(time.Millisecond * 50)
			}
		}()
	*/
	w.SetContent(list)
	w.ShowAndRun()
}

```

### Fyne version

2.3.1

### Go compiler version

1.20

### Operating system

Windows

### Operating system version

Windows 10 20H2

**Comment by andydotxyz** [comment]
After you change the `FillColor` field of a `Rectangle` you must call `Refresh`

**Comment by jojosboomstick** [comment]
@andydotxyz Thanks a lot. It really turned out to be so easy and why didn't I pay attention right away
