### ISSUE TITLE
When the List widget scrolls up and down, the list items are out of order and the text is displayed incorrectly.

### ISSUE THREAD

**Issue by netskyline** [fyne-io/fyne#3668]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When the List widget scrolls up and down, the list items are out of order and the text is displayed incorrectly, probably because the Refresh() method is not called. 

Please check the code and also suggest exposing the OnScrolled event.

### How to reproduce

Drag the scroll bar or middle mouse button to scroll

### Example code

The standard List widget creates the code

```go
list := widget.NewListWithData(...
```

### Fyne version

2.3

### Go compiler version

1.19.5

### Operating system

Android

### Operating system version

MacOS Ventura 13.2.1

**Comment by Jacalz** [comment]
Please include a full example code instead of just a line. This is not something that I personally have noted in any of my projects so it is quite hard to debug otherwise. Examples makes it much easier to reproduce and, in some cases, rule out potential bugs in the user code (definitely not saying that it’s the case here though).

> also suggest exposing the OnScrolled event.

Please keep feature requests and bug reports in separate issues. I believe there already is an issue for this feature somewhere.

**Comment by andydotxyz** [comment]
This widget does work and refresh correctly whilst scrolling.
Perhaps the code inside your setup for Lise is not actually binding the source data to items inside the refresh callback.
It is not possible to tell as your code does not show how your update callback functions.

**Comment by netskyline** [comment]
```go
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
)

// var data = []string{"a", "string", "list"}

func main() {
	var data = []string{}
	for i := 0; i < 100; i++ {
		data = append(data, fmt.Sprintf("item %02d", i))
	}

	myApp := app.New()
	myWindow := myApp.NewWindow("List Widget")

	list := widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return canvas.NewText("template", color.NRGBA{R: 0, G: 255, B: 0, A: 255})
		},
		func(i widget.ListItemID, o fyne.CanvasObject) {
			o.(*canvas.Text).Text = data[i]
		})

	myWindow.SetContent(list)
	myWindow.Resize(fyne.NewSize(400, 300))
	myWindow.ShowAndRun()
}

```

**Comment by andydotxyz** [comment]
After you set a field (like `Text = ...` you need to call `Refresh` (on that label).
Alternatively you can use `SetText` which would ensure the new state is rendered.

**Comment by netskyline** [comment]
It shows that the problem is solved after calling the Refresh() method, thank you very much!

```go
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
)

// var data = []string{"a", "string", "list"}

func main() {
	var data = []string{}
	for i := 0; i < 100; i++ {
		data = append(data, fmt.Sprintf("item %02d", i))
	}

	myApp := app.New()
	myWindow := myApp.NewWindow("List Widget")

	list := widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return canvas.NewText("template", color.NRGBA{R: 0, G: 255, B: 0, A: 255})
		},
		func(i widget.ListItemID, o fyne.CanvasObject) {
			t := o.(*canvas.Text)
			t.Text = data[i]
			t.Refresh()
		})

	myWindow.SetContent(list)
	myWindow.Resize(fyne.NewSize(400, 300))
	myWindow.ShowAndRun()
}

```

**Comment by andydotxyz** [comment]
> But when the amount of data in the list is particularly large, the refresh becomes particularly sluggish, resulting in no response

This should not be true, at least in the general sense. You can see it demonstrated with 10000 data points in the demo at least.
