### ISSUE TITLE
on Windows 10 NewAdaptiveGrid(0) blanks app window on start until resized

### ISSUE THREAD

**Issue by vinser** [fyne-io/fyne#3669]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

On Windows 10 when the app starts the single base window is empty.
When the window is resized or when it is minimized and then maximized, all elements in the window become visible.
No matter what theme is used custom or default.
I built the app using MSYS2 and TDM-GCC the result was the same.
On my SBC with Ubuntu arm64 it builds and works fyne.

### How to reproduce

Run the code below and try to resize app window

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
)

func main() {
	a := app.New()

	tab := container.NewTabItemWithIcon("Choice", theme.GridIcon(), container.NewAdaptiveGrid(0))

	contentTabs := container.NewAppTabs(tab)
	contentTabs.SetTabLocation(container.TabLocationBottom)

	wMain := a.NewWindow("TABS")
	wMain.Resize(fyne.NewSize(1344, 756))
	wMain.CenterOnScreen()
	wMain.SetContent(contentTabs)
	wMain.ShowAndRun()
}
```

### Fyne version

2.3.1

### Go compiler version

go1.20.1 windows/amd64

### Operating system

Windows

### Operating system version

Windows 10 22H2

**Comment by andydotxyz** [comment]
What is the expected outcome when you add a grid that has 0 rows? This doesn't seem like a desirable configuration...

**Comment by vinser** [comment]
I use grid to display images from GetWD or preferred folder. When no images found I show empty UI which allows to choose other folder.  Simple code sample above is not my app. I put it here to locate the trouble. My app works as expected on Ubuntu but on Windows it needs window resize to display UI. I hoped that app will work identically on different platforms as stated :)

**Comment by andydotxyz** [comment]
I agree that it should work as stated, but "0 columns" is quite an edge case, what is the expected behaviour?

**Comment by vinser** [comment]
IMO expected grid behavior with 0 rows/columns is to display nothing, something like Label do with empty string.
```go
	-- tab := container.NewTabItemWithIcon("Choice", theme.GridIcon(), container.NewAdaptiveGrid(0))
	++ tab := container.NewTabItemWithIcon("Choice", theme.GridIcon(), widget.NewLabel(""))
```
  Unlike the grid, the label works correctly both on Linux and on Windows

**Comment by andydotxyz** [comment]
The PR https://github.com/fyne-io/fyne/pull/3689 should fix this inconsistency.
I decided that 0 rows does not make sense, as the min size can't make sensible decisions on that.
Instead we assume at least 1 row/column.

**Comment by vinser** [comment]
Thank you. I attached a software crutch to workaround this case in app - an empty text canvas in onecolumn grid :)

**Comment by andydotxyz** [comment]
Fixed on develop ready for next release
