### ISSUE TITLE
On Windows 10 app window size does not maintain aspect ratio when scaled up

### ISSUE THREAD

**Issue by vinser** [fyne-io/fyne#3676]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When app.SettingsSchema.Scale in settings.json scaled up application window doesn't maintain aspect ratio - vertical dimension was not changed. App windows zoom in keeps aspect ratio when scaled down.
The bug is on Windows 10. On my SBC with Linux Ubuntu arm64 fyne works as expected. 

### How to reproduce

1. Run fyne_demo
2. Start Fyne Settings - Ctrl+,
3. Apply Small Scale
4. Apply Normal Scale back and see window aspect ratio distortion. 

### Example code

Please use fyne_demo

### Fyne version

2.3.1; 2.2

### Go compiler version

go version go1.20.1 windows/amd64

### Operating system and version

Windows 10

### Additional Information

I used fyne_settings in my app and found this bug.

**Comment by vinser** [comment]
Initial Normal Scale
![image](https://user-images.githubusercontent.com/14954512/220951544-6d9d81eb-d886-400b-8c86-1d09e51010c0.png)
Small Scale
![image](https://user-images.githubusercontent.com/14954512/220951927-f4790e64-bf37-40bb-9447-c6ab29b47558.png)
Back to Normal Scale
![image](https://user-images.githubusercontent.com/14954512/220952472-ca41b736-b0d3-4574-b876-695fa06a304d.png)
Vertical size was shrinked

**Comment by andydotxyz** [comment]
I cannot replicate this on Windows.
What C toolchain were you using (TDM/MSYS2/WSL)?

**Comment by vinser** [comment]
I use
```
C:\TDM-GCC-64>gcc --version
gcc (tdm64-1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
```

**Comment by andydotxyz** [comment]
Does it happen every time, or is it intermittent?

**Comment by vinser** [comment]
It happened every time, but today I can't catch this bug either. Very weird.
I've tried fyne_demo and my Pixyne app and both works correctly. I think it's thirteenth today :)
I propose to close the case as non reproducible. I'm sorry for wasting your time

**Comment by vinser** [comment]
Times will show...

**Comment by andydotxyz** [comment]
Not a problem. Maybe we managed to resolve it without realising. Happy it's working for you now anyhow :)
