### ISSUE TITLE
tray can not be show on ubuntu 22.04

### ISSUE THREAD

**Issue by fayfive** [fyne-io/fyne#3678]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Tray can not be show on ubuntu 22.04 and work well on windows 10.

### How to reproduce

1.go build
2.run it on the terminal `./exe`

### Example code

```go
aboutMenuItem := fyne.NewMenuItem("about", func() {
	aboutWindow := a.NewWindow("about")
	aboutWindow.SetContent(aboutContent)
	aboutWindow.Show()
})
menu = fyne.NewMenu("aaa", aboutMenuItem)
trayResouce, err := fyne.LoadResourceFromPath("icon.png")
if err != nil {
	log.Println(err)
	desk.SetSystemTrayIcon(defaultResouce)
} else {
	desk.SetSystemTrayIcon(trayResouce)
}
desk.SetSystemTrayMenu(menu)
```

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system and version

ubuntu 22.04

**Comment by Jacalz** [comment]
Can you please include the full example code? Also, can you share the terminal output (in case of any error) on Ubuntu?

**Comment by fayfive** [comment]
of course

```go
func main() {
	a := app.New()
	a.Lifecycle().SetOnStarted(func() {
		if desk, ok := a.(desktop.App); ok {
			aboutContent := container.NewVBox(
				widget.NewLabel("hello"),
			)
			aboutMenuItem := fyne.NewMenuItem("about", func() {
				aboutWindow := a.NewWindow("about")
				aboutWindow.SetContent(aboutContent)
				aboutWindow.Show()
			})
			menu = fyne.NewMenu("aaa", aboutMenuItem)
			trayResouce, err := fyne.LoadResourceFromPath("icon.png")
			if err != nil {
				log.Println(err)
				desk.SetSystemTrayIcon(defaultResouce)
			} else {
				desk.SetSystemTrayIcon(trayResouce)
			}
			desk.SetSystemTrayMenu(menu)
		}
	})
	a.Lifecycle().SetOnExitedForeground(func() {

	})
	a.Lifecycle().SetOnStopped(func() {

	})
	a.Run()
}
```

**Comment by Jacalz** [comment]
Did you get any error?

**Comment by Jacalz** [comment]
The thing is that I’m not entirely sure that Ubuntu even provided the extensions by default to enable system tray. You should get an error in the terminal if that is the case

**Comment by andydotxyz** [comment]
What we need to know is what window manager / desktop environment is being used. Some of them (as noted in other issues) don't support modern system tray apps.

**Comment by fayfive** [comment]
> What we need to know is what window manager / desktop environment is being used. Some of them (as noted in other issues) don't support modern system tray apps.

I use default ubuntu 22.04 desktop. It's wayland.

**Comment by Jacalz** [comment]
Gnome does not support system tray without an extension. I doubt that Ubuntu has that installed by default. Again, can you please run the application from a terminal and add the terminal output here?

**Comment by fayfive** [comment]
> Gnome does not support system tray without an extension. I doubt that Ubuntu has that installed by default. Again, can you please run the application from a terminal and add the terminal output here?

I can run in the terminal and output. There is no error

**Comment by andydotxyz** [comment]
I think we only log if there is an error sending to dbus. We have succeeded in sending the information about system tray but the spec does not return any information on whether the item could be displayed.

**Comment by andydotxyz** [comment]
You can see some tips for older Linux at https://github.com/fyne-io/systray
