### ISSUE TITLE
Execute callback on Refresh

### ISSUE THREAD

**Issue by drakbar** [fyne-io/fyne#369]
So I have a program that generates the color values of pixels inside the dimensions of the canvas. When the window is resized the dimensions of the canvas changes, and I need to re-run the function with changed dimensions. 

I am using NewRasterWithPixels to create the canvas with the specified pixel function. 

I would like to avoid running the one time function for each pixel.  Is there a point where I can hook into to have that one time function run prior to the pixel functions executions?

**Comment by andydotxyz** [comment]
If you use NewRaster() instead you will pass it a function that is called each time the raster needs to refresh. This function returns a whole image instead of individual pixel colours

**Comment by drakbar** [comment]
Thanks that worked like a charm!
