### ISSUE TITLE
widget.table new api

### ISSUE THREAD

**Issue by hq-zhonger** [fyne-io/fyne#3692]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I have encountered a problem in the table control I want to echo the content of the table MyApp.InformationResultTable.CreateCell = func() fyne.CanvasObject {
return widget.NewLabel("https://baijia.baidu.com")
}
When returning other controls here, it will be difficult to modify due to various size problems, so I have to choose NewLabel
NewLabel cannot automatically recognize the size and change
when my data is not long
<img width="765" alt="1" src="https://user-images.githubusercontent.com/78897251/222381540-767d6fc1-510f-4dd7-9246-2c4c354a0e1e.PNG">

it's just a little bit over it looks ok
when my data is long

<img width="716" alt="2" src="https://user-images.githubusercontent.com/78897251/222381830-51190358-c671-4b1c-bb85-485a33013b8a.PNG">

### Describe the solution you'd like to see.

I hope that the table control can automatically scale the content beyond the format like the entry control
Or you can add a table.index[0].SetWidget(100) to add column width to the specified column

**Comment by andydotxyz** [comment]
Please use `Table.SetColumnWidth` when you realise content is longer than you expected.

**Comment by andydotxyz** [comment]
Closing as answered
