### ISSUE TITLE
GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float)

### ISSUE THREAD

**Issue by Klaus-Tockloth** [fyne-io/fyne#3697]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Sporadic and undeterministic this message occurs:

UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable

The message occurs after closing a window or the application. I haven't observed any drawback in conjunction with the message.

### How to reproduce

I'm not able to reproduce the message.

### Screenshots

Not applicable.

### Example code

Not applicable.

### Fyne version

fyne.io/fyne/v2 v2.3.1

### Go compiler version

go version go1.20.1 darwin/arm64

### Operating system and version

Apple M1 Pro, 13.2.1 (22D68)

### Additional Information

It seems that the message is related to OpenGL and macOS on Apple M1.

**Comment by andydotxyz** [comment]
Please try our `develop` branch as this may be resolved already

**Comment by andydotxyz** [comment]
We are working toward that soon - I expect to have a vote open early next week at the latest

**Comment by andydotxyz** [comment]
> Please try our `develop` branch as this may be resolved already

Of course it is still useful to know the answer to this question - we can't really close the issue or mark it as delivered in the release if we don't have confirmation that the fix works.

**Comment by Klaus-Tockloth** [comment]
> In the meantime I try to avoid window close operations. Because sometimes a close operation leads to an undeterministic "segmentation violation". Unclear ... maybe my fault.

The panic (segmentation violation) doesn't occurs anymore. It seems that the Fyne release v2.3.2, probably issue #3397, has fixt it.

The mainly discussed issue "UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable" still exists. I will try to write a simple program to reproduce it.

**Comment by andydotxyz** [comment]
We saw that error in recent tastings and deduced that it relates to a bug in Apple's GLES implementation. This should only apply to mobile builds - can you confirm what build command you are using so we can rule that out?

**Comment by Klaus-Tockloth** [comment]
This forces the message and misbehavior:

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	application := app.NewWithID("de.freizeitkarte-osm.test")

	wMain := application.NewWindow("Show Markdown Text")
	wMain.CenterOnScreen()
	wMain.SetMaster()
	wMain.SetFixedSize(true)

	// container will be used multiple times (this leads to issues)
	markdownContainer := createMarkdownContainer()

	label := widget.NewLabel("Press the Button to see whatever you expect.")
	button := widget.NewButton("Show Markdown", func() {
		MarkdownWindow(application, markdownContainer)
	})
	content := container.NewVBox(label, button)
	wMain.SetContent(content)
	wMain.ShowAndRun()
}

func MarkdownWindow(app fyne.App, markdownContainer fyne.CanvasObject) {
	wMarkdown := app.NewWindow("Markdown Text")
	wMarkdown.Resize(fyne.NewSize(300, 300))
	wMarkdown.SetContent(markdownContainer) // NOK
	// wMarkdown.SetContent(createMarkdownContainer()) // OK
	wMarkdown.Show()
}

func createMarkdownContainer() fyne.CanvasObject {
	preview := widget.NewRichTextFromMarkdown(loremIpsum)
	preview.Wrapping = fyne.TextWrapWord
	return container.New(layout.NewVBoxLayout(), preview)
}

var loremIpsum = `**Lorem Ipsum**

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.

---

**At Vero**

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
`
```

Screenshot 1 (OK, one window):
<img width="1000" alt="Bildschirm­foto 2023-03-22 um 10 17 01" src="https://user-images.githubusercontent.com/5493128/226857321-b8c574b1-262c-4040-a200-ff142a174f51.png">

Screenshot 2 (NOK, two windows):
<img width="1316" alt="Bildschirm­foto 2023-03-22 um 10 17 29" src="https://user-images.githubusercontent.com/5493128/226857548-f09b5e9f-cc3c-4763-bcde-36a5eeecb841.png">

I use the same container a second time. This triggers the issue. Probably my fault ... a basic misunderstanding (or misuse) of the (container/window) concept.

**Comment by andydotxyz** [comment]
A widget can only be visible in one place at a time... I suspect this may be an issue in your code as you say.

**Comment by Klaus-Tockloth** [comment]
Thanks for the clarification.

**Comment by Klaus-Tockloth** [comment]
I close this issue because it is related to a defect in the user code and not in Fyne.
