### ISSUE TITLE
List row focus indicator disappears on scrolling

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3699]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

It seems that the list rows use the same visual indicator for focused and hovered state. This indicator is hidden when the list is scrolled, which makes sense for the hovered state but not the focused state, as the row still has focus and will be selected when the space bar is pressed.

### How to reproduce

Run any Fyne app that includes a list (demo works). Focus a list row with the tab key, then scroll the list, and observe that the visual focus indicator is hidden but the row still will be selected when space bar is pressed.

### Example code

Fyne demo

### Fyne version

2.3.1

### Go compiler version

go1.19.4 darwin/amd64

### Operating system and version

Mac OS

**Comment by andydotxyz** [comment]
Fixed in v2.3.2 release :)
