### ISSUE TITLE
List row focus not reset when row widget is reused to display a new item

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3700]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When a list row is focused, and then the list is scrolled a full screen or more (so all the list row widgets are now presenting different data), the focus state is not cleared, and pressing the space bar results in an unexpected list row being selected. Expected behavior is that when you scroll a focused list row off of the visible area, the focus should now be reset to nil, rather than remaining with the actual list row widget as it's reused to present different data.

### How to reproduce

1. Launch any Fyne app with a list containing a few screens worth of data.
2. Focus a list row
3. Scroll the list until that row is no longer visible
4. Press space bar and see that an unexpected list row is selected.

### Example code

fyne demo, with window size shrinked so that the number of visible list rows is reduced.

### Fyne version

2.3.1

### Go compiler version

go1.19.4 darwin/amd64

### Operating system and version

Mac OS

**Comment by andydotxyz** [comment]
Please update to v2.3.1 as I think this was already fixed

**Comment by dweymouth** [comment]
Sorry I reported the wrong Fyne version in the ticket. This is present on 2.3.1 (that's what is in the `master` branch right now?). What was fixed is the hover state being properly cleared/reset.

**Comment by andydotxyz** [comment]
I'm not totally certain about this one. The focus implementation could probably be improved - following discussions it should be the `List` not the `listItem` that is focused, so when it scrolls would it really be expected that the focus resets? I'm not sure I agree...

**Comment by andydotxyz** [comment]
Fixed in v2.3.2 release :)
