### ISSUE TITLE
VScroll container not respecting Max container

### ISSUE THREAD

**Issue by syllith** [fyne-io/fyne#3709]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When wrapping a container.NewVScroll in a container.NewMax, the Vscroll does not expand to fill to the remaining screen space

### How to reproduce

Create a NewVScroll wrapped in a container.NewMax, append a canvas.Text to the VScroll, and the VScrolls width is still only as large as the canvas.Text's width

### Screenshots

Real world application:
![Untitled-1](https://user-images.githubusercontent.com/42996651/223509137-b039a0a5-29a0-4ca2-94f2-b1f9ff293336.png)

Sample application:
![image](https://user-images.githubusercontent.com/42996651/223513107-8a17968f-2631-4165-9cce-0e02f9b5afec.png)

### Example code

```
package main

import (
	"image/color"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

var a fyne.App = app.New()
var w fyne.Window = a.NewWindow("Window")

var beginBtn = &widget.Button{Text: "Button"}
var form = container.NewVBox(beginBtn)
var consoleContainer = container.NewVBox()
var consoleScroll = container.NewVScroll(consoleContainer)
var MainView = container.NewHBox(
	form,
	&canvas.Line{StrokeColor: color.RGBA{138, 138, 138, 255}, StrokeWidth: 1},
	container.NewMax(consoleScroll), // <--- I would expect NewMax to cause consoleScroll to fill the entire space
)

func main() {
	go func() {
		for {
			appendToConsole("This is some example text")
			time.Sleep(500 * time.Millisecond)
		}
	}()

	w.SetContent(container.NewBorder(nil, nil, nil, nil, MainView))
	w.ShowAndRun()
}

func appendToConsole(text string) {
	entry := canvas.NewText(text, color.White)
	entry.TextSize = 12
	entry.TextStyle = fyne.TextStyle{Monospace: true}

	consoleContainer.Add(entry)
	consoleContainer.Refresh()
}
```

### Fyne version

2.3.1

### Go compiler version

1.20.1

### Operating system and version

Windows 11

### Additional Information

Perhaps this is not a bug and I'm just misunderstanding the use of the NewMax container, so apologies if that is the case, but I've searched high and low for an answer but have yet to find one. Thank you for your time

**Comment by Bluebugs** [comment]
container.NewMax does create a container that will calculate its MinSize based on the largest items in it. So in this case, there is only one item, so it just propagate the scroller MinSize.

What you are looking for is a container.NewBorder and set the scroller as the fifth element.

**Comment by syllith** [comment]
Pardon my ignorance, but I'm having trouble understanding which element I should be wrapping the border around. I believe this is what you're wanting me to do but I'm still getting the same results

```
var MainView = container.NewHBox(
	form,
	&canvas.Line{StrokeColor: color.RGBA{138, 138, 138, 255}, StrokeWidth: 1},
	container.NewBorder(nil, nil, nil, nil, consoleScroll),
)
```

**Comment by Bluebugs** [comment]
So the HBox is also propagating the MinSize of its content. What you want is to pack that HBox inside a Border also. Most layout problem get solved by using more NewBorder :-D

**Comment by syllith** [comment]
Hm, I'm still getting the same behavior unfortunately.
```
var MainView = container.NewBorder(nil, nil, nil, nil,
	container.NewHBox(
		form,
		&canvas.Line{StrokeColor: color.RGBA{138, 138, 138, 255}, StrokeWidth: 1},
		container.NewBorder(nil, nil, nil, nil, consoleScroll),
	),
)
```

**Comment by syllith** [comment]
I fixed it! Here's what I did. Perhaps this is what you were trying to tell me, but this seems to have the exact behavior I need
```
var MainView = container.NewBorder(
	nil,
	nil,
	container.NewHBox(
		form,
		&canvas.Line{StrokeColor: color.RGBA{138, 138, 138, 255}, StrokeWidth: 1},
	),
	nil,
	consoleScroll,
)
```

**Comment by andydotxyz** [comment]
Basically the use of HBox says "pack these in a row, as narrow as possible" and using `Max` does not override that - no child container can force the parent to give it more space.
The usage of border looks correct now
