### ISSUE TITLE
Implement overflow on tab container

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#371]
When there are more than 7 tabs UI tends to overfit, it'll be nice if a scroll bar would be added to the container

**Comment by andydotxyz** [comment]
Can we extend this to "overflow handling" I think that on some platforms a scroll may not be the right solution...

**Comment by metaclips** [comment]
Do you have an example of how overflow works

**Comment by andydotxyz** [comment]
See “tab overflow” or “tab menu” for a couple of examples https://developer.blackberry.com/native/documentation/gaming_porting/ios_porting/mapping.html

**Comment by metaclips** [comment]
Yes, this looks way better

**Comment by metaclips** [comment]
Itll also be good if we could add other widgets like labels to tab items

**Comment by andydotxyz** [comment]
> Itll also be good if we could add other widgets like labels to tab items

I don't think this part fits - items on a tab bar should control the content within it so this could add inconsistencies?

**Comment by charlesdaniels** [comment]
> > Itll also be good if we could add other widgets like labels to tab items
> 
> I don't think this part fits - items on a tab bar should control the content within it so this could add inconsistencies?

Unless I misunderstand the context, an example use case would be icons in tab items. Another example, once data binding is implemented, would be a label where the text changes in response to some other event (web browsers do this all the time for their tabs). Embedding a smaller button, such as "close" would also be a use case for this.

Of course, all of those could be added as pieces of the notebook API, but it would be more generalized to just allow any widget to be embedded. 

(I assume we are referring to "tab item" as "the thing that has the tab title in it that you click on to change to that tab")

**Comment by andydotxyz** [comment]
tab items can already have icons - text, or icon, or both.
And thse can be changed already.

We have more recently identified that there are two use-cases for tabs. One is application areas (like mobile app tabs or fyne_demo) and another is open files (IDE or browser for example).
We think that they probably have different behaviour and we were focusing on the former first - as this is primarily a requirement for small screen devices. Adding close icons or custom widgets in that scenario does not really make sense.

I hope that makes sense.

**Comment by charlesdaniels** [comment]
I'm not convinced that there aren't other use cases for widgets in tabs. However I am convinced that the use cases for that are niche enough that it's safe to say "you want it, go write your own notebook implementation".

Hmm... does Fyne support a notebook without the tabs rendered at all? I could imagine a notebook would just be a special case of that, but I can think of other container widgets where you might have several "views" you want to switch between programmatically.

**Comment by andydotxyz** [comment]
We don't have a widget do do that specifically - as there is no widget to draw ;).
You would probably use `fyne.NewContainerWithLayout(layout.MaxLayout())` and just call `Container.Content = ...; Container.Refresh()` in your own code.

**Comment by andydotxyz** [comment]
Depends on #1310 because app tabs and document tabs will have different overflow.

**Comment by stuartmscott** [comment]
On develop for testing :)
