### ISSUE TITLE
hover effect on menu

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#372]
If I click on the File menu, and then try and hover over to the Edit menu, the menu doesnt open automatically and I have to manually click the next menu to open it. Expected behavior is for the next menu to open on hover over if I am already viewing an open menu.

**Comment by andydotxyz** [comment]
Moving to 1.2 as there are other related items to work on in that release

**Comment by andydotxyz** [comment]
On develop for testing, thanks so much @toaster

**Comment by andydotxyz** [comment]
This works on mac and Linux, but is not working on Windows...?

**Comment by andydotxyz** [comment]
It looks like the hover events are not being triggered or actioned after an initial tap on the menu bar - when this is on a Windows OS. Not sure how this can be different per-OS

**Comment by andydotxyz** [comment]
Apologies, it was a bad git state
