### ISSUE TITLE
Calling SetContent() in SetOnEnteredForeground() hangs application

### ISSUE THREAD

**Issue by fuskiid** [fyne-io/fyne#3724]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

This bug can be reproduced by modifying the "Hello, World!" example with a lifecycle event (as shown below).

When calling SetContent() inside a Lifecycle().SetOnEnteredForeground(), the application will hang with no error and you will be forced to terminate the application.

When running with `go run -tags mobile` the application will run as expected with no hang.

### How to reproduce

Run example code provided on desktop

### Example code

Example of hanging code:
```go 
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	a.Lifecycle().SetOnEnteredForeground(func() {
		w.SetContent(container.NewVBox(
			hello,
			widget.NewButton("Goodbye!", func() {
				hello.SetText("Bye :(")
			}),
		))
	})

	w.ShowAndRun()
}
```

### Fyne version

v2.3.1

### Go compiler version

go1.20.2

### Operating system and version

Arch Linux (6.2.5-zen1-1-zen)

**Comment by fuskiid** [comment]
Work around code that will run fine: 
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	content := container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	)
	w.SetContent(content)

	a.Lifecycle().SetOnEnteredForeground(func() {
		content.Objects = []fyne.CanvasObject{hello, widget.NewButton("Goodbye!", func() {
			hello.SetText("Bye :(")
		})}
	})

	w.ShowAndRun()
}
```

**Comment by Jacalz** [comment]
While I agree that calling `SetContent()` probably shouldn't deadlock in this case, I just want to point out that the "workaround" is the better approach in general (or even better, you can save references to your button and label and just update their text without creating new objects).

**Comment by andydotxyz** [comment]
Fixed on develop branch
