### ISSUE TITLE
Strange sizing behavior for Entry widget with TextWrapOff

### ISSUE THREAD

**Issue by pbrown12303** [fyne-io/fyne#3725]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Under some circumstances, the size of the highlighted entry area is smaller than the current string in the Entry widget. This was observed when the Entry widget is the bottom half of a VBox and the top half has content whose width is less than the width of the string currently in the Entry widget. The attached example illustrates this.

### How to reproduce

In the attached example, create an HBox containing an icon and an empty string. Make this the top half of a VBox. In the bottom half of the VBox, create an Entry widget with TextWrapOff and a string that is wider than the minimum of the HBox.

### Screenshots

![image](https://user-images.githubusercontent.com/18626700/224758748-bb2ce48d-ae07-4b91-bffe-3686c7ac39f3.png)

### Example code

[main.zip](https://github.com/fyne-io/fyne/files/10959278/main.zip)

### Fyne version

2.3.1

### Go compiler version

1.20.1

### Operating system and version

Windows 10 22H2

**Comment by andydotxyz** [comment]
Can you please paste a small code snippet instead of attaching a project?
The aim is that people can reproduce it fast and that, if accepted, the code forms unit tests to verify the fix from.

**Comment by pbrown12303** [comment]
`	testApp := app.New()
	w := testApp.NewWindow("Test Text Wrap Off Behavior")
	drawingContainer := container.NewWithoutLayout()

	// Example A - abstraction string is empty
	// Get the Icon
	nodeIcon := widget.NewIcon(ResourceElementIconPng)
	// Get the abstraction string
	abstractionString := ""
	abstractionText := canvas.NewText(abstractionString, color.Black)
	hBox := container.NewHBox(nodeIcon, abstractionText)
	nodeLabel := "Node Label A"
	entryWidget := widget.NewEntry()
	entryWidget.SetText(nodeLabel)
	entryWidget.Wrapping = fyne.TextWrapOff
	nodeContainer := container.NewVBox(hBox, entryWidget)
	fynePosition := fyne.NewPos(100, 50)
	drawingContainer.Add(nodeContainer)
	nodeContainer.Move(fynePosition)

	w.SetContent(drawingContainer)
	w.Resize(fyne.NewSize(600, 150))
	w.ShowAndRun()
`

**Comment by andydotxyz** [comment]
I don't think the Entry widget is at fault here - you use `drawingContainer := container.NewWithoutLayout()` which means you want to control the layout. But your layout does not make sure the `Entry` widget has space to meet it's minimum size requirements...

If you make it `drawingContainer := container.NewHBox()` instead it works as expected.

Or add the line `nodeContainer.Resize(nodeContainer.MinSize())` to your manual layout code.

**Comment by pbrown12303** [comment]
I think you are correct. I put the same structure inside Charles' node widget (from the diagram widget extension) and it displays as expected. I will close this.
