### ISSUE TITLE
Theme Icons page in fyne_demo is broken on develop

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3727]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The "Theme Icons" page in `fyne_demo` is broken on develop. The buttons and the selector for displaying theme icons does no work. Only resizing the window causes the displayed icon to be updated.

This is possibly related to https://github.com/fyne-io/fyne/issues/3694. It is likely caused by the same change.

### How to reproduce

1. Open `fyne_demo`.
2. Go to the `Theme Icons` page.
3. Switch icons.
4. Resize the window.

### Screenshots

[Screencast from 2023-03-14 10-46-01.webm](https://user-images.githubusercontent.com/25466657/224961730-59598f18-7c72-4a36-8475-f0c0c3e54da6.webm)

### Example code

Use the "Theme Icons" page in fyne_demo.

### Fyne version

58e13d8d97f82af5511c8300508a5fbe9492dc58

### Go compiler version

1.19.6

### Operating system and version

Fedora Linux 37

**Comment by andydotxyz** [comment]
I think you're right - this is the same as the checkbox issue and also the reason that icons don't appear in system tray menu items on develop either. We may have to insert a refresh in the image construction to get the old behaviour back. Thoughts @Bluebugs ?

**Comment by andydotxyz** [comment]
I think in this instance the line 40 of `widget/icon.go` is the issue, as it is not directly calling the `Refresh` of the image button but instead asking the canvas to refresh its texture.

**Comment by andydotxyz** [comment]
This was fixed already :)
