### ISSUE TITLE
GridLayout updates to support orientation

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#373]
I propose that we rename the GridLayout(cols) to GridColumnLayout(cols) allowing us to add a GridRowLayout(rows) that will lay out from top to bottom then left to right (suitable for a landscape view.

Then we can add GridOrientationLayout(rowcols) (maybe a better name?) that will use the GridColumnLayout is used in portrait but GridRowLayout would be used if the view is wider than tall.

In the simplest form that means that on a portrait layout a GridOrientationLayout(1) with 2 cells would put one above the other, then if made landscape (through resize or rotate) would set them side by side...

Just some thoughts :)

**Comment by okratitan** [comment]
I agree with this.  I think the first thing that needs to be done is finish horizontal scrolling however.

**Comment by andydotxyz** [comment]
I'm not sure I see how scroll is required for this..?

**Comment by andydotxyz** [comment]
merged to develop for testing
