### ISSUE TITLE
Mobile simulator fails to link to OpenGL

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3731]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Running `fyne_demo` after compiling with `-tags mobile` on develop results in the following crash:
```
panic: failed to link OpenGL program:


goroutine 16 [running]:
fyne.io/fyne/v2/internal/painter/gl.(*painter).createProgram(0xc0001122a0, {0xb207f3?, 0x9?})
        /home/jacob/git/fyne/internal/painter/gl/painter.go:174 +0x665
fyne.io/fyne/v2/internal/painter/gl.(*painter).Init(0xc0001122a0)
        /home/jacob/git/fyne/internal/painter/gl/gl_gomobile.go:73 +0x145
fyne.io/fyne/v2/internal/driver/mobile.(*mobileDriver).handlePaint(0xc0000de580, {0x40?}, {0xc550e8, 0xc000156000})
        /home/jacob/git/fyne/internal/driver/mobile/driver.go:250 +0x9a
fyne.io/fyne/v2/internal/driver/mobile.(*mobileDriver).Run.func1({0xc4f2c0?, 0x12eff40})
        /home/jacob/git/fyne/internal/driver/mobile/driver.go:188 +0x418
fyne.io/fyne/v2/internal/driver/mobile/app.main.func1()
        /home/jacob/git/fyne/internal/driver/mobile/app/x11.go:55 +0x34
created by fyne.io/fyne/v2/internal/driver/mobile/app.main
        /home/jacob/git/fyne/internal/driver/mobile/app/x11.go:54 +0x1ea
```

Master and release branch are both working fine.

### How to reproduce

1. Compile `fyne_demo` with `go build -tags mobile`.
2. Run `./fyne_demo`
3. Notice crash

### Example code

Any Fyne application will do.

### Fyne version

f0e5190448680df16bfda21f1554098a65af2cc3

### Go compiler version

Go 1.19.6

### Operating system and version

Fedora Linx 37

**Comment by andydotxyz** [comment]
Upgrading to a release blocker for v2.3.2 - this is a regression since v2.3.1

**Comment by andydotxyz** [comment]
A quick git bisect shows that this was introduced during the text -> single channel render code.
Perhaps @Bluebugs is able to help us hunt this down?

**Comment by andydotxyz** [comment]
Upgrading it again, this is causing iOS (and maybe Android?) builds to crash on boot.
