### ISSUE TITLE
Table shows old data after removing content

### ISSUE THREAD

**Issue by tandem97** [fyne-io/fyne#3736]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

After refresh table with empty data previous data is still showing

### How to reproduce

go run main.go

### Example code

```go
package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

var data = [][]string{[]string{"top left", "top right"},
	[]string{"bottom left", "bottom right"}}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Table Widget")

	list := widget.NewTable(
		func() (int, int) {
			return len(data), len(data[0])
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("wide content")
		},
		func(i widget.TableCellID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(data[i.Row][i.Col])
		})

	go func() {
		time.Sleep(5 * time.Second)
		data = [][]string{{}}
		list.Refresh()
	}()
	myWindow.SetContent(list)
	myWindow.ShowAndRun()
}
```

### Fyne version

2.3.1

### Go compiler version

1.19.3

### Operating system and version

win10

**Comment by andydotxyz** [comment]
Confirmed (and slightly simplified the code) - it seems some "null case" optimisation is not full re-painting the content.
Scroller knows as the bars disappear...

**Comment by tandem97** [comment]
The problem is not reproducible on 2.5.2. Should it be closed?

**Comment by andydotxyz** [comment]
Oh, thanks for commenting, yes it should close
