### ISSUE TITLE
fyne command not found (~/go/bin is in path)

### ISSUE THREAD

**Issue by slukits** [fyne-io/fyne#3737]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Followed https://developer.fyne.io/started til "Check your installation" which reported the fyne command missing:
1. in troubleshooting I'm told to execute:
   go get fyne.io/fyne/v2/cmd/fyne
   I didn't see that one on https://developer.fyne.io/started (linux)
2. I can find ~/go/pkg/mod/fyne.io/fyne/v2@v2.3.1/cmd/fyne
3. but ls ~/go/bin doesn't report a fine command

### How to reproduce

see above

### Example code

It's the setup tool reporting an error, hence no go code.

### Fyne version

2.3.1

### Go compiler version

1.20.2 linux/amd64

### Operating system and version

Arch Linux 6.2.2-arch2-1

### Additional Information

Thank you for your effort!

**Comment by andydotxyz** [comment]
Oops, I think the instruction is on the "packaging" page - a little restructuring may be needed. run:

    go install fyne.io/fyne/v2/cmd/fyne@latest
