### ISSUE TITLE
package -android doesn't work on my Mac M1

### ISSUE THREAD

**Issue by serge-hulne** [fyne-io/fyne#3743]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

when  I type:

```
fyne package -os android -appID com.example.myapp
```

I get the error message : 

```
panic: unsupported GOARCH: arm64

goroutine 1 [running]:
fyne.io/fyne/v2/cmd/fyne/internal/mobile.archNDK(...)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/env.go:291
fyne.io/fyne/v2/cmd/fyne/internal/mobile.(*ndkToolchain).Path(0x1400020b9a0, {0x1400002a151, 0x25}, {0x102c85594, 0x5})
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/env.go:319 +0x78
fyne.io/fyne/v2/cmd/fyne/internal/mobile.envInit()
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/env.go:107 +0x1ac
fyne.io/fyne/v2/cmd/fyne/internal/mobile.buildEnvInit()
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/env.go:76 +0x2ec
fyne.io/fyne/v2/cmd/fyne/internal/mobile.runBuildImpl(0x10303b600)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/build.go:93 +0x3c
fyne.io/fyne/v2/cmd/fyne/internal/mobile.runBuild(...)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/build.go:74
fyne.io/fyne/v2/cmd/fyne/internal/mobile.RunNewBuild({0x16d4e3869, 0x7}, {0x16d4e3878, 0x11}, {0x1400026c050, 0x42}, {0x1400023a01c, 0x4}, {0x102c85125, 0x5}, ...)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/internal/mobile/build.go:278 +0x1d8
fyne.io/fyne/v2/cmd/fyne/commands.(*packager).packageAndroid(...)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/commands/package-mobile.go:18
fyne.io/fyne/v2/cmd/fyne/commands.(*packager).doPackage(0x1400021a680)
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/commands/package.go:122 +0x500
fyne.io/fyne/v2/cmd/fyne/commands.(*packager).Run(0x1400021a680, {0x140000b8170, 0x0, 0x0})
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/commands/package.go:69 +0xb8
main.main()
	/Users/sergehulne/go/pkg/mod/fyne.io/fyne/v2@v2.0.4/cmd/fyne/main.go:85 +0x554
sergehulne@Serges-Mac-mini 1_hello_world % 
sergehulne@Serges-Mac-mini 1_hello_world % 
sergehulne@Serges-Mac-mini 1_hello_world % cat main.go 
```

The app is a simple hello world:
```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### How to reproduce

Just on a Mac M1 (with the same charateristics):

```
fyne package -os android -appID com.example.myapp
```

### Screenshots

```
fyne package -os android -appID com.example.myapp
```

### Example code

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### Fyne version

fyne cli version v2.0.4

### Go compiler version

go version go1.19.5 darwin/arm64

### Operating system and version

MacOS Venura 13.2.1 Arm , M1

### Additional Information

```
fyne package -os ios -appID serge.hulne@gmail.com
```
Doesn't work either, but:

```
fyne package
```
works.

**Comment by Bluebugs** [comment]
Please open a different issue for ios, but from the command line you shared, it seems you need to provide the provisioning and private key to have it working.

Regarding the Android support, we currently do not support building Android from an ARM machine with fyne command directly as the upstream of the Android NDK project doesn't provide an Arm64 build. The likely best way to go at it in the near term is going to be with the next release of `fyne-cross` (v1.4.0) and using a docker with rosetta emulation.

**Comment by andydotxyz** [comment]
> Please open a different issue for ios,

Agreed, it certainly should work - on our Apple Silicon it's looking fine.

**Comment by serge-hulne** [comment]
Thank you! 

Should I close the issue ?

**Comment by andydotxyz** [comment]
I think so, I changed the title to be android specific. If you have trouble with the iOS beyond setting provision then open a new one and we can look at it - or open a discussion or join Slack/Discord if you think it could be a usage question.

**Comment by serge-hulne** [comment]
All right!

Thanks.
