### ISSUE TITLE
widget.NewTable displays abnormally in container.NewVBox

### ISSUE THREAD

**Issue by achillis2016** [fyne-io/fyne#3745]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The fyne table widget displays abnormally in container.NewVBox,  only shows with the minimum height. Even if I set a specific height for it, it doesn't work. Below is the test code, which shows only a very short row in the table section after running.

### How to reproduce

please test my example code and you will see the problem.

### Screenshots

![fyne Table](https://user-images.githubusercontent.com/16607564/226096448-fd3a64bd-d801-4b9d-b3fd-7fb63f2326e5.jpg)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Dialog")
	myWindow.Resize(fyne.NewSize(600, 400))

	label := widget.NewLabel("This is a label")
	table := widget.NewTable(
		func() (int, int) {
			return 3, 5
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("Cell")
		},
		func(i widget.TableCellID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(fmt.Sprintf("Cell %d:%d", i.Row, i.Col))
		},
	)
	table.Resize(fyne.NewSize(0, 400))
	button := widget.NewButton("Button", func() {})

	content := container.NewVBox(
		label,
		table,
		button,
	)

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}
```

### Fyne version

2.3.1

### Go compiler version

1.20

### Operating system and version

Windows10 and Ubuntu

### Additional Information

I tested the program on both Windows 10 and Ubuntu，the problem both exists.

**Comment by andydotxyz** [comment]
Items in VBox are all showed using their minimum height.
Specifying a height is ignored if you place the item in a managed container https://developer.fyne.io/faq/layout.

You probably want border or something other than the vertical box https://developer.fyne.io/explore/layouts

**Comment by andydotxyz** [comment]
Closing as not an issue
