### ISSUE TITLE
Vertical radio shadow appears to low. 

### ISSUE THREAD

**Issue by drakbar** [fyne-io/fyne#375]
When hovering over an item in a vertical radio group the shadow is too low.

Picture of observed behavior. Note that the mouse is hovering over the first (top) element.
![vert](https://user-images.githubusercontent.com/20728117/62167627-4833f700-b2e9-11e9-8979-303e9b0211d6.png)

Picture of expected behavior (except that the elements layout in the picture is horizontal). 
![hor](https://user-images.githubusercontent.com/20728117/62167628-4833f700-b2e9-11e9-99ff-a843bebdeceb.png)

The darker circle (shadow) appears to be one radius too low.
OS: Windows 10
Fyne Version: 1.1
Scale: 1.00

**Comment by sdolny** [comment]
fix PR: https://github.com/fyne-io/fyne/pull/383

**Comment by andydotxyz** [comment]
That fix works nicely, a little fix in formatting and we can merge it in

**Comment by andydotxyz** [comment]
Ready for testing on develop
