### ISSUE TITLE
line next char \n cant useful

### ISSUE THREAD

**Issue by EddieChan1993** [fyne-io/fyne#3750]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

`label.ParseMarkdown("aaa\naa")` line breaks cannot be resolved to

### How to reproduce

i want to turn next line by use label.ParseMarkdown() include char \n,but cant useful,

### Example code

label := widget.NewRichTextWithText("")
	label.Wrapping = fyne.TextWrapWord 
	label.Scroll = container.ScrollVerticalOnly
	label.ParseMarkdown("aaa\naa")

### Fyne version

v2.3.1

### Go compiler version

1.18

### Operating system and version

macOs

**Comment by andydotxyz** [comment]
A newline in markdown is not a line break - you need a double break to form a new line ("aaa\n\naa") https://daringfireball.net/projects/markdown/syntax

**Comment by EddieChan1993** [comment]
3ks
