### ISSUE TITLE
Fyne package should optionally pad icons for Mac OS to fit conventions

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3752]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

On Mac OS, application icons are supposed to have a small amount of transparent padding around the main icon image (this is to allow for icons that have a "tool" like the hammer in the XCode icon that extend beyond the main image's rounded rectangle). See [here](https://bootcamp.uxdesign.cc/creating-app-icons-for-macos-11-and-up-1132ccd479bc) and [here](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) for more info.

### Describe the solution you'd like to see.

It would be nice for `fyne package` to be able to automatically add the standard amount of padding around the input icon when packaging for Mac OS. This should be optional/disableable in case the developer has already prepared an icon asset that is directly suitable for Mac OS.

**Comment by andydotxyz** [comment]
Should we add the curved corner as well? This happens automatically on iOS apps...

**Comment by dweymouth** [comment]
> Should we add the curved corner as well? This happens automatically on iOS apps...

Yes that would be nice too. Of course it should be disableable/optional as well. I manually rounded corners for my icon (and it's rounded on Linux/Windows too) but I had to prepare a mac-specific padded version.

**Comment by andydotxyz** [comment]
Fixed on develop :)
