### ISSUE TITLE
fyne.CurrentApp().Settings().SetTheme memory leaks

### ISSUE THREAD

**Issue by alexballas** [fyne-io/fyne#3755]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Every time I run fyne.CurrentApp().Settings().SetTheme I see an increase in memory usage which does not recover. Please refer to the example code below

When I first run the app:
RES memory:  51M

After 3 minutes:
RES memory: 1172M

### How to reproduce

Run the provide code and observe the memory usage of the application.

### Example code

```go
package main

import (
	"time"

	fyne "fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {

	myApp := app.New()
	myWindow := myApp.NewWindow("Test Dialog")
	l := widget.NewLabel("hello")
	myWindow.SetContent(l)

	go func() {
		for i := 0; i < 1000; i++ {
			go func() { fyne.CurrentApp().Settings().SetTheme(theme.DarkTheme()) }()
			time.Sleep(500 * time.Millisecond)
			go func() { fyne.CurrentApp().Settings().SetTheme(theme.LightTheme()) }()
			time.Sleep(500 * time.Millisecond)
		}
	}()

	myWindow.ShowAndRun()
}

```

### Fyne version

v2.3.2

### Go compiler version

1.20.2

### Operating system and version

Ubuntu 18.04

**Comment by dweymouth** [comment]
Dup of #3640

**Comment by alexballas** [comment]
Ty. Will close this one then
