### ISSUE TITLE
Add option in List to hide separators

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3756]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The List widget has a lot of nice builtins but if the developer wants a non-interactive list (eg to display a log file as recently discussed in the discord), or if the row widgets themselves handle interactivity, then it is not really suitable to use the existing List without forking it to comment out builtin behavior. 

### Describe the solution you'd like to see.

The `List` widget should have new publicly exported flags:

```go
type List struct {
    // ...
    DisableSelection bool
    DisableRowFocus bool
    DisableHover bool
    NoSeparator bool
    // ...
}
```

Or perhaps DisableSelection should disable rows being focusable and hoverable as well, and in that case be named DisableInteractivity?

Also, maybe instead of DisableSelection, have a new enum SelectionMode once multi-select is actually implemented:

```go
type SelectionMode int

const (
    SelectionModeSingle SelectionMode = iota // default, since existing behavior is single-select
    SelectionModeMulti
    SelectionModeNone
)
```

**Comment by andydotxyz** [comment]
> or if the row widgets themselves handle interactivity, then it is not really suitable to use the existing List without forking it to comment out builtin behavior.

In this case we don't have to worry as the child widgets will override the behaviour in the List (as child interaction always has preference over parent).

**Comment by dweymouth** [comment]
Yeah I like `HideSeparators` as a name. Agree that focus is really the only one that requires forking the List code if you don't want it since the other behaviors can be overridden by the row widgets.

**Comment by dweymouth** [comment]
Wanted to revisit this discussion to talk about what disabling focus could look like, API-wise, for the collection widgets. @Jacalz and I discussed adding selection to the GridWrap widget in fyne-x to prep for moving it into Fyne. If selection is added, however, I will have to maintain a fork of the widget to keep using it in my project (as I already do with List) because I need builtin focusability of the items to be disabled.

**Comment by andydotxyz** [comment]
Ah, that is indeed particularly problematic because implementing an interface such as Focusable is done at compile time and a runtime switch can't disable it.
Disabling selection and dividers / space is easier as these are done at runtime.
Might need a bit of exploration here!

**Comment by dweymouth** [comment]
How do disableable widgets like button reject the focus when they are disabled? Maybe a similar strategy could be used?

**Comment by andydotxyz** [comment]
The focus manager understands the Disabled interface and avoids focusing those widgets.

**Comment by dweymouth** [comment]
Just updating to clarify that a hide separators option is the only thing that needs to be added, API-wise. Everything else can be achieved by extending widget.List and making it Disableable and disabled.

**Comment by dweymouth** [comment]
On develop for 2.5.0
