### ISSUE TITLE
Systray MenuItem separators not rendered

### ISSUE THREAD

**Issue by d1ss0nanz** [fyne-io/fyne#3759]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

After upgrading from version 2.3.1 to 2.3.1 all but the first MenuItem separators are gone.
Even the one before the `Quit` item.

### How to reproduce

1. run the attached application
2. only the first separator is visible

### Example code

```func main() {
    app := app.New()

    systrayMenu := fyne.NewMenu("Test", &fyne.MenuItem{Label: "Click"})
    if desk, ok := app.(desktop.App); ok {
        desk.SetSystemTrayMenu(systrayMenu)
    }
    systrayMenu.Items = append(systrayMenu.Items, fyne.NewMenuItemSeparator(), &fyne.MenuItem{Label: "a"}, &fyne.MenuItem{Label: "b"}, fyne.NewMenuItemSeparator(), &fyne.MenuItem{Label: "c"})

    app.Run()
}
```

### Fyne version

2.3.2

### Go compiler version

1.20

### Operating system and version

macOS Ventura

**Comment by andydotxyz** [comment]
Apologies for this, updating systray to include the fix in https://github.com/fyne-io/systray/pull/42 has resolved this on `develop` and the release branch.
