### ISSUE TITLE
Insecure password field

### ISSUE THREAD

**Issue by silverkorn** [fyne-io/fyne#376]
Hi!
Trying the demo included, the password input field is allowed to copy the content in the clipboard (Using CTRL+C). I guess this should not be possible.
Thanks!

**Comment by silverkorn** [comment]
Thanks!
Although your commit title mention "or paste", which should still be allowed. 
(Looking into the commit, it seems that you correctly only applied it for copy and cut 👍 )

**Comment by andydotxyz** [comment]
Oops, thanks for spotting the mistake. It was just in the comment as you say
