### ISSUE TITLE
Hidden elements re-appear when in a parent that is shown

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#377]
hide function in toolbar widget doesn't seem to work.

**Comment by andydotxyz** [comment]
This seems to work perfectly wel in fyne_demo - can you please provide more information?

**Comment by metaclips** [comment]
> This seems to work perfectly wel in fyne_demo - can you please provide more information?

To reproduce the error on fyne_demo, hide the fyne_logo image when you run it, it initially hides the image but on navigating to another tab and then switching back to the widget tab you notice it shows the hidden image, if you also remove the welcome tab from the first index tab it ignores the Hide() function.

**Comment by andydotxyz** [comment]
I think there might actually be an easier fix here than I imagined

**Comment by metaclips** [comment]
Nice, expectant :)

**Comment by andydotxyz** [comment]
This is a trivial fix but is a behaviour change in our widget/container contract so I will develop a little further and it should make it into the next release.
