### ISSUE TITLE
Window width increases consistently when the input text reaches edge.

### ISSUE THREAD

**Issue by spatocode** [fyne-io/fyne#378]
**Issue**
While inputing text, windows width size increases consistently when the input text reaches the edge of window. This continues as long as you keep making entry on the same column.

**Expected behavior**
I think there should be a horizontal scroll bar in entry widget for overflowed text input. It should help to fix the windows size overflow.

**Platform**
Windows 10 Os

**Comment by andydotxyz** [comment]
Quite right, thanks. First we need to add horizontal scrolling #132 so it's not a quick fix but should be in the next major update.

**Comment by 4avka** [comment]
This is possibly also related, maybe worth a separate bug report but there is no bounds checking on the cursor as I discovered when I tried to implement a naive character maximum limit and it causes a panic that bombs the whole app. The cursor should check length and fall to the last position available before code tries to access the index beyond the boundary.

**Comment by andydotxyz** [comment]
I guess that depends on how you implemented the limit?

**Comment by andydotxyz** [comment]
adding #471 would fix this
