### ISSUE TITLE
fyne release command not working on macOS for submitting app store

### ISSUE THREAD

**Issue by milkcoke** [fyne-io/fyne#3787]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

It seems `fyne release` command  error occurs as shown below even though I input arguments correctly.
I'm trying [this feature](https://github.com/fyne-io/fyne/pull/1609)

but error occurs like this

```log
exit status 1
```

That's all.

#### My command
```bash
$ fyne release -icon [my-icon-path] -name [my-app-name] \
--os darwin -appID [my-app-ID] --appVersion 1.0 --appBuild 1 \
--cert [my-cert] \
--profile macOS -category "developer-tools"
```

### Example code

.

### Fyne version

2.3.3

### Go compiler version

1.20.1

### Operating system and version

Mac OS 13.3 Ventura / M1

### My guess the cause of problem
I was seeing my project directory while that command executing. 
There's a `entitlements.plist` and `MyApp.app` file

But after error occurs, those files are eliminated immediately

I refer to [release.go](https://github.com/fyne-io/fyne/blob/master/cmd/fyne/internal/commands/release.go#L323)

```Go
func (r *Releaser) packageMacOSRelease() error {
	// try to derive two certificates from one name (they will be consistent)
	appCert := strings.Replace(r.certificate, "Installer", "Application", 1)
	installCert := strings.Replace(r.certificate, "Application", "Installer", 1)
	unsignedPath := r.Name + "-unsigned.pkg"

	defer os.RemoveAll(r.Name + ".app") // this was the output of package and it can get in the way of future builds

	cleanup, err := r.writeEntitlements(templates.EntitlementsDarwin, nil)
	if err != nil {
		return errors.New("failed to write entitlements plist template")
	}
	defer cleanup()

	cmd := execabs.Command("codesign", "-vfs", appCert, "--entitlement", "entitlements.plist", r.Name+".app")
	err = cmd.Run()
	if err != nil {
		fyne.LogError("Codesign failed", err)
		return errors.New("unable to codesign application bundle")
	}

    // ⚠️ Maybe error occurs here
	cmd = execabs.Command("productbuild", "--component", r.Name+".app", "/Applications/",
		"--product", r.Name+".app/Contents/Info.plist", unsignedPath)
	err = cmd.Run()
	if err != nil {
		fyne.LogError("Product build failed", err)
		return errors.New("unable to build macOS app package")
	}
	defer os.Remove(unsignedPath)

	cmd = execabs.Command("productsign", "--sign", installCert, unsignedPath, r.Name+".pkg")
	return cmd.Run()
}
```

I guess error occurs in `productbuild` process since if I input `--cert [wrong-cert-name]` 
error would occur `Codesign failed`.

According to above code, entitlements and package directories are deleted even when error occurs. So it's difficult to find what's the problem exactly.

### Question summary
1. How to resolve this problem? is there any wrong part on my CLI command?
2. Is this package file supporting arm64 and x64 both? by just providing one file like [universal macOS Binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)?

I thought maybe [this issue](https://github.com/fyne-io/fyne/pull/3352) to be resolved for debugging when we use `release` command.

**Comment by andydotxyz** [comment]
The profile needs to be the name of your provisioning profile downloaded from Apple's developer centre.

**Comment by milkcoke** [comment]
Thanks @andydotxyz ,
I fixed the `--profile` option but it still same error occurs.

**Comment by andydotxyz** [comment]
Can you show the name of the profile and certificate from Apple or on your local system, and the command you are using?
It still sounds very much like they don't match.

**Comment by milkcoke** [comment]
I'm worrying about exposing my personal information..

My app name is 'Toolbox Def'

```bash
$ fyne release -icon assets/app_icon.png -name "Toolbox Dev" \
--os darwin -appID "toolbox.milkcoke" --appVersion 1.0 --appBuild 1 \
--cert "3rd Party Mac Developer Application: [My-Info]" \
--profile "toolbox_milkcoke_profile.provisionprofile" \
-category "developer-tools"
```

#### Profile information

<img width="799" alt="profile_name" src="https://user-images.githubusercontent.com/48945177/230380025-37d21da7-7012-41c7-a65d-bbfc2b0930e1.png">

#### screenshot
<img width="766" alt="error_screenshot" src="https://user-images.githubusercontent.com/48945177/230381688-4e201192-1447-4f60-b2c3-ec2be935114f.png">

**Comment by andydotxyz** [comment]
Sorry for the long delay here. It looks like you have name and ID messed up in your Apple config.

**Comment by andydotxyz** [comment]
If the "App ID" was in fact `toolbox.milkcoke` then most of your command would be correct. However the provisioning profile remains incorrect - it should not be a filename but a profile name. The name is displayed in the provision details in Apple developer portal or in the Finder "QuickLook" for the file.

**Comment by andydotxyz** [comment]
Did you get this resolved? I don't think it is an error in the Fyne tooling.
I just wanted to reach out to see if you git it fixed rather than just closing the issue.

**Comment by milkcoke** [comment]
It's not resoloved.
I stopped registering my app on app store since market security policy ... both microsoft store and app store.
Instead, I publish my app on [my personal blog](https://milkcoke.github.io/docusaurus/toolbox-dev/releases/v1.0.0)

Thanks your support andy.

**Comment by andydotxyz** [comment]
I'm sorry to hear you couldn't continue. Given that the previous suggestion was metadata in you Apple account was mixed up, and that you're not exploring it further, I think this should be closed. Anyone with info about this not working for them could reopen it.

**Comment by kaicherry** [comment]
I think this issue here (because I experienced it and have done many apps) is the nomenclature + slight change in procedures since  switched command line tools:
--profile is *not* asking for the physical .mobileprovision file, but the "Name" assigned to this profile in the  Dev Portal. 

It's clear to you/in your head, but I assure you, this is the source of the confusion when this is reported :)

-J

**Comment by andydotxyz** [comment]
I'm sure you are right. However none of the docs refer to a file name. We have "name of the provisioning profile for this release build".

Please do provide what would be clearer so we can avoid confusion. You could even open a pull request on the command or docs.

**Comment by Gys** [comment]
I recognize this problem 😅 Also automatically thought it was a file name because the profile is downloaded as a file, so it makes sense to pass the name of the file. Maybe `"Name" as given to this profile in the  Dev Portal` is a clearer description, as suggested by @kaicherry :) I also found that pressing the spacebar to see a preview of the profile file shows its details, including the profile name.
