### ISSUE TITLE
Text doesn't render in Windows VM

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#3790]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Text doesn't render on Windows (11) VirtualBox VM running in an Ubuntu host. Where the text should be is just an empty space. Hardware acceleration is enabled for the VM. This is a regression since earlier Fyne versions on the same VM with the same settings rendered text just fine. This problem is not present in a non-VM install of Windows.

### How to reproduce

Create a Windows 11 VM inside VirtualBox on Ubuntu (no idea if this is present with other combos of virtualization software, host OS, etc). Run the latest fyne demo.

### Screenshots

[screenshot](https://user-images.githubusercontent.com/5303666/230256584-3f8a0df7-23b1-4588-8bd8-14c62c60373f.png)

### Example code

fyne demo @ latest

### Fyne version

2.3.3

### Go compiler version

1.19.4 windows/amd64

### Operating system and version

Windows 11 (VM guest)

**Comment by andydotxyz** [comment]
Hmm, I wonder if it relates somehow to the single channel text optimisations. @Bluebugs can you check this out please?
I don't know why it would compile and run but not render!

**Comment by Bluebugs** [comment]
Do you have any error message if you start the application from a console.

**Comment by Bluebugs** [comment]
And what is the GL driver you are using in that VM?

**Comment by dweymouth** [comment]
No error logs seen, just the "Lifecycle: Started, Entered Foregrond, etc" logs.

According to VirtualBox:

> System > Acceleration: VT-x/AMD-V, Nested Paging, Hyper-V Paravirtualization

> Display > Video Memory: 128MB
> Display > Graphics Controller: VBoxSVGA
> Display > Acceleration: 3D

**Comment by Bluebugs** [comment]
Do you have the guest addition installed?

**Comment by dweymouth** [comment]
Yes, I'm like 95% sure I do but it was awhile since I set up that VM. I can double check later and update here.

**Comment by heejit** [comment]
is this related : #3879

**Comment by Jacalz** [comment]
@dweymouth I believe that this was resolved when emojis landed. Can you please test again?
