### ISSUE TITLE
Mouse cursor desync with Split handle when draging

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3791]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

You have a Split container, you drag it with the mouse until one end (reaching content's MinSize) and continu draging the cursor past that limit ; when returning to the other side, the Split handle is not synchronized on the mouse cursor.

### How to reproduce

Anything with a Split container will reproduce the bug

### Screenshots

https://user-images.githubusercontent.com/1791230/230330846-9dac719d-7612-4d38-a6dc-5cdbca6543a0.mp4

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	w.SetContent(container.NewHSplit(
		widget.NewLabel("Testing"),
		widget.NewLabel("Testing"),
	))

	w.Resize(fyne.NewSize(400, 400))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.3.2

### Go compiler version

1.20

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
This was recently fixed on develop
