### ISSUE TITLE
Is there better way for embedding a hyperlink into text body?

### ISSUE THREAD

**Issue by drakbar** [fyne-io/fyne#380]
So this isn't that big of an issue, but as you can see from the picture below that text appears noncontagious. This is definitely happening because of the HBox, but I cannot think of a better way to make a block of text that has hyperlinks embedded inside of it.
  
![link](https://user-images.githubusercontent.com/20728117/62400643-84639380-b545-11e9-858b-2e37553ae1f8.png)

Here is the snippet I use to create it
```go
   widget.NewHBox(
	widget.NewLabel("some text"),
	widget.NewHyperlink("hyperlink", url),
	widget.NewLabel("some more text"),
	widget.NewHyperlink("another hyperlink.", url2))
 ```

**Comment by andydotxyz** [comment]
Widgets all have their own layout and so usually are padded. Joining them together like this is not intended.
You could use canvas.Text to do something more like what you want, but that is more work.
Perhaps this becomes a duplicate of the markdown feature request? #149

**Comment by drakbar** [comment]
I don't know too much about blackfriday, but I would assume that markdown would be able to handle it. Looking forward to that feature 😄. Gonna close this issue.
