### ISSUE TITLE
iOS simulator closes (or crashes?) with helloworld or fyne-demo app

### ISSUE THREAD

**Issue by arnos** [fyne-io/fyne#3802]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In the iOS simulator (using iphone14) I can install the app, but when touching the app icon, the app launches a black screen and instantly closes.

I've tried this with both a simple helloworld and the fyne-demo code in this repo.

Is this a behaviour of the simulator or am I missing something?

### How to reproduce

1. create a new fyne project
2. source code for main.go (see example code)
3. package it `fyne package -os ios -appID fyne-demo -icon mobileIcon.png`
4. install it on simulator `xcrun simctl install booted Fyne-Demo.app`

### Example code

```go 
package main

import (
	"fyne.io/fyne/theme"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("io.fyne.demo")
	a.SetIcon(theme.FyneLogo())

	w := a.NewWindow("Fyne Demo")

	w.SetContent(widget.NewLabel("Hello World!"))

	w.ShowAndRun()
}
```

### Fyne version

2.2.3

### Go compiler version

go version go1.19.5 darwin/arm64

### Operating system and version

mac OS ventura

**Comment by andydotxyz** [comment]
The os should be "iossimulator" not "ios" when testing on the simulator

**Comment by arnos** [comment]
Thanks @andydotxyz corrected and tested, I'll submit a change to the documents for https://developer.fyne.io/started/mobile

**Comment by andydotxyz** [comment]
Perfect thanks. Merged your suggestion.
