### ISSUE TITLE
Rich Text image alignment

### ISSUE THREAD

**Issue by vinser** [fyne-io/fyne#3810]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

 Image in RichText is always center aligned. It's impossible to align it to left or right edge. That's why its hard to display well composed rich text containing images.

### Is it possible to construct a solution with the existing API?

There is no means 

### Describe the solution you'd like to see.

It will be useful to add alignment for RichText ImageSegment to align it alongside with segments of other type.

**Comment by andydotxyz** [comment]
A good suggestion

**Comment by andydotxyz** [comment]
Maybe this is the same as #3505?

**Comment by vinser** [comment]
> Maybe this is the same as #3505?

Surely, it's the same

**Comment by andydotxyz** [comment]
Resolved (on develop) for v2.4.0 :)
