### ISSUE TITLE
Menu separator not visible with light theme

### ISSUE THREAD

**Issue by Klaus-Tockloth** [fyne-io/fyne#3814]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Menu separator not visible with light theme (windows, linux).

### How to reproduce

Start application and activate menu.

### Screenshots

OK:

![image 2](https://user-images.githubusercontent.com/5493128/231416765-0a35b056-ab2f-47ae-a9dd-f09ee0c3bc2a.png)

NOK:

![image](https://user-images.githubusercontent.com/5493128/231416823-c0d7d9a8-d9b1-4830-8fe2-25be5ec839a3.png)

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	application := app.New()
	wMain := application.NewWindow("Menu Separator")
	wMain.Resize(fyne.NewSize(400, 400))
	hello := widget.NewLabel("Menu separators not shown under Windows.")
	wMain.SetContent(hello)

	generalHelp := fyne.NewMenuItem("General", func() {})
	problemHelp := fyne.NewMenuItem("Problem", func() {})
	versionHelp := fyne.NewMenuItem("Version", func() {})
	helpMenu := fyne.NewMenu("Help", generalHelp, fyne.NewMenuItemSeparator(), problemHelp, fyne.NewMenuItemSeparator(), versionHelp)

	mainMenu := fyne.NewMainMenu(helpMenu)
	wMain.SetMainMenu(mainMenu)
	wMain.ShowAndRun()
}

### Fyne version

fyne version v2.3.3

### Go compiler version

go version go1.20.3 darwin/arm64

### Operating system and version

Windows 10 Pro (20H2)

**Comment by andydotxyz** [comment]
Fixed on release branch for v2.3.5 :)
