### ISSUE TITLE
fyne package has no option to add files to the Resources folder for Mac OS app

### ISSUE THREAD

**Issue by stephane-archer** [fyne-io/fyne#3819]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

`fyne package` has no option to add files to the Resources folder for Mac OS app

### Is it possible to construct a solution with the existing API?

I can package the app then add these files manually but that completely destroy the problem that `fyne package` tries to solve

### Describe the solution you'd like to see.

adding a command line option would be great

**Comment by Jacalz** [comment]
Can you not install using the `fyne install` command?

> I can package the app then add these files manually but that completely destroy the problem that fyne package tries to solve

I am not entirely sure that I agree with that. It is about creating packages that can be distributed, not how to install them. Are you asking for bundling an installer with the package? If that's the case, then we have the same problem on Windows but not Linux/BSD.

**Comment by Bluebugs** [comment]
I think, correct me if I am wrong, but the idea here is to add custom file to the macos package. I am not to sure of the use case here, but the problem with this feature request is that adding file like that would only work on macos. Was `fyne bundle` considered? This allow embedding file on the binary and is cross platform.

**Comment by stephane-archer** [comment]
@Bluebugs understood what I meant 

here is what I currently do in my Makefile:
```
dist/intel/MyApp.app/Contents/MacOS/MyAppGui dist/intel/MyApp.app/Contents/Info.plist dist/intel/MyApp.app/Contents/Resources/icon.icns&: MyAppGui icon/icon.png
	mkdir -p dist/intel/ && fyne package --executable MyAppGui --name dist/intel/MyApp --appVersion $(CurrentVersion) --icon icon/icon.png

dist/intel/MyApp.app/Contents/Resources/MyAppCli: MyAppCli
	mkdir -p $(@D) && cp $? $@

dist/intel/MyApp.app/Contents/Resources/config.ini: config.ini
	mkdir -p $(@D) && cp $? $@
``` 
to make it clear, I need to add `config.ini` and `MyAppCli` in the `MyApp.app/Contents/Resources/` folder

currently `fyne package` expect that the app to be a single binary and that it doesn't need any additional file.

To make it more general an option like `-additionalFile` could be great, in the case of MacOS this will put file in `MyApp.app/Contents/Resources/` for other platforms I'm not sure what is appropriate.

the issue with `fyne bundle` is that the user can't modify the `config.ini` for it's needs or use `MyAppCli` in a script

**Comment by andydotxyz** [comment]
> currently `fyne package` expect that the app to be a single binary and that it doesn't need any additional file.

That is correct, it is our design and it enables the true platform portability as many app package formats don't support bundled files.

> the issue with fyne bundle is that the user can't modify the config.ini for it's needs

Another challenge is that some bundle formats don't support writing of files that are part of a bundle.
File modifications should be done in user-space (`App.Storage().RootURI()`).

The recommended approach is to bundle the default file and, if modifications are supported, then extract it to the writable space and allow modifications.

> here is what I currently do in my Makefile:

Fyne, like most Go apps, expects that code can simply be run without a Makefile. Adding scripts also gets in the way of portability so we don't want to encourage it.

**Comment by andydotxyz** [comment]
As @Bluebugs says there is a whole `Preferences` API that can solve the config problem for you if the changes are managed by the app. Using functions like `Preference.StringWithFallback` could replace the need for file handling.
With the added bonus that the data is syncronised by any set `CloudProvider`!

https://developer.fyne.io/explore/preferences

**Comment by waynebloss** [comment]
I would like to bundle multiple binaries for Linux, macOS and Windows and I would prefer them not all to be bundled together.

**Comment by andydotxyz** [comment]
As I am sure you can imagine the tools here are designed for building applications that work on any target platform.
Bundling binaries separate to the app which is being compiled is not going to be supported in the main tooling.

If you want to bundle multiple apps into one you may need a custom build pipeline or some scripts locally to build the final output.

**Comment by andydotxyz** [comment]
> currently `fyne package` expect that the app to be a single binary and that it doesn't need any additional file.

This is absolutely correct - and for some of the platforms we would have to change how the app is delivered to support this feature request (for example windows could no longer ship a runnable .exe). Additionally, as noted above, bundled resources will not be writable on some systems even if the feature was added.

Closing as not in-line with our design and promise for cross-platform compatibility. I recommend the Preference api for managing user preferences (which has built-in support for default values and also can be edited by the user).
