### ISSUE TITLE
[Windows]go-gl:build constraints exclude all Go files and how it Slove.

### ISSUE THREAD

**Issue by legiorange** [fyne-io/fyne#3820]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.

Frist, I can't install github.com/go-gl/gl. Like https://github.com/fyne-io/fyne/issues/2973
And I have gcc problem.

I waste 6h to solve all question. So I open a Issue here, help other guys quickly start Fyne project.

### How to reproduce

1. Need set CGO_ENABLED=1 to fix go-gl:build constraints exclude all Go files
``` 
go env -w CGO_ENABLED=1
```
then:
```
D:\gitvip\website>go run main.go
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

```

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

### Fyne version

2.3.3

### Go compiler version

1.20.3

### Operating system and version

Windows 11

### Additional Information

2.Install Mingw-w64
We need gcc , need install Mingw 
Mingw can build Unix and POSIX programes ,and have no need runtime env.

2.1Linux&Mac:
    
    You don't need install MinGW-W64.Just close 

2.2Windows:

     Don't try winget install command on this . not work.
How to download:

Here to download online installer  [MinGW-W64 online installer](https://github.com/Vuniverse0/mingwInstaller/releases/download/1.2.0/mingwInstaller.exe) 

You know what , China have F******* GFW, If you're Chinese you probably won't even be able to open GitHub.
In other words, you can't download mingw at all.
Try this :

1. Find a VPN,Curse the developers and masterminds of the F**** GFW if you have one.

2.Download other source:
2.1 https://sourceforge.net/projects/mingw-w64/
I set windows env path , not work 
2.2 https://github.com/niXman/mingw-builds-binaries/releases
I chose  
    x86_64-12.2.0-release-posix-seh-msvcrt-rt_v10-rev2.7z
If you don't know all it means just download.

2.3 Add unzip path to windows env path.

open cmd.exe and run:
```
gcc -v 
```
No Error. 

Next:
 Restart IDE  and run
```
go run main.go
```
Stuck, Just wailt sometime , it will work.

My fyne demo finally run, hope this can help you.

Other Way:
    go install github.com/fyne-io/fyne-cross@latest
```

D:\gitvip\website>fyne-cross windows -arch=amd64    
[i] Target: windows/amd64
[i] Cleaning target directories...
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create?platform=linux%2Famd64": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
[✗] could not clean the "bin" dir /app/fyne-cross/bin/windows-amd64: exit status 127
```
When you want use it , you need **Docker**.

Then you can try command 

    fyne-cross windows -arch=amd64,386

**Comment by yangbo** [comment]
I also have the same "exclude all go files" issue and solved just as your solution.
In short, you just need:
1. install MSYS and GCC. Follow [The steps for installing with MSYS2 (recommended)](https://developer.fyne.io/started/)
2. `go env -w CGO_ENABLED=1`
3. `go build`

That's it, thanks!

**Comment by Jarrettluo** [comment]
It's works!

**Comment by Jarrettluo** [comment]
It's works!
