### ISSUE TITLE
Move a window between two or more monitors cause unexpected resize

### ISSUE THREAD

**Issue by renathoaz** [fyne-io/fyne#3821]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Hi there, I have two monitors when I move my fyne app window between them the app window resizes even though my app is setted to  a fixed size. ```w.SetFixedSize(true)```.

I noticed that the same also happens with fyne_demo.

### How to reproduce

1. Grab window app and move between two monitors without releasing mouse click button
2. if you repeat it, sometimes the size changes again. Sometimes decreasing other times increasing the size.### 

### Screenshots

**1** - First run, before moving:
![Seleção_002](https://user-images.githubusercontent.com/16307350/231836368-37112403-a7e2-4986-a08d-0328bb786a19.png)
**2** - Moving to the second monitor and returning to the first one without releasing mouse click button:
![Seleção_003](https://user-images.githubusercontent.com/16307350/231836831-be5b9f65-de1b-42d0-83ac-8da9099c210d.png)

### Example code

```go 
package main

import (
	"fmt"
	"os"

	"lorem/wizard/assets"
	"lorem/wizard/navigator"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	var (
		fapp   = app.New()
		w      = fapp.NewWindow(fapp.Metadata().Name)
		router *navigator.Navigator
		err    error
	)

	installBtn := func() *widget.Button {
		b := widget.NewButtonWithIcon("Install",
			theme.MoveUpIcon(),
			func() {
				fmt.Println("test")
			})
		b.Importance = widget.HighImportance
		return b
	}
	logo := canvas.NewImageFromFile("assets/images/logo.png")
	logo.FillMode = canvas.ImageFillContain
	logo.ScaleMode = canvas.ImageScaleFastest
	logo.SetMinSize(fyne.NewSize(200, 200))

	router, err = navigator.New(w,
		navigator.Page{Path: "page1", Container: container.NewBorder(
			logo,
			nil,
			nil,
			nil,
			container.NewCenter(container.NewGridWithColumns(
				1,
				installBtn(),
			)),
		)},
	)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	w.SetIcon(assets.AppIcon)
	w.SetContent(router.CurrentPage.Container)
	w.CenterOnScreen()
	w.Resize(fyne.NewSize(544, 356))
	w.SetFixedSize(true)
	w.ShowAndRun()
}
``` 

### Fyne version

v2.3.3

### Go compiler version

go1.20.2

### Operating system and version

Ubuntu 22.04.2 LTS

### Additional Information

I'm new to Fyne,  That behavior doesn't happen with any other app on my Ubuntu, only with Fyne apps.

**Comment by andydotxyz** [comment]
The apps change size to accommodate the changing pixel density. This works on must systems ok.
Unfortunately it seems that Gnome does not allow a window to adapt whilst being dragged in some configurations.

I think there is another bug raised here but can't find it just now.

**Comment by andydotxyz** [comment]
I found it - #2704, closing as duplicate
