### ISSUE TITLE
Move cmd/fyne out to a tools repo

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3825]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The `cmd/fyne` package is currently using quite a few more modules than regular Fyne and it is polluting the `go.mod` file making it look like Fyne applications have more dependencies than they actually have. On top of this, the `cmd/fyne` package will get significantly larger once `fyne-cross` gets merged in meaning that moving it out might make development in the future.

### Is it possible to construct a solution with the existing API?

Maybe. There are a few changes that might need to be done (Android being notable). We should look into see if this is doable.

### Describe the solution you'd like to see.

We talked about creating a `fyne.io/tools/fyne` package on the call yesterday. Move it into there if it is possible.

**Comment by Jacalz** [comment]
Assigning me to check if this is doable for the moment. I might tackle the move as well but we get there when we get there :)

**Comment by Jacalz** [comment]
I have got this mostly working over at https://github.com/Jacalz/fynetools. The only problem is that the `go generate` command does not run the gendex code needed for the mobile packaging.

**Comment by Jacalz** [comment]
@andydotxyz  Did you have an idea for how we should get that working?

**Comment by andydotxyz** [comment]
I think the only way is for it to rely on the fyne repo being next to it at a parent folder...
Eventually we will get rid of this requirement but at least go generate only has to be run by the fyne developers and not by other coders.

**Comment by Jacalz** [comment]
I think I have the generation working now as of https://github.com/Jacalz/fynetools/commit/c320888f57617b81180119119d2f25b17a2a372b and https://github.com/Jacalz/fynetools/commit/72ad1f2ac29ea074eda5597d453907b2eb7faa7e. Workflows are now also up and running to verify that it is working as expected.

**Comment by andydotxyz** [comment]
Great news. Was it straight forward? Maybe we should catch up on the Friday call?

**Comment by Jacalz** [comment]
Yeah, it was quite straight forward. I was basically a one or two line fix to get it working. We can chat about it on Friday :)

**Comment by Jacalz** [comment]
Done :)
