### ISSUE TITLE
Add APIs for refreshing individial items in collections

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3826]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

This was discussed on the call yesterday. There are a few cases where you know which item index needs a refresh but the only way to refresh it is to refresh the whole collection using `.Refresh()`. We should add an API to refresh individual items in collections (cells in Table, rows in List and so on). As a bonus, the collection widget can be smart and avoid a refresh if the item is not currently visible.

### Is it possible to construct a solution with the existing API?

It should be possible

### Describe the solution you'd like to see.

Add an API to refresh individual items in collections (cells in Table, rows in List and so on).

**Comment by andydotxyz** [comment]
This is completed for v2.4.0 :)
