### ISSUE TITLE
Support for hot reloading

### ISSUE THREAD

**Issue by algoflows** [fyne-io/fyne#3830]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

App development is slow having to manually re-build the app everytime we want to see changes.

### Is it possible to construct a solution with the existing API?

Probably.

### Describe the solution you'd like to see.

Hot reload/rebuild of the app that preserves state in some way like flutter kotlin multiplatform/desktop, blazor, react, svelte, wails2. I would love to be able to save my code in editor and then the app window refreshes to reflect changes quickly and preserve the state.

I find it quite slow and cumbersome developing without hot reload/rebuild. I've gow for watching and rebuilding but everytime the built app reloads on the screen it launches smack bang in the middle and then the editor looses focus so I need to manually move the window out the way and then refocus my back into the editor. 

Ideally, the window would remember it's last placed position before closing to be rebuilt and then also once rebuilt and shown the vscode editor remains focused.

It would be amazing to have proper stateful hot reload/refresh feature would be the business and make developing in Fyne as nice as Flutter or Wails2.

**Comment by andydotxyz** [comment]
The framework is more oriented toward engineered code than UI tweaking. Have you explored the unit testing functionality? It should help to get that immediate feedback without the visual inspection loop?

**Comment by Bluebugs** [comment]
I don't think hot reloading is that doable with pure Go solution. It might also be that hot reload is maybe just a technical artifact of the lack of having an easy way to quickly adjust and see what something look like when using those different technical solution. In the case of Fyne, as @andydotxyz is saying, it isn't engineered to have a lot of UI tweaking which means the work is mostly in assembling widget and container together, something I think we can do better than by just hacking on hot reload. A long time ago, it was possible to do UI design quickly with tools like Visual Basic, Delphi and so on, a bit of a lost knowledge this days, but I did put a post about it to gather ideas for it, if you are interested: https://fynelabs.com/2023/04/14/making-graphical-application-development-simple/

**Comment by algoflows** [comment]
Hey all, hot reload is basically expected now when building UI, it is the case. I immediately didn't enjoy the devex in Fyne coming from a plethora of other solutions working for an innovation lab we've tried them all. Devex is hugely important now and close to immediate refresh is what many developers expect when so many UI development toolkits already have those solutions built in. Having to manually rebuild the app is pretty behind the curve. Just providing feedback.

**Comment by algoflows** [comment]
Vlang managed to support hotreload, hoping you rethink this. Also, many coders prefer not to use low code builders because eventually we need to cut eventually.

**Comment by algoflows** [comment]
I mean a mini fix, would be automatic recompilation on file changes but whenever that happens the window closes and then re-opens in another part of the screen if you've moved the window to develop around the editors placement. Ideally a fix would be that the window position is remembered and when recompilation happens the window opens in the last position it was before recompilation. This would give a basic reload feature, it won't be as fast as other solutions but would be similar.

**Comment by andydotxyz** [comment]
> I mean a mini fix, would be automatic recompilation on file

I don't think that's a good approach - it only works for trivial applications without any app state. The Go approach to building robust software that lasts and can be collaborated on is so much more important than real-time rendering of the code changes. Lean on unit tests more than design confirmation and Fyne will work well for you.

You may be interested in #554 as it relates to what you were proposing (and you can monitor files to recompile in your own build environment if you would like).

**Comment by andydotxyz** [comment]
Closing as design driven hot-reload development doesn't really align with what we consider important for the Fyne design principles.

**Comment by algoflows** [comment]
Well that's a shame, Vlang has implemented hot/live reload and almost all new modern UI development technologies have it as standard now. 

Closing this, doesn't fill me with confidence in the direction of Fyne. Such a shame as it looks promising. Developer experience should be up on the list and hot reload or live preview features are expected as they're so prevalent. 

At the very least having the save window position so when we recompile with file watchers that I don't need to reorganize the windows each time I want to test changes to an application. 

Oh well, moving on.

**Comment by andydotxyz** [comment]
The Fyne developers passionately believe in developer experience as well. We have our own design direction and it aligns well with Go.

As my prior message linked, you can see that remembering windows is on our todo list. If you consider hot reload for design based coding essential then other toolkits probably fit your requirements better.

I believe I have described our design decisions and outlined our plan for other ways to make app building easier. Hot reloading of code changes at this level is not required to make the tooling we plan, and very few developers are actually requesting it.

**Comment by algoflows** [comment]
Saying not many developers are requesting it from a tiny pool of developers isn't the metric to be validating and providing features that would attract the larger market to use the tooling. Looking at all cross platform tooling all support live reload of some kind. I guess the bar set by most modern cross platform must be wrong.

Will check back from time to time, I have a sneaky feeling you'll come around eventually. As they say on a long enough time horizon everyone is right.

**Comment by argigeek** [comment]
> Saying not many developers are requesting it from a tiny pool of developers isn't the metric to be validating and providing features that would attract the larger market to use the tooling. Looking at all cross platform tooling all support live reload of some kind. I guess the bar set by most modern cross platform must be wrong.
> 
> Will check back from time to time, I have a sneaky feeling you'll come around eventually. As they say on a long enough time horizon everyone is right.

You can use Air for Go (Livel Reloading).

[https://github.com/cosmtrek/air](https://github.com/cosmtrek/air)
