### ISSUE TITLE
Expose bind to facilitart custom bindings

### ISSUE THREAD

**Issue by aodhan-domhnaill** [fyne-io/fyne#3835]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

It's hard to make custom bindings for other types (eg. time.Time).

I would like `bind` exposed publicly. https://github.com/fyne-io/fyne/blob/master/data/binding/binding.go#L59

### Is it possible to construct a solution with the existing API?

Yes, but a lot of code duplication

### Describe the solution you'd like to see.

```
type base struct {
	listeners sync.Map // map[DataListener]bool

	lock sync.RWMutex
}
```

To,

```
type Base struct {
	listeners sync.Map // map[DataListener]bool

	lock sync.RWMutex
}
```

Happy to put out a PR if the maintainer agrees with this.

**Comment by aodhan-domhnaill** [comment]
Makes sense.

**Comment by Jacalz** [comment]
There are a few examples in https://github.com/fyne-io/fyne-x/tree/master/data/binding.
