### ISSUE TITLE
PopUp appears at window border

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#385]
When NewPopUp is called, it appears at the window border, popup ought to be slightly above or below the clicked button.
![Screenshot from 2019-08-04 23-54-00](https://user-images.githubusercontent.com/31141573/62430766-b8db7900-b718-11e9-94bd-0260edf920fd.png)

**Comment by andydotxyz** [comment]
NewPopUp is not actually loading a menu relative to the click position (there is no position passed to the constructor) - you have to reposition it yourself. This is because of PopUp being  used for many different things like dialogs, drop downs etc.

After you call `NewPopUp()`, you should add something like:
```go 
widgetPos := fyne.CurrentApp().Driver().AbsolutePositionForObject(myWidget)
mousePos := fyne.NewPos(widgetPos.X+event.Position.X, widgetPos.Y+event.Position.Y)
myPopup.Move(mousePos)
```
From there you can adjust position as you see fit.

**Comment by metaclips** [comment]
This panics at line 1
`panic: interface conversion: fyne.Canvas is nil, not *gl.glCanvas

goroutine 11 [running]:
fyne.io/fyne/internal/driver/gl.(*gLDriver).AbsolutePositionForObject(0xc00000e280, 0x764ca0, 0xc0000801e0, 0x0, 0x0)
	/home/michael/go/pkg/mod/fyne.io/fyne@v1.1.0/internal/driver/gl/driver.go:35 +0x1b7
main.main.func8()
	/home/michael/Desktop/programming/golang/recreateError/main.go:63 +0x9f
fyne.io/fyne/widget.(*Button).Tapped(0xc000169650, 0xc000300c30)
	/home/michael/go/pkg/mod/fyne.io/fyne@v1.1.0/widget/button.go:209 +0x6d
created by fyne.io/fyne/internal/driver/gl.(*window).mouseClicked
	/home/michael/go/pkg/mod/fyne.io/fyne@v1.1.0/internal/driver/gl/window.go:646 +0xd48`

**Comment by andydotxyz** [comment]
Are you sure you passed in the right object? That can happen if you ask for information about an object that has not been rendered.

**Comment by metaclips** [comment]
> Are you sure you passed in the right object? That can happen if you ask for information about an object that has not been rendered.

Yes, this works perfectly, thanks chief.
