### ISSUE TITLE
canvas.Line not a CanvasObject

### ISSUE THREAD

**Issue by raymon68** [fyne-io/fyne#3859]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

using fyne.io/fyne/v2 v2.3.4

Cannot add canvas.Line to []CanvasObject because canvas.Line does not follow CanvasObject .
According to `go run .`  canvas.Line has a Hide() but it is no good for CanvasObject because the receiver is a *canvas.Line.

I am making a widget and this is occuring as I try to prepare the return []CanvasObject for the Objects() function to adhere to the WidgetRenderer interface.

I was originally using canvas.Rect for the same widget renderer Objects() and no problem.

### How to reproduce

Sample code defines the problem

### Example code

```go

type lineWidgetRenderer struct {
	lineWidget *LineWidget
	lines      []canvas.Line
	currSize   fyne.Size
}


func (lwr lineWidgetRenderer) Objects() []fyne.CanvasObject {

	co := []fyne.CanvasObject{}

	for _, l := range lwr.lines {

		co = append(co, l) //<--Error here
	}

	return co

}
```

### Fyne version

2.3.4

### Go compiler version

go version go1.20.4 linux/amd64

### Operating system and version

Fedora release 38 (Thirty Eight)  kernel: 6.2.13-300.fc38.x86_64

**Comment by dweymouth** [comment]
`*canvas.Line` is a CanvasObject. At your line where the error occurs, you can do this instead: ```co = append(co, &l)```

**Comment by Jacalz** [comment]
Indeed. Either use a list of *canvas.Line or use the reference as mentioned above. The methods take a pointer receiver and thus you need to use a reference to the struct. This is strive for pretty much all interfaces as far as I know.

**Comment by andydotxyz** [comment]
> `*canvas.Line` is a CanvasObject. At your line where the error occurs, you can do this instead: `co = append(co, &l)`

Actually I would recommend making the change higher up, so:
```go
lines      []*canvas.Line
```
That is more in keeping with the design - with that change `append(co, l) will work as expected.
