### ISSUE TITLE
Scrolling in Table Widget is slow with a lot of rows

### ISSUE THREAD

**Issue by mdmdmdmdmd** [fyne-io/fyne#3860]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If i add several hundreds of thousands of rows into a table, scrolling becomes very slow, and uses lots of cpu resources.

### How to reproduce

[fynetable.zip](https://github.com/fyne-io/fyne/files/11390178/fynetable.zip)

build, run, push "Test" button, and try to scroll (to the bottom)

### Example code

```go
```

### Fyne version

2.3.3 but also develop branch from 2023-05-02

### Go compiler version

1.20.3

### Operating system and version

Windows 11

**Comment by Jacalz** [comment]
Please provide example code the in future. It makes it a lot easier to test and verify bugs.

**Comment by andydotxyz** [comment]
Further to that:

> [fynetable.zip](https://github.com/fyne-io/fyne/files/11390178/fynetable.zip)
> build, run, push "Test" button, and try to scroll (to the bottom)

I am sure the reporter will understand that we don't download code bundles and run them in pursuit of replicating issues.
1) it is a bit of a security issue
2) Working on peoples own code repositories is more of a support issue and is reserved for project sponsors

A code sample would be much easier to work with. However I do think that this was addressed by #3861
