### ISSUE TITLE
I click the systray `quit` . by the app not quit 

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#3869]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I click the systray `quit` . but the app not quit , and the app main window may be  quit or  hide.

![image](https://user-images.githubusercontent.com/37319319/236454704-bb8a81ec-8e11-477a-b80c-280fa9c67d24.png)

![image](https://user-images.githubusercontent.com/37319319/236454107-698b59a0-c1f8-41a2-8daa-e3c91588fe72.png)

![image](https://user-images.githubusercontent.com/37319319/236454311-167054ad-3619-4e46-bab2-cc2a723161e9.png)

### How to reproduce

1. add systray 
2. click `quit`
3. but not quit

### Example code

```go
	a := app.New()
	w := a.NewWindow("快码网点端")

	w.SetContent(widget.NewLabel("网点服务启动成功\n请不要退出"))
	w.Resize(fyne.NewSize(250, 50))
	w.SetOnClosed(func() {
		logs.Info("1")
	})

	//https://developer.fyne.io/explore/systray
	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetCloseIntercept(func() {
		w.Hide()
		logs.Info("退出")
	})

	w.ShowAndRun()
```

### Fyne version

2.3.4

### Go compiler version

1.20.4

### Operating system and version

windows 10

**Comment by andydotxyz** [comment]
The quit operation tries to close all windows before exiting. By using the close veto and not closing the window you are forcing it not to exit...
