### ISSUE TITLE
tinygo:wasm-ld: error: /var/folders/.../tinygo1760742876/main.o: undefined symbol

### ISSUE THREAD

**Issue by BorzdeG** [fyne-io/fyne#3873]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

```
tinygo:wasm-ld: error: /var/folders/_c/0y69nbgd6070hmt232mrhg640000gn/T/tinygo1760742876/main.o: undefined symbol: os/signal.signal_recv
tinygo:wasm-ld: error: /var/folders/_c/0y69nbgd6070hmt232mrhg640000gn/T/tinygo1760742876/main.o: undefined symbol: os/signal.signal_enable
failed to run tool: wasm-ld
error: failed to link /var/folders/_c/0y69nbgd6070hmt232mrhg640000gn/T/tinygo1760742876/main: exit status 1
```

### How to reproduce

1. Create main.go by [Hello World](https://developer.fyne.io/started/hello)
2. compile using TinyGo: `tinygo build -target wasm ./...`

### Example code

```go


package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
```

### Fyne version

2.3.4

### Go compiler version

1.20.4

### Operating system and version

MacOS Ventura 13.4 (chip: Apple M1 Pro)

### Additional Information

TinyGo: tinygo version 0.27.0 darwin/amd64 (using go version go1.20.4 and LLVM version 15.0.0)

**Comment by Bluebugs** [comment]
Please test develop, it does compile, but take a very long time. The resulting binary crash at startup and I couldn't figure why.

**Comment by BorzdeG** [comment]
If I understand correctly, the problem is using time.Sleep : https://github.com/tinygo-org/tinygo/issues/310

**Comment by Bluebugs** [comment]
Yeah, they are unnecessary for the wasm case and disable on develop normally (last time I checked). You will also need the develop branch of tinygo with reflection support. 
.

**Comment by Bluebugs** [comment]
But note that their is a crash in tinygo included code in the initialization of some map.

**Comment by BorzdeG** [comment]
Hmm... TinyGo seems to support reflection in recent versions...

All right, I will collect while the standard compiler. True, this results in a too large file - ~20Mb :( It seems to be too much for "Hello World"

**Comment by Bluebugs** [comment]
Yes, you need to disable symbols. I forgot the flags, but the binary should be around 9mb at the end.

**Comment by Bluebugs** [comment]
And if your cdn does compress file, the delivered final binary over the network should be around 3 to 4 mb.

**Comment by andydotxyz** [comment]
Also the file size relates to the full Go runtime and C libraries compiled in to make the graphics work and various standard icons etc. "Hello world" will be approx the same as a medium sized application as the actual code is a very low percentage in small applications.
