### ISSUE TITLE
Text not visible in fyne app

### ISSUE THREAD

**Issue by islippers** [fyne-io/fyne#3879]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

All text in any content tab or button is not visible. Not sure if there is a setting somewhere that needs to be set. 
I have also ran the fyne demo app with the same results. See screen shot. 

### How to reproduce

Run go run fyne.io/fyne/v2/cmd/fyne_demo@latest on linux mint.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/30820690/f9b93b03-6a30-4cd9-a696-097663875657)

### Example code

go run fyne.io/fyne/v2/cmd/fyne_demo@latest

### Fyne version

latest 

### Go compiler version

1.18

### Operating system and version

Linux Mint

**Comment by andydotxyz** [comment]
One other person has reported this and it seems to relate to the graphics driver. Can you compare what hardware you are using and what OpenGL / graphics driver versions?

**Comment by heejit** [comment]
I am using Windows7  vm via Virtual-Box in ubuntu 20.04 I have used 

fyne version develop : fyne.io/fyne/v2 v2.3.6-0.20230614212946-594e3eb17bc8

![Screenshot_2023-06-15_13-46-25](https://github.com/fyne-io/fyne/assets/11409425/ebe7f024-7223-4ecb-b36f-f74903a3f853)

Vm configuration:
![windows7-vm-Screenshot_system_config](https://github.com/fyne-io/fyne/assets/11409425/e6f63218-a333-49e3-ab69-3d85473e1763)

**Comment by Jacalz** [comment]
Hi @heejit. Can you please test on `develop` now? I think it might have been resolved.

**Comment by heejit** [comment]
I have tested with :  fyne.io/fyne/v2 v2.3.6-0.20230812072749-e63d4e8030ef 

it is working fine thanks.
