### ISSUE TITLE
Disabled RadioGroup does not display status

### ISSUE THREAD

**Issue by XanderCheung** [fyne-io/fyne#3882]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In version 2.3.4, the radio group item does not display the selected status correctly when radio group is disabled.

### How to reproduce

1. SetSelected 
2. Disable radio group

### Screenshots

![20230511150408](https://github.com/fyne-io/fyne/assets/28296509/c52dfc0a-849d-4ac7-a2b5-6cec735665c4)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	normalGroup := widget.NewRadioGroup([]string{"A", "B", "C"}, func(string) {})
	normalGroup.SetSelected("A")

	disabledGroup := widget.NewRadioGroup([]string{"A", "B", "C"}, func(string) {})
	disabledGroup.SetSelected("A")

	// disable
	disabledGroup.Disable()

	w.SetContent(container.NewVBox(
		normalGroup,
		widget.NewLabel(fmt.Sprintf("normalGroup selected: %s", normalGroup.Selected)),
		disabledGroup,
		widget.NewLabel(fmt.Sprintf("disabledGroup selected: %s", disabledGroup.Selected)),
	))

	w.ShowAndRun()
}

```

### Fyne version

2.3.4

### Go compiler version

1.19.2

### Operating system and version

macOs Monterey

**Comment by andydotxyz** [comment]
Fixed on develop and release/v2.3.x ready for v2.3.5
