### ISSUE TITLE
AppTabs has overlapping tabs in VBox or HBox

### ISSUE THREAD

**Issue by shangdan1987** [fyne-io/fyne#3885]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

AppTabs has overlapping tabs in VBox or HBox;
After preliminary verification,
container.TabLocationTop, container.TabLocationBottom -->AppTabs has overlapping tabs in HBox

container.TabLocationLeading and container.TabLocationTrailing -->AppTabs has overlapping tabs in VBox

### How to reproduce

must appear

### Screenshots

![Uploading Snipaste_2023-05-12_16-41-12.png…]()

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("X2demo")

	searchEntry := widget.NewEntry()
	searchEntry.SetPlaceHolder("some message")

	tabs := container.NewAppTabs(
		container.NewTabItem("devices info", widget.NewLabel("Hello")),
		container.NewTabItem("mqtt ", widget.NewLabel("World!")),
	)
	tabs.Append(container.NewTabItemWithIcon("Home", theme.HomeIcon(), widget.NewLabel("Home tab")))
	tabs.SetTabLocation(container.TabLocationLeading)

	container := container.NewVBox(
		searchEntry,
		tabs,
		layout.NewSpacer(),
		widget.NewLabel("log info"),
	)

	myWindow.SetContent(container)
	myWindow.Resize(fyne.NewSize(800, 600))
	myWindow.ShowAndRun()
}
```

### Fyne version

2.3.4

### Go compiler version

1.19.3

### Operating system and version

win11

**Comment by shangdan1987** [comment]
DocTabs also exhibit the same phenomenon

**Comment by andydotxyz** [comment]
The screenshot does not seem to be working - can you upload it again?

**Comment by shangdan1987** [comment]
<img width="146" alt="微信图片_20230513170518" src="https://github.com/fyne-io/fyne/assets/24599292/43b4ad88-98b9-47a3-bfa9-8a3e8c10743c">

**Comment by andydotxyz** [comment]
Fixed on develop and release branch ready for v2.3.5
