### ISSUE TITLE
New Event: OnClick

### ISSUE THREAD

**Issue by drakbar** [fyne-io/fyne#389]
So the Tapped event is nice, but the trigger for it is on release of the mouse button. 

It would be nice to have an event that is triggered when the mouse button changes from not pressed to being pressed.

A practical use that I can think of for this would be an increment or decrement button that has a large range of values. Instead of clicking and releasing for each value, it would be nice to be able to click and hold and having the values change in proportion to how long its been held down.

**Comment by andydotxyz** [comment]
This is tricky. Should it be desktop specific? Mouse interactions and touchscreen mobiles are different and we are trying to do both. I suppose “OnHeld” could work.

If you want something just for desktop then you could use “desktop.OnMouseDown” as we have some mouse handlers in the desktop driver.

**Comment by drakbar** [comment]
Yea I would imagine that it would be isolated to desktop, mainly I am just suggesting the event be exposed not the implementation that deals adjusting the incremental step. 

This is a picture what I was thinking of.
![button](https://user-images.githubusercontent.com/20728117/62664168-2c130400-b940-11e9-8ace-a2400d53dbc1.png)

An alternative to this is a slider bar (which I am currently working on at the moment), but there are other issues with this type of mechanism. The biggest issue with the slider is that there is a trade off between precision and value range.

**Comment by andydotxyz** [comment]
What if we added a new interface that exposed TapHold and TapEnd? the TapHold would trigger after a short period of holding and TapEnd would occur when the button or finger lifts.
If the widget under mouse/finger responds to this I imagine it would trump the Tapped and TappedSecondary?

This is complex as we have to consider TappedSecondary on mobile as tap+hold whereas on desktop it's just a right click. perhaps TappedSecondary and TapHold are mutually exclusive on mobile? This sounds possible though :)

**Comment by andydotxyz** [comment]
Thinking all this through maybe it should just be desktop specific - and if so then the events are already in place.
Looking at the spinner example it's too fiddly for a phone and they typically have popups of some sort to handle that kind of input...

**Comment by drakbar** [comment]
I personally couldn't think of a use case of where someone would encounter this type issue on mobile. It is just my personal opinion that it is because software on mobile is designed as a different experience than that of desktop. It not a qualitative opinion but more of a functional one.

**Comment by andydotxyz** [comment]
Yes I think you're probably right. In which case there is desktop.MouseDown and desktop.MouseUp to handle this :).
