### ISSUE TITLE
Fastest scale mode is not working on Linux arm64 device

### ISSUE THREAD

**Issue by vinser** [fyne-io/fyne#3891]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I use ImageScaleFastest scale mode I've got
```
2023/05/15 21:21:57 Fyne error:  Invalid canvas.ImageScale value (2), using canvas.ImageScaleSmooth as default value
2023/05/15 21:21:57   At: /home/vinser/go/pkg/mod/fyne.io/fyne/v2@v2.3.4/internal/painter/gl/texture.go:195
``` 

### How to reproduce

1. Run the code beneath 

### Example code

```go
func main() {
	a := app.New()
	w := a.NewWindow("Test Fyne")
	img := canvas.NewImageFromFile("20141014_040331.jpg")
	img.FillMode = canvas.ImageFillContain
	img.ScaleMode = canvas.ImageScaleFastest
	w.SetContent(container.NewMax(img))
	w.Resize(fyne.NewSize(500, 500))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.3.4

### Go compiler version

go version go1.20.4 linux/arm64

### Operating system and version

Ubuntu 22.04

**Comment by Jacalz** [comment]
This has been fixed an will be in the next v2.3.5 release.
