### ISSUE TITLE
Android bad handling of destroy() event (orientation change, back button) At least on emulator

### ISSUE THREAD

**Issue by blaize** [fyne-io/fyne#3895]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have the exact same problem as described here : https://github.com/fyne-io/fyne/issues/677
I only tested on BlueStack emulator on Windows 11.

It also occur when I open a file dialog, it go on the android file manager and when It come back to the app, there is only a black screen.

### How to reproduce

1/ Copy the code snippet
2/ fyne package -os android -appID com.exemple.test
3/ Import .apk package into BlueStack
4/ Run the app
5/ Click on open file
6/ Select a file from your emulator drive
7/ Click on open
8/ You should have a black screen.

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("com.exemple.test")

	w := a.NewWindow("test window")
	lbl2 := widget.NewLabel(a.Storage().RootURI().Path())

	btn := widget.NewButton("open file", func() {
		dialog.ShowFileOpen(func(uc fyne.URIReadCloser, err error) { lbl2.SetText(uc.URI().String()) }, w)
	})

	w.SetContent(container.NewVBox(lbl2, btn))

	w.ShowAndRun()
}

```

### Fyne version

fyne version : fyne cli version: v2.3.4

### Go compiler version

go version : go version go1.20.4 windows/amd64

### Operating system and version

Windows 11

### Additional Information

BlueStack AppPlayer 5.11.56.1003 N32

**Comment by andydotxyz** [comment]
I don't know if anyone has tested on that emulator. Can you try an official one and compare?

**Comment by blaize** [comment]
Hello, you right I tested on android studio emulator and it's work fine. I guess BlueStack have something special. Don't know if it worth to investigate to make fyne works on BlueStack or not.
By the way, I can now test my app on another emulator and it's all I wanted.

**Comment by andydotxyz** [comment]
I think really we can't commit to fixing issues in non-standard emulators.
Issues reported against "android compatible" devices are not supported so I guess we put this in the same category.
