### ISSUE TITLE
DocTab selection underline not updated when deleting an Item

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#3905]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Deleting a tab item N, while N+1 is selected, will not update the selection underline bar.

### How to reproduce

Run the code, add 3 tabs, select tab 2, close tab 1, see the selection bar is under tab 3 rather than 2

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/1791230/b74674c5-e385-49c5-90d4-326352a35ff9)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	tab := container.NewDocTabs()

	count := 1
	btn := widget.NewButton("Add Tab", func() {
		tab.Append(container.NewTabItemWithIcon(
			fmt.Sprintf("Tab Item %d", count), theme.HomeIcon(), widget.NewLabel(fmt.Sprintf("Tab Content %d", count)),
		))
		tab.SelectIndex(len(tab.Items) - 1)
		count += 1
	})

	w.SetContent(container.NewBorder(btn, nil, nil, nil, tab))
	w.ShowAndRun()
}
```

### Fyne version

develop v2.3.4-rc1.0.20230516195251-56dd0f3e0f32

### Go compiler version

1.20

### Operating system and version

Windows 10

**Comment by Jacalz** [comment]
> I also encounter sometimes crash when adding a tab and selecting it.
> 
> I'll try to reproduce...

Please keep one problem per issue. If there is another crash then open a new issue.

**Comment by matwachich** [comment]
Unfortunatly, [this PR](https://github.com/fyne-io/fyne/pull/3983) did not solve this bug report.

Try the code above :

- Add 3 tabs
- Select 2nd tab
- Close first tab

see selection bar not syncronized.

**Comment by andydotxyz** [comment]
Fixed on develop :)
