### ISSUE TITLE
Running the app in sudo mode reports an error

### ISSUE THREAD

**Issue by neujl** [fyne-io/fyne#3926]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I running the app in sudo mode reports an error:
sslvpn@sslvpn-KaiTianM739T:/tmp$ sudo /usr/bin/safeconnect
[sudo] sslvpn 的密码：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xca1c78]

goroutine 1 [running, locked to thread]:
github.com/godbus/dbus/v5.(*Conn).export(0x40000bf7c8?, 0x40000bf798?, {0x34d44e?, 0x6?}, {0x3549ec?, 0x84a5d8?}, 0x88?)
        github.com/godbus/dbus/v5@v5.1.0/export.go:383 +0x28
github.com/godbus/dbus/v5.(*Conn).exportMethodTable(0x29fce0?, 0x40000bf9f8?, {0x34d44e?, 0x13?}, {0x3549ec?, 0x1a?}, 0x60?)
        github.com/godbus/dbus/v5@v5.1.0/export.go:367 +0xb4
github.com/godbus/dbus/v5.(*Conn).ExportSubtreeMethodTable(...)
        github.com/godbus/dbus/v5@v5.1.0/export.go:346
fyne.io/systray/internal/generated/notifier.ExportStatusNotifierItem(0x0?, {0x34d44e, 0x13}, {0x462148?, 0x1adad00})
        fyne.io/systray@v1.10.1-0.20220621085403-9a2652634e93/internal/generated/notifier/status_notifier_item.go:192 +0x2e8
fyne.io/systray.nativeStart()
        fyne.io/systray@v1.10.1-0.20220621085403-9a2652634e93/systray_unix.go:168 +0x64
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x400049e000)
        fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/loop.go:117 +0x124
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0x40004b0000?)
        fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/driver.go:164 +0x38
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0x40004b0000)
        fyne.io/fyne/v2@v2.2.3/internal/driver/glfw/window.go:230 +0x2c
main.main()
        safeconnect/main.go:137 +0x7dc
sslvpn@sslvpn-KaiTianM739T:/tmp$ cd /home/work/

If i running app in normal mode, the application running ok
My OS is kylin.

### How to reproduce

1. install application
2. running app in terminal with sudo mode

### Example code

```go
func main() {
...
	if desk, ok := a.(desktop.App); ok {
		//makeSubMenu(a, w, desk, tabs, tunnel, tunnellog, route)
		mySystray(a, w, desk)
	}
...
}
...
func mySystray(a fyne.App, w fyne.Window, desk desktop.App) {
	m := fyne.NewMenu("MyApp",
		fyne.NewMenuItem("Show", func() {
			w.Show()
		}))
	desk.SetSystemTrayMenu(m)
}
```

### Fyne version

2.2.3

### Go compiler version

1.19

### Operating system and version

kylin, like debian

**Comment by andydotxyz** [comment]
Running a graphical app as root normally doesn't work because it cannot connect to your graphics or system buses. Does this work for other graphical apps on your system?

We certainly should fix the crash, but I'm not sure if that will resolve the underlying issue of it not working.

**Comment by andydotxyz** [comment]
This was fixed a number of releases ago (back in February). Please upgrade your Fyne library.
