### ISSUE TITLE
x\text\encoding reading unexpected EOF error

### ISSUE THREAD

**Issue by devcomcool** [fyne-io/fyne#393]
Source :
package main

import (
	"fyne.io/fyne/widget"
	"fyne.io/fyne/app"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))

	w.ShowAndRun()
}

Error:
# command-line-arguments
2019/08/10 00:03:00 C:\Workspace\pkg\windows_amd64\fyne.io\fyne\vendor\golang.org\x\text\encoding\korean.a(_go_.o): error reading unexpected EOF

Go env:
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Workspace
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build051799950=/tmp/go-build -gno-record-gcc-switches

PATH:
PATH=C:\Program Files (x86)\NetSarang\Xshell 6\;
C:\ProgramData\Oracle\Java\javapath;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Workspace\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\ProgramData\ComposerSetup\bin;C:\webServer\mysql\bin;
C:\webServer\php-7.2.11-Win32-VC15-x64;
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\Git\cmd;
C:\Go\bin;
C:\TDM-GCC-64\bin;
C:\Workspace\bin;
C:\Users\user\AppData\Local\Microsoft\WindowsApps;
C:\Users\user\AppData\Roaming\Composer\vendor\bin;
C:\Program Files\Java\jdk1.8.0_144\bin;
C:\Users\user\AppData\Local\atom\bin;
C:\Users\user\AppData\Local\Microsoft\WindowsApps;
C:\Users\user\AppData\Local\GitHubDesktop\bin;
C:\Users\user\go\bin

**Comment by andydotxyz** [comment]
I don't think this is a Fyne issue but something about the files on your system (for example another reported https://webcache.googleusercontent.com/search?q=cache:X3lWqaxawwYJ:https://stackoverflow.com/questions/57074135/how-to-handle-eof-error-while-building-go-application+&cd=3&hl=en&ct=clnk&gl=uk)

Can you try removing the Fyne code and trying again? Perhaps something broke when the code was downloaded? Or it could be a hard drive issue?

**Comment by devcomcool** [comment]
@andydotxyz 
Thanks. 

PS C:\Workspace> go run test/test.go
# command-line-arguments
2019/08/13 17:36:59 C:\Workspace\pkg\windows_amd64\fyne.io\fyne\vendor\golang.org\x\text\encoding\korean.a(_go_.o): error reading unexpected EOF
PS C:\Workspace> rm c:\workspace\pkg\windows_amd64\fyne.io\fyne\vendor\golang.org\x\text\encoding\korean.a

Deleting the korean.a file causes normal output

Thanks

**Comment by andydotxyz** [comment]
great, thanks for letting us know :)
