### ISSUE TITLE
App hangs when dragging window to external display

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#394]
This may not be present in 1.1 release - verify first...

**Comment by andydotxyz** [comment]
That's gone away now @steveoc64 :)

**Comment by steveoc64** [comment]
ah yes, was seeing that on mac when dragging the window between monitors.  (Sat-1 spinning ball of death)

Will try that again in a couple of hours and confirm that the fix applies in the Sth Hemisphere :)
