### ISSUE TITLE
Add notifications support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#398]
Initial version could be just text.
We should explore if icons can be attached across our supported platforms as well.
This needs to hit Windows, macOS, Linux, iOS and Android..!

**Comment by dhinojosac** [comment]
I'm using this library https://github.com/gen2brain/beeep  in my chat app. Maybe this one could work.

**Comment by andydotxyz** [comment]
Trying to get a simple API together and I have come up with this. Open to discussion pre-PR just in case :)

**Declaration**
```
App.SendNotification(*Notification)


type Notification struct {
	Title, Content string
}

func NewNotification(title, content string) *Notification {
	return &Notification{Title: title, Content: content}
}
```

**Usage**
```
			fyne.CurrentApp().SendNotification(&fyne.Notification{
				Title:   "Form for: "+name.Text,
				Content: largeText.Text,
			})
```

Using a concrete type (like menus) we can add new fields in the future with no breakage.
Like icons, timeouts, delays etc...

**Comment by andydotxyz** [comment]
In addition to Title and Content text we will (system dependent) display the app name and icon, inferred from the app data or packaging.

**Comment by andydotxyz** [comment]
On develop for testing
