### ISSUE TITLE
tabItem did not removed on screen after remove all tabItems from AppTabs

### ISSUE THREAD

**Issue by spxvszero** [fyne-io/fyne#3980]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Remove all tabs from AppTabs, the last tab item did not remove on screen.

### How to reproduce

1、create new container.AppTabs without container.TabItems,  show it in window.
2、the view shown on window is an empty page with a seperator line on top. this line is between tabs and content.
3、create a new container.TabItems and add in AppTabs. it is ok while render on window.
4、remove this tabItem. The tab content is removed on window,  but the tab did not removed, the tab title still remain on window.

### Screenshots

![before](https://github.com/fyne-io/fyne/assets/14317611/2d97e970-1cb8-44a3-beaa-49a43e913a84)
![add](https://github.com/fyne-io/fyne/assets/14317611/b65f7c62-e49a-4923-ab92-0bd3aa1c5b48)
![bug](https://github.com/fyne-io/fyne/assets/14317611/89442f08-3a44-41a5-ab64-017ec10ab8ec)

### Example code

```go
templabel := widget.NewLabel("Contents for this " +title + " Tab")
c := widget.NewButton("Close", func() {
	clearTab(title)     //Close Tap Item
})

tItem := container.NewTabItem(title,
	container.NewVBox(
		templabel,c),
)
tabContainer.Append(tItem)         //Add Tap Item
```

This is clearTab func done:
```go
tabContainer.RemoveIndex(idx)
tabContainer.Refresh()
keyWindow.Content().Refresh()
```

### Fyne version

v2.3.3

### Go compiler version

1.17.7

### Operating system and version

macOS Catalina 10.15.7

### Additional Information

I found the problem is this code : 
[https://github.com/fyne-io/fyne/blob/1834d704a305f4729cce65213f5b5c3098e1d993/container/apptabs.go#L278-L301](url)

which line is :
```
for i := len(r.appTabs.Items); i > 0; i-- {
```

I change to :
```
for i := len(r.appTabs.Items); i >= 0; i-- {
```

and the problem is fixed.

**Comment by andydotxyz** [comment]
Thanks so much for finding this and hunting down a solution.
Would you consider opening a PR and a little unit test as you have found the fix already?

**Comment by spxvszero** [comment]
@andydotxyz Well, i have already make pull request #3983
