### ISSUE TITLE
New default theme updates (Rounded corners) missing on some of the built in widgets.

### ISSUE THREAD

**Issue by ismyhc** [fyne-io/fyne#3981]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [x] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Im currently working in develop for the new default theme which has a lot of new rounded items like buttons, entries, etc. This is amazing step forward in an out of the box good style for fyne. Ive found a handful of other builtins that IMO should also adopt round corners to complete this look.

- Card border needs rounded corners
- List selection needs rounded corners
- Tree selection needs rounded corners
- Table selection needs rounded corners
- Dropdown menu container when opened needs rounded corners
- All dialog containers / splash needs rounded corners

It's also worth noting that list & tree selection should probably not have separators (or at least be able to be turned off). Hiding this looks sooo much better imo. I understand this can be done via theme and making separator transparent, but that affects using separators in other areas "I think ".

Also these may be more of taste and need more thought to be changed but could potentially be solved with rounded corners

- Scroll indicators look out of place. Consider rounded corners
- Split indicator looks out of place. Not exactly sure design direction here
- Tabs/Doc Tabs really look bad. Consider using current button style. Maybe even like gtk grouped buttons.

Attaching some images describing some of the issues above.

<img width="746" alt="Screenshot 2023-06-17 at 8 09 11 AM" src="https://github.com/fyne-io/fyne/assets/840551/bc136232-64f5-4fa0-902e-83a5e7c1e875">
<img width="831" alt="Screenshot 2023-06-17 at 8 10 58 AM" src="https://github.com/fyne-io/fyne/assets/840551/1cddbf97-f55b-4a06-81e1-ede7cdb63235">
<img width="867" alt="Screenshot 2023-06-17 at 8 11 14 AM" src="https://github.com/fyne-io/fyne/assets/840551/8ddc84af-022c-4859-9e11-206a0d9484e2">

### Describe the solution you'd like to see.

I think a lot of this was probably just missed in the default theme update. Some of these need more thought probably.

Once I understand how these work I could possibly help on this :)

Ive created this at @andydotxyz request instead of just putting slack one by one as I find them :)

**Comment by Jacalz** [comment]
Adding this as blocker for now. The dialog shadow makes the transition to rounded corners a little bit harder there but we should try to do as much as possible with this to make sure we have good consistency. I think the hover and selection for things like tabs and collection widgets is the most important at the moment.

**Comment by Jacalz** [comment]
Notes from today's meeting:
- We are aiming for selection to use rounded corners for the upcoming release. Rounded shadows require more work and will not make it for v2.4.0 unfortunately.

For the one working on this, this is how Adwaita handles rounded selection: 
![image](https://github.com/fyne-io/fyne/assets/25466657/b0c36716-e731-4136-b3ac-21819128750c)
![image](https://github.com/fyne-io/fyne/assets/25466657/0bf62ae0-1822-4557-8b84-ab306b9199d4)

**Comment by Jacalz** [comment]
I believe that basically all in this that we can do for v2.4.0 has been implemented. Closing in favor of https://github.com/fyne-io/fyne/issues/4129 and https://github.com/fyne-io/fyne/issues/4130 for tracking future work with rounded theme corners.
