### ISSUE TITLE
Fyne Demo: Login form username field deselects on focus when empty 

### ISSUE THREAD

**Issue by soypat** [fyne-io/fyne#3985]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Selecting username field while password field filled deselects it immediately.

### How to reproduce

1. Open Fyne demo
2. Goto login form
3. Leave username empty and select password field and write something in it
4. Select username field

### Screenshots

https://github.com/fyne-io/fyne/assets/26156425/3ceae0da-5a0d-426a-a54c-610b8feec56f

### Example code

See Fyne Demo.

### Fyne version

Latest release to date

### Go compiler version

1.20

### Operating system and version

Linux Mint 21 with XFCE

**Comment by andydotxyz** [comment]
I cannot replicate this behaviour on develop, maybe it was already resolved? If you could check that would be great as our next release will come from that branch.

**Comment by soypat** [comment]
I git cloned repo, switched to `develop` and ran `go run ./cmd/fyne_demo` . Still am getting the same bug.

**Comment by soypat** [comment]
Reproducing it seems to have its quirks (audio on to see where I click)

https://github.com/fyne-io/fyne/assets/26156425/b16ffefa-b450-46be-b51f-38269012b5aa

**Comment by Jacalz** [comment]
@soypat I can not replicate this. Can you try again with the code on `develop` please?

**Comment by soypat** [comment]
So this is not replicable with latest version of `develop` because the develop version does not resize on data entry... which in itself might be another issue because the data entry box is ***tiny***.
![image](https://github.com/fyne-io/fyne/assets/26156425/8dcdeeab-2ef8-4909-9dc0-5e611e1c4ea0)

I've tracked the culprit to what I think is the following steps to reproduce on `master`:
1. Fill the login password
2. click on one of the extremes of the **empty** username field such that when window resizes your cursor lies outside the bounds of the new resized login window (you must have a long window)

**Comment by soypat** [comment]
This issue with tiny data entry boxes is an issue I've run into when using Fyne. Not sure how to give input widgets a decent size...

**Comment by soypat** [comment]
Aha! I've been able to reproduce this bug on the latest develop!

Follow steps above but with one extra step:
1. Fill in an invalid Username such as `@`, this will ensure a validation message shows
2. Click elsewhere to lose focus of the Username field. This will cause an error to display saying "username can contain only...". This will also have the side effect of enlarging input box
3. Click on one of the extreme  corners of the username box such that when window resizes your cursor lies outside the bounds of the newly resized smaller username text field

**Comment by andydotxyz** [comment]
> This issue with tiny data entry boxes is an issue I've run into when using Fyne. Not sure how to give input widgets a decent size...

The size issue is not with the inputs, they will fill the space given, it's that the dialog isn't big enough. So you can call `Resize` on the `Dialog` instance.
