### ISSUE TITLE
Buttons become unclickable when in a container.NewWithoutLayout

### ISSUE THREAD

**Issue by Westsi** [fyne-io/fyne#3987]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When creating a button widget, moving it (although moving seems to be unnecessary to reproduce) and putting it inside a NewWithoutLayout container, it becomes unclickable bold text and loses the button highlight/overlay. I have tried moving the buttons before putting them in the container, after putting them in, but nothing seems to work, other than using a container that positions them, but I need custom positioning.

### How to reproduce

1. Make a new window and app.
2. Make a button (and move it if you want).
3. Make a new container.NewWithoutLayout and put the button inside it.
4. Set the window's content to the container. 
5. ShowAndRun() the window

### Screenshots

![Screenshot (623)](https://github.com/fyne-io/fyne/assets/76999267/7f838b03-78ff-456e-9447-a6fd1e962ab0)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Bug?")
	hello := widget.NewLabel("Is this a bug?")

	contButton := widget.NewButton("Continue", func() {
		a.NewWindow("Test").Show()
	})
	cancButton := widget.NewButton("Cancel", func() {
		a.Quit()
	})
	w.SetContent(container.NewWithoutLayout(
		hello,
		contButton,
		cancButton,
	))
	w.Resize(fyne.NewSize(1280, 720)) // to show buttons completely
	contButton.Move(fyne.NewPos(100, 100))
	cancButton.Move(fyne.NewPos(110, 200))

	w.ShowAndRun()
}

```

### Fyne version

2.3.5

### Go compiler version

1.18.3

### Operating system and version

Windows 10

### Additional Information

x64 AMD

**Comment by andydotxyz** [comment]
If you are going to self-manage a container you must resize the widgets inside it.
The interactive area is only as large as you set it to be.
Add `Resize` next to your `Move` calls.
