### ISSUE TITLE
SetMainMenu(menu) running success but no menu desplay

### ISSUE THREAD

**Issue by gitstliu** [fyne-io/fyne#3988]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

run this code no menu desplay

### How to reproduce

1 run the code in mac Apple M2 Max Ventura 13
2 there is no menu desplay in the window

### Screenshots

<img width="404" alt="截屏2023-06-19 22 24 39" src="https://github.com/fyne-io/fyne/assets/35721846/522c60f7-5cd3-49c1-b8ad-a7b6580cf68f">

### Example code

package main

// import fyne
import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
)

func main() {
	// New app
	a := app.NewWithID("com.anydom.com")
	w := a.NewWindow("Main menu items")
	w.Resize(fyne.NewSize(400, 400)) // 400x400 window size
	// Menu items
	menuItem1 := fyne.NewMenuItem("New", nil)  // ignore functions
	menuItem2 := fyne.NewMenuItem("Edit", nil) // ignore functions
	menuItem3 := fyne.NewMenuItem("Run", nil)  // ignore functions
	// New Menu
	newMenu1 := fyne.NewMenu("File", menuItem1, menuItem2, menuItem3)
	// more items
	newMenu2 := fyne.NewMenu("Other", menuItem1, menuItem2, menuItem3)
	newMenu3 := fyne.NewMenu("Help", menuItem1, menuItem2, menuItem3)
	// New main menu
	menu := fyne.NewMainMenu(newMenu1, newMenu2, newMenu3)
	// setup main menu
	w.SetMainMenu(menu)
	w.ShowAndRun()
}

### Fyne version

fyne.io/fyne/v2 v2.3.5

### Go compiler version

1.20.5

### Operating system and version

macOS Apple M2 Ventura 13

**Comment by Jacalz** [comment]
On macOS, by default, we integrate natively with the menus up in the top bar like all other applications. If you want menus inside the application, you can build with `-tags no_native_menus` per the [compile options](https://developer.fyne.io/explore/compiling) documentation.

**Comment by gitstliu** [comment]
OK, thanks for you help. @Jacalz
