### ISSUE TITLE
HBox layout content covered up 

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#3993]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

the list content was covered up .

<img width="743" alt="image" src="https://github.com/fyne-io/fyne/assets/37319319/2d752b2b-3343-4fdf-97bc-8ccbcebae352">

### How to reproduce

just see below code,thanks

### Screenshots

<img width="500" alt="image" src="https://github.com/fyne-io/fyne/assets/37319319/e81f2e1e-1370-453a-a4d7-44ca3c99a3e4">

### Example code

```go

	list := widget.NewList(
		func() int {
			return len(showUserDataModels)
		},
		func() fyne.CanvasObject {
			text := widget.NewLabel("")
			text.Resize(fyne.Size{
				Width: 250,
			})
			button := widget.NewButton("打开浏览器", nil)
			button.Importance = widget.HighImportance // 按钮的主题，就是颜色
			button.Resize(fyne.Size{
				Width: 250,
			})
			container := container.New(layout.NewHBoxLayout(), text, button)
			container.Resize(fyne.Size{
				Width: 250,
			})
			return container
		},
		func(i widget.ListItemID, o fyne.CanvasObject) {
			container := o.(*fyne.Container)
			container.Objects[0].(*widget.Label).SetText(getIpName(showUserDataModels[i].ProxyName))
			container.Objects[1].(*widget.Button).OnTapped = func() {
				logger.Infof("Button tapped for: %+v", showUserDataModels[i])
				if showUserDataModels[i].IsProxy && showUserDataModels[i].ProxyPort > 0 {
					// 需要代理
					proxyResult, proxyServer := src.MacService(showUserDataModels[i].ProxyPort)
					if proxyResult && len(proxyServer) > 0 {
						go browser.OpenBrowser(showUserDataModels[i], userDataModels, proxyServer)
					} else {
						dialog.ShowInformation("提示", "网点那边电脑不在线，应该是电脑没开机，或者让网点那边电脑重启下。", w)
					}
				} else {
					go browser.OpenBrowser(showUserDataModels[i], userDataModels, "")
				}
			}
		})

	form := dialog.NewForm("登陆中...", "登陆", "取消", items, func(b bool) {
		if !b {
			return
		}
		var rememberText string
		if remember {
			rememberText = "and remember this login"
			user.UpdateUserAccount(userAccountModel, username.Text, password.Text)
		}
		logger.Println("Please Authenticate", username.Text, password.Text, rememberText)
		if len(username.Text) > 0 && len(password.Text) > 0 {
			showUserDataModels = login.Login(username.Text, password.Text, userDataModels)
			list.Refresh()
		}
	}, w)
	form.Resize(fyne.Size{
		Width: 250,
	})
	form.Show()

	vbox := container.NewVBox()
	label := widget.NewLabel("robot")
	vbox.Add(label)
	//box := container.NewHBox(list, vbox)
	//box := container.NewMax(layout.NewHBoxLayout(), list, vbox)

	vboxList := container.NewVBox(list)
	//vboxList.Resize(fyne.NewSize(w.Canvas().Size().Width, w.Canvas().Size().Height))
	vboxList.Layout = layout.NewVBoxLayout()

	box := container.New(layout.NewHBoxLayout(), vboxList, layout.NewSpacer(), vbox)
	list.Resize(fyne.Size{
		Width: 250,
	})
	vboxList.Resize(fyne.Size{
		Width: 250,
	})
	//box.Add(list)
	//box.Add(vbox)

	w.SetContent(box)
```

### Fyne version

2.3.5

### Go compiler version

1.20.5

### Operating system and version

macos and ubuntu

**Comment by Jacalz** [comment]
This is not a bug, it is the intended behaviour because you are using the wrong kind of layout. Per https://pkg.go.dev/fyne.io/fyne/v2/layout#NewHBoxLayout, the HBox make the items as big as their Horizontal MinSize. You basically need to rethink which layouts you are using.

I would suggest reading https://developer.fyne.io/explore/layouts and having a look at the video at the bottom.

**Comment by aohanhongzhi** [comment]
I did it by the video

https://www.youtube.com/watch?v=eR1COQXcZ6M

<img width="500" alt="image" src="https://github.com/fyne-io/fyne/assets/37319319/b17422eb-8bf8-4088-93e5-0d519c736a48">

**Comment by Jacalz** [comment]
But the code in the video doesn't match up with your code example above. The video uses the layouts in a correct way.

Here are a few problems that I have noted with the code:

- You are calling `.Resize()` manually which should **never** be done for objects within containers with layouts.
- For what it's worth, the resize calls, if they worked correctly (they will just be resized automatically by the layout so your calls or no-op), would have resized to 250 units wide and 0 height.
- The layouts issues with VBox and HBox mentioned above. For exampl, the VBox will only make the list display one item in height.

I can only recommend you to have a look at the video again. The list is not in a VBox and the left and right contents are in a HSplit.
