### ISSUE TITLE
Updating text grid widget too often will cause high cpu usage

### ISSUE THREAD

**Issue by princessmortix** [fyne-io/fyne#3994]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I was told to report this bug here so.

If the text grid widget is updated too often it will make fyne use too much cpu and can also memory leak.

### How to reproduce

Unsure if this is acceptable, but you can clone this repository: https://github.com/princessmortix/defractureiser, and change line [294](https://github.com/princessmortix/defractureiser/blob/main/main.go#L294) and line [370](https://github.com/princessmortix/defractureiser/blob/main/main.go#L370) from fmt to log, and the text will output to the text grid widget instead of the os stdout.

### Screenshots

I originally found it while coding defractureiser:

https://github.com/fyne-io/fyne/assets/47502554/87cb1722-0fa6-469b-8f21-8352da80826f

While coding the example code, I also found out that it can memory leak too: 
![image](https://github.com/fyne-io/fyne/assets/47502554/49da382e-2ea3-4de3-9f3e-1acd955c17bc)

See the video:

https://github.com/fyne-io/fyne/assets/47502554/165bacef-b340-4ab1-abd1-f38ecd78d6cd

### Example code

```go
package main

import (
	"log"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

type TextGridWriter struct {
	TextGridWidget *widget.TextGrid
}

func (tw *TextGridWriter) Write(p []byte) (n int, err error) {
	logMsg := string(p)
	tw.TextGridWidget.SetText(tw.TextGridWidget.Text() + logMsg)
	return len(p), nil
}

func main() {
	exampleApp := app.New()
	exampleWindow := exampleApp.NewWindow("Example")
	exampleWindow.Resize(fyne.NewSize(800, 600))

	exampleTextGrid := widget.NewTextGrid()
	scrollableTextGrid := container.NewVScroll(exampleTextGrid)
	scrollableTextGrid.SetMinSize(fyne.NewSize(800, 300))

	lagButton := widget.Button{
		Text:     "Click to lag",
		OnTapped: func() { updateTextGrid(exampleTextGrid) },
	}

	exampleContent := container.New(layout.NewVBoxLayout(), scrollableTextGrid, &lagButton)
	exampleWindow.SetContent(exampleContent)
	exampleWindow.Show()
	exampleApp.Run()
}

func updateTextGrid(textGridWidget *widget.TextGrid) {
	textGridWidgetWriter := &TextGridWriter{TextGridWidget: textGridWidget}
	log.SetOutput(textGridWidgetWriter)
	for i := 0; i < 100; i++ {
		log.Println("The quick brown fox jumps over the lazy dog.")
	}
	log.Println("Done.")
}
```

Minimal example I could make

### Fyne version

2.3.5

### Go compiler version

1.20.4

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
As TextGrid is a 2D array of runes you can avoid the overhead of newline concatenation and re-parse by setting the row directly. https://developer.fyne.io/api/v2.3/widget/textgrid.html#func-textgrid-setrow
As it says passing a rowID beyond the bounds will expand the widget. This may be faster, either way it's useful for the bug report to compare the two.

**Comment by princessmortix** [comment]
Will test if the PR makes it less laggy :)

**Comment by princessmortix** [comment]
It is indeed using way less resources than before, should I close this issue?
![Taskmgr_dxsEFNnwwm](https://github.com/fyne-io/fyne/assets/47502554/048cdade-f047-4b26-bc2a-3877649d81b3)

**Comment by andydotxyz** [comment]
Thanks for confirming :) looks like it is good to close. Will be in v2.4.0
