### ISSUE TITLE
Compiling error in armv7

### ISSUE THREAD

**Issue by Mr-BeanSir** [fyne-io/fyne#3997]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I hope to compile graphical software on armv7. I tried to compile on both Windows and Ubuntu, but both reported errors. Below are the errors reported by Ubuntu. And fyne cross cannot compile for armv7

system:Linux ubuntu 5.15.0-75-generic #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

error:
```
# command-line-arguments
/usr/lib/go-1.20/pkg/tool/linux_amd64/link: running arm-linux-gnueabihf-gcc failed: exit status 1
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lGL
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lX11
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lXrandr
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lXxf86vm
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lXi
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lXcursor
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lXinerama
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
```

go env:
```
GO111MODULE="on"
GOARCH="arm"
GOBIN=""
GOCACHE="/home/dou/.cache/go-build"
GOENV="/home/dou/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dou/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dou/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go-1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.20/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOARM="7"
AR="ar"
CC="arm-linux-gnueabihf-gcc"
CXX="arm-linux-gnueabihf-g++"
CGO_ENABLED="1"
GOMOD="/home/dou/桌面/dsdou/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1683978079=/tmp/go-build -gno-record-gcc-switches"
```

### How to reproduce

go build main.go

### Example code

package main

import (
	app2 "fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app2.New()
	window := app.NewWindow("this title")
	window.SetContent(widget.NewLabel("show content"))
	window.ShowAndRun()
}

### Fyne version

2.3.5

### Go compiler version

1.20.5

### Operating system and version

ubuntu 20.04.1

**Comment by andydotxyz** [comment]
> And fyne cross cannot compile for armv7

I'm not sure this is true, if so there should be a Fyne-cross bug to track it.

It will help if you share the command you used to compile in the examples above.

It sounds like you don't have the libraries specific to the armv7 architecture which you will need to compile locally.
I would expect Fyne-cross is easier, though other CI pipelines like https://fynelabs.com/geoffrey/ can help you too ;).

**Comment by 912929782** [comment]
May I ask if you have solved it now? Is there a good way to share? I have also encountered this problem @Mr-BeanSir

**Comment by Mr-BeanSir** [comment]
> 请问现在解决了吗？有好的方法分享一下吗？我也遇到过这个问题@Mr-BeanSir



> May I ask if you have solved it now? Is there a good way to share? I have also encountered this problem @Mr-BeanSir

**Comment by Mr-BeanSir** [comment]
> May I ask if you have solved it now? Is there a good way to share? I have also encountered this problem @Mr-BeanSir

尝试在armv7的系统上直接编译，或者将需要的库拉取，我已经不再尝试使用fyne在armv7上编译，因为我所编译的平台仅支持gtk+2.0
