### ISSUE TITLE
option to specify the location for preference.json

### ISSUE THREAD

**Issue by pkk-code** [fyne-io/fyne#3998]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Could we introduce a feature that allows users to select the directory location and name for the preferences.json file? This would enable users to specify their preferred location and prevent loss of settings and preferences when transitioning to a different system or reinstalling the operating system.

### Describe the solution you'd like to see.

During the application startup, could we incorporate an option to specify the storage location for storing and retrieving settings and preferences? This would provide users with the ability to define their preferred location, ensuring that their settings and preferences remain intact even when switching systems or reinstalling the operating system.

**Comment by andydotxyz** [comment]
The location is different for every OS so this would not be as simple as you think. And on some platform it simply can't be changed (sandboxing like iOS and android).

I do have to ask though, what sort of system update destroys the user home directory?

**Comment by Atrbear** [comment]
So how to find the default location of preference.json in favor of every os? Could you please update more detail in document

**Comment by andydotxyz** [comment]
It's an internal detail so I guess we didn't document it - but you can find the os specific `rootConfigDir` methods in the various app files at https://github.com/fyne-io/fyne/blob/1834d704a305f4729cce65213f5b5c3098e1d993/app/app_windows.go#L59.

It should be in the place specified by the OS standards for app configuration.

**Comment by Jacalz** [comment]
I think some sort of tool to import or export preference files would be a better option than being able to change the path

**Comment by andydotxyz** [comment]
> I think some sort of tool to import or export preference files

They are flat files already. Maybe I misunderstood your suggestion.

**Comment by Jacalz** [comment]
I just mean a helpful GUI tool where the user can use file dialogs to import and export to different locations without necessarily knowing where the underlying files are located

**Comment by Jacalz** [comment]
I'm not necessarily saying that it has to be part of `fyne_settings`. Any developer that wants it in their application can probably create one if necessary, which might solve the use case mentioned for opening this issue

**Comment by pkk-code** [comment]
> The location is different for every OS so this would not be as simple as you think. And on some platform it simply can't be changed (sandboxing like iOS and android).
> 
> I do have to ask though, what sort of system update destroys the user home directory?

Example - Reinstall of new operating system or formatting the c:\drive due to system issue.  Also, another use case is application hosted in citrix VDI, where administrators are requesting to keep the contents outside of AppData to different location as appdata location is disabled by default

It would be great if we have an option to specify where these files can reside and loaded at the start of application.

**Comment by andydotxyz** [comment]
If you are going to wipe your hard drive won't you back up your home directory? If you do that the data is saved.

I'm not familiar with your second case. If `AppData` is not the correct place for windows users can you find some docs of a better location?

**Comment by Jacalz** [comment]
> If you are going to wipe your hard drive won't you back up your home directory? If you do that the data is saved.

Is that true for systems other than Linux though?

**Comment by andydotxyz** [comment]
Do you mean backing up or locations? For the latter, yes - all the preference storage locations are inside user home directory on desktops. On mobile it is inside the sandbox which the phone will backup.

**Comment by Jacalz** [comment]
I thought the folders for preferences on Windows and macOS weren't in the home folders but you're right. Otherwise we wouldn't be able to write to the files without admin right, I think :)

**Comment by andydotxyz** [comment]
I think there is no action to take here.
You can get the location we use for writing with `App.Storage().RootURI` (sorry if I forgot to mention this before).

We can't support setting this at an app level because of the platform specifics mentioned before.
If you think this should be a user preference setting that we support then please re-open this issue and we can look at it further. 

This would impact the location of preferences.json and all the `storage` APIs and document presistance.
