### ISSUE TITLE
Can i change font ?

### ISSUE THREAD

**Issue by SeaSalvageUnit** [fyne-io/fyne#400]
I had to delete the following file as it had 'error reading unexpected EOF' error and kept displaying broken Korean texts (white rectanlgles in the attached image). 

$gopath/pkg/windows_amd64/fyne.io/fyne/vendor/golang.org/x/text/encoding/korean.a

Is there a way to change the font in go because it seems to be not supporting Korean language?

[Image File](https://bot.onionbot.me/K-012.png) - Korean

[Image File](https://bot.onionbot.me/K-013.png) - English

**Comment by andydotxyz** [comment]
Unfortunately we don't package a Korean font with Fyne but yes, you can set your own.
If you find a suitable .ttf file you can set the environment variable "FYNE_FONT" to the path and then run the application. It should then work as expected.

We are trying to find a better solution without adding too much extra data into every app. Apologies for the inconvenience.

**Comment by devcomcool** [comment]
@andydotxyz Only TTF file? cannot otf?

oh. "Cause: freetype: invalid TrueType format: bad TTF version"

Thank ur reply

**Comment by andydotxyz** [comment]
Only TTF, sorry. If you are experiencing problems can you share the file and we will test it out?

**Comment by andydotxyz** [comment]
Assuming that a TTF file was obtained and the issue resolved

**Comment by wejoy** [comment]
> 
> 
> @andydotxyz Only TTF file? cannot otf?
> 
> oh. "Cause: freetype: invalid TrueType format: bad TTF version"
> 
> Thank ur reply

Well, that is because those package
github.com/golang/freetype
only support TTF and must be version1.0.0

You may try the ttf font file from Droid,
https://github.com/aosp-mirror/platform_frameworks_base/tree/android-sdk-4.0.3_r1/data/fonts
It looks good to me in Chinese.

**Comment by mazhiyu** [comment]
@andydotxyz Can the font file(.ttf) be integrated in app when packaging a graphical app? Otherwise i must provide the font file independently.

**Comment by andydotxyz** [comment]
Yes that can be done. You can bundle a font resource using “fyne bundle” and then you could reference this in a custom theme. The theme would then be set with App.Settings().SetTheme(). It’s not exactly the same but it should work until we find a way to package all language fonts.

**Comment by mazhiyu** [comment]
> Yes that can be done. You can bundle a font resource using “fyne bundle” and then you could reference this in a custom theme. The theme would then be set with App.Settings().SetTheme(). It’s not exactly the same but it should work until we find a way to package all language fonts.

Ok, i will try it. Thanks.

**Comment by aztack** [comment]
Is it possible to dynamic load/set/change font after app started?

**Comment by andydotxyz** [comment]
Themes provide this feature. But please use discussions to ask new questions, not a closed issue.
