### ISSUE TITLE
test.Type do not work on Entry

### ISSUE THREAD

**Issue by simmarn** [fyne-io/fyne#4005]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I try to perform unit testing according to the Fyne tutorial I get compilation error when using test.Type.
$ go test
# main [main.test]
./main_test.go:16:12: cannot use in (variable of type *"fyne.io/fyne/v2/widget".Entry) as type "fyne.io/fyne".Focusable in argument to test.Type:
        *"fyne.io/fyne/v2/widget".Entry does not implement "fyne.io/fyne".Focusable (missing Focused method)
FAIL    main [build failed]

### How to reproduce

1. https://developer.fyne.io/started/testing and perform the tutorial
2. go test returns compilation error as described above.

### Example code

main.go:
`package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func makeUI() (*widget.Label, *widget.Entry) {
	return widget.NewLabel("Hello world!"),
		widget.NewEntry()
}

func main() {
	a := app.New()
	w := a.NewWindow("Hello Person")

	w.SetContent(container.NewVBox(makeUI()))
	w.ShowAndRun()
}
`
main_test.go:
`package main

import (
	"testing"

	"fyne.io/fyne/test"
)

func TestGreeting(t *testing.T) {
	out, in := makeUI()

	if out.Text != "Hello world!" {
		t.Error("Incorrect initial greeting")
	}

	test.Type(in, "Andy")
	if out.Text != "Hello Andy!" {
		t.Error("Incorrect user greeting")
	}
}
`

### Fyne version

v2.3.5

### Go compiler version

go version go1.18.1 linux/amd64

### Operating system and version

Ubuntu 22.04.2 LTS

**Comment by Jacalz** [comment]
We are using that function locally in the tests for the toolkit itself. I believe that the issue comes from your IDE having imported Fyne without the v2 path in one of the includes. Looking at your error message, you can see that there is no `v2` in there. There is an issue for it in gopls over at https://github.com/golang/vscode-go/issues/2818.
