### ISSUE TITLE
Entry supports select text and get focus

### ISSUE THREAD

**Issue by lowking** [fyne-io/fyne#4024]
### Checklist

- [ ] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I set up a shortcut to search, and when I press the shortcut, I need to focus on the text entry and select all the text.

### Is it possible to construct a solution with the existing API?

No

### Describe the solution you'd like to see.

Ability to get text entry focus and select all text by calling method.

**Comment by matwachich** [comment]
window.Canvas().Focus(your_entry)
your_entry.TypedShortcut(&fyne.ShortcutSelectAll{})

**Comment by andydotxyz** [comment]
Thanks @matwachich
