### ISSUE TITLE
Single line Entry throws away selected text on submission

### ISSUE THREAD

**Issue by Goltanju** [fyne-io/fyne#4026]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Pretty much the title, fairly simple bug I think. The single line entry will discard any selected text on submit.

### How to reproduce

With a single line entry:

1. Type in "abc" and hit enter: you get "abc" ✔️ 
2. Type in "abc" hit ctrl+a to select all and hit enter: you get "" 😢 
3. Type in "abc" select just the b and hit enter: you get "ac" 😢 

### Example code

```go
package main

import (
        "fmt"
        "image/color"

        "fyne.io/fyne/v2"
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/canvas"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/theme"
        "fyne.io/fyne/v2/widget"
)

func main() {
        application := app.NewWithID("test-gui")
        window := application.NewWindow("Test GUI")
        monospace := fyne.MeasureText("M", theme.TextSize(), fyne.TextStyle{Monospace: true})
        min := canvas.NewRectangle(color.RGBA{})
        min.SetMinSize(fyne.NewSize(monospace.Width*20, monospace.Height*5))
        entry := widget.NewEntry()
        label := widget.NewLabel("")
        entry.OnSubmitted = func(v string) {
                label.SetText(fmt.Sprintf("%q", v))
        }
        window.SetContent(container.NewMax(min, container.NewGridWithRows(2, entry, label)))
        window.Show()
        application.Run()
}
```

### Fyne version

develop

### Go compiler version

1.20.5

### Operating system and version

Windows 11

**Comment by Goltanju** [comment]
This patch seems to fix the problem, but I don't really know if it's the correct approach:

```diff
diff --git a/widget/entry.go b/widget/entry.go
index 41967616e..5ada3d289 100644
--- a/widget/entry.go
+++ b/widget/entry.go
@@ -1028,7 +1028,9 @@ func (e *Entry) selectingKeyHandler(key *fyne.KeyEvent) bool {
                return true
        case fyne.KeyReturn, fyne.KeyEnter:
                // clear the selection -- return unhandled to add the newline
-               e.eraseSelection()
+               if e.MultiLine {
+                       e.eraseSelection()
+               }
                return false
        }
```

**Comment by andydotxyz** [comment]
Good catch.
A sensible fix - though it would need unit tests as well to confirm fix and avoid regressions.

**Comment by andydotxyz** [comment]
Fix landed on `develop`, thanks so much @Goltanju
