### ISSUE TITLE
Icon Questions

### ISSUE THREAD

**Issue by devcomcool** [fyne-io/fyne#403]
1. How do I add custom icons in theme.Homelcon() command?

2. How do I change the program icon?

I'm new to Go language and sorry if I'm asking too many questions. fyne-demo examples are being very helpful. Thank you.

**Comment by andydotxyz** [comment]
To change the theme icons you need to provide an alternative theme implementation. This is then passed to fyne.CurrentApp().Settings().SetTheme(...).

The program icon is packaged when preparing to share, due to how GUI apps work. This is handled by the "fyne bundle" command - https://fyne.io/develop/distribution.html

**Comment by devcomcool** [comment]
@andydotxyz 
Can I only use basic icons in basic theme settings? 

no2 question is solved.

**Comment by andydotxyz** [comment]
Sorry I don’t understand - do you want to change theme icons or do you want to add your own?

Adding new icons is possible as well, we recommend bundling them using “Fyne bundle” so you still distribute just one binary file

**Comment by devcomcool** [comment]
@andydotxyz 
I want to add a new icon.
But I'm looking at "fyne bundle" and need to add it as .go to add the icon?

**Comment by andydotxyz** [comment]
It is recommended to embed icons in your .go code using a tool like that so it is all compiled in.
You can also load icons from the filesystem if you wish - but that is not as portable.

**Comment by devcomcool** [comment]
@andydotxyz 
Thanks. 
Do you have any examples I can refer to?
"fyne.io/fyne/cmd/fyne_demo" is a good example for beginners
I want to go deeper.

**Comment by andydotxyz** [comment]
Try our examples repository. The “bugs” game uses custom icons - see the “gen” script as well.

**Comment by kendax** [comment]
Is there a way one can get an already existing icon to have a different color

**Comment by Jacalz** [comment]
@kendax This issue was closed over fir years ago. Please open a new question on GitHub Discussions.
