### ISSUE TITLE
Entry Placeholder Style Only Applied On Click

### ISSUE THREAD

**Issue by dozn** [fyne-io/fyne#4035]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Placeholder text on an entry field uses the TextStyle of the entry field itself, although it seems to be applied only once clicked upon.

### How to reproduce

Click on the entry field.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/16659513/5badaba3-0d27-4883-b2f5-edd60ab7094b)
![image](https://github.com/fyne-io/fyne/assets/16659513/60ed6571-c860-42c0-b2a5-7f4b31c9750f)

### Example code

```go
func main() {
	application := app.New()
	window := application.NewWindow("Test")

	entryField := widget.NewEntry()
	entryField.PlaceHolder = "Test"
	entryField.TextStyle = fyne.TextStyle{Bold: true}

	window.SetContent(entryField)
	window.ShowAndRun()
}
```

### Fyne version

e050d7994adc06da78efc61fd9c7fb035faf57ff

### Go compiler version

1.20.5

### Operating system and version

Arch Linux (kernel 6.1.37 LTS)

### Additional Information

I would expect it to be bold without having to be clicked on, and in fact I'd even prefer if there were separate styling options for both the placeholder and the text itself, although that's perhaps a feature request =b

**Comment by andydotxyz** [comment]
Fixed ready for v2.4.0
