### ISSUE TITLE
Entry Field on Android in Landscape Mode Shows "0"

### ISSUE THREAD

**Issue by dozn** [fyne-io/fyne#4036]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If you touch an entry field while in landscape mode on Android, the edit box which comes up displays a "0" which you cannot remove.

### How to reproduce

1. Go into landscape mode
2. Click on the entry field

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/16659513/2657baa7-bffa-43ec-bd2e-809b6a30cdcc)
![image](https://github.com/fyne-io/fyne/assets/16659513/e4069cb4-1ebf-4df1-98c4-e2bb2a59b05e)

### Example code

```go
func main() {
	application := app.New()
	window := application.NewWindow("Test")

	entryField := widget.NewEntry()

	window.SetContent(entryField)
	window.ShowAndRun()
}
```

### Fyne version

e050d7994adc06da78efc61fd9c7fb035faf57ff

### Go compiler version

1.20.5

### Operating system and version

Android 10 and 12.1

**Comment by andydotxyz** [comment]
This is resolved on develop branch. Will be in v2.4.1
