### ISSUE TITLE
fyne package doesn't give app metadata in develop branch

### ISSUE THREAD

**Issue by mbaklor** [fyne-io/fyne#4045]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

ONLY ON DEVELOP BRANCH

When packaging the app using `fyne package`, `fyne.CurrentApp().Metadata` results in an empty default struct. Tested multiple times with multiple builds, and it seems like the metadata functionality is broken.
This might only be a windows problem, but it happened on both win10 and win11

### How to reproduce

1. write code that tries to read from the app metadata
2. add the metadata to a widget you can see in the app
3. build with `fyne package`
4. run the packaged app

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/78748463/8b43ad64-ce1c-448f-bc5f-f2f9b5a4de64)

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	win := a.NewWindow("Test Window")

	st := fmt.Sprintf("%+v", a.Metadata())
	fmt.Println(st)
	label := widget.NewLabel(st)
	win.SetContent(label)
	win.ShowAndRun()
}
```

### Fyne version

v2.3.6-0.20230704203313-e050d7994adc

### Go compiler version

v1.20.5

### Operating system and version

Windows 10, Windows 11

**Comment by andydotxyz** [comment]
I cannot seem to replicate this - using the develop `fyne` and develop version of the library it works great.
You can see in the "advanced" screen of fyne_demo that there is info packaged.

**Comment by mbaklor** [comment]
I've tried building the fyne_demo from the entire fyne repo and it worked, in both the main and develop branches, however when I copied out the entire fyne_demo folder to its own folder (so it depends on the imported fyne library) and the issue is there again.

Tested that on both window 10 and ubuntu.
I'll upload the copied out demo folder to a repo and share it here as soon as I get back to my computer.

**Comment by mbaklor** [comment]
Update, this is the exact fyne demo code but copied into a new repo (and the submodules edited as needed), when running `fyne package` here the metadata didn't get included. If I revert to the `fyne/v2@latest` the metadata gets included again.
https://github.com/mbaklor/fyne_demo

![image](https://github.com/fyne-io/fyne/assets/78748463/3f145f5e-a34a-4f59-802e-aa3345fde8b7)

**Comment by andydotxyz** [comment]
I've managed to track this down. The package command is doing some version checks that are failing outside of the tagged releases. Not sure why yet but I think we must have made a false assumption about the semver handling.

**Comment by andydotxyz** [comment]
Fixed on develop branch
