### ISSUE TITLE
Add Mime Type Support to file pickers

### ISSUE THREAD

**Issue by okratitan** [fyne-io/fyne#405]
Hello -

I would like to propose that we add some mime type support that can be provided through fyne and especially helpful for things like a file chooser that we have in upcoming releases after we have a data binding and list/grid widgets that cache.  I will begin the work on this and follow it up with a PR.

**Comment by andydotxyz** [comment]
Nice. I imagine it would go nicely with file icons?

**Comment by andydotxyz** [comment]
Changed the title, with file open and save dialogs landing there is now a place we could start to develop this.
At the moment we have folder / file icons and a "parent folder" icon.
The code just writes the file extension over the file icon. Simple but effective until this ticket progresses ").

**Comment by andydotxyz** [comment]
Probably needs to be part of the new `fyne.File` API.
This is complex for iOS and Android ...

Nice to have also filter by mime
