### ISSUE TITLE
Compiling error in armv7

### ISSUE THREAD

**Issue by 912929782** [fyne-io/fyne#4051]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Does anyone know how to handle this problem？ Issue #3997 

### How to reproduce

go build main.go

### Example code

package main

import (
app2 "fyne.io/fyne/v2/app"
"fyne.io/fyne/v2/widget"
)

func main() {
app := app2.New()
window := app.NewWindow("this title")
window.SetContent(widget.NewLabel("show content"))
window.ShowAndRun()
}

### Fyne version

2.3.5

### Go compiler version

1.20.5

### Operating system and version

ubuntu 20.04.0

**Comment by andydotxyz** [comment]
Why have you opened a new issue that is the same as an old one?

I also don't see any error or bug listed in the details above.

Armv7 compilation does work, so we will need a lot more details in your "how to reproduce" otherwise we can't help.

**Comment by 912929782** [comment]
1.My go env  【go version go1.20.3 linux/amd64】
GO111MODULE="on"
GOARCH="arm"
GOBIN=""
GOCACHE="/home/zlgmcu/.cache/go-build"
GOENV="/home/zlgmcu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zlgmcu/gowork/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zlgmcu/gowork"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOARM="7"
AR="ar"
CC="arm-linux-gnueabihf-gcc"
CXX="arm-linux-gnueabihf-g++"
CGO_ENABLED="1"
GOMOD="/home/zlgmcu/testFyne/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3403924469=/tmp/go-build -gno-record-gcc-switches"

2.My code main.go
package main

import (
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/widget"
)

func main() {
        a := app.New()
        w := a.NewWindow("Hello")

        hello := widget.NewLabel("Hello Fyne!")
        w.SetContent(container.NewVBox(
                hello,
                widget.NewButton("Hi!", func() {
                        hello.SetText("Welcome :)")
                }),
        ))

        w.ShowAndRun()
}

3.go build main.go

4.Error information
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-gnueabihf-gcc failed: exit status 1
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lGL
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lX11
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lXrandr
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lXxf86vm
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lXi
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lXcursor
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lXinerama
/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lGL
collect2: error: ld returned 1 exit status

5.My opinion
Go is cross-platform, and when I modify its environment variables, it compiles cross-platform. But joining fyne now is not an option.Please tell me what the problem  is?  @andydotxyz

**Comment by Jacalz** [comment]
Go can only cross-compile pure Go code but that doesn’t apply when you are using CGo to interact with C-libraries. You need to install a C-compiler and corresponding libraries for that specific platform. The easies way to cross-compile is to install fyne-cross. More information is available over at https://developer.fyne.io/started/cross-compiling.
