### ISSUE TITLE
Find a more elegant way to avoid binding data "echos"

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4061]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Input widgets (such as Entry) call binding setters when they change, and these are then echoed back to the widget with a delay. This can result in a jitter or lost input letters so a "ignore delay" is being used to avoid the feedback.

It feels like there could be a better way, such as when setting list which listener should not be called back. This may not be trivial, or may require a breakage, but should be considered for a future version.

### How to reproduce

Things like bug #3887 show the problem, though they are being fixed on a case-by-case for now.

### Example code

Use a two-way binding, like `String` and set regularly - you will see old state being restored.

### Fyne version

2.3.5

### Go compiler version

1.20.4

### Operating system and version

macOS

**Comment by dan-frohlich** [comment]
This seems like a common publish / subscribe problem. That is the subscribers should be able to Id and ignore messages they produced.

If the bound data callbacks and registry had a param containing a field uniquely identifying the UI object, that bound data item could potentially not send update events to the object which sourced the change. Alternately, the id could be passed to all subscribers and each subscriber could choose how to handle calls regarding changes sourced from itself.

**Comment by andydotxyz** [comment]
I feel like Entry now (on develop) has a good model for this (we know the change comes from binding so we can avoid pushing it back out).
