### ISSUE TITLE
Can I ask if this framework does not recognize Chinese characters?

### ISSUE THREAD

**Issue by AaronChengHao** [fyne-io/fyne#4065]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Can I ask if this framework does not recognize Chinese characters?

### Describe the solution you'd like to see.

Can I ask if this framework does not recognize Chinese characters?

**Comment by andydotxyz** [comment]
It supports all unicode and known languages, but it does not bundle a Chinese font at this time. See any of the other Chinese bugs that are open for more info, like #2660.

**Comment by andydotxyz** [comment]
Also please do not use a feature request to ask a question without. Try to search for answers or ask on one of the discussion / support channels.
