### ISSUE TITLE
It does not appear that a Label widget can be made Shortcutable

### ISSUE THREAD

**Issue by pbrown12303** [fyne-io/fyne#4066]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If I extend the Label widget  and add a TypedShortcut, the widget does not respond to the shortcut function. If I extend the Entry widget, it works fine. 

### How to reproduce

1. Extend the Label widget
2. Add a TypedShortcut function for the extended widget
3. Add the widget to a displayed screen
4. Put a breakpoint in the TypedShortcut function
5. Interact with the widget - the function is never called

The code below is the example I tried. If I change the struct to include widget.Entry instead of widget.Label and uncomment the label.Disable() line, I get the desired behavior.

Note that the compiler is happy with the variable of type fyne.Shortcutable being assigned a *shortcutableLabel. It just doesn't work. 

### Example code

```go
var _ fyne.Shortcutable = (*shortcutableLabel)(nil)
var _ fyne.Focusable = (*shortcutableLabel)(nil)

type shortcutableLabel struct {
	widget.Label
}

func (sl *shortcutableLabel) FocusGained() {
	log.Print("Focus Gained")
}

func (sl *shortcutableLabel) FocusLost() {
	log.Print("Focus Lost")
}

func (sl *shortcutableLabel) TypedKey(*fyne.KeyEvent) {

}

func (sl *shortcutableLabel) TypedRune(rune) {

}

func newFocusableLabel() *shortcutableLabel {
	label := &shortcutableLabel{}
	label.ExtendBaseWidget(label)
	// label.Disable()
	return label
}

func (sl *shortcutableLabel) TypedShortcut(shortcut fyne.Shortcut) {
	log.Print(shortcut.ShortcutName())
	switch typedShortcut := shortcut.(type) {
	case *fyne.ShortcutCopy:
		typedShortcut.Clipboard = FyneGUISingleton.window.Clipboard()
		typedShortcut.Clipboard.SetContent(sl.Text)
	}
}

```

### Fyne version

2.3.5

### Go compiler version

1.20.6

### Operating system and version

Windows 10

**Comment by dweymouth** [comment]
You have to implement all 4 methods of Focusable in order to create a focusable widget (even if you stub out the implementations)

https://developer.fyne.io/api/v2.3/focusable.html

**Comment by pbrown12303** [comment]
Sorry, Shortcutable is what I am after and didn't update the code names and my title appropriately. All updated now.

**Comment by andydotxyz** [comment]
You can't get shortcut events unless the widget is focused - so it must be Focusable and also actually be focused.

**Comment by pbrown12303** [comment]
I had already tried that (later removing the Focusable functions). I have added them back in. No matter what I do, the FocusGained() never gets called for a Label. It does for an Entry.

**Comment by pbrown12303** [comment]
If there is a dependency between Shortcutable and Focusable, the documentation for Shortcutable should mention this.

**Comment by andydotxyz** [comment]
> I had already tried that (later removing the Focusable functions). I have added them back in. No matter what I do, the FocusGained() never gets called for a Label. It does for an Entry.

If you tab/shift-tab around your UI it will get focus. You may want to update the display slightly when it does. If you want to gain focus on tap you'll need to make it Tappable as well, and request focus when your input is tapped.

**Comment by pbrown12303** [comment]
Still have issues. Even if I tab around and get the focus in the Label widget (which is a pain), the right mouse does not bring up the menu of shortcuts. Is there yet another function I need to implement?

With respect to focus, how do I request focus for the Label widget? The only RequestFocus I can find is on the window itself.
