### ISSUE TITLE
widget.Select doesn't display all items on mobile

### ISSUE THREAD

**Issue by blaize** [fyne-io/fyne#4068]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I have enought options in widget.Select to have to scroll down to choose one, I noticed one or more elements in the end doesn't show up on Android 13.

Works fine on Windows.
Can't select the last option on android emulator and real android phone.

In my real app, where there are more options, this is worse. I can't select the last 3 options.

### How to reproduce

1/ Compile the sample code attached with fyne package -os android -appID select.size
2/ Run on emulator or real android device
3/ Try to select the option 24

### Screenshots

https://github.com/fyne-io/fyne/assets/1087443/2d6fea97-0879-41cb-925f-b7287acdaf62

### Example code

```
package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.NewWithID("select.size")
	w := a.NewWindow("select.size")

	lstr := make([]string, 25)

	for i := 0; i < 25; i++ {
		lstr[i] = fmt.Sprintf("%d", i)
	}

	sel := widget.NewSelect(lstr, func(s string) {})

	w.SetContent(sel)

	w.ShowAndRun()

}

```

### Fyne version

2.3.5

### Go compiler version

1.20.5

### Operating system and version

Android 13

**Comment by dan-frohlich** [comment]
I came here to report this issue as well.

**Comment by andydotxyz** [comment]
It seems to relate to the "safe area" - the top of an overflowing overlay gets moved but the height is not adjusted accordingly.
