### ISSUE TITLE
SVG image causes crash on MacOS

### ISSUE THREAD

**Issue by kargirwar** [fyne-io/fyne#4083]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When loading an SVG image using NewImageFromFile the app crashes immediately.  Trace below:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1000e0a80]

goroutine 5 [running, locked to thread]:
image.(*NRGBA).Bounds(0x1004c4322?)
	/usr/local/go/src/image/image.go:351
fyne.io/fyne/v2/internal/painter/gl.(*painter).imgToTexture(0xc0001007d0, {0x1006f7c90?, 0x0?}, 0x0?)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:100 +0x342
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlImageTexture(0xc0001007d0, {0x1006fae80?, 0xc00007c180})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:124 +0xbd
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc0001007d0, {0x1006fae80, 0xc00007c180}, 0xc00005d970)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc0001007d0, {0x1006fae80?, 0xc00007c180?}, 0xc000012060?, {0x18?, 0x0?}, {0x18?, 0x0?}, {0x5d980?, 0xc0?}, ...)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:171 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawImage(0xc0001007d0, 0xc00007c180, {0x281da0?, 0x1?}, {0x7c19c?, 0xc0?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:40 +0xb2
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0x100f9b108?, {0x1006fae80?, 0xc00007c180?}, {0xe05d?, 0x1?}, {0x56ce00?, 0x1?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:83 +0x72
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0xc00002a0e0?, {0x1006fae80, 0xc00007c180}, {0x3fbe25?, 0x1?}, {0x0?, 0x0?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/painter.go:89 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0x10058c820?, {0x7c180?, 0xc0?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:287 +0x115
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0x1006fae80?, 0xc00007c180}, {0x7c180?, 0xc0?}, {0x6f9e5?, 0x1?}, {0x5db48?, 0xc0?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0x1006fae80, 0xc00007c180}, 0x0, {0x0, 0x0}, {0x41911?, 0x1?}, {0x0?, 0x0?}, {0x5dc38?, ...}, ...)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/util.go:169 +0x2b2
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0x1006fae80?, 0xc00007c180?}, 0xc000007a00?, 0x200000003?)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc000036080, 0xc00005dd80, 0xc00005dd50)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc00040c000, 0xc00005dd50?, 0x1004c4886?)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc00040c000, {0x0?, 0x0?})
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:299 +0xfb
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:207 +0x8f
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003c13b0?, 0xc00005de30)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00005de98?, 0xc000072400?)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc00005df90?)
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:254 +0x1a6
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/pankaj/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:230 +0xea
exit status 2

### How to reproduce

Compile and run the code below. Use image from here [https://upload.wikimedia.org/wikipedia/commons/b/b8/Clock_11-06.svg](url)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Image")
	image := canvas.NewImageFromFile("clock.svg")
	image.FillMode = canvas.ImageFillOriginal
	w.SetContent(image)

	w.ShowAndRun()
}

```

### Fyne version

2.3.5

### Go compiler version

1.20.6

### Operating system and version

macOS Monterey 12.6.1

**Comment by andydotxyz** [comment]
It looks like the image was nil - are you certain that is the right relative path?

**Comment by kargirwar** [comment]
> It looks like the image was nil - are you certain that is the right relative path? Were there any warnings before the crash?

The image is in same directory as main.go. I have given entire stack trace.

**Comment by andydotxyz** [comment]
Are you running with "go run" or from a "fyne package" app icon?

**Comment by andydotxyz** [comment]
Just checking at this end. Works perfectly using "go run"

**Comment by brokenarmor451** [comment]
It occurs in my computer's os too (q4os debian 11.7 based).
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5348a0]

goroutine 24 [running, locked to thread]:
image.(*NRGBA).Bounds(0xa006e2?)
        /usr/local/go/src/image/image.go:351
fyne.io/fyne/v2/internal/painter/gl.(*painter).imgToTexture(0xc00013e0a0, {0xc7e740?, 0x0?}, 0x0?)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:100 +0x342
fyne.io/fyne/v2/internal/painter/gl.(*painter).newGlImageTexture(0xc00013e0a0, {0xc81dd8?, 0xc0000c2300})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:124 +0xbd
fyne.io/fyne/v2/internal/painter/gl.(*painter).getTexture(0xc00013e0a0, {0xc81dd8, 0xc0000c2300}, 0xc00005d970)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/texture.go:36 +0x4f
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawTextureWithDetails(0xc00013e0a0, {0xc81dd8?, 0xc0000c2300?}, 0xc00011ea50?, {0x18?, 0x0?}, {0x18?, 0x0?}, {0x5d980?, 0xc0?}, ...)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:171 +0x8b
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawImage(0xc00013e0a0, 0xc0000c2300, {0x7117c0?, 0x0?}, {0xc231c?, 0xc0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:40 +0xb2
fyne.io/fyne/v2/internal/painter/gl.(*painter).drawObject(0x7fdd68110a68?, {0xc81dd8?, 0xc0000c2300?}, {0x43275d?, 0x0?}, {0xac3d00?, 0x0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/draw.go:83 +0x72
fyne.io/fyne/v2/internal/painter/gl.(*painter).Paint(0xc000118950?, {0xc81dd8, 0xc0000c2300}, {0x8bc265?, 0x0?}, {0x0?, 0x0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/painter/gl/painter.go:89 +0x74
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0xae6b00?, {0xc2300?, 0xc0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:287 +0x115
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree.func1({0xc81dd8?, 0xc0000c2300}, {0xc2300?, 0xc0?}, {0x497665?, 0x0?}, {0x0?, 0x0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:438 +0x277
fyne.io/fyne/v2/internal/driver.walkObjectTree({0xc81dd8, 0xc0000c2300}, 0x0, {0x0, 0x0}, {0x466f51?, 0x0?}, {0x0?, 0x0?}, {0x5dc38?, ...}, ...)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/util.go:169 +0x2b2
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree({0xc81dd8?, 0xc0000c2300?}, 0xc000082ea0?, 0x200000003?)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/util.go:134 +0x4c
fyne.io/fyne/v2/internal/driver/common.(*Canvas).walkTree(0xc000000000?, 0xc0000a2600, 0xc00005dd80, 0xc00005dd50)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:459 +0x165
fyne.io/fyne/v2/internal/driver/common.(*Canvas).WalkTrees(0xc0000a8240, 0xc00005dd50?, 0xa00dc6?)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/common/canvas.go:371 +0x3c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc0000a8240, {0x0?, 0x0?})
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/canvas.go:299 +0xfb
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:207 +0x8f
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0004173b0?, 0xc00005de30)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/window.go:907 +0x4f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00005de98?, 0xc000128340?)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:198 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc00005df90?)
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:106 +0x1ac
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:254 +0x1a6
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/xxx/go/pkg/mod/fyne.io/fyne/v2@v2.3.5/internal/driver/glfw/loop.go:230 +0xea
exit status 2
```
But if I don't change fill mode to original or I use develop branch instead of v2.3.5 there is no problem.

**Comment by andydotxyz** [comment]
Ah, ok cool so develop branch already has it fixed.
That's cool as we are working towards release already.

**Comment by longsizhuo** [comment]
> original

you save me all day, just do not use `img.FillMode = canvas.ImageFillOriginal` can help to solve problem
