### ISSUE TITLE
Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#409]
I was trying to run fyne_demo but got crash. Fyne is fresh from go get. 

go version go1.12.9 windows/386
Windows 10

```
2019/08/22 18:34:43 Fyne error:  window creation error
2019/08/22 18:34:43   Cause: APIUnavailable: WGL: The driver does not appear to support OpenGL
2019/08/22 18:34:43   At: T:/libraries/Gopath/src/fyne.io/fyne/internal/driver/gl/window.go:999
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by andydotxyz** [comment]
Can you confirm what graphics card and related hardware you are running on?
This could be related to an issue with computers that have twin graphics chips where one of them does not support full OpenGL. If we can find more info then we may be able to work a solution.

**Comment by Kvaz1r** [comment]
Graphics card - AMD Radeon vega mobile gfx

**Comment by andydotxyz** [comment]
Do you have a model number?

**Comment by Kvaz1r** [comment]
Problem solved by updating drivers. I start hating Win10 ;-)

**Comment by elgs** [comment]
I have the same problem running Win10 in Virtualbox.

**Comment by andydotxyz** [comment]
@elgs can you try turning on the virtual graphics hardware and/or installing a graphics driver?

**Comment by elgs** [comment]
@andydotxyz do you happen to know where the virtual graphics hardware is to turn on? I was not able find it.

**Comment by andydotxyz** [comment]
On the macOS host it's in the per-VM settings screen under "Display", here are my settings:

![Screenshot 2020-10-26 at 08 03 09](https://user-images.githubusercontent.com/294436/97147672-c6d44a00-1761-11eb-9ec0-2b83168b6e84.png)

**Comment by elgs** [comment]
Thank you so much for the fast reply. I know this is not related to fyne library. But I was not able to set Graphics Controller to VMSVGA. I got invalid setting detected. I don't know why. I tried to google this error message, but didn't get really helpful information.

![2020-10-26 01 17 46](https://user-images.githubusercontent.com/55955/97148912-1fd3bc00-1729-11eb-9255-3f502400d10b.gif)

**Comment by andydotxyz** [comment]
Just see what combinations you can use and try them. One might work.
It's possible that the issue was missing drivers in Windows rather than missing graphics in the VM.

**Comment by elgs** [comment]
Checking the Enable 3D Acceleration did the trick! Thank you so much!

**Comment by carlbomsdata** [comment]
I have the same problem on my Windows 11 machine.
I am connected using RDP session.

<img width="394" alt="Screenshot 2024-10-31 at 21 52 42" src="https://github.com/user-attachments/assets/bb8bab18-55c7-4c21-9711-e7a18f9e059b">
<img width="449" alt="Screenshot 2024-10-31 at 21 51 46" src="https://github.com/user-attachments/assets/9ae9b3e0-be71-4204-a115-214d5b0c5594">

Any ideas?

**Comment by andydotxyz** [comment]
The OpenGl 1.1 is decades old - we need 3.1 at least (15 years old or more).
The generic display adapter is not sufficient, but you could use mesa3d.dll as other windows server users have suggested for Remote Desktop execution.

**Comment by andydotxyz** [comment]
Running a driver from 2006 on windows 11 looks a bit suspicious though. As per the OP maybe an update will fix it.
