### ISSUE TITLE
Add menu support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#41]
Drop down menu from a menu bar to start with.
The toolbar layout could be re-used - then we can use layout.NewSpacer() to right align items like a "Help" menu.

The drop-downs should have separator support which would be horizontal lines, similar to the toolbar vertical ones.

Let's not worry about cascading menus yet :)

**Comment by steveoc64** [comment]
Qt (I think its Qt) does it right on the mac as well - adding it to the MacOSX menu at the top.

I think you can do this with some effort with the Gtk bindings, but its work.

**Comment by andydotxyz** [comment]
Requires #155

**Comment by andydotxyz** [comment]
This is ready to test on the feature/menu branch.
No support for macOS native menus yet but it works in-canvas for Windows, Linux (and macOS).

**Comment by andydotxyz** [comment]
This is now on develop branch for testing
