### ISSUE TITLE
I cannot use fyne.io/fyne/v2/app in my program

### ISSUE THREAD

**Issue by Immanuel-supanova** [fyne-io/fyne#4104]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Karen 3")

	w.SetContent(widget.NewLabel("Hello World"))
	w.ShowAndRun()
}

### How to reproduce

1. go run main.go
2. The error:

package command-line-arguments
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v3.2-core/gl: build constraints exclude all Go files in C:*********\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v3.2-core\gl

### Example code

package main

import (
	"fyne.io/fyne/v2/app" // the issue is with this line
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Karen 3")

	w.SetContent(widget.NewLabel("Hello World"))
	w.ShowAndRun()
}

### Fyne version

v2.3.5

### Go compiler version

1.20

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
Strangely what this message means is that you don't have the required C compiler installed to make the behind-the-scenes graphics code work.

https://developer.fyne.io/started/

**Comment by Jacalz** [comment]
Closing per the comment above
