### ISSUE TITLE
Memory leak in font metrics cache

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4108]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The `fontSize` cache [here](https://github.com/fyne-io/fyne/blob/develop/internal/cache/text.go#L10) is only cleaned out on settings change, and it stores arbitrary user-supplied strings in the map key. It should be made an expiring cache and have expired entries cleaned out during the periodic clean task.

### How to reproduce

Run fyne_demo and scroll through all rows of the list/table demos, or any other text-heavy Fyne app.

### Example code

fyne-demo

### Fyne version

develop

### Go compiler version

go1.19.4 darwin/amd64

### Operating system and version

Mac OS

**Comment by andydotxyz** [comment]
Thanks @dweymouth for resolving this (on develop) for v2.4.0 :)
