### ISSUE TITLE
Add images to visual elements documentation

### ISSUE THREAD

**Issue by cassis163** [fyne-io/fyne#4111]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Tried to use this toolkit, but not getting a quick overview of what the visual elements actually look like annoys me. The provided code snippets alone are not enough for getting a quick feel of what this toolkit provides.

### Describe the solution you'd like to see.

Quick and easy visual cues of the provided elements that this toolkit provides. I want to see what stuff looks like.

**Comment by Jacalz** [comment]
We have a development documentation site over at https://developer.fyne.io/ and the [Getting started](https://developer.fyne.io/started/) page mentions running the demo which puts pretty much all of the components on display. Is there anything that is missing from that?

**Comment by Jacalz** [comment]
The [Widget List](https://developer.fyne.io/explore/widgets) also provides images for a variety of different widgets. You will find a lot of similar pages for icons, layouts and dialogs under the same category.

**Comment by cassis163** [comment]
Ah, my bad. I should admit that I was skimming through the docs. The thing is that I expected the individual widget pages to also contain a visual preview (for example https://developer.fyne.io/widget/choices).
