### ISSUE TITLE
button with icon has wrong padding on right

### ISSUE THREAD

**Issue by pseidemann** [fyne-io/fyne#4124]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

when a button has an icon, the padding on the left and the padding on the right have a mismatch, making the content of button look shifted to the right. the fix would be to have the right padding equal to the left padding.

### How to reproduce

open demo and click on "widgets"

### Screenshots

<img width="85" alt="Screenshot 2023-08-03 at 00 41 46" src="https://github.com/fyne-io/fyne/assets/431162/346b057f-e4a3-4a90-ba40-bcb76d60629f">

### Example code

```go
widget.NewButtonWithIcon("Cancel", theme.CancelIcon(), func() {})
```

### Fyne version

2.3.5

### Go compiler version

1.20.6

### Operating system and version

macOS 13.5

**Comment by andydotxyz** [comment]
This has already been resolved on develop :) release coming soon
