### ISSUE TITLE
Add mobile menu support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#413]
Burger button and side bar?

**Comment by joeblew99** [comment]
MacDonalds or Burger King :) Sorry i could not help myself.

I see lots of use for a bottom app strip these days.  No idea o the proper name. Google chrome beta uses it.
Like this: https://www.androidpolice.com/wp-content/uploads/2019/05/chrome-duet-labels-on-3.png
For mobile it makes lots of sense as your thumb is close to it.

**Comment by andydotxyz** [comment]
That's probably functionally a toolbar. We have not thought about ho our toolbar works on mobile yet, but it could have similar styling...
Menu is different, usually less frequently used item hence why it's behind a burger button.

**Comment by andydotxyz** [comment]
Merged to develop
