### ISSUE TITLE
Improve design of tabs to fit better with rounded corners

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4130]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The current design of the tab bar is inherently hard to adapt to the new theme look with rounded corners. it is especially true for the selection. We should think about updating the design to fit in better with the new theme. This is how it looks in contrast to the rounded button:
![image](https://github.com/fyne-io/fyne/assets/25466657/4d8c6f4e-ac7e-4634-aca7-c17ccc7d032a)

Just making the selection rectangle rounded would not fit in with the tab bar below.

### Is it possible to construct a solution with the existing API?

It depends on the ideas being used. If we want to solve the idea about using rounded top corners then no. Otherwise yes.

### Describe the solution you'd like to see.

One idea that I initially had was to solve the issue by using rounded corners on the top part of the selection. I don't if it is the best solution but it is (apart from the fact that we can't individually control rounded corners yet) more or less the simplest as we won't need to get rid of the tab bar. See mockup below:
![image](https://github.com/fyne-io/fyne/assets/25466657/6e2e94fe-6661-441c-b6f9-935a9c1ba79e)

### Some other inspiration:
How tabs in Firefox look:
![image](https://github.com/fyne-io/fyne/assets/25466657/1b767293-79da-4514-8bbc-716a6264dd16)

How tabs look in Adwaita:
![image](https://github.com/fyne-io/fyne/assets/25466657/3007d596-5eea-47d9-91ee-5ae1916e300d)

**Comment by Jacalz** [comment]
Another option would be to round the entire tab selector and have the tab selection bar be rounded as well (pill shaped):
![image](https://github.com/fyne-io/fyne/assets/25466657/c5936667-a185-4b0d-b7ad-0548299ee5f7)

**Comment by ismyhc** [comment]
> Another option would be to round the entire tab selector and have the tab selection bar be rounded as well (pill shaped): ![image](https://user-images.githubusercontent.com/25466657/258204297-c5936667-a185-4b0d-b7ad-0548299ee5f7.png)

Not a fan of this. Personally I wouldn't carry much over from the current tab design. 

In my opinion it should take inspiration from Adwaita's View Switcher. Probably fairly simple to implement as well.

![view-switcher-title-dark](https://github.com/fyne-io/fyne/assets/840551/46e5c5a3-2b8e-40f5-8db9-714b34c79fa6)
![view-switcher-bar](https://github.com/fyne-io/fyne/assets/840551/d11a4ab1-2b4d-44dd-8ec3-015184f7d830)

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ViewSwitcher.html

**Comment by andydotxyz** [comment]
I don't think we should switch to the adwaita style just for one widget, the use of primary colour from material makes this feel much clearer to what is going on.

I am considering just rounding the hover rectangles for now at least, it's a pretty good intermediate suggestion. How the selection indicator works is the larger question.

**Comment by Jacalz** [comment]
> I don't think we should switch to the adwaita style just for one widget, the use of primary colour from material makes this feel much clearer to what is going on.

I agree with you. While I am generally big fan of Adwaita, we are not following the same design principles and I don't think their tab design would fit in very well. I'm also quite a fan of how the little blue line animates back and forth to show the selected tab.

We could try rounding the tab selection indicator. I think it might look good and it shouldn't be very hard to try. It will likely make the rounded selection indicators look less out of place.

**Comment by Jacalz** [comment]
Develop now has the improved tab design. Closing
