### ISSUE TITLE
`Select` has wrong height, padding and border

### ISSUE THREAD

**Issue by pseidemann** [fyne-io/fyne#4142]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

compared to Entry, MultiLineEntry and SelectType, `Select` has the wrong height, padding and border.

it doesn't have a border all around, but instead just a border on the bottom. the padding inside Select seems to be less. the padding outside is wrong (?).

this is especially visible in a Form widget. there, the label doesn't align properly with the Select.

### How to reproduce

open fyne demo and go to input widgets

### Screenshots

<img width="752" alt="Screenshot 2023-08-06 at 21 33 11" src="https://github.com/fyne-io/fyne/assets/431162/2a8e9d14-19f2-4ed1-b7fd-8fed0c79b29d">

inside a Form widget:

<img width="470" alt="Screenshot 2023-08-06 at 21 37 53" src="https://github.com/fyne-io/fyne/assets/431162/0e40eb6c-e6d4-4176-a092-f11883a0fe51">

### Example code

fyne demo

### Fyne version

2.3.5

### Go compiler version

1.20.6

### Operating system and version

macOS 13.5

**Comment by andydotxyz** [comment]
The select styling has already been updated for v2.4.0
