### ISSUE TITLE
Add keyboard support for iOS and Android

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#415]

**Comment by andydotxyz** [comment]
This may be a lot of work if we want to use the system keyboard...
Gomobile does not support it... https://github.com/golang/go/issues/9361.

We could take the "custom keyboard" route, which is probably required for tablet linux anyway... but it will make the keyboards far less capable than the expected system provided ones...

**Comment by Bluebugs** [comment]
Nuklear support it via a Java bridge:
https://github.com/golang-ui/nuklear/blob/7fd95796294db4f4204fb36cf78eaa70fbbab501/cmd/nk-android/main.go#L174-L180

**Comment by andydotxyz** [comment]
Android support for keyboard is now on develop branch for testing :)

**Comment by andydotxyz** [comment]
iOS is now also on develop branch
