### ISSUE TITLE
fyne.TextTruncate is deprecated but Entry widget has no replacement

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4157]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

We have deprecated the `fyne.TextTruncate` constant and replaced it with `fyne.TextTruncateClip` but the replacement doesn't work in `Entry` because it has no `Truncation:` field (it really shouldn't have either but we need a better way to set truncation). This means that people will get deprecation notices that they can't do anything about which will be annoying and confusing.

### How to reproduce

1. Create an entry with `entry.Wrapping = fyne.TextTruncate`.
2. Run `staticcheck ./...` in the project root (not in the Fyne repo, deprecation warnings are currently disabled)
3. See deprecation warning

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewEntry()
	hello.Wrapping = fyne.TextTruncate
	w.SetContent(hello)

	w.ShowAndRun()
}
```

### Fyne version

2194a0ffe3065cc43092d48a978141eba0703ba7

### Go compiler version

1.20.7

### Operating system and version

Fedora Linux 38

**Comment by Jacalz** [comment]
I realized that there is a problem here. The Entry's `Scroll` field takes a `widget.ScrollDirection` form the `internal/widget` package. A user has to know that `container.ScrollDirection` is the same thing. However, we can not import `container` into the `widget` package because we get a circular dependency. Any ideas for what we should do?

**Comment by andydotxyz** [comment]
> I realized that there is a problem here. The Entry's `Scroll` field takes a `widget.ScrollDirection` form the `internal/widget` package. A user has to know that `container.ScrollDirection` is the same thing (my IDE was definitely not smart enough). However, we can not import `container` into the `widget` package because we get a circular dependency. Any ideas for what we should do?

This is a pre-existing issue and matches the pattern in `RichText`. Once we have a solution it will be a non-breaking change to apply it to both as these are aliases.
