### ISSUE TITLE
Tiny height miscalculation in multiline entry

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#4159]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Height calculation in MultLineEntry based on SetMinRowsVisible is a little wrong.
Too small for 2 lines (VScroll appearing), somewhat good for 3 lines, a little too big for 4 lines and more.

### How to reproduce

Write text in a multiline entry.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/1791230/44e2ccc9-2571-4d32-80cd-12726e526511)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("")

	var entries []fyne.CanvasObject
	for i := 0; i < 5; i++ {
		e := widget.NewMultiLineEntry()
		e.SetMinRowsVisible(i + 2)
		entries = append(entries, e)
	}

	w.SetContent(container.NewVBox(entries...))
	w.ShowAndRun()
}
```

### Fyne version

v2.3.6-0.20230805063135-4e8dee148627

### Go compiler version

1.21

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
Fixed for release :)
