### ISSUE TITLE
Add appropriate tools for building mobile apps

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#417]
Let's integrate with the "fyne build" command so we don't have to rely on the slightly out of date "gomobile".

**Comment by joeblew99** [comment]
Mihgt be useful ?
https://github.com/ClarkGuan/ddmobile/blob/master/env.go

**Comment by joeblew99** [comment]
For devs to get all the bits srtup right leads to a ton of issues i noticed.

There is a boot strapper here:
https://github.com/winwisely99/bootstrap/tree/master/mac
https://github.com/winwisely99/bootstrap/tree/master/win
It gets everything onto their OS using brew and scoop. 
On the cards is to wrap it with golang and then sniff what OS they are on and just make the correct calls to brew and scoop. 
Gotta add linux i know :)

Then how to compile stuff for desktop and mobile.
At the moment we use hover and flutter. Its wrapped in a Make file and again on the cards to wrap it using golang.
https://github.com/winwisely99/bootstrap/blob/master/example/flutter/go-flutter-desktop/examples/Makefile

Plan is to support golang mobile and fyne. 
Then Users can use fyne and / or flutter together.

**Comment by andydotxyz** [comment]
Basic integration is there but it requires gomobile installed - this should be fixed before release but is now a lower priority...

Also it requires the not-yet-released go compiler from git so we should return to this after that is released...

**Comment by andydotxyz** [comment]
This probably needs further work but the build tools are in and the gomobile dependency is out.
Closing this high level ticket and we can open more if required for follow on improvements.
