### ISSUE TITLE
fyne release -os android/arm 

### ISSUE THREAD

**Issue by gyanpatel** [fyne-io/fyne#4174]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

fyne release command fails when specifying rch type 
e.g.
fyne release -os android/arm 

### How to reproduce

create a release using arch type

fyne release -os android/arm 
fyne release -os android/arm64 etc

### Example code

any fyne mobile app 

### Fyne version

v2.3.5

### Go compiler version

1.20

### Operating system and version

MacOS Darwin

**Comment by gyanpatel** [comment]
inflating: tmpbundle/resources.pb
 extracting: tmpbundle/classes.dex
 extracting: tmpbundle/lib/armeabi-v7a/libkiddos.so
 adding: res/ (stored 0%)
 adding: res/mipmap-xxxhdpi-v4/ (stored 0%)
 adding: res/mipmap-xxxhdpi-v4/icon.png (deflated 9%)
 adding: manifest/ (stored 0%)
 adding: manifest/AndroidManifest.xml (deflated 65%)
 adding: lib/ (stored 0%)
 adding: lib/armeabi-v7a/ (stored 0%)
 adding: lib/armeabi-v7a/libkiddos.so (deflated 34%)
 adding: resources.pb (deflated 12%)
 adding: dex/ (stored 0%)
 adding: dex/classes.dex (deflated 52%)
Enter Passphrase for keystore:
**jarsigner: unable to open jar file: /Users/lakshmipatel/play-store
exit status 1**

**Comment by andydotxyz** [comment]
Fixed on develop and will be in v2.4.3
