### ISSUE TITLE
How to get tap/mouse events on raster canvas

### ISSUE THREAD

**Issue by benc-uk** [fyne-io/fyne#418]
I'm adding a raster canvas to my window
```
mainCanvas := canvas.NewRasterWithPixels(redrawMyCanvas)
window.SetContent(mainCanvas)
```
Which is works great, but now I want to get tap events on that canvas or window

Looking through the API can't see any way to do this, I found a way to get key events from the main app window, but taps & clicks seem strangely elusive 

What am I missing?

**Comment by andydotxyz** [comment]
The basic canvas objects are not interactive, so don’t provide any hooks to get key or mouse presses. To get Tapped events you need to create a simple widget that implements the “Tappable” interface. You can have your Raster as the content and add Tapped() and TappedSecondary() to get these events. This is not extensively documented yet as we want to make it easier for the 1.2 release. I’d recommend checking out the “life” example in our examples repository which does most of what you want. https://github.com/fyne-io/examples

**Comment by benc-uk** [comment]
Thanks, I suspected that

**Comment by benc-uk** [comment]
I've spent some time on this and sorry, I've given up.

I looked at the 'life' example and copied some of it implementing all the CanvasObject methods, but now it's not clear how I get my actual canvas to render. I don't want to have to add all these new struct types and dozens of methods just to get some basic click events.

Do I need to implement CanvasObject? Widget? WidgetRenderer? All three?

I understand the library is very new, but it's very confusing to try to do something so basic

**Comment by okratitan** [comment]
This is how I did it in fyfoto. Substitute my canvas.Image with your raster:

https://github.com/okratitan/fyfoto/blob/7f87c4f145d36fbc1c1a43006779075fc1b1e36f/cmd/fyfoto/main.go#L44

https://github.com/okratitan/fyfoto/blob/7f87c4f145d36fbc1c1a43006779075fc1b1e36f/cmd/fyfoto/browser.go#L87

https://github.com/okratitan/fyfoto/blob/7f87c4f145d36fbc1c1a43006779075fc1b1e36f/cmd/fyfoto/thumbnailer.go#L110

**Comment by andydotxyz** [comment]
The way that the toolkit is designed the "canvas" package (basic drawing) is not interactive, to get user interactions it's the widget package. Yes we should make it simpler to create basic widgets (there are some plans but nothing in the codebase yet).

Perhaps the feature request of an interactive image widget #123 would be useful so you could add thoughts to that thread perhaps?

**Comment by benc-uk** [comment]
Understood, thanks Andy.

I've moved to using Ebiten, as for what I was doing (a window with a big canvas I wanted to push pixels into) it just makes more sense

I think it's best to close this for now.

I love what you're doing with Fyne, I'll definitely keep an eye on the project :)

**Comment by paultag** [comment]
I'd hit this same issue and also couldn't get it working properly. I seem to be hung up on the "inheritance" that's being added, as well as not being super clear on what types are being attempted to cast to a Tappable; I have no clear solution here, and am likely going to have to bail on using Fyre :(

**Comment by andydotxyz** [comment]
Hi @paultag the inheritance is not for canvas elements - just for Widgets.
The canvas primitives are tightly coupled to the graphics drivers so can't be extended in that way.
You might want to reference the `interactiveRaster` component added in our `pixelEdit` demo.

https://github.com/fyne-io/pixeledit/blob/master/internal/ui/raster.go

**Comment by paultag** [comment]
@andydotxyz I was able to cargo-cult that into working, thank you. In an effort to turn a negative interaction into something positive, is there a helpful way to contribute documentation that would make this easier to understand for newcomers? Even after getting it working, I'm not sure I understand why a canvas.Raster isn't a Widget itself (and why I needed the widget at all in this), so perhaps it'd be useful for me to turn those calories into a markdown file

**Comment by janpfeifer** [comment]
I know the topic is closed, but I'm still fumbling with this, and thought I would ask here. 

I want a CanvasObject (?? I'm assuming CanvasObject is something posititioned in a Canvas and knows how to draw itself, like a canvas.Rectangle ?) that is clickable.

I thought since the CanvasObject is drawable, it should be trivial. 

So I looked into @okratitan example (probably outdated now, using the undefined `widget.Box`), I don't see which code makes it draw the contained `imageObject`.

I also read through the [tutorial](https://developer.fyne.io/tutorial/write-custom-widget), but it also seems to indicate I have to implement a `CreateRenderer` method and a `WidgetRenderer` interface.

So I copied&pasted the internal `BaseRenderer` and added the missing methods, and the minimal, and not yet working, version of a very simple "TappableCanvas" I came up with was:

```
type TappableCanvas struct {
	widget.BaseWidget
	canvas   fyne.CanvasObject
	OnTapped func()
}

func NewTappableCanvas(canvas fyne.CanvasObject, onTapped func()) *TappableCanvas {
	return &TappableCanvas{BaseWidget: widget.BaseWidget{}, canvas: canvas, OnTapped: onTapped}
}

func (t *TappableCanvas) Tapped(ev *fyne.PointEvent) { t.OnTapped() }

type BaseRenderer struct{ objects []fyne.CanvasObject }

func NewBaseRenderer(objects []fyne.CanvasObject) *BaseRenderer { return &BaseRenderer{objects} }

func (r *BaseRenderer) Destroy() {}

func (r *BaseRenderer) Objects() []fyne.CanvasObject {
	return r.objects
}

func (r *BaseRenderer) SetObjects(objects []fyne.CanvasObject) {
	r.objects = objects
}

func (r *BaseRenderer) MinSize() fyne.Size { return r.objects[0].MinSize() }

func (r *BaseRenderer) Refresh() { r.objects[0].Refresh() }

func (r *BaseRenderer) Layout(size fyne.Size) {}

func (t *TappableCanvas) CreateRenderer() fyne.WidgetRenderer {
	return NewBaseRenderer([]fyne.CanvasObject{t.canvas})
}
```

There ought to be a simpler way, no ?

(I read through the docs, and some of the code, and still I don't see an easy way ... not widget that fits my needs either -- I could copy&paste a lots of code from Icon ... but I hoped it would be simpler)

**Comment by janpfeifer** [comment]
A little more poking around and I realized that `CanvasObjects` can also be interactive (be `Tappable`, `Draggable`, etc.).

That simplified things to:

```
type tappableCanvasObject struct {
	fyne.CanvasObject
	OnTapped func()
}

func MakeTappable(canvas fyne.CanvasObject, onTapped func()) *tappableCanvasObject {
	return &tappableCanvasObject{CanvasObject: canvas, OnTapped: onTapped}
}

func (t *tappableCanvasObject) Tapped(ev *fyne.PointEvent) { t.OnTapped() }
```

This make a tappable CanvasObject (I tested it), but for some reason the contained `canvas` doesnt' get drawn !? If I remove the `MakeTappable()` call and pass the `canvas` directly to my container, it gets drawn, but it's not longer tappable.

Any ideas what is happening ?

**Comment by andydotxyz** [comment]
> A little more poking around and I realized that `CanvasObjects` can also be interactive (be `Tappable`, `Draggable`, etc.).

This isn't really true unfortunately. To add interactivity you need to add new methods as you have shown, which requires extending / embedding other objects - this is what Widgets are designed for. The canvas primitives (`Rectangle` etc) are not extendible, they are passed to the driver to draw and it cannot understand a "custom" rectangle.
Interactive elements need to be widgets, that is how the API works.

**Comment by andydotxyz** [comment]
Extending `BaseWidget` is the simplest way to make a completely custom widget. There are two alternatives:
1) Find a simple widget and extend it (this can work for things like `widget.Icon`) - that way you can avoid defining a renderer.
2) Wait another few days and see #2279 land. This feature that will arrive in v2.1 means that you don't have to write a renderer but can instead do:

```
func (o *myObj) CreateRenderer() {
    return widget.NewSimpleRenderer(rect)
}
```

**Comment by janpfeifer** [comment]
Awesome, waiting for #2279, thanks!

**Comment by fish-hex** [comment]
> I know the topic is closed, but I'm still fumbling with this, and thought I would ask here.
> 
> I want a CanvasObject (?? I'm assuming CanvasObject is something posititioned in a Canvas and knows how to draw itself, like a canvas.Rectangle ?) that is clickable.
> 
> I thought since the CanvasObject is drawable, it should be trivial.
> 
> So I looked into @okratitan example (probably outdated now, using the undefined `widget.Box`), I don't see which code makes it draw the contained `imageObject`.
> 
> I also read through the [tutorial](https://developer.fyne.io/tutorial/write-custom-widget), but it also seems to indicate I have to implement a `CreateRenderer` method and a `WidgetRenderer` interface.
> 
> So I copied&pasted the internal `BaseRenderer` and added the missing methods, and the minimal, and not yet working, version of a very simple "TappableCanvas" I came up with was:
> 
> ```
> type TappableCanvas struct {
> 	widget.BaseWidget
> 	canvas   fyne.CanvasObject
> 	OnTapped func()
> }
> 
> func NewTappableCanvas(canvas fyne.CanvasObject, onTapped func()) *TappableCanvas {
> 	return &TappableCanvas{BaseWidget: widget.BaseWidget{}, canvas: canvas, OnTapped: onTapped}
> }
> 
> func (t *TappableCanvas) Tapped(ev *fyne.PointEvent) { t.OnTapped() }
> 
> type BaseRenderer struct{ objects []fyne.CanvasObject }
> 
> func NewBaseRenderer(objects []fyne.CanvasObject) *BaseRenderer { return &BaseRenderer{objects} }
> 
> func (r *BaseRenderer) Destroy() {}
> 
> func (r *BaseRenderer) Objects() []fyne.CanvasObject {
> 	return r.objects
> }
> 
> func (r *BaseRenderer) SetObjects(objects []fyne.CanvasObject) {
> 	r.objects = objects
> }
> 
> func (r *BaseRenderer) MinSize() fyne.Size { return r.objects[0].MinSize() }
> 
> func (r *BaseRenderer) Refresh() { r.objects[0].Refresh() }
> 
> func (r *BaseRenderer) Layout(size fyne.Size) {}
> 
> func (t *TappableCanvas) CreateRenderer() fyne.WidgetRenderer {
> 	return NewBaseRenderer([]fyne.CanvasObject{t.canvas})
> }
> ```
> 
> There ought to be a simpler way, no ?
> 
> (I read through the docs, and some of the code, and still I don't see an easy way ... not widget that fits my needs either -- I could copy&paste a lots of code from Icon ... but I hoped it would be simpler)

[#697](https://github.com/fyne-io/fyne/issues/697#issuecomment-2016711295),  I used "widget.NewSimpleRenderer" to achieve  better practice,
