### ISSUE TITLE
Scroll increment has changed in Develop

### ISSUE THREAD

**Issue by squidkeeper** [fyne-io/fyne#4180]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When implementing a Scrollable widget on a desktop system, I found that the minimum change in ScrollEvent.Scrolled.DY (one step of the mouse wheel) has changed from 10 in 2.3.5 to 25 in Develop (v2.3.6-0.20230822134109-060343c8c5b1).  Neither is particularly wrong, but the change is disconcerting, as I would have to do some rescaling, depending on version.

### How to reproduce

Create new widget that implements fyne.Scrollable.
Watch size of Scrolled.DY while gently moving mouse scroll wheel.
Observe increments differ between 2.3.5 and Develop.

### Example code

```
type Spinner struct {
        widget.BaseWidget
...
}

func (ms *Spinner) Scrolled(e *fyne.ScrollEvent) {
        log.Println("scroll by", e.Scrolled.DY)  // was 10, now it's 25
...
}
```

### Fyne version

2.3.5 vs. 2.3.6-0.20230822134109-060343c8c5b1

### Go compiler version

1.20.6

### Operating system and version

Ubuntu 22.04

**Comment by andydotxyz** [comment]
This was changed for Linux as a result of a bug that it was too slow.
What sort of "rescaling" is required to deal with scroll speed?

**Comment by squidkeeper** [comment]
OK, that's fine for me; just wondered if it was an accident. I'm using it to adjust a multi-digit spinner widget so I have to take account of the smallest possible increment (on desktop mouse). Example...

https://github.com/fyne-io/fyne/assets/137963349/5b5222d8-c804-4bd0-be68-8549aad7bf01

**Comment by andydotxyz** [comment]
Beware of doing this. Increment varies on different OS because of platform specific hardware abstractions. Don't make any assumptions about the smallest increment - it would be better to use a scroller or list etc where we handle the details for you.

**Comment by andydotxyz** [comment]
Also watch out, I don't think your widget will work on mobile devices.

**Comment by andydotxyz** [comment]
I do wonder now though - should we have an "ScrollIota" or similar constant made public which adjusts for the platform specific code? (Can't be 2.4 but maybe should be considered?)
