### ISSUE TITLE
./cmd/hello/main.go not working - no current Fyne app available

### ISSUE THREAD

**Issue by renlite** [fyne-io/fyne#4200]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In develop branche following error:
"Attempt to access current Fyne app when none is started"

````Go
func CurrentApp() App {
	val := app.Load()
	if val == nil {
		LogError("Attempt to access current Fyne app when none is started", nil)
		return nil
	}
	return (val).(appContainer).current
}
````

### How to reproduce

1. go run .\cmd\hello\main.go

### Example code

```Go
a := app.New()
```

### Fyne version

develop

### Go compiler version

1.21.0

### Operating system and version

Windows

**Comment by renlite** [comment]
It works in the meantime.

**Comment by andydotxyz** [comment]
Please check what version "develop" was pointing to.

**Comment by renlite** [comment]
Thanks, it's "## 2.4.0 - 30 August 2023".
I think I have had a sync problem. My fork is now in sync with the "develop" branche and it works.

**Comment by andydotxyz** [comment]
That's not a version number either sorry. If you're not using a tagged release we need the SHA from git to pin it down.

Glad it's fixed though
