### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by huqiuyun** [fyne-io/fyne#4205]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

the ico is stretching, not shrinking

### Describe the solution you'd like to see.

![image](https://github.com/fyne-io/fyne/assets/3490039/f45a708e-81cb-42d6-ad40-e56c3b86fafd)

code: 
	form := widget.NewForm(
		&widget.FormItem{Text: "程序状态：", Widget: container.NewHBox(programStatus, layout.NewSpacer())},
	)

the ico is stretching, not shrinking

**Comment by andydotxyz** [comment]
I don't understand this bug. There is no mention of `ico` in the code, nor any illustration of something being stretched...

**Comment by Jacalz** [comment]
Closing due to lack of response
