### ISSUE TITLE
Entry's  Wrapping Option not work in version 2.4.0

### ISSUE THREAD

**Issue by sunvim** [fyne-io/fyne#4212]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

in version v2.3.5 , it works well,  it shows like below:

![18d5eddccd74aeaa8.png](https://s1.imagehub.cc/images/2023/09/03/18d5eddccd74aeaa8.png)

but in v2.4.0 it not work, it shows like below:
![1012741adee7aadf8.png](https://s1.imagehub.cc/images/2023/09/03/1012741adee7aadf8.png)

### How to reproduce

run last code

### Example code

```go
package main

import (
"fyne.io/fyne/v2"
"fyne.io/fyne/v2/app"
"fyne.io/fyne/v2/container"
"fyne.io/fyne/v2/layout"
"fyne.io/fyne/v2/widget"
)

func main() {
myApp := app.New()
myWindow := myApp.NewWindow("entry wrapping bug")

pwdLabel := widget.NewLabel("passwd")
passwd := widget.NewEntry()
passwd.Wrapping = fyne.TextWrapOff
passwd.SetPlaceHolder("this password input entry")
confirmLabel := widget.NewLabel("confirm")
confirm := widget.NewEntry()
confirm.Wrapping = fyne.TextWrapOff
confirm.SetPlaceHolder("this confirm input entry")
grid := container.New(layout.NewFormLayout(), pwdLabel, passwd, confirmLabel, confirm)
myWindow.SetContent(grid)
myWindow.ShowAndRun()
}
```

### Fyne version

2.4.0

### Go compiler version

1.21.0

### Operating system and version

Linux home-ws 6.1.49-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Aug 27 23:08:04 UTC 2023 x86_64 GNU/Linux

### Additional Information

hope this project  better and better!

**Comment by andydotxyz** [comment]
I'm not sure what you're reporting - the entries do not appear to be wrapping.
What is the outcome expected that was not in 2.4.0?

**Comment by Jacalz** [comment]
Also please don’t share parts of an entire project for the example code. The text states that you should share a minimal running example.

**Comment by sunvim** [comment]
> I'm not sure what you're reporting - the entries do not appear to be wrapping. What is the outcome expected that was not in 2.4.0?

humm, sorry about that, I mean if I close the entry text wrapping, set  `Wrapping = fyne.TextWrapOff` , it should show like below in version v2.3.5 :

![1.png](https://s1.imagehub.cc/images/2023/09/03/1.png)

**Comment by sunvim** [comment]
> Also please don’t share parts of an entire project for the example code. The text states that you should share a minimal running example.

ok ,let me reedit it, thanks

**Comment by sunvim** [comment]
if adjust code, set entry Scroll attr to 3 , it works well!

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("entry wrapping bug")

	pwdLabel := widget.NewLabel("passwd")
	passwd := widget.NewEntry()
	passwd.Scroll = 3
	passwd.SetPlaceHolder("this password input entry")
	passwd.Wrapping = fyne.TextWrapOff
	confirmLabel := widget.NewLabel("confirm")
	confirm := widget.NewEntry()
	confirm.Scroll = 3
	confirm.SetPlaceHolder("this confirm input entry")
	confirm.Wrapping = fyne.TextWrapOff
	grid := container.New(layout.NewFormLayout(), pwdLabel, passwd, confirmLabel, confirm)
	myWindow.SetContent(grid)
	myWindow.ShowAndRun()
}

```

it shows:
![1b0763efcfb731f8e.png](https://s1.imagehub.cc/images/2023/09/03/1b0763efcfb731f8e.png)

but the widget `Entry` attr Scroll value  does not open for developer, so I have to set `confirm.Scroll = 3`, it should set `confirm.Scroll=ScrollNone`

![11083d11c14992181.png](https://s1.imagehub.cc/images/2023/09/03/11083d11c14992181.png)

**Comment by andydotxyz** [comment]
Set it to `container.ScrollNone` then.
Maybe this was missed from the changelog, I will get it into the upgrade notes

**Comment by andydotxyz** [comment]
I added a note to https://developer.fyne.io/api/v2.4/upgrading, hopefully that helps others that don't see where the constants are. They were used in `RichText` in 2.3, though it would be nice to find a solution that IDEs can suggest.
