### ISSUE TITLE
Problem in new version,with DWM

### ISSUE THREAD

**Issue by rw209** [fyne-io/fyne#422]
Very glad to see progress in Fyne, but new version brought run-time error in tail windows manager - DWM (dwm.suckless.org)
Im chek on old ver. - working fine
new version:
```
panic: InvalidValue: Invalid window minimum size -2147483648x-2147483648

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.acceptError(0x0, 0x0, 0x0, 0xffffffff, 0xffffffff)
        /home/user/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/error.go:173 +0x1c4
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.panicError(...)
        /home/user/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/error.go:184
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.(*Window).SetSizeLimits(0xa8841c0, 0x80000000, 0x80000000, 0xffffffff, 0xffffffff)
        /home/user/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:444 +0x5e
fyne.io/fyne/internal/driver/gl.(*window).fitContent(0xa87e750)
        /home/user/go/src/fyne.io/fyne/internal/driver/gl/window.go:248 +0x120
fyne.io/fyne/internal/driver/gl.(*window).SetContent.func1()
        /home/user/go/src/fyne.io/fyne/internal/driver/gl/window.go:372 +0x24
fyne.io/fyne/internal/driver/gl.runOnMain(0xa870a98)
        /home/user/go/src/fyne.io/fyne/internal/driver/gl/loop.go:44 +0x96
fyne.io/fyne/internal/driver/gl.(*window).SetContent(0xa87e750, 0x856a400, 0xa886240)
        /home/user/go/src/fyne.io/fyne/internal/driver/gl/window.go:371 +0x8d
main.welcome(0x856a440, 0xa886150)
        /home/user/go/src/github.com/fyne-io/examples/main.go:51 +0x209
main.main()
        /home/user/go/src/github.com/fyne-io/examples/main.go:90 +0x81f
```
Debian 9
go version go1.12.1 linux/386
fyne version - dont know, im do "go get -u fyne.io/fyne" about 3 hours ago

**Comment by andydotxyz** [comment]
I imagine this is version 1.1.1 as that is currently top of the default branch. When you say you checke d the "old version" and it worked - which version was that?

This may be due to auto-scaling and monitor hints. Can you try setting the FYNE_SCALE environment variable to 1 and reporting what happens? i.e. `env FYNE_SCALE=1.0 go run main.go`

**Comment by rw209** [comment]
Old version - about 8 - 9 august 2019

`env FYNE_SCALE=1.0 go run main.go` works fine.
how build binaries with this param?
`env FYNE_SCALE=1.0 go build` still crash with previous error

**Comment by andydotxyz** [comment]
That parameter is for runtime and is not compiled in.
We are changing how scaling defaults in the next release so perhaps we can make 1.0 default so that people don't experience problems with strange video drivers or monitors.

**Comment by rw209** [comment]
Ok, thank you
