### ISSUE TITLE
Multiline Entry with long text becomes very slow/laggy when typing

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#4221]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Typing in an Entry with a long text is very laggy.

### How to reproduce

Run the code, type some text.

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"github.com/brianvoe/gofakeit/v6"
)

func main() {
	a := app.New()
	w := a.NewWindow("")

	e := widget.NewMultiLineEntry()
	e.Wrapping = fyne.TextWrapWord
	e.SetText(gofakeit.Paragraph(10, 10, 10, "\n\n"))

	w.SetContent(e)
	w.Resize(fyne.NewSize(400, 400))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.4.0

### Go compiler version

1.20.7

### Operating system and version

Windows 10

**Comment by Jacalz** [comment]
This likely relates to https://github.com/fyne-io/fyne/issues/2969.

**Comment by andydotxyz** [comment]
I would think this is specific to wrapping and not just universal - is that correct?

**Comment by andydotxyz** [comment]
Then I agree, this is a duplicate. There is work to fix this but it's quite complex so is taking some time.
