### ISSUE TITLE
Pasting text in entry places the cursor before content, not after

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4229]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When pasting something into the Entry widget, it places the cursor in the wrong position. It places the position to the left of the pasted content until I press left or right it moves the cursor relative to the right of the pasted content. It behaves very strangely.

### How to reproduce

1. Paste this into an entry widget: "hello"
2. Notice that cursor is to the left of the word
3. Press the right arrow
4. Notice that it moves the cursor to the right of the word
5. Paste "hello" once again
6. Press left arrow
7. Notice that the cursor is to the left of the last "o"

### Example code

Just use any entry in fyne_demo

### Fyne version

v2.4.0

### Go compiler version

1.20.8

### Operating system and version

Fedora Linux 38

**Comment by matwachich** [comment]
You did not search the issue tracker hhhhh
https://github.com/fyne-io/fyne/issues/4181

**Comment by Jacalz** [comment]
Whoops. I checked the latest unverified issues opened and the v2.4.x milestone but found nothing. I'll make sure to add that one to the milestone...
