### ISSUE TITLE
modify the design of a button or label, widget

### ISSUE THREAD

**Issue by SeaSalvageUnit** [fyne-io/fyne#423]
Should you use https://fyne.io/develop/custom-widget.html to modify the design of a button or label?

I want to create a design I think but it's hard

Is there an example of design modification

**Comment by andydotxyz** [comment]
We don't really support widget customisation. If you are using standard widgets then the design is set. If you want custom designs then you need to build custom widgets.
Apologies if that is not ideal, but our "widget" package is trying to preserve a consistent user experience including design and style.

If there is a semantic property of a widget that we have missed then a feature request could be raised, but if it's to override theme properties for certain items we likely won't add that.

**Comment by SeaSalvageUnit** [comment]
@andydotxyz Thanks.
