### ISSUE TITLE
Calling Entry.SetText and then Entry.Bind immediately will ignore the bound value

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4235]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Due to recent "debounce" delay code the `SetText` is taken as user input, but if done before a bind this is not correct.

### How to reproduce

* Create an Entry
* Set the text
* Bind
* See that the bound value is not shown

### Example code

```go
s := binding.NewString()
s.Set("replace")
e := widget.NewEntry()
e.SetText("Thing")
e.Bind(s)
```

### Fyne version

2.4.0

### Go compiler version

1.21.1

### Operating system and version

Darwin

**Comment by williambrode** [comment]
This is the PR that added the delay code for reference: https://github.com/fyne-io/fyne/pull/4062

Another affect of this change is that bound entries don't update if changes are too rapid.  I'll open a separate issue to track that - though its root cause will be the same.

**Comment by andydotxyz** [comment]
Fixed on develop, will pick to release branch too
