### ISSUE TITLE
Selecting items from a list causes the keyboard to popup on Android. Also blocks back action.

### ISSUE THREAD

**Issue by alexballas** [fyne-io/fyne#4236]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I select the items from a list, this causes the keyboard to popup. Is there a scenario where we would require this? I tested it by compiling the list example here [https://developer.fyne.io/collection/list](https://developer.fyne.io/collection/list)

As a side effect, after you select an item, doing the back action multiple times in an attempt to exit the app, stops working.

### How to reproduce

- select an item from the list in android
- observe the keyboard popping up
- Now try to exit by pressing the back action on your mobile
- First back action will close the keyboard
- Subsequent back actions do nothing

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

var data = []string{"a", "string", "list"}

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Widget")

	list := widget.NewList(
		func() int {
			return len(data)
		},
		func() fyne.CanvasObject {
			return widget.NewLabel("template")
		},
		func(i widget.ListItemID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(data[i])
		})

	myWindow.SetContent(list)
	myWindow.ShowAndRun()
}
```

### Fyne version

v2.5.0

### Go compiler version

1.21.0

### Operating system and version

Android 10

**Comment by andydotxyz** [comment]
Ah, so this is as a result of being focusable I guess.

I don't think the inoperable back button relates to this issue though. Are you sure you compiled using the latest `fyne` tool as well? You need latest both for the interceptable back operation to work (added in v2.4.0).

**Comment by alexballas** [comment]
Hello Andy, yes I'm using the latest fyne cli tool.
```go
$ fyne version
fyne cli version: v2.4.0
```
The interceptable back operation works fine, it's just that when the list is in focus and the keyboard pops, back stops working when sending multiple back actions. You can still make it work by tapping somewhere else inside the app as long as you're not tapping that same list widget.

For my case I just disabled the list focus, so problem solved, but I do find this a bit annoying for the people who actually want their lists to be focusable.

**Comment by andydotxyz** [comment]
The focus issue is fixed. It would be good to know if your back button problem is still an issue after the list focus fix is applied...

**Comment by andydotxyz** [comment]
Sorry it appears the PR never got opened for some reason. up now.

**Comment by andydotxyz** [comment]
Fixed on develop, will merge it back into next release
