### ISSUE TITLE
CanvasObject does not refresh automaticly

### ISSUE THREAD

**Issue by BoseSean** [fyne-io/fyne#424]
I am working on an app referring to the structure of example/life. 
The problem is after `widget.Refresh(a)` is called, the `Raster` does not refresh automatically until I resize the window. 
Is there any documentation on how to properly refresh a CanvasObject?

**Comment by andydotxyz** [comment]
`canvas.Refresh(myRaster)`

If you have built a custom widget then it's render should ensure that items that can change are refreshed within its Refresh() method. The Life demo probably does not do this as it is on a timer to refresh each generation of the game.

**Comment by BoseSean** [comment]
@andydotxyz Thanks for your help, that is the problem.
