### ISSUE TITLE
The fyne dialog component is limited by the size of the main window

### ISSUE THREAD

**Issue by oneAsiaPeople** [fyne-io/fyne#4247]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When the main window does not require a large size, clicking on the file management dialog box will compress it within the scope of the main window

### How to reproduce

show me code

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/45536185/32c89c28-c8e9-4f3f-a62e-c43e7bd321c5)
![image](https://github.com/fyne-io/fyne/assets/45536185/bfb12348-4d61-4d3a-8694-178d953283eb)

### Example code

```

func (app *Config) saveFunc(win fyne.Window) func() {
	return func() {

		saveDialog := dialog.NewFileSave(func(write fyne.URIWriteCloser, err error) {
			if err != nil {
				dialog.ShowError(err, win)
				return
			}
			if write == nil {
				return
			}

			if !strings.HasSuffix(strings.ToLower(write.URI().String()), ".mp4") {
				dialog.ShowInformation("ERROR", "Please name you file with a .md extension", win)
				return
			}

			//write.Write([]byte(cfg.EditWidget.Text))
			app.CurrentFile = write.URI()
			//win.SetTitle(win.Title() + "-" + write.URI().Name())
			app.SaveFileEntry.Text = write.URI().Path()
			app.SaveFileEntry.Refresh()
			defer write.Close()

		}, win)

		//设置默认名称
		saveDialog.SetFileName("untitled.mp4")
		//saveDialog.SetFilter(filter)
		saveDialog.Show()

	}
}


```

### Fyne version

v2.4.0

### Go compiler version

go1.20.5

### Operating system and version

windows 10

**Comment by andydotxyz** [comment]
This is not a bug. In Fyne dialogs appears inside a window to limit the number of windows created.
It is not possible to draw larger than the current window. If you want to make a dialog larger than the window in use then you can open a new one that is larger and show the dialog there instead.

**Comment by oneAsiaPeople** [comment]
Thank you. I have successfully completed this function and created a new Windows window
