### ISSUE TITLE
When I create a new Windows, I hope the original window is not operable

### ISSUE THREAD

**Issue by oneAsiaPeople** [fyne-io/fyne#4249]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When I create a new Windows, I hope the original window is not operable

### Describe the solution you'd like to see.

When I create a new Windows, I hope the original window is not operable

**Comment by andydotxyz** [comment]
I think you are looking for the dialog package. That will allow you to add new content over disabled existing content.

These are "modal overlays" and it is not possible with multiple windows.
