### ISSUE TITLE
Spacer in HBox with hidden item will cause an additional trailing padding

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#4259]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When we have a HBox, with items (say buttons) and a Spacer somewhere. If we hide an item, a non desirable padding is inserted at the end of the HBox.

### How to reproduce

Run the provided code (preferably with -tags debug), and tap the button.
You'll see additional padding added/removed in the the trailing end of the HBox.

### Screenshots

Before hiding 2nd button
![image](https://github.com/fyne-io/fyne/assets/1791230/03c79f61-953c-42b1-b259-16e42ac61a2b)

After Hiding 2nd button
![image](https://github.com/fyne-io/fyne/assets/1791230/fb4304ff-31fe-4fe0-8e6f-681da031b5af)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("")

	b0, b1, b2 := &widget.Button{Icon: theme.ConfirmIcon()}, &widget.Button{Icon: theme.ConfirmIcon()}, &widget.Button{Icon: theme.ConfirmIcon()}

	border := container.NewBorder(
		nil,
		container.NewHBox(
			widget.NewSeparator(),
			widget.NewButton("Toggle", func() {
				if b1.Visible() {
					b1.Hide()
				} else {
					b1.Show()
				}
			}),
		),
		nil, nil,
		container.NewHBox(
			b0,
			layout.NewSpacer(),
			b1, b2,
		),
	)

	w.SetContent(border)
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

2.4.0

### Go compiler version

1.20.7

### Operating system and version

Windows 10

**Comment by dweymouth** [comment]
Fixed on develop
