### ISSUE TITLE
Application stops responding when scrolling a table

### ISSUE THREAD

**Issue by mpldr** [fyne-io/fyne#4263]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When scrolling in a table, the program suddenly became unresponsive. Not sure if it is because of that

### How to reproduce

Could not reliably reproduce. Here is a dump.
[deadlock.txt](https://github.com/fyne-io/fyne/files/12657446/deadlock.txt)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

var dummylog = [][]string{
	{"Time", "Level", "Message"},
	{"2023-09-18T12:03:27.261+02:00", "WARN", "no config loaded"},
	{"2023-09-18T12:03:27.261+02:00", "INFO", "starting uniview"},
	{"2023-09-18T12:03:27.261+02:00", "DEBUG", "connecting"},
	{"2023-09-18T12:03:27.261+02:00", "DEBUG", "starting player…"},
}

func main() {
	myApp := app.NewWithID("sh.moritz.slocker")
	myWindow := myApp.NewWindow("Stop Slacking, Start Slocking!")
	searchbox := widget.NewEntry()
	topbar := container.New(layout.NewHBoxLayout(), widget.NewButton("O", func() {}), widget.NewButton("↓", func() {}), searchbox)

	list := widget.NewTable(
		func() (int, int) {
			return len(dummylog), len(dummylog[0])
		},
		func() fyne.CanvasObject {
			label := widget.NewLabel("")
			label.TextStyle.Monospace = true
			return label
		},
		func(i widget.TableCellID, o fyne.CanvasObject) {
			o.(*widget.Label).SetText(dummylog[i.Row][i.Col])
		})

	content := container.New(layout.NewVBoxLayout(), topbar, list)
	myWindow.SetContent(content)

	myWindow.Show()
	myApp.Run()
}

```

### Fyne version

v2.4.0

### Go compiler version

go version go1.21.1 linux/amd64

### Operating system and version

Archlinux

### Additional Information

Program was running in Xwayland. Not sure, if that matters, but I better mention it.

**Comment by andydotxyz** [comment]
I cannot see the deadlock in the log.

It is very difficult to test with the table squashed into a VBox - can you replicate it if the `list` is the full content of the window?

**Comment by mpldr** [comment]
The deadlock is not a "deadlock"-deadlock because the first goroutine is technically still running, it's just not doing anything to get the other goroutines to run. The application also wouldn't respond to any but the deadly signals or any kind of input. #4210

**Comment by andydotxyz** [comment]
Please test against the develop branch. If the issues were related this could be fixed already.

**Comment by junmaqiang** [comment]
I also encountered a similar situation. When I clicked on the area outside the table component unit, the entire program was stuck, and then it took a while for the first row and column to be selected, which was similar to a stuck state.

**Comment by andydotxyz** [comment]
Are you testing latest develop? It should be fixed already as noted above.

**Comment by mpldr** [comment]
I did and could not reproduce. So I guess it's either fixed or rare enough :D

**Comment by nnsay** [comment]
I meet the problem when I paste big size string into `entry` widget.
<img width="1219" alt="image" src="https://github.com/fyne-io/fyne/assets/14331919/292f1e28-f645-42ac-8e5f-842da9c2d9f9">

**Comment by andydotxyz** [comment]
Please don't add info about pasting info into a Entry on a closed issue about Tables.
