### ISSUE TITLE
Arch linux didnt run the app

### ISSUE THREAD

**Issue by martirosharutyunyan** [fyne-io/fyne#4267]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

go build github.com/go-gl/gl/v3.2-core/gl:
# pkg-config --cflags  -- gl gl
pkg-config: exec: "pkg-config": executable file not found in $PATH

in arch linux installation add the pkg-config to dependecies

### How to reproduce

go build github.com/go-gl/gl/v3.2-core/gl:
# pkg-config --cflags  -- gl gl
pkg-config: exec: "pkg-config": executable file not found in $PATH

### Example code

package desktop

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func App() {
	converterApp := app.New()
	window := converterApp.NewWindow("Converter")
	window.SetContent(widget.NewLabel("hello arxiv"))
	window.ShowAndRun()
}

### Fyne version

v2.4.0

### Go compiler version

go1.21.0

### Operating system and version

Manjaro

**Comment by andydotxyz** [comment]
You don't have some developer tools installed. Please follow the getting started doc https://developer.fyne.io/started/

**Comment by BarunW** [comment]
Have you test using fyne_demo before writing any code

**Comment by JordanGoulder** [comment]
if you are missing `pkg-config`, run the following command to install it:

````
sudo pacman -S pkgconf
````

I run Manjaro and I have this package installed as well as the others listed on the getting started page and I have no issues.
