### ISSUE TITLE
Panic in demo

### ISSUE THREAD

**Issue by verdverm** [fyne-io/fyne#4288]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The demo crashed while I was looking around

```
panic: InvalidValue: Invalid scancode 128

goroutine 51 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x4487e0004477c000?})
        /home/tony/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:174 +0x1f4
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/tony/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:185
github.com/go-gl/glfw/v3.3/glfw.(*Window).SwapBuffers(0xc0000c27e0?)
        /home/tony/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/context.go:42 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/loop.go:205 +0xf8
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0003d3d50?, 0xc006a9de30)
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/window.go:922 +0x43
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0x4?, 0x1?)
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/loop.go:188 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0xc006a9df90?)
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/loop.go:95 +0x1a5
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/loop.go:244 +0x1d5
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread in goroutine 1
        /home/tony/go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/glfw/loop.go:220 +0xbb
```

### How to reproduce

...

### Example code

...

### Fyne version

2.4.0

### Go compiler version

1.21.1

### Operating system and version

debian bookworm

**Comment by andydotxyz** [comment]
> The demo crashed while I was looking around

Please provide more information. What happened immediately before the panic?

**Comment by verdverm** [comment]
I think mouse click

**Comment by andydotxyz** [comment]
Is there any more information you can provide? It's pretty difficult to figure out why the window implementation would have been nil...

**Comment by verdverm** [comment]
I don't have any additional insights.

1. I ran the demo
2. I was navigating around
3. at some (inconsistent) point, it crashed. It happened more than once, but I never found a reliable way to reproduce.

I was using the mouse almost exclusively while looking around.

Run from ChromeOS in the Terminal App

**Comment by andydotxyz** [comment]
Given the number of fixes in the previous 2 releases and lack of steps to reproduce reliably I think this should be closed.
If you can replicate it in v2.4.2 with the same stack trace please re-open this issue.
