### ISSUE TITLE
Set size of widgets

### ISSUE THREAD

**Issue by dseichter** [fyne-io/fyne#429]
Hello,
I want to define a fixed size to an EntryWidget

```
editValue := widget.NewEntry() 
editValue.SetPlaceHolder("Your first value")
editValue.Size(what to do here?)
```

But it does not work. I searched for an example, how I am able to set the width of a entry, but using MinSize does not have any effect.
The documentation gives me the information, to use fyne.Size(width,height), but Size does not accept it. Can you give me the the decisive clue? or is it currently not supported for widgets like Entry?

thank you very much in advance!

**Comment by andydotxyz** [comment]
Normally widgets exist within a layout - if that is the case then the layout is setting the size of the entry, not the entry itself. A widget's MinSize() determines the smallest it can be set to. A layout controls the size of widgets by using their Resize(size) method.

It's not clear what you want to achieve overall as an Entry will expand to fill the space available. Perhaps the parent container is too small?

**Comment by dseichter** [comment]
Hello, thanks for your answer. Yes, I think, the parent container was too small. Now it looks better than before :) I have to adjust some theme settings, to have a nice looking app like I want. 

I am new to fyne, but currently the best solution for go gui :+1: 

With the resize method I am able to control my layout for longer entries. Working with Forms and a lot of Entry and Check widgets.
