### ISSUE TITLE
Add popUp to the Entry widget 

### ISSUE THREAD

**Issue by tayadelmar** [fyne-io/fyne#430]
Add popUp to the Entry widget on a right mouse click, which supports the following options:
 - **Copy/Paste/Cut**

The `Paste` option already merged to the develop branch, but it needs some improvements:

- [x] Replace selected text.   
_Paste a text from the clipboard with replacement of selected text._
 
- [x] Hide popUp on Entry.Hide() method.

- [x] Remain the focus on Entry when popUp appears.
_Some thoughts about it from @andydotxyz : "glfw is loosing the focus when the overlay is clicked", "the issue might be that overlays are a separate thing, and so potentially the driver is not realizing it should not remove focus on tap"_ 

- [x] Hide popUp on typing, except navigation and control keys.

**Comment by andydotxyz** [comment]
I'm pretty sure that all of these elements are now addressed on our develop branch ready for release.
If possible could you verify for us ? :)

**Comment by tayadelmar** [comment]
yes! It works fine to me!
