### ISSUE TITLE
WASM Copy / Paste

### ISSUE THREAD

**Issue by rmasci** [fyne-io/fyne#4301]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Tried running several fyne apps using wasm. The apps all run, you see the window in the browser, but copy / paste is not available nor can you open files, save files etc. 

### How to reproduce

1. Simple App, Code pasted in 'Example Code' section
2. Run fyne serve --port 8080 --target wasm
3. In browser, try to copy / paste. I can't select any text I type, I can't copy it to the clipboard and if I have text on the clipboard I can't paste it in. 
4. I've tried more complex applications, none of them seem to work. Tried in Windows / Mac, browsers: Edge, Firefox, Safari

### Example code

``` go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.SetContent(widget.NewMultiLineEntry())
	w.Resize(fyne.Size{Height: 640, Width: 480})
	w.ShowAndRun()
}
```

### Fyne version

fyne.io/fyne/v2 v2.4.0

### Go compiler version

go version go1.21.1

### Operating system and version

Windows 11, Mac Ventura M2

### Additional Information

Every app I try, including apps found on https://apps.fyne.io/ seem to work with copy / paste. I also noticed trying to open a file / save a file doesn't work either. All this works on a desktop app without a problem, just not in wasm.

**Comment by Bluebugs** [comment]
Indeed, this is currently not implemented in the wasm and the js backend. The change actually have to be done in the glfw-js module at https://github.com/fyne-io/glfw-js/blob/master/browser.go#L925 and https://github.com/fyne-io/glfw-js/blob/master/browser_wasm.go#L941 . I currently do not have the time to work on this, but it should be a possible task for someone beginning to look at fyne code base and its dependencies.

**Comment by sujalcodes3** [comment]
I would love to contribute to this issue, but I am a beginner. Can you please suggest me where to start?

**Comment by Bluebugs** [comment]
So gopherjs ans go wasm have a different api, that's why there is two place to implement it. When you look at the content of the file, you will see how the access to the js api is done. From there, the idea is to look up how things are done in pure Javascript and do that same logic, but in go (once for gopherjs and once for wasm).

**Comment by gcottom** [comment]
I've made the changes here, [Pull Request](https://github.com/fyne-io/glfw-js/pull/13)
The dependency is with glfw-js. My changes address right click copy and paste for both gopherjs and WASM.

**Comment by andydotxyz** [comment]
Thanks so much for this, now landed on develop. It should be possible to back-port it to v2.4.4
