### ISSUE TITLE
A lot of "cannot find package"

### ISSUE THREAD

**Issue by BinaryBytecode** [fyne-io/fyne#4304]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I get this error when I execute _go run main.go_:

`/home/myhome/go/src/fyne.io/fyne/v2/internal/svg/svg.go:16:2: cannot find package "github.com/srwiley/oksvg" in any of:
	/usr/lib/go/src/github.com/srwiley/oksvg (from $GOROOT)
	/home/myhome/go/src/github.com/srwiley/oksvg (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/svg/svg.go:17:2: cannot find package "github.com/srwiley/rasterx" in any of:
	/usr/lib/go/src/github.com/srwiley/rasterx (from $GOROOT)
	/home/myhome/go/src/github.com/srwiley/rasterx (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/storage/repository/parse.go:9:2: cannot find package "github.com/fredbi/uri" in any of:
	/usr/lib/go/src/github.com/fredbi/uri (from $GOROOT)
	/home/myhome/go/src/github.com/fredbi/uri (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/font.go:11:2: cannot find package "github.com/go-text/render" in any of:
	/usr/lib/go/src/github.com/go-text/render (from $GOROOT)
	/home/myhome/go/src/github.com/go-text/render (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/font.go:12:2: cannot find package "github.com/go-text/typesetting/di" in any of:
	/usr/lib/go/src/github.com/go-text/typesetting/di (from $GOROOT)
	/home/myhome/go/src/github.com/go-text/typesetting/di (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/font.go:13:2: cannot find package "github.com/go-text/typesetting/font" in any of:
	/usr/lib/go/src/github.com/go-text/typesetting/font (from $GOROOT)
	/home/myhome/go/src/github.com/go-text/typesetting/font (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/font.go:14:2: cannot find package "github.com/go-text/typesetting/shaping" in any of:
	/usr/lib/go/src/github.com/go-text/typesetting/shaping (from $GOROOT)
	/home/myhome/go/src/github.com/go-text/typesetting/shaping (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/image.go:8:2: cannot find package "golang.org/x/image/draw" in any of:
	/usr/lib/go/src/golang.org/x/image/draw (from $GOROOT)
	/home/myhome/go/src/golang.org/x/image/draw (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/draw.go:10:2: cannot find package "golang.org/x/image/math/fixed" in any of:
	/usr/lib/go/src/golang.org/x/image/math/fixed (from $GOROOT)
	/home/myhome/go/src/golang.org/x/image/math/fixed (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/widget/markdown.go:8:2: cannot find package "github.com/yuin/goldmark" in any of:
	/usr/lib/go/src/github.com/yuin/goldmark (from $GOROOT)
	/home/myhome/go/src/github.com/yuin/goldmark (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/widget/markdown.go:9:2: cannot find package "github.com/yuin/goldmark/ast" in any of:
	/usr/lib/go/src/github.com/yuin/goldmark/ast (from $GOROOT)
	/home/myhome/go/src/github.com/yuin/goldmark/ast (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/widget/markdown.go:10:2: cannot find package "github.com/yuin/goldmark/renderer" in any of:
	/usr/lib/go/src/github.com/yuin/goldmark/renderer (from $GOROOT)
	/home/myhome/go/src/github.com/yuin/goldmark/renderer (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/painter/gl/gl_core.go:9:2: cannot find package "github.com/go-gl/gl/v3.2-core/gl" in any of:
	/usr/lib/go/src/github.com/go-gl/gl/v3.2-core/gl (from $GOROOT)
	/home/myhome/go/src/github.com/go-gl/gl/v3.2-core/gl (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/driver/glfw/driver_desktop.go:18:2: cannot find package "fyne.io/systray" in any of:
	/usr/lib/go/src/fyne.io/systray (from $GOROOT)
	/home/myhome/go/src/fyne.io/systray (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/driver/glfw/driver.go:12:2: cannot find package "github.com/fyne-io/image/ico" in any of:
	/usr/lib/go/src/github.com/fyne-io/image/ico (from $GOROOT)
	/home/myhome/go/src/github.com/fyne-io/image/ico (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/internal/driver/glfw/clipboard.go:12:2: cannot find package "github.com/go-gl/glfw/v3.3/glfw" in any of:
	/usr/lib/go/src/github.com/go-gl/glfw/v3.3/glfw (from $GOROOT)
	/home/myhome/go/src/github.com/go-gl/glfw/v3.3/glfw (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/app/settings_desktop.go:11:2: cannot find package "github.com/fsnotify/fsnotify" in any of:
	/usr/lib/go/src/github.com/fsnotify/fsnotify (from $GOROOT)
	/home/myhome/go/src/github.com/fsnotify/fsnotify (from $GOPATH)
/home/myhome/go/src/fyne.io/fyne/v2/app/app_xdg.go:17:2: cannot find package "github.com/godbus/dbus/v5" in any of:
	/usr/lib/go/src/github.com/godbus/dbus/v5 (from $GOROOT)
	/home/myhome/go/src/github.com/godbus/dbus/v5 (from $GOPATH)`

### How to reproduce

1. create a package
2. follow fyne install instructions
3. add a main.go file
4. add the example code
5. run _go run main.go_

### Example code

main.go
```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))
}
```

### Fyne version

2.4.0

### Go compiler version

1.21.1

### Operating system and version

Arch Linux x86_64  kernel: 6.5.5

**Comment by andydotxyz** [comment]
Run "go mod tidy"

**Comment by BinaryBytecode** [comment]
I already did that

**Comment by BinaryBytecode** [comment]
> Run "go mod tidy"

I already did that
