### ISSUE TITLE
Incomplete display of Chinese on select

### ISSUE THREAD

**Issue by 1506353029** [fyne-io/fyne#4306]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Incomplete display of Chinese on select
i tried using big select,but still

### How to reproduce

just add Chinese options to a widget.select

### Screenshots

![QQ截图20231010190500](https://github.com/fyne-io/fyne/assets/38553546/0de4e20e-d714-4499-8c78-6c5db8dfa18d)
![QQ截图20231010190517](https://github.com/fyne-io/fyne/assets/38553546/fc2118f8-a9f8-410c-bfa2-3ad517482e59)

### Example code

very easy

### Fyne version

2.4.0

### Go compiler version

1.21.0

### Operating system and version

win10

**Comment by qiwentaidi** [comment]
This issue has been fixed in fyne 2.4.1
