### ISSUE TITLE
Performance regression when scrolling inside the file dialog

### ISSUE THREAD

**Issue by alexballas** [fyne-io/fyne#4307]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

File dialog file scrolling is much slower in version 2.4.x compared to the previous ones. Check video

### How to reproduce

check video

### Screenshots

https://github.com/fyne-io/fyne/assets/11015965/73285757-f3fe-4848-a871-3bf5567d8a42

### Example code

No code required

### Fyne version

v2.4.0, v2.4.1

### Go compiler version

1.20.2

### Operating system and version

Ubuntu 18.04

**Comment by JordanGoulder** [comment]
Which version is the previous version you are comparing it to?

**Comment by alexballas** [comment]
Hello @JordanGoulder. Apologies for missing this. The old one is on version v2.3.2

**Comment by andydotxyz** [comment]
> Hello @andydotxyz, just wanted to confirm. Is this still planned to be looked at as part of the 2.4.x fixes or are you now aiming to get something in the upcoming 2.5.x releases?

Apologies I missed this message. We are trying to prioritise it for the coming bug fix release.

**Comment by andydotxyz** [comment]
Fixed on develop and will be in v2.5.3

**Comment by alexballas** [comment]
Hello @andydotxyz,
I just tested the latest develop version and the performance regression is still there. I can also record a video to demonstrate, when the time permits.

**Comment by andydotxyz** [comment]
That's strange. Cpu usage dropped by 80% approx, and it is noticeably better on my machines.
Maybe there is an additional issue?
Do please check it's definitely latest.
