### ISSUE TITLE
SetFullScreen on startup

### ISSUE THREAD

**Issue by codenoid** [fyne-io/fyne#431]

**Comment by andydotxyz** [comment]
I don’t understand what this issue is... you can set a window to FullScreen before it’s shown?

**Comment by codenoid** [comment]
yup, i can't SetFullScreen before `ShowAndRun`

**Comment by andydotxyz** [comment]
Thanks, this must have slipped into the last release, will hotfix ASAP

**Comment by andydotxyz** [comment]
Fixed in 9f17bc0
