### ISSUE TITLE
PasswordEntry initial text is not obscured

### ISSUE THREAD

**Issue by pingProMax** [fyne-io/fyne#4312]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In the password type input box, initialization will directly display the password

### How to reproduce

Run instance code

### Screenshots

![动画](https://github.com/fyne-io/fyne/assets/44503794/06f98b50-d559-4c0e-a971-4d67f526fe36)

### Example code

```golang
package frame

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func LoginHandle(app fyne.App) {
	w := app.NewWindow("登录")
	w.Canvas()

	usernameEntry := &widget.Entry{PlaceHolder: "请输入用户名", Text: "admin"}
	passwdEntry := &widget.Entry{PlaceHolder: "请输入密码", Password: true, Text: "admin"}
	loginBut := &widget.Button{
		Text: "登录",
		Icon: theme.ConfirmIcon(),
		OnTapped: func() {
			//登录
			if usernameEntry.Text == "admin" && passwdEntry.Text == "admin" {
				w.Hide()
				UserHandle(app)
			} else {
				dialog.ShowInformation("提示", "密码错误！", w)
			}

		},
	}
	froms := container.NewVBox(usernameEntry, passwdEntry, loginBut)

	green := color.NRGBA{R: 0, G: 180, B: 0, A: 255}
	canvasRectangle := canvas.NewRectangle(green)
	canvasRectangle.SetMinSize(fyne.NewSize(300, 300))

	w.Resize(fyne.NewSize(300, 300))
	w.SetContent(
		container.NewCenter(
			container.NewBorder(nil, nil, nil, nil, canvasRectangle, container.NewVBox(
				layout.NewSpacer(),
				froms,
				layout.NewSpacer(),
			)),
		),
	)

	w.Show()
}
```

### Fyne version

v2.4.1

### Go compiler version

1.21.1

### Operating system and version

Windows 11

**Comment by schnoddelbotz** [comment]
I ran into the same reproducible issue today - not on a login form but within a config widget, using:
```
ADPasswordInput := widget.NewPasswordEntry()
ADPasswordInput.Text = a.config.ADpass // to "show" the configured password (from keychain)
```

I found as work-around, calling `Refresh()` on the input helped to obfuscate the text:
```
ADPasswordInput.Refresh()
```

Hope this helps.

**Comment by pingProMax** [comment]
> 我今天遇到了同样的可重现问题 - 不是在登录表单上，而是在配置小部件中，使用：
> 
> ```
> ADPasswordInput := widget.NewPasswordEntry()
> ADPasswordInput.Text = a.config.ADpass // to "show" the configured password (from keychain)
> ```
> 
> 我发现作为解决方法，调用`Refresh()`输入有助于混淆文本：
> 
> ```
> ADPasswordInput.Refresh()
> ```
> 
> 希望这可以帮助。

Yes, thank you

**Comment by pingProMax** [comment]
> I ran into the same reproducible issue today - not on a login form but within a config widget, using:
> 
> ```
> ADPasswordInput := widget.NewPasswordEntry()
> ADPasswordInput.Text = a.config.ADpass // to "show" the configured password (from keychain)
> ```
> 
> I found as work-around, calling `Refresh()` on the input helped to obfuscate the text:
> 
> ```
> ADPasswordInput.Refresh()
> ```
> 
> Hope this helps.

Yes, thank you

**Comment by andydotxyz** [comment]
Landed on develop and release branch, will be in v.2.4.2
