### ISSUE TITLE
Triple clicking in an Entry widget should select all text

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4328]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

This is fairly standard behavior across OSes and UI toolkits. We should aim to support it.

### Is it possible to construct a solution with the existing API?

Yes, by extending Entry to override Tapped and implementing the behavior yourself

### Describe the solution you'd like to see.

Triple clicking in the entry should select all text in a single line entry, or all of the current line in a multi-line entry

**Comment by andydotxyz** [comment]
Yeah this is good. I'm not sure if we need to do this with actual triple click implementation or through baking it in to just Entry?

**Comment by dweymouth** [comment]
I think baking it into entry is probably fine. 99% of widgets won't need a triple click interaction

**Comment by dweymouth** [comment]
Added on develop
