### ISSUE TITLE
Add more shortcuts to fyne.Shortcut

### ISSUE THREAD

**Issue by spatocode** [fyne-io/fyne#434]
Currently, fyne supports **cut**, **copy** and **paste** shortcuts. That's pretty fine.
The Shortcut interface needs improvements and there's a need for more shortcuts like
1. Undo
2. Redo
3. Select all

**Comment by andydotxyz** [comment]
Undo and Redo require more than just the shortcut but also the manager which is more work - I will open another ticket. Select All could be done quickly :)

**Comment by andydotxyz** [comment]
As Undo and Redo have a new issue and Select All is now in I will close this issue
