### ISSUE TITLE
Changing theme while application is running doesn't change some parameters on some widgets

### ISSUE THREAD

**Issue by pztrn** [fyne-io/fyne#4344]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When changing theme from dark to light (or vice versa) some widgets like buttons doesn't change it's theme. E.g buttons doesn't change background until mouseover, never changes font color.

### How to reproduce

1. Create a window with tabs and buttons placed in tabs. Open that app.
2. Open fyne_settings, change theme from dark to light (or vise versa).
3. Switch back to running application, change active tab. Some buttons doesn't change it's background and almost no buttons changed font color.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/869402/4ef557bb-7e9d-48bb-9702-9629c710dbfb)

### Example code

I'll add code later if neccessary. Just create a window, put tabs in it, but some buttons in tabs containers.

### Fyne version

2.3.5, 2.4.1

### Go compiler version

1.21.3

### Operating system and version

Arch Linux latest @ 20231026

**Comment by andydotxyz** [comment]
You will need to provide code to replicate this. As you can see in fyne_demo and in our tests it does normally work.

**Comment by qiwentaidi** [comment]
I think you can try this function
```go`
// https://github.com/fyne-io/fyne/issues/2996
func Refresh(tableapps ...*container.AppTabs) {
	for _, c := range tableapps {
		c.OnSelected = func(t *container.TabItem) {
			fyne.CurrentApp().Settings().SetTheme(fyne.CurrentApp().Settings().Theme())
		}
	}
}
```

**Comment by sdassow** [comment]
Experiencing this effect as well, and didn't get around to isolate the code for testing yet. So for now just a comment.

**Comment by sdassow** [comment]
Just isolated the code in question, and it does involve AppTabs like others also mentioned.
To reproduce, run it, click button to change theme in one tab, then switch to other tab and see the issue:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Theme Test")

	foo := container.NewVBox(
		widget.NewButton("dark", func() {
			a.Settings().SetTheme(theme.DarkTheme())
		}),
		widget.NewButton("light", func() {
			a.Settings().SetTheme(theme.LightTheme())
		}),
	)

	bar := container.NewVBox(
		widget.NewButton("dark", func() {
			a.Settings().SetTheme(theme.DarkTheme())
		}),
		widget.NewButton("light", func() {
			a.Settings().SetTheme(theme.LightTheme())
		}),
	)

	tabs := container.NewAppTabs(
		container.NewTabItem("Foo", foo),
		container.NewTabItem("Bar", bar),
	)

	w.SetContent(tabs)
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Fixed on develop :)
