### ISSUE TITLE
The color selection of cells by condition is lost when scrolling rows in the table for v2.4.1

### ISSUE THREAD

**Issue by Dmitriy147** [fyne-io/fyne#4351]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When creating a table in version 2.4.1, when using a large number of rows with scrolling, the highlighting of cells by condition is lost. Artifacts also appear in the font of the strings.
The same code in version 2.3.5 works stably.

### How to reproduce

1. Create a project with the code below
2. Use v.2.3.5
3. Try to run and scroll the rows
4. Change v.2.3.5 to v.2.4.1
5. Run the project and try to scroll thw rows - the haotic color of cell will appeare.

### Screenshots

For v.2.4.1:
![Безымянный](https://github.com/fyne-io/fyne/assets/78656465/c3bbde60-3579-4a33-8a67-ca8af5fbebfe)

For v.2.3.5:
![Безымянный](https://github.com/fyne-io/fyne/assets/78656465/a6430087-9e59-4d60-a267-8cf4295f387e)

### Example code

```go
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Table Widget")
	myWindow.Resize(fyne.NewSize(500, 300))
	myWindow.CenterOnScreen()

	table := widget.NewTable(nil, nil, nil)
	table.Length = func() (int, int) {
		return 20, 3
	}
	table.CreateCell = func() fyne.CanvasObject {
		return canvas.NewText("p", nil)
	}
	table.UpdateCell = func(i widget.TableCellID, o fyne.CanvasObject) {
		o.(*canvas.Text).Text = fmt.Sprintf("%v %v", i.Row, i.Col)
		o.(*canvas.Text).Alignment = fyne.TextAlign(fyne.TextAlignCenter)
		o.(*canvas.Text).Color = nil
		if i.Row == 2 {
			o.(*canvas.Text).Color = color.NRGBA{R: 222, G: 222, B: 22, A: 255}
		}
	}

	table.SetColumnWidth(0, 100)
	table.SetColumnWidth(1, 100)
	table.SetColumnWidth(2, 300)

	myWindow.SetContent(table)
	myWindow.ShowAndRun()
}
```

### Fyne version

2.3.5 and 2.4.1

### Go compiler version

1.21.3

### Operating system and version

windows 10 x64 Pro

**Comment by Nyx2022** [comment]
i have the similar problem https://github.com/fyne-io/fyne/issues/4352

**Comment by andydotxyz** [comment]
After you manually change internal fields of a canvas object you must call `Refresh()` or it may not update immediately.

**Comment by Dmitriy147** [comment]
Great! Solved!
