### ISSUE TITLE
Fyne 2.4.1 Table with ToolTipLabel display confusion

### ISSUE THREAD

**Issue by Nyx2022** [fyne-io/fyne#4352]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have some rows in table, and every cell is a TapAndTooltipLabel,when i scroll up and down somtimes, it will display confused like the gif
![动画](https://github.com/fyne-io/fyne/assets/51039208/312885c1-0b0c-4846-953c-217f2b085cac)

### How to reproduce

just use fyne.table normally with TapAndTooltipLabel

### Example code

taskDbs = widget.NewTableWithHeaders(func() (int, int) {
		l := 0
		if Data != nil && Data.Dbs!= nil {
			l = len(*Data.Dbs)
		}

		return l,
			len(TableHeader_db[0])
	}, nil, nil)

	taskDbs.CreateCell = func() fyne.CanvasObject {
		return TapAndToolTipLabel.NewTapAndTooltipLabel("label", nil, "", func(s string, event *fyne.PointEvent) {}, func(s string, event *fyne.PointEvent) {}, func(s string, event *desktop.MouseEvent) {}, nil)
	}
	taskDbs.UpdateCell = func(id widget.TableCellID, template fyne.CanvasObject) {
		currItem, ok := Results.Get(strconv.Itoa(id.Row))
		if ok {
			tl := template.(*TapAndToolTipLabel.TapAndTooltipLabel)
			tltxt := ""
			switch id.Col {
			case 0:
				tltxt = currItem.DbName
				break
			case 1:
				if currItem.Tables != nil {
					tltxt = strconv.Itoa(len(*currItem.Tables))
				} else {
					tltxt = "0"
				}
				break
			case 2:
				tltxt = currItem.ReMark
				break
			}

			tl.SetText(tltxt)
		}

	}
	taskDbs.CreateHeader = func() fyne.CanvasObject {
		return widget.NewLabelWithStyle("lebel", fyne.TextAlignCenter, fyne.TextStyle{Bold: true})
	}
	taskDbs.UpdateHeader = func(id widget.TableCellID, template fyne.CanvasObject) {
		if id.Row == -1 {
			template.(*widget.Label).SetText(TableHeader_db[0][id.Col])
		} else {
			template.(*widget.Label).SetText(strconv.Itoa(id.Row + 1))
		}
	}
	taskDbs.SetColumnWidth(0, 210)
	taskDbs.SetColumnWidth(1, 100)
	taskDbs.SetColumnWidth(2, 30)
	taskDbs.SetColumnWidth(3, 100)
	

### Fyne version

2.4.1

### Go compiler version

1.21.1

### Operating system and version

windows 11

**Comment by andydotxyz** [comment]
Surely this is a bug against `TapAndTooltip` code and not the fyne `Table` collection?

**Comment by Nyx2022** [comment]
> Surely this is a bug against `TapAndTooltip` code and not the fyne `Table` collection?这肯定是针对 `TapAndTooltip` 代码的错误，而不是 fyne `Table` 集合？

how can i solve it?

**Comment by andydotxyz** [comment]
We have no idea what to recommend as your code was not included.
Remember this is a bug tracker for the fyne toolkit and not projects that are built using these APIs.
