### ISSUE TITLE
We need textbrowser similar to qt

### ISSUE THREAD

**Issue by pennkao** [fyne-io/fyne#4354]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Unable to implement textbrowser function using entry

### Is it possible to construct a solution with the existing API?

Unable to implement textbrowser function using entry

### Describe the solution you'd like to see.

Unable to implement textbrowser function using entry

**Comment by dweymouth** [comment]
Could `widget.RichText` be what you are looking for? It supports styled text and hyperlink segments

**Comment by pennkao** [comment]
I want to a chatroom that supports selecting text and copying, but cannot be edited

**Comment by dweymouth** [comment]
So maybe if widget.RichText could be made selectable, that would work? (BTW "textbrowser" is not a clear feature request. Something like "add selection support to RichText" makes clear what the desired feature is)

**Comment by pennkao** [comment]
Richtext has no borders. I am currently using the readonly implementation of Entry to meet my needs

**Comment by pennkao** [comment]
I have decided to give up fyne and use Python qt6I have decided to give up fyne and use Python qt6. fyne cannot achieve complex functions

**Comment by Jacalz** [comment]
> fyne cannot achieve complex functions

Now that's a statement I don't agree with. It is an open source project. If you wish to add missing functionality and someone has to implement it for it to exist. If no one does so, we'd get nowhere

**Comment by andydotxyz** [comment]
It's a fairly confusing statement really. People are using Fyne in production for some quite complex systems. Plus there is a full desktop environment and app builder created with this toolkit.
But we cannot satisfy everyone. If folk prefer Qt then that is not a problem.
