### ISSUE TITLE
FileDialog: make setView method public

### ISSUE THREAD

**Issue by akares** [fyne-io/fyne#4356]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Currently `gridView` is hard-coded value for `viewLayout` of the File Dialog and there's no way to change it via public API.

We work with many files named almost identically and grid view cuts all the unique parts of the names. So the list view is more preferable in this case and it's annoying to change the view every time by clicking the button.

### Describe the solution you'd like to see.

Please, make `setView` method and `viewLayout` type public.

**Comment by dweymouth** [comment]
I believe there is an upcoming change to save the user preference in the global fyne settings, so once you switch to list view it will stay there. Not sure if this would resolve your feature request or if you still have a rationale for making it a public API

**Comment by akares** [comment]
> I believe there is an upcoming change to save the user preference in the global fyne settings, so once you switch to list view it will stay there. Not sure if this would resolve your feature request or if you still have a rationale for making it a public API

Preferences persisting for sure will resolve the issue. Did not know it's planned. Thank you!

**Comment by andydotxyz** [comment]
It's landed on develop branch already :)
