### ISSUE TITLE
Add Undo/Redo support for widget.Entry

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#436]
Required for #434

**Comment by andydotxyz** [comment]
As this ticket add to the entry popup

**Comment by AndrewWPhillips** [comment]
I think this should not just be changes to the text but also changes to the selection, in which case it may even be required for read-only entry widgets.

**Comment by andydotxyz** [comment]
Undoing selection sounds a little uncommon? If I make a change then copy 3 different bits of text then undo has to be executed 4 times to undo the actual change I intended...

**Comment by xypwn** [comment]
@andydotxyz This can be closed now, right?

**Comment by andydotxyz** [comment]
Ah yes thanks, I missed that
