### ISSUE TITLE
Slider should not hold onto focus after it's interacted with by the mouse

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4369]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If you tap or drag a slider, since 2.4 when focus was added, the slider holds on to focus afterward. I don't think this is how it should be given that pretty much every widget other than Entry only grabs focus when focused by the keyboard.

### How to reproduce

Run fyne demo and tap a slider

### Example code

Fyne demo

### Fyne version

2.4.1

### Go compiler version

go1.21.1

### Operating system and version

macOS Ventura M2

**Comment by andydotxyz** [comment]
> I don't think this is how it should be given that pretty much every widget other than Entry only grabs focus when focused by the keyboard.

As discussed in the PR I think this is a bigger question. Shouldn't interacting with an input widget give it focus?
Whatever we do it should be specific, and I don't think Slider is the only one impacted.

**Comment by dweymouth** [comment]
I think we decided the other direction - that all input widgets keep focus by default, so I am closing this. It is of course possible for app developers to achieve the other behavior by extending the widgets and overriding Tapped, Dragged, etc to call FocusLost
