### ISSUE TITLE
Incorrect row header width in widget.Table

### ISSUE THREAD

**Issue by vinser** [fyne-io/fyne#4370]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Neither  SetColumnWidth nor template in CreateHeader do not set row header width up. 
See the first fixed column on screenshot below

### How to reproduce

Run the code below

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/14954512/1caa4879-bc61-4a5d-8c7f-1cd5fd5e6769)

### Example code

```go
import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Table with Borders")

	t := widget.NewTableWithHeaders(
		func() (int, int) { return 5, 5 },
		func() fyne.CanvasObject {
			return widget.NewLabel("Cell 000, 000")
		},
		func(id widget.TableCellID, o fyne.CanvasObject) {
			label := o.(*widget.Label)
			label.SetText(fmt.Sprintf("Cell %d, %d", id.Row, id.Col))
		})

	t.SetColumnWidth(-1, 100)

	t.CreateHeader = func() fyne.CanvasObject {
		return widget.NewLabel("Row 000")
	}

	t.UpdateHeader = func(id widget.TableCellID, o fyne.CanvasObject) {
		l := o.(*widget.Label)
		if id.Col == -1 {
			l.SetText(fmt.Sprintf("Row %d", id.Row))
		} else {
			l.SetText(fmt.Sprintf("Column %d", id.Col))
		}
	}

	content := container.NewBorder(nil, nil, nil, nil, t)

	w.Resize(fyne.NewSize(400, 300))
	w.CenterOnScreen()
	w.SetContent(content)
	w.ShowAndRun()
}
```

### Fyne version

2.4.1

### Go compiler version

1.21.3

### Operating system and version

Ubuntu 22.04 arm64, Windows 10 amd64

**Comment by Ju-B** [comment]
i encounter the same issue.

The code to handle header sizing do not use t.columnWidths nor t.rowHeights.
The size is always the one from the template's Minsize cached in t.headerSize.

Exposing t.headerSize or have a setter could help set the row header's width and column header's height
Or handle -1 case in SetColumnWidth and SetRowHeight to affect t.headerSize in stead of changing the maps

**Comment by andydotxyz** [comment]
Understood the use-case and now the patch is landed too. Marking for next feature release
