### ISSUE TITLE
Irregular layout when using entry widget

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#438]
When using Fyne containerWithLayout with an Entry, there's an irregular vertical spacing.

```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	fyneApp := app.New()
	window := fyneApp.NewWindow("Test")
	password := widget.NewPasswordEntry()

	text := widget.NewLabel("Hello")

	window.SetContent(
		widget.NewVBox(
			fyne.NewContainerWithLayout(layout.NewFixedGridLayout(fyne.NewSize(93, 127)), password),
			text))
	window.ShowAndRun()
}

```
This doesn't occur on Fyne v1.1.0

**Comment by andydotxyz** [comment]
Can you please confirm what the irregularity is? I ran the code but can't see an obvious issue...

**Comment by metaclips** [comment]
The vertical spacing between the password entry and hello label shouldn't be, this doesn't occur in v1.1.0

**Comment by metaclips** [comment]
Can this also be implemented in develop branch? seems the issue occurs there also.

**Comment by andydotxyz** [comment]
Master is now merged back into develop, apologies
