### ISSUE TITLE
Systray not created

### ISSUE THREAD

**Issue by theHilikus** [fyne-io/fyne#4381]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Using the sample systray code from [here](https://developer.fyne.io/explore/systray) I get the following error in the console and there is no systray icon or entry. The app window opens normally and I see the dummy label but no systray

> ❯ go run .
> 2023/11/12 00:52:40 Failed to read icon format image: unknown format

If I add a resource pointing to a png icon, the error is gone but the systray still doesn't appear

One thing I noticed even when the error is there is that if I close the app window, the process doesn't terminate. This is the case even though `w.SetCloseIntercept` is commented out. The call to `SetSystemTrayMenu` is doing something that doesn't let the process terminate. If I comment that out, when the window closes, the process terminates

### How to reproduce

1. Create an app with the code provided
2. `go run .`

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/1633408/a6db4887-9542-4316-8d41-9cea18b28d5c)
No systray icon

### Example code

```go
func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		res, err := fyne.LoadResourceFromPath("icon.png")
		if err != nil {
			fmt.Println("Error loading resource: " + err.Error())
			return
		}
		desk.SetSystemTrayIcon(res)
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	// w.SetCloseIntercept(func() {
	// 	w.Hide()
	// })
	w.ShowAndRun()
}
```

### Fyne version

2.4.1

### Go compiler version

go1.21.3 linux/amd64

### Operating system and version

Ubuntu 22.04.3 LTS

**Comment by andydotxyz** [comment]
From the screenshot it looks like it is working, but with no icon. Default icons are applied when you package an app ("fyne package" for example).
Using "go build" there is no icon metadata so you will have to call either "App.SetIcon" or "DesktopApp.SetSystemTrayIcon" for it to know what to draw.
These should all be png files.

**Comment by andydotxyz** [comment]
> If I add a resource pointing to a png icon, the error is gone but the systray still doesn't appear

Could be a caching issue somewhere. Use a .png and log out and back in again to test it for sure.

**Comment by lucor** [comment]
Since you are using Ubuntu 22.04 it could be related to #4371

**Comment by theHilikus** [comment]
> system tray apps don't quit when you close the windows.
Really? from the documentation the impression I got is that that is still the case and that's why we need to disable that default behaviour by explicitly using `SetCloseIntercept`. In my example you can see that I disabled that part and the process still doesn't die but there's no icon. And BTW, it is not that it's there but with a missing icon. The systray before and after I launch the process looks exactly the same and when I hover the mouse I can confirm there is no entry at all

**Comment by theHilikus** [comment]
> Since you are using Ubuntu 22.04 it could be related to #4371

yes! this was it. thank you for the fast reply gentlemen

Adding a call on the appside to `systray.SetTitle("test")` fixed it. Should this be mentioned in the systray documentation or the PR will fix it? I'm still not very familiar with metadata but in the documentation it gives the impression that metadata is optional only to customize the icon, not mandatory. It seems that at least in ubuntu it is mandatory

**Comment by andydotxyz** [comment]
Metadata is optional (at least the metadata file - some OS builds will require parameters on a per-case basis).

We don't need more documentation or other alteration, just for that bug fix to be landed, which it is now.

**Comment by andydotxyz** [comment]
Can you test the develop branch without your local SetTiyle fix @theHilikus - if it works we can close this issue and set it to be in the next release.

**Comment by theHilikus** [comment]
I can confirm the fix works. I used `develop` at a289a25 with 
```go
	if desk, ok := dailyApp.(desktop.App); ok {
		showItem := fyne.NewMenuItem("Show", func() {
			window.Show()
		})
		menu := fyne.NewMenu("Daily Systray Menu", showItem)
		desk.SetSystemTrayMenu(menu)
		// systray.SetTitle("Daily")
		window.SetCloseIntercept(func() {
			window.Hide()
		})
	}
```

Thank you!
