### ISSUE TITLE
Clicking in Empty Table Body where no rows are present app hangs.

### ISSUE THREAD

**Issue by anclancy** [fyne-io/fyne#4387]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When clicking into an empty table section(lower Body section)  app will hang. 

When clicking in table app will hang for about 15 seconds but not throw error most of the time only throw error on Mac, not sure if it is related.

It threw this error on a Mac.  
log.go:12: Fyne error: Failed to focus object which is not part of the canvas’ content, menu or overlays.
 2023/11/14 10:42:24 log.go:19:  At: /go/pkg/mod/fyne.io/fyne/v2@v2.4.0/internal/driver/common/canvas.go:182

Tested on 2.4.0 and 2.4.1 

Also tested this on Demo App 2.4.1 table doesn't hang

OS: windows 10 11 and on Mac

### How to reproduce

Run app
Go to table that calls data
click below row, where no cell is present or empty table body

### Example code

	ZeroTrustTable = widget.NewTableWithHeaders(
			func() (int, int) { return 0, 4 },
			func() fyne.CanvasObject {
				return widget.NewLabel("Cell 000, 000")
			},

			func(i widget.TableCellID, cell fyne.CanvasObject) {

				label := cell.(*widget.Label)
				label.Truncation = fyne.TextTruncateEllipsis
				//label.Refresh()
				switch i.Col {
				case 0:
					label.SetText(fmt.Sprintf("%d", i.Row))
				case 1:
					label.SetText(*zerotableData[0].Platforms[i.Row].Name)
				case 2:
					label.SetText(fmt.Sprintf("%d", *zerotableData[0].Platforms[i.Row].NumAids))
				case 3:
					label.SetText(fmt.Sprintf("%f", *zerotableData[0].Platforms[i.Row].AverageOverallScore))
				// case 4:
				// 	label.SetText(fmt.Sprintf("%T", zerotableData[0].Platforms[i.Row].Compliance))

				default:

				}

			})

		ZeroTrustTable.SetColumnWidth(0, 50)
		ZeroTrustTable.SetColumnWidth(1, 150)
		ZeroTrustTable.SetColumnWidth(2, 100)
		ZeroTrustTable.SetColumnWidth(3, 110)
		//	ZeroTrustTable.SetColumnWidth(4, 200)

		ZeroTrustTable.Refresh()

		// Toggles Indexing built into Header Feature
		ZeroTrustTable.ShowHeaderColumn = false
		ZeroTrustTable.ShowHeaderRow = true
		// Header Customization/labeling
		ZeroTrustTable.UpdateHeader = func(id widget.TableCellID, template fyne.CanvasObject) {
			label = template.(*widget.Label)
			label.Alignment = fyne.TextAlignLeading
			switch id.Col {
			case 0:
				label.SetText("#")
			case 1:
				label.SetText("Platform")
			case 2:
				label.SetText("Device Count")
			case 3:
				label.SetText("Overall Average")
			// case 4:
			// 	label.SetText("Compliance")
			default:

			}
		}

### Fyne version

2.4.0 2.4.1

### Go compiler version

1.20.1

### Operating system and version

windows 10 11 and on Mac

**Comment by andydotxyz** [comment]
I can replicate this on v2.4.0 but not on v2.4.1 - can you please double check the v2.4.1 version in your app?
The PR #4268 merged a while back should have resolved it.

**Comment by anclancy** [comment]
Ok it is fixed had to manually get it to update mod file. Thanks!!
