### ISSUE TITLE
Shortcuts only work with modifier 

### ISSUE THREAD

**Issue by sdassow** [fyne-io/fyne#4393]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When a shortcut has no modifier it does not seem to work.

### How to reproduce

1. Run below code on desktop
3. Press Control+Escape - label text changes
2. Only press Escape - nothing happens even though the label text should change as well

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")
	l := widget.NewLabel("Hello World!")

	esc := &desktop.CustomShortcut{
		KeyName: fyne.KeyEscape,
	}
	w.Canvas().AddShortcut(esc, func(shortcut fyne.Shortcut) {
		l.SetText("ESC")
	})

	ctrlesc := &desktop.CustomShortcut{
		Modifier: fyne.KeyModifierControl,
		KeyName:  fyne.KeyEscape,
	}
	w.Canvas().AddShortcut(ctrlesc, func(shortcut fyne.Shortcut) {
		l.SetText("CTRL+ESC")
	})

	w.SetContent(l)
	w.ShowAndRun()
}
```

### Fyne version

2.4.1

### Go compiler version

1.19

### Operating system and version

OpenBSD 7.4

**Comment by andydotxyz** [comment]
That's correct. A shortcut without a modifier isn't a shortcut, at least in our world, if you want to respond to keys then use OnTypedRune or OnTypedKey on canvas or relevant extension for the widget you are working on.

**Comment by andydotxyz** [comment]
(related is #2927)

**Comment by sdassow** [comment]
Oh! How did I miss that issue?! That at least I should have caught myself, sorry.

I do think it would be worth giving a hint in the documentation about shortcuts though - PR incoming...

**Comment by sdassow** [comment]
Closing this issue since above PR addresses it now.
