### ISSUE TITLE
Entry refreshes too often

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4397]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In interactive steps (especially when cursor moves, like paste) the entry is refreshed many times.
We should try to reduce any refreshes that occur in quick succession in case they result in multiple frame draws.

### How to reproduce

paste lots?

### Example code

n/a

### Fyne version

v2.4.2

### Go compiler version

1.20.2

### Operating system and version

All

### Additional Information

As discussed in #4396

**Comment by Dorbmon** [comment]
How about to add a flag to disable the refresh? We can set that flag before we call some functions, then disable the flag after the procedure we need. After that, we can do the refresh manually.
All we need to do is to add the code to check the refresh flag in the Refresh() and update the flag where we need.

**Comment by Jacalz** [comment]
I think it is better to rework all the internal methods to not refresh and then have the exported methods refresh (or something along those lines). Some kind of refactoring basically. Having a flag in the struct to disable a specific function seems like a bad practice in my opinion.
