### ISSUE TITLE
iam not getting window also iam not getting error

### ISSUE THREAD

**Issue by Mohamedjcali** [fyne-io/fyne#4408]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

when irun the code which produces fyne helloworld is not working ima not seeing any think and if icancel and write helloworld in golang iam seeing the hello world in the terminal

### How to reproduce

1:

### Screenshots

![Screenshot (55)](https://github.com/fyne-io/fyne/assets/101645646/6b30fbe0-3629-4d1c-b421-e1d603089ef2)
this time time when irun hello world in golang normaly  is working
![Screenshot (56)](https://github.com/fyne-io/fyne/assets/101645646/64bc1e7f-4ec7-4d09-95bc-59296514e01d)
but when irun fyne iam getting nothing

![Screenshot (57)](https://github.com/fyne-io/fyne/assets/101645646/c12d9a03-dfdd-448f-9f42-4c7c3d17f3c1)
and idonloaded allll requirments

### Example code

package main

import (
	"fmt"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
	fmt.Println("hello world")
}

### Fyne version

2.4.1

### Go compiler version

1.21.4

### Operating system and version

windows 10

**Comment by Mohamedjcali** [comment]
it worked thanks but it taked like 8 minutes

**Comment by andydotxyz** [comment]
Oh sorry, 8 is a lot. Other builds should be almost instantaneous now. A large Fyne upgrade may take 2mins on first build. It's just hard to escape that there is a lot of code in our drivers and the windows C compilers are sloooow
