### ISSUE TITLE
Entry widget is not sizing properly in v2.4.1

### ISSUE THREAD

**Issue by etolnz** [fyne-io/fyne#4412]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When compiling using v2.3.5 the Entry box sizes to placeholder size. When I updated to v2.4.1 the box does not size correctly.
The exact same code (shown below) was compiled using the go.mod files (shown below).

### How to reproduce

Compile the file using the two different go.mod files.

### Screenshots

![using v2 3 5](https://github.com/fyne-io/fyne/assets/70080372/342c8c76-0306-4120-99c5-631b708974de)
![using v2 4 1](https://github.com/fyne-io/fyne/assets/70080372/069946e4-894f-479d-900a-3dd8a37f4d42)

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

var myApp fyne.App
var myCanvas fyne.Canvas
var myWindow fyne.Window

type enterEntry struct {
	widget.Entry
}

func newEnter() *enterEntry {
	entry := &enterEntry{}
	entry.ExtendBaseWidget(entry)
	return entry
}

func main() {
	myApp = app.New()
	myWindow = myApp.NewWindow("")
	myCanvas = myWindow.Canvas()
	input := newEnter()
	input.MinSize()
	input.SetPlaceHolder("Enter some text")
	ui := container.New(layout.NewVBoxLayout(), container.New(layout.NewHBoxLayout(), input))
	myCanvas.SetContent(ui)
	myCanvas.Focus(input)
	myWindow.ShowAndRun()
}

### Fyne version

v2.3.5 and v2.4.1

### Go compiler version

1.20.2

### Operating system and version

Windows 11

### Additional Information

module Test3.5

go 1.20

require fyne.io/fyne/v2 v2.3.5

require (
	fyne.io/systray v1.10.1-0.20230602210930-b6a2d6ca2a7b // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/fredbi/uri v0.1.0 // indirect
	github.com/fsnotify/fsnotify v1.5.4 // indirect
	github.com/fyne-io/gl-js v0.0.0-20220119005834-d2da28d9ccfe // indirect
	github.com/fyne-io/glfw-js v0.0.0-20220120001248-ee7290d23504 // indirect
	github.com/fyne-io/image v0.0.0-20220602074514-4956b0afb3d2 // indirect
	github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6 // indirect
	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20221017161538-93cebf72946b // indirect
	github.com/go-text/typesetting v0.0.0-20230405155246-bf9c697c6e16 // indirect
	github.com/godbus/dbus/v5 v5.1.0 // indirect
	github.com/goki/freetype v0.0.0-20220119013949-7a161fd3728c // indirect
	github.com/gopherjs/gopherjs v1.17.2 // indirect
	github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/srwiley/oksvg v0.0.0-20220731023508-a61f04f16b76 // indirect
	github.com/srwiley/rasterx v0.0.0-20210519020934-456a8d69b780 // indirect
	github.com/stretchr/testify v1.8.0 // indirect
	github.com/tevino/abool v1.2.0 // indirect
	github.com/yuin/goldmark v1.4.13 // indirect
	golang.org/x/image v0.3.0 // indirect
	golang.org/x/mobile v0.0.0-20211207041440-4e6c2922fdee // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f // indirect
	golang.org/x/text v0.6.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	honnef.co/go/js/dom v0.0.0-20210725211120-f030747120f2 // indirect
)

module Test4.1

go 1.20

require fyne.io/fyne/v2 v2.4.1

require (
	fyne.io/systray v1.10.1-0.20230722100817-88df1e0ffa9a // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/fredbi/uri v1.0.0 // indirect
	github.com/fsnotify/fsnotify v1.6.0 // indirect
	github.com/fyne-io/gl-js v0.0.0-20220119005834-d2da28d9ccfe // indirect
	github.com/fyne-io/glfw-js v0.0.0-20220120001248-ee7290d23504 // indirect
	github.com/fyne-io/image v0.0.0-20220602074514-4956b0afb3d2 // indirect
	github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6 // indirect
	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20221017161538-93cebf72946b // indirect
	github.com/go-text/render v0.0.0-20230619120952-35bccb6164b8 // indirect
	github.com/go-text/typesetting v0.0.0-20230616162802-9c17dd34aa4a // indirect
	github.com/godbus/dbus/v5 v5.1.0 // indirect
	github.com/gopherjs/gopherjs v1.17.2 // indirect
	github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/srwiley/oksvg v0.0.0-20221011165216-be6e8873101c // indirect
	github.com/srwiley/rasterx v0.0.0-20220730225603-2ab79fcdd4ef // indirect
	github.com/stretchr/testify v1.8.4 // indirect
	github.com/tevino/abool v1.2.0 // indirect
	github.com/yuin/goldmark v1.5.5 // indirect
	golang.org/x/image v0.11.0 // indirect
	golang.org/x/mobile v0.0.0-20230531173138-3c911d8e3eda // indirect
	golang.org/x/net v0.14.0 // indirect
	golang.org/x/sys v0.11.0 // indirect
	golang.org/x/text v0.12.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	honnef.co/go/js/dom v0.0.0-20210725211120-f030747120f2 // indirect
)

**Comment by andydotxyz** [comment]
Sorry, but actually the old version was not correct and the new one is. It's complicate and I'll save the details for you but in 2.4.0 you will need to turn scrolling off if you want to force it to fit the content. Usage of the constructor has remained consistent (always defaulting to scroll) in case that helps.

Anyhow, just set the scroll direction to the none constant and you'll get the previous behaviour back.

**Comment by etolnz** [comment]
Thank you for the quick response, but "just set the scroll direction to the none constant" has me stumped.

**Comment by andydotxyz** [comment]
Just:

```go
entry.Scroll = container.ScrollNone
```

**Comment by etolnz** [comment]
You're the man Andy! Thank you.

**Comment by andydotxyz** [comment]
Happy to help
