### ISSUE TITLE
Extended TextGrid widget does not display text

### ISSUE THREAD

**Issue by rr3tt** [fyne-io/fyne#4413]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I'm attempting to extend the TextGrid widget but when it's extended text no longer renders.  In the code sample I used `NewTextGridFromString` to set the text but I get the same issue when using `SetCell`.

### How to reproduce

Run example code

### Screenshots

<img width="100" alt="Screenshot 2023-11-22 at 20 38 13" src="https://github.com/fyne-io/fyne/assets/9170527/a6039c6d-b8ac-43c3-8ae6-b1fe4cc17297">

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type ExtendedTextGrid struct {
	widget.TextGrid
}

func NewExtendedTextGrid() *ExtendedTextGrid {
	e := &ExtendedTextGrid{
		// text doesn't display from this
		TextGrid: *widget.NewTextGridFromString("ExtendedTextGrid"),
	}
	e.ExtendBaseWidget(e)
	return e
}

func main() {
	a := app.New()
	window := a.NewWindow("")
	window.Resize(fyne.NewSize(500, 500))

	extendedTextGrid := NewExtendedTextGrid()
	textGrid := widget.NewTextGridFromString("TextGrid")

	window.SetContent(container.NewBorder(
		extendedTextGrid,
		textGrid,
		nil,
		nil,
		nil,
	))

	// text doesn't display from this either
	extendedTextGrid.SetText("foobar")
	window.ShowAndRun()
}
```

### Fyne version

v2.4.2

### Go compiler version

go1.21.4 darwin/arm64

### Operating system and version

macOS Ventura 13.6.1

**Comment by Jacalz** [comment]
Your code does not seem to be correct. Extending a widget should not be done using a pointer. Use this instead:
```go
type ExtendedTextGrid struct {
	widget.TextGrid
}
```

**Comment by rr3tt** [comment]
@Jacalz I updated the example code above to not use a pointer when embedding, even when doing this it still does not display text.

**Comment by Jacalz** [comment]
I think your pointer de-reference might be causing all kinds of weird problems. Will run your code later today and see what I can find.

**Comment by andydotxyz** [comment]
Yeah please don't work around this "no pointer" suggestion - you need to avoid calling the parent constructor as well.
Just embed the widget you want to extend and don't replace it with another widget through constructing. I think what you have here is two TextGrids and the rendering system is getting confused.

**Comment by Jacalz** [comment]
Yeah removing that line and doing `e.SetText()` resolves the problem. I think the wrong struct is extended in your code above.

**Comment by rr3tt** [comment]
Ah that makes sense, thank you!
