### ISSUE TITLE
Passing nil container to border should not panic

### ISSUE THREAD

**Issue by matwachich** [fyne-io/fyne#4414]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When passing a nil pointer to a container to a border container, the app panics.

### How to reproduce

Just run the provided code.

### Example code

```go
func main() {
	a := app.New()
	w := a.NewWindow("")

	var footer *fyne.Container // = nil
	if false {
		footer = container.NewCenter(widget.NewLabel("Footer Content"))
	}

	w.SetContent(container.NewBorder(
		container.NewCenter(widget.NewLabel("Header Content")),
		footer,
		nil, nil,
		widget.NewLabel("Center content\nLine 2"),
	))

	w.ShowAndRun()
}
```

### Fyne version

2.4.1

### Go compiler version

1.20.7

### Operating system and version

Windows 10

### Additional Information

Passing a nil pointer to container should be the same as passing nil directly.
This will ease dynamic layouts creation.

**Comment by andydotxyz** [comment]
Unfortunately they are not the same thing. A pointer to nil cannot be checked as nil and so we have to assume it's an object... I think if the type you are choosing to not assign was an interface (like fyne.CanvasObject) then Go would work as you expect.

**Comment by andydotxyz** [comment]
I think this is one of the "go gotchas", if I recall correctly.

**Comment by matwachich** [comment]
You are right!
I actually used *fyne.Container to avoid "this problem" with interface!

It works well with CanvasObject.

Closing... Thanks
