### ISSUE TITLE
Decouple clipboard from fyne.Window

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4418]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The clipboard in GLFW was previously tied to the window. This is no longer the case so I think it seems strange to have a `window.Clipboard()` method when clipboards generally are per app or per system and not per window.

See https://github.com/fyne-io/fyne/pull/4417 for step one.

### Is it possible to construct a solution with the existing API?

Yeah. We can move the clipboard struct anywhere we'd like.

### Describe the solution you'd like to see.

Add a `app.Clipboard()` method and deprecate the one on the window.

**Comment by Jacalz** [comment]
Cool. I'll assign myself and look into implementing this

**Comment by pierrec** [comment]
What is the status of this issue? I had a quick glance and it seems that what is left is:
- add the Clipboard() method to fyne.App
- expose the clipboard struct from internal/glfw and internal/mobile
- add the Clipboard() method to fyne.driver to expsoe that struct?
- implement the Clipboard method on app/fyneApp
- deprecate fyne.Window.Clipboard (as of 2.6?)

This seems too simple to be true :)

**Comment by andydotxyz** [comment]
That sounds about right except I don't think there is any need to expose new structs to do this...

**Comment by Jacalz** [comment]
I wonder if step two here should be to deprecate the clipboard field from shortcuts? Is there any point in passing a copy of the clipboard with each shortcut if it can be looked up easily from the app?

**Comment by andydotxyz** [comment]
It can be deprecated yes, but we will have to keep populating those deprecated fields until v3 because they were filled from inside the toolkit.

**Comment by Jacalz** [comment]
Absolutely, I'm aware of that :)

**Comment by Jacalz** [comment]
I wonder if this should stay open until those fields are deprecated or if that should be a different ticket?

**Comment by andydotxyz** [comment]
Given that there is no harm in using them still I don't think this has to stay open.
