### ISSUE TITLE
canvas.NewImageFromURI not working on Android

### ISSUE THREAD

**Issue by R00tendo** [fyne-io/fyne#4423]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I tried to make an app that loads an image from a URL but it only worked on Windows, on Android the space is just left empty. 

### How to reproduce

1. Make a program that has the code block mentioned.
2. `fyne package -os android -appID com.example.app`.
3. Install.
4. Run.

### Example code

```go
imgPath := "http://server/image.png"
imgURL := storage.NewURI(imgPath)
photo := canvas.NewImageFromURI(imgURL)
photo.FillMode = canvas.ImageFillOriginal
window.SetContent(container.NewMax(photo))
```

### Fyne version

2.4.2

### Go compiler version

1.20

### Operating system and version

Windows, Android

### Additional Information

- The phone can connect to the server so it's not a network issue.
- I have tried the program with 2 real phones and 1 virtual one. (all different versions of android: 14, 12, 13)
- I have tried retrieving these formats: png, jpg, webp   (ofc, none of them have worked).

**Comment by andydotxyz** [comment]
Please remove the `NewMax` container (a single item inside a max/stack is a no-op as widgets fill by default), then remove the fill mode too (due to pixel density the image will be 1/4 size on Android so you may not be seeing it).

Last stop using deprecated "NewURI" and pick "ParseURI" so you can check the error returned as well.

Then let us know if the output is still empty with no error...

**Comment by R00tendo** [comment]
@andydotxyz 
### **New code:**
```Go
imgPath := "http://server/image.png"
imgURL, err := storage.ParseURI(imgPath)
if err != nil {
    fmt.Println(err)
    return
}
photo := canvas.NewImageFromURI(imgURL)
window.SetContent(photo)
```

And sadly, it didn't error out, but the image still wouldn't appear....

**Comment by andydotxyz** [comment]
Check the logs ("adb logcat") for anything mentioning Fyne - as far as I know none of the image load/render rails silently...

**Comment by R00tendo** [comment]
Nevermind, I fixed the issue. So the backend server I have has very little resources (because it's only for testing) and apparently it took just the right amount of time so that when I tried the app on my Windows (in the same network), it managed to transfer the image on time but when I tried it with my phone over the internet, the connection timed out 🤣  

Anyways, thank you for trying help : )
