### ISSUE TITLE
the photo can not display

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#4432]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I want to resize the photo, but it doesn`t display correctly

### How to reproduce

seemy code

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/37319319/2923a665-eef3-4c78-8b26-eb813e9f5baa)

### Example code

```
	uri := "https://staticedu-wps.cache.iciba.com/image/71997fa082318cf15234c9eaacfec25d.jpg"
	url, _ := storage.ParseURI(uri)
	image := canvas.NewImageFromURI(url)
	image.Resize(fyne.NewSize(200, 400))
	image.FillMode = canvas.ImageFillStretch
	vbox.Add(image)
```

### Fyne version

2.4.2

### Go compiler version

1.21

### Operating system and version

windows 10 and ubuntu22.04

**Comment by andydotxyz** [comment]
VBox compresses all items to minimum height. Minimum height of a bitmap in a vector space is not defined, so it falls to 1px.
You should use a layout that gives the image as much space as you want it to fill.

**Comment by Jacalz** [comment]
Have a look at https://www.youtube.com/watch?v=LWn1403gY9E&embeds_referring_euri=https%3A%2F%2Fdeveloper.fyne.io%2F&source_ve_path=OTY3MTQ&feature=emb_imp_woyt

**Comment by andydotxyz** [comment]
Looks like you want it to fill the space, so you probably want a border container where your buttons are at the top and your image fills the remaining space.

**Comment by aohanhongzhi** [comment]
> Why did you think a Card would fill the remaining space? The Border container that I suggested will solve the problem.

so , could you tell me what is the `Border container `? 

```go
	container1 := container.New(layout.NewBorderLayout(image, nil, nil, nil))
```

I used `NewBorderLayout` ,but it still not right.

![image](https://github.com/fyne-io/fyne/assets/37319319/8889d2fc-1c95-4bd7-bdb6-182a9a85a93c)

**Comment by andydotxyz** [comment]
> Looks like you want it to fill the space, so you probably want a border container where your buttons are at the top and your image fills the remaining space.

container.NewBorder(buttons, nil, nil, nil, image)

**Comment by aohanhongzhi** [comment]
> > Looks like you want it to fill the space, so you probably want a border(边境) container where your buttons are at the top and your image fills the remaining(保持) space.
> 
> container.NewBorder(buttons, nil, nil, nil, image)
you are right, thank you very much!
![image](https://github.com/fyne-io/fyne/assets/37319319/ae400f12-4119-40f7-ad6d-96d6fe5e238d)
