### ISSUE TITLE
Support dynamically adding tab item 

### ISSUE THREAD

**Issue by baolitoumu** [fyne-io/fyne#444]
i just find the code
/*
// Prepend inserts a new CanvasObject at the top of the group
func (t *TabContainer) Prepend(object fyne.CanvasObject) {
	t.Items = append(t.Items, item)
	t.tabBar.Append(t.makeButton(item))
	t.children = append(t.children, item.Content)

	t.CreateRenderer().Refresh()}
}

// Append adds a new CanvasObject to the end of the group
func (t *TabContainer) Append(item TabItem) {
	t.Items = append(t.Items, item)
//	t.tabBar.Append(t.makeButton(item))
//	t.children = append(t.children, item.Content)

	t.CreateRenderer().Refresh()
}
*/
but it's not work

**Comment by andydotxyz** [comment]
Those features are not yet implemented, sorry.
Do you want to make this a feature request? :)

**Comment by baolitoumu** [comment]
yes,i have try to implemented this,and I have spent a lot of time，I think this is really an important function.

**Comment by andydotxyz** [comment]
Can you expand on why this is important to your app? I had imagined that dynamically changing the content of a tab bar was uncommon.

**Comment by baolitoumu** [comment]
Similar to a batch of mailbox management software, so I can easily switch the sidebar after I add the mailbox.

**Comment by andydotxyz** [comment]
That's a good answer, thanks :)

**Comment by baolitoumu** [comment]
I think every ui element can be added, deleted and modified. This gives the framework enough flexibility. :)

**Comment by andydotxyz** [comment]
Adding the "good first issue" tag - it may not be trivial but it would be contained within the TabContainer widget "Refresh" function.

**Comment by baolitoumu** [comment]
thank you so much

**Comment by andydotxyz** [comment]
On develop for testing

**Comment by andydotxyz** [comment]
Added in v1.2.1
