### ISSUE TITLE
Fyne app now broken after upgrading go to 1.21.5 and doing go get -u.

### ISSUE THREAD

**Issue by pnunn** [fyne-io/fyne#4441]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have a fyne app I'm developing that compiled and ran happily until I upgraded golang and did a go get -u.

I now have 

`# fyne.io/fyne/v2/internal/painter
../../go/pkg/mod/fyne.io/fyne/v2@v2.4.2/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)
`
when I do a go run .

Any ideas?

### How to reproduce

Install golang 1.21.5
go get -u
try and run an application that was previously running.

### Example code

go run .

### Fyne version

2.4.2

### Go compiler version

1.21.5

### Operating system and version

Linux (KDE Neon)

**Comment by andydotxyz** [comment]
Remove your project go.mod and "go mod init" then "go mod tidy" again, it should unbreak.

**Comment by pnunn** [comment]
Fixed thanks to @andydotxyz

**Comment by figuerom16** [comment]
Ran into the same issue.  Above steps fixed it.  Seems to be caused by upgrading the typesetting package.

```
[github.com/go-text/typesetting](https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231206174126-ce41cc83e028) v0.0.0-20231206174126-ce41cc83e028 // Not Working
[github.com/go-text/typesetting](https://pkg.go.dev/github.com/go-text/typesetting@v0.0.0-20231126133128-3b7c9205d99e) v0.0.0-20231126133128-3b7c9205d99e // Working
```
