### ISSUE TITLE
Add option to create APK for a single architecture

### ISSUE THREAD

**Issue by ExplorerSec** [fyne-io/fyne#4444]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When developing for Android, I found that the APKs generated were always larger than other solutions. The reason is that the default APK always contains four types of ABI, x86, x86_64, v7a, and v8a, which means that if we specify one of them, we will reduce the size of the program by a quarter of the original size!

### Is it possible to construct a solution with the existing API?

Yes，it is so easy to make it! Just provide a option, and send it to NDK!

### Describe the solution you'd like to see.

Just provide a option, and send it to NDK!

**Comment by Jacalz** [comment]
Related to https://github.com/fyne-io/fyne/issues/1097. I agree, we might want to build for one architecture at a time like we do for all other platforms.

**Comment by Jacalz** [comment]
Not sure I would call it a duplicate. This is more what needs to be done that the other issue which arguably is more stating the problem rather then the solution.

**Comment by ExplorerSec** [comment]
I'm sorry that I just found out a few hours ago that the problem has been solved, and I submitted an example, but the nupload was not successful due to network issues.

I've tried to port the program to Android, but by looking up official documentation and searching the internet, I always get build commands that look something like this:

```shell
fyne package -os android -appID com.example.myapp -icon mobileIcon.png
```

In fact, the original issue has already been supported, and if it is only for a specific Android ABI, such as v8a, we can use the following command:

```shell
fyne package -os android/arm64 -appID com.example.myapp -icon mobileIcon.png
```

Now we reduce the size of the application by a quarter of the original size.



In the end, I'm sorry for my poor English. And it's almost the first time I submit an issue, so If I use a word that is incorrect, I hope to understand.

**Comment by andydotxyz** [comment]
I would agree that this is already supported.

**Comment by Jacalz** [comment]
The other one was still open so I figured that it hadn't been solved. Should we close them both then?

**Comment by ExplorerSec** [comment]
Probably, but I am not sure, as I am new here. It's up to you.

**Comment by Jacalz** [comment]
Sorry, that was more of a question to @andydotxyz 😅

**Comment by ExplorerSec** [comment]
对不起，我理解错了你的意思。我为之前说过的话感到抱歉。😅

**Comment by ExplorerSec** [comment]
Sorry, I misunderstood what you meant. I'm sorry for what I said before.😅

**Comment by andydotxyz** [comment]
> The other one was still open so I figured that it hadn't been solved. Should we close them both then?

The other was about them being big - that probably has more conversation left. This is about supporting single platform, which we do.
