### ISSUE TITLE
GPU acceleration for canvas.Circle

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4447]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

canvas.Circle is currently not GPU accelerated

### Is it possible to construct a solution with the existing API?

yes, use canvas.Rectangle with full corner radius

### Describe the solution you'd like to see.

canvas.Circle should be accelerated. Since we can already create an acclerated circle using canvas.Rectangle with fully rounded corners, it certainly should be possible, and since a circle doesn't have differing corner radii, the shader could even be more efficient than the rounded rectangle.

**Comment by Jacalz** [comment]
Is this not already done on the develop  branch already? I think Andrew added it as part of the blinking wait thing. Though I suppose a specific OpenGL shader that isn’t a rounded rectangle would be even faster down the line

**Comment by andydotxyz** [comment]
Jacob is absolutely right (and I had forgotten!) Circle acceleration is on develop.

**Comment by dweymouth** [comment]
Should this not be in the v2.4.5 milestone? Since it doesn't add any new public APIs?

**Comment by andydotxyz** [comment]
That's an interesting question. It was bundled in with new features so was overlooked.
It doesn't seem like a high risk change given how well tested it is now.
