### ISSUE TITLE
Package for IOS fails with "requires XCode" when XCode is installed

### ISSUE THREAD

**Issue by gptlang** [fyne-io/fyne#4450]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I cannot package [the example app](https://github.com/fyne-io/calculator) for IOS on my Mac.

```sh
$ fyne package -os ios -appID my.domain.appname

-os=ios requires XCode
```

XCode is installed and running. Command line tools have also been installed via `xcode-select --install`

### How to reproduce

1. Fresh installation of MacOS Sonoma 14.1.2
2. `git clone https://github.com/fyne-io/calculator`
3. `cd calculator`
4. `go install fyne.io/fyne/v2/cmd/fyne@latest`
5. `fyne package -os ios -appID my.domain.appname`

### Fyne version

2.4.2

### Go compiler version

1.21.4

### Operating system and version

MacOS Sonoma 14.1.2

### Additional Information

IOS Simulator also doesn't work

**Comment by andydotxyz** [comment]
If you open the "Xcode" application has the license agreement been signed?
Also if you recent upgraded macOS you will need to re-install the command line tools, try running the command again to make sure it is still installed.
