### ISSUE TITLE
xcodebuild: error: Unable to read project 'main.xcodeproj' from folder

### ISSUE THREAD

**Issue by gptlang** [fyne-io/fyne#4452]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

```
xcrun xcodebuild -configuration Release -project /tmp/fyne-work-3356407224/main.xcodeproj -allowProvisioningUpdates DEVELOPMENT_TEAM=Apple Worldwide Developer Relations failed: exit status 74
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Release -project /tmp/fyne-work-3356407224/main.xcodeproj -allowProvisioningUpdates "DEVELOPMENT_TEAM=Apple Worldwide Developer Relations"

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    DEVELOPMENT_TEAM = Apple Worldwide Developer Relations

2023-12-11 13:59:40.124 xcodebuild[86872:6973698] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 89. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2023-12-11 13:59:40.125 xcodebuild[86872:6973698] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
2023-12-11 13:59:40.127 xcodebuild[86872:6973698] Writing error result bundle to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/ResultBundle_2023-11-12_13-59-0040.xcresult
xcodebuild: error: Unable to read project 'main.xcodeproj' from folder '/tmp/fyne-work-3356407224'.
	Reason: The project ‘main’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /tmp/fyne-work-3356407224/main.xcodeproj
```

### How to reproduce

1. `git clone https://github.com/fyne-io/calculator`
2. cd calculator
3. Obtain profile from  `~/Library/MobileDevice/Provisioning\ Profiles`
4. Obtain certificate by exporting from Xcode and running `openssl pkcs12 -info -in DeveloperCert.p12 -nodes -legacy`, then saving the certificate into a file
5. Run the release command
```
fyne release -os ios  -appID "com.example.myapp" -appVersion "0.0.1" -profile self.mobileprovision -certificate cert
```

### Example code

See https://github.com/fyne-io/calculator

### Fyne version

2.4.2

### Go compiler version

go1.21.4

### Operating system and version

MacOS Sonoma 14.1.2

### Additional Information

`fyne package -os ios -appID com.example.myapp` works and produces `Calculator.app`. The issue is exclusively with release.

The path specified does not exist (`/tmp/fyne-work-3356407224/main.xcodeproj: cannot open `/tmp/fyne-work-3356407224/main.xcodeproj' (No such file or directory)`)

**Comment by andydotxyz** [comment]
You are passing a filename instead of the name of the provisioning profile. You need to have double clicked it to install, then pass the name that you gave the profile which is stored inside the file.

**Comment by andydotxyz** [comment]
That is the right directory. Quickview will show you the name of the profile if you press spacebar in Finder.

If your account has expired then the certificates may no longer work.

**Comment by andydotxyz** [comment]
How did you create that profile? It sounds like you didn't do so using their provisioning and certification service online?

**Comment by gptlang** [comment]
It was made via xcode. Looks like this requires an actual paid developer account. My workflow works for me so I'll close this issue.

Workaround: Build app, put in "Payload" folder, zip it, rename to ipa, send it off to AltStore for provisioning. Stuff can be unsigned and missing, it doesn't matter.

**Comment by andydotxyz** [comment]
I hope your app got published ok. Is there a doc you could share that shows how no signing is ok for this type of upload?

**Comment by acheong08** [comment]
I wasn't uploading to Apple but sideloading with [AltStore](https://altstore.io/). I don't have any docs, was just trying out random things.
