### ISSUE TITLE
widget and layout don't work

### ISSUE THREAD

**Issue by cartmanarlekin** [fyne-io/fyne#4455]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I can't use "fyne" because when I try to execute "go get fyne.io/fyne/v2 " and when importing the corresponding modules, I always get an error, nothing helps from what I could find in Google.

### How to reproduce

go get fyne.io/fyne/v2 , go mod tidy.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/69133613/41af4661-453c-4418-891e-edd3c93b7bc3)
![image](https://github.com/fyne-io/fyne/assets/69133613/687c9b28-42e4-4d18-9cbb-9448b4822651)

### Example code

package main

import (
	"math/rand"
	"strings"
	"time"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/container/layout"
	"fyne.io/fyne/v2/container/widget"
	"fyne.io/fyne/v2/theme"
)

var jokes = []string{
	"Почему программисты так плохо играют в футбол? Потому что они не могут стоять на одном месте и следить за мячом одновременно.",
	"Как программист попросит вас сходить в магазин? `sudo go to market`.",
	"Что говорит Java-программист перед тем, как зайти в бар? - Ожидайте.",
	// Добавьте здесь свои анекдоты
}

func main() {
	rand.Seed(time.Now().UnixNano())

	myApp := app.New()
	myWindow := myApp.NewWindow("Анекдоты Чатбот")

	inputEntry := widget.NewEntry()
	outputLabel := widget.NewLabel("Добро пожаловать! Введите 'Анекдот пожалуйста'.")

	sendButton := widget.NewButtonWithIcon("Отправить", theme.MailSendIcon(), func() {
		userInput := inputEntry.Text
		response := getJokeResponse(userInput)
		outputLabel.SetText(response)
		inputEntry.SetText("")
	})

	content := container.NewVBox(
		container.New(layout.NewSpacer(), widget.NewLabel("Чатбот на Go"), layout.NewSpacer()),
		container.New(layout.NewSpacer(), inputEntry, sendButton, layout.NewSpacer()),
		container.New(layout.NewSpacer(), outputLabel, layout.NewSpacer()),
	)

	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}

func getJokeResponse(userInput string) string {
	if containsIgnoreCase(userInput, "Анекдот пожалуйста") {
		return getRandomJoke()
	}
	return "Извините, я не понимаю ваш запрос. Пожалуйста, напишите 'Анекдот пожалуйста', чтобы услышать анекдот."
}

func getRandomJoke() string {
	index := rand.Intn(len(jokes))
	return jokes[index]
}

func containsIgnoreCase(s, substr string) bool {
	s, substr = strings.ToLower(s), strings.ToLower(substr)
	return strings.Contains(s, substr)
}

### Fyne version

2.4.2

### Go compiler version

1.21.4

### Operating system and version

windows 11

**Comment by andydotxyz** [comment]
The sub package "container/layout" and "container/widget" do not exist.

**Comment by cartmanarlekin** [comment]
then how can I use them, because they are in the files?
![ааааа](https://github.com/fyne-io/fyne/assets/69133613/9f907e88-c7de-48b2-9861-43923345fc26)

**Comment by andydotxyz** [comment]
That is `widget` and `layout` not `container/widget` and `container/layout`.
