### ISSUE TITLE
error while importing fyne.io/fyne/v2/internal/painter/gl: build constraints exclude all Go files in C:\Users\<username>\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20231021071112-07e5d0ea2e71\v2.1\gl

### ISSUE THREAD

**Issue by lorypelli** [fyne-io/fyne#4456]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I can't use the library because of this

### How to reproduce

Install latest version of fyne, also it happens with older ones

### Example code

the getting started code in the repo

### Fyne version

2.4.2

### Go compiler version

1.21.5

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
The Go compiler cannot find your C compiler. Try following https://developer.fyne.io/started/

**Comment by lorypelli** [comment]
> The Go compiler cannot find your C compiler. Try following https://developer.fyne.io/started/

https://jmeubank.github.io/tdm-gcc/download/
I actually already have the one from visual studio but I installed also this one and it doesn't work...

**Comment by lorypelli** [comment]
@andydotxyz I managed to fix, but now it's saying this
![image](https://github.com/fyne-io/fyne/assets/87276663/29337e1f-d146-477c-a260-618ca963a462)

**Comment by lorypelli** [comment]
all fixed

**Comment by lorypelli** [comment]
It's not necessary to reopen it, all is fixed now and I'm using the framework, if there are some problems, I will open a new issue

**Comment by twi1ightt** [comment]
> @andydotxyz I managed to fix, but now it's saying this ![image](https://private-user-images.githubusercontent.com/87276663/290996463-29337e1f-d146-477c-a260-618ca963a462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDE0MTAsIm5iZiI6MTcwMzcwMTExMCwicGF0aCI6Ii84NzI3NjY2My8yOTA5OTY0NjMtMjkzMzdlMWYtZDE0Ni00NzdjLWEyNjAtNjE4Y2E5NjNhNDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE4MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTAzOTVkZThiYTRmYWQ1NjQ5NGIzOTVlMDc4YTRhODdmY2Y4YzVkZWEyOTM5OGNhOTZkYTRiM2RmMTE5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sjmrcYsP1bh-f94MUwk6aM3vBFA2s0AstChvGbTOSzs)

how did you manage to fix it, im having the same issue and i have a c compiler already, tried "go clean -modcache" and reruinding and nothing

**Comment by lorypelli** [comment]
> > @andydotxyz I managed to fix, but now it's saying this ![image](https://private-user-images.githubusercontent.com/87276663/290996463-29337e1f-d146-477c-a260-618ca963a462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDE0MTAsIm5iZiI6MTcwMzcwMTExMCwicGF0aCI6Ii84NzI3NjY2My8yOTA5OTY0NjMtMjkzMzdlMWYtZDE0Ni00NzdjLWEyNjAtNjE4Y2E5NjNhNDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE4MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTAzOTVkZThiYTRmYWQ1NjQ5NGIzOTVlMDc4YTRhODdmY2Y4YzVkZWEyOTM5OGNhOTZkYTRiM2RmMTE5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sjmrcYsP1bh-f94MUwk6aM3vBFA2s0AstChvGbTOSzs)
> 
> how did you manage to fix it, im having the same issue and i have a c compiler already, tried "go clean -modcache" and reruinding and nothing

You need to have it in PATH and if it's not GCC, you would need to change the env variable, also, check if C is enabled
