### ISSUE TITLE
iOS packaging issue

### ISSUE THREAD

**Issue by lidldev** [fyne-io/fyne#4460]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Hello, I am trying to package for iOS with Fyne, but I am getting this error and I don't understand how to solve it.

error --> failed to look up certificate : exit status 44

### How to reproduce

I wrote a very simple application to try this, but when I package it, I get the error I mentioned above (xCode iOS items are installed).

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Clock")
	entry := widget.NewEntry()

	w.Resize(fyne.NewSize(300, 500))
	w.SetContent(container.NewVBox(entry))
	w.Show()

	w.SetContent(container.NewVBox(widget.NewButton("Button!!", func() {
		w2 := a.NewWindow("Heey!!")
		w2.Resize(fyne.NewSize(300, 500))
		w2.Show()
	})))

	a.Run()
}
```

### Fyne version

v2.4.2

### Go compiler version

1.21.5

### Operating system and version

macOS Sonoma 14.1.2

**Comment by andydotxyz** [comment]
Do you have an Apple developer certificate and provisioning profile for your application?
If you're not sure what that is we have some docs at https://developer.fyne.io/started/distribution.

If you have them, were they installed into the current mac you are using to build from?

**Comment by AhmetAffan0** [comment]
> Do you have an Apple developer certificate and provisioning profile for your application? If you're not sure what that is we have some docs at https://developer.fyne.io/started/distribution.
> 
> If you have them, were they installed into the current mac you are using to build from?

i dont know developer certificate Is there any need for packaging?

**Comment by andydotxyz** [comment]
To put an app onto a physical item of Apple hardware you need to sign up to their developer programme.

**Comment by RiRa12621** [comment]
is this the same for working the the ios simulator?

```
$ fyne package -os iossimulator -appID com.testing -icon images/apple-touch-icon.png 
failed to look up certificate : exit status 44


```

**Comment by andydotxyz** [comment]
> is this the same for working the the ios simulator?
> 
> ```
> $ fyne package -os iossimulator -appID com.testing -icon images/apple-touch-icon.png 
> failed to look up certificate : exit status 44
> ```

Someone else reported this recently - it seems that can happen if you don't have Xcode fully set up. I think that they don't inject the developer certificate until you log it in.
We tried to ship a certificate to just work out of the box, maybe that has expired in the tooling. If you have done all the setup then best to open an issue instead of commenting on a closed one.

**Comment by RiRa12621** [comment]
FYI in case anyone else runs into: you need to actually start up xcode, go to
settings add your appleID and then manage certificates and if you click the little
plus, you can add a developer certificate. After this you'll be able to build like expected.
