### ISSUE TITLE
Compilation fails with error about out.LineBounds.LineHeight in internal/painter/font.go:209:65

### ISSUE THREAD

**Issue by rasteric** [fyne-io/fyne#4468]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Compilation of my program (which uses almost all of Fyne's features) fails after a general dependency upgrade:

```
fyne.io/fyne/v2/internal/painter
/home/nemo/go/pkg/mod/fyne.io/fyne/v2@v2.4.2/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)

```
The program is the [GUI version of my toy Lisp interpreter](https://github.com/rasteric/z3s5-lisp/blob/main/cmd/z3g/z3g.go) with wrapper functions defined [here](https://github.com/rasteric/z3s5-lisp/blob/main/gui/gui.go).

### How to reproduce

It's a compilation failure on Linux Mint 21.2 Cinnamon using Go 1.21.4

### Example code

I cannot isolate the compilation error, the wrapper uses nearly all features of Fyne. But it compiled fine before I upgraded dependencies.

### Fyne version

2.4.2

### Go compiler version

1.21.4

### Operating system and version

Linux Mint 21.2

**Comment by dweymouth** [comment]
Did you use `go get -u` to update all dependencies? You need to keep the modules that Fyne depends on at the same version as requested in Fyne's go.mod. The latest versions of the go-text dependencies introduced breaking public API changes that Fyne has not migrated to yet.

**Comment by rasteric** [comment]
Yes it, I used `go get -u ./...`, and also tried `go clean -modcache` in my attempts to get it working again. It would be good to know when users can update their Fyne app using `go get -u`, or the docs should state how to update the Fyne dependency without breaking an existing dependency chain.

**Comment by dweymouth** [comment]
I think `go get fyne-io/fyne/v2@latest` should be the preferred command to update the Fyne version for your project

**Comment by rasteric** [comment]
Thanks I will update more carefully next time.

**Comment by Jacalz** [comment]
Yeah, updating dependencies of dependencies is rarely a good idea unless you are 100% sure that there are no API or behaviour changes.

**Comment by 941748** [comment]
Switch back to go version 1.17.13  and there should be no problem.

**Comment by andydotxyz** [comment]
This does not relate to Go version, it is a mismatch between an old and new go-text/typesetting API
