### ISSUE TITLE
Padding set to zero make form labels jump out

### ISSUE THREAD

**Issue by geertjanvdk** [fyne-io/fyne#4471]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When padding is set to zero (0), and we show a form, the labels might go outside the canvas it is added to. This can be a PopUp or container.

### How to reproduce

1. Compile and run the example code provided with this report `go run .`

### Screenshots

<img width="573" alt="padzero" src="https://github.com/fyne-io/fyne/assets/6458628/b0f68c8d-86a2-4772-b493-9da6cd7e902a">

### Example code

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	a.Settings().SetTheme(myTheme{})

	w := a.NewWindow("PadZero")
	w.Resize(fyne.NewSize(800, 600))
	w.CenterOnScreen()

	usernameField := widget.NewEntry()
	passwordField := widget.NewPasswordEntry()

	f := &widget.Form{}

	f.Append("Username", usernameField)
	f.Append("Password", passwordField)

	popUp := widget.NewModalPopUp(f, w.Canvas())
	popUp.Resize(fyne.NewSize(300, 200))
	popUp.Show()
	
	w.ShowAndRun()
}

type myTheme struct{}

var _ fyne.Theme = (*myTheme)(nil)

func (m myTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {

	return theme.DefaultTheme().Color(name, variant)
}

func (m myTheme) Font(style fyne.TextStyle) fyne.Resource {

	return theme.DefaultTheme().Font(style)
}

func (m myTheme) Icon(name fyne.ThemeIconName) fyne.Resource {

	return theme.DefaultTheme().Icon(name)
}

func (m myTheme) Size(name fyne.ThemeSizeName) float32 {

	switch name {
	case theme.SizeNamePadding:
		return 0
	default:
		return theme.DefaultTheme().Size(name)
	}
}

```

### Fyne version

2.4.2

### Go compiler version

1.21

### Operating system and version

macOS 14.1

### Additional Information

Discussed on Gophers Slack #fyne.

**Comment by andydotxyz** [comment]
Resolved on develop branch and we will pick it into v2.4.4 in January.
