### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by catsalt** [fyne-io/fyne#448]
how can I adjust the whole UI's Text size? it's too small, and I try my best to find, but didn't  find the way to change the text size,

**Comment by andydotxyz** [comment]
@catsalt we are working on different releases, without knowing the answer to the question posted above, or a response to if @yale8848 suggestion helped I can't accurately answer your question, sorry.

With text sizing there is FYNE_SCALE and Settings.SetTheme() in the current release, fyne_settings will appear later this year but there are other changes in patch releases that will fall soon. I'm still not sure which of these aspects fits your needs as there is not a lot of information to go on.
