### ISSUE TITLE
Adding max and min size limit

### ISSUE THREAD

**Issue by kehiy** [fyne-io/fyne#4484]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

add a method to set maximum and minimum window size limit.

### Describe the solution you'd like to see.

.

**Comment by andydotxyz** [comment]
The minimum size of a window is already set - the minimum size of its content.

What would the purpose be of setting a maximum size for user-resizable window?

**Comment by kehiy** [comment]
to ensure that the user won't be able to reduce the window to an unusable size.

**Comment by andydotxyz** [comment]
Yes, user cannot reduce already - that is the min size. What I was asking about was the request for a max size.

**Comment by kehiy** [comment]
also make sure user won't increase it more than a specific size.

**Comment by andydotxyz** [comment]
I understand what you mean regarding a max size - but what is a use-case?
Why should app developers stop users making use of the space on their screen?
