### ISSUE TITLE
High rate text widget/container

### ISSUE THREAD

**Issue by r00tc0d3** [fyne-io/fyne#4489]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

High CPU load when adding thousands of text canvas object to a VBox.

### Is it possible to construct a solution with the existing API?

Not sure

### Describe the solution you'd like to see.

For logging purposes I need a widget or container which can cope with thousands of log lines per second. I did some testing using a VBox and VScroll with adding text objects which works fine until the adding rate becomes to high. 

What I want to do is to limit the refresh rate to the screen rate, e.g. 60Hz but be able to add more data (text) to the container/widget. Also, processing only the data which is visible. This to keep the cpu load low and no unnecessary work is done. I have done this using imgui (with golang binding). There I am using clipper, which does the job fine . But I want to change to Fyne but with some testing this is keeping me from changing.

Do I overlook something are does this have to be made? If so, what is the best way to implement it.

**Comment by andydotxyz** [comment]
VBox cannot optimise - it must render everything above it to calculate where lower elements are.
Probably you want a `Liat` which only draws what is visible.s

**Comment by r00tc0d3** [comment]
A did some testing with `List` but the spacing between the line is quite large? Performance (and stability) looks much better.
With a normal list one could use SetItemHeight but how is that done with a data binded list? Or is there another way to change the padding of a single widget?

**Comment by andydotxyz** [comment]
Using a raw list and a data bind list should not change how you set a row height.

**Comment by r00tc0d3** [comment]
`func (l *List) SetItemHeight(id ListItemID, height float32)` needs a id, which you don't have with `func NewListWithData(data binding.DataList, createItem func() fyne.CanvasObject, updateItem func(binding.DataItem, fyne.CanvasObject)) *List {
`

**Comment by r00tc0d3** [comment]
I am new to Fyne and I am struggling manipulating single widgets, so not the theme. I have used containers and other stuff to change the height but without results. I am puzzled.

**Comment by r00tc0d3** [comment]
The 'List' will not work properly. Also the lack of control of widgets makes it hard to use.
Fyne looks really cool and mature but it laks some basics. I have to think if I will start using Fyne.
For me this issue can be closed. Might create some new ones :-)

**Comment by andydotxyz** [comment]
> > Using a raw list and a data bind list should not change how you set a row height.
> 
> 
> 
> 
> 
> `func (l *List) SetItemHeight(id ListItemID, height float32)` needs an id, which you don't have using  updateItem function
> 
> `func NewListWithData(data binding.DataList, createItem func() fyne.CanvasObject, updateItem func(binding.DataItem, fyne.CanvasObject))`

The ListItemID matches the index of your data - so you could iterate if you know it in advance, maybe include an id in your bound data or just use the "NewList" instead?

**Comment by andydotxyz** [comment]
> Also the lack of control of widgets makes it hard to use.
> 
> Fyne looks really cool and mature but it laks some basics.

Widget size is set by the container it is in, I've no idea what lacking you are describing, so I'm not sure I can be more helpful.

**Comment by r00tc0d3** [comment]
I need only a list with text. The 'List' can do that. However the space between the lines (Labels) is for me too large. So, I want to decrease the size between the lines (Labels widgets). How do I do that?
I managed to get what I want using
``` golang
func (m myTheme) Size(name fyne.ThemeSizeName) float32 {
	switch name {
	case theme.SizeNameSeparatorThickness:
		return 0
	case theme.SizeNameInnerPadding:
		return 0
	case theme.SizeNamePadding:
		return 0
	default:
		return theme.DefaultTheme().Size(name)
	}
}
```
But this is for all widgets using a theme change. Using SetItemHeight did not has the wanted effect. It behaved rather strange. Also I want to set it global for the list. Not for every individual using a index.

I like to do stuff per widget. Something like:
``` golang
    w := widget.NewLabel("Label").SetHeight(25.2).SetFgColor(red).SetWidth(100)..etc
```
Simular for a list.
```  golang
        tmpl := widget.NewLabel("template")
	tmpl.TextStyle = fyne.TextStyle{Monospace: true}
	l := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return tmpl
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		})
```

This could be written as:
``` golang
      l := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("template").SetTextStyle(fyne.TextStyle{Monospace: true})
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			o.(*widget.Label).Bind(i.(binding.String))
		}).SetItemHeight(25.2)
```
Which is more compact an easier to read. At least for my ;-)
So set the properties where they apply and return the context so you can concatenate them for easy reading.

**Comment by Jacalz** [comment]
The idiom of `NewA().DoStuff().DoMore()` is something you see a lot of in Rust (and probably other languages) but it is relatively uncommon in Go. Truth be told, I'm also not a huge fan of it myself. Makes things harder to read in my opinion (and is probably somewhat slower unless the compiler manages to optimize it). Making that change would also be a huge breaking change so you are unlikely to ever see it in our code base I would think.

**Comment by r00tc0d3** [comment]
> The idiom of `NewA().DoStuff().DoMore()` is something you see a lot of in Rust (and probably other languages) but it is relatively uncommon in Go. Truth be told, I'm also not a huge fan of it myself. Makes things harder to read in my opinion (and is probably somewhat slower unless the compiler manages to optimize it). Making that change would also be a huge breaking change so you are unlikely to ever see it in our code base I would think.

I know quite a lot of go code which uses idiom. The compiler does optimize it very well. But it is choice.
It is not a big breaking change. It is optional to use it. You could still do it 'the old fashion way'. One need to use the `_` it bit more :-)

**Comment by r00tc0d3** [comment]
But apart from the syntax, I still can't make easily property changes to a widget like sizes, colors, flags and styles.

**Comment by Jacalz** [comment]
> It is not a big breaking change. It is optional to use it. […] And it can be added one at a time. It is also not much work, I think.

Nope. It is a huge breaking change. We’d have to change every return type on every method. It would result in not a single Fyne project compiling with the new version…

**Comment by Jacalz** [comment]
> But apart from the syntax, I still can't make easily property changes to a widget like sizes, colors, flags and styles.

The PR https://github.com/fyne-io/fyne/pull/4313 might improve things for you but in general you are not supposed to change sizes in that way. Andrew probably has a better answer here but in general you should make sure to keep the interface consistent and not change widgets individually.

**Comment by andydotxyz** [comment]
> Also I want to set it global for the list. Not for every individual using a index.

The widgets have a standard height so that they always align.

If you want to change that in a List usage the easiest thing to do is put it in a container with a custom "negative padded" layout. Just implement the Layout interface and return less than the widgets MinSize and lay it out to be half the difference offset up and left.

https://developer.fyne.io/extend/custom-layout

**Comment by andydotxyz** [comment]
> But apart from the syntax, I still can't make easily property changes to a widget like sizes, colors, flags and styles.

The widgets are standard size and look. The theme controls all those aspects. Either use the builtin behaviour APIs (like importance and disabled etc) or extend them or build your own widgets.

Most likely you'll get best help by joining one of the support channels and describing the sorts of customisation you can't figure how to achieve - common use-cases normally have APIs that could have been overlooked.

**Comment by r00tc0d3** [comment]
> > It is not a big breaking change. It is optional to use it. […] And it can be added one at a time. It is also not much work, I think.
> 
> Nope. It is a huge breaking change. We’d have to change every return type on every method. It would result in not a single Fyne project compiling with the new version…

I don't agree. See this example

``` golang
package main

// TextStyle represents the styles that can be applied to a text canvas object
// or text based widget.
type TextStyle struct {
	Bold      bool // Should text be bold
	Italic    bool // Should text be italic
	Monospace bool // Use the system monospace font instead of regular
	// Since: 2.2
	Symbol bool // Use the system symbol font.
	// Since: 2.1
	TabWidth int // Width of tabs in spaces
}

type Label struct {
	height    float32
	width     float32
	TextStyle TextStyle
}

// NewLabel creates a new label widget with the set text content
func NewLabel(text string) *Label {
	return &Label{}
}

func (l *Label) SetStyle(s TextStyle) *Label {
	l.TextStyle = s
	return l
}

func main() {
	// Fyne Style
	t1 := NewLabel("template")
	t1.TextStyle = TextStyle{Monospace: true}

	// Fyne style using Setter
	t2 := NewLabel("template")
	t2.SetStyle(TextStyle{Monospace: true})

	// Chained method style
	_ = NewLabel("template").SetStyle(TextStyle{Monospace: true})
}

```

**Comment by r00tc0d3** [comment]
> > But apart from the syntax, I still can't make easily property changes to a widget like sizes, colors, flags and styles.
> 
> The widgets are standard size and look. The theme controls all those aspects. Either use the builtin behaviour APIs (like importance and disabled etc) or extend them or build your own widgets.
> 
> Most likely you'll get best help by joining one of the support channels and describing the sorts of customisation you can't figure how to achieve - common use-cases normally have APIs that could have been overlooked.

Sure that's why I am asking. But Fyne's way of API dealing with properties is not needed and can be changed without breaking. Just adding. Because how is construct now, a lot of work and insides are needed for a simple change.
But it is better to discuss it on the support channels, I agree, and not in a GitHub issue.
Which one is most used? Discord or Slack?

**Comment by Jacalz** [comment]
> I don't agree. See this example. No breaking

That’s only because the example doesn’t cover all the cases. Any change of a function signature is breaking. Take this pseudo code when `Refresh()` is assumed to be updated to return a reference to the object:

```go
func SetOnChanged(callback func()) {
}

func main() {
    label := widget.NewLabel()
    SetOnChanged(label.Refresh) // Does no longer compile because the function signature changed and does not match void func()
}
```

It IS a huge breaking change. Even more so for methods that already return something else. It isn’t feasible for us to do that change.

I also don’t quite understand why what we already have is hard to use. You just call the methods on the object you have instead of chaining together methods.

**Comment by r00tc0d3** [comment]
> > I don't agree. See this example. No breaking
> 
> That’s only because the example doesn’t cover all the cases. Any change of a function signature is breaking. Take this pseudo code when `Refresh()` is assumed to be updated to return a reference to the object:
> 
> ```go
> func SetOnChanged(callback func()) {
> }
> 
> func main() {
>     label := widget.NewLabel()
>     SetOnChanged(label.Refresh) // Does no longer compile because the function signature changed and does not match void func()
> }
> ```
> 
> It IS a huge breaking change. Even more so for methods that already return something else. It isn’t feasible for us to do that change.
> 
> I also don’t quite understand why what we already have is hard to use. You just call the methods on the object you have instead of chaining together methods.

It breaks because you want to implement it on all methods. You shouldn't. There's no reason to put Refresh() in a chain.
It is not hard to use it otherwise. When applied to setters you give extra freedom without loosing the ability use it your way.

**Comment by Jacalz** [comment]
> It breaks because you want to implement it on all methods. You shouldn't. There's no reason to put Refresh() in a chain.

All methods or just some methods makes no difference at all. Any change to the function signature of a method will be breaking, there is no way around it.

Refresh was also just an example. Whether it makes sense or not is irrelevant as the problem applies to all kinds of changes of function signatures. The very same problem occurs if you modify `entry.SetText(string)` to return the object reference and had already passed that method into a `func SetOnChanged(callback func(string)) in your code.

**Comment by r00tc0d3** [comment]
> > It breaks because you want to implement it on all methods. You shouldn't. There's no reason to put Refresh() in a chain.
> 
> All methods or just some methods makes no difference at all. Any change to the function signature of a method will be breaking, there is no way around it.
> 
> Refresh was also just an example. Whether it makes sense or not is irrelevant as the problem applies to all kinds of changes of function signatures. The very same problem occurs if you modify `entry.SetText(string)` to return the object reference and the developer already passed that method into a `func SetOnChanged(callback func(string))` somewhere.

Ok, no change means no progress. If that's want you want fine with me.
But I think is not as black a white as you are suggesting. I would have liked a more constructive discussion.
API is one thing. The fyne style is sometimes not my style (some, like directly modifying members is very debatable) but it is what it is and everybody has an opinion about it. There should be consensus in the fyne team and something has to be chosen else there will never by an implementation. I am glad Fyne exists. 

The biggest issue a have with fyne is that a have to put stuff in a container to be able to change properties of a widget which should just be changeable. Initial the get the theme values but after that the user should be able to change it easily.
I worked with lots of gui library and frameworks over the past 30 or more years. Never I could not change the size of a widget....

**Comment by Jacalz** [comment]
All I was trying to say is that it isn't as simple of a change as you seemed to think. It was not a discussion of the best API design on my part. I'm not outright dismissing the idea (although I'm personally not a fan of that API design) but doing that change would be a very big one and require a `v3` version update. It would require a lot of coordination in our team if we were to keep the API consistent and avoid developer confusion.

**Comment by r00tc0d3** [comment]
I understand what you are saying which is a valid argument. 
I think the change, which can be done in phases, is smaller than what you are thinking. And you think is bigger than I am thinking. We don't know each other so that's a hard one, but the true probably lies in the middle :-P
Thanks for your views!

**Comment by Jacalz** [comment]
That might be the case, yes :)

**Comment by andydotxyz** [comment]
> Ok, no change means no progress. If that's want you want fine with me.
> But I think is not as black a white as you are suggesting. I would have liked a more constructive discussion.

This has been discussed before (there will be issues or proposals around somewhere, a few years back). At the time it was looked into in-depth and it was agreed (by the proposer) to be non-trivial and would indeed require breaking changes.
As it would be a change in the general API design aesthetic we also felt that changing in small increments would lead to an inconsistent developer experience and so it was parked until a future breaking API release is considered.

**Comment by andydotxyz** [comment]
> The biggest issue a have with fyne is that a have to put stuff in a container to be able to change properties of a widget which should just be changeable. Initial the get the theme values but after that the user should be able to change it easily.
> I worked with lots of gui library and frameworks over the past 30 or more years. Never I could not change the size of a widget....

The size is set by the parent container, that is our design. It allows a much more flexible layout system that scales to many different types of devices.
The designers of this have also worked with lots of GUI libraries over 20 or more years. Many in fact have built those systems!

The design we have is different, but it's different with good reasons - as set out in our architecture/design documentation.

**Comment by r00tc0d3** [comment]
> > Ok, no change means no progress. If that's want you want fine with me.
> > But I think is not as black a white as you are suggesting. I would have liked a more constructive discussion.
> 
> This has been discussed before (there will be issues or proposals around somewhere, a few years back). At the time it was looked into in-depth and it was agreed (by the proposer) to be non-trivial and would indeed require breaking changes. As it would be a change in the general API design aesthetic we also felt that changing in small increments would lead to an inconsistent developer experience and so it was parked until a future breaking API release is considered.

Fair enough and understandable. It is always a struggle between progress and breaking things. However, at some moment in time one has to make tough decisions. But as I understand it not now.

**Comment by r00tc0d3** [comment]
> > The biggest issue a have with fyne is that a have to put stuff in a container to be able to change properties of a widget which should just be changeable. Initial the get the theme values but after that the user should be able to change it easily.
> > I worked with lots of gui library and frameworks over the past 30 or more years. Never I could not change the size of a widget....
> 
> The size is set by the parent container, that is our design. It allows a much more flexible layout system that scales to many different types of devices. The designers of this have also worked with lots of GUI libraries over 20 or more years. Many in fact have built those systems!
> 
> The design we have is different, but it's different with good reasons - as set out in our architecture/design documentation.

It feels, at least for me, a bit over engineered which also comes with a cost. But it is easy for me to say. I will do a deep-dive and try to comprehend the consideration you all made.
