### ISSUE TITLE
Android: "Failed to create directory" error  when using  Storage().Create function.

### ISSUE THREAD

**Issue by ekremparlak** [fyne-io/fyne#4490]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When i tried to create a storage it gives an "Failed to create directory" error. 
Also when trying to use the Preferences, it work until i restart the app. After restarting everything lost.

When i tried to create a new file directly from  os.Create, it gives an read-only filesystem error.

I testing this on Android 9,12,14 . 12 is a real device, others emulator

I build the app with fyne-cross

### How to reproduce

1. Build the app with ```fyne-cross android --app-id=com.example.myapp```
2. Open the app, app would be crashed 

### Example code

````go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"
)

func checkifconfigexists() bool {
	// check if the config file exists
	storage, err := Myapp.Storage().Open("config.json")
	defer storage.Close()
	return err == nil
}

func createStorage() error {
	// create a storage file
	storage, err := Myapp.Storage().Create("config.json")
	if err != nil {
		return err
	}
	defer storage.Close()
	return nil
}

func ReadConfig() (config AppConfig, err error) {
	// open the config file
	storage, err := Myapp.Storage().Open("config.json")
	if err != nil {
		return
	}
	defer storage.Close()

	// read the config file
	body, err := io.ReadAll(storage)
	if err != nil {
		return
	}

	// unmarshal the config file
	err = json.Unmarshal(body, &config)
	if err != nil {
		return
	}

	return
}

func SaveConfig(config AppConfig) (err error) {
	// open the config file
	storage, err := Myapp.Storage().Save("config.json")
	if err != nil {
		return
	}
	defer storage.Close()

	// marshal the config file
	body, err := json.Marshal(config)
	if err != nil {
		return
	}

	// write the config file
	_, err = storage.Write(body)
	if err != nil {
		return
	}

	return
}

func init() {
	Myapp = app.NewWithID("com.example.myapp")
	AppWindow = Myapp.NewWindow("TabContainer Widget")
	AppWindow.Resize(fyne.NewSize(1024, 600))
	AppWindow.SetContent(tabs())

	//check if the config file exists
	if !checkifconfigexists() {
		err := createStorage()
		if err != nil {
			fmt.Println(err.Error())
		}
		SaveConfig(Config)
	}

	// read the config file
	err := error(nil)
	Config, err = ReadConfig()
	if err != nil {
		fmt.Println(err.Error())
	}
	AppWindow.ShowAndRun()
}
````

### Fyne version

2.4.3

### Go compiler version

1.20

### Operating system and version

Fedora 38

### Additional Information

Since i build with fyne-cross, i'm not sure with go compiler version they use.

If the example code may not be enough, i can make a repo to reproduce the error.

**Comment by ArsArsArsArs** [comment]
Relatable. Looking forward to a fix

**Comment by andydotxyz** [comment]
Following some Discord conversation today it seems like this could be coming from an unexpected area.
Can you please find out what `App.Storage().RootURI()` is returning?

Either

- that is correct and we have an error in our permission code
- the root is not correct and there is something in the bootstrap not working (which is what we found on discord today)

**Comment by atljoseph** [comment]
Coming from iOS here... Was having similar issue. I grabbed the code from this issue and tried to run it (expecting it to work somewhat), and found that that a number of modifications were required. Something weird was happening in the originally posted code between checking existence and opening and writing to file...Would never write anything, but this code does write a file! Want to make sure ya'll aren't chasing your tails on this on the Android side, as i also was on Android.
```
package main

import (
	"encoding/json"
	"fmt"
	"image/color"
	"io"
	"strings"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

//go:generate fyne bundle -o bundled.go assets

type AppConfig struct {
	MyVal string
}

type MyApp struct {
	App    fyne.App
	Window fyne.Window
}

func main() {
	myapp := MyApp{App: app.NewWithID("com.example.files.app")}
	myapp.App.Settings().SetTheme(newTheme())
	myapp.Window = myapp.App.NewWindow("Example")
	myapp.Window.Resize(fyne.NewSize(1024, 600))
	myapp.Window.SetContent(widget.NewButton("Test", func() {

		//check if the config file exists
		rootUri := strings.Join(strings.Split(myapp.App.Storage().RootURI().String(), "/"), "\n")
		filename := "config.json"
		defaultConfig := AppConfig{
			MyVal: "123",
		}

		writer, err := myapp.App.Storage().Create(filename)
		if err != nil {
			dialog.NewError(fmt.Errorf("error on Create Writer %s: %w; RootURI: %s", filename, err, rootUri), myapp.Window).Show()
		}
		defer writer.Close()

		jsonBytes, jsonErr := json.Marshal(defaultConfig)
		if jsonErr != nil {
			dialog.NewError(fmt.Errorf("error on Marshal JSON %s: %w; RootURI: %s", filename, err, rootUri), myapp.Window).Show()
		}

		if _, err := writer.Write(jsonBytes); err != nil {
			dialog.NewError(fmt.Errorf("error on Write File %s: %w; RootURI: %s", filename, err, rootUri), myapp.Window).Show()
		}

		reader, err := myapp.App.Storage().Open(filename)
		if err != nil {
			dialog.NewError(fmt.Errorf("error on Create Reader %s: %w; RootURI: %s", filename, err, rootUri), myapp.Window).Show()
		}
		defer reader.Close()

		readBytes, readErr := io.ReadAll(reader)
		if readErr != nil {
			dialog.NewError(fmt.Errorf("error on Read File %s: %w; RootURI: %s", filename, readErr, rootUri), myapp.Window).Show()
		}
		dialog.NewInformation(fmt.Sprintf("file %s", filename), string(readBytes), myapp.Window).Show()
	}))
	myapp.Window.ShowAndRun()
}

type Theme struct {
	fyne.Theme
}

func newTheme() fyne.Theme {
	return &Theme{
		Theme: theme.DefaultTheme(),
	}
}

func (t *Theme) Color(name fyne.ThemeColorName, _ fyne.ThemeVariant) color.Color {
	return t.Theme.Color(name, theme.VariantDark)
}

func (t *Theme) Size(name fyne.ThemeSizeName) float32 {
	return t.Theme.Size(name)
}

```

**Comment by ekremparlak** [comment]
Hi @atljoseph there was some discussion on the discord and it was found that the error doesn't happen if you  call it from the main function
From discord:

> 
> ````
> var a fyne.App
> 
> func init() {
>     a = app.NewWithID("something")
>     a.Storage().RootURI().Path() // /data/data
> }
> 
> func main() {
>    a.Storage().RootURI().Path() // /data/user/0... (The correct path)
>    dbPath()
> }
> 
> func dbPath() {
>     a.Storage().RootURI().Path() // /data/data
> }
> ````

**Comment by atljoseph** [comment]
OK, thanks! Glad its resolved all around, to a degree :)

**Comment by andydotxyz** [comment]
Are you certain about `dbPath` being wrong? That makes no sense.

Not working in `init` makes sense as apps should be created in `main`.
The JVM and iOS app context won't exist before the app actually starts executing.

**Comment by ekremparlak** [comment]
I believe that test was done by @ArsArsArsArs 
But i was also  test it  with calling from another package without init and the result was the same. I may remembering wrong. 
I will try to reproduce it on weekend

**Comment by andydotxyz** [comment]
Please do check it yourself, or get the original reporter on Discord to check. It just doesn't make sense that a property that has been set will be forgotten again in the next function call. There is nothing magic about calling a function in `main` vs a method called from it.

**Comment by ekremparlak** [comment]
I tried to reproduce it but this time there was no problem. Maybe i was using the init().

**Comment by andydotxyz** [comment]
It does seem like this is due to the app being created inside `init()` instead of using the `main()` function.
I had not noticed that on the original code and should have called it out immediately, sorry.
