### ISSUE TITLE
CanvasObject not drawn after call to Show() in goroutine if Hide() was called before ShowAndRun()

### ISSUE THREAD

**Issue by seternate** [fyne-io/fyne#4494]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If any CanvasObject is hidden before the EventLoop started (aka ShowAndRun() called) a call to Show() of the CanvasObject from another gorountine does not show the CanvasObject. It will not be drawn to the screen until any update is done like a resize or any other event (e.g. hovering a button on the UI). After that the CanvasObject which was Show() called on is drawn to the screen.

### How to reproduce
First way:
1. Execute the example code
2. Wait for 2 seconds so that Show() was called (Button is not drawn)
3. Resize the window and the Button pops up

Second way:
1. Execute the example code
2. Wait Wait for 2 seconds so that Show() was called (Button is not drawn)
3. Hover the Button that is present and the other Button pops up

### Screenshots

Before resizing the window / hovering the other Button
![grafik](https://github.com/fyne-io/fyne/assets/29413619/5ed1dde9-0685-4f76-94d9-1e811486b789)

After resizing the window / hovering the other Button
![grafik](https://github.com/fyne-io/fyne/assets/29413619/e5b61878-a4ef-4f12-9582-dfb572b07a56)

### Example code

```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	window := app.NewWindow("test")
	window.Resize(fyne.NewSize(250, 100))
	button := widget.NewButton("SHOW ME", nil)
	button.Hide()
	go func() {
		time.Sleep(2 * time.Second)
		fmt.Println("SHOW BUTTON")
		button.Show()
	}()
	button1 := widget.NewButton("SHOW HIS BROTHER", nil)
	window.SetContent(container.NewVBox(button, button1))
	window.ShowAndRun()
}
```

### Fyne version

v2.4.3

### Go compiler version

1.21.4

### Operating system and version

Windows 10

**Comment by Jacalz** [comment]
The version `v2.3.5` is many months old at this point. Please update to the latest release `v2.4.3` and see if the issue still happens. We do not have long term support of `v2.3.x`.

**Comment by seternate** [comment]
Updated to `v2.4.3` with the same behaviour. Also updated the reported fyne version above.

**Comment by Jacalz** [comment]
Thanks for checking. I am back at my computer now and I think I can replicate something similar. Seems to updated once the mouse is moved into the window?

**Comment by Jacalz** [comment]
Hmm. The issue might be button specific. I doubt that the goroutine has anything to do with the issue

**Comment by seternate** [comment]
Yeah I at first thought the same, but if you remove the 2nd button it does not update as well (at least if I try it). I initially encountered that problem by writting a custom widget and found the same behaviour with the button. Did not check every other build in widget so far, but for the Entry it is the same behaviour.

```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	window := app.NewWindow("test")
	window.Resize(fyne.NewSize(250, 100))
	entry := widget.NewEntry()
	entry.Hide()
	go func() {
		time.Sleep(2 * time.Second)
		fmt.Println("SHOW")
		entry.Show()
	}()
	window.SetContent(container.NewVBox(entry))
	window.ShowAndRun()
}
```

**Comment by seternate** [comment]
I found a programatic work around to this. If you resize the parent object after calling Show() it will be updated. But more than that I was not able to find out / debug, because I miss a good junk of internal knowledge.

```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	app := app.New()
	window := app.NewWindow("test")
	window.Resize(fyne.NewSize(250, 100))
	entry := widget.NewEntry()
	entry.Hide()
	go func() {
		time.Sleep(2 * time.Second)
		fmt.Println("SHOW")
		entry.Show()
		window.Resize(window.Canvas().Size().Add(fyne.NewPos(1, 1)))
	}()
	window.SetContent(container.NewVBox(entry))
	window.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Instead of resize try refreshing the container...
Not sure if that is a fix or a workaround though! If you add or remove in a container you certainly need to refresh it.

**Comment by seternate** [comment]
This worked in this case. The problem is than solved. And with that knowledge I was able to get the desired behaviour in my custom wigdet (not a very clean solution since I guess I misuse a widget for something a container should do). Anyway thanks for your input have a good New Year! ❤️ 🎆
