### ISSUE TITLE
fyne breaks with latest github.com/go-text/typesetting

### ISSUE THREAD

**Issue by ingothierack** [fyne-io/fyne#4520]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If I upgrade all dependencies in my fyne project by `go get -u ./...` it pulls in an incompatible version of `github.com/go-text/typesetting` 

go: upgraded github.com/go-text/typesetting v0.0.0-20230616162802-9c17dd34aa4a => v0.1.0

../../../go/pkg/mod/fyne.io/fyne/v2@v2.4.3/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)

They renamed the LineHeight() function to LineThickness() at some point in december like a lot of other stuff.

### How to reproduce

1. create a new fyne project
2. upgrade all dependencies by `go get -u ./...`
3. go run
4. Error
 ```# fyne.io/fyne/v2/internal/painter
../../../go/pkg/mod/fyne.io/fyne/v2@v2.4.3/internal/painter/font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)
```

### Example code

no code as it is a dependency problem

### Fyne version

2.4.3

### Go compiler version

1.21.5

### Operating system and version

macOS 14.2.1

**Comment by Jacalz** [comment]
Duplicate of #4441, #4443, and #4468.

That we can’t compile with a version that we don’t officially support is not a bug in Fyne. My advice is to not blindly update transitive dependencies in your Go modules. Unless you know exactly what has changed and that there are no subtle changes that might introduce bugs or incorrect behaviour, let the package that imports a specific package decide when to update that package.

I.e. never run a bare `go get -u`. If you must update transitive dependencies (for things like security issues), do so on a per package level and not for the whole module.
