### ISSUE TITLE
Allow apps to block screen locking/screensaver

### ISSUE THREAD

**Issue by mbaklor** [fyne-io/fyne#4534]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I was thinking of building a mobile monitoring app, and wanted the screen to remain on while the app is running.

I looked into it and there are simple native APIs for it.

On iOS you can call
```objective-c
[[NSOperationQueue mainQueue] addOperationWithBlock:^ {
    [UIApplication sharedApplication].idleTimerDisabled = YES;
}];
```
(Thanks Andy for finding this, I only found the Swift API)

On Android it's split into two options, either keep screen on or keep CPU running, not entirely sure we need the latter and the former doesn't require permissions:
```java
public class MainActivity extends Activity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
  }
}
```
https://developer.android.com/develop/background-work/background-tasks/scheduling/wakelock
It looks like there's also a C version of this code but I could only find mention of it and not the API itself.

### Describe the solution you'd like to see.

I think probably just add to the mobile driver API a method that calls the native APIs, preferably something that can be set and reset, so you can keep screen on for specific long lasting tasks and let it lock otherwise

**Comment by Jacalz** [comment]
Why should it be mobile specific? I think something similar would be very useful for some kinds of applications on desktop as well

**Comment by mbaklor** [comment]
Oh I guess I didn't think about it, is screen lock blocking an api that exists on desktop? Most of my PCs I use without auto locking and auto screen dimming so I really just didn't think of it. I'll give a looksee tomorrow if these features exist on desktops and how

**Comment by Jacalz** [comment]
Any video player is usually a good example of inhibiting the screen from sleeping/locking :)

**Comment by mbaklor** [comment]
Okay, looks like mac is the same is ios, so that's easy enough.

Linux gives `XScreenSaverSuspend(display, bool)` from here: https://linux.die.net/man/3/xscreensaversuspend

Windows has `SetThreadExecutionState(flags)` from here: https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate

**Comment by Jacalz** [comment]
Cool. Thanks for looking up support. Linux is probably not that simple though. We need a solution that works on both X11 and on Wayland but it's probably not a huge problem. I think the XDG Portal API might have something for it

**Comment by mbaklor** [comment]
Okay took a little finding (their docs are messy imo) but looks like the XDG portal equivalent is `org.freedesktop.ScreenSaver.Inhibit`
https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Inhibit

**Comment by andydotxyz** [comment]
iOS and Android are on that PR :)

**Comment by andydotxyz** [comment]
Desktop support now added too, this will be in v2.5.0
