### ISSUE TITLE
fyne Dependency library error

### ISSUE THREAD

**Issue by QinYinSafe** [fyne-io/fyne#4542]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I used it today, I found that it could not be compiled, and it prompted /home/qin/go/pkg/mod/fyne.io/fyne/v2@v2.4.3/internal/painter/font.go:209:65: out. LineBounds.LineHeight undefined (type shaping. Bounds has no field or method LineHeight)
, I used go get -u fyne.io/fyne/v2@v2.4.2 to lower the version, but it still didn't work, my system is deepin

### How to reproduce

not

### Screenshots

![微信图片_20240116111513](https://github.com/fyne-io/fyne/assets/101846895/11cb9b39-d891-4b14-a91b-b4589b515466)

### Example code

not

### Fyne version

2.4.3

### Go compiler version

1.21

### Operating system and version

linux deepin20.9

### Additional Information

not

**Comment by Jacalz** [comment]
Duplicate of https://github.com/fyne-io/fyne/issues/4468

**Comment by andydotxyz** [comment]
Just to comment a little further on this - the "don't update all dependencies with -u" is an opinion passed down from the go-text project as well. As part of the collaboration we want to find a way to make it smoother and I believe that we can avoid these problems from our next release. Please bear with us whilst we manage to hide the fact we are using "pre v1" dependencies within our internal code.
