### ISSUE TITLE
can not Input Chinese characters

### ISSUE THREAD

**Issue by terry2010** [fyne-io/fyne#4544]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Latest demo code: The Fyne demo currently can not inputting Chinese characters in forms

### How to reproduce

1. run latest fyne_demo 
2. click widgets->form
3. Input Chinese characters

ps :  could use microsoft input or [qq pinyin ](https://qq.pinyin.cn)

### Screenshots

![图片](https://github.com/fyne-io/fyne/assets/1849037/26428ab1-b620-43e3-a0d6-18a56c6f90c1)

### Example code

just use latest demo 

### Fyne version

latest

### Go compiler version

1.20

### Operating system and version

windows 10

**Comment by andydotxyz** [comment]
Isn't this a duplicate of #2777 

Also, the default font does not support Chinese (and other script) languages, you will need to use a custom theme or FYNE_FONT to specify the right font file until we address that in v2.5.0

**Comment by terry2010** [comment]
> Isn't this a duplicate of #2777
> 
> Also, the default font does not support Chinese (and other script) languages, you will need to use a custom theme or FYNE_FONT to specify the right font file until we address that in v2.5.0

Based on the information provided in the reference link, I attempted the approach of manually specifying the font in the asker's code, which resolved the issue.

`	
err := os.Setenv("FYNE_FONT", "C:\\Windows\\Fonts\\STSONG.TTF")
	if err != nil {
		return
	}
`
