### ISSUE TITLE
Web target missing multiple window support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4556]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Web driver missing multiple windows support.
Probably should be implemented like mobile as a full size stack.

### How to reproduce

Multiple windows in web build

### Example code

App.NewWindow(“2”).Show()

### Fyne version

2.4.3

### Go compiler version

1.21

### Operating system and version

Web

**Comment by dweymouth** [comment]
I haven't even played with Fyne mobile, but I would think multiple windows on web should be new browser tabs, though open to suggestions

**Comment by Jacalz** [comment]
I’m no expert but multiple windows might be hard to achieve, I would think. We’d have to start a new window and launch the WASM executable there again (with all the state set up for the new window)?

**Comment by andydotxyz** [comment]
Thanks. I did search but could not find that for some reason
