### ISSUE TITLE
Web target missing storage and preferences support

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4557]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Preferences and storage docs not saved.
We could build it just as LocalStorage as a first pass.

### How to reproduce

Use preferences or storage on a web target

### Example code

various

### Fyne version

2.4.3

### Go compiler version

1.21

### Operating system and version

Web

**Comment by Jacalz** [comment]
Partially a duplicate of https://github.com/fyne-io/fyne/issues/2734?

**Comment by andydotxyz** [comment]
Thanks for that. Searching failed me. Noted preferences in the original ticket
