### ISSUE TITLE
macOS: move window to current desktop

### ISSUE THREAD

**Issue by flowchartsman** [fyne-io/fyne#4563]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I'm working on an application that is primarily systray-based, but includes the option to pop up a window to view logs. To avoid killing the app, I don't close this window, but instead just hide and show it. One thing I've noticed however is that the window always remembers its position and originating desktop, so that, if I switch desktops and show the window again, it jumps back to the desktop the window was initially opened on.

This seems like the correct default behavior for most apps (at least on minimize), but for systray applications there is kind of this expectation that windows are ephemeral and sort of follow you around. Also, hide and show aren't exactly minimize either, so it's  so it's tough to say. It might be nice to have the option to pull a window into the current desktop on show. It can be worked around by moving the window while it's visible, but this is a bit of a pain. Note: This application has so far been developed on macOS, so I don't know if a similar analog exists on the other platforms or not (haven't had the chance to test yet).

There may be another technique I could be using to do this, but I wasn't able to find any good guidance on it in the docs, presumably because this sort of application isn't that common.

### Is it possible to construct a solution with the existing API?

I'm not sure. I wasn't able to find any clear answers, and the API for windows at least includes no methods that I could find for positioning.

### Describe the solution you'd like to see.

It might be nice to have the option to pull a window into the current desktop on show, perhaps as a variadic option to the call to show. It's obviously not the default, so it should have a small blast radius. Of course, there may be a better solution I'm just not aware of.

**Comment by andydotxyz** [comment]
Existing windows will remember the position - that seems correct.
So to create a fresh window each time you can allow the original one to be closed.

Like the discussion about manually moving windows , some OS will not allow apps to move their content between desktops outside of the window controls.

**Comment by flowchartsman** [comment]
> So to create a fresh window each time you can allow the original one to be closed.
Yeah, that seems fair. Probably overthinking this. Closing.
