### ISSUE TITLE
Implement 	SetDisableScreenBlanking(bool) for desktop 

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4567]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

SetDisableScreenBlanking(bool) was added mobile only for first pass

### Describe the solution you'd like to see.

support all platforms

**Comment by dweymouth** [comment]
This might actually be a more complex API on desktop. It seems on MacOS at least, you can either disable the display from shutting off entirely (which would be desired in eg a movie player), or disable the system from sleeping but allowing the display to turn off (which would be useful for eg. a music player). Perhaps SetDisableScreenBlanking should be moved to the mobile driver to allow a more complex three-state API for desktop, if it is possible for other OSes as well.

https://developer.apple.com/library/archive/qa/qa1340/_index.html

**Comment by andydotxyz** [comment]
That is a good point. But conceptually isn't the screen going off and the system sleeping separate concerns? I.e. disabling the screen off is universal but disabling suspend/sleep is desktop specific?

**Comment by dweymouth** [comment]
Also a good point. Hopefully it is possible to control the 2 independently on all desktop platforms. Looks like on Mac it probably is

**Comment by andydotxyz** [comment]
This was resolved :)
