### ISSUE TITLE
image rendering tests are fragile

### ISSUE THREAD

**Issue by josharian** [fyne-io/fyne#4573]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Run `go test ./...`. I get multiple test failures around rendering images not matching perfectly. The diffs appear quite small.

Example:

```
       	           	--- Expected
        	           	+++ Actual
        	           	@@ -4251,3 +4251,3 @@
        	           	 00010990  ff fd fd ff ff ff ff ff  f2 c0 c0 ff c8 01 01 ff  |................|
        	           	- 000109a0  c8 00 00 ff d4 35 35 ff  ff ff ff ff ff ff ff ff  |.....55.........|
        	           	+ 000109a0  c8 00 00 ff d4 36 36 ff  ff ff ff ff ff ff ff ff  |.....66.........|
        	           	 000109b0  ff ff ff ff ff fd fd ff  ff ff ff ff cd 17 17 ff  |................|
        	Test:       	TestDocTabs_ApplyTheme
        	Messages:   	Image did not match master. Actual image written to file:///Users/josh/x/fyne/container/testdata/failed/doctabs/desktop/single_custom_theme.png.
FAIL
FAIL	fyne.io/fyne/v2/container	0.789s
```

### How to reproduce

See above.

### Example code

Again, see above.

### Fyne version

caf50f6407d7f8a5abc91064338ce9bc3b1820bb

### Go compiler version

1.21.6

### Operating system and version

macOS Sonoma

### Additional Information

How would you like to approach fixing this? Do you want to allow some tolerance in pixel values? Or have multiple allowed images it can match?

**Comment by andydotxyz** [comment]
It's not fragile in the traditional sense - the issue here is that M1/2 chips output the images slightly differently to all other CPUs. Any hints appreciated as this is bugging me too!

**Comment by dweymouth** [comment]
@josharian is this fully resolved by your PR?

**Comment by josharian** [comment]
Yep, thanks!
