### ISSUE TITLE
crash on develop branch when theme is set

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#459]
fyne crashes on develop branch if theme is changed
https://play.golang.com/p/dnhRaAOIrb8

**Comment by andydotxyz** [comment]
I cannot repicate this please confirm fyne version (mod or git SHA) and a crash trace.

**Comment by metaclips** [comment]
crash log https://bpaste.net/show/cFt_
version on go.mod v1.0.2-0.20190924085827-001e29b51344 
commit 001e29b

**Comment by andydotxyz** [comment]
Thanks.
Looks like this is a mac specific issue, unless someone else can look this will have to wait until next week as I don't have access to one this week.

**Comment by andydotxyz** [comment]
Resolved. There was an issue where the settings re-publish was causing canvases to respect the "0" scale value instead of realising that was just the "unset" value..!

**Comment by metaclips** [comment]
Thanks.
