### ISSUE TITLE
Allow application to set default view (list/grid) of file dialog before showing it

### ISSUE THREAD

**Issue by maruu** [fyne-io/fyne#4595]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I think the issue has already been described here: https://github.com/fyne-io/fyne/issues/2165
I essentially have the same pains, but instead of having to click on the list-view toggle button all of the time, I would like to show the dialogs with that view by default.

### Is it possible to construct a solution with the existing API?

It might be able to get a reference to the button, as is done in the tests, but I would prefer a more clear API.
https://github.com/fyne-io/fyne/pull/2251/files#diff-3144205fac6ab76f332735320fee204ddb6963bcc76a40684806537d5a999534R441

### Describe the solution you'd like to see.

When creating a dialog, like `dialog.NewFileOpen()` I would propose to have a method on the returned object like `SetDefaultView()` which lets me select whether to use the `Grid` or `List` view. I would expect that this is set before the `Show()` method is called.

With some help from you (i.e. drafting the solution together), I would be happy to help implement it.

**Comment by andydotxyz** [comment]
It doesn't need to be SetDefaultView, just SetView would work.
However the latest version remembers your preference, is that not sufficient?

**Comment by maruu** [comment]
I would prefer if I could already provide the appropriate view for my usecase from the beginning, as the current default view (grid) currently is a problem for my users. Telling them how they can change it would require an additional documentation step, which is why I would prefer that the dialog is opened with the list view already from the beginning.

If you agree that this could be a useful feature I can look into the implementation, if its fine for you.

**Comment by andydotxyz** [comment]
I'm curious to understand why the grid view is a problem, but it seems like you have a real use-case there.

**Comment by maruu** [comment]
The filenames my users are using are quite long (30+ characters). 
In my experience, the grid view only allows to show a short substring of the filename. If I understand it correctly, this was also the initial reason to implement the list view (as described here: https://github.com/fyne-io/fyne/issues/2165)
As the filenames all start with the same characters, and are only distinguished by the last few characters, using the grid view it is difficult to distinguish between the different files. My users reported that with the list view it is easier for them, which is why I would like to set this as the default.

**Comment by andydotxyz** [comment]
Thanks for your work @maruu this is now on develop branch ready for v2.5.0
