### ISSUE TITLE
fyne doesn't hide widgets on start

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#460]
fyne does not hide widgets when set to hidden before window is set on develop branch https://play.golang.com/p/1L9xbTy3ffm

**Comment by andydotxyz** [comment]
I cannot replicate this issue with latest develop branch. Hidden items are hidden when running that code. There was a bug whereby theme was not correctly applied, this is now fixed.

Please update and try again. If it still occurs then can you confirm the version (mod file or git SHA) of Fyne you experience it with and a screenshot?

**Comment by metaclips** [comment]
Yes, works fine now, thanks.
