### ISSUE TITLE
Flashes appear during writing of images to a canvas

### ISSUE THREAD

**Issue by bob-anderson-ok** [fyne-io/fyne#4611]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

My "video player" works well, but at random times, flashes very briefly white. I tried disabling GC around the image updates. That did not help.

I tried runtime.LockOSThread() around the image updates - that did not help.

I don't have a short code snip to demo with, but provide a video in hopes that the problem is well known. I am a new, but happy, Fyne user, and so possess a great depth of ignorance.

### How to reproduce

Watch video

### Screenshots

https://github.com/fyne-io/fyne/assets/5105423/a1727f8b-16e1-4d43-b6e3-b3756d7a85ce

### Example code

I hope the video will be enough.

### Fyne version

fyne.io/fyne/v2 v2.4.3

### Go compiler version

go 1.21

### Operating system and version

Win11 Pro

**Comment by Jacalz** [comment]
> I hope the video will be enough.

No. Please always add example code so we can replicate the issue.

**Comment by andydotxyz** [comment]
It is possible that there is a delay in painting so when you ask for the image to display it does not happen immediately.
Are you by any chance writing the image to be white and reusing it?

Important note is that when you call Refresh it is not actually painting to canvas, it is queueing the change to be reflected in next redraw - which will happen asynchronously.

**Comment by bob-anderson-ok** [comment]
andydotxyz:

I read a file and then write the content to the image. I do not explictly Refresh although I have done so as a test, but the flashes remained.

Jaclz:

I'll put together a demo package - all the code, plus a file to 'play'. Do I just drop that in this box?

**Comment by bob-anderson-ok** [comment]
[demo-fits-folder.zip](https://github.com/fyne-io/fyne/files/14167329/demo-fits-folder.zip)
[main.zip](https://github.com/fyne-io/fyne/files/14167337/main.zip)

**Comment by bob-anderson-ok** [comment]
I changed the theme to dark and now it flashes black. With white theme it flashes white.

**Comment by bob-anderson-ok** [comment]
I was trying to build a simple demo of the flashing. Now I can't use Fyne at all because of the above error. I do not know enough to be able to rollback to something that does work.

**Comment by bob-anderson-ok** [comment]
I have built a simple demo that repeatedly shows the same image using the same mechanisms that are in my "video player".

It does not "flash", so I'm closing this thread.

I got Fyne to work again in my demo program by NOT accepting any of the updates shown to be available in go.mod

I'm new to Golang and probably haven't learned that updates come with risks. Plus, there's the old maxim: If it's not broken, don't fix it. I should have followed it, but the presence of references to image in two of the updates seduced me.

**Comment by andydotxyz** [comment]
> I went to go.mod and updated all available modules as image was mentioned in two of them.  Sadly, now I get:
> 
> 
> 
> # fyne.io/fyne/v2/internal/painter
> 
> ..\pkg\mod\fyne.io\fyne\v2@v2.4.3\internal\painter\font.go:209:65: out.LineBounds.LineHeight undefined (type shaping.Bounds has no field or method LineHeight)
> 
> 
> 
> Where do I go from here?
> 
> 

You can always upgrade Fyne safely but it looks like you upgraded *all* dependencies and sadly one library we use pushed a breaking change. 

In the future you can do just a single library upgrade like "go get fyne.io/fyne/v2@latest" to avoid this.

We are preparing an update to fyne that hides the go-text breakage but I've been too busy to release it the last week sorry.

**Comment by bob-anderson-ok** [comment]
Thanks for that advice about updates.

I believe that i have found the cause of the ‘flashing’ sort of.

I was reading the images from the file-system on demand. So to show an
image, a file was opened, read, and then closed. I have changed to reading
all images into a slice once when a folder of images is selected and
displaying them from there thereafter Now no flashing. So, best guess is
the file system activity somehow interacted with Fyne canvas operations,
maybe just grabbing some time at a bad time. Just a guess.

Bob

**Comment by andydotxyz** [comment]
Ah. File operations are slow and expensive compared to the graphical operations, so perhaps it was blanking the image when load started and what you were seeing was the delay in load time.
You workaround seems sensible, though you may need to move that to a worker goroutine for larger directories.
