### ISSUE TITLE
RichText swallowing whitespace after Markdown links

### ISSUE THREAD

**Issue by sdassow** [fyne-io/fyne#4613]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Spaces and linebreaks following a markdown link in a RichText widget get swallowed.

### How to reproduce

1. Run example code
2. See missing whitespace after link

### Screenshots

Missing space after link:
![fyne-richtext-url-squeeze](https://github.com/fyne-io/fyne/assets/70379952/339f2968-2ef2-4565-a0a6-978caffc96c9)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

var md = `# headline for a wide window

[https://docs.fyne.io/started/hello](https://docs.fyne.io/started/hello)

foo

bar
`

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	rt := widget.NewRichTextFromMarkdown(md)

	w.SetContent(rt)
	w.ShowAndRun()
}
```

### Fyne version

2.4.3

### Go compiler version

1.21.1

### Operating system and version

OpenBSD 7.4

**Comment by dweymouth** [comment]
Can you test on develop? There was a bug (#3528) that is fixed on develop for the next release, at least for `widget.Hyperlink` but I actually don't remember if it fixed it in RichText as well. The swallowing spaces issue may be a new one though.

**Comment by sdassow** [comment]
Turns out those are two issues after all, my bad. The one about the link is indeed fixed in develop.
Going to change the description so that it's only about swallowing the spaces.

**Comment by codesoap** [comment]
I've just encountered a similar issue and after some investigation I think there is a more general problem. There is special logic in the `addTextToSegment` function, which adds spaces between text segments. This code does not consider other inline elements, like emphasis, strong text and links.

# Demo
```go
package main

import "fyne.io/fyne/v2/app"
import "fyne.io/fyne/v2/widget"

func main() {
        a := app.New()
        w := a.NewWindow("test")
        r := widget.NewRichTextFromMarkdown(`foo
[bar](https://bar.com)
baz.

foo
*emph*
baz

foo
**strong**
baz

[split
link](https://bar.baz)

This works,
though.`)
        w.SetContent(r)
        w.ShowAndRun()
}
```
Currently produces this (the "split link" example may also show another bug):
![newline](https://github.com/fyne-io/fyne/assets/42150522/0a73b255-6838-4505-b51b-a2a10233c9f4)

# Tests
I have prepared a fix for the missing spaces around links, but now that I see the more general problem, I'm not sure this fix is the right way. Maybe a deeper change in the markdown parsing code is required (especially for the split link problem). However, I can already contribute some tests for `widget/markdown_test.go`:

```go
func TestRichTextMarkdown_NewlinesAroundEmphasis(t *testing.T) {
	r := NewRichTextFromMarkdown("foo\n*bar*\nbaz")
	assert.Equal(t, "foo bar baz", r.String())
}

func TestRichTextMarkdown_NewlinesAroundStrong(t *testing.T) {
	r := NewRichTextFromMarkdown("foo\n**bar**\nbaz")
	assert.Equal(t, "foo bar baz", r.String())
}

func TestRichTextMarkdown_NewlinesAroundHyperlink(t *testing.T) {
	r := NewRichTextFromMarkdown("foo\n[bar](https://fyne.io/)\nbaz")
	assert.Equal(t, "foo bar baz", r.String())
}

func TestRichTextMarkdown_NewlineInHyperlink(t *testing.T) {
	r := NewRichTextFromMarkdown("[foo\nbar](https://fyne.io/)")
	assert.Equal(t, "foo bar", r.String())
}
```

**Comment by andydotxyz** [comment]
Looks like you're on to something here thanks.
I wonder if the "split link" could be either an issue with the parser we use, or maybe not allowed in the spec (not sure).

**Comment by codesoap** [comment]
@andydotxyz FYI: I've started looking into fixing this (including the "split link"). Just a heads up, so that we don't do the same work in parallel by accident.
