### ISSUE TITLE
Can't seem change the size ScrolledContainer

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#462]
I have a label that I fill with a lot of content, but when having it in a scrolled container, it just keeps being one row thick. Even with a lot of line of text inside the label. Resizing both the label within the container and the container itself doesn't seem to change the size.

![image](https://user-images.githubusercontent.com/25466657/65450533-9c68dc80-de3d-11e9-908e-976c107a6f60.png)

How it looks:
![image](https://user-images.githubusercontent.com/25466657/65450554-ac80bc00-de3d-11e9-913a-299397a3b69d.png)

**Comment by metaclips** [comment]
here you go https://play.golang.com/p/Z1Gzau9UfHa

**Comment by andydotxyz** [comment]
VBox collapses vertical sizes to their min, whilst stretching the width. This is working as designed. Calling Resize on an object that is managed by a parent will have no effect (I think this is in the godoc). You should use a layout that expands contents to fill the space instead - I imagine a BorderLayout for your example.

**Comment by Jacalz** [comment]
Thanks for telling me how it should be done, really couldn’t figure this out my self.

**Comment by dkotik** [comment]
I had a really hard time figuring this out as well until I found this thread. Update documentation to make this clear? I can PR, if needed.

**Comment by andydotxyz** [comment]
Which documentation were you following? I know that layouts need more documentation but I don't know where best to place it :).
PRs are always appreciated!
