### ISSUE TITLE
Calling SetContent from Window OnDropped can freeze application

### ISSUE THREAD

**Issue by codesoap** [fyne-io/fyne#4624]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have added a `SetOnDropped` handler to the main window of my application. If the handler just does something trivial, like printing to stdout, everything works as expected. If, however, the handler calls `SetContent` on the window, the `SetContent` is run and then the application freezes forever.

### How to reproduce

I can create the problem by running the test program and dropping a file into the application window.

### Example code

```go
package main

import "fyne.io/fyne/v2"
import "fyne.io/fyne/v2/app"
import "fyne.io/fyne/v2/widget"

func main() {
	a := app.New()
	w := a.NewWindow("test")
	w.SetOnDropped(func(pos fyne.Position, uris []fyne.URI) {
		w.SetContent(widget.NewLabel("File dropped"))
	})
	w.ShowAndRun()
}
```

### Fyne version

2.4.3

### Go compiler version

1.22.0

### Operating system and version

MX Linux, I believe version 21; it's basically Debian

**Comment by codesoap** [comment]
While searching for existing code that uses `SetOnDropped`, I found this: https://github.com/metal3d/fyne-streamer/blob/8800be35603ad89a6599e6a09152a988655e828a/examples/blender-peertube/main.go#L111

It looks like someone else already found the bug and also found a workaround. This works:
```go
package main

import "fyne.io/fyne/v2"
import "fyne.io/fyne/v2/app"
import "fyne.io/fyne/v2/widget"

func main() {
	a := app.New()
	w := a.NewWindow("test")
	w.SetOnDropped(func(pos fyne.Position, uris []fyne.URI) {
		go func() { w.SetContent(widget.NewLabel("File dropped")) }()
	})
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Updated title to be freeze not crash as they are quite different

**Comment by andydotxyz** [comment]
Fixed on Develop branch, but it probably missed v2.4.4 - if we do 2.4.5 before 2.5.0 then this should be in it

**Comment by codesoap** [comment]
Awesome, thanks for the lightning fast fix, @andydotxyz ! I'll try to test it with the development branch, when I find some time.

**Comment by codesoap** [comment]
I've now tested on the `develop` branch and don't see the problem anymore. Thanks again!

**Comment by codesoap** [comment]
Milestone v2.4.5 had been set for this issue, but the fix has not been released with v2.4.5. Was this ticket missed when preparing the release or was this a conscious choice?

**Comment by andydotxyz** [comment]
You're right this was missed somehow.
It is now picked to the release branch so that whatever release comes next it will certainly be included.
Sorry about that.

**Comment by codesoap** [comment]
No worries and thanks for the quick action ❤️
