### ISSUE TITLE
button.Resize not functional

### ISSUE THREAD

**Issue by kingsley8524267** [fyne-io/fyne#4629]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I want to make the button icon become bigger like fill full the grid, but it not work

### How to reproduce

Just run the code

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	myApp := app.New()
	mainWindow := myApp.NewWindow("Blind Box Game")
	mainWindow.Resize(fyne.NewSize(600, 600))
	grid := createGrid()
	content := container.NewVBox(grid)
	mainWindow.SetContent(content)
	mainWindow.ShowAndRun()
}

func createGrid() *fyne.Container {
	grid := container.NewGridWithColumns(5)
	for i := 1; i <= 25; i++ {
		grid.Add(createGridItem())
	}
	return grid
}

func createGridItem() *fyne.Container {
	boxIcon, _ := fyne.LoadResourceFromPath("assest\\icon\\box.png")
	button := widget.NewButtonWithIcon("", boxIcon, nil)
	button.Resize(fyne.NewSize(250, 250))
	return container.New(layout.NewGridWrapLayout(fyne.NewSize(80, 80)), button)
}

```

### Fyne version

v2.4.3

### Go compiler version

go version go1.19.6 windows/amd64

### Operating system and version

windows 10

**Comment by dweymouth** [comment]
You are putting the button in a container with layout (GridWrapLayout).  The `Resize` function on button will be called by the layout to manage the size and position. If you want to manually resize widgets using `Resize`, you must put them in a container without a layout (`container.NewWithoutLayout`) and then you need to manually manage the size and position. Or more likely what you want is a different layout that allows the buttons to be bigger.

**Comment by kingsley8524267** [comment]
I want make the logo become bigger, using container.NewWithoutLayout is make the size bigger, but not the logo size
![image](https://github.com/fyne-io/fyne/assets/133184499/737b2b82-5202-4b75-a7ea-a68f2748b95e)

**Comment by dweymouth** [comment]
The size of the logo is managed by the button widget and is set to a standard size. If you need the icon to be bigger, you will need to use a custom widget, or open a feature request (not a bug report) for allowing the button icons to scale up if the button itself is larger.

**Comment by kingsley8524267** [comment]
can you give me an example of custom widget?

**Comment by andydotxyz** [comment]
https://docs.fyne.io/extend/custom-widget
