### ISSUE TITLE
Clipboard not working in web app

### ISSUE THREAD

**Issue by r00tc0d3** [fyne-io/fyne#4644]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

using Clipboard().SetContent(content) works in a desktop app but not in a web (WASM) app.

### How to reproduce

Executing code with window.Clipboard().SetContent(content) using `fyne serve` will result in not having `content` in the systems clipboard. 

### Example code

```
	if content, err := bind.Get(); err == nil {
		w.Clipboard().SetContent(content)
	}
```

### Fyne version

2.4.4

### Go compiler version

1.22 /  GOPHERJS_GOROOT=.../sdk/go1.18.10

### Operating system and version

macOS

**Comment by Jacalz** [comment]
Might have been fixed on the develop branch with https://github.com/fyne-io/fyne/pull/4348?

**Comment by andydotxyz** [comment]
Also there was missing clipboard code added recently I think (also develop) - unless the PR didn't land yet.

**Comment by r00tc0d3** [comment]
I try to upgrade to develop but I get this remark. Any idea why?
``` shell
go get github.com/fyne-io/fyne/v2@develop
go: github.com/fyne-io/fyne/v2@develop (v2.4.4-rc2.0.20240216150315-ca0e9e52caad) requires github.com/fyne-io/fyne/v2@v2.4.4-rc2.0.20240216150315-ca0e9e52caad: parsing go.mod:
        module declares its path as: fyne.io/fyne/v2
                but was required as: github.com/fyne-io/fyne/v2
```

**Comment by Jacalz** [comment]
You tried to import with the GitHub url and not `fyne.io/fyne/v2@develop`?

**Comment by r00tc0d3** [comment]
If I change the go.mod to develop I get this
``` shell
fyne package -os web
../../../../go/pkg/mod/fyne.io/fyne/v2@v2.4.4-rc2.0.20240216150315-ca0e9e52caad/app.go:84:16: undefined: atomic.Pointer
```
Desktop is working.

**Comment by Jacalz** [comment]
Is that an old version of `cmd/fyne`? Support for GopherJS has been removed. Try compiling with `-os wasm` instead.

**Comment by r00tc0d3** [comment]
Yes indeed it was an older fyne. With the new version using wasm on develop the copy is working too! Great.
I will close the issue
