### ISSUE TITLE
Add IntToFloat (and FloatToInt) in bindings

### ISSUE THREAD

**Issue by chran554** [fyne-io/fyne#4666]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When sing the Slider with bind data your are bound to use (no pun intended) binding.Float.
I have tried to use the slider bound to an int value and there were some unnecessary (?) work around to make it work.

### Is it possible to construct a solution with the existing API?

A binding.IntToFloat can be created like below:
```go
binding.StringToFloatWithFormat(binding.IntToStringWithFormat(myBoundInt, "%d.000000"), "%f")
```

```go
boundTeaPotCount := binding.NewInt()

slider := widget.NewSliderWithData(0, 130, binding.StringToFloatWithFormat(binding.IntToStringWithFormat(boundTeaPotCount, "%d.000000"), "%f"))
label := widget.NewLabelWithData(binding.IntToString(boundTeaPotCount))
```

### Describe the solution you'd like to see.

I am missing a (in convert.go, binding package):
```go
func IntToFloat(v Int) Float 
```
and maybe
```go
func FloatToInt(v Float) Int 
```
for completeness, but I am aware of the problem with design regarding rounding vs truncating of decimals.

```go
boundTeaPotCount := binding.NewInt()

slider := widget.NewSliderWithData(0, 130, binding.IntToFloat(boundTeaPotCount))
label := widget.NewLabelWithData(binding.IntToString(boundTeaPotCount))
```

**Comment by andydotxyz** [comment]
Thanks to @Dorbmon this is now done on `develop` and will be in `v2.5.0` in the coming month
