### ISSUE TITLE
Need to hook the fyne generated "Quit" menu item in fyne system tray menu

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#4670]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I need to hook the fyne generated "Quit" menu item in fyne system tray menu. I will not necessarily have ANY windows open or even created when a user selects "Quit" from the system tray menu. 

I believe there is a simple fix for this. Provide a SetCloseIntercept() type method on fyne.Desktop.App object. After all, the system tray menu is created using the fyne.Desktop.App object, not the fyne.Window object.

### Is it possible to construct a solution with the existing API?

No

### Describe the solution you'd like to see.

I believe there is a simple fix for this. Provide a SetCloseIntercept() type method on fyne.Desktop.App object. After all, the system tray menu is created using the fyne.Desktop.App object, not the fyne.Window object.

**Comment by andydotxyz** [comment]
What is the use-case for intercepting the quit request if there is no visible action in progress?

**Comment by brucealthompson** [comment]
Real applications consist of MUCH more than the UI.
________________________________

**Comment by Jacalz** [comment]
That is not a very helpful answer to an entirely reasonable question. Understanding the use case will make it easier to reason about adding functionality.

**Comment by andydotxyz** [comment]
It gives me enough information to say "just run your code after "App.Run()" has returned. You don't need any hooks to be informed when the event loop ends.

**Comment by brucealthompson** [comment]
Sat 2/24/2024 3:05 PM
It gives me enough information to say "just run your code after "App.Run()" has returned. You don't need any hooks to be informed when the event loop ends.
________________________________

**Comment by andydotxyz** [comment]
It does not relate to the Quit menu item or the system tray. It is part of the app runloop that when exited the main function will continue.

You can see it illustrated by "tidyUp()" here: https://docs.fyne.io/started/apprun

**Comment by Gys** [comment]
The Quit command (Cmd+Q) in macOS can be captured by using github.com/golang-design/hotkey
