### ISSUE TITLE
Improper utf-8 to ascii character conversion on paste from clipboard (Windows). A space follows apostrophe in text widget.

### ISSUE THREAD

**Issue by dataparency** [fyne-io/fyne#4674]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Improper utf-8 to ascii character conversion on paste from system clipboard (Windows).
In debugger (Goland) glfw.GetClipboardString seems to return improper conversion of utf-8 right single quote (0xe28099) in string for display. Shows with an extra trailing space in text field display.  Clipboard call returns content with 226, 128, 153, bytes for the apostrophe. glfw must be failing on improperly converting utf-8 bytes of the clipboard paste.

### How to reproduce

Paste clipboard text from web browser into text widget. If it has  Unicode apostrophe, it will insert a space following the apostrophe. Space not added if directly inputting ASCII apostrophe (27) say from keyboard into text. 

### Screenshots

![ScreenshotFyne](https://github.com/fyne-io/fyne/assets/57114479/012e8452-10b4-4a5e-ab8d-66c2aea7c02f)

### Example code

d.message = widget.NewMultiLineEntry()
d.message.Wrapping = fyne.TextWrapWord
d.message.SetMinRowsVisible(10)

### Fyne version

fyne.io/fyne/v2 v2.4.3

### Go compiler version

GoLand 2023.3.4 Golang 1.9.1

### Operating system and version

Windows 10 Pro Version	22H2 Installed on	‎3/‎16/‎2021 OS build	19045.4046 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by andydotxyz** [comment]
I cannot seem to replicate this. I wonder whether it relates to the OS, or the source material?
Do you see this if you copy the same quote character and surrounding content from another site, such as https://stackoverflow.com/questions/34852374/utf-8-unrecognised-character ?
