### ISSUE TITLE
How to dynamically add  entries into box in the goroutine

### ISSUE THREAD

**Issue by hundredwz** [fyne-io/fyne#468]
I have a goroutine where there is a http request, and after the response, I want to dynamically generate one entry , and add it to to parent box.
But when I just try this in the goroutine, the total window stuck and no operations work.
Could any one help me?

**Comment by andydotxyz** [comment]
This should work as you describe. Please share some code so we can help with this issue.

**Comment by hundredwz** [comment]
I fixed it. The content of thr response is too long and the the size of the entry becomes larger of my desktop.
But whn I try multiline entry, the result seems to be not so good either. Do you have any good suggestion?

**Comment by andydotxyz** [comment]
Can you be more specific about what "not so good" means?
What do you see, how does it differ from what you are trying to obtain?

**Comment by andydotxyz** [comment]
Is it possible that you are requesting text wrap like https://github.com/fyne-io/fyne/issues/332?

**Comment by hundredwz** [comment]
yes, I am requesting  text wrap. Thank you and I think I should wait to the next version. This issue can be closed now.
