### ISSUE TITLE
Please add a way to embed the `FyneApp.toml` metadata into the `go build`.

### ISSUE THREAD

**Issue by mondy** [fyne-io/fyne#4688]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Simply put, I want to disable `-H=windowsgui` and embed the `FyneApp.toml` metadata.
See #3781 and #3604.

The option to disable `-H=windowsgui` in `fyne build` was not accepted.
However, if there is a way to add metadata when `go build`, the problem is solved.

### Describe the solution you'd like to see.

Add a new subcommand to the fyne command to generate metadata source code.
The source code to set the metadata is generated at `fyne build` time.
The source code for the following section will be helpful.

https://github.com/fyne-io/fyne/blob/e332a5e47813bff1af9631cbbfe84654c0143189/cmd/fyne/internal/commands/build.go#L377C6-L377C28

Or maybe there is a better way. Is there anything?

**Comment by andydotxyz** [comment]
As you can see in the PR #4715 I realised that it should be possible to do this completely transparently so that when you run using standard Go tools we pick up metadata if present.

**Comment by andydotxyz** [comment]
From v2.5.0 this will just work by default :)
