### ISSUE TITLE
modal PopUp containing a Select closes early

### ISSUE THREAD

**Issue by seanpringle** [fyne-io/fyne#469]
According to [the docs](https://godoc.org/fyne.io/fyne/widget#PopUp) a modal PopUp can contain any "standard elements", which I take to mean any CanvasObject.

Placing a Select inside a modal PopUp causes the latter to close when the former is opened, and the options then appear alone at the top-left. Other controls, like a Button, work fine and don't automatically close the modal.

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	"log"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Popup", func() {
			widget.NewModalPopUp(
				widget.NewVBox(
					widget.NewSelect([]string{"one", "two"}, func(item string) {
						log.Println(item)
					}),
				),
				w.Canvas(),
			)
		}),
	))

	w.ShowAndRun()
}
```

Real bug, or docs bug, or "just don't do that"? :-)

 - OS: Ubuntu
 - Version 18.04
 - Go version 1.13
 - Fyne version 1.1.1

**Comment by andydotxyz** [comment]
Well found.
This is due to our simplistic implementation of overlays - the select box popup overwrites the modal popup.
This is indeed a bug but fixing it may not be trivial.

**Comment by andydotxyz** [comment]
Moving to 1.2 release sorry, this will be quite complex to fix and we are working in that area for the larger release.

**Comment by andydotxyz** [comment]
On develop for testing
