### ISSUE TITLE
Input control highlighting bug for scale = small / large

### ISSUE THREAD

**Issue by m-rei** [fyne-io/fyne#4696]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When i switch to scale = small or large, the border highlighting gets messed up around controls (the bottom line is not rendered properly)

### How to reproduce

Open fyne_demo, go to File -> Settings and change the scale to either small or large. Then go to Widgets -> Form und select the name input field.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/18645499/aeb2ba72-bfed-4198-bed4-d76a90076a63)

### Example code

There is no code.

### Fyne version

2.4.0

### Go compiler version

1.21.7

### Operating system and version

Fedora 39

**Comment by dweymouth** [comment]
Ah can you test this with the latest Fyne (2.4.4) to see if it has been resolved since 2.4.0?

**Comment by m-rei** [comment]
> Ah can you test this with the latest Fyne (2.4.4) to see if it has been resolved since 2.4.0?

Yes, seems to have been resolved. Nice!

**Comment by dweymouth** [comment]
I have seen this continue to reproduce in Fyne 2.5.x, though it is for sure a duplicate of #4475 so no need to reopen this issue
