### ISSUE TITLE
Can I package fyne app with some static resource?

### ISSUE THREAD

**Issue by jianfengye** [fyne-io/fyne#4702]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Can I package fyne app with some static resource. 
Then when i install app, the static resource will be copy in my mac book ?

### How to reproduce

I can not find any api for config for package with static resource like mp3.

### Example code

I can not find any api for config for package with static resource like mp3.

### Fyne version

2.2.3

### Go compiler version

1.18

### Operating system and version

macOs

**Comment by Jacalz** [comment]
Have a look at go:embed. It works just as well for Fyne as any other Go application: https://blog.jetbrains.com/go/2021/06/09/how-to-use-go-embed-in-go-1-16/

Also, please don’t use the issue tracker for asking questions. Use Discord, Slack or GotHub discussions.
