### ISSUE TITLE
Scrollbars for multiline input(entry) widget

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#471]
**Is it possible to construct a solution with the existing API?**
Yes, it possible now if put the widget into ScrollContainer. 

**Describe the solution you'd like**
Entry widget itself can contain scrollbars (vertical and horizontal). It can be set automatically(after resize, after text changing) or always to be shown if corresponding property is set.

**Comment by andydotxyz** [comment]
What are the benefits to adding the scrollers into the entry, above doing it the way you describe by putting the entry inside a scrollcontainer?

**Comment by Kvaz1r** [comment]
Flexibility(allow use different modes), simplicity/convenient(no need create container by myself).

**Comment by andydotxyz** [comment]
Fair enough. I think this is probably duplicate of #378 - the right way may be complex as we look at mobile as you can't really have a scrollcontainer within a scrollcontainer which might mean entry has to be limited based on it's context - any thoughts?

**Comment by Kvaz1r** [comment]
I don't think that it's duplicate. 378 describes actual unexpected (and incorrect) behaviour i.e. bug. And this issue about settings i.e. feature request. But it's not really important.

**Comment by andydotxyz** [comment]
I think the reverse was true ;) if we fix this the bug goes away.
You're probably right this is something that people will expect

**Comment by andydotxyz** [comment]
As per #338 we will need to improve pageup/down handling one scrolling is in.
Obviously changing cursor position should update scroll position so it's visible.

**Comment by andydotxyz** [comment]
It was agreed today that this should be added.
However it is a behaviour break so we're not comfortable putting it in until 2.0.
That is currently expected around July so should not be too long to wait.

**Comment by fleshin** [comment]
"Obviously changing cursor position should update scroll position so it's visible."
Is this going to happen with single line Entry as well??

**Comment by andydotxyz** [comment]
Yes, single and multi line entries are the same widget

**Comment by fleshin** [comment]
Great, anxiously waiting for this to appear on the develop branch! Thanks! :)

**Comment by andydotxyz** [comment]
On `develop` for testing
