### ISSUE TITLE
Building with fyne release does not set Metadata().Release to true

### ISSUE THREAD

**Issue by rad756** [fyne-io/fyne#4711]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Building with fyne release does not set Metadata().Release to true.
Also affects building with fyne-cross

### How to reproduce

Build the code in example with fyne release or fyne-cross and it prints out test to the terminal where it should print out prod.

### Example code

```package main

import (
	"fmt"

	"fyne.io/fyne/v2/app"
)

func main() {
	a := app.New()

	if a.Metadata().Release {
		a = app.NewWithID("com.example.app")
		fmt.Println("prod")
	} else {
		a = app.NewWithID("com.example.app.test")
		fmt.Println("test")
	}
}```

### Fyne version

2.4.4

### Go compiler version

go version go1.21.8 linux/amd64

### Operating system and version

openSUSE Tumbleweed x86_64

### Additional Information

When building with fyne build --release it prints out prod to terminal

**Comment by andydotxyz** [comment]
What is the release of the fyne command line? (`fyne --version`)

**Comment by andydotxyz** [comment]
I thought I could replicate this but I cannot. The `fyne release` command hard-codes release `bool` to `true` so I'm at a loss as to what is happening here...

**Comment by rad756** [comment]
The output of fyne --version is "fyne version v2.4.4"

I tried to run the above code with go run . && fyne build && fyne release
- All I got printed in terminal was test
- The release should print out prod, correct?

**Comment by rad756** [comment]
Maybe this is for some reason a platform specific bug, are you trying to check this only on MacOS? Or also tried it on Windows and Linux? I do not have a windows install with the dev enviornment setup right now, I could check it another day on Windows if it could help track down the core of this issue

**Comment by andydotxyz** [comment]
> I tried to run the above code with
>
>     go run .
>     fyne build (the built binary)
>     fyne release (the built binary)

The last "the built binary" is concerning me - did you clear out the previous one before testing release? What was the path to the release binary that you tested?

**Comment by rad756** [comment]
I deleted the binary that built with fyne build first. Then I ran fyne release which created an archive which I extracted and ran that extracted binary

**Comment by andydotxyz** [comment]
Can you please compile the tool locally with a log of "b.release" on line 199 of cmd/fyne/internal/commands/build.go (inside build() function). That way we can see if false is being passed in somehow. If so then a "debug.PrintStack" would help a lot.

**Comment by rad756** [comment]
Just so I understand you correctly, you would like for me to compile fyne v2.4.4 locally with the changes you requested above?

**Comment by rad756** [comment]
Locally compiled source code for fyne v2.4.4 with the addition of "log.Println(b.release)".
Compiling the above code snippet with fyne release and running the built binary, metadata is false but the log during compiling is true.

Tried to do the same with  "fyne package - os linux --release". Log during compile was true but after running the executed binary the metadata was true this time.

Doing the same with "fyne package - os linux" goes to false on both compile log and print of executed binary.

**Comment by andydotxyz** [comment]
Thanks this has been very helpful, PR inbound
