### ISSUE TITLE
Checkboxes in bound list exhibits odd behavior

### ISSUE THREAD

**Issue by BillBuilt** [fyne-io/fyne#4719]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The OnChanged callback set on a checkbox used in a NewListWithData is exhibiting odd behavior such as being called when the list changes even though it was never clicked on.

Without any user interaction, running the example code produces the following even though no boxes were clicked on:
```
2024/03/13 08:37:25 INFO updating list
2024/03/13 08:37:25 INFO checked user="User 1" on=false
```

### How to reproduce

1. run the example code and do not click on any boxes
2. watch the logs to see the callback get fired when the list updates
3. run again and click some boxes and observe the callback behavior when the list updates

### Example code

```go
package main

import (
	"log/slog"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)
func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("List Data")
	myWindow.Resize(fyne.Size{800, 600})

	type user struct {
		ID int
		Name string
		Active bool
	}
	item1 := user{
		ID:     1,
		Name:   "User 1",
		Active: true,
	}
	item2 := user{
		ID:     2,
		Name:   "User 2",
		Active: false,
	}
	item3 := user{
		ID:     3,
		Name:   "User 3",
		Active: true,
	}
	item4 := user{
		ID:     4,
		Name:   "User 4",
		Active: false,
	}
	item5 := user{
		ID:     5,
		Name:   "User 5",
		Active: false,
	}
	item6 := user{
		ID:     6,
		Name:   "User 6",
		Active: true,
	}

	l := []any{item1, item2, item3}
	l2 := []any{item4, item5, item6}

	data := binding.NewUntypedList()
	err := data.Set(l)
	if err != nil {
		panic(err)
	}

	list := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewCheck("", nil)
		},
		func(i binding.DataItem, o fyne.CanvasObject) {
			u, _ := i.(binding.Untyped).Get()
			usr := u.(user)
			chk := o.(*widget.Check)
			chk.SetText(usr.Name)
			chk.SetChecked(usr.Active)
			chk.OnChanged = func(b bool) {
				slog.Info("checked","user", usr.Name,"on", b)
			}
		},
	)

	go func() {
		time.Sleep(5*time.Second)
		slog.Info("updating list")
		data.Set(l2)
		list.Refresh()
	}()
	myWindow.SetContent(container.NewBorder(nil, nil, nil, nil, list))
	myWindow.ShowAndRun()

}
```

### Fyne version

fyne version v2.4.4

### Go compiler version

1.22.0

### Operating system and version

M2 macOS 14.4

**Comment by andydotxyz** [comment]
The `OnChanged` is firing when you call `SetChecked` I'm guessing - it does not mean the change necessarily came from a screen tap.

I would think this would be a reasonable solution:

```go
			chk.OnChanged = func(b bool) {
				if b != usr.Active {
					slog.Info("checked","user", usr.Name,"on", b)
				}
			}
```

**Comment by BillBuilt** [comment]
I changed the callback to this and ran the above exampes again:
```go
chk.OnChanged = func(b bool) {
	if b != usr.Active {
		slog.Info("changed", "user", usr.Name, "on", b)
	} else {
		slog.Info("callback fired", "user", usr.Name, "on", b)
	}
}
```

Run and do nothing:
```
2024/03/13 09:23:54 INFO updating list
2024/03/13 09:23:54 INFO changed user="User 1" on=false
```

The callback is still getting fired but User 1 was not changed and yet is reporting that it was.

**Comment by BillBuilt** [comment]
Are the checkboxes getting reused when the list is updated or are they redrawn? The above example leads me to believe they are not being recreated. User 1 is the first check box and initially is checked. When the list is redrawn, User 4 is the first check box and is NOT checked, but the callback would seem to think that it changed, even though it did not, it is (should be) a brand new checkbox. However, this behavior is not exhibited in all cases so it's a bit ambiguous in that regard once you start manually making changes to the first list.

**Comment by andydotxyz** [comment]
> The callback is still getting fired but User 1 was not changed and yet is reporting that it was.

I /think/ this relates to User 1 not being User 4, but I am a little lost.

**Comment by BillBuilt** [comment]
>I think some confusion here may be due to the fact that you're not updating a source list but replacing it with a new one.

Well the goroutine basically simulates clicking on a header or something that triggers a new list be loaded. I suppose you could think of a TODO list type thing, where you have a list of TODO lists. Click on LIST A and get the todo's for that, but then click on LIST B and it should populate with LIST B's data. LIST A and LIST B have differing amounts of data in various states, etc.

How should I load a new list if not by using `data.Set()`?

**Comment by BillBuilt** [comment]
Thank you for your time. I believe I have solved this problem by not using `Set()` to load in new data but rather replace the list widget entirely with a new call to `widget.NewListWithData()` and replacing the old list with the new one.

**Comment by andydotxyz** [comment]
I can see how that is a neat solution.
I will spend some more time thinking about this as I think there are still unexpected behaviour here - but combining binding items with replacing a parent is non-trivial so it takes thinking!

**Comment by vbobkov1968** [comment]
I can also tell similar odd behaviour takes palce with a list that uses checkboxes without binding.

**Comment by andydotxyz** [comment]
Why would you comment on a closed issue? We demonstrates that the issue was not with the List or the Check widgets - look for a similar flaw in your list item update code.
