### ISSUE TITLE
Emoji support - Not all emojis work

### ISSUE THREAD

**Issue by montovaneli** [fyne-io/fyne#4729]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Not all emojis work. For example, 🔴 works, but 🟢 does not. I haven't tested it in other environments, only on Windows 11. Also, I haven't made any font modifications.

### How to reproduce

Using a simple hello world, for example.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/25851559/13ee1451-b99d-4d71-aa72-73c0e71c9728)

### Example code

```
package main

import (
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/widget"
)

func main() {
    myApp := app.New()
    myWindow := myApp.NewWindow("Hello")

    myWindow.SetContent(widget.NewLabel("🔴🟢Hello World"))

    myWindow.ShowAndRun()
}
```

### Fyne version

2.4.4

### Go compiler version

1.22.1

### Operating system and version

Windows 11

**Comment by andydotxyz** [comment]
The font bundled currently only supports up to the Unicode emoji standard version 9.
In the next major release of Fyne it will fall back to system fonts so the missing ones, if found on your system, should start to appear.
Alternatively you can bundle a different emoji font with a custom theme.

**Comment by JaviLib** [comment]
I'd like to reopen this issue, because at least in MacOS, the default provided font is still fixed on Unicode 9, which is a 2016 standard. I think it is time to update to the latest versions of the font, which at the time I think it is Unicode 15.

**Comment by andydotxyz** [comment]
This was held back due to licensing not preference - we couldn't find a compact SVG font with permissive license that we could bundle.

In v2.5.0 it will delegate to the operating system fonts so this may go away - you could test develop branch.
