### ISSUE TITLE
Multiple select popups during background operations (crash)

### ISSUE THREAD

**Issue by stridebn** [fyne-io/fyne#4730]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When clicking multiple times on a select object while the program is performing background tasks, many Fyne reads each click and generates multiple popups below the select. This causes the program to crash.

### How to reproduce

During any background operation where the window is unresponsive, click multiple times on any select. Once the window is responsive, click on the dropdown menus to select items. Multiple popups will have generated, and a click on any but the top will crash the program.

### Example code

The following can be put in an application to demonstrate the issue.
```
    selectOptions := []string{"Option 1", "Option 2"}
    testSelect := widget.NewSelect(selectOptions, func(selected string) {
        fmt.Println("selected: ", selected)
    })
    testSelect.PlaceHolder = "Click me multiple times after clicking the button"
    waitButton := widget.NewButton("Click me!", func() {
        start := time.Now()
        // Loop until the specified duration has passed
        for time.Since(start) < (5 * time.Second) {
            // This is the busy wait part, where the loop continuously checks the time
        }
    })
```

### Fyne version

2.4.4

### Go compiler version

1.19.2

### Operating system and version

Mac 12.7.1

**Comment by andydotxyz** [comment]
> During any background operation where the window is unresponsive

The window should never be unresponsive - this points towards a potential issue outside what is reported above.

**Comment by andydotxyz** [comment]
> Multiple popups will have generated, and a click on any but the top will crash the program.

Can you please provide the crash log that is occurring in this situation?

**Comment by andydotxyz** [comment]
This is landed on develop and the release branch, it will be on v2.4.5
