### ISSUE TITLE
Question about the demo app

### ISSUE THREAD

**Issue by G5Becks** [fyne-io/fyne#474]
Hi. first of all, thanks for the great work you are doing here.

So I downloaded and ran the demo project and everything worked perfectly right out of the box. I have no idea how the api of the library works so I decided to copy-paste all of the demo app into my own app and learn by editing it to my liking.

The issue I ran into was that in my app, it renders to the wrong size for some reason. Please see the attached image below.

<img width="1237" alt="Screen Shot 2019-10-04 at 3 34 21 PM" src="https://user-images.githubusercontent.com/42525743/66234778-933d0280-e6bc-11e9-9241-a8daf0fd7ccd.png">
 
Is there any reason why that would happen? I am looking to learn about any potential gotchas to look out for when using this lib.

Thanks.

**Comment by andydotxyz** [comment]
Probably nothing you did wrong. The recent versions changed how we calculate scaling for different monitors. It’s likely you’re using 2 different versions of the library somehow.

The next point release (1.1.2) should tidy it all up and be consistent going forward

**Comment by G5Becks** [comment]
Ok, thanks.

**Comment by G5Becks** [comment]
On a side note, when is the 1.1.2 release expected to be complete?

**Comment by andydotxyz** [comment]
Hopefully in the next week

**Comment by andydotxyz** [comment]
That’s the release out now :)
