### ISSUE TITLE
Form.OnSubmit does not add Submit button to the Form

### ISSUE THREAD

**Issue by alwindoss** [fyne-io/fyne#475]
**Describe the bug**
When Form.OnSubmit = func() {} Submit should be added to the Form but Submit does not appear

**Device (please complete the following information):**
 - OS: MacOS Mojave
 - Version 10.14.6
 - Go version 1.13.1
 - Fyne version 1.1.1

**Comment by andydotxyz** [comment]
Can you please provide example code? The fyne_demo app has this working so there may be some detail that we are missing to replicate this issue...

**Comment by alwindoss** [comment]
Here's the link to the [Code](https://play.golang.org/p/0WYnFh2HKIa)

**Comment by alwindoss** [comment]
Would you need more information? Is this still an issue or will remain a question?

**Comment by andydotxyz** [comment]
Apologies no, that is clear.
If you pass the Submit parameter to a &Form{} instead of after the constructor func it will work - but this still need fixes.

I'm hoping that changes to how refresh works in 1.2 will make this easier

**Comment by alwindoss** [comment]
Would this be simple enough for a newbie to contribute?

**Comment by andydotxyz** [comment]
There is probably a simple fix - don’t commit the layout so early. But we have followed this pattern throughout so changing that might have an impact.
Possibly the more correct approach is to check the Submit and Cancel fields on each Refresh() and update the buttons appropriately

**Comment by steveoc64** [comment]
In my dev branch, I changed OnSubmit on forms to be :

form.OnSubmit(func) *form
that sets the private property onSubmit

This was to support chaining

I think doing that would fix the issue

**Comment by steveoc64** [comment]
https://github.com/fyne-io/fyne/pull/959  addresses this

**Comment by andydotxyz** [comment]
On develop for testing
