### ISSUE TITLE
Example code won't compile on windows

### ISSUE THREAD

**Issue by NRicode** [fyne-io/fyne#4750]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

get the example code from readme.md, paste it somewhere and try to compile it on windows. the build will stuck forever with high cpu usage %

### How to reproduce

-

### Screenshots

-

### Example code

-

### Fyne version

latest

### Go compiler version

latest

### Operating system and version

windows 11

### Additional Information

-

**Comment by NRicode** [comment]
pls put the 10 minute compile time on windows at the top of the page thx

**Comment by devhindo** [comment]
How did you solve that? ugh
