### ISSUE TITLE
add a X to just close dialog

### ISSUE THREAD

**Issue by aohanhongzhi** [fyne-io/fyne#4761]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

no

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

add a X to just close dialog

![img_v3_029i_a8c8c341-a437-492b-b31b-329084e747cg](https://github.com/fyne-io/fyne/assets/37319319/87fa8d37-71a2-4661-be31-09a20fa5605b)

**Comment by andydotxyz** [comment]
Dialogs are designed to be "modal input" as in you need to acknowledge or choose from the provided options.
I don't think adding a way to cancel them outside of the specified choices makes sense.

However, if you want to put extra content like this into a dialog you can - use the custom dialog and then you completely control the content.
