### ISSUE TITLE
How to create widget in expanded form? 

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#479]
MCVE:

```
package main

import (
	"log"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {

	app := app.New()
	w := app.NewWindow("MCVE")
	w.Resize(fyne.Size{800, 600})

	out := widget.NewEntry()
	out.SetText("Sample")

	BStart := widget.NewButton("Button", func() {
		log.Println("Clicked")
	})
	w.SetContent(widget.NewHBox(
		widget.NewVBox(
			widget.NewEntry(),
			BStart,
		),
		widget.NewScrollContainer(widget.NewVBox(
			out,
		))))
	w.ShowAndRun()
}
```

I want that out widget fill all available horizontal space. It's not clear for me how to do it from documentation or samples.

**Comment by andydotxyz** [comment]
The VBox and HBox widgets are shrinking their contents - their layout stretches in one dimension (width for VBox and height for HBox) and shrinks to min on the other - this is how their contents are packed.
Remove the VBox from around "out" and it should work as expected

**Comment by Kvaz1r** [comment]
good to know, thanks. But which container should be used if need packed several widgets?

**Comment by andydotxyz** [comment]
That depends on how you wish them to be laid out... Vbox and HBox are just helpers around fyne.NewContainerWithLayout - and so fyne.Container is the correct container, but you can apply various layouts (from the layout package).
