### ISSUE TITLE
Special characters missing in default font

### ISSUE THREAD

**Issue by slntopp** [fyne-io/fyne#480]
Hi, I'm trying to add some hints for users with special characters such as ⌘(cmd), ⌥(opt) and 
⎇(alt), but Fyne cannot find them and renders it so:
<img width="45" alt="Снимок экрана 2019-10-08 в 18 12 07" src="https://user-images.githubusercontent.com/32666515/66413158-25b00f80-e9f7-11e9-9e12-a36892c3cf17.png">
Printing to console works fine of course.
How could this be solved?
Thanks for your help

**Comment by andydotxyz** [comment]
Can you please share the code snippet so it can be replicated?

**Comment by andydotxyz** [comment]
P.S. Are you certain that Option and Alt keys are different? In my experience they are the same and bear the ⌥ symbol.

**Comment by slntopp** [comment]
Yes, sorry, alt and opt are one button.
I've added it as Labels before and as Entry now:
```
label := widget.NewEntry()
label.SetText("⌥+Shift+K")
label.SetReadOnly(true)
```

**Comment by andydotxyz** [comment]
Confirmed, I guess our builtin font is missing these symbols, hopefully we can resolve this by combining many font files.

**Comment by andydotxyz** [comment]
Closing as part of wider issue #598
