### ISSUE TITLE
Android packaging fails:  could not determine kind of name for C.ALooper_pollAll

### ISSUE THREAD

**Issue by TimidFuzz** [fyne-io/fyne#4806]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Command: `fyne package -os android -appID com.example.test`
Output:
```
go build -buildmode=c-shared -o /tmp/fyne-work-1596608702/lib/armeabi-v7a/libtest.so test failed: exit status 1
# fyne.io/fyne/v2/internal/driver/mobile/app
../../go/pkg/mod/fyne.io/fyne/v2@v2.4.5/internal/driver/mobile/app/android.go:520:6: could not determine kind of name for C.ALooper_pollAll
```

### How to reproduce

1. Install android ndk
2. Copy the code & install fyne
3. Export the environment variable  `export ANDROID_NDK_HOME=~/Android/Sdk/ndk/27.0.11718014/`
4. Package for android using `fyne package -os android -appID com.example.test`

### Example code

```
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("test")

	content := widget.NewLabel("Hello world!")

	w.SetContent(content)

	w.ShowAndRun()
}
```

### Fyne version

v2.4.5

### Go compiler version

1.22.0

### Operating system and version

Manjaro linux

### Additional Information

This seems to affect only the latest versions of the ndk. Using r20b fixes the issue.

**Comment by TimidFuzz** [comment]
Using an older version of the ndk solves the problem for me (i.e [r20b](https://github.com/android/ndk/wiki/Unsupported-Downloads))

**Comment by Joab0** [comment]
I solved it by going to the error (https://github.com/fyne-io/fyne/blob/d8e9fe02c9bb9e4b4c42778f5cae8ffcc43f36e2/internal/driver/mobile/app/android.go#L520) and removing the condition
![image](https://github.com/fyne-io/fyne/assets/96753252/42d1b4ca-49a3-4282-870b-d3a65a745295)

**Comment by Rstyles** [comment]
Hello. I was able to solve this issue replacing the `C.ALooper_pollAll()` with `C.ALooper_pollOnce` where the error was called at `../../go/pkg/mod/fyne.io/fyne/v2@v2.4.5/internal/driver/mobile/app/android.go:520:6:`

![image](https://github.com/fyne-io/fyne/assets/39748882/21dd87bf-5113-409d-9540-80241ea0a728)

I found the solution here https://developer.android.com/ndk/reference/group/looper

![image](https://github.com/fyne-io/fyne/assets/39748882/e3f26ef1-4426-45f5-b078-b3007a8de466)

I hope this helps

**Comment by TimidFuzz** [comment]
Suggested fix resolves the issue

**Comment by andydotxyz** [comment]
I landed that change on to develop thanks for the tip
