### ISSUE TITLE
binding.Untyped crashes when set to nil

### ISSUE THREAD

**Issue by williambrode** [fyne-io/fyne#4807]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When setting a `binding.Untyped` to nil, it crashes.  I expect this case to work - since the type I'm using is a pointer and could be nil.  The code seems to handle nil properly in several code paths, but not for `.Set()`

### How to reproduce

Set binding.Untyped to something other than nil, then set it to nil.

### Example code

```go
 a := binding.NewUntyped()
 a.Set(nil)  // this is fine since it's already set to nil
 b := 1
 a.Set(&b)
 a.Set(nil) // crashes
```

### Fyne version

2.4.4

### Go compiler version

1.19.3

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
Thanks to @Dorbmon this is now fixed on develop
