### ISSUE TITLE
Poor contrast for progressbar text

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4845]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

As initially reported in https://github.com/Jacalz/rymdport/issues/115, the `widget.ProgressBar` component has poor contrast for the text in the case where the progress bar hasn't covered the progress background yet. Both the light and dark themes exhibit poor contrast initially but good contrast later on. See screenshots below.

### How to reproduce

1. Open up `fyne_demo`.
2. Go to the `Widgets -> Progress` page.
3. Notice that the text contrast is poor initially but turns good once the progress reaches ahead of the text.

## Dark theme:

**Poor contrast for text in the dark region of the progress bar:**

![image](https://github.com/fyne-io/fyne/assets/25466657/f6fbec41-5dbb-4daa-92b1-2bb494cddb81)

**Good contrast for text in the light region of the progress bar:**

![image](https://github.com/fyne-io/fyne/assets/25466657/82f3d79a-9883-43c3-af21-8b4d0c3057a7)

## Light theme

**Poor contrast for text in the light region of the progress bar:**

![image](https://github.com/fyne-io/fyne/assets/25466657/a7af6cb5-e236-4996-88f2-3656bb045f26)

**Good contrast for text in the dark region of the progress bar:**

![image](https://github.com/fyne-io/fyne/assets/25466657/f970e01a-2e44-4dd4-a645-67ca55d7d2f5)

### Example code

See fyne_demo.

### Fyne version

v2.4.5

### Go compiler version

1.22.3

### Operating system and version

Fedora Silverblue 40

**Comment by andydotxyz** [comment]
This probably relates to #4929

**Comment by toaster** [comment]
Yes, I’ve already a fix for the progressbar in my PR queue.

**Comment by toaster** [comment]
Sneak preview:
<img width="645" alt="grafik" src="https://github.com/fyne-io/fyne/assets/73959/502c2241-7502-459d-a468-59117e8aca96">
<img width="636" alt="grafik" src="https://github.com/fyne-io/fyne/assets/73959/5a230268-ecaf-428e-bc51-d4435e27704c">

**Comment by Jacalz** [comment]
This is no longer an issue after #4956 landed.
