### ISSUE TITLE
Enhance documentation for table headers

### ISSUE THREAD

**Issue by Kukulkano** [fyne-io/fyne#4873]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I just check if fyne is able to fulfil my needs and I found that tables in documentation do not even mention headers.

I then found bug #1658 partially fixed (only tables, not tree). So headers are available in general. But I found no example or information in the documentation at https://docs.fyne.io/collection/table .

### Describe the solution you'd like to see.

I would like to see a description and example code for creating a table including headers. Maybe the headers are a separate section but at least it might be linked then.

**Comment by andydotxyz** [comment]
I guess it's covered in the api docs https://docs.fyne.io/api/v2.4/widget/table.html  but not the basic intro you linked.
Some practical example is also at https://fynelabs.com/2023/10/05/user-data-sorting-with-a-fyne-table-widget/
