### ISSUE TITLE
Entry (read only) state can support the right mouse button

### ISSUE THREAD

**Issue by piaoyunsoft** [fyne-io/fyne#488]
I hope Entry (read only) state can support double-click mouse, provide pop-up menu, select text and copy it.

example：

![4B17A90639F0623339DC6188DACADB91](https://user-images.githubusercontent.com/8001467/66793725-339eec80-ef31-11e9-8632-f66b9481414a.png)

**Comment by andydotxyz** [comment]
This is now on develop for testing
