### ISSUE TITLE
[Linux:Gnome] wrong window size after setting label.Wrapping value.

### ISSUE THREAD

**Issue by progfargo** [fyne-io/fyne#4888]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

setting label.Wrapping to fyne.TextWrapBreak results in wrong window size.

### How to reproduce

run the sample code

### Screenshots

![Screenshot from 2024-05-28 22-03-16](https://github.com/fyne-io/fyne/assets/1869476/d0af0399-048c-485a-b8aa-e1e1eb238691)

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("bakalim ne olacak")
	w.Resize(fyne.NewSize(300, 300))

	label := widget.NewLabel("what will hapen? what will hapen? what will hapen? what will hapen? what will hapen? what will hapen?")

	label.Wrapping = fyne.TextWrapBreak

	w.SetContent(label)

	w.ShowAndRun()
}

### Fyne version

v2.4.5

### Go compiler version

go version go1.22.2

### Operating system and version

Linux 5.15.0-107-generic #117-Ubuntu x86_64 GNU/Linux

**Comment by andydotxyz** [comment]
This has come up before - it seems to be specific to Gnome window manager as we ask for the window to be tall because of the initial minimal width, then figure out it can be wider so the height could be smaller.
We set the smaller minimum height but the window does not realise it.

I cannot find an original issue for this so unless anyone else can we will leave this open to track the (possible?) solution.

**Comment by pirST** [comment]
The same problem in Lubuntu 24.04 and Kubuntu 24.10. If you put "\n" after the first characters, the problem does not appear.

**Comment by andydotxyz** [comment]
> The same problem in Lubuntu 24.04 and Kubuntu 24.10. If you put "\n" after the first characters, the problem does not appear.

Instead of listing the bistro please state the window manager - that is what controls the window min size interpretation...

**Comment by pirST** [comment]
> Instead of listing the bistro please state the window manager - that is what controls the window min size interpretation...
Openbox 3.6.1 and kwin 5.1.5

**Comment by andydotxyz** [comment]
Looks like the issue #4097 covers the root cause which applies to more systems than I realised.
