### ISSUE TITLE
Draggable widget's event listener areas don't move along when a label is present

### ISSUE THREAD

**Issue by ivancho1707** [fyne-io/fyne#4892]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am trying to create an application using the Fyne framework that draws a rectangle and a label to show mouse interactions. The application works correctly when logging interactions to the console. However, **when I add a label** to display these interactions, the **dragging and tapping listener area of the rectangle does not move from its original position**, even though the rectangle itself moves.

### How to reproduce

1. The below application initializes a window with an interactive rectangle and a label. Most of the code is implementing the Draggable and Tappable interfaces for the rectangle
2. The rectangle responds to drag and tap events, updating its position and logging the events.
3. Without the label, the rectangle moves correctly, and events are logged to the console as expected.
4. With the label added, the rectangle's visual representation moves correctly, but the event listener areas (tapping and dragging) do not follow the rectangle's new position. They remain in the initial position.

## Without label (good)
![good](https://github.com/fyne-io/fyne/assets/670294/668dc315-cc3b-4eac-8264-ebd4f18da08f)

## With label (NG)
![bug](https://github.com/fyne-io/fyne/assets/670294/b714a529-f09f-41a3-a240-4c7c9c9e60cb)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
	"image/color"
	"log"
)

func main() {
	a := app.New()
	w := a.NewWindow("Events")

        // This block only adds a label
	label := widget.NewLabel("Hello Fyne!")
	content := container.New(layout.NewVBoxLayout(), label, &interactiveRect{})
	w.SetContent(content)

	//w.SetContent(&interactiveRect{}) // if I omit the above block and uncomment this line, the app does work as expected
	w.Resize(fyne.NewSize(800, 600))
	w.ShowAndRun()
}

var _ fyne.Tappable = (*interactiveRect)(nil)
var _ fyne.SecondaryTappable = (*interactiveRect)(nil)
var _ fyne.Draggable = (*interactiveRect)(nil)

type interactiveRect struct {
	widget.BaseWidget
	position fyne.Position
}

func (r *interactiveRect) CreateRenderer() fyne.WidgetRenderer {
	r.ExtendBaseWidget(r)
	return &interactiveRectRenderer{
		rect:     canvas.NewRectangle(color.NRGBA{R: 255, G: 0, B: 0, A: 255}),
		rectSize: fyne.NewSize(50, 70),
		rectPos:  &r.position,
	}
}

func (r *interactiveRect) MinSize() fyne.Size {
	r.ExtendBaseWidget(r)
	return r.BaseWidget.MinSize()
}

func (r *interactiveRect) Tapped(event *fyne.PointEvent) {
	log.Println("Tapped", event)
}

func (r *interactiveRect) TappedSecondary(event *fyne.PointEvent) {
	log.Println("TappedSecondary", event)
}

func (r *interactiveRect) Dragged(event *fyne.DragEvent) {
	r.position = fyne.NewPos(event.Position.X-25, event.Position.Y-35)
	r.Refresh()
	log.Println("Dragged", event)
}

func (r *interactiveRect) DragEnd() {
	log.Println("DragEnd")
}

var _ fyne.WidgetRenderer = (*interactiveRectRenderer)(nil)

type interactiveRectRenderer struct {
	rect     *canvas.Rectangle
	rectSize fyne.Size
	rectPos  *fyne.Position
}

func (r *interactiveRectRenderer) Destroy() {}

func (r *interactiveRectRenderer) Layout(size fyne.Size) {
	r.rect.Resize(r.rectSize)
	r.rect.Move(*r.rectPos)
}

func (r *interactiveRectRenderer) MinSize() fyne.Size {
	return r.rectSize
}

func (r *interactiveRectRenderer) Objects() []fyne.CanvasObject {
	return []fyne.CanvasObject{r.rect}
}

func (r *interactiveRectRenderer) Refresh() {
	r.rect.Move(*r.rectPos)
	r.rect.Refresh()
}
```

### Fyne version

2.4.5

### Go compiler version

go1.22.3

### Operating system and version

OSX 14.5

**Comment by Jacalz** [comment]
```go
// This block only adds a label
label := widget.NewLabel("Hello Fyne!")
content := container.New(layout.NewVBoxLayout(), label, &interactiveRect{})
```

As far as I can tell, this code is the source of your issues; it isn’t only adding a label. If you read the VBox documentation, you will see that it renders items at their vertical MinSize. Your rectangle’s MinSize is the hardcoded size of the rectangle and as such, this is the only space that the VBox layout provides for your widget. When you move it, you only move it within the space that the parent layout provides. I suppose a Border container with the label in the top position and the rectangle in the middle is what you are after.

**Comment by andydotxyz** [comment]
It's simpler than that as far as I can tell. The actual custom widget is packed into the HBox right next to the label.
The rectangle is drawn outside of this interactive area (relative to the interactive area which is not moving).

The flaw is that the "interactive rectangle" is not being moved, it's just drawing a different position. instead of moving the rectangle, move the widget. To do this the item will have to be inside "container.NewWithoutLayout" instead of a HBox.

The reason it worked before will have been because the "interactive area" filled the screen (assuming, based on description).
