### ISSUE TITLE
Pannable canvas

### ISSUE THREAD

**Issue by TimidFuzz** [fyne-io/fyne#4893]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I need the main canvas to be pannable using mouse clicks.

### Is it possible to construct a solution with the existing API?

As far as I am aware, the current API does not make this possible.

### Describe the solution you'd like to see.

A way to focus the canvas at position (x, y) outside of the window boundaries

**Comment by andydotxyz** [comment]
A container has child elements that can be positioned anywhere - positive or negative.
So you probably just want a "container.New" passing in a custom layout or "container.NewWithoutLayout" and you can manage the position of the child elements yourself.

**Comment by TimidFuzz** [comment]
Usually panning is done using a right click or middle mouse button drag. Can this be achieved using fyne?

**Comment by andydotxyz** [comment]
> Usually panning is done using a right click or middle mouse button drag. Can this be achieved using fyne?

Yes. Though you'd want to make it less "button specific" so it works on mobile too.
There is a "Draggable" abstraction already so you don't have to think about device events, though of course you can listen for specifics if you want.

**Comment by andydotxyz** [comment]
Closing as already possible
