### ISSUE TITLE
Add support for changing device orientation using mobile simulator

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#4894]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Our mobile driver supports looking up the orientation of the device and adapting the content for it. You basically need to use Android studio, XCode or have access to a real device to test this functionality. It would be very useful if we could expose a way to force-change the orientation, and make the application redraw and layout accordingly, at runtime. This would make the mobile simulator more useful for testing applications.

(This is especially useful with cool features like https://github.com/fyne-io/fyne/pull/4887 landing)

### Is it possible to construct a solution with the existing API?

Should be possible.

### Describe the solution you'd like to see.

Some way to have like a button or option to change the rotation at runtime when using the mobile simulator. I don't know quite how this would be done best. Maybe something like the tool-window that Android studio uses (not sure about having it in a separate window though) and we could then add more useful testing options into that.

**Comment by andydotxyz** [comment]
There is a simpler option whereby we assert that the "device" is horizontal if width > height when resizing the window.

**Comment by Jacalz** [comment]
That is a really cool fix. Nice idea :+1:

**Comment by andydotxyz** [comment]
It should be in already ;) let me know if it does not work in your testing...

**Comment by Jacalz** [comment]
What commit was the change in? :)

**Comment by andydotxyz** [comment]
https://github.com/fyne-io/fyne/commit/bbc307cb784c5e05312b3c584ceac7d6b522c6a1

**Comment by Jacalz** [comment]
Nice. I can indeed confirm that it is fixed :)
