### ISSUE TITLE
Feature Request: Entry responding to mouse events

### ISSUE THREAD

**Issue by J7mbo** [fyne-io/fyne#4897]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

When updating to glfw 3.4, `GLFW_MOUSE_PASSTHROUGH` allows the user to click through any element to anything that is behind it. This means that anything in the UI cannot be clicked on.

Given a transparent window background and floating set to true, one can 'overlay' a button on the screen. Given that Buttons implement `Hoverable`, one can then have passthrough set to false on mouse-in of the button, so it's then clickable, and on mouse-out set passthrough enabled again. Whilst keeping the window 'floating' set to true, this allows whatever is behind this transparent window to be worked with, except for the button which can be interacted with as well.

This cannot currently be done with `Entry`s, because they don't implement `Hoverable`.

### Is it possible to construct a solution with the existing API?

In my local fork I am able to have `Entry` implement `Hoverable` by adding the `MouseIn`, `MouseMoved` and `MouseOut` methods to `entry.go` and setting a property on `Entry`, namely `hovered` , accordingly. This is the same as `focused`, and is also exactly how `button.go` does it.

With those minor changes, I can then in userland extend the entry widget to watch for `MouseIn` and `MouseOut` events, and change the passthrough value accordingly.

### Describe the solution you'd like to see.

I would love to have the go-ahead to add the ability for an `Entry` to react to mouse events. I'd be happy to create the MR for that, but would need guidance on what tests would be required.

Additionally, it is imperative that this would not be blown up into an MR for adding `Hoverable` to everything. Only `Entry` alone, like `Button`, would be the focus of the MR.

I'd really like it if I could be supported to contribute this feature.

**Comment by andydotxyz** [comment]
It sounds like you have already forked Fyne, as transparent / floating windows are not supported in our code.

To add functionality to Entry (or any widget) you do not have to fork the project, just extend the widget as in the documentation: https://docs.fyne.io/extend/extending-widgets

**Comment by andydotxyz** [comment]
(closing as already possible in user code)
