### ISSUE TITLE
[develop - android build] error while building to android

### ISSUE THREAD

**Issue by lostdusty** [fyne-io/fyne#4907]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

![image](https://github.com/fyne-io/fyne/assets/47502554/25e9a86c-aea8-4dc6-a36a-23e89852572e)
Unsure what else to describe. Going back to v2.4.5 works

### How to reproduce

Package with `fyne package -os android/arm`

### Example code

Any simple app should trigger the bug.

### Fyne version

v2.4.6-0.20240603133300-d41f1e22dc25

### Go compiler version

1.22.3

### Operating system and version

Windows 10

### Additional Information

Android NDK version: 25.2.9519653
GCC: gcc (tdm64-1) 10.3.0

**Comment by andydotxyz** [comment]
Thanks for the report, this is now fixed.
