### ISSUE TITLE
Don't show title when mouse hover on Systray menu

### ISSUE THREAD

**Issue by xiebruce** [fyne-io/fyne#4916]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Yes,  when I move my mouse hover on Systray menu, it will show the title, which cover on the submenu(I can't see submenu)

![image](https://github.com/fyne-io/fyne/assets/13575500/5912a2e4-a30c-4000-b868-b29021fe3a0f)

### Is it possible to construct a solution with the existing API?

I don't know, I'm not familiar with it.

### Describe the solution you'd like to see.

Don't show the title by default, but provide an option to enable it in case someone need it.

**Comment by andydotxyz** [comment]
Fixed on develop and will be the default for v2.5.0 onward.
