### ISSUE TITLE
Labels clipping some text below baseline

### ISSUE THREAD

**Issue by zxzx1290** [fyne-io/fyne#4936]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have been using a custom font in my program, but it seems like some of the text is being cut off (see screenshot p alpha). I want to adjust the line height, but I can't find an option to do so.

### How to reproduce

load custom font NotoSansCJKtc-Regular.ttf

### Screenshots

![擷取](https://github.com/fyne-io/fyne/assets/11659056/2e844326-91a1-46dc-904a-d3e69b0998f8)

### Example code

```
//go:embed fonts/MicrosoftJhengHeiRegular.ttf
var NotoSansCJKtcRegular []byte

var myfont = &fyne.StaticResource{ StaticName: "NotoSansCJKtcRegular", StaticContent: NotoSansCJKtcRegular }

type theme1 struct{}

var _ fyne.Theme = (*theme1)(nil)

func (theme1) Font(s fyne.TextStyle) fyne.Resource {
    return myfont
}
```

### Fyne version

2.4.5

### Go compiler version

1.22.1

### Operating system and version

Windows 10 X64

**Comment by andydotxyz** [comment]
The minimum size for the label should be set by the font lookups.
Can you share the code which is rendering that label?

**Comment by zxzx1290** [comment]
> The minimum size for the label should be set by the font lookups. Can you share the code which is rendering that label?

`
package main

import (
	_ "embed"
    "image/color"
    "fyne.io/fyne/v2"
    "fyne.io/fyne/v2/app"
    "fyne.io/fyne/v2/container"
    "fyne.io/fyne/v2/widget"
    "fyne.io/fyne/v2/theme"
)

//go:embed fonts/NotoSansCJKtc-Regular.ttf
var NotoSansCJKtcRegular []byte

var myfont = &fyne.StaticResource{ StaticName: "NotoSansCJKtcRegular", StaticContent: NotoSansCJKtcRegular }

type theme1 struct{}

var _ fyne.Theme = (*theme1)(nil)

func (theme1) Font(s fyne.TextStyle) fyne.Resource {
    return myfont
}
func (theme1) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
    return theme.DefaultTheme().Color(n, v)
}
func (theme1) Icon(n fyne.ThemeIconName) fyne.Resource {
    return theme.DefaultTheme().Icon(n)
}
func (theme1) Size(n fyne.ThemeSizeName) float32 {
    return theme.DefaultTheme().Size(n)
}

func main() {
    a := app.New()
    a.Settings().SetTheme(&theme1{})
    w := a.NewWindow("Hello")

    hello := widget.NewLabel("Hello Fyne!你好 gggyyyjjjj")
    w.SetContent(container.NewVBox(
        hello,
        widget.NewButton("Hi!", func() {
            hello.SetText("Welcome :)")
        }),
    ))

    w.ShowAndRun()
}
`

![image](https://github.com/fyne-io/fyne/assets/11659056/8c7ed4eb-184f-4482-a383-98b73fa6a374)

**Comment by andydotxyz** [comment]
Thanks for this, clearly something internal is not measuring correctly. Can you please test with fyne `develop` version as we are preparing the next release and font rendering and measurement has changed.

**Comment by zxzx1290** [comment]
Look like the problem still exist.

![image](https://github.com/fyne-io/fyne/assets/11659056/ff062a52-585f-4d4f-8641-8f59fc2fb4a9)

**Comment by andydotxyz** [comment]
Thanks, I wonder if this could relate to the text hints for the latin characters in the Chinese font you are using?

If you are testing against develop then you should be able to remove the custom theme and it will look up system fonts for the glyphs not bundled. It is possible that by mixing the fonts in this way the baseline or height calculations will be correct. Not a fix-fix but a good bit of information for us to work with.

**Comment by zxzx1290** [comment]
Thanks, after removing the custom theme, the problem is gone.

![image](https://github.com/fyne-io/fyne/assets/11659056/601d12fc-204a-43b7-a38d-e4f2a7984d7f)

using fyne.io/fyne/v2 v2.4.6-0.20240617212519-759df6f70f7e
