### ISSUE TITLE
Font can't be displayed correctly after fyne package

### ISSUE THREAD

**Issue by xuecangqiuye** [fyne-io/fyne#4943]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have used `fyne bundle` to convert the someFont.otf into my res/fontRes.go, it works normally with `go run main.go`, but font cannot be displayed correctly after the `fyne package`.

### How to reproduce

1. Go to 'my project root directory'.
2. ` fyne bundle res/somefont.otf >> res/fontRes.go`
3. rename res/fontRes.go package name 'main' to 'res'
 ```
package res

import "fyne.io/fyne/v2"

var ResourceSourceHanSansCNRegularOtf = &fyne.StaticResource{
	StaticName: "SourceHanSansCN-Regular.otf",
	StaticContent: []byte(
```
4. create custom theme
```go
package appcomponents

import (
	"image/color"
	"myproject/res"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

type myTheme struct{}

var _ fyne.Theme = (*myTheme)(nil)

func (*myTheme) Font(s fyne.TextStyle) fyne.Resource {
	return res.ResourceSourceHanSansCNRegularOtf
}

func (*myTheme) Color(n fyne.ThemeColorName, _ fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(n, theme.VariantLight)
}
func (*myTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}
func (*myTheme) Size(n fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(n)
}

```
5. use custom theme in app. It displays correctly with `go run main.go`
```
func main() {
	
	myApp := app.New()
	myApp.Settings().SetTheme(&myTheme{})
```
6. package the app with `fyne package --icon .dkwanConfig/icon.png  -os windows`
7. open the packaged app, the font display incorrectly.

### Screenshots

![gorun](https://github.com/fyne-io/fyne/assets/39404875/54261b85-ba24-4470-a9a5-ab80da009f61)

![ext](https://github.com/fyne-io/fyne/assets/39404875/f1dab3be-5be1-4aff-b3cd-023b1117371f)

### Example code

```go
var isCN = false
func init() {
	lang := os.Getenv("LANG")
	if strings.Contains(lang, "zh_CN") {
		isCN = true
	}
	log = utils.GetLogger()
	initApp()
	authInfo = initInputs()

}

func initApp() {
	//build app
	myApp = app.NewWithID("DKGWAN")
	myApp.SetIcon(res.ActivatedIconPng)
	if isCN {
		myApp.Settings().SetTheme(&myTheme{})
	} else {
		myApp.Settings().SetTheme(theme.LightTheme())
	}
	appLifecycle(myApp)
}
```

### Fyne version

2.4.5

### Go compiler version

1.22.4

### Operating system and version

win11

**Comment by andydotxyz** [comment]
This should not be possible, as the code compiled is exactly the same.
Please try clearing all caches and deleting the packaged assets and doing it again - it sounds like something is out of date.

**Comment by xuecangqiuye** [comment]
> This should not be possible, as the code compiled is exactly the same. Please try clearing all caches and deleting the packaged assets and doing it again - it sounds like something is out of date.

Yes, you were right about this issue, I have figured out where I made the mistake.
The problem is here
```go
	lang := os.Getenv("LANG")
	if strings.Contains(lang, "zh_CN") {
		isCN = true
	}
```
'LANG' doesn't exist in windows. But it exist in mingGW, so that the font display correct when `go run`.
Thank you for your reply.
