### ISSUE TITLE
BorderLayout does not show border objects when used in an AppTab

### ISSUE THREAD

**Issue by dehaansa** [fyne-io/fyne#4958]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When adding a Button to the bottom section of a new border layout, it does not appear in the app unless I also add it to the objects... slice.

I also observed similar issues when using a border layout inside a List, the border objects were not accessible in the updateItem function. This appears to be a regression in the `container.New(layout.NewBorderLayout(...` new style vs using the `container.NewBorder(...` where the border objects are added to the layout's objects slice.

### How to reproduce

1. Create an AppTabs container
2. Add a container using a BorderLayout to the AppTabs container
3. Add an object to one of the border sections of the BorderLayout, and an object to the center section (the remaining objects... slice)

### Screenshots

<img width="802" alt="image" src="https://github.com/fyne-io/fyne/assets/563558/bd50009c-1a8e-45b8-bd25-da0e51804eee">

<img width="806" alt="image" src="https://github.com/fyne-io/fyne/assets/563558/bb78ce4f-6080-43b8-b785-f10003c97150">

### Example code

Not working appropriately:
```go
a := app.New()
w := a.NewWindow("Test App")

addResourceButton := g.defineAddResourceButton()
tabs := container.NewAppTabs(
	container.NewTabItem("Resources", container.New(layout.NewBorderLayout(
		nil,               //TOP
		addResourceButton, //BOTTOM
		nil,               //LEFT
		nil,               //RIGHT
	),
		widget.NewLabel("test label"),
	)),
)

w.SetContent(tabs)
w.Resize(fyne.NewSize(800, 0))
w.ShowAndRun()
```

Workaround:
```go
a := app.New()
w := a.NewWindow("Test App")

addResourceButton := g.defineAddResourceButton()
tabs := container.NewAppTabs(
	container.NewTabItem("Resources", container.New(layout.NewBorderLayout(
		nil,               //TOP
		addResourceButton, //BOTTOM
		nil,               //LEFT
		nil,               //RIGHT
	),
		widget.NewLabel("test label"),
		addResourceButton, // internally these are skipped by the layout but need to be here for the list item to work
	)),
)

w.SetContent(tabs)
w.Resize(fyne.NewSize(800, 0))
w.ShowAndRun()
```

### Fyne version

2.4.5

### Go compiler version

1.21.0

### Operating system and version

OSX Sonoma 14.5

**Comment by Jacalz** [comment]
> When adding a Button to the bottom section of a new border layout, it does not appear in the app unless I also add it to the objects... slice.

This is just how layouts and containers work; it is not a bug. I’m order for something to be rendered, you need to add it to the objects slice. There is no way for the layout to add objects into the container it is in, you are only telling which items go where.

Like you say, the `container.New()` function does indeed make things easier but there is no regression there.

**Comment by andydotxyz** [comment]
> This appears to be a regression in the container.New(layout.NewBorderLayout(... new style vs using the container.NewBorder(... 

You've got them the wrong way round - `container.NewBorder` is the new shortcut and recommended, for the reason you have understood above.
