### ISSUE TITLE
Notifications are not working on iOS

### ISSUE THREAD

**Issue by Gys** [fyne-io/fyne#4966]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I create a simple Fyne app only to test notifications. The app works on MacOS and Android. When I compile and install on iOS there is no notification.

The docs https://developer.apple.com/documentation/usernotifications/asking-permission-to-use-notifications  state: 

`Local and remote notifications...`

`..., you must obtain permission to use them.` 

I think the `must` is critical here. Fyne provides no mechanism to ask for permission? 

### How to reproduce

The simplest notifications app will do.

### Example code

```
func main() {
	a := app.New()
	w := a.NewWindow("Notification Example")
	btn := widget.NewButton("Show Notification", func() {
		notification := fyne.NewNotification("Notification Title", "This is the notification.")
		a.SendNotification(notification)
	})
	w.SetContent(container.NewVBox(
		widget.NewLabel("Click the button to show a notification."),
		btn,
	))
	w.ShowAndRun()
}
```

### Fyne version

2.4.5

### Go compiler version

go1.21.5 darwin/amd64

### Operating system and version

MacOS Sonoma 14.5 (Intel)

### Additional Information

iOS 17.5.1

**Comment by Jacalz** [comment]
Likely fixed on develop with https://github.com/fyne-io/fyne/commit/d6261cf3b18b754c351266895fb85dad58d124f1 already?

**Comment by andydotxyz** [comment]
Good point, thanks
