### ISSUE TITLE
Optionally allow internal callback for Hyperlink and HyperlinkSegment to handle clicks and taps internally 

### ISSUE THREAD

**Issue by rasteric** [fyne-io/fyne#4972]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Instead of doubling the efforts, it would make sense to optionally have a callback in `Hyperlink` and `HyperlinkSegment` to handle the included URL programmatically. 

There are two main use cases:

- It is sometimes useful to override defaults like in `xdg-open` on Linux, for example if the application has its own set of preferred applications, when the system-wide default is known to be inadequate for a certain target, and when the helper application is provided by the application and not commonly installed on the host system.
- Many applications require internal links that, for all intents and purposes, behave like web links but jump to different displays or objects within the application. Think of links to custom database objects, for instance. Using URLs with proprietary protocol and host scheme allows these applications to mix internal links freely with external links.

This is related to issue #1847 but not identical. While #1847 concerns the "official" platform-wide registration of URLs and is therefore much more complicated, this issue only concerns a way to handle Hyperlinks and URL dispatch programmatically. The default behavior would still be to call the default platform-specific URL dispatcher.

### Is it possible to construct a solution with the existing API?

Only with custom widgets that mirror `Hyperlink` and `HyperlinkSegment`, if I'm not mistaken (please correct me if I'm wrong).

### Describe the solution you'd like to see.

There are two very different ways to achieve the functionality.

1. Minimal modification of Hyperlink:

```
type HyperlinkActionFunc func()

Hyperlink.SetActionCallback(cb HyperlinkActionFunc)
Hyperlink.RemoveActionCallback() // optional, maybe not needed
```

2. Similar to a solution to issue #1847 but not automatically implying a platform-wide registration of the scheme.

Example API: 

```
type GlobalURIDispatchFunc func(u fyne.URI)

storage.SetGlobalURIDispatcher(dispatcher GlobalURIDispatchFunc)

```

and call this in the Hyperlink and HyperlinkSegment actions. In addition:

```
storage.DefaultOpenURI(u fyne.URI) // open the given URI by the platform's default handler
```

**Comment by andydotxyz** [comment]
I don't get this. Isn't `Hyperlink.OnTapped` sufficient for whatever use-case you are working on above?

**Comment by rasteric** [comment]
I didn't see it! I have a habit of googling for Fyne + term because the built-in search on fyne.io is not very flexible. Unfortunately, I got:

[https://docs.fyne.io/api/v2.0/widget/hyperlink.html](https://docs.fyne.io/api/v2.0/widget/hyperlink.html)

instead of

[https://docs.fyne.io/api/v2.4/widget/hyperlink.html](https://docs.fyne.io/api/v2.4/widget/hyperlink.html)

without realizing. Thanks for the reply! Yes, `OnTapped()` suffices. Issue closed.

**Comment by Jacalz** [comment]
I am personally a big fan of https://pkg.go.dev given that it contains all Go packages and gets lots of development from the Go team. If you feel that the API docs on our own site is limiting you when searching, I would suggest trying this one out instead. Specifically, you can find Hyperlink over here: https://pkg.go.dev/fyne.io/fyne/v2/widget#Hyperlink

**Comment by andydotxyz** [comment]
Recently our docs was updated to help Google prefer the unversioned (latest) page instead. It will take some time to propagate.
