### ISSUE TITLE
MacOS not asking for permission to show notifications

### ISSUE THREAD

**Issue by Gys** [fyne-io/fyne#4974]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If I create and show a notification on my Mac, it shows an `osascript` commandline created notification. Confusing, because the icon is different from my app and, more problematic, it contains an 'open' button which opens an empty 'Script editor' folder when clicked...

Looking at the code I find this a *fallback method* for showing notifications.

I did not understand why the fallback was shown because the code is explicitly first asking for permission and if allowed should show normal notifications. 

Looking in the app log I find this:

```
2024-06-25 12:08:28.632115+0100 0x2f4640a  Error       0x0                  32374  0    usernotificationsd: (UserNotificationsCore) [com.apple.usernotificationsd:Connections] [nil] Entitlement 'com.apple.private.usernotifications.bundle-identifiers' required to request user notifications
2024-06-25 12:08:28.632303+0100 0x2f4640a  Error       0x0                  32374  0    usernotificationsd: (UserNotificationsCore) [com.apple.usernotificationsd:Connections] [nil] setObservingUserNotifications not allowed: io.guidu2.app
2024-06-25 12:08:28.632741+0100 0x2f4640a  Error       0x0                  32374  0    usernotificationsd: (UserNotificationsCore) [com.apple.usernotificationsd:Connections] [nil] Entitlement 'com.apple.private.usernotifications.bundle-identifiers' required to request user notifications
2024-06-25 12:08:28.652991+0100 0x2f4640a  Error       0x0                  32374  0    usernotificationsd: (UserNotificationsCore) [com.apple.usernotificationsd:Connections] [nil] requestAuthorization not allowed: io.test2.app
2024-06-25 12:08:28.654569+0100 0x2f46129  Default     0x0                  27974  0    notifications: (UserNotifications) [com.apple.UserNotifications:Connections] [io.test2.app] Requested authorization [ didGrant: 0 hasError: 1 hasCompletionHandler: 1 ]
2024-06-25 12:08:28.655571+0100 0x2f46129  Default     0x0                  27974  0    notifications: Fyne error asking for permission to send notifications Error Domain=UNErrorDomain Code=1 "(null)"
```

So it seems the app is not properly setup to ask for permission?

I found this Apple document that might relate to this:
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_aps-environment

It says `To add this entitlement to your app, enable the Push Notifications capability in Xcode.`. So I assume this requires a change in the xcode project that is used for building darwin apps.

### How to reproduce

Create a minimal notification app. Build for darwin and run on MacOS.

### Example code

```
func main() {
	a := app.New()
	w := a.NewWindow("Notification Example")
	btn := widget.NewButton("Show Notification", func() {
		notification := fyne.NewNotification("Notification Title", "This is the notification.")
		a.SendNotification(notification)
	})
	w.SetContent(container.NewVBox(
		widget.NewLabel("Click the button to show a notification."),
		btn,
	))
	w.ShowAndRun()
}
```

### Fyne version

2.4.5

### Go compiler version

go1.21.5 darwin/amd64

### Operating system and version

MacOS Sonoma 14.5 (Intel)

**Comment by andydotxyz** [comment]
Sadly this is due to Apples enforcement policies. We cannot show a native notification unless the app has been packaged and run through the app launcher.

It will follow the standard process of shipped via the store or a package, or installed using "fyne install".

**Comment by Gys** [comment]
Hmmm, `fyne install` does not support darwin? I tried the latest v2.4.5. Instead I used `fyne release`.

**Comment by andydotxyz** [comment]
Fyne install does support Darwin. It supports all the platforms we build for.

If for some reason you are not seeing follow-up notifications please open an issue, this is not a known problem.

**Comment by Gys** [comment]
> Fyne install does support Darwin. It supports all the platforms we build for.

The `install` help says:
```
 OPTIONS:
   --target value, --os value    The mobile platform to target (android, android/arm, android/arm64, android/amd64, android/386, ios, iossimulator).
   --installDir value, -o value  A specific location to install to, rather than the OS default.
   --icon value                  The name of the application icon file.
   --use-raw-icon                Skip any OS-specific icon pre-processing (default: false)
   --appID value, --id value     For Android, darwin, iOS and Windows targets an appID in the form of a reversed domain name is required, for ios this must match a valid provisioning profile
   --release                     Enable installation in release mode (disable debug, etc). (default: false)
   --help, -h                    show help (default: false)
```

So it explicitly says only mobile platforms. 

If I do `fyne install --os darwin` it says `Unsupported target operating system "darwin"'.

**Comment by andydotxyz** [comment]
Yikes! Docs need updated.

Don't pass an os parameter and it will install on the current OS

**Comment by andydotxyz** [comment]
Perhaps this improvement will help? https://github.com/fyne-io/fyne/pull/4990

**Comment by Gys** [comment]
> If for some reason you are not seeing follow-up notifications please open an issue, this is not a known problem.

I opened another issue for this.

**Comment by Gys** [comment]
> Sadly this is due to Apples enforcement policies. We cannot show a native notification unless the app has been packaged and run through the app launcher.
> 
> It will follow the standard process of shipped via the store or a package, or installed using "fyne install".

Using `fyne install` does not support `--profile` and `--certificate` and therefore the resulting app will not be certified and still **not** use native notifications. It seems to me that, at least for darwin, the `build`, `package` and `install` do almost the same, which might make them confusing. Maybe consider to, for example, merge the build and package commands? Unless for some platforms this really results in something very different?

Only the `release` command has a clear different result.

Ideally the `install` command would also support profile and certificate params. To test native notifications I now have to make a release and then manually use the installer in the resulting .pkg. This makes quick tests a bit cumbersome.

**Comment by Gys** [comment]
I came up with this line to reinstall a `release` version from the commandline. The 5s delay is for the OS to release the notifications settings:

`pkill -x notifications ; sudo rm -R /Applications/notifications.app ; sleep 5 ; sudo installer -pkg notifications.pkg -target /Applications && l /Applications/notifications.app && open /Applications/notifications.app/`

**Comment by andydotxyz** [comment]
>  It seems to me that, at least for darwin, the build, package and install do almost the same, which might make them confusing

It shouldn't be confusing. The `build` command just creates a binary (like go build), the `package` command creates a full GUI package (.app for Darwin) and the `install` command actually installs it locally.

> Ideally the install command would also support profile and certificate params. 

It doesn't seem like a good thing to require Apple's approval to package software for a local installation.

> This makes quick tests a bit cumbersome.

The intent is that people should not need to test every permutation of the app - the notifications will work locally or on released package setup too. I'm glad you have a way to test it using a release-ready packaging on a local install, but mostly that's not something folk should need to worry about.
