### ISSUE TITLE
Clicking First App Tab Multiple Times Causes Strange Drawing Behavior

### ISSUE THREAD

**Issue by p4k1tz** [fyne-io/fyne#4992]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When creating a window with App Tabs containing grid with rows -> grid with columns -> buttons and then clicking the first tab multiple times draws content from last tab inside the first tab. I t is worth noting, I am using the same buttons in multiple tabs to create "views". 

### How to reproduce

The below creates the content for a window that has this problem. The window itself is set to main window, is fixed size, and is 600x360.
	
	

### Screenshots

![Animation](https://github.com/fyne-io/fyne/assets/22823690/5251d6b8-9fea-4f8c-b494-98361d9ba0e3)

### Example code

```go
tabs := container.NewAppTabs(
		container.NewTabItemWithIcon(
			"All Tools",
			theme.WarningIcon(),
			container.NewGridWithRows(
				3,
				container.NewGridWithColumns(
					3,
					buttonMountPDrive,
					buttonUnmountPDrive,
					buttonExtractPDrive,
				),
				container.NewGridWithColumns(
					3,
					buttonLinkWorkshopMods,
					buttonAddLocalMods,
					buttonKillDayZ,
				),
				container.NewGridWithColumns(
					3,
					buttonKillDayZDiag,
					buttonPackMods,
					buttonTextureWatcher,
				),
			),
		),
		container.NewTabItemWithIcon(
			"Work Drive",
			theme.FolderIcon(),
			container.NewGridWithRows(
				3,
				container.NewGridWithColumns(
					2,
					buttonMountPDrive,
					buttonUnmountPDrive,
				),
				container.NewGridWithColumns(
					2,
					buttonExtractPDrive,
					buttonAddLocalMods,
				),
				container.NewGridWithColumns(
					2,
					buttonLinkWorkshopMods,
				),
			),
		),
		container.NewTabItemWithIcon(
			"Mods",
			theme.SettingsIcon(),
			container.NewGridWithRows(
				3,
				container.NewGridWithColumns(
					2,
					buttonKillDayZ,
					buttonKillDayZDiag,
				),
				container.NewGridWithColumns(
					2,
					buttonPackMods,
				),
			),
		),
		container.NewTabItemWithIcon(
			"Retexture",
			theme.FileImageIcon(),
			container.NewGridWithRows(
				3,
				container.NewGridWithColumns(
					2,
					buttonTextureWatcher,
				),
			),
		),
	)

	//tabs.SetTabLocation(container.TabLocationLeading)

	//innerContent := container.NewGridWithColumns(
	//	1,
	//	tabs,
	//)

	c.Window.SetContent(tabs)

	tabs.Refresh()
	```

### Fyne version

v2.4.6-0.20240705195151-7d4b6e61804e

### Go compiler version

1.21.0

### Operating system and version

Windows 10

**Comment by andydotxyz** [comment]
You should not put one widget into multiple containers, this will create undefined behaviours.

**Comment by p4k1tz** [comment]
In my case this is a desired, I am sure I can just copy the button, but should adding a widget to multiple containers really cause undefined behavior?

**Comment by andydotxyz** [comment]
Yes it really will be undefined. An object can only appear in one place. If you put it in two containers then you are asking 1 item to exist in 2 different places.

**Comment by andydotxyz** [comment]
Of course two different buttons can have the same label and they could even have the same function to call on tapped - but it cannot exist in two different places.
