### ISSUE TITLE
App Metadata is empty on windows (develop branch)

### ISSUE THREAD

**Issue by Sharrnah** [fyne-io/fyne#4994]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When calling `fyne.CurrentApp().Metadata().Version` or `a.Metadata().Version` (where `a` is created by `a := app.NewWithID("app.id")`

i only get back `0.0.1` for the Version, and Build returns `1`, no matter what i define in the FyneApp.toml
```
Website = "https://github.com/Sharrnah/whispering-ui"

[Details]
  Icon = "app-icon.png"
  Name = "Whispering Tiger"
  ID = "tiger.whispering"
  Version = "1.3.1"
  Build = 5
```

It works with the public released v2.4.5.

### How to reproduce

- Define a Version and Build value in the FyneApp.toml
- Build the app using `fyne package --release`
- Check in code the values via `fyne.CurrentApp().Metadata().Version` or `fyne.CurrentApp().Metadata().Build`

Properties of the exe has saved these correctly.

### Screenshots

![grafik](https://github.com/fyne-io/fyne/assets/55756126/dbc2711b-aedc-4bd5-8542-ae06988a6f7b)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"strconv"
)

func main() {

	a := app.NewWithID("app.id")
	w := a.NewWindow("application")

	AppVersion := a.Metadata().Version
	AppBuild := strconv.Itoa(a.Metadata().Build)

	w.SetTitle("Application " + AppVersion + " (" + AppBuild + ")")

	w.SetMaster()
	w.CenterOnScreen()

	w.Show()
	a.Run()
}
```

```toml
Website = "xyz"

[Details]
  Name = "application"
  ID = "app.id"
  Version = "1.3.1"
  Build = 7

```

### Fyne version

7d4b6e61804e07f026ab29de24adfcdc5b2324b3

### Go compiler version

1.22.5

### Operating system and version

Windows 11

**Comment by andydotxyz** [comment]
I cannot replicate this, it works great on develop.
Please make sure that the fyne executable is also up to date.

**Comment by Sharrnah** [comment]
ah. i am sorry. i haven't thought about that. reinstalling the cmd fixed it.

Sorry again. :)
