### ISSUE TITLE
Support the register of URL scheme with the OS

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [fyne-io/fyne#4996]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

It would be awesome if the `fyne package` could support registering a schema such as 'magnet://' so that if we click the magnet uri in our browser, it will be matched by our application and to deal with it.

### Describe the solution you'd like to see.

The `fyne package` command add new parameter to support this.

**Comment by andydotxyz** [comment]
Updated title to be clearer. We support registering schemes internally, but this is requesting with OS level integration I believe.
