### ISSUE TITLE
Japanese text doesn't truncate properly using fyne.TextTruncateEllipsis

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4998]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When truncating text in a label, richtext, etc. Japanese text (and possibly other scripts too) don't truncate at the right position and instead overstep the boundary of the widget.

### How to reproduce

Run the example app

### Screenshots

<img width="412" alt="image" src="https://github.com/fyne-io/fyne/assets/5303666/967e9aad-83cb-41c1-8c26-a96b575b6591">

### Example code

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test truncate")
	l1 := widget.NewLabel("hereisakindoflonglabeltextwithnospaces")
	l1.Truncation = fyne.TextTruncateEllipsis
	l2 := widget.NewLabel("これはテキストの切り捨てがどのように機能するかをテストするための日本語の文です")
	l2.Truncation = fyne.TextTruncateEllipsis
	rect := &canvas.Rectangle{
		StrokeColor: &color.NRGBA{R: 255, A: 255},
		StrokeWidth: 2,
	}
	w.SetContent(container.New(layout.NewGridLayoutWithColumns(2),
		container.NewVBox(l1, l2),
		rect,
	))
	w.Resize(fyne.NewSize(300, 150))
	w.ShowAndRun()
}
```

### Fyne version

develop

### Go compiler version

n/a

### Operating system and version

mac

**Comment by andydotxyz** [comment]
I have a local fix that should resolve the issue and will open a PR soon.
However it does not completely fix the test case provided as that is a mix of different types of text which triggers a bug in go-text as far as I can see. Reported upstream and will see what the team say (https://github.com/go-text/typesetting/issues/166)

**Comment by andydotxyz** [comment]
Fixed on develop, will merge to release before .2
