### ISSUE TITLE
Error while importing fyne

### ISSUE THREAD

**Issue by KyotoGuru** [fyne-io/fyne#4999]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Hello guys! I have the following problem: I cannot use fyne. When installing it according to the official page https://docs.fyne.io/started FyneSetupTool displays the correct installation, but an error occurs in VSCode (screenshot 1). go mod tidy, re-creating the module does not help solve the problem in any way. Reloading fyne does not give any results either. 

How I tried to solve the problem: 
1) Completely reinstalling go 
2) Reinstalling mSys 
3) Reinstalling vs code and using other code editors. 

Nothing helps. I did not find a similar problem on the Internet. The Fyne Setup Tool shows the following (fyne helper also installed, did not help) (screenshot 2). All Path variables are specified according to the installation, and all applications are installed correctly. Please help me! 

### How to reproduce

I don't known :(

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/99592396/bee91ea1-a5c2-4bbc-9dad-f1a103c20dd5)
![image](https://github.com/fyne-io/fyne/assets/99592396/3729f1a6-427b-46ca-a0fe-73c470174d3b)

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}

// under - error

error while importing fyne.io/fyne/v2/app: missing go.sum entry for module providing package fyne.io/systray (imported by fyne.io/fyne/v2/internal/driver/glfw); to add:
	go get fyne.io/fyne/v2/internal/driver/glfw@v2.4.5compiler
error while importing fyne.io/fyne/v2/app: missing go.sum entry for module providing package github.com/fredbi/uri (imported by fyne.io/fyne/v2/storage/repository); to add:
	go get fyne.io/fyne/v2/storage/repository@v2.4.5compiler
error while importing fyne.io/fyne/v2/app: missing go.sum entry for module providing package github.com/fsnotify/fsnotify (imported by fyne.io/fyne/v2/app); to add:
	go get fyne.io/fyne/v2/app@v2.4.5 
	
	...and more packages

### Fyne version

2.4.5

### Go compiler version

1.22.5

### Operating system and version

Windows 11

**Comment by andydotxyz** [comment]
Type "go mod tidy", should fix missing modules in your IDE
