### ISSUE TITLE
Typing Chinese characters in widget.Entry and perform undo/redo crashes the app.

### ISSUE THREAD

**Issue by evanhyd** [fyne-io/fyne#5001]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

widget.Entry undo/redo is not compatiable with Chinese characters. Undo/Redo crashes the app when dealing with multiple Chinese characters.

### How to reproduce

1. Create a text entry
2. Type random Chinese characters (for example, 测试) in the text entry
3. Call Undo()/Redo() or use the corresponding hotkey
4. Observe that the text entry transits into error states

//to crash the app
1. Create a text entry
2. Type random Chinese characters (for example, 测试) in the text entry
3. Select all and delete
4. Perform Undo() twice (ctrl + Z)
5. Observe that fyne crashes

### Screenshots

![image](https://github.com/user-attachments/assets/b1929a0f-634b-423b-9b9e-e85389fade0a)
![image](https://github.com/user-attachments/assets/f4416bb1-cc73-4298-8faf-453e629e764e)
![image](https://github.com/user-attachments/assets/aff0e672-f0d0-4e48-861e-b7e82e9d2879)

### Example code

Create text entry widget, type in Chinese characters, press ctrl + z, ctrl + y to perform undo and redo.

### Fyne version

2.5.0

### Go compiler version

1.22

### Operating system and version

Windows 10

### Additional Information

At: home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/driver_desktop.go:171
panic: runtime error: slice bounds out of range [4:2]

goroutine 11 [running]:
fyne.io/fyne/v2/widget.(*entryModifyAction).sub(...)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2316
fyne.io/fyne/v2/widget.(*entryModifyAction).Undo(0xc000f55ea0?, {0xc0053aadbe?, 0x7ff6a4a23872?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2297 +0x90
fyne.io/fyne/v2/widget.(*entryUndoStack).Undo(0xc000d7fc08?, {0xc0053aadbe?, 0x7f0000c000f55ed8?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:2378 +0x4c
fyne.io/fyne/v2/widget.(*Entry).Undo(0xc000d7fc08)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:787 +0x49
fyne.io/fyne/v2/widget.(*Entry).registerShortcut.func1({0xc000d7fc58?, 0x7ff6a5349920?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:1160 +0x17
fyne.io/fyne/v2.(*ShortcutHandler).TypedShortcut(0xc000d7fc58, {0x7ff6a55c8580, 0x7ff6a5b67b80})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/shortcut.go:21 +0x6e
fyne.io/fyne/v2/widget.(*Entry).TypedShortcut(0xc0002eca20?, {0x7ff6a55c8580?, 0x7ff6a5b67b80?})
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/widget/entry.go:966 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).triggersShortcut.func1()
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window.go:912 +0x24
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(...)
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/common/window.go:35
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1 in goroutine 1
        home/Go/dependency/pkg/mod/fyne.io/fyne/v2@v2.5.0/internal/driver/glfw/window.go:997 +0x136
2024/07/18 00:06:27 exit status 2
exit status 1

**Comment by andydotxyz** [comment]
When reporting a crash can you please include the panic printed to the terminal?

**Comment by evanhyd** [comment]
added more info

**Comment by dweymouth** [comment]
fixed for 2.5.1

**Comment by evanhyd** [comment]
thanks
