### ISSUE TITLE
entry FocusGained/FocusLost functions run before resizing for the mobile keyboard is complete

### ISSUE THREAD

**Issue by hkparker** [fyne-io/fyne#5003]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I'm not sure if this is a bug or if this is just me trying to do something that can't be done with the API.  I'm trying to get a callback that runs immediately after the mobile keyboard has been displayed and the UI has been resized (#566 and #2371, as addressed in 2.5.0).  The keyboard is being displayed when an entry is clicked, and so my idea was to create a custom entry widget and use `FocusGained` and `FocusLost`.  I was depending on the assumption that `FocusGained` would be called after the keyboard had been displayed and the rest of the UI resized, but this is not the case.

Instead, when I log the height of the container being resized (a VScroll), the `FocusGained` and `FocusLost` functions are called before the UI is resized.  This is evident because the logs appear a few seconds before the keyboard is visible (displaying the keyboard and resizing the UI takes about 3-5 seconds at least, see #1062, so this is easy to watch in slow motion).  This is also evident by the fact that the logs report the correct height of the container _before_ the resize operation.

Logs go something like:

```
*clicks the entry*

level=warning msg="entry focus changed" focused=true height=951.4219

*keyboard later appears, UI resizes*
*hit the back button*

level=warning msg="entry focus changed" focused=false height=563.9219

*keyboard disappears*

```

Main questions are:

**1) Should an entry's `FocusGained`/`FocusLost` be called before or after the UI has been resized for the mobile keyboard?**
**2) If the answer is before, is there currently a way to run code immediately after the keyboard resize has been complete?**

### How to reproduce

One would have to build a purpose built app to reproduce this, which depending on where this discussion goes I can do, but I have no open sourced example.

### Example code

Entry looks something like this

```go
type customEntry struct {
    widget.Entry
    customOnFocusChanged func(bool)
    ///...
}

//...

func (e *customEntry) FocusGained() {
	e.Entry.FocusGained()
	if e.customOnFocusChanged != nil {
		e.customOnFocusChanged(true)
	}
}

func (e *customEntry) FocusLost() {
	e.Entry.FocusLost()
	if e.customOnFocusChanged != nil {
		e.customOnFocusChanged(false)
	}
}
```

Then checking the height of the resized scroll like

```go
s := // a scroll that gets resized by the appearance of the mobile keyboard
e.customOnFocusChanged = func(focused bool) {
    if fyne.CurrentDevice().IsMobile() {
        log.WithFIelds(log.Fields{
            "height": s.Size().Height
            "focused": focused,
        }).Warn("entry focus changed")
    }
}
```

### Fyne version

2.5.0

### Go compiler version

go1.22.5 linux/amd64

### Operating system and version

Android 14

**Comment by dweymouth** [comment]
The FocusGained/FocusLost hooks are called immediately after a widget gains or loses focus and is mostly intended for the widget to update its styling, e.g. show the blue border around Entry and the caret. What is your use case for needing a hook that is called after the mobile keyboard is visible?

**Comment by hkparker** [comment]
I'm building a chat app.  When you focus the thread entry in a chat app on mobile, the keyboard appears, and, generally speaking, the chat history will scroll down / move up to accommodate that, such that you're still looking at the same lowest message.

Below is an example from signal (apologies for the tall message)

No keyboard visible, scrolled all the way down

<img src ="https://github.com/user-attachments/assets/5714bc34-1a1c-4438-8df6-e8e6265fc57e" width="300">

Let's focus the entry so that they keyboard displays

<img src="https://github.com/user-attachments/assets/1163623f-2f39-4cbd-a13e-27e2292b549b" width="300">

Message "20" is still the bottom message, we're still scrolled all the way down

Now let's try adding more messages, and scrolling up a bit

<img src="https://github.com/user-attachments/assets/44411b0a-13c6-4246-ad78-c55d90089e67" width="300">

You can see we're scrolled up a bit (jump-to-buttom button appears).  And now let's focus the entry again

<img src="https://github.com/user-attachments/assets/2e7e6a76-fa4e-4a5b-a25f-5129d28a3d3b" width="300">

23/24 is still at the bottom, so the scroll moves regardless of where it was pre-keyboard.

---

Now, building something similar in Fyne, here's what I experience

Start by opening a thread and seeing the message history

<img src="https://github.com/user-attachments/assets/f7db6a6c-803f-479b-8272-bf505ce753bc" width="300">

Then focusing the thread entry

<img src="https://github.com/user-attachments/assets/2f3585fd-5ad2-4165-b35c-4e49a9fa7b97" width="300">

Dang, I need to automatically scroll down!  Messages 7-10 are now covered by the keyboard and they shouldn't be.  We should instead still be scrolled all the way down after the keyboard appears.  But how can I know how much to scroll down, and how can I do it right after the keyboard appears?  This is the behavior I'm trying to build.

**Comment by dweymouth** [comment]
You should be able to do this by putting your message component in a container with a custom layout. In your layout your Layout function will be called with a new size when the keyboard appears and you can scroll and resize your messages in response to that.

**Comment by hkparker** [comment]
Brilliant, ok.  Thank you!  I'd like to clarify what you're suggesting a bit.

Right now I'm using a Scroll (though I'm planning on switching to a custom widget.List at some point after I wrap up the current feature set I'm working on).  Say I continue with a Scroll for now though, would this be a matter of making a new custom extension on Scroll (and the `scrollContainerRenderer`) so that I can adjust the renderer's `Layout` function to add this behavior?  (and, in a future widget.List world, basically do the same thing there?)

Or, alternatively and more simply, could I leave everything as is, and wrap that Scroll inside a new container with my own thing that implements `fyne.Layout`, and have my custom layout basically do nothing and just place the scroll where it should be, but then use that to detect changes and adjust the scroll position as needed?

**Comment by dweymouth** [comment]
The last one is what I was suggesting - that should be all you need to make this scenario work, and you can move on to the custom List-based widget later

**Comment by hkparker** [comment]
Perfect, ok that's what I suspected since that's a lot easier.  And it's agnostic to whatever scroll type thing I use underneath, so that doesn't complicate moving on to the widget.List implementation when I'm ready.  I'll give this a try soon, thank you for the help!

**Comment by andydotxyz** [comment]
A great solution @dweymouth thanks for that - layouts to the rescue again :).
Do you think this would be worth a small example in the docs somewhere as it's super useful.

**Comment by hkparker** [comment]
Just wanted to follow up and say I implemented this and it worked beautifully with very minimal code changes, thanks again for the suggestion @dweymouth

**Comment by hkparker** [comment]
@andydotxyz I mentioned I'd share what I came up with, [here's the gist](https://gist.github.com/hkparker/873fffedc5bb94506e5bdbaf6d088408).  I'm not sure if it's perfect, I'm hard coding a scroll-to-bottom condition to avoid setting an offset that's higher than makes sense when there less content in the scroll than the height of the scroll, which might not be necessary.  But anyway, it works.

Cool thing about this too is not only does it solve the mobile keyboard problem, it handles the growth of my expanding multi-line entry on desktop equally well, which I hadn't even thought to address yet.
