### ISSUE TITLE
How do i fix the terrible bug

### ISSUE THREAD

**Issue by MidnightSong** [fyne-io/fyne#5011]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I think I may not be able to express this clearly, so pls look at i uploaded video

### How to reproduce

look at the video 

### Screenshots

https://github.com/user-attachments/assets/ea16e694-7f99-4f92-bff2-5452f1ee0e7d

### Example code

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

var data = [][]string{
	{"Row 1, Col 1", "Row 1, Col 2"},
	{"Row 2, Col 1", "Row 2, Col 2"},
	{"Row 3, Col 1", "Row 3, Col 2"},
	{"Row 4, Col 1", "Row 4, Col 2"},
	{"Row 5, Col 1", "Row 5, Col 2"},
	{"Row 6, Col 1", "Row 6, Col 2"},
}

func main() {
	mainApp := app.NewWithID("a.b.c.d")
	mainWin := mainApp.NewWindow("test table")
	table := getTable()
	mainWin.SetContent(container.NewStack(table))
	mainWin.CenterOnScreen()
	mainWin.Resize(fyne.NewSize(600, 400))
	mainWin.ShowAndRun()
}

func getTable() *widget.Table {
	// Get length
	length := func() (int, int) { return len(data), 3 }
	// Create label
	create := func() fyne.CanvasObject {
		label := widget.NewLabel("unload")
		label.Wrapping = fyne.TextWrapWord
		check := widget.NewCheck("", func(b bool) {
			fmt.Println("unload")
		})
		check.Hide()
		return container.NewStack(label, check)
	}
	update := func(id widget.TableCellID, cell fyne.CanvasObject) {
		c := cell.(*fyne.Container)
		switch id.Col {
		case 2:
			c.Objects[0].(*widget.Label).Hide()
			check := c.Objects[1].(*widget.Check)
			check.Show()
			check.OnChanged = func(b bool) {
				fmt.Printf("Check Row:%d Col: %d \n", id.Row+1, id.Col+1)
			}
		default:
			label := c.Objects[0].(*widget.Label)
			label.SetText(data[id.Row][id.Col])
		}
	}
	table := widget.NewTableWithHeaders(length, create, update)
	table.SetColumnWidth(0, 100)
	table.SetColumnWidth(1, 100)
	return table
}
```

### Fyne version

v2.5.0

### Go compiler version

1.21

### Operating system and version

macOS Sonoma 14.5 Apple M2  and windows 11 x86

**Comment by dweymouth** [comment]
Unfortunately that video does not play or download in my browser. Also from the PR title I have no idea what is going on. A code snippet that reproduces the issue and a better title would be a huge help!

**Comment by andydotxyz** [comment]
I'm going to guess it is a bug in the re-use code and the OP is seeing check boxes appear in columns supposed to be text.

They have missed the Hide()/Show() calls in some of the update logic.
