### ISSUE TITLE
Slider widget needs a Set() method

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#502]
In implementing the DataAPI, it is expected that widgets have an appropriate Set() type method to be able to set the value from outside the widget code. (ie - the underlying data has changed, so trigger an update on subscribed widgets)

eg:
Entry.SetText(txt string)
Radio.SetSelected(txt string)
Check.SetChecked(b bool)
Label.SetText(txt string)

Slider Widget - doesnt appear to have a Set() type method.

**Comment by steveoc64** [comment]
https://github.com/fyne-io/fyne/pull/503

Added a Set(float64) method to the Slider  in the PR above. Pretty simple change.

**Comment by andydotxyz** [comment]
Probably should be SetValue() to match the Value field - like how Entry is SetText vs Text and Check is SetChecked vs Checked

**Comment by stuartmscott** [comment]
Implemented in #1350
