### ISSUE TITLE
customise/remove shadow from non modal widget.PopUp

### ISSUE THREAD

**Issue by Paul365x** [fyne-io/fyne#5022]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

The shadow is displayed as rectangular following the bounding box. However if you are working on popups that are circular or other shapes the shadow is an incompatible shape. Removing it - hide flag maybe - or much harder - make it follow the content rather than the bounding box

### Is it possible to construct a solution with the existing API?

no. The renderer uses a shadow renderer and all values are hardcoded or private.

### Describe the solution you'd like to see.

Would be happy with just having the ability to switch off shadows for those cases where it is inappropriate - as an eg I am currently working on an animated gizmo in a popup that is circular. Quite ruins the effect to have a square shadow around it.

**Comment by andydotxyz** [comment]
An alternative request would be for the shadow to follow the shape of content? This is more complex but does not require new APIs and stays consistent on the UI.

**Comment by dweymouth** [comment]
Oh wow, TIL about the public Overlays API - this could probably be used to build custom tooltips! (though I will probably need to make the shadow API public in my fork since I would want shadows around them but have them not change the focus manager at all like PopUps do)
