### ISSUE TITLE
SetFullScreen require sleep some time to take effect

### ISSUE THREAD

**Issue by xfaris** [fyne-io/fyne#5031]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

SetFullScreen require sleep some time to take effect; otherwise, it won't go fullscreen and the window's position will be incorrect.

### How to reproduce

I see some code in internal/driver/glfw/window.go

if w.fullScreen { // this does not work if called before viewport.Show()
			go func() {
				time.Sleep(time.Millisecond * 100)
				w.SetFullScreen(true)
			}()
		}

### Example code

func myShow() {
    window.Show()
    time.Sleep(1 * time.Second)
    window.SetFullScreen(true)
}

func myHide() {
    window.SetFullScreen(false)
    window.Hide()
}

myShow -> myHide -> myShow 

### Fyne version

2.4.5

### Go compiler version

1.20

### Operating system and version

windows 10

**Comment by andydotxyz** [comment]
I cannot replicate from the code provided - please include a complete sample that demonstrates the problem.
