### ISSUE TITLE
Fyne 2.5 breaks automatic themed font color adjustment of buttons when changing Primay Color

### ISSUE THREAD

**Issue by Gambloide** [fyne-io/fyne#5032]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Prior to Fyne 2.5, buttons would change their font color based on their background color.
With 2.5, when changing the themes primary color, this is not the case anymore.
If you use the dark theme and use a light primary color, Fyne will place white text on a bright background.
It even goes as far as putting pure white text on pure a white white background.

This combined with https://github.com/fyne-io/fyne/issues/5025 seems to make it basically impossible to assure readable text and icons on buttons depending on a user's accent/primary color, even if you try to overwrite the default behavior. Hence, these probably have to be fixed before https://github.com/fyne-io/fyne/issues/4367 should be completed.

### How to reproduce

**Steps to Reproduce**

Run the below example code once with Fyne 2.5 and once with Fyne 2.4.3
Notice how the text on the button is readable with 2.4.3, but invisible with 2.5.

### Screenshots

**With Fyne 2.4.3**
![Screenshot_20240726_150452](https://github.com/user-attachments/assets/038fb151-2b7f-46f8-a1e4-cace1e95071f)

**With Fyne 2.5**
![Screenshot_20240726_150040](https://github.com/user-attachments/assets/f6a5a2a0-b774-41f9-8a44-258c4622fd7c)

### Example code

``` go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type customTheme struct{}

var _ fyne.Theme = (*customTheme)(nil)

func (m customTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	if name == theme.ColorNamePrimary {
		return color.RGBA{R: 0xFF, G: 0xFF, B: 0xFF, A: 0xff}
	}

	return theme.DefaultTheme().Color(name, variant)
}

func (m customTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func (m customTheme) Font(style fyne.TextStyle) fyne.Resource {
	return theme.DefaultTheme().Font(style)
}

func (m customTheme) Size(name fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(name)
}

func main() {
	app := app.New()
	app.Settings().SetTheme(&customTheme{})
	window := app.NewWindow("")

	window.SetContent(
		&widget.Button{
			Text:       "Button",
			Importance: widget.HighImportance,
			Icon:       theme.RadioButtonCheckedIcon(),
		},
	)

	window.ShowAndRun()
}
```

### Fyne version

2.5

### Go compiler version

1.22.4

### Operating system and version

Nobara Linux 40

**Comment by dweymouth** [comment]
There is a new theme color name that controls the color of foreground content (text and icons) on top of a Primary background - https://github.com/fyne-io/fyne/blob/master/theme/color.go#L85

**Comment by andydotxyz** [comment]
I think it's a combination of that plus the custom theme shown ignores the light/dark mode setup.
If it truly is only providing light mode code then it should force the delegation to use light as well.

**Comment by Gambloide** [comment]
I am sorry for the late reaction to the responses.

I appear to be ignorant of the intended ways to adjust the theme in fyne then, given I am under the impression of having done as documented (https://docs.fyne.io/extend/custom-theme.html) and not been able to glean any contradicting information from the 2.5 release notes, which introduced a change in behavior.

This is not an attempt to turn this into support discussion or to argue against closing the issue. I wanted to provide  context for my original post in light of your responses and thank you for nudging me into the right direction. 👌
