### ISSUE TITLE
Some problems encountered when using the NewRichTextWithText (markdown syntax incompatible) method.

### ISSUE THREAD

**Issue by wonderfulLand** [fyne-io/fyne#5066]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

- The markdown bold syntax does not work when the word is Chinese characters. As shown in the following figure

![image](https://github.com/user-attachments/assets/3073f04b-2dc0-432b-9d03-ceb13ed6234b)

- The markdown citation syntax does not take effect, and the sentence is not quoted, as shown in the following figure.

![image](https://github.com/user-attachments/assets/c15c484a-6f12-4450-a8ec-542f26827cd8)

### 1.system os
win 11
### 2.golang version
1.22.6
### 3.fyne version
2.5.0

### Example code

```go
func CreateRichInMarkDown(content <-chan string) fyne.Widget {
	markdown := widget.NewRichTextWithText("")
	go func() {
		for {
			content, _ := <-content
			markdown.ParseMarkdown(content)
			markdown.Refresh()
		}
	}()
	return markdown
}
```

### Fyne version

2.5.0

### Go compiler version

1.22.6

### Operating system and version

win 11

**Comment by andydotxyz** [comment]
> The markdown citation syntax does not take effect, and the sentence is not quoted, as shown in the following figure.

This is confusing to me because the image shows that the text is indented as a quote should be...

**Comment by wonderfulLand** [comment]
> In my testing it is working fine. I think you have a space immediately after the "**" which stop it being bold.


Hello! Have you ever conducted tests using Simplified Chinese?

**Comment by wonderfulLand** [comment]
> This is confusing to me because the image shows that the text is indented as a quote should be...

When using the Markdown citation syntax, the first line is indeed indented, but the background color rendering is not applied.

**Comment by andydotxyz** [comment]
> > In my testing it is working fine. I think you have a space immediately after the "**" which stop it being bold.
> 
> Hello! Have you ever conducted tests using Simplified Chinese?

Yes, on a regular basis. I replicated the problem you displayed exactly and it was resolved by removing the extra space character.

**Comment by andydotxyz** [comment]
> > This is confusing to me because the image shows that the text is indented as a quote should be...
> 
> When using the Markdown citation syntax, the first line is indeed indented, but the background color rendering is not applied.

Applying a background colour is not part of how we render quotations and is not part of the specification either.
