### ISSUE TITLE
The content of the entries in the list may wrap to a new line or get lost when scrolling.

### ISSUE THREAD

**Issue by 0x414a** [fyne-io/fyne#5071]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The content of the entries in the list may wrap to a new line or get lost when scrolling.

### How to reproduce

After entering something in either entry, scroll the pulley

### Screenshots

https://github.com/user-attachments/assets/4b844b3f-cc2a-4724-97d2-a1653743f601

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"strconv"
)

func main() {
	a := app.New()
	win := a.NewWindow("Test")

	list := widget.NewList(
		func() int {
			return 20 // 列表项的总数
		},
		func() fyne.CanvasObject {
			return container.NewBorder(nil, nil, widget.NewLabel(""), nil, widget.NewEntry())
		},
		func(id widget.ListItemID, item fyne.CanvasObject) {
			item.(*fyne.Container).Objects[1].(*widget.Label).SetText(strconv.Itoa(id))
		},
	)

	border := container.NewBorder(
		nil,
		nil,
		nil,
		nil,
		list,
	)
	win.SetContent(border)
	win.Resize(fyne.NewSize(400, 300))
	win.SetOnClosed(func() { a.Quit() })
	win.ShowAndRun()
}

### Fyne version

fyne version v2.5.0

### Go compiler version

go version go1.22.0 

### Operating system and version

darwin/arm64

**Comment by andydotxyz** [comment]
That is correct. List re-uses objects for efficiency. As you have done with updating the label you must manage what data is shown / changed in the entry according to which row it is configured for.
