### ISSUE TITLE
Make `fyne serve` accept `--metadata` flags

### ISSUE THREAD

**Issue by flimzy** [fyne-io/fyne#5074]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

`fyne package` exposes some options that are not exposed to `fyne serve`, but could still be relevant:

- `--metadata`
- `--tags`

And a couple others that may be technically relevant, but of less obvious value, as they seem purely aesthetic for local development:

- `--name`
- `--appVersion`

### Describe the solution you'd like to see.

I'd like to see at least `--metadata` passed through when provided to the `fyne serve` command.

**Comment by andydotxyz** [comment]
Good catch. Typically we would not add new API / command surface in a point release, but as this is an omission on one sub command I think we can get it in.

**Comment by andydotxyz** [comment]
Thanks for fixing, might just get into v2.5.1
