### ISSUE TITLE
button-disable-OnTapped?

### ISSUE THREAD

**Issue by jingc1413** [fyne-io/fyne#5076]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I think when I click the button, I disable it and it no longer responds to events. In fact, the button does turn gray, but ontraped continues to respond.

### How to reproduce

code

### Screenshots

![image](https://github.com/user-attachments/assets/2e9f9995-303a-42f3-8433-f04fcdfffa13)
I clicked twice in 1 second.

### Example code

code:
```golang
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"log"
	"time"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Button Widget")

	content := widget.NewButton("click me", nil)
	content.OnTapped = func() {
		content.Disable()
		defer content.Enable()
		log.Println("tapped")
		time.Sleep(time.Second * 3)
	}
	myWindow.SetContent(content)
	myWindow.ShowAndRun()
}
```

### Fyne version

v2.5.0

### Go compiler version

1.21.4

### Operating system and version

windows10

**Comment by andydotxyz** [comment]
You are blocking the entire graphics event thread with `Sleep`, and immediately after you unblock the button has become enabled again. So the events will be blocked (queued) and then processed, by which time the button is no longer enabled.

Remove the timer and the `Enable()` and you will see that a disable button cannot be tapped.
