### ISSUE TITLE
Demo Compilation error : /usr/bin/ld: cannot find -lXxf86vm: No such file or directory

### ISSUE THREAD

**Issue by byezy** [fyne-io/fyne#5079]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Cannot install demo due to compilation error

### How to reproduce

Just trying to install the demo app per instructions:

go install fyne.io/fyne/v2/cmd/fyne_demo@latest

### Screenshots

ThinkPad-P50:~/GolandProjects/fynepods$ go install fyne.io/fyne/v2/cmd/fyne_demo@latest

# fyne.io/fyne/v2/cmd/fyne_demo
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lXxf86vm: No such file or directory
collect2: error: ld returned 1 exit status

### Example code

```
 go install fyne.io/fyne/v2/cmd/fyne_demo@latest
```

### Fyne version

fyne.io/fyne/v2/cmd/fyne_demo@latest

### Go compiler version

go version go1.22.6 linux/amd64

### Operating system and version

Linux Mint 22

**Comment by andydotxyz** [comment]
Depending on your system there are some setup steps required - Linux stopped shipping developer libraries / headers by default. Did you try the dependency install line from https://docs.fyne.io/started/ ?

**Comment by byezy** [comment]
Thanks very much for the quick answer.

Yes, got way ahead of myself and missed that bit, which was indeed the issue.

Great work!
