### ISSUE TITLE
compilation failed ubuntu 24.04 LTS 

### ISSUE THREAD

**Issue by gauravcodepro** [fyne-io/fyne#5085]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I am developing a cloud native application and when i am compiling the code, it is giving error. I tested the fyne installation twice but it is giving the following error: 

```
go run fyne.io/fyne/v2/cmd/fyne_demo@latest
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
i install the libx11-dev using the sudo apt-cache search libx11 | grep ^ lib | sudo apt-get update && sudo apt-get install libx11-dev and it is showing the complete installation of libx11. I wrote a OpenGL code and it is working fine. Can you help with this. 

Thank you,
Gaurav

### How to reproduce

I am developing a cloud native application and when i am compiling the code, it is giving error. I tested the fyne installation twice but it is giving the following error: 

```
go run fyne.io/fyne/v2/cmd/fyne_demo@latest
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
i install the libx11-dev using the sudo apt-cache search libx11 | grep ^ lib | sudo apt-get update && sudo apt-get install libx11-dev and it is showing the complete installation of libx11. I wrote a OpenGL code and it is working fine. Can you help with this. 

Thank you,
Gaurav

### Example code

I am developing a cloud native application and when i am compiling the code, it is giving error. I tested the fyne installation twice but it is giving the following error: 

```
go run fyne.io/fyne/v2/cmd/fyne_demo@latest
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
i install the libx11-dev using the sudo apt-cache search libx11 | grep ^ lib | sudo apt-get update && sudo apt-get install libx11-dev and it is showing the complete installation of libx11. I wrote a OpenGL code and it is working fine. Can you help with this. 

Thank you,
Gaurav

### Fyne version

go install fyne.io/fyne/v2/cmd/fyne@latest

### Go compiler version

1.26

### Operating system and version

Ubuntu 24.04 LTS

### Additional Information

I am developing a cloud native application and when i am compiling the code, it is giving error. I tested the fyne installation twice but it is giving the following error: 

```
go run fyne.io/fyne/v2/cmd/fyne_demo@latest
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
i install the libx11-dev using the sudo apt-cache search libx11 | grep ^ lib | sudo apt-get update && sudo apt-get install libx11-dev and it is showing the complete installation of libx11. I wrote a OpenGL code and it is working fine. Can you help with this. 

Thank you,
Gaurav

**Comment by andydotxyz** [comment]
Did you try the library install commands from https://docs.fyne.io/started/?

**Comment by gauravcodepro** [comment]
Yes i tried and the only change is that instead of using the golang suggested in the version of the started fyne, I used the latest version of the golang. Is it possible that the fyne is causing the compilation error with the new version of golang.?. 

Thank you for the time taken to help me approaching towards a solution,
Gaurav

**Comment by andydotxyz** [comment]
No, this error is separate to the Go compiler. The developer headers for libX11 are not being found by your C compiler.

**Comment by andydotxyz** [comment]
Perhaps you can verify where Xlib.h is found on your system?

**Comment by gauravcodepro** [comment]
i did check 
```
❯ sudo apt-get install libx11-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libx11-dev is already the newest version (2:1.8.7-1build1).
```
but it is still showing the error. 
```
❯ go install fyne.io/fyne/v2/cmd/fyne@latest
❯ go run fyne.io/fyne/v2/cmd/fyne_demo@latest
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from go/bin/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/c_glfw.go:4:
./glfw/src/x11_platform.h:33:10: fatal error: X11/Xlib.h: No such file or directory
   33 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
^C
```
any guess?.

**Comment by gauravcodepro** [comment]
i further checked and also made the X11 in the PATH 
```
export PATH=/usr/include/X11:$PATH 
echo $PATH 
(base) gauravcodepro-XPS-13-9350% echo $PATH
/usr/include/X11:/home/gauravcodepro/.local/bin:/usr/include/X11:/usr/include/X11:/home/gauravcodepro/miniconda3/bin:/home/gauravcodepro/miniconda3/condabin:/home/gauravcodepro/.cargo/bin:/home/gauravcodepro/.juliaup/bin:/home/gauravcodepro/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/gauravcodepro/.local/bin
```
but the error is the same.

**Comment by andydotxyz** [comment]
PATH is not used to look up libraries.

**Comment by gauravcodepro** [comment]
this is not working and i think i will solve this later. Thank you for the time taken and help provided. I close this now.

**Comment by andydotxyz** [comment]
Just rounding this out the conversation happened on another channel and pasting in the command from the getting started seemed to solve the issue.

**Comment by Tim-Restart** [comment]
I've recently had the same problem trying to recompile an app that had previously worked. Installing the following dependency along with the libx11 dev fixed the issue:

```sudo apt-get install xorg-dev```

**Comment by andydotxyz** [comment]
xorg-dev is on our list of dependencies in the documentation.
You might find that some system upgrades remove these developer headers unfortunately but I don't think there is a problem where with Fyne or the docs.
