### ISSUE TITLE
Trigger MenuItem Selection in Open Menu of Select Widget in Test

### ISSUE THREAD

**Issue by jimorc** [fyne-io/fyne#5086]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I am building a custom widget based on the Select widget. I am not able to unit test a tap on the widget's menu items.
A call to `test.Tap` or `test.TapAt` results in opening the widget's menu of option values. There is no way to then select a menu item from the menu because a second `test.Tap` or `test.TapAt` call on the widget is again passed to the Select widget, and not to the appropriate menu item. Therefore, it is not possible to test the trigger code of the menu item.
Calling `Select.SetSelected` or `Select.SetSelectIndex` does not trigger the menu item tapped code and therefore is not a sufficient workaround.

### Is it possible to construct a solution with the existing API?

I know of no solution at this time.

### Describe the solution you'd like to see.

Add the ability to `test.TapAt` on menu items of a Select widget.

**Comment by jimorc** [comment]
On Slack, Andrew Williams pointed out that what I need to use is `test.TapCanvas`.
I have managed to get that to work.

**Comment by andydotxyz** [comment]
Alternatively you can tap the popup menu, as it is an overlay you would gain access to it using the Canvas overlay stack APIs.

**Comment by andydotxyz** [comment]
> Alternatively you can tap the popup menu, as it is an overlay you would gain access to it using the Canvas overlay stack APIs.

I'm calling this the resolution to the issue. Popup menus are not part of the widgets that they appear from (as shown by the way they are over other content).
