### ISSUE TITLE
If I want to make one, does the widget.richtext support the function of dragging and dropping selected text with the mouse?

### ISSUE THREAD

**Issue by wonderfulLand** [fyne-io/fyne#5091]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

no

### Is it possible to construct a solution with the existing API?

no

### Describe the solution you'd like to see.

The text content in widget.richtext supports mouse selection and copying

**Comment by andydotxyz** [comment]
Fyne has interactive text (which can be selected, copied etc) and static text widgets.

Entry is interactive but Label and RichText are not interactive widgets.

**Comment by andydotxyz** [comment]
I think this question was answered, closing as duplicate of #21
