### ISSUE TITLE
Metadata().Release will not allow the app to run/show

### ISSUE THREAD

**Issue by rad756** [fyne-io/fyne#5102]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

trying to run complied binary or "go run ." project where Metadata().Release exists will not allow the gui to show

### How to reproduce

Check app metadata release mode (might not be limited to this only) in your code and ui won't show

### Screenshots

N/A

### Example code
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	if a.Metadata().Release {
		a = app.NewWithID("com.example.x")
	} else {
		a = app.NewWithID("com.example.x.testing")
	}

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}
### Fyne version

2.5.1 and 2.5.0

### Go compiler version

1.22.6

### Operating system and version

Tumbleweed Fedora and Windows 10

### Additional Information

If the below is commented out from example code it will not show ui on fyne 2.5.0 and 2.5.1 but will on prior versions

	if a.Metadata().Release {
		a = app.NewWithID("com.example.x")
	} else {
		a = app.NewWithID("com.example.x.testing")
	}

**Comment by andydotxyz** [comment]
I cannot replicate with that code snippet on 2.4.x, 2.5.x or 2.6(develop), the following code works:

```go
func main() {
	a := app.NewWithID("dummy")

	if a.Metadata().Release {
		a = app.NewWithID("com.example.x")
	} else {
		a = app.NewWithID("com.example.x.testing")
	}

	w := a.NewWindow("ID")
	w.SetContent(widget.NewLabel("-" + a.UniqueID() + "-"))
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
Ah, the critical difference is that you have to create the window _before_ replacing the app instance.

I think it's fair to say you cannot replace the app once it has been used to show a window.

If you move the window creation to after the app was set then the code will be unblocked.

**Comment by rad756** [comment]
I confirmed as well that the above solution works.
Just find it strange it was working with the code example before 2.5.
That code had an error from the start and only became a problem due to something changing in v2.5, am I understanding this correctly?

If so then its probably best to close this issue.

Also thanks Andy!

**Comment by andydotxyz** [comment]
> That code had an error from the start and only became a problem due to something changing in v2.5, am I understanding this correctly?

That is one way to put it I guess. Having multiple app instances in a runtime is not supported, and so we have no tests around it. By creating multiple apps you will also have multiple instances of caches and all the background threads that keep an app alive.

Creating a window from an old app and then running a new app should never have worked, it's quite curious that it did.
I think this is indeed not an issue. If you wanted to resurrect it to be a supported usage you would have to completely quit the old app before creating a new one, in which case you might other issues as even that is not currently supported.
