### ISSUE TITLE
Improve how shortcut special keys for menu items are rendered on Windows and Linux

### ISSUE THREAD

**Issue by ErikKalkoken** [fyne-io/fyne#5108]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

With Fyne it is possible to define shortcuts and assign them to menu items. Those shortcuts are then rendered alongside the menu item to inform the user about them.

However, special keys (e.g. ALT, SHIFT, ..) are always rendered as symbols  - and apparently in macOS style -, which will most likely be confusing to many users on Windows and Linux.

Example from the Demo App:
![Screenshot from 2024-09-03 19-44-23](https://github.com/user-attachments/assets/a6e538bf-1604-4bd9-b8e6-af924586063c)

e.g. the 2nd symbol from the left is actually the ALT key

### Is it possible to construct a solution with the existing API?

No

### Describe the solution you'd like to see.

I would suggest to render all special keys as plain text on Windows and Linux. E.g. "Alt" and use the "+" key as separator, e.g. "Alt+G" or "Ctrl+C". This appears to be how most apps on Linux and Windows are doing it.

The following example is VS Code on Ubuntu/Gnome:

![Screenshot from 2024-09-03 19-58-09](https://github.com/user-attachments/assets/36b493ee-f861-4d24-85af-d8cfb818ef10)

And here LibreOffice Word on Ubuntu/Gnome:

![image](https://github.com/user-attachments/assets/abb6a1a2-8403-439e-a5f1-8e426ce0ead5)

**Comment by ErikKalkoken** [comment]
See also the related discussion on [Discord](https://discord.com/channels/953020122690359327/953030515152281650/1280584825773887509)

**Comment by andydotxyz** [comment]
Thanks so much for the fix, it is on develop and will be in v2.5.3
