### ISSUE TITLE
panic: NotInitialized: The GLFW library is not initialized

### ISSUE THREAD

**Issue by giuliohome** [fyne-io/fyne#5132]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Cannot run a second window after closing the first one

### How to reproduce

Simply `go run .`, then close the first windows that appears and the second will crash.

### Example code

```go
func main() {

	myApp := app.New()
	myWindow := myApp.NewWindow("Canvas")
	myWindow.Resize(fyne.NewSize(100, 100))
	myWindow.ShowAndRun()

	myApp2 := app.New()
	w := myApp2.NewWindow("Clock")
	w.ShowAndRun() 

}
```

### Fyne version

latest

### Go compiler version

1.23.1

### Operating system and version

Alpine 3.21.0

### Additional Information

I understand that:

> An application should only have one runloop and so you should only call Run() once in your code. Calling it a second time will cause errors.

However, I want to run a second application from my code, after the user closes the first one. How should I handle this?

**Comment by giuliohome** [comment]
Sequentialized Full Demo Code (with Multi-Window Single-Instance Workaround).

```go
package main

import (
	"fmt"
	"image/color"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"fyne.io/fyne/v2/canvas"
)

func updateTime(clock *widget.Label) {
	formatted := time.Now().Format("Time: 03:04:05")
	clock.SetText(formatted)
}

func tidyUp() {
	fmt.Println("Exited")
}

func main() {
	myApp := app.New()

	w := myApp.NewWindow("Clock")
	myWindow := myApp.NewWindow("Canvas")

	myWindow.SetOnClosed(func() {
		w.Show()
	})

	myCanvas := myWindow.Canvas()
	blue := color.NRGBA{R: 0, G: 0, B: 180, A: 255}
	rect := canvas.NewRectangle(blue)
	myCanvas.SetContent(rect)

	go func() {
		time.Sleep(time.Second * 3)
		green := color.NRGBA{R: 0, G: 180, B: 0, A: 255}
		rect.FillColor = green
		rect.Refresh()
	}()

	myWindow.Resize(fyne.NewSize(200, 200))
	myWindow.Show()

	clock := widget.NewLabel("")
	updateTime(clock)

	w.SetContent(clock)
	go func() {
		for range time.Tick(time.Second) {
			updateTime(clock)
		}
	}()

	w.Resize(fyne.NewSize(200, 200))

	myApp.Run()
}
```
This sometimes triggers an exception, so I repen the issue.

# Segmentation Fault:

- The invalid memory address or nil pointer dereference and subsequent SIGSEGV: segmentation violation errors indicate that the code is trying to access memory that hasn't been properly initialized, possibly related to GLFW (which Fyne uses for window handling).
- This could be a bug in Fyne’s GLFW driver, especially since it’s happening in the input.go file of the glfw package. It might be triggered by the way your application manages multiple windows or interacts with the canvas.

```
localhost:~/myfyne$ go run full.go 
2024/09/11 15:54:42 Fyne error:  Error parsing user locale
2024/09/11 15:54:42   Cause: language: tag is not well-formed
2024/09/11 15:54:42   At: /home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/lang/locale.go:35
2024/09/11 15:54:42 Fyne error:  Error parsing user locale
2024/09/11 15:54:42   Cause: language: tag is not well-formed
2024/09/11 15:54:42   At: /home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/lang/locale.go:23
Exited
localhost:~/myfyne$ go run full.go 
2024/09/11 15:54:58 Fyne error:  Error parsing user locale
2024/09/11 15:54:58   Cause: language: tag is not well-formed
2024/09/11 15:54:58   At: /home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/lang/locale.go:35
2024/09/11 15:54:58 Fyne error:  Error parsing user locale
2024/09/11 15:54:58   Cause: language: tag is not well-formed
2024/09/11 15:54:58   At: /home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/lang/locale.go:23
Exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6c258]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetInputMode.func1(0xac0480?, 0x33001, 0x34001)
	/home/bob/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/input.go:394 +0x18
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetInputMode(0xd70980?, 0xd6d578?, 0x1?)
	/home/bob/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/input.go:394 +0x13
fyne.io/fyne/v2/internal/driver/glfw.(*window).processMouseMoved(0xc000101c00, 0x4068c00000000000, 0x3ff0000000000000)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/window.go:380 +0x27c
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseMoved(...)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/window_desktop.go:393
github.com/go-gl/glfw/v3.3/glfw.goCursorPosCB(0xc00004bb00?, 0x4068c00000000000, 0x3ff0000000000000)
	/home/bob/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/input.go:339 +0x3e
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1596 +0x3f
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	/home/bob/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/window.go:931 +0x13
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).pollEvents(...)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/loop_desktop.go:25
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0x47a132?)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/loop.go:136 +0x1a5
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc0002d91e0)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/internal/driver/glfw/driver.go:164 +0x73
fyne.io/fyne/v2/app.(*fyneApp).Run(0xc000133c20)
	/home/bob/go/pkg/mod/fyne.io/fyne/v2@v2.5.1/app/app.go:68 +0x65
main.main()
	/home/bob/myfyne/full.go:61 +0x262
exit status 2
localhost:~/myfyne$
```

**Comment by giuliohome** [comment]
After further testing, the panic and segmentation fault error has not reoccurred. It appears to be a rare issue and may have been triggered by an unusual edge case in my setup. I'll monitor the situation, and if the problem persists or becomes more frequent, I will reopen the issue with additional information. Thanks for your time and support!

**Comment by dweymouth** [comment]
I have also been seeing this panic when my app quits. Even an issue that happens only rarely is still an issue that needs to be addressed. Reopening

**Comment by andydotxyz** [comment]
They are different stacks, Drew's seems to be referencing a nil event queue

**Comment by giuliohome** [comment]
As for my example, while the latest version of the workaround seems stable, I could easily revert to previous versions where the panic error was more frequent. However, I'm unsure if you have an opinionated approach to writing code and whether you'd consider alternative examples too contrived. That's why I was considering closing the issue

**Comment by andydotxyz** [comment]
> 1. FWIW, this is the stack trace from the code in my [first, initial post](https://github.com/fyne-io/fyne/issues/5132#issue-2519051936). [↩](#user-content-fnref-1-8d6a39e2ea61898c1de051bcd9c6a93e)

Oh, in that case this is not a new issue - we do not support running multiple applications at runtime and there is a bug to track the fact that a second cannot be started after the first.

Why not just use the same application instance, showing and hiding windows - that is how it is designed?

**Comment by andydotxyz** [comment]
Closed as duplicate of #3063

**Comment by dweymouth** [comment]
Is this really a duplicate? This issue is showing up without attempting to run an app twice from the same process, it shows up occasionally just on a regular app.Quit()

**Comment by andydotxyz** [comment]
> Is this really a duplicate? This issue is showing up without attempting to run an app twice from the same process, it shows up occasionally just on a regular app.Quit()

I read the code linked from "first, initial post" a couple of messages ago and it was clearly showing two apps.

**Comment by andydotxyz** [comment]
> Unsubscribed from this useless thread.

Unfortunately you deleted all of the information so we can no longer reason over what was or was not a unique bug report...
