### ISSUE TITLE
Can't build and can't install demo

### ISSUE THREAD

**Issue by paulober** [fyne-io/fyne#5137]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

If i try to run the demo or my project which both use fyne i get following output:
```console
go run main.go
package command-line-arguments
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in C:\Users\MyUser\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v2.1\gl
```

### How to reproduce

1. New folder
2. go mod init something.com
3. `go get fyne.io/fyne/v2`
4. create main file with demo
5. `go run main.go`

### Example code

The one from your README.md

### Fyne version

2.5.1

### Go compiler version

1.23.1

### Operating system and version

Windows 11 23H2 (OS Build 22631.4169)

**Comment by dweymouth** [comment]
The Go compiler cannot find your C compiler - see the setup instructions in https://docs.fyne.io/started/
