### ISSUE TITLE
Entry text input resize window

### ISSUE THREAD

**Issue by cdavid14** [fyne-io/fyne#514]
**Describe the bug**
When the user put an text bigger than Entry size the window its being resized [screenshot1] and when the text is removed, the overflow stills [screenshot2] , am i doing something wrong? it's my first time using Fyne.
i've tested this issue with main and develop branch and no success..

**To Reproduce**
1. Type random text bigger than screen
2. Erase the text
3. See error

**Code**
```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	a.Settings().SetTheme(theme.LightTheme())
	w := a.NewWindow("Box Manager")
	w.SetContent(fyne.NewContainer(
		fyne.NewContainerWithLayout(
			layout.NewGridLayout(1),
			group("Buscar", true,
				fyne.NewContainerWithLayout(layout.NewFormLayout(),
					label("Smartcard:"),
					entry("500123456"),
				),
				fyne.NewContainerWithLayout(layout.NewFormLayout(),
					label("MAC:"),
					entry("XX:XX:XX:XX:XX:XX"),
				),
				fyne.NewContainerWithLayout(layout.NewGridLayout(1),
					button("Search", buscar),
				),
			),
			group("Resultados da busca", true,
				fyne.NewContainerWithLayout(layout.NewGridLayout(1)),
			),
		),
	))
	w.SetFixedSize(true)
	w.CenterOnScreen()
	w.Show()
	a.Run()
}

func buscar() {

}

func label(text string) *widget.Label {
	w := widget.NewLabel(text)
	return w
}

func entry(placeholder string) *widget.Entry {
	w := widget.NewEntry()
	w.SetPlaceHolder(placeholder)
	return w
}

func button(text string, action func()) *widget.Button {
	w := widget.NewButton(text, action)
	return w
}

func group(title string, visible bool, children ...fyne.CanvasObject) *widget.Group {
	w := widget.NewGroup(title, children...)
	if visible {
		w.Show()
	} else {
		w.Hide()
	}
	return w
}
```

**Screenshots**
![att3](https://user-images.githubusercontent.com/5961014/68086824-8122c100-fe2e-11e9-942d-429f6092ec17.png)
![att1](https://user-images.githubusercontent.com/5961014/68086483-6438be80-fe2b-11e9-88b8-cd99013457e2.png)
![att2](https://user-images.githubusercontent.com/5961014/68086495-82062380-fe2b-11e9-99a6-a0e3c58e83f1.png)

**Device:**
 - OS: Linux Mint 
 - Version: 19.2 Tina
 - Go version: go version go1.13.3 linux/amd64
 - Fyne version: 8b1963e4eeee1aa7be94a1177b0e02c12a4c83e4

**Comment by andydotxyz** [comment]
Isn’t the bug here that the entry causes the window to expand? If so a duplicate of #378 - there is a workaround to put the entry in a scroll container.

**Comment by cdavid14** [comment]
> Isn’t the bug here that the entry causes the window to expand? If so a duplicate of #378 - there is a workaround to put the entry in a scroll container.

i've tried change the function below to put the Entry inside ScrollContainer but he create an vertical scroll and the bug stills..

I'll wait for #132 

```
func entry(placeholder string) *widget.ScrollContainer {
	w2 := widget.NewEntry()
	w2.SetPlaceHolder(placeholder)

	w := widget.NewScrollContainer(w2)
	w.Hidden = true
	return w
}
```
**Screenshots**
![att1](https://user-images.githubusercontent.com/5961014/68089407-424d3500-fe47-11e9-84a8-c2077b128f7c.png)
![att2](https://user-images.githubusercontent.com/5961014/68089410-45e0bc00-fe47-11e9-8d09-4491ab372f81.png)
![att3](https://user-images.githubusercontent.com/5961014/68089412-4711e900-fe47-11e9-9ba4-1985942bbd4a.png)

**Comment by andydotxyz** [comment]
Oops, thanks - I forgot that we had not yet released the horizontal scroll!...
