### ISSUE TITLE
How to do drag and drop recognition of files and drag and drop reading of folder paths？

### ISSUE THREAD

**Issue by Xzhiming** [fyne-io/fyne#5153]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

yes

### Is it possible to construct a solution with the existing API?

Drag and drop the file to the window to recognize the file and read its contents; Drag and drop the folder to read its path.

### Describe the solution you'd like to see.

Drag and drop the file to the window to recognize the file and read its contents; Drag and drop the folder to read its path.

**Comment by andydotxyz** [comment]
Use `Window.SetOnDropped` to be informed when user drops a file into your window

**Comment by andydotxyz** [comment]
This was answered (not really a feature request after all) - please use discussions to ask questions in the future.
