### ISSUE TITLE
Scrolling is really slow

### ISSUE THREAD

**Issue by Timmmm** [fyne-io/fyne#516]
I just had a play with Fyne's demo app on Mac 10.14. A few things stood out, one of which is that scrolling is *really* slow. If you want a good first impression I'd fix that!

**Comment by andydotxyz** [comment]
Thanks for the feedback. Can you confirm what scroll action you were performing? Is this a scroll wheel, arrow keys, touchpad gesture or click and drag scroll bar?

**Comment by Timmmm** [comment]
Both scroll wheel and dragging the scroll bar with an external mouse. There were other issues too, but I feel like this is the biggest thing that put me off, and I don't want to deluge you with issues that you're probably aware of. :-)

**Comment by andydotxyz** [comment]
Please feel free to report all bugs if they do not already appear in the issue list :)
We have about 3 weeks to next release and want to make it great!

With regards to slow scroll can you report more about your device, perhaps with a video capture?
I cannot replicate what you are describing unfortunately.
Could you also confirm the version of Fyne you are using?

**Comment by Timmmm** [comment]
Sure, I'm using 98fc45eeb2f12a3d3d0ad62f485883130e292312, Macbook Pro with Intel Iris Pro graphics. Easily capable of scrolling! Here's a screen capture, first with the trackpad, and then the mouse:

[fyne_scrolling.mov.zip](https://github.com/fyne-io/fyne/files/3819019/fyne_scrolling.mov.zip)

**Comment by andydotxyz** [comment]
Hmm, yes I think I see from that.
I expect it relates to object caching that will be part of the list widget proposed for 1.2 release.

However if you were able to switch to Fyne develop branch you could tell if the work we have done so far improves it for you :)

**Comment by Timmmm** [comment]
I tried `develop` and it was maybe *slightly* better but I might be imagining it. Still really bad.

**Comment by andydotxyz** [comment]
Is it possible to check the v1.2.0-beta1 tag and see if you think this is better?
I think we probably have lots of improvement to be made in this area but interested to see what your tests show.

**Comment by Timmmm** [comment]
I just tried `develop` and unfortunately the "Scroll" tab with the horizontal and vertical buttons is still really slow. The "Full Scroll" page is fine though.

**Comment by andydotxyz** [comment]
This is very strange as it is incredibly speedy at this end.
If it's just the items with text scrolling then I suspect we have a chaching bug in the calculations.
Is it possible to run a profiler to see where it's struggling on your current setup?

**Comment by Timmmm** [comment]
Here you go. Not sure how useful this is, but it does seem to spend a suspicious amount of time deleting textures.

[pprof001.svg.zip](https://github.com/fyne-io/fyne/files/3932772/pprof001.svg.zip)

**Comment by andydotxyz** [comment]
Thanks for this @Timmmm it's very strange that the CPU usage is not higher overall with the type of lag you are describing.
I have made another change that's on develop now which may help.
When you got that profile output was it during some intensive scrolling?

**Comment by andydotxyz** [comment]
Comments from @toaster are that this is way better now. What do you find @Timmmm ?

**Comment by Timmmm** [comment]
Yep much better for me too.

**Comment by justjosias** [comment]
Scrolling through a label with lots of text is extremely slow and buggy. In addition, it is generally slow and lagging.

**Comment by andydotxyz** [comment]
Can you please confirm the code for this label, I.e. what settings (wrap, style etc)?
Text handling does indeed need optimisation and we are working on possible solutions.

Additionally you mentioned it being buggy - can you expand on the types of bug you see when scrolling?
