### ISSUE TITLE
Unable to scroll on macOS when Fyne app is in background

### ISSUE THREAD

**Issue by sdassow** [fyne-io/fyne#5162]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Usually on macOS it is possible to scroll in windows without having focus.
With Fyne apps it is different and can be tested with fyne_demo.

### How to reproduce

1. Start fyne_demo
2. Move window to the side
3. Change focus to another window with fyne_demo still visible
4. Hover over fyne_demo without clicking/focus
5. Try to scroll

### Example code

```
$ cd cmd/fyne_demo/
$ go run .
2024/09/25 17:02:11 Lifecycle: Started
2024/09/25 17:02:12 Lifecycle: Entered Foreground
...
```

### Fyne version

Noticed in 2.3 or something, and now still in develop

### Go compiler version

Any

### Operating system and version

macOS, multiple versions

**Comment by andydotxyz** [comment]
This was reported in #3495 and then found to be working...

Perhaps it relates to the macOS hardware. We tested and it's all good on M2... which model still has this problem?

**Comment by sdassow** [comment]
It's on older hardware indeed: MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by sdassow** [comment]
Works on the same model with more recent macOS (Sonoma).
