### ISSUE TITLE
Minimum size of a window

### ISSUE THREAD

**Issue by MonaChanDev** [fyne-io/fyne#5174]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Hi, I've just been using Fyne to build GUIs, but I immediately noticed that it's not possible to set a minimum size for the window. 

I believe that this lack (or my ignorance) does not favor the correct use of the application by the user, since (as you can see from the photo attached below) it does not allow the window to be moved without resizing it first. Plus it doesn't show the window title

![immagine](https://github.com/user-attachments/assets/74d037bc-c508-40b0-8f72-ce25b732d791)

Using the Resize() function obviously apparently solves the problem, but the user can still resize the window as in the previous situation. To solve this problem, in my ignorance with this toolkit, I found myself having to set "\t\t\t\t\t\t\t\t\t\t\t\" inside a label , thus obtaining a very approximate minimum dimension, at least in width

### Describe the solution you'd like to see.

It would be convenient to find a similar function

`w := a.NewWindow("ToDo", 800, 600)`

Or

`w.SetMinSize(800, 600)`

You could also act on setting a minimum size for the containers instead of the window

**Comment by andydotxyz** [comment]
> Hi, I've just been using Fyne to build GUIs, but I immediately noticed that it's not possible to set a minimum size for the window.

The minimum size of a window is determined by the minimum size of the content inside it.

> Using the Resize() function obviously apparently solves the problem

Yes, `Window.Resize()` is the correct way to ask the system to use more space than the minimum.

Why would you want the user to be disallowed from making the window as small as the content inside it allows?
What happens on a smaller screen, or where the user wants to arrange their own desktop to fit as much on screen as possible?

**Comment by MonaChanDev** [comment]
> Why would you want the user to be disallowed from making the window as small as the content inside it allows?

The point is that conditions like these can be requested by the user himself (as in my case, although I understand that there are people who will not believe their ears). Furthermore, this could also damage the development of borderless windows for something more custom. If it is not possible to act directly on the window that is fine, but at least a minimum size is allowed for widgets and containers without using tricks such as tabulation

**Comment by andydotxyz** [comment]
> The point is that conditions like these can be requested by the user himself

I don't understand this sentence. What is being requested that we should disallow?

>  this could also damage the development of borderless windows

Well; we don't support borderless except the splash - I really don't see how these relate as a Borderless will respect the `Window.Resize` and also there are no border overlaps to worry about.

**Comment by MonaChanDev** [comment]
🤡

**Comment by andydotxyz** [comment]
> 🤡

I have no idea what this means. Please can you explain what this was adding to the topic?
