### ISSUE TITLE
TextWrapBreak modifies text content (\n are added)

### ISSUE THREAD

**Issue by zakirullin** [fyne-io/fyne#5177]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

 Word wrapping is expected to be purely visual, no changes should be made to the content. Now the text content of `Entry` is modified - `\n` characters are added to the text

### How to reproduce

1) Create multiline entry
2) Set text wrapping to either `TextWrapBreak` or `TextWrapWord`
3) Enter one long enough line of text without `\n` so that word wrapping is applied
4) `Entry.Text` now contains `\n` and we can't know the original content

### Example code

```go
e := widget.NewMultilineEntry()
e.Wrapping = fyne.TextWrapBreak
```

### Fyne version

v2.5.1

### Go compiler version

1.22.5

### Operating system and version

macOS High Sierra

**Comment by andydotxyz** [comment]
I cannot replicate the problem from the code provided.

Additionally I cannot make the reported newlines appear with this code:

```go
package main

import (
	"log"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewMultiLineEntry()
	hello.SetText("Hello A very long line")
	hello.Wrapping = fyne.TextWrapWord
	w.SetContent(hello)

	go func() {
		for {
			time.Sleep(time.Second)
			log.Println("Content", hello.Text)
		}
	}()

	w.ShowAndRun()
}
```
