### ISSUE TITLE
Dropdown initial position is wrong.

### ISSUE THREAD

**Issue by Timmmm** [fyne-io/fyne#518]
Using 98fc45eeb2f12a3d3d0ad62f485883130e292312, on MacOS 10.14, on a Macbook Pro with Intel Iris Pro graphics.

Sometimes when you open a dropdown there is a brief flash with it in the wrong position. Screen capture below.

[fyne_menu_position.mov.zip](https://github.com/fyne-io/fyne/files/3819026/fyne_menu_position.mov.zip)

**Comment by andydotxyz** [comment]
Hmm. I have reworked the popup layout code somewhat for the 1.2 release - can you please try to replicate with the "develop" branch? I have not seen that flicker on my testing on macOS.

**Comment by Timmmm** [comment]
Still a problem in `develop`. In fact when it happened on `develop` it wasn't a brief flash - the dropdown actually stayed in position at the top-left of the window and I could interact with it.

**Comment by andydotxyz** [comment]
This is a good thing :) fixing a static error is much easier than a flicker ;)

**Comment by andydotxyz** [comment]
Resolves on master and ready for testing before 1.2
