### ISSUE TITLE
systray error: failed to register: The name org.kde.StatusNotifierWatcher was not provided by any .service files

### ISSUE THREAD

**Issue by innerdev** [fyne-io/fyne#5182]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Trying to use systray. Getting the following error:
```
systray error: failed to register: The name org.kde.StatusNotifierWatcher was not provided by any .service files
```
I'm under Linux Mint 22 with Mate DE.

How to fix the bug? I was trying to connect fyne with github.com/getlantern/systray with no success (getlantern/systray IS working under my system).

Source (it is from example):

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}
```

How to fix it?

### How to reproduce

Compile source code under Linux Mint 22 with Mate DE.

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}
```

### Fyne version

2.5.1

### Go compiler version

go1.22.8 linux/amd64

### Operating system and version

Linux Mint 22 with Mate DE

**Comment by andydotxyz** [comment]
The GetLantern project uses legacy "XEmbed" protocol for displaying system tray.
The Fyne system tray is lighter and uses the newer "StatusNotifier" protocol.

Mate uses outdated protocols by default and you may need to load a plugin to support the more recent system.
Consider checking the Mate issue tracker, for example https://github.com/mate-desktop/mate-desktop/issues/286.

**Comment by andydotxyz** [comment]
Closing because this isn't an issue with Fyne our the fyne systay module either.
