### ISSUE TITLE
Looking for a dialog similar to NewFileOpen() that allows file data entered from API

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#5187]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I am writing a multi platform application using Fyne. I used to have the UI and backend all as a single application.

Now I have broken apart frontend and backend using an API between them. The monolithic application uses dialog.NewFileOpen(). Now that I have broken the application apart I see that dialog.NewFileOpen() no longer works. First, it does not do anything in a wasm (of course). In a natively complied client, it lists the files on the client instead of the server.

### Is it possible to construct a solution with the existing API?

dialog.NewFileOpen() is the base API for this enhancement.

### Describe the solution you'd like to see.

Since I have an existing API between client and server, I am looking for a FileOpen dialog that takes its file / directory information data from the API itself. I assume there would need to be a new parameter with a list of file URLs added to the "NewFileOpen" for initialization as well as a callback which is called when the user selects a directory object.

Essentially, I would like to split the dialog.ShowFileOpen() into a frontend UI and a backend file info API. The frontend simply displays the file list given to it by the backend and provides a callback(s) to the backend when there is a UI event that requires a new file list from the back end. I am sure dialog.ShowFileOpen() is already organized like this. There is just no interface between front end and back end exposed via the API right now.

**Comment by Jacalz** [comment]
I don't understand what you are trying to say or what `notify.NewFileOpen()` refers to given that we don't have a `notify` package here. Why can you not use `dialog.NewFileOpen()` and pass in a callback there that then sends your data to the backend?

**Comment by brucealthompson** [comment]
**I don't understand what you are trying to say or what notify.NewFileOpen() refers to given that we don't have a notify package here.**

Very sorry. I meant dialog.NewFileOpen().

**Why can you not use dialog.NewFileOpen() and pass in a callback there that then sends your data to the backend?**

I believe you have the use case backwards. The files to select are on the server, not the client. The client runs the UI front end. The client can actually be a wasm that is served from the server. So the client UI is selecting a file(s) on the server.

**Comment by andydotxyz** [comment]
If you want to mount a remote file dataset then you probably want to register the file provider ("repository").
The file browser can then be told to look there instead ("SetLocation"). You should not need to do any modification to the toolkit to make this happen.

**Comment by andydotxyz** [comment]
> The only issue is I do not have an API call in the fyne toolkit that can display the file list once I get it from the server.

Yes you do, that is what the repository registering can support - any type of filesystem can be loaded into the storage repository and worked with / iterated over etc.

>  I am sure dialog.ShowFileOpen() is already organized like this. There is just no interface between front end and back end exposed via the API right now.

Yes it is set up to do this - the interface between the front and back is the storage API which loads data through the registered storage repositories. You can see that Fyne ships with 3 turned on "file://", "http://" and "https://" though for obvious reasons we open the file dialog in the file space not the web repository space.

> For example, dialog.ShowFileOpen() is currently a NULL implementation in a fyne generated wasm.

This comment is not making sense to me - there is no code inside the dialog package that can possible return `nil` instead of an instance of the file dialog, at least that I can see. What test are you performing and where are you seeing the `nil`?

**Comment by brucealthompson** [comment]
Yes you do, that is what the repository registering can support - any type of filesystem can be loaded into the storage repository and worked with / iterated over etc.

OK. I think this may be my misunderstanding I see an API called:
 func (f *[FileDialog](https://pkg.go.dev/fyne.io/fyne/v2@v2.4.4/dialog#FileDialog)) SetLocation(u fyne.ListableURI)

My guess is this API can be used to use an http based file repository instead of the local filesystem. Please let me try this. I will close this ticket myself once I have proven that it works.

> This comment is not making sense to me - there is no code inside the dialog package that can possible return nil instead of an instance of the file dialog, at least that I can see. What test are you performing and where are you seeing the nil?

I think this is my misunderstanding again. I used dialog.ShowFolderOpen() instead of dialog.NewFolderOpen(). dialog.ShowFolderOpen()  does nothing in js likely because there is no default file repository set for js.

**Comment by andydotxyz** [comment]
> If their any example code that shows how to use the http repository in the context of fyne?

It works just like file - you would pass the location a URI that starts https:// instead of file://

**Comment by brucealthompson** [comment]
> It works just like file - you would pass the location a URI that starts https:// instead of file://

OK. It sounds like I need to extend the http repository since my implementation will actually support CanList() and List() as I am actually supporting an http based view into a filesystem on a server.

Thanks for all your help. I made the decision to use fyne about 18 months ago and have never regretted it.

I will close this ticket when I have completed the implementation.

**Comment by andydotxyz** [comment]
Ag yes, those are missing I forgot sorry.
Are you using, or would you consider, WebDAV? If that was the case I could see an argument for adding the repository type to Fyne or fyne-x...

**Comment by brucealthompson** [comment]
> Are you using, or would you consider, WebDAV? If that was the case I could see an argument for adding the repository type to Fyne or fyne-x...

I personally do not need all of WebDAV. I just need to be able to pick a directory in a hierarchical directory list. But of course if there was a WebDAV repository type it would add a LOT of value to fyne.

**Comment by andydotxyz** [comment]
I guess this should be closed in preference of #5200 ?

**Comment by Jacalz** [comment]
I agree. Also worth noting for future requests, I just want to say that I'm not a fan of using the wording "I need". Saying that you need something sounds like trying to force us to do something and that's not cool. If would have been better to just label the issue something like "Support inputing data from API in FileDialog" in this case :)

**Comment by brucealthompson** [comment]
Hmmmm……

 

So there is no interest in developing a fyne repository for WebDav?

**Comment by andydotxyz** [comment]
> So there is no interest in developing a fyne repository for WebDav?

I don't think anybody said that.

This is not a feature request for WebDav - the title issue is implemented pending a bug fix which is why I proposed closing it.

**Comment by brucealthompson** [comment]
Added a new feature request for webdav repository. 
https://github.com/fyne-io/fyne/issues/5203
