### ISSUE TITLE
README example stuck on Windows when running `go run .` with nothing appearing

### ISSUE THREAD

**Issue by devhindo** [fyne-io/fyne#5193]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

basically I have the same issue as #4750

### How to reproduce

go run .

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewLabel("Hello World!"))
	w.ShowAndRun()
}

### Fyne version

2.5.1

### Go compiler version

1.22.8

### Operating system and version

Windows 11

**Comment by andydotxyz** [comment]
Please wait a few minutes - the first build on windows can take a long time.

**Comment by andydotxyz** [comment]
This is not a bug. Windows C compilers are not very fast and the first time you build a Fyne app we have to compile all the graphics drivers and various system tool.

This will not happen again until you do a major Fyne upgrade.

**Comment by devhindo** [comment]
I have wsl. Should I use it? Is it supported?

**Comment by andydotxyz** [comment]
WSL will work. But I you are using a toolkit that can build for any system then I would recommend a windows terminal so you are building windows apps.
Otherwise you are building linux apps and using a compatibility layer for Windows - doesn't that partly defeat the purpose?

**Comment by devhindo** [comment]
I'm mainly building an Android/IOS app if this would hlep. So, Should I go with Windows?

**Comment by andydotxyz** [comment]
It doesn't matter a lot - the compilers on Windows are slow :(. If you are not building apps to run on the current platform it's probably irrelevant if you use WSL. However it's probably worth noting that our docs for windows are using MSYS2 and mingw not the WSL system.
