### ISSUE TITLE
Package command fails on OpenBSD

### ISSUE THREAD

**Issue by sdassow** [fyne-io/fyne#5195]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

OpenBSD [tar](https://man.openbsd.org/tar) does not support the -J flag and fails during `fyne package`.

### How to reproduce

Run `fyne package --os openbsd --release` on OpenBSD.

### Example code

Any code.

### Fyne version

any

### Go compiler version

any

### Operating system and version

OpenBSD any version

**Comment by andydotxyz** [comment]
Ah shoot. When we moved to .xz checks were made to ensure it was supported everywhere. we missed this.

Can it be enabled through an external plugin or will we need to revert to .tar.gz for BSD usages?

**Comment by sdassow** [comment]
We could use `gtar` (GNU tar) instead, which can be installed from packages/ports.

**Comment by andydotxyz** [comment]
> Other than that, using gtar wouldn't be the best user experience since it means installing something else first.

Unusual for someone to reply to their own suggestion going against it ;).

It sounds like we have no choice - should we just create .gz when run on OpenBSD? I'm not sure it matters too much.
It may also mean we have to use that when packaging /for/ openBSD as well, or you won't be able to open the archives.

**Comment by sdassow** [comment]
> > Other than that, using gtar wouldn't be the best user experience since it means installing something else first.
> 
> Unusual for someone to reply to their own suggestion going against it ;).

Just thinking out loud ;).

> It sounds like we have no choice - should we just create .gz when run on OpenBSD? I'm not sure it matters too much.

I'll have a look and brew something up. When I found this I just created an issue for later.

> It may also mean we have to use that when packaging /for/ openBSD as well, or you won't be able to open the archives.

For distribution it doesn't matter as much.
For source distribution not at all since that's usually handled in the ports tree for proper OpenBSD packaging as a build dependency.
For binary distribution it means a small inconvenience having to manually install GNU tar and/or xz first.

**Comment by andydotxyz** [comment]
> For binary distribution it means a small inconvenience having to manually install GNU tar and/or xz first.

Sorry I missed this before commenting on the PR.
Typically we want to put the package install / additional dependency on the developer not the end user. Is it a bad thing to adapt the fix so it avoids that compression for both developer and user?

**Comment by sdassow** [comment]
Solve in the PR by using the target OS to switch format for OpenBSD.
