### ISSUE TITLE
binding.UntypedList does not call data handler's if a new slice is set of the same size of the previous slight even if the slice is completely different.

### ISSUE THREAD

**Issue by steampoweredtaco** [fyne-io/fyne#5196]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

The handler will not be called back in cases where the length of the set slice is the same as the old one even if the slice is different. 

My expectation would be to always get the data listener handlers a callback whenever Set() is called when the size of the list is the same but the slice pointer or content is different.

To simplify, it probably makes sense to always call the data listeners even if the slice passed to Set() is identical; the data listener can make equality checks if that's an important optimization.

### How to reproduce

See example code below.

### Example code

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2/data/binding"
	"sync"
	"time"
)


func main() {
	var wg sync.WaitGroup
	untypedListBinding := binding.NewUntypedList()
	// will trigger for initial, set {1,1}, but not set {2,2}
	// will not trigger for 2,2
	// for the empty trigger for the first bind
	wg.Add(1)
	untypedListBinding.AddListener(binding.NewDataListener(func() {
		defer wg.Done()
		v, _ := untypedListBinding.Get()
		fmt.Printf("%+v\n", v)
	}))

	wg.Wait()

	wg.Add(1)
	untypedListBinding.Set([]any{1, 1})
	wg.Wait()

	wg.Add(1)
	untypedListBinding.Set([]any{2, 2})
	done := make(chan struct{})
	go func() {
		wg.Wait()
		done <- struct{}{}
	}()
	select {
	case <-done:
		fmt.Println("no bug no problem")
	case <-time.After(10 * time.Second):
		fmt.Println("timeout, didn't get all three expected callbacks")
		wg.Done()
		<-done
		wg.Wait()
	}
```
Output:
```
[]
[1 1]
timeout, didn't get all three expected callbacks

Process finished with the exit code 0
```
 I would expect to see [2 2] and the "no bug no problem" printed if it was working OK.

### Fyne version

4fab19a03065c1dde93f84dd8691393669d22e5e

### Go compiler version

go version go1.23.1 windows/amd64

### Operating system and version

Windows 10

### Additional Information

The issue is simply that the code will only call .trigger() when the size of the slice is the same as the pervious slice set; it probably should always call trigger, but if it wants to be tricky and not call if the slice being set hasn't change that would be a more difficult problem to solve.

The Reload() method also won't fix this, although it isn't exposed by the interface returned by NewUntypedList even though you can get it of you know about the fyne internals a bit.

Here is a much more involved test where I was checking all of the permutations I could think of to make sure there were no other bugs such as with the GetValue(index) paths and it also tests including using Reload():
```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2/data/binding"
	"sync"
	"time"
)

func main() {
	untypedListBinding := binding.NewUntypedList()

	var count int
	var expectedCount int

	var wg sync.WaitGroup
	firstTime := true
	untypedListBinding.AddListener(binding.NewDataListener(func() {
		// ignore the first time listener is called as it is by design.
		if firstTime {
			firstTime = false
			return
		}
		defer wg.Done()
		count++
		fmt.Printf("listener call count: %d, expected count %d\n", count, expectedCount)
		data, err := untypedListBinding.Get()
		fmt.Printf("boundList: %+v error: %+v\n", data, err)
		if len(data) != untypedListBinding.Length() {
			panic("this should never happen")
		}
		for i := range data {
			v, err := untypedListBinding.GetValue(i)
			if err != nil {
				panic("this should never happen")
			}
			if data[i] == v {
				continue
			}
			fmt.Printf("At run %d internal indexed base items not updated correctly! (data[%d]=%+v) != (GetItem(%d)=%+v)", expectedCount, i, data[i], i, v)
		}
	}))
	expectedCount++
	fmt.Println("1) Initial binding works fine")
	wg.Add(1)
	err := untypedListBinding.Set([]any{0})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	fmt.Println("2) Adding more values works fine")
	wg.Add(1)
	err = untypedListBinding.Set([]any{0, 1})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	wg.Add(1)
	fmt.Println("3) Adding more values work fine if new slice older indexes do not match older bound slice")
	err = untypedListBinding.Set([]any{3, 1, 2})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	wg.Add(1)
	fmt.Println("4) Less values work fine")
	err = untypedListBinding.Set([]any{0, 1})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	wg.Add(1)
	fmt.Println("5) Adding less values when older index is change works fine")
	err = untypedListBinding.Set([]any{3})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	wgFin := make(chan struct{})
	wg.Add(1)
	fmt.Println("6) Changing the slice with set but not changing size will result in no listener being called, this is a bug")
	err = untypedListBinding.Set([]any{4})
	if err != nil {
		panic(err)
	}
	go func() {
		wg.Wait()
		wgFin <- struct{}{}
	}()
	// To demonstrate the bug we need to wait and see a bit that the handler gets called
	deadline := time.NewTimer(10 * time.Second)
	select {
	case <-wgFin:
		fmt.Println("bug was not hit?!")
	case <-deadline.C:
		wg.Done()
		<-wgFin
		fmt.Println("Timed out waiting for binding update")
	}

	expectedCount++
	fmt.Println("7) Adding a slice with more values to show the data handler is called but expected count is now off")
	wg.Add(1)
	err = untypedListBinding.Set([]any{0, 1, 2})
	if err != nil {
		panic(err)
	}
	wg.Wait()

	expectedCount++
	wgFin = make(chan struct{})
	wg.Add(1)
	fmt.Println("8) Updating with same size but different values and trying a workaround to call Reload, but that still does not trigger an update, this is a bug?")

	err = untypedListBinding.Set([]any{3, 4, 5})
	if err != nil {
		panic(err)
	}
	reloadableBinding, ok := untypedListBinding.(binding.ExternalUntypedList)
	if !ok {
		panic("invalid test")
	}
	// OK to call Reload after Set and not get a double wait due to the pr
	// Set bug as described above.
	reloadableBinding.Reload()
	go func() {
		wg.Wait()
		wgFin <- struct{}{}
	}()
	// To demonstrate the bug we need to wait and see a bit that the handler gets called
	deadline = time.NewTimer(10 * time.Second)
	select {
	case <-wgFin:
		fmt.Println("bug was not hit?!")
	case <-deadline.C:
		wg.Done()
		<-wgFin
		fmt.Println("Timed out waiting for binding update, two opportunities missed to call handler")
	}
}
```

Output:
```
1) Initial binding works fine
listener call count: 1, expected count 1
boundList: [0] error: <nil>
2) Adding more values works fine
listener call count: 2, expected count 2
boundList: [0 1] error: <nil>
3) Adding more values work fine if new slice older indexes do not match older bound slice
listener call count: 3, expected count 3
boundList: [3 1 2] error: <nil>
4) Less values work fine
listener call count: 4, expected count 4
boundList: [0 1] error: <nil>
5) Adding less values when older index is change works fine
listener call count: 5, expected count 5
boundList: [3] error: <nil>
6) Changing the slice with set but not changing size will result in no listener being called, this is a bug
Timed out waiting for binding update
7) Adding a slice with more values to show the data handler is called but expected count is now off
listener call count: 6, expected count 7
boundList: [0 1 2] error: <nil>
8) Updating with same size but different values and trying a workaround to call Reload, but that still does not trigger an update, this is a bug?
Timed out waiting for binding update, two opportunities missed to call handler
```
The interesting bits is line labeled **6)** (same as the simple example) and **7)** just proves that the binding still works with a different size. and **8)** uses a casting trick to get the right interface to call Reload() which shows even that will not trigger a bind call.  I am not sure if that is a bug or not.

For clarity,  **1-5)** are all things working as expected.

**Comment by andydotxyz** [comment]
Binding a list informs you when it materially changes (different count of entries) much like a Map will call back if keys are added or removed.

Bindings of a collection of types such as these are for connecting with the collection widgets. Each item inside this containing parent type will be updated if the child data changes. In this way setting a whole new slice will update the child items if their data has changed. i.e. [1, 2, 3] then set to [1, 4, 3] will fire updates only the middle element. In this way it matches the Fyne mantra that you should always refresh the smallest possible scope for efficiency and a great user experience.

You can see this in action in fyne_demo as always, but an example list is:

```go
package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	data := binding.BindFloatList(&[]float64{1, 2, 3})
	list := widget.NewListWithData(data,
		func() fyne.CanvasObject {
			return widget.NewLabel("item x.y")
		},
		func(item binding.DataItem, obj fyne.CanvasObject) {
			f := item.(binding.Float)
			text := obj.(*widget.Label)
			text.Bind(binding.FloatToStringWithFormat(f, "item %0.1f"))
		})

	go func() {
		x := 2.0
		for {
			item, _ := data.GetItem(1)
			item.(binding.Float).Set(x)
			x += 1.0
			time.Sleep(time.Second)
		}
	}()

	w.SetContent(list)
	w.Resize(fyne.NewSize(80, 120))
	w.ShowAndRun()
}
```

**Comment by andydotxyz** [comment]
As indicated above I don't think there is an issue here, it the DataList types work as expected.

**Comment by steampoweredtaco** [comment]
I am doing this: **"Bindings of a collection of types such as these are for connecting with the collection widgets."**  

However, I think perhaps I'm relaying on the abstraction to much for a use case to general as fyne requires.  I guess I can live with that, but it would save me a lot of work if there was an option to trigger the listeners on any update, not just size change. I can also work around this by changing the expose binding from an untypedList to just an untypedData any where the any is a []MyType.  That is a work around and fits the model better for my usuage.

So in summary, not a bug and there are other ways to do what I need to with a different binding type for my use case.
----

I really would like you to understand my use case though for future consideration of the reusability of all the great bindings for some more general use cases.  I think bindings will be an important aspect of easily preventing races between user space code and the UI loop moving forward so I was hoping I could use it more intuitively.

I am not using the binding to drive data **into** UI widgets. The UI isn't the sink, it triggers something to build up a source based on various gui state and then it just happens to be producing an update that is an entire list.  The listener (userspace code) is a data sink that expects a list which is generated and maintained via the user actions in the GUI.  **Items in the list doesn't necessarily have a one to one correlation to a leaf widget. **

The data in the list is more native and the data sink (remember this is outside of the UI) does not need any specific specialized performance to get individual item updates.  It is a get the list of items, process them in the order they are represented, finish and forget about the list state until another binding update happens and expects that list might be completely different.

**Comment by andydotxyz** [comment]
> It is a get the list of items, process them in the order they are represented, finish and forget about the list state until another binding update happens and expects that list might be completely different.

That doesn't really sound like data binding. It seems like you just want to get the latest copy of a list for processing at some backend. Probably a channel is your friend here.
