### ISSUE TITLE
Blurry content on VirtualBox

### ISSUE THREAD

**Issue by kroksys** [fyne-io/fyne#520]
Windows on VirtualBox have problems detecting correct DPI so the content becomes blurry (see the picture below - open it in full screen).
When I run the same app from macOS (host) the app is not blurry anymore.

![Screen Shot 2019-11-08 at 12 56 48](https://user-images.githubusercontent.com/15876796/68472153-8914a380-0228-11ea-996a-0ff25d997f10.png)

 - OS: Windows 10 on VirtualBox hosted on Mac
 - Windows 10, macOS Catalina v10.15.1
 - Go 1.13.1
 - Fyne version 1.1.2

I played with changing  Fonts and Scale, but that didn't solve the problem.

**Comment by andydotxyz** [comment]
If you click on the advanced tab what scale does it say is being used?

**Comment by kroksys** [comment]
Scale 1.00

**Comment by andydotxyz** [comment]
can you report if that value changes, or the display is more clear if you set the environment FYNE_SCALE to "auto"?

**Comment by kroksys** [comment]
After setting up FYNE_SCALE to "auto" or "0" Result Scale was 0.7
It was still blurry (looked more blurry than before).
I believe this happens because of the VirtualBox virtual screen.

**Comment by andydotxyz** [comment]
Yes, that makes sense. I cannot figure out why the Fyne content was blurry but other content was not.
Does windows internally have some scaling settings?
Can you confirm the virtual box window size vs the internal windows desktop size please?

**Comment by andydotxyz** [comment]
This should be resolved now as we are using window's builtin scaling value..?
Please re-open if it is still an issue.
