### ISSUE TITLE
Bug in dialog.NewFolderOpen() with custom repositories

### ISSUE THREAD

**Issue by brucealthompson** [fyne-io/fyne#5200]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Register a new repository with a new scheme. I used the scheme "httpfile". Then set the folder location for dialog.NewFolderOpen() with the following code:

```go
locationURI, err := storage.ParseURI("httpfile:///")
  if err != nil {
    return err
  }
  listableURI, err := storage.ListerForURI(locationURI)
  if err != nil {
    return err
  }
  folderdialog := dialog.NewFolderOpen(callback, parent)
  folderdialog.SetLocation(listableURI)
  folderdialog.Show()
```

The resulting file dialog uses the default directory (without returning an error) instead of the URI in listableURI.
func (f *FileDialog) effectiveStartingDir() fyne.ListableURI in fyne.io\fyne\v2@v2.5.2\dialog\file.go has incorrect logic at the beginning.

I have already found the code causing this issue and fixed it. Here is the code causing this issue in: fyne.io\fyne\v2@v2.5.2\dialog\file.go

```go
func (f *FileDialog) effectiveStartingDir() fyne.ListableURI {
	if f.startingLocation != nil {
		if f.startingLocation.Scheme() == "file" {
			path := f.startingLocation.Path()

			// the starting directory is set explicitly
			if _, err := os.Stat(path); err != nil {
				fyne.LogError("Error with StartingLocation", err)
			} else {
				return f.startingLocation
			}
		}
		
	}
```

Here is the fix:

```go
func (f *FileDialog) effectiveStartingDir() fyne.ListableURI {
	if f.startingLocation != nil {
		if f.startingLocation.Scheme() == "file" {
			path := f.startingLocation.Path()

			// the starting directory is set explicitly
			if _, err := os.Stat(path); err != nil {
				fyne.LogError("Error with StartingLocation", err)
			} else {
				return f.startingLocation
			}
		}
		**return f.startingLocation**
	}
```

Add **return f.startingLocation** to the end of the above code segment.

### How to reproduce

Register a new repository with a new scheme. I used the scheme "httpfile". Then set the folder location for dialog.NewFolderOpen() with the following code:

```go
locationURI, err := storage.ParseURI("httpfile:///")
  if err != nil {
    return err
  }
  listableURI, err := storage.ListerForURI(locationURI)
  if err != nil {
    return err
  }
  folderdialog := dialog.NewFolderOpen(callback, parent)
  folderdialog.SetLocation(listableURI)
  folderdialog.Show()
```

The resulting file dialog uses the default directory (without returning an error) instead of the URI in listableURI.
func (f *FileDialog) effectiveStartingDir() fyne.ListableURI in fyne.io\fyne\v2@v2.5.2\dialog\file.go has incorrect logic at the beginning.

### Example code

```go
locationURI, err := storage.ParseURI("httpfile:///")
  if err != nil {
    return err
  }
  listableURI, err := storage.ListerForURI(locationURI)
  if err != nil {
    return err
  }
  folderdialog := dialog.NewFolderOpen(callback, parent)
  folderdialog.SetLocation(listableURI)
  folderdialog.Show()
```

### Fyne version

2.5.2

### Go compiler version

1.23.1

### Operating system and version

Windows 11

### Additional Information

I have already implemented the fix in my copy of fyne. See above for the fix. Works fyne now.

**Comment by andydotxyz** [comment]
Thanks for the careful analysis - I agree with the proposed fix. Would you like to place that into a PR so it gets associated with your account? :). (plus Hacktoberfest credits!)

**Comment by brucealthompson** [comment]
Would you like to place that into a PR so it gets associated with your account? :). (plus Hacktoberfest credits!)

PR == Merge Request?? Can you point me to documentation for your development process? I assume you want me to check into a branch off of main on Github. Is there any naming convention you use?

**Comment by brucealthompson** [comment]
I am a bit stuck with git. I created a fork of fyne-api and checked in the change into a local branch. Now I have no idea how to test my application using the code I just checked into my branch. I tried doing a go get "https://github.com/brucealthompson/fyne-api@release/v2.5.x". I get an error from go when I do this.

**Comment by andydotxyz** [comment]
Thanks so much for the fix :)
