### ISSUE TITLE
How to draw 3D elements and control 3d view?

### ISSUE THREAD

**Issue by epowsal** [fyne-io/fyne#5228]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want draw 3d elements in view.at future it could add event for 3d elements.

### Is it possible to construct a solution with the existing API?

I have not found.

### Describe the solution you'd like to see.

a view can draw 3d or 2d shape.

**Comment by andydotxyz** [comment]
> **Describe the solution you'd like to see.**
>
> a view can draw 3d or 2d shape.

Can you be more specific please? Obviously lots of 2D drawing is supported already, that is what we use to paint the user interface.

Using maths or a graphics package it is possible to project 3D into a 2D space (some users have done this already to draw 3d mesh on a Fyne canvas). But perhaps you are talking about 3D acceleration or using an OpenGL API? It is not clear from the information included.

**Comment by epowsal** [comment]
a widget can simple draw 3d line or load saved models for view only.it like mathematicas plot output.using third part maybe too complex.

**Comment by andydotxyz** [comment]
I see, I think that it should be closed following the OpenGL (3D engine) request #563.
