### ISSUE TITLE
Weird layout using entry widget with NewFixedGridLayout

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#523]
**Describe the bug**
When using entry widgets with a fixed grid layout, placeholder text is not placed in the right position.

**To Reproduce**
code in go playground https://play.golang.org/p/qLNIh-YbOJI

**Screenshots**
<img width="320" alt="Screenshot 2019-11-09 at 21 27 20" src="https://user-images.githubusercontent.com/31141573/68534710-bf8d1400-0337-11ea-8eaa-29e2f721c779.png">

Fixed grid layout was used only for password entry.

**Device (please complete the following information):**
 - OS: MacOS
 - Version Catalina 10.15.1
 - Go version go1.13.1
 - Fyne version 1.1.2

**Comment by andydotxyz** [comment]
Your code is manually specifying a grid size with a smaller height than the entry MinSize... I'm not sure this is a bug as it's doing what you specified.

**Comment by metaclips** [comment]
Yes this makes sense, thanks alot.
