### ISSUE TITLE
In Tab Container the second tab's label content is invisible

### ISSUE THREAD

**Issue by mazhiyu** [fyne-io/fyne#524]
**Describe the bug**
In tab container example: [https://tour.fyne.io/widget/tabcontainer.html](https://tour.fyne.io/widget/tabcontainer.html),
the second tab's label content is invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/8840751/68538370-f69e0c80-03ad-11ea-8a3f-590a3a98577d.png)
![image](https://user-images.githubusercontent.com/8840751/68538372-04539200-03ae-11ea-92ef-42e4ba7926ff.png)

**Device (please complete the following information):**
 - OS: [macOS Catalina]
 - Version [10.15.1]
 - Go version [1.13.4]
 - Fyne version [master:98fc45eeb2f12a3d3d0ad62f485883130e292312]

**Comment by andydotxyz** [comment]
This should already be fixed on “develop” branch - could you test that please?

**Comment by mazhiyu** [comment]
Yeah, it worked. Sorry, my negligence.

**Comment by andydotxyz** [comment]
Not at all - such fixes should normally be pushed to master. Unfortunately we are in the middle of large changes so that has been delayed - it should all be released later this month though :)
