### ISSUE TITLE
cannot control list height when used in border layout

### ISSUE THREAD

**Issue by taleintervenor** [fyne-io/fyne#5244]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

A typical usage scenario is log panel (or output panel) which many IDEs have. The panel will continuely print text, which may grow to thousands of lines. It turns out that multiline entry cannot handle so much lines of text, it will stuck heavily. So the only choice may be the list widget.
And in such scenario, log panel should stick to the bottom of window and have a static height to leave the main space to other panels (like edit panel). So it should be used with border layout.
Then the problem comes: it seems that we cannot control the height of list. In border layout, Fyne always set the list height to only 1 line's height, making it quite ussless.

### Describe the solution you'd like to see.

Why not give user the ability to set min height (and maybe width) of list, just like SetMinRowsVisible() provided by entry widget?

Or maybe Fyne can enhance the entry widget to optimize its preformance when handling thousands of lines?

**Comment by andydotxyz** [comment]
Personally I would opt for a split in this scenario so that the user can resize the log viewer compared to the content.

However if you want to go down the Border route then realise that any widget can have a MinSize set by extending the widget and providing a new `MinSize` method. Hints in this extend doc: https://docs.fyne.io/extend/extending-widgets

**Comment by taleintervenor** [comment]
> Personally I would opt for a split in this scenario so that the user can resize the log viewer compared to the content.
> 
> However if you want to go down the Border route then realise that any widget can have a MinSize set by extending the widget and providing a new `MinSize` method. Hints in this extend doc: https://docs.fyne.io/extend/extending-widgets

Well, you are right. Split may be the better solution.
