### ISSUE TITLE
[MacOS] Compilation not completing

### ISSUE THREAD

**Issue by wchangc** [fyne-io/fyne#5245]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

package command-line-arguments
	imports fyne.io/fyne/v2/app
	imports fyne.io/fyne/v2/internal/driver/glfw
	imports fyne.io/fyne/v2/internal/driver/common
	imports fyne.io/fyne/v2/internal/painter/gl
	imports github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in /Users/wchangc/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20211210172815-726fda9656d6/v2.1/gl

### How to reproduce

go 1.23.2
fyne.io/fyne/v2 v2.5.2 // indirect
fyne.io/systray v1.11.0 // indirect

### Example code

package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Macos

**Comment by andydotxyz** [comment]
The compiler cannot find the required C compiler to build the underlying graphics and OS code.
Did you follow the getting started to ensure the dependencies were all installed? https://docs.fyne.io/

**Comment by wchangc** [comment]
<img width="390" alt="image" src="https://github.com/user-attachments/assets/3982c21b-b3f8-4978-9b9f-2599415c40c3">
Hello, I have installed the detection software and all the tests have passed, but I still can't run the demo

**Comment by wchangc** [comment]
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/9f7e8037-64c3-4ae8-b7e7-8e84cfec19be">
This is the error message

**Comment by andydotxyz** [comment]
It cannot find the compiler wherever you executed the build. The environment must not be the same as the system environment. Try a different shell/terminal - it looks like either it has been customised or that one isn't picking up the system config.

**Comment by andydotxyz** [comment]
>  Q:  engine binary not found in PATH what's that? how to show detail msg ?

fyne-cross uses docker or podman to run containers - if neither are installed it cannot proceed.

**Comment by andydotxyz** [comment]
> I have the same error log, pls help!
> 
> I compile program use cmd:` GOOS=windows go build main.go`

If you are manually specifying OS instead of using our packaging helpers you must specify `CC` as well and point to the C toolchain, as well as `CGO_ENABLED=1` - see docs at https://docs.fyne.io/started/cross-compiling.
