### ISSUE TITLE
Wrong position of wrapped CanvasObject - seemingly multiplied by 2

### ISSUE THREAD

**Issue by i-fix-retarded-bugs** [fyne-io/fyne#5247]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

With each tap (call of Tapped()) one would expect the white rectangle (see the code) to move 10x10 pixels south-east, but it moves 20x20 pixels south-east. Its position, however, gets updated correctly. So it's the rendering process that produces this bug.
`followerRectangle` added to help visualize the problem.

### How to reproduce

1. Copy and paste and run the code.
2. Click on the white rectangle.
3. Observe that the white rectangle is seemingly getting moved twice, while the "follower" red rectangle shows the true position the white rectangle should be in.

### Screenshots

https://github.com/user-attachments/assets/cc042567-69c5-445b-8ac9-fa0e17bb3875

### Example code

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"image/color"
	"time"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hi")

	rectangle := canvas.NewRectangle(color.White)
	canvasObjectTappable := wrap(rectangle)
	canvasObjectTappable.Resize(fyne.NewSize(100, 100))

	followerRectangle := canvas.NewRectangle(color.Transparent)
	followerRectangle.StrokeWidth = 2
	followerRectangle.StrokeColor = color.RGBA{R: 250, G: 30, B: 30, A: 100}
	go func() {
		for range time.Tick(time.Second) {
			pos := canvasObjectTappable.Position()
			size := canvasObjectTappable.Size()
			followerRectangle.Move(pos)
			followerRectangle.Resize(size)
		}
	}()

	c := container.NewWithoutLayout(canvasObjectTappable, followerRectangle)

	w.SetContent(c)

	w.Show()
	a.Run()
}

type CanvasObjectTappable struct {
	fyne.CanvasObject
}

var (
	_ fyne.Widget   = (*CanvasObjectTappable)(nil)
	_ fyne.Tappable = (*CanvasObjectTappable)(nil)
)

func wrap(co fyne.CanvasObject) *CanvasObjectTappable {
	return &CanvasObjectTappable{
		CanvasObject: co,
	}
}

func (b *CanvasObjectTappable) CreateRenderer() fyne.WidgetRenderer {
	return widget.NewSimpleRenderer(b.CanvasObject)
}

func (b *CanvasObjectTappable) Tapped(ev *fyne.PointEvent) {
	fmt.Printf("%+v\n", ev)
	b.Move(b.Position().AddXY(10, 10))
}
```

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Pop_OS 22.04

**Comment by i-fix-retarded-bugs** [comment]
One can also  have some less trivial move logic (e.g. `b.Move(ev.AbsolutePosition)` and the buggy behaviour still persists. But it can be less obvious what's going on due to less predictability of pointer positions.

**Comment by i-fix-retarded-bugs** [comment]
Here is a better code snippet that also illustrates this problem. It's basically the same as the original one, but one can also drag the rectangle. The doubling effect is much more pronounced when dragging.

```go
package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"image/color"
	"time"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hi")

	rectangle := canvas.NewRectangle(color.White)
	canvasObjectTappable := wrap(rectangle)
	canvasObjectTappable.Resize(fyne.NewSize(100, 100))

	followerRectangle := canvas.NewRectangle(color.Transparent)
	followerRectangle.StrokeWidth = 2
	followerRectangle.StrokeColor = color.RGBA{R: 250, G: 30, B: 30, A: 100}
	go func() {
		for range time.Tick(time.Second) {
			pos := canvasObjectTappable.Position()
			size := canvasObjectTappable.Size()
			followerRectangle.Move(pos)
			followerRectangle.Resize(size)
		}
	}()

	c := container.NewWithoutLayout(canvasObjectTappable, followerRectangle)

	w.SetContent(c)

	w.Show()
	a.Run()
}

type CanvasObjectTappable struct {
	fyne.CanvasObject
}

var (
	_ fyne.Widget    = (*CanvasObjectTappable)(nil)
	_ fyne.Tappable  = (*CanvasObjectTappable)(nil)
	_ fyne.Draggable = (*CanvasObjectTappable)(nil)
)

func wrap(co fyne.CanvasObject) *CanvasObjectTappable {
	return &CanvasObjectTappable{
		CanvasObject: co,
	}
}

func (b *CanvasObjectTappable) Dragged(event *fyne.DragEvent) {
	pos := b.Position().Add(event.Dragged)
	b.Move(pos)
}

func (b *CanvasObjectTappable) DragEnd() {
	fmt.Println("drag end")
}

func (b *CanvasObjectTappable) CreateRenderer() fyne.WidgetRenderer {
	return widget.NewSimpleRenderer(b.CanvasObject)
}

func (b *CanvasObjectTappable) Tapped(ev *fyne.PointEvent) {
	fmt.Printf("%+v\n", ev)
	b.Move(b.Position().AddXY(10, 10))
}
```

**Comment by andydotxyz** [comment]
Fyne coordinates are not pixels.
A pixel size will vary hugely depending on the output device and OS configuration. The fyne coordinates are device agnostic and consistent across setups. 

https://docs.fyne.io/architecture/geometry

**Comment by i-fix-retarded-bugs** [comment]
But the code above exclusively uses fyne's API (Position and Size). Are you saying it's normal that `followerRectangle`, which is coded to copy the white rectangle's position and size, always appears as though it has exactly half of the white rectangle's coordinates? As in they're divided by 2

**Comment by i-fix-retarded-bugs** [comment]
@andydotxyz Can you please elaborate on this? I cannot see where I used pixels directly in my code. And I still do not understand why the white rectangle is misplaced so.

**Comment by andydotxyz** [comment]
> But the code above exclusively uses fyne's API (Position and Size). Are you saying it's normal that `followerRectangle`, which is coded to copy the white rectangle's position and size, always appears as though it has exactly half of the white rectangle's coordinates? As in they're divided by 2

My apologies, I was scanning your description and saw that you were referring to pixels.

**Comment by andydotxyz** [comment]
Oh I see it now. You cannot extend a CanvasObject directly (only Widgets) so you are trying to wrap one with another?...

The output canvas object and the inner canvas object are different - but they are sharing the same state (as one will delegate to the other). The outer one which has no visible output is in the correct place and then the inner one is in the same place relative to the parent. Hence the *2 effect.

If you're trying to make custom components then use widgets, it is the only route we support.

**Comment by i-fix-retarded-bugs** [comment]
@andydotxyz Thank you for your help

**Comment by andydotxyz** [comment]
> @andydotxyz Thank you for your help

You're welcome, sorry that I didn't get there with the first pass!
