### ISSUE TITLE
Can you develop a loaded component

### ISSUE THREAD

**Issue by junmaqiang** [fyne-io/fyne#5254]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

There is an asynchronous interaction action in daily software, so it is necessary to load this component

### Describe the solution you'd like to see.

Similar to the following effect

https://media.tenor.com/qXzHf2tesO0AAAAM/loading-gif-steiness.gif

**Comment by andydotxyz** [comment]
`widget.NewActivity()`

https://docs.fyne.io/api/v2.5/widget/activity.html

**Comment by andydotxyz** [comment]
Please don't ask questions with feature requests.
