### ISSUE TITLE
Android: Key presses may cause doubled events

### ISSUE THREAD

**Issue by pjanx** [fyne-io/fyne#5259]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

With different virtual keyboards (Samsung Keyboard, Unexpected Keyboard, _however_ Microsoft SwiftKey is _fine_) and also with an attached hardware keyboard, I get doubled key presses. The observation with a hardware keyboard is such that the app then acts on both pressing and releasing the keys.

I've never seen it with another app. I couldn't manage to reproduce it in an emulator.

### How to reproduce

Switch around virtual keyboards, type into an Entry, and also use the Backspace key.

### Example code

```
package main

import (
	"net"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/driver/mobile"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Bugs")
	w.Resize(fyne.NewSize(640, 480))
	w.SetContent(widget.NewMultiLineEntry())

	connectAddress := widget.NewEntry()
	connectAddress.SetPlaceHolder("host:port")
	connectAddress.Validator = func(text string) error {
		_, _, err := net.SplitHostPort(text)
		return err
	}
	connectAddress.SetText(string([]byte{3, 2, 1, 65, 66, 67, ':', '1'}))
	connectAddress.TypedKey(&fyne.KeyEvent{Name: fyne.KeyPageDown})

	var wConnect *dialog.FormDialog
	wConnect = dialog.NewForm("Connect to relay", "Connect", "Exit",
		[]*widget.FormItem{
			{Text: "Address:", Widget: connectAddress},
		}, func(ok bool) {
			if ok {
			} else if _, ok := a.Driver().(mobile.Driver); ok {
				wConnect.Show()
			} else {
				a.Quit()
			}
		}, w)
	wConnect.Show()
	w.ShowAndRun()
}
```

### Fyne version

2.5.2

### Go compiler version

1.23.2

### Operating system and version

Android 13 One UI 5.1

**Comment by andydotxyz** [comment]
Which soft keyboard did you have loaded?

**Comment by pjanx** [comment]
It's a bit wild:
 - Unexpected Keyboard: virtual Backspace, everything but numbers on a HW keyboard (key down, key up),
 - Samsung Keyboard: virtual Backspace, everything but numbers on a HW keyboard (key down, key up),
 - Microsoft SwiftKey: works as expected, also on a HW keyboard.

**Comment by andydotxyz** [comment]
Just for clarity "virtual Backspace, everything but numbers" means that all duplicate except the number keys yes?
So to put it another way "duplicates on virtual keyboard and all keys on hardware except numbers"?

What is confusing me is that a hardware keyboard changes behaviour based on the loaded virtual keyboard. There must be something about android events that changes the interpretation based on what software is currently connected to the input field?...

**Comment by andydotxyz** [comment]
Related and possibly duplicate: https://github.com/fyne-io/fyne/issues/2774

**Comment by pjanx** [comment]
Ah, yeah, I went through all issues but failed to notice some. Feel free to close.
