### ISSUE TITLE
did not work for me

### ISSUE THREAD

**Issue by mh-cbon** [fyne-io/fyne#526]
**Describe the bug**
A clear and concise description of what the bug is. > Absolutely no idea, sorry.

**To Reproduce**

I have two versions of the same code, one is working, the other is not, i cant figure out why. The resulting windows are full black (correct size), and after few seconds they hang and notifications occurs to say it is dead and ask me to close or wait (they don t listen keyboard events).

Version 1, working OK
```go
package main

import (
	"flag"
	"fmt"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/widget"
)

func main() {

	flag.Parse()
	files := flag.Args()

	i := 0
	a := app.New()
	for _, file := range files {
		wname := fmt.Sprintf("#%v %v", i, file)
		w := a.NewWindow(wname)
		img := canvas.NewImageFromFile(file)
		img.FillMode = canvas.ImageFillStretch
		img.FillMode = canvas.ImageFillOriginal
		img.FillMode = canvas.ImageFillContain
		scroll := widget.NewScrollContainer(img)
		w.SetContent(scroll)
		w.Canvas().SetOnTypedKey(func(k *fyne.KeyEvent) {
			w.Close()
		})
		w.Show()
		scroll.Resize(fyne.NewSize(400, 400))
		w.Resize(fyne.NewSize(400, 400))
		i++
		<-time.After(time.Second)
	}
	a.Run()
}
```

version 2, not working,
```go
package main

import (
	"flag"
	"fmt"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"log"
	"os"

	"../../govision"
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/widget"
)

func main() {

	flag.Parse()
	files := flag.Args()

	err := govision.
		Stream(govision.OpenDocs(files), govision.DecodeDocs(os.Stdin)).
		Map(openWindows).
		Sink(govision.CloseDocs).
		Drain()

	if err != nil {
		log.Fatal(err)
	}

}

func openWindows(dst chan<- govision.Doc, src <-chan govision.Doc, cerr chan error) {
	i := 0
	a := app.New()
	for doc := range src {
		// mat := doc.Layers[0].Mat
		// gocv.CvtColor(mat, &mat, gocv.ColorBGRToRGB)
		// im, err := mat.ToImage()
		// if err != nil {
		// 	cerr <- err
		// 	continue
		// }
		wname := fmt.Sprintf("#%v %v", i, doc.Name)
		w := a.NewWindow(wname)
		// img := canvas.NewImageFromImage(im)
		img := canvas.NewImageFromFile("/home/mh-cbon/image/7.png")
		img.FillMode = canvas.ImageFillStretch
		img.FillMode = canvas.ImageFillOriginal
		img.FillMode = canvas.ImageFillContain
		scroll := widget.NewScrollContainer(img)
		w.SetContent(scroll)
		w.Canvas().SetOnTypedKey(func(k *fyne.KeyEvent) {
			w.Close()
		})
		w.Show()
		scroll.Resize(fyne.NewSize(400, 400))
		w.Resize(fyne.NewSize(400, 400))
		i++
	}
	a.Run()
}
```

For somewhat reasons when i try to open windows from my pipeline, it does not work.

do you have any ideas ?

Apart, it appeared to me during the testing that this library is very sensitive to concurrent uses, i believe a Paragraph should exist about it in the readme. I dont remember having read anything about this.

**Screenshots**
no use

**Device (please complete the following information):**
$ lsb_release -a && go env && go version && (cd ../gow/src/fyne.io/fyne/ && git rev-parse HEAD)
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
GOARCH="amd64"
GOBIN="/home/mh-cbon/gow/bin"
GOCACHE="/home/mh-cbon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mh-cbon/gow"
GOPROXY=""
GORACE=""
GOROOT="/home/mh-cbon/.gvm/gos/go1.12.7"
GOTMPDIR=""
GOTOOLDIR="/home/mh-cbon/.gvm/gos/go1.12.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build103930905=/tmp/go-build -gno-record-gcc-switches"
go version go1.12.7 linux/amd64
98fc45eeb2f12a3d3d0ad62f485883130e292312

**Comment by mh-cbon** [comment]
For a moment i thought it was a file path issue, but it is not..

**Comment by mh-cbon** [comment]
adding a screenshot of the program not working
![Capture d’écran de 2019-11-11 12-46-23](https://user-images.githubusercontent.com/17096799/68585038-64ffcf00-0481-11ea-9425-339a396f3ad3.png)

the working program
![Capture d’écran de 2019-11-11 12-47-49](https://user-images.githubusercontent.com/17096799/68585088-83fe6100-0481-11ea-8da3-4c9cc273ea59.png)

**Comment by andydotxyz** [comment]
Unfortunately I cannot replicate as the source of the problem is how your govision function calls into app.Run().
Fyne is designed to be compatible with any thread/concurrency model, however there is one exception - Run() must be called from the main() function, or from the same thread that it runs on.
My guess is that behind the govision.Stream().Map() you are calling showWindows back on a goroutine?

There are many ways to do this - the easiest of this is to take out app.Run() and move it to after the govision entry point, that should then work as expected

**Comment by mh-cbon** [comment]
yes, it is goes within its own routine. Calling app.Run from main is hard in my case because if i call app.Run before any window is created, it panics. Because the stream can be infinite, it might happen it never reaches its end before ctrl+c.
Also, if i was to use a dummy hidden window, that would require to call for app.Run before the stream is processed, resulting in an app blocking at Run and never listening to its input.

> Run() must be called from the main() function, or from the same thread that it runs on.

i suspected something like that so i took care to have all fyne calls grouped within the same routine, but it did not help. I would say fyne must be run from main.

thanks for taking a look.

**Comment by andydotxyz** [comment]
I would recommend launching your stream in a goroutine, then immediately calling Run().
Fyne should not panic just because you have not shown a window.
In fact it should *never* panic, if it does please file a bug :).

Sorry about this complication - it's basically the one design aspect that we cannot escape!

**Comment by mh-cbon** [comment]
Is there an example of an fyne app implementing, for example, the network api ?

**Comment by andydotxyz** [comment]
Fyne currently has no networking components. If you want to run any server components or background processing just launch it in a go routine before you call Run()
