### ISSUE TITLE
System tray monitoring

### ISSUE THREAD

**Issue by jerryan1** [fyne-io/fyne#5261]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

If I want to listen for left click, right click, and double-click mouse events on the system tray, how do I need to implement it

### Describe the solution you'd like to see.

I want to implement a double-click system tray with a mouse, and then open a browser operation, so I need a tray mouse to listen for events.

**Comment by andydotxyz** [comment]
Many operating systems do not support double tap operations on the system tray so the Fyne library does not include that.

You may have more luck with the underlying system tray APIs [systray](/fyne-io/systray)

**Comment by jerryan1** [comment]
> Many operating systems do not support double tap operations on the system tray so the Fyne library does not include that.
> 
> You may have more luck with the underlying system tray APIs [systray](/fyne-io/systray)

I understand the reason you mentioned, but I think we should learn more about QT and go beyond it

**Comment by andydotxyz** [comment]
I'm happy to learn from toolkits and to exceed what has been done before, absolutely.
But we need to think about the user first, and how can we make a consistent experience across platforms.

**Comment by andydotxyz** [comment]
You may want to also check out https://github.com/fyne-io/systray/issues/84#issuecomment-2480843440

**Comment by jerryan1** [comment]
> I'm happy to learn from toolkits and to exceed what has been done before, absolutely. But we need to think about the user first, and how can we make a consistent experience across platforms.

I'm glad to communicate with you. I believe that maintaining cross platform consistency should not sacrifice some of the features on the original operating system, which makes people feel unhappy when using it. We cannot consider this issue from the perspective of developers, because real software users do not consider cross platform things. Users only want to use it comfortably.

**Comment by andydotxyz** [comment]
I do not disagree with your point, but consider this scenario: 

a) a menu is required to manage a sys tray app
b) the developer decided to make left click "show window" and right click "show menu"
c) the OS running does not support the right click option.

In this case the app becomes unusable.
This is what we, as responsible toolkit API creators, must guard against.
