### ISSUE TITLE
Support multiple colors for different buttons.

### ISSUE THREAD

**Issue by lebaoworks** [fyne-io/fyne#5274]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I want to create a table with multiple buttons, each button having a different color.

### Is it possible to construct a solution with the existing API?

As far as I know, the button color can currently only be assigned through the theme.

I've tried https://blogvali.com/button-color-background-image-fyne-gui-golang-tutorial-44/, the color only show at the four small corners of each button.
![image](https://github.com/user-attachments/assets/9b4f1eb3-7151-46ac-b73b-f72c7094115f)

### Describe the solution you'd like to see.

Add single field like color to Button struct

**Comment by andydotxyz** [comment]
The widget APIs are based on semantics - I.e. what does a coloured button /convey/. For this you can use the `Importance` field to set the meaning and colours will adjust accordingly.

The blog you posted is out of date - from when buttons were transparent.

You can of course create a simple custom widget that includes a coloured rectangle that is tappable.
Lastly there is a `ThemeOverride` container that would allow every button to have a different theme.

**Comment by lebaoworks** [comment]
@andydotxyz
I have finally set the color of the button using NewThemeOverride.

```
package main

import (
	"image/color"
	"log"

	"fyne.io/fyne/v2"
)

type CustomTheme struct {
	org   fyne.Theme
	color func(fyne.ThemeColorName, fyne.ThemeVariant) color.Color
	font  func(fyne.TextStyle) fyne.Resource
	icon  func(fyne.ThemeIconName) fyne.Resource
	size  func(fyne.ThemeSizeName) float32
}

func NewCustomTheme(org fyne.Theme) *CustomTheme {
	return &CustomTheme{
		org:   org,
		color: org.Color,
		font:  org.Font,
		icon:  org.Icon,
		size:  org.Size,
	}
}

func (b *CustomTheme) ColorCb(new func(fyne.ThemeColorName, fyne.ThemeVariant) color.Color) *CustomTheme {
	b.color = new
	return b
}

func (b *CustomTheme) FontCb(new func(fyne.TextStyle) fyne.Resource) *CustomTheme {
	b.font = new
	return b
}

func (b *CustomTheme) IconCb(new func(fyne.ThemeIconName) fyne.Resource) *CustomTheme {
	b.icon = new
	return b
}

func (b *CustomTheme) SizeCb(new func(fyne.ThemeSizeName) float32) *CustomTheme {
	b.size = new
	return b
}

func (b *CustomTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	log.Printf("name: %v, variant: %v", name, variant)
	return b.color(name, variant)
}

func (b *CustomTheme) Font(style fyne.TextStyle) fyne.Resource {
	log.Printf("style: %v", style)
	return b.font(style)
}

func (b *CustomTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	log.Printf("name: %v", name)
	return b.icon(name)
}

func (b *CustomTheme) Size(name fyne.ThemeSizeName) float32 {
	log.Printf("name: %v", name)
	return b.size(name)
}
```


```
importButtonContainer := container.NewThemeOverride(
		importButton,
		NewCustomTheme(Application.Settings().Theme()).
			ColorCb(func(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
				switch name {
				case theme.ColorNameButton:
					return color.RGBA{R: 0x2C, G: 0x2C, B: 0x2C, A: 255}
				case "text":
					return color.Black
				default:
					return Application.Settings().Theme().Color(name, variant)
				}
			}),
	)
```

However, I want to set the color of the text as well, but there is no fyne.ThemeSizeName for text. I tried matching 'text', but it didn't work.

**Comment by andydotxyz** [comment]
Maybe you are interested in https://github.com/fyne-io/fyne/pull/4959 then?

**Comment by lebaoworks** [comment]
@andydotxyz

Currently, I can work around it by overriding the theme theme.ColorNameForeground to change the button text color.

Thank you for your support, I will close this as completed.
