### ISSUE TITLE
Canvas text with alpha transparency doesn't render correctly

### ISSUE THREAD

**Issue by ncw** [fyne-io/fyne#5275]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Canvas text with alpha transparency doesn't render correctly.

If you run the program below it should produce two texts of very nearly the same color, but it produces one black and one red.

The difference is that the red text has alpha 255 whereas the black text has alpha 254

### How to reproduce

Run the example code

### Screenshots

![image](https://github.com/user-attachments/assets/b630a495-9c30-4022-b5da-1b7d29aeed6f)

### Example code

```go
package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Red Text Canvas")

	text1 := canvas.NewText("This is some red text", color.RGBA{R: 255, G: 0, B: 0, A: 255})
	text1.TextSize = 30
	text1.TextStyle = fyne.TextStyle{Bold: true}
	text1.Move(fyne.NewPos(0, 0))

	text2 := canvas.NewText("Slighty transparent red", color.RGBA{R: 255, G: 0, B: 0, A: 254})
	text2.TextSize = 30
	text2.TextStyle = fyne.TextStyle{Bold: true}
	text2.Move(fyne.NewPos(0, 50))

	content := container.NewWithoutLayout(text1, text2)
	myWindow.SetContent(content)

	myWindow.Resize(fyne.NewSize(400, 300))
	myWindow.ShowAndRun()
}
```

### Fyne version

v2.5.3-0.20241117144446-a48acbbf88de (latest develop)

### Go compiler version

go1.23.2

### Operating system and version

Ubuntu 22.04.5 LTS

**Comment by ncw** [comment]
Thanks for the explanation and sorry for the noise.

**Comment by hkparker** [comment]
Brilliant, I was running into this same confusion and this issue saved me from trying to make some demo code to open an issue!  Thanks to you both.
