### ISSUE TITLE
Per app language settings not working on recent macOS versions

### ISSUE THREAD

**Issue by sdassow** [fyne-io/fyne#5277]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

In recent versions of macOS a language can be chosen per app. Fyne does not seem to support this yet, and in fact it does require support from the application.

### How to reproduce

1. Install any Fyne app that supports more than one language
2. Go to SystemSettings -> General -> Language & Region -> Applications
3. Click "+" and select installed Fyne app

### Screenshots

<img width="446" alt="Screenshot 2024-11-20 at 00 57 22" src="https://github.com/user-attachments/assets/8f6f27b0-fb5b-49a1-ad12-bf5e34b4bcaa">

### Example code

Any installed Fyne app shows this.

### Fyne version

develop

### Go compiler version

go1.23.3 darwin/amd64

### Operating system and version

macOS Sonoma (14.7.1)

### Additional Information

Simply creating `lproj` directories in `Contents/Resources/` makes the languages appear, but when selected the app still doesn't localize. Maybe some additional API needs to be called?

The directory format for localization is mentioned here: https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

**Comment by sdassow** [comment]
Found something that seems related: https://github.com/tumic0/GPXSee/issues/474
As I understand instead of the .lproj directories it can be done via plist: https://github.com/tumic0/GPXSee/commit/2549204662bf218f2169126ff75eec35c90368a5

**Comment by sdassow** [comment]
With both PRs referenced above applied it looks like the following in macOS settings, and the app gets the preference too:
<img width="471" alt="Screenshot 2024-11-20 at 22 24 46" src="https://github.com/user-attachments/assets/b0021c11-ce1f-436a-84e0-2649854ba552">

**Comment by sdassow** [comment]
Sort of related, and maybe a useful keyword at some point in the future: CFBundleDevelopmentRegion

**Comment by andydotxyz** [comment]
We will release the update to the package command - but I guess we need to land/fork the appropriate change to go-locale before this is complete?

**Comment by dweymouth** [comment]
I believe this is completed on develop now after #5330 ?
