### ISSUE TITLE
Set Min size of window

### ISSUE THREAD

**Issue by Coder-Iro** [fyne-io/fyne#528]
Is there no method to set the minimum size of the window?
If not, can you make it?

**Comment by andydotxyz** [comment]
The window minimum size is the minimum size of all the widgets or objects you put in it. Is this not sufficient?

**Comment by Socio-path** [comment]
I would like to force the minimum size of the window. Is it impossible?

2019년 11월 12일 (화) 오후 10:55, Andy Williams <notifications@github.com>님이 작성:

**Comment by andydotxyz** [comment]
No this is not impossible, it will be forced by the minsize of the content.
Is there a use-case that we are missing where the window must always be larger than the content inside it? More details would be helpful.

**Comment by andydotxyz** [comment]
I have decided to close this issue as setting a window to a minsize irrespective of content is an anti-pattern... Complex layouts are being built which affect window size based on layout, content etc etc. The right way to do this is to either use Resize() and ignore the min size or to set the components inside to appropriate min sizes so the layout will set the window min size for you.

**Comment by itschrono** [comment]
Hello
> No this is not impossible, it will be forced by the minsize of the content.
> Is there a use-case that we are missing where the window must always be larger than the content inside it? More details would be helpful.

There is: dialog, popup window, other content hidden and displayed with logic. This can avoid some accordion effect... But this can be done by wrapping everything in a proper layout anyway. Also when I spawn a dialog this does not change window size and text is fucked up even by setting text wrapping so "content is an anti-pattern" is a bit ironic.

**Comment by andydotxyz** [comment]
Can you please moderate your language @itschrono?

**Comment by andydotxyz** [comment]
There are many types of hidden content that can appear so it’s not quite as straight forward. TabContainer always ensures the window is big enough for any tab, so some widgets can do this. A popup (menu for example) will scroll If it is larger than the window, in most cases this is ok. Dialogs are the tricky one and we have another issue tracking that topic (#1112).

Please let me know if you think there is something additional to these that we should be supporting.

**Comment by manprinsen** [comment]
@itschrono I am experience the same problem as you.
My workaround is to create a transparent rectangle, then add your items on top of it.

`
package main

import (
	"fmt"
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
)

func main(){
	fmt.Println("hello")

	myApp := app.New()
	myWindow := myApp.NewWindow("title")
	myWindow.Resize(fyne.NewSize(800,600))
	myWindow.CenterOnScreen()

	
	bg := canvas.NewRectangle(color.RGBA{255, 0, 0, 0})
	bg.SetMinSize(fyne.NewSize(800,600))

	label := widget.NewLabel("hello")
	labelContainer := container.New(layout.NewCenterLayout(),label)


	content := container.New(
		layout.NewStackLayout(), 
		bg, 
		labelContainer,
	)
	myWindow.SetContent(content)

	myWindow.ShowAndRun()
}
`

Hope it can be of any help!

**Comment by ByteSizedMarius** [comment]
> [@itschrono](https://github.com/itschrono) I am experience the same problem as you. My workaround is to create a transparent rectangle, then add your items on top of it.
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	"image/color"
> 
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/widget"
> 	"fyne.io/fyne/v2/canvas"
> 	"fyne.io/fyne/v2/container"
> 	"fyne.io/fyne/v2/layout"
> )
> 
> func main(){
> 	fmt.Println("hello")
> 
> 	myApp := app.New()
> 	myWindow := myApp.NewWindow("title")
> 	myWindow.Resize(fyne.NewSize(800,600))
> 	myWindow.CenterOnScreen()
> 
> 	
> 	bg := canvas.NewRectangle(color.RGBA{0, 0, 0, 0})
> 	bg.SetMinSize(fyne.NewSize(800,600))
> 
> 	label := widget.NewLabel("hello")
> 	labelContainer := container.New(layout.NewCenterLayout(),label)
> 
> 
> 	content := container.New(
> 		layout.NewStackLayout(), 
> 		bg, 
> 		labelContainer,
> 	)
> 	myWindow.SetContent(content)
> 
> 	myWindow.ShowAndRun()
> }
> ```
> 
> Hope it can be of any help!

That's a creative solution to an artificial problem. Thanks.
