### ISSUE TITLE
Colors between different windows

### ISSUE THREAD

**Issue by 161424** [fyne-io/fyne#5291]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

![image](https://github.com/user-attachments/assets/d66771b6-02a4-46c7-b57c-028b0b8eace3)
![image](https://github.com/user-attachments/assets/ab62ddfd-6859-4603-ba69-627935ae9c5b)

There are two windows here, the first window is the official fynedemo, and the second window is a program I wrote myself. The problem is that when using fynedemo for color changes, the color in the second window will also change. I guess it was written to the default file after changing the color using fynedemo. Here is the relevant code in my project:

![image](https://github.com/user-attachments/assets/9baf93a3-a088-4b17-a721-3078556869e3)

The main reason for creating a theme separately is that using Chinese characters can cause garbled characters, so it is necessary to change the content of ’StaticContent‘.

When trying to use a custom theme, if you want to change a certain color, such as changing the background to red, it seems like you need to build a color list that includes all the content, which feels inconvenient. Looking forward to version 3.0

### How to reproduce

open fyne demo，click file->setting->main color->apply

### Example code

var (
	//go:embed fonts/NotoSansSC-6.ttf
	CascadiaCode []byte
)

type MyTheme struct{}

var _ fyne.Theme = (*MyTheme)(nil)

func (m MyTheme) Font(fyne.TextStyle) fyne.Resource {
	return &fyne.StaticResource{
		StaticName:    "NotoSansSC-6.ttf",
		StaticContent: CascadiaCode,
	}
}

func (*MyTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(n, v)
}

func (*MyTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (*MyTheme) Size(n fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(n)
}

### Fyne version

2.4.5

### Go compiler version

1.23.2

### Operating system and version

win11

**Comment by andydotxyz** [comment]
> There are two windows here, the first window is the official fynedemo, and the second window is a program I wrote myself. The problem is that when using fynedemo for color changes, the color in the second window will also change.

That is correct - the fyne_demo is launching "fyne settings" which is changing your preferred primary colour. When your user account says it prefers red instead of blue for primary then all apps will use that setting.

This does not relate to custom themes and it does not mean you have to replicate the entire theme. If your app wants a specific primary colour then simply return that colour when the `ColourNamePrimary` name is passed to `Color` callback.
