### ISSUE TITLE
System Tray Menu show missing id

### ISSUE THREAD

**Issue by ilovesusu** [fyne-io/fyne#5304]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When I move the mouse to the icon, it prompts missing id.

### How to reproduce

When I move the mouse to the icon, it prompts missing id.

### Screenshots

![image](https://github.com/user-attachments/assets/8143d6fc-b5a9-4092-938d-6a1cfd29b79d)

### Example code

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("SysTray")

	if desk, ok := a.(desktop.App); ok {
		m := fyne.NewMenu("MyApp",
			fyne.NewMenuItem("Show", func() {
				w.Show()
			}))
		desk.SetSystemTrayMenu(m)
	}

	w.SetContent(widget.NewLabel("Fyne System Tray"))
	w.SetCloseIntercept(func() {
		w.Hide()
	})
	w.ShowAndRun()
}

### Fyne version

2.5.2

### Go compiler version

latest

### Operating system and version

archlinux KDE

**Comment by andydotxyz** [comment]
The system tray will attempt to show your app name. If one is not found it will use the ID. As an ID must be unique one is generated internally if you omit it.

You can fix this by adding app metadata, or by using `app.NewWithID` instead of `app.New`.
https://docs.fyne.io/started/metadata
