### ISSUE TITLE
support setting RGBA color for RichText

### ISSUE THREAD

**Issue by hkparker** [fyne-io/fyne#5306]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

I've been using `canvas.Text` for something, and setting the color as a `color.Color`.  This is great, however I want to use truncation now, which doesn't come with `canvas.Text`.

So I went to use `widget.RichText` instead, but the only way to set the color is using named colors from the theme.

I'm not trying to use theme colors though.  My colors could be any RGBA value, and they come from users and can't be anticipated in advance.  I doesn't make sense to me to dynamically load user content like that into the theme, even if that was possible.

### Is it possible to construct a solution with the existing API?

I don't think so

### Describe the solution you'd like to see.

`richText.Segments[0].(*widget.TextSegment).Style.Color = &color.RGBA{}`

Or I guess, alternatively, supporting truncation on the `canvas.Text` would solve my problem, but that seems like it doesn't go there.

**Comment by andydotxyz** [comment]
You can extend the theme to provide different named colours. This is the way to do it.

If you ignore theme and have, for example, a dark purple text in light mode it will become impossible to read if the user switches to dark mode.

**Comment by dweymouth** [comment]
To be clear, for @hkparker's use case where the colors can be arbitrary and come from the user, they'd want to have a custom theme that accepts HTML hex color strings as ColorName values and parses them to return the corresponding color.Color

**Comment by andydotxyz** [comment]
I see there is an assertion that users can specify any colour they want - but it is our job to make sure the UI remains usable.

I don't know the exact use-case - perhaps that would help?

**Comment by hkparker** [comment]
My app has users identified by UUIDs.  From these UUIDs I deterministically generate an RGBA value.  It's my job to make sure that whatever value comes out of this function is appropriate for the UI and has dark/light versions that work well, but within that constraint I want them to be (relatively) unique to that user, to serve as that user's default color.  They are therefore unpredictable.  I generate these colors by using data from the UUID to select within a range of values for a color that I know will look presentable, so it's not naively going to spit out a bad color.

This color is used in the user's name on chat bubbles as well as their default icon (shown when they haven't selected an image).  This color generation technique is also used to give groups a default icon.  Here's an example of a chat bubble, with the pink value being generated this way:

![chat_bubble_color](https://github.com/user-attachments/assets/77aba08a-06ba-43bf-96a1-9dc80a0b79a4)

Signal messenger does something similar.  Signal actually used to use these colors as the background colors for chat bubbles (see examples [here](https://user-images.githubusercontent.com/10113399/120925120-59b16b80-c6d7-11eb-81d3-74fd19d180a5.png) and [here](https://user-images.githubusercontent.com/32278206/131049581-1d8e3a0c-943c-4aaf-b2fb-b05885c4a654.png)), but stopped doing that and is now using them more how I described.

In my chat bubble example above, the user's name is simply "android", however my app supports much longer (but still capped) names.  On screens where the username is longer than the possible width of the bubble, I want these colorful usernames to be truncated gracefully and not run off the edge.

**Comment by hkparker** [comment]
There is code in the app that generates RGBA from UUIDs, but I can't know them ahead of time.

If Alice adds Bob as a friend for example, Alice has never seen Bob's UUID before.  How does Alice load the generated color for Bob into the theme at runtime, and access it via that UUID?  It looks to me like you'd need to export the theme as JSON, add a new entry, and re-import it?  That seems really incorrect to me, since these colors aren't part of the theme of the app and redefining the theme shouldn't be part of adding a new contact.

**Comment by andydotxyz** [comment]
> There is code in the app that generates RGBA from UUIDs, but I can't know them ahead of time.

You don't have to know them ahead of time - that code could be moved to the theme. Or the theme could look it up somehow - themes do not have to be static.

> It looks to me like you'd need to export the theme as JSON, add a new entry, and re-import it? 

Absolutely not - like I said themes can be dynamic - JSON is a convenience source but mostly they are written in Go.

**Comment by dweymouth** [comment]
To clarify, @hkparker, you can put whatever logic you want in your custom theme's `Color` function. I recommend adding code to parse an HTML color string of the form "#RRGGBB" or "#RRGGBBAA" and then you can color rich text segments by setting `segment.Style.ColorName = "#3F2EF3"` for example

**Comment by hkparker** [comment]
Oh!  Ok very helpful, I haven't played around with theming much yet so I was thinking of the implementation as being much more rigid, but that's just on me for not having been around that part of the codebase much yet.  Thank you both.  I think this is a fine approach, I'll give it a try when I put together my first custom theme.
