### ISSUE TITLE
canvas.Image and canvas.Raster textures are not refreshed while actively resizing window.

### ISSUE THREAD

**Issue by windexlight** [fyne-io/fyne#531]
**Describe the bug**
canvas.Image and canvas.Raster objects that are resized when the window is being resized do not have their underlying textures updated while the window is actively being resized (i.e. border hotspot is being dragged). When hotspot is released to "finish" the resize, only then is the texture actually updated. During resize, if we go from a small size to a larger size, there is noticeable blurriness as the smaller resolution image is scaled up to fill the larger area (this looks very much to me like it is OpenGL doing the scaling, as the visual quality reminds me of old 3D games with low resolution textures). I first noticed this in my own app, in which I was experimenting with using a canvas.Raster object created with NewRaster(generate func(w, h int) image.Image) to supply the image on demand using my own function (neat idea, by the way). I could see while debugging that canvas.Refresh() was being called for my canvas.Raster object every time it changed size, but canvas.Refresh() would not trigger my generate function to be called until after the window border was released.

I then checked to see if the demo exhibited similar behavior, and it did. I'm making an assumption that it uses canvas.Image to display SVG images.

**To Reproduce**

1. Build and run Fyne demo in a desktop environment (seen on Windows 10).
2. Go to tab with icon selector / display.
3. Start with a small window and drag border to increase window size.
4. Observe that icon appears blurry until mouse is released to finish resize.

**Screenshots**
Can add later if necessary.

**Device (please complete the following information):**
I am opening this issue at a time when I don't have easy access to my development system (sorry). I can update with more information in a week or so if reproduction is a problem.
 - OS - Windows 10, kept up to date, but don't have access to look at build number currently.
 - Go version - Unsure at present, sorry. It could be 6-12 months old.
 - Fyne version - Whatever was pulled with "go get fyne.io/fyne" as of mid to late last week.

**Comment by andydotxyz** [comment]
I think this is done on purpose so that resizing a window is not too slow...
Maybe once we have some optimisations in for 1.2 we could review this and see if we can do better?

**Comment by windexlight** [comment]
I thought that might be the case. It seems reasonable to expose a flag so the app developer can make the choice about performance vs visual quality. In my case I would choose the latter. I feel like it’s an implicit expectation of most users these days that a window not lose visual quality while resizing.

**Comment by windexlight** [comment]
One other thing to mention here. On Windows 10, if a window is maximized, and then the title bar is clicked and dragged downwards to restore the window to non-maximized, the textures are scaled and never updated until the window border is dragged - so they’re left in a bad state after restore. This would be addressed by #560.

**Comment by andydotxyz** [comment]
This is now on develop for testing.
We probably have some optimising to do :)
