### ISSUE TITLE
glfw repaint crash

### ISSUE THREAD

**Issue by hiroyukki** [fyne-io/fyne#5311]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I run demo `hello`, window show out and looks like ok, but crash when I click button `Hi!`.
I trace it, crashed at glXMakeCurrent in `go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/glfw/src/glx_context.c`

crash stack in go:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa860 pc=0x7f4d128be4]

runtime stack:
runtime.throw({0xb96d77?, 0x7f61a259a8?})
        /opt/go/src/runtime/panic.go:1047 +0x40 fp=0x7f83fbbda0 sp=0x7f83fbbd70 pc=0x4517c0
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:825 +0x240 fp=0x7f83fbbde0 sp=0x7f83fbbda0 pc=0x467f40

goroutine 13 [syscall, locked to thread]:
runtime.cgocall(0xa2b2f8, 0x40003bbd58)
        /opt/go/src/runtime/cgocall.go:157 +0x50 fp=0x40003bbd20 sp=0x40003bbce0 pc=0x421480
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwMakeContextCurrent(0x7b31880)
        _cgo_gotypes.go:1570 +0x30 fp=0x40003bbd50 sp=0x40003bbd20 pc=0x99d6e0
github.com/go-gl/glfw/v3.3/glfw.(*Window).MakeContextCurrent.func1(0xcb10b8?)
        /home/pc/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/context.go:19 +0x50 fp=0x40003bbd90 sp=0x40003bbd50 pc=0x99fb00
github.com/go-gl/glfw/v3.3/glfw.(*Window).MakeContextCurrent(0x0?)
        /home/pc/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240506104042-037f3cc74f2a/context.go:19 +0x60 fp=0x40003bbde0 sp=0x40003bbd90 pc=0x99fa60
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0x9e4820?, 0x40003bbe20)
        /home/pc/fyne-master/internal/driver/glfw/window.go:927 +0x40 fp=0x40003bbe00 sp=0x40003bbde0 pc=0x9ee490
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0x3?, 0x0?)
        /home/pc/fyne-master/internal/driver/glfw/loop.go:209 +0x44 fp=0x40003bbe40 sp=0x40003bbe00 pc=0x9e68d4
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).drawSingleFrame(0x40003bbf88?)
        /home/pc/fyne-master/internal/driver/glfw/loop.go:95 +0x1c8 fp=0x40003bbee0 sp=0x40003bbe40 pc=0x9e60b8
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1()
        /home/pc/fyne-master/internal/driver/glfw/loop.go:263 +0x18c fp=0x40003bbfd0 sp=0x40003bbee0 pc=0x9e6cdc
runtime.goexit()
        /opt/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40003bbfd0 sp=0x40003bbfd0 pc=0x482e44
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/pc/fyne-master/internal/driver/glfw/loop.go:241 +0xcc

It is noteworthy that provider of libGLX is `libGLX_inno.so`, is that is a private implementation of libGL ?
I run hello with gdb, crash stack is:
![hello_crash](https://github.com/user-attachments/assets/55c3bdce-ff63-420a-8aa1-5ad2d70e842b)

My environment is kylin linux(a China custom version), my CPU is D3000(an arm64 architecture cpu, China custom version also)

### How to reproduce

It seems hard to show up because my equipment is custom made.
So I'm not sure this issues is helpful

### Example code

hello in fyne/cmd/hello

### Fyne version

all version

### Go compiler version

1.20.13

### Operating system and version

Kylin Linux V10 SP1

**Comment by andydotxyz** [comment]
> ## Fyne version
>
> all version

I doubt you have tested every version - please list which you found the problem. There is no version info in the log for us to work with.

**Comment by hiroyukki** [comment]
> > ## Fyne version
> > all version
> 
> I doubt you have tested every version - please list which you found the problem. There is no version info in the log for us to work with.

You are right, of course I can not test all version, but I try some version, all crashed on my china custom environment.
I trace it, crached in libGLX ，I think may be some bugs in libGLX on this especial hardware environment?(I test many platforms, windows, ubuntu, MacOS x64 and M1/M2/M3, fyne works fine, So I doubt libGLX bugs but I can not fix it)
I try v2.5.3-rc7 again:
![helle_crash](https://github.com/user-attachments/assets/5f38660f-413d-4e59-b187-68ea6b4692a7)
I notice that seems glfwInit in main thread, but repaint in another thread? I dont know is there a potential risk.

**Comment by hiroyukki** [comment]
> > ## Fyne version
> > all version
> 
> I doubt you have tested every version - please list which you found the problem. There is no version info in the log for us to work with.

thx for attention,  I resolved the "bug",It's not a software bug, but hardware bug in extension of gpu driver.
I set LIBGL_ALWAYS_SOFTWATE=1 go disable hardware acceleration, it works.
I report this to graphics card's vendor.

**Comment by hiroyukki** [comment]
Not fyne's bug, a gpu driver bug found
