### ISSUE TITLE
Checkbox not responding to click because it is too "large"?

### ISSUE THREAD

**Issue by xrfang** [fyne-io/fyne#5331]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Checkbox only works if the window is resized to its minimal state, i.e. exactly the size of the checkbox + its label.

### How to reproduce

Already communicated with Andy on Slack

### Example code

```go
package main

import (
	"fmt"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World!")
	w.Resize(fyne.NewSize(400, 240))
	chk := widget.NewCheck("Option 1", func(b bool) {
		fmt.Printf("option1 is: %v\n", b)
	})
	w.SetContent(chk)
	w.ShowAndRun()
}
```

### Fyne version

v2.5.3

### Go compiler version

1.23.3

### Operating system and version

Debian 12

**Comment by Jacalz** [comment]
> Already communicated with Andy on Slack

Sorry but that's not very helpful. Please always fill in as much information as possible in the issue description.

**Comment by xrfang** [comment]
@Jacalz  sorry but there is really nothing to say, just run the program and you will see it. I have already described the problem.  If you need more info, please reply, or contact me on Slack

**Comment by Jacalz** [comment]
I'm just trying to say how we prefer issue descriptions to be written in the future. If it is a simple as just running the program, then you should just write that. With saying that it was communicated with someone on slack could imply that there is more to it and it is better to keep all the information in one place here available for everyone to see.

FYI: What I would have preferred to see is something like this (per the comment in the issue description):

1. Run the example program.
2. Notice that it...

Anyway, if it is as simple as you say and we can replicate then there is likely no more information needed.

**Comment by xrfang** [comment]
@Jacalz  ok.  The tutorial I am following is: https://www.youtube.com/watch?v=n79Axf8tA2Q&list=PL5vZ49dm2gshlo1EIxFNcQFBUfLFoHPfp&index=5 

The video does NOT show this bug, so, my guess are: 1) either this is a new bug, or 2) it appears on Linux but not Windows.

**Comment by andydotxyz** [comment]
Looks like this is the side effect of a prior bugfix, replicated with a unit test.

**Comment by andydotxyz** [comment]
Fixed on develop branch, will be in the next release
