### ISSUE TITLE
Multiline Entry widget does not correctly Resize / display if used in multiple tabs,

### ISSUE THREAD

**Issue by Sharrnah** [fyne-io/fyne#5338]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Textareas inside Split containers are not always rendered or rendered in the correct size if switching between tabs that contain these.

Using Fyne v2.5.3 on windows 11.

In the  screenshot, the text fields should fill both sides of the split part. (there is no vertical split between them)

The actual size is not the size of any other place the widgets are used, so i don't think its because they are shared, and they are only visible once at all times.
The same textarea widgets are used multiple times in different tabs. But as i said, only one tab is visible at all times and i want them to share the same content.

It seems doing a delayed Refresh() on the tab.Content solves this.
```go
appTabs.OnSelected = func(tab *container.TabItem) {
	go func() {
		time.Sleep(time.Millisecond * 100)
		tab.Content.Refresh()
	}()
}
```

### How to reproduce

1. Create a Entry Widget with MultiLine enabled.
2. Have the Widget being sharead so you can use the same instance on multiple app tabs
3. switch between the tabs that display the widget (Or click twice on a tab to get wrongly sized widgets)
4. notice that often the size / placement is incorrect or is not shown at all until a resize event or mouse hover over a split widget handle that contains the widgets

### Screenshots

![grafik](https://github.com/user-attachments/assets/1f80835c-1731-4ba7-b442-cad1b299f154)

### Example code

```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/lang"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

var textarea = widget.NewMultiLineEntry()
var textareaB = widget.NewMultiLineEntry()

func CreateTab(tabName string) fyne.CanvasObject {

	row := container.New(
		layout.NewGridLayout(2),
		container.NewBorder(nil, nil, nil, nil, textarea),
		container.NewBorder(nil, nil, nil, nil, textareaB),
	)

	appLayout := container.NewBorder(
		nil,
		nil, nil, nil,
		container.NewVSplit(
			row,
			container.New(layout.NewHBoxLayout(), widget.NewLabel(tabName)),
		),
	)

	return appLayout
}

func main() {

	a := app.NewWithID("test")

	w := a.NewWindow("Test")
	w.SetMaster()

	w.Resize(fyne.NewSize(float32(800), float32(600)))

	w.CenterOnScreen()

	appTabs := container.NewAppTabs(
		container.NewTabItem(lang.L("Tab 1"), CreateTab("Tab 1")),
		container.NewTabItem(lang.L("Tab 2"), CreateTab("Tab 2")),
	)

	appTabs.SetTabLocation(container.TabLocationTop)

	w.SetContent(container.NewBorder(nil, nil, nil, nil, appTabs))
	// show main window
	w.Show()

	a.Run()
}

```

### Fyne version

2.5.3

### Go compiler version

1.23.4

### Operating system and version

Windows 11

### Additional Information

Could only reproduce it by double clicking on a tab in example code. But result is the same.

**Comment by andydotxyz** [comment]
In reproduction steps:

> 2. Have the Widget being sharead so you can use the same instance on multiple app tabs

This is invalid usage. A widget should exist in only 1 parent maximum.

**Comment by andydotxyz** [comment]
I tried running the example code but cannot replicate the issue.
Also it does not seem to match the replication steps so I'm not sure which is right or what I'm missing.

**Comment by Sharrnah** [comment]
Okay. i investigated a bit more. It happens more likely in my application because i do some specialities when switching tabs.

In the Demo Code it only happens when clicking multiple times on the already active tab.
See how it looks:
![Bildschirmaufnahme2024-12-23133058](https://github.com/user-attachments/assets/067c752d-3fe1-4236-96f6-e0453a040924)

I understand that this seems to be not a valid usage of it. But it worked perfectly fine before, so this is a different behaviour than before.

I guess if this is not considered to be fixed i can change how i use the widgets.

**Comment by andydotxyz** [comment]
Ah, weird - by tapping multiple times on the same tab I now see it.

However if I modify it so that it is not re-using the same widget in multiple different locations the problem goes away.

In addition if you do exactly the same test but resize the window instead of moving the split the issue does not happen. This demonstrates that the issue is squarely because one entry has two different sizes. This relates to my point above that one widget should only ever be attached to one parent.
