### ISSUE TITLE
my macbook osx 10.15 can't build project got the error

### ISSUE THREAD

**Issue by cyrus0880** [fyne-io/fyne#546]
**Describe the bug**
i just try to build this demo code 
main.go
 
```go
package main

import (
	"fyne.io/fyne/widget"
	"fyne.io/fyne/app"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))

	w.ShowAndRun()
}
```

i get this error
```besh
$go build
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ../../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_darwin.go:8:
../../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
# fyne.io/fyne/internal/driver/gl
../../fyne.io/fyne/internal/driver/gl/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:193:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here
```

**Device (please complete the following information):**
 - OS: OSX
 - Version 10.15
 - Go version  go1.13.4 darwin/amd64

how can fix this problem?

**Comment by mazhiyu** [comment]
maybe something wrong with `xcode`, after updates os, you should install `xcode` again
`xcode-select --install`

**Comment by cyrus0880** [comment]
> If it's just some warning, you can ignore it, otherwise maybe something wrong with `xcode`, after updates os, you should install `xcode` again.
> `xcode-select --install`

i try reinstall xcode & run this xcode-select --install
i get this mgs
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by mazhiyu** [comment]
your `go build` command just got some warnings, the execute file may already be in the same folder as the main.go file,  which name is the same as directory name.

**Comment by andydotxyz** [comment]
These are just warnings and can be ignored. You should find the executable file in the folder with your code

**Comment by cyrus0880** [comment]
> your `go build` command just got some warnings, the execute file may already be in the same folder as the main.go file, which name is the same as directory name.



> These are just warnings and can be ignored. You should find the executable file (It will be called “main” from the command you used above) in the folder with your code

i fond it the executable file and can run it thx

i can try build my old project now
