### ISSUE TITLE
Support reporting CapsLock key events

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#552]
From slack thread :
https://gophers.slack.com/archives/CB4QUBXGQ/p1574740084243300

It appears that CapsLock key does not emit a keyscan code - as tested in fyne_demo -> advanced.

Shift and Ctrl keys work already, but CapsLock doesnt.

SDL reports a scancode for CapsLock, so it should be possible to address.

**Comment by andydotxyz** [comment]
This will not be possible until we are able to upgrade GLFW - #183, apologies.
I think the library is available upstream now but it is unlikely to bring such a large change into the 1.2 release as it is nearly complete at this time.

**Comment by deluan** [comment]
Understandable. That's fine, it is not a pressing issue, at least for me, but it is definitely something I think Fyne should support

**Comment by steveoc64** [comment]
Can no longer reproduce ?

Hitting Capslock is reporting a keyscan.   Unsure whats changed to make this work now, if its a fix, I cant see any code on our end that has fixed this

**Comment by andydotxyz** [comment]
Does it appear in the list of key events in fyne_demo -> Advanced?
on macOS for me it does not.

Upgrading to GLFW earlier made this possible (there was no keycode before) but we still need to figure how to include this in the API. is it treated as a modifier or as a key?

**Comment by andydotxyz** [comment]
On develop for testing
