### ISSUE TITLE
ModalPopup window doesn't stay centered on window resize

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#553]
**Describe the bug**
when window is resized, modal popup doesn't stay centered

**To Reproduce**
On fyne_demo at full screen
1. Go to window tabmenu
2. Click on confirm button
3. Try to resize window to the minmum

**Screenshots**
On full screen
<img width="1680" alt="Screenshot 2019-11-26 at 22 40 49" src="https://user-images.githubusercontent.com/31141573/69675037-0734cf00-109e-11ea-9182-ea5c8009fef6.png">
On resize
<img width="901" alt="Screenshot 2019-11-26 at 22 41 12" src="https://user-images.githubusercontent.com/31141573/69675086-27fd2480-109e-11ea-8faf-8248a5e81c44.png">

**Device (please complete the following information):**
 - OS: macos
 - Version catalina 10.15.1
 - Go version 1.13
 - Fyne version v1.1.3-0.20191126142316-5ce499317159

**Comment by andydotxyz** [comment]
Good catch thanks

**Comment by andydotxyz** [comment]
Resolved on develop ready for next release

**Comment by metaclips** [comment]
Nice, thanks.
