### ISSUE TITLE
Window.Resize sometimes crashes on start

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#557]
**Describe the bug**
On start fyne crashes when run multiple times

**To Reproduce**
Code https://play.golang.org/p/hUEwsrIu9bk
You have to run multiple times >=4 to notice the panic, really not sure why.
Stack trace https://bpaste.net/show/OJWR6

**Device (please complete the following information):**
 - OS: macOS
 - Version 10.15.1
 - Go version 1.13
 - Fyne version v1.1.3-0.20191126142316-5ce499317159

**Comment by andydotxyz** [comment]
I am unable to reproduce this. Is there anything more you can share about the mac hardware?
I assume this does not happen when the Resize call is removed?
Does it happen if you reverse the Resize and SetContent calls?

**Comment by metaclips** [comment]
I don't seem to have this issue again using the latest commit on develop branch. 
Would close this now. Thanks.
