### ISSUE TITLE
canvas images doesn't show when placed in a box

### ISSUE THREAD

**Issue by metaclips** [fyne-io/fyne#558]
**Describe the bug**
When a canvas image is placed in a box it doesn't show till a window resize

**To Reproduce**
1. Run https://play.golang.org/p/YMUhvQowPD7
2. Resize window to see image

**Device (please complete the following information):**
 - OS: macOS
 - Version 10.15.1
 - Go version 1.13
 - Fyne version v1.2.0-beta1.0.20191130180205-1df1ac1c3bae

**Comment by andydotxyz** [comment]
I don't know if it's any help but you could use widget.Icon instead, which forces the image to be the standard icon size.

Either way this needs to be fixed.

**Comment by andydotxyz** [comment]
On develop for testing.

**Comment by metaclips** [comment]
Thanks.
