### ISSUE TITLE
Add better documentation regarding build tags

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#561]
**Is your feature request related to a problem? Please describe.**
Looking through the wiki makes it obvious that there are different tags that can be used to change in what way the files are built, but there isn't any good documentation about it. 

I found out about the wayland and efl tags from the wiki but there is little to know information as far as I can see. I can work out what the wayland one does without a problem, but not everyone will know that as an example...

**Describe the solution you'd like**
I would like either a wiki page about build tags and all the possible tags that can be used for modifying how the package is built and there should be sufficient information about what they do along with general pros and cons compared to not using them for example. Or a simple table in the README file, or both, I don't really know.

**Comment by andydotxyz** [comment]
Unfortunately any page that refers to EFL or wayland is quite out of date now (I need to fix, can you point me to the one you found?).
There are not really many build tags as the system is designed to automatically detect your system and set up.

What particularly are you trying to do, we can update the documentation accordingly.

**Comment by Jacalz** [comment]
I see that the page about wayland was updated nine hours ago, but [here](https://github.com/fyne-io/fyne/wiki/Performance) is where you will find the efl tag mentioned.

I tested the wayland tag now on wayland and it seems to not really be working. Is it removed in the upcoming 1.2 release?

**Comment by andydotxyz** [comment]
Thanks for this. Wayland support was temporarily removed in 1.0 after having supported it in early development. It will be back in 1.3, so I removed it from the document for now. Ideally it won’t need a tag to enable it when we are done.

**Comment by Jacalz** [comment]
You are welcome.

**Comment by andydotxyz** [comment]
I have updated that page now, can you let me know if that is more helpful?
I will add a page about build tags as well because 1.2 has some useful additions :)

**Comment by andydotxyz** [comment]
I have added a section to the end of https://fyne.io/develop/compiling.html.
Let me know if you think anything else should be added, otherwise I think this issue can be closed.

**Comment by Jacalz** [comment]
Great stuff and really useful. Just one small little issue:

Small text and no real way to tell the different sections apart. Should ideally be with bigger text and some sort of distance between the text for each tag or put it in a table:
![image](https://user-images.githubusercontent.com/25466657/70055519-fb836400-15d9-11ea-98fb-b916211f85a5.png)

**Comment by andydotxyz** [comment]
Thanks for the feedback. It is already in a table but if you have suggestions for improved CSS then we certainly could update it :)

Thanks for the tip on the other page too

**Comment by Jacalz** [comment]
It's better than nothing, but could of course be improved. I am no man for helping with CSS improvements, just take my word for what I think could be improved :)

Regarding the other page. Is 16MB file size really correct? Most of my fyne programs end up betwwen 7 and 9 megabytes. 😅

**Comment by andydotxyz** [comment]
Are you running on develop or on a released version? We added a lot more graphics in 1.2 and so the size has gone up. Tackling this is on the list for later as I'd like to keep the sizes down considerably.

**Comment by Jacalz** [comment]
I’m using the stable version, so that explains stuff. Anyway thanks for making (what I regard as) one of the best GUI libraries period. I agree, the size right now is a problem and it’s sad to see it balloon to also most double 😐

**Comment by andydotxyz** [comment]
Thanks very much!
The size is mostly embedded iconography required for buttons, dialogs and so forth.
We are considering a build flag that could omit them for people that want to build in their own graphics - would that help?

**Comment by Jacalz** [comment]
I am mostly using the built in graphics so I don’t think it changes much for me, but it would be cool if it could include only the graphics that the application uses?
