### ISSUE TITLE
Ability to set text dpi and background color

### ISSUE THREAD

**Issue by sanguohot** [fyne-io/fyne#569]
The `TextDPI` is a little big for my use case.
I think it is better to give a default value and support changing it.
Now I have to change the source code, it is not so ideal.

// TextDPI is a global constant that determines how text scales to interface sizes
`const TextDPI = 78`

Also, the backgroud's `alpha` seems not work when setting to 0x0.

This is my code
```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
	"os"
	"path/filepath"
)

var (
	content = "阅读是一件非常愉快的事情，哈哈。早睡早起可以养生!o(╯□╰)o \r\nHappy Friday"
)

func init()  {
	os.Setenv("FYNE_FONT", filepath.Join("sgh_test", "assets", "static", "PingFang Regular.ttf"))
	os.Setenv("FYNE_SCALE", "1")
}

func main() {
	app := app.New()
	lightTheme := theme.LightTheme()
	app.Settings().SetTheme(lightTheme)
	w := app.NewWindow("")
	label := widget.NewLabel(content)
	vbox := widget.NewVBox(
		label,
	)
	w.SetContent(vbox)
	w.CenterOnScreen()
	w.SetFixedSize(true)
	w.ShowAndRun()
}
```

![fyne](https://user-images.githubusercontent.com/25117034/70411893-5dd2dd80-1a8e-11ea-9f49-017c6077b43d.png)

**Comment by andydotxyz** [comment]
If you want to change the size of text would it not be better to set the font size? Everything in the widget package is standardised and does not offer much configuration but you can use the canvas package to build any graphical output you want.
TextDPI could be device specific as it's an implementation detail of one renderer.

I cannot see where you are setting background alpha to 0x0, but the theme determines the window colour. We do not currently support transparent windows.

**Comment by sanguohot** [comment]
I never pay attention to this package `canvas`, it could be another choice.
Thanks a lot.
