### ISSUE TITLE
Fyne settings file not found causes printed error

### ISSUE THREAD

**Issue by Cloudladderllc** [fyne-io/fyne#576]
Fyne settings file not found causes printed error upon app start. App still runs.

**To reproduce:**
Run a Fyne 1.2 app on a vanilla system that has never run a Fyne app before

**Occurs on:**
 - OS: Linux, Windows, Darwin
 - Fyne version: 1.2

Doesn't occur on Fyne 1.1

**Error output:**

Darwin:

2019/12/14 18:35:10 Fyne error: Settings watch error:
2019/12/14 18:35:10  Cause: lstat /Users/tkidd/Library/Preferences/fyne: no such file or directory
2019/12/14 18:35:10  At: /go/src/fyne.io/fyne/app/settings_desktop.go:15

Windows:

2019/12/14 18:38:13 Fyne error:  Settings watch error:
2019/12/14 18:38:13   Cause: GetFileAttributes: The system cannot find the file specified.
2019/12/14 18:38:13   At: C:/Projects/Go/src/fyne.io/fyne/app/settings_desktop.go:15

Linux:

2019/12/14 18:44:38 Fyne error:  Settings watch error:
2019/12/14 18:44:38   Cause: no such file or directory
2019/12/14 18:44:38   At: /go/src/fyne.io/fyne/app/settings_desktop.go:15

**Comment by andydotxyz** [comment]
This will be in the 1.2.1 release - it's on the release/v1.2.1 branch if you'd like to test.

**Comment by andydotxyz** [comment]
Released in v1.2.1
