### ISSUE TITLE
Scroll horizontally when holding down shift key

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#579]
**Is your feature request related to a problem? Please describe.**
Applications usually scroll up and down with the scroll wheel normally, but left to right when the user also holds down shift,

**Is it possible to construct a solution with the existing API?**
Should be possible as far as I can see.

**Describe the solution you'd like**
Scroll horizontally when holding down shift key.

**Comment by andydotxyz** [comment]
Are you sure it's Ctrl? Most documentation seems to recommend Shift...

**Comment by Jacalz** [comment]
Yeah you are right, it is Shift 🤦‍♂

**Comment by andydotxyz** [comment]
Cool. We discussed this during development and one thing was unclear, perhaps we can discuss here before it's fixed:

If you have a two-dimensional scroller (touch pad, scrollwheel with horizontal) what should happen to the horizontal component if shift is pressed? ignored, inverted, added to the vertical vector?

**Comment by Jacalz** [comment]
I will try to answer some of your questions using my laptop (has touch screen):
- On touch pad: scrolling up and down while holding shift scrolls left and right.
- On touch pad: scrolling left and right while holding shift just scrolls left and right like normal (ignored basically).
- On touch screen: shift is totally ignored no matter how you scroll.

**Comment by toaster** [comment]
I'm not sure what the remaining work for this issue is. With the 1.2 release the horizontal scrolling was introduced and it already contained the capability to scroll horizontally when holding `Shift` while scrolling vertically.
So, what's to do here?

**Comment by Jacalz** [comment]
This might be a bug report then, because I can't get it to work on Linux. Will try on MacOS and Windows too to see if I can replicate there.

**Comment by andydotxyz** [comment]
I would have to add that I don't think it made it in, or at least is not working here either.
Also I can't see it in the driver code.

**Comment by toaster** [comment]
I just verified with the demo app. Its in the window.go AFAIR. However, I'm currently setting up a Gentoo desktop system and will check there.

**Comment by Jacalz** [comment]
It will scroll horizontal if that is the only way to scroll, no matter if you hold down shift or not. 
However, as soon as you have the possibility to scroll both vertical and horizontal, it just scroll vertical and doesn't care about shift being pressed. I think this might be what you are thinking about? @toaster

**Comment by toaster** [comment]
The mouse wheel scrolls horizontally if there is no other scroll direction, that's true. But if there are both directions available `Shift` + mouse wheel should scroll horizontally, too, and does so on my Mac.

**Comment by andydotxyz** [comment]
That’s so strange, I can’t make it work on my Mac on master or develop. Using trackpad scroll, maybe that matters?
Do you know where this code is @toaster?

**Comment by Jacalz** [comment]
I have done some more testing and the following is what I have seen:

### Touchpad:
- **Windows:** Scrolling horizontal on the touchpad works, but not if you hold down shift and scroll vertically on the touchpad (it works like this in chrome for people not having horizontal scroll on touchpads).
- **Linux:** Same as Windows above just that the horizontal scroll of the touchpad is very jumpy.

### Mouse:
- **Windows:** Scrolling vertical on the mouse wheel and holding shift does not work as expected.
- **Linux:** Same issue as with Windows above.

**Comment by toaster** [comment]
@andydotxyz There is no `Shift` + scroll code because the OS handles this (on MacOS). That's why it doesn't work for the touchpad (doesn't need to because you can easily scroll horizontally there).

**Comment by toaster** [comment]
Maybe we need code for Linux/Windows, will check this as soon as I have my Gentoo box running.

**Comment by andydotxyz** [comment]
Ah yes I see. macOS does this for you - but Linux systems do not seem to - toolkits seem to add that themselves.

**Comment by toaster** [comment]
I can verify that Gentoo+Gnome does not scroll horizontally with `Shift`. There are hacks to make it working using the X keyboard configuration but there doesn't seem to be a simple way to achieve this.
I didn't test on Windows, yet, but it seems that the situation is the same there. There are special apps to do this but the OS doesn't support it out-of-the-box.

I'll add code for this.

**Comment by andydotxyz** [comment]
Perfect, thanks.

**Comment by andydotxyz** [comment]
on branch release/v1.2.2 for testing
