### ISSUE TITLE
Label widget can display old text stretched over new dimensions

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#583]
**Describe the bug**
When the containing layout is refreshed at the same time as a label Text is changed it's possible to see the old text stretched over the space of the new text.
MinSize seems correct but the texture is out of date.

**To Reproduce**
Minimal app to follow

**Screenshots**
To follow

**Device (please complete the following information):**
 - OS: macOS (also seen on Linux)
 - Version: Catalina
 - Go version: 1.12
 - Fyne version: 1.2.0, 1.1.2

**Comment by andydotxyz** [comment]
![Screenshot 2019-12-15 at 14 00 38](https://user-images.githubusercontent.com/294436/71276934-c0f52780-234c-11ea-8a74-625850794ed5.png)

**Comment by andydotxyz** [comment]
I have not been able to replicate this in a smaller application which means it will take longer to fix. In the new year I will get time to replicate it properly. If you are able in the meantime to create a smaller demo application then we may be able to get this back up the priority list.

**Comment by metaclips** [comment]
Ok, would do that. Thanks.

**Comment by andydotxyz** [comment]
Fix on develop for testing

**Comment by andydotxyz** [comment]
Reverted the fix, sorry this is more complex than I thought

**Comment by andydotxyz** [comment]
The fix is on develop - hopefully it fixes the original issue too @metaclips
