### ISSUE TITLE
A new size Button, but it not work?

### ISSUE THREAD

**Issue by airplayx** [fyne-io/fyne#588]
```
        cc := widget.NewButton("提交", func() {

	})
	cc.Resize(fyne.NewSize(5, 1))
	fmt.Println(cc.Size())

	return &widget.Form{
		OnCancel: func() {

		},
		OnSubmit: func() {
			fmt.Println(cc.Size())
		},
		Items: []*widget.FormItem{
			{Text: "submit", Widget: cc},
		},
	}
```
### **look it**  
[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0cAAABdCAYAAABuHx3jAAARUklEQVR4nO3dB3DVZbrH8SchnSSUkARCQIoUpYOwDAMK6EaqlGVdygJ3adIuiEjR61XQYVHaMJci3QvisriroAKyQ4uUpV2agCAShBAIabR0QsLN8zLnbE5yCCQ558CS72fmTM751/f84wz5+b7v87qlpqbeEwAAAAAoJdzd3W0+T5gwQaZNmybuDzgeAAAAAEoVwhEAAAAACOEIAAAAAAzCEQAAAAAI4QgAAAAADMIRAAAAAAjhCAAAAAAMwhEAAAAACOEIAAAAAAzCEQAAAADk8ijJyTExMY5qBwAAAAC4RPXq1e1up+cIAAAAAIRwBAAAAAAG4QgAAAAApIRzjsLDwx3VDgAAAAB4rOg5AgAAAAApQc9RWlqa5OTkOLItAAAAAOB0Hh4e4ufnV3B7cS6mwSg+Pl6ysrJK3DAAAAAAcCVvb28JCQkpEJCKFY60x0iDUWhoqEMaBwAAAACukpCQYHcUHHOOAAAAAEAIRwAAAABgEI4AAAAAQAhHAAAAAGAQjgAAAABACEcAAAAAYBCOAAAAAEAIRwAAF9i8ebP1fVJSkly6dKnAKzo6+pGutWHDBsnOznZWUwEApVixFoEFAKAoNBx17drVvF+2bJncvn1bAgMDbY45fPiwfP311w+9lgapyMhIefnll53SVgBA6UU4AgC4XP/+/aVmzZo2295++22bzxs3bpRNmzYVODclJUW2b98u69atK7BvxIgR0qpVK8c2FgBQahCOAABOM23aNImPj5fz58/L6NGjpWPHjma79h75+fnZHBsbG2vzuWfPnuZlkZCQIMHBwdbPd+7ckbS0NClfvrwTvwEAoDQhHAEAnEbDkdJgtHjxYvN+5syZ8uabb0rt2rVtjtVjHkSD05QpU2T+/PlSsWJFs+3ixYsyY8YMeffdd6VevXrO+QIAgFKFcAQAcIl79+5JRkaGeHt7m1Dj6elps//GjRt2z7ty5YoJQO+99541GKm6devKRx99ZLaPHTuW4XQAgBIjHAEAnE7nCY0bN06GDh0qb7311iOfd+LECZk7d66Zj+Tm5lZgf2ZmpsyePVsmT55s9rds2dKRzQYAlDKEIwCA02hVulWrVkliYqIZYvf999/LwoULrfu1rHdQUJD1c2hoqOlVUgcOHJDly5fLrFmzxNfXV0aOHGnmKgUEBJj9V69eNT1HS5culTlz5sj48eNlwYIFNtcDAKAoCEcAAKd5//33pUuXLnLu3DmpVauWjBkzxgQlHx8f8ff3l2HDhsmSJUvEw6PgP0fNmzeXRYsWmWPVoEGDZN68efLBBx+YYgzTp08385A0OOlL5zRRnAEAUBKEIwCA02gBBaVluS20BHe7du2kadOm5vO2bdusQ+YaN24sYWFh5r2Xl5fNtTp37mzWQlq/fr2cPn1aXn31VWnQoIF1P8EIAFBS7o+7AQCA0uXnn382vUYW2gukc4f0lZOTU+i5WtFu5cqVZiHY7t27O7upAIBShp4jAIDLXLt2zaxXpPOEtKS36tq1q91hdXlplbsNGzbI1q1bZerUqRIdHW2G5A0ePFg6dOhgt1gDAABFRTgCADiNLtKqwUZ7h5TOCxo1apQkJyeb+Ue6QOzRo0clMDBQypQpY44JDw83c4j0HN0XGRkpp06dMsPoNFRZ5iB16tRJ1qxZYwo+tG/f3gzVY70jAEBJEI4AAE6zZ88e2bJli0RERJhApPOJNMioFi1ayMGDB+XQoUOm1HdWVpbZPmHCBPNT5ylFRUWZ4ydNmmQNTxaVK1c2Jbz1XA1Qn332mfTr10+aNGni0u8IAHh6uKWmpt4r6kn6D5GuVq4lVwEAAADg34kO8a5SpYp1Dqz+jzldcoKCDAAAAAAgVKsDAAAAAINwBAAAAABCOAIAAAAAg3AEAAAAAEI4AgAAAACjWOscubu7i6enp8TFxTm6PQAAAADgVN7e3ibT5FescOTn5ychISGSk5NT4oYBAAAAgCt5eHiYTFNge3EvaO9iAAAAeDqkpaXxP8KdTHsuLH9T87yfDMUORwAAAHg66R/q8fHxkpWV9bib8lTTaSo6GkvxvF1Lh9Xps8/f4UM4AgAAgA3twdA/1H19fR93U55q6enp1t4ifd7HzjIyy1VaPJ9ht6eOanUAAAAAIIQjAAAAADAIRwAAAAAghCMAAAAAMAhHAAAAACCEIwAAAAAwCEcAAAAAIIQjAAAAOEhsbKx8+umnkp2d/cBj7t69a46Ji4tzYctcRxdzzcjIeNzNsOvmDdc989SUm5Keluyy+zkKi8ACAADAITZu3CjffPON3LhxQ6ZMmSJlypSx2a+haebMmbJv3z7x8PCQ4cOHP/K1dcHOgwcPyvHjx831PT09pWbNmhIRESGBgYGO/irFNn78eBk9erS0a9fucTfFxrYty+XIoc0yePhsqVK1TqHH3roZLyeObpfE+Ojc554tgeUqyQutu0vFoLBHvt/33y6SsmXLSeceY0va9AJir/wiX3z2XzJw6CcSWqWmQ69NOAIAAIBDjBgxQq5fvy67d++We/fuydSpU60BKW8wat++vQwZMuSRr3vt2jX58MMPJSkpSdq0aSPVq1eX5ORk2b59u4SHh0vr1q2d9ZWeChqM9u/5u4RXfy434FQt9NioX47Il59Pl6rV6puXhqPLl36SSiHVixSOnKmsfwWp36CN+AdUsG679OtJyb6bJbXqNC/RtQlHAAAAcAgNQhqI1J49e8xPy2cNRnv37pWXXnpJJk2aVKBX6UFu374tkydPljp16si8efPEx8fHZv+dO3cc+A2ePnmD0YA//Vm8ffwKPX7rt4ukxW+6SkTXN2y2Z2VlOrOZRaI9Wd16vWmzbfeOtVKtRkPCEQAAAJ4cloCkPUeWgKTvLcFIg86jBiO1evVq8fX1NdfUoXT5eXl5Wd/rXJ+TJ0+aYXfBwcHSpEkTcXe/P8VeQ9Tly5elRo0akpiYKKdOnZKyZctK8+bNba5hae+ZM2fk6tWr5t56HX9/f+t+vc65c+fEz89PmjVrViCwPSmKGozUjevXJLRK7QLbPT29zU/tSYq/dtH0JHl4/Ov3cftWghn6WL5CqM15+iyjL56Sm7nXrVipqlR75nnrvrtZdyQx4bKEVK4h15Ni5erls+a6YeF1zf6khBi5EnM29/dU3oQeNzf3AuflZGeb95mZ6ZKSfF2uXY0Sv7LlTIAqDsIRAAAAHErDzzvvvGN6iywB6cUXXyxyMNKheDt37jTD9ewFo7yuXLki48aNk9DQUAkKCpKffvpJnn32WdMGDUhaAGLMmDEycuRI2bx5s4SFhcnp06elcuXKpkfKEpASEhLMED4NUHXr1jVBS7+DpQdsxYoV8t1330mDBg3MML+FCxfKJ598Yob3PUmKE4xU9RoN5cDer6ROvZYmZOSXkZ4iyxaMlrETV5mwY7F7518k606G9PrDFOu2u9lZ8sWqdyXrbqZ4e/nKxQs/St3nWsvv+r2bG3Tc5ObNOHOtDr8dLD+fOZAbRP3l16jj0iFisHjkhrGDezdIcOgzJlw9U7OR9B003VzXct7b732ZG4hTZf3n0yU15YYkJcZI1Lkj0vSFCHnp5T8W67kRjgAAAPBE0sCTnp4uDRs2fOixGoBmzJgh9evXN59jYmJMwQftIWrcuLH1OA1ES5YsMSFNK8sNGzbM9Gp17NjR9HJoMNJwNXfuXGtgunXrlvm5Y8cO2bZtmyxevFiqVr0fDDRYafU9vbcr7d75hZlj0yHiPwrsK24wUq/1mSjrVr8vC+cOkTYv/l5+06aneHoVr2fs5PFd0vsPU838IJUQd0lWLB4nJ45uk6YtIqzHaQGIYWP+x7w//n//kC3fLpLQyjVl1IRlpsdKe4M0DGkhhvzFJHQe1Pgpa+TzFVPMsLr2rwwsVlstKOUNAAAAh7IUX7AMpdNeIy3SoD0shZX5zi81NdX81KFtD1OlShVrMLKcU758eROw8urXr5+19yokJMQErwsXLpjPGqSioqJMxbm8Q+3Klbvfg7Jp0ybp0aOHNRipTp06ybFjx1w690mHlZ07c1D27FonO/6xymZfSYKR0mFxw8cskLbt+8o/d/9NFsz5k/xy9lCx2ln9mQbWYKS0F6hR0w5y9vQ+m+Natelhff9cw3a53y9TWrftbR3KVzmstvj7VzDhytnoOQIAAIDD5A9GOpROaa+MvSp2hbHM89GhbZUqFT6HRHuY1q9fL0eOHDG9RloqPC0tzcyDyUt7hfLfIzPzfrEBDUY6PK5ChQpiT3R0tJmHtHXrVus2XbdJ76G9SzrPyRU8PL3kj0NnytqV78i+yPVyL+eevNJ5aImDUd7ra69R85adJXL756Ynqe+gaWZIXFHkHXZn3RZUVa7G/GKzzT+govW9pc0BAba/J2/fsrnPOqtI9y8OwhEAAAAcwl4wsoQge1XsHhaQtIdGw8vhw4dNtbrCzJo1y5QRf+ONN0zRBT1v6NChRWq/Bjd9Fba/V69epohDftpL5Uo+PmVNQNI5Pf/c/aVcvHA8N3ScK3EwsrmHr7906j5K0tNuy97Iv9qEo9wnle/ogs/Nzc41MzNSxdu75G1zFobVAQAAwCGWLl1qgpGuY5S/+IKlil3btm1NQFq5cuVDr6fziLp16yZfffWVWevoQTS06AKxffv2NcPkNBhp5TotqlAUGqp0GJ4WWrBH11fS0uJaqCH/62EFI5xBA9KAIX826xE5OhjlFRQcbqrBKcv8o5Tb122OSYy/XOC8pMQrBbZdOH/UtPdJRTgCAACAQ/Tp00d69+79wHWMLFXsevbsaXpgHkX//v2lWrVqMnHiRImMjDTD59TNmzdNgYTz58+bymeBgYFm7o8GJZ3/o0USCusFskdLdteuXVs+/vhja0DS+2l5cPXaa6+ZeUf79++3nqPzlX744Yci3ceRLAGpZevuJQ5GWqb773+ZIZcu/GjmNenn6F9PyZGDm6X+8/fnDuk8oKrV6pn5SHfv3p9npUUUtFhCfpd+/VEO7//W/B70Wtr7FHftorzQulux2/ggvn6BEhcbZe6VnX232NdhWB0AAAAcQgscaNntwmhA0nLaj0oLI2hYWbt2rSxYsMC81/lEOtenVq1a1jlNY8eOlTlz5siuXbtMj9OAAQNMZbqi0POmT58u8+fPl4EDB0rFihUlJSVFXn/9dWnUqJGpaKe9UZY2aG+RBjMtIf44aUDq3GNsia+j3yU5OUlWL9dnqsHSTby8faRFqy42pbG79PhP+euaD2T2R7/P/f34So3aTaRhkw7WsGTRuNkrprR25PY1Zl6Wj4+/9Bv8YYG1kBxBA9e6//3v3Db1kWYvdJLfdhlerOu4paamFi1SAwAA4KmmgSA2NvaRqsS5ks5p0nCiQ+a0sELehVmVFlbQ9Yy0MEJJ256cnGzmMOm1dLHXvLRnSsuAa3DTQFhc2iulVfaUPu9jZ5+MuThZWZly80acWeS1XPmQ3NBYsBdQe4J04VYfHz+bggr2JN9OMmsgVQgKMwHMWe7k3iMl917lcsNXmTKF9wG1eD7DPHvLf0MTJkyQadOm0XMEAACAfw/a66SLvD6It7e3mRfkCAEBAeZlj4aiJ23RV0fSoXPBIYU/Rw1MlYIf7RkEBAY9/CAH8PLysVshryiYcwQAAAAAQjgCAAAAAINwBAAAAABCOAIAAAAAg3AEAAAAAEI4AgAAAACDUt4AAACwoYuh6gKnug4PnEefsT5ry/tm9dMec4tKDy1Xbnn2eRGOAAAAYEMXPdXFTXNych53U55q+se5ZYFZnrdreXh4FFjc12x/DG0BAADAE87eH45wHp63a9nrNTLbXdwOAAAAAHgiEY4AAAAAQAhHAAAAAGAQjgAAAABACEcAAAAAYBCOAAAAAEAIRwAAAABgEI4AAAAAQAhHAAAAAGD8PzAWGLsGl472AAAAAElFTkSuQmCC](url)

**Comment by andydotxyz** [comment]
By putting it in a parent widget or layout you are asking something else to control the size. As indicated in the documentation, Resize and Move are managed by layouts. What are you trying to do?

**Comment by airplayx** [comment]
> By putting it in a parent widget or layout you are asking something else to control the size. As indicated in the documentation, Resize and Move are managed by layouts. What are you trying to do?

all right
