### ISSUE TITLE
What widget to   display curve

### ISSUE THREAD

**Issue by fenglingxian** [fyne-io/fyne#592]
When I want to generate a line chart ，I didn't find the right widget。

What widget to use？

**Comment by fenglingxian** [comment]
> When I want to generate a line chart ，I didn't find the right widget。
> 
> What widget to use？

like qtchart

**Comment by fenglingxian** [comment]
same as  qtchart

**Comment by fenglingxian** [comment]
same as  qtchart

**Comment by Kvaz1r** [comment]
Plotting is not trivial task so unlikely such control appears soon, but you probably can be able plot chart into file or io.Writer and print it with fyne. 
https://github.com/wcharczuk/go-chart
https://github.com/gonum/plot

**Comment by andydotxyz** [comment]
I would recommend a Go library that draws to an image.Image and then you can show that using canvas.NewImageFromImage.

**Comment by fenglingxian** [comment]
> 绘制不是一件容易的事，因此不太可能很快出现这种控制，但是您可以将图表绘制到文件或io.Writer中，并使用fyne打印。
> [https://github.com/wcharczuk/go-chart ](https://github.com/wcharczuk/go-chart)
> https://github.com/gonum/plot

I just studied golang. I'll study it.Thanks

**Comment by fenglingxian** [comment]
> I would recommend a Go library that draws to an image.Image and then you can show that using canvas.NewImageFromImage.

It's not easy to achieve. I'll study it.Thanks.

**Comment by andydotxyz** [comment]
People have used https://github.com/vdobler/chart with Fyne before and reported it to be quite easy.

**Comment by leedstyh** [comment]
Hi, sorry to post here

Do we have any plan/roadmap on plotting chart? My use case might include plotting stock candlestick charts.

**Comment by andydotxyz** [comment]
Not currently, but people are working on things outside the core project already https://twitter.com/ajstarks/status/1245751771655475202?s=21
