### ISSUE TITLE
Make FYNE_SCALE="auto" the default on Linux

### ISSUE THREAD

**Issue by stapelberg** [fyne-io/fyne#595]
From https://github.com/fyne-io/fyne/pull/442#issuecomment-531476452:
> On linux you set FYNE_SCALE="auto"

It took me quite a while to find this. It would be nice if hi-dpi displays would be detected automatically. 

I’m not sure what the motivation was behind commit https://github.com/fyne-io/fyne/pull/454/commits/20ad36979fbb5ea192406e90ed5080106869284c. I’m guessing automated detection didn’t work on some environment, but on Linux systems, glfw uses the same algorithm as Google Chrome, which is to query the individual monitor via RandR first and fall back to the widely-set `Xft.dpi` resource second: https://sources.debian.org/src/glfw3/3.3-1/src/x11_init.c/?hl=788#L788

This is to say, on Linux, the detection generally works fine, and I think FYNE_SCALE should default to auto, at least on Linux. I can send a PR to change it, but wanted to file this issue first to check whether that would be okay?

Thanks!

**Comment by andydotxyz** [comment]
Yes, I agree. I always wanted auto (as a Linux dev mostly) but windows and macOS it didn’t always work.

There was also the issue of what is the “baseline” DPI? Should it be 72, 96? I have it set at 144, but that is too small for a lot of people. I am considering a proposal for “auto multiple” where you could specify that you’d like smaller or larger auto scaling. Perhaps I can write it here and wrap it all up in one go?

**Comment by andydotxyz** [comment]
I have written up my proposal here: https://github.com/fyne-io/fyne/wiki/Scaling-Revisited
Do you think this meets your requirements?

**Comment by stapelberg** [comment]
Thanks for the proposal! Comments:

* I’m not entirely sure having two additive scaling settings (user scale and fyne_scale) is better than what many other applications do, i.e. auto-detect a single scale setting and letting the user override it.
* The proposal includes making `auto` work again on Linux, so it does meet my personal needs.
* I’m surprised to read that macOS systems ever report wrong scaling factors. They have been at the forefront of hi-dpi displays with their Retina displays since 2013, and control hardware and software on all their devices.

**Comment by andydotxyz** [comment]
I think maybe I did not explain well - there is no intention to combine configurable scales... the detected one is coded in and the only configuration then multiplies on top of the system detected/defined scale factor.

I didn't mean to imply that macOS does it wrong. What I meant is that auto-detecting on macOS isn't the right thing to do as it already has scale management - if we use "1" as the baseline then the apps will render at the same approx scale as the OS apps - then the user could make them larger or smaller if desired...

**Comment by stapelberg** [comment]
> only configuration then multiplies on top of the system detected/defined scale factor.

Yeah, the multiplication is what doesn’t seem intuitive to me (an override seems simpler to reason about). If you’re dead set on the approach, maybe the config interface could display the effective scale factor to help users understand what’s going on.

**Comment by andydotxyz** [comment]
I’d imagined that hiding the factor may be more helpful “smaller”.. “small” etc or something like “feels like” as Apple does.

The problem with overrides is that you go right back to “1.5x lowdpi” is very different to “1.5x hidpi” so we need something to level it out for a meaningful output - that’s why I proposed a multiple approach.

Of course for windows and macOS it’s just multiplying vs the OS setting so 1.1 is a little larger and 0.9 is a little smaller. It’s going to feel exactly the same for them really, it’s just linux where the maths comes in, and that is all multiplying against a baseline of 1 == 96dpi (for instance) instead of 1 == whatever the monitor DPI happens to be.

**Comment by andydotxyz** [comment]
I have made a branch with this on in case it helps - https://github.com/fyne-io/fyne/commit/b09c93cf5846c01eae829bef0575e1361a2198f6

**Comment by stapelberg** [comment]
Just checked out the branch, and the examples now look good on my screen without setting the FYNE_SCALE environment variable.

**Comment by andydotxyz** [comment]
Great! And setting a scale > 1 gets bigger with < 1 getting smaller?
Does the code make sense? After all working is just part of a good solution ;)

**Comment by andydotxyz** [comment]
PR created for the complete solution https://github.com/fyne-io/fyne/pull/603

**Comment by andydotxyz** [comment]
This is now merged in to develop :) (thanks @okratitan).
Working next on the FyneDesk changes so it automagically scales windows, borders and backgrounds accordingly.
