### ISSUE TITLE
Add bootstrapper to get developers up faster (like efler?)

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#6]
Automate the "getting started" docs with a single entry point for any OS

**Comment by ajwillia-ms** [comment]
This now works for Mac OS X and some modern Linux distros - Windows may be a bigger problem...

**Comment by ajwillia-ms** [comment]
Thanks, I have updated the docs a little at https://github.com/fyne-io/bootstrap/ to try and help folk find this out if that's what they would prefer.

**Comment by andydotxyz** [comment]
With the new (now default) OpenGL driver this should no longer be needed.
