### ISSUE TITLE
Suppress(or change label for) menu item "Quit" in first menu of application.

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#602]
**Describe the bug**
It's not very convenient when one menu item has label in different language than others, so it would be good or to have opportunity to suppress the Quit item or customize label on it. Screenshot is below: 

**To Reproduce**
```
package main

import (
	"fmt"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
)

func main() {
	app := app.New()
	w := app.NewWindow("MCVE")
	w.Resize(fyne.Size{500, 400})
	w.SetMainMenu(
		fyne.NewMainMenu(
			fyne.NewMenu("Файл",
				fyne.NewMenuItem("Создать", func() { fmt.Println("1") }),
				fyne.NewMenuItem("Открыть", func() { fmt.Println("2") }),
				fyne.NewMenuItem("Закрыть", func() { fmt.Println("3") }),
			),
		))
	w.ShowAndRun()
}
```

**Screenshots**
![fiss1](https://user-images.githubusercontent.com/17313967/71923517-d3b58c00-3195-11ea-865e-7ede6d05f2b4.jpg)

**Device (please complete the following information):**
 - OS: Win
 - Version: 10
 - Go version go1.13.5 windows/amd64
 - Fyne version v1.2.1

**Comment by andydotxyz** [comment]
It was intended that you could replace it - but it’s flawed due to only checking English: https://github.com/fyne-io/fyne/blob/93c7b8da5bad616145e1c164a5eb5dd7079b1150/internal/driver/glfw/menu.go#L32

Clearly the right solution is to support translations, I’m not sure if there is a nice intermediate approach - perhaps we could make QuitMenuItem a type rather than a string check?

Any thoughts?

**Comment by Kvaz1r** [comment]
Thanks, I really can change label with this code:
```
	w.SetMainMenu(menu)
	for _, item := range menu.Items[0].Items {
		if item.Label == "Quit" {
			item.Label = "Выход"
		}
	}
```

So it's good enough for me. I close the issue because there is work solution and i18 is separate and really huge issue.

**Comment by andydotxyz** [comment]
Thanks, I’m glad you found a solution

**Comment by andydotxyz** [comment]
As per #605 we should find a better solution for 2.0 release

**Comment by Kvaz1r** [comment]
For some reason trick above doesn't work anymore. It seems that now menu build on running the application(`w.ShowAndRun()`) and not when main menu is setting(`w.SetMainMenu(menu)`)

**Comment by andydotxyz** [comment]
There were some changes required in event ordering to support certain window events.
The same workaround code should work if you run it in a goroutine before show (possibly with a tiny delay).
Not ideal but this is a workaround afterall - the real fix will be with localisation support in a later release.

**Comment by Kvaz1r** [comment]
Yes, that works:

```
	go func() {
		time.Sleep(2 * time.Second)
		for _, item := range menuBar.Items[0].Items {
			if item.Label == "Quit" {
				item.Label = "Выход"
			}
		}
	}()
```

It's more than enough for me. Wasn't sure that such way is correct because of concurrency.
