### ISSUE TITLE
Updating text and calling refresh for widget doesn't work

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#607]
**Describe the bug**
When updating the .Text var for either a Label or Entry (those are the ones that I have tested, might be more but I don't know) and then calling .Refresh() for that widget, nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a widget and change it's text with `yourWidgetName.Text = "something"`.
2. Refresh the widget by calling `yourWidgetName.Refresh()` afterwords.
3. Test the application for the change.
4. See that nothing happens

**Example code:**
```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
	"strconv"
)

func isNumeric(s string) bool {
	_, err := strconv.ParseFloat(s, 64)
	return err == nil
}

func main() {
	a := app.New()
	w := a.NewWindow("Temperature Converter")

	inputC := widget.NewEntry()
	inputF := widget.NewEntry()

	label := widget.NewLabel("Celsius =")

	inputC.OnChanged = func(text string) {
		if !isNumeric(inputC.Text) {
			return
		}

		cDeg, _ := strconv.Atoi(inputC.Text)
		fDeg := float64(cDeg)*(9.0/5.0) + 32

		inputF.Text = strconv.Itoa(int(fDeg))
		inputF.Refresh()
	}

	inputF.OnChanged = func(text string) {
		if !isNumeric(inputF.Text) {
			return
		}

		fDeg, _ := strconv.Atoi(inputF.Text)
		cDeg := (float64(fDeg) - 32) * (5.0 / 9.0)

		inputC.Text = strconv.Itoa(int(cDeg))
		inputC.Refresh()
	}

	w.SetContent(fyne.NewContainerWithLayout(layout.NewGridLayout(4),
		inputC, widget.NewLabel("Celsius ="), inputF, widget.NewLabel("Fahrenheit")))

	w.ShowAndRun()
}
```

**Device (please complete the following information):**
 - OS: [e.g. Linux, iOS] Solus (Linux)
 - Version [e.g. 22] 4
 - Go version [e.g. 1.12] 1.13.5
 - Fyne version [e.g. 1.1 or git SHA] 1.2.1

**Comment by Kvaz1r** [comment]
You can and probably should use method SetText/1 and not use directly setting value for Text field in that case your code work as expected. 

I can reproduce the behavior and it seems that Refresh/0 doesn't call refresh for inner [textProvider](https://github.com/fyne-io/fyne/blob/831e9ea605b29b9cb0de737067b741009d387a2f/widget/text.go#L114) as it happens in SetText/1 method.

**Comment by andydotxyz** [comment]
Text, as with other properties, is available to developers who want to change data without refreshing (like 4 things should be changed and you don’t want to cause 4 refreshes).

This is a valid bug and the use case should be supported.

**Comment by andydotxyz** [comment]
on release/v1.2.2 for testing

**Comment by Jacalz** [comment]
Thanks. I will test it as soon as I get home 👍

**Comment by Jacalz** [comment]
Looks like the fix does what it is supposed to do. Good job :+1:
