### ISSUE TITLE
Deprecated warning on demo

### ISSUE THREAD

**Issue by krostar** [fyne-io/fyne#61]
Hi,

When I `go run` the demo, I'm getting the following message:

```console
$> go run .
# fyne.io/fyne/driver/gl
../../driver/gl/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here
```

The app is launching without any problems though.
I don't really know what information to add, let me know if you need more info.

krostar

**Comment by andydotxyz** [comment]
Yes, sorry, macOS Mojave has deprecated OpenGL.
To make this go away we will have to add a MetalKit driver for darwin :(

**Comment by LucasMW** [comment]
So it was addressed

**Comment by andydotxyz** [comment]
Unfortunately not - but the deprecation warning does not impact the framework at this time so we closed it. It is technically blocked on #183

**Comment by cnbuff410** [comment]
Is this warning going away with the potential release 3.3 of GLFW?

**Comment by andydotxyz** [comment]
It should do, yes. We need to work with the Go-gl/glfw project to get the Go bindings released before we can see that benefit. Tracking in #183
