### ISSUE TITLE
Support Multiple Screen

### ISSUE THREAD

**Issue by DalfDev** [fyne-io/fyne#610]
**Is your feature request related to a problem? Please describe.**
To make an application that can be displayed on two screens of the same computer, you have to be able to choose on which screen you launch a window. 

**Is it possible to construct a solution with the existing API?**
Should be possible as far as I can see.

**Describe the solution you'd like**
Choose on which screen you want to display the window.

**Comment by andydotxyz** [comment]
This is normally controlled by your window manager or operating system.
Can you provide some more information so we can understand this better please?

**Comment by andydotxyz** [comment]
Request for information over 9 months old, closing
