### ISSUE TITLE
Window hangs when Ctrl+V in entry

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#611]
### To Reproduce:
Steps to reproduce the behaviour:
1. Copy some text
2. Run example code
3. Ctrl+V in entry
4. Program stop responding, see hang

### Screenshots:
https://i.imgur.com/7SGmyTA.png

### Example code:

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")

	w.SetContent(widget.NewEntry())
	w.Resize(fyne.NewSize(300, 300))
	w.ShowAndRun()
}
```

### Device
 - OS: Ubuntu 18.04 bionic, KDE 5.47.0 / Plasma 5.12.9, Linux 4.15.0-74-generic
 - Go version: 1.13
 - Fyne version: develop, v1.2.2-0.20200111142255-87f5739f077d

Error is reproduced only on develop branch, v1.2.1 seems ok. Also hangs when press Ctrl+C. Ctrl+A is ok

**Comment by andydotxyz** [comment]
This is a good catch, thanks.
And sorry!

**Comment by andydotxyz** [comment]
Available for testing on develop branch
