### ISSUE TITLE
Mouse Down ignores object visibility

### ISSUE THREAD

**Issue by krostar** [fyne-io/fyne#62]
Hi,

On the demo app, in the demos menu, on the Widgets items there is three tabs: buttons, input and group. When I click on the second tab (Input) and play with widgets, there is few callbacks print (`checked true/false`, `selected Item 1/2`, ...).

The problem is that if I click on the third tab (group) and click on the same location the widgets of the input tab were, I'm getting the same callbacks print. For example if I click on the background right below "Grouped content", I get the message `checked true/false` ; if I click even lower I'm getting the `selected Item 1/2` message`.

I'm not sure I'm explicit enough, I can take screenshot if needed.
krostar

**Comment by andydotxyz** [comment]
Aha! a great bug thanks.
The click handler is ignoring object visibility.

Oops!

**Comment by andydotxyz** [comment]
This was resolved at the same time as #69
