### ISSUE TITLE
about prerequisites

### ISSUE THREAD

**Issue by lanseyujie** [fyne-io/fyne#622]
Hello, I think there is something wrong with the *README.md*.

> Debian/Ubuntu based systems may also need to install the `libegl1-mesa-dev` and `xorg-dev` packages.

I installed it on kubuntu, but I still can't compile the demo due to the error **Package gl was not found in the pkg-config search path.**.

I found the package name is `libgl1-mesa-dev`, not `libegl1-mesa-dev` in [https://github.com/go-gl/gl](https://github.com/go-gl/gl) , and I tested that it works with `libgl1-mesa-dev`.

**Comment by andydotxyz** [comment]
Thanks very much, you are quite right - it was accidentally added when we added GLES support for arm devices. I'll update the docs somehow (both are correct, depending on the system).
