### ISSUE TITLE
Dialog with large width contents overflows

### ISSUE THREAD

**Issue by spatocode** [fyne-io/fyne#627]
### Describe the bug:
While making a steady input in an entry inside a custom dialog, the dialog width increases tremendously till it overflows the parent container's visibility. This is as a result of the issue #378. Similarly, this also happens if you create a dialog with a large message/content. Now a better approach could be to set a fixed size for the dialog. We could also add a scroller to the entry(see #471)  in a dialog, but this doesn't look like a good UI design for the dialog.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to the fyne demo app.
2. Click on windows tab.
3. Click on the custom button under the custom group.
4. Make a steady character input
5. See error

### Device (please complete the following information):
 - OS: [Windows]
 - Version: [10]
 - Go version: [e.g. 1.13.5]
 - Fyne version: [e.g. 1.2.0]

**Comment by andydotxyz** [comment]
It seems like this might be a duplicate of #471, what do you think?

**Comment by spatocode** [comment]
Not at all. #471 is a feature request on entries. This is about dialog width size with respect to its contents(it may be an entry or message). Maybe the issue title is misleading. Will change that.

**Comment by andydotxyz** [comment]
Thanks, I guess this opens a more complex question.
All Fyne API is based upon packing items into containers based on at least their MinSize - a dialog, or any window, will be at least the MinSize of it's content.

With that in mind what would you propose? For Entry the issue you describe is clear - a user can expand the content (which we can fix with adding a scroller). However I'm not sure what the bigger picture is here. Can you provide some more information about the problem?

**Comment by spatocode** [comment]
Adding scrollers to entry in a dialog solves the problem for contents(entry), but from a UI perspective i don't think that having scroller on dialog entry is common. I'm thinking of a better way of hiding overflowed entry texts without the use of scroller.

Asides entry, contents like texts/messages with a large width size increases the dialog size tremendously. This makes the dialog too large and even overflows it's visibility in worst cases. Maybe we need to find a way to ensure that very long texts span more than one line.

**Comment by metaclips** [comment]
> Adding scrollers to entry in a dialog solves the problem for contents(entry), but from a UI perspective i don't think that having scroller on dialog entry is common. I'm thinking of a better way of hiding overflowed entry texts without the use of scroller.
> 
> Asides entry, contents like texts/messages with a large width size increases the dialog size tremendously. This makes the dialog too large and even overflows it's visibility in worst cases. Maybe we need to find a way to ensure that very long texts span more than one line.

What of password entries I really dont think it'll go well with this. Also how would one differentiate it with if enter key is pressed, are texts going to be double spaced?

**Comment by andydotxyz** [comment]
Perhaps #332 plus #471 resolve this then?

**Comment by spatocode** [comment]
> What of password entries I really don't think it'll go well with this. Also how would one differentiate it with if enter key is pressed, are texts going to be double spaced?

I'm not sure i got you question, but i think password entries are same with others in this case.
I'll close this now as #332 will definitely solve this issue.
