### ISSUE TITLE
"hello world" error

### ISSUE THREAD

**Issue by holu123gg** [fyne-io/fyne#631]
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
exec: "gcc": executable file not found in %PATH%
# fyne.io/fyne/vendor/github.com/go-gl/gl/v3.2-core/gl
exec: "gcc": executable file not found in %PATH%

it's on windows 10. 
i  checked  that  there are " c:/mingw64/bin"   in  environment  variable   "path"

what  should i  do now  to fix it?

**Comment by holu123gg** [comment]
i tried msys2  ,  there is  the same   problem

**Comment by Kvaz1r** [comment]
Which version of Go do you have? (amd64/386)

**Comment by holu123gg** [comment]
amd64

**Comment by Kvaz1r** [comment]
There are really many problem with path in Windows and really few installers made the process properly. Could you check will the issue gone if you install gcc together with [Strawberry Perl](http://strawberryperl.com) for 64-bit systems?

**Comment by holu123gg** [comment]
i  fix  it;  it's  my fault .  
i  typed "c/mingw/bin" into  env variable, but  installed   mingw into  "c:/mingw/mingw"

thanks  for your response
