### ISSUE TITLE
Scale does not match user configuration in Windows 10

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#635]
### Describe the bug:
There is a user configuration for a percentage scale in Windows 10.
Fyne apps do not respect this

### To Reproduce:
Steps to reproduce the behaviour:
1. Load Fyne app on Windows 10
2. Right click desktop -> desktop settings
3. Scroll to scale and set it to, for example, 200%
4. See that fyne app does not update
5. Launch another instance of the app and see it is the same size as the first one.

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: 1.12.5
 - Fyne version: 1.2.1

**Comment by perqin** [comment]
There is [an API](https://github.com/glfw/glfw/commit/16bf872117896fb88493403157fcd367303fd1f6#diff-7a6c70f06dc23e69c5a9bfe9c3967e64R1957) for retrieving system scaling, does it help?

**Comment by andydotxyz** [comment]
Absolutely!
We just need to get GLFW 3.3.2 into the go bindings, which recently update to 3.3.
As soon as it's available we could use that API to resolve this ticket - good catch.

**Comment by DamnWidget** [comment]
Also happening to me on Linux with version v1.2.2 it was fine on v1.1.1 Scaling feels broken in general on v1.2.2

![image](https://user-images.githubusercontent.com/329766/74575200-f3528800-4f7d-11ea-966f-b06e27a4c385.png)
![image](https://user-images.githubusercontent.com/329766/74575248-1bda8200-4f7e-11ea-84ca-57d7154df7ff.png)

Is there any way to enforce an scale in the meanwhile?

**Comment by andydotxyz** [comment]
The behaviour on Linux is changed in 1.2.2 @DamnWidget. For all platforms we added a “system scale”, for macOS this is “1” due to the way it handles scaling. On Windows we seem to have the bug that is the topic of this issue.

On Linux (as there is no standard for scaling) it calculates the DPI of a screen and updates system scale so the base is 96DPI. A user scale of 1.2 will larger than this or 0.9 will be smaller. The readout in fyne_demo is the result of system*user (we should update this to display the details). It looks like you have a fairly dense screen and so the system scale is calculated as 1.5.

I hope this helps. In an updated version of our settings UI I think we will update it to “tiny” “small” “normal” “big” “huge” so the maths is hidden completely.

This enables windows to maintain real size when dragged from one screen to another when they are very different sizes.

**Comment by DamnWidget** [comment]
So in my screen that calculation should be around 144DPi as my screen is 344mm x 194mm and my resolution 1920x1080 so it's around a 200% bigger than any other element in my desktop. This feels pretty alien being honest.

Shouldn't be the behavior to apply a 1x factor by default and let the user choose if they want to make it bigger (or smaller). By the way, is there any way to modify the scale while the application is running and the window is drawn?

**Comment by andydotxyz** [comment]
I also prefer around 144dpi, which is what we originally based it on. However it was pointed out that other platforms default to 96 so we corrected. If you set your scale to 0.7 or 0.8 you should be sorted - this is basically the user setting. We considered adding a “disable auto” flag but with that set then dragging a window to a low DPI screen you’d see it get much bigger, which is what we are trying to avoid.

You can change settings at runtime using the fyne_settings app - ‘go get fyne.io/fyne/cmd/fyne_settings’.

**Comment by DamnWidget** [comment]
Gotcha, sorry for hijack the issue thread by the way

**Comment by andydotxyz** [comment]
On develop for testing

**Comment by andydotxyz** [comment]
Sorry, this fix cannot go out with 1.2.4 as it depends on GLFW that we have not pushed back into 1.2.x
We will be releasing it with 1.3 coming as soon as we can wrap up the feature work as well.
