### ISSUE TITLE
Rendering is blocked on some scaling

### ISSUE THREAD

**Issue by perqin** [fyne-io/fyne#637]
### Describe the bug:

When setting scale to some value with `FYNE_SCALE` environment variable, the rendering seems blocked.

### To Reproduce:
Steps to reproduce the behaviour:
1. The snippet in *Example code* section below renders a button. When everything works properly, the background of the button will change when the mouse is hovering over it.
2. Set `FYNE_SCALE` environment variable to `2.2` and re-run.
3. Move the mouse and the button is unresponsive now.
4. Setting scale to `2.5` is working.

### Example code:

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	application := app.New()

	window := application.NewWindow("Hello")
	c := fyne.NewContainerWithLayout(layout.NewCenterLayout(), widget.NewButton("Hello", func() {
	}))
	c.Resize(fyne.Size{Width: 300, Height:300})
	window.SetContent(c)

	window.ShowAndRun()
}
``` 

### Device (please complete the following information):
 - OS: Windows 10
 - Version: 10.0.18363
 - Go version: 1.13.6
 - Fyne version: 1.2.1
 - Device info: Laptop with a screen of resolution 3840x2160 and system's scaling set to 250%.

**Comment by andydotxyz** [comment]
We have fixed some issues in the pending v1.2.2 release - is it possible for you to test with the "release/v1.2.2" branch to see if this issue is resolved for you?

**Comment by perqin** [comment]
This is solved in v1.2.2, thanks! By the way, I am wondering why the scale is set to 1.0 by default? In my opinion we can set default to auto, and also use detected system configuration (like the scale settings in Windows 10) on auto mode.

**Comment by andydotxyz** [comment]
You're quite right, but 1.0 is the new "auto" as it's relative to system setting.
That said there is indeed an issue with Windows 10 #635.
On macOS the system controls scale so 1.0 is the right baseline - it seems that Windows 10 does not behave the same way.

On linux it is "auto" as previously understood because there is no core DPI control.

**Comment by andydotxyz** [comment]
1.2.2 is now live, closing this issue.
