### ISSUE TITLE
Numpad keyEvents don't fire

### ISSUE THREAD

**Issue by xphlawlessx** [fyne-io/fyne#642]
Key event's for numpad keys not firing (*,/,-,+,.) and all numbers, i can see in the source that the numbers atleast should work, any ideas?
Windows 10

**Comment by andydotxyz** [comment]
Can you share the code that is not working? There are various different ways to listen to keys or symbols... are you using TypedKey when actually TypedRune would provide relevant events?

**Comment by xphlawlessx** [comment]
Oh, that's exactly what I was missing. My apologies , can I close this or is that something the owner does? Thanks.

**Comment by andydotxyz** [comment]
Great thanks. Feel free to close if you’re happy
