### ISSUE TITLE
The secondary tap for buttons is not implemented

### ISSUE THREAD

**Issue by palikar** [fyne-io/fyne#644]
Looking at the [button file](https://github.com/fyne-io/fyne/blob/master/widget/button.go), I can see that there is a facility for capturing secondary clicks on a button. I assume that this is an event for when the button widget is clicked with the right mouse button.

However, it seems that the end user (developer) can't use this feature. The `TappedSecondary` function is empty. Is there any particular reason for that? Do you have plans to implement this soon? I could implement it myself and submit a PR if there is an interest in this missing feature.

**Comment by andydotxyz** [comment]
You are quite right, the default button does not have right click functionality. This is not a mistake, we don’t think this feature is a common use-case. In your application you can extend the standard button and provide a TappedSecondary replacement, like the document at https://fyne.io/develop/extending-widgets.html.
