### ISSUE TITLE
entry cannot get the width of the parent element and adapt

### ISSUE THREAD

**Issue by baolitoumu** [fyne-io/fyne#646]
It seems that the child elements cannot be displayed correctly when trying to implement the first layout below
![image](https://user-images.githubusercontent.com/14047916/73713895-ffeb0b00-4749-11ea-993a-a91cca7bcfe5.png)

code：

````
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
	"fyne.io/fyne/widget"
	"image/color"
)
func main()  {
	a := app.New()
	w := a.NewWindow("xxxxx")
	w.SetPadded(false)
	w.SetContent(
		mainview(),
	)
	a.Settings().SetTheme(theme.LightTheme())
	w.Resize(fyne.NewSize(900, 700))
	w.ShowAndRun()
}
func mainview() *fyne.Container {
	w2 := widget.NewEntry()
	w2.SetPlaceHolder("email")
	email := widget.NewScrollContainer(w2)
	return fyne.NewContainerWithLayout(
		layout.NewCenterLayout(),
		email,
		BorderBody(270,40),
	)
}
func BorderBody(width,hight int) *fyne.Container   {
	top:=HorizontalLine(width,1)
	bottom:=HorizontalLine(width,1)
	left:=VerticalLine(hight,1)
	right:=VerticalLine(hight,1)
	borderset:=layout.NewBorderLayout(top,bottom,left,right)

	return fyne.NewContainerWithLayout(borderset,top,bottom,left,right)
}
func HorizontalLine(length, strong int) fyne.CanvasObject {
	rect := canvas.NewRectangle(&color.RGBA{0, 0, 0, 0xff})
	rect.SetMinSize(fyne.NewSize(length, strong))
	rect.Visible()
	return rect
}
func VerticalLine(length, strong int ) fyne.CanvasObject {
	rect := canvas.NewRectangle(&color.RGBA{0, 0, 0, 0xff})
	rect.SetMinSize(fyne.NewSize(strong, length))
	return rect
}

```

**Comment by baolitoumu** [comment]
![image](https://user-images.githubusercontent.com/14047916/73714347-92d87500-474b-11ea-9c2a-d78901d261b3.png)
![image](https://user-images.githubusercontent.com/14047916/73714360-9a981980-474b-11ea-97cc-1dada0a93e21.png)

**Comment by andydotxyz** [comment]
Widgets in Fyne are padded by default according to MinSize. A container's layout controls any additional sizing required. The code you have used is working correctly.

```
return fyne.NewContainerWithLayout(
		layout.NewCenterLayout(),
		email,
```

The center layout places all items in the center of the container at their minimum size.
You need to pick the correct layout. Looking at your illustration I imagine that VBoxLayout is the best match - that stacks items one above the other at their minimum height, but filling the width of the container it lays out.

I would recommend reading the layout tour available at https://tour.fyne.io/layout/.

**Comment by andydotxyz** [comment]
Closing as not an issue, the requested layout is working as expected.

**Comment by baolitoumu** [comment]
thx so much，i fist to see the tour
