### ISSUE TITLE
Add basic media control Icons to theme (ie: play, pause, stop, ff/rev etc.)

### ISSUE THREAD

**Issue by rootVIII** [fyne-io/fyne#649]
### Is your feature request related to a problem? Please describe:
I just finished a rough version of a [Roku GUI remote ](https://github.com/rootVIII/rokuremote) using Fyne. As you can see there, the icons look great except that I am missing a couple (Play... maybe on/off).

### Is it possible to construct a solution with the existing API?
I don't think so. I checked [here](https://github.com/fyne-io/fyne/blob/master/theme/icons.go) as well as the theme godocs and didn't see any transport controls.

### Describe the solution you'd like to see:
Possibly adding more icons in the next release? Thank you :) And sorry for opening a 2nd report.

**Comment by andydotxyz** [comment]
Absolutely. We use the material design icons which are downloaded in svg format and bundled into theme/icons/ folder. Adding these seems like a good idea - we would accept pull requests as well :)

**Comment by rootVIII** [comment]
Ok thank you!

**Comment by andydotxyz** [comment]
On develop for testing :)

**Comment by rootVIII** [comment]
I just saw! Thank you so much!
