### ISSUE TITLE
Silently ignores -executable flag when packaging for a mobile OS

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#652]
### Describe the bug:

`fyne package` silently ignores the `-executable` flag when packaging for a foreign OS, and always tries to build.  Fyne *should* let the user know that it's ignoring command-line flags, even if it's for a good reason.

### To Reproduce:

Steps to reproduce the behaviour:
1. Check out a project
2. Build an executable
3. Try to use `fyne` to package for, e.g., Android

```
$ hg clone https://hg.sr.ht/\~ser/healthdiary
$ go build -o hd ./cmd/diary
$ fyne package -os android -appID ser1.net.healthdiary -executable ./hd -icon assets/hdf.png -name "Health Diary"
can't load package: package .: no Go files in /home/ser/tmp/healthdiary

Error building application: exit status 1
```

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.4.15
 - Go version: go version go1.13.7 linux/amd64
 - Fyne version: Fyne doesn't have an (obvious) version function, but git reports it was built from eba8bb2e8629ad0cbe2d4b07a051043a9759e4f3

**Comment by andydotxyz** [comment]
Thanks, this should be fixed. It needs to warn the developer that -executable flag is ignored for mobile builds. The binary that you have built will most likely not be suitable for packaging Android and so it needs to rebuild.

**Comment by andydotxyz** [comment]
New version on develop ready for testing

**Comment by xxxserxxx** [comment]
Confirmed fixed.
