### ISSUE TITLE
empty space on autoscale when window.SetFixedSize(true)

### ISSUE THREAD

**Issue by Cherrg** [fyne-io/fyne#654]
### Describe the bug:

if window.SetFixedSize(true) id set and the window get scaled automatically. e.g. when moved to second screen with lower DPI, there is some unused space, as the content is scaled, but the window keeps its size

### To Reproduce:
Steps to reproduce the behaviour:
- create a window with some elements
- set window.SetFixedSize(true)
- compile 
- move the window to second screen with same resolution, but much larger  --> lower DPI
- the Bug: The content is resized, while the window keeps the old pixel count -> so there is a huge unused space in the window

### Screenshots:

![image](https://user-images.githubusercontent.com/24939127/73984664-739f3a80-4939-11ea-9b9e-362e4e0bf770.png)
![image](https://user-images.githubusercontent.com/24939127/73985424-6e42ef80-493b-11ea-9f6a-5f5f0dc18f2e.png)

### Device (please complete the following information):
 - OS: [ubuntu 18.04 lts]
 - Window Manager: kde/plasma5 
 - Go version: [e.g. 1.13.7]
 - Fyne version: [some commits after 1.2.2 or git SHA: f8e2b48639beb1bf4b28af4b08d39f27a5f7396b]

EDIT: 
the click bindings seem to be still in window size
-> added screenshot of demo app -> see position of mouse cursor and button hover effect

**Comment by andydotxyz** [comment]
I've looked at the code and I cannot understand why this might happen.
I wonder if possibly the window manager will not allow a window to become smaller than the initial minsize (we do change minsize).
Is it possible to test with a different window manager / desktop environment with the same configuration otherwise?

**Comment by Cherrg** [comment]
did a test on a different machine:
OS: Ubuntu18.04lts
Window Manager: XFCE4.12
Result: same bug:
![grafik](https://user-images.githubusercontent.com/24939127/74094007-8d2bb800-4ada-11ea-8044-66baf9a77e3b.png)

(I will add a third test on different window manager and edit this comment in a few minutes)

**Comment by andydotxyz** [comment]
Thanks very much. I guess I need to look somewhere else.

**Comment by andydotxyz** [comment]
Ok I popped a fix on the release/v1.2.3 branch maybe you could test and confirm?
