### ISSUE TITLE
Fyne can't package mobile apps using modules

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#655]
### Describe the bug:

`fyne package` fails building for foreign OSes when the package contains external dependencies, but the command it fails on works when run manually.

### To Reproduce:

Because of #653, we have to move the sources into the current directory.

```
$ hg clone https://hg.sr.ht/\~ser/healthdiary
destination directory: healthdiary
requesting all changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 4 changes to 4 files
new changesets 65d468f58cb5
updating to branch default
4 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ cd healthdiary
$ mv ./cmd/diary/*.go .                                                                         
$ fyne package -os android -appID ser1.net.healthdiary -sourceDir . -icon assets/hdf.png -name "Health Diary"
/usr/lib/go/bin/go build -buildmode=c-shared -o /tmp/gomobile-work-979800834/lib/armeabi-v7a/libgo_.so . failed: exit status 1
main.go:40:2: cannot find package "github.com/peterbourgon/diskv/v3" in any of:
        /usr/lib/go/src/github.com/peterbourgon/diskv/v3 (from $GOROOT)
        /home/ser/go/src/github.com/peterbourgon/diskv/v3 (from $GOPATH)

$ /usr/lib/go/bin/go build -buildmode=c-shared -o /tmp/gomobile-work-979800834/lib/armeabi-v7a/libgo_.so .
$ echo $?
0
$ file /tmp/gomobile-work-979800834/lib/armeabi-v7a/libgo_.so
/tmp/gomobile-work-979800834/lib/armeabi-v7a/libgo_.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=b57067112acbd77f919ac09e9a0cd1df17ec6a33, not stripped
```

#### EDIT

Vendoring the dependencies doesn't work, either:

```
$ go mod vendor
$ ls vendor/github.com/peterbourgon/diskv/v3/                                                   
compression.go
diskv.go
go.mod
go.sum
index.go
LICENSE
README.md
$ fyne package -os android -appID ser1.net.healthdiary -sourceDir . -icon assets/hdf.png -name "Health Diary"
/usr/lib/go/bin/go build -buildmode=c-shared -o /tmp/gomobile-work-175352815/lib/armeabi-v7a/libgo_.so . failed: exit status 1
main.go:40:2: cannot find package "github.com/peterbourgon/diskv/v3" in any of:
        /usr/lib/go/src/github.com/peterbourgon/diskv/v3 (from $GOROOT)
        /home/ser/go/src/github.com/peterbourgon/diskv/v3 (from $GOPATH)
```

#### EDIT 2

Fyne *can* build packages with dependencies for foreign OSes if changes are made to the code to accomodate it.  This probably won't work except for trivial dependency lists, but maybe it'll help someone.

`diskv` uses go modules, and has a `v3` at the end.  This needs to be stripped.  I'm going to 1) move the sources around to get past #653; 2) manually `go get` the `diskv` project; and 3) change the sources so they're importing the package without the major version information.

```
$ cd ~/tmp
$ rm -rf healthdiary
$ hg clone https://hg.sr.ht/\~ser/healthdiary
$ cd healthdiary
$ go get -u github.com/peterbourgon/diskv
$ mv ./cmd/diary/main.go .
$ sed -i 's^diskv/v3^diskv^' main.go
$ fyne package -os android -appID ser1.net.healthdiary -sourceDir . -icon assets/hdf.png -name "Health Diary"
$ echo $?
0
$ file healthdiary.apk
healthdiary.apk: Zip archive data, at least v2.0 to extract
```

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.4.15
 - Go version: go version go1.13.7 linux/amd64
 - Fyne version: Fyne doesn't have an (obvious) version function, but git reports it was built from eba8bb2e8629ad0cbe2d4b07a051043a9759e4f3

**Comment by andydotxyz** [comment]
The “mv” line above seems strange - can you explain?

When you repeat the command it is no longer building Android as the environment variables are different - to try and reproduce the build you would need to set GOOS to android and also a suitable GOARCH flag.

Have you tried installing the dependency using “go get”?

**Comment by xxxserxxx** [comment]
@andydotxyz sure; it's because #653, where fyne won't build applications for foreign OSes unless the sources are in the current directory.

Also, I figured out how to get it to build with the recent edit.  I would *guess* fyne is struggling with go modules, because if I remove the major version from the import (the v3), and manually check out the package, I can get it to build.

Note, `go` has no issue with this.

```
$ cd ~/tmp
$ rm -rf healthdiary
$ hg clone https://hg.sr.ht/\~ser/healthdiary
destination directory: healthdiary
requesting all changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 4 changes to 4 files
new changesets 65d468f58cb5
updating to branch default
4 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ cd healthdiary
$ go build -o thing ./cmd/diary
$ echo $?
0
```

**Comment by andydotxyz** [comment]
You're quite right in your guess. Fyne package can handle modules, but not when building for iOS and Android. We base on gomobile tooling which is currently adding mobile support so we should be able to fix this in an upcoming release.

**Comment by xxxserxxx** [comment]
Sort of!  It does work, but only if the import doesn't include a major revision number.  I filed #660, which is a stand-alone test for this with a number of observations, explicit commands for reproducing, and some screencap videos demonstrating behaviors.  It's strange that modules work but choke on version numbers.

It still sounds like an upstream issue, but #660 can serve as a test when they fix it.

**Comment by xxxserxxx** [comment]
#660 is a cleaner duplicate of this, so closing this one.
