### ISSUE TITLE
fyne package mobile apps ignore -name flag

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#657]
### Describe the bug:

APKs after installation produce an application entry with an icon, but no application name.

### To Reproduce:

This depends on the steps in **EDIT 2** of #655, which I won't repeat here.  The last step after munging the repository is to build the APK; then connect an Android device and install the APK.

```
$ fyne package -os android -appID ser1.net.healthdiary -sourceDir . -icon assets/hdf.png -name "Health Diary"
$ adb -d install healthdiary.apk
Performing Streamed Install                                                                     
Success        
```

Once installed, the application has either no name or "."; according to the Android app info screen, it's name is "ser1.net.healthdiary".

### Screenshots:

On the Launcher (the very first application):

![screenshot](https://user-images.githubusercontent.com/60757196/73989382-3623b880-490b-11ea-9ecf-83c92708bc24.png)

And querying Android for the app info:

![appinfo](https://user-images.githubusercontent.com/60757196/73989386-3a4fd600-490b-11ea-9c4c-5f7fbab2442e.png)

### Device (please complete the following information):
 - Mobile: Google Pixel 2, Android 10
 - OS: Linux
 - Version: 5.4.15
 - Go version: go version go1.13.7 linux/amd64
 - Fyne version: Fyne doesn't have an (obvious) version function, but git reports it was built from eba8bb2e8629ad0cbe2d4b07a051043a9759e4f3

**Comment by andydotxyz** [comment]
Thanks. I think that the mobile build is determining name from the directory (which you specified as "."). It should not ignore the -name parameter. Thanks for reporting

**Comment by andydotxyz** [comment]
Fixed on develop ready for testing

**Comment by xxxserxxx** [comment]
Confirmed fixed.
