### ISSUE TITLE
Error unicode decoding with(without) correct font

### ISSUE THREAD

**Issue by yougg** [fyne-io/fyne#659]
### Describe the bug:
the task bar title and launcher tip text was error decoding

### To Reproduce:
run with following code:
```go
func main() {
	a := app.New()

	w := a.NewWindow("Go图形界面")
	w.SetContent(&widget.Box{Children: []fyne.CanvasObject{
		&widget.Label{Text: "你好 Fyne!"},
		&widget.Button{Text: "再见", OnTapped: func() {
			a.Quit()
		}},
	}})

	w.ShowAndRun()
}
```
set chinese font and run:
```bash
export FYNE_FONT=~/.local/share/fonts/SIMYOU.TTF
go run hello.go
```

### Screenshots:

![image](https://user-images.githubusercontent.com/1641020/74037246-db688a80-49f8-11ea-98b6-27979d3349d8.png)

![image](https://user-images.githubusercontent.com/1641020/74037263-e58a8900-49f8-11ea-80fa-6e5a3ba12e81.png)

### Device :
 - OS: Ubuntu 19.10 x86_64
 - Go version:  1.13.6
 - Fyne version: 1.2.2

**Comment by andydotxyz** [comment]
Thanks. We must have an encoding issue in the encoding of metadata.
Had you run "fyne install" before or not?

If you were just running "go run" it is possible that this is a gnome issue!

**Comment by yougg** [comment]
tried `fyne install`,  still the same error

**Comment by andydotxyz** [comment]
are you launching from the command line or from an app launcher? Do both behave the same way?

**Comment by yougg** [comment]
both launch from command line and app launcher cause the same result

**Comment by andydotxyz** [comment]
OK thanks. This seems to be specific to Linux/Ubuntu, as other OS are working as expected.
I'll have to get an Ubuntu VM running to try and see what's going on.

**Comment by zyfdegh** [comment]
I solved this by setting `FYNE_FONT ` as said in #736 
```sh
# 1. download a free Chinese font http://www.foundertype.com/index.php/FontInfo/index.html?id=131
# 2. put it to your projects, e.g. under assets/ 
$ export FYNE_FONT=assets/fzhtjw.ttf
$ go run main.go
```

**Comment by yougg** [comment]
@zyfdegh 
it is not font mismatch in my problem, it is error decoding

**Comment by andydotxyz** [comment]
It's an interesting question - is the font you are passing to Fyne the same as the one used in the status bar/icon bar?

**Comment by yougg** [comment]
i have try to set the system font and launch the application,  it's still not working.  

![image](https://user-images.githubusercontent.com/1641020/79215873-d6074080-7e7e-11ea-8c29-49cd42bac05d.png)

**Comment by andydotxyz** [comment]
Ah! I see from that screenshot that it’s not taking the info from the window at all, it’s some other metadata. I guess there is metadata somewhere that isn’t in the window. When you launch from the command line what command do you use?

**Comment by yougg** [comment]
i ran 'hello' application from app launcher in the last screenshot

after set the system font to 'YouYuan.ttf' and reboot OS, i run `./hello` or `go run hello.go` command with (or without) `export FYNE_FONT=/usr/share/fonts/truetype/youyuan/YouYuan.ttf` in command line, it's the same result.

**Comment by lysShub** [comment]
> I solved this by setting `FYNE_FONT ` as said in #736
> 
> ```shell
> # 1. download a free Chinese font http://www.foundertype.com/index.php/FontInfo/index.html?id=131
> # 2. put it to your projects, e.g. under assets/ 
> $ export FYNE_FONT=assets/fzhtjw.ttf
> $ go run main.go
> ```



> I solved this by setting `FYNE_FONT ` as said in #736
> 
> ```shell
> # 1. download a free Chinese font http://www.foundertype.com/index.php/FontInfo/index.html?id=131
> # 2. put it to your projects, e.g. under assets/ 
> $ export FYNE_FONT=assets/fzhtjw.ttf
> $ go run main.go
> ```
great
you should open this folder
```
C:\Windows\Fonts
```

**Comment by changkun** [comment]
I spend some time to dig this issue. I started with a simple example using glfw:

```
package main

import (
	"runtime"

	"github.com/go-gl/glfw/v3.3/glfw"
)

func init() { runtime.LockOSThread() }
func main() {
	err := glfw.Init()
	if err != nil {
		panic(err)
	}
	defer glfw.Terminate()

	window, err := glfw.CreateWindow(640, 480, "你好", nil, nil)
	if err != nil {
		panic(err)
	}
	window.MakeContextCurrent()

	for !window.ShouldClose() {
		window.SwapBuffers()
		glfw.PollEvents()
	}
}
```

And apparently the problem exists:

![image](https://user-images.githubusercontent.com/5498964/139821452-829419c4-c3ce-4966-86e4-ac47d634c2b6.png)

Hence the problem cannot be fixed unless glfw can fix it (since fyne is based on glfw window management).

Then, while digging into glfw source code, it turns out that the window title on the topbar is set by XClassHint in glfw:

https://github.com/glfw/glfw/blob/fb0f2f92a38c1d6a776ffeb253329f8d1c65694c/src/x11_window.c#L759-L760

The source code looks fine then I starts to wonder how it might be fixed.
Then I wrote an even simple example using plain X11 APIs:

```
// g++ -o main main.cpp -lX11 -lGL -lGLEW -L/usr/X11/lib -I/opt/X11/include
#include <iostream>
#include <cstring>

#include <X11/Xlib.h>
#include <X11/Xutil.h>

const char *title = "你好";

int main(int argc, char** argv) {
	Display* d = XOpenDisplay(NULL);
	if (d == NULL) {
		std::cout << "Could not open display\n";
		return 1;
	}
	Window w = XCreateWindow(d, RootWindow(d, DefaultScreen(d)), 0, 0, 800, 600, 0, 0, 0, 0, 0, NULL);

	// Set window title
	XChangeProperty(d,  w,
		XInternAtom(d, "_NET_WM_NAME", False),
		XInternAtom(d, "UTF8_STRING", False), 8,
		PropModeReplace, (unsigned char*) title, strlen(title));

	// Set top bar title
	XClassHint* hint = XAllocClassHint();
	hint->res_name  = (char*) title;
	hint->res_class = (char*) title;
	XSetClassHint(d, w, hint);
	XFree(hint);

	XClearWindow(d, w);
	XMapRaised(d, w);

	XEvent ev;
	while (true) { XNextEvent(d, &ev); }

	XDestroyWindow(d, w);
	XCloseDisplay(d);
	return 0;
}
```

![image](https://user-images.githubusercontent.com/5498964/139822188-e6d35711-ce3f-4405-9dec-f415ff6eafe2.png)

Problem exists. Later I found [document](https://linux.die.net/man/3/xutf8setwmproperties) says that we could use:

```
Xutf8SetWMProperties(d, w, title, NULL, NULL, 0, NULL, NULL, hint);
```

to set the title and hint in UTF8 encoding. But sadly the problem remains to exists.

In the end, I think the problem might simply because that the X11 implementer GNOME mishandles this title property for the top bar (but I don't really found any evidence).

Either way, there is no fixes on the fyne side, and the issue should be closed.

Lastly, I would suggest a workaround for the application's title:

```diff
package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()

-	w := a.NewWindow("你好")
+	w := a.NewWindow("hello")
+	go func() {
+               // Let glfw set an ascii title first,
+               // then change the window title to a UTF-8 encoded title
+		time.Sleep(time.Millisecond)
+		w.SetTitle("你好")
+	}()
	w.SetContent(container.NewVBox([]fyne.CanvasObject{
		&widget.Label{Text: "你好 Fyne!"},
		&widget.Button{Text: "再见", OnTapped: func() {
			a.Quit()
		}},
	}...))

	w.ShowAndRun()
}
```

![image](https://user-images.githubusercontent.com/5498964/139824345-9c340b4c-3e23-434b-890c-c049af63830a.png)

**Comment by Shawn-Huang-Tron** [comment]
My app can't even show Chinese on the label, not only the window, Does it still exist, and is the same problem?
<img width="729" alt="image" src="https://github.com/fyne-io/fyne/assets/107823650/ad2414ed-3f31-4f3e-8bab-da62840248e8">
<img width="724" alt="image" src="https://github.com/fyne-io/fyne/assets/107823650/ce4d3394-4d86-4766-bc69-2bb4ef8bae31">

**Comment by andydotxyz** [comment]
Please use the "develop" version of Fyne or wait for v2.5.0 in the coming weeks.
