### ISSUE TITLE
Allow providing a manifest for Android, or passing in arguments to set permission requests

### ISSUE THREAD

**Issue by xxxserxxx** [fyne-io/fyne#662]
### Is your feature request related to a problem? Please describe:
To access network or filesystem resources, an Android app must [set a permissions request](http://developer.android.com/guide/topics/manifest/manifest-intro.html#perms) in the AndroidManifest.xml file in an APK bundle.  Without this, an app can't access those resources.  There is currently no way, using `fyne package`, to provide those permissions, so a developer must

1. Build the package
2. Unzip the package
3. Decode the binary XML that the AndroidManifest.xml is bundled as
4. Add the permission requests
5. Re-binary-XML-encode the AndroidManifest.xml
6. Re-zip the APK

### Describe the solution you'd like to see:
This request is to have a way through `fyne package` to provide those permission requests.  This could be either by a flag for each permission (could be a lot of flags), or some key/value syntax, or a file containing either a set of permissions, or an entire manifest file.

A URL was provided above to the specification for the permissions requests.  The relevant part of the manifest looks like this:

```
<manifest ... >
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
```

The Android manifest has many options, for specifying compatibility, intents, and so on.  Eventually, these will need to be supported, but network and/or filesystem access are probably a bare minimum need for most apps.

**Comment by andydotxyz** [comment]
An AndroidManifest.xml in the source directory should be included instead of the auto generated one...
If that’s not working then I guess this is a bug report :)

**Comment by xxxserxxx** [comment]
No!  I didn't see that in the documentation, but I probably just missed it.

That's perfect, thanks.
