### ISSUE TITLE
Add the ability to make custom keyboard shortcuts

### ISSUE THREAD

**Issue by botsarehots** [fyne-io/fyne#663]
### Is it possible to construct a solution with the existing API?
I'm not quite sure, I see this in the [canvas object](https://github.com/fyne-io/fyne/blob/v1.2.2/shortcut.go#L24) but don't think that's what it's used for and have been unable to get one working.

### Describe the solution you'd like to see:
The ability to add a keyboard shortcut such as `Ctrl + Tab` and have a `handle` function that will be called anytime this key combo has been pressed.

**Comment by andydotxyz** [comment]
Both Entry and Canvas have an AddShortcut function that takes a Shortcut and a func callback. You can pass &desktop.CustomShortcut{key, modifier} (this is in the driver/desktop package as you are adding a feature that will not work on other platforms).

**Comment by botsarehots** [comment]
I see now. It works great!

Here's some example code for other people with the same question. It's based off of the `Getting Started` section of the `README.md`

It simply adds the keyboard shortcut `Ctrl + Tab` to quick the application.

```go
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/driver/desktop"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()

	w := a.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			a.Quit()
		}),
	))

	ctrlTab := desktop.CustomShortcut{KeyName: fyne.KeyTab, Modifier: desktop.ControlModifier}
	w.Canvas().AddShortcut(&ctrlTab, func(shortcut fyne.Shortcut) {
		a.Quit()
	})

	w.ShowAndRun()
}
```
