### ISSUE TITLE
Windows Server 2012 (with no graphics) does not work

### ISSUE THREAD

**Issue by zhangxianweihebei** [fyne-io/fyne#664]
### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - OS: [e.g. Linux, MacOS or iOS] 
windwos server 2012
 - Version: [e.g. 22]
 - Go version: [e.g. 1.12.3]
 - Fyne version: [e.g. 1.2.0 or git SHA]

![image](https://user-images.githubusercontent.com/15844529/74100860-2fe14680-4b6e-11ea-8dd7-3c8347a16124.png)
![image](https://user-images.githubusercontent.com/15844529/74100867-4091bc80-4b6e-11ea-9736-ea5de6436fc6.png)

**Comment by zhangxianweihebei** [comment]
C:\Users\Administrator\Desktop>skynet.ui.exe
2020/02/09 18:42:11 Fyne error:  window creation error
2020/02/09 18:42:11   Cause: APIUnavailable: WGL: The driver does not appear to
support OpenGL
2020/02/09 18:42:11   At: C:/Go/work/src/fyne.io/fyne/internal/driver/glfw/windo
w.go:1044
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7d236d]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*window).Resize(0x0, 0xfa, 0x12c)
        C:/Go/work/src/fyne.io/fyne/internal/driver/glfw/window.go:164 +0x2d
main.main()
        D:/gitWork/skynet.ui/main.go:58 +0x52

**Comment by andydotxyz** [comment]
What graphics system is in the machine and which graphics driver are you using?

**Comment by zhangxianweihebei** [comment]
No video driver installed

**Comment by andydotxyz** [comment]
Sorry but at this time Fyne apps require a video driver installed to run.

**Comment by zhangxianweihebei** [comment]
It's just a simple page, can you package it

**Comment by andydotxyz** [comment]
I'm sorry I don't understand this question.

**Comment by Xuzan9396** [comment]
@zhangxianweihebei  你解决了吗？ 同样是windows server 打不开

**Comment by andydotxyz** [comment]
@Xuzan9396 At this time you require a graphics driver to run Fyne applications.

**Comment by markgician** [comment]
@andydotxyz I meet the same issue on azure vm. (Standard D2s v3) the default display adapter is "microsoft hyper-v video driver", how to update graphic driver in this case?

I can probably get around it if I upgrade to an N-series vm with GPU supported but that's expensive and I think there should be an easy way to have graphic driver in cloud vm.
