### ISSUE TITLE
why when I fyne package the android app . the app name always is org.golang.app.GoNativeActivity

### ISSUE THREAD

**Issue by zhzhyu** [fyne-io/fyne#665]
### To Reproduce:
Steps to reproduce the behaviour:

### Device (please complete the following information):
 - OS: [e.g. Linux, MacOS or iOS]
 - Version: [e.g. 22]
 - Go version: [e.g. 1.12.3]
 - Fyne version: [e.g. 1.2.0 or git SHA]
I had sitting androidmainfest.xml android:label,but mybe never use it

**Comment by zhzhyu** [comment]
No matter how I set androidmanifest.xml,the app name never change，always is "org.golang.app.GoNativeActivity"

**Comment by andydotxyz** [comment]
There are improvements to this on release/v1.2.3 branch (not released yet) would you be able to test that version as well?

**Comment by zhzhyu** [comment]
> There are improvements to this on release/v1.2.3 branch (not released yet) would you be able to test that version as well?
Can you tell me when the new will release

**Comment by zhzhyu** [comment]
Can you tell me when the new will release

**Comment by andydotxyz** [comment]
We don't have a schedule yet - probably in a week or two.
It would be helpful if you could test before release so we can verify it fixes your issue

**Comment by andydotxyz** [comment]
Actually hold on - this is the name of the main activity, not the name of the app.
Can you please explain where you are seeing this used as the app name?

**Comment by zhzhyu** [comment]
> We don't have a schedule yet - probably in a week or two.
> It would be helpful if you could test before release so we can verify it fixes your issue

I am very willing to test in advance. Could you send me an email? Thank you very much

**Comment by zhzhyu** [comment]
> We don't have a schedule yet - probably in a week or two.
> It would be helpful if you could test before release so we can verify it fixes your issue

mail@zhzhyu..com

**Comment by zhzhyu** [comment]
> We don't have a schedule yet - probably in a week or two.
> It would be helpful if you could test before release so we can verify it fixes your issue

mail.zhzhyu.com

**Comment by zhzhyu** [comment]
> We don't have a schedule yet - probably in a week or two.
> It would be helpful if you could test before release so we can verify it fixes your issue

mail@zhzhyu.com

**Comment by zhzhyu** [comment]
> Actually hold on - this is the name of the main activity, not the name of the app.
> Can you please explain where you are seeing this used as the app name?

It's on the android home screen，app name
![Screenshot_20200210_202818](https://user-images.githubusercontent.com/58381672/74149942-efec9300-4c43-11ea-96a9-46194ea69293.jpg)

**Comment by andydotxyz** [comment]
Can you confirm the package command you are using and the name of the directory you are building in?

**Comment by zhzhyu** [comment]
> Can you confirm the package command you are using and the name of the directory you are building in?

yes I can

**Comment by andydotxyz** [comment]
Apologies, I meant can you please tell us what package command you are using, and what the directory name is that you are building in.

**Comment by ffdfgdfg** [comment]
I tested version 1.2.3 without custom `AndroidManifest.xml` file, it works fine.
But our app needs internet permission, so I need to use a custom manifest file.
In version 1.2.3, I found there are some updates with manifest template
https://github.com/fyne-io/fyne/blob/4c845642c7858e2687d8e59bd38b735f63d2603f/cmd/fyne/internal/mobile/manifest.go#L58
I follow this template and change my manifest file
``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
        xmlns:android="http://schemas.android.com/apk/res/android"
        package="org.nps.client"
        android:versionCode="1"
        android:versionName="0.26.5">

    <uses-permission android:name="android.permission.INTERNET"/>
    <application android:label="Npc" android:debuggable="true">
        <activity android:name="org.golang.app.GoNativeActivity"
                  android:label="Npc"
                  android:configChanges="orientation|keyboardHidden">
            <meta-data android:name="android.app.lib_name" android:value="npc"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```
But when I build it, use a script 
``` shell
cd /go
apt-get install libegl1-mesa-dev libgles2-mesa-dev libx11-dev -y
go get -u fyne.io/fyne/cmd/fyne fyne.io/fyne
echo "fyne install success"
mkdir -p /go/src/ehang.io/nps
cp -R /app/* /go/src/ehang.io/nps
cd /go/src/ehang.io/nps
rm cmd/npc/sdk.go
echo "tidy success"
cd /go/src/ehang.io/nps
go mod vendor
cd vendor
cp -R * /go/src
cd ..
rm -rf vendor
echo "vendor success"
cd gui/npc
fyne package -appID org.nps.client -os android -icon ../../docs/logo.png
mv npc.apk /app/android_client.apk
echo "android build success"
```
with this manifest file, it shows the problem.

**Comment by andydotxyz** [comment]
Hmm. The package should not be altering a custom manifest - perhaps you can get a copy of the manifest from the packaged application and compare? That would probably be most helpful at this stage

**Comment by ffdfgdfg** [comment]
Yes, I find the question where is.
I use `aapt` to phase the apk manifest file
without custom manifest here is
```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
    A: package="org.nps.client" (Raw: "org.nps.client")
    A: platformBuildVersionCode=(type 0x10)0xf
    A: platformBuildVersionName="4.0.4-1406430" (Raw: "4.0.4-1406430")
    E: uses-sdk (line=2)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0xf
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
    E: application (line=8)
      A: android:icon(0x01010002)=@0x7f020000
      A: android:label(0x01010001)="Npc" (Raw: "Npc")
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
      E: activity (line=9)
        A: android:label(0x01010001)="Npc" (Raw: "Npc")
        A: android:name(0x01010003)="org.golang.app.GoNativeActivity" (Raw: "org.golang.app.GoNativeActivity")
        A: android:configChanges(0x0101001f)=(type 0x11)0xa0
        E: meta-data (line=12)
          A: android:name(0x01010003)="android.app.lib_name" (Raw: "android.app.lib_name")
          A: android:value(0x01010024)="npc" (Raw: "npc")
        E: intent-filter (line=13)
          E: action (line=14)
            A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
          E: category (line=15)
            A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
```
With custom manifest file on previous reply
```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="0.26.5" (Raw: "0.26.5")
    A: package="org.nps.client" (Raw: "org.nps.client")
    A: platformBuildVersionCode=(type 0x10)0xf
    A: platformBuildVersionName="4.0.4-1406430" (Raw: "4.0.4-1406430")
    E: uses-sdk (line=2)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0xf
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
    E: uses-permission (line=8)
      A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
    E: application (line=9)
      A: android:icon(0x01010002)=@0x7f020000
      A: android:label(0x01010001)="Npc" (Raw: "Npc")
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
      E: activity (line=10)
        A: android:name(0x01010003)="org.golang.app.GoNativeActivity" (Raw: "org.golang.app.GoNativeActivity")
        A: android:label(0x01010001)="Npc" (Raw: "Npc")
        A: android:configChanges(0x0101001f)=(type 0x11)0xa0
        E: meta-data (line=13)
          A: android:name(0x01010003)="android.app.lib_name" (Raw: "android.app.lib_name")
          A: android:value(0x01010024)="npc" (Raw: "npc")
        E: intent-filter (line=14)
          E: action (line=15)
            A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
          E: category (line=16)
            A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
```
It show's `android:name` and `android:label` where places swapped
Also I removed the `android.permission.INTERNET` option, and find it just fine.
So I move the  `android.permission.INTERNET` option to behind the `application` like this
``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
        xmlns:android="http://schemas.android.com/apk/res/android"
        package="org.nps.client"
        android:versionCode="1"
        android:versionName="0.26.5">

    <application android:label="Npc" android:debuggable="true">
        <activity android:name="org.golang.app.GoNativeActivity"
                  android:label="Npc"
                  android:configChanges="orientation|keyboardHidden">
            <meta-data android:name="android.app.lib_name" android:value="npc"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```
It works
```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="0.26.5" (Raw: "0.26.5")
    A: package="org.nps.client" (Raw: "org.nps.client")
    A: platformBuildVersionCode=(type 0x10)0xf
    A: platformBuildVersionName="4.0.4-1406430" (Raw: "4.0.4-1406430")
    E: uses-sdk (line=2)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0xf
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
    E: application (line=8)
      A: android:icon(0x01010002)=@0x7f020000
      A: android:label(0x01010001)="Npc" (Raw: "Npc")
      A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
      E: activity (line=9)
        A: android:label(0x01010001)="Npc" (Raw: "Npc")
        A: android:name(0x01010003)="org.golang.app.GoNativeActivity" (Raw: "org.golang.app.GoNativeActivity")
        A: android:configChanges(0x0101001f)=(type 0x11)0xa0
        E: meta-data (line=12)
          A: android:name(0x01010003)="android.app.lib_name" (Raw: "android.app.lib_name")
          A: android:value(0x01010024)="npc" (Raw: "npc")
        E: intent-filter (line=13)
          E: action (line=14)
            A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
          E: category (line=15)
            A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
    E: uses-permission (line=19)
      A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
```
Tested on my phone, just show the correct app name
Thanks

**Comment by andydotxyz** [comment]
Wow, so the attribute order seems to be the problem?

**Comment by ffdfgdfg** [comment]
That's it, the order

**Comment by andydotxyz** [comment]
Perhaps this is related to the device or android version? Do you see the issue on emulator or any other devices?

**Comment by ffdfgdfg** [comment]
My phone is android 9, nokia8, and the issue in my repo just tell me his phone is huawei, but not tested on and emulator, you can download [this](https://github.com/ehang-io/nps/releases/download/v0.26.4/android_client.apk) and test it.

**Comment by pymq** [comment]
Can confirm the same behavior in my app on android 8.0.

**Comment by andydotxyz** [comment]
Thank you for all this. I checked the android spec and cannot find anything that should imply this behaviour - the “label” field should always be used not the “name”. I suspect the package code must be mid-reading it somehow... will look into it further

**Comment by andydotxyz** [comment]
It would be great if you could check the upcoming 1.2.4 release (currently on `release/v1.2.4` branch) and see if the behaviour is changed or fixed...

**Comment by ffdfgdfg** [comment]
I tested the 1.2.4 release, behavior not changed, order still effect.

**Comment by andydotxyz** [comment]
I cannot explain why this is happening, but the manifest in 1.4.1 (release date to be set) will include a permissions section, so it should illustrate that others go there too.
Hopefully that is sufficient to close this issue, sorry it's not a cleaner fix.
