### ISSUE TITLE
Add Spinner widget

### ISSUE THREAD

**Issue by Kvaz1r** [fyne-io/fyne#667]
SpinCtrl control allows users to provide a spin (up/down) interface to move through pre-defined numbers using up and down arrows. 

### Is it possible to construct a solution with the existing API?
It possible if combine two buttons, one entry and fields for keeping range and current value with corresponding handlers. 

### Describe the solution you'd like to see:
Separate widget.

**Comment by DerThorsten** [comment]
I hacked smth together in #704 but I doubt that this is of good enough quality to be integrated in the library but might be still useful

**Comment by andydotxyz** [comment]
Closing as duplicate
