### ISSUE TITLE
glfw not linking under windows10 with msys64

### ISSUE THREAD

**Issue by gshields** [fyne-io/fyne#669]
Using window10v1909 with msys64(latest) and go 1.14rc1
gcc (GCC) 9.1.0
........................

go get -u -f fyne.io/fyne/cmd/fyne_demo
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw\c_glfw_windows.go:6:
E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function 'createMonitor':
E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:68:5: warning: implicit declaration of function 'wcscpy' [-Wimplicit-function-declaration]
   68 |     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
      |     ^~~~~~
E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c: In function '_glfwPlatformIsSameMonitor':
E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:228:9: warning: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
  228 |     if (wcslen(first->win32.displayName))
      |         ^~~~~~
E:\go_src\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/win32_monitor.c:229:16: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
  229 |         return wcscmp(first->win32.displayName, second->win32.displayName) == 0;
      |                ^~~~~~
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

**Comment by andydotxyz** [comment]
I think this results from a mix of 32 and 64 bit installed toolchain (see related faiface/pixel#112). The GCC is clearly 64bit, but is mingw or something else perhaps 32bit?
It's complicated to rectify this but I would suggest reinstalling and ensuring to choose "64 bit" for everything.

**Comment by gshields** [comment]
I removed window git and MinGW and updated the windows drivers and reinstall git and MinGW.
Previous I did the  go get -u -f fyne.io/fyne/cmd/fyne_demo under git bash (as I prefer bash). This time I used the old DOS box and IT WORKED !!, Thanks
