### ISSUE TITLE
could not build hello, maybe go-gl related

### ISSUE THREAD

**Issue by A1311981684** [fyne-io/fyne#671]
### Describe the bug:
First I tried to go build fyne_demo, it failed.Then I went to try with hello, it failed, too.Both of them gaved this info:

MetalFish@DESKTOP-EP4TCOH MINGW64 /f/VirtualBox/Ubuntu/GoPath/src/fyne.io/fyne/cmd/hello
$ go build
# github.com/go-gl/gl/v3.2-core/gl
..\..\..\..\..\pkg\mod\github.com\go-gl\gl@v0.0.0-20190320180904-bf2b1f2f34d7\v3.2-core\gl\procaddr.go: In function 'void* GlowGetProcAddress_glcore32(const char*)':
..\..\..\..\..\pkg\mod\github.com\go-gl\gl@v0.0.0-20190320180904-bf2b1f2f34d7\v3.2-core\gl\procaddr.go:41:31: error: invalid conversion from 'PROC {aka long long int (*)()}' to 'void*'
 [-fpermissive]
   void* pf = wglGetProcAddress((LPCSTR) name);
                               ^
..\..\..\..\..\pkg\mod\github.com\go-gl\gl@v0.0.0-20190320180904-bf2b1f2f34d7\v3.2-core\gl\procaddr.go:48:24: error: invalid conversion from 'FARPROC {aka long long int (*)()}' to 'voi
d*' [-fpermissive]
   return GetProcAddress(ogl32dll, (LPCSTR) name);
                        ^
# github.com/go-gl/glfw/v3.2/glfw
_cgo_export.c: In function 'void _cgo_861c8851bbe2_Cfunc__Cmalloc(void*)':
_cgo_export.c:361:53: error: invalid conversion from 'void*' to '_cgo_861c8851bbe2_Cfunc__Cmalloc(void*)::<anonymous struct>*' [-fpermissive]
  } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                                     

### Device (please complete the following information):
 - OS: Windows 10
 - Version: 17134
 - Go version: 1.13.1
 - Fyne version: 1.22

**Comment by andydotxyz** [comment]
Hmm, I have not seen this error before. Can you explain a little more about your development environment? It's listed as Windows10 but in the error log it says Ubuntu.
Without understanding more I'm not sure where to explore.

**Comment by andydotxyz** [comment]
Request for information over 9 months old, closing
