### ISSUE TITLE
The parameter is incorrect

### ISSUE THREAD

**Issue by tianxia0079** [fyne-io/fyne#672]
when i use package:
fyne package -os darwin -icon myapp.png

show this error:
Error building application: fork/exec C:\Go\bin\go.exe: The parameter is incorrect.

**Comment by andydotxyz** [comment]
This should already be fixed on the upcoming v1.2.3 release.
Is it possible for you to install from the release/v1.2.3 branch and see if it resolves the problem for you?

**Comment by tianxia0079** [comment]
> This should already be fixed on the upcoming v1.2.3 release.
> Is it possible for you to install from the release/v1.2.3 branch and see if it resolves the problem for you?

the latest release is v1.2.2.   where is v1.2.3 ,thanks

**Comment by tianxia0079** [comment]
> This should already be fixed on the upcoming v1.2.3 release.
> Is it possible for you to install from the release/v1.2.3 branch and see if it resolves the problem for you?

copy that

**Comment by andydotxyz** [comment]
1.2.3 is released with this in
