### ISSUE TITLE
can fyne built into single binary executable on windows without any dependencies?

### ISSUE THREAD

**Issue by jinfagang** [fyne-io/fyne#673]
can fyne built into single binary executable on windows without any dependencies?

**Comment by andydotxyz** [comment]
That is how we have designed things - to have no runtime dependencies.
It will, however, require a graphics driver present so if you don't have that available the apps won't work.
Does this answer your question?

To build an app simply use `go build` and if you want to package metadata for distribution then `fyne package` is your friend (from `go get fyne.io/fyne/cmd/fyne`).

**Comment by jinfagang** [comment]
thanks for replying. To my understanding, on a bare newly windows pc, built a very simple binary of fyne app (with only one button), and there is no logic, will it runing by simply copy this binary exe file to another windows PC (same windows system)? It seems on Ubuntu it will need glfw or something else, but that's easy to install, will windows have these driver issue (might hard to install on windows, newbie users doesn't know what's graphic driver at all)

**Comment by andydotxyz** [comment]
It is correct that copying a binary to another computer should work (assuming same OS and architecture). Linux does not require glfw or other dependencies - none of the platforms we support do. If the computer is set up with a monitor and is up to date it should just work.

**Comment by typeless** [comment]
There are probably some opportunities to improve this further.
Last time I checked, doing `GOOS=windows go build` on Linux still needs cgo (and a mingw gcc installed). But Gio (an immediate mode GUI library) can build independently with pure Go. So, I assume it is technically possible to get rid of cgo at least for Windows.

**Comment by Kvaz1r** [comment]
That's because Gio use [ANGLE drivers for emulating OpenGL ES](https://gioui.org/doc/install#windows) so that "cgo" part came  with .dlls. So only `go build` not enough.

**Comment by andydotxyz** [comment]
Yes there are ways to have less complication at *compile time* (like the ANGLE dlls) but what Fyne focuses on is to have 0 dependencies at *runtime*. This is of course a tradeoff which can mean a little more complication when compiling. It is really only evident when cross compiling which is why @lucor created the [fyne-cross](https://github.com/lucor/fyne-cross) project to do the heavy lifting for you.

**Comment by andydotxyz** [comment]
I think that I am going to close this issue as the answer to the original question is "Yes" and it was not related to the complexities of cross compiling.
