### ISSUE TITLE
Select widgets with many options overflow UI without scrolling

### ISSUE THREAD

**Issue by mcred** [fyne-io/fyne#675]
### Describe the bug:
If a select widget has more options than the window can handle, they overflow without any way to scroll and select items off screen.

### To Reproduce:
Build an app with the code below. 

### Screenshots:
<img width="865" alt="Screen Shot 2020-02-13 at 1 19 00 AM" src="https://user-images.githubusercontent.com/4326032/74406940-e2c7d380-4dfe-11ea-8a65-3169ded88cad.png">

### Example code:
```go
	a := app.New()
	w := a.NewWindow("Test")
	form := &widget.Form{
		OnCancel: func() {
			fmt.Println("Cancelled")
		},
		OnSubmit: func() {
			fmt.Println("Submitted")
		},
	}
	s := []string{"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"}
	test := widget.NewSelect(s, func(string) {})
	form.Append("Test", test)

	w.SetContent(widget.NewVBox(
		form,
	))

	w.Resize(fyne.NewSize(800, 600))
	w.ShowAndRun()
```

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.3
 - Go version: 1.13
 - Fyne version: 1.2.2

**Comment by mcred** [comment]
@andydotxyz If you have an idea of how this should be fixed and can point me in the right direction, I'll take a crack at it and open and PR.

**Comment by andydotxyz** [comment]
Well, the material design guide includes some designs. I think this would essentially work if the menu inside a PopUpMenu were inside a ScrollContainer it would work (the select overlay is just a popupmenu I think).
However the minSize will need updated so that it’s the full size where possible. That way it should not scroll when the screen is big enough but when the minsize is not matched due to limits the scroll should kick in.

**Comment by DamnWidget** [comment]
I was playing with this for a while, I could make the overlay to slide but I can't figure out how the `minSize` is supposed to work, with the current implementation the slide is just 32x32 and just modals have a right bar. Exposing the `ScrollContainer` inner `Content.MinSize` I end up with the same behavior than before adding the `ScrollContainer` and the scroll never kicks in

**Comment by andydotxyz** [comment]
Perhaps it's not a MinSize issue at all but a Resize issue.
With the scroller set up and the content using it's current MinSize it should scroll - when the content is too large for the popOver perhaps it needs to resize down to the available space to make the scroll maths work?

**Comment by mcred** [comment]
I also thought to use Resize to make the height within the app window, but resize doesn't seem to have any effect on Select. 

```go
a := app.New()
w := a.NewWindow("Test")
form := &widget.Form{
	OnCancel: func() {
		fmt.Println("Cancelled")
	},
	OnSubmit: func() {
		fmt.Println("Submitted")
	},
}
s := []string{"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"}
test := widget.NewSelect(s, func(string) {})

test.Resize(fyne.NewSize(200, 200))

form.Append("Test", test)

w.SetContent(widget.NewVBox(
	form,
))

w.Resize(fyne.NewSize(800, 600))
w.ShowAndRun()
```
<img width="815" alt="Screen Shot 2020-02-18 at 9 02 43 PM" src="https://user-images.githubusercontent.com/4326032/74794759-1341be80-5292-11ea-88c7-ac8d40246e71.png">

**Comment by andydotxyz** [comment]
Yes, the Select in your example (“test”) is the button, not the popup - so it’s size is co trolled by the layout. You’d need to try resizing inside the widget where the popup is controlled.

**Comment by andydotxyz** [comment]
The change linked above may make this easier. I had not realised that when items overflow they were not being constrained to the canvas size. Now they are.
I imagine that now if you include a scroller but set the scroller minSize to the content minsize (plus padding?) then the updated code should force the scroller to appear.
This is available on "develop" or "release/v1.2.3" branches at this time.

**Comment by mcred** [comment]
I will check that out very soon! Thank you.

**Comment by stuartmscott** [comment]
BTW this issue can be encountered in fyne_demo on the Graphics screen when the Select containing icon names is opened.

**Comment by toaster** [comment]
This is fixed on develop and hopefully will be part of 1.3.

**Comment by andydotxyz** [comment]
That 7.3% decrease in test coverage is weird - any idea what might have caused coveralls to think this?

**Comment by andydotxyz** [comment]
(raised on Slack so this can be closed)

**Comment by BhanuMeghraj** [comment]
Hey can we have select widget with text . I mean a dropdown list where we can also write the text if the option is not available in dropdown

**Comment by andydotxyz** [comment]
Try the `widget.SelectEntry` component @BhanuMeghraj

**Comment by BhanuMeghraj** [comment]
can you please give me an example

**Comment by andydotxyz** [comment]
https://github.com/fyne-io/fyne/blob/9b5a176fe1dc80beae72a3074d0d5cd2b409637c/cmd/fyne_demo/tutorials/widget.go#L217

**Comment by Jacalz** [comment]
I have now marked these comments as off topic as they were not related to the issue in question.
