### ISSUE TITLE
Complete Native Menu Implementation

### ISSUE THREAD

**Issue by Jonconradt** [fyne-io/fyne#682]
Currently missing from native menus, see [darwin implementation](https://github.com/fyne-io/fyne/blob/master/internal/driver/glfw/menu_darwin.m):

- [Enable](https://developer.apple.com/documentation/appkit/nsmenuitem/1514863-isenabled)/Disable a menu item 
- Separators
- KeyEquivalents
- Indentation levels

The Apple Documentation for MenuItem: https://developer.apple.com/documentation/appkit/nsmenuitem

While I realize that these seem like small things compared to the larger work that needs to be done, menus are a primary UX element for users. These small features would help the apps feel equivalent to other UX frameworks.

**Comment by andydotxyz** [comment]
This would be great to add - but we will have to add support for those same things inside the Fyne canvas menus as well (for systems other than macOS).

Separator and disabled could be done relatively easily, indentation is tracked by another ticket (#395) but the key equivalents will take more work overall in the toolkit first.

**Comment by toaster** [comment]
Separators were added to develop branch and will be part of 1.3.
Disabled menu items are planned but probably won’t be part of 1.3.
The same applies to KeyEquivalents (aka Shortcuts).

Regarding indentation: I don’t think that this is useful. Apples design documentation (https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/) says:

> Use a submenu instead of indenting menu items. Indentation results in an inconsistent interface and doesn’t express relationships between menu items. If you need to indent, then a submenu is a better choice.

Submenus probably will land in 1.3 (#905).

**Comment by toaster** [comment]
#905 now contains the support for native submenus, too

**Comment by vmcrash** [comment]
See also https://github.com/fyne-io/fyne/issues/1372

**Comment by andydotxyz** [comment]
I think the key equivalent / shortcut feature is the only remaining item

**Comment by andydotxyz** [comment]
We think this is complete now in Bowmore release :)
