### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [fyne-io/fyne#683]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/fyne-io/fyne)](https://www.tickgit.com/browse?repo=github.com/fyne-io/fyne)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/fyne-io/fyne)](https://www.tickgit.com/browse?repo=github.com/fyne-io/fyne)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by andydotxyz** [comment]
We have some embedded code from another project that has lots of TODOs in that we don't want to spend time fixing - can it ignore specific directories?

**Comment by patrickdevivo** [comment]
@andydotxyz ah understood! It can't do so yet, but it's a common feature request and support should be added soon via a config file in the root of the repository. I can post back here when that's implemented!

**Comment by andydotxyz** [comment]
Thanks for letting me know.
If you don't mind I'll close this issue for now and perhaps you could re-open it once this feature is in?
