### ISSUE TITLE
Runtime error on theme change when built with -tags mobile

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#688]
### Describe the bug:
An application that tries to set the theme before a window is created will fail due to an error on run-time when built using` -tags mobile`, but not if it is built without that tag. The errors that are getting spewed out are the following:

```go
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x69201a]goroutine 8 [running]:
fyne.io/fyne/internal/app.ApplyThemeTo(0x0, 0x0, 0x895ae0, 0xc000124000)
	/home/jacob/go/src/fyne.io/fyne/internal/app/theme.go:23 +0xfa
fyne.io/fyne/internal/app.ApplySettings(0x890760, 0xc000120000, 0x894480, 0xc00006a360)
	/home/jacob/go/src/fyne.io/fyne/internal/app/theme.go:30 +0xf0
fyne.io/fyne/app.NewAppWithDriver.func1(0xc000026480, 0xc00006a360)
	/home/jacob/go/src/fyne.io/fyne/app/app.go:108 +0x6b
created by fyne.io/fyne/app.NewAppWithDriver
	/home/jacob/go/src/fyne.io/fyne/app/app.go:105 +0x15f
```

### To Reproduce:
Steps to reproduce the behaviour:
1. Build and run [this code](https://gist.github.com/Jacalz/b09b4cceca7bdc6b7946fd44fdf55b68) with `go run`.
2. Build and run the same code snippet with `go run -tags mobile` (will not start at all).
3. Instead build and run [this code](https://gist.github.com/Jacalz/723b828fbbb3fce991eb57cd5d20e52b) snippet with `go run -tags mobile`.

### Example code:
Not working code version: https://gist.github.com/Jacalz/b09b4cceca7bdc6b7946fd44fdf55b68
Working code version: https://gist.github.com/Jacalz/723b828fbbb3fce991eb57cd5d20e52b

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.5.3
 - Go version: 1.13.6
 - Fyne version: 1.2.0, 1.2.2 and devlop branch have all been tested.

Currently tested on Linux only.

**Comment by andydotxyz** [comment]
on develop for testing, this will merge into pending v1.2.3 release shortly

**Comment by andydotxyz** [comment]
Now on the pending 1.2.3 release branch
