### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by iamjinlei** [fyne-io/fyne#689]
### thread safey model and best practices
Sorry for being naive here. When I try to understand the design of the fyne architecture, I had trouble understanding how it designed the mechanism to explicitly avoid concurrency issues, especially when user goroutines are involved.

For example, when I read the widget/progressbar.go code, I am a little confused. if SetValue() is called on a separate goroutine while driver is traversing the obj tree and updating the pixels, isn't it going to cause race on the 'Value'? I must have missed a very important principle in the design but I am not able to find relevant documents. Any clarification would help. Thanks!

**Comment by Kvaz1r** [comment]
Some part isn't thread safe just yet - see https://github.com/fyne-io/fyne/issues/506

**Comment by andydotxyz** [comment]
Yes @Kvaz1r is correct there have been issues raised around thread safety and we are working on them.
However the example you describe is not likely to occur, here is why:

* Once a widget has drawn once it's rendering is cached.
* When you update a value the drawing code will be using the cached version.
* Once the change is made then Refresh() is called on the object so that on the next frame it will be re-drawn (and that is when the value will be read).

It's not a perfect design but it does mean that most of these cases don't occur. I am not denying there is work to improve it, and some efforts are underway for the 1.3 release to ensure that more complex cases cannot happen (for example if you wanted to update a value twice in a frame then the explanation does not hold).

**Comment by iamjinlei** [comment]
Very helpful information @andydotxyz. Thanks!

As one with a few days of experience with fyne, a short document about the overall architecture and when the renderer's api would be triggered would be extremely helpful!

I am closing this out.


> Yes @Kvaz1r is correct there have been issues raised around thread safety and we are working on them.
> However the example you describe is not likely to occur, here is why:
> 
> * Once a widget has drawn once it's rendering is cached.
> * When you update a value the drawing code will be using the cached version.
> * Once the change is made then Refresh() is called on the object so that on the next frame it will be re-drawn (and that is when the value will be read).
> 
> It's not a perfect design but it does mean that most of these cases don't occur. I am not denying there is work to improve it, and some efforts are underway for the 1.3 release to ensure that more complex cases cannot happen (for example if you wanted to update a value twice in a frame then the explanation does not hold).

**Comment by iamjinlei** [comment]
Actually, the race can still happen if multiple updates happen in a short period.


> Yes @Kvaz1r is correct there have been issues raised around thread safety and we are working on them.
> However the example you describe is not likely to occur, here is why:
> 
> * Once a widget has drawn once it's rendering is cached.
> * When you update a value the drawing code will be using the cached version.
> * Once the change is made then Refresh() is called on the object so that on the next frame it will be re-drawn (and that is when the value will be read).
> 
> It's not a perfect design but it does mean that most of these cases don't occur. I am not denying there is work to improve it, and some efforts are underway for the 1.3 release to ensure that more complex cases cannot happen (for example if you wanted to update a value twice in a frame then the explanation does not hold).

**Comment by andydotxyz** [comment]
I'm glad it helped. 
That is a good suggestion thanks - we do need to write more of this up. It was designed but the design did not become a helpful document ;)

**Comment by andydotxyz** [comment]
> Actually, the race can still happen if multiple updates happen in a short period.

You are quite right it's not perfect, though the different changes would need to be in < 1/60th second. You can "batch" changes by setting fields then calling refresh once all is done.
This area is where I am focussing to improve safety, mainly I think a "SetThenRefresh(func())" helper will mean that the API, or the developer directly, could set fields within the helper knowing that it is safe and the function itself would hold a lock to ensure this. It's just a thought at the moment but will be tested soon.
