### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by iamjinlei** [fyne-io/fyne#693]
continuing on the previously closed ticket regarding the thread safety issue.

After a second thought, I feel it almost always needs an atomic value in a widget (unless it is pretty static) to hold the state. When other goroutines update the widget data, it would need to wrap all data and associated canvas objects into a struct and atomically swap into the widget's atomic value field. On the renderer side, it would need to load the value from atomic and update layout accordingly.

If this is the case, then the renderer creating becomes pretty dumb if it only holds a pointer to the widget object. I am just curious about the plan to making it thread safe and the according design.

I realize the existing widgets implementation in the repo do not have much problem because they are pretty static, i.g. the widget data are not updating frequently and the associated canvas objects do not add or remove on the fly. If they do, then these implementation would all have issues. I checked the box widget. If we are going to support adding or removing canvas object on the fly, then the objects fields would need to be held by the widget unless you invalid renderer cache each time append() is called.

That being said, I cannot wait to see the new release coming out with the fix for the concurrency issue.

**Comment by andydotxyz** [comment]
We have ProgressBar widget which can often be updated many times a second.
The Box widget, and others, support adding and removing on the fly - the Children field is available and each Refresh() every widget should check whether or not it's content has changed or layout invalidated.

I'm not sure if there is a bug referenced in this content, can you please confirm if there is or isn't?

**Comment by iamjinlei** [comment]
For the ProgressBar, accessing to Value field is not thread safe. The driver thread can read Value while external goroutine is calling SetValue(). It is just luckly that the value is a float64 and does not cause a noticable issue. Strictly speaking, It should be an atomic.Value

Regarding the box implementation, the Append()/Prepend() function calls refresh after updating Children slice. Based on my understanding, the renderer cache is not invalided. So the previously created rendered will continue to be used. If that is the case, the renderer's objects slice is not updated. I grep the code, but only see the rendered is invalided on window close. I could be wrong so.

**Comment by andydotxyz** [comment]
ProgressBar.Value does indeed need safe access set like the other widgets discussed - I was just using it to illustrate a more rapidly updated widget.

The renderer cache “invalidation” does not require a renderer removal and a new one created, just the cache in the driver is reset. Any time Refresh() is called that mechanic causes items to be invalidated when necessary.

**Comment by iamjinlei** [comment]
Hmmm, maybe I misread the code. But I only find one instance of cache.DestroyRenderer() call, which is in called in window.close()

> The renderer cache “invalidation” does not require a renderer removal and a new one created, just the cache in the driver is reset. Any time Refresh() is called that mechanic causes items to be invalidated when necessary.

**Comment by andydotxyz** [comment]
That is quite correct. DestroyRenderer() means “we are done with this Renderer and won’t use it any more” (I.e. widget is hidden or removed) whereas Refresh() means “something has changed so the item should be redrawn”.

**Comment by iamjinlei** [comment]
You are right. I missed one L104 in widget/box.go which assigns b.box.Children to b.objects in the Refresh(). Then this is again a thread safety issue, which kinda make me nervous...
My current workaround is to create a wrapper struct to keep all widget states and save the wrapper in an atomic value. When states need to be changed, it saves a new wrapper struct's pointer to the atomic value.
I am closing this out!

**Comment by andydotxyz** [comment]
I could see that makes sense. We like to have something a little more approachable for general consumption - like an atomic state internally for those key items. If you would like to contribute upstream that would be greatly appreciated (on develop branch though)
