### ISSUE TITLE
fyne_demo: canvas is not refreshed when visible

### ISSUE THREAD

**Issue by sbinet** [fyne-io/fyne#70]
on ArchLinux/amd64: when I run the `fyne_demo` example and move another window over the `Examples` "main" canvas of the `fyne_demo`, the content of that "main" window isn't redrawn.

it's refreshed only when _e.g._ resizing.
this bug doesn't happen for _e.g._ the `Life` window, which is always refreshed/redrawn.

is there an `OnFocus` or `OnVisible` event to listen to? (there's an `OnKeyPressed`, IIRC)

**Comment by SvenDowideit** [comment]
I'm also seeing a non-drawn canvas on Linux using i3wm for the "Hello" example - though I presumed it was due to the simplified window manager?

**Comment by SvenDowideit** [comment]
mmm, so I added a `aboutWindow.Canvas().Refresh(aboutWindow.Content())` and that appears to work for my issue.

**Comment by andydotxyz** [comment]
Thanks for the information. That code will indeed for a complete redraw, but including it in the right place is the trick I guess - where did your addition go to resolve it at your end?

**Comment by andydotxyz** [comment]
@sbinet Can you confirm what window manager you are using for this? I cannot replicate on my Arch machine...

**Comment by andydotxyz** [comment]
This is stumping me. Has the content been drawn and then covered, then on reveal it is not drawing correctly? In X11 I think that the window surfaces should be cached.

@SvenDowideit for some reason I could not replicate with i3 either.

Can you please confirm it's the latest fyne and possibly the steps to reproduce the issue?
Thanks!

**Comment by sbinet** [comment]
I am using `openbox`:

```
$> yay -Qi openbox 
Name            : openbox
Version         : 3.6.1-4
Description     : Highly configurable and lightweight X11 window manager
Architecture    : x86_64
URL             : http://openbox.org
Licenses        : GPL
Groups          : lxde  lxde-gtk3  lxqt
Provides        : libobrender.so=32-64
Depends On      : startup-notification  libxml2  libxinerama  libxrandr
                  libxcursor  pango  imlib2  librsvg  libsm
Optional Deps   : plasma-workspace: for the KDE/Openbox xsession
                  python2-xdg: for the openbox-xdg-autostart script
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1215.00 KiB
Packager        : Florian Pritz <bluewind@xinu.at>
Build Date      : Mon 25 Jun 2018 11:51:42 AM CEST
Install Date    : Mon 25 Jun 2018 08:08:12 PM CEST
```

I am using:
- fyne-io/examples@38f035e
- fyne-io/fyne@5ee8fcd

**Comment by jadr2ddude** [comment]
So this may be openbox specific or GPU-driver specific. I am unable to replicate with latest Manjaro (Arch-fork) on amd64 with Cinnamon. I will try on openbox on my system when i get a chance.

**Comment by sbinet** [comment]
let me know if there's something I can do on my side to help you track this down.

**Comment by jadr2ddude** [comment]
I have managed to replicate this with these commands:
```
Xephyr -br -ac -noreset -screen 800x600 :1 &
DISPLAY=:1 openbox &
DISPLAY=:1 fyne_demo &
```
![image](https://user-images.githubusercontent.com/16477604/52181563-43bad580-27c1-11e9-8a3b-4114b2312d67.png)

This will open a nested display with Xephyr, run openbox in it, and run the fyne demo in it.

**Comment by andydotxyz** [comment]
Thanks so much for all of this.
It seems that, whilst we had hooked in to the callbacks, it was not refreshing all the time.
This would have affected any Linux WM that does not composite or back buffer windows.
