### ISSUE TITLE
can't download fsnotify v1.4.7

### ISSUE THREAD

**Issue by SinTan1071** [fyne-io/fyne#702]
got an error when using `fyne package -os darwin -icon icon.jpg`

```shell
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/go-gl/glfw v0.0.0-20181213070059-819e8ce5125f
go: downloading github.com/srwiley/oksvg v0.0.0-20190829233741-58e08c8fe40e
go: downloading golang.org/x/image v0.0.0-20190802002840-cff245a6509b
go: downloading github.com/srwiley/rasterx v0.0.0-20181219215540-696f7edb7a7e
go: downloading github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff
go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
build command-line-arguments: cannot load github.com/fsnotify/fsnotify: github.com/fsnotify/fsnotify@v1.4.7: Get https://proxy.golang.org/github.com/fsnotify/fsnotify/@v/v1.4.7.zip: dial tcp 172.217.24.17:443: i/o timeout
```

**Comment by andydotxyz** [comment]
This error means your computer can not reach GitHub - I don’t think it’s a bug in Fyne.

**Comment by SinTan1071** [comment]
@andydotxyz Thanks for noticing, I know it's not a bug in Fyne, and I didn't report this as a bug, right? But it's weird, I'm pretty sure I can access to github, otherwise I can't talk to you about it here, I think it's the version 1.4.7 that cause this error, is there any other version can let me try?

**Comment by SinTan1071** [comment]
@andydotxyz I just tried another time, It works!! Hallelujah!!!
