### ISSUE TITLE
Select drop-down width is wrong if the drop-down is too tall for the window.

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#706]
### Describe the bug:

When a drop-down is too tall for a window its size gets wrong (too wide). It probably gets the canvas' size because the `PopUp.Size()` reports this and the ensureMinSize functionality performs `Resize(Size().Union(MinSize()))` if the size is smaller than the `MinSize()`. 

### To Reproduce:

1. run fyne_demo
2. make the window wider
3. open the icon selector drop-down
4. see the drop-down which is too tall and also wider than the select which should not be the case

### Screenshots:

![Bildschirmfoto 2020-02-24 um 20 24 14](https://user-images.githubusercontent.com/73959/75184325-817bfa80-5744-11ea-8af9-c923029934e4.png)

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.14.6
 - Go version: 1.12.1
 - Fyne version: develop (4f81a6642d9b9e17830d82a3c7a7e2944ea18144)

**Comment by andydotxyz** [comment]
Oh good catch, somehow I didn't notice that it was wide, I was fixed on it being in the right position :)

**Comment by andydotxyz** [comment]
Fix is on release/v1.2.3 for testing (and develop)
