### ISSUE TITLE
Allow resetting the Select Widget selected field

### ISSUE THREAD

**Issue by Ariemeth** [fyne-io/fyne#723]
### Is your feature request related to a problem? Please describe:

The Select Widget does not have a way to reset the currently selected option back to being empty.  The only options that can be set using `SetSelected` are ones that are in the options slice.  This means that one cannot set the selected value to be empty unless you have an empty string as part of the options slice.

### Is it possible to construct a solution with the existing API?

Including an empty string in the options slice allows you to set the selected value back to an empty string which resets back to the placeholder.

### Describe the solution you'd like to see:

I see two possible options right now.  
1.  Allow the SetOption function on the Select Widget to accept an empty string even if an empty string does not exist in the option slice effectively resetting the widget.
2. Add a Reset() type function that clears the currently selected value.

**Comment by andydotxyz** [comment]
This is on develop branch for testing
