### ISSUE TITLE
Allow widgets to influence mouse cursor style

### ISSUE THREAD

**Issue by AhmedMKamal** [fyne-io/fyne#726]
Is there a way to set the cursor style on a widget, like pointer, text, grab, etc?

**Comment by andydotxyz** [comment]
We currently do not support this sorry. If you could provide more information about what you’re looking to do we could try and add something

**Comment by AhmedMKamal** [comment]
@andydotxyz I'm trying to build a custom entry widget for a source code editor app, for now, my custom widget is working quite well but I can't set the cursor style to text when I hover over it.

here's an example from `.Net WPF` which I used to work with
```c#
// listen to mouse enter event.
private void MyWidgetMouseEnter(object sender, SelectionChangedEventArgs e)
{
  // set the cursor to pen.
  DisplayArea.Cursor = Cursors.Pen;
}

// listen to mouse leave event.
private void MyWidgetMouseLeave(object sender, SelectionChangedEventArgs e)
{
  // set the cursor to cursor.
  DisplayArea.Cursor = Cursors.Cursor;
}
```

**Comment by andydotxyz** [comment]
If you are extending the Entry widget this should "just work" (but I think there is a bug that causes it not to). I guess we could create some desktop extension that can hint at a different cursor type. It's not something we can support cross-platform for obvious reasons.

**Comment by AhmedMKamal** [comment]
@andydotxyz, I understand, I'll try to dive deeper into `fyne`'s source code and see if I can help.

**Comment by andydotxyz** [comment]
This is on develop for testing
