### ISSUE TITLE
Window is not controllable after exiting FullSreen Mode

### ISSUE THREAD

**Issue by Bekassyl** [fyne-io/fyne#727]
### Describe the bug:

When window exits FullScreen mode, it appears at top left corner and cannot be dragged somewhere else. In addition, menu bar disappears. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Run fyne_demo
2. Go to 'Advanced'
3. Press 'FullScreen' and press again to exit that mode
5. Or run my code written below

### Screenshots:

!
![Screenshot (2)](https://user-images.githubusercontent.com/24650439/76062109-9f1e4080-5f4a-11ea-8ebb-66ae47936ad5.png)

### Example code:

```
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("FullScreen Bug")

	x := widget.NewButton("FullScreen", func(){
		myWindow.SetFullScreen(!myWindow.FullScreen())
	})

	myWindow.SetContent(x)
	myWindow.ShowAndRun()
}
```

### Device (please complete the following information):
 - OS: Windows
 - Fyne version: Latest

**Comment by Bekassyl** [comment]
Seems like in  `func (w *window) SetFullScreen(full bool){}`  SetMonitor(nil) doesn't work as expected

**Comment by andydotxyz** [comment]
This seems to be not an issue on macOS or Linux, assuming therefore it's WIndows only

**Comment by andydotxyz** [comment]
on develop for testing
