### ISSUE TITLE
RecycleView in fyne

### ISSUE THREAD

**Issue by hussam132** [fyne-io/fyne#728]
can I make RecycleView in fyne or ScrollView in fyne ???

**Comment by andydotxyz** [comment]
For scrolling use the widget.ScrollContainer.

I don’t know what type of behaviour a RecycleView provides, perhaps you can give us some more information?

**Comment by hussam132** [comment]
RecycleView  it's the same of the scroll view but can you give me a simple example about how I use   `widget.ScrollContainer`  and what I should puts as argument of the scrollcntain
and finally I want to tell me where I found a full documentations of all fyne property because in the tour tutorial is missing the scroll view also in the fyne website

**Comment by andydotxyz** [comment]
Have you looked at fyne_demo? It shows how all the widgets work (and in the meantime we will update the documentation).

`go get fyne.io/fyne/cmd/fyne_demo`

**Comment by hussam132** [comment]
if you mean this demo[https://github.com/fyne-io/fyne/blob/93c7b8da5bad616145e1c164a5eb5dd7079b1150/cmd/fyne_demo/main.go]

I can't find the scroll widget in the code ???

**Comment by Kvaz1r** [comment]
It's placed on Scroll tab in Widgets section. Here the code - https://github.com/fyne-io/fyne/blob/master/cmd/fyne_demo/screens/widget.go#L101-L123

**Comment by hussam132** [comment]
how I can make the scrolling in the vertical direction only , and can I change the size of the button inside the scroller ???

**Comment by andydotxyz** [comment]
Currently you can only make it scroll in the horizontal only direction if the scroller expands to a larger (or equal) height than the content. We are considering ways to make this easier.

I'm not sure which button you are referring to though?

**Comment by hussam132** [comment]
but I made a simple scroller example contains a buttons and when I small the screen the scrolling becomes in the two x and y directions but i want it to be scrolling only up and down

**Comment by Kvaz1r** [comment]
In that case just don't provide scroller container for horizontal layouting. Byw, it would be much easier if you show complete (but minimal) reproducable example or patch that shows diff to standard sample.

**Comment by hussam132** [comment]
this's my example and  I do not want to use the fixed size grid Layout can I make it only scroll in vertical view without using the fixed size layout  

```
package main

import (
	"fyne.io/fyne"
	//"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	//"image/color"
	"log"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	//"fyne.io/fyne/theme"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Button Widget")

	left := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	top := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	text1 := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	text2 := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	text3 := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	text4 := widget.NewButton("click me", func() {
		log.Println("tapped")
	})
	text5 := widget.NewButton("5", func() {
		log.Println("tapped")
	})

	text6 := widget.NewButton("6", func() {
		log.Println("tapped")
	})
	text7 := widget.NewButton("7", func() {
		log.Println("tapped")
	})
	text8 := widget.NewButton("8", func() {
		log.Println("tapped")
	})
	text9 := widget.NewButton("9", func() {
		log.Println("tapped")
	})
	text10 := widget.NewButton("10", func() {
		log.Println("tapped")
	})
	text11 := widget.NewButton("11", func() {
		log.Println("tapped")
	})
	text12 := widget.NewButton("12", func() {
		log.Println("tapped")
	})
	text13 := widget.NewButton("13", func() {
		log.Println("tapped")
	})
	text14 := widget.NewButton("14", func() {
		log.Println("tapped")
	})
	text15 := widget.NewButton("15", func() {
		log.Println("tapped")
	})
	text16 := widget.NewButton("16", func() {
		log.Println("tapped")
	})
	text17 := widget.NewButton("17", func() {
		log.Println("tapped")
	})
	text18 := widget.NewButton("18", func() {
		log.Println("tapped")
	})
	text19 := widget.NewButton("19", func() {
		log.Println("tapped")
	})

	box11 := fyne.NewContainerWithLayout(layout.NewGridLayout(1),
		text6,text5,text4,text3,text2,text1,text7,text8,text9,text10,text11,text12,text13,text14,text15,text16,text17,text18,text19)
	scroller :=widget.NewScrollContainer(box11)

	grid := fyne.NewContainerWithLayout(layout.NewBorderLayout(top, left, nil, nil),
		top, left, scroller)

	myWindow.SetContent(grid)
	myWindow.ShowAndRun()
}

```

**Comment by andydotxyz** [comment]
As there is no API to do that directly you can force it by making the scroll view wide enough to contain the width of your buttons.
You can do this either by extending the ScrollContainer widget to have a new MinSize() method, or you could put a rectangle behind it (as canvas.Rectangle provides SetMinSize()) (a container with a MaxLayout will overlay one on the other and have a min size of the larger).

**Comment by hussam132** [comment]
the minimum width of the scroller will be the minimum width of the text on the button so that's why I think the relative size property will help to fix this because when we make the scroller width be 100% of the screen that's mean the scrolling always will be vertical and if I decrease the width of the scroller the text on the buttons will decrease with the same percentage

**Comment by andydotxyz** [comment]
I'm sorry I don't understand this comment. What relative size are you referring to?

**Comment by hussam132** [comment]
I mean if we can set the size of the scroller to be 100% of the size of any screen "if this property possible" then the scrolling will be vertical since the width of the scroller and the buttons inside it will be change there size relative to any change happen to the screen size "if we cosider that the scroller becomes scroll in the horenzotinal direction if the size of the screen becomes smaller then the text on the buttons" in other word the design will be the same in all the different size of the screens I mean if you run my example above  it will be no horizontal scrolling because the size of the text on the button is very small but if we change it to be more longer like "ytndthnjdcnjcbsdcsdcdzvuunjldbcsjbvlb" the scrolling will be vertical and horizontal that's why the size of the text on the button will effect the design  ;I hope my idea clear

**Comment by andydotxyz** [comment]
Widgets can fill a container by using the right layout - that is not a problem.
It is the job of a widget's MinSize() value to ensure that it cannot be smaller than is acceptable for the user interface - that is why I suggested that the solution currently would be to enlarge the scroller min width to be wide enough that scrolling is not required.

**Comment by hussam132** [comment]
but How I can use the MinSize() ??
`scrollerdata.SetMinSize(fyne.NewSize(320, 320))`
I mean for example "from the demo example" what's the numbers represent here

**Comment by andydotxyz** [comment]
Perhaps some of our documentation may help? https://fyne.io/develop/geometry.html

**Comment by andydotxyz** [comment]
In the development of the file select dialog (currently on feature/filedialog branch) I have an example that might help.
I have added a ScrollContainer.SetMinSize() on that branch to make this easier as well, though it is currently possible if you put a rectangle behind the scrollcontainer with both in a maxlayout container - the new API is much cleaner.
