### ISSUE TITLE
Chinese input method not supported on linux xorg desktop

### ISSUE THREAD

**Issue by electricface** [fyne-io/fyne#73]
ibus，fcitx

**Comment by afocus** [comment]
theme fonts do not support Chinese

**Comment by electricface** [comment]
https://github.com/ibus/ibus/wiki

**Comment by andydotxyz** [comment]
Hi, I have installed the tools you mentioned but I cannot figure how exactly to replicate what you are describing.
Is it possible to provide some more detailed steps to verify this?

Locally if I use FYNE_FONT=<a_chinese_font.ttf> fyne_demo with some chinese content it seems to work. Can you try the same and let me know if it's still broken please?

**Comment by electricface** [comment]
If you want to enter Chinese on your computer, you will need to use the Chinese input method.
The pc-type keyboard only has a to z keys, you need to enter some letters, then come out a word selection interface, and then select the text you really want to input. For example, if you use the Pinyin input method and type "shijie", you will see "世界", "时间", "事件" and other words.
Mature ui toolkits, such as qt and gtk, support Chinese input methods.

**Comment by andydotxyz** [comment]
Unfortunately we cannot address this for Milestone 1.0.
Hopefully GLFW can get the contributions necessary and we could then integrate it in a later release.

**Comment by medivh-jay** [comment]
I have the same problem， cannot intput chinese

**Comment by andydotxyz** [comment]
The upstream issue has been moved to a later release - I don't have any information about when we may be able to resolve this, sorry.

**Comment by andydotxyz** [comment]
We are upgrading GLFW to 3.3 in our next major release, but the upstream issue has been moved to 3.4, sorry. We will need to make a plan for how (and when) to better support multi-language, i18n and accessibility.

**Comment by electricface** [comment]
You can support fcitx first and then ibus.

**Comment by runner-mei** [comment]
can fix it soon?

**Comment by andydotxyz** [comment]
Internationalisation is a very compex topic and is not scheduled for the release we are working on (or the one after that).
Currently we expect to focus on it for 3.0 which has no timeline yet.

**Comment by runner-mei** [comment]
@andydotxyz update https://github.com/go-gl/glfw,  it update glfw to 3.3.3 and  it fix fcitx.

**Comment by andydotxyz** [comment]
This is now in release branch `release/v2.0.x` - can you please test ffor me @runner-mei ?
It would be great if the update fixes this issue!

**Comment by runner-mei** [comment]
@andydotxyz update to release/v2.0.x andtest fail,  
but I copy https://github.com/glfw/glfw/archive/refs/tags/3.3.3.tar.gz to github.com/go-gl/glfw, override old code files, and it is ok

**Comment by andydotxyz** [comment]
So the changes did not make it ton 3.3.3?

**Comment by andydotxyz** [comment]
> but I copy https://github.com/glfw/glfw/master to github.com/go-gl/glfw, override source files, and it is ok

Where did you copy the files to?

**Comment by runner-mei** [comment]
@andydotxyz  copy from master branch of  https://github.com/glfw/glfw

**Comment by andydotxyz** [comment]
> @andydotxyz copy from master branch of https://github.com/glfw/glfw

Where did you copy the files to?

The commits you link to were added 13 months ago, so it seems unlikely that they are missing in the recent builds...

**Comment by runner-mei** [comment]
@andydotxyz Yes, The commits you link to were added 13 months ago.

https://github.com/glfw/glfw/blob/3.3.3/src/x11_window.c#L775

https://github.com/glfw/glfw/commit/44b5d06583cd21ac237eb8f6263db03faf1726c2#diff-8c3a21538cd2ef071ab75ebf6ff2693fd14d4167d7096f6d41fd8ce2a0fe54e4L775

**Comment by andydotxyz** [comment]
So you mean that you extracted the GLFW code into `vendor/github.com/go-gl/glfw/v3.3/glfw/gflw/src`?
