### ISSUE TITLE
Can I move the "New Menu" item to the far right?

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#731]
### Is your feature request related to a problem? Please describe:

Nope just a request.

### Describe the solution you'd like to see:

I want to move "New Menu" item to the end of right side like toolbar (widget.NewToolbarSpacer()).
But there is no function to move menu item.

**Comment by andydotxyz** [comment]
This is not currently supported sorry. Menus behave very differently on various platforms so it’s hard to think of how to make a cross platform approach.

Perhaps you can explain why being on the right is desirable?

**Comment by yms2772** [comment]
> This is not currently supported sorry. Menus behave very differently on various platforms so it’s hard to think of how to make a cross platform approach.
> 
> Perhaps you can explain why being on the right is desirable?

I wanna set a "login menu" to the end of right like a website.

**Comment by andydotxyz** [comment]
Are you sure that is a good idea for core functionality? Remember that on some operating systems (macOS, Ubuntu Unity) the menu will be along the edge of the screen far from the content...

**Comment by yms2772** [comment]
@andydotxyz

I have no choice. There is no function to replace my idea.
I wanna set "Login" on the same menu line.

**Comment by andydotxyz** [comment]
I was trying to suggest that copying web app layout and moving core functionality into the menu is a bit of an anti-pattern due to it potentially removing content from the main window. Would a toolbar or other layout of buttons inside the canvas be closer to what you want to do?

**Comment by yms2772** [comment]
@andydotxyz 
Um.. Ok I'll look for a solution like a toolbar.

**Comment by andydotxyz** [comment]
I have researched this a bit more and found that some toolkits that used to support this recommend against it. So I'm going to close as won't fix.

Extract from GTK docs (gtk_menu_item_set_right_justified):

"Sets whether the menu item appears justified at the right side of a menu bar. This was traditionally done for “Help” menu items, but is now considered a bad idea. (If the widget layout is reversed for a right-to-left language like Hebrew or Arabic, right-justified-menu-items appear at the left.)"
