### ISSUE TITLE
Memory leaks in renderers and canvases cache maps

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#735]
### Describe the bug:
Once created `CanvasObject` and its renderer are never freed. Two caches are stored here:
`internal/driver/glfw/driver.go` - canvases
`internal/cache/widget.go` - renderers
As I can see from code, they are only cleared on window close and only objects that are still in use by that window.
The current workaround is to reuse all widgets but it's hard to do in dynamic interfaces.

### To Reproduce:
Continuously create new widgets, for instance in a long running applications.

### Example code:
```go
package main

import (
	"time"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("test")

	setContent := func() {
		box := widget.NewVBox(
			widget.NewEntry(), widget.NewEntry(),
			widget.NewButton("submit", nil),
		)
		w.SetContent(widget.NewGroup("group", box))
	}

	setContent()
	go func() {
		for range time.NewTicker(100 * time.Millisecond).C {
			setContent()
		}
	}()

	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Device:
 - Go version: 1.13.8
 - Fyne version: develop, 84bca6e4cfaa

**Comment by fpabl0** [comment]
Fixed on `develop`.
