### ISSUE TITLE
Unicode characters cannot be displayed correctly after packaging。

### ISSUE THREAD

**Issue by heshiyingx** [fyne-io/fyne#736]
### Describe the bug:
I have set `FYNE_FONT` before packaging, but Unicode characters cannot be displayed correctly after packaging

### To Reproduce:

```go
func main() {
	
	myApp := app.New()
	myApp.Settings().SetTheme(theme.LightTheme())
	myAppWindow := myApp.NewWindow("这是标题")
	myAppWindow.Resize(fyne.Size{100,200})
	myAppWindow.SetContent(widget.NewVBox(
		widget.NewLabel("你好"),
		widget.NewButton("退出", func() {
			myApp.Quit()
		}),
	))

	myAppWindow.ShowAndRun()
}
```
set chinese font and set fyne_font before package:
```bash
export FYNE_FONT=/System/Library/Fonts/STHeiti\ Light.ttc
fyne package -os darwin -icon myapp.png
```
![image](https://user-images.githubusercontent.com/8655811/76276670-6fac6280-62c1-11ea-8fc8-99ae071187b7.png)

set chinese font and set fyne_font before run:
```bash
export FYNE_FONT=/System/Library/Fonts/STHeiti\ Light.ttc
go run main.go 
```
![image](https://user-images.githubusercontent.com/8655811/76276721-9cf91080-62c1-11ea-9c62-6d8ba5c9af04.png)

### Device (please complete the following information):
 - OS: [MacOS ]
 - Version: [10.14.6]
 - Go version: [1.13.8]
 - Fyne version: [1.2.3]

**Comment by andydotxyz** [comment]
FYNE_FONT is a runtime environment variable, it does not package up the fonts that you list.
Apologies for the confusion. We are working on a way to make it easier for non-supported languages to have fonts downloaded somehow on first-run, but this is not yet resolved.
In the meantime people using your app with Chinese characters will also have to set this environment variable.

**Comment by andydotxyz** [comment]
At this time the bundled font supports around 500 languages (according to the "Noto Sans" documentation https://www.google.com/get/noto). However there are nearly 100 additional languages that we need to support including Bengali, Chinese, Japanese and Thai.

**Comment by heshiyingx** [comment]
> At this time the bundled font supports around 500 languages (according to the "Noto Sans" documentation https://www.google.com/get/noto). However there are nearly 100 additional languages that we need to support including Bengali, Chinese, Japanese and Thai.

ok!thank you very much!
