### ISSUE TITLE
HOWTO? grid layout with different size columns

### ISSUE THREAD

**Issue by rfay** [fyne-io/fyne#737]
### Describe the bug:

I've been trying to make a simple grid of labels that has appropriately sized columns based on the text in the label widgets in the columns, and I just fail to do it. It seems that all the columns are always set to the same size. I've tried a GridLayoutWithRows of a GridLayoutWithColumns and several other things. Even though the MinSize() of the column is correctly calculated, when you push it into 

### To Reproduce:

Here's a snippet of one of many approaches I've tried. With every single approach I end up with identical column widths: https://gist.github.com/rfay/85aeb42ba7175f331639a259885a6e4d

### Screenshots:

<img width="1439" alt="DDEV-Local" src="https://user-images.githubusercontent.com/112444/76352116-21548f00-62d4-11ea-9925-a3d5d46dc093.png">

### Example code:

Snippet: https://gist.github.com/rfay/85aeb42ba7175f331639a259885a6e4d

### Device (please complete the following information):
 - OS: macOS
 - Version: Catalina
 - Go version: 1.14
 - Fyne version: 1.2.3

**Comment by andydotxyz** [comment]
Yes, that is correct, our grid layout is a uniform grid. I guess you are looking for a table widget, which we have not yet created. The plan is that it would be built on top of the data binding API we are adding in release 1.3. There are some workarounds posted where people have used combined layouts to create the effect. Like #157?

**Comment by rfay** [comment]
Wow, talk about responsiveness. Thanks!

**Comment by rfay** [comment]
I note that #157 doesn't help at all though, columns are still the max of any cell:

<img width="767" alt="Hello_and_rfay_t3v9composer-web___etc_cron_d" src="https://user-images.githubusercontent.com/112444/76358575-4c90ab80-62df-11ea-9321-404ca3fe8b56.png">

**Comment by andydotxyz** [comment]
Goodness you are quite right - I never ran the code that was contributed ;)
I updated it by removing the grid layout and get the following result:
![Screenshot from 2020-03-10 21-11-28](https://user-images.githubusercontent.com/294436/76359962-f8ec8500-6313-11ea-9248-6e42e1b655e6.png)

**Comment by andydotxyz** [comment]
It should be noted that this only work as long as all of your cells have the same height, otherwise alignment goes off

**Comment by rfay** [comment]
Would you mind gist-ing your solution? `	return widget.NewVBox(objects...)
` definitely doesn't get the result you show here.

Also, to use that code I had to download and manually install v3.2/glfw in vendor per https://github.com/icexin/gocraft/issues/8#issuecomment-477987644

**Comment by andydotxyz** [comment]
Did you copy and paste my updated code? There is no instance of “NewVBox(objects...)” in what I pasted (it’s HBox)?

**Comment by andydotxyz** [comment]
If you are performing your own vendoring then yes that is an issue - we have introduced a new “fyne vendor” command that solves this for you - I haven’t mentioned it on the website yet but you could try it out if you have the latest version of the ‘fyne’ command.

**Comment by rfay** [comment]
You didn't mention that you had updated https://github.com/fyne-io/fyne/issues/157#issuecomment-597319590 :) so no, I didn't... (and thanks!) 

Requiring `fyne vendor` sure sounds like a suspicious hack, sad to say. But I'll sure try it.

**Comment by andydotxyz** [comment]
Apologies, I was working on 3 issues concurrently ;). 

Fyne vendor may feel like a hack but unfortunately it’s due to the design of go vendor, as the missing directory contains no go code... if you have a better solution we would be glad :)

**Comment by rfay** [comment]
I note that installing "fyne" requires `go get fyne.io/fyne/cmd/fyne`, which I also don't think is mentioned anywhere.

**Comment by rfay** [comment]
And unfortunately...
```
 ~/go/bin/fyne vendor
Unsupported command vendor
```

Thanks so much for your amazing and prompt help.

**Comment by andydotxyz** [comment]
It’s not mentioned everywhere but I think the first place mentioning the command should cover it https://tour.fyne.io/introduction/packaging.html.
Or there is a more complete developer page https://fyne.io/develop/distribution.html

**Comment by andydotxyz** [comment]
Apologies, the vendor subcommand is currently in testing so you’d need to build it from the develop branch. (Now that I think about it that’s probably why it’s not documented anywhere yet ;) ).

**Comment by rfay** [comment]
```
git clone github.com/fyne-io/fyne
cd fyne
git checkout origin/develop
go install ./cmd/fyne
cd <myproject>
~/go/bin/fyne vendor
```

**Comment by rfay** [comment]
And I confirm that https://github.com/fyne-io/fyne/issues/157#issuecomment-597319590 does what I'm after... Now to adapt! Thanks!

**Comment by andydotxyz** [comment]
Great, thanks for letting us know. Can we close this as a duplicate of that ticket do you think?

**Comment by rfay** [comment]
Well, people will stumble on the vendor problem, but yes. Closing as duplicate of #157 now that https://github.com/fyne-io/fyne/issues/157#issuecomment-597319590 does what's needed. I'll move discussion of `fyne vendor` over there.
