### ISSUE TITLE
Possible to cross-compile macOS version on Linux? 

### ISSUE THREAD

**Issue by rfay** [fyne-io/fyne#741]
### Describe the question:

From https://fyne.io/develop/cross-compiling.html I note that "You will also need to install the macOS SDK". Does that mean that it's impossible to cross-compile a macOS version on Linux?  (And same question for Windows of course, and same question about compiling Windows/Linux on macOS)

Thanks,
-Randy

**Comment by andydotxyz** [comment]
No, it is absolutely possible to cross-compile for macOS from Linux. You will have to obtain the macOS SDK from Apple (easiest is via the XCode download where you can extract the files from).
It is not possible, however, to compile apps for iPhone on anything apart from a Mac. These are license issues not technical issues really.

I put some more details in Chapter 14 "Distributing your application" in my [Go GUIs book](https://www.packtpub.com/gb/application-development/hands-gui-application-development-go).
You can also learn a lot from [osxcross documentation](https://github.com/tpoechtrager/osxcross).

**Comment by andydotxyz** [comment]
Of course if you would rather not juggle SDKs and compiler toolchains you might want to use the [fyne-cross](https://github.com/lucor/fyne-cross) tool.

**Comment by andydotxyz** [comment]
Closing this issue with the summary answer "yes" :)

**Comment by rfay** [comment]
I didn't know the "Go GUIs" book was yours! I was reading that yesterday on Safari. 

Oh, I see fyne-cross is mentioned on https://fyne.io/develop/cross-compiling.html - it just gets lost below the hard stuff. Probably the virtual stuff should be mentioned before the "who would ever do it" stuff that requires api download and such.

Thanks so much!

**Comment by andydotxyz** [comment]
That's a good suggestions, we could probably re-order the page when fyne-cross matches parity with the supported platforms. We will probably get a chance to polish a lot of this stuff once 1.3 development is completed.
