### ISSUE TITLE
Size and the minimum size of the Layouts and widgets

### ISSUE THREAD

**Issue by hussam132** [fyne-io/fyne#748]
I want to knew what the default Size and the minimum size of the Layouts and widgets 
or what the criterion of the sizes of each Layouts and widgets in the design that's appears automatically when it's created without the size specifying by the user ???

**Comment by andydotxyz** [comment]
The minimum size of a widget and a layout is the minimum required to show its contents and padding. The default size for everything is it’s minimum size. A layout will then influence the size of its children according to its algorithm within the size of its container.

The special cases are that a window will expand its content to fill and a container with no layout allows widgets to be positioned manually.

You could check out the tour segment on layouts https://tour.fyne.io/layout/

**Comment by hussam132** [comment]
will be my fyne design in my PC at the full screen mode the same in the phones ; I mead I don't care size different between the full screen in the PC and the mobiles does the layout and the widget design and arrangement will be the same in mobile like in the PC ???

**Comment by andydotxyz** [comment]
Most widgets work the same on desktop and mobile. A TabContainer will make sure that the tabs are in an appropriate position on mobile. You can use things like AdaptiveGridLayout if you want your screen to adjust for vertical / horizontal alignment.

For general questions I recommend joining the #fyne channel on gophers slack server (link in footer of https://fyne.io/)
