### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by billc3012** [fyne-io/fyne#753]
An onsizechange function on a window would allow some layout control at the application level.

Fyne is a very nice well-thoughtout  package.  Your tutorial is excelent.

I am  writing a client frontend for my GO web application.  I wanted to add some responsive design and need to know if the user resizes the window manually.  To test responsive design I normally just resize a window on the desktop I am working on.

I found using browsers and websockets inflexible and am now trying to use fyne to develop a GUI

Thanks for such a nice package.  Keep up the good work.

**Comment by andydotxyz** [comment]
Fyne containers and widgets already respond to changing window sizes, this is done without callbacks like other toolkits have in place.
To manage an area manually you can either write a layout (implement fyne.Layout) and pass it to `fyne.NewContainerWithLayout` or create a widget (a little more complex, covered on https://fyne.io/develop/custom-widget.html).

You will see that both a Layout and a WidgetRenderer have 2 similar methods, Layout and MinSize. The minSize call (as you might guess) states the smallest that it's contents can be. The Layout method is called every time the size changes and will pass the current size in.

**Comment by billc3012** [comment]
Thanks Andy.  Just the information I need.

I will proceed as suggested; possibly a purpose built widget will be
appropriate.

Thanks for the prompt reply.

Bill
