### ISSUE TITLE
shape with gradient color

### ISSUE THREAD

**Issue by sadeghpro** [fyne-io/fyne#756]
Can I draw a shape with gradient color for example a line with gradient color or a circle with linear gradient color from right to left?

**Comment by andydotxyz** [comment]
We don't currently have support for that feature no. Our canvas API is prioritising the drawing tools for supporting widgets. Contributions are accepted though :)

**Comment by sadeghpro** [comment]
tnx, I'll work on it

**Comment by sadeghpro** [comment]
Ok I check `rasterx` project and I found :
```
func (s *ScannerGV) SetColor(clr interface{}) {
	switch c := clr.(type) {
	case color.Color:
		s.clipImage.ColorFuncImage.Uniform.C = c
		if s.clipImage.clip == image.ZR {
			s.Source = &s.clipImage.ColorFuncImage.Uniform
		} else {
			s.clipImage.ColorFuncImage.colorFunc = func(x, y int) color.Color {
				return c
			}
			s.Source = s.clipImage
		}
	case ColorFunc:
		s.clipImage.ColorFuncImage.colorFunc = c
		if s.clipImage.clip == image.ZR {
			s.Source = &s.clipImage.ColorFuncImage
		} else {
			s.Source = s.clipImage
		}
	}
}
```
`SetColor` parameter is interface and accept two type `color.Color` or `rasterx.ColorFunc`.
Then if we change `StrokeColor` of `Line` and `FillColor` of `Circle` and `Rectangle` type to `interface{}` then we can generate `ColorFunc` and pass it or use rasterx gradient like this:
```
package main

import (
	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"github.com/srwiley/rasterx"
	"golang.org/x/image/colornames"
)

func main() {
	myApp := app.New()
	w := myApp.NewWindow("Line")
	linearGradient := &rasterx.Gradient{Points: [5]float64{0, 0, 1, 0, 0},
		IsRadial: false, Bounds: struct{ X, Y, W, H float64 }{
			X: 50, Y: 50, W: 100, H: 100}, Matrix: rasterx.Identity}

	linearGradient.Stops = []rasterx.GradStop{
		{StopColor: colornames.Aquamarine, Offset: 0.3, Opacity: 1.0},
		{StopColor: colornames.Skyblue, Offset: 0.6, Opacity: 1},
		{StopColor: colornames.Darksalmon, Offset: 1.0, Opacity: .75},
	}
	line := canvas.NewLine(linearGradient.GetColorFunction(1))
	line.StrokeWidth = 5
	w.SetContent(line)

	w.Resize(fyne.NewSize(100, 100))
	w.ShowAndRun()
}
```
out put is 
<img width="108" alt="Screen Shot 2020-03-20 at 9 24 51 AM" src="https://user-images.githubusercontent.com/22843329/77140561-45ac2a80-6a8f-11ea-9d90-d744c0307844.png">
every thing  is good but I think maybe it's confuse beginners when see FillColor type is interface.I think it's better to change access of `FillColor` to private and create two `SetSolidColor(c color.Color)` and `SetGradientColor(color rasterx.ColorFunc)`. but this way need a big change in project and all project use this project then I can't choose which one better.
is there a better solution?

**Comment by andydotxyz** [comment]
The pattern is for draw primitives to use fields so that there is no hidden complexity - the graphics driver can optimise and perhaps upload the problem to a graphics card (that is why we have gradient types that are defined by their fields, not by a function).
If there was some way to use the current gradient definitions and pass them as parameters into line etc that might be more suitable.

I agree that `Color: interface{}` is confusing to beginners and it removes our aim to rely on compile time checks for correct API usage.
