### ISSUE TITLE
Allow Disabling of ScrollContainer Direction

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#763]
### Is your feature request related to a problem? Please describe:
By default a ScrollContainer can scroll in both horizontal and vertical directions. When reading text scrolling horizontally is tedious.

### Is it possible to construct a solution with the existing API?
Not possible at this time

### Describe the solution you'd like to see:
A way to create a ScrollContainer for a given direction only whose MinSize takes into account the child content's MinSize.

For example, a ScrollContainer can be created for only the vertical direction. An Entry with text wrapping enabled can be added to ScrollContainer so that it can only be scrolled vertically and long lines of text are wrapped to the next line.

**Comment by andydotxyz** [comment]
In a slight follow on to the topic above:

Yes it is possible to make this work in the current API. If the scrollcontainer was big enough to handle the content in the direction you do not want to scroll then this would work around the issue - that is how we have been doing it so far.

That said fixing it properly is very welcome :)

**Comment by andydotxyz** [comment]
The minimum size of content doesn’t change when a window resizes surely? Anyhow it was just a workaround for the record - not disagreeing with the need of this feature

**Comment by stuartmscott** [comment]
@andydotxyz is there any pending work, or do you think this can be closed?

**Comment by andydotxyz** [comment]
Oh develop for testing
