### ISSUE TITLE
Add support for "true" ComboBox with editable field

### ISSUE THREAD

**Issue by MarSoft** [fyne-io/fyne#769]
### Is your feature request related to a problem? Please describe:

Sometimes it is necessary to have a drop-down combobox with editable field. Fyne currently doesn't seem to support such widget.

### Is it possible to construct a solution with the existing API?

I suspect it should be possible, but I could not find out how.

### Describe the solution you'd like to see:

There should be a widget like `EditableSelect` which should combine some properties of `Select` and `Entry` widgets.

**Comment by andydotxyz** [comment]
This is in our `develop` branch as SelectEntry, it will be part of the 1.3 release due in May.
See #732 
Closing as duplicate
