### ISSUE TITLE
Gobind feature

### ISSUE THREAD

**Issue by ehsannm** [fyne-io/fyne#777]
Currently we are using gobind (gomobile project) to create sdk for our native apps. Since Fyne is a great framework for creating apps, it is also good to provide a way to create golang sdk which could be used by existing native apps.

Do you have any plan for this?

**Comment by andydotxyz** [comment]
We do not have any plans for this. Fyne is designed to create full applications - we need to control the content of the window and it's lifecycle therefore I don't think gobind makes sense.

Please do let me know if I have misunderstood - what is the specific idea you had in mind to call a Go based GUI from within a language-native app?

**Comment by ehsannm** [comment]
I understand that Fyne is full application framework, which is great. But I think there is also demand for some mixed environment projects. For instance, we have a project which UI is already implemented with the device specific SDKs, i.e. JAVA and Swift ... but we want to create a component in Golang which could be called from both apps. At the moment the only solution is using Gobind, which is not very active project and I guess it will add value to Fyne project more. Also helps to move UI to Fyne gradually for already existing apps. 

I am just proposing this, and I reckon this help us move to Fyne easier. Since writing from scratch is something which tie hands in existing projects.

**Comment by andydotxyz** [comment]
Unfortunately the Fyne app (like any other app framework) needs to run an event loop on the main thread. To support mixed app environments would require somehow multiplexing different event loops in an application.

I’m not going to say this can’t or won’t be done - but it is a huge amount of work and not a high priority. I can’t imagine the strange dis-jointed user experience that would be created by having different parts of an application use different widget sets.

**Comment by Bluebugs** [comment]
I would like to add that in my experience bindings between different language lead to unmaintained or under maintained piece of code (Even with a lot of auto generated code). The main reason being that the intersection of people who know both side of the fence and can understand the fence become very small. So on top of this binding being always very complex, they also are usually lead to massive technical debt and split community (Imagine reporting a bug on Fyne when used from Java and expect a Go developers that do not understand the binding and Java to figure out the problem).

I think it is one think I really like about Fyne is that its users of the API and the developers of the API use the same language creating no barrier between this two community to understand each others need. I do not think it would be wise to change this core feature of the Fyne project and maybe it should be an official goal of the project.

**Comment by Jacalz** [comment]
I must say that I fully agree with @Bluebugs in regards to this. My experience with using various bonds for code written in other languages has been all but positive.

**Comment by ehsannm** [comment]
I am not fan of the mixed environments and I don't want talk about it. Because it is big topic and both have their cons and pros. But my point is in real life there are many mixed environment projects. Specially in apps. mixing js, html, css in native apps is common. 

And some time things like encryptions, search indexing , ... are easier in some languages. Or may be you find a good lib in Rust or Go and you think of using it in your app. 

Another thing is that if you want to move an existing project to Fyne, it is more practical to do it gradually. And if you could support it as i mentioned like 'gobind' then it is much easier to also move UI to Fyne.

This is just a proposal, which I think helps to grow the Fyne community and make it to the top against Flutter or ReactNative ....

**Comment by andydotxyz** [comment]
We don't intend to support embedding JS/HTML into Fyne apps for UX and code maintenance reasons. I think the same applies in this case, as BlueBugs indicated.

If we support a "module" approach then it no longer holds true that you can just run a Fyne app on any platform to get the same result. I see how some people would want this, but the more I think about it the more I think this does not fit for us.

**Comment by txthinking** [comment]
Is there any plan to support ios extension

**Comment by andydotxyz** [comment]
Can you explain what you mean by iOS extension @txthinking - is it this? https://developer.apple.com/app-extensions/

**Comment by txthinking** [comment]
Yes. That is the link.

**Comment by andydotxyz** [comment]
Some items yes, other items possibly not. If you have a particular use-case that you want to enable then please open a ticket and describe the details.

**Comment by andydotxyz** [comment]
I'm going to close this ticket as the headline item isn't something weare progressing.
If you want to call out to other languages (as some other comments mentioned) there is CGo and from there you can Objective-C or even call into Android JVM (see the toolkit code for examples).
