### ISSUE TITLE
bind callback like javascript

### ISSUE THREAD

**Issue by Virgil-N** [fyne-io/fyne#778]
I created a button and I want to bind a function later. And I don not want to wrap button in a new struct.
Just like:
btn := widget.NewButton(s string, func() {} /*optional*/)
btn.click(func() {...})
or
btn.click = func() {...}

**Comment by andydotxyz** [comment]
You can set `Button.OnTapped` later on.

**Comment by Virgil-N** [comment]
> You can set `Button.OnTapped` later on.

I found it. Thanks!
I'll try to use it.

**Comment by Virgil-N** [comment]
> You can set `Button.OnTapped` later on.

One more question.
eg:
btn := widget.NewButton(s string, f func() {...})
Why f is required? I think change it optional is better.
