### ISSUE TITLE
Fonts are faded on macOS

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#78]
Text appears pale or blurred

**Comment by NickolayPolozovAKQA** [comment]
Fonts appear blurry again after [e14b7d3](https://github.com/fyne-io/fyne/commit/e14b7d32a26da87f051bb5c09b47f7e83b40aa7e)

**Comment by andydotxyz** [comment]
Can you please confirm OS and version so we can replicate?

**Comment by NickolayPolozovAKQA** [comment]
@andydotxyz  MacOS 10.14.3

**Comment by andydotxyz** [comment]
Thanks. I think this must be a retina display issue. I have pushed a fix - please let me know if it helps.
