### ISSUE TITLE
Shortcuts not properly interpreted on non en_US keyboard

### ISSUE THREAD

**Issue by pieter-biomerieux** [fyne-io/fyne#790]
### Describe the bug:
Shortcut keys are based on en_US keyboard layout (qwerty).

When using Crtl+a on an azerty keyboard nothing happens. Ctrl+q, on the other hand, triggers select all, because "q" is on the same place on azerty as "a" would be on qwerty. 

### To Reproduce:
Steps to reproduce the behaviour:
1. Use an azerty keyboard
2. Add an entry widget to your application
3. Type some text
4. Try to select it with Ctrl+a
5. Nothing happens
6. Try to select it with Ctrl+q
7. All text is selected

### Device (please complete the following information):
 - OS: Ubuntu
 - Version: 18.10
 - Go version: 1.12.7
 - Fyne version: 79219c23682e4cec4246dead2d7e4c7370470d21

**Comment by andydotxyz** [comment]
I have provided an alternative fix in #809 which guarantees that fyne.KeyQ will be the key to generate a 'q' rune. This seems logical and matches how mobile works. However it's not perfect. To generate all key codes, it would need to add keys name constants for the following keys: ':', 'ù', '$', '^', ')', '<'. (if this seems sensible we can certainly do it)

Another alternative that I have considered is to stop generating key events for printable characters (using the rune callback only), but that seems a bit extreme.

**Comment by andydotxyz** [comment]
Solution is available on develop branch for testing now if you're interested.
