### ISSUE TITLE
Implement widget.NewFileChooserButton() and actions (akin to gtk3 impl.)

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#794]
### Is your feature request related to a problem? Please describe:
Before using Fyne, I was using Gotk3 and when using the wonderful new file dialog implementations I noticed that I was missing something from Gtk that I think would be beneficial to have to make the file dialog even more useful, namely file widget buttons. They make it a simpler and nicer for developers to have fancy looking buttons for doing various file actions.

### Describe the solution you'd like to see:

Having a separate dialog is great and it gives developers a lot more flexibility, but I think the inclusion of a `widget.NewFileChooserButton()` would make it easier for users that just want a button. The Gotk3 implementation looks like this:
![image](https://user-images.githubusercontent.com/25466657/78064323-df2de300-7391-11ea-9f4b-da7dcac17cb8.png)

This button then show a file icon or folder icon in the widget when the user has select something and makes it both visually pleasing and clear to see if something has been selected or not.

![image](https://user-images.githubusercontent.com/25466657/78064834-9cb8d600-7392-11ea-8722-85680fc319e8.png)

 Another important part of this is the action that is used when creating the widget. This allows to set weather or not it should handle save, open, select folder or create folder. This means that one widget can handle multiple different ways of interaction.

An action is implemented like this:

![image](https://user-images.githubusercontent.com/25466657/78065051-fd481300-7392-11ea-90fb-e1496d9a6b48.png)

### Is it possible to construct a solution with the existing API?
Yeah I think so. Using an action for the widget for save or open could just open those dialog functions. Selecting and creating folders would of course need to be done too, but in general, yes.

**Comment by andydotxyz** [comment]
Hmm, this is an interesting one. I can't remember the last time I saw one of these (outside the restrictions of a web browser).
So I thought I would ask - is there a big need for such a thing? Obviously you think so - but what are other people's opinions? (anyone?)

**Comment by Jacalz** [comment]
After a lot of though and a little bit of forgetting to answer, I have concluded that I don't think this is a much needed feature. Will close this for now.
