### ISSUE TITLE
Consistent Directional Constructor Names

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#795]
The naming convention for constructors of directional widgets and layouts is NewHX and NewVX, eg:
- NewHBox & NewVBox
- NewHBoxLayout & NewVBoxLayout

However newer additions do not follow this convention (my bad), eg:
- NewHorizontalScrollContainer & NewVerticalScrollContainer

**Comment by andydotxyz** [comment]
That is a good point. I wondered about whether the longer was better - but as it's not a big deal either way let's go with the existing standard, good catch.
