### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Virgil-N** [fyne-io/fyne#798]
App crashed.

My codes here:

```
package layout

import (
	"fmt"
	"log"
	"os"
	"strconv"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
	p "github.com/Virgil-N/models/person"
)

type appInfo struct {
	name string
	icon fyne.Resource
	canv bool
	run  func(fyne.App)
}

func init() {
	defer func() {
		if msg := recover(); msg != nil {
			file, _ := os.Create("error.log")
			defer file.Close()
			logger := log.New(file, "[Error]", log.Ldate|log.Ltime)
			logger.Panicln(msg)
		}
	}()
	app := app.New()
	appInfo := &appInfo{
		name: "myTestApp~",
	}
	if icon, err := fyne.LoadResourceFromPath("./resource/img/icon/appIcon.jpg"); err == nil {
		appInfo.icon = icon
	}
	fmt.Println(appInfo.icon.Name())

	personOpts := []p.SetPerson{
		p.SetPersonName("Ann"),
		p.SetPersonAge(12),
		p.SetPersonGender('F'),
	}

	person := p.NewPerson(personOpts...)

	window := app.NewWindow("😍😍😍")
	window.Resize(fyne.NewSize(600, 400))
	window.CenterOnScreen()
	window.SetIcon(appInfo.icon)

	menuItems := make([]*fyne.MenuItem, 3, 9)
	for i := 0; i < 3; i++ {
		menuItem := fyne.NewMenuItem("hello", func() {
			fmt.Println(i)
		})
		menuItems = append(menuItems, menuItem)
	}
	menu := fyne.NewMenu("menu", menuItems...)
	mainMenu := fyne.NewMainMenu(menu)

	window.SetMainMenu(mainMenu)

	btn1 := widget.NewButton(person.Name, func() {})
	btn2 := widget.NewButton(strconv.Itoa(int(person.Gender)), func() {
		app.Quit()
	})
	btnList := widget.NewVBox(btn1, btn2)

	btn1.OnTapped = func() {
		fmt.Println("btn1 tapped 2")
	}

	check := widget.NewCheck("Are you a teacher?", func(checked bool) {
		if checked == true {
			fmt.Println("checked")
		} else {
			fmt.Println("not checked")
		}
	})

	text := widget.NewLabel(appInfo.name)

	widgetContainer := fyne.NewContainerWithLayout(
		layout.NewGridLayout(1),
		fyne.NewContainerWithLayout(layout.NewCenterLayout(), text),
		fyne.NewContainerWithLayout(layout.NewCenterLayout(), check),
		fyne.NewContainerWithLayout(layout.NewCenterLayout(), btnList),
	)

	fixedContainer := fyne.NewContainerWithLayout(layout.NewFixedGridLayout(fyne.NewSize(300, 300)), widgetContainer)
	container := fyne.NewContainerWithLayout(layout.NewCenterLayout(), fixedContainer)

	window.SetContent(container)

	window.ShowAndRun()
}
```

When I click the mainMenu, it crash.

Here is the output info:
`API server listening at: 127.0.0.1:45445
person init finished.
appIcon.jpg
checked
not checked
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7832dc]

goroutine 18 [running]:
fyne.io/fyne/widget.NewPopUpMenuAtPosition(0xc00006e750, 0xd0d200, 0xc00022a000, 0x0, 0x1d, 0x0)
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/widget/menu.go:20 +0x21c
fyne.io/fyne/internal/driver/glfw.showMenu(0xc00006e750, 0x0, 0x1d, 0xd0d200, 0xc00022a000)
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/menu.go:56 +0x5a
fyne.io/fyne/internal/driver/glfw.(*menuBarAction).ToolbarObject.func1()
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/menu.go:22 +0x165
fyne.io/fyne/widget.(*Button).Tapped(0xc000224090, 0xc00008c220)
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/widget/button.go:169 +0x7b
fyne.io/fyne/internal/driver/glfw.(*window).mouseClicked.func6()
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/window.go:666 +0x5a
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc000226000)
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/window.go:1030 +0x8a
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow.func1
	E:/workspace/go/GOPATH_DIR/pkg/mod/fyne.io/fyne@v1.2.3/internal/driver/glfw/window.go:1062 +0x314
`

### Device:
 - OS: Win10
 - Version: lastest
 - Go version: 1.14
 - Fyne version: lastest

**Comment by andydotxyz** [comment]
This code cannot be run locally because it relies on resources.
Can you minimise the code down to essential code to replicate the crash please?

**Comment by andydotxyz** [comment]
I think I see what the problem is. You are accidentally inserting 3 nil menus into the main menu...
The initial size of the `menuitems` is 3, meaning it has 3 nils before you start appending. Please use one of the following instead:

```menuItems := make([]*fyne.MenuItem, 0, 3)```

or the simpler

``` var menuitems []*fyne.MenunItem```

**Comment by Virgil-N** [comment]
> I think I see what the problem is. You are accidentally inserting 3 nil menus into the main menu...
> The initial size of the `menuitems` is 3, meaning it has 3 nils before you start appending. Please use one of the following instead:
> 
> `menuItems := make([]*fyne.MenuItem, 0, 3)`
> 
> or the simpler
> 
> ` var menuitems []*fyne.MenunItem`

Your codes run well.
Thanks!
