### ISSUE TITLE
FileDialog not scrolling to the top if a directory is entered

### ISSUE THREAD

**Issue by kori-irrlicht** [fyne-io/fyne#800]
### Describe the bug:
If you enter a directory in the FileDialog, the FileDialog does not scroll back to the top. In some cases you can't even see the content of the new directory.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to a directory with a lot of subdirectories
2. Scroll to the bottom
3. Enter a directory

### Screenshots:
![fyne-filedialog-bug](https://user-images.githubusercontent.com/10913205/78161833-56bd4a00-7446-11ea-8c21-cb91e08fdf15.png)

### Device (please complete the following information):
 - Fyne version: v1.2.4-0.20200328160144-a85639c2c5ff

**Comment by andydotxyz** [comment]
Thanks for catching this, should be fixed now
