### ISSUE TITLE
Selecting a tab on extended TabContainer doesn't display it as selected but it's content displays

### ISSUE THREAD

**Issue by pawkordek** [fyne-io/fyne#810]
### Describe the bug:
Selecting a tab on extended _TabContainer_ by clicking on it doesn't display it as if it were selected (color change) even though it's content gets displayed. The previously selected tab has the correct color instead. It also happens when updating the selected tab using _TabContainer_'s _SelectItemIndex_ or _SelectItem_ functions.

### To Reproduce:
1. Extend _TabContainer_ and create at least two tabs with some content (for example using the code below).
2. Switch to the second tab by clicking on it.
3. Observe that while the displayed content belongs to the second tab, the second tab doesn't have blue (when using dark theme) background indicating that it has been selected. Instead, the first tab is colored as selected.

### Screenshots:
![fyne_tab_container_bug](https://user-images.githubusercontent.com/29333779/78411672-ba936e80-7610-11ea-8e43-7f388b687543.gif)

### Example code:
```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

type ExtendedTabContainer struct {
	*widget.TabContainer
}

func NewExtendedTabContainer() *ExtendedTabContainer {
	container := ExtendedTabContainer{
		TabContainer: widget.NewTabContainer(
			widget.NewTabItem("First tab", widget.NewVBox(widget.NewLabel("Text on first tab"))),
			widget.NewTabItem("Second tab", widget.NewVBox(widget.NewLabel("Text on second tab")))),
	}
	container.ExtendBaseWidget(container)
	return &container
}

func main() {
	application := app.New()
	window := application.NewWindow("test")
	window.SetContent(NewExtendedTabContainer())
	window.ShowAndRun()
}
```

### Device:
 - OS: Void Linux
 - Go version: go1.14 linux/amd64
 - Fyne version: 1.2.3

**Comment by andydotxyz** [comment]
On further investigation this isn't a bug sorry. When extending widgets you need to embed them as their struct, not a pointer - as follows:

```go
type ExtendedTabContainer struct {
	widget.TabContainer
}

func NewExtendedTabContainer() *ExtendedTabContainer {
	container := &ExtendedTabContainer{Items:}
	container.ExtendBaseWidget(container)

	container.Items = []*widget.TabItem{
		widget.NewTabItem("First tab", widget.NewVBox(widget.NewLabel("Text on first tab"))),
		widget.NewTabItem("Second tab", widget.NewVBox(widget.NewLabel("Text on second tab"))),
	}

	return container
}
```

**Comment by andydotxyz** [comment]
Ah, there is a bug here as well sorry. You will need to use the revised code above, but when 1.2.4 releases it will work as expected.

**Comment by andydotxyz** [comment]
It's working on the develop branch just now if you'd like to test. I will be starting the release setup soon, I expect it should be out in a week or so.

**Comment by pawkordek** [comment]
I tested it today using the develop branch and it works now. Thank you.
