### ISSUE TITLE
How to hide text in the entry when overflow

### ISSUE THREAD

**Issue by Virgil-N** [fyne-io/fyne#811]
I create a entry with NewFixedGridLayout, when the input text is too long, some text is display out of the container.
How can I hide the text out of the container, like "overflow:hidden" in css.

**Comment by Virgil-N** [comment]
And fixedLayout dose not work on form widget.
`
fyne.NewContainerWithLayout(
			layout.NewFixedGridLayout(fyne.NewSize(200, 20)),
			widget.NewForm(),
		)
`

**Comment by andydotxyz** [comment]
I think that this probably relates to scrolling in entries (#471) - a team discussion decided that it didn't make sense to truncate entry content as the user wants to be able to edit the whole content even if it's small.

Also calling "Resize" on any widget only makese sense if they are not being managed by a layout. Either the layout of a container controls the size and position of all contents or you use no layout and manage these yourself.

**Comment by andydotxyz** [comment]
It's possible that the FixedGridLayout is not the right thing for your application - it is the only layout that does not respect widget MinSize (possibly this could be fixed?). It currently enforces the size specified irrespective of the content. Overflow issues should not be evident in any other layout used.
