### ISSUE TITLE
Key events not blocked by overlays

### ISSUE THREAD

**Issue by toaster** [fyne-io/fyne#814]
### Describe the bug:

When opening a pop-up (like the menu) the overlay should catch all events. This works well for mouse events but keyboard events are still forwarded to the window's content.

Maybe this isn't fixable by generic event blocking in overlays. When a pop-up belongs to a form widget (`Select` or `EntrySelect`), the `<TAB>`-key should probably close the pop-up.

### To Reproduce:

Steps to reproduce the behaviour:
1. Open demo app without native menus
2. Open the Widget->Input pane
3. Click on a menu
4. Press `<TAB>` until the entry widget has focus
5. Enter some text
6. See error

### Screenshots:

![keyboard_events_with_open_menu](https://user-images.githubusercontent.com/73959/78469295-1d276000-7720-11ea-9142-2cd2527cd6c1.gif)

**Comment by toaster** [comment]
This is partly fixed with #1318 which fixes the focus handling for overlays.
However, the menu part is still open.

**Comment by andydotxyz** [comment]
This has a pretty solid solution on `develop` now, thanks @toaster.
Closing
