### ISSUE TITLE
Add tab support for moving through focus items

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#82]
Shift-tab should go backward

**Comment by eugenekurasov** [comment]
Hi, is any update? If not, I want to help implement this feature.

**Comment by andydotxyz** [comment]
Not yet, sorry. We are working through the 1.1 milestone in priority order https://github.com/fyne-io/fyne/milestone/2 .

We are roughly half way through and there are a couple of large tasks ahead of this.

Contributions would be gratefully received thanks!

**Comment by andydotxyz** [comment]
I am picking up this work now, hopefully we can have something for testing next week

**Comment by andydotxyz** [comment]
This is now on develop branch for testing
