### ISSUE TITLE
FileDialog: Set start directory

### ISSUE THREAD

**Issue by kori-irrlicht** [fyne-io/fyne#821]
### Is your feature request related to a problem? Please describe:
 - It's kinda annoying to always navigate the file system to the working dir to load the (test) data for my program.
 - If I want to specify a location to save a file to, I'd like my program to have a default location, which is not the $HOME dir (could be a specific dir or the dir from which the initial data was loaded)

### Describe the solution you'd like to see:
It would be nice to set the (starting) dir of the FileDialog by calling a function or as a parameter for ShowFile(Open|Save). Or it could be specified with the Preferences-API.

**Comment by andydotxyz** [comment]
Agreed that this should be added. Though I don't think it should have any connection with preferences.

**Comment by andydotxyz** [comment]
This is a work in progress, but I don't think it's a blocker any more.
As discussed this morning it's more of a developer utility rather than user - for them home directory makes more sense.

**Comment by andydotxyz** [comment]
`FileDialog.SetLocation` now on develop for testing
