### ISSUE TITLE
App crashes on startup in develop branch

### ISSUE THREAD

**Issue by yms2772** [fyne-io/fyne#824]
### Describe the bug:

App crash

I found issue #816 and it fixed at 1.2.4. But develop branch has this error too.
So please add that fixed codes to develop branch.

### Example code:

any code

```go
goroutine 1 [running, locked to thread]:
fyne.io/fyne.CurrentDevice(0x0, 0xc00015c300)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/device.go:40 +0x2b
fyne.io/fyne/app.defaultTheme(0x46c045c, 0xa)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/app_darwin.go:17 +0x22
fyne.io/fyne/app.(*settings).setupTheme(0xc00002e200)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/settings.go:126 +0x9e
fyne.io/fyne/app.(*settings).load(0xc00002e200)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/settings.go:90 +0x5c
fyne.io/fyne/app.loadSettings(...)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/settings.go:132
fyne.io/fyne/app.NewAppWithDriver(0x47a1b00, 0xc00015c2a0, 0x0, 0x0, 0x2, 0xc0000bc210)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/app.go:99 +0x60
fyne.io/fyne/app.NewWithID(...)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/app_gl.go:13
fyne.io/fyne/app.New(0x47a28e0, 0xc00002e180)
	/Users/jongmin_park/Documents/tmi_downloader/src/fyne.io/fyne/app/app.go:86 +0x88
main.main()
	/Users/jongmin_park/Downloads/TMIdownloader/tmi_downloader.go:70 +0x19f
```

### Device (please complete the following information):
 - OS: MacOS
 - Version: 10.15.4 (Latest)
 - Go version: 1.14.1 (Latest)
 - Fyne version: develop

**Comment by andydotxyz** [comment]
The fixes for 1.2.4 will be merged back into develop after release.
Given how much the code bases have diverged this is a complicated process and it's best to just do it once. If we merge it all in one go then no fixes get missed in the process.

**Comment by yms2772** [comment]
> The fixes for 1.2.4 will be merged back into develop after release.
> Given how much the code bases have diverged this is a complicated process and it's best to just do it once. If we merge it all in one go then no fixes get missed in the process.

Then according to roadmap, the fixes for 1.2.4 will be merged into develop at 13 April and before coming 13 April, we cannot use develop branch on latest version of MacOS. Right?

**Comment by andydotxyz** [comment]
In the meantime you can specify a theme in your environment (FYNE_THEME=“dark”) and everything should work as normal. Sorry for the inconvenience.

**Comment by andydotxyz** [comment]
You know you are probably right - this should have been considered a hotfix.
I took another look at the code and realised it would probably merge OK. So it's now on develop.
Apologies for the confsion and thanks for the contribution.
