### ISSUE TITLE
Consistent widget file layout

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#827]
Every widget seems to have a different file layout; some define the widget struct, widget constructors, widget functions, then widget renderer. Others define the renderer first with widget constructors at the bottom. Others like Toolbar define their auxiliary objects first. Can we define and adhere to a consistent file layout?

My preferred file layout would be;
- widget struct
- widget constructor(s)
- widget exported functions
- widget unexported functions
- widget auxiliary objects
- widget renderer
- widget renderer auxiliary objects

Existing files can be updated without breaking the API although they will lose git blame-ability.

**Comment by andydotxyz** [comment]
This works for me. Though I would be tempted to put the renderer with the object it renders rather than after it's auxiliary objects.

The other possible change would be putting renderers in another file. It could make it a little more annoying to develop but it would further encourage the separation :)

**Comment by stuartmscott** [comment]
That makes sense;
- widget struct
- widget constructor(s)
- widget exported functions
- widget unexported functions
- widget renderer
- widget auxiliary objects
- widget renderer auxiliary objects

Yeah @toaster mentioned this as well. It would be good to separate them, but if most changes to a widget affect its renderer too then it will be annoying

**Comment by toaster** [comment]
I like the idea!

Regarding separated files:
1. If we do this then the auxiliary objects should have their own files, too, shouldn't they?
2. This would create a lot of more files in the widget folder.

What about this:
- keep renderer and widget together in a file (for now)
- extract auxiliary widgets into separate files
- keep other auxiliary objects in their widget's file

**Comment by andydotxyz** [comment]
Changes such as this probably have a relatively small window to put in as reordering files is very disruptive to potential merges of PRs, bugs or branches. If this is to be in as part of 1.3 push then I would say we likely need it in the next 3 or 4 days, otherwise it gets pushed to the (longer) 2.0 window that opens around May 5th.

Any thoughts or volunteers?

**Comment by stuartmscott** [comment]
2.0 seems more realistic and sensible

**Comment by andydotxyz** [comment]
Can I request that we have [Set|Is] prefix ignored in the orderring so that MyVal and SetMyVal are next to each other?

**Comment by stuartmscott** [comment]
On a separate, but related topic, tests should also be consistent.

A feature XYZ should have all public APIs checked by test cases located in a separate file and package. Some internal behaviour may also need to be tested, these tests should be in a separate file with the same package:
- XYZ.go (package xyz) - main feature being tested
- XYZ_test.go (package xyz_test) - main tests
- XYZ_internal_test.go (package xyz) - internal tests

Furthermore, test names should start with "TestXYZ", followed by use-case-specific names separated by underscores, ie: "TestXYZ_foo_bar"

**Comment by toaster** [comment]
IMO, we need some kind of document for this.
The document should contain the current consent and it should be modifiable with version management.
So either a text/markdown file in the repo or a Wiki page.

**Comment by toaster** [comment]
These rules should apply to _all_ files (maybe with additional specific rules like for tests).

**Comment by toaster** [comment]
From #1355 

I propose to put package exported functions that are not constructors before all other stuff (right behind the import statement).

**Comment by andydotxyz** [comment]
If we’re adding package functions then we should also specify for package private functions. I don’t think they seem as well suited to being at the top?

**Comment by andydotxyz** [comment]
I think this is now all captured at: https://github.com/fyne-io/fyne/wiki/Contributing

**Comment by stuartmscott** [comment]
Nice work Andy! This can be closed now and future additions/edits should be made to that wiki. Tho I may still use "#827" as a shorthand for "As per the contribution guidelines" :)
