### ISSUE TITLE
Rendering issues on a window running on a separate goroutine when resizing

### ISSUE THREAD

**Issue by parkerqueen** [fyne-io/fyne#829]
### Describe the bug:
If I try to resize a window with a container having multiple canvas objects, many of the container's canvas objects are not rendered. The window is using a Grid Layout of 50 Columns.

If I instead use a layout with a smaller number of columns (say 10), it doesn't break as often (only if you wildly resize the window).

Additionally, this only happens when I run the window as a goroutine `go w.ShowAndRun()`. If I dont, it works perfectly fine.

Lastly, sometimes nothing would render from the get go. Just a blank screen would appear. (See the last screenshot). Again, unlikely to happen in a grid with 10 columns but very likely in case of 50 columns.

### To Reproduce:
Look at the code below.

### Screenshots:
Before:
![f](https://user-images.githubusercontent.com/25511740/78787756-449e5700-79c4-11ea-9c2f-7d90909bb63c.png)

After Resizing:
![f2](https://user-images.githubusercontent.com/25511740/78787776-4c5dfb80-79c4-11ea-8c10-f3150f7e53cd.png)

The Blank Screen:
![f3](https://user-images.githubusercontent.com/25511740/78788504-592f1f00-79c5-11ea-8e1f-653dc4212d70.png)

### Example code:
```go
package main

import (
	"image/color"
	"time"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
)

var guiApp fyne.App
var guiWin fyne.Window

func main() {
	guiApp = app.New()

	guiWin = guiApp.NewWindow("A Window")
	guiWin.Resize(fyne.Size{Width: 1200, Height: 800})

	container := fyne.NewContainerWithLayout(layout.NewGridLayout(50))
	for r := uint(0); r < 50; r++ {
		for c := uint(0); c < 50; c++ {
			container.AddObject(canvas.NewRectangle(color.White))
		}
	}

	guiWin.SetContent(container)
	go guiWin.ShowAndRun()
	time.Sleep(50 * time.Second)
}
```

### Device (please complete the following information):
 - OS: Pop!_OS (A wrapper around Ubuntu honestly)
 - Version: 18.04 LTS
 - Go version: 1.14.1
 - Fyne version: 1.2.3

**Comment by andydotxyz** [comment]
Sorry, but you cannot run Window.ShowAndRun() from a goroutine.
The UI drawing requires to be run in main().

**Comment by andydotxyz** [comment]
p.s. yes this "sort of works" on Linux but will crash on macOS. We probably should find a way to provide better error or logging in this situation.

**Comment by andydotxyz** [comment]
Would something like PR #833 be beneficial to clearly halt apps that are started in a way that we don't support?

**Comment by parkerqueen** [comment]
@andydotxyz 
Alright. In that case I would suggest adding information about this on the tour as that's usually the first resource people use to learn fyne.

Just to reiterate, I'd have to run everything graphics related on the main thread and all my computations/app logic on separate goroutines? What about multiple windows?

**Comment by parkerqueen** [comment]
> Would something like PR #833 be beneficial to clearly halt apps that are started in a way that we don't support?

Yes. I don't see an issue with panicking. It would help stop unsuspecting users right in their tracks.

**Comment by andydotxyz** [comment]
It should be documented yes. I tried to explain it on https://tour.fyne.io/basics/apprun.html but maybe it could be clearer.

This does not impact any of your other code - Fyne doesn’t mind what thread any of your code is run on **except** Run.

Any number of windows can be shown from main() or other goroutines, it is only ShowAndRun() or Run() that must block main(). If you want to show others from main then do so before calling the blocking call.
