### ISSUE TITLE
Layout called before Refresh

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#834]
In some cases a widget can be laid out before refresh is called, resulting in incorrect renders. This can happen if a widget is resized, as Resize(size) calls Layout(size) in BaseWidget.

After discussion with the community the consensus is to expect CreateRenderer to return a renderer that is ready to go.

Affected Widgets:
- Check
- Icon
- Radio

**Comment by andydotxyz** [comment]
This must be fixed before we can fully enforce thread safety on renderers. Otherwise the Refresh -> Layout vs Layout -> Refresh confusion will cause deadlocks.

How bad is this right now? Perhaps we should consider looking into a more complete solution in 2.0?

**Comment by stuartmscott** [comment]
On develop
