### ISSUE TITLE
Positioning does not support fine-grained accuracy for scale > 1.0

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#835]
As discussed we should find a way to support sub-point positioning so that HiDPI output is able to use full display precision through all pixels (or sub-points?).
Probably means moving from int to float64 (as it's standard and float32 requires lots of casting) in fyne.Position and fyne.Size.

I am not sure if we should change the NewSize and NewPosition constructors (as int is enough for most use-cases) - it's possible that NewPreciseSize etc could be added - but there is no hiding that the values are floats...

**Comment by charlesdaniels** [comment]
I have submitted a proposal [here](https://github.com/fyne-io/fyne/wiki/Proposal:-Use-Vectors-to-Represent-Position,-Size,-Etc.) which I think may be relevant.

**Comment by andydotxyz** [comment]
`Vector` underlying interface for common `Size` and `Position`  to simplify some of the maths as well.
As per the illustration above - but maybe interface at the top and structs implementing.

**Comment by andydotxyz** [comment]
Hi @charlesdaniels I got a version of the Vec2 in that didn't break the existing types - let me know what you think.

**Comment by charlesdaniels** [comment]
I like this approach, but why having `IsZero()` be part of the interface?

Should also add a comment indicating which value from `Get()` is intended to be the horizontal component, and which the vertical, just for clarity.

I wish that Go had interface receivers... that would make it much easier for us to provide a rich set of different helper methods in exchange for the developer just defining a simple interface.

**Comment by andydotxyz** [comment]
On `develop` branch for testing.
