### ISSUE TITLE
Duplicating appearance of an existing UI

### ISSUE THREAD

**Issue by Michael-F-Ellis** [fyne-io/fyne#841]
### Is your feature request related to a problem? Please describe:

This is actually a question about Fyne's capabilities rather than a feature request. I have an existing control system application that runs on a Raspberry Pi.  The backend logic has been ported successfully from Python to Go and the experience has been very positive in terms of performance and maintainability.

The user interface runs in a Chrome browser instance in Kiosk mode with the usual mish-mash of html, css and javascript and there's still a python intermediate layer between the backend and the communication with the user interface.

Maintenance and adding features is a headache.  I'd dearly love to have a solution consisting of a single app written entirely in Go.  

### Is it possible to construct a solution with the existing API?

That's the big question. My customer really likes the appearance of the present UI.  Making the change would be much more easily acceptable if the layout, fonts and colors can match the existing UI as closely as possible.  

The UI is not extremely sophisticated. It's mainly a series of pages similarly styled with a header containing a png logo and several icons for frequently accessed operations,  a menu bar with 4 dropdown menus, and body consisting of one or more panels with readouts and setpoint inputs.  The font sizes are optimized for an 800 x 480 touchscreen. See the attached screenshot below.

So my basic question is: Are Fyne's layouts and widgets sufficiently configurable to closely duplicate the appearance of the existing UI? In finite time, of course :-)

### Describe the solution you'd like to see:

If the answer to my question is yes, I'd appreciate links to documentation and/or examples showing how to do it.

Thanks!

![2020-04-09-144935_800x480_scrot](https://user-images.githubusercontent.com/6699301/78935602-0a43c100-7a7b-11ea-85e3-6c6cacdfbe95.png)

**Comment by andydotxyz** [comment]
Yes this is possible. Under fyne widgets is our canvas API which supports loading images, specifying custom font colour and size. And you can specify an alternative font through the theme api (see https://github.com/andydotxyz/beebui).

That said, however, our widgets are designed for a standard appearance and do not offer much customisation. Because of this you will likely have to implement many of the components yourself. Entirely possible but quite a lot of work in comparison to a standard material design GUI.

**Comment by Michael-F-Ellis** [comment]
Thanks, Andy, I appreciate the candid response.  I think it makes sense for me to take a shot at mocking up the interface to see how close I can get the available customizations. The potential benefit of having the entire app in one language is large and worth pursuing.

Is it ok to use this issue as a place to ask further questions on this topic?

**Comment by andydotxyz** [comment]
If you want to ask questions I'd recommend our #fyne channel on the gophers slack server.
Details of various support are on our website https://fyne.io/support/.

We use GitHub for tracking the project development so there are far fewer people that can help out here than on Slack.
