### ISSUE TITLE
panic on TappedSecondary on extended widgets

### ISSUE THREAD

**Issue by Cherrg** [fyne-io/fyne#844]
### Describe the bug:

i tried to extend the entry widget. May I'm doing something wrong or there is some kind of bug. In example code below the right click on the second entry field produces go panic. (My goal is to extend the password field and overwrite some listeners -> OK(focus/click next element) + ESC(delete content))

Log Message: 
```
panic: interface conversion: fyne.Canvas is nil, not *glfw.glCanvas

goroutine 34 [running]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).AbsolutePositionForObject(0xc00009f170, 0x919c60, 0xc0001b4100, 0x919c60, 0xc0001b4100)
        /$GOPATH/src/fyne.io/fyne/internal/driver/glfw/driver.go:37 +0x128
fyne.io/fyne/widget.(*Entry).TappedSecondary(0xc0001b4100, 0xc000026460)
        /$GOPATH/src/fyne.io/fyne/widget/entry.go:542 +0x2e7
fyne.io/fyne/internal/driver/glfw.(*window).mouseClicked.func5()
        /$GOPATH/src/fyne.io/fyne/internal/driver/glfw/window.go:664 +0x38
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc000164000)
        /$GOPATH/src/fyne.io/fyne/internal/driver/glfw/window.go:1030 +0x50
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow.func1
        /$GOPATH/src/fyne.io/fyne/internal/driver/glfw/window.go:1062 +0x1a0

```

### To Reproduce:
Steps to reproduce the behaviour:
1. compile example code
2. right click on first field -> open up context menu
2. right click on second field -> runtime panic
4. See error -> program crashed

### Example code:
```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)
//extend widget.Entry
type ExtendedField struct {
	*widget.Entry
}
// right click working
func NewField1() *ExtendedField {
	pf := &ExtendedField{
		Entry: &widget.Entry{}, // <--- raw Entry, working fine
	}
	pf.ExtendBaseWidget(pf)
	return pf
}
// right not click working
func NewField2() *ExtendedField {
	pf := &ExtendedField{
		Entry: widget.NewEntry(), // <--- entry by function, panic on right click
	}
	pf.ExtendBaseWidget(pf)
	return pf
}
// inside app add fields to window
func main() {
	// create app
	mainApp := app.NewWithID("my app")
	w := mainApp.NewWindow("first window")
	// create buggy input fields
	field1 := NewField1() // <-- right click working
	field1.SetPlaceHolder("Field 1")
	field2 := NewField2() // <-- right click not working7
	field2.SetPlaceHolder("Field 2")
	// set layout
	w.SetContent(widget.NewVBox(
		field1,
		field2,
	))
	// run app
	w.ShowAndRun()
}
```
-->

### Device (please complete the following information):
 - OS: Linux
 - Version: 18.04 lts
 - Go version: go1.13.7 
 - Fyne version: (current master) ed30d6786124c2c34e9d454076901df3e3830ca8

**Comment by andydotxyz** [comment]
You should not embed a pointer to a widget, but the wiget itself. And there is no need to call a constructor to the embedded widget as it will be built as part of the type when done correctly.

```go
type ExtendedField struct {
	widget.Entry
}

func NewField() *ExtendedField {
	pf := &ExtendedField{}
	pf.ExtendBaseWidget(pf)
	return pf
}
```

**Comment by Cherrg** [comment]
thanks for your help, I removed, the pointer. So 
```
pf := &ExtendedField{
	Entry: widget.Entry{}, // <--- raw Entry
}
```
should be equal to 
```
pf := &ExtendedField{}
```
like you said -> it is part of the type.

---
What will I do if i need a constructor on the entry field. E.g. when I try to extend the password field. 
```
pf := &ExtendedField{
	Entry: 	*widget.NewPasswordEntry()
}
```
This will be broken. That was my reason for the pointer to the widget.

```
type ExtendedField struct {
	*widget.Entry
}
func NewField() *ExtendedField {
	pf := &ExtendedField{
		Entry: 	widget.NewPasswordEntry(),
	}
	pf.ExtendBaseWidget(pf)
	return pf
}
```
This will produce a working passwordEntry,  with exception of the right click. (same error as above)
To shorten the code i replaced the password part with the normal entry widget

**Comment by andydotxyz** [comment]
```
pf := &ExtendedField{}
pf.Password = true
```

**Comment by andydotxyz** [comment]
In the future the NewPasswordEntry() will return a *PasswordEntry but until then the answer above is correct.
