### ISSUE TITLE
Disable maximize button in window frame when FixedSize = true

### ISSUE THREAD

**Issue by doansson** [fyne-io/fyne#853]
### Is your feature request related to a problem? Please describe:
Right now when a window is SetFixedSize(true), the maximize button in the window frame is still enabled. So the user expect he can maximize the window, but since FixedSize = true, the window just snap in the top left of the screen.
**OS:** Windows 10
**fyne version:** 1.2.4
**Go version:** 1.14.2

### Describe the solution you'd like to see:
It would be great if when the window is FixedSize = true, the maximize button would be disabled or even removed.

**Comment by Jacalz** [comment]
There is a reason that the issue template contains the fields that it has, so please don’t just remove them without filling them in. It just makes it much harder and takes longer to get help if you do this.

Looking at your problem then, this looks like a bug as I know that I have seen this working many times before. On what platform are you seeing this and what fyne version are you using?

**Comment by doansson** [comment]
Sorry about the template. I added the OS in the first message.
I can try to test with X11 if it is also the case.

**Comment by okratitan** [comment]
I'll have to look at the code. There is probably some window type hint we aren't setting that os/window managers would use when drawing decorations. In Fynedesk we handle this case by not showing the maximize button if the window Max size is less than the screen size. But is likely that we need to flag the window as a dialog window or such if it is fixed size so that OS's that use win types like that can adjust.

**Comment by andydotxyz** [comment]
Works on Linux as far as I can tell, so this is a mac/windows ticket now

**Comment by andydotxyz** [comment]
We can correct this on first-show, but after that changing the value will not adjust the window borders, this is a requirement of some desktops. Seems reasonable though?

**Comment by andydotxyz** [comment]
This is fixed on `develop` branch for testing. If you set fixedSize before showing the window then the OS will get the window hints correct.
