### ISSUE TITLE
Unable to install fyne_demo

### ISSUE THREAD

**Issue by heliomcp** [fyne-io/fyne#861]
### Describe the bug:
**Error trying to install fyne_demo** 

### To Reproduce:
```bash
**MSYS Prompt /c/teste**
$ go get fyne.io/fyne

**MSYS Prompt /c/teste**
$ go get fyne.io/fyne/cmd/fyne_demo
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
```

### Screenshots:
n/a

### Example code:
n/a

### Device (please complete the following information):
 - OS: Windows
 - Version: 10
 - Go version: go1.14.2 windows/amd64
 - Fyne version: latest

**Comment by andydotxyz** [comment]
It looks like you have a 32bit mingw install on a 64 bit system.
Your entire toolchain will have to be 64bit for this to work.

**Comment by heliomcp** [comment]
@andydotxyz thank you for you response.

I have installed 32 and 64 bits but now I uninstalled all gcc packages from my msys environment and installed [TDM-GCC-64](https://jmeubank.github.io/tdm-gcc/download/).

Now I have this error:
```bash
$ go get fyne.io/fyne/cmd/fyne_demo/
# fyne.io/fyne/cmd/fyne_demo
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o: in function `glfwSwapBuffers':
C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:609: undefined reference to `__assert_func'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o: in function `glfwExtensionSupported':
C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:642: undefined reference to `__assert_func'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o: in function `glfwGetProcAddress':
C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:707: undefined reference to `__assert_func'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o: in function `glfwGetInputMode':
C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:153: undefined reference to `__assert_func'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o: in function `glfwSetInputMode':
C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:174: undefined reference to `__assert_func'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\HMCPER~1\AppData\Local\Temp\go-link-604648911\000004.o:C:\Users\hmcpereira\go\src\fyne.io\fyne\vendor\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:262: more undefined references to `__assert_func' follow
collect2.exe: error: ld returned 1 exit status
```

Am i missing something?

**Comment by andydotxyz** [comment]
It looks like you have hit something strange that was reported elsewhere go-gl/glfw#202 - I wonder if the hints there might help. Perhaps there is a mis-match with the Go  install?

**Comment by heliomcp** [comment]
I have read the post and I don't think I have 32bits vs 64bits diferences. I have only installed 64 bit  versions.  `go get -u github.com/go-gl/glfw/v3.3/glfw` was installed ok.

GO 64 bits was installed without problems and as you can see below gcc is 64 bits to.

![image](https://user-images.githubusercontent.com/9692595/79378317-03beb900-7f55-11ea-804a-e4258c51e1f6.png)

If I understand correctly TDM-GCC can be 32 or 64 bits:
- 32 bits = gcc/i686-w64-mingw32
- 64 bits = gcc/x86_64-w64-mingw32 [**mine**]

```bash
C:\Users\hmcp\teste>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-git-9.2.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --enable-large-address-aware --disable-rpath --disable-symvers --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 9.2.0 (tdm64-1)

C:\Users\hmcp\teste>go version
go version go1.14.2 windows/amd64
```

**Comment by heliomcp** [comment]
## problem solved

In the `go env` my default installation have `set GO111MODULE=`. After activate **go mod** with the command `set GO111MODULE=on` all runs ok.

```bash
C:\Users\hmcp\teste>go get fyne.io/fyne/cmd/fyne_demo
go: downloading fyne.io/fyne v1.2.4
go: found fyne.io/fyne/cmd/fyne_demo in fyne.io/fyne v1.2.4
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: downloading golang.org/x/image v0.0.0-20190802002840-cff245a6509b
go: downloading github.com/fyne-io/mobile v0.0.1
go: downloading github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff
go: downloading github.com/srwiley/oksvg v0.0.0-20200311192757-870daf9aa564
go: downloading github.com/srwiley/rasterx v0.0.0-20181219215540-696f7edb7a7e
go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
go: downloading github.com/go-gl/glfw v0.0.0-20181213070059-819e8ce5125f
go: downloading golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading golang.org/x/text v0.3.0
```

@andydotxyz thank you for your help.

**Comment by jzyzxx** [comment]
> ## problem solved
> In the `go env` my default installation have `set GO111MODULE=`. After activate **go mod** with the command `set GO111MODULE=on` all runs ok.
> 
> ```shell
> C:\Users\hmcp\teste>go get fyne.io/fyne/cmd/fyne_demo
> go: downloading fyne.io/fyne v1.2.4
> go: found fyne.io/fyne/cmd/fyne_demo in fyne.io/fyne v1.2.4
> go: downloading github.com/fsnotify/fsnotify v1.4.7
> go: downloading github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
> go: downloading golang.org/x/image v0.0.0-20190802002840-cff245a6509b
> go: downloading github.com/fyne-io/mobile v0.0.1
> go: downloading github.com/goki/freetype v0.0.0-20181231101311-fa8a33aabaff
> go: downloading github.com/srwiley/oksvg v0.0.0-20200311192757-870daf9aa564
> go: downloading github.com/srwiley/rasterx v0.0.0-20181219215540-696f7edb7a7e
> go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
> go: downloading github.com/go-gl/glfw v0.0.0-20181213070059-819e8ce5125f
> go: downloading golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb
> go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
> go: downloading golang.org/x/text v0.3.0
> ```
> 
> @andydotxyz thank you for your help.
I have met the same problem but i have set GO111MODULE=on but nothing changed

**Comment by andydotxyz** [comment]
> I have met the same problem but i have set GO111MODULE=on but nothing changed

The same error can be caused by incorrect GCC installation - through a mismatch of 32 vs 64bit or by not having the required mingw_w64 toolchain available

**Comment by jzyzxx** [comment]
Thanks for your response,there is my gcc env:`Using built-in specs.
COLLECT_GCC=C:\TDM-GCC-64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-git-9.2.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --enable-large-address-aware --disable-rpath --disable-symvers --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 9.2.0 (tdm64-1)`
And there is my go env:
`set GO111MODULE=on
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOCACHE=C:\Users\DELL\AppData\Local\go-build
set GOENV=C:\Users\DELL\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=c:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\gopath\src\fyne.io\fyne\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\DELL\AppData\Local\Temp\go-build019881378=/tmp/go-build -gno-record-gcc-switches`
I am  quiet sure it  match.

**Comment by andydotxyz** [comment]
Are you sure that the TDB gcc is what is run in the path? It looks like it might not be...
Check what you are building for with:
```
$ which gcc
$ gcc -dumpmachine
```

**Comment by xfye** [comment]
My solution:

1. pacman -R gcc
2. pacman -S mingw-w64-x86_64-gcc
3. export PATH=$PATH:/mingw64/bin/
