### ISSUE TITLE
Applications appear to large on Linux

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#862]
Hi,
First, thanks for your all your work, i like it :)
I just noticed that the scaling described here 
https://github.com/fyne-io/fyne/wiki/Scaling-Revisited

may not be the best practice, as I'm having trouble using my apps on Linux, they are so big and sometimes does not fit on the screen; while on Windows works just fine

Is it possible to disable the feature that adjust the scaling factor for Linux and keep it just like Windows/MacOS ? (or even better control the scaling factor from within the app itself)

**Comment by Jacalz** [comment]
I totally agree with you on this. We have talked a lot about this in the past and this seems to be something that really needs to be fixed. The default size seems fine on my 1080p 24" display but on my laptop screen with 1080p and 15", the applications are just huge. We need a better way of calculating the correct application sizes or moving over to auto again. It is not a wise decision to force every user to change their scale if they want to use the application. The application should just work out of the box with no tinkering required.

**Comment by andydotxyz** [comment]
You can control the scaling factor, there is an app `fyne_settings` that can do this, or you could set an environment variable, `FYNE_SCALE` to something like 0.8.

The reason that Windows and macOS work differently is that they have a global system setting for how the screen should be scaled. This is what fyne_settings attempts to replicate on Linux.

**Comment by andydotxyz** [comment]
FYI @Jacalz this is "auto" :-p

**Comment by andydotxyz** [comment]
The calculations are based on a 96DPI standard which is the default for most systems.
On a laptop it's common to prefer 144DPI, but we have not found a way to articulate "this is a laptop" screen. Additionally it depends on wheter this is "i'm using a laptop" where 144DPI would be good, vs "my laptop is docked next to my screen"where 96DPI works better.

If you can suggest a good solution to this we would welcome it but so far nothing has become obvious.

**Comment by Jacalz** [comment]
> FYI @Jacalz this is "auto" :-p

Sorry. I thought that you said that we switched off auto in 1.2.0 in one of the discussions that we had. Just decided that I should give my views on the issues as I have been experiencing this as well.

**Comment by andydotxyz** [comment]
"auto" is used on Linux as the system scale.
The user setting (through settings or environment) then multiply the system scale.
This means that 0.8 is smaller text and 1.5 is 50% bigger.
It is a change to pre-1.2 and I probably did a bad job explaining the difference.

Also (I now realised, sorry):
In 1.2.0 - 1.2.2 I think we had it switched off, then this new version was switched back on.

**Comment by andydotxyz** [comment]
I wasn't sure if this issue could be closed or not. It feels like there is not a bug here, but that possibly something like docs or config tools need improved.
Thoughts?

**Comment by s77rt** [comment]
It's just a bad scaling factor, not really a bug, but the calculation should be improved

**Comment by andydotxyz** [comment]
I don’t quite understand sorry. How can the calculation be improved if the issue seems to be that 96dpi standard is larger than you would prefer? Does setting your user configuration to 0.67 give the result that you prefer?

Unless I have misunderstood - perhaps you can provide more information about how bad the situation is? I don’t think there is info about screen size, resolution or an indication of how large an application really is?

**Comment by s77rt** [comment]
I'm closing this for now.
Just for future ref, the issue to be exact is that the "auto" option does not return a proper value for laptops, and i end up using another value than "auto"

**Comment by andydotxyz** [comment]
Can you please help by saying how it’s not a “proper value”? The algorithm is designed to show windows at a consistent size. This is modelled on 96 DPI and apps will be the same size irrespective of the screen they are on. Is that not what you were getting?

**Comment by s77rt** [comment]
the app shows bigger than expected, i had to set the value to 0.80 (or 0.75) to get a nice view.
using auto the app does not even fit in the screen.

**Comment by andydotxyz** [comment]
Sorry to be a pest but it would be helpful to have more details. I understand if you don't want to though given the state of this issue now being closed.

* What is the screen size & resolution?
* Which app are you running (or what is it's Fyne window dimension)?
* How does the window look (scale-wise) if you move it to an external monitor?

A scale of 0.67 puts things back to where I had them originally (144DPI baseline) I am working on a theory that Linux users are more likely to want smaller fonts than Windows / macOS and perhaps we should have respected that?

**Comment by s77rt** [comment]
@andydotxyz 
Sorry for the late reply,
- 15.6" 1920x1080
- about 500x800 
- Not tested

**Comment by andydotxyz** [comment]
OK, I am re-opening this to capture more information to inform a possible decision to changing the default DPI.

If the calulations are working correctly then the window will appear the same size on any of your screens laptop or otherwise, Let's use fyne_demo as a test case.

Using v1.2.4:
FYNE_SCALE=1 (or unset) should be approx 177x130mm - I have tested this on laptop, desktop, HiDPI and normal.
This size is emulating 96DPI.

The first question is, do you get the same size. The second question is should the default be smaller.
 
To emulate 120DPI baseline (half way between the old 144 and the new 96) try this:
FYNE_SCALE=0.8 then fyne_demo should then measure 142x105mm.
Again, let me know if you get the same size, and whether you feel this is a better default.

Thanks for your time on this @s77rt @Jacalz :)

**Comment by andydotxyz** [comment]
interestingly it seems that macOS moved a couple of years ago from the default being around 96dpi to 122 (depending on screen) with 2 steps "larger text" and 2 "more space" roughly 72 to 144 dpi

**Comment by s77rt** [comment]
Using v1.2.4
FYNE_SCALE=1.00 (screen scale: 1.50) => 180x118mm
FYNE_SCALE=0.80 (screen scale: 1.20) => 144x96mm
FYNE_SCALE=0.75 (screen scale: 1.10) => 132x88mm

personally i feel it should be between 0.75 and 0.80

**Comment by andydotxyz** [comment]
Thanks @s77rt it seems like the algoritm is working as expected at your end.
It sounds like a vote toward moving Linux users to a 120DPI baseline as that would be around the 0.8 now. I'll bring it up on our community call on Wednesday and see if we can get agreement.

**Comment by Jacalz** [comment]
I have now done more testing from my side. The results and opinions that I have after this are shown below:

### 13 inch 1080p laptop screen:
 Fyne_demo is reporting a scale of 1.80 on my 13 inch Linux laptop with a 1080p screen, which feels huge. When playing around with different values on `FYNE_SCALE`, I would say that something between 0.70 and 0.80 seems to fit my screen the best and thus be the same size as everything else on the computer, but it should definitely not be getting a 1.80 scale by default, in my opinion.

Some window sizes on that laptop:
 - **Default:**: fyne_demo reports a scale of 1.80 -> 180x115mm
 - **FYNE_SCALE=0.80**: fyne_demo reports a scale of 1.50 -> 150x95mm

![big-fyne-windows](https://user-images.githubusercontent.com/25466657/79775810-13fbdd00-8335-11ea-83b3-e2436c2314f4.png)

### 24 inch 1080p desktop screen:
I do however still find 1.0 scale on a 24" screen to be perfect. No bigger and no smaller. Having a 0.80 make everything super tiny and very blurry (do note that image compression makes everything blurry in the screenshot). It might be the case that smaller screen (say for example 17inch and down) should have a bigger DPI like 120DPI and bigger screen should stick to the 96DPI standard that we have today. That is what I propose for a change in window size behaviour.

![fyne-scale-0 80-24](https://user-images.githubusercontent.com/25466657/79775991-59b8a580-8335-11ea-9863-4bc367739246.png)

### 15 inch 1080p laptop screen:
Now on to the last testing and the one done on my 15 inch laptop. The default scale seems to be 1.50 which also feels too big and out of proportions compared to everything else on the screen. below are the values reported with the different scale factors. Here it seems that setting FYNE_SCALE to 0.80 gives the best result on the 15 inch screen and is the most in line with all other applications.

 - **Default:** fyne_demo reports a scale of 1.50 -> 180x115mm
 - **FYNE_SCALE=0.80**: fyne_demo reports a scale of 1.20 -> 140x85mm

### Summary:

My opinion on the matter is that laptop DPI levels (or smaller screens in general) should be increased to go from 96DPI to 120DPI and thus be more in size comparison with the rest of the applications on screen. Applications on larger screen like my 24 inch desktop screen looks fine the way they are with 96DPI and I think they can be left as is.

**Comment by andydotxyz** [comment]
**Proposal**
We move to a 120DPI baseline for auto scaling (only used by Linux) from 96DPI.
This auto scale will not go below 1.0

User scale will continue to multiply the system scale so users can choose larger or smaller scaling.

I also propose that the fyne_settings app be updated to provide a simpler scale picker - 2 sizes below and 2 sizes above the baseline.

Some users may want an advanced scale option - but we could suggest they edit the config file directly. (or provide an alternative UI under an advanced option?)

**Comment by Jacalz** [comment]
Sounds good to me. I think having an advanced option in `fyne_settings` would be good along with the simplified scale settings mentioned above :)

**Comment by toaster** [comment]
Trying to have a  window the same physical size on all screens is misguided IMO.
The eye-to-display distance is normally much less for smaller laptop screens than for large desktop screens. For mobile devices it is even less. That’s why the same window should be smaller (physically) on a laptop display than on a desktop display.
I think we should think about a solution which takes the display size (not the resolution) into account to guess what kind of display (desktop, laptop, tablet, phone) it is and adjust the scale computation to a specific baseline for this kind of display.

**Comment by Bluebugs** [comment]
@toaster absolutely and it also depends on context. If your laptop are on your lap on the couch, it is likely closer to your eyes than when it is on your desk used as a secondary screen. Also if a mobile is connected to a TV, you have a very different scale ratio expectation from users. Handling scale automatically can become quite the rabbit hole to explore!

It would be nice to have the scale factor of a screen remember the context it was set in (which other screen are being connected as a first approximation) and use this information to estimate at first the reading distance and pixel ratio the user see from where he is (pixel per degree angle or something like that).

**Comment by Jacalz** [comment]
I also agree with @toaster with this. It is basically what I have been trying to say all along, just rephrased in better context. The application should scale in a way that makes sure that it is perceived to be the same size as every other application in the system. This is generally what my elaborate testing above showed and how I tried to get it to fit in with the other apps. As I have stated in the past, a user should not need to change window scaling to make it have the same size as other apps on the system, it should be done automatically adjusted based on screen size.

**Comment by andydotxyz** [comment]
I think that @Bluebugs has done a decent job of explaining that the presence of a 15" screen does not mean you have it on your lap. Let's compare what some other systems do:

*) Gnome: find a "HiDPI" threshold and use 200% above it or 100% below it.
*) Windows: defaults like above but additionally you can choose (per screen - not per context) 100%, 150%, 200% and others
*) macOS: uses 200% for "retina" and 100% for all others. The user is then offered 2 smaller and 2 larger options in settings (if it thinks your monitor "supports it".

This does not include mobile, as there are "known densities" documented for devices and/or OS patterns that aim for a consistent text size across devices.

I would absolutely love to agree with 

>a user should not need to change window scaling to make it have the same size as other apps on the system,

but there is no "system configuration" centrally on Linux - if there was this would not be a conversation at all. We are hamstrung by Gnome's inability to use floating point scales (on X at least) and I do not think we should stick to lowest common denomenator when it comes to platform support.

Gnome and KDE and EFL all use different configurations for application sizes. Some based on screen size, some on pixel density, some on user setting - we have to pick a design that works across all.
The design above is what I think best accomplashes this.

**Comment by toaster** [comment]
Regarding MacOS: As their simple strategy works very well for the small range of displays manufactured by Apple, it is totally crap (and I mean it!) for displays outside these specifications.
We have 24" (or 23" I don’t remember) with WQHD (2560x1440) and the scaling is totally broken on MacOS. It isn’t recognized as HiDPI but the LowDPI mode makes everything tiny on the screens. Totally unusable.

So, don’t go with such a simple approach as Apple does.

For Windows: I’m not sure (don’t using Windows on recent hardware) but they don’t even get it totally right on their own Hardware. My wife has a SurfacePad (maybe I got this wrong) with 3000x2000 (14" I think) and some elements seem to be too small while others are okay. Using 125% scale doesn’t really make it better.

**Comment by andydotxyz** [comment]
I agree that the Apple approach doesn't really cut it. But I also think that none of them do.
That's why I think that something different is probably required.

I'm not sure how we went from everyone who was reporting the issue or would be affected by it being in agreement to this back-to-square-one position on something that has been in Fyne design from the beginning...

**Comment by andydotxyz** [comment]
As a reminder here is the previous discussion about the scaling that was put into the latter 1.2 releases. https://github.com/fyne-io/fyne/wiki/Scaling-Revisited

This update to 120 is following that previous document but with a different baseline DPI (which was not specified).

**Comment by andydotxyz** [comment]
I am re-reading this again to see how I can get it moving along and I think that the line:

> The application should scale in a way that makes sure that it is perceived to be the same size as every other application in the system

Is something I actually don't agree with. In Gnome X11 the windows will be either 100% or 200% - so in some lucky cases it looks great and in many others it is too small or too big. I don't think we should strive to match this behaviour sorry.
If the desktops were doing a great job of scaling on the hardware appropriately then yes we probably should be matching the desired behaviour.

Feel free to try and convince me otherwise, but I would like to wrap this up one way or another so we can move forward.

My current thoughts are that the change I have recommended is made and we can then raise tickets for specific instances where it does not do the right thing. i.e. a "Gnome compatibility mode" flag or "match my XFCE app size" feature request?...

**Comment by andydotxyz** [comment]
I've been exploring windows a little bit more and can add that in the latest Windows 10 the "scale" is detected, based on DPI, to the closest 25%.
When dragging windows between screens it will adjust the window scale as the centre of the window moves to the new screen.
Basically exactly the same as my proposal for Linux with the exception that we round to 10% if scale instead of 25%...

**Comment by ohir** [comment]
> The application should scale in a way that makes sure that it is perceived to be the same size as every other application in the system

So all fyne based apps should have a well-known "fyne-config" location. There the first fyne-based app that run would write scale factor user deemed as useful for her. Every next launch this setting can be applied to this and other apps. It should be a file-based config as, simplest solution via FYNE_SCALE_FACTOR environment var is way too demanding on the casual user.

**Comment by andydotxyz** [comment]
On linux this location is ~/.config/fyne/settings.json, this is where user preference is stored.
You can edit the file directly or run fyne_settings app.

**Comment by andydotxyz** [comment]
For clarity of what is proposed at this time:

> My current thoughts are that we make the change to 120DPI baseline (similar to 0.8 user scale now) and we can then raise tickets for specific instances where it does not do the right thing. i.e. a "Gnome compatibility mode" flag or "match my XFCE app size" feature request?...

**Comment by mattboll** [comment]
I totally agree that 0.8 scale is pretty good, it is what I set from the beginning in fynedesk, and it seems that the current algorithm is pretty appropriate as it works as expected on a high DPI laptop and a standard DPI external screen, so from my point of view it's a go for the 120DPI baseline change

**Comment by andydotxyz** [comment]
On develop for testing for the 1.3 release
