### ISSUE TITLE
SystemScale is too big if FYNE_SCALE is not set

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#865]
### Describe the bug:
SystemScale is too big if FYNE_SCALE is not set

### To Reproduce:
Steps to reproduce the behaviour:

1. Run fyne_demo
2. The returned SystemScale is too big (7.40 in my case)
3. Set FYNE_SCALE `export FYNE_SCALE=1` then run fyne_demo
4. The returned SystemScale is "[acceptable?](https://github.com/fyne-io/fyne/issues/862)"
5. Set FYNE_SCALE `export FYNE_SCALE="auto"` then run fyne_demo
6. Same as (4) that means the results on (2) are not related to the auto scaling factor
7. Unset FYNE_SCALE `unset FYNE_SCALE` then run fyne_demo
8. Back to (2) issue confirmed to happen only when FYNE_SCALE is not set

### Device:
 - OS: Linux
 - Go version: 1.13
 - Fyne version: 1.2.4

This only happens on 1.2.4 which i just upgraded to.

**Comment by s77rt** [comment]
Looks like just a messy configuration was being used.
Run `fyne_settings` and set scaling to auto, now things are back to normal, yet not sure what caused the change on the configs.
Closing this for now.

**Comment by andydotxyz** [comment]
Yes there was a small chance that some users could experience a strange multiplying of scale value when upgrading to 1.2.4. Resetting config, or just changing it to what you would like, will fix the issue.
Sorry for the inconvenience.
