### ISSUE TITLE
[Example Needed] Custom Settings

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#868]
Hi,
Can you attach an example of how to make an app use a [custom settings](https://github.com/fyne-io/fyne/blob/25c18bb42b20ff622a36802c92fc12319d5442d8/app/settings.go#L93-L104) file?

**Comment by andydotxyz** [comment]
Sorry there is no facility to use a custom settings file - that is global configuration managed by the toolkit.
Perhaps the preferences API would be what you are looking for? You can set and get any user specified values that way.
https://fyne.io/develop/tutorials/preferences-api

**Comment by s77rt** [comment]
@andydotxyz 
The preferences are good, but not enough
I need to set the theme and the scale factor per app

the preferences would be useful only if there is a way to override the scale factor from inside the app, just like we can do for the theme (using Settings().SetTheme())

so maybe add a Settings.SetScale() too ?

**Comment by andydotxyz** [comment]
Overriding scale factor per-app is not supported.
Perhaps you can provide a use-case for this behaviour so we can evaluate?
The problem we are trying to avoid is that no matter what a user will not get a consistent experience with your app if you do that.

**Comment by s77rt** [comment]
no specific use case, i just think that the scale factor is a per app thing.
Some apps may be larger than others, so setting a scale on one app without touching the others would be nice

**Comment by andydotxyz** [comment]
Consider the global scale like your monitor scale setting. If you want bigger fonts in all your apps then you set it to a higher number.
Having font sizes be different in different applciations is not something we want to support in the main API.

**Comment by andydotxyz** [comment]
Unless you find a use-case that requires such customisation this ticket is closed as wont-fix.
