### ISSUE TITLE
fyne-cross and fyne package

### ISSUE THREAD

**Issue by mehrdad-dev** [fyne-io/fyne#878]
### Describe the bug:
Hi
I get fyne-cross with go get but show this error and can't build this:

`go get github.com/lucor/fyne-cross/cmd/fyne-cross`
error:
```
# github.com/lucor/fyne-cross/internal/builder
go/src/github.com/lucor/fyne-cross/internal/builder/builder.go:118:18: cmd.String undefined (type *exec.Cmd has no field or method String)
```

And also when i want to use fyne package:

`go get fyne.io/fyne/cmd/fyne`
and when i eant build this:
```
# command-line-arguments
./main.go:15:11: undefined: command
```

so, i can't build my project because cmd/fyne or fyne-cross can't build.

### Device (please complete the following information):
 - OS: Mint 19.3
 - Go version: go1.12.9 linux/amd64
 - Fyne version: 1.2.4

**Comment by lucor** [comment]
Hi @mehrdad-dev 

fyne-cross requires go >= 1.13, just updated the README to reflect that. Thanks for the report.

With regard to fyne, I'm sorry but it is not clear to me if you are getting the error with `go get fyne.io/fyne/cmd/fyne` or trying to complile your application using the fyne cli.
Could you please report the steps you did so we can reproduce ?
Thanks

**Comment by lucor** [comment]
Oh ok, maybe I'm got it. 
Are you by any chance compiling the fyne command from the code under GOPATH ?
Like:
```
$ cd $GOPATH/src/fyne.io/fyne/cmd/fyne
$ go build main.go
# command-line-arguments
./main.go:15:11: undefined: command
```
If so, this is not needed since the `go get` command builds and install it for you under `$GOPATH/bin`

If for any reason you'd like to compile the fyne command yourself just run ```go build .``` instead.

**Comment by andydotxyz** [comment]
If you want to build that package locally (which you can do) you would need to specify "." (the package) rather than "main.go" (a single file) as it needs all the files to build:

```
$ cd $GOPATH/src/fyne.io/fyne/cmd/fyne
$ go build .
```

But like @lucor says the go-get command will have installed it.

**Comment by mehrdad-dev** [comment]
thank you @lucor and  @andydotxyz.
my problem fixed.

**what is my problem? :**
i can't build fyne and fyne-cross for packaging and cross compiling.

**and solution:**
**for fyne-cross**:
 i just upgrde go version from 1.12 to 1.14 and then try to build it with this command in fyne-cross directory:
`go build .`
and then copy executable file in /usr/local/bin.
And then it was fixed.

**for fyne cli packaging:**
just run this:  `go build .`
and then copy executable file in /usr/local/bin.


thank you very much for help.

**Comment by andydotxyz** [comment]
The copy to /usr/local/bin should not be needed, just run ‘go install’ and then check $GOPATH/bin is in your PATH.
