### ISSUE TITLE
fyne-cross keep command window

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#880]
Hi,
building an app with `go build` build an app (gui) + a command window
while using fyne-cross `fyne-cross --targets=windows/amd64` prevents the command window from being shown

can you add an option to control that so fyne-cross can keep the command window ?

**Comment by lucor** [comment]
@s77rt tracked in lucor/fyne-cross/issues/57

**Comment by s77rt** [comment]
Oops my bad, thanks for opening the issue in the right place :)

(unrelated to this issue: kindly refer to https://github.com/fyne-io/fyne/pull/876#partial-pull-merging)

**Comment by andydotxyz** [comment]
Sorry, refer to it why?

**Comment by s77rt** [comment]
@andydotxyz 
"At least 1 approving review is required by reviewers with write access."
