### ISSUE TITLE
save the files a library with packaging

### ISSUE THREAD

**Issue by mehrdad-dev** [fyne-io/fyne#881]
Hi.
i write a piano and violin app with fyne.
and i use this lib for piano and violin sounds in go:
`https://github.com/dbatbold/beep`

this lib use a .zip file for play sounds.
that this sound files in this dir : `/home/{username}/.beep/voices/`

and then ...
when i create executable file for linux or windows and run this file,
Instead of play correct sounds, play notes with system sounds.
this is happened in other systems, in my system it's ok.

how to when i packaging my app save this sounds by packaging?

thanks.

### Device:
 - OS: Linux mint 19.3
 - Go version: 1.14
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment]
The normal way to embed resources is https://fyne.io/develop/tutorials/bundle. The loaded resource can be parsed as a zip file at runtime using a []byte reader I expect.

Other options exist like https://github.com/alecthomas/gobundle
