### ISSUE TITLE
Building application with fine for windows x64 from a headless debian

### ISSUE THREAD

**Issue by nfoerster** [fyne-io/fyne#883]
My host is a windows system x64 and I have to build a windows GUI. However, I develop in a vagrant/debian headless system and I try to compile the demo application for windows from this guest system. Unfortunatelly I get problems compiling the openGL library:
```
vagrant@debian-10:~/test/cmd$ env GOOS=windows GOARCH=amd64 go build
build github.com/go-gl/gl/v3.2-core/gl: cannot load github.com/go-gl/gl/v3.2-core/gl: no Go source files
```

If I build native the application in debian with `go build`, no problems occur during the build, however I can't run it because I'm on a headless system.

Do you know any workarounds to get the compilation for windows running?

**Comment by andydotxyz** [comment]
To cross compile you will have to add CGO_ENABLED=1 and also ensure you have a windows toolchain installed. You might find hints about cross compiling at https://fyne.io/develop/cross-compiling

**Comment by andydotxyz** [comment]
Is there anything more we can do to help resolve your issue @nfoerster ?

**Comment by nfoerster** [comment]
No sorry, your answer solved my issue!
