### ISSUE TITLE
Change button size

### ISSUE THREAD

**Issue by mehrdad-dev** [fyne-io/fyne#884]
I want create a row of button with specific high and width,
but when i want change button size with this code, is not work:
```
func makeKeyboardTab() fyne.Widget {
	list := widget.NewHBox()

	for i := 1; i <= 8; i++ {
		index := i
		button := widget.NewButton(fmt.Sprintf("Button %d", index), func() {
			fmt.Println("Tapped", index)
		})
		button.Resize(fyne.NewSize(5, 10))
		list.Append(button)
	}
	return widget.NewVBox(
		widget.NewLabelWithStyle("\nEnter notes from keyboard", fyne.TextAlignCenter, fyne.TextStyle{Bold: true}),
		list,
	)
}
```

function makeKeyboardTab  in :
```
func HomeScreen(win fyne.Window) fyne.CanvasObject {
	return fyne.NewContainerWithLayout(layout.NewVBoxLayout(),
		widget.NewTabContainer(
			widget.NewTabItem("Notes", makeNoteTab(win)),
			widget.NewTabItem("Keyboard", makeKeyboardTab()),
		),
	)
}
```

### Device:
 - OS: linux mint 19.3
 - Go version:  1.14
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment]
The VBox is controlling the size of the items within it.
In Fyne a layout or widget will control the size of it's children. 

Can you expand more on why you want buttons to be specific sizes?

**Comment by mehrdad-dev** [comment]
I want create a row for piano keyboard.
In fact, I need 2 rows، 
 that each row:
All buttons with high and width same.

**Comment by andydotxyz** [comment]
A grid layout maybe of help https://tour.fyne.io/layout/gridlayout.html, but I imagine you’ll want to create a custom layout before long. https://fyne.io/develop/tutorials/custom-layout
