### ISSUE TITLE
Add keyboard support to buttons

### ISSUE THREAD

**Issue by tataDan** [fyne-io/fyne#885]
Buttons do not receive focus when the user presses the <Tab> key. (Presumably, they do not implement the Focusable interface).  It would be nice if they could receive focus.  Additionally, it would be nice if once a button does receive focus, the user could use the space key to invoke the button's handler.

This issue is similar to the one fixed by PR #287 that dealt with checkboxes.

**Comment by tataDan** [comment]
Post should have said "when the user presses the <Tab> key" not "when the user presses the key".

**Comment by tataDan** [comment]
`The original post should have stated "when the user presses the <Tab> key", not "when the user presses the key".`

**Comment by toaster** [comment]
I think this is done with #2263.

**Comment by andydotxyz** [comment]
Indeed good catch - this is on `develop` branch for testing before 2.1 release.
