### ISSUE TITLE
fyne package macOS missing mmacosx-version-min

### ISSUE THREAD

**Issue by andrewarrow** [fyne-io/fyne#886]
### Is your feature request related to a problem? Please describe:
My binary runs in mac but the terminal window opens and I want to distribute it with an icon and maybe a nice .dmg image disk installer.

### Is it possible to construct a solution with the existing API?
This feels like a whole other part of the fyne echo system if it doesn't already exist?

### Describe the solution you'd like to see:
A whole documented system for how to release your final fyne binary on mac, windows and linux.

<img width="216" alt="mac" src="https://user-images.githubusercontent.com/127054/79806611-ad1ef980-831d-11ea-8f3f-f8c6e186ddd7.png">

when I right click on a normal MacOS app I get "Show Package Contents" menu option and then all this inside the .app file ^

What's the process for distributing apps created with fyne to the Mac App Store?

**Comment by andrewarrow** [comment]
oh, i found https://fyne.io/develop/distribution thanks!

**Comment by andrewarrow** [comment]
Ran into a few more issues:

```
export CGO_CFLAGS=-mmacosx-version-min=10.8   
export CGO_LDFLAGS=-mmacosx-version-min=10.8
```

Had to set these when building for a target less than my mac's version.

Also a friend got:

```
dyld: Library not loaded: /usr/local/opt/portaudio/lib/libportaudio.2.dylib
```

And to fix he did `brew install portaudio` but how can I make fyne package include that dylib?

**Comment by andrewarrow** [comment]
And 1 more thing that didn't work in testing, he got message:

https://discussions.apple.com/thread/7022499

Check with the developer to make sure "foo" works with this version of OS X.

This was when he was trying to just open foo.app fyne package produced. Finally I sent him just the binary and he `chmod +x foo` and ran it from terminal and then that worked. (After brew install portaudio issue was fixed.)

**Comment by andydotxyz** [comment]
You can manually install .dylib to our app bundle after `fyne package` similar to: http://www.chilkatforum.com/questions/4235/how-to-distribute-a-dylib-with-a-mac-os-x-application

It's possible that we could somehow simplfy this process, but it's hard to think how to do this in platform agnostic manner... Please open a feature request if this is something you want to explore further

**Comment by andydotxyz** [comment]
> And 1 more thing that didn't work in testing, he got message:

I looked up that thread but could not understand how installers relate to our app packages. This should just work. Perhaps you can open a fresh issue with the error information and details of his computer?

**Comment by andydotxyz** [comment]
"fyne package" is pretty complete now, for app based distribution (not installers) and "fyne release" does the same for store upload.
Changing this to be specifically about the min-version

**Comment by andydotxyz** [comment]
Updated the min to 10.11 in PR #1612 if you'd like to test @andrewarrow

**Comment by andydotxyz** [comment]
Now on branch `release/v1.4.x` and prepping for 1.4.2
