### ISSUE TITLE
Scrollable TabContainer

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#891]
Hi,
I hope you can look into implementing a Scrollable TabContainer

Issue:
Adding many tabs make the window gets taller and taller, will make the app unusable.

Demo:
https://i.postimg.cc/TPjjJNkq/tabcontainerisnotscrollable.gif

**Comment by andydotxyz** [comment]
I'm not sure that scrolling tabs is the most intuative approach - it is common on web pages but less so on native applications. We have proposed an overflow control (like a drop-down menu or similar) instead. I hope you agree it will solve this issue?
Closing as duplicatte of #371

**Comment by s77rt** [comment]
@andydotxyz 
if you look into the demo, you will see that the tabs are used as "instances", every time the user clicks on the button "Launch hashcat!" an instance is being created and it's access is being provided by creating a new tab.
i don't see how a drop-down menu would be a solution here

**Comment by andydotxyz** [comment]
I don’t mean that you should add a menu, I mean that we intend to implement overflow using a “...” menu. Will that not work ok?

**Comment by s77rt** [comment]
Actually anything that can handle having many tabs without the window getting taller will be okay,
will that fix my issue?

**Comment by andydotxyz** [comment]
yes

**Comment by s77rt** [comment]
can you give me more details about this please ? :)

**Comment by andydotxyz** [comment]
The conversation is at #371
