### ISSUE TITLE
Support filtering of file dialog

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#893]
Probably filter by mime type - this will need to be translated to other mobile specific approaches for iOS, Android.
Provide standard filterings, but maybe the ability to pass a function for more specific filtering...

**Comment by suifengqjn** [comment]
Why does it not support selecting folders or multiple files

**Comment by andydotxyz** [comment]
Because that is a lot more complicated to do across all platforms.
We will try to add support for that in future releases. Opening a new ticket would be helpful so we can track the requirement.

**Comment by stuartmscott** [comment]
Opened #941

**Comment by andydotxyz** [comment]
In a slack conversation I posted this as a conversation piece, thought I would post it here too.

```
package main

type FileFilter interface {
	Matches(fyne.File) bool
}

type ExtensionFileFilter struct
	Extensions []string
}

func (e *ExtensionFileFilter) Matches(f fyne.File) bool {
	ext := filepath.Extension(f.URI)
	for _, childExt := range e.extensions {
		if childExt == ext {
			return true
		}
	}
	
	return false
}

type MimeFileFilter struct
	Mime string
}

func (m *MimeFileFilter) Matches(f fyne.File) bool {
	mime := mimeForURI(f.URI)
	if mime == m.mime {
		return true
	}
	
	if m.mime[:len(m.mime)-1] == "*" {
		return strings.SubString(mime, m.mime)
	}
	
	return false
}

type LocalFileFilter struct {
}

func (l *LocalFileFilter) Matches(f fyne.File) bool {
	return len(f.URI()) > 7  && f.URL()[:7] == "file://"
}
```

**Comment by stuartmscott** [comment]
I like it - it gives a lot of flexibility. The only limitation is fyne.File - you can only make a filefilter based on Name/URI, you can't for example make a filter based on the file size. However that is not a typical use case, and we can always extend fyne.File in future. I think your proposal covers most use cases well.

**Comment by andydotxyz** [comment]
A bummer just realised it will have to be URI (string) only because we moved away from fyne.File to fyne.FileReadCloser - we cannot pass them around as they are literally pointers into files.
Slightly less extensible then, but still checks the current boxes.

**Comment by steveoc64** [comment]
Could I ask why we are needing to create a fyne.File / fyne.FileReadCloser as opposed to being able to use os.File / io.Filexxxxx ?

**Comment by andydotxyz** [comment]
Look at all of the functionality on os.File - a lot of that is not possible in the cross platform  (esp mobile) environments. our FileReadCloser can be used in place of any os.ReadCloser so it's not as buig a deal as it seems.

**Comment by andydotxyz** [comment]
Good hussle, thanks @okratitan :)

This is now on develop for testing

**Comment by Niek** [comment]
I noticed `ExtensionFileFilter` is case-sensitive. This is a but annoying, because some software saves files as .e.g `.JPG` I have to duplicate each extension filter. What about making it case-insensitive? I'm talking about this line:
https://github.com/fyne-io/fyne/blob/550fbc9cf875549843aa15e975fce9a527eb9fd0/storage/filter.go#L30
