### ISSUE TITLE
Set Scroll Position for a ScrollContainer

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#894]
Hi,
Is it possible to set the scroll position of scroll container ?
(or at least scroll to the top)

#### Issue:
in the below demo, you will see that there is a search box with results below it, searching for "md5" results on a long list so i scroll down, then i decided to search for "md4" (keeping the same scroll position), the results seems empty (although there is a result at the top but you just can't see until you scroll up)
so i want to add a feature that before the search function happens, the scroll position will be set to 0 (to the top) to fix this issue.
#### DEMO:
https://i.postimg.cc/Rh0JSgty/hashcat-launcher-scrollupneeded.gif

i hope the use case is clear,

**Comment by fleshin** [comment]
Have you tried adjusting the scroll Offset after each update? 

Here is an example: https://www.reddit.com/r/everythingfyne/comments/fystp5/tip_how_to_scroll_down_your_multilineentry_upon/

**Comment by s77rt** [comment]
@fleshin 
`.Offset = fyne.NewPos(0,0)` is what i was looking for, thanks :)
