### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#896]
Hi,

Is it possible to drag and drop a file an app?

example:
a file is on the desktop and the app is open, so you want to drag that file and drop it to the app (and get's it path or name or anything?)

i hope the idea is clear :)

**Comment by andydotxyz** [comment]
This is not currently possible but we want to add it. It's a large piece of work so will not make 1.3 next month but I hope to include it in 2.0 around July.

Closing as duplicaet of #142
