### ISSUE TITLE
TabContainer add a spacer (horizontal line)

### ISSUE THREAD

**Issue by s77rt** [fyne-io/fyne#899]
Hi,
It would be nice if we can add an horizontal line to the tab container to separate between different tabs :)

**Comment by andydotxyz** [comment]
hmm, not too sure about this - can you add more information about why this design would be desirable over what exists?

**Comment by s77rt** [comment]
"desirable over what exists?"
not desirable over what exists, this won't replace anything, it would be just an added feature.
it's good for ux, to list some tabs then a spacer then other tabs
so the user knows that the first tabs have something common and so the last tabs...

check [github's menu](https://i.postimg.cc/2jt9K38N/github-menu.png), it have some items and a spacer between every few common items

**Comment by zyfdegh** [comment]
An sneaky way to do this can be

```go
import (
    "fyne.io/fyne/layout"
    "fyne.io/fyne/widget"
)

tabs := widget.NewTabContainer(
    widget.NewTabItem("____", layout.NewSpacer()),
)
```
Check the [image here](https://postimg.cc/BX99chVN), hope it helps.

**Comment by andydotxyz** [comment]
I see what you are referring to. Toolbars have spacers and separators. Menus (in 1.3 will) have separators. Tabcontainers do not as they are designed to have the same sort content throughout - I.e. top level application areas or files in a panel.

**Comment by andydotxyz** [comment]
See: https://material.io/components/tabs#placement

We decided to move to a more prominent “current tab” highlight and also that scrolling isn’t the way we want to handle overflow, otherwise it’s the spec

**Comment by andydotxyz** [comment]
Let's stick to the spec for now.
