### ISSUE TITLE
How to transform the UI to fit interface like Blender3D modeling program?

### ISSUE THREAD

**Issue by gdeverlant** [fyne-io/fyne#903]
Greetings to y'all!
First of all i would like to congrats everyone for this amazing library!

My feature request is it possible to get an interface which allows us to reproduce this kind of UI with the current implementation?

![image](https://user-images.githubusercontent.com/26530975/80257653-b1cb1100-8681-11ea-87f7-6ed0bafbcdb0.png)

This is an open source 3D modeling program which IMHO has the best of the UI so far!
You can find it at https://www.blender.org/ and download and test it.

How complicated is it to adapt the whole UI from Fyne to reflect the same as in Blender3D?

Best regards

**Comment by andydotxyz** [comment]
Anything is possible as the canvas api is available to build your own widgets. Also you can extend existing widgets.

I guess it’s not clear from your issue what the question is - are there certain widgets you are asking about, or is it the 3D surface?

We don’t support embedding 3D accelerated content at this time so that might be the closest thing to a limitation from a performance perspective.

**Comment by gdeverlant** [comment]
Can someone provide any tutorial concerning coding widgets so that we can get a basic?

I am not asking for 3D accelerated content only 2D/Video/Audio/Microphone/Camera/etc,,,

**Comment by tataDan** [comment]
Have you had a chance to look at https://fyne.io/develop/tutorials/extending-widgets and https://fyne.io/develop/tutorials/write-custom-widget?

**Comment by andydotxyz** [comment]
I didn't know that Blender used microphone and camera!  Fyne does not have built-in support for them, nor for audio yet, but there are libraries out there you could use with it.

**Comment by gdeverlant** [comment]
Well it does use it and there are more and more features added because of the Epic Mega Grant from of $100 000. They hired many other people to focus on specific area that needed care in Blender.
