### ISSUE TITLE
Is there a way to color text ?

### ISSUE THREAD

**Issue by yyewolf** [fyne-io/fyne#906]
I want to have some kind of a console box with logs, and I wanted to know if it was possible to make it so that some text would be green while some other text is red for example.

**Comment by andydotxyz** [comment]
Canvas.Text can hold any colour. Widget.Label is designed to fit theme, so doesn’t support that customisation. I imagine that a list of text objects may work?

**Comment by Kvaz1r** [comment]
But what about text grid where exists such feature? I noticed it was [merged](https://github.com/fyne-io/fyne/pull/873) into develop. Can we hope to seen it in next release? :)

**Comment by yyewolf** [comment]
If I use this technique, is it possible to write something like that :

{red} Some {red} {blue} Text {blue} {red} here. {red}

On a single line ?

**Comment by yyewolf** [comment]
Nevermind, I managed to do it using widget.NewHBox(text1, text2, text3)

**Comment by andydotxyz** [comment]
The TextGrid is expected to be in 1.3 release, yes.
It provides support for monospaced grid of characters where every unicode element can have it's own style (currently foreground and background colour).

**Comment by noerw** [comment]
> Canvas.Text can hold any colour. Widget.Label is designed to fit theme, so doesn’t support that customisation. I imagine that a list of text objects may work?

@andydotxyz  What if I need `widget.Label` features such as text wrapping? That's not available on the canvas primitive afaics..

**Comment by andydotxyz** [comment]
That is correct. We are aware of this limitation and aiming to make improvements to the general text API but for 1.4 it will probably remain this way, sorry.

**Comment by noerw** [comment]
Ok, thanks for the info :)
