### ISSUE TITLE
Scroll Container

### ISSUE THREAD

**Issue by yyewolf** [fyne-io/fyne#908]
Is it possible to set the scroll container to be at the end ?
For instance, if I append an object inside of the GroupWithScroller, I want the user to be able to see it by putting the scroll bar at the bottom.

Thanks !

**Comment by andydotxyz** [comment]
You can use the Offset property in ScrollContainer to control the position. Just remember to call Refresh() after manually changing a widget's fields.

**Comment by yyewolf** [comment]
I can't find how to scroll to the end though, I'm currently trying this :

```
adjust := LogScroll.Size().Height
LogScroll.Offset = fyne.NewPos(0, adjust)
LogScroll.Refresh()
```

**Comment by andydotxyz** [comment]
The magic number 5 is a little strange. I think the solution would be:
```
	offset := scroll.Size().Height - content.Size().Height
	scroll.Offset = fyne.NewPos(0, offset)
	scroll.Refresh()
```
