### ISSUE TITLE
Entry: while adding text beyond visible region there is no auto-scroll

### ISSUE THREAD

**Issue by Aukstkalnis** [fyne-io/fyne#912]
### Describe the bug:
I add text at the bottom of text wedget, then pres enter, then write, and there is no autoscroll. The text is bellow the visible field. I think this is a bug, because when writing, user do not need to manually scroll down to see what is written.

### To Reproduce:
Steps to reproduce the behaviour:
1. Go to fyne_demo
2. Click on Wiggets
3. Click on Text
4. Hit enter until the text reaches the bottom 
5. See that text are gone and no autostroll was made.

### Device (please complete the following information):
 - OS: Windowns
 - Version: 10
 - Go version: 1.14.2
 - Fyne version: 40c918da68f15c82a87381a7eff3e7e5ca607cda

**Comment by andydotxyz** [comment]
Quite right. This is a flaw in the current scrolling of the Entry widget that needs to be addressed.
Unfortunately the underrlying work is a breaking change and so we can't address it in a feature release, and it will have to wait until 2.0 later in the year. Depends upon #471

**Comment by Aukstkalnis** [comment]
Ok, but I think for demo you just need to add simple workaround to just move scroll container when cursor is bellow the visible field.

**Comment by andydotxyz** [comment]
I don't think that our demo should be including workarounds, we need to fix this properly.

**Comment by andydotxyz** [comment]
Going to close this as a duplicate, we will work through Entry and other Text handling improvements in 2.0 following #471
