### ISSUE TITLE
Window redraws can pause during resize

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#913]
Related to #12, the runloop pauses on move.resize on some systems.

on MacOS: resize blocks the runloop
on Windows: resize and move block the runloop

In #531 we added live refresh of canvas, but this only works when the window is actually moved. If the user is holding down the resize action but not making a resize it does not repaint (like on a move).

Therefore we need to run a background timer to simulate the runloop for macOS and Windows when we detect that it has been paused (because GLFW is blocking on event poll).

**Comment by MartyMacGyver** [comment]
Thank you for opening this based on our conversation!

**Comment by andydotxyz** [comment]
Removing blocker as this is not a new issue. It has been improved in this release already.
I would like to see a complete solution here but we have other things that really are blocking the release.

**Comment by MartyMacGyver** [comment]
When I go to try this out (when 1.3 is out) what changes should I expect to see in terms of this issue?

**Comment by andydotxyz** [comment]
With this version the app will refresh as you move or resize.
However if you hold the mouse down without moving then it will still pause. Tht is the thing we still need to fix.

**Comment by andydotxyz** [comment]
OK I finally have a complete fix in the works for this issue.
It has required an overhaul of our run loop but it uncovered some things that could have been done better so it's a good thing overall.
It works locally but combined with the "live resize" feature the resize is very slow and a little glitchy so needs more work still.

**Comment by andydotxyz** [comment]
On develop for testing

**Comment by MartyMacGyver** [comment]
Cool! Thank you!
