### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#916]
This probably needs some requirements fleshed out.

* verifying the content of an input (with some indication that verification fails
* verifying the content of a form (so Submit can be disabled)
* restrict input types on fields and switch soft-keyboard where appropriate.

**Comment by Atomotron** [comment]
Except for switching the soft keyboard, this can all be done by overriding KeyDown. See [issue 1038](https://github.com/fyne-io/fyne/issues/1038) for a suggestion for how failed validation could be indicated to the user.

**Comment by andydotxyz** [comment]
It might be better for cross platform to use OnChanged (so you validate the content not they key event) - mobile does not generate key events.

The soft keyboard type may be addressed separately in #975

**Comment by Atomotron** [comment]
Given our discussion, I think the best way to implement this would be with:

- Subclassing to override OnChanged.
- A guarantee that OnChanged will run before anything is drawn. (This ensures that if you want to scrub, say, letters out of a number input, you can do it without flashing invalid input on the screen.)
- An IsValid flag in the Entry struct that its renderer respects, along with new colors in the theme interface.
- Some new subclasses of Entry that implement typical validation stuff in their default OnChanged

To see why this is a good idea, let's use an integer range with a maximum length as an example. Suppose I need to ask for a range start and a range end, where end > start, and also end < start + 100. (Perhaps my API will refuse to return more than 100 records.) In this case...

1. The validity of an entry can result in an error status displayed anywhere, including the valid state of *another* entry. I might want to report an error by setting a label's text, opening a pop-up, or logging to a file. Further, changing the range start can make a previously valid range end invalid. As a result, the validator needs write access to the valid state of both entries.
2. The validity of an entry can depend on data that comes from anywhere. The range end's validity depends on the value of the range start. I might also want to validate it by doing something weird, like requesting from the network.

It's clear that the cleanest way to support the general case would be to allow the user to run arbitrary code whenever an widget changes. Closures and callbacks would be a natural way to do this, but Fyne doesn't use callbacks, which leaves subclassing and additional fields in the widget struct as the remaining alternative.

Specific entry types, like "integer," "natural number," or "phone number," would fit in to this scheme as derived widgets. Maybe they could be packaged in fyne/widget/validated to keep them from proliferating and taking up too much of the widget namespace.

**Comment by andydotxyz** [comment]
I don't know that overriding widget methods like `OnChanged` is required, or particularly clean. 
I would prefer a new function / interface (i.e. `IsValid() bool` on a `Validatable` interface perhaps) that any input widget could implement (or at least a certain subset) implementing that in an extended widget feels much cleaner as the widget knows how to ask for a validation result and can more cleanly render the result.
You're right that order of events would need to be guaranteed here. I imagine that processsing events is first, then validating, then calling OnChanged with the result, perahps only if valid.
This avoids adding an "IsValid" boolean that requires external code to maange it.

This approach would mean that we could add some default validation without overriding so much, either through overloading or composition (for example `NewEmailEntry()` or `Entry.SetValidation(EmailValidation)`).

Let me know what you think about this proposed approach. It is similar to what you describe above but fits a little more with the current API design so should be easier to discover / learn.

**Comment by Atomotron** [comment]
I agree that the interface design would be more consistent with the existing architecture of Fyne, although I also think it would take less typing to set a callback than it would to extend a widget. In some contexts it is worth pointing out that a closure *is* an object implementing a single-function interface, although Go does have a lot of single-function interfaces.

A hidden deciding factor here is whether or not it would be beneficial to Fyne internals for there to be an interface for widgets that can be validated. With callbacks alone it would not be possible to write a function that accepted any widget with an IsValid field. Whether or not this is important depends on information I don't know, but you might have some insight.

**Comment by Jacalz** [comment]
Moving the last input field restriction to a new issue. The input validation for Entry and Form have landed and will be in the 1.4 release soon :)
