### ISSUE TITLE
Initially shown file dialog does not fill content

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#930]
### Describe the bug:
When first shown, and until resize, the file dialog content is not filling the scrollable area.
This is new

### To Reproduce:
Steps to reproduce the behaviour:
1. fyne_demo
2. Windows
3. ShowFileOpen

Looks like it's just the clipping that is not correct the content seems about right and scrolls as expected.

### Screenshots:
<img width="790" alt="Screenshot 2020-05-04 at 15 48 37" src="https://user-images.githubusercontent.com/294436/80979269-06f3e900-8e1f-11ea-9b4e-52ea8018e0fd.png">

### Device (please complete the following information):
 - OS: macOS 10.15
 - Version: latest
 - Go version: 1.12
 - Fyne version: develop

**Comment by stuartmscott** [comment]
I have a feeling this is related to #834, try adding logs to your renderer.Refresh and renderer.Layout functions then reproducing this issue.

**Comment by andydotxyz** [comment]
I will try... but this has happened in the last week or two, but the other issue goes back a month or more...

**Comment by andydotxyz** [comment]
I think this relates to scroller. It is also visible on the containers tab of fyne_demo when you look at the scroll tab

**Comment by stuartmscott** [comment]
Interestingly this is fixed by resizing the window, opening the demo on a second monitor, or setting the demo window size before adding the content;
```go
w := a.NewWindow("Fyne Demo")
w.Resize(fyne.NewSize(1,1))
```
Maybe glScissor can't be set before the window has position/size.

**Comment by andydotxyz** [comment]
I agree that it's weird that those actions fix it.
However I don't think it can be a glScissor issue as this has worked for nearly a year before it started breaking this month.

**Comment by andydotxyz** [comment]
I was randomly testing other stuff and noticed that this goes away with latest develop if you `-tags no_native_menus`. It does flicker sometimes noticeably on load...
So I suspect that the menu bar is causing a refresh that fixes an underlying issue that has gone un-noticed.
Using macOS native menus this refresh is skipped and the screen does not re-calculate something.
It may be a duplicate of #938 after all...

**Comment by stuartmscott** [comment]
Interesting, so it is adding an extra refresh? But this is a patch fix - the root cause is much deeper.
The fact that resizing the window _before_ creating and showing a file dialog fixes this issue makes me think that the scroller is dependent on some internal state (possibly around scale/size) is wrong and which a resize fixes.

**Comment by andydotxyz** [comment]
Yeah you're probably right.

**Comment by andydotxyz** [comment]
This plus other things seem to be fixed on my #966 PR as it addresses the ordering of some events :)

**Comment by andydotxyz** [comment]
On develop for testing :)
