### ISSUE TITLE
Gui Not Responding

### ISSUE THREAD

**Issue by c5sousa** [fyne-io/fyne#933]
Hello, I am trying to use fyne to implement a GUI for my tello drone but seem to be having an issue when trying to get it running. I am unsure of if this is a fyne issue or a drone issue but I am trying to build a controller for my drone and when the drone starts the window opens for the GUI but it will constantly say not responding. Here are some pictures to show what it normally looks like outside of the anonymous function and inside the anonymous function.  
![image](https://user-images.githubusercontent.com/60722757/81030048-58b76600-8e55-11ea-947b-db802497402c.png)
Now when I put it inside of the anonymous function which is then being passed to the drone this is what happens.
![image](https://user-images.githubusercontent.com/60722757/81030191-e85d1480-8e55-11ea-8919-b15bc3d4eb50.png)
I am also linking my main function to show you whats going on, when I remove the code for the GUI from the anonymous function, the GUI starts up fine but the drone wont start and if I start the drone before the GUI, once the drone stops, the GUI starts. So my only other option I would think is to put the GUI inside of the anonymous function but that doesn't seem to work. Sorry for the long post, I just felt that it would help to give as much info up front in case I cant respond back fast enough. Any help would be greatly appreciated thank you.
![image](https://user-images.githubusercontent.com/60722757/81030289-4e499c00-8e56-11ea-8366-6d099cda017a.png)
![image](https://user-images.githubusercontent.com/60722757/81030321-70431e80-8e56-11ea-875e-36257d365ad5.png)

**Comment by andydotxyz** [comment]
Sorry but you must start the GUI from main(), not within a goroutine. In 1.3 this will be clearer, resulting in a panic. It’s probable that the issue you are seeing is due to the event loop not managing to paint graphics correctly.

**Comment by c5sousa** [comment]
Thank you, I am new to Go so I was not sure why that was happening. Is there a way to get both of them going at the same time? My issue from there is getting the button events handled within that go routine so that when you click the button the robot executes one of the methods designated to that button.

**Comment by stuartmscott** [comment]
Hey @c5sousa,

Currently you have:
```
func main() {
    drone := ...
    work := func() {
        // Setup Fyne
    }
    // Setup Gobot with work
}
```

What if you rearranged this to:
```
func main() {
    drone := ...
    go func() {
        // Setup Gobot
    }
    // Setup Fyne
}
```

**Comment by c5sousa** [comment]
Hey @stuartmscott, So when I put robot.Start() before the gui which sets up the connection between my PC and the drone, and starts the ddrone up, the gui wont show up until after I close the connection between my PC and the Drone, pretty much stopping the robot. I had also tried maybe putting robot.Start() into one of the buttons anonymous functions but once I click that button that starts it, I cant click any other buttons until I close the connection again.

**Comment by andydotxyz** [comment]
With @stuartmscott suggestion you would but `robot.Start()` inside the `go func() {` so that it does not block the creation of GUI.

**Comment by c5sousa** [comment]
So @andydotxyz and @stuartmscott, I did what you said and it works perfectly, thank you so much. But just one last question, what does go func() {}()  do? Is this specific to just go?

**Comment by andydotxyz** [comment]
Yes, `go functionCall()` is Go's way of starting code "in the background" - like a new thread but much lighter.

Usually it is not needed, but in this instance the GUI and the drone want to block until the process is complete, so this code creates the drone server in the background so the GUI can setup and run it's graphical processing which must occur in main().
