### ISSUE TITLE
Differences Between GL and Software Renderers

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#944]
### Is your feature request related to a problem? Please describe:
"fyne.io/fyne/internal/widget".BaseRenderer implements BackgroundColor() and returns theme.BackgroundColor().

If an object (eg "fyne.io/fyne/widget".Group) is used in a dialog, its background does not match the dialog background.

### Is it possible to construct a solution with the existing API?
There is no easy way to override the background color. One option is to make a custom widget extending Group which uses a different renderer - but this seems like overkill

### Describe the solution you'd like to see:
Either baseRenderer should have a transparent background, or there need to be a SetBackgroundColor(color.Color) then BackgroundColor returns that, or if it is not set, return theme.BackgroundColor()

**Comment by andydotxyz** [comment]
I'm not sure about this... The dialog should be using backgroundColor, so perhaps there is another issue somewhere. Perhaps you have an image so we can look at what might be wrong in the rendering?

Moving to transparent by default is probably an option nevertheless but I'd like to know if we have an underlying issue.

Adding a SetBackgroundColor to all widgets isn't something we should consider, as widgets should expose only logic/state APIs

**Comment by andydotxyz** [comment]
Suggest change of title to "Dialog background is not theme.BackgroundColor"?

**Comment by stuartmscott** [comment]
I'm using a dialog which on mobile contains a tabber with two tabs (Sign In/Sign Up), and on desktop (with more screen real estate) shows the two pieces of content side-by-side. Here are two screenshots (mobile & desktop) to show the problem that triggered this issue:

<img width="600" alt="Screen Shot 2020-05-06 at 6 53 44 AM" src="https://user-images.githubusercontent.com/1117080/81185449-74f6f800-8f66-11ea-8727-9e745617dc99.png">

<img width="801" alt="Screen Shot 2020-05-06 at 6 46 15 AM" src="https://user-images.githubusercontent.com/1117080/81184824-b89d3200-8f65-11ea-86a7-c780badebdf9.png">

It looks like dialog (modal popup) has theme.ShadowColor() as its background - which is fine as you'd want the dialog to have a different color than the window, but Group and Tabber use theme.BackgroundColor(). If the default was transparent, I think this issue would be resolved.

**Comment by andydotxyz** [comment]
The shadow colour is supposed to be used for the semi-transparent shadow drawn around the modal.
The dialog content background should be bg colour.

**Comment by stuartmscott** [comment]
Okay, let's use your suggested title for this bug and make dialog background the same as window background, ie. theme.BackgroundColor()

**Comment by andydotxyz** [comment]
dialog/base.go:58 seems to indicate we already are, I think there is a more subtle issue

**Comment by stuartmscott** [comment]
widget/popup.go:253 made me think it was rendering the background with the shadow color

**Comment by andydotxyz** [comment]
OK, not a problem. But now it seems we have 2 widgets using background colour but they look different... hmm.
I wonder if my colourspace changes fix this at all? not sure why they would but it is in that area...

**Comment by stuartmscott** [comment]
It is certainly better, but there is still a colour difference:

<img width="799" alt="Screen Shot 2020-05-06 at 10 26 36 AM" src="https://user-images.githubusercontent.com/1117080/81208598-2e17fb00-8f84-11ea-95f5-34a9fbe9afa4.png">

**Comment by andydotxyz** [comment]
Hmm. I wonder if that is an artifact in the Gl renderer? if you capture the canvas from a software renderer do you see the same issue?

**Comment by stuartmscott** [comment]
Attempted in #949

**Comment by andydotxyz** [comment]
This is the software renderer version, looks like it might be a GL issue...

![dialog_background_group](https://user-images.githubusercontent.com/294436/81324093-5db32a00-908e-11ea-8010-5e87375cd336.png)

**Comment by stuartmscott** [comment]
Here's what I get:

![dialog_bg_light](https://user-images.githubusercontent.com/1117080/81325824-ca5a0480-904d-11ea-9392-fdb6a4fadf28.png)
![dialog_bg_dark](https://user-images.githubusercontent.com/1117080/81325840-ce862200-904d-11ea-8b54-1e1fb9e8c40e.png)

If the issue is in GL, what's the best way to track it down?

**Comment by andydotxyz** [comment]
I'd say that running the app as normal and a lot of screenshots will help.
Use a colour pixel check on the resulting images and compare it to the theme values.

I'd suggest testing once with it as content of the window then another as the content of a dialog and see what changes.

**Comment by andydotxyz** [comment]
I think the title is not fitting well now. Probably something about subtle differences in background colours in GL renderer?

**Comment by andydotxyz** [comment]
All graphical types should be supported by the incoming #1141.
I would love to mark this as resolved but I guess the subtle background issues are what caused this to be opened in the first case right @stuartmscott?

In combination with the previous #947 for NRGBA transition this may now be resolved?

**Comment by andydotxyz** [comment]
Ping @stuartmscott

**Comment by stuartmscott** [comment]
This appears to be fixed
