### ISSUE TITLE
[Question] Horizontal centering of container

### ISSUE THREAD

**Issue by talentlessguy** [fyne-io/fyne#946]
Hello, once again I ask a question, because didn't find it anywhere.

**How to center the element horizontally in a container?**

# What I want to do

I want my progress bar to centered horizontally, like this:

![image](https://user-images.githubusercontent.com/35937217/81175519-59164500-8fac-11ea-81f2-c907be7c1883.png)

# What I tried to do

## bar between 2 rectangles as spacers

I tried putting empty rectangles before and after progress bar so it would be like this:

![image](https://user-images.githubusercontent.com/35937217/81175365-194f5d80-8fac-11ea-92dc-0c67cb497a4f.png)

but it doesn't seem to help:

```go
package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
)

// NewAudioBar - track bar
func NewAudioBar(currentTime int, timeLeft int) *fyne.Container {
	currentBar := canvas.NewRectangle(theme.PrimaryColor())

	totalBar := canvas.NewRectangle(color.Black)

	currentBar.Resize(fyne.NewSize(100, theme.Padding()*2))

	totalBar.Resize(fyne.NewSize(300, theme.Padding()*2))

	c := fyne.NewContainer(totalBar, currentBar)

	spacer := canvas.NewRectangle(color.Transparent)

	spacer.Resize(fyne.NewSize(50, theme.Padding()*2))

	layout := fyne.NewContainerWithLayout(layout.NewHBoxLayout(), spacer, c, spacer)

	return layout
}
```

What I get is this:

![image](https://user-images.githubusercontent.com/35937217/81174838-32a3da00-8fab-11ea-81be-54bcd47e5fae.png)

WIthout spacers, it's almost the same:

```go
layout := fyne.NewContainerWithLayout(layout.NewHBoxLayout(), c)
```

![image](https://user-images.githubusercontent.com/35937217/81174913-51a26c00-8fab-11ea-98eb-30beef9ed469.png)

Setting spacer's rectangle width to 1000, or to 10, al results the same. 

## `NewContainerWithLayout`

Also I tried to use `NewContainerWithLayout`: 

```go
layout := fyne.NewContainerWithLayout(layout.NewCenterLayout(), c)
```

but it doesn't do what I want to have:

![image](https://user-images.githubusercontent.com/35937217/81175790-c924cb00-8fac-11ea-93ab-e09a5b3aaa26.png)

Any ideas and suggestions? I've gone through the Fyne tour and couldn't fine anything :(

**Comment by andydotxyz** [comment]
The NewCenterLayout would work correctly if your progress bar had a minsize.
Each layout has different characteristics, but essentially they either expand content or collapse it.

Your code is manually setting the size of an element by putting it in an unmanaged container, and then putting that into a layout managed container. Your custom child content has no defined minsize so it is effectively collapsed.

Given the code you already have it's probably easiest to align the boxes yourself within the space available, `Rectangle.Move()`.

**Comment by talentlessguy** [comment]
@andydotxyz oh thanks it worked!

the solution, as u described, looks like this:

```go
// Create rectangle bar
currentBar := canvas.NewRectangle(theme.PrimaryColor())
// Resize it
currentBar.Resize(fyne.NewSize(100, theme.Padding()*2))
// Set it's min size
currentBar.SetMinSize(fyne.NewSize(100, theme.Padding()*2))
```

go code:

```go
package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/canvas"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/theme"
)

// NewAudioBar - track bar
func NewAudioBar(currentTime int, timeLeft int) *fyne.Container {
	currentBar := canvas.NewRectangle(theme.PrimaryColor())

	totalBar := canvas.NewRectangle(color.Black)

	currentBar.Resize(fyne.NewSize(100, theme.Padding()*2))

	currentBar.SetMinSize(fyne.NewSize(100, theme.Padding()*2))

	totalBar.Resize(fyne.NewSize(300, theme.Padding()*2))

	totalBar.SetMinSize(fyne.NewSize(300, theme.Padding()*2))

	c := fyne.NewContainer(totalBar, currentBar)

	c.MinSize().Add(fyne.NewSize(300, theme.Padding()*2))

	layout := fyne.NewContainerWithLayout(layout.NewCenterLayout(), c)

	return layout
}
```

it works perfectly well:

![image](https://user-images.githubusercontent.com/35937217/81301679-0909b200-9082-11ea-8e69-c14c390ac265.png)

**Comment by zhexyez** [comment]
Nice. Very nice... The question is listed as "centering of container", but the code shows canvas. It doesn't work with Labels or Containers. Maybe there is another way around. I've just started with Fyne.

**Comment by zhexyez** [comment]
> Nice. Very nice... The question is listed as "centering of container", but the code shows canvas. It doesn't work with Labels or Containers. Maybe there is another way around. I've just started with Fyne.

```
HeaderText := widget.NewLabel("Some Text")
HeaderText.Alignment = fyne.TextAlignCenter
HeaderItself := container.New(layout.NewAdaptiveGridLayout(1), HeaderText)
//HeaderItself := container.New(layout.NewCenterLayout(), HeaderText) <- fills entire available space
```

**Comment by andydotxyz** [comment]
> Nice. Very nice... The question is listed as "centering of container", but the code shows canvas. It doesn't work with Labels or Containers. Maybe there is another way around. I've just started with Fyne.

The technique will center in whatever space is given - container, canvas or inside another widget.

**Comment by andydotxyz** [comment]
> > Nice. Very nice... The question is listed as "centering of container", but the code shows canvas. It doesn't work with Labels or Containers. Maybe there is another way around. I've just started with Fyne.
> 
> 
> 
> This is how you do it:
> 
> 
> 
> ```Go
> 
> HeaderText := widget.NewLabel("Some Text")
> 
> HeaderText.Alignment = fyne.TextAlignCenter
> 
> HeaderItself := container.New(layout.NewAdaptiveGridLayout(1), HeaderText)
> 
> //HeaderItself := container.New(layout.NewCenterLayout(), HeaderText) <- fills entire available space
> 
> ```

To center text all you need is the `Alignment` set.

Putting it in a grid layout will make no difference - it is still filling the available space, but centering inside it.
The Center layout/container is useful for items that don't have this alignment, or to center a child container where all the objects should be grouped - as in the original post.

**Comment by zhexyez** [comment]
> > > Nice. Very nice... The question is listed as "centering of container", but the code shows canvas. It doesn't work with Labels or Containers. Maybe there is another way around. I've just started with Fyne.
> > 
> > 
> > This is how you do it:
> > ```go
> > HeaderText := widget.NewLabel("Some Text")
> > 
> > HeaderText.Alignment = fyne.TextAlignCenter
> > 
> > HeaderItself := container.New(layout.NewAdaptiveGridLayout(1), HeaderText)
> > 
> > //HeaderItself := container.New(layout.NewCenterLayout(), HeaderText) <- fills entire available space
> > ```
> 
> To center text all you need is the `Alignment` set.
> 
> Putting it in a grid layout will make no difference - it is still filling the available space, but centering inside it. The Center layout/container is useful for items that don't have this alignment, or to center a child container where all the objects should be grouped - as in the original post.

Thank you. But how do you do smth like this:
```css
margin-top: 0;
text-align: center;
```

**Comment by andydotxyz** [comment]
There are many different ways - as with Fyne layouts it depends on how the whole space should be layed out not just a single item.
However likely the closest guess is `container.NewHBox(layout.NewSpacer(), myWidget, layout.NewSpacer())`.

Can you please open a new discussion or use one of the support channels when you have new questions, as this ticket was closed over 2 years ago.
