### ISSUE TITLE
Support Focus Traversal in Dialogs

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#948]
### Is your feature request related to a problem? Please describe:
Although it is possible for windows, it is not possible to use tab to traverse input elements in a dialog.

### Is it possible to construct a solution with the existing API?
Not that I know of.

### Describe the solution you'd like to see:
Similar functionality as seen in windows, ported to dialogs as well.

**Comment by jkvatne** [comment]
I believe this  is fixed in my PR #1074. But it required some hacks.

**Comment by andydotxyz** [comment]
Indeed, there is a lot of good stuff in that PR. If we could get it broken into smaller parts then we could probably see parts land soon :)

**Comment by andydotxyz** [comment]
Does this relate to #814?

**Comment by andydotxyz** [comment]
Should this be closed as ready for testing on `develop` now?

**Comment by toaster** [comment]
Yes.
