### ISSUE TITLE
Paste in MultilineEntry not working in Windows build

### ISSUE THREAD

**Issue by simplyibo** [fyne-io/fyne#952]
### Describe the bug:
Copy&Paste using the shortcuts ctrl+c and ctrl+v **does not** work inside the Entry fields on Win7/Win10 (pressumably also Win8) OS. However rightclick->copy rightclick->paste **does** work.
As the shortcuts seem to work properly on MacOS and Ubuntu this seems to be a Bug on Windows only.

### To Reproduce:
Steps to reproduce the behaviour:
1. Copy some short text from somewhere outside your fyne GUI (e.g. Browser)
2. Focus an entry or multiline entry field in your GUI
3. Press ctrl+v on your keyboard
4. See: nothing happening, Expectation: Text is in entry field

### Device (please complete the following information):
 - OS: Windows
 - Version: Tested with Win7 and Win10
 - Go version: 1.14.2
 - Fyne version: 1.2.4

**Comment by andydotxyz** [comment]
I cannot replicate this issue sorry. The shortcuts fire and the advanced panel shows key events as expected.
Is there anything unusual about your setup? I.e. is the keyboard a different layout - is your input set to a non-english locale? Anything that might be needed to replicate this issue would be helpful

**Comment by simplyibo** [comment]
> Is there anything unusual about your setup? I.e. is the keyboard a different layout - is your input set to a non-english locale? Anything that might be needed to replicate this issue would be helpful

Yes, the locale was german (de) which means the layout was different (QWERTZ). Tried it with 2 PCs, nothing special on them, but there is a chance it might be the keyboard layout though.

**Comment by andydotxyz** [comment]
Could you perhaps please try the patch that I posted on #981 as a possible fix and/or debug info? I'm not yet sure if these are the same issues or not as I can't replicate either.

**Comment by andydotxyz** [comment]
There are reports also that this may be fixed on the `develop` branch - is this something that you would be able to test for us please @simplyibo

**Comment by simplyibo** [comment]
Hi @andydotxyz,
yes I will test this.

**Comment by simplyibo** [comment]
> There are reports also that this may be fixed on the `develop` branch - is this something that you would be able to test for us please @simplyibo

Yes, I can confirm that develop branch works fine. Shortcuts ctrl+v / ctrl+c work in Entry fields now!

**Comment by simplyibo** [comment]
> Not sure if this is related, but the KeyDown events were not firing for a-z as well.

This one works as well now.

**Comment by andydotxyz** [comment]
Excellent. thanks for confirming
