### ISSUE TITLE
Support for Event Subscription on Fyne Window 

### ISSUE THREAD

**Issue by simplyibo** [fyne-io/fyne#953]
### Is your feature request related to a problem? Please describe:
I want to react/subscribe on events like key-pressed, mouse-clicked when a specific window is in focus. The subscribed handlers (e.g. callback functions) should be called for the occurance of the specific event they subscribed on. It should be possible to add multiple subscribers/callbacks to the list with a kind of "add" function.

It should not matter where the focus inside the window is (e.g. an entry). The subscribed event should be fired wherever (e.g.) a key is pressed, but only when the fyne window is in focus.

Nice-to-haves: 
* The callback will receive an event struct with more information
* The currently focused object is provided as a property of the fired event
* Subscription is always made with the same add... function using an "event" Parameter which defines type (e.g. key, mouse, touch), action (e.g. down, left-click-down), focus (window, object)
* Life would be even easier when there are not only primitive event-types like "key" but also types like "shortcut" supporting up to 3 or 4 keys pressed together that you can subscribe on

### Is it possible to construct a solution with the existing API?
I don't think so. I was not able to react on keypress on the whole window canvas while the focus in on a specific element.

**Comment by andydotxyz** [comment]
Window.OnTypedRune/Key will be fired if the keyboard is not currently used on a focussed element.
If you want a shortcut that is always responded to then use Window.Canvas().AddShortcut()

Widgets can respond to user interaction by implementing one of the various interfaces in the canvasobject.go file:

```
type Scrollable interface

type Draggable interface

type Focusable interface

type Shortcutable interface
```

and there are desktop and mobile extensions if you want to go platform-specific.

**Comment by andydotxyz** [comment]
I think that what you are requesting is already implemented.
Please be more specific about what you cannot figure out how to do so we can suggest a solution or identify a gap in the API.

**Comment by simplyibo** [comment]
> Window.OnTypedRune/Key will be fired if the keyboard is not currently used on a focussed element.

Yes, I figured this out and that's why it's useless for me. Let's say I want to implement a shortcut for "save" with "ctrl+s" in an Editor like UI. The User would expect to be able to do this shortcut when entry is focused and also when it's not focused -> means I want to listen to the whole window. That's why I wrote:
"It should not matter where the focus inside the window is (e.g. an entry). The subscribed event should be fired wherever (e.g.) a key is pressed, but only when the fyne window is in focus."

> If you want a shortcut that is always responded to then use Window.Canvas().AddShortcut()

That Shortcut implementation seem just to know copy and paste but not save or delete.

> I think that what you are requesting is already implemented.
> Please be more specific about what you cannot figure out how to do so we can suggest a solution or identify a gap in the API.

Ok I will try my best. I would like to react to keypress no matter where the focus is on. 
Let's say I have a window, with a button, multiple entry fields, checkboxes and some random space. 
1. The user clicks on any of these elements or on any space inside the window or just refocuses the window after focusing another applications window
2. The user presses ctrl (key down) -> callback
3. The user presses s (key down) -> callback

**Comment by andydotxyz** [comment]
For custom shortcuts use the `driver.desktop.CustomShortcut` featture (there is a tutorial for this overdue!). It exists in the desktop package as clearly it won't work on mobile runtime.

You'll find that many "hardware specific" events are hidden in preference of more cross-platform solutions. It sounds like CustomShortcut is the solution to your main issue.

**Comment by simplyibo** [comment]
What I also figured out when playing around with KeyDown function inside MultilineEntry:
The keys a-z are not being fired on Win7/Win10 but works on Ubuntu and MacOS.
Might this be an OS specific bug? In that case I guess it should be the same with "CustomShortcut".

**Comment by simplyibo** [comment]
> For custom shortcuts use the `driver.desktop.CustomShortcut` featture (there is a tutorial for this overdue!). It exists in the desktop package as clearly it won't work on mobile runtime.
> 
> You'll find that many "hardware specific" events are hidden in preference of more cross-platform solutions. It sounds like CustomShortcut is the solution to your main issue.

Thanks a lot, I will try this out.

**Comment by andydotxyz** [comment]
It sounds like there may be a bug in a-z key events not being fired. Maybe the windows build is not loading the full desktop extensions somehow. Perhaps you could open an issue for that so we can track the fix?

I don't know what you mean about how this should be the same for shortcuts.

**Comment by simplyibo** [comment]
Well my assupmtion was that it might be a general (not only for KeyDown) issue on Win because:
* Not able to fire KeyDown for [a-z] inside entry 
* But also not able to copy&paste with default shortcuts (using "ctrl+c" and "ctrl+v") inside entry, which I already opened another bug issue for: https://github.com/fyne-io/fyne/issues/952

**Comment by andydotxyz** [comment]
Ah yes I see what you mean. We'll get that ticket investigated and as you say it may solve more than just shortcuts.
Does this ticket need to remain open for any additional issues?

**Comment by simplyibo** [comment]
I think we can close it!
I will try out the CustomShortcuts and wait for the #952 fix if I run into the same issues unter Windows.
