### ISSUE TITLE
Refresh() doesn't refresh text labels inside of a loop in anonymous func

### ISSUE THREAD

**Issue by talentlessguy** [fyne-io/fyne#954]
### Describe the bug:

When I capture some value inside of:

```go
go func() {
  for { ... }
}
```

`widget.Refresh()` doesn't seem to be working. No errors, but it doesn't update anything.

Although, values are getting updated and I can even print them in console.

### To Reproduce:
Steps to reproduce the behaviour:
1. Clone the repo:

```sh
git clone https://github.com/talentlessguy/quark-player.git
```
2. Download the depencies:

```sh
go mod download
```

3. Run the app:

```sh
go run *.go
```

### Screenshots:

Here, updated values are being printed into console, but layout doesn't refresh anything.

![image](https://user-images.githubusercontent.com/35937217/81323687-6b70ab80-909e-11ea-9d2d-0945c80dce5b.png)

### Example code:

`NewTimeInfo` function:

```go
// NewTimeInfo - layout with two labels representing track time info
func NewTimeInfo(pos time.Duration, len time.Duration) *fyne.Container {

	posLabel := widget.NewLabel(pos.String())

	lenLabel := widget.NewLabel(len.String())

	return fyne.NewContainerWithLayout(layout.NewHBoxLayout(), posLabel, lenLabel)
}
```

Usage of values inside of `go func() for`:
```go
ap := NewAudioPanel(format.SampleRate, streamer)

	var position time.Duration
	var length time.Duration

	timeInfo := NewTimeInfo(position, length)

	go func() {
		for {

			position = ap.sampleRate.D(ap.streamer.Position()).Round(time.Second)
			length = ap.sampleRate.D(ap.streamer.Len()).Round(time.Second)
                        // Outputs everything in console
			fmt.Printf("%v of %v", position, length)
			fmt.Println()
                        // Doesn't refresh anything
			timeInfo.Refresh()
		}
	}()
```

### Device (please complete the following information):
 - OS: Linux
 - Version: 5.4.35
 - Go version: 1.14.2
 - Fyne version: v1.2.4

**Comment by andydotxyz** [comment]
It doesn't look like you are changing the timeInfo before refreshing it, so there is nothing to refresh...

**Comment by talentlessguy** [comment]
@andydotxyz hmm, should I do it like this, reassigning new layout?

```go
	var position time.Duration
	var length time.Duration

	timeInfo := NewTimeInfo(position, length)

	go func() {
		for {
			position = ap.sampleRate.D(ap.streamer.Position()).Round(time.Second)
			length = ap.sampleRate.D(ap.streamer.Len()).Round(time.Second)
			fmt.Printf("%v of %v", position, length)
			fmt.Println()
			timeInfo.Refresh()
			timeInfo = NewTimeInfo(position, length)

		}
	}()
```

It now outputs track length properly but not current position. Even when it outputs `2s` at console, in UI it is `0s`:

![image](https://user-images.githubusercontent.com/35937217/81327738-67478c80-90a4-11ea-8af1-816ddcf2a4fd.png)


it now outputs length properly but duration is still 0s

**Comment by andydotxyz** [comment]
I don't think that anything needed to be redesigned - you just need to set the position / length into your timeinfo code - your updating of variables is not communicating outside the for loop.

**Comment by andydotxyz** [comment]
Look at your code and think "how will the label get the updated information". When you create the label it is just using the current information - your updated text is lost - you don't communicate it to the GUI.

**Comment by stuartmscott** [comment]
```
timeInfo := NewTimeInfo(position, length)
```
is pass by value, not pass by reference. So when you update position and length in your loop, TimeInfo cannot see the update.

**Comment by talentlessguy** [comment]
guys, sorry for my poor Golang knowledge :)

my friend helped me to figure out the proper way:

```go
// layout.go
// NewTimeInfo - layout with two labels representing track time info
func NewTimeInfo(pos time.Duration, len time.Duration) (*fyne.Container, *widget.Label, *widget.Label) {

	posLabel := widget.NewLabel(pos.String())
	lenLabel := widget.NewLabel(len.String())

	return fyne.NewContainerWithLayout(layout.NewHBoxLayout(), posLabel, lenLabel), posLabel, lenLabel
}
```

```go
// main.go
var position time.Duration
	var length time.Duration

	timeInfo, posLabel, lenLabel := NewTimeInfo(position, length)

	go func() {
		for {

			position = ap.sampleRate.D(ap.streamer.Position()).Round(time.Second)
			length = ap.sampleRate.D(ap.streamer.Len()).Round(time.Second)
			posLabel.SetText(position.String())
			lenLabel.SetText(length.String())
			fmt.Printf("%v of %v", position, length)
			fmt.Println()
			timeInfo.Refresh()
		}
	}()
```

I hope it this answer will help someone like me :D
