### ISSUE TITLE
document how to deploy to web

### ISSUE THREAD

**Issue by glycerine** [fyne-io/fyne#956]
https://fyne.io/blog/ says

~~~
And… Web
And not to call it qiuts at adding mobile support to the upcoming 1.2 release 
but we will be adding support for web delivery as well.

You heard it right, Fyne apps will be deliverable through a standard web browser, 
if that is what you want to do! We are working on a web driver alongside our mobile 
work and are excited to be able to unveil that here today as well!

This means that the 1.2 release of Fyne will fully support 
all of the following platforms:

macOS
Windows
Linux
Raspberry Pi
iOS
Android
Web
And all of this will be possible from a single app code base - no special drivers and no complex device handling.
~~~

but I can find nothing about how to deploy the fyne_demo app (for example) as a website.

For example, how would I get that nice screenshot from the blog where the browser is loading http://localhost:8080/fyne.io/fyne/cmd/fyne_demo/ ?

Please point me to it, and add instructions to the docs.

**Comment by andydotxyz** [comment]
Sorry but the web work did not get released in 1.2 and it will not be in 1.3 either.
You can see the work in progress in #818 which includes a tech preview at https://fyne.ddlm.me/.

Apologies for not making that clear in a follow-up blog post.

**Comment by mohamadpk** [comment]
why there is nothing for develop the web front end ,just some simple example i found in the web ,and i create a project i get million of error at run time.fyne is very useful but if dont have a web cannot race with flutter

**Comment by andydotxyz** [comment]
You just type "fyne serve". It is documented at https://docs.fyne.io/started/webapp.

Please don't comment on old, closed issues.
