### ISSUE TITLE
Subjective comment on default colour choices in provided Fyne themes

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#958]
After reading the docs on colour selection :
https://www.material.io/design/color/dark-theme.html#ui-application

.. I think the primary blue that we are running with is probably a little oversaturated.

Experimenting with plugging in the suggested "200" colors, the Fyne demo looks a bit less like a Fyne app, and more like other material themed apps.

**Comment by steveoc64** [comment]
The widget set is getting towards maturity now ... would be good to start recruiting some designer talent to make it look better.

I wish I was good at design - I find it quite difficult.

**Comment by stuartmscott** [comment]
The golden image test framework @toaster introduced could be really helpful here as it makes it easier to compare aesthetic changes. Here's a sample:
```go
// Create a new app with theme
test.NewApp()
defer test.NewApp()
test.ApplyTheme(t, theme.LightTheme())

// Create a widget
button := &widget.Button{
	Text: "FooBar",
}

// Create a window with the software painter
window := test.NewWindowWithPainter(button, software.NewPainter())
window.Resize(button.MinSize().Max(fyne.NewSize(150, 200)))

// Capture the canvas and compare with golden
test.AssertImageMatches(t, "button_foobar.png", window.Canvas().Capture())

// Clean up
window.Close()
```

**Comment by steveoc64** [comment]
Tilo is doing some awesome things with testing - Ive learned a lot from him lately.

Thats pretty cool, will have a play with the AssertImageMatches

**Comment by toaster** [comment]
😊

**Comment by steveoc64** [comment]
Given that this patch does most of it now, and Im having fun with it -Will put another patch based on this that adds being able to set the palette from JSON as well. Can do that without touching the interface.

**Comment by steveoc64** [comment]
Lets have a go at getting primary icon color sorted with @stuartmscott

**Comment by andydotxyz** [comment]
Not sure how we approach this now that 1.3 is out. Popped into 1.3.x for now

**Comment by andydotxyz** [comment]
The primary (and a few other) colours have been updated on develop with #1195, so I'm marking this issue as resolved.
There is more work to do on theming of course, but there are other tickets / PRs to track.
