### ISSUE TITLE
Submenus not working in Mobile

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#962]
### Describe the bug:
Tapping on submenu does nothing.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open Fyne demo
2. Click on menu icon
3. Click on File
4. Click on New
5. Nothing happens

The same in Widgets -> Buttons -> pup-up button.

### Device (please complete the following information):
 - OS: Android
 - Version: 8.0
 - Go version: 1.14.2
 - Fyne version: develop 04d654b06855c53d2a7c18caafbcca2161baff73

**Comment by andydotxyz** [comment]
Quick test shows that the popoup sub menus are not working either :(

**Comment by toaster** [comment]
fixed on develop
