### ISSUE TITLE
CenterOnScreen does not work before Show() is called

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#97]
If we set a window to be centered before it is shown it does not work correctly.
The content top left appears centered. My guess is that we have a 0, 0 content before rendering is calculated.

From PR #96

**Comment by paulhovey** [comment]
I put some debug statements in (haven't figured out how to step through go code yet, kinda surprisingly) and got this:

```before SetContent()
before w.CenterOnScreen()
before w.Show()
monX, monY =  0 0
viewWidth, viewHeight =  254 152
newX, newY =  833 464
in moved(); w.xpos, w.ypos =  833 464
in moved(); w.xpos, w.ypos =  0 25
in moved(); w.xpos, w.ypos =  4 25```

However, changing the end of the function to include a `Show()` make it work more reliably:

`// set new window coordinates
w.viewport.Show()
w.viewport.SetPos(newX, newY)`

It seems as though the coordinates are sometimes getting set to a new offset in Show(), but I couldn't find where the coordinates were coming from in the code.  I assume glfw somewhere?  Is calling `Show()` from `CenterOnScreen()` an acceptable fix?

**Comment by paulhovey** [comment]
I'm having problems running my dumb test app - it just has two windows and I'm modifying the content and trying to recenter.  The app crashes half the time, making debugging even more frustrating :sweat_smile: 

In any case, can you see if the changes I made [on branch exposeSetPos](https://github.com/fyne-io/fyne/compare/develop...paulhovey:exposeSetPos) work well for you?  I removed most of CenterOnScreen() from running on the main thread, and factored in the window content scaling, which seems to work for me on my setup.  If they look good, I can create a PR, but I wasn't confident enough in them to create one yet!

**Comment by andydotxyz** [comment]
That looks better, but I am not sure about Max - it hides the fact that one will be 0 and the other not...
Does it work just as well as if winWidth == 0 { useCanvasWidth * scale } ?
I think that would be easier to read

Also if you are going to expose "SetPos" then to match the Resize method, and other interfaces in Fyne, it should surely be "Move" - I was about to suggest a fyne.Position parameter but that would probably be wrong (as this is screen coordinates, and so the difference should be clear).
But should we expose it?

**Comment by paulhovey** [comment]
I think `Max()` is better, because if the initial window created has a width of 10 or some minimum, then the if-statement may not pick up on it.  I can add an extra comment for clarity.

Exposing or hiding a method is your call, chief!  In my eyes, it seems reasonable to give the programmer access to moving a window around, if they want to lock it to a corner of the screen or split screen or something like that.  Any reason it should be hidden?

**Comment by andydotxyz** [comment]
OK, that is a good argument for Max. Perhaps some comment or clearer naming will help with that approach.

If we expose the method of moving a window then really we also need to expose the method of screen dimensions, offsets I think - so the developer knows what space is available. I think we should keep it private until a real user-case at which point we can do it completely.

As always keep it private until we know the real need of a user to access the API :)
