### ISSUE TITLE
android: pressing enter in multiline entry hides keyboard

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#971]
### Describe the bug:
Pressing enter on the virtual keyboard when typing in entry hides it. It should hide keyboard only when MultiLine is false.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open Fyne demo
2. Open Form tab in Widgets tab
3. Type something in Message, press enter
4. Keyboard is hidden, but focus is still on entry

### Device (please complete the following information):
 - OS: Android
 - Version: 8.0
 - Go version: 1.14.2
 - Fyne version: develop 04d654b06855c53d2a7c18caafbcca2161baff73

**Comment by andydotxyz** [comment]
What is the label on the keyboard button you are tapping?

**Comment by pymq** [comment]
Ah I see. It's "OK" instead of "Enter" icon. From #972 [video](https://imgur.com/a/SZzkddz) you can see the Samsung keyboard example. I just tried with another keyboard - it's the same: there is no "Enter" button, line breaks on pressing to "OK" and keyboard hides. And now we coming to question about supporting different types of keyboard - only digits, multiline etc

**Comment by andydotxyz** [comment]
multiple keyboards will be a later addition as we need to add support to the toolkit for that.
Your description is logical, and we have a decision to make.
At this time we don't have support for different types of keyboard so we need to pick either the newline capable one (that would fix this issue) for all entries, or leave it as it is.
I suspect that moving to an "enter" button is the right thing to do and will resolve this issue. It will also bring more modern phones in line with the older ones that don't support the same configuration of "action" button.

**Comment by andydotxyz** [comment]
Fixed for testing on develop

**Comment by pymq** [comment]
Cool, thanks!

It would be also great to hide keyboard on enter if it's !MultiLine entry.
I can send a CL if it helps.

**Comment by andydotxyz** [comment]
Unfortunately the keyboard currently does not know about the details of the entry. That’s where the bigger fix comes in.
But if you can find a way to do it sooner that would be a bonus

**Comment by pymq** [comment]
I think it could be done simply in https://github.com/fyne-io/fyne/blob/develop/widget/entry.go#L400
by something like
```go
if device, ok := fyne.CurrentDevice().(mobile.Device); ok {
	device.HideVirtualKeyboard()
}
```
Focus will still be at entry, but at least keyboard will hide.

**Comment by andydotxyz** [comment]
That's a clever workaround. Not entirely certain if we should but I will look into it :)
(hesitance is because keyboard handling is in the driver currently...)

**Comment by andydotxyz** [comment]
Let's come back top this if your #975 does not resolve the issue
