### ISSUE TITLE
android: typing in entry expand it only after full refresh

### ISSUE THREAD

**Issue by pymq** [fyne-io/fyne#972]
### Describe the bug:
Typing in entry doesn't expand it. Also strange layout bug after submitting the form, see video.

### To Reproduce:
Steps to reproduce the behaviour:
1. Open Fyne demo
2. Open Form tab in Widgets tab
3. Type many lines in Message, see text is not visible
4. Revisit tab, entry expanded

[video](https://imgur.com/a/SZzkddz)

### Device (please complete the following information):
 - OS: Android
 - Version: 8.0
 - Go version: 1.14.2
 - Fyne version: develop 04d654b06855c53d2a7c18caafbcca2161baff73

**Comment by andydotxyz** [comment]
Fix is on develop for testing
