### ISSUE TITLE
Android emulator app crashes on repeated attempts to run.

### ISSUE THREAD

**Issue by mrjrieke** [fyne-io/fyne#977]
### Describe the bug:
Re-opening demo app in android emulator causes failures after the 1st try without recovering. 
 I usually end up with a black screen every time after the first try.  I imagine this is probably limited to the emulator, but not entirely certain.

Workaround: uninstall/reinstall

### To Reproduce:
Steps to reproduce the behaviour:
1. Install android emulator x86 version 23  or x86_64 version 28
2. Deploying "Hello world" demo application -- changing the text to a very long line of text.
3. Click on the "Hello world" application icon.
4. Click the "Home" key to escape out of the app.
5. Click on the "Hello world" application icon again.
5. From hence forth you will see: "Draw context is NULL" in x86.  In Android 28,
05-11 22:28:28.037  4605  4629 E EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
05-11 22:28:28.037  4605  4629 E EGL_emulation: tid 4629: swapBuffers(537): error 0x300d (EGL_BAD_SURFACE)
05-11 22:28:28.037  4605  4629 I GoLog   : app: failed to swap buffers (EGL_BAD_SURFACE)

### Example code:
Demo app. "hello"

### Device (please complete the following information):
 - OS: Linux
 - Version: 3.16.0-9-amd64 #1 SMP Debian 3.16.68-2 (2019-06-17) x86_64 GNU/Linux
 - Go version: 1.12.5
 - Fyne version: 0b492d882b0227fd80c10dcf2237942ae5aadaa6

**Comment by mrjrieke** [comment]
glxinfo:
OpenGL version string: 3.0 Mesa 10.3.2

**Comment by andydotxyz** [comment]
Thanks for the report.
You mention in step 2 you modified text. Is this related, or do you see the same issue with an un-modified application?

**Comment by mrjrieke** [comment]
Initially, yes, but then I thought..  maybe this isn't to do with the text change.  I then tested with the original and found the same behaviour.

Incidentally, I did come across a fix you made for ios during the restore event and glx back in 2019.  Could it be android is wanting a similar fix?

**Comment by andydotxyz** [comment]
It shouldn't be the same as this issue is not present on the device - just the emulator.
That is, I cannot replicate it - perhaps you could test on device and let us know?

**Comment by mrjrieke** [comment]
I just managed to do some more testing.  Deploying to real android device seems to not display the above problem.  So, I guess it's something to do with my emulator.  I hate to say it, but this is probably one of those lesser priority bugs.

Something else I've noticed with this app running on my emulator: the exit button doesn't seem to work in the emulator (not sure if those two problems could be related).  However buttons from the demo app seem to function just fine in the emulator.

**Comment by andydotxyz** [comment]
Yes quit is a no-op on mobile driver because of the lifecycle imposed by the OS.
We need a better hello world app with that in mind :)

**Comment by andydotxyz** [comment]
I can no longer replicate this with the upcoming v2.0.0 release on `develop` branch.
Can you test this again after we release v2.0.0 at the end of the week please?

**Comment by mrjrieke** [comment]
Sorry Andy, I haven't had time to try to set this up and reproduce/verify this.  I imagine this is fine now.  I'll re-open it later if I still see problems.
