### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by rajkumarks7** [fyne-io/fyne#978]
can you please write a example for login screen less number of examples.

**Comment by andydotxyz** [comment]
Can you be more specific please? What do you expect that it should show that the fyne_demo -> widget -> form code does not cover?

**Comment by rajkumarks7** [comment]
Like a login screen

**Comment by rajkumarks7** [comment]
It should take username, password and should has a submit button to submit the data for authentication .

**Comment by andydotxyz** [comment]
Have you looked at the form example in fyne_demo? https://github.com/fyne-io/fyne/blob/master/cmd/fyne_demo/screens/widget.go#L72

**Comment by rajkumarks7** [comment]
it is not showing any screen. can you give a simple example of login screen which can take username and password.

**Comment by andydotxyz** [comment]
Perhaps you can expand on what "now showing any screen" means?
Is it the case that you want help building a dialog that contains a login screen? 
If you could point to something specific that you are trying to build that might be helpful.
Typically our examples show how to use the API rather than how to build applications, but there may be something we can do.

**Comment by rajkumarks7** [comment]
yes sir ,i am building a app which uses your library which shows the dialog login screen which takes the input username and password once you submit it will leave the page.it is used for authenicate.

**Comment by Jacalz** [comment]
Are you trying to make a login screen that changes the view to something else when pressing submit? Are you looking to just have a dialog or the window for login?

**Comment by rajkumarks7** [comment]
just for login authenication

**Comment by Jacalz** [comment]
Does the #989 change solve your use-case? It shows how a login dialog could be implemented.

**Comment by rajkumarks7** [comment]
i am creating a login screen that will take input and authenicate then once login credentials are correct then it will take you to another screen

**Comment by rajkumarks7** [comment]
yes sir

**Comment by andydotxyz** [comment]
Closed by #989
