### ISSUE TITLE
Label does not refresh

### ISSUE THREAD

**Issue by dartmann** [fyne-io/fyne#98]
Hi, first of all I am new to Go and this framework so please have mercy when I got things wrong in the first place. My Issues are as follows:

- I added a nice little GUI (window with label and button) to my Go app. When I update the label by pressing the button and calling `setText` method of label it wount work. I worked around by calling `w.Canvas().Refresh(w.Content())` of window. Is this expected behavior?

- Moreover, I can not align the text of my label centered by setting `l.Alignment = fyne.TextAlignCenter`. But this works if I instantiate the label via `NewLabelWithStyle` instead of `NewLabel` and pass the alignment option as an argument.

Thanks for your help and comment. And thanks for this easy to use GUI framework! 😄

PS: I am building on a Win 10 (1803) machine.

**Comment by andydotxyz** [comment]
I'm sorry to hear you are having problems with Fyne - don't apologise for being a beginner as we want to make this easy for everyone :)

In both of your points it's new bugs! (oops)
We recently refactored the text handling for label and entry and along the way have broken some property setting.
I can see why the label issue is there but the SetText is stranger. We will try and fix these today!

Apologies

**Comment by andydotxyz** [comment]
There is a potential fix created and being discussed - hopefully it can be landed tomorrow

**Comment by andydotxyz** [comment]
These are both now fixed - your code should work as expected
