### ISSUE TITLE
How to prevent NewEntry from stretching/resizing?

### ISSUE THREAD

**Issue by rootVIII** [fyne-io/fyne#984]
If my input text exceeds the length of a `NewEntry()` widget in the UI, the whole application starts to stretch horizontally as the `NewEntry() `widget expands. Is it possible to prevent this, so that the `NewEntry()` doesn't change size horizontally?

**Comment by andydotxyz** [comment]
For now you can put it inside a ScrollContainer.
There is a better solution being lined up for a later release.
We are tracking that in #471

**Comment by rootVIII** [comment]
Wow that was fast! Thanks will look at that and close this. Thanks...
