### ISSUE TITLE
Android app INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME

### ISSUE THREAD

**Issue by Virgil-N** [fyne-io/fyne#985]
### Describe the bug:
Can't install Android app.

### To Reproduce:
I use command below to generate app:
fyne package -os android -appID test -icon resource/img/icon/appIcon.jpg

When I input "adb install fyne_app.apk", my terminal prints:
adb: failed to install fyne_app.apk: Failure [INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME: Invalid manifest package: must have at least one '.' separator]

How can I solve this problem?
Thanks!

### Device (please complete the following information):
 - OS: win10
 - Version: last
 - Go version: go1.14.2 windows/amd64
 - Fyne version: 1.2.4

**Comment by Virgil-N** [comment]
I found it's a mistake.
I replaced command with "fyne package -os android -appID xxx.com.test -icon resource/img/icon/appIcon.jpg", and it works.

**Comment by andydotxyz** [comment]
Thanks for this. We should probably put some validation into the fyne command so this is avoided.
