### ISSUE TITLE
Adding a hidden object to FixedGridLayout creates a blank.

### ISSUE THREAD

**Issue by mondy** [fyne-io/fyne#996]
### Describe the bug:
Adding a hidden widget to FixedGridLayout creates a blank.
Does FixedGridLayout support hidden widgets?
Is there a problem with the way I use it?
I think you should be able to have blanks every three, or no blanks at all.
For me personally, I'd prefer to be no blanks at all.

### To Reproduce:
1. Execute the following code
1. It creates an unnatural blank, as in the screenshot.

### Screenshots:
![ss](https://user-images.githubusercontent.com/3961824/82140067-02402380-9868-11ea-9130-8b3719dced24.jpg)

### Example code:

```go
package main

import (
	"strconv"

	"fyne.io/fyne"
	"fyne.io/fyne/app"
	"fyne.io/fyne/layout"
	"fyne.io/fyne/widget"
)

func main() {
	length := 100
	application := app.New()
	window := application.NewWindow("")
	grid := fyne.NewContainerWithLayout(layout.NewFixedGridLayout(fyne.NewSize(200, 200)))
	grid.Objects = make([]fyne.CanvasObject, 0, length)
	for i := 0; i < length; i++ {
		label := widget.NewLabel(strconv.Itoa(i))
		label.Hidden = i%3 == 0
		grid.Objects = append(grid.Objects, label)
	}
	window.SetContent(widget.NewScrollContainer(grid))
	window.ShowAndRun()
}

```

### Device (please complete the following information):
 - OS: Ubuntu 18.04
 - Go version: go version go1.14.2 linux/amd64
 - Fyne version: v1.2.4

**Comment by andydotxyz** [comment]
On develop for testing
